### ISSUE TITLE
Use post data from the mysql database rather than ElasticSearch's index

### ISSUE THREAD

**Issue by archon810** [10up/ElasticPress#1000]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Bug and feature request

Describe the issue you encountered:
I'm using Advanced Excerpt (https://wordpress.org/plugins/advanced-excerpt/), and with ElasticPress, the nicely formatted posts (including embeds, images, etc) turns into text-only content that I presume is coming from ElasticPress's index.

How can we make it so that the post data is always loaded from the db, or that Advanced Excerpt plays nicely with ElasticPress?

Current WordPress version:
4.9.2

Current ElasticPress version:
2.4

Current Elasticsearch version:
5.6.6

Where do you host your Elasticsearch server:
Self

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Advanced Excerpt https://wordpress.org/plugins/advanced-excerpt/

**Comment by archon810** [comment]
Seemingly related: https://github.com/10up/ElasticPress/issues/345.

**Comment by JACK-ARRAY** [comment]
ElasticPress pulls only post id from Elasticsearch, rest data pulled from MySQL. I am using it from last one year. Can you post your code here? So we can help you.

**Comment by archon810** [comment]
Oh, interesting. I'll try to figure out what's happening by the process of experimentation and elimination.

In the meantime, here is a pair of screenshots, which shows the issue. Our logic pulls out the first image in every post and makes it a thumbnail. With EP on, no image shows up, so all thumbs end up the default logo.

Furthermore, as you can see, pretty much all non-text related features are gone and even paragraphs are all merged into one.

![image](https://user-images.githubusercontent.com/469543/35234281-6b7037d6-ff55-11e7-8113-c40bbd659208.png)

![image](https://user-images.githubusercontent.com/469543/35234310-8a5e8bb6-ff55-11e7-87ac-32a6dd1291c5.png)

**Comment by ScreamingDev** [comment]
Hint on this issue (one way to do it but no proper solution): 

- ElasticSearch returns the IDs
- The filter "ep_retrieve_the_post" can use `get_posts` to retrieve the actual posts via SQL.

Problem then again is: get_posts instantiates all data which is the slowest part of get_posts. So the advantages in speed are gone.

**Comment by archon810** [comment]
@ScreamingDev I'll be OK with that. For us, the slowest is by far the search itself.

An alternative is to store the full untouched content of the post with the index. Can that be happening, perhaps with a flag in the settings? I can't be the first person to point out that this is an issue - does nobody else have a problem with the data coming back all run-on and stripped like that?

**Comment by tlovett1** [comment]
ElasticPress DOES pull all post data from ES. You could change that here - https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L249

**Comment by ScreamingDev** [comment]
@tlovett1 sorry but could you verify some more thoughts on that please. Just to be clear:

- Fetching data from ES does not trigger any usual post action or filter.
- Third party plugins relying on that are doomed.
- Using the filter we both mentioned and `get_posts` with a set of IDs would bring that support back.
- Using `get_posts` also slows down everything again because it is the same collection of posts and the same process as before.

Is that correct?
