### ISSUE TITLE
Configuration for Elastic admin?

### ISSUE THREAD

**Issue by NetwarSystem** [10up/ElasticPress#1001]
Hello,

I am trying to configure Elasticpress for first time and this is extremely confusing.

All that is offered is "enter your elasticsearch URL".

I have systems running Wazuh, Timesketch, some of my own code. I am pretty familiar with Elasticsearch, have a cluster of four 6.1.2 machines, some of the standalone stuff is still on 5.6.6, I've started writing Python for direct access.

What I expected was to provide Elasticpress an IP and a port - 127.0.0.1 and 9200 in my case.

I have tried various permutations of the IP, localhost, including or not having :9200 at the end of URL.

I dig git clone and started digging into the code, I could find no obvious IP address/port config file.

So I thought I would ask here. Sorry for potato post in the midst of important stuff, but after :30 of digging and not finding it, I'm sure I missed something simple.

**Comment by eugene-manuilov** [comment]
Hey @NetwarSystem,

I am not sure what exactly happens on your end, but `http://localhost:9200/` should be sufficient. Can you post a result of `curl http://localhost:9200/` command? Do you see Elasticsearch response?

**Comment by NetwarSystem** [comment]
OK, there was no information on what to do in terms of format. I will give this a try. Thanks.
