### ISSUE TITLE
Initial Sync incredibly slow.

### ISSUE THREAD

**Issue by fcbits** [10up/ElasticPress#1002]
Describe the issue you encountered.  Sync is very slow now with my data set.  IT will take about 20 days currently.  Is there a way to remove the SQL_CALC_FOUND_ROWS.  This part of the query being issued is very slow on a larger data set and I think that is the bulk of the problem.  Not sure if this can be controlled via elasticpress code.

SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_type IN ('post', 'page', 'attachment', 'thirstylink', 'content_ad_widget') AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.ID DESC LIMIT 39200, 350

Current WordPress version:  4.8.2
Current ElasticPress version: latest
Current Elasticsearch version:  5.6

**Comment by JACK-ARRAY** [comment]
350 posts/second is not slow, i have 40000 posts and time taken to sync is around 3 minutes.

**Comment by eugene-manuilov** [comment]
Hi @fcbits,

do you sync using WP_CLI command or via admin dashboard? If you use WP_CLI, then you can set `posts-per-page` param to increase posts per page number what can help you to increase indexing speed. If via admin dashboard, then there is `ep_index_posts_per_page` filter to update posts per page parameter.

Unfortunately, we can't remove SQL_CALC_FOUND_ROWS because we need to know how many posts we need to index.

**Comment by tlovett1** [comment]
How large is the dataset?

**Comment by fcbits** [comment]
Thanks @eugene-manuilov @tlovett1 - The dataset now is about 9 million rows and growing.  I initially used the admin dashboard but that was timing out because it wasn't responding I think in 30 seconds.  So then I went to WP_CLI which was much better but when I did the math it just was going to be a 20+ day process at the rate it was going.  I guess its possible I could ramp it up then from 350 to a higher number but I recall reading somewhere that the upper bound is limited and you don't want to push that many documents to elasticsearch at once.  Do you know what the highest upper limit of posts-per-page I could set?  Most of my posts are not that lengthy.

**Comment by fcbits** [comment]
Also, partially related to this I tried using larger --posts-per-page=10000 setting.
(I'm not sure how high this can go).  It seems in the middle of this it hits some mysqli_query error.  I'm not sure what would cause that.

Processed 120000/4531157 entries. . .
PHP Warning:  mysqli_query(): MySQL server has gone away in /var/www/html/wp-includes/wp-db.php on line 1924
Warning: mysqli_query(): MySQL server has gone away in /var/www/html/wp-includes/wp-db.php on line 1924
PHP Warning:  mysqli_query(): Error reading result set's header in /var/www/html/wp-includes/wp-db.php on line 1924
Warning: mysqli_query(): Error reading result set's header in /var/www/html/wp-includes/wp-db.php on line 1924
Request string length: 13.55 MB
Processed 130000/4531157 entries. . .
