### ISSUE TITLE
Why am I getting the terms empty for my custom post types?

### ISSUE THREAD

**Issue by diwakhat1603** [10up/ElasticPress#1003]
Why am I getting the terms empty for my custom post types? Looks like these terms (tags and categories) not getting indexed when the plugin is network activated in a multi-site wordpress set-up

**Comment by eugene-manuilov** [comment]
Hi @diwakhat1603,

it is hard to understand what happens on your end. Could you please give us more information about your setup and what you are trying to do?

**Comment by nprasath002** [comment]
Closing this issue due to in activity. Please feel free to reopen this
