### ISSUE TITLE
Search multisite

### ISSUE THREAD

**Issue by davidkinnberg** [10up/ElasticPress#1010]
As a total noob at Elasticsearch I'm hoping to get some help on this.

**Background**
We're running Wordpress Multisite with 4 sites. ElasticPress is installed as a network plugin.
Elastic search has indexed all 4 sites accoring to the ElasticPress plugin.
Searching on any of these 4 sites works fine using Elastic search.

**Question**
Is it possible to search all 4 sites at one time from any of these 4 sites?
If so, how do I do it?

**Environment**
Wordpress 4.9.2 Multisite
Elasticpress 2.4 (network installed)
Elasticsearch  (hosted, not installed by me)

Thanks in advance!

**Comment by nprasath002** [comment]
Hi David,

You can filter the search scope with filter `ep_search_scope`. The search scope. Accepts `all` (string), a single site id (int or string), or an array of site ids (array). Let me know if you need more info

**Comment by tlovett1** [comment]
You can just pass `sites => "all"` to your WP_Query
