### ISSUE TITLE
toc plugin and sync elastic

### ISSUE THREAD

**Issue by Eventusrus** [10up/ElasticPress#1012]
function action_queue_meta_sync at first build post args (prepare_post()) and later check what is meta field name and if meta is hidden return nothing. 
That strange and also, this situation bad for performance.

Maybe best way: first check meta_key and after load post_args?

Current WordPress version: 4.9.1
Current ElasticPress version: 2.4

**Comment by nprasath002** [comment]
I am not sure i understand what you are suggesting? Can you submit a PR or code snippet that displays the change?
