### ISSUE TITLE
There is a problem with connecting to your Elasticsearch host. How To Solve This issue.

### ISSUE THREAD

**Issue by sarun007** [10up/ElasticPress#1013]
Hello
I have been using ElasticPress and Elastic Search for several months now without issue, however I logged into WPAdmin this morning and saw this message:

"There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again, or you may need to change your settings."

Current WordPress version: 4.9.2

Current ElasticPress version: 2.4

Where do you host your Elasticsearch server: https://1e6b5a4d4e222b95a6b4d34f2e594dbb.us-central1.gcp.cloud.es.io:9243/

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): ManageWP - Worker: by ManageWP – 4.3.3
Async JavaScript: by Clough I.T. Solutions – 2.17.11.15
Autoptimize: by Frank Goossens (futtta) – 2.3.2
Better Search Replace: by Delicious Brains – 1.3.2
Contact Form 7: by Takayuki Miyoshi – 4.9.2
Debug Bar ElasticPress: by 10up – 1.3
Debug Bar: by wordpressdotorg – 0.9
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
ElasticPress: by Taylor Lovett
Matt Gross
Aaron Holbrook
10up – 2.4

Envato WordPress Toolkit: by Envato – 1.7.3
Ninja Forms: by The WP Ninjas – 3.2.10
Popup Maker: by WP Popup Maker – 1.6.6
Real-Time Find and Replace: by Marios Alexandrou – 3.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.1
Relevanssi: by Mikko Saari – 4.0.3
Ultimate Member: by Ultimate Member – 1.3.88
WC Fields Factory: by Saravana Kumar K – 2.0.5 – Not tested with the active version of WooCommerce
WC Speed Drain Repair: by WP Fix It – 1.2 – Not tested with the active version of WooCommerce
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.4
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.1.0
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.0
WooCommerce Measurement Price Calculator: by SkyVerge – 3.13.0
WooCommerce PDF & Print: by gVectors Team – 1.5.0 – Not tested with the active version of WooCommerce
WooCommerce Pretty Emails: by MB Création – 1.8.6 – Not tested with the active version of WooCommerce
WooCommerce Product Finder: by WooCommerce – 1.2.4
WooCommerce: by Automattic – 3.2.6
WooSidebars: by WooThemes – 1.4.3
WP Smush: by WPMU DEV – 2.7.6
WPMU DEV Dashboard: by WPMU DEV – 4.4
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.4.6
YITH WooCommerce Wishlist: by YITHEMES – 2.2.0

**Comment by nprasath002** [comment]
Hi Sarun,

Can you check your your wp-config and make sure ElasticPress is configured in the following format?

define( 'EP_INDEX_PREFIX', 'PREFIX-' );
define( 'ES_SHIELD', 'xxx:PPPPPP' );
define( 'EP_HOST', 'https://xxx.yyy' );

**Comment by nprasath002** [comment]
Hope this is resolved. Closing this
