### ISSUE TITLE
After update to version 2.4.1 .The related post don't work anymore.

### ISSUE THREAD

**Issue by nqzhang** [10up/ElasticPress#1014]
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?

Describe the issue you encountered:

Current WordPress version:

Current ElasticPress version:

Current Elasticsearch version:

Where do you host your Elasticsearch server:

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by eugene-manuilov** [comment]
Hi @nqzhang,

by "related posts" you mean "ElasticPress - Related Posts" widget, don't you?

**Comment by nqzhang** [comment]
@eugene-manuilov yes . After update ,the related post  widget show nothing.When i downgrade the plugin to 2.3.2. It worked again.

**Comment by tlovett1** [comment]
Fixed in 2.4.2
