### ISSUE TITLE
Is this the correct way to add a field to index in woocommerce

### ISSUE THREAD

**Issue by otherjohn** [10up/ElasticPress#1015]
Hi all,
We use a plugin that creates a new order ID with the prefix "w" on it, and we need to search for orders like w12345 in the admin.
It appears that the following code placed in the theme functions file should do this for us:

    function shop_order_search_fields_add_formatted_order_id( $search_fields ) {
    	$search_fields[] = '_order_number_formatted';
    	return $search_fields;
    }
    add_filter( 'shop_order_search_fields', 'shop_order_search_fields_add_formatted_order_id', 9999);

Is this correct? Do I reindex afterward?

**Comment by nprasath002** [comment]
I think that should work.

**Comment by tlovett1** [comment]
Please reopen if this didn't work. Thanks!
