### ISSUE TITLE
class-ep-api.php Authorization in format_request_headers

### ISSUE THREAD

**Issue by ZeroX66** [10up/ElasticPress#1017]
Hi there,

I have some issues here with this if

		if ( defined( 'ES_SHIELD' ) && ES_SHIELD ) {
			$headers['Authorization'] = 'Basic ' . base64_encode( ES_SHIELD );
		}

I set defined('ES_SHIELD', 'login:pass'); in wp-config but it seems to have the value 1 here and ES_SHIELD have the login/pass so the criteria will not be true here and then not plugin login correct to ES.

/Thanks

**Comment by nprasath002** [comment]
Not sure how the defined ES_SHIELD is changed to 1. Can you check your source code to see there is no other hooks/code thats changing the value of ES_SHIELD?

**Comment by nprasath002** [comment]
Hope this is resolved. Closing this out. Feel free to reopen if you still having any issues
