### ISSUE TITLE
how would you exclude results for Woocommerce Catalog visibility = hidden or shop only?

### ISSUE THREAD

**Issue by otherjohn** [10up/ElasticPress#1018]
Question:
In woocommerce you have the "Catalog visibility" which can be "Shop and search results","Shop only","Search results only", and "hidden".   We use this ability to hide products that are added to a users cart for free when they purchase a qualifying item.  

We need to exclude items that are set to hidden or shop only since both of those do not show up in a regular WordPress search.

I have done something like [#253](https://github.com/10up/ElasticPress/issues/253#issuecomment-98881570) and have re-indexed afterward with no luck.  The items toggled to be excluded keep showing up.

Here is my code:

    /**
     * Filters WP_Query arguments for initial ElasticPress indexing.
     * Searches for posts with 'do_not_index' and adds those post IDs to 'posts__not_in' argument.
     * @param array $args
     * @return array
     */
    function my_ep_filter( $args ) {
    /// "elasticsearch_index" is a checkbox that you check to exclude. So a a value of 1 = do not show in search.
    	$query   = new WP_Query( array( 'meta_key' => 'elasticsearch_index', 'meta_value' => '1', 'fields' => 'ids' ) );
    	$exclude = array();
    	if ( 0 < $query->post_count ) {
    		$args[ 'post__not_in' ] = $query->posts;
    	}
    	return $args;
    }
    
    add_filter( 'ep_index_posts_args', 'my_ep_filter' );
    
    /**
     * Filter to determine if a post should not be indexed.
     * @param bool $return_val Default is false.
     * @param array $post_args
     * @param int $post_id
     * @return boolean
     */
    function my_ep_stop_sync( $return_val, $post_args, $post_id ) {
        /// "elasticsearch_index" is a checkbox that you check to exclude. So a a value of 1 = do not show in search.
    	$to_index    = get_post_meta( $post_id, 'elasticsearch_index', true );
       	$to_index    = filter_var( $to_index, FILTER_VALIDATE_BOOLEAN );
    	if ( false === boolval( $to_index ) ) {
    		return false;
    	}
    	/**
    	 * OPTIONAL: Delete the post from the index...
    	 */
    	if ( function_exists( 'ep_delete_post' ) ) {
    		ep_delete_post( $post_id );
    	}
    
    	return true;
    }
    add_filter( 'ep_post_sync_kill', 'my_ep_stop_sync', 10, 3 );

**Comment by otherjohn** [comment]
I have updated my code to include woo 3.+ product_visibility and I am still seeing results that I shouldn't.  I tested my query in mysql to make sure it is pulling the correct post IDs to exclude.

    function my_ep_filter( $args ) {
    	global $wpdb;
    
    	$query   = "
    				SELECT DISTINCT $wpdb->posts.ID FROM $wpdb->posts 
    				INNER JOIN $wpdb->postmeta ON ($wpdb->postmeta.post_id = $wpdb->posts.ID AND $wpdb->postmeta.meta_key='elasticsearch_index')
    				INNER JOIN $wpdb->term_relationships ON( $wpdb->posts.ID = $wpdb->term_relationships.object_id )
    				INNER JOIN $wpdb->term_taxonomy ON( $wpdb->term_relationships.term_taxonomy_id = $wpdb->term_taxonomy.term_taxonomy_id )
    				INNER JOIN $wpdb->terms ON( $wpdb->term_taxonomy.term_id = $wpdb->terms.term_id )
    				WHERE  ( $wpdb->term_taxonomy.taxonomy = 'product_visibility' AND $wpdb->terms.slug = 'exclude-from-search' ) 
    				OR $wpdb->postmeta.meta_value = '1' ";
        $posts_to_be_excluded = $wpdb->get_results($query);
    
    
    	if ( 0 < $wpdb->num_rows ) {
    		$args[ 'post__not_in' ] = $posts_to_be_excluded;
    	}
    	return $args;
    }
    add_filter( 'ep_index_posts_args', 'my_ep_filter' );

**Comment by nprasath002** [comment]
Hi @otherjohn ,

> I have updated my code to include woo 3.+ product_visibility and I am still seeing results that I shouldn't

Can you provide use with the new code?

**Comment by nprasath002** [comment]
Hope this is resolved
