### ISSUE TITLE
Posts failed to index: class_cast_exception

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1019]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Bug.

Describe the issue you encountered:

Most posts fail to index with the error "class_cast_exception".

Current WordPress version:

4.9.2

Current ElasticPress version:

2.4.2

Current Elasticsearch version:

5.5.0

Where do you host your Elasticsearch server:

Self-hosted.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce.

Steps to reproduce:

1. wp elasticpress index --setup --show-bulk-errors --url=http://www.mysite.com

Console output:

```
- 17: Product A
type: class_cast_exception
reason: 

- 16: Product B
type: class_cast_exception
reason: 

- 15: Product C
type: class_cast_exception
reason: 
```

Logs:

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long

WARN  [elasticsearch[192.168.1.2][clusterService#updateTask][T#1]] ClusterService.java:1255 updateTableSchema Ignoring enabled object with no sub-fields

DeprecationLogger.java:290 deprecated Deprecated field [include] used, expected [includes] instead
ERROR [elasticsearch[192.168.1.2][bulk][T#2]] ClusterService.java:2418 upsertDocument [java.lang.ClassCastException].[shard-1] failed to parse field post=post_modified
```

**Comment by nprasath002** [comment]
Hi Ahmed,

I was not able to reproduce this with a local woocommerce install. It would be helpful if you can give an export of your product(s) with real or dummy data that matches real data

**Comment by ahmed-sigmalux** [comment]
I nuked our ElasticSearch setup and reinstalled everything. The errors haven't reappeared so I'll close this ticket.
