### ISSUE TITLE
Usage of `post_filter` for status and type?

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/ElasticPress#1021]
_Have you searched for similar issues before submitting this one?_

Yes.

_Is this a bug, question or feature request?_

Question.

_Describe the issue you encountered:_

Hi there! I have a question about the structuring of queries using ElasticPress. By default, it seems that WP_Query settings for `post_type` and `post_status` are mapped to ES's `post_filter`, and not as a `query`.

As per [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-request-post-filter.html), `post_filter` happens after aggregations have already been performed, so any aggregation will have posts of any status or type, and the search may be slightly slower as it's pulling all data and then discarding some results.

My question is to get some clarity regarding the logic behind this?

Thank you!

_Current WordPress version:_ 4.9.4
_Current ElasticPress version:_ 2.4.2
_Current Elasticsearch version:_ 5.6.5
_Where do you host your Elasticsearch server:_ Docker
_Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):_ ElasticPress Debug Bar

_Steps to reproduce:_

1. Perform a search of a custom post type or status.
2. Examine Elasticsearch query in Debug Bear.

Screenshots, if needed: Not needed.

**Comment by tlovett1** [comment]
I don't think there is a good reason behind that. It's probably worth changing although something that is lower priority.
