### ISSUE TITLE
Incompatible with Returns and Warranty Requests (official WooCommerce extension)

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1022]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Bug.

Describe the issue you encountered:

Using the official WooCommerce extension Returns and Warranty Requests shortcodes (see https://docs.woocommerce.com/document/warranty-and-returns/#section-16) crashes WordPress. Debug log shows:

```
PHP Fatal error:  Uncaught Error: Call to undefined function wc_print_notices() in /var/www/wordpress/plugins/woocommerce-warranty/templates/shortcode-return-form.php:4
Stack trace:
#0 /var/www/wordpress/plugins/woocommerce/includes/wc-core-functions.php(211): include()
#1 /var/www/wordpress/plugins/woocommerce-warranty/includes/class-warranty-shortcodes.php(61): wc_get_template('shortcode-retur...', Array, 'warranty', '/var/www/humble...')
#2 /var/www/wordpress/wp-includes/shortcodes.php(319): Warranty_Shortcodes->render_return_form_shortcode('', '', 'warranty_return...')
#3 [internal function]: do_shortcode_tag(Array)
#4 /var/www/wordpress/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(warran...', 'do_shortcode_ta...', '[warranty_retur...')
#5 /var/www/wordpress/wp-includes/class-wp-hook.php(286): do_shortcode('[warranty_retur...')

```

The extension works fine with ElasticPress disabled.

Current WordPress version:

4.9.4

Current ElasticPress version:

2.4.2

Current Elasticsearch version:

5.5.10

Where do you host your Elasticsearch server:

Self-hosted

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce, Returns and Warranty Requests

Steps to reproduce:

1. Install ElasticPress and Returns and Warranty Requests
2. Perform a manual index
3. Create a new page with the shortcode [warranty_return_form] (per the official WooCommerce instructions)
4. WordPress crashes on page save

Screenshots, if needed:

**Comment by nprasath002** [comment]
`wc_print_notices()` is not part of ElasticPress and its revealing a bug in warranty and returns plugin.
