### ISSUE TITLE
404 Not Found when installing plugins after activating ElasticPress

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1023]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Bug.

Describe the issue you encountered:

Using Query Monitor, I see the following errors when installing plugins after I've already activated ElasticPress:

```
GET
https://www.example.com/resources/media/woocommerce-follow-up-emails.zip	404 Not Found	
-
File_Upload_Upgrader->__construct() wp-admin/includes/class-file-upload-upgrader.php:80
wp_insert_attachment() wp-includes/post.php:4912
wp_insert_post() wp-includes/post.php:3449
update_attached_file() wp-includes/post.php:338
update_post_meta() wp-includes/post.php:1804
update_metadata() wp-includes/meta.php:202
add_metadata() wp-includes/meta.php:122
do_action('added_post_meta') wp-includes/plugin.php:453
EP_Sync_Manager->action_queue_meta_sync() extensions/elasticpress/classes/class-ep-sync-manager.php:132
ep_prepare_post() extensions/elasticpress/classes/class-ep-api.php:2647
EP_API->prepare_post() extensions/elasticpress/classes/class-ep-api.php:595
apply_filters('the_content') wp-includes/plugin.php:203
WP_Embed->autoembed() wp-includes/class-wp-embed.php:393
preg_replace_callback() wp-includes/class-wp-embed.php:411
WP_Embed->autoembed_callback() wp-includes/class-wp-embed.php:411
WP_Embed->shortcode() wp-includes/class-wp-embed.php:270
wp_oembed_get() wp-includes/embed.php:98
WP_oEmbed->get_html() wp-includes/class-oembed.php:397
WP_oEmbed->get_data() wp-includes/class-oembed.php:348
WP_oEmbed->get_provider() wp-includes/class-oembed.php:278
WP_oEmbed->discover() wp-includes/class-oembed.php:442
Plugin: elasticpress
```

Current WordPress version:

4.9.4

Current ElasticPress version:

2.4.2

Current Elasticsearch version:

5.5.10

Where do you host your Elasticsearch server:

Self-hosted.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce and Query Monitor

Steps to reproduce:

1. Install and activate ElasticPress
2. Install and activate Query Monitor
3. Install any other plugin via the UI upload
4. Check Query Monitor for HTTP errors

Screenshots, if needed:

**Comment by nprasath002** [comment]
Hi there,

Thanks for the bug report. I was able to reproduce this issue locally. This needs more investigation for a potential solution

**Comment by csloisel** [comment]
I am unable to replicate this locally at the moment on a Docker based setup.

**Comment by tott** [comment]
Hi @ahmed-sigmalux,

I'm having a hard time reproducing your issue as well but noticed the following in your error message "https://www.example.com/resources/media/woocommerce-follow-up-emails.zip	404 Not Found"
Can you explain a bit more in detail how you tried to install this plugin. It would be also helpful to know if you configured your Elasticsearch server and performed an index on your site. Are you using a multi-site or single site setup?

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
