### ISSUE TITLE
How to ElasticPress Incremental Indexing

### ISSUE THREAD

**Issue by xianx** [10up/ElasticPress#1024]
Elasticpress always stats indexing from the begin when ever scan command is given from the plugin panel. How to improve this behavior with incremental indexing?

Because my site has more than 100K publish posts and for indexing it takes more time as it stats indexing from beginning.

**Comment by nprasath002** [comment]
You can use wp-cli to index posts and specify an offset parameter

**Comment by xianx** [comment]
When new post is added do elastic search index them automatically?

**Comment by xianx** [comment]
@nprasath002 Please let me know.

**Comment by nprasath002** [comment]
Yes. When you create a new post ES will index only that post automatically

**Comment by nprasath002** [comment]
Marking this as closed. Please reopen if you have any questions
