### ISSUE TITLE
Securing public endpoint for autosuggest

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1027]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Question.

Describe the issue you encountered:

I want to enable autosuggest and have read the help content and an issue discussing the matter: https://github.com/10up/ElasticPress/issues/955. We will have Nginx as the publicly accessible server proxying to an ElasticSearch cluster.

What restrictions do we need to put in place to secure the public endpoint? At a minimum:

* Restrict to GET
* Limit to location to /mywebsite-1

But then what else? Which tables should we allow for autosuggest to work? Anything else we should lock down?

Current WordPress version:

4.9.4

Current ElasticPress version:

2.4

Current Elasticsearch version:

6.1

Where do you host your Elasticsearch server:

Self

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce

**Comment by nprasath002** [comment]
> Where do you host your Elasticsearch server:
Self

Can you provide the the url of your ES Server so that i can troubleshoot more?

**Comment by ahmed-sigmalux** [comment]
It wouldn't make sense for me to open my ElasticSearch server and publically post the URL before I've correctly secured it no?

**Comment by ahmed-sigmalux** [comment]
I found a sample configuration at https://github.com/10up/ElasticPress-Autosuggest.

I'm still having trouble with autosuggest, however, so I'll open a separate issue.
