### ISSUE TITLE
404 / 500 errors using autosuggest

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1029]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Question.

Describe the issue you encountered:

I activated autosuggest and set the endpoint to es-search. I'm also using the Nginx config at https://github.com/10up/ElasticPress-Autosuggest/.

Autosuggest fails on our website, however, with an error 404:

```
POST https://www.mysite.com/es-search 404 ()
(anonymous) @ VM1223:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
u @ autosuggest.min.js:formatted:65
(anonymous) @ autosuggest.min.js:formatted:146
(anonymous) @ autosuggest.min.js:formatted:25
setTimeout (async)
(anonymous) @ autosuggest.min.js:formatted:24
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```

Current WordPress version:

4.9.4

Current ElasticPress version:

2.4.2

Current Elasticsearch version:

6.1

Where do you host your Elasticsearch server:

Self

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce

Steps to reproduce:

1. Proxy Nginx using the config at https://github.com/10up/ElasticPress-Autosuggest/
2. Enable autosuggest and reindex
3. Try a search in WooCommerce

Screenshots, if needed:

**Comment by tlovett1** [comment]
That plugin is deprecated. I don't the nginx config would work.
