### ISSUE TITLE
wp-options so many records cause site slowdown

### ISSUE THREAD

**Issue by nqzhang** [10up/ElasticPress#1031]
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?

Describe the issue you encountered:

Current WordPress version:

Current ElasticPress version:

Current Elasticsearch version:

Where do you host your Elasticsearch server:

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. wp-optinos has so many records like _transient_ep_related_posts
2. select count(\*) FROM wp_options WHERE option_name like '_transient_ep_related_posts%';
+----------+
| count(*) |
+----------+
|   186417 |
+----------+
1 row in set (0.23 sec)

3.mysql slow log 

SET timestamp=1519330283;
SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes';
\# User@Host: root[root] @  [*.*.*.*]
\# Thread_id: 24442  Schema: *.*.*.*  QC_hit: No
\# Query_time: 2.679889  Lock_time: 0.000017  Rows_sent: 52354  Rows_examined: 642855
\# Rows_affected: 0

Screenshots, if needed:

**Comment by Krullet** [comment]
I'm new to ElasticPress and Elasticsearch, and I dunno if I have a similar issue? My spec are the following:
WordPress version: 4.9.4
ElasticPress version: 2.4.2
Elasticsearch version: 6.2.2
Woocommerce version: 3.3.3

I have a large set of 22 155 products imported to WooCommerce, giving me:
wp_postmeta:	 775 209 rows,	103,9 Mb	
wp_posts:  44 245 rows,	17,5 Mb
wp_term_relationships: 137 110 rows, 8,5 Mb

I though the whole idea of elastic search was to offload the Mysql database, but correct me if I'm wrong? it is still growing a lot in MySQL with my amount of products? As I imported my products, the elasticsearch data dictionary increased in size from a few Mb to 270 Mb, so it is clearly doing something. 

Am i doing something wrong or are these numbers expected?

**Comment by nprasath002** [comment]
Transient `_transient_ep_related_posts` have an expiration of an hour and should be removed after that. Looking at the code i am not sure how the `ep_related_posts` got so large and stale.

I would recommend deleting all the `ep_related_posts` and see if it grows again.

**Comment by nqzhang** [comment]
select count(*) FROM wp_options WHERE option_name like '_transient_ep_related_posts%';
+----------+
| count(*) |
+----------+
|   234136 |
+----------+
1 row in set (0.32 sec)

I think its growing

**Comment by nqzhang** [comment]
My temp solution is add an index on autoload column so the  sql like 
"SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes';
"
will be faster

**Comment by nprasath002** [comment]
Can you try deleting all the *_transient_ep_related_post* and see the results

**Comment by nqzhang** [comment]
i am afraid if it will broke the site related post

**Comment by nprasath002** [comment]
Related posts transients are regenerated when its empty. So it want break the site. We have an hour expiration for transient and it gets deleted. Transient API uses cron job to perform this task. I am suspecting you site's cron is executed
