### ISSUE TITLE
Constant to set autosuggest endpoint?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1033]
Can you add a constant to set the autosuggest endpoint?

**Comment by nprasath002** [comment]
You can set the autosuggest endpoint in settings. Right now you cannot define a constant for that

**Comment by ahmed-sigmalux** [comment]
In case it wasn't clear, I was asking if you can add a constant to set the endpoint.

**Comment by nprasath002** [comment]
No you cannot define a constant for autosuggest.

**Comment by ec-raphael** [comment]
I'm not sure, but I think you're misunderstand @ahmed-sigmalux 

I think he is making a suggestion: it should be possible to define the endpoint as a constant, and the question was more about "is that something you can add soon"?

If not, then I'll make the suggestion. Many other plugins that have a strong developer focus allow settings to be defined either in the dashboard or as constants, this is something ElasticPress seems to lack and would be very useful 😃

**Comment by ahmed-sigmalux** [comment]
Yes, you're understanding is correct, @ec-raphael .

**Comment by ivankristianto** [comment]
@ahmed-sigmalux I re-open the issue.
