### ISSUE TITLE
Had to kill the process, entire server becomes unresponsive.

### ISSUE THREAD

**Issue by Salamander3** [10up/ElasticPress#1034]
I have a horror story.

I followed this tutorial:
https://guides.wp-bullet.com/install-configure-elasticsearch-to-speed-up-wordpress-search/

I installed this on a dedicated server with 3 WP sites (not Woo just WP).

CPU model            : Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
Number of cores      : 8
CPU frequency        : 3892.792 MHz
Total size of Disk   : 1847.9 GB (22.1 GB Used)
Total amount of Mem  : 7816 MB (1219 MB Used)
Total amount of Swap : 8956 MB (71 MB Used)
System uptime        : 16 days, 9 hour 44 min
Load average         : 0.97, 0.67, 0.61
OS                   : Ubuntu 16.04.4 LTS
Arch                 : x86_64 (64 Bit)
Kernel               : 4.4.0-112-generic

So i set it up, the server works all fine and dandy. The query speed was faster than WP as promised.
Server loads avg around 0.40.
This lasted for 5 minutes.

Then i notice, Filezilla not responding...hmm
Then Putty stopped responding...weird.
All 3 sites unresponsive.

By miracle i manage to log via ssh and kill it (with fire).
All back to normal.

Looks like as soon as it started getting hit it couldn't take it. This is a decent server mostly idle brought down to it's knees in 5 mins....something's not right.

Ideas?

**Comment by nprasath002** [comment]
I need more information to troubleshoot this issue. Can you provide me a ElasticPress related error log?

**Comment by Salamander3** [comment]
I'm sorry i removed the plugin. Too dangerous for production.
