### ISSUE TITLE
How does this work with load balanced servers?

### ISSUE THREAD

**Issue by andrewbanchich** [10up/ElasticPress#1038]
Have you searched for similar issues before submitting this one?
Yes.

Is this a bug, question or feature request?
Question.

Where do you host your Elasticsearch server:
AWS.

If we have a load balancer and several servers behind that with WordPress and ElasticPress installed on each, will that cause any issues? I am not sure if it will index all our posts several times (once per server).

**Comment by nprasath002** [comment]
Yes. It will index posts several times but it won't cause any issues. Let us know if you have any questions

**Comment by andrewbanchich** [comment]
Thanks!
