### ISSUE TITLE
Possible bug with Ajax Search for WooCommerce plugin

### ISSUE THREAD

**Issue by bin0k** [10up/ElasticPress#1040]
Possible bug using the Ajax Search for WooCommerce plugin (https://de.wordpress.org/plugins/ajax-search-for-woocommerce/).

When searching for products, categories or any other search term, the Elastic Search function doesn't seem to work. It completely ignores Elastic Press and doesn't optimize the search like expected. The Ajax Search still functions.

Current WordPress version: 4.9.4
Current WooCommerce version: 3.3.3
Current ElasticPress version: 2.4.2
Where do you host your Elasticsearch server: Maxcluster

Steps to reproduce:

    Install WooCommerce, ElasticPress and Ajax Search for WooCommerce plugin
    Activate the Ajax Search
    Search for any search term

I speculate that this is a compatibility problem with the Ajax Search for WooCommerce. Do you have any other suggestion for a search instead of the Ajax Search?

**Comment by tott** [comment]
Hi @bin0k,

I just had a brief look at the plugin you mentioned and it seems that it hooks pretty late (with a priority of 500) on the the filter actions for the query alterations. I think this method interferes with the way ElasticPress works and does not allow it take over this request. You may be able to try reducing the priority of the filters in class-search.php but I am afraid this plugin will need further alterations to make it compatible with ElasticPress as it performs quite some changes to the default queries.

I hope this helps anyway. Please let us know if you had any success.

Best
         Thorsten
