### ISSUE TITLE
Results are not relevant, EP returns too many results

### ISSUE THREAD

**Issue by zkingdesign** [10up/ElasticPress#1042]
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? - Question

Describe the issue you encountered: There's a huge difference between elasticsearch results and what gets returned by WP_Query

Current WordPress version: 4.9.4

Current ElasticPress version: 2.4.2

Current Elasticsearch version: 6.1.0

Where do you host your Elasticsearch server: Testing on local currently

Steps to reproduce:

1. I'm trying to search for a term, but there's a major difference between what gets returned by Elasticpress and Elasticsearch endpoint. Let's say I search for 'expert'.

If I go to the elasticsearch endpoint http://localhost:9200/_search?q=expert I get 137 results, if I run the WP_Query within the site I get 1976 results.

Am I missing something here? 

My query is:
````
$args = array(
			'ep_integrate'   => true,
			'search_fields' => array(
				'post_title',
				'post_content',
				'post_excerpt',
			),
			'post_type' => array('post', 'question', 'answer', 'guides'),
			's' => $search,
			'paged' => $pageNumber,
			'posts_per_page' => 9,
			'post_status' => 'publish',
		);

$query = new WP_Query( $args );

**Comment by tott** [comment]
Are all of post types you're querying set to be indexed in elasticpress ie. are they set to be public. If these posts types are not registered as public post types you would need to inject them through the ep_indexable_post_types filter and perform a reindex.

**Comment by zkingdesign** [comment]
hi @tott 

Yes all those post types are publicly queriable.

**Comment by zkingdesign** [comment]
On the left side you'll see part of the results listed via the WP_Query, on the right you'll see the elasticsearch endpoint and the total number of results http://prntscr.com/ittxwq

**Comment by tlovett1** [comment]
Please install the ElasticPress Debug Bar plugin and show is the actual query that's being sent to ES. Thanks!

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh

**Comment by jeffceriello** [comment]
Hi there, I'm having the same issue unfortunately. I have successfully installed ES and EP.

The WooCommerce website I'm working on has ~17.000 products, all categorised and attributed properly. If I search for "red shoes" I would expect to see a list with shoes (product category) at the top, possibly red (product attribute) and no other product.

At the moment when I perform that search I see all sorts of products in the list (creams, make up, dresses, trousers, etc) and there would be no limit in the number of results unless I set it.

![Screenshot 2020-02-20 at 11 56 57](https://user-images.githubusercontent.com/5859601/74927660-51e19100-53d8-11ea-8347-cd89a5c70a55.png)
![Screenshot 2020-02-20 at 11 57 06](https://user-images.githubusercontent.com/5859601/74927665-54dc8180-53d8-11ea-9728-7a8dd608207d.png)
![Screenshot 2020-02-20 at 11 57 15](https://user-images.githubusercontent.com/5859601/74927666-55751800-53d8-11ea-8820-e28ca046e83b.png)

The query in `search.php` looks like the below (I have tried with a simpler query but it just shows nothing so I thought I had to merge multiple queries)

```
$search_query = get_search_query();

$q1 = get_posts(array(
    'ep_integrate'   => true,
    'post_type' => 'product',
    'posts_per_page' => -1,
    'post_status' => 'publish',
    's' => $search_query
));

$q2 = get_posts(array(
    'ep_integrate'   => true,
    'post_type' => 'product',
    'posts_per_page' => -1,
    'post_status' => 'publish',
    'tax_query' => array(
        array(
            'taxonomy'      => 'pa_designer',
            'terms'         => sanitize_text_field(preg_replace('/%20/', '+', $query[1])),
            'field'         => 'name'
        ),
        array(
            'taxonomy'      => 'pa_colour',
            'terms'         => sanitize_text_field(preg_replace('/%20/', '+', $query[1])),
            'field'         => 'name'
        ),
        array(
            'taxonomy'      => 'pa_fabric',
            'terms'         => sanitize_text_field(preg_replace('/%20/', '+', $query[1])),
            'field'         => 'name'
        ),
        'relation' => 'OR'
    )
));

$q3 = get_posts(array(
    'ep_integrate'   => true,
    'post_type' => 'product',
    'posts_per_page' => -1,
    'post_status' => 'publish',
    'tax_query' => array(
        array(
            'taxonomy'      => 'product_cat',
            'terms'         => sanitize_text_field(preg_replace('/%20/', '+', $query[1])),
            'field'         => 'name'
        )
    )
));

$merged = array_merge( $q1, $q2, $q3 );

$post_ids = array();
foreach( $merged as $item ) {
    $post_ids[] = $item->ID;
}

$unique = array_unique($post_ids);

$the_query = new WP_Query(array(
    'ep_integrate'   => true,
    'post__in' => $unique,
    'posts_per_page' => 50,
    'post_type' =>  'product',
    'post_status' => 'publish'
));
```

The Search Field & Weighting setting in the back end looks like this

![Screenshot 2020-02-20 at 11 36 52](https://user-images.githubusercontent.com/5859601/74927747-80f80280-53d8-11ea-905d-2886121958fc.png)

Ideally the search should return only products and it should look into the product category, product attributes (colour, designer, fabric) and the product title. If I search for `red shoes` or `long sleeves white shirt` I would expect to see the relevant results and only those.

Could I please have some help with this?

**Comment by moejoee91** [comment]
any update on this ?
