### ISSUE TITLE
The Plugin Page does not show a helpful error

### ISSUE THREAD

**Issue by drusellers** [10up/ElasticPress#1047]
Have you searched for similar issues before submitting this one?
- Yes

Is this a bug, question or feature request?
- Feature Request

Describe the issue you encountered:
- The UI of ElasticPress does not show any sort of helpful error

Current WordPress version:
- 4.9.4

Current ElasticPress version:
- 2.4.2

Current Elasticsearch version:
- 5.4.3

Where do you host your Elasticsearch server:
- bonsai.io

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
- woocommerce

Steps to reproduce:

1.  paste in url to elasticsearch
2. hit save changes
3. get bad error

Screenshots, if needed:

![image](https://user-images.githubusercontent.com/63355/37941203-a2644dd6-3132-11e8-804e-535df0c00184.png)

you get the same error for a 429 as you do for a 500. The error would ideally return the error message of the ES server (if it was a 4xx or 5xx) error. If its something about EP, then ideally you would know that and help me walk through fixing it.

**Comment by tlovett1** [comment]
Definitely something we could improve. Thanks for the suggestion!

**Comment by petenelson** [comment]
If you want to assign this to me, I can work on it.

**Comment by brandwaffle** [comment]
@petenelson you got it, good sir!

**Comment by petenelson** [comment]
Pull request for exposing the response code and error message: https://github.com/10up/ElasticPress/pull/1142

**Comment by brandwaffle** [comment]
@allan23 can you review? Thanks!

**Comment by allan23** [comment]
Resolved in #1142
