### ISSUE TITLE
Exclude meta in filter

### ISSUE THREAD

**Issue by Spidlace** [10up/ElasticPress#1048]
**Have you searched for similar issues before submitting this one?** Yes

**Is this a bug, question or feature request?** Question

**Describe the issue you encountered:**
I want to add a weight of 1 for all post meta and for two meta, i add a custom weight (see example)

```php
function sp_set_es_search_args_es($ep_formatted_args, $args = ''){

    // Move the existing query.
    $existing_query  = $ep_formatted_args['query'];
    unset($ep_formatted_args['query']);
    $ep_formatted_args['query']['function_score']['query'] = $existing_query;

    $ep_formatted_args['query']['function_score']['functions'] = array(
        array(
            "filter" => array(
                "match" => array(
                    "post_title" => get_query_var('s'),
                ),
            ),
            "weight" => 2,
        ),
        array(
            "filter" => array(
                "match" => array(
                    "meta.introduction.value" => get_query_var('s'),
                ),
            ),
            "weight" => 1.5,
        ),
        array(
            "filter" => array(
                "match" => array(
                    "_all" => get_query_var('s'),
                ),
            ),
            "weight" => 1,
        ),
    );

    // Specify how the computed scores are combined.
    $ep_formatted_args['query']['function_score']["score_mode"] = "sum";
    $ep_formatted_args['query']['function_score']["boost_mode"] = "replace";

    return $ep_formatted_args;
}
add_filter('ep_formatted_args', 'sp_set_es_search_args_es', 300, 2);
```
But I don't want post_title and meta.introduction.value get the weight 1 (in filter _all).
How can I exclude this post_meta for _all but not for there filter ?

I hope you understand my request

**Current WordPress version:** 4.9

**Current ElasticPress version:** 2.4.2

**Current Elasticsearch version:** 5.6.8

**Where do you host your Elasticsearch server:**  /

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):** /

**Comment by tott** [comment]
Hi,
I'm not 100% certain that I understood your request. I think you would like to ensure the custom weight only for specific matches but not when matching all documents?
Should this be the case you need to inject your weight for the match_all query such as outlined here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-all-query.html

Should this not be what you like to achieve please let us know what the high level outcome is you're trying to achieve.

Thanks

**Comment by Spidlace** [comment]
Hi, 
Thanks for answer me.
This is not exactly what I want..

In my website, i have a lot of custom field.
In my code I give a weight of 2 to the _post title_, 1.5 to one custom meta (_meta.introduction.value_) and for all the rest, I want a weight of 1.

With my code (above), this work, but I don't want "**post_title**" and "**meta.introduction.value**" take the weight of "all the rest".
I try to exclude this fields from _all but I fail

Do you know any method for do this ? 
(Should I put all the name of all fields or can I exclude a few field?)

Let me know if this is more understandable.

Thanks

**Comment by Ritesh-patel** [comment]
Hi @Spidlace 

Did you find solution for this? If not, you may want to look into this reference: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/include-in-all.html which guides how to exclude element from `_all`.

Thanks

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh

**Comment by ashish200025** [comment]
@### 

> [`****`](

- 

@1. url
Duplicate of 
Duplicate of ##

)
