### ISSUE TITLE
Incorrect mapping types

### ISSUE THREAD

**Issue by andrewbanchich** [10up/ElasticPress#1049]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
After the initial sync, I deleted the Elasticsearch index so we could reindex our posts and the mapping is now incorrect for the `post_date` field. It is shown as a text field, so now when I look at the data in Kibana I can't select it as the timestamp.

Current WordPress version:
4.9

Current ElasticPress version:
Latest

Current Elasticsearch version:
6.0.1

Where do you host your Elasticsearch server:
AWS

**Comment by tott** [comment]
Hi @andrewbanchich,
can you advise how you re-indexed your posts and deleted the index? Were you using the wp-cli commands or how specifically did you perform these actions? If you look at the mapping for your index you should see a similar mapping as outlined in https://github.com/10up/ElasticPress/blob/develop/includes/mappings/5-2.php reflected. If this is not the case the system likely tried to determine the mapping automatically and I would advise to run a full re-index through the wp-cli command if possible.

Best
        Thorsten

**Comment by andrewbanchich** [comment]
@tott I deleted the index by doing a `DELETE` request to the entire index pattern, then I used WP-CLI to index the posts again. I didn't use the `--setup` flag though, since I manually cleared it.

**Comment by tlovett1** [comment]
If a field type is incorrect, I'm willing to bet you initial mapping failed.

**Comment by andrewbanchich** [comment]
I'll test it out and see. I didn't think so, though, since I remember I was originally able to select it in Kibana as the timestamp.

Thanks!
