### ISSUE TITLE
Index _wp_page_template meta field

### ISSUE THREAD

**Issue by cbratschi** [10up/ElasticPress#1050]
Have you searched for similar issues before submitting this one?

Yes

Is this a bug, question or feature request?

Question

Describe the issue you encountered:

Hidden meta fields are not indexed. We need a way to store _wp_page_template values in order to query the template used by a page. Is there a way to add hidden fields?

Current WordPress version:

4.9.4

Current ElasticPress version:

2.4.2

Current Elasticsearch version:

6.2.2

Where do you host your Elasticsearch server:

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by csloisel** [comment]
Hi @cbratschi,

You should be able to use the `ep_prepare_meta_allowed_protected_keys` filter to accomplish this. For example:
```php
add_filter( 'ep_prepare_meta_allowed_protected_keys', function( $protected_keys ) {
	$protected_keys[] = '_wp_page_template';
	return $protected_keys;
} );
```

**Comment by cbratschi** [comment]
@csloisel thanks a lot, this is the feature I was looking for. There are so many filters and it is hard to find the correct ones without them being documented ;)
