### ISSUE TITLE
Hidden meta and acf support

### ISSUE THREAD

**Issue by kwiatdiamonds** [10up/ElasticPress#1051]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question and possible feature request

Describe the issue you encountered:

We are seeing elasticpress errors : status 400 on certain pages of our website. It relates to inability to sort on meta fields. After searching extensively I think I’ve learned that hidden fields either don’t get indexed or are not searchable. I’ve seen a few links that confirm the issue but haven’t found code that resolves it. I’m asking the question for help as to how to resolve while also requesting that more seamless support within the plugin become available so that this would work more seamlessly with hidden meta data and acf plugin fields. 

Current WordPress version:
4.9.5

Current ElasticPress version:

2.4.2 elasticpress

Current Elasticsearch version:
2.3.4 elasticsearch

Where do you host your Elasticsearch server:
Pagely

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Woocommerce
Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by tlovett1** [comment]
What does your search query look like?

**Comment by kwiatdiamonds** [comment]
Hi - i replied to the email - but putting here too just in case. 
[query.txt](https://github.com/10up/ElasticPress/files/1884815/query.txt)

**Comment by kwiatdiamonds** [comment]
See attached for Query Args, Query Body and Query Response for an example where we are getting status 400 errors/codes.

**Comment by tlovett1** [comment]
Can you paste the response for when you don't sort by that meta key?

**Comment by kwiatdiamonds** [comment]
It’s the woocommerce product add-on plugin that is doing this. How would I run the query without that?

**Comment by Ritesh-patel** [comment]
@kwiatdiamonds you can pass the same arguments as the plugin would do to custom WP_Query with different sort meta key. Also, you may want to check if that meta_key exists in single post object in Elasticsearch.
