### ISSUE TITLE
Error after plugin install with Elastic Search 6.2.3

### ISSUE THREAD

**Issue by flaversaver21** [10up/ElasticPress#1052]
Have you searched for similar issues before submitting this one?
yes

Is this a bug, question or feature request?
bug

Describe the issue you encountered:
**Error: Your Elasticsearch version is below the minimum required Elasticsearch version 1.7.** **ElasticPress may or may not work properly.**

Current WordPress version:
4.9.5
Current ElasticPress version:
2.4.2
Current Elasticsearch version:
6.2.3
Where do you host your Elasticsearch server:
mddhosting.com
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Redux Framework |   | by Team Redux – 3.6.8
-- | -- | --
Advanced Custom Fields |   | by Elliot Condon – 4.4.12
AfterShip - WooCommerce Tracking |   | by AfterShip – 1.8.4 – Not tested with the active version of WooCommerce
Contact Form 7 |   | by Takayuki Miyoshi – 5.0.1
Documents Tab WooCommerce |   | by Adrian Dimitrov – 1.0 – Not tested with the active version of WooCommerce
ElasticPress |   | by Taylor Lovett, Matt Gross, Aaron Holbrook, 10up – 2.4.2
Email Cart for WooCommerce |   | by Rymera Web Co – 1.4.6 – Not tested with the active version of WooCommerce
WooCommerce Quickview |   | by Iconic – 3.4.4 – Not tested with the active version of WooCommerce
WPBakery Page Builder |   | by Michael M - WPBakery.com – 5.4.5
Manage Notification E-mails |   | by Virgial Berveling – 1.3.0
WooCommerce Upsells Shortcode |   | by SkyVerge – 1.0.0 – Not tested with the active version of WooCommerce
UPS WooCommerce Shipping |   | by Xadapter – 3.9.13
User Switching |   | by John Blackbourn – 1.3.0
WC Multiple Email Recipients |   | by Con Schneider – 1.2.4 – Not tested with the active version of WooCommerce
Woo EDD Email Domain Blacklist |   | by Md. Kowsar Hossain – 2.0.0 – Not tested with the active version of WooCommerce
WooCommerce AvaTax |   | by SkyVerge – 1.6.2
WooCommerce Bulk Order Form |   | by Jeremiah Prummer – 2.2.1 – Not tested with the active version of WooCommerce
WooCommerce Print Invoice & Delivery Note |   | by Tyche Softwares – 4.4.2
WooCommerce Enable Free Shipping on a Per Product Basis |   | by Patrick Rauland & eugenf – 1.0.2 – Not tested with the active version of WooCommerce
WooCommerce Sage Payments USA Gateway |   | by Andrew Benbow – 2.1.8
WooCommerce Sequential Order Numbers |   | by SkyVerge – 1.8.2 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.3.4
WooSidebars |   | by WooThemes – 1.4.3
Yoast SEO |   | by Team Yoast – 7.2
LiveChat |   | by LiveChat – 3.4.2
WP reCaptcha Integration |   | by Jörn Lund – 1.2.1
WP Super Cache |   | by Automattic – 1.5.9
YITH WooCommerce Compare |   | by YITHEMES – 2.3.0
YITH WooCommerce Wishlist

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:
<img width="1450" alt="screen shot 2018-04-07 at 11 07 06 am" src="https://user-images.githubusercontent.com/9562723/38458507-e52b1f12-3a53-11e8-8474-886a4b548b4d.png">

**Comment by flaversaver21** [comment]
By installing PHP Curl I now have the ability to do a sync. It throws a compatibility error with v6.2.3, so clearly the wordpress plugin needs to be updated.

**Comment by Ritesh-patel** [comment]
Hi @flaversaver21 

The max Elasticsearch version supported as of now is 6.1. We are looking into it to get it compatible with Elasticsearch 6.2.3.

**Comment by Ritesh-patel** [comment]
In our initial testing we found that it works fine with Elasticsearch 6.2.3. You may want to check with your host regarding installed Elasticsearch version. What version it says when you check "Elasticsearch Host" URL from settings? If it's 6.2.3, the error message you are getting is wrong and it looks like it fails to get Elasticsearch version.

**Comment by Rayduxz** [comment]
@Ritesh-patel Since it's compatible, can at least there be a quick update to hide the warning up to this version? Or make the warning not permanent to be able to dismiss it.

Thank you!

**Comment by Ritesh-patel** [comment]
@Rayduxz Warning for 6.2.3 version will be removed in future update but it shouldn't be prevent it from working. @flaversaver21 Looking at the error you are facing, it shows Elasticsearch version 1.7, you may want to check with the hosting service.

**Comment by tlovett1** [comment]
2.5 supports ES 6.2.

**Comment by mremms** [comment]
Struggling with connections ElasticPress to Elasticsearch?  
Wordpress 4.9.8.
ElasticPress 2.6.1
Multi-site: yes
Port 9200 open: yes

[root@server elasticsearch]# curl -XGET 127.0.0.1:9200
{
  "name" : "rp9lpLX",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Zkg-qHzdTF6MYiD-McSCog",
  "version" : {
    "number" : "6.1.3",
    "build_hash" : "af51318",
    "build_date" : "2018-01-26T18:22:55.523Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

so all looking good here but getting the can't connect message in ElasticPress?

In my case I had disabled curl as a security measure in php.ini.  Maybe this will help someone!
