### ISSUE TITLE
ElasticSearch DB gets out of sync

### ISSUE THREAD

**Issue by cbratschi** [10up/ElasticPress#1054]
Have you searched for similar issues before submitting this one?
Yes.

Is this a bug, question or feature request?
A question so far.

Describe the issue you encountered:
Our ElasticPress setup is now running for about two weeks and it happened twice that results from ElasticPress were out-of-date. Suddenly changes in WordPress are no longer sent to ElasticSearch and the "Protected Content" plugin delivers old values, for instance an old title or reports a published article as draft. Creating the index again solves this issue. However, ElasticPress does not report any issues on a production system. Is there a way to get more details about such an issue and how can we solve it?

Current WordPress version:
4.9.5

Current ElasticPress version:
2.4.2

Current Elasticsearch version:
6.2.2

Where do you host your Elasticsearch server:
elastic.co

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
ACF, Yoast SEO, ...

Steps to reproduce:

1. Install ElasticPress
2. Index data
3. Wait for people to complain about CMS issues

Screenshots, if needed:

**Comment by cbratschi** [comment]
The problem is that logs are disabled in our production system. All other third-party systems are monitored by us and we report errors via mail and in our dashboard. It would be very useful if ElasticPress offers a way to intercept errors. I did not check the ElasticPress source code yet to see how ElasticSearch errors are handled.

**Comment by cbratschi** [comment]
Well, found the ep_remote_request action. We will use this one to monitor ElasticPress.

**Comment by Ritesh-patel** [comment]
ElasticPress fires `ep_after_index_post` action on post sync (https://github.com/10up/ElasticPress/blob/2.5/classes/class-ep-api.php#L115), check value of $return, if it's false, than there was an error indexing that post. 

You can also use Debug Bar ElasticPress: https://wordpress.org/plugins/debug-bar-elasticpress/ plugin to debug requests made to Elasticsearch instance.

Thanks

**Comment by tlovett1** [comment]
I'd recommend using the Query Log within ElasticPress Debug Bar plugin.

**Comment by cbratschi** [comment]
Today an inconsistency happened again: a new article was no longer listed in the posts view. However, no errors were reported this time. Re-indexing all posts solved the issue again.

We monitor the following actions:

1) ep_remote_request

Here we got some connection timeouts in the past. After the last ElasticPress update this week we did not see any further timeouts. EP anyway retries a couple of times and therefore this should not have been an issue.

2) ep_after_index_post

We check for $return === false. So far no errors were reported. In some cases $return is null, for instance whenever attachments are saved (we ignore those cases).

3) ep_index_post_retrieve_raw_response

Here we check if $request is an error and report the full error message. This case never happened so far.

We are using the Debug Bar but in our production system we cannot enable the Query Log.

So it is still not clear why we get those inconsistencies again and again.

**Comment by cbratschi** [comment]
We just had a new issue: a published article is still shown as draft in the internal search.

In the meantime we enabled the Query Log on production but this case did not show up and our code also did not report anything.

Could you please extend the Query Log screen to show timestamps of all logged items?

**Comment by cbratschi** [comment]
It happened four times this week that the ElasticSearch database was out of sync. Some metadata fields were inconsistent. Again, we only saw a few timeouts in the logs but no reported errors. The Query Log is empty too.

This is a showstopper for our production system. Somehow MySQL updates are either not synchronized or not correctly updated. Any ideas what could have gone wrong? Are others observing similar issues?

**Comment by allan23** [comment]
Hi @cbratschi, what kind of caching mechanisms do you have on your production site?

**Comment by cbratschi** [comment]
W3 Total Cache is active but for logged in users no caching is active at all. So caching should not be the issue.

We just increased the network retries from 1 (default) to 4. Probably this will reduce this issue.

**Comment by cbratschi** [comment]
This issue is still open. Currently we only use ElasticPress for external searches but we want to use WordPress internal integration soon again. However, this issue prevents it so far.

**Comment by brandwaffle** [comment]
@cbratschi I do think the connection errors you're continuing to see are likely related to the problem. I noticed you're hosting with Elastic.co, which imposes certain CPU-credit style limits that we've seen interfere with indexing and other ElasticPress sync activities.

Another user recently reported similar timeout issues there https://github.com/10up/ElasticPress/issues/1102. I suspect there might be a performance limitation with the Elastic cloud which is causing intermittent performance issues for ElasticPress users.

As we did in issue 1102, we'd be happy to spin up a demo for you of our elasticpress.io service so you can confirm whether the issue is slow connectivity with elastic.co. You can simply visit https://elasticpress.io and request a demo--no credit card is needed. If this resolves your problem you're welcome to use that service or a different service--there are others on this forum successfully using services such as Cloudways or qbox.io (though of course we'd love to have you as a customer!).

**Comment by cbratschi** [comment]
@brandwaffle By default there was only a single connection without retries being used. We are used now 3 retries and no longer got any timeout errors. There was just one exception where a timeout was reported.

Right now we are no longer using the "Protected Content" indexing, just external searches run through ElasticPress. This month we plan to activate it again for certain dashboard searches. I will update this ticket once we gathered more details.

**Comment by brandwaffle** [comment]
@cbratschi thanks for the update! Based on our experience, I still think it's worth considering the connectivity problem, but if you do determine it's something we can correct in code, please let us know!

**Comment by cbratschi** [comment]
This week we had issues with two articles. Both articles did not appear in search results at all and the search text is part of the title. After synchronizing, the first article appeared in search results. This means the article was not in ElasticSearch.

The second article is still not visible. This is very strange.

We are logging all ElasticPress connectivity issues but there are no log reports for both issues.
