### ISSUE TITLE
Which action should I call?

### ISSUE THREAD

**Issue by mynamavi** [10up/ElasticPress#1055]
Hi,
This is question.
I have  to sync custom data like User Info. 
Using: current version of EP and 6.0 of ES on AWS.

As i told, I need to sync user info in elastic search indeixing, I want to use ElasticPress for that because it can sync the data. My question which action should I call or which file should I look to start with?

It will be great help if you could point me to right direction.
Thanks

**Comment by Ritesh-patel** [comment]
Can you give more details in what way you want to index user data? Is it users table you want to index or you want to add user data with a post object?

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh

**Comment by mynamavi** [comment]
Sorry Ritesh, I sorted that out but didn't checked the thread.

**Comment by mynamavi** [comment]
BTW Thanks!
