### ISSUE TITLE
Additional filters in post_filter

### ISSUE THREAD

**Issue by brusic** [10up/ElasticPress#1059]
Since I opened the issue/question, I have changed the title and focus after learning some more details. I am not in charge of the WP installation.

**Have you searched for similar issues before submitting this one?**
Yes

**Is this a bug, question or feature request?**
Question

**Describe the issue you encountered:**
At some point, there is a callback that adds a post_lang term filter to the post filter:

```
{
  "post_filter": {
    "bool": {
      "must": [
        {
          "term": {
            "post_type.raw": "..."
          }
        },
        {
          "terms": {
            "post_status": [
              ...
            ]
          }
        },
        {
          "term": {
            "post_lang": "en"
          }
        }
      ]
    }
  }
}
```

My question is, where is this added? Since I cannot find a reference to post_lang in the code, I am assuming it is derived from the overall wp_query. Is this assumption correct? Which callback handles adding additional filters to post_filters? We think it might have to do with enabling the WPML plugin.

Original issue, which I think is wrong:
Was this (post_lang) added in a recent version? We are starting to think this was added perhaps in 2.4.2. It is occurring after the call to ep_weight_recent, but that is where my trail runs cold. It is returned after the call to apply_filters( 'ep_search_args', $args, $scope, $query_args )  ( https://github.com/10up/ElasticPress/blob/2.4.2/classes/class-ep-api.php#L211 )

**Current WordPress version:**
4.9.2

**Current ElasticPress version:**
2.4.2

**Current Elasticsearch version:**
5.5

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):**
ACF, Askimet, Custom Taxonomy, WPML, ...

**Comment by Ritesh-patel** [comment]
Hi @brusic 

As far as I know ElasticPress doesn't add `post_lang` field into query. I am suspecting one of the plugin must be using `ep_formatted_args` or `ep_search_args` filter to add that field. It's worth checking out with other plugins disabled and see which plugin adding the field by activating them one by one.

**Comment by brusic** [comment]
Please excuse me if I never responded. It was in fact another plugin (WPML) that added the filter. Find it bizarre that other plugins will know about Elasticsearch.
