### ISSUE TITLE
Flush cache how?

### ISSUE THREAD

**Issue by neosin** [10up/ElasticPress#1061]
We have an issue where the tags are not updating, they no longer exist in the WP DB and appear to be stuck in ElasticSearch, how do we dump the ElasticSearch cache?

**Comment by Ritesh-patel** [comment]
Please check this guide: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-clearcache.html for how to clear index cache. If nothing helps, you can try re-indexing.

**Comment by allan23** [comment]
@neosin, does a re-index resolve your issue?
