### ISSUE TITLE
Optimize backend searches

### ISSUE THREAD

**Issue by Demitjev** [10up/ElasticPress#1063]
Have you searched for similar issues before submitting this one?
No

Is this a bug, question or feature request?
feauture/bug

Describe the issue you encountered:
When I search within my +100.000 products in WooCommerce, in the admin interface/backend, my searches is  not powered by ES. They are still  incredible slow.

Current WordPress version:
4.9.5

Current ElasticPress version:
2.5

Current Elasticsearch version:
5.3

Where do you host your Elasticsearch server:
Localhost

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce an alot of others

Steps to reproduce:

1.  Open backend
2. Click Products
3. Do a search. It takes forever

Thank you so much for reading :)

**Comment by Ritesh-patel** [comment]
Hi Demitjev,

So what I understand is you have enabled "Protected Content" feature but it's not working for WooCommerce in dashboard, is that correct? If so, make sure you have re-indexed all the data, you may also want to check with Debug Bar ElasticPress: https://wordpress.org/plugins/debug-bar-elasticpress/ plugin and see what data it sends/receives.

**Comment by lkraav** [comment]
I think at first I also failed to realize that admin queries are part of the Protected Content feature. Not sure if this is addressed clearly enough in GETTING STARTED or similar documentation block.

**Comment by allan23** [comment]
Hi @lkraav, does activating Protected Content resolve your issue?

**Comment by zldang** [comment]
I am also having the same problem:
WordPress 4.9.5
WooCommerce 3.3.5
ElasticPress 2.5.2
ElasticSearch 6.2

Products Search on admin page is also very slow.
I have about 50k products, searching takes ~ 50 to 60 seconds.

**Comment by zldang** [comment]
@lkraav I have Protected Content activated and it doesn't help.

**Comment by allan23** [comment]
@zldang Have you installed the ElasticPress Debug Bar plugin? Perhaps we can track down where the slowness is coming from.

**Comment by Demitjev** [comment]
No. Sorry for not getting back. Haven’t tried debug bar, as we had to disable ES as it also turned out that when we searched on order id’s in the backend, we got no results, even though the order number were valid. Right now we have turned to Redis as is works very well, it gives an amazing fast front+backend. Except for searches. They are stil slow. 

We do have a lot of custom fields on our products, as well as 2 additional tag-trees. No variations. Is it because ES is not indexing all my customs fields and tags? This is the case for the Woocommer Custom Search. (an official plugin for WC with autosuggest, makes it own table which makes the searching a bit faster, but still too slow for autosuggest and autocomplete (1-5secs) without ES. 

The goal for us is a dedicated database-servers on AWS, with ES for searching and Memcached for object cache. We are working on this as we speak.

**Comment by allan23** [comment]
@Demitjev, you mention that you have a lot of other plugins installed including WooCommerce Custom Search. Have you tried searches with certain plugins disabled? This may help you determine what is causing the bottleneck.

**Comment by Demitjev** [comment]
Yes, tried without the most nescescary ones.

*Mvh. Peer Elmelund // Webdesigner hos Ondesign*

Ondesign by Athenas // Vestergade 63, 3. Sal // DK-5000 Odense C
www.ondesign.dk // peer@ondesign.dk // telefon: 321 290 62

2018-06-11 20:49 GMT+02:00 Allan Collins <notifications@github.com>:

**Comment by allan23** [comment]
Please try the debug bar plugin and let us know the results.
