### ISSUE TITLE
facet search and range slider support?

### ISSUE THREAD

**Issue by kwiatdiamonds** [10up/ElasticPress#1068]
Have you searched for similar issues before submitting this one?
Yes
Is this a bug, question or feature request?
Question
Describe the issue you encountered:
I see that facet search is part of the latest update. I was wondering if it's possible to create a slider ui for a range search, as opposed to a select / checkbox output?

Current WordPress version:

Current ElasticPress version:

Current Elasticsearch version:
Version 2.5

Where do you host your Elasticsearch server:
pagely

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by allan23** [comment]
@kwiatdiamonds, at the moment the functionality only has checkboxes. However, we will likely add filters to the Facets to allow developers to customize it.

**Comment by elvismdev** [comment]
@allan23 

> @kwiatdiamonds, at the moment the functionality only has checkboxes. However, we will likely add filters to the Facets to allow developers to customize it.

@allan23 Are any of this filters already available and customizations examples somewhere? I'm in need also to have a slider and date facets powered by ElasticPress.
