### ISSUE TITLE
After upgrading to 2.5, the_content() returns unformatted content in blog view

### ISSUE THREAD

**Issue by florianbrinkmann** [10up/ElasticPress#1070]
Hi,

today I upgraded to ElasticPress 2.5. After visiting the blog page of my site, I noticed that instead of the part until the read more link, the whole content is displayed inside a single `p` element (like the result of `the_content()` without length limit) – the single view is not affected. After disabling EP, everything looks fine again, and the issue was not there with 4.2.4.

Current WordPress version: 4.9.5

Current ElasticPress version: 2.5

Current Elasticsearch version: 2.4.6

Where do you host your Elasticsearch server: Heroku.

Thanks in advance,
Florian

**Comment by florianbrinkmann** [comment]
Thanks @Ritesh-patel, that fixed it!
Today I noticed that the issue also appears on the search results view, and there also with 2.4.2.

**Comment by tlovett1** [comment]
Fixed in 2.5.1.
