### ISSUE TITLE
Searches not being handled by Elasticpress

### ISSUE THREAD

**Issue by pidesign** [10up/ElasticPress#1075]
Have you searched for similar issues before submitting this one?
**Yes**

Is this a bug, question or feature request?
**Question**

Describe the issue you encountered:
**I've installed ElasticSearch and ElasticPress using the instructions from https://www.cloudways.com/blog/elasticsearch-on-wordpress. The sync works fine and I'm able to run commands from the WP-CLI. I installed the debug bar and elasticpress addon but it doesn't show any queries.**

Current WordPress version:
**4.8.6**

Current ElasticPress version:
**2.5.1**

Current Elasticsearch version:
**5.4**

Where do you host your Elasticsearch server:
**Cloudways**

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
**Woocommerce**
Theme: Divi

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by allan23** [comment]
Hello @pidesign,
Can you share what the ElasticPress section of the Debug Bar outputs?
