### ISSUE TITLE
Elasticpress crashes when indexing at fv-wordpress-flowplayer (solved)/ No posts shown (unsolved)

### ISSUE THREAD

**Issue by hermannkm** [10up/ElasticPress#1078]
```
admin@server:/var/www/blog/wp-admin$` wp elasticpress index
Indexing posts...
PHP Fatal error:  Uncaught Error: Call to a member function _get_option() on null in /var/www/blog/wp-content/plugins/fv-wordpress-flowplayer/models/lightbox.php:303
Stack trace:
#0 /var/www/blog/wp-includes/class-wp-hook.php(286): FV_Player_lightbox->html_lightbox_images('<p>Wann immer i...')
#1 /var/www/blog/wp-includes/plugin.php(203): WP_Hook->apply_filters('<p>Wann immer i...', Array)
#2 /var/www/blog/wp-content/plugins/elasticpress/classes/class-ep-api.php(624): apply_filters('the_content', 'Wann immer ich ...')
#3 /var/www/blog/wp-content/plugins/elasticpress/classes/class-ep-api.php(2701): EP_API->prepare_post(17298)
#4 /var/www/blog/wp-content/plugins/elasticpress/bin/wp-cli.php(583): ep_prepare_post(17298)
#5 /var/www/blog/wp-content/plugins/elasticpress/bin/wp-cli.php(533): ElasticPress_CLI_Command->queue_post(17298, 350, false)
#6 /var/www/blog/wp-content/plugins/elasticpress/bin/wp-cli.php(419): ElasticPress_CLI_Command->_index_helper(Array)
#7 [internal function]: ElasticPress_CLI_Command->index(Array, Array)
#8  in /var/www/blog/wp-content/plugins/fv-wordpress-flowplayer/models/lightbox.php on line 303
Fatal error: Uncaught Error: Call to a member function _get_option() on null in /var/www/blog/wp-content/plugins/fv-wordpress-flowplayer/models/lightbox.php:303
Stack trace:
#0 /var/www/blog/wp-includes/class-wp-hook.php(286): FV_Player_lightbox->html_lightbox_images('<p>Wann immer i...')
#1 /var/www/blog/wp-includes/plugin.php(203): WP_Hook->apply_filters('<p>Wann immer i...', Array)
#2 /var/www/blog/wp-content/plugins/elasticpress/classes/class-ep-api.php(624): apply_filters('the_content', 'Wann immer ich ...')
#3 /var/www/blog/wp-content/plugins/elasticpress/classes/class-ep-api.php(2701): EP_API->prepare_post(17298)
#4 /var/www/blog/wp-content/plugins/elasticpress/bin/wp-cli.php(583): ep_prepare_post(17298)
#5 /var/www/blog/wp-content/plugins/elasticpress/bin/wp-cli.php(533): ElasticPress_CLI_Command->queue_post(17298, 350, false)
#6 /var/www/blog/wp-content/plugins/elasticpress/bin/wp-cli.php(419): ElasticPress_CLI_Command->_index_helper(Array)
#7 [internal function]: ElasticPress_CLI_Command->index(Array, Array)
#8  in /var/www/blog/wp-content/plugins/fv-wordpress-flowplayer/models/lightbox.php on line 303

```
Have you searched for similar issues before submitting this one?
y
Is this a bug, question or feature request?
bug?
Describe the issue you encountered:
Indexing stalled at some point, never finished. Tried command line indexing getting this error
Current WordPress version:
4.9.5
Current ElasticPress version:
2.5.1
Current Elasticsearch version:
6.2.3
Where do you host your Elasticsearch server:
localhost
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
FV Player
Steps to reproduce:

At wp cli try 

wp elasticpress index

Screenshots, if needed:

**Comment by allan23** [comment]
Hi @hermannkm,
The FV WordPress Flowplayer plugin is not properly developed to run from WP CLI. (It is relying on a global variable that never gets set on CLI, but does on the frontend facing site.) The plugin developer will need to address this issue to have it work from WP CLI.

To get around this, you will have to run an index from the wp-admin interface.

Alternatively, you can run it via WP CLI, but excluding the loading of the Flowplayer plugin: 
`wp elasticpress index --skip-plugins=fv-wordpress-flowplayer`.

**Comment by hermannkm** [comment]
Hi Allan,
thank you for your reply. 
My problem started at the wp-admin interface, syncing never finished but stalled with „Paused syncing“ at 2257/2257 or „Syncing 2261/2261". I tried to figure out the problem and therefore went to cli to delete my index and reindex.
Now I did this using your command which finished perfectly, although my EP dashboard is stuck at the same message.
Where should I go now?

Hermann

**Comment by hermannkm** [comment]
<img width="224" alt="bildschirmfoto 2018-05-09 um 06 03 38" src="https://user-images.githubusercontent.com/12869273/39802865-884ced7c-536f-11e8-9a0b-518b5a004bf9.png">
<img width="682" alt="bildschirmfoto 2018-05-09 um 06 02 28" src="https://user-images.githubusercontent.com/12869273/39802938-bd38ea72-536f-11e8-9019-4792690e9c85.png">
<img width="1108" alt="bildschirmfoto 2018-05-09 um 06 02 20" src="https://user-images.githubusercontent.com/12869273/39802939-bd78a82e-536f-11e8-9119-407866ff1719.png">

**Comment by lkraav** [comment]
Yes, there are multiple plugins that are careless with their global variables.

You could file a bug report here https://foliovision.com/support/fv-wordpress-flowplayer/bug-reports and refer them over here.

**Comment by hermannkm** [comment]
Just did that (awaiting moderation). Deactivated FV Player for now but still no luck. Uninstalled and installed EP. Still, dashboard stuck at "paused" or forever "Syncing".

**Comment by hermannkm** [comment]
Now indexing is working flawlessly. Alas in my landing page (which is just the domain name blog.klockerei.at) no posts are shown if elasticpress is enabled. Other menues listing e.g. category entries show perfectly. Don't know where to look next, had to disable again.

**Comment by allan23** [comment]
@hermannkm, do you have the Debug Bar and Debug Bar ElasticPress plugin installed?

If so, it can help troubleshoot your issue.

**Comment by allan23** [comment]
Closing due to no response in 25 days.
