### ISSUE TITLE
Hide password protected posts from search results

### ISSUE THREAD

**Issue by tomdxw** [10up/ElasticPress#1083]
Have you searched for similar issues before submitting this one? Yes.

Is this a bug, question or feature request? Bug or feature request, depending on how you look at it.

Describe the issue you encountered:

WordPress's default search hides password protected posts from logged out users.

ElasticPress doesn't hide password protected posts from logged out users, and doesn't record the password protected status in Elasticsearch so there's no easy way to hide the password protected posts.

Current WordPress version:

4.9.5

Current ElasticPress version:

2.5.2

Current Elasticsearch version:

5.6.5

Where do you host your Elasticsearch server:

n/a

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

None.

Steps to reproduce:

1. Create a password protected post
2. Search for it as a logged out user and see that it's not in the results
3. Activate ElasticPress and sync
4. Search for the post as a logged out user and see that it's in the results

**Comment by allan23** [comment]
@tomdxw thank you for bringing this to our attention.

**Comment by tlovett1** [comment]
@allan23 can you test/create a PR?

**Comment by rebeccahum** [comment]
Can we re-open this issue because it looks like it got reverted?
