### ISSUE TITLE
Do not search for author_name when searching products in woocommerce

### ISSUE THREAD

**Issue by pierrebuet** [10up/ElasticPress#1086]
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?
Bug
Describe the issue you encountered:
Search on the product archive page for a string like the login of one shop manager and you will got all the products listed

Explanation : ep_improve_default_search is adding a search_fields array to the query, not matter which post type. This includes author_name and the taxonomies post_tag and category which are then not relevant for woocommerce.

Sometime later on the same hook and if woocommerce is installed, ep_wc_translate_args adds again arguments to search_fields, which are the relevant one when searching products. Unfortunately, the first arguments added to search_fields are not unset but kept.

To help solving the issue: In woocommerce.php, replacing around line 436 and 464
$search_fields = $query->get( 'search_fields', array( 'post_title', 'post_content', 'post_excerpt' ) )
in $search_fields = array( 'post_title', 'post_content', 'post_excerpt' )
solved the bug for me.

**Comment by allan23** [comment]
Thanks for the information @pierrebuet. I have created a pull request to address this.
