### ISSUE TITLE
multisite problems

### ISSUE THREAD

**Issue by mattimpact** [10up/ElasticPress#1087]
Have you searched for similar issues before submitting this one? yes

Is this a bug, question or feature request? Question

Describe the issue you encountered:

I am trying to get this to work using a multisite. I have managed to get it to query the multiple indexes by adding;

`$news = new WP_Query( 
    array(
        's'             => $search_string,
        'sites'         => array(1,2,3,4),
        'ep_integrate'   => true,
    )
);`

Using 'sites' => 'all' did not appear to work. Now I get the query showing up in the debugger e.g.

`https://endpoint.es.amazonaws.com/site-1,site-2,site-3,site-4/post/_search
`

But I get no results - I am using terms that give a me result - the only result I get it for the current site. 

I could only get the child sites indexed by activating the plugin on each site too.

Any help much appreciated.

Current WordPress version: 4.9.6 multisite

Current ElasticPress version: 2.52

Current Elasticsearch version: 6.2

Where do you host your Elasticsearch server: AWS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): wpmu domain mapping

**Comment by mattimpact** [comment]
is elasticsearch 6.2 supported - just looked at previous issuse: https://github.com/10up/ElasticPress/issues/1085

**Comment by mattimpact** [comment]
sort of got this working downgraded elasticsearch 5.1 - this made no difference though

running the indexing via wp-cli I was getting SQL errors that related to wpml which was running on one of the sites - I turned this off and things got better.

Then I disabled the document search as I was getting attachment not found errors.

I have altered the plugin slightly to make the document search work(not) with AWS as I know there is an issue with the ingest plugin.

**Comment by mattimpact** [comment]
right upgrade back to 6.2 and documents is now working - I setup a completely new domain on AWS

**Comment by allan23** [comment]
Hi @mattimpact,
It sounds like you have multiple issues here. 
What were you able to resolve and what is still outstanding?

**Comment by mattimpact** [comment]
Everything is working - I have not turned wpml back on yet but the documents are being indexed. I built a new elasticsearch node on AWS which seemed to make a difference - although when using documents I need to comment out the check for ingest plugin to make it work with AWS

**Comment by photocurio** [comment]
@mattimpact can you link to the Ingest Attachment issue?

**Comment by ethanclevenger91** [comment]
@photocurio I believe he's referring to [this](https://github.com/10up/ElasticPress/issues/1020#issuecomment-364968081)
