### ISSUE TITLE
"reason": "No mapping found for [meta._iwj_featured_date.long] in order to sort on",

### ISSUE THREAD

**Issue by iexpertini** [10up/ElasticPress#1090]
Hi there,

Please can anyone help as we are unable to fix it. 

1. If we put some keyword as an example in Query Args **sales**
`array(71) {
  ["post_type"]=>
  string(7) "iwj_job"
  ["post_status"]=>
  array(1) {
    [0]=>
    string(7) "publish"
  }
  ["s"]=>
  string(5) "sales"
  ["meta_query"]=>
  array(1) {
    ["relation"]=>
    string(3) "AND"`

the Elasticpress in debug shows this 

`
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "No mapping found for [meta._iwj_featured_date.long] in order to sort on",
                "index_uuid": "NietcrsgQhy1H6j2Anhtgg",
                "index": "1041971172-1"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "1041971172-1",
                "node": "_jVCiSiZSLyUrRcAZ9D9Xg",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "No mapping found for [meta._iwj_featured_date.long] in order to sort on",
                    "index_uuid": "NietcrsgQhy1H6j2Anhtgg",
                    "index": "1041971172-1"
                }
            }
        ]
    },
    "status": 400
}
`

I think we need to add  `ignore_unmapped" : true`
But where we need to add this? 

2. Secondly If no keyword is put in search. The elastic press in debug mode not show anything 

TOTAL ELASTICPRESS QUERIES:
0
TOTAL BLOCKING ELASTICPRESS QUERY TIME:
0 ms
No queries to show

**Comment by iexpertini** [comment]
Hi there,
 
I fond solution here: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-

sort.html#_ignoring_unmapped_fields

GET /_search
{
    "sort" : [
        { "price" : {"unmapped_type" : "long"} }
    ],
    "query" : {
        "term" : { "product" : "chocolate" }
    }
}

But where i need to put this code. Can anyone PLEASE HELP.

No answer from so long :(((((((((((((((((((((((((((((((((((

Thanks,
Ahsan

**Comment by allan23** [comment]
Hello @iexpertini,

Can you provide more information on how you are performing queries? 

Which plugins are you using? Which version of ElasticSearch?

Can you let us know what `iwj_featured_date` is? Is that from a plugin or custom code?

**Comment by iexpertini** [comment]
Hi,

I am using Elasticsearch 6 version from Google Cloud of Bitnami. The plugin I set up is Elasticpress on my Wordpress site.

The Wordpress theme template of injobs has its own Search frame and they are using query to pass by this custom meta value "iwj_featured_date" for every custom post i.e. post_type=iwj_job. But since "iwj_featured_date" value is empty and the search is not displaying results from Elasticsearch.

Although Elasticsearch supporting the default Wordpress search.

So, I need one solution to ignore empty meta values while sorting the result.

Kindly let me know if you need more information on it.

Thanks,
Ahsan

**Comment by allan23** [comment]
Ahsan,
Is Injobs a free or commercial theme? Where can I find this for testing?

**Comment by iexpertini** [comment]
Hi Allan

Once you noted this let me know we can delete this message.


Thanks please note all site details 

Theme Job Search: http://searchnzjobs.co.nz/jobs/?keyword=sale&iwj_location=&iwj_cat= 
Although working fine for default wordpress search:
 http://searchnzjobs.co.nz/?s=job


Here is the site Admin
http://searchnzjobs.co.nz/wp-admin
username: http://searchnzjobs.co.nz 
password: rt06rt06

Check Debug at top right: http://searchnzjobs.co.nz/jobs/?keyword=sale&iwj_location=&iwj_cat=#debug-menu-target-EP_Debug_Bar_ElasticPress


I have added File Manager plugin for you to access 

However, FTP is also here:
FTP server:  108.167.158.140
FTP Username: searchnzjobs@searchnzjobs.co.nz
FTP Password: rt06rt06
FTP port:  21

Elasticsearch server: http://user:zofgcveWkG9Y@35.192.3.245/elasticsearch/
Elasticsearch indexer:  http://35.192.3.245/elasticsearch/searchnzjobsconz-1/_search  

Once you noted this let me know we can delete this message.

Thanks,
Ahsan

**Comment by allan23** [comment]
@iexpertini,
Please do not post passwords or any sensitive data publicly. 
This sounds like an issue with the theme code. However, unless you can prove that the issue exists on another theme, or a custom WP_Query, or through a code snippet, please let us know.

In this case, I would advise that you contact the theme developer and work closely with them.
