### ISSUE TITLE
comment_count value is frequently incorrect

### ISSUE THREAD

**Issue by tomdxw** [10up/ElasticPress#1092]
Have you searched for similar issues before submitting this one? Yes.

Is this a bug, question or feature request? Bug.

Describe the issue you encountered: `get_post()` returns an object with an old `comment_count` value, not the current value.

Current WordPress version: 4.9.6

Current ElasticPress version: 2.5.2

Current Elasticsearch version: 5.6.5

Where do you host your Elasticsearch server: I'm reproducing this issue locally with Elasticsearch running in a Docker container.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): None.

Steps to reproduce:

1. Activate ElasticPress
1. Activate Twenty Seventeen
1. Add `<h1><?php echo esc_html(json_encode(get_comments_number())) ?></h1>` to `wp-content/themes/twentyseventeen/template-parts/post/content.php` (or just activate a theme that shows comment counts on archive pages instead)
1. Create a new post
1. Add a comment

Visiting the post, you'll see `"1"` indicating that there's 1 comment on the post (this is correct).

Visiting the homepage, you'll see `0` indicating that the post has 0 comments (this is incorrect).

ElasticPress should either reindex a post when a comment is added/approved, or it should retrieve the comment_count value from MySQL instead of from Elasticsearch.

**Comment by allan23** [comment]
Thanks @tomdxw. So ElasticPress doesn't sync to Elasticsearch when a comment is inserted, which will show the comment count being incorrect. It is only correct on the single post page because that is fetched directly from MySQL as opposed to Elasticsearch.

We will discuss this internally with the team to determine if there are any performance issues by syncing the comment count upon comment insertion. 

(CC: @tlovett1 )

**Comment by allan23** [comment]
Upon internal discussion, we believe that syncing comment count when comments are inserted is not a wise approach due to performance concerns.

**Comment by JayWood** [comment]
If anyone else comes across this ticket, here's a function for you to use to get them from the DB directly:

```
/**
 * If EP is enabled, gets the count from the DB, otherwise uses core methods to get counts.
 *
 * @param \WP_Post|int $post
 *
 * @return int The comment count.
 */
function get_comments_count_from_db( $post ) {
	global $wpdb;
	if ( ! is_plugin_active( 'elasticpress/elasticpress.php' ) ) {
		return get_comments_number( $post );
	}

	if ( is_a( $post,'WP_Post' ) ) {
		$post = $post->ID;
	}

	$sql = $wpdb->prepare( "select count(comment_id) from {$wpdb->comments} where comment_approved=%d and comment_post_id=%d", [ 1, intval( $post ) ] );
	$count = $wpdb->get_var( $sql );

	/**
	 * Filters the returned comment count for a post.
	 *
	 * @since 1.5.0
	 *
	 * @param string|int $count   A string representing the number of comments a post has, otherwise 0.
	 * @param int        $post_id Post ID.
	 */
	$count = apply_filters( 'get_comments_number', $count, intval( $post ) );

	return intval( $count );
}```
