### ISSUE TITLE
Exlude Attachments from indexing

### ISSUE THREAD

**Issue by tonybahama** [10up/ElasticPress#1093]
Hi!

Is there any filter to exclude attachments from indexing?

We have 800.000 images, 5.000 products, 50.000 orders.

We'd like to only index everything other than images, because there are no searches for images. I am suspecting for single product page, archive page, admin order search purposes it would not help to improve performance right?

Is there a filter to exclude some post types?

We use cli, I saw there is a possibility to exclude for initial index but found no option on the dashboard to prevent attachments from indexing in the future. For example the add_attachment events.

**Comment by allan23** [comment]
Hello @tonybahama,
Out of the box, ElasticPress does not index attachments. Unless you have the Documents feature activated, you should not be seeing them sent to ElasticSearch.

In regards to the filter for post types, you can use: `ep_searchable_post_types` which will filter an array of post types you wish to be searchable.

**Comment by tonybahama** [comment]
Thanks!

It does index them, even without the documents feature. At least with ssh it does.


If I use the filter, activate it, and run it with ssh will it take that into consideration?

**Comment by tonybahama** [comment]
Also please answer a question, we may even leave indexing attachmenst out...

We'd like to only index everything other than images, because there are no searches for images. I am suspecting for single product page, archive page, admin order search purposes it would not help to improve performance right?

**Comment by allan23** [comment]
@tonybahama, 

```
add_action('ep_searchable_post_types', function($post_types) {
    
    // Put your code here to remove or add a certain post type.

    return $post_types;
});
```
