### ISSUE TITLE
400 error - bad request on every post

### ISSUE THREAD

**Issue by tonybahama** [10up/ElasticPress#1097]
Have you searched for similar issues before submitting this one?
Yes, found other 400 errors but not quite like this
Is this a bug, question or feature request?
bug
Describe the issue you encountered:

We are seeing a 400 Bad Request error for every API call. Frontend, admin everywhere.
The index was successful, was done with ssh.

We have 800k indexed posts. It was the same with attachmenst left out.

Current WordPress version:
4.9.6
Current ElasticPress version:
2.5.2
Current Elasticsearch version:
Elastisearch is hosted on Kinsta as well.
Where do you host your Elasticsearch server:

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce
Steps to reproduce:

1. Index
2. Try to load any page :)

Screenshots, if needed:
<img width="1110" alt="screen shot 2018-06-13 at 8 34 38" src="https://user-images.githubusercontent.com/19731470/41334221-0dfb8f60-6ee5-11e8-9870-ded738be792a.png">

**Comment by RistoNiinemets** [comment]
I had the same issue. After some digging and debugging, I found out that the posts weren't successfully indexed. I finally managed to index them after I synced 1 post per page. In my case, way too many attribute taxonomies were used generally, and this caused timeouts.

`wp elasticpress index --setup --posts-per-page=1`

**Comment by tonybahama** [comment]
Thanks for the feedback.

Will try that!

We have about 20-30 taxonomies for each product so that might be an issue...

**Comment by allan23** [comment]
Can you send us the results from the ElasticPress Debug Bar?

**Comment by sc0ttkclark** [comment]
Getting this one a project recently too. EP Debug Bar says this for the response (Error 400):

```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "no [query] registered for [query]",
                "line": 1,
                "col": 174
            }
        ],
        "type": "parsing_exception",
        "reason": "no [query] registered for [query]",
        "line": 1,
        "col": 174
    },
    "status": 400
}
```

**Comment by sc0ttkclark** [comment]
Updated comment with body too

**Comment by sc0ttkclark** [comment]
Update comment with args, which might give a clue into the issue. The meta_query uses a LIKE and the meta value has double quotes in the value it's checking against (ACF serialized array).

**Comment by sc0ttkclark** [comment]
Perhaps the issue here is that there's no real querying going on in the `query` property being sent to Elasticsearch but it's instead just using `post_filter` on it's own.

This project no longer uses ElasticPress as far as I know, so I unfortunately won't be able to revisit this specific problem.

**Comment by allan23** [comment]
As this appears to be an edge case with minimal details to reproduce. I'm closing this issue out.
