### ISSUE TITLE
Querying Users

### ISSUE THREAD

**Issue by weaverhe** [10up/ElasticPress#1098]
I'm wondering if it's possible to query the users tables as part of elasticpress. 

I've got a site with over 250k users (and adding 5-10k/week) which I need to be able to search by several different data points. It's painfully slow just hitting the DB directly, so I'm exploring alternatives.

I'm happy to provide any additional details - thanks in advance!

**Comment by allan23** [comment]
Hi @weaverhe, this is a feature we've been working on.
