### ISSUE TITLE
Plugin is keep giving error on Elastic search version 5.4

### ISSUE THREAD

**Issue by ibadrehman** [10up/ElasticPress#1101]
My site is hosted on Cloudways using Linode server. I tried using the plugin using all three elastic search version (1.7, 2.4 and 5.4) but the plugin is still giving me the error as 
'Your Elasticsearch version is below the minimum required Elasticsearch version 1.7. ElasticPress may or may not work properly.'

Following this guide: https://www.cloudways.com/blog/elasticsearch-on-wordpress/

**Comment by allan23** [comment]
Hi @ibadrehman, are you able to hit the Elasticsearch endpoint to see the JSON payload containing the version?

Depending on your setup, you may need to run a curl to http://127.0.0.1:9200/ on your server.

**Comment by ibadrehman** [comment]
Could you please walk me through which command am I suppose to run on my server?

**Comment by allan23** [comment]
Sure. If your Elasticsearch is on the same server, you would run the following command from the command line:
`curl -i http://127.0.0.1:9200`

**Comment by ibadrehman** [comment]
I ran the command and this is what I got
`HTTP/1.1 301 Moved Permanently                                                                                                                       
Server: nginx                                                                                                                                        
Date: Wed, 27 Jun 2018 08:50:32 GMT                                                                                                                  
Content-Type: text/html; charset=UTF-8                                                                                                               
Content-Length: 0                                                                                                                                    
Connection: keep-alive                                                                                                                               
Location: http://wordpress-1798-53XX79.cloudwaysapps.com/                                                                                          
Cache-Control: max-age=2592000                                                                                                                       
Expires: Fri, 27 Jul 2018 06:28:53 GMT                                                                                                               
Age: 8489                                                                                                                                            
X-Cache: HIT    `

And I still see the same error. What am I missing?

**Comment by allan23** [comment]
Closing due to no response in 25 day.s
