### ISSUE TITLE
Sync error in dashboard on WPEngine

### ISSUE THREAD

**Issue by rpovelones** [10up/ElasticPress#1102]
Have you searched for similar issues before submitting this one?
Yep

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
When syncing from the dashboard, I get an error message saying "An error occurred while syncing". We are hosting on WPEngine and Elastic Cloud. The sync runs for about 1-2 mins and then gives the error. But there are only 62 pages to sync so it should be super fast. I have an exact copy of the live site running locally also with a local elasticsearch server. The sync works fine there, however, not on the WPEngine server. But when I look on the actual elasticsearch server, the data does appear to be there. So I'm not sure what is going on. There are no errors that I can see in the server logs either.

I had WPEngine support look into the issue, but they could not find anything. The did however confirm that there were no additional config steps for the plugin on their platform. So they recommended I reach out here.

Also, to note we are hosting on Elastic Cloud and I have tried to authenticate with `EP_SHEILD` defined in wp-config as well as directly in the host URL per https://wpengine.com/support/setting-elasticpress-elastic-co/.

Current WordPress version: 
4.9.6

Current ElasticPress version: 
2.5.2

Current Elasticsearch version: 
5.6.4

Where do you host your Elasticsearch server: 
https://www.elastic.co/cloud 

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
- ACF content analysis for Yoast SEO
- Gravity Forms ACF Field
- Advanced Custom Fields Pro
- Backupbuddy
- Disable Comments
- Elasticpress
- Gravity forms
- Redirection
- SearchWP
- WP Smush
- Sucuri Scanner
- Yoast

Steps to reproduce:

1. Install plugin, put in Elasticsearch server
2. Click sync button from ElasticPress admin screen
3. Sync runs for a minute or 2, then displays a small message next to the sync button saying "An error occurred while syncing". There is also a 500 admin-ajax error in the dev tools console.

Screenshots, if needed:
<img width="1148" alt="screen shot 2018-06-27 at 9 13 25 am" src="https://user-images.githubusercontent.com/3476825/41978436-e088942c-79ef-11e8-8785-61638b960b46.png">

**Comment by rpovelones** [comment]
Hi, just wanted to check in here. Any thoughts?

**Comment by tott** [comment]
Hi Robert, 
this behavior indicates usually that there is some trouble with the hosting provider in your case elastic.co or WPE. Given your description, I'd start looking at Elastic.co and validate if there might be some resource limits or pre-allocated CPU credits being hit during the indexing operation. 

Let us know if this does not get you any further.

**Comment by rpovelones** [comment]
Thanks @tott. I am only indexing 62 records (post type pages). Would it be realistic that that would hit any sort of resource limits? Seems like that should be a very quick sync. Or are there some other resource limits I might not be thinking about?

**Comment by tott** [comment]
Hey Robert, we can’t speak directly to any hardware or software limits imposed by cloud hosting providers, but you're right - it would be really weird to run into limitations with only 62 posts unless you're indexing a huge amount of data within each post. The easiest way to isolate the cloud provider as the source of the issue would be to grab a free demo account on the ElasticPress.io service and see if you run into the same issue. We don’t require a credit card on any info besides email to get a 14-day trial. These endpoints are also username / password protected so will be a pretty close match to what you have now.

**Comment by rpovelones** [comment]
OK thank you. That is a good suggestion. I just put in a request for a free demo. I will try that and report back here.

**Comment by tott** [comment]
Hi Rober, did you manage to test out the demo account? Did this resolve your issue?

**Comment by rpovelones** [comment]
Hi yes, sorry @tott I did open a demo account on ElasticPress.io and that solved the sync issue! So we can be confident the issue lies with our Elastic Cloud server via elastic.co. I'm working with them to diagnose the issue. Once I get more information, I will post it back here.
