### ISSUE TITLE
How to boost title and content matches for specific custom post types?

### ISSUE THREAD

**Issue by daveboulden** [10up/ElasticPress#1104]
I am trying to figure out the syntax to boost search matches for certain scenarios. I am currently searching on **post_title**, **post_content**, **post_type** and two taxonomies. I have set weight values for each of the search fields using the **ep_formatted_args** hook using this example [here](https://github.com/10up/ElasticPress/issues/998#issuecomment-357194351)

Now I want to set an extra weight or boost value when the search fields match the query string AND it is for a specific custom post type with a different weight value for each custom post type. 

How would I go about that as it seems the filters in the above linked example don't allow multiple field matches?

This is the code from my plugin that I currently have hooked to **ep_formatted_args**:

```

function set_es_search_args($ep_formatted_args, $args = ''){

	$existing_query = $ep_formatted_args['query'];
	unset($ep_formatted_args['query']);
	$ep_formatted_args['query']['function_score']['query'] = $existing_query;

	$ep_formatted_args['query']['function_score']['functions'] = array(
		array(
			"filter" => array(
				"match" => array(
					"post_title" => get_query_var('s'),
				),
			),
			"weight" => intval(get_option('elasticpress_cci_weightings_weight_post_title')),
		),
		array(
			"filter" => array(
				"match" => array(
					"post_content" => get_query_var('s'),
				),
			),
			"weight" => intval(get_option('elasticpress_cci_weightings_weight_post_content')),
		),
		array(
			"filter" => array(
				"match" => array(
					"post_type" => get_query_var('s'),
				),
			),
			"weight" => intval(get_option('elasticpress_cci_weightings_weight_post_type')),
		),
		array(
			"filter" => array(
				"match" => array(
					"taxonomy.topic" => get_query_var('s'),
				),
			),
			"weight" => intval(get_option('elasticpress_cci_weightings_weight_tax_topic')),
		),
		array(
			"filter" => array(
				"match" => array(
					"taxonmomy.cci-tag" => get_query_var('s'),
				),
			),
			"weight" => intval(get_option('elasticpress_cci_weightings_weight_tax_ccitag')),
		),
	);

	// Specify how the computed scores are combined.
	$ep_formatted_args['query']['function_score']["score_mode"] = "sum";
	$ep_formatted_args['query']['function_score']["boost_mode"] = "replace";

	return $ep_formatted_args;
}

```

**Comment by daveboulden** [comment]
Hi, this is on a customer's website we migrated to new servers. I have had to reimplement their ElasticSearch setup as they were previously using ElasticSearch 1.5 with the FantasticElastic plugin.

The effect they are asking us to implement is a way to make any matches against the fields we are searching to have greater significance when the match found is within a post that is a specific custom post type. They want matches within the specific custom post types (they have 7 of them)( to have varying configurable significance per post-type. E.g. any matches in a **Custom_type_3** article always get a bigger boost than if the exact same match was made in an **Custom_type_1** article.

In the admin page of my custom plugin I have a "boost" field for each of the custom post types where the administrator can set the amount of boost a match within that custom post type is given on top of the boosts already in place for matching on **post_title**, **post_content** etc.

**Comment by sc0ttkclark** [comment]
Please also note that you may have to `unset( $ep_formatted_args['sort'] );` because the sort may override some of that boosting (if orderby in the WP_Query is date etc)

**Comment by sc0ttkclark** [comment]
Definitely you need to force _score sort if you are going to do function_score, we couldn’t get it working today with any other sort, which should have been obvious to use given what we were trying to do LOL

**Comment by sc0ttkclark** [comment]
Otherwise it won’t weigh anything at all

**Comment by oscarssanchez** [comment]
Apologies for late response here!

@daveboulden , from what you say, I think you have the right snippet here and maybe what sc0ttclarck mention was what you needed for EP to weigh your queries. 

If this is not the case, do you have a query in elasticsearch format that does what you try to achieve here ?
