### ISSUE TITLE
Elasticsearch 6.3 compatibility?

### ISSUE THREAD

**Issue by lkraav** [10up/ElasticPress#1105]
6.2 compatibility diagnosis https://github.com/10up/ElasticPress/issues/1052#issuecomment-380290427 gives me hope that maybe it's just as easy w/ 6.3 and the admin notice version requirement could be bumped higher?

PS this repo's new issue template could probably use quote markers for better clarity result, as shown below.

> Have you searched for similar issues before submitting this one?

"6.3" gives zero results

> Is this a bug, question or feature request?

Feature request

> Describe the issue you encountered:

"Your Elasticsearch version 6.3.1 is above the maximum required Elasticsearch version 6.2. ElasticPress may or may not work properly." may or may not :) be annoying admins for no reason at all.

> Current WordPress version:

4.9.7

> Current ElasticPress version:

2.5.2

> Current Elasticsearch version:

6.3.1

> Where do you host your Elasticsearch server:

Self

> Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

... I'd say "yes, everything" here.

> Steps to reproduce:

N/A

> Screenshots, if needed:

N/A

**Comment by oscarssanchez** [comment]
Hi @lkraav ,

Thanks for raising this issue,

In upcoming updates, there should definitely be official support for higher versions of ElasticSearch and you will not see the notice displaying for ES 6.3.

In the meantime, if this is a problem for you or for your clients, you could change the `EP_ES_VERSION_MAX` to 6.3 . This is located in line 36 of the `elasticpress.php` file. Although you will not see the notice anymore, just take into account that the notice serves a purpose and it is to redirect ElasticPress users to fully supported versions of ES, so they do not have any problems.

**Comment by lkraav** [comment]
Well sure, but my question is also "are there any actual compatibility issues that the development team has already identified"?

If the issue at hand is just the cosmetics, that'd be great.

**Comment by schrapel** [comment]
@edwinsiebel If you use Composer we use this plugin to alter things like this https://github.com/cweagans/composer-patches

**Comment by rudyamid** [comment]
The latest version of Elasticsearch is 6.4.2 now, and I've just recently installed the Elasticpress plugin.  It's not connecting to my localhost:9200 (nor 127.0.0.1) instance. I verified the Elasticsearch is installed properly (simple config) and confirmed with Kibana that I can connect/monitor/index without any security setting.

**Comment by oscarssanchez** [comment]
Hi @rudyamid , 

I recently tested out 6.4.2 and there's no problem while connecting ES to ElasticPress. There's a problem though when making use of the related posts feature. This will be addressed soon.

If you have problems while connecting, there must be an issue with the setup of ES. 

If you are working locally, I highly recommend you trying out WP-local-docker : https://github.com/10up/wp-local-docker which comes with a container with ES and can be modified to the version you need fairly easily. This is also how I tested 6.4.2 with ElasticPress.

Have a good day,

**Comment by rudyamid** [comment]
Hi @oscarssanchez 

Although installing the Docker version sounds intriguing, I still would like my local setup to work. Can Elasticpress output more verbose (debug) logging so I can see exactly where it's having a problem?  ie. name resolution, connection refused, etc.

Thanks

**Comment by oscarssanchez** [comment]
Hey @rudyamid ,

There's PR https://github.com/10up/ElasticPress/pull/1142 that's likely to be merged for ElasticPress 2.7 . With this feature, you will see more meaningful messages of what's happening if there's an error with ElasticSearch. You are very welcome to try it in the meantime and hope this helps!

**Comment by ratputin** [comment]
Any word on when compatibility will be 100%? Or have you considered adding an option to dismiss the notice?

TIA!
KO
