### ISSUE TITLE
How to correctly use ep_remote_request() with parameters?

### ISSUE THREAD

**Issue by daveboulden** [10up/ElasticPress#1107]
_Have you searched for similar issues before submitting this one? YES

Is this a bug, question or feature request? Question and documentation request

Describe the issue you encountered: Unable to use ep_remote_request() with PUT parameters

Current WordPress version: 4.9.6

Current ElasticPress version: 2.4.2

Current Elasticsearch version: 6.2.2

Where do you host your Elasticsearch server: AWS_

My first request is: Can we have some documentation and basic examples of how to use **ep_remote_request()**? Do the search parameters need to be JSON encoded or PHP arrays? Should the method be a node at the same level as the search query or should that be wrapped in another node?

When calling a "PUT /indexname" command through **ep_remote_request()** without any further parameters, it works. But when adding any parameters, it fails.

I have tried the following code, but it is currently giving me an authentication error which seems like a red herring to me.

```

	$blog_id = get_current_blog_id();
	$ep_path = "/cci_".$blog_id."_synonyms";

	$ep_req = array(
		'method' => 'PUT',			
		'body' => array(
			'settings' => array(
				'index' => array(
					'number_of_shards' => 3,
					'number_of_replicas' => 2, 
					'analysis' => array(
						'analyzer' => array(
							'default' => array(
								'type' => 'custom',
								'tokenizer' => 'standard',
								'filter' => array( 'lowercase', 'stop', 'my_synonyms'),
								'char_filter' => array('html_strip')
							),
							'default_search' => array(
								'type' => 'custom',
								'tokenizer' => 'standard',
								'filter' => array( 'lowercase', 'stop', 'my_synonyms'),
								'char_filter' => array('html_strip')
							)
						),
						'filter' => array(
							'my_synonyms' => array(
								'type' => 'synonym',
								'synonyms' => array('abc,def,ghi,jkl','mno,pqr,stu,vwx')
							)
						)
					)
				)
			)							
		)							
	);

	$rslt = ep_remote_request($ep_path, json_encode($ep_req));


```

The error returned is:

`{"headers":{},"body":"{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/get] requires authentication","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"action [indices:admin/get] requires authentication","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}} `

Am I formatting the **ep_remote_request()** call correctly? Without any discernable documentation on the function it is difficult to know exactly how it should be formatted... what I have so far has been gleaned from checking the **class_ep_api.php** file and scant mentions in extensive Google searches.

**Comment by daveboulden** [comment]
Several hours of Google-slog has helped me arrive at the solution. The code should have been:

```
	$ep_args = [
		"settings" => [
			"index" => [
				"number_of_shards" => "3",
				"number_of_replicas" => "2",
				"analysis" => [
					"analyzer" => [
						"default" => [
							"type" => "custom",
							"tokenizer" => "standard",
							"filter" => [ "lowercase", "stop", "my_synonyms"],
							"char_filter" => ["html_strip"]
						],
						"default_search" => [
							"type" => "custom",
							"tokenizer" => "standard",
							"filter" => ["lowercase", "stop", "my_synonyms"],
							"char_filter" => ["html_strip"]
						]
					],
					"filter" => [
						"my_synonyms" => [
							"type" => "synonym",
							"synonyms" => ["abc,def,ghi,jkl","mno,pqr,stu,vwx"]
						]
					]
				]
			]
		]
	];
			
	$ep_body = [
		"method" => "PUT",	
		"body" => json_encode($ep_args)
	];			

	$rslt = ep_remote_request($ep_path, $ep_body);

```

It would have been so much easier (and quicker!) were there a simple bit of documentation declaring the 2nd parameter to **ep_remoterequest()**, "**args[]**" was a PHP array containing the HTTP verb in the array item "**method**" and the JSON encoded parameters in the array item "**body**".

Could I suggest such an explanation is added to the documentation where it mentions **ep_remote_request()**?

**Comment by oscarssanchez** [comment]
Hi @daveboulden,

Thanks for taking the time to make suggestions to the ElasticPress plugin! 
I agree, Accessor functions are not that intuitive and could use a PHP Doc bloc.

Really something that could use some improvement.

**Comment by daveboulden** [comment]
Yes, I wasn't until I saw the `create_network_alias()` function in the `EP_API class` that it became clear the search arguments had to be json-encoded and supplied in the "body" array element of the 2nd parameter. So even a short paragraph and a few examples would save an awful lot of head-scratching and code-diving for anyone else trying to figure out how to use `ep_remote_request()`. 

Other than  that, I have had great success using ElasticPress in a migration project where I was tasked with replacing the FantasticElastic plugin following a big change from ElasticSearch v1.5 to v6.2.2.

**Comment by daveboulden** [comment]
Hi Oscar,

It’s been a big learning curve getting up to speed with ElasticSearch alongside trying to figure out how to get deeper access to ElasticSearch via the existing API and connection within ElasticPress.

I have been working on a WordPress migration from AWS to Azure following a company acquisition by one of our customers. The newly acquired company’s website was still using ElasticSearch v1.5 with a heavily extended v3.2 FantasticElastic plugin, meaning I’ve had quite a task on my hands to migrate that all to ElasticSearch v6.2.2 and ElasticPress v2.4.2 including configurable weightings by field and custom post-type along with the need to offer configurable synonyms for the main search index … unfortunately for me, I also extended ElasticPress to provide custom post-type aggregates and faceting all before the v2.5 release of ElasticPress… still, I’ve leant a lot by tackling it!

Many thanks,
Dave.


--

Dave Boulden – Director
DA Media Limited

Tel:      01795 559456
Email: dave@da-media.co.uk<mailto:dave@da-media.co.uk>
Web:   http://www.da-media.co.uk/


The Information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. If you are not the intended recipient of this message, please do not read, copy, use or disclose this communication but notify the sender immediately. It should be noted that any review, retransmission, dissemination or other use of, or taking action in reliance upon this information, by persons or entities other than the intended recipient is prohibited. Any views or opinions are solely those of the author and do not necessarily represent those of DA Media Limited. DA Media Limited is registered in England and Wales, No: 04283345

**Comment by oscarssanchez** [comment]
@daveboulden Glad to hear ElasticPress has helped you. I'll try to come up with a PR to better document this.
