### ISSUE TITLE
No content return

### ISSUE THREAD

**Issue by aure-itconsultis** [10up/ElasticPress#1109]
Hello,

I need your help to find how to setup the plugin with my multi-site project.

- **Have you searched for similar issues before submitting this one?**
Yes, I can't find a similar issue.

- **Is this a bug, question or feature request?**
I think it's a question.

- **Describe the issue you encountered:**
I got no return from the WP_Query when I enable the ElasticPress plugin.

- **Current WordPress version:**
The latest one.

- **Current ElasticPress version:**
The latest one.

- **Current Elasticsearch version:**
Version 6.2.0.

- **Where do you host your Elasticsearch server:**
On my own server.

- **Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):**
Here is the list : ACF / Gravity Form / WPML / Yoast SEO.

**What I did ?**

- Install ElasticSearch on the server.
- Install ElasticSearch plugin for documents.
- Create a custom endpoint to do some search (`wp-json/itc/v2/search/mykeyword`).
- Install ElasticPress plugin.
- Enable the ElasticPress plugin on the network.
- Enable settings and synchronise the content.

**What I see**

- The custom endpoint is working fine with WP_Query and without ElasticPress plugin.
- During synchronisation, I got no error.
- I try to use this `wp elasticpress index --setup`, no error and it doesn't return content.

Here is the search code : 

```
$search_result          = new WP_Query(array(
       'ep_integrate'   => true,
        's' => $search,
        'post_type' => 'any'
        'posts_per_page' => 5,
        'sites' => 'current',
        'paged' => $paged
));
```

And to be sure that is not my code, I try to use this one too but it return nothing with ElasticPress : 

```
$search_result =        new WP_Query( array(
              'ep_integrate'   => true,
              'post_type'      => 'post',
              'posts_per_page' => 20,
            ));
```

Do you have an idea ?

Thanks !

**Comment by allan23** [comment]
Hi @aure-itconsultis, have you tried using the `--network-wide` parameter in WP CLI so that all sites are getting indexed?

**Comment by aure-itconsultis** [comment]
Thanks @allan23, I think it's good now, I will continue to work on my REST custom endpoint.
