### ISSUE TITLE
X-ElasticPress-Search

### ISSUE THREAD

**Issue by schrapel** [10up/ElasticPress#1110]
Have you searched for similar issues before submitting this one? `Yes`

Is this a bug, question or feature request? `Bug/Feature request`

Describe the issue you encountered:

Current WordPress version:
4.7

Current ElasticPress version:
2.5.2

Current Elasticsearch version:
6.2.2

Where do you host your Elasticsearch server:
AWS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): Proprietary 

Steps to reproduce:

1. Enable ElasticPress
2. Add a invalid host
3. Go to `?s=test`

It will say `X-ElasticPress-Search: true` as a header even though it is not being used. 

The simple solution seems to check `ep_elasticsearch_can_connect` and `ep_get_index_status` before adding the error. But this creates an additionnal overhead in api calls which I don't really like. 

I don't have a solution that's why I opened the issue but I am happy to work on one after a discussion. I don't feel like the current header adds any benefit.

**Comment by oscarssanchez** [comment]
Hi @schrapel  and thank you for taking the time to raise this issue! 

I can confirm i get the same result with the steps provided above. I'll CC @tlovett1 , he can probably provide a much richer discussion than I.

**Comment by tlovett1** [comment]
Hey @schrapel, yep you're right.

We aren't checking if the connection is valid before querying ES. This is of course to save a request.

I don't think this approach is wrong. Maybe we should be caching a bad request for a few minutes before retrying. Although I can see that frustrating people as well.

Regarding the header, we could just send it later in the process - after a successful query is made.

Thoughts?

**Comment by allan23** [comment]
Hi @schrapel, we have not heard from you on this for nearly a month, we are closing this issue.
