### ISSUE TITLE
FYK – tax_query and meta_query performance

### ISSUE THREAD

**Issue by pySilver** [10up/ElasticPress#1112]
FYK, if you are building anything relatively big with WP/WooCommerce you should pay attention to a filter cache which has great influence on query performance. 

Keeping this in mind there is absolutely no reason to use "must" instead of "filter" in a tax_queries or "meta_queries" because this kind of queries have limited filtering abilities that does not involve full-text search capabilities. 

Few changes should/could be made in `\EP_API::format_args`
Rationale:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html
https://www.ebayinc.com/stories/blogs/tech/elasticsearch-performance-tuning-practice-at-ebay/

**Comment by oscarssanchez** [comment]
@pySilver Thanks for submitting! 

PR's are always welcome if you would like to work on one.

**Comment by brandwaffle** [comment]
@pySilver this seems like a great idea. Any reason why we can't apply the same logic to the post_status and post_type.raw as well? I don't think there are any scenarios where having those contribute to the score would be the desired outcome.

We're working towards a rewrite of some internals on the plugin, so I think this makes sense to rework in tandem with that.

**Comment by pySilver** [comment]
@oscarssanchez I'm sorry (typical excuse, yeah) – im a little bit out of time to make a proper PR. All I have done is just replaced `must` with `filter` and tested, so nothing got broken.

@brandwaffle sure, this is what we are doing.
