### ISSUE TITLE
Multisite 4.7.11 display issue with posts and pages after plugin activation, plugin otherwise working fine.

### ISSUE THREAD

**Issue by willhoy2** [10up/ElasticPress#1114]
Have you searched for similar issues before submitting this one?
Yes, but with minimal luck in finding an answer.

Is this a bug, question or feature request?
A bug so far as i know.

Describe the issue you encountered:
Whilst the plugin appears to work correctly and searching is working fine, when activated, the dashboard page and post pages display content across the multisite from authors that do not have access to said sites, and authorised authors content goes awol.
The screen shot shows that even as super-admin i am unable to access or edit greyed out posts, and they seem to have collected strange titles...
I will assume something is being collected from the database incorrectly, or conflicting with an existing Function i have in place. 

Current WordPress version:
4.7.11 (upgraded from 4.6.12 where same problem occurred, updated to compatibility requirement of elasticpress)

Current ElasticPress version:
Version 2.5.2

Current Elasticsearch version:
Version 6.3.0

Where do you host your Elasticsearch server:
Azure - PHP Version: 5.6.36-1+ubuntu14.04.1+deb.sury.org+1

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Seeing as you asked, but i have disabled every last one, with the problem still occurring... (For those of you who think OMG!, it's all about the ram, and site loads in 160ms with even all this going on..) 
 - 360° Panoramic Viewer v1.3 by Liviu Cerchez (Inactive)
 - Add Existing Users v1.2.1 by WPMUDEV (Active network-wide)
 - Addon Library v1.3.73 by Unite CMS (Active)
 - Admin Columns v3.2.3 by AdminColumns.com (Active network-wide)
 - Admin Menu Editor v1.8.4 by Janis Elsts (Inactive)
 - Advanced Database Cleaner v2.0.0 by Younes JFR. (Active network-wide)
 - Advanced iFrame Pro v7.5.3 by Michael Dempfle (Active)
 - All In One Addons for WPBakery Page Builder (formerly Visual Composer) v3.5.1 by Sike (Active network-wide)
 - Apex Notification Bar v1.0.0 by AccessPress Themes (Inactive)
 - Astero WordPress Weather Plugin v1.3.1 by ArchTheme (Inactive)
 - Async JavaScript v2.18.06.13 by Frank Goossens (futtta) (Active network-wide)
 - Auto Albums - Multi Level Responsive Grid v1.1 by David Blanco (Inactive)
 - Awesome Flickr Gallery v3.5.6 by Ronak Gandhi (Inactive)
 - Better Plugin Compatibility Control v4.9.5 by Oliver Schlöbe (Active network-wide)
 - Better Search Replace v1.3.2 by Delicious Brains (Active network-wide)
 - Better WordPress Google XML Sitemaps v1.4.1 by Khang Minh (Active network-wide)
 - Blog Designer PRO v2.2 by Solwin Infotech (Inactive)
 - Blog Manager v1.24 by OTWthemes.com (Inactive)
 - Blogs Directory v1.2.0.4 by WPMUDEV (Inactive)
 - Buttons X v1.9.62 by Gautam Thapar (Inactive)
 - Classifieds WP v1.1 by classifiedswp (Active)
 - ClientEngage UberChat for WordPress v2.2.1 by ClientEngage (Inactive)
 - Cloner v1.7.7 by WPMU DEV (Active network-wide)
 - Composium - Visual Composer Extensions Addon v5.2.8 by Tekanewa Scripts by Kraut Coding (Inactive)
 - Contact Form 7 v4.7 by Takayuki Miyoshi (Inactive)
 - Cool Timeline Pro v2.3 by Cool Timeline Team (Inactive)
 - CSSJockey Unlimited Pop-ups v1.4.3 by Mohit Aneja (CSSJockey) (Inactive)
 - Custom Google Search v1.2.3 by WPMU DEV (Inactive)
 - Custom Post Templates v1.5 by Simon Wheatley (Inactive)
 - Custom Sidebars Pro v3.1.6 by WPMU DEV (Inactive)
 - Cyber Fox Christmasify! v1.2.1 by Cyber Fox (Inactive)
 - Debug Bar ElasticPress v1.3 by 10up (Active network-wide)
 - Default featured image v1.6.1 by Jan Willem Oostendorp (Active)
 - dflip v1.3.3 by Deepak Ghimire (Inactive)
 - DHVC Form v1.4.8 by Sitesao (Inactive)
 - Directories v1.1.15 by SabaiApps (Inactive)
 - Directories - Frontend v1.1.15 by SabaiApps (Inactive)
 - Directories - Payments v1.1.15 by SabaiApps (Inactive)
 - Directories - Reviews v1.1.15 by SabaiApps (Inactive)
 - Directories Pro v1.1.15 by SabaiApps (Inactive)
 - Disable Comments v1.7.1 by Samir Shah (Active network-wide)
 - Display Posts Shortcode v2.9.0 by Bill Erickson (Active network-wide)
 - Duplicate Page v2.7 by mndpsingh287 (Active network-wide)
 - Duplicator Pro v3.7.4 by Snap Creek (Active network-wide)
 - Easy Tables (vc) v1.0.9 by WPBakery (Active network-wide)
 - Easy Updates Manager v7.0.3 by Easy Updates Manager Team (Active network-wide)
 - Easy WP SMTP v1.3.6 by wpecommerce, alexanderfoxc (Inactive)
 - ElasticPress v2.5.2 by Taylor Lovett, Matt Gross, Aaron Holbrook, 10up (Active network-wide)
 - Email Address Encoder v1.0.7 by Till Krüss (Active network-wide)
 - Email Log v2.2.5 by Sudar (Inactive)
 - Embed Any Document Plus v2.0 by Awsm Innovations (Active network-wide)
 - Error Log Viewer by BestWebSoft v1.0.7 by BestWebSoft (Inactive)
 - Everest Gallery v1.0.2 by AccessPress Themes (Inactive)
 - EWWW Image Optimizer v4.2.3 by Shane Bishop (Active network-wide)
 - Fast Media Gallery - Visual Composer Addon v1.0 by Ad-theme.com (Active network-wide)
 - Feed Them Social (Facebook, Instagram, Twitter, etc) v2.4.6 by SlickRemix (Inactive)
 - Final Tiles Grid Gallery v3.3.4 by Green Tree Labs (Inactive)
 - Final Tiles Grid Gallery (Envato) v3.3.39 by Green Tree Labs (Inactive)
 - Fortuna Portfolio CPT v1.0 by blueowlcreative (Inactive)
 - GeoDirectory v1.6.28 by GeoDirectory (Inactive)
 - GeoDirectory Advance Search Filters v1.4.0 by GeoDirectory (Inactive)
 - GeoDirectory Ajax Duplicate Alert v1.1.5 by GeoDirectory (Inactive)
 - GeoDirectory Claim Manager v1.2.6 by GeoDirectory (Inactive)
 - GeoDirectory Custom Google Maps v1.0.7 by GeoDirectory (Inactive)
 - GeoDirectory Custom Post Types v1.2.8 by GeoDirectory (Inactive)
 - GeoDirectory Franchise Manager v1.0.0 by GeoDirectory (Inactive)
 - GeoDirectory Location Manager v1.4.7 by GeoDirectory (Inactive)
 - GeoDirectory Marker Cluster v1.2.6 by GeoDirectory (Inactive)
 - GeoDirectory Payment Manager v1.4.0 by GeoDirectory (Inactive)
 - GeoDirectory Re-Captcha v1.0.9 by GeoDirectory (Inactive)
 - GeoDirectory Review Rating Manager v1.3.1 by GeoDirectory (Inactive)
 - GeoDirectory Social Importer v1.2.0 by GeoDirectory (Inactive)
 - Google Analytics for WordPress by MonsterInsights v7.0.9 by MonsterInsights (Active network-wide)
 - Google Website Translator v1.4 by Prisna (Inactive)
 - Gravity Forms v2.2.3.16 by rocketgenius (Active network-wide)
 - Gravity Forms Polls Add-On v3.0 by Rocketgenius (Active network-wide)
 - Gravity Forms Quiz Add-On v3.0 by Rocketgenius (Active network-wide)
 - Gravity Forms Survey Add-On v3.0 by Rocketgenius (Active network-wide)
 - Gravity Forms User Registration Add-On v3.7.6 by rocketgenius (Active network-wide)
 - Health Check & Troubleshooting v1.2.1 by The WordPress.org community (Inactive)
 - Hotel Listing v1.1.9 by e-plugin (Inactive)
 - HTML Email Templates v2.0.6 by WPMU DEV (Active network-wide)
 - Icon Box for WPBakery Page Builder v1.5.1 by Brainstorm Force (Active)
 - Institutions Directory v1.1.8 by e-plugin (Inactive)
 - jQuery Updater v3.3.1 by Ramoonus (Active network-wide)
 - Justified Gallery v1.3.1 by Damian Góra (Active network-wide)
 - LearnDash LMS v2.0.6.6 by LearnDash (Inactive)
 - Loco Translate v2.1.4 by Tim Whitlock (Inactive)
 - Maintenance Pro v3.2 by fruitfulcode (Inactive)
 - Map List Pro v3.12.5 by SmartRedFox (Active)
 - Massive Addons for WPBakery Page Builder v2.3.2 by MassivePixelCreation (Inactive)
 - Memphis Documents Library v3.9.5 by Ian Howatson (Active)
 - Moderation v1.0.9 by WPMU DEV (Active network-wide)
 - Multi-Domains for Multisite v1.3.4.5 by WPMU DEV (Active network-wide)
 - Multisite Cloner v0.2.2.1 by Manuel Razzari, Patricio Tarantino (Active network-wide)
 - Multisite Content Copier v1.5.3 by WPMU DEV (Inactive)
 - Multisite Directory v0.2.3 by Meitar Moscovitz <meitar@maymay.net> (Inactive)
 - Multisite Enhancements v1.4.3 by Frank Bültge (Active network-wide)
 - Multisite Robots.txt Manager | MS Robots.txt v1.0.12 by tribalNerd, Chris Winters (Inactive)
 - Multisite Theme Manager v1.1.6 by WPMU DEV (Active network-wide)
 - Multisite User Management v1.1 by Brent Shepherd (Active network-wide)
 - Multisite Widgets Context v1.1.2 by nicholas_io (Active network-wide)
 - My Custom Functions v4.24 by Space X-Chimp (Active)
 - My Custom Styles v4.24 by Space X-Chimp (Active network-wide)
 - MyMail - Email Newsletter Plugin for WordPress v2.1.31 by revaxarts.com (Inactive)
 - My WP Mega Menu v1.1.10 by MyThemeShop (Inactive)
 - Nav Menu Roles v1.9.2 by Kathy Darling (Active network-wide)
 - Network Latest Posts v3.7.1 by Jose Luis SAYAGO (Active network-wide)
 - Newscodes v2.1.1 by Mihajlovic Nenad (Inactive)
 - Optimize Database after Deleting Revisions v4.6.2 by CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands (Inactive)
 - Parallax & Video Backgrounds for Visual Composer v1.5.6 by Brainstorm Force (Inactive)
 - Peter's Login Redirect v2.9.1 by Peter Keung (Inactive)
 - Postie v1.9.24 by Wayne Allen (Inactive)
 - Post Indexer v3.0.6.4 by WPMU DEV (Inactive)
 - PressApps Accordion Faq v2.1.0 by PressApps (Active)
 - Pretty Plugins v1.5.4 by WPMU DEV (Active network-wide)
 - Pro Bulk Watermark Plugin for WordPress v2.0 by AA-Team (Inactive)
 - Progress Map by CodeSpacing v3.9.2 by Hicham Radi (CodeSpacing) (Inactive)
 - Pro Sites v3.5.9.3 by WPMU DEV (Active network-wide)
 - Real 3D Flipbook v3.4.9 by creativeinteractivemedia (Inactive)
 - Real Estate Pro v1.3.9 by e-plugin (Inactive)
 - Really Simple CAPTCHA v2.0.1 by Takayuki Miyoshi (Inactive)
 - Redirection v3.4 by John Godley (Active)
 - Redis Object Cache v1.3.8 by Till Krüss (Active network-wide)
 - Remove HTTP v2.1.1 by Fact Maven (Active network-wide)
 - Reports v1.0.8 by WPMU DEV (Active network-wide)
 - Restrict Content v2.2.3 by Pippin Williamson (Inactive)
 - Row Separators v1.0 by Gambit Technologies (Inactive)
 - Scheduled Content v1.2.2 by WPMU DEV (Active network-wide)
 - SecuPress Pro — WordPress Security v1.2.5.1 by WP Media (Inactive)
 - Server Status v1.2.10 by LittleBizzy (Active)
 - Set Password on Multisite Blog Creation v1.1.2.3 by WPMU DEV (Active network-wide)
 - Signup TOS v1.3.5 by WPMU DEV (Active network-wide)
 - Simple Share Buttons Adder v7.4.18 by Simple Share Buttons (Inactive)
 - Site Categories v1.0.9.4 by WPMU DEV (Active network-wide)
 - Site Generator Replacement v1.0.2.2 by S H Mohanjith (Incsub), Andrew Billits (Incsub) (Active network-wide)
 - Sleek Announce v1.0 by Josh Sears (Inactive)
 - Sleek Facebook Slider v1.0 by Sleek Plugins (Inactive)
 - Slick Menu v1.0.9.8 by XplodedThemes (Active)
 - Slick Menu Duplicate v1.0.3 by XplodedThemes (Inactive)
 - Slick Menu Import / Export v1.0.3 by XplodedThemes (Inactive)
 - Slick Menu Social Networks v1.0.5 by XplodedThemes (Active)
 - Smart Slider 3 Pro v3.3.6 by Nextend (Inactive)
 - Snapshot Pro v3.1.9 by WPMU DEV (Inactive)
 - Social Auto Poster v2.8.2 by WPWeb (Active)
 - SSL Insecure Content Fixer v2.7.0 by WebAware (Inactive)
 - Stop Visual Composer Activation Nag v2016.04.26 by khromov (Active network-wide)
 - Sugar FAQs for WordPress v1.3.1 by Pippin Williamson (Inactive)
 - SuperCarousel v3.1 by Taraprasad Swain (Inactive)
 - Support System v2.1.9.4 by WPMU DEV (Active network-wide)
 - Team Members PRO v4.1.1 by WP Darko (Inactive)
 - The Events Calendar v4.1.4 by Modern Tribe, Inc. (Active)
 - The Events Calendar: Community Events v4.0.2 by Modern Tribe, Inc. (Active)
 - The Events Calendar: Filter Bar v4.0.2 by Modern Tribe, Inc. (Inactive)
 - The Events Calendar PRO v4.1.3 by Modern Tribe, Inc. (Active)
 - TinyMCE Advanced v4.3.10.1 by Andrew Ozz (Inactive)
 - Ultimate Addons for WPBakery Page Builder v3.16.24 by Brainstorm Force (Active)
 - Ultimate LinkedIn Integration v1.1.1 by The Thought Engineer (Inactive)
 - Ultimate Responsive Image Slider v3.2.0 by Weblizar (Inactive)
 - Ultimate Tweaker v1.4.2 by Amino-Studio <support@amino-studio.com> (Inactive)
 - Unlimited Addons for WPBakery Page Builder v1.0.37 by Unite CMS (Inactive)
 - UpdraftPlus - Backup/Restore v2.14.12.24 by UpdraftPlus.Com, DavidAnderson (Active network-wide)
 - Upload Media by Zip v0.9.1 by Kailey Lampert (Inactive)
 - User Role Editor Pro v4.47.2 by Vladimir Garagulia (Active network-wide)
 - VC Animated Gradient Background v1.1 by Boom-Apps (Inactive)
 - VC Particles 3D Background v1.1 by Boom-Apps (Inactive)
 - VC Row Background Particles All in One v1.5 by wptpnet (Active)
 - VC Sine Background v1.0 by Boom-Apps (Inactive)
 - VC Smokey Background v1.2 by Boom-Apps (Inactive)
 - VC Super Bundle v1.2.2 by Gambit Technologies, Inc (Inactive)
 - VC Violet Background v1.1.1 by Boom-Apps (Inactive)
 - VC Waves Background v1.1 by Boom-Apps (Inactive)
 - Visual Composer Addons Mega Pack v1.2 by Ad-theme.com (Inactive)
 - Visual Composer Background Sliders v1.2 by SB Themes (Inactive)
 - Visual Composer Image Hover Effect v1.0 by zafar ullah joiya (Inactive)
 - Visual Composer One Page Builder v1.4 by Ad-theme.com (Inactive)
 - Visual Composer Page Intro v1.1 by AD-THEME (Inactive)
 - W3 Total Cache v0.9.7 by Frederick Townes (Active network-wide)
 - Watermark v0.3.4 by Alexis Blondin (Inactive)
 - Wordpress Automatic Plugin v3.36.0 by ValvePress (Inactive)
 - WordPress GDPR v1.5.14 by DB-Dzine (Inactive)
 - WordPress Importer v0.6.4 by wordpressdotorg (Inactive)
 - Wordpress Mega Pack for Visual Composer v1.0 by Ad-theme.com (Inactive)
 - WordPress Navigation Menu Links v1.0.4 by Agbonghama Collins (Inactive)
 - WordPress Version Info v1.1.3 by alpipego (Inactive)
 - WP Author Box Pro v2.0.7 by phpbits (Inactive)
 - WPBakery Page Builder v5.5.1 by Michael M - WPBakery.com (Active network-wide)
 - WP CleanFix v5.3.5 by Giovambattista Fazioli (Inactive)
 - WP Crontrol v1.6.2 by John Blackbourn & contributors (Active network-wide)
 - WP Domain Checker v4.2.1 by Asdqwe Dev (Inactive)
 - WP Flat Tour Builder v3.258 by Biscay Charly (loopus) (Inactive)
 - WP Google Map Pro v5.0.5 by flippercode (Inactive)
 - WP Instagram Widget v2.0.3 by Scott Evans (Inactive)
 - WP Mail SMTP v1.3.3 by WPForms (Active network-wide)
 - WP Mega Menu Pro v1.0.9 by AccessPress Themes (Inactive)
 - WPMU DEV Dashboard v4.5.2 by WPMU DEV (Active network-wide)
 - WP Multi-Network v1.8.1 by johnjamesjacoby, ddean, BrianLayman, rmccue (Active network-wide)
 - WP Notification Bar Pro By MyThemeShop v1.1.14 by MyThemeShop (Inactive)
 - WP Post Modules v1.9.10 by SaurabhSharma (Inactive)
 - WP ProGrid : Ajax Post/Custom Post Display+Filter v2.4 by Proword (Inactive)
 - WP Real Media Library v3.4.8 by Matthias Günter (Active network-wide)
 - WP Security Audit Log v3.2.2.1 by WP White Security (Active network-wide)
 - WP Snow Effect v1.1.8 by WPManiax (Inactive)
 - WP Statistics v12.3.6.4 by Verona Labs (Inactive)
 - WP Translate v5.0.2 by HahnCreativeGroup (Active network-wide)
 - Youtube Videos To Wordpress Posts v4.0.6 by Karim Lamghari & Younes Rafie (Inactive)

Steps to reproduce:

1. Activate plugin in same environment, multiste of same spec with over 160 sites. 
2. Problem appears from cross blog users, and super-admin unable to edit or view postss in posts page, per screenshot.

Screenshots, if needed:
![untitled](https://user-images.githubusercontent.com/41865743/43366939-5f5a908c-9388-11e8-974c-f77307114011.png)

**Comment by willhoy2** [comment]
I also forgot to mention, the latest posts i had written have dissipated completely off the page (but show still in the front end), until i deactivate the plugin, and then everything returns to normal without search across site. As i do not use front end editing, this is a real pain. Any help appreciated guys, because this plugin is otherwise exactly what i need.

**Comment by allan23** [comment]
Hi @willhoy2,

Have you verified that the issue is not caused by a plugin as you have so many?

**Comment by willhoy2** [comment]
Yes, as stated,  "but i have disabled every last one, with the problem still occurring..." but thankyou for the thought....

**Comment by oscarssanchez** [comment]
Hi @willhoy2, can you test this out on a similar environment, without installing any plugins but ElasticPress? 

Given that there's  so many plugins and we don't know what they did before, we can't really know what's happening here. Reproducing successfully this issue on a fresh install so we can discard that option would be a first step to help you better.

**Comment by allan23** [comment]
Hi @willhoy2 ,

I am closing this issue since we did not have a response from you.
