### ISSUE TITLE
Enabled SSL to our site data is not getting sync with elastic cloud

### ISSUE THREAD

**Issue by yshanthipriya** [10up/ElasticPress#1115]
Hi,

We enabled SSL to our web site after that we are unable to sync data with elastic cloud.

Have you searched for similar issues before submitting this one? 
Yes

Is this a bug, question or feature request?
Bug

Describe the issue you encountered: Unable to sync data to elastic cloud

Current WordPress version: 4.9.6

Current ElasticPress version: 2.5.2

Current Elasticsearch version: v5.6.10

Where do you host your Elasticsearch server: elastic cloud

**Comment by brandwaffle** [comment]
@yshanthipriya Unfortunately, our ability to troubleshoot connectivity issues on other hosts is somewhat limited. 

Your best bet is to install the Debug Bar and Debug Bar ElasticPress plugins and then report back here with the results of the debug output. You might also be able to get more information from Elastic.co.
