### ISSUE TITLE
Meta query NOT IN with "match" instead of "terms"

### ISSUE THREAD

**Issue by victor-gabou** [10up/ElasticPress#1116]
Have you searched for similar issues before submitting this one?
**Yes**

Is this a bug, question or feature request?
**Question or feature request**

Describe the issue you encountered:
**I have a post_type with an ACF Pro field (type: Taxonomy, Appearance: Select) that I use to filter my results. On a certain page I need to exclude 2 taxonomies from my search, so I use the "NOT IN" compare value. But the way the data is stored on the database (so in Elasticsearch) do not allow me to find them, because the "NOT IN" use "terms" and in my case I would need to use "match"**

**For the moment I modify the php file directly, from**
```
case 'not in':
case '!=':
  if ( isset( $single_meta_query['value'] ) ) {
    $terms_obj = array(
      'bool' => array(
        'must_not' => array(
          array(
            'terms' => array(
              $meta_key_path => (array) $single_meta_query['value'],
            ),
          ),
        ),
      ),
    );
  }

  break;
```
**to :**
```
case 'not in':
  if ( isset( $single_meta_query['value'] ) ) {
    $terms_obj = array(
      'bool' => array(
        'must_not' => array(
          array(
            'match' => array(
              $meta_key_path => (array) $single_meta_query['value'],
            ),
          ),
        ),
      ),
    );
  }

  break;
case '!=':
  if ( isset( $single_meta_query['value'] ) ) {
    $terms_obj = array(
      'bool' => array(
        'must_not' => array(
          array(
            'terms' => array(
              $meta_key_path => (array) $single_meta_query['value'],
            ),
          ),
        ),
      ),
    );
  }

  break;
```
**It works as I need, but I don't really like to work on plugins file directly because of updates and so**

Current WordPress version:
**4.9.7**

Current ElasticPress version:
**2.5.2**

Current Elasticsearch version:
**6.2.2**

Where do you host your Elasticsearch server:
**On a personal server**

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
**ACF Pro, WPML and others, but not a bug so I don't think this matter to list all of them**

So, do you think there is an other way to do what I need without changing the plugin's files.
If not, could you add a way to have more control on the elasticsearch query (to achieve this for example)

Thanks for your plugin and your time!

Victor

**Comment by oscarssanchez** [comment]
Hi @victor-gabou ,

Have you tried using using the `ep_formatted_args` filter?

Another approach may be to create a taxonomy 'exclude_from_my_page' and go from there.
