### ISSUE TITLE
Plugin's taxonomy not being indexed with posts

### ISSUE THREAD

**Issue by stirrell** [10up/ElasticPress#1120]
Have you searched for similar issues before submitting this one?
Yes.

Is this a bug, question or feature request?
Question.

Describe the issue you encountered:
I have the plugin, Agora Middleware 2.x Authentication Plugin, installed and it registers a taxonomy using the following code:
```
$register_taxonomy_args = array(
			'hierarchical' => true,
			'labels' => array(
				'name' => _x( 'Pubcodes', 'taxonomy general name' ),
				'singular_name' => _x( 'Pubcode', 'taxonomy singular name' ),
				'search_items' =>  __( 'Search Pubcodes' ),
				'popular_items' => __( 'Popular Pubcodes' ),
				'all_items' => __( 'All Pubcodes' ),
				'parent_item' => null,
				'parent_item_colon' => null,
				'edit_item' => __( 'Edit Pubcode' ),
				'update_item' => __( 'Update Pubcode' ),
				'add_new_item' => __( 'Add New Pubcode' ),
				'new_item_name' => __( 'New Pubcode Name' ),
				'separate_items_with_commas' => __( 'Separate pubcodes with commas' ),
				'add_or_remove_items' => __( 'Add or remove pubcodes' ),
				'choose_from_most_used' => __( 'Choose from the most used pubcodes' )
			),
			'query_var' => true,
			'show_tagcloud' => false,
			'show_in_quick_edit' => true,
			'show_ui' => false
		);
		register_taxonomy( 'pubcode', $post_types ,$register_taxonomy_args );
```

When I search on this information, I get no results. I queried one of the posts with a term from the taxonomy set and verified that it does not include information for that taxonomy in Elasticsearch. I tried to set `publicly_queryable` to true and re-indexed but that did not help.

Current WordPress version:
4.9.8

Current ElasticPress version:
2.5.2

Current Elasticsearch version:
6.0.1

Where do you host your Elasticsearch server:
Amazon AWS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Advanced Custom Fields PRO, bbPress, Contact Form 7, Wordfence, Yoast.

Steps to reproduce:

1. Index posts using WP-CLI (`wp elasticsearch index --url=<site>`) - I tried indexing separately because I read some information about taxonomies and multi-sites not working without a bash shell workaround (https://github.com/10up/ElasticPress/issues/334) and thought this might be related.

Here is what the test record looks like in the database:
![image](https://user-images.githubusercontent.com/2236935/44073460-fd006570-9f61-11e8-80bb-8bdc7ca0c7e8.png)

I am just seeing `category` items being stored as part of the record in Elasticsearch. Any ideas, suggestions would be greatly appreciated. Thanks!

**Comment by oscarssanchez** [comment]
Hi @stirrell thanks for submitting your question,

Is Agora Middleware 2.x a public download we can access? That would be amazing to test out your question.

Thanks and have a nice day!

**Comment by stirrell** [comment]
Hello Oscar,

Thanks so much for the response. Unfortunately, I don't think that there is a public download for this plugin. I was unable to find one. That said, I have been digging into this and suspect that the issue is that the taxonomy defined by Agora Middleware is not getting called when indexing occurs. I ran the following WP CLI command to index just the product type attached to this taxonomy:

`wp elasticpress index --network-wide --nobulk --post-type="il_product"`

I can see that in `class-ep-api.php`, when `get_object_taxonomies` is called, that I am not getting the `pubcode` taxonomy in the returned values. So I suspect the issue is that the taxonomy is just not available to ElasticPress on index. Thanks again for your response.

**Comment by allan23** [comment]
Hi @stirrell,

This does sounds like the issue in #334 (when a post type or taxonomy is registered only for a certain site via a plugin or theme code).

Is the Agora Middleware plugin network activated?

**Comment by allan23** [comment]
Closing due to no response in 20 days.

**Comment by isaquemelo** [comment]
I'm having the same problem here. Did you manage to solve it @stirrell?

When the `get_object_taxonomies` is called during a WP-CLI command the custom taxonomies are not present. But, when I run the indexaxion from the plugin dashboard, they are all there. For example:

wp cli command (`wp elasticpress index --setup --show-bulk-errors --per-page=350`):
```
Array()
```
Now using the dashboard to index:

```
Array
(
    [tnc_tax_570369] => WP_Taxonomy Object
        (
            [name] => tnc_tax_570369
            [label] => Taxonomia de exemplo
            [labels] => [....]
            [description] => 
            [public] => 1
            [publicly_queryable] => 1
            [hierarchical] => 1
            [show_ui] => 
            [show_in_menu] => 
            [show_in_nav_menus] => 1
            [show_tagcloud] => 
            [show_in_quick_edit] => 
            [show_admin_column] => 
            [meta_box_cb] => post_categories_meta_box
            [meta_box_sanitize_cb] => taxonomy_meta_box_sanitize_cb_checkboxes
            [object_type] => Array
                (
                    [0] => tnc_col_570361_item
                )

            [cap] => stdClass Object
                (
                    [manage_terms] => manage_categories
                    [edit_terms] => manage_categories
                    [delete_terms] => manage_categories
                    [assign_terms] => edit_posts
                )

            [rewrite] => Array
                (
                    [with_front] => 1
                    [hierarchical] => 
                    [ep_mask] => 0
                    [slug] => taxonomia-de-exemplo
                )

            [query_var] => tnc_tax_570369
            [update_count_callback] => _update_generic_term_count
            [show_in_rest] => 
            [rest_base] => 
            [rest_controller_class] => 
            [default_term] => 
            [rest_controller] => 
            [_builtin] => 
        )

    [tnc_tax_135] => WP_Taxonomy Object
        (
            [name] => tnc_tax_135
            [label] => Estado
            [labels] => [...]
            [description] => 
            [public] => 1
            [publicly_queryable] => 1
            [hierarchical] => 1
            [show_ui] => 
            [show_in_menu] => 
            [show_in_nav_menus] => 1
            [show_tagcloud] => 
            [show_in_quick_edit] => 
            [show_admin_column] => 
            [meta_box_cb] => post_categories_meta_box
            [meta_box_sanitize_cb] => taxonomy_meta_box_sanitize_cb_checkboxes
            [object_type] => Array
                (
                    [0] => tnc_col_570361_item
                    [1] => tnc_col_6_item
                )

            [cap] => stdClass Object
                (
                    [manage_terms] => manage_categories
                    [edit_terms] => manage_categories
                    [delete_terms] => manage_categories
                    [assign_terms] => edit_posts
                )

            [rewrite] => Array
                (
                    [with_front] => 1
                    [hierarchical] => 
                    [ep_mask] => 0
                    [slug] => estado
                )

            [query_var] => tnc_tax_135
            [update_count_callback] => _update_generic_term_count
            [show_in_rest] => 
            [rest_base] => 
            [rest_controller_class] => 
            [default_term] => 
            [rest_controller] => 
            [_builtin] => 
        )

)
```

**Info:**
- Not a multisite
- The taxonomy is generated by another plugin (tainacan)
- The associated post-type (`get_object_taxonomies( **$post->post_type**, 'objects' )`) is a custom post type;

**Comment by stirrell** [comment]
I'm sorry, @isaquemelo. I honestly don't remember if I ever got this working. It was part of a project I was working on at a previous employer so I don't have access to the code anymore so I am not sure where it stands. Sorry I couldn't be any help!

**Comment by isaquemelo** [comment]
It's okay @stirrell, thank you so much for your time. 
I managed to solve the problem passing the param `--user=ID` to the wp-cli command. Now all private post-types / taxonomies are indexed correctly.
