### ISSUE TITLE
Search in Russian bad results

### ISSUE THREAD

**Issue by ijakparov** [10up/ElasticPress#1121]
I have WP site in Russian language, looks like search works very poor from the box, in fact it doesn't search phrases 3-4 words length and singe words if to change last letter (in russian it's normal). I tried to put next code into functions.php and resync elasticpress, but nothing change.

```php
function elasticpress_config_mapping( $mapping ) {


	$mapping['settings']['analysis']['filter']['russian_stop'] = array(
		'type' => 'stop',
		'stopwords' => '_russian_',
	);
	$mapping['settings']['analysis']['filter']['russian_stemmer'] = array(
		'type' => 'stemmer',
		'language' => 'russian',
	);
	$mapping['settings']['analysis']['analyzer']['russian']['tokenizer'] = 'standard';
	$mapping['settings']['analysis']['analyzer']['russian']['filter'] = array(
            "lowercase",
            "russian_stop",
            "russian_keywords",
            "russian_stemmer"
	);


	return $mapping;
}


add_filter( 'ep_config_mapping', 'elasticpress_config_mapping', 10, 1 );
```

**Comment by oscarssanchez** [comment]
Hi @ijakparov ,

Have you also tried using  the `ep_analyzer_language` filter ?

Also, setting mappings for post_content or post_title might help out with what you are trying to accomplish. Something like: 

`$mapping['mappings']['post']['properties']['post_content']['analyzer']` 

Thanks for raising your question and have a great day!

**Comment by oscarssanchez** [comment]
I'm closing this issue in the meantime @ijakparov  since we did not get response, feel free to reply and we can reopen it.
