### ISSUE TITLE
WP CLI  require_once(bin/wp-cli.php) error in Cloudways

### ISSUE THREAD

**Issue by robin-scott** [10up/ElasticPress#1128]
Have you searched for similar issues before submitting this one?

Yes

Is this a bug, question or feature request?

Yes :) - actually this may be a WP CLI issue. Just noting here for reference so there's a log when resolved.

Describe the issue you encountered:

WP CLI in Cloudways managed hosting - require_once(bin/wp-cli.php) - this is erroring.

Current WordPress version:

4.9.8

Current ElasticPress version:

2.6.0

Current Elasticsearch version:

Elasticsearch 5.4 

Where do you host your Elasticsearch server:

Same instance (127.0.0.1:9200)

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

Install in Cloudways setup. WP admin interface all working, WP CLI is producing this error:

`PHP Warning:  require_once(bin/wp-cli.php): failed to open stream: No such file or directory in [ROOT]/wp-content/plugins/elasticpress/elasticpress.php on line 69
Warning: require_once(bin/wp-cli.php): failed to open stream: No such file or directory in [ROOT]/wp-content/plugins/elasticpress/elasticpress.php on line 69
PHP Fatal error:  require_once(): Failed opening required 'bin/wp-cli.php' (include_path='phar:///usr/local/bin/wp/vendor/phpunit/php-token-stream:phar:///usr/local/bin/wp/vendor/phpunit/phpunit-mock-objects:phar:///usr/local/bin/wp/vendor/phpunit/php-code-coverage:phar:///usr/local/bin/wp/vendor/phpunit/phpunit:phar:///usr/local/bin/wp/vendor/symfony/yaml:.:/usr/share/php') in [ROOT]/wp-content/plugins/elasticpress/elasticpress.php on line 69
Fatal error: require_once(): Failed opening required 'bin/wp-cli.php' (include_path='phar:///usr/local/bin/wp/vendor/phpunit/php-token-stream:phar:///usr/local/bin/wp/vendor/phpunit/phpunit-mock-objects:phar:///usr/local/bin/wp/vendor/phpunit/php-code-coverage:phar:///usr/local/bin/wp/vendor/phpunit/phpunit:phar:///usr/local/bin/wp/vendor/symfony/yaml:.:/usr/share/php') in [ROOT]/wp-content/plugins/elasticpress/elasticpress.php on line 69`

I'll try to figure this out in another instance if its CLI or latest Elasticpress. I don't think this happened before though in previous version. I'll try to find it our side :)

**Comment by robin-scott** [comment]
Version 2.5.2 of ElasticPress does not create this error in same setup - not isolated root cause of this though.

**Comment by johnReeve** [comment]
I'm also seeing this on Pantheon's hosting, but I just started looking into it, too.

`Warning: require_once(bin/wp-cli.php): failed to open stream: No such file or directory in /srv/bindings/4df2f9a86368475f9514d2c3ed3e44db/code/wp-content/plugins/elasticpress/elasticpress.php on line 69
Fatal error: require_once(): Failed opening required 'bin/wp-cli.php' (include_path='phar:///opt/pantheon/wp-cli1/wp-cli.phar/vendor/phpunit/php-token-stream:phar:///opt/pantheon/wp-cli1/wp-cli.phar/vendor/phpunit/phpunit-mock-objects:phar:///opt/pantheon/wp-cli1/wp-cli.phar/vendor/phpunit/php-code-coverage:phar:///opt/pantheon/wp-cli1/wp-cli.phar/vendor/phpunit/phpunit:phar:///opt/pantheon/wp-cli1/wp-cli.phar/vendor/symfony/yaml:.:/usr/share/pear:/usr/share/php:/srv/bindings/4df2f9a86368475f9514d2c3ed3e44db/code/wp-content/mu-plugins/vendor/phpseclib1.0.11') in /srv/bindings/4df2f9a86368475f9514d2c3ed3e44db/code/wp-content/plugins/elasticpress/elasticpress.php on line 69`

**Comment by johnReeve** [comment]
I've installed it from the WP plugin repo; if I look at that repo, I am not seeing the ./bin directory that I see in the repo here on github:

https://plugins.trac.wordpress.org/browser/elasticpress/trunk

I dunno if that is the reason behind the issue, but that's what my first guess would be.  For the moment, I'm not in hurry, so I will just wait and see if the wp plugin repo version gets updated.

**Comment by robin-scott** [comment]
Thanks @johnReeve - I think you got this one found. The /bin directory is not present in the WP repo copy of 2.6.0 - but it is in the repo 2.5.2 copy (which works). This will want fixing there.

**Comment by johnReeve** [comment]
It might be obvious, but I commented out the `require_once( 'bin/wp-cli.php' );` on my local install so I could do some unrelated work, and that fixed it in the short term so I can at least use WP-CLI.

**Comment by robin-scott** [comment]
Yeah pulling down latest release from here works too - that directory is missing in the WP repo is all.

**Comment by robin-scott** [comment]
2.6.0 from here will work: https://github.com/10up/ElasticPress/releases

**Comment by allan23** [comment]
@robin-scott and @johnReeve,

Thank you for reporting this issue. We have pushed a minor update to the WP.org repository that includes the missing file.

Apologies for any headaches this may have caused.

**Comment by johnReeve** [comment]
No worries... thanks for the super-duper useful software.
