### ISSUE TITLE
Facet feature hijacks main queries that use non-indexable post types and status

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/ElasticPress#1129]
**Have you searched for similar issues before submitting this one?**
Yes

**Is this a bug, question or feature request?**
Bug

**Describe the issue you encountered:**
When the "Facet" feature is enabled, going to rewrite paths added by other plugins / libraries (such as [WP-Router](https://github.com/jbrinley/WP-Router)) results in a 404 because the post type is not actually indexed by ElasticPress. The `ep_facets_is_facetable()` function should at the very least check if the post types in the `WP_Query` are covered with `ep_get_indexable_post_types()` and the post status(es) are covered with `ep_get_indexable_post_status()`.

**Current WordPress version:**
4.9.8

**Current ElasticPress version:**
2.6.1

**Current Elasticsearch version:**
Not applicable

**Where do you host your Elasticsearch server:**
Searchly

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):**
* The Events Calendar
* The Events Calendar: Community Events
* The Events Calendar: Elasticsearch Integration

**Steps to reproduce:**

1. Setup ElasticPress
2. Enable Facet feature
3. Go to a URL path that was covered by a custom WP_Query+rewrite path (such as the [Community Events premium plugin](https://theeventscalendar.com/product/wordpress-community-events/) for [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/) which uses [WP-Router](https://github.com/jbrinley/WP-Router))
4. See that the URL returns a 404 response, because the main WP_Query now has `'ep_integrate' => true` and `'ep_facet' => true` mistakenly set on it by the Facet feature in ElasticPress

**Comment by oscarssanchez** [comment]
Hi @sc0ttkclark, thank you for taking the time to raise the issue.

Do you know if there is a public plugin we could use to test this out, and if we find the same problem, work and test a solution? 

Thank you very much and have a nice day

**Comment by sc0ttkclark** [comment]
Best way to test this is to have a custom query handler, so on pre_get_posts you would add an action that would setup the WP_Query arguments for a specific page given a certain circumstance like for [WP-Router](https://github.com/jbrinley/WP-Router/blob/master/WP_Router_Page.class.php#L105).

At that point, it's very easy to further confirm the problem -- just set the post type and/or post status to any that are not indexable by ElasticPress and you'll see the Facet feature take over for those queries.

I don't think you even need any other plugin to confirm it, here's some example code:

```php
add_action( 'pre_get_posts', 'my_pre_get_posts' );

function my_pre_get_posts( WP_Query $query ) {

	$my_custom_var = $query->get( 'my_custom_var' );

	if ( ! empty( $my_custom_var ) ) {
		$query->set( 'post_type', 'non_ep_post_type' );
		$query->set( 'post_status', 'non_ep_post_status' );

		// If we want to fake a singular, we could do the following.
		$query->set( 'p', 1234 );

		// Some other config tweaks to treat this as a single post.
		$query->is_single = true;
		$query->is_singular = true;
		$query->is_404 = false;
		$query->is_home = false;
	}

}
```

Ultimately, the `ep_facets_is_facetable()` needs to first check if the post status/type(s) in the current query it's about to integrate with -- are indexable by EP or not. In the example code above, it is *not* indexable by EP, thus totally breaks the query from returning the expected dataset (from the DB, not from EP).

**Comment by sc0ttkclark** [comment]
Please also note, the post type in WP-Router is supposed to be excluded from search: https://github.com/jbrinley/WP-Router/blob/master/WP_Router_Page.class.php#L18

So by definition, it should not be in the default indexable post types for EP.
