### ISSUE TITLE
ES Language Analyzers

### ISSUE THREAD

**Issue by george2seven** [10up/ElasticPress#1132]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question (maybe feature request :) )

Describe the issue you encountered:
When ElasticPress creates the index on the es host what analyzer is specifying?
Can we use another analyzer if is needed? 
related link: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/analysis-lang-analyzer.html

Current WordPress version:

Current ElasticPress version:

Current Elasticsearch version:
6.2

Where do you host your Elasticsearch server:
aws

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by brandwaffle** [comment]
@george2seven Yes! You can specify the language analyzer by overriding the default in this filter:
https://github.com/10up/ElasticPress/blob/a24d36ad4ea02ca971e5192b7160b806a7947411/includes/mappings/5-2.php#L23

**Comment by george2seven** [comment]
Thanks @brandwaffle !!

**Comment by george2seven** [comment]
Apologies for re-opening this issue but although I am able to add the language analyzer I want there are certain filters that come with that analyzer and I am not sure whether or not to override the default ones or add the ones I want.

basically my question is how do I take the 5-2.php file and adjust it to fit this scenario:

{
  "settings": {
    "analysis": {
      "filter": {
        "greek_stop": {
          "type":       "stop",
          "stopwords":  "_greek_" 
        },
        "greek_lowercase": {
          "type":       "lowercase",
          "language":   "greek"
        },
        "greek_keywords": {
          "type":       "keyword_marker",
          "keywords":   ["παράδειγμα"] 
        },
        "greek_stemmer": {
          "type":       "stemmer",
          "language":   "greek"
        }
      },
      "analyzer": {
        "rebuilt_greek": {
          "tokenizer":  "standard",
          "filter": [
            "greek_lowercase",
            "greek_stop",
            "greek_keywords",
            "greek_stemmer"
          ]
        }
      }
    }
  }
}

Thank you very much

**Comment by george2seven** [comment]
...of course this analyzer will be used only for the post title and the post text and so it makes it more difficult to understand how to configure the mapping without breaking functionality for the rest of the plug-in. thanks

**Comment by scooterlord** [comment]
Hello again and sorry for reopening this as well :)

When you use a different language analyzer what happens with the ‘default’ English language?
