### ISSUE TITLE
Sorting WooCommerce category by price not returning from Elastic

### ISSUE THREAD

**Issue by martian77** [10up/ElasticPress#1134]
**Have you searched for similar issues before submitting this one?**
Yes

**Is this a bug, question or feature request?**
Bug

**Describe the issue you encountered:**
I'm trying to use the WooCommerce Category sort by price functionality, accessible via the customiser in the latest versions of WooCommerce. The products display in the correct order, but when I look in debug-elastic it says Elastic is returning a 400 error, no mapping found for price. If I add some extra code in to override this and make it order by meta.price.double then the Elastic response is what I would expect. 

**Current WordPress version:**
4.9.8

**Current ElasticPress version:**
2.6.1

**Current Elasticsearch version:**
5.2.2

Where do you host your Elasticsearch server:
Amazon

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
- WooCommerce
- Debug bar
- Debug bar elasticpress

Steps to reproduce:

1. Set up a WooCommerce product category with archive.
2. In the Customiser, under WooCommerce, Product Catalogue, Default product sorting, select either price in ascending or descending order. 
3. View the category archive.
4. Check the debug bar elasticpress for the Query Response code and for the result. 

Screenshots, if needed:

**Comment by brandwaffle** [comment]
@martian77 thanks for the report! We're looking into this and will update the issue as soon as we have some more info.

**Comment by oscarssanchez** [comment]
Hi @martian77 , I can confirm i get a 400 error, I'll try to come up with a solution for this. Thanks for reporting it !

**Comment by oscarssanchez** [comment]
Just updating @martian77 , made a PR for this in case you want to try it in the meantime :)
