### ISSUE TITLE
ElasticPress + Foogallery

### ISSUE THREAD

**Issue by argus231** [10up/ElasticPress#1138]
Hello

ElasticPress together with the plugin Foogallery creates an endless loop. 
As soon as both addons are active, countless entries "_foogallery_css" are stored in the wp_postmeta. 
This goes on until it comes to a timeout. 
In my test environment, only the two plugins are active.

![bild 1](https://user-images.githubusercontent.com/43783562/46350894-42806d00-c656-11e8-986c-344a20a351e0.jpg)
![bild 2](https://user-images.githubusercontent.com/43783562/46350896-44e2c700-c656-11e8-88ea-e33855db3901.jpg)

Can someone help me. 
THX!

**Comment by bradvin** [comment]
hey ElasticPress team,

I am from the FooGallery team. I would like to replicate this issue on my local dev setup. 
Would it be possible to get a temp account with elasticpress.io so I can replicate this?

**Comment by brandwaffle** [comment]
@bradvin definitely! If you drop us a line at support@elasticpress.io we'll get you set up right away.

**Comment by bradvin** [comment]
thanks @brandwaffle I will email shortly

**Comment by oscarssanchez** [comment]
Closing this one as access was given. Please let us know if we can help with something else @bradvin :)
