### ISSUE TITLE
Sort using custom post meta field

### ISSUE THREAD

**Issue by chersull** [10up/ElasticPress#1140]
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? Question

Describe the issue you encountered: cURL returns my results correctly when sorting on a custom meta field, but I cannot figure out how to translate this to my wordpress code. 

Current WordPress version: 4.9.8

Current ElasticPress version: 2.6.1

Current Elasticsearch version: 2.3.1

Where do you host your Elasticsearch server: This is my local dev instance.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): Not using any of these plugins

### Question
This is probably a simple thing.  Meta field I am trying to sort on is indexed properly and below cURL returns my results ordered as expected.    For testing, I have two documents with this field set, one as a "3" and one as a "1".  The 3 document is returned first, then the 1 document, then the remaining documents by relevancy score in descending order.     

```
curl -X GET 'http://localhost:9200/_search?pretty' -d '
{  
   "from": 0,  
   "size": 5,
   "_source": "post_title",  
    "sort": [
        { "meta.mmm_search_boost.value":   { "order": "desc", "ignore_unmapped": true }},
        { "_score": { "order": "desc" }}
    ],
      "query": {    
          "match_phrase_prefix": {      
               "post_title": {            
               "query": "stro",     
                 "slop": "10",        
                "max_expansions": 25     
                }    
           }  
    },
"post_filter": {
    "bool": {
      "must": [
        {
          "terms": {
            "post_type.raw": [
              "mmm_resources_link",
              "mmm_resources_file",
              "mmm_resources_form",
              "mmm_resources_text"
            ]
          }
        },
        {
          "term": {
            "post_status": "publish"
          }
        }
      ]
    }
  }'
```
But the below code from Wordpress does not return the correct ordering.  I'm sure I just have a syntax error in my `$args['sort']` array...but I can't seem to narrow it down.  Appreciate any help.  
```
public function prepare_suggestion_search_args( $args, $scope, $query_args ) {
		$search_terms = \MMM\Helpers\get_search_query();

		$args['query'] = array(
			'match_phrase_prefix'    => array(
				'post_title'         => array(
					'query'          => $search_terms,
					'slop'           => 10, 					
                                        'max_expansions' => 25,				
                                  ),
			),
		);
		$args['ep_integrate'] = true;
		$args['sort'] = array(
			'meta.mmm_search_boost.value'      => array(
			'order'                             => 'desc',
			'ignore_unmapped'                   => true
			),
			'_score'                            => array(
				'order'                         => 'desc'
			)
		);
		return $args;
	}
```

**Comment by chersull** [comment]
Friends I will be away from my office for a few days and returning next 10/10, just in case I get some responses.  Thank you again -

**Comment by oscarssanchez** [comment]
Hi @chersull , the ElasticPress debug bar comes very handy in these types of situations as it displays the full converted query body that actually is requested to elasticsearch. 

You can download it here: https://wordpress.org/plugins/debug-bar-elasticpress/ or https://github.com/10up/debug-bar-elasticpress If you could paste here the query body that would be great to help you out 

Thank you for raising your question and have a good day!

**Comment by oscarssanchez** [comment]
Closing this one out @chersull as we did not hear back from you.
