### ISSUE TITLE
Can I somehow use "minimum_should_match"

### ISSUE THREAD

**Issue by FredrikLodon** [10up/ElasticPress#1141]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I can get the result I want through Postman when I use the "minimum_should_match" parameter. But can I somehow use this in WP_Query and Elasticpress? If not what is best practice instead, to come as close as possible to the "minimum_should_match" parameter?

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
6.2.4

Where do you host your Elasticsearch server:
Own VPS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce

**Comment by brandwaffle** [comment]
Hi @FredrikLodon, you can add any arguments you want to the Elasticsearch query using this filter:
https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1681

Hope that helps!

**Comment by oscarssanchez** [comment]
HI @FredrikLodon , was your question answered? 

Have a good day :)

**Comment by oscarssanchez** [comment]
Closing this one out @FredrikLodon . Feel free to reach out if this was not answered for you :)
