### ISSUE TITLE
admin query SLOW

### ISSUE THREAD

**Issue by jedidiah13** [10up/ElasticPress#1143]
Have you searched for similar issues before submitting this one? **yes**

Is this a bug, question or feature request? **bug?**

Describe the issue you encountered: **my admin queries are taking an enormous amount of time on the backend.  i can search on the front end and it takes 1-2 seconds, but searching products on the backend takes 8-12 seconds**

Current WordPress version: **4.9.8**

Current ElasticPress version: **2.6.1**

Current Elasticsearch version: **6.2.4**

Where do you host your Elasticsearch server: **Centos 7 Server hosted by Media Temple, 205.186.128.20**

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
**
Advanced Access ManagerDeactivate
--
Advanced Custom FieldsDeactivate
Bing Site Verification plugin using Meta TagDeactivate
BLAZING WooCommerce Shipment TrackingDeactivate
Categories to Tags Converter ImporterDeactivate
CCRind custom shippingDeactivate
Coming Soon Page & Maintenance Mode by SeedProdSettings \| Deactivate
Debug BarDeactivate
Debug Bar ElasticPressDeactivate
ElasticPressDashboard \| Deactivate
Facebook for WooCommerceSettings \| Deactivate
Gmail SMTPDeactivate \| Settings
Google Analytics Dashboard for WP (GADWP)Settings \| Deactivate
Google Sitemap by BestWebSoftSettings \| Deactivate
Image Rotation FixerDeactivate
Import from eBay to WooCommerceDeactivate
ImsanitySettings \| Deactivate
LTL Freight Quotes - YRC EditionSupport \| Settings \| Deactivate
Multiple Packages for WooCommerceDeactivate
Query MonitorDeactivate
Redis Object CacheSettings \| Deactivate
SEO Optimized ImagesDeactivate
Storefront Footer BarDeactivate
UPS WooCommerce ShippingSettings \| Documentation \| Support \| Deactivate
Widget ContextDeactivate
Woo Discount RulesDeactivate
WooCommerceSettings \| Deactivate
WooCommerce - ShipStation IntegrationSettings \| Support \| Docs \| Deactivate
WooCommerce AdWords Conversion TrackingDeactivate \| Settings
WooCommerce Checkout ManagerSettings \| Support \| Deactivate
WooCommerce Google Analytics IntegrationSettings \| Support \| Deactivate
WooCommerce Google Product FeedDeactivate
WooCommerce Intuit Payments GatewayConfigure Credit Cards \| Configure eChecks \| Use Legacy QBMS Gateway \| Docs \| Support \| Review \| Deactivate
WooCommerce PayPal Checkout GatewaySettings \| Docs \| Deactivate
WooCommerce PDF Invoices & Packing SlipsSettings \| Deactivate
WordPress ImporterDeactivate
WP TranslateDeactivate
WP-Lister Pro for eBaySettings \| Deactivate
WP-OptimizeOptimizer \| Settings \| Deactivate
Yoast SEO PremiumSettings \| Deactivate
Yoast SEO: WooCommerceDeactivate

please excuse the extra information after each plugin, just copy pasted from the plugin list
**

Screenshots, if needed:
![screen shot 2018-10-05 at 9 26 25 am](https://user-images.githubusercontent.com/10978996/46542629-7fca4200-c884-11e8-9598-43aebc12bd48.png)
![screen shot 2018-10-05 at 9 26 48 am](https://user-images.githubusercontent.com/10978996/46542648-89ec4080-c884-11e8-9a6e-c7665dd6ab55.png)
![screen shot 2018-10-05 at 9 27 18 am](https://user-images.githubusercontent.com/10978996/46542654-8e185e00-c884-11e8-85d8-07b4c302fb80.png)
![screen shot 2018-10-05 at 9 27 34 am](https://user-images.githubusercontent.com/10978996/46542661-8fe22180-c884-11e8-89a7-ffd8045fc624.png)
![screen shot 2018-10-05 at 9 28 16 am](https://user-images.githubusercontent.com/10978996/46542665-92447b80-c884-11e8-866b-5ffbc3690901.png)

**Comment by jedidiah13** [comment]
no, it always seems to succeed just fine, but for some reason it defaults to WP query.  is there somewhere i need to program in to make the search always use elastic search?

also, what can i do to get the cluster status to show 'green'?

**Comment by brandwaffle** [comment]
@jedidiah13 are those screenshots showing the EP queries from the admin the ones that are taking 8-10 seconds? If so, it seems the Elasticsearch part of that is only 30ms, so my first guess would be there's a ton of admin code running alongside ElasticPress that's causing the overall site experience to be slow. If you turn off the Protected Content Feature or disable ElasticPress, does the performance change noticeably?

The cluster status has to do with shards and data integrity. It _could_ have an effect on query performance, since it could indicate that Elasticsearch doesn't know where your data is stored inside its cluster. There are a few good tutorials about resolving this issue (https://www.elastic.co/blog/red-elasticsearch-cluster-panic-no-longer) but unfortunately it's beyond the scope of the support we can provide here. Elasticsearch can get a bit complicated, which is why we built elasticpress.io 😄

**Comment by jedidiah13** [comment]
another side note:
i wrote code to search for multiple skus simultaneously and placed it in my functions.php file in my theme.
when elasticpress is enabled, it no longer finds them all, it only finds the first search term.  this leads me to believe that elasticpress is using altering the query, but is still taking a LONG time

i deactivated elasticpress and my code worked fine for finding multiple skus.  the code i wrote is as follows...
![screen shot 2018-10-05 at 10 51 34 am](https://user-images.githubusercontent.com/10978996/46545723-b60bbf80-c88c-11e8-9198-1f98ab692a01.png)
![screen shot 2018-10-05 at 10 51 48 am](https://user-images.githubusercontent.com/10978996/46545724-b7d58300-c88c-11e8-91d9-d025df593584.png)

**Comment by jedidiah13** [comment]
yea you seem to be right about the elasticpress search working very fast.
its the **WC_Product_Data_Store_CPT->search_products** from the first screenshot that is slowing everything down... does anyone know how i can eliminate this?

**Comment by brandwaffle** [comment]
@jedidiah13 Nice! If you add ep_integrate => true as a query param your SKU query should also run through ElasticPress.

**Comment by brandwaffle** [comment]
@jedidiah13 in fact, that might work for the WC_Product_Data_Store_CPT plugin too--if there's a MySQL query running really slowly in there, you could filter it (assuming the plugin allows) to add ep_integrate => true or you could always just edit the plugin directly if necessary (though upgrading would break your improvement in that case). Is the plugin in question available on the WP.org repo? Can you point me to it?

**Comment by jedidiah13** [comment]
its part of woocommerce apparently, im not certain

**Comment by jedidiah13** [comment]
https://docs.woocommerce.com/wc-apidocs/class-WC_Product_Variable_Data_Store_CPT.html

**Comment by brandwaffle** [comment]
@jedidiah13 ok, yup. That does a direct MySQL query which could easily take 6 seconds to run. Let me do a bit of digging and see what kind of a solution I can come up with.

**Comment by jedidiah13** [comment]
awesome, thanks for all the help!

**Comment by brandwaffle** [comment]
@jedidiah13 no problem! At first glance, that code was introduced 8 months ago and replaced a simple lookup by meta. https://github.com/woocommerce/woocommerce/blame/f7028154a1564cb63f940ae7311054d1536b2662/includes/admin/list-tables/class-wc-admin-list-table-products.php#L441

Unfortunately, it doesn't look like there are any filters that can be used to prevent the function from running the direct DB query (at least not in a simple way--there might be a hacky one out there but I haven't looked deep enough to know, and suspect I wouldn't want it in production anyway).

I'm not sure what to do here except to open a support ticket with Woo asking them to allow us to filter this to prevent the default search from running. As you've seen, that MySQL query is really slow, so having an option to override it with ElasticPress would be very, very helpful.

**Comment by jedidiah13** [comment]
cool, i'll definitely submit to Woocommerce, that time is ridiculous

**Comment by brandwaffle** [comment]
@jedidiah13 did you end up submitting a ticket? I'd love to +1 it if so.
