### ISSUE TITLE
Using ep_find_related

### ISSUE THREAD

**Issue by tridoan** [10up/ElasticPress#1150]
Hello,
So using this API method to retrieve "related" posts in a current install of a site. However, we're seeing results that are sporadic. Some results will share the same tags, some do not. What is the criteria "under the hood" for this method that would return a post as a related post to the passed in post ID?

Is it based on the post's title? Post body? Category/taxonomy? Tags? 

How are each criteria weighted in order for the code to know which one to return first? Is it by date? Or is it by how many word matches? Etc?

Any insight on this would be greatly helpful, thank you!

**Comment by allan23** [comment]
There has also been a change pushed to the `develop` branch for related posts. This slated for the 2.7.0 release, so please feel free to test.
