### ISSUE TITLE
Return more than 10000 records when pulling all from search?

### ISSUE THREAD

**Issue by elvismdev** [10up/ElasticPress#1152]
Hi, 

When loading a search page with empty search value `myworpress.com/?s=` is expected that `$wp_query->found_posts` have the value of all the available records in the WordPress backend. I have around 25k posts records in WordPress and all indexed in the Elasticsearch cluster. However the `found_posts` count on this search only gives me `10000` as value, which is the default on ES [`index.max_result_window`](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html). 

Is there a filter in ElasticPress I can use to increse this number or the parameter `max_result_window`?

**Comment by allan23** [comment]
Hi @elvismdev,
Yes, there is a filter for this:

```
The request will return a HTTP 500 Internal Error if the size of the
 request is larger than the [index.max_result_window] parameter in ES.
 See the scroll api for a more efficient way to request large data sets.

$posts_per_page = apply_filters( 'ep_max_results_window', 10000 );```

**Comment by jitendraharpalani22** [comment]
@allan23 I am facing this issue with Elasticpress latest version. My `posts_per_page` is set to 10 for pagination. I was getting the count earlier via `found_posts` which was the total number of posts= 350,000. Now, though it is returning 10000 which seems to be the default in new ES 7.4.2

It used to work with 6.3 and previous version of EP. I tried the filter mentioned above to set max_results_window to -1. 
```
add_filter( 'ep_max_results_window', 'max_results_window' );
public function max_results_window() {
		return -1;
	}
```
