### ISSUE TITLE
prepare_post(). absint was applied to comment_status

### ISSUE THREAD

**Issue by jcastilloa** [10up/ElasticPress#1153]
Have you searched for similar issues before submitting this one? **Yes.**

Is this a bug, question or feature request? **Bug**

_Describe the issue you encountered:_

https://github.com/10up/ElasticPress/blob/9826fc6ddee3c612079d8046e48658da2a9c2023/classes/class-ep-api.php

$comment_status = absint( $post->comment_status );

In method prepare_post, absint was applied to $post->comment_status (string: "open" / "closed").

The result is zero to any value of comment_status.

**Comment by oscarssanchez** [comment]
Hi @jcastilloa ,

Thanks for the catch! 

A PR was created to solve this issue :)
