### ISSUE TITLE
ElasticPress search with Boolean Operators?

### ISSUE THREAD

**Issue by elvismdev** [10up/ElasticPress#1154]
Hi, 

I can't find much information about Boolean Search capabilities with ElasticPress, although [Elasticsearch supports using boolean operators within the searched string](https://www.elastic.co/blog/lost-in-translation-boolean-operations-and-filters-in-the-bool-query), so far I don't get the expected outcome when I use AND, OR, NOT while searching contents in the WordPress site where I have ElasticPress + Elasticsearch. 

An example of what I'm trying to accomplish:

**jack AND jill** — Will return posts that contain both jack and jill
**ahab NOT moby** — Will return posts that contain ahab but not moby
**tom OR jerry** — Will return posts that contain tom or jerry, or both

Do I'm missing something, or is that ElasticPress cannot construct [bool queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) from this to Elasticsearch and pass them through to the ES cluster?

**Comment by oscarssanchez** [comment]
Hi @elvismdev ,

ElasticPress has a range of filters in `format_args()` to add custom arguments to the final query that's passed into  ElasticSearch. Just a few that might come handy:

`ep_formatted_args`
`ep_formatted_args_query`

If you install our debug bar: https://wordpress.org/plugins/debug-bar-elasticpress/ or https://github.com/10up/debug-bar-elasticpress you can check that bool queries are supported if you do a test search in your site. Debug bar also might come handy to debug your queries as you can check  your query args from PHP as well as the query body in JSON that's being sent to ElasticSearch.

Hope this helps out.

**Comment by elvismdev** [comment]
Hi @oscarssanchez ,

Do you mean, if I try putting in my default WordPress search bar something like "ahab NOT moby", I should see a bool query in debug bar with the `must_not` clause? 

Or, this is actually something I have to construct myself with using the filters `ep_formatted_args`, `ep_formatted_args_query` ?

Thanks for your feedback on this.

**Comment by tlovett1** [comment]
In theory you could also programmatically filter `ep_formatted_args` using https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html to accomplish this.

**Comment by oscarssanchez** [comment]
Closing this one out @elvismdev . Feel free to reach out if your question was not answered :)
