### ISSUE TITLE
resume indexing with wp-cli

### ISSUE THREAD

**Issue by diditho** [10up/ElasticPress#1155]
Hello,

We are now in the middle of indexing 3 million post with wp-cli.
Is there a way so that if the indexing fail because timeout and other network or server issue we can resume the process and not strart the index from zero again ?

Thank You

Screenshots, if needed:
![image](https://user-images.githubusercontent.com/3233097/47949190-42cf9900-df71-11e8-8703-f8d9013bab25.png)

**Comment by ivankristianto** [comment]
@diditho 
you can use `[--posts-per-page] [--offset]`
by default posts-per-page is 350.
You can set it, and when it failed use offset where you left off. In your example you can set it with 33251.

**Comment by diditho** [comment]
Thank You @ivankristianto
