### ISSUE TITLE
Syncing issues

### ISSUE THREAD

**Issue by pvlvsk** [10up/ElasticPress#1161]
Hello, thank you for this plugin! 

Have you searched for similar issues before submitting this one?

Yes

Is this a bug, question or feature request?

bug

Describe the issue you encountered:

When i have my woocommerce products catalog set on „custom ordering“ and try to manually sort the products, the result is not updating on the front end. The same is happening when I change featured products for a custom themes widget. Workaround is to manually resync in Elasticpress Settings. 

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
6.2

Where do you host your Elasticsearch server:
VPS on Upcloud

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Woocommerce 3.4.6

Thank you!

**Comment by oscarssanchez** [comment]
Hi @pvlvsk ,

Thanks for letting us know about this issue.

I think this might be related to:  https://github.com/10up/ElasticPress/issues/1134

**Comment by oscarssanchez** [comment]
Hi @pvlvsk 

Per testing, sorting products manually while editing a product seem to work without problems. Are you arranging all of your products? as this did not work for me if i did not arrange other products. Could you please give us steps to reproduce this issue ? Thanks in advance.

At first I tought the sorting was done through the customizer, hence my confusion.

**Comment by oscarssanchez** [comment]
Closing this one out as we did not hear back @pvlvsk , feel free to comment if this is still an issue. 

Thanks!
