### ISSUE TITLE
How to make Facet filtration?

### ISSUE THREAD

**Issue by ijakparov** [10up/ElasticPress#1168]
**Have you searched for similar issues before submitting this one?**
yes

**Is this a bug, question or feature request?**
no

**Describe the issue you encountered:**
How can I make custom facet search? Something like FacetWP does.

**Comment by oscarssanchez** [comment]
hI @ijakparov ,

Could you describe in more detail what do you try to achieve? ElasticSearch does support facet filtering by taxonomies. You can use this feature by putting the face widget in your site's sidebar.

**Comment by ijakparov** [comment]
Hello @oscarssanchez. I want to make facet search by meta fields, taxonomies, and to have abillity make index from custom tables, and use this data for facets too.

**Comment by oscarssanchez** [comment]
Hi @ijakparov ,

Facets support search by taxonomy only at this point. Custom table indexing is not supported at this point too.

**Comment by oscarssanchez** [comment]
Closing this one out, feel free to contact if the question was not answered @ijakparov
