### ISSUE TITLE
Related Posts not related

### ISSUE THREAD

**Issue by 4lxndr** [10up/ElasticPress#1169]
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? Question

Describe the issue you encountered:
I have 4 posts, 2 with the title test and content a lot of test words. The other 2 posts are "hello world" and "hello you" and the content is lorem ipsum generated content. Both posts are in the same category named "test". If i excute `ep_find_related` with the id of the post with the "hello world" title i assume that the related post "hello you" is in the list. Its not. Why? Whats the weighting to get "related" posts? How can i influence the related post behaviour?

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
4.2

Where do you host your Elasticsearch server:
Docker

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Nothing

Steps to reproduce:
1. write post
2. ...
3. profit

Screenshots, if needed:
xxx

**Comment by oscarssanchez** [comment]
Hi @4lxndr ,

Thanks for raising your question, you can find the arguments for the related posts in `ep_related_posts_formatted_args` : https://github.com/10up/ElasticPress/blob/develop/features/related-posts/related-posts.php#L33

We are not adding any additional boosting / weigh as you can see here. 

If you wish to modify the arguments that get passed to elasticsearch, you can make use of `ep_formatted_args` filter .

Let us know if this serves your needs or we can help you out

**Comment by 4lxndr** [comment]
Hi @oscarssanchez,

thanks for the explanation! I'll use the filter and try it out later this week. 

Best Regards
