### ISSUE TITLE
installed plugin doesn't works

### ISSUE THREAD

**Issue by luismareze** [10up/ElasticPress#1174]
Have you searched for similar issues before submitting this one? yes, for sure

Is this a bug, question or feature request? Question

Describe the issue you encountered: I believe is a silly question but I did as every tutorial says to do.
My point is I am running a site with 10sku with woocommerce and dokan. I'd like to improve this performance at all, render better the whole site, search and everything.
I indexed and sent my data to my ES in AWS. It Is ok.
What do I need to do? Do I need to coding my theme and change the function calls?
Or the plugin do it byhimself?
How can I the queries trying to acess my ES?
I believe I am not understing how it works and my site is the same before intalled the plugin.
thanks

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
6.5.0

Where do you host your Elasticsearch server: AWS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): woocomerce, dokan, wp bakery

Steps to reproduce:

1.  I set up my ES in AWS, my ES is public for test
2. Put my config on wp-config
3. ran the index 
4. refresh my site and is being extremely slow

**Comment by oscarssanchez** [comment]
Hi @luismareze , you can check ElasticPress is running if there's no errors showing up in the plugin dashboard. Additionally and to make sure your queries are running through ElasticPress and into elasticsearch, you can install our debug bar: https://github.com/10up/debug-bar-elasticpress and check if queries are being made through elasticsearch. 

It might look something like this: 

![es](https://user-images.githubusercontent.com/31049169/49124121-c8005200-f280-11e8-96b0-f67a0dee26d0.png)

No further coding is required in your theme files unless you want to customize your queries.

Hope this helps and have a good day!

**Comment by luismareze** [comment]
thanks @oscarssanchez .

In my debug I can't see the WP_Query shorcut and still so slow to load the homepage. 25s, running in localhost and ES in AWS. Any tips ? or Misunderstood  of config to try to improve this perfomance?

Thanks

![sem titulo](https://user-images.githubusercontent.com/13120053/49125006-9948a280-f2a5-11e8-9e32-74a4ec289104.png)

**Comment by oscarssanchez** [comment]
Hi @luismareze ,

Could you test if the behavior is the same on another sample site and by testing with and without certain plugins? If the behavior is the same, specially without plugins, then this has probably to do with your elasticsearch instance in AWS. If the sites loads considerably better, then it's probably an issue with a plugin you may have activated. 

Happy to help out troubleshooting this.

**Comment by oscarssanchez** [comment]
Hi @luismareze , 

I'm closing this now as we did not hear back from you. Please feel free to reach out if the issue was not solved for you.

Thanks.
