### ISSUE TITLE
WooCommerce products disappearing when plugin is enabled

### ISSUE THREAD

**Issue by jeffceriello** [10up/ElasticPress#1175]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
It seems to be a bug

Describe the issue you encountered:
When the ElasticPress plugin is enabled, many of our products disappear from our online store. they only reappear when I disable ElasticPress.

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
6.2

Where do you host your Elasticsearch server:
self, on same host as website

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce and many more

Steps to reproduce:

1. Enable ElasticPress
2. Visit shop page

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi @jeffceriello ,
Please note you may have to run a resync from the ElasticPress dashboard.

Let us know how it went after doing this, and thanks for raising your concern.

**Comment by jeffceriello** [comment]
Hi @oscarssanchez, thank you for your reply.

I have tried resyncing but that does not fix it. Only after deactivating the plugin all products show again.

What else could it be? Do the WooCommerce archive loops need some customisation for them to not go in conflict with ElasticPress?

**Comment by jeffceriello** [comment]
Hi Oscar,

Sorry but I'm pretty new to ElasticSearch. I guess the ES server is the IP of the server where ES has been installed on but where do I find the ES index name?

Thanks so much for your help on this.

**Comment by oscarssanchez** [comment]
Closing this one out @jeffceriello , please feel free to reopen if you have more questions.

**Comment by jeffceriello** [comment]
Hi Oscar,

Thanks so much for your help with this matter. I'm sorry for the very late reply but I've been travelling for a couple of months, away from civilisation.

I have finally managed to do what you suggested. I can find some of the woocommerce mapping in the elasticsearch instance

http://176.56.56.116:9200/wardrobeiconscom-1/_mappings


and here is the other ping request

http://176.56.56.116:9200/wardrobeiconscom-1/post/_search?pretty=true

Can you see anything wrong in there?

Thank you

**Comment by jeffceriello** [comment]
Hi Oscar,

I'm just chasing up to know if you managed to have a look at this yet?

Thank you
