### ISSUE TITLE
Show counts in faceted search widget

### ISSUE THREAD

**Issue by ray-lee** [10up/ElasticPress#1180]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Feature request

Describe the issue you encountered:
In the faceted search widget, we'd like to display the number of posts that are associated with each term.

If #1160 is merged, we could do this using the ep_facet_search_widget filter, but we would need to duplicate a lot of code, and this seems like it would be a common enough requirement that it should be supported out of the box. I'm happy to implement this and make a pull request.

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
6.2

**Comment by oscarssanchez** [comment]
Hi @ray-lee ,

Thanks for raising the issue, and sorry for the late reply, we just had a chance to discuss your suggestions today. Also, thanks for submitting those two previous PR's ! It 's always good to know there's people interested into making the plugin better.

After the internal discussion, this seems like a good feature to have, so please proceed whenever you have time to do this. 

Thanks!

**Comment by ray-lee** [comment]
Great, thanks. I'm working on this now.

**Comment by oscarssanchez** [comment]
Hi @ray-lee, do you mind if I redo this PR for 3.0? it looked very promising :)

**Comment by ray-lee** [comment]
@oscarssanchez Sure, no problem.
