### ISSUE TITLE
Support ElasticSearch 6.2+ as 5.6 will EOL around March 2019

### ISSUE THREAD

**Issue by jonstanley** [10up/ElasticPress#1183]
Have you searched for similar issues before submitting this one?
Yes, see ticket [#1052](https://github.com/10up/ElasticPress/issues/1052), and also [#1170](https://github.com/10up/ElasticPress/issues/1170)

Is this a bug, question or feature request?
Bug-cum-feature-request? Elastic.co states that ElasticSearch version `5.6.x` will EOL either on March 11, 2019 or on release of version `7.0.0`, [whichever comes first](https://www.elastic.co/support/eol). Given that `6.5.2` is current, there may be a `6.6.x` release, or a jump to `7.0.0` Real-Soon-Now™. As minor version releases in the `6.x` "shouldn't" break anything, would make sense to get ElasticPress tested for that line going forward.

Describe the issue you encountered:
Initial plugin configuration error pukes with:

> Your Elasticsearch version is below the minimum required Elasticsearch version 1.7. ElasticPress may or may not work properly.

Documentation seems to imply only ElasticPress version 5.x is the maximum supported version, but there's official support since EP `2.5` for ES `6.2.x`

Current WordPress version:

`5.0.0`

Current ElasticPress version:

`2.6.1`

Current Elasticsearch version:

`6.5.2`

Where do you host your Elasticsearch server:

localhost

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

None

Steps to reproduce:

1. Install current ElasticSearch (`6.5.2`)
2. Install ElasticPress via wp-cli (gets version `2.6.1`)
3. Apparent hard error on the config page, but it's actually a soft error of ElasticSearch being too new.

Screenshots, if needed:
N/A

**Comment by oscarssanchez** [comment]
Hi @jonstanley,

Thanks for the heads up! I didn't know about that.

There has been some issues to integrate the minor releases of elasticsearch 6.x. The good news is ElasticPress 2.7 is going to support till 6.3. Of course the plugin will keep being updated to support more recent versions of ES.

Thanks again, and hope your day is going well :)

**Comment by jonstanley** [comment]
Hi @oscarssanchez!

I see WordPress.org has the more recent release of the plugin up, will upgrade to that and glad to here EP will get synced up with future releases of ES... 💃 👍
