### ISSUE TITLE
autosuggest CORS issue

### ISSUE THREAD

**Issue by zhex900** [10up/ElasticPress#1184]
Hi,
I need help to with CORS. Elasticsearch is hosted on elastic.site.com. Woocommerce is on uat.site.com. I get this error in the dev console. Is there anything else I should do?

    Access to XMLHttpRequest at 'https://api.site.com/index/post/_search' from 
    origin 'https://uat.site.com' has been blocked by CORS policy:
    Response to preflight request doesn't pass access control check: 
    No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is what I added to `<VirtualHost *:80>` block

       Header always set Access-Control-Allow-Origin "*"
       Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
       Header always set Access-Control-Max-Age "1000"
       Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"

    ➜  ~ curl -I https://uat.site.com
    HTTP/2 200
    server: nginx/1.15.7
    date: Tue, 11 Dec 2018 04:33:51 GMT
   content-type: text/html; charset=UTF-8
    x-powered-by: PHP/7.2.8
    access-control-allow-origin: *
    link: <https://uat.site.com.au/wp-json/>; rel="https://api.w.org/"
    link: <https://uat.site.com.au/>; rel=shortlink
    access-control-allow-methods: POST, GET, OPTIONS, DELETE, PUT
    access-control-max-age: 1000
    access-control-allow-headers: x-requested-with, Content-Type, origin, authorization, accept, 
    client-security-token
    strict-transport-security: max-age=31536000

**Comment by jordan26** [comment]
Did you fix this @zhex900? Same issues here.

**Comment by zhex900** [comment]
Sorry, I didn't find a solution. I gave up.

**Comment by naqirizvi** [comment]
any update on the solution ?
