### ISSUE TITLE
ES_SHIELD 401

### ISSUE THREAD

**Issue by microsupportau** [10up/ElasticPress#1186]
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? Bug/Question

Describe the issue you encountered:

Current WordPress version: 4.9.8

Current ElasticPress version: Latest

Current Elasticsearch version: 5.6

Where do you host your Elasticsearch server: Local Install

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): WooCommerce

Steps to reproduce:

1. 401 Error if x-pack or search guard installled
2. ES_SHIELD is set with correct username and password.
3. 

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi @microsupportau ,

Sorry for the late reply, I just had a chance to test this with an elastic cloud trial account, which has X-pack installed and i did not have any problems when i set my ES_SHIELD constant.

Could you please describe your issue in better detail ?
Thanks and have a great day!
