### ISSUE TITLE
The bulk request uses an incorrect Content-Type

### ISSUE THREAD

**Issue by MrEfrem** [10up/ElasticPress#1187]
Have you searched for similar issues before submitting this one?
yes

Is this a bug, question or feature request?
bug

Describe the issue you encountered:
How described in https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html:
`When sending requests to this endpoint the Content-Type header should be set to application/x-ndjson.`.
But you send the header `Content-Type: application/json` and therefore my proxy server, which transfers requests to Elasticsearch throws an error when trys to parse a body of request as `JSON`.
I think would be more correctly to use right `Content-Type`.

**Comment by allan23** [comment]
Hi @MrEfrem,

What is the exact error you are receiving?

**Comment by MrEfrem** [comment]
Try use the ‘body-parser’ npm package and you will understand me. And why do you interest my error? This is explicit bug, because different of official documentation.

**Comment by allan23** [comment]
The reason I ask is because you are using a proxy server in between your elasticsearch instance and your server. If the proxy server does not accept the correct content-type you will get an error.

**Comment by MrEfrem** [comment]
I use the proxy because I want process data adding to Elasticsearch and trigger some functions. I implement the proxy in Google cloud function. Because cloud functions run over Express.JS and google cloud platform uses ‘body-parser’ by default to parse ‘JSON’ then this incorrect header ‘Content-type’ leads to an error of parsing ‘JSON’.

**Comment by MrEfrem** [comment]
hi @allan23, I believe that Elasticpress should not always send an `application/json` header. My proxy accepts correct headers but for bulk requests the content header should be `application/x-ndjson`. Do you plan on fixing this issue? I'm just curious because I have solved the issue now in the proxy but it's not ideal. It would be much better if Elasticpress would always set correct content headers and not always application/json: https://github.com/10up/ElasticPress/blob/093b9ebbf8518420391706f47d7461a3e5cac136/classes/class-ep-api.php#L366

**Comment by allan23** [comment]
Hello @MrEfrem, you can actually change the content-type header by using the `ep_format_request_headers` filter.
