### ISSUE TITLE
Stop ep_integrate=false from overriding the s parameter

### ISSUE THREAD

**Issue by spelkey-ucd** [10up/ElasticPress#1189]
Have you searched for similar issues before submitting this one?
Yes.

Is this a bug, question or feature request?
Question, but maybe a feature request

Describe the issue you encountered:
I have the search feature enabled, but I don't want to use it for all searches. Basically, I would like to be able to use the `s` keyword parameter in a new WP Query object when `ep_integrate=>false`  so, I can use the plain old MySQL search. However, when I enter an `s` parameter and set `ep_integrate=>false`, the query ignores `s` as stated in the Readme. How can I stop this behavior? 

Current WordPress version:
WordPress 4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
5.4.1

Where do you host your Elasticsearch server:
Docker, locally. Linux in production.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
ACF, Relevancy (for now) and a few more.

Steps to reproduce:

1. Create query object. Set ep_integrate to false, s to anything.
2.  Run search.
3.  Nothing returns.

Thanks for your help!

**Comment by incredimike** [comment]
I also need to know the answer to this question.

**Comment by incredimike** [comment]
Seems to me that around line 72 in `classes/class-ep-wp-query-integration.php` There is the following pre_get_posts call:
```
public function action_pre_get_posts( $query ) {
		if ( ! ep_elasticpress_enabled( $query ) || apply_filters( 'ep_skip_query_integration', false, $query ) ) {
			return;
		}
...
```

Perhaps that void return should be `return $query;` instead?

**Comment by oscarssanchez** [comment]
Hi @spelkey-ucd  and @incredimike ,

Sorry for late response, I was trying to reproduce this like this:
```
$query1 = new WP_Query( array(
    'ep_integrate'   => true,
    's' => 'fox',
    'posts_per_page' => 20,
) );
$result1 = $query1->found_posts;

$query2 = new WP_Query( array(
    'ep_integrate'   => false,
    's' => 'brown',
    'posts_per_page' => 20,
) );
$result2 = $query2->found_posts;
```
But it looks like to me the s parameter is not getting overridden to me. Looking at the debug bar it looks like in this case, the only query that goes through elasticsearch is "fox", and "brown" is made via MySQL.

Could you please give more detailed steps if this not how this is supposed to be reproduced? Maybe I'm not getting it.

Thanks

**Comment by spelkey-ucd** [comment]
Is it actually returning results for "brown"?

When I use the same code snippet, I get no results for the MySQL query even though I get results when I perform the same query on a site clone that doesn't use Elasticpress.

However, when I remove the `s` parameter, and filter by a different parameter like `post_type`, I get results.

Quoting from the [readme](https://github.com/10up/ElasticPress/blob/develop/README.md#supported-wp_query-parameters) it says "Setting ep_integrate to false will override the s parameter if provided."

Thanks for your help!

**Comment by spelkey-ucd** [comment]
so after some more troubleshooting, it looks like ElasticPress is fighting with Relevanssi - possibly on the `posts_request` hook. Is it possible to temporarily disable ElasticPress completely with a `remove_filter` function?

**Comment by oscarssanchez** [comment]
Hi @spelkey-ucd apart from the `ep_integrate` parameter in WP_Query there's not a remove_filter function you can use
