### ISSUE TITLE
Strange behaviour on my home page

### ISSUE THREAD

**Issue by willstocks-tech** [10up/ElasticPress#1193]
> Have you searched for similar issues before submitting this one?

Tried to but couldn't find anything based on a quick search

>Is this a bug, question or feature request?

Bug

>Describe the issue you encountered:

Following the process documented here: https://www.cloudways.com/blog/elasticsearch-on-wordpress/ I have setup ElasticPress/ElasticSearch on my Cloudways Wordpress instance, however when I enable EP, my homepage (list of blog posts) gets replaced by the "failed search" screen (cleared all caches!)?
I've since disabled the plugin on my site and will try to get it setup on my test site!

It's not the 404 screen... it's the "No search results" screen

>Current WordPress version:

5.0.2

>Current ElasticPress version:

2.7

>Current Elasticsearch version:

5.4

>Where do you host your Elasticsearch server:

locally

>Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

A few - I'll get the list. Main ones that _may_ interfere being Autoptimize and W3TC

>Steps to reproduce:

1. Setup EP (Cloudways Digital Ocean 1GB with ES enabled)
2. Ensure homepage is a list of blogposts
3. Enable EP and navigate to homepage

>Screenshots, if needed:
![image](https://user-images.githubusercontent.com/43744514/50767538-20aa0e00-1275-11e9-863e-183c978d1661.png)

**Comment by fkkm1999** [comment]
Version 2.7.0
--

**Comment by willstocks-tech** [comment]
Was that the ElasticPress version (Plugin), or the ElasticSearch version (service via Cloudways platform)?

**Comment by fkkm1999** [comment]
2.4, but its something in the plugin probably.

**Comment by willstocks-tech** [comment]
Ahhh, OK cool - yeah I was trying to use 5.4 because 6.# didn't work at all (would be nice to see this in the future) so it's not just one version. I highly doubt Cloudways have wrecked ElasticSearch their end, so I'd be leaning more towards plugin-side :(

**Comment by oscarssanchez** [comment]
Hi @willstocks-tech  and @fkkm1999 ,

I just tested 2.7 with ES 5.4.2 and everything behaves as expected from my side. 

Because this seems to be from the same hosting provider, I'm inclined to think the problem must be on their side, so the best thing here would be to reach out to them. 

Also, note that ES is supported up to 6.3, so you can install that one if you want to :)

Have a good day!

**Comment by willstocks-tech** [comment]
Aha - thanks @oscarssanchez! I'll give the debug bar a go as well as will reach out to the guys at Cloudways (@Saquibrizwan and @shahroznawaz) to see what's what.
When I was using 6.3, it kept giving me a cURL error relating to SSL something or other (I'll regrab that and will log separately if it's not an environmental thing)

**Comment by shahroznawaz** [comment]
Hey Will, Thanks for notifying it. Looks strange to me also. I need to test it on my end also to check if this happend on every wordpress install or anything specific causing this. I'll test it and add the comment here.

**Comment by willstocks-tech** [comment]
@oscarssanchez this is a mammoth, but installed, reactivated, synced and went to my homepage and immediately:
```
TOTAL ELASTICPRESS QUERIES:
1
TOTAL BLOCKING ELASTICPRESS QUERY TIME:
37 ms
Host: http://127.0.0.1:9200
Time Taken: 37 ms
URL: http://127.0.0.1:9200/willstockscouk-1/post/_search
Method: POST
Query Args: 
array(68) {
  ["error"]=>
  string(0) ""
  ["m"]=>
  string(0) ""
  ["p"]=>
  int(0)
  ["post_parent"]=>
  string(0) ""
  ["subpost"]=>
  string(0) ""
  ["subpost_id"]=>
  string(0) ""
  ["attachment"]=>
  string(0) ""
  ["attachment_id"]=>
  int(0)
  ["name"]=>
  string(0) ""
  ["static"]=>
  string(0) ""
  ["pagename"]=>
  string(0) ""
  ["page_id"]=>
  int(0)
  ["second"]=>
  string(0) ""
  ["minute"]=>
  string(0) ""
  ["hour"]=>
  string(0) ""
  ["day"]=>
  int(0)
  ["monthnum"]=>
  int(0)
  ["year"]=>
  int(0)
  ["w"]=>
  int(0)
  ["category_name"]=>
  string(0) ""
  ["tag"]=>
  string(0) ""
  ["cat"]=>
  string(3) "-10"
  ["tag_id"]=>
  string(0) ""
  ["author"]=>
  string(0) ""
  ["author_name"]=>
  string(0) ""
  ["feed"]=>
  string(0) ""
  ["tb"]=>
  string(0) ""
  ["paged"]=>
  int(0)
  ["meta_key"]=>
  string(0) ""
  ["meta_value"]=>
  string(0) ""
  ["preview"]=>
  string(0) ""
  ["s"]=>
  string(0) ""
  ["sentence"]=>
  string(0) ""
  ["title"]=>
  string(0) ""
  ["fields"]=>
  string(0) ""
  ["menu_order"]=>
  string(0) ""
  ["embed"]=>
  string(0) ""
  ["category__in"]=>
  array(0) {
  }
  ["category__not_in"]=>
  array(0) {
  }
  ["category__and"]=>
  array(0) {
  }
  ["post__in"]=>
  array(0) {
  }
  ["post__not_in"]=>
  array(0) {
  }
  ["post_name__in"]=>
  array(0) {
  }
  ["tag__in"]=>
  array(0) {
  }
  ["tag__not_in"]=>
  array(0) {
  }
  ["tag__and"]=>
  array(0) {
  }
  ["tag_slug__in"]=>
  array(0) {
  }
  ["tag_slug__and"]=>
  array(0) {
  }
  ["post_parent__in"]=>
  array(0) {
  }
  ["post_parent__not_in"]=>
  array(0) {
  }
  ["author__in"]=>
  array(0) {
  }
  ["author__not_in"]=>
  array(0) {
  }
  ["ep_integrate"]=>
  bool(true)
  ["ep_facet"]=>
  bool(true)
  ["aggs"]=>
  array(3) {
    ["name"]=>
    string(5) "terms"
    ["use-filter"]=>
    bool(true)
    ["aggs"]=>
    array(3) {
      ["category"]=>
      array(1) {
        ["terms"]=>
        array(2) {
          ["size"]=>
          int(10000)
          ["field"]=>
          string(19) "terms.category.slug"
        }
      }
      ["post_tag"]=>
      array(1) {
        ["terms"]=>
        array(2) {
          ["size"]=>
          int(10000)
          ["field"]=>
          string(19) "terms.post_tag.slug"
        }
      }
      ["post_format"]=>
      array(1) {
        ["terms"]=>
        array(2) {
          ["size"]=>
          int(10000)
          ["field"]=>
          string(22) "terms.post_format.slug"
        }
      }
    }
  }
  ["tax_query"]=>
  array(0) {
  }
  ["ignore_sticky_posts"]=>
  bool(false)
  ["suppress_filters"]=>
  bool(false)
  ["cache_results"]=>
  bool(false)
  ["update_post_term_cache"]=>
  bool(true)
  ["lazy_load_term_meta"]=>
  bool(true)
  ["update_post_meta_cache"]=>
  bool(true)
  ["post_type"]=>
  string(0) ""
  ["posts_per_page"]=>
  int(4)
  ["nopaging"]=>
  bool(false)
  ["comments_per_page"]=>
  string(2) "50"
  ["no_found_rows"]=>
  bool(false)
  ["order"]=>
  string(4) "DESC"
}
Query Body: 
Query Response Code: HTTP 200
Query Result: 
{
    "took": 25,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "terms": {
            "doc_count": 0,
            "post_format": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "category": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "post_tag": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            }
        }
    }
}
```

**Comment by willstocks-tech** [comment]
PHP: 7.2.9
MySQL: 5.7.24

If this helps anyone?

**Comment by shahroznawaz** [comment]
> PHP: 7.2.9
> MySQL: 5.7.24
> 
> If this helps anyone?

Hey @willstocks-tech can you tell what exact settings and versions you are using? Also which wordpress you are using from the 3 options at Cloudways? Have you setup SSL cert?

**Comment by willstocks-tech** [comment]
Not a problem at all @shahroznawaz. So I'm setup as follows:
Wildcard Lets Encrypt SSl
![image](https://user-images.githubusercontent.com/43744514/50780278-72b15a80-129a-11e9-9b1d-dc5603444ee0.png)
W3TC configured per: https://www.cloudways.com/blog/how-to-use-w3-total-cache-wordpress/
ElasticPress setup as per: https://www.cloudways.com/blog/elasticsearch-on-wordpress/

If you want some further details (such as specifics relating to the settings configs) let me know via PM or will@willstocks.co.uk and I'll grab some screenshots etc.

**Comment by willstocks-tech** [comment]
I tried Elasticsearch 6.5 first, but that just straight up didn't work. 5.4 setup fine, but obviously there's this issue :)

**Comment by shahroznawaz** [comment]
@fkkm1999 I've noted your issue also and looking into it I'll add comment here after testing it :)

**Comment by allan23** [comment]
Hi @willstocks-tech,  you mentioned W3TC. What are your caching settings for that plugin?

**Comment by willstocks-tech** [comment]
Shahroze - I’ll get that sent over this evening!

Alan - I set up W3TC as per:
https://www.cloudways.com/blog/how-to-use-w3-total-cache-wordpress/ however
I know @fkkm1999 isn’t using W3TC per the comment above

**Comment by fkkm1999** [comment]
Thank you.

Bit of topic but does elasticpress need to work for elastic search to work, or does elasticpress just hook up the front end search with elastic search?

**Comment by willstocks-tech** [comment]
Just to confirm with everyone - I have set up a staging site for the guys at Cloudways to work with to try and resolve the issues
They have logged a ticket against my account for me (shout out to @shahroznawaz for arranging) and their support team are currently investigating/troubleshooting.
Will update here when I get an update!

**Comment by fkkm1999** [comment]
I just did some trouble shooting with  CW support and after disabling my childtheme it was working again so i guess its something in my functions.php for me.

**Comment by shahroznawaz** [comment]
> Just to confirm with everyone - I have set up a staging site for the guys at Cloudways to work with to try and resolve the issues
> They have logged a ticket against my account for me (shout out to @shahroznawaz for arranging) and their support team are currently investigating/troubleshooting.
> Note: This staging environment consists of a fresh WP install and a direct copy of my theme and plugins. Everything else remains completely untouched. Copied and pasted `/wp-content/themes/` and `wp-content/plugins/` exactly and that is all.
> Will update here when I get an update!

Hey will, Thanks for the shoutout. I'm in touch with the support team and they are investigating the issue on the server level. I hope the issue will resolve soon and we come to know the problem. As @fkkm1999 had resolved the issue by finding in a local file which is a part of the application so till then you can dig out in-app files too :)

**Comment by willstocks-tech** [comment]
@fkkm1999 - did you manage to work out what exactly within your functions.php was causing the issue?

**Comment by fkkm1999** [comment]
> @fkkm1999 - did you manage to work out what exactly within your functions.php was causing the issue?

I was able to fix it, it was a piece of code in my child themes functions.php that was hiding out of stock products. I deleted it im not sure what it exactly was sorry :(

**Comment by willstocks-tech** [comment]
Ahhhh bummer!

No worries - they guys @ Cloudways have my theme and might be able to pick out the function that's causing the issue, because I'm not even sure where to start! Do you remember what that piece of code was hooking in to? Maybe I'm hooking into the same place!

**Comment by fkkm1999** [comment]
No idea, I just copy paste from google lol. :P  Goodluck with solving it :)

**Comment by willstocks-tech** [comment]
Hey Oscar,

No worries!

Cloudways did some checks and it’s defo looking theme related.

I’m going to purse through my functions.php to see if I can work out what
is causing the issue! I’ll let you know if/when I work out what it is 😊

**Comment by willstocks-tech** [comment]
@oscarssanchez - I've managed to identify the issue:
```
function excludeCat($query) {
	if ( $query->is_home ) {
		$query->set('cat', '-10');
	}
return $query;
}
add_filter('pre_get_posts', 'excludeCat');
```

I'm excluding a specific list of posts that have a specific category set, from displaying on my home page. Why would this throw off EP?!

**Comment by willstocks-tech** [comment]
@oscarssanchez / @allan23 - any thoughts on this, or potential other methods I could use??
