### ISSUE TITLE
Allow user to specify selector for autosuggest

### ISSUE THREAD

**Issue by allan23** [10up/ElasticPress#1196]
Currently, users must use the selector hardcoded in the plugin. This means that if their theme does not have the selector or if they want to have autosuggest on a certain element, they will need to make customizations in the theme.

Giving users the ability to specify a selector within the dashboard will be a good step forward.

**Comment by tott** [comment]
I think it's likely best to put this as an optional setting into the autosuggest feature screen https://github.com/10up/ElasticPress/blob/develop/features/autosuggest/autosuggest.php#L42
