### ISSUE TITLE
Allow customization of facet widget query parameters

### ISSUE THREAD

**Issue by ray-lee** [10up/ElasticPress#1198]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Feature

Describe the issue you encountered:
Our search result page has links that allow users to change the sort order, and to limit the results to a single post type. These links go to URLs with query parameters like `?post_type=page&orderby=date&s=hello`. When we add the facet widget, the terms in the widget are linked to URLs with query parameters like `?s=hello&filter_foo=bar`. The `post_type` and `orderby` params are not retained, so the post type limitation and sort order are lost when the user clicks on a facet term. We want these to be maintained.

I would propose adding a filter that could be applied here:

https://github.com/10up/ElasticPress/blob/b2f77c706787617dbc70f12fba14d4de31c23a0b/features/facets/facets.php#L429-L453

So at line 451, something like:

```
$query_string = apply_filters( 'ep_facet_query_string', $query_string );
```

Happy to make a pull request for this.

**Comment by allan23** [comment]
Hi @ray-lee,

We would love a pull request for this.

**Comment by Salamander3** [comment]
I need exactly this too. Why is it closed? It doesn't seem implemented.

**Comment by Salamander3** [comment]
For future me and someone with same issue. If you created your own query vars you can add them to the facets like so:
1) Make sure you register your keys, mine is called sorted:
```
//add get params to query var
add_filter('query_vars', 'add_my_var');
function add_my_var($public_query_vars) {
    $public_query_vars[] = 'sorted';
    return $public_query_vars;
}
```

2) Modify facets code. i don't know how to filter this otherwise:
Around 437 add:

```
	$sorted = get_query_var('sorted');
	
	if ( ! empty( $sorted) ) {
		$query_string .= 'sorted=' . $sorted;
	}
```
