### ISSUE TITLE
Ensure Autosuggest defaults to plugin settings

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#1205]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Feature Request

Describe the issue you encountered:
The autosuggest feature does not implement the same defaults that were set by other functions and requires additional filters to ensure consistent behavior.

Looking at https://github.com/10up/ElasticPress/blob/develop/features/autosuggest/autosuggest.php#L198 you can see that instead of using ep_get_indexable_post_types(), ep_get_indexable_post_status() it defaults to hardcoded values. These values should be changed to the ep_get_indexable_..() functions to ensure consistent behavior.

**Comment by joelrendall** [comment]
Hi, I hope it's ok to comment here. I'm seeing this message in my dashboard _(Autosuggest feature is enabled.… "Use safe values" checkbox in Autosuggest settings to default to safe content search)_ 

However, I can't see this checkbox in the autosuggest settings. 
<img width="618" alt="Screenshot 2020-05-12 15 45 38" src="https://user-images.githubusercontent.com/8376419/81707289-747bc700-9468-11ea-9dc8-7513a7d0f99a.png">

Apologies if I'm crazy and looking in the wrong place. Just wanted to make sure it wasn't moved or removed at some point. Thanks in advance!
