### ISSUE TITLE
Misleading requirements

### ISSUE THREAD

**Issue by Salamander3** [10up/ElasticPress#1213]
https://github.com/10up/ElasticPress#requirements
Why oh WHY don't you write right there that anything above 6.3 will not work properly? Isn't that the freaking point of the requirements? You gotta install latest elasticsearch to find out is not compatible. Who decides not to include this vital information and keep it to himself?

**Comment by speedwheel** [comment]
@Salamander3 what is the latest verion of Elasticsearch that is supported?

**Comment by brandwaffle** [comment]
@Salamander3 thank you for your suggestion. We always welcome suggestions and bug reports, and ask only that you raise them in a civil way so as to promote positive discourse.

We can add a "max Elasticsearch version supported" line to the Readme in the next release of the plugin, which I think should address this issue.

**Comment by brandwaffle** [comment]
@speedwheel currently we support up to version 6.3 of Elasticsearch. Elastic does tend to push a lot of new versions which can break backwards compatibility, so we do test a bit before we bump version support. We'll include the max supported version in future releases.

It's always worth testing with a newer version if you want the latest and greatest Elasticsearch--simply disable the version check. Just keep in mind there might be some less-obvious compatibility issues and our ability to provide support might be a bit slower.

**Comment by speedwheel** [comment]
@brandwaffle Thank you for your reply, I understand now, I am looking to test this plugin out, and it's good to know this.

**Comment by Salamander3** [comment]
@brandwaffle I'm sorry i snapped i'm not a Linux pro so it took me a while to get everything working only to find out i wasted my time and had to start over.
Won't happen again.

**Comment by brandwaffle** [comment]
@Salamander3 no worries--Elasticsearch is not easy to set up and I've been there too :)

Your point is a good one and we're definitely going to include a max version going forward.

**Comment by Salamander3** [comment]
I just finished syncing and yes it works, bypasses MySQL but the search results are nowhere near as good as WordPress. It just returns hundreds of irrelevant posts.
Setting search to "disabled" has no effect i had to deactivate the plugin to make it stop.

Is there any way for me to tweak how it searches?

**Comment by brandwaffle** [comment]
@Salamander3 yes, you can create [custom search weighting](https://github.com/10up/ElasticPress/wiki/Weighting-Search-Results) by using the filters in the plugin, as well as[ add synonyms](https://github.com/10up/ElasticPress/wiki/Synonym-Analyzer) to create better results.
