### ISSUE TITLE
How to require ALL words instead of ANY words

### ISSUE THREAD

**Issue by espechtcfe** [10up/ElasticPress#1214]
Our wordpress site uses elasticpress for search and when more than one word is entered, any posts that contain ANY of the words are returned.  I'm trying to figure out how to make it so that ALL of the words are required, but not necessarily in the order provided.

10Up suggested this code for this purpose, however this only matches an exact phrase:

`add_filter( 'ep_formatted_args', __NAMESPACE__ . '\set_to_exact', 10, 2 );
function set_to_exact( $formatted_args, $args ) {
	if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
		$formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
		unset( $formatted_args['query']['bool']['should'] );
	}
	return $formatted_args;
}`

Does anyone have any ideas on how ElasticPress can require all of the words in any order?

**Comment by oscarssanchez** [comment]
Hi @espechtcfe 

Try this and it will require all of the words in any order:


```

function set_to_exact( $formatted_args, $args ) {
    if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
        $formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
        $formatted_args['query']['bool']['must'][0]['multi_match']['operator'] = 'AND';
        unset( $formatted_args['query']['bool']['should'] );
        unset( $formatted_args["query"]["bool"]["must"][0]["multi_match"]["type"] );
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );
```

For further precision tweaking, you can check this page: https://www.elastic.co/guide/en/elasticsearch/guide/current/match-multi-word.html

And adjust the array accordingly.

Thanks for raising the question, and hope you have an awesome day!

**Comment by espechtcfe** [comment]
Thank you so much, oscarssanchez!  This is working beautifully!

**Comment by Salamander3** [comment]
@oscarssanchez Could this be modified to match partial words? Example:
If someone searches for "Eur" but he meant "Europe" it will not find anything. Wp default search finds partial matches. How to do it in elasticpress?
