### ISSUE TITLE
ElasticPress errors out when excluding posts from homepage

### ISSUE THREAD

**Issue by willstocks-tech** [10up/ElasticPress#1216]
_Originally posted by @willstocks-tech in https://github.com/10up/ElasticPress/issues/1193#issuecomment-456304060_

@oscarssanchez / @allan23 - I've managed to identify the issue:
```
function excludeCat($query) {
	if ( $query->is_home ) {
		$query->set('cat', '-10');
	}
	return $query;
}
add_filter('pre_get_posts', 'excludeCat');
```

I'm excluding a specific list of posts that have a specific category set, from displaying on my home page. Why would this throw off EP?!

Is there anything I can do to alleviate this issue? I'd rather not have to show those posts on my homepage (I can, but I'd prefer not to)

**Comment by willstocks-tech** [comment]
Hey @oscarssanchez 

Yeah - I'll grab the output shortly for you :) I do have this output already: https://github.com/10up/ElasticPress/issues/1193#issuecomment-451984973 but I'll grab a "newer" one for you!

**Comment by allan23** [comment]
Hi @willstocks-tech, have you tried changing the query to use `category__not_in` instead of setting `cat` to `-10`?

https://codex.wordpress.org/Class_Reference/WP_Query#Category_Parameters

**Comment by willstocks-tech** [comment]
Admittedly, no - I haven't!

The code I have currently was based on: https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts

I can rewrite it as (?):
```
function excludeCat($query) {
	$exclude = array(10);
	if( is_home() ) {
	 	 set_query_var('category__not_in', $exclude);
	}
	return $query;
}
add_filter('pre_get_posts', 'excludeCat');
```

**Comment by willstocks-tech** [comment]
An alternative to the above (even though the codex pages aren't being much help here for me!):

```
function excludeCat($query) {
  if ($query->is_home() && $query->is_main_query()) {
    $query->set('category__not_in', array(10));
  }
//return $query //Is this needed?
}
add_action('pre_get_posts', 'excludeCat');
```
Based on: https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts again

Because I'm doing this in `functions.php`, not a theme file... would either this or the above be OK in terms of EP?

**Comment by allan23** [comment]
@willstocks-tech, please give the first one a shot and let us know.

**Comment by willstocks-tech** [comment]
Leave it with me, I'll change it shortly! (apologies for the delayed response - manic few days!)

**Comment by willstocks-tech** [comment]
First one didn't work at all - It returned a single post!
I have now applied:
```
function excludeCat($query) {
	if( is_home() ) {
	 	 set_query_var('category__not_in', array(10));
	}
	return $query;
}
add_filter('pre_get_posts', 'excludeCat');
```
And I had to re-sync EP... but so far it's looking OK: https://willstocks.co.uk

**Comment by willstocks-tech** [comment]
So far, so good! EP appears to be working without an issue now. Searches return as expected (although I need to triple check whether posts in category 10 return in the search results - I assume they do) and the homepage/all other pages now show my content as I would expect!

To confirm, the function I ended up having to use (to exclude my categories) was:
```
function excludeCat($query) {
	if( is_home() ) {
	 	 set_query_var('category__not_in', array(10));
	}
	return $query;
}
add_filter('pre_get_posts', 'excludeCat');
```
