### ISSUE TITLE
UI / Css is messed up 

### ISSUE THREAD

**Issue by jasonbronson** [10up/ElasticPress#1217]
Have you searched for similar issues before submitting this one?
yes

Is this a bug, question or feature request?
bug

Describe the issue you encountered:
css / ui is messed 

Current WordPress version:
4.9
Current ElasticPress version:
Version 2.7.0 
Current Elasticsearch version:
 Elasticsearch version 6.5.4
Where do you host your Elasticsearch server:
locally
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Yoast
Steps to reproduce:

1. Install latest version 
2. Activate
3. See css issue

Screenshots, if needed:
https://gyazo.com/e4eb714c5ccf16cae367c0fa41c6ff75

**Comment by oscarssanchez** [comment]
Hi @jasonbronson , 

It looks like` ep_admin_styles-css` is not loading on your side. How did you install ElasticPress?

Unfortunately i could not reproduce this.

Thanks for raising the question and have a good day!

**Comment by jasonbronson** [comment]
It must of been a caching issue it loaded finally.
