### ISSUE TITLE
VIP Go status?

### ISSUE THREAD

**Issue by jonathanstegall** [10up/ElasticPress#1218]
Have you searched for similar issues before submitting this one? Yes. There was an older discussion in #800.

Is this a bug, question or feature request? Question

Describe the issue you encountered:

Current WordPress version: 5.0.3

Current ElasticPress version: 2.7.0

Current Elasticsearch version: I'm not sure what version VIP Go runs.

Where do you host your Elasticsearch server: VIP Go

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): We have a lot of these. One relevant plugin may be Jetpack.

**Question**

I'm wondering if you have learned any further information about running ElasticPress on WordPress.com VIP Go hosts. I believe it should be possible, but I'm having trouble finding out what the details would be like. I plan to investigate further with folks at Automattic as well, but was hoping to learn if you had any further information after the blockers mentioned in previous issues were resolved. Is it as simple as enabling the plugin in VIP? If it is, is there a convention for how to configure the host and index that ElasticPress use?

**Comment by tlovett1** [comment]
ElasticPress has been used on VIP Go previously. I would just reach out to VIP and ask them what next steps for using it are.
