### ISSUE TITLE
[Question] How to use same elasticsearch server with multiple WP installations?

### ISSUE THREAD

**Issue by RetroGameTalk** [10up/ElasticPress#1219]
Hello, i've a simple question. I got Elasticpress to work on 1 WP Site just fine.
If i want other websites to use the same server do i just install Elasticpress and index them?
Or do i need to do something else first? I don't want results to mix, Each site must search on it's own posts.

**Comment by oscarssanchez** [comment]
Hi @Salamander3 ,

Yes, you can index many site's content into one Elasticsearch cluster. Keep in mind the performance of your server (hence, your site) might suffer depending on the characteristics of your server, traffic and requests made to Elasticsearch.

Your information will not mix between sites, as all data from each WordPress site is stored separately.

Thanks for raising the quesiton, and have a good day

**Comment by Salamander3** [comment]
Alright so when i run elasticpress on a new site it will create it's own separate index.
I have a dedicated VPS for elasticsearch different than the webserver.
I will monitor CPU/Memory usage, so far it's mostly idle despite of the constant search queries. Unlike MySQL on WP Database that was filling my slow queries log. You guys are legends.

**Comment by sorrow-poetry** [comment]
hello, sorry for opening this issue again. but i wanna know if there is a way to customize the indexes name for each WP site
to recognize each website.
