### ISSUE TITLE
How to do case insensitive searches

### ISSUE THREAD

**Issue by tamara-m** [10up/ElasticPress#1225]
**Have you searched for similar issues before submitting this one?**
Yes.

**Is this a bug, question or feature request?**
Question

**Describe the issue you encountered:**

I am looking to how to modify ElasticPress to do case insensitive searches with tax_query.
I want users to type their search "soccer" and receive posts with that taxonomy term using `'field' => 'name'`  (using slug seems to make things more complicated).

The term was saved as "**S**occer", capital "S" (users save these and we have no control of how they enter them)

I want users to type in "soccer", "Soccer", or "SOCCER" or whatever lowercase/uppercase combo and still get the results corresponding to "Soccer".

Right now, you must type in exactly "Soccer" with capital "S" to get the results, any other way except what matches the term name exactly doesn't return any results. 

Was wondering if you could guide me a little on how to achieve this. If this could be then turned into a PR with a new filter or something, I'd be happy to develop it and contribute. 

Thank you

**Comment by tamara-m** [comment]
Think I found the answer, is playing around with` ep_config_mapping`

**Comment by GhostToast** [comment]
@tamara-m I'm curious what your fix was ultimately

**Comment by tamara-m** [comment]
@GhostToast it ended up being something else entirely. Although I started looking at that filter, in the end I got the standard 's' search to work (which didn't at that time), and so I didn't need to take care of matching the cases. In case it helps, what I did was add the taxonomy to the 's' search fields like this:

```
'search_fields' => array(	'taxonomies' => array('my_tax') )
```
Hope this helps.
