### ISSUE TITLE
Autosuggest Endpoint URL

### ISSUE THREAD

**Issue by willstocks-tech** [10up/ElasticPress#1226]
### Have you searched for similar issues before submitting this one?
Yes

### Is this a bug, question or feature request?
Question

### Current WordPress version:
5.0.3

### Current ElasticPress version:
Latest

### Current Elasticsearch version:
5.4

### Where do you host your Elasticsearch server:
localhost

### Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

###Steps to reproduce:

The question:
I'm trying to setup autosuggest, but it prompts me to enter an endpoint URL. I'm not using the service that is linked to, but I want to use my local elasticsearch (I have no protected content to worry about). I can't find any documentation on how to configure this. I've assumed http://localhost:ESPort but it doesn't seem to play ball!

Can you confirm how I can do this? Do I need to register a RestAPI route and pass off the autosuggest to that? Server level config (apache/nginx)?

**Comment by willstocks-tech** [comment]
This is currently what I'm looking at, but want to confirm this is the correct method to implement: https://github.com/grossherr/elasticpress-autosuggest-endpoint/blob/master/elasticpress-autosuggest-endpoint.php

**Comment by oscarssanchez** [comment]
Hi @willstocks-tech, these links might help:

https://florianbrinkmann.com/en/4714/autosuggest-elasticpress-apache/
https://github.com/10up/ElasticPress-Autosuggest

Best regards,
