### ISSUE TITLE
No posts found using autocomplete

### ISSUE THREAD

**Issue by aaemnnosttv** [10up/ElasticPress#1231]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
Searching for posts using autocomplete did not return any results when it should have easily matched a common term.

Current WordPress version:
5.0.3

Current ElasticPress version:
Latest `dev-develop` 8fa0e5b1a4a527346ae7a3fda6252d7e38ac7639

Current Elasticsearch version:
5.6.5

Where do you host your Elasticsearch server:
WP Local Docker v2

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
n/a

Steps to reproduce:

1. Configure autocomplete like so  
![](https://user-images.githubusercontent.com/31049169/51547267-8bd61180-1e2b-11e9-88f9-9dc58b8e0a51.png)
2. Try a search for any term
3. Results come back as no match

Root cause found here, introduced in #1211 

https://github.com/10up/ElasticPress/blob/0f107486bd7ee175b2b8000b694b65b9fd16384c/features/autosuggest/autosuggest.php#L211-L212

**Comment by oscarssanchez** [comment]
Closed via #1232
