### ISSUE TITLE
Search HTML

### ISSUE THREAD

**Issue by cbratschi** [10up/ElasticPress#1238]
Have you searched for similar issues before submitting this one?
Yes.

Is this a bug, question or feature request?
A question.

Describe the issue you encountered:
Currently the default analyzer strips HTML code. This is normally fine but we have a use case where we are searching specific attributes. Is there a simple way to cover this case?

Current WordPress version:

Current ElasticPress version:

Current Elasticsearch version:

Where do you host your Elasticsearch server:

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi @cbratschi 

Maybe adding a custom analyzer like it is described here:
https://github.com/10up/ElasticPress/wiki/Synonym-Analyzer

With this in mind: 
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/analysis-htmlstrip-charfilter.html

Kind regards,

**Comment by cbratschi** [comment]
Yes, we already changed this and excluded all iframes from being removed. This works fine.
