### ISSUE TITLE
EP 2.8.0 reordering homepage posts

### ISSUE THREAD

**Issue by willstocks-tech** [10up/ElasticPress#1239]
Have you searched for similar issues before submitting this one?

Yes

Is this a bug, question or feature request?

Bug (sorry, it’s a bit of a skeleton as I’m currently mobile!!!)

Describe the issue you encountered:

Just upgraded to 2.8.0 (lastest release - via mobile, I know my bad!) and my list of posts has now been sorted into a random order on my homepage (again - no search has been made, for some reason EP has restructured my homepage). I have had to temporarily disable and will rollback to 2.7.0 later

Current WordPress version:

5.0.3

Current ElasticPress version:

2.8.0

Current Elasticsearch version:

5.something (I will confirm exact version number later)

Where do you host your Elasticsearch server:

Localhost 

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Will get a list shortly (I’m on mobile at the moment so it’s not the easiest task!)

Steps to reproduce:

1. Have EP 2.7.0 + homepage as blog feed
2. Upgrade to EP 2.8.0
3. View homepage and notice that random posts are now being shown, rather than latest and chronological.

Screenshots, if needed:

Will grab later on - the only thing I’m aware of that EP has ever been concerned about before is:
https://github.com/10up/ElasticPress/issues/1216

**Comment by allan23** [comment]
@willstocks-tech can you confirm this is happening outside of your theme and custom codebase?

**Comment by Salamander3** [comment]
Exact same thing.
Updated to 2.8 and the homepage posts are sorted randomly. So, i rebuilt the index, no change.

Downloaded 2.7 uploaded it, refresh page, posts back to normal order (latest first).
My homepage is WordPress default "latest posts" on settings reading, not a static page or custom loop. Woocommerce not installed, regular WP.

**Comment by willstocks-tech** [comment]
@allan23 - I will go through the ol’ functions.php again to see if I can whittle it down - I haven’t been able to test with an alternate theme as it was in production (I know, I know).

Is there  a specific change/hook/filter that may have changed that I should keep an eye out for that may result in this behaviour? I can’t quite work it out from the commit messages between 2.7 and 2.8 and I would prefer to not have to parse through the diffs 😂

**Comment by allan23** [comment]
Hey @willstocks-tech  and @Salamander3,

We believe we have found the root cause of this issue and have prepared a pull request that should resolve it.

https://github.com/10up/ElasticPress/pull/1245

Would it be possible for you to test this PR  to see if it resolves your issues?

**Comment by willstocks-tech** [comment]
Hi Allan,

I’ll grab a copy and will give it a go - is it only the one file change that is necessary?

I don’t use sticky posts - is that the reason for the issue?

**Comment by allan23** [comment]
We believe that the logic for this feature is the cause whether or not a site uses sticky posts.

**Comment by willstocks-tech** [comment]
Hi @allan23 - I’m so sorry, I haven’t had a chance to test this out! :( I noticed that a new version of EP is now available publicly - I’ve been busy with other projects this last week and have just migrated to a new server stack (doesn’t yet include ES - but will do soon!) so I’ll update ASAP (next couple of days) and will confirm back for you!
Cheers
Will

**Comment by Salamander3** [comment]
I can confirm 2.8.1 solves it.
