### ISSUE TITLE
Admin status page

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#124]
Would be helpful to show whether or not ElasticPress is currently replacing search. Additional future uses could be settings/reindexing commands as well as showing usage and searches performed.

**Comment by AaronHolbrook** [comment]
Could allow enabling and disabling of things like autosuggest and admin search (if either of these are placed into the core plugin)

**Comment by ivankruchkoff** [comment]
So when working on #1 I imagined it having this functionality too, and yes a status page rather than a widget.

https://github.com/ivankruchkoff/ElasticPress/commit/a1c3435d998c872e6c6e551b13d9feabc290477f contains the start of this functionality

**Comment by tlovett1** [comment]
@ivankruchkoff what do you imagine the status page showing?

**Comment by ivankruchkoff** [comment]
Any useful stats we can get from the ES hosts:

* Info about all indices (size, num shards, num replicas, num docs) -- for multisite, only for the current site
* Top searches (by week, month, all time) per index.
* health check (up / down)

If possible:
 * query times (mean / peak load)
 * num elasticpress queries compared to num of regular wordpress search queries

**Comment by tlovett1** [comment]
Health check, plus index info is good. Top searches is not possible as far as I know without adding another layer of complexity.

**Comment by allan23** [comment]
Given we have the GUI indexing page, is this issue still valid?

**Comment by AaronHolbrook** [comment]
Nope, that's exactly what was meant here.

I would love to see more information - maybe break out the other features into separate tickets?

**Comment by allan23** [comment]
Let's have separate issues to admin page enhancements. Closing this one.

**Comment by AaronHolbrook** [comment]
Perfect, thanks @allan23
