### ISSUE TITLE
Removal of mapping types

### ISSUE THREAD

**Issue by MrEfrem** [10up/ElasticPress#1246]
Have you searched for similar issues before submitting this one?
yes
Is this a bug, question or feature request?
question

Have you got a plan to remove of mapping types and when?
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types

**Comment by oscarssanchez** [comment]
I think this would need to be addressed when adding compatibility for new ES versions. 
There has not been a discussion when this is going to be implemented.

Thanks for the heads up!
