### ISSUE TITLE
Is there any way to display result type in autosuggest search?

### ISSUE THREAD

**Issue by andreirebe** [10up/ElasticPress#1251]
Have you searched for similar issues before submitting this one?
yes
Is this a bug, question or feature request?
question
Describe the issue you encountered:

I have two questions:

1. Is there any way to display result type in autosuggest search? For example if I search for Car and i have car in woocommerce products to show me next to the result [product] and I have a car post to show me next to the result [post]

2. How can I weight the result to show me exact matches from title prior to other results?
<img width="321" alt="screenshot 2019-02-14 at 22 36 36" src="https://user-images.githubusercontent.com/1461693/52816079-17e4fd00-30a9-11e9-992a-8ecc7c76c07c.png">

I searched for "plic b4" but the first result is "plic c7"

Current WordPress version:
latest
Current ElasticPress version:
5.0.3
Current Elasticsearch version:
5.4

**Comment by fabianmarz** [comment]
Looking at the [autosuggest.js](https://github.com/10up/ElasticPress/blob/develop/assets/js/autosuggest.js#L331-L334) code, there's currently no option to customise the search results.

**Comment by fabianmarz** [comment]
As I'm blocked by this issue I came up with the following approach:

```js
var filteredObject = jQuery( document ).triggerHandler( 'elasticpress.searchItem.filter', element ) || {
  'text': text,
  'url': url
};
filteredObjects.push( filteredObject );
```

As triggerHandler will return `undefined` in case no handlers are triggered I'm using the common practice pattern to assign a default value. 

See [docs](http://api.jquery.com/triggerhandler/) for more informations.

@oscarssanchez, @tlovett1 what's your opinion about this?

**Comment by fabianmarz** [comment]
@tlovett1, why did your close this without any reaction on it? 🤷‍♂

**Comment by fabianmarz** [comment]
@tlovett1, as there is still no way to modify the search results in the most recent version could you please give a short statement about my suggestion as you closed this issue without commenting it. In order to be able to replace SearchWP properly, we need to rely on adjusting the search results template.

Here's the code I prepared for the most recent EP version to add new data to the search items and be able to adjust the template:
```diff
diff --git a/wp-content/plugins/elasticpress/assets/js/autosuggest.js b/wp-content/plugins/elasticpress/assets/js/autosuggest.js
index d39674981..b29af1708 100644
--- a/wp-content/plugins/elasticpress/assets/js/autosuggest.js
+++ b/wp-content/plugins/elasticpress/assets/js/autosuggest.js
@@ -197,6 +197,18 @@ function escapeDoubleQuotes( str ) {
 	return str.replace( /\\([\s\S])|(")/g, '&quot;' );
 }
 
+/**
+ * Prepares the template for a single list item.
+ *
+ * @param data The data to use in the template
+ * @returns string The item template string
+ */
+function itemTemplate ( data ) {
+	let template = `<span class="autosuggest-item" data-search="${  escapeDoubleQuotes( data.text )  }" data-url="${ data.url }">${  escapeDoubleQuotes( data.text )  }</span>`;
+	template = jQuery( document ).triggerHandler( 'elasticpress.searchItem.template', [ template, data ] ) || template;
+	return `<li> ${ template } </li>`;
+}
+
 /**
  * Update the auto suggest box with new options or hide if none
  *
@@ -222,8 +234,7 @@ function updateAutosuggestBox( options, $localInput ) {
 	}
 
 	for ( i = 0; i < options.length; ++i ) {
-		const { text, url } = options[i];
-		itemString += `<li><span class="autosuggest-item" data-search="${  escapeDoubleQuotes( text )  }" data-url="${  url  }">${  escapeDoubleQuotes( text )  }</span></li>`;
+		itemString += itemTemplate( options[i] );
 	}
 	jQuery( itemString ).appendTo( $localSuggestList );
 
@@ -434,10 +445,12 @@ if ( epas.endpointUrl && '' !== epas.endpointUrl ) {
 							if( ! usedPosts[ postId ] ) {
 								usedPosts[ postId ] = true;
 
-								filteredObjects.push( {
+								const searchItem = {
 									'text': text,
 									'url': url
-								} );
+								};
+								const filteredObject = jQuery( document ).triggerHandler( 'elasticpress.searchItem.filter', [searchItem, element] ) || searchItem;
+								filteredObjects.push( filteredObject );
 							}
 						} );
 

```

**Comment by fabianmarz** [comment]
@brandwaffle, as mentioned in #1620 here is the desired look of the search results which we currently achieve by using SearchWP.

We have a (scrollable) container containing the following information:
- Product title
- Product image
- Meta key/value pairs (delivery time, price, sale price)

![image](https://user-images.githubusercontent.com/863823/72277635-8a03f000-3632-11ea-9465-898a469ad091.png)

Would be great if we can find some approach to achieve some customisations

**Comment by brandwaffle** [comment]
@fabianmarz thanks for the example! What I'm looking at looks more like dynamic search results refreshed via AJAX and appearing in the same place normal results would. If this is the case, we are working on an AJAX results feature and would likely be able to accomplish what you're doing here quite easily, as this new feature would simply use a template partial for your theme to generate each AJAX result. If this is really "autosuggest" specifically, as in when I click for "alle Ergebnisse" I would see a list of results in a _different_ format, then we'll need to do a bit more thinking about how to execute on this.

**Comment by fabianmarz** [comment]
Wow sorry. I think I got it now 🙈 Those are two different kind of concepts which I misused and misunderstood as I just saw the AJAX live results and thought it would do the job. On our current implementation typing "tisch" in the search bar shows the same results as calling the WP search results page `?s=tisch&post_type=product` which will be redirect to, when clicking "alle Ergebnisse". This is what we want to keep.

The results page looks the following:
![image](https://user-images.githubusercontent.com/863823/72294976-f0026e80-3656-11ea-84be-dbd6ae4f49e8.png)

Currently we're using some WooCommerce filters in the sidebar to narrow down the results. Those should be exchanged with the facets widget provided by EP.

Is there a schedule when the AJAX results feature mentioned by you will be rolled out?

**Comment by hedqvist** [comment]
@brandwaffle Any update regarding 

> we are working on an AJAX results feature and would likely be able to accomplish what you're doing here quite easily, as this new feature would simply use a template partial for your theme to generate each AJAX result

Would be great if we could implement lets say "Product Image" here in the autosuggest results.

**Comment by hedqvist** [comment]
@fabianmarz Was there a solution where you managed to use autosuggest and change the looks of results? I'm mainly after a solutin where I can add Product Image and price to the results...

**Comment by fabianmarz** [comment]
@hedqvist, I hacked the plugin code myself. I basically added the changes I commented in this issue but switched over to an AJAX search (instead of the autosuggest feature) and thus dropped it in the end. I'm not sure if any adjustments to the autosuggest template are possible by now.

**Comment by hedqvist** [comment]
I see, thanks for a quick reply @fabianmarz, but you are still using it as of today? I looked into your site and it seems to display suggestion/results in a nice way. Both with price and product image.

**Comment by shmaltz** [comment]
Is displaying autosuggest results with a featured image (or meta field) still not possible?

**Comment by brandwaffle** [comment]
@shmaltz the issue around product image is more complicated than simply editing the JSON results, as the product image URL is not stored in WordPress' meta and therefore only the attachment ID is available in the JSON. For all other fields, you can use this approach to display other meta https://gist.github.com/brandwaffle/e211ba57cc2b09ab4435d4ccd2ed1df1. Please note that you can also use this approach to display the meta if you filter in the image URL during index time (you can add a thumbnail URL for your desired crop size as meta and it will be accessible the same as the other fields in the example JS).

**Comment by shmaltz** [comment]
Thank you @brandwaffle.

How would I use that code? Do I have to edit `autosuggest.js`?
