### ISSUE TITLE
Issues when searching in taxonomie

### ISSUE THREAD

**Issue by ccournoyer-oktane** [10up/ElasticPress#1252]
When i search the word "bioprote" I get 0 result, if i search for "Bioprotec" I get 25 results.
Bioprotec is a term in the product_cat taxonomy.
I checked with the debug bar plugin and the search_fields are set correctly
![capture d ecran le 2019-02-14 a 15 48 08](https://user-images.githubusercontent.com/24938235/52816853-2bc03d00-3070-11e9-9049-52d100891bf8.png)

Site is hosted on cloudways

**Comment by brandwaffle** [comment]
@ccournoyer-oktane any chance you can include the additional information in the intake form including the versions of ElasticPress and Elasticsearch you're running? Thanks!

**Comment by ccournoyer-oktane** [comment]
Sure, running ElasticPress 2.8.1 and Elasticsearch 5.4

**Comment by brandwaffle** [comment]
Thanks @ccournoyer-oktane that rules out the sticky posts issue that existed in 2.8.

Are you able to post the results of the EP JSON query that is generated (it's the option right below the EP Debug Bar option that outputs the WP Query array). That will tell us if the computed query is properly formatted.

**Comment by brandwaffle** [comment]
@ccournoyer-oktane one other question: are you running WooCommerce and if so, is the WooCommerce feature in ElasticPress active or turned off?

**Comment by ccournoyer-oktane** [comment]
We are running Woocommerce and the option is activated in ElasticPress.
For the EP JSON, I'm not sure if this is the correct info but here the Query result:
{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "terms": {
            "doc_count": 0,
            "product_tag": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "pa_type-de-commande": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "post_format": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "product_cat": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "category": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "product_shipping_class": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            },
            "post_tag": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            }
        }
    }
}

**Comment by ccournoyer-oktane** [comment]
Hi i was wondering if there is some kind of premium support?

**Comment by ccournoyer-oktane** [comment]
@brandwaffle for the EP JSON, I'm not sure if this is the correct info but here the Query result:
{
"took": 5,
"timed_out": false,
"_shards": {
"total": 5,
"successful": 5,
"failed": 0
},
"hits": {
"total": 0,
"max_score": null,
"hits": []
},
"aggregations": {
"terms": {
"doc_count": 0,
"product_tag": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
},
"pa_type-de-commande": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
},
"post_format": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
},
"product_cat": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
},
"category": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
},
"product_shipping_class": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
},
"post_tag": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
}
}
}
}

**Comment by brandwaffle** [comment]
@ccournoyer-oktane we do provide premium support at an hourly rate. You can reach out to sales@elasticpress.io if you'd like to learn more!

For this issue, I'm actually looking for the query that EP sends over to the Elasticsearch server, rather than the response. You'll see an option right above the one you pasted that says "Query Body" rather than "Query Result." If you can paste that into here, it will tell us exactly the query that ElasticPress is trying to make through Elasticsearch.

**Comment by ccournoyer-oktane** [comment]
@brandwaffle here the query 
{
    "from": 0,
    "size": 20,
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": "bioprote",
                        "type": "phrase",
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.product_cat.name",
                            "terms.pa_taille.name",
                            "meta._sku.value",
                            "meta.category.value",
                            "meta.post_tag.value",
                            "meta.product_tag.value",
                            "meta.product_cat.value"
                        ],
                        "boost": 4
                    }
                },
                {
                    "multi_match": {
                        "query": "bioprote",
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.product_cat.name",
                            "terms.pa_taille.name",
                            "meta._sku.value",
                            "meta.category.value",
                            "meta.post_tag.value",
                            "meta.product_tag.value",
                            "meta.product_cat.value"
                        ],
                        "boost": 2,
                        "fuzziness": 0,
                        "operator": "and"
                    }
                },
                {
                    "multi_match": {
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.product_cat.name",
                            "terms.pa_taille.name",
                            "meta._sku.value",
                            "meta.category.value",
                            "meta.post_tag.value",
                            "meta.product_tag.value",
                            "meta.product_cat.value"
                        ],
                        "query": "bioprote",
                        "fuzziness": 0
                    }
                }
            ]
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must_not": [
                            {
                                "terms": {
                                    "terms.product_visibility.term_taxonomy_id": [
                                        18223
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "term": {
                        "post_type.raw": "product"
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                },
                {
                    "term": {
                        "post_lang": "fr"
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "bool": {
                                "must_not": [
                                    {
                                        "terms": {
                                            "terms.product_visibility.term_taxonomy_id": [
                                                18223
                                            ]
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "term": {
                                "post_type.raw": "product"
                            }
                        },
                        {
                            "terms": {
                                "post_status": [
                                    "publish",
                                    "acf-disabled"
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                },
                "pa_type-de-commande": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_type-de-commande.slug"
                    }
                }
            }
        }
    }
}

**Comment by ccournoyer-oktane** [comment]
@brandwaffle Honestly i dont know what could cause the issues. Query argument is pretty basic.

**Comment by brandwaffle** [comment]
@ccournoyer-oktane I'm still hoping to take an in-depth look before the end of the week, but in the meantime I did notice the "fuzziness" is set to 0 on all queries. Are you doing anything to set that or is that the default behavior of the plugin?

**Comment by ccournoyer-oktane** [comment]
I had this filter :
`add_filter( 'ep_fuzziness_arg', function () {
    return 1;
 }, 10, 0 );`
to set it to 1.
I disabled it but it does'nt appear to change anything
I did another test by re-adding the filter but instead of 1 i set the fuzziness to to 
`add_filter( 'ep_fuzziness_arg', function () {
    return 2;
}, 10, 0 );`
With it i'm able to get the correct result with single word search.
But now if I search an word like "Coq" I get all the product as result.
Same thing if I search "Coq cuivre", I will get all the result for either Coq or cuivre. instead of result matching both result.
Here the new query body after setting the filter to 2

`add_filter( 'ep_fuzziness_arg', function () {
    return 2;
}, 10, 0 );`

**Comment by ccournoyer-oktane** [comment]
@brandwaffle I was was able to solve most of my problem by setting fuzziness to 2 and by adding an filter to disable elasticpress when displaying a taxonomy archive. Unfortunaly, I'm still stick with strange result when I make a search containing three letter word. 
When I search for "Coq cuivre" I get 2966 result instead of 3. The first 3 result are correct. However, following result will only match "Cuivre" then match nothing at all.
![capture d ecran le 2019-03-08 a 10 36 35](https://user-images.githubusercontent.com/24938235/54038274-1e3d3500-418e-11e9-8073-91a8951a9297.png)
 
`{
    "from": 0,
    "size": 20,
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": "coq cuivre",
                        "type": "phrase",
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.product_cat.name",
                            "terms.pa_taille.name",
                            "meta._sku.value",
                            "meta.category.value",
                            "meta.post_tag.value",
                            "meta.product_tag.value",
                            "meta.product_cat.value"
                        ],
                        "boost": 4
                    }
                },
                {
                    "multi_match": {
                        "query": "coq cuivre",
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.product_cat.name",
                            "terms.pa_taille.name",
                            "meta._sku.value",
                            "meta.category.value",
                            "meta.post_tag.value",
                            "meta.product_tag.value",
                            "meta.product_cat.value"
                        ],
                        "boost": 2,
                        "fuzziness": 0,
                        "operator": "and"
                    }
                },
                {
                    "multi_match": {
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.product_cat.name",
                            "terms.pa_taille.name",
                            "meta._sku.value",
                            "meta.category.value",
                            "meta.post_tag.value",
                            "meta.product_tag.value",
                            "meta.product_cat.value"
                        ],
                        "query": "coq cuivre",
                        "fuzziness": 2
                    }
                }
            ]
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must_not": [
                            {
                                "terms": {
                                    "terms.product_visibility.term_taxonomy_id": [
                                        0
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "term": {
                        "post_type.raw": "product"
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                },
                {
                    "term": {
                        "post_lang": "fr"
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "bool": {
                                "must_not": [
                                    {
                                        "terms": {
                                            "terms.product_visibility.term_taxonomy_id": [
                                                0
                                            ]
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "term": {
                                "post_type.raw": "product"
                            }
                        },
                        {
                            "terms": {
                                "post_status": [
                                    "publish",
                                    "acf-disabled"
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                },
                "pa_type-de-commande": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_type-de-commande.slug"
                    }
                }
            }
        }
    }
}`

**Comment by brandwaffle** [comment]
@ccournoyer-oktane if you turn on autosuggest and do a test that way, do the results improve? I ask because the Autosuggest feature uses the ngram analyzer which is designed to handle partial queries. If you're getting better results that way, it might be worth switching to that analyzer for your main queries.

**Comment by ccournoyer-oktane** [comment]
@brandwaffle I turn it on and the index started rebuilding itself. Meanwhile, I did a few search and the result was perfect. But a soon as the index was done rebuilding, the problem came back.

**Comment by brandwaffle** [comment]
@ccournoyer-oktane so if you start to type 'coq' it does not autosuggest results that include 'coq cuivre'?

If the fuzziness approach is working somewhat well, you might look into this blog post https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/. It describes how you can filter the Elastic query to only match on all words, rather than just one. This should reduce the 2966 results down to just those that contain both 'coq' and 'cuivre.'

By the way, are you setting the language analyzer to 'French' via a filter? If not, that could be the whole issue here--if Lucene isn't able to detect the language it won't properly break down words and phrases for later search. You can use the `'ep_analyzer_language'` filter for this purpose.

**Comment by ccournoyer-oktane** [comment]
@brandwaffle Ok so i added the filter to limit result to full text matches and it did the trick
Search work as intented now.
Everything related to language is handled by wpml, so the option to integrate it in elasticpress is activated.
Thx a lot the help
