### ISSUE TITLE
Hook for additional Settings

### ISSUE THREAD

**Issue by technosailor** [10up/ElasticPress#1254]
**Have you searched for similar issues before submitting this one?**

Yes

**Is this a bug, question or feature request?**

Feature request

**Describe the issue you encountered:**

Working with a client who needs to provide additional options for connecting to their ES cluster. I realized there are no hooks to add additional settings to the settings page.

**Current WordPress version:**

5.0.1

**Current ElasticPress version:**

2.8.1

**Current Elasticsearch version:**

6.5.4

**Where do you host your Elasticsearch server:**

Heroku Bonsai

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):**

Nothing. Vanilla install.

I will be submitting a PR with a new hook shortly and will link this issue.

EDIT: PR - https://github.com/10up/ElasticPress/pull/1261

**Comment by technosailor** [comment]
@tlovett1 Anything more specific this PR would need to get it merged for the next release?

**Comment by brandwaffle** [comment]
@technosailor can you give an example of the type of settings you're looking to add here? Username and password auth are supported in the URL bar, or you can add ES_SHIELD credentials via wp-config.php.

I'm not opposed to adding the hook but want to make sure there's a solid case for it.

**Comment by technosailor** [comment]
@brandwaffle Sure. Initially, we are only supporting the basic auth settings, and it's true that this is already there. Though the idea is to make this stupidly simple for non-technical users, so we'd like to avoid `ES_SHIELD`. Longer term, we support multiple ES instances (failover, for instance) and domains. These may all, to the end of making it stupidly frictionless to the end user, get settings fields as well.

**Comment by brandwaffle** [comment]
@technosailor that makes a lot of sense. I think we can get this queued up for 3.0 cc @tlovett1

**Comment by technosailor** [comment]
Thanks @brandwaffle! 🎉

**Comment by technosailor** [comment]
@brandwaffle for the sake of managing my client's expectations, do you have a sense for when 3.0 will be released?

**Comment by brandwaffle** [comment]
@technosailor we're hoping to have the beta version out by the end of the week. Probably a few weeks after that for "official" release on WP.org.
