### ISSUE TITLE
Post editor show wrong post after plugin activation

### ISSUE THREAD

**Issue by ifsand** [10up/ElasticPress#1258]
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?
bug

Describe the issue you encountered:
after plugin activation  and  post syncronization to elasticsearch, when i try to edit any post , the editor show another post , different from the selected one.

Current WordPress version: 5.0.3

Current ElasticPress version: 2.8.1 

Current Elasticsearch version: 6.3

Where do you host your Elasticsearch server: bare metal server

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): 
AddToAny Share Buttons
Akismet Anti-Spam
Amazon Associates Link Builder
Author Image
Category Order and Taxonomy Terms Order
Cookie Notice
Custom Sidebars
Customizer Export/Import
EasyAzon
EasyAzon Pro
Google Analytics Dashboard per WP (GADWP)
Importatore convertitore da categorie a tag
Insert Headers and Footers
Magic Liquidizer Responsive Table
Nofollow for external link
OneSignal Push Notifications
Optimality
Popups - WordPress Popup
Responsive Pricing Table
Shortcodes Ultimate
Smush
T(-) Countdown
TinyMCE Advanced
Tradurre con Loco
W3 Total Cache
WP Comment Policy Checkbox
WPSSO Core [Main Plugin]
WPSSO Schema JSON-LD Markup
Yoast SEO

Steps to reproduce:

1.  install and enable elasticpress
2.  sync posts
3. try to edit any post

**Comment by tott** [comment]
Can you try to disable W3TotalCache and confirm if the issue persists. This will help us ruling out caching issues.

**Comment by ifsand** [comment]
yes the problem persist

**Comment by allan23** [comment]
Hello @ifsand, it sounds like you may have some kind of caching issue going on or a plugin conflict. Unfortunately, the next step you would need to take is to deactivate all plugins to determine which one is the culprit.
