### ISSUE TITLE
Auto index on post submit

### ISSUE THREAD

**Issue by dnikola** [10up/ElasticPress#1259]
Hello people, 

thanks for this amazing plugin.

This is more info question than issue, but since WP forum support page is not monitored I decided to post it here, sorry if my decision is wrong :)

Is it possible to make plugin auto index content when it is posted? 

Thanks!

**Comment by tott** [comment]
Hi, thanks for your feedback. After an initial sync the plugin will automatically sync all changes and additions.

**Comment by dnikola** [comment]
Hi @tott 

Thanks for your very fast replay! 

This are very good news. 

 - If i got a good point all query's even WP admin dash are served by Elastic (without additional customization?)
  -So actually if post is created by some kind of plugin it will be also sync or that plugin need to use some filter or action?
- Is all content sync (post, custom post's, comments, pages) and if yes are all data sync along with that post?

Once again thanks!

**Comment by tott** [comment]
As long as posts are created using regular WP APIs and running through the usual action/filter hooks ElasticPress will pick them up. If you have any plugins which work directly with the database and circumvent this behavior you can run into issues but other than that all post types returned here https://github.com/10up/ElasticPress/blob/2.8.1/classes/class-ep-config.php#L212 will be indexed. Comments, however, are not indexed.

**Comment by dnikola** [comment]
@tott  great, thanks!

And about comments, may i ask why ? :)

Thanks!

**Comment by allan23** [comment]
Hi @dnikola,
ElasticPress is configured to overwrite WordPress' WP_Query functionality. Most plugins abide by WP best practices by using WP_Query for all database interaction. However, if a plugin does not use it and instead uses $wpdb for a direct query, then ElasticPress cannot hijack it and perform the query on Elasticsearch.

Thank you for your inquiry.

**Comment by brandwaffle** [comment]
@dnikola Comments are likely to be added in upcoming versions. Once version 3.0 is released it makes it easier for additional content types to be added to the plugin.
