### ISSUE TITLE
How i can index attachments?

### ISSUE THREAD

**Issue by majestica** [10up/ElasticPress#1260]
Hi, first I want to say thanks for the great plugin. Tell me please, I noticed the attachments are not indexed, how can I enable attachment indexing? In order to search the media library faster, I have more than 200,000 images in attachments, and for me it is very important. Please give an example if it's not difficult for you. thank

P.S
I'm not sure what I did right, I added the code and reindexed, but I didn’t search the media library faster, probably I’m missing something :(
media files have a file name, Caption and description. on these fields will search?

```
add_filter('ep_indexable_post_status', function(){

    return array( 'publish', 'inherit' );

} );
```

**Comment by allan23** [comment]
Hello @majestica, can you verify that your Elasticsearch has the[ Ingest Attachment Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html)?

**Comment by majestica** [comment]
> Hello @majestica, can you verify that your Elasticsearch has the[ Ingest Attachment Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html)?

Hi, I did not try this plugin, since I don’t have anything in attachments except for png and jpeg, can I do without this plugin?

**Comment by majestica** [comment]
guys, can someone help me?

**Comment by oscarssanchez** [comment]
Hi @majestica , by checking this and this issue https://github.com/10up/ElasticPress/issues/674 i don't think searching on media library is something you can currently do. Can you confirm @allan23 ?

**Comment by wss-chadical** [comment]
fyi - I got media searching working on a elasticsearch 5.6, with an ingest node, plus the ingest attachment plugin.
