### ISSUE TITLE
Features turning itself of at some point

### ISSUE THREAD

**Issue by iDuuck** [10up/ElasticPress#1262]
**Is this a bug, question or feature request?** Bug/Question

**Describe the issue you encountered:**

I am currently hosting a page with an Elasticsearch-powered search for a client. It's now multiple times, that the Elasticpress plugin has disabled some options by itself. I am using the "Documents" feature a lot on this project, but at some point the feature turns of by itself and it is not searching for documents anymore. Is this a known bug?

**Current WordPress version:** 4.9.9 

**Current ElasticPress version:** 2.6.1

**Current Elasticsearch version:** 6.4.0

**Where do you host your Elasticsearch server:** On the same server.

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):** WooCommerce

**Comment by allan23** [comment]
Hi @iDuuck, this is the first we have heard about this. Any reason why you are not running the latest version of ElasticPress?

**Comment by iDuuck** [comment]
Don't want anything to break suddenly. But will give it a try now.

**Comment by sjeng** [comment]
I noticed the same behavior if for any reason Elasticsearch server is unreachable by the plugin.  Elasticpress will deactivate the Documents feature when that happens.

**Comment by iDuuck** [comment]
@sjeng Okay, strange one. Shouldn't really happen when on the same server, should it?

**Comment by iDuuck** [comment]
@allan23 It's actually a bug then, right?

**Comment by iDuuck** [comment]
Still not working, though. Just update the plugin.

**Comment by iDuuck** [comment]
Any update?
