### ISSUE TITLE
Woocommerce products disappears when plugin in enabled

### ISSUE THREAD

**Issue by jeffceriello** [10up/ElasticPress#1263]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Seems to be a bug

Describe the issue you encountered:
When the ElasticPress plugin is enabled, many of our products disappear from our online store. They only reappear when I disable ElasticPress.

Current WordPress version:
5.1

Current ElasticPress version:
2.8.1

Current Elasticsearch version:
6.2

Where do you host your Elasticsearch server:
self, on same host as website

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce, WP Fastest Cache and many more

Steps to reproduce:

1. Enable ElasticPress
2. Visit the shop pages

Screenshots, if needed:

**With plugin installed**
![screenshot 2019-02-24 at 11 25 48](https://user-images.githubusercontent.com/5859601/53298017-87848600-3827-11e9-9eb8-4f80958c878f.png)
![screenshot 2019-02-24 at 11 25 55](https://user-images.githubusercontent.com/5859601/53298020-91a68480-3827-11e9-9054-7d326e0cdda4.png)

**With plugin disabled**
![screenshot 2019-02-24 at 11 31 08](https://user-images.githubusercontent.com/5859601/53298029-bd296f00-3827-11e9-8c13-86ab49dd65f0.png)
![screenshot 2019-02-24 at 11 31 16](https://user-images.githubusercontent.com/5859601/53298031-c0bcf600-3827-11e9-8a7c-b3195edbe674.png)

==================================

Hi Oscar,

I did open this issue in December but it has been closed and I never got a reply to this https://github.com/10up/ElasticPress/issues/1175#issuecomment-456717129

Thank you

**Comment by oscarssanchez** [comment]
Hi @jeffceriello ,

Sorry about the lack of response, I did not get any other emails from this issue, but thanks for opening a new one.

First of all i'd really recommend not exposing your elasticsearch server like that, so if you could hide it, I think that would be better for you form a security standpoint.

Second, by looking at these responses, how many woocommerce products does your store has? 

Kind regards,

**Comment by jeffceriello** [comment]
Hi Oscar,

Thank you for your reply.

I have removed the elasticsearch server references from the comment.

There are around 11,800 products in the store.

Thanks

**Comment by oscarssanchez** [comment]
Hi @jeffceriello ,

I remember I saw about half that number of products on the links you provided. Can you re-index with wp-cli and check if there's any errors please? 

With this command:
`wp elasticpress index --setup --show-bulk-errors`

Thanks!

**Comment by jeffceriello** [comment]
Hi Oscar,

Thank you for your reply.

I managed to re-index via wp-cli and these are the results

```
[root@wardrobeicons-com public_html]# wp elasticpress index --setup --show-bulk-errors --allow-root
Success: Index deleted
Success: Mapping sent
Indexing posts...
Processed 350/13616 entries. . .
Processed 700/13616 entries. . .
Processed 1050/13616 entries. . .
Processed 1400/13616 entries. . .
Processed 1750/13616 entries. . .
Processed 2100/13616 entries. . .
Processed 2450/13616 entries. . .
Processed 2800/13616 entries. . .
Processed 3150/13616 entries. . .
Processed 3500/13616 entries. . .
Processed 3850/13616 entries. . .
Processed 4200/13616 entries. . .
Processed 4550/13616 entries. . .
Processed 4900/13616 entries. . .
Processed 5250/13616 entries. . .
Processed 5600/13616 entries. . .
Error: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received
Adding mapping...
Deleting index...
```
It looks like it got half way through indexing and then timed out.

What could it be?

Thank you!

**Comment by oscarssanchez** [comment]
Hi @jeffceriello , 

You may want to try to index with less posts per page. 

`wp elasticpress index --setup --show-bulk-errors --posts-per-page=10`

If this gets an error too, maybe even lowering it to 1 post per page.

**Comment by jeffceriello** [comment]
Hi Oscar,

Thank you. I've tried indexing 10 posts per page and it processes all the entries fine but in the end it says:
`The following posts failed to index:`
with a list of posts (there are a lot of them) looking like this one
```
- 786: J.Crew £148
type: illegal_argument_exception
reason: Limit of total fields [5000] in index [wardrobeiconscom-1] has been exceeded
```

At the end of the list it says
```
Number of posts indexed on site 1: 13663
Total time elapsed: 5,177.461
Success: Done!
Adding mapping...
Deleting index...
```

What does that limit of total fields [5000] mean?

Thank you

**Comment by oscarssanchez** [comment]
Hi @jeffceriello ,

This means you are exceeding the total fields allowed in elasticsearch.  What I would do is look at my post meta table and check out for unused or duplicated meta and clean it. If everything looks ok, then I would only include the important post meta data in the elasticsearch index. Check for example: https://github.com/10up/ElasticPress/issues/1267

**Comment by jeffceriello** [comment]
Hi @oscarssanchez ,

Thank you so much for your reply.

Could you please point me to the right direction for checking for unused or duplicated meta and cleaning it? Is that something I would do directly in the database? If so, what's the best way to do so?

In the issue #1267 another user says
"In order to reduce the mappings we had to exclude most of our fields which are not required for searches."

How do I exclude fields from elasticsearch index? Is it by using Source Filtering? If so, do you have an example of it with ACF and where to put it?

Thank you. Sorry for all these questions but I hope I'll have elasticsearch working after this.

**Comment by oscarssanchez** [comment]
Hi @jeffceriello ,

You can use ep_prepare_meta_excluded_public_keys to exclude meta. This might help as it was also related to this issue: https://github.com/10up/ElasticPress/issues/1192

Unfortunately i can't really tell which meta should be excluded or deleted since i don't know your site , db and codebase, but one way to go about it is check fields that are similar, for example :_

test_field_1
test_field_2
etc.

Hope this helps.

**Comment by jeffceriello** [comment]
Hi Oscar,

I just managed to come back on this issue. I am still trying to exclude meta data but after I do that and resync I still get the same errors
```
- 44868 (Post): 
type: illegal_argument_exception
reason: Limit of total fields [5000] in index [wardrobeiconscom-post-1] has been exceeded
```
The meta structure looks like this
`"meta" : {
          "properties" : {
            "_backorders" : {
              "properties" : {
                "boolean" : {
                  "type" : "boolean"
                },
                "date" : {
                  "type" : "date",
                  "format" : "yyyy-MM-dd"
                },
                "datetime" : {
                  "type" : "date",
                  "format" : "yyyy-MM-dd HH:mm:ss"
                },
                "double" : {
                  "type" : "double"
                },
                "long" : {
                  "type" : "long"
                },
                "raw" : {
                  "type" : "keyword",
                  "ignore_above" : 10922
                },
                "time" : {
                  "type" : "date",
                  "format" : "HH:mm:ss"
                },
                "value" : {
                  "type" : "text",
                  "fields" : {
                    "raw" : {
                      "type" : "keyword",
                      "ignore_above" : 10922
                    },
                    "sortable" : {
                      "type" : "keyword",
                      "ignore_above" : 10922,
                      "normalizer" : "lowerasciinormalizer"
                    }
                  }
                }
              }
            },
            "_downloadable" : {
              "properties" : {
                "boolean" : {
                  "type" : "boolean"
                },
                "date" : {
                  "type" : "date",
                  "format" : "yyyy-MM-dd"
                },
                "datetime" : {
                  "type" : "date",
                  "format" : "yyyy-MM-dd HH:mm:ss"
                },
                "double" : {
                  "type" : "double"
                },
                "long" : {
                  "type" : "long"
                },
                "raw" : {
                  "type" : "keyword",
                  "ignore_above" : 10922
                },
                "time" : {
                  "type" : "date",
                  "format" : "HH:mm:ss"
                },
                "value" : {
                  "type" : "text",
                  "fields" : {
                    "raw" : {
                      "type" : "keyword",
                      "ignore_above" : 10922
                    },
                    "sortable" : {
                      "type" : "keyword",
                      "ignore_above" : 10922,
                      "normalizer" : "lowerasciinormalizer"
                    }
                  }
                }
              }
            },
`
I've gone through each meta key and manually added to the filter `ep_prepare_meta_excluded_public_keys`
`apply_filters( 'ep_prepare_meta_excluded_public_keys', 
    array(
        '_backorders',
        '_crosssell_ids',
        '_downloadable',
        '_featured',
        .......
), $post );`
and I've added that to the file functions.php.
Does it look ok to you or is there something wrong?
Thanks

**Comment by jeffceriello** [comment]
Hi Oscar,

I think I've managed to sort the filter out with the below

```
add_filter( "ep_prepare_meta_excluded_public_keys", function ($arr, $post) {
    $excluded = [
        '_backorders',
        '_crosssell_ids',
        ............
];
    return $excluded;
}, 1, 2 );
```

After the resync I now get the below for 14 elements

```
- 2177 (Post): 
type: mapper_parsing_exception
reason: failed to parse
type: illegal_argument_exception
reason: field name cannot be an empty string
```

What could that be and how could I fix that?
Thanks!
