### ISSUE TITLE
Defining EP_HOST constant prevents update of Post index per cycle in WPMU

### ISSUE THREAD

**Issue by bwcorey** [10up/ElasticPress#1275]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
The constants `EP_HOST`, `EP_SHIELD`, and `EP_INDEX_PREFIX` are defined in wp-config (as opposed to entering them in the Elasticpress settings screen), and it appears that this is preventing the "Post index per cycle" setting from being updated.

In `elasticpress/classes/class-ep-dashboard.php`, around line 897 or so, there is a conditional that detects a multisite settings update:

```php
if ( defined( 'EP_IS_NETWORK' ) && EP_IS_NETWORK && isset( $_POST['ep_host'] ) ) {
```

The problem is that when `EP_HOST` is defined in wp-config.php, the `ep_host` field gains the disabled attribute, preventing its inclusion in the form submit, causing the conditional to fail. This is reproducible in Firefox 65.0.1.

Current WordPress version:
5.0.3

Current ElasticPress version:
2.8.1

Current Elasticsearch version:
5.2.2

Where do you host your Elasticsearch server:
Hosted Elasticpress (elasticpress.io)

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
ACF, Gravity Forms, Yoast

Steps to reproduce:

1. Define `EP_HOST` in wp-config.php.
2. Browse to the Elasticpress settings screen.
3. Change the "Post index per cycle" value to something other than the default.
4. Submit the form.
5. The page will refresh with "Post index per cycle" set back to the default value (350).

**Comment by oscarssanchez** [comment]
Hi @bwcorey , thanks for reporting this! We will look into it

**Comment by brandwaffle** [comment]
@dkoo any chance you could look at this one and perhaps include it in the PR that changes the way settings are handled from #1269 ?

**Comment by allan23** [comment]
Hi @bwcorey,

Are you still experiencing this issue with the latest version of ElasticPress?

**Comment by bwcorey** [comment]
After updating the plugin to version 3.0.2 I can confirm that this issue is no longer present.

**Comment by allan23** [comment]
Great to hear.
