### ISSUE TITLE
Related Post returns same 5 posts for every posts

### ISSUE THREAD

**Issue by cubryto** [10up/ElasticPress#1278]
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? bug

Describe the issue you encountered:
Related post features return same 5 posts for every posts

Current WordPress version: 5.1

Current ElasticPress version: 2.8.1

Current Elasticsearch version: 6.2.0

Where do you host your Elasticsearch server: self-host, centos server

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

I don't know how you can reproduce this. I'll paste value of $formatted_args here. It seems  [post_type.raw] => post is always true. Could this be a problem when most of my posts have a different post type?

[from] => 0
[size] => 5
[sort] => Array (
    [0] => Array (
        [post_date] => Array (
            [order] => desc
            )
        )
    )
[query] => Array (
    [more_like_this] => Array (
        [like] => Array (
            [_id] => 356081
            )
        [fields] => Array (
            [0] => post_title
            [1] => post_content
            [2] => terms.post_tag.name
            )
        [min_term_freq] => 1
        [max_query_terms] => 12
        [min_doc_freq] => 1
        )
    )
[post_filter] => Array (
    [bool] => Array (
        [must] => Array (
            [0] => Array (
                [term] => Array (
                    [post_type.raw] => post
                    )
                )
            [1] => Array (
                [term] => Array (
                    [post_status] => publish
                    )
                )
            )
        )
    )

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi @cubryto , this is correct, ElasticSearch related posts widget is only searching on post_type `posts`. 

Because I don't know how your site is setup, I can't give a better answer for the moment. 

If you could better describe how many post_types do you have, which plugins, etc. and install our debug bar and paste the query body and result, we can definitely give you better advise.

Kind regards and hope your day is great.

**Comment by schneyra** [comment]
@cubryto Can you have a look, if those 5 posts are the newest 5? I'm having a similar problem: #1274

**Comment by cubryto** [comment]
When I look at the function ep_find_related( $post_id, $return = 5 ), I found out that the request is always made through the database instead of Elasticsearch server.
I added echo $query->request to ep_find_related function

function ep_find_related( $post_id, $return = 5 ) {
	$args = array(
		'more_like'		 => $post_id,
		'posts_per_page' => $return,
		'ep_integrate'   => true,
	);
    
	$query = new WP_Query( apply_filters( 'ep_find_related_args', $args ) );

       //I added this to see the request 
       echo $query->request;
	if ( ! $query->have_posts() ) {
		return false;
	}
	return $query->posts;
}

The request is always like this "SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish') ORDER BY wp_posts.post_date "

**Comment by oscarssanchez** [comment]
@cubryto , can you please install the elasticpress debug bar and tell us the query result of related posts?

**Comment by oscarssanchez** [comment]
Hi @cubryto I'm closing this for now due to inactivity, please feel free to open a new issue if you still have problems
