### ISSUE TITLE
AND logic between 2 facets?

### ISSUE THREAD

**Issue by Salamander3** [10up/ElasticPress#1279]
### Have you searched for similar issues before submitting this one?
yes
### Is this a bug, question or feature request?
question
### Describe the issue you encountered:
When using 2 facets the relation between them seems to be OR, i'd need it to be AND.

### **Example:**
Taxonomy 1: Countries.
Taxonomy 2: Languages.
I select Country USA, Language English.

It returns ALL posts with term USA + ALL posts with term English.

What i expect: Posts tagged BOTH English and USA.
**Should exclude:**
Posts with tax English without USA.
Posts with tax USA without English.

Basically an AND logic between facets. is this possible?

### Current WordPress version:
5.1
### Current ElasticPress version:
2.8.1
### Current Elasticsearch version:
6.3.0
### Where do you host your Elasticsearch server:
Same server as WP.
### Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Yoast SEO
WP Super Cache
WP Mail SMTP
Related Posts By Taxonomy
Query Monitor
Google XML Sitemaps
GD Rating System
ElasticPress
Fast Velocity Minify
Custom Post Type UI
Classic Editor

### Steps to reproduce:

1. Add 2 facets
2. Pick a term on each.
3. All posts from each selection show, not posts that contain both terms. (OR instead of AND)

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi @Salamander3 ,

Since `facet_query()` is hooked to pre_get_posts, have you tried to set the relation parameters on `pre_get_posts` with a priority after `facet_query()` is executed?

**Comment by Salamander3** [comment]
Hi, i haven't. I'm not sure how to get the right priority, something like this would do? (I'm no coder)

```
add_action( 'pre_get_posts', 'facets_priority', 15 );

function facets_priority( $query ) {

                //where my facets will render
		if ( !is_admin() && $query->is_main_query() && is_post_type_archive() )	
	{
	$query->set( 'tax_query', array(
               'relation' => 'AND',
              
            ));
	}
}
```

**Comment by Salamander3** [comment]
![this](https://user-images.githubusercontent.com/8179611/54091222-cb29d480-437d-11e9-80d7-a7be432bc99f.png)
