### ISSUE TITLE
WooCommerce search not working properly

### ISSUE THREAD

**Issue by iDuuck** [10up/ElasticPress#1281]
Is this a bug, question or feature request? Bug/Question

Describe the issue you encountered:

I have a shop for a client, which uses WooCommerce and ElasticPress. When I do a search (even when I say `$query->set('ep_integrate', false);`) I am not able to see all the search results.

See an example here: https://portal.ovb.de/shop?s=Together+Strong

"Debug Bar" still says, that the Elasticsearch request is fired. 

How to fix this?

Current WordPress version: 4.9.9

Current ElasticPress version: 2.8.1

Current Elasticsearch version: 6.4.0

Where do you host your Elasticsearch server: On the same server.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): WooCommerce

**Comment by iDuuck** [comment]
Addition: Also tried to disable the "Search" feature in ElasticPress, which also isn't helping anything.

**Comment by oscarssanchez** [comment]
Hi @iDuuck ,

Could you confirm the product you are searching was properly indexed by ElasticPress? By "fired", do you mean the request was successful ? what is the request result? 

Thanks!

**Comment by iDuuck** [comment]
Ok, I think (if ElasticPress would work right) this is a bug in WooCommerce, too. Since I am seeing in the Debug Bar, that the results are actually documents.

**However**, I am disabling search and still ElasticSearch is used for search. How does this happen?

**Comment by oscarssanchez** [comment]
Hi @iDuuck did you disable the woocommerce feature or the search feature?

**Comment by iDuuck** [comment]
Tried both. Neither worked.

**Comment by iDuuck** [comment]
Any update here, @oscarssanchez

**Comment by oscarssanchez** [comment]
Hi @iDuuck ,

Just had some time to check this again. 

Two questions:

- Have you checked if the issue persists on ElasticPress 3.0?
- If it still is an issue, are you able to reproduce this on other environments and can give us instructions on how we can reproduce as well?

Thanks

**Comment by oscarssanchez** [comment]
Closing for now @iDuuck  please feel free to open a new issue if the issue persists. Thanks
