### ISSUE TITLE
How to sync custom post types?

### ISSUE THREAD

**Issue by marianagarciaferreira** [10up/ElasticPress#1284]
I did the sync and no post was sent to the elasticsearch. I configured the post types but did not synchronize the posts

how to sync custom posty types to elastic?

**Comment by jordan26** [comment]
Interested to know this too.

**Comment by marianagarciaferreira** [comment]
Anyone know how I can index manually?

I have an action that monitors when saving a specific post and I have a php doing a manual query, now I need to index this data in a specific type.
Does anyone know how I can make a laugh?

**Comment by oscarssanchez** [comment]
Hi @marianagarciaferreira , @jordan26 ,

Hope you are doing well, would you mind sharing some steps to reproduce the issues you are currently having?

@marianagarciaferreira I did not fully understand your last comment. Do you mean you need to duplicate the data from the post you are saving and inject it into an already existing post post_type ?

**Comment by marianagarciaferreira** [comment]
no, I need to index the wordpress menus.
I made php and got the menus now in action save I try to index the type menus in elasticsearch

**Comment by marianagarciaferreira** [comment]
i try

 $data = $_POST['nav-menu-data'];
       //  $client = \EP_API::factory();

        $path = trailingslashit(ep_get_index_name()) . 'menus';
        $body = array(
            'type'  => 'menus',
            'data'    => $data
        );

        $request_args = array('method' => 'POST', 'body' => $body, 'timeout' => 30);
        $request = ep_remote_request($path, apply_filters('ep_bulk_index_posts_request_args', $request_args, $data));

but not work

I just need to manually index the WordPress menus or include when saving the menu in admin

**Comment by marianagarciaferreira** [comment]
if ($_POST['nav-menu-data']) {
        $data = $_POST['nav-menu-data'];
       $client = \EP_API::factory();

        $path = trailingslashit(ep_get_index_name()) . 'menus';
        $body = array(
            'type'  => 'menus',
            'data'    => $data
        );
        $client->bulk_index_posts($body);

    }

**Comment by marianagarciaferreira** [comment]
I am in error and I hit because I did not find any documentation on how to add a type and its data in an index

**Comment by marianagarciaferreira** [comment]
all return error

WP_Error Object ( [errors] => Array ( [400] => Array ( [0] => Bad Request ) ) [error_data] => Array ( [400] => Array ( [headers] => Requests_Utility_CaseInsensitiveDictionary Object ( [data:protected] => Array ( [content-type] => application/json; charset=UTF-8 [content-encoding] => gzip [content-length] => 148 ) ) [body] => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"},"status":400} [response] => Array ( [code] => 400 [message] => Bad Request ) [cookies] => Array ( ) [filename] => [http_response] => WP_HTTP_Requests_Response Object ( [response:protected] => Requests_Response Object ( [body] => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"},"status":400} [raw] => HTTP/1.1 400 Bad Request content-type: application/json; charset=UTF-8 content-encoding: gzip content-length: 148 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"},"status":400} [headers] => Requests_Response_Headers Object ( [data:protected] => Array ( [content-type] => Array ( [0] => application/json; charset=UTF-8 ) [content-encoding] => Array ( [0] => gzip ) [content-length] => Array ( [0] => 148 ) ) ) [status_code] => 400 [protocol_version] => 1.1 [success] => [redirects] => 0 [url] => http://127.0.0.1:9200/apifleurylab-1/post/_bulk?pipeline=apifleurylab-1-attachment [history] => Array ( ) [cookies] => Requests_Cookie_Jar Object ( [cookies:protected] => Array ( ) ) ) [filename:protected] => [data] => [headers] => [status] => ) ) ) )

**Comment by marianagarciaferreira** [comment]
is there any way to index WordPress menus?

**Comment by marianagarciaferreira** [comment]
I solved!!!!!!
after scouring the files of the plugin I found how to index the menu of WordPress

    if ($_POST['nav-menu-data']) {
        $post_type = get_post_type( $post_ID );
        $post_args = ep_prepare_post( $post_ID );
        $response = ep_index_post( $post_args, true );
    }
