### ISSUE TITLE
Search custom fields

### ISSUE THREAD

**Issue by speedwheel** [10up/ElasticPress#1285]
Hello, how can I indedx and search custom fields, any examples? I want to add another field that will have the content of the post without the html, because it's creating problems.

**Comment by oscarssanchez** [comment]
Hi @speedwheel ,

Have you looked at `ep_search_fields` as well as `ep_config_mapping` filters?

**Comment by oscarssanchez** [comment]
Closing for now due to inactivity @speedwheel  please feel free to open a new issue if the problem is not solved.
