### ISSUE TITLE
BUG:Named meta queries not working

### ISSUE THREAD

**Issue by aluferraz** [10up/ElasticPress#1286]
Have you searched for similar issues before submitting this one?
Yes
Is this a bug, question or feature request?
Bug
Describe the issue you encountered:

When using documented "Named sub-meta queries and multiple orderby arguments" doesn't work with elasticpress.

https://codex.wordpress.org/Class_Reference/WP_Meta_Query#Named_sub-meta_queries_and_multiple_orderby_arguments

Current WordPress version:
5.0.3
Current ElasticPress version:
2.8.1
Current Elasticsearch version:
6.3.2
Where do you host your Elasticsearch server:
Local
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Woocommerce
Steps to reproduce:

1. Create a hook:
        add_action( 'woocommerce_product_query', 'order_by_foto'),99 );
2. Implement the hook that changes the meta_query array:
`
function order_by_foto($q)
    {
        $meta_query = $q->get('meta_query');
        $newMetaQuery =
            array(
                'relation' => 'AND',
                'query_foto' =>array(
                    'relation' => 'OR',
                    array(
                        'relation' => 'OR',
                        'tem_foto' => array(
                            'key' => '_thumbnail_id',
                            'compare' => 'EXISTS' // include post with _thumbnail_id key
                        ),
                        'nao_tem_foto' => array(
                            'key' => '_thumbnail_id',
                            'compare' => 'NOT EXISTS', // include post with _thumbnail_id key
                        )
                    ),
                )
            );
        if (!!$meta_query) {
            $meta_query[] = $newMetaQuery;
        } else {
            $meta_query = $newMetaQuery;
        }
        $orderby = $q->get('orderby');
        $newOrderBy = [];

        if (is_string($orderby)) {
            if($orderby === 'menu_order title'){
                $newOrderBy['nao_tem_foto'] = 'DESC';
            }
            $orderArgs = explode(' ', $orderby);
            foreach ($orderArgs as $orderArg) {
                $newOrderBy[$orderArg] = $q->get('order');
            }
            if($orderby !== 'menu_order title'){
                $newOrderBy['nao_tem_foto'] = 'DESC';
            }
        } else {
            if (is_array($orderby)) {
                $newOrderBy = $orderby;
            }
            $newOrderBy['nao_tem_foto'] = 'DESC';
        }

        /**
         * ALTERANDO CONSULTA
         */
        $q->set('meta_query', $meta_query);
        $q->set('orderby', $newOrderBy);
    }
`
3. Access woocommece product categories page.
4. Check debugbar elasticpress result:

Query Response Code: HTTP 400
"reason": "No mapping found for [nao_tem_foto] in order to sort on"

Query Args:

`array(72) {
  ["product_cat"]=>
  string(20) "smart-phones-tablets"
  ["error"]=>
  string(0) ""
  ["m"]=>
  string(0) ""
  ["p"]=>
  int(0)
  ["post_parent"]=>
  string(0) ""
  ["subpost"]=>
  string(0) ""
  ["subpost_id"]=>
  string(0) ""
  ["attachment"]=>
  string(0) ""
  ["attachment_id"]=>
  int(0)
  ["name"]=>
  string(0) ""
  ["static"]=>
  string(0) ""
  ["pagename"]=>
  string(0) ""
  ["page_id"]=>
  int(0)
  ["second"]=>
  string(0) ""
  ["minute"]=>
  string(0) ""
  ["hour"]=>
  string(0) ""
  ["day"]=>
  int(0)
  ["monthnum"]=>
  int(0)
  ["year"]=>
  int(0)
  ["w"]=>
  int(0)
  ["category_name"]=>
  string(0) ""
  ["tag"]=>
  string(0) ""
  ["cat"]=>
  string(0) ""
  ["tag_id"]=>
  string(0) ""
  ["author"]=>
  string(0) ""
  ["author_name"]=>
  string(0) ""
  ["feed"]=>
  string(0) ""
  ["tb"]=>
  string(0) ""
  ["paged"]=>
  int(0)
  ["meta_key"]=>
  string(0) ""
  ["meta_value"]=>
  string(0) ""
  ["preview"]=>
  string(0) ""
  ["s"]=>
  string(0) ""
  ["sentence"]=>
  string(0) ""
  ["title"]=>
  string(0) ""
  ["fields"]=>
  string(0) ""
  ["menu_order"]=>
  string(0) ""
  ["embed"]=>
  string(0) ""
  ["category__in"]=>
  array(0) {
  }
  ["category__not_in"]=>
  array(0) {
  }
  ["category__and"]=>
  array(0) {
  }
  ["post__in"]=>
  array(0) {
  }
  ["post__not_in"]=>
  array(0) {
  }
  ["post_name__in"]=>
  array(0) {
  }
  ["tag__in"]=>
  array(0) {
  }
  ["tag__not_in"]=>
  array(0) {
  }
  ["tag__and"]=>
  array(0) {
  }
  ["tag_slug__in"]=>
  array(0) {
  }
  ["tag_slug__and"]=>
  array(0) {
  }
  ["post_parent__in"]=>
  array(0) {
  }
  ["post_parent__not_in"]=>
  array(0) {
  }
  ["author__in"]=>
  array(0) {
  }
  ["author__not_in"]=>
  array(0) {
  }
  ["orderby"]=>
  array(3) {
    ["nao_tem_foto"]=>
    string(4) "DESC"
    ["menu_order"]=>
    string(3) "ASC"
    ["title"]=>
    string(3) "ASC"
  }
  ["order"]=>
  string(3) "ASC"
  ["meta_query"]=>
  array(2) {
    ["relation"]=>
    string(3) "AND"
    ["query_foto"]=>
    array(2) {
      ["relation"]=>
      string(2) "OR"
      [0]=>
      array(3) {
        ["relation"]=>
        string(2) "OR"
        ["tem_foto"]=>
        array(2) {
          ["key"]=>
          string(13) "_thumbnail_id"
          ["compare"]=>
          string(6) "EXISTS"
        }
        ["nao_tem_foto"]=>
        array(2) {
          ["key"]=>
          string(13) "_thumbnail_id"
          ["compare"]=>
          string(10) "NOT EXISTS"
        }
      }
    }
  }
  ["tax_query"]=>
  array(3) {
    ["relation"]=>
    string(3) "AND"
    [0]=>
    array(4) {
      ["taxonomy"]=>
      string(18) "product_visibility"
      ["field"]=>
      string(16) "term_taxonomy_id"
      ["terms"]=>
      array(1) {
        [0]=>
        int(63)
      }
      ["operator"]=>
      string(6) "NOT IN"
    }
    [1]=>
    array(3) {
      ["taxonomy"]=>
      string(11) "product_cat"
      ["field"]=>
      string(4) "slug"
      ["terms"]=>
      array(22) {
        [0]=>
        string(20) "smart-phones-tablets"
        [1]=>
        string(11) "smartphones"
        [2]=>
        string(19) "smartphones-tablets"
        [3]=>
        string(21) "smartphones-tablets-2"
        [4]=>
        string(7) "tablets"
        [5]=>
        string(32) "accessories-smart-phones-tablets"
        [6]=>
        string(29) "chargers-smart-phones-tablets"
        [7]=>
        string(10) "powerbanks"
        [8]=>
        string(14) "unlocked-phone"
        [9]=>
        string(17) "4g-lte-smartphone"
        [10]=>
        string(6) "cables"
        [11]=>
        string(20) "chargers-smartphones"
        [12]=>
        string(6) "covers"
        [13]=>
        string(15) "featured-phones"
        [14]=>
        string(7) "holders"
        [15]=>
        string(13) "mobile-phones"
        [16]=>
        string(18) "mobiles-accesories"
        [17]=>
        string(22) "powerbanks-smartphones"
        [18]=>
        string(16) "featured-tablets"
        [19]=>
        string(17) "tablet-accesories"
        [20]=>
        string(18) "tablet-accessories"
        [21]=>
        string(10) "tablet-pcs"
      }
    }
  }
  ["wc_query"]=>
  string(13) "product_query"
  ["posts_per_page"]=>
  int(24)
  ["post_type"]=>
  string(7) "product"
  ["suppress_filters"]=>
  bool(false)
  ["ep_integrate"]=>
  bool(true)
  ["ignore_sticky_posts"]=>
  bool(false)
  ["cache_results"]=>
  bool(true)
  ["update_post_term_cache"]=>
  bool(true)
  ["lazy_load_term_meta"]=>
  bool(true)
  ["update_post_meta_cache"]=>
  bool(true)
  ["nopaging"]=>
  bool(false)
  ["comments_per_page"]=>
  string(2) "50"
  ["no_found_rows"]=>
  bool(false)
  ["taxonomy"]=>
  string(11) "product_cat"
  ["term"]=>
  string(20) "smart-phones-tablets"
}`

**Comment by Salamander3** [comment]
Same for me, it's not mapping the custom meta https://github.com/10up/ElasticPress/issues/1296

**Comment by oscarssanchez** [comment]
Hi @aluferraz ,

Just had a chance to look at this. It looks like the meta field did not make the mapping. This could be many reasons, you could have a lot of meta keys it exceeds the field limit on Elasticsearch and it just ignores putting this key into mappings, maybe it is a protected meta, etc. 

My first recommendation is to do a WP CLI index to check if there's any issues with the field limit:

wp elasticpress index --setup --show-bulk-errors 

If not, could you please try the solution on #1296 ? 

Thanks!

**Comment by oscarssanchez** [comment]
Closing for now @aluferraz  please feel free to open a new issue if the issue persists. Thanks
