### ISSUE TITLE
Performing a custom ES search. using EP in a sort of connector mode.

### ISSUE THREAD

**Issue by thesquaremedia** [10up/ElasticPress#1287]
Have you searched for similar issues before submitting this one?
yes
Is this a bug, question or feature request?
question
Describe the issue you encountered:
is it plausible to use elasticpress as more so of a connector/client. basically I would like to be able to create my own custom queries that I send to elastic search. this way I would have a global search functionality where I could have the search return post,buddypress group, buddypress activities and users in the same list of results. I have a case where the search will be using a lot of facets for different post types and the facets only apply to specific post types. so I figured I need to send a highly customized elastic search query. It seems I should be able to index different data by using the indexable filter. so that I could even built functionality to index and search buddypress data like groups and activities.
Current WordPress version:

Current ElasticPress version:

Current Elasticsearch version:

Where do you host your Elasticsearch server:

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi @thesquaremedia ,

You can send pretty customizable queries to ES by using the `ep_formatted_args` filter.

Alternatively, you can definitely ping your ElasticSearch server in any way you would like to, and you can interact with your index by building your own functions too. As an example, here is how ElasticPress pings the index to search for documents: https://github.com/10up/ElasticPress/blob/develop-2.x/classes/class-ep-api.php#L189

**Comment by thesquaremedia** [comment]
@oscarsanchez thanks a lot for the response that helps!

**Comment by oscarssanchez** [comment]
Hi @thesquaremedia ,

Full index will only be triggered if you perform it. For this I think scheduling the indexing from WP-CLI would work perfectly for your case.

When you refer to delta indexing, do you mean indexing of new posts? If so, this is triggered whenever a new post is posted. 

Hope this helps :)

**Comment by oscarssanchez** [comment]
Closing for now due to inactivity. Please feel free to open a new issue if you still have questions @thesquaremedia
