### ISSUE TITLE
How to show related posts of the same custom type only?

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1288]
I've read ep_formatted_args is used to modify the query but i only want it to affect related posts function. If i want to show **related posts only of the same post type** for an array of types. How would the function look like?

My function looks like this (it's supposed to do an AND logic on search terms only). I'd like to add related posts too:

 function set_to_exact( $formatted_args, $args ) {
    if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
        $formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
        $formatted_args['query']['bool']['must'][0]['multi_match']['operator'] = 'AND';
        unset( $formatted_args['query']['bool']['should'] );
        unset( $formatted_args["query"]["bool"]["must"][0]["multi_match"]["type"] );
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );

**Comment by oscarssanchez** [comment]
Hi @Salamander3 , have you tried something like: 

```
$post_type = get_post_type();
$formatted_args['post_filter']['bool']['must']['term'] = "post_type.raw" => $post_type;
```

**Comment by Salamander3** [comment]
> Hi @Salamander3 , have you tried something like:
> 
> ```
> $post_type = get_post_type();
> $formatted_args['post_filter']['bool']['must']['term'] = "post_type.raw" => $post_type;
> ```

Hi thanks for the code, i put it right above "return $formatted_args;" (outside of the if) and it gives php error:
`Fatal error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) on line 39`

Are you sure the double arrow is the correct syntax? Or am i using it on the wrong place?

**Comment by oscarssanchez** [comment]
Hi @Salamander3,

Yeah i think you are right i did not test this code, I think the correct one should be: 

$formatted_args['post_filter']['bool']['must']['term']['post_type.raw'] =  $post_type;

**Comment by Salamander3** [comment]
Ok it says: 400 Bad Request
Error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "no [query] registered for [0]",
                "line": 1,
                "col": 263
            }
        ],
        "type": "parsing_exception",
        "reason": "no [query] registered for [0]",
        "line": 1,
        "col": 263
    },
    "status": 400
}
```
Query:
```
{
    "from": 0,
    "size": 6,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "more_like_this": {
            "like": {
                "_id": 146274
            },
            "fields": [
                "post_title",
                "post_content",
                "terms.post_tag.name"
            ],
            "min_term_freq": 1,
            "max_query_terms": 12,
            "min_doc_freq": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": {
                "0": {
                    "term": {
                        "post_type.raw": "post"
                    }
                },
                "1": {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                },
                "term": {
                    "post_type.raw": "nds-roms"
                }
            }
        }
    }
}
```
