### ISSUE TITLE
BUG: Changing the "filter url" breaks the tax_query

### ISSUE THREAD

**Issue by aluferraz** [10up/ElasticPress#1290]
FIX AT: #1289 

Have you searched for similar issues before submitting this one?
Yes
Is this a bug, question or feature request?
Bug
Describe the issue you encountered:

When you rewrite the filter url to hide the "pa_" string, ElasticPress breaks the query by searching a taxonomy that doesn't exist.

For example:
http://mywoocommerce.url/shop/?filter_brands=apple 
**Elasticpress searches for a taxonomy named "brands", which doesn't exist. The correct taxonomy is "pa_brands"**

http://mywoocommerce.url/shop/?filter_pa_brands=apple 

**This would produce the right query, but the URL is uglier**

**To fix that, I made the taxonomy identification just like Woocommerce's code (woocommerce/includes/class-wc-query.php / get_layered_nav_chosen_attributes)**

[`class-wc-query.php`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L768)

Current WordPress version:
5.1.1
Current ElasticPress version:
2.8.1
Current Elasticsearch version:
6.3.2

Where do you host your Elasticsearch server:
Local
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce
Screenshots, if needed:

![image](https://user-images.githubusercontent.com/5156410/54570344-fbe0be00-49bc-11e9-88c5-afe107b242a0.png)

**Comment by allan23** [comment]
Hello @aluferraz,

Please let me know if I understand your issue correctly:

- Faceting using `filter_pa_brand` works correctly.
- When you modify the facet name to match the WooCommerce filter it does not.

Is this correct?

**Comment by aluferraz** [comment]
Hello @allan23,

Faceting using filter_pa_brand works correctly.
Faceting using filter_brand it doesn't.

The taxonomy identification was different on ElasticPress comparing it with woocommerce's wc-query.

**Comment by allan23** [comment]
I see. 
You also submitted a pull request to resolve this. 

Can you refactor it for the latest version of ElasticPress (3.x)?

**Comment by fabianmarz** [comment]
@aluferraz, any updates on the rebase?

**Comment by aluferraz** [comment]
> @aluferraz, any updates on the rebase?

Rebase done: https://github.com/10up/ElasticPress/pull/1410

**Comment by felipeelia** [comment]
First of all, thanks for opening the issue! I don't think this one is a bug though. Also, I wonder what we would do if a site has both taxonomies (pa_brand AND brand.)
