### ISSUE TITLE
[BUG] Attribute archive pages problem

### ISSUE THREAD

**Issue by harslannet** [10up/ElasticPress#1293]
this is a bug.

Describe the issue you encountered:

There is a problem with the plug-in;
When we activate this plugin, the attributes links show all the products on the site, not the relevant products!

For example, this link should only show 1 products https://getmagic.app/pa5BSXlY85 (it should be like this: https://getmagic.app/TrEkTe09KC )

only this product needs to be listed (https://getmagic.app/m8KfHxbu3Y)

Do you have any idea how to solve this problem?

Current WordPress version: 5.1.1
Current Woocommerce version: 3.5.7
Current ElasticPress version: 2.8.1
Current Elasticsearch version: 5.4

Where do you host your Elasticsearch server: Cloudways

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): Woocommerce

**Comment by oscarssanchez** [comment]
Hi @harslannet ,

Can you please share a sample attribute and meta_data of

https://www.devritesbih.com/erkek-taki/fosilli-damla-kehribar-925-ayar-gumus-yuzuk/
https://www.devritesbih.com/kadin-takilari/dogal-hakiki-damla-kehribar-bileklik-2/ 

And also the product that you say it should only be displayed?

Also, could you please install the elasticpress debug bar: https://github.com/10up/debug-bar-elasticpress
And let us know what is the query body and query result please?

Thanks!

**Comment by harslannet** [comment]
Hi @oscarssanchez ,
Choose any attribute, click and the result will always be the same!

**Debug bar results:**
TOTAL ELASTİCPRESS QUERİES: 0
TOTAL BLOCKİNG ELASTİCPRESS QUERY TİME: 0 ms
No queries to show

**Comment by harslannet** [comment]
Hi,
Do you do something to solve this problem?

**Comment by allan23** [comment]
Hello @harslannet,

Have you upgraded to the latest version of ElasticPress?

**Comment by oscarssanchez** [comment]
Closing for now @harslannet
