### ISSUE TITLE
how to sort Facets terms by name asc instead of count desc?

### ISSUE THREAD

**Issue by Salamander3** [10up/ElasticPress#1298]
The facets widget sorts by count desc. But it's hard for people to find stuff with this order (random to them).
So i looked at /facets/class-ep-facet-widget.php

```
$terms = ep_get_term_tree( $terms, 'count', 'desc', true );
$term_tree = ep_get_term_tree( $terms, 'count', 'desc', false );
```
And yes, changing these has the desired effect but with 1 problem. The greyed-out terms don't move to the bottom. So i would need some sort of logic to move the count->0 to the bottom and the rest by name asc.

Does this make sense?

**Comment by oscarssanchez** [comment]
Hi @Salamander3, there was PR in progress to show the counts so the sorting would make more sense to users: https://github.com/10up/ElasticPress/issues/1180 maybe we can redo this soon.

I think you would need custom code to modify this if you change the facet sorting, as of now it is intended to work only this way. To modify the widget display however there is this filter: `ep_facet_search_widget` that said, i don't think it is advisable to directly change the source, as it will get overridden when you update the plugin.

**Comment by Salamander3** [comment]
Yup this is too specific and would require too much code to work the way i'd like it to be. Thanks for the info. I'll see myself out.
