### ISSUE TITLE
Can't select any filter. It seems like results count is zero for every term. 

### ISSUE THREAD

**Issue by pemz** [10up/ElasticPress#1299]
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?

Describe the issue you encountered:
Can't select any filter, all is like faded out. 
Same for every filter type.
If debugging code, then $GLOBALS['ep_facet_aggs'] is empty

Current WordPress version:
5.1.1
Current ElasticPress version:
2.8.2
Current Elasticsearch version:
6.3.2
Where do you host your Elasticsearch server:
Own server
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Woocommerce
Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:
![image](https://user-images.githubusercontent.com/31883197/55056506-f5161300-506e-11e9-8dec-2e144636857b.png)

**Comment by tlovett1** [comment]
@pemz is this still a problem?

**Comment by Rahmon** [comment]
Hi @pemz. 

I'll close this issue due it has not had recent activity. Please feel free to reopen this issue or create a new one if you need anything else.

Thanks!
