### ISSUE TITLE
change host and index prefix on the fly via CLI

### ISSUE THREAD

**Issue by mustafauysal** [10up/ElasticPress#1302]
Overriding host and prefix via CLI command would be useful in some cases.

I'm not sure when #659 will be implemented, but when we able to index different hosts, shifting Elasticsearch version can be smoother.  (~10 hours downtime is not good for working with large datasets)

What are you guys thinking about this? 🤔

**Comment by oscarssanchez** [comment]
Hi @mustafauysal , thanks for the PR!!, I will bring this up in our internal standup.

**Comment by mustafauysal** [comment]
The PR has been merged, I'm closing the issue.
