### ISSUE TITLE
connect elasticpress to my own elasticsearch server

### ISSUE THREAD

**Issue by alifazeli** [10up/ElasticPress#1306]
Hi
I made an elasticsearch server with kibana based on this toturial
https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elastic-stack-on-centos-7
Now i want to connect elasticpress to my own server
how can i do it?

**Comment by oscarssanchez** [comment]
Hi @alifazeli ,

It looks like you should get a localhost:9200 url from what i could briefly check. Simply input that host URL into the settings page and you should be good to go.

**Comment by alifazeli** [comment]
tnx for answer
 i add my url to settings and it seems that it connected
but when i click on resync after syncing 16 record i got "an error occurred while syncing:
![image](https://user-images.githubusercontent.com/45519108/56024881-3886a780-5d26-11e9-9b2b-dae0e680b060.png)

**Comment by alifazeli** [comment]
is there any log for elasticpress?
apache log:
`[Fri Apr 12 13:23:02.353838 2019] [fcgid:warn] [pid 12708] [client x.x.x.x] mod_fcgid: stderr: #2 /home/mywordpress/public_html/wp-includes/shortcodes.php(199): preg_replace_callback('/\\\\[(\\\\[?)(toko_s...', 'do_shortcode_ta...', '<p>[vc_row full...'), referer: http://mywordpress.com/wp-admin/admin.php?page=elasticpress-settings
[Fri Apr 12 13:23:02.353852 2019] [fcgid:warn] [pid 12708] [client x.x.x.x] mod_fcgid: stderr: #3 /home/mywordpress/public_html/wp-includes/class-wp-hook.php(286): do_shortcode('<p>[vc_row full...'), referer: http://mywordpress.com/wp-admin/admin.php?page=elasticpress-settings
[Fri Apr 12 13:23:02.353864 2019] [fcgid:warn] [pid 12708] [client x.x.x.x] mod_fcgid: stderr: #4 /home/mywordpress/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters('<p>[vc_row full...', Array), referer: http://mywordpress.com/wp-admin/admin.php?page=elasticpress-settings
[Fri Apr 12 13:23:02.353877 2019] [fcgid:warn] [pid 12708] [client x.x.x.x] mod_fcgid: stderr: #5 /home/mywordpress/public_html/wp-content/plugins/elasticpress/classes/class-ep-api.php(624): apply_filters('the_content', '[vc_row full_wi...'), referer: http://mywordpress.com/wp-admin/admin.php?page=elasticpress-settings
[Fri Apr 12 13:23:02.353891 2019] [fcgid:warn] [pid 12708] [client x.x.x.x] mod_fcgid: stderr: #6 /home/mywordpress/public_html/wp-content/plugins/elasticpress/classes/class-ep-api.php(2780): EP_API->prepare_post(2314), referer: http://mywordpress.com/wp-admin/admin.php?page=elasticpress-settings
[Fri Apr 12 13:23:02.353913 2019] [fcgid:warn] [pid 12708] [client x.x.x.x] mod_fcgid: stderr: #7 /hom in /home/mywordpress/public_html/wp-content/plugins/toko-sliders/slider/slider.php on line 155, referer: http://mywordpress.com/wp-admin/admin.php?page=elasticpress-settings
`

**Comment by oscarssanchez** [comment]
Hi @alifazeli ,

Can you please run this command and report back what's the output on your terminal please? 

wp elasticpress index --setup --show-bulk-errors 

Thanks!

**Comment by alifazeli** [comment]
tnx for support @oscarssanchez

This is output:
Adding mapping...
Deleting index...
Success: Index deleted
Success: Mapping sent
Indexing posts...




        Processed 43/43 entries. . .
Number of posts indexed on site 1: 43
Total time elapsed: 1٫895
Success: Done!
..............
Its strange, it seems everything is ok in terminal
but from interface i get syncing error yet

**Comment by oscarssanchez** [comment]
Hi @alifazeli , is the content of your site indexed then ?
