### ISSUE TITLE
Plugin breaks woocommerce order tracking when enabled

### ISSUE THREAD

**Issue by flaversaver21** [10up/ElasticPress#1307]
Have you searched for similar issues before submitting this one?
- yes

Is this a bug, question or feature request?
- bug

Describe the issue you encountered:
- Plugin enabled, woocommerce order tracking gives error that order doesn't exist. Disable plugin and it works. Start a sync and it will work, but minute the sync ends the error result returns. This happens on both of our woocommerce sites (although very similar, one site is fully updated while the other is a month or two since last round of plugin updates)

Current WordPress version:
- 5.1.1

Current ElasticPress version:
- 2.8.2

Current Elasticsearch version:
- 6.2.3

Where do you host your Elasticsearch server:
- pressjitsu

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
- woocommerece
- sequential order numbers

Steps to reproduce:

1. Run sync and attempt to track oder, it works
2. When sync finishes track order gives an error. 
3. 

Screenshots, if needed:
<img width="1458" alt="Screen Shot 2019-04-11 at 10 45 05 PM" src="https://user-images.githubusercontent.com/9562723/56014782-801c1d80-5cab-11e9-8289-25456937e03c.png">

**Comment by flaversaver21** [comment]
More info...

When protected content is disabled it works. However, that's not an option for our stores.

**Comment by oscarssanchez** [comment]
Thanks for the report @flaversaver21 , we will definitely have a look into it!

**Comment by oscarssanchez** [comment]
HI @flaversaver21 just went through the steps to reproduce, could you please let us know which tracking plugin are you using ? thanks

**Comment by flaversaver21** [comment]
Not using a plugin. Our order tracking page is simply using the shortcode for the built in order tracking in Woocommerce. 

_WooCommerce has guest tracking built in, but it’s not used anywhere by default. You can add a shortcode to your site to create an order tracking form: [woocommerce_order_tracking]

The tracking form allows guests to enter their order number and email information to revisit order details._

**Comment by oscarssanchez** [comment]
Hi @flaversaver21 ,

Just had an opportunity to give this a shot again. 

This is what i did on my end:

1.-  Checkout with payment option "pay with cash on delivery"
2.- Do an elasticpress sync
3.- Browse test tracking page and search for order
4.- Order appears
5.- Check other pages are using elasticsearch

Does this apply for all of your orders? Am I missing something out with my testing? 

Thanks

**Comment by flaversaver21** [comment]
Yeah, it's every single order and we have thousands of orders. Your instructions don't really apply to our problem. To be clear, when the elasticpress plugin is enabled, I can't track orders. When the plugin is doing it's sync, the order tracking works. However, the second the sync completed order tracking breaks again. If you want I can show you on our live store.

**Comment by flaversaver21** [comment]
I tested Elasticpress 3.0 plugin and got the exact same results. I can provide direct access to this site for troubleshooting. 

Also, the error specifically says: Sorry, the order could not be found

We do use custom order numbers. I'm guessing it simply doesn't know where to find the order number. If I disable elasticpress, this works. So elastic "protected content" is causing this problem.

**Comment by flaversaver21** [comment]
Any further help here? We're happy to pay to get some type of support because it's a major drag on our customers at current and this plugin is the direct cause.

**Comment by beannt** [comment]
I have the same problem too, I use Woocommerce sequential order numbers pro plugin, and not work when track order, is there any way to disable Elastic search on track-order page ?

**Comment by brandwaffle** [comment]
@flaversaver21 @beannt we have seen this recently with the Sequential Order Numbers plugin because the metadata from that plugin that contains the custom order number meta is not synced by default to ElasticPress (I believe because it's set as non-public meta).

We are working on a solution that will work in the majority of use-cases, but if you'd like a temporary solution I believe that adding that meta to the ElasticPress sync will enable Sequential Order Numbers to function properly (including the track orders page).

**Comment by flaversaver21** [comment]
How do we add that meta to ElasticPress sync?

**Comment by brandwaffle** [comment]
@flaversaver21 there's a filter you can use here https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L392 ( 'ep_prepare_meta_allowed_protected_keys' ).

You'll want to add the key name of the custom order ID meta and return it out of that filter.

P.S. I also reached out to you via LinkedIn in case a quick call might be helpful.

**Comment by flaversaver21** [comment]
I’m not sure what the “key name of the custom order ID” would be.  I looked through the db, but nothing jumps out at me. Any guidance here?

**Comment by oscarssanchez** [comment]
Hi @flaversaver21 , 

If you have access to debug tools, I think the fast way (at least for me) could be to update a random order that matches this scenario, and set a breakpoint here: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable.php#L296

This way you can check all meta related to that specific order.

Kind regards,

**Comment by oscarssanchez** [comment]
Closing for now due to inactivity, please feel free to open a new ticket @flaversaver21 if the ticket has not been resolved for you.

**Comment by flaversaver21** [comment]
I was able to figure out the "key name of the order ID", but I need help implementing this.

**Comment by flaversaver21** [comment]
reopen.
