### ISSUE TITLE
Get the corrected word

### ISSUE THREAD

**Issue by elegra-glopez** [10up/ElasticPress#1308]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I want to print on the screen a message like Google "Did you mean..." when the user types a word incorrectly. Is there any way to get which is the word corrected by Elastic? For example, the user searches for 'helloo' and Elastic interprets 'hello'. What I need to get is the corrected word. I searched in the query result and it's not there.
Thanks!

Current WordPress version:
5.1

Current ElasticPress version:
2.8.2

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WPML

**Comment by oscarssanchez** [comment]
I think you will need to write some custom code to add that functionality to your site. Maybe this can be insightful : https://qbox.io/blog/how-to-build-did-you-mean-feature-with-elasticsearch-phrase-suggester 

You could definitely tweak the ES query body that elasticpress translate via filters and also retrieve the elasticsearch response. 

Kind regards,

**Comment by elegra-glopez** [comment]
Thanks @oscarssanchez

**Comment by photocurio** [comment]
I'm working on this same issue.  I am able to get the word suggestions easily by adding a suggest block to the formatted args like this:
```php
    function fmcna_es_suggest( $formatted_args ) {
	! isset( $formatted_args['suggest'] ) && $formatted_args['suggest'] = array(
		'text'                     => get_search_query( false ),
		'fmcna_suggest-title'      => array(
			'term' => array(
				'field' => 'post_title',
			),
		),
		'fmcna_suggest-content'    => array(
			'term' => array(
				'field' => 'post_content',
			),
		),
		'fmcna_suggest-attachment' => array(
			'term' => array(
				'field' => 'attachments.attachment.content',
			),
		),
	);
	return $formatted_args;
    }
    add_filter( 'ep_formatted_args', 'fmcna_es_suggest', 10, 2 );
```

Now if I type a misspell a search term and check the query result in the elasticpress debugger, I see the suggest block, and it has some helpful suggestions.  Nice!!

**The problem:** I can't figure out how to get the suggest block into the wp_query response.  Naturally I'd rather not make a second query to get the suggests.  Anyone have any ideas?

**Comment by BeshoyAtef** [comment]
any updates ?
