### ISSUE TITLE
Facet custom HTML filter should pass $widget_title for customization purposes

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#1310]
The filter for custom HTML for facet widgets here https://github.com/10up/ElasticPress/blob/develop-2.x/features/facets/class-ep-facet-widget.php#L236 does not pass in the $widget_title, which makes it impossible to style the HTML using that particular attribute. The filter should pass along the $widget_title as well as the existing HTML + params.

**Comment by oscarssanchez** [comment]
Closing via #1330
