### ISSUE TITLE
Searching multiple indexes, permalinks all use current site URL

### ISSUE THREAD

**Issue by MWDelaney** [10up/ElasticPress#1312]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I'm trying to use ElasticSearch to search multiple sites at once (multiple indexes). This is working well! Results are shown from all indexes, but the permalinks all use the base URL of the current site. How can I access the indexed permalink from my results page so my links work correctly?

Current WordPress version:
4.9.6

Current ElasticPress version:
2.8.2

Current Elasticsearch version:
5.2.2 (hosted)

Where do you host your Elasticsearch server:
ElasticPress.io

Steps to reproduce:

1. Index multiple sites
2.  Add something like this to search multiple indices:
```
add_filter('ep_index_name', function ($index_name) {
    if (is_search()) {
        return 'yourname*';
    }
}, 20, 2);
```
3. See the results from multiple sites, but the permalinks all act as though the content is on the current site.

Thank you!

**Comment by MWDelaney** [comment]
I guess another way to phrase my question is: how do I access the ElasticPress results (specifically the permalink) from inside a loop? I don't want to use WordPress functions because they'll only work within the context of the site I'm on. I just want the raw field that ElasticPress has.

**Comment by tlovett1** [comment]
Permalink isn't stored in Elasticsearch. You need to use the WP function or store the URL as a special field in Elasticsearch via custom code.
