### ISSUE TITLE
Using standalone wp_query doesn't seem to be instantiating ES

### ISSUE THREAD

**Issue by rferguson10** [10up/ElasticPress#1313]
Have you searched for similar issues before submitting this one?
YES

Is this a bug, question or feature request?
Question 

Describe the issue you encountered:

Current WordPress version:
5.1.1

Current ElasticPress version:
2.8.2

Current Elasticsearch version:
6.2.0

Where do you host your Elasticsearch server:
localhost:9200

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
none

Steps to reproduce:

I setup a simple query just in my functions.php to test and it doesn't seem to be querying Elastic. I know because I've tried while there is an index in ES and without and it's the same issue. Also, looking through the code, it doesn't look like filter_posts_request in class-ep-wp-query-integration.php is firing for my query. Isn't the posts_request hook suppose to enable for any wp_query? It does only seem to work when I hit the normal WP search page with a query ex: /s=test 

I'm hoping to use this within templates other than search, like I might with get_posts or similar.

$posts = new WP_Query( array(
    'ep_integrate'   => true,
    'post_type'      => 'post',
    'posts_per_page' => 20,
) );

print_r($posts);

**Comment by tlovett1** [comment]
This should work. Are you testing via the Debug Bar ElasticPress plugin?

**Comment by allan23** [comment]
@rferguson10 can you advise?

**Comment by rferguson10** [comment]
I was trying to just query it in the template, or functions.php as it says in my description. I've since written a separate class that interfaces with ES directly.
