### ISSUE TITLE
WP-CLI Issue with stats and status

### ISSUE THREAD

**Issue by davidhefley** [10up/ElasticPress#1317]
Have you searched for similar issues before submitting this one? YES

Is this a bug, question or feature request? BUG

Describe the issue you encountered:
If I don't have user indexing enabled, and I try to do a wp-cli elasticpress stats or wp-cli elasticpress status, I get:

Fatal error: Uncaught Error: Call to a member function get_index_name() on boolean in /var/www/html/wp-content/plugins/elasticpress/includes/classes/Command.php:920

If I enable user indexing, the problem goes away.  

Current WordPress version:  5.2

Current ElasticPress version: 3.0

Current Elasticsearch version: 6.3.2

Where do you host your Elasticsearch server: Local install

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
None

**Comment by tlovett1** [comment]
Thanks for the report @davidhefley. We are looking into this.
