### ISSUE TITLE
WP-CLI posts-per-page parameter issue

### ISSUE THREAD

**Issue by trilobita99** [10up/ElasticPress#1319]
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? Bug

Describe the issue you encountered:
have updated to EP3. Error when using wp-cli :-

```
wp elasticpress index --setup --posts-per-page=50

Error: Parameter errors:
 unknown --posts-per-page parameter
```

Current WordPress version: 5.2

Current ElasticPress version: 3

Current Elasticsearch version: 6.7.1

Where do you host your Elasticsearch server: Local

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. use wp-cli :- wp elasticpress index --setup --posts-per-page=50
2. 
3. 

Screenshots, if needed:

**Comment by tlovett1** [comment]
Hey @trilobita99, `posts-per-page` has been renamed to `per-page`. We'll make sure the docs get corrected.

Thanks!

**Comment by brandwaffle** [comment]
@tlovett1 the docs are correct but perhaps we should call out that this flag has changed explicitly in the readme? I can take the action item if you agree.

**Comment by tlovett1** [comment]
I already added it to the readme

**Comment by trilobita99** [comment]
Thanks. --per-page works like a charm.
