### ISSUE TITLE
REST Search includes attachments

### ISSUE THREAD

**Issue by davidhefley** [10up/ElasticPress#1320]
Have you searched for similar issues before submitting this one? YES

Is this a bug, question or feature request? BUG

Describe the issue you encountered: When you search with the REST api, attachments are included if document indexing feature is enabled and querying a custom post type

Current WordPress version: 5.2

Current ElasticPress version: 3

Current Elasticsearch version: 6.3

Where do you host your Elasticsearch server: Local

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): 
None, and using twentynineteen

Steps to reproduce:

1. register a custom post type
2. navigate to the appropriate endpoint:
<yoursite>/wp-json/wp/v2/custmposttype?search=commute
3. Matching documents returned - dumping the EP query shows that posttype is set to both the custom post type and attachments

To fix (with EP code hack which I'd rather not do since I'm not really sure this is the proper place and it won't survive updates!):

In includes/classes/Feature/Documents/Documents.php, on line 117:

Changed:

if ( ! empty( $post_type ) ) {

to:

if ( ! empty( $post_type ) && !REST_REQUEST ) {

**Comment by tlovett1** [comment]
Thanks @davidhefley. We'll get this fixed.
