### ISSUE TITLE
Translate fields of orderby (.raw,  .value, .sortable)

### ISSUE THREAD

**Issue by vnmedeiros** [10up/ElasticPress#1324]
Hi all.

The documentationsays that the resulting path to sorting by metadata is: `meta.my_key.raw`:

> * ```orderby``` (*string*)
> 
>     Order results by field name instead of relevance. Supports: ```title```, ```modified```, `meta_value`, `meta_value_num`, ```type```, ```name```, ```date```, and ```relevance```; anything else will be interpretted as a document path i.e. `meta.my_key.long` or `meta.my_key.raw`. You can sort by multiple fields as well i.e. `title meta.my_key.raw`

But, in method `parse_orderby` of class User (User.php) on line 573 we have:
```PHP
} elseif ( 'meta_value' === $orderby_clause ) {
	if ( ! empty( $query_vars['meta_key'] ) ) {
		$sort[] = array(
			'meta.' . $query_vars['meta_key'] . '.value' => array(
				'order' => $order,
			),
		);
	}
}
```
As you see, the resulting path ends with `.value` (not as described in documentation).

In my tests, sorting by a metadata value is not working, unless use the filter `ep_formatted_args` and fix it to user `.value.sortabe` at the end. (using `.raw`, as the docs says, would also work, but there would be problems with upper and lower cases).

Do you confirm this is an issue or if I am missing something?

Also, I found other fields that were also not working and that need a special mapping. These are the fields I had to deal with in my filter for them to work:

```
post_title -> post_title.sortable
post_author -> post_author.login.sortable
post_name -> post_name.raw
post_type -> post_type.raw
meta_value -> meta.my_key.value.sortable
```

**Comment by vnmedeiros** [comment]
https://github.com/10up/ElasticPress/pull/1420

**Comment by oscarssanchez** [comment]
Closing as t looks like 1420 solved this.
