### ISSUE TITLE
The v2.8.2 of the plugin disappeared on WordPress Plugin website

### ISSUE THREAD

**Issue by tgijasonyip** [10up/ElasticPress#1328]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I am using composer to download plugins from WordPress Official plugin website. I found that the v2.8.2 of the plugin no longer exist after the v3.0 is released.
Although it is still possible to get the version via GitHub, I wonder why the version is removed.

![image](https://user-images.githubusercontent.com/38749833/57908312-4c3ba580-78b2-11e9-9fe8-848b5e10b912.png)

**Comment by tlovett1** [comment]
This is fixed.
