### ISSUE TITLE
warning made by the function addcslashes inside ep_register_feature function

### ISSUE THREAD

**Issue by tgijasonyip** [10up/ElasticPress#1329]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
There is a PHP warning - "Warning: addcslashes() expects parameter 1 to be string, array given in /var/www/html/wp-content/plugins/elasticpress/includes/compat.php on line 60" made by the function call - addcslashes which is called inside ep_register_feature function.
I think the problem is because other plugins had been used the function "ep_register_feature" to register some integrations. Since those plugins call the function inside a class, they have to put a array for the callback arguments such as feature_box_summary_cb, setup_cb but the php function addcslashes does not accept array input.

For example, here is how WPML calls the "ep_register_feature" function.
`ep_register_feature( 'wpml_integration', array(
			'title' => __( 'Integration WPML with ElasticPress', 'sitepress' ),
			'setup_cb' => array( $this, 'set_up' ),
			'feature_box_summary_cb' => array( $this, 'box_summary' ),
			'feature_box_long_cb' => array( $this, 'box_description_long' ),
			'requires_install_reindex' => false,
		) );`

Current WordPress version:
4.9.7

Current ElasticPress version:
3.0

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WPML

Steps to reproduce:

1. Upgrade the plugin from v2.8.2 to v3.0
2. Find the warnings on WordPress login page
3. Cannot login WordPress

Screenshots, if needed:
![image](https://user-images.githubusercontent.com/38749833/57909008-26af9b80-78b4-11e9-8e6e-edbc786caceb.png)

**Comment by tlovett1** [comment]
This will be fixed in 3.0.1. Thanks!
