### ISSUE TITLE
ElasticPress doesn't work with Yith Ajax Filter

### ISSUE THREAD

**Issue by kevin25** [10up/ElasticPress#1331]
__Have you searched for similar issues before submitting this one?__

Yes, I have
__Is this a bug, question or feature request?__

Bug
__Describe the issue you encountered:__

The Ajax Filter By Yith doesn't work anymore.

__Current WordPress version?__

5.2

__Current ElasticPress version?__

3.0
__Current Elasticsearch version?__

2.4.6
__Where do you host your Elasticsearch server?__
Local host
__What ElasticPress features do you have currently active?__
Post Search
__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
Elementor Pro: by Elementor.com – 2.4.3
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.11.0 – Not tested with the active version of WooCommerce
Google Address Autocomplete for WooCommerce: by MB Création – 2.3.4 – Not tested with the active version of WooCommerce
JanStudio Addons: by JanStudio – 1.2.2
Just In Time Sales Offers: by Rymera Web Co – 1.2.7 – Not tested with the active version of WooCommerce
Just In Time Sales Offers Premium: by Rymera Web Co – 1.3.2 – Not tested with the active version of WooCommerce
Kirki Toolkit: by Ari Stathopoulos (@aristath) – 3.0.39
Mailchimp for WooCommerce: by Mailchimp – 2.1.16 – Not tested with the active version of WooCommerce
PixelYourSite Super Pack: by PixelYourSite – 1.0.2
Prettify reviews: by Freddy Muriuki – 1.0
Recover Abandoned Cart: by Fantastic Plugins – 21.0 – Not tested with the active version of WooCommerce
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Currency Converter: by WooCommerce – 1.6.5 – Not tested with the active version of WooCommerce
WooCommerce Facebook Conversion Pixel: by Seravo Oy – 0.1 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.6.2 – Not tested with the active version of WooCommerce
WooCommerce MailChimp Subscribe: by SeedProd – 1.0.8 – Not tested with the active version of WooCommerce
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.3.9.7 – Not tested with the active version of WooCommerce
WooCommerce Twilio SMS Notifications: by SkyVerge – 1.9.0 – Not tested with the active version of WooCommerce
WooSwatches - Woocommerce Color or Image Variation Swatches: by woomatrix – 2.7.07 – Not tested with the active version of WooCommerce
WordPress Importer: by wordpressdotorg – 0.6.4
Wordpress Pinterest Automatic: by ValvePress – 4.7.0
WP Optin Wheel Pro: by StudioWombat – 3.0.5 – Not tested with the active version of WooCommerce
XL WooCommerce Sales Triggers: by XLPlugins – 2.7.0 – Not tested with the active version of WooCommerce
YITH Product Size Charts for WooCommerce Premium: by YITHEMES – 1.1.5 – Not tested with the active version of WooCommerce

__Steps to reproduce:__

1. Go to the categories with Filter enabled on the sidebar
2. Click on size or color 
3. Nothing shows up.

__Screenshots, if needed:__
<img width="1673" alt="Screen Shot 2019-05-20 at 16 35 33" src="https://user-images.githubusercontent.com/2909982/58011835-54e3e400-7b1d-11e9-9621-43a035145a0b.png">

**Comment by oscarssanchez** [comment]
Hi @kevin25 , there's #1342 which integrates the default woocommerce price filter. You can always adapt to your needs as this uses get parameters to build the query. 

Kind regards.
