### ISSUE TITLE
Installing Elasticpress prevents searching orders with customer name

### ISSUE THREAD

**Issue by rekkitatu** [10up/ElasticPress#1332]
I noticed that when I have Elasticpress installed there are some issues with orders view in the backend. For example searching the orders by customer name isn't working when Elasticpress is active (protected content featured disabled). If I enable the protected content indexing, then the search with customer name does work but with this setting I'm also seeing problems where filtering orders by status there are orders displayed with other statuses as well.

Using WC 3.6.3, Elasticpress 3.0.1, Elasticsearch 5.6.16

__Features enabled:__ Post search, woocommerce, facets, related, protected content

__Steps to reproduce (order search):__

1. Enable Elasticpress with protected contend disabled
2. Search orders with customer names in backend orders view => search doesn't give any results and search seems to work only with orderID

Main point is enabling Elasticpress plugin shouldn't break existing Woocommerce features.

**Comment by nicolinuxfr** [comment]
Same problem here, using WooCommerce 3.6.4, ElasticPress 3.0.3 and ElasticSearch 6.7.2. 

Let me know if you need more information.

**Comment by flaversaver21** [comment]
Same here. I'm having nothing but headaches with Elastic Press to the point I would tell everyone else to run. Huge bugs. Nothing but headaches and problems. 500 errors. Can't search orders. Screws up the front end search results. It's ruining our store and thus pissing off customers.

**Comment by jordan26** [comment]
Having same issue where when ES is activated, the search in admin for customer orders etc returns nothing.
