### ISSUE TITLE
assets/css/autosuggest.css contains less/scss code

### ISSUE THREAD

**Issue by gassan** [10up/ElasticPress#1333]
Should the file be compiled or renamed?

**Comment by gassan** [comment]
The same with dashboard.css

**Comment by tlovett1** [comment]
Compiled assets are in `dist` now.

**Comment by gassan** [comment]
imho renaming sources to *.pcss would be a better option.

![Bildschirmfoto 2019-05-23 um 09 26 59](https://user-images.githubusercontent.com/2382015/58234505-fa29d280-7d3e-11e9-9665-96010f75b912.png)

**Comment by gassan** [comment]
![Bildschirmfoto 2019-05-23 um 09 43 58](https://user-images.githubusercontent.com/2382015/58234640-4e34b700-7d3f-11e9-8b18-8203deca5e7e.png)

**Comment by gassan** [comment]
hmm. gulp task cssclean could also be removed
