### ISSUE TITLE
Fix php errors please!!!!11111111111

### ISSUE THREAD

**Issue by nasyrov** [10up/ElasticPress#1339]
Hi guys,

Thanks for the amazing plugin!

Could you please fix php issues in `DateQuery`?
I actually made a PR #1338 to fix those...

Thanks,
Evgenii

**Comment by nasyrov** [comment]
`DateQuery` class is unusable, I cannot construct date related queries

**Comment by tlovett1** [comment]
@nasyrov I pushed fixes to develop. Can you test?

**Comment by tlovett1** [comment]
Also, what are the WP_Query args you are using to reproduce the error?

**Comment by nasyrov** [comment]
Thanks for that, why not use the php use statments for that?

**Comment by nasyrov** [comment]
```php
       $query->set('date_query', [
            [
                'year'          => 2014,
                'compare'  => '>='
            ],
        ]);
```

**Comment by nasyrov** [comment]
``` php
      /**
	 * Return singleton instance of class
	 *
	 * @return object
	 * @since 0.1.0
	 */
	public static function factory() {
		static $instance = false;
		if ( ! $instance ) {
			$instance = new self();
		}
		return $instance;
	}
```

It's called singleton not factory, factory will new up an instance on every call...
I would suggest renaming to `instance` and `static $instance = false;` what is that?

``` php

final class Elasticpress
{
  /**
    * The instance of the class.
    *
    * @param Elasticpress
    */
  private static $instance;

  /**
    * Return singleton instance of class.
    *
    * @return Elasticpress
    */
  public static function instance(): Elasticpress
  {
    if (is_null(static::$instance) {
      static::$instance = new static;
    }

    return static::$instance;
  }
}

**Comment by tlovett1** [comment]
Hey @nasyrov, I agree we could improve the use statements. For now I'm going to close this. Thanks!
