### ISSUE TITLE
Please tell me how to limit results to the searched word.

### ISSUE THREAD

**Issue by pinpin0528** [10up/ElasticPress#1340]
When someone searches for a bank, I want to display the searched word “bank.”
However, now all words including “bank” are displayed.
I tried the parameter fuzziness, but I didn't get what I wanted.
I don’t know how to set it up.

**Comment by oscarssanchez** [comment]
Hi @pinpin0528 ,

This has been addressed a couple of times. Please refer to : https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/

Kind regards,
