### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by binaryfire** [10up/ElasticPress#1341]
__Have you searched for similar issues before submitting this one?__ yes

__Is this a bug, question or feature request?__ question

__Describe the issue you encountered:__

Hi all!

I've been reading other threads re: multisite but I'm still not clear on what the best approach would be for my setup. The thread at https://github.com/10up/ElasticPress/issues/1041 answers my questions about compatibility/functionality but not about performance.

I don't really need cross-network queries. Each of my child sites is owned by a different client. One or two clients have a few related child sites but for the most part 1 child site = 1 client with their own domain.

Does network activating the plugin impose some kind of performance penalty? If there's no downside then I'd prefer to network activate it for the dashboard, ease of use etc. However if there's a performance benefit in activating it separately on each child site then I'd consider doing it that way instead.

Thanks!

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__

Woocommerce, Easy Digital Downloads, WP-ERP

**Comment by felipeelia** [comment]
I know this has been waiting here for a while (sorry, @binaryfire!), so I'll leave a reply and close it.

No performance penalty is expected. Here are some pros and cons of the multisite activation:

Pros:
- Manage settings in just one place
- Cross-network queries

Cons:
- Synonyms and Weighting Dashboards are not supported
