### ISSUE TITLE
WooCommerce price filter widget doesn't work after 3.0 update

### ISSUE THREAD

**Issue by traed** [10up/ElasticPress#1346]
__Have you searched for similar issues before submitting this one?__
Yes

__Is this a bug, question or feature request?__
Bug

__Describe the issue you encountered:__
The WooCommerce price filter widget isn't working after updating to EP 3.0. The query params min_price and max_price are added to the URL but EP seems to ignore these. Looking at the query using debug bar there is no price filtering anywhere in the query.

__Current WordPress version?__
5.2.1

__Current ElasticPress version?__
3.0.2

__Current Elasticsearch version?__
Tested on 6.3 and 6.6

__Where do you host your Elasticsearch server?__
Own server

__What ElasticPress features do you have currently active?__
Post Search, WooCommerce, Related Posts, Facets

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
Advanced Custom Fields PRO
Debug Bar ElasticPress
Debug Bar
ElasticPress
Mailchimp for WooCommerce
Trustpilot-reviews
WooCommerce Brands
WooCommerce 3.6.3
Yoast SEO
WP Super Cache (not active)

__Steps to reproduce:__
1. Rebuild index.
2. Add the price filter widget to a widget area that shows up on the shop page.
3. Filter by price
4. Nothing changes

The filter works if I disable EP. This has worked in the past with EP enabled though. Could it have something to do with WooCommerce using lookup tables now?

**Comment by oscarssanchez** [comment]
Hi @traed ,

Just did a PR a couple of days ago to integrate the query with ES https://github.com/10up/ElasticPress/pull/1342. Would you mind doing some testing?

**Comment by traed** [comment]
@oscarssanchez See my comment on the PR
