### ISSUE TITLE
ep_search_request_path filter no longer available in 3.0

### ISSUE THREAD

**Issue by rpovelones** [10up/ElasticPress#1348]
__Have you searched for similar issues before submitting this one?__
Yes

__Is this a bug, question or feature request?__
Question

__Describe the issue you encountered:__
I've noticed the `ep_search_request_path` that was previously available in version 2.8 is no longer available in version 3+. I was using this filter to change the index ElasticPress searches to one or more indexes. Is there any option currently in 3.0 to filter the index/alias ElasticPress queries in Elasticsearch?

__Current WordPress version?__
5.2.1

__Current ElasticPress version?__
2.8.1

__Current Elasticsearch version?__
5.6.14

__Where do you host your Elasticsearch server?__
Elastic Cloud

__What ElasticPress features do you have currently active?__
Post Search, Related Posts, Facets

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
+--------------------------------+----------+
| name                           | version  |
+--------------------------------+----------+
| acf-content-analysis-for-yoast-seo | 2.3.0    |
| Gravity-Forms-ACF-Field-master | 1.1.0    |
| advanced-custom-fields-pro     | 5.7.13   |
| backupbuddy                    | 8.3.11.0 |
| classic-editor                 | 1.4      |
| column-shortcodes | 1.0 |
| disable-comments               | 1.9.0    |
| elasticpress                   | 2.8.1    |
| gravityforms                   | 2.4.8    |
| gravityformsmailchimp | 4.6 |
| redirection                    | 4.2.3    |
| smart-logo-showcase-lite | 1.1.1 |
| sucuri-scanner                 | 1.8.20   |
| wp-smushit | 3.2.0.1 |
| wp-extra-file-types                | 0.4.3    |
| wpdatatables               | 2.1    |
| wordpress-seo                  | 11.1     |
+--------------------------------+----------+

__Steps to reproduce:__

1. Update from ElasticPress 2.8.1 to version 3.0.2
2. Look through plugin source code and see `ep_search_request_path` filter is no longer available thus, my filter is not working

__Screenshots, if needed:__

**Comment by tlovett1** [comment]
You can use https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L634. However, we will readd in 3.0.3. Thank you!

**Comment by rpovelones** [comment]
Great! Thanks Taylor. I'll wait for 3.0.3 before upgrading.
