### ISSUE TITLE
Combined ES query and types question.

### ISSUE THREAD

**Issue by thesquaremedia** [10up/ElasticPress#1349]
__Have you searched for similar issues before submitting this one?__
yes
__Is this a bug, question or feature request?__
question
__Describe the issue you encountered:__
So in the latest version are post and users set as different types in the same index? I see that post/_search and then user/_search. I thought newer versions of elastic search since 6.0 query getting rid of multiple types. is there a way I could run a query to combine post and user searches that will come back as a full set of results that can be paginated together?

what is impeding the Users implementation from working on Wordpress 4.9. wanted to know as I was trying to test the feature on that wordpress version but was getting this sync error

Rejecting mapping update to [index_name] as the final mapping would have more than 1 type: [post, user]

As always I appreciate the help.

__Current WordPress version?__
4.9.10
__Current ElasticPress version?__
3.0.2
__Current Elasticsearch version?__
"6.2.4",
__Where do you host your Elasticsearch server?__

__What ElasticPress features do you have currently active?__

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__

__Steps to reproduce:__

1.
2.
3.

__Screenshots, if needed:__

**Comment by thesquaremedia** [comment]
I think I managed to get it working. question how can I override the Post Indexable either as a whole or the QueryIntegration Portion of things?

**Comment by thesquaremedia** [comment]
Just looking for confirmation but looks like adding the modify classes in the theme and running `Indexables::factory()->register( new CUSTOM_NS\Indexable\Post\Post() );` seems to override the plugins classes for the Post

**Comment by allan23** [comment]
@thesquaremedia were you able to resolve your issue?

**Comment by thesquaremedia** [comment]
hi yes it seems I was able to do what I was trying. to do. I manage to load my own customize Post indexable. and then I use the filter to skip the default post querying from running. as to not have two queries running at the same time. might be good to provide a way to load a developers customize version of the Post indexable class to change methods that don't have filter.
