### ISSUE TITLE
Elasticsearch version 6.8.0 and 7.1

### ISSUE THREAD

**Issue by skynet** [10up/ElasticPress#1356]
Any plans or timeline for making ElasticPress work with latest versions of Elastichsearch?

**Comment by nicolinuxfr** [comment]
I'm trying to use ElasticPress with ElasticSearch 6.8. 

Indexing and search features seem to work fine, so I was wondering : is there something I should know and maybe wait until an update ?

**Comment by shadyvb** [comment]
@tlovett1 FYI the readme still references 6.3 as the maximum supported version.
