### ISSUE TITLE
How to call facets widget on 3.0.3 ?

### ISSUE THREAD

**Issue by Salamander3** [10up/ElasticPress#1366]
Hi dumb question, on 2.8.2 i used to call facets like this:

```
$args['before_widget'] = '<div class="facet-wrap">';
$args['after_widget'] = '</div>';
$args['before_title'] = '<span class="filter-title">';
$args['after_title'] = '</span>';
echo '<aside class="widget-area">';
echo '<section id="ep-facet-3" class="widget widget_ep-facet">';
$taxonomies = array( 'genre', 'language', 'region');
	
	foreach ($taxonomies as $tax) {
		$instance['facet'] = $tax;
		$instance['title'] = $tax.'s';
  the_widget( 'EP_Facet_Widget', $instance, $args);
  
	}
  echo '</section>
  </aside>';
```

But now i updated the plugin it stopped rendering, i think the widget changed name but, i can't figure the new name. The old class was EP_Facet_Widget but now it's just "Widget" and it doesn't work, also tried ep-facet but no deal.

How can i make my code work with the new version?

**Comment by psorensen** [comment]
@Salamander3 Try using the full namspace: 

```php
the_widget( 'ElasticPress\Feature\Facets\Widget', $instance, $args )
```

**Comment by Salamander3** [comment]
> ```
> the_widget
> ```

@psorensen This works great after re-sync. Thanks.

Solved then.
