### ISSUE TITLE
Display an admin warning if nodes < 2

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#1373]
Per the Elasticsearch best practices we should show a notice to users in the Admin Dashboard if they're running an Elasticsearch setup with only 1 node. Using our new notice system, this should be dismissable in the Admin but mandatory on ElasticPress dashboard screens.

In general, this warning should notify if status != green (a single node automatically triggers yellow status).

We also want to link to the new Health dashboard so folks can track down where the issue is occurring.

**Comment by oscarssanchez** [comment]
Closing as this has been implemented already
