### ISSUE TITLE
400 error - bad request on WooCommerce categories

### ISSUE THREAD

**Issue by mforbak** [10up/ElasticPress#1376]
__Have you searched for similar issues before submitting this one?__
Yes, I have found [#1097](https://github.com/10up/ElasticPress/issues/1097) but unresolved.

__Is this a bug, question or feature request?__
bug

__Describe the issue you encountered:__
Every request on WooCommerce archive pages (shop page, categories, tags, size archive) returning **400 Bad Request**

__Current WordPress version?__
5.2.2

__Current ElasticPress version?__
3.0.3

__Current Elasticsearch version?__
6.3.2 (but the same error occurs when tested elasticsearch 5.x.x)

__Where do you host your Elasticsearch server?__
locally (docker)

__What ElasticPress features do you have currently active?__
Post Search, WooCommerce, Protected Content, Related Posts, Facets

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
WooCommerce, WooCommerce Blocks, ACF PRO, ARVE Advanced Responsive Video Embedder, PNG to JPG, Query Monitor, SmartLook Visitor Screen Recording, WP All Import Pro, WP All Import - WooCommerce Add-On Pro, Yoast SEO

__Steps to reproduce:__
I am not sure, I am worried it broke when I added many products. Or it could be broken when many attributes used? But for example blog page (with articles) have no issue. I think it is because many product attributes (maybe).

1. Install WordPress multisite
2. Import around 200k products
3. Run reindex using CLI
4. And now it is not working

I am not really sure why :)

__Screenshots, if needed:__
![image](https://user-images.githubusercontent.com/12497013/60025268-924a0d00-9699-11e9-87e5-7fc0b5924483.png)

**Comment by mforbak** [comment]
Ok, I probably found the issue. The issue occurs when sort by popularity is default. All other sorting options works fine, but popularity not.

![image](https://user-images.githubusercontent.com/12497013/60027205-4dc07080-969d-11e9-846a-c70067ef32c9.png)

**Comment by tlovett1** [comment]
@oscarssanchez will investigate. Perhaps orderby popularity isn't working.

**Comment by oscarssanchez** [comment]
Hi @mforbak ,

Thanks for reaching out and reporting, 

This relates to another issue we had in the past when price was set as default sorting. I'm not sure if this is due to new Woocoommerce version, but the fix for it seems to be the same. Would you mind testing if https://github.com/10up/ElasticPress/pull/1392  solves the issue for you ? 

Thanks!
