### ISSUE TITLE
elasticsearch-elasticpress docker

### ISSUE THREAD

**Issue by extremeshok** [10up/ElasticPress#1377]
Just a little heads up.

We have developed a docker container with elasticsearch which can be used for dev, testing or production 

* https://hub.docker.com/r/extremeshok/elasticsearch-elasticpress
* https://github.com/extremeshok/docker-elasticsearch-elasticpress

### Notes
```
elasticsearch/elasticsearch:6.3.2
added healthcheck
still uses default entrypoint and cmd
```
### Plugins
```
ingest-attachment : attachment (document/pdf) support
analysis-smartcn : support for chinese users or mixed english/chinese in posts.
analysis-phonetic : ignore spelling (support for mispelt keywords)
```

**Comment by tlovett1** [comment]
Thanks!

**Comment by extremeshok** [comment]
Any chance to have a mention (link) to the docker in the readme ?

**Comment by tlovett1** [comment]
Please submit a PR @extremeshok
