### ISSUE TITLE
Autosuggest: Quotes are not escape and break search results.

### ISSUE THREAD

**Issue by fabianmarz** [10up/ElasticPress#1387]
__Have you searched for similar issues before submitting this one?__
- ✅ 

__Is this a bug, question or feature request?__
- Bug 🐛

__Describe the issue you encountered:__
- If search results contain quotes the `data-search` attribute breaks, as the output is not escaped. See screenshot:

__Steps to reproduce:__

1. Index post with quotes
2. Search for post via the Autosuggest feature in EP

__Screenshots, if needed:__

![image](https://user-images.githubusercontent.com/863823/60517133-6d7c1800-9cdf-11e9-8422-35bbc1638221.png)

**Comment by tlovett1** [comment]
@oscarssanchez please test and create a fix PR.

**Comment by oscarssanchez** [comment]
Thanks for reaching out @fabianmarz ,

Would you mind testing https://github.com/10up/ElasticPress/pull/1391 to check if this solves your issue? 

Thanks!

**Comment by fabianmarz** [comment]
Can be closed as #1391 resolved it. Thanks for the fix!
