### ISSUE TITLE
Query Response Code: HTTP 400 - malformed URL

### ISSUE THREAD

**Issue by zandergrin** [10up/ElasticPress#1390]
Bug report

__Describe the issue you encountered:__

When setting up elasticpress on cloudways we're getting an error. 
When looking in the elasticpress debug bar we get Query Response Code: HTTP 400

Seems to be an issue with the URL. The Debug bar seems to show the URL for the query as
`URL: http://localhost:9200/wordpressxxxxxxxxxxcloudwaysappscomwp-post-1/post/_search`
(numbers replaced for security)

It looks to me like there's a slash missing from that at the least, at the most, it's completely the wrong path. I'm not sure where this URL comes from, how to correct it, or what it should be.

Here's the query that's calling it (have tried on a few different queries)

`             $q = new WP_Query([
                    'ep_integrate'   => true,
                    'post_type' => 'illustrator',
                    'posts_per_page' => -1,
                    'meta_query' => array(
                        array(
                            'key' => 'artist_type',
                            'value' => 'showcase'
                            )
                        )
                ]);`

It was all set up following these instructions - which have worked on other instances. 
https://www.cloudways.com/blog/elasticsearch-on-wordpress/

__Current WordPress version?__
Version 5.2.2

__Current ElasticPress version?__
3.0.3
__Current Elasticsearch version?__
tried 2.4 and 5.5
currently 5.5

__Where do you host your Elasticsearch server?__
cloudways

__What ElasticPress features do you have currently active?__
all default

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
I've disabled all plugins - except ACF (which the site needs to function) 

__Screenshots, if needed:__
![image](https://user-images.githubusercontent.com/1317985/60722067-bb835c80-9f27-11e9-8338-498f646fe029.png)

**Comment by brandwaffle** [comment]
Hi @zandergrin I'm not really able to determine if the URL is correct or not. If Cloudways installs Elasticsearch on the same server as your WordPress site, this URL might work. If not, then you're correct that it wouldn't work. That said, it appears to be the correct structure for a URL, so I'd start by insuring you have the correct URL in your settings page. Cloudways support should be able to assist with this.

**Comment by zandergrin** [comment]
thanks for the reply.. 
so what you're saying is
`IPADDRESS:PORT/PATHNAMEWP-POST-1/POST is correct.`
shouldn't it be
`IPADDRESS:PORT/PATHNAME/WP-POST-1/POST is correct.`
Note the slash between the pathname and wp-post-1 in the second one.

I've checked with cloudways and the server is correctly configured. 
I've checked the installation, and can see the path is being pulled through by other php functions correctly

So my question is - where is the value for this URL set? how is it set? Can it be manually set?

Thanks

**Comment by zandergrin** [comment]
ok thanks. I checked with cloudways before writing the ticket, they couldn't find an issue with the configuration. I checked the installation files and applications settings too. I guess I'll keep digging.

**Comment by brandwaffle** [comment]
https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable.php#L74

You may also want to expand the tabs showing the query body and query result. There's a chance that some custom code in the theme is creating mapping or other data that's not properly formatted for Elasticsearch that is causing the 400 error. If you deactivated plugins after the initial EP sync, make sure to run a full reindex as well, as you might have old fields created by those plugins still active in mapping.

**Comment by zandergrin** [comment]
sorry yes - I should have included that...

`"error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "No mapping found for [wpse_last_word] in order to sort on",
                "index_uuid": "uPXM7CiaSEq2P7q5-ep5SA",
                "index": "wordpress297460911126cloudwaysappscomwp-post-1"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "wordpress297460911126cloudwaysappscomwp-post-1",
                "node": "CM9XCoJWSN6tef0DP87DoA",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "No mapping found for [wpse_last_word] in order to sort on",
                    "index_uuid": "uPXM7CiaSEq2P7q5-ep5SA",
                    "index": "wordpress297460911126cloudwaysappscomwp-post-1"
                }
            }
        ]
    },
    "status": 400
}`
