### ISSUE TITLE
Autosuggest: Facet Widget choices

### ISSUE THREAD

**Issue by fabianmarz** [10up/ElasticPress#1394]
__Have you searched for similar issues before submitting this one?__
- ✅ 

__Is this a bug, question or feature request?__
- bug

__Describe the issue you encountered:__
- In https://github.com/10up/ElasticPress/blob/develop/assets/js/autosuggest.js#L248 `input[type="search"]` is used to trigger the autosuggest search query
- Such query is also triggered when using a Facet widget to drill down the facet choices as it's using `input[type="search"]` as well which also inserts an autosuggest list. In my case the list is empty (but didn't figure out why. I think that might be another topic)
- Probably the selector list should be tied to a more specific selector to avoid unnecessary ES queries

__Current WordPress version?__
- 4.9

__Current ElasticPress version?__
- head:develop

__Current Elasticsearch version?__

- 6.7

__Where do you host your Elasticsearch server?__
- Locally

__What ElasticPress features do you have currently active?__
- Autosuggest
- Facets
- Protected content

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
- WooCommerce

__Steps to reproduce:__

1. Insert facet widget into page
2. Check XHR when filtering for facet options
3. An `ep-autosuggest` list is inserted as well

__Screenshots, if needed:__
![image](https://user-images.githubusercontent.com/863823/60818590-3b1a6100-a19e-11e9-93ea-d578325292ea.png)

**Comment by oscarssanchez** [comment]
It feels like this is still a problem per https://github.com/10up/ElasticPress/blob/develop/assets/js/autosuggest.js#L359

**Comment by oscarssanchez** [comment]
Weirdly I could not reproduce this, although it would seem as if the problem is still valid. 

Tested with twentynineteen and twentytwentyone. @felipeelia or @Rahmon can you confirm or deny you can reproduce the bug?

**Comment by felipeelia** [comment]
I can't reproduce it. Actually, although we really get all `input[type="search"]` for autosuggest, we do remove the facet ones later since [EP 3.4.3](https://github.com/10up/ElasticPress/releases/tag/3.4.3) with:

```
const epInputs = Array.from(epInputNodes).filter(
	(node) => !node.classList.contains('facet-search'),
);
```
