### ISSUE TITLE
Help Adding "key name of the order ID"

### ISSUE THREAD

**Issue by flaversaver21** [10up/ElasticPress#1396]
I was able to figure out the "key name of the order ID", but I need help implementing this.

_Originally posted by @flaversaver21 in https://github.com/10up/ElasticPress/issues/1307#issuecomment-510584233_

**Comment by flaversaver21** [comment]
Going back to version 2.8.2 and toggling enable / disable of EP along with sequential order numbers pro and somehow I can now track orders. However, all orders are completely gone when you look at order history of a user. If I disable EP, I can suddenly see all my order history again. 

This might be the worst plugin on the planet. I've never had so many issues and they all started with version 2.8.X

**Comment by brandwaffle** [comment]
@flaversaver21 I'm sorry to hear you feel this way about the plugin. We do our best to provide general support for our free and open-source offering, and support for compatibility with other plugins is an area where we do our best to provide solutions, though the reality is there is a wide range of plugins created for WordPress and we are not able to provide compatibility for all of them.

In #1307 there is also additional information that we requested from you, including some debug output that would help us further troubleshoot your issue. In particular, if you provide us with the name of the meta key that you would like to whitelist, we can give you an example of how to use the filter we mentioned in #1307, which you would be able to drop into your functions.php file or anywhere you add custom code within your WordPress site. Without knowing the exact name, the format would be something like this:
```add_filter( 'ep_prepare_meta_allowed_protected_keys', 'whitelist_sequential_order_meta', 10, 2 );
function whitelist_sequential_order_meta( $meta, $post ) {
  $meta[] = '<name_of_meta_key>';
  return $meta;
}
```
Again, we are happy to help further troubleshoot with you to achieve the functionality you're looking for with our plugin and Sequential Order Numbers.

**Comment by flaversaver21** [comment]
I followed up with that info in the previous ticket, but clearly that was glossed over. 

Regardless, I have that part working and I have no idea how I fixed it per say. I'm no longer on version 3.0.3 either. Back to 2.8.2 

Now all customer orders are missing from their order history. Plus I can't search for order numbers, users, emails, or phone numbers in the admin order search. If I turn off EP, it all works. So how am I supposed to proceed here. I'm happy to give you FTP access to our server.

**Comment by flaversaver21** [comment]
Excuse me, I didn't put the order key in the ticket. I send that via email to both you and another one of your devs. 

The meta key Sequential Order Numbers is using:

_order_number

**Comment by brandwaffle** [comment]
@flaversaver21 thanks for the call yesterday! For those following along at home, if you need to add support for Sequential Order Numbers Pro to your ElasticPress/WooCommerce search, you can add the following filter to your functions.php:

```
add_filter( 'ep_prepare_meta_allowed_protected_keys', 'whitelist_sequential_order_meta', 10, 2 );
function whitelist_sequential_order_meta( $meta, $post ) {
  $meta[] = '_order_number';
  $meta[] = '_order_number_formatted';
  return $meta;
}
```

**Comment by volmerf** [comment]
Hi @brandwaffle I added your snippet to my functions.php and now I see the _order_number in the ES result query. But when I search in the woocommerce admin for a sequential order number instead of order id I don't get the right result. Any idea how to fix this? 

It looks like ES is not searching on this meta data.

ES result:
` "meta": {
                        "_order_number": [
                            {
                                "value": "3873",
                                "raw": "3873",
                                "long": 3873,
                                "double": 3873,
                                "boolean": false,
                                "date": "3873-03-13",
                                "datetime": "3873-03-13 10:29:36",
                                "time": "10:29:36"
                            }
                        ],
                        "_order_key": [
                            {
                                "value": "order_5d99a8de9059c",
                                "raw": "order_5d99a8de9059c",
                                "boolean": false,
                                "date": "1971-01-01",
                                "datetime": "1971-01-01 00:00:01",
                                "time": "00:00:01"
                            }
                        ],`

Any help would be appreciated.

**Comment by volmerf** [comment]
Also it's good to know for people who land on this solution to know thatafter adding the snippet to their functions.php they need to rebuild their index(es).

**Comment by volmerf** [comment]
@brandwaffle any update on this would be much appreciated. We still can't search for the order number generated by the sequential order plugin?

Thanks.

@flaversaver21 did you solve this problem?

**Comment by amanfredini76** [comment]
Hi,

my elasticpress search by post id, not order_number, even i've inserted this snippet

@flaversaver21

**Comment by amanfredini76** [comment]
any news @flaversaver21
