### ISSUE TITLE
get posts with featured image meta query not working

### ISSUE THREAD

**Issue by columbian-chris** [10up/ElasticPress#1401]
Is there a way to return only posts that have a featured image?

The following was not working for me:

```php
get_posts(array(
	'ep_integrate' => true,
	'meta_query' => array(
		array(
			'key' => '_thumbnail_id',
			'compare' => 'EXISTS'
		),
	)
))
```

**Comment by columbian-chris** [comment]
Appears to be working after 3.1.0 release. Might be related to "Support for nested tax queries" reported in version changelog.

**Comment by columbian-chris** [comment]
After resyncing, this functionality still appears to be very selectively working for me. Some of these queries are still throwing a 400 with this error returned:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "No value specified for terms query",
                "line": 1,
                "col": 233
            }
        ],
        "type": "parsing_exception",
        "reason": "No value specified for terms query",
        "line": 1,
        "col": 233
    },
    "status": 400
}
```

**Comment by dinhtungdu** [comment]
I tested this bug with a filter to allow indexing `_thumbnail_id`, ElasticPress works correctly and can query posts with thumbnail.
