### ISSUE TITLE
Ability to specify the number of shards/replicas has been removed

### ISSUE THREAD

**Issue by dustinrue** [10up/ElasticPress#1403]
**Describe the bug**
Version 1.2 introduced the ability to specify the number of shards/replicas at index creation time. This was removed in a recent release. You can see the addition at - https://github.com/10up/ElasticPress/blob/v1.2/classes/class-ep-api.php#L283. 

**Steps to Reproduce**

**Expected behavior**
Utilizing the filters mentioned would allow you to limit the number of shards/replicas

**Screenshots**

**Environment information**

**Additional context**

**Comment by tlovett1** [comment]
Hmm interesting. When was this removed?

**Comment by dustinrue** [comment]
It seems to have disappeared with the 3.0 release
