### ISSUE TITLE
Under some conditions you will receive an incorrect message of "An index is already occuring. Try again later"

### ISSUE THREAD

**Issue by dustinrue** [10up/ElasticPress#1404]
**Describe the bug**
This may happen with other curl issues but is easily triggered when the remote ES server is using a self signed SSL certificate. Under this scenario the cURL call will fail but EP takes this to mean an index operation is already happening. In version 3.0.3 of the plugin the error is issued at line 1070 of includes/classes/Command.php after attempting to `get_elasticsearch_version`.

**Steps to Reproduce**

1. Have ES made available using a self signed certificate (there may be other ways to trigger a curl error but this one always cause the issue)
2. Using wp-cli attempt to issue an elasticpress command such as `stats` or `status`
3. Get the incorrect error

**Expected behavior**
In previous versions of the plugin the error is simply that the ES server cannot be reached. In at least 3.0.3 the error incorrectly tells you an index operation is occurring. Expected behavior would be to output the actual cause or revert to the previous message. The full error would be much more useful however.

Also, occurring is spelled as "occuring"

**Screenshots**

**Environment information**
- ES: 5.6 through proxy using self signed SSL certificate
- ElasticPress Plugin: 3.0.3

**Additional context**
This error is probably most likely to occur in a development environment. To make things more difficult WordPress ships with its own ca-bundle.crt file which circumvents any curl.cainfo or openssl.cafile/capath settings in php.ini.

**Comment by tlovett1** [comment]
The develop branch decreases the likelihood of this error. However, it is still a problem. The solution is registering a shutdown hook in WP-CLI that cleans up the indexing transient. Other people are having issues with this as well.

**Comment by felipeelia** [comment]
It seems it is not a problem anymore, as the whole info about the ongoing sync is added only after the ES connectivity check. Also, the way all calls made to `Command::connect_check()` are done right now, would avoid any wrong message being displayed before the actual `Could not connect to Elasticsearch.` error.
