### ISSUE TITLE
Connection issues with Redis Object Cache plugin enabled

### ISSUE THREAD

**Issue by majemedia** [10up/ElasticPress#1405]
**Describe the bug**

When setting the host via dashboard to `http://localhost:9200` the "can't connect to host..." error message comes up.

If I then run `wp elasticsearch status` OR `wp elasticsearch index` and then refresh the dashboard the error goes away.

UNTIL

I hit one of the dashboard settings pages... then the error comes back.

The error also comes back if I deactivate OR reactivate Redis Object Cache

No changes occurred to the `wp_options` table during either of these.

I've already applied the filter from #1064 

**Expected behavior**

Error shouldn't show on dashboard with `http://localhost:9200` as a setting.

**Environment information**
- Ubuntu 18.04LTS
- ElasticPress: 3.0.3
- WordPress: 5.2.2
- Redis Object Cache: 1.4.3
- NGINX
- MariaDB

**Comment by dustinrue** [comment]
Hello @majemedia ,

Can you provide the output from `curl http://localhost:9200/` from the machine running the site?

Thank you!

**Comment by majemedia** [comment]
```
{
  "name" : "9IGC5tg",
  "cluster_name" : "CLIENTDATABASENAME",
  "cluster_uuid" : "OrcLl0h9Raqq3xbghh8N6A",
  "version" : {
    "number" : "6.5.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "8c58350",
    "build_date" : "2018-11-16T02:22:42.182257Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by dustinrue** [comment]
Would you be able to drop your Elasticsearch version to 6.3.2 and try it again?

**Comment by majemedia** [comment]
Sorry I cannot (production server) and this was installed via apt-get. I tried to see if aptitude had different versions available so that I didn't have to add the repo:

Results from aptitude versions elasticsearch

```
Package elasticsearch:
i   6.5.1
```

**Comment by dustinrue** [comment]
Ok, the highest officially supported version of ES is 6.3 and I'd try to rule out some kind of version incompatibility before digging in too far. When I setup WP 5.2.2 and Redis Cache 1.4.3 locally I was unable to replicate the issue.

**Comment by cy-slayer** [comment]
@majemedia Did you ever find a way to fix this?

Currently I have set up a cron to run wp elasticpress status to hit my server to keep on refreshing the connection.

**Comment by majemedia** [comment]
@cy-slayer I did not and I ended up just self-hosting a custom es server. It doesn't seem to have issues if you're going off somewhere else... the issue stems mainly around localhost connections (if I remember correctly)
