### ISSUE TITLE
Weighting: Taxonomies used on multiple Post Types don't show up

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#1414]
I use the same Taxononmies, even categories, tags... on multible Custom Post Types. On the new Weighting there are completly missing. 

**Describe the bug**

I think the problem ist on line 64 at includes/classes/Feature/Search/Weighting.php:

`		$taxonomies = get_taxonomies(
			[
				'public'      => true,
				'object_type' => [ $post_type ],
			]
		);
`

To query only for one `$post_type` gets you only post types that are registred to only this `$post_type`.

A solution could be to query all taxonomies and than check with `in_array` to object_type on every Taxonomy object.

**Steps to Reproduce**

1. Create a Custom Post Type and add e.g. "category" to "taxonomies" as an argument.
2. Go to the Weighting-Page
3. Category is missing from all post types.

**Expected behavior**

Taxonomies should be available to all post types.

**Environment information**
 - Plugins and version: 3.1

**Comment by cmmarslender** [comment]
@goaround thanks for filing this! Fix will be released with the next version.
