### ISSUE TITLE
index setup time out

### ISSUE THREAD

**Issue by kozora** [10up/ElasticPress#1424]
wp elasticpress index --setup 
Adding post mapping...
Success: Mapping sent
Indexing posts...
Processed 350/11114...
Processed 700/11114...
Processed 1050/11114...
Processed 1400/11114...
Processed 1750/11114...
Processed 2100/11114...
Processed 2450/11114...
Processed 2800/11114...
Processed 3150/11114...
Processed 3500/11114...
Processed 3850/11114...
Processed 4200/11114...
Processed 4550/11114...
Processed 4900/11114...
Error: cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes received

**Comment by dustinrue** [comment]
Can you provide some more information about the environment?  How is Elasticsearch hosted? If it is a provider what provider? If it is self hosted what is the health of the server? What are you indexing? Does it include documents?

This message typically means your Elasticsearch service is struggling to keep up. What you’re doing will help define how to adjust your indexing process.

**Comment by kozora** [comment]
I see in CHANGELOG there set a limit to 5000
https://github.com/10up/ElasticPress/blob/develop/CHANGELOG.md#added-11
I want to change it, where I can find the file

**Comment by mustafauysal** [comment]
> I see in CHANGELOG there set a limit to 5000
https://github.com/10up/ElasticPress/blob/develop/CHANGELOG.md#added-11
I want to change it, where I can find the file

@kozora you can use `ep_user_total_field_limit` and `ep_total_field_limit` filters to change default value.
