### ISSUE TITLE
Virtual post meta data

### ISSUE THREAD

**Issue by mch0lic** [10up/ElasticPress#1427]
**Is your enhancement related to a problem? Please describe.**
Unable to insert additional virtual/dynamic meta data for object, in this case WooCommerce product, into ElasticPress index.

**Describe the solution you'd like**
Option to programatically modify (add) object's meta data before it is inserted into ElasticSearch.

**Describe alternatives you've considered**
Open to ideas.

**Comment by jordan26** [comment]
If you add fields to a post type via ACF, they're sent to ElasticSearch automatically, however any which are added manually, such as I am with update_post_meta etc, ElasticPress does not know about them and does not sync them to ElasticSearch.

Therefore using the following filter you can declare the meta fields you would like the sync to send across also:

add_filter( 'ep_prepare_meta_allowed_protected_keys', function( $protected_keys ) {
    $protected_keys[] = '_your_meta_key';
    return $protected_keys;
} );

cc @mch0lic

**Comment by mch0lic** [comment]
@jordan26 I'm aware of this filter and this would only allow me to include **existing** meta key & value into the the index. If the meta data does not exist this is completely useless.

Why do I need this feature? I have custom data that is not stored as product meta (e.g. data in custom tables, dynamically created string, etc.). Some of the data could improve search results given it is added to the index as product meta and queries are tweaked using existing EP hooks, but at the same time I have no interest in duplicating data in database just to get this meta data to be picked up and index hence the new filter.

**Comment by felipeelia** [comment]
Closing this one as #1428 was merged and [`ep_prepare_meta_data`](http://10up.github.io/ElasticPress/ep_prepare_meta_data.html) was made available.
