### ISSUE TITLE
Question: How to ignore posts with a specific post_meta field

### ISSUE THREAD

**Issue by angtheod** [10up/ElasticPress#1437]
**Describe your question**

I need to check when searching the existence of a WP Page meta field (stored in `post_meta` table) so that I can ignore those pages.

Now, when I do a direct curl to ES (with the data below) I get the correct results
```
{
  "query":
  {
    "bool":
    {
      "must_not":
      [
        { "exists":
          {
            "field": "meta.do_not_index"
          }
        }
      ]
    }
  }
}
```
But I have not found a way to translate this correctly to EP arguments.
I have tried something like this in the `ep_formatted_args` filter but it is not working
```
$formatted_args['query']['bool']['must_not'] = [
	[
		'exists' => [
			'field' => 'meta.do_not_index',
		],
	],
];
```
Any help?
PS: Is there a way via EP to not Index those posts at all in the first place?

**Comment by mlaroy** [comment]
thanks @angtheod , we are looking into this issue.

**Comment by mlaroy** [comment]
Hi @angtheod 

The best way to omit your posts from search queries is to hook into the `pre_get_posts` action, and filter out your results with a meta query.

An example could look like:

```
<?php

add_action( 'pre_get_posts', function( \WP_Query $query ) {
    if ( $query->is_main_query() && $query->is_search() ) {
        $meta_query = [
            [
                'key' => 'do_not_index',
                'compare' => 'NOT EXISTS',
            ]
        ];
        $query->set( 'meta_query', $meta_query );
    }
} );
```

You can also do this using WP_Query:

```
<?php

$query = new WP_Query([
    'ep_integrate' => true,
    'meta_query' => [
        [
            'key' => 'do_not_index',
            'compare' => 'NOT EXISTS',
        ]
    ]
]);
```

Finally, preventing indexing may not be your best solution, since they would not show on the admin side either, if using the protected content feature.
However, if you really wanted to prevent these from being indexed by ElasticPress in the first place, you could add a function to hook into some filters:

```
<?php

/**
 * Checks if the do_not_index meta key is present (not empty) and doesn't index the post if so
 *
 * @param bool $should_kill_index
 * @param int|\WP_Post  $post_object Could be an id or possible an object
 * @return bool
 */
function check_skip_index( $should_kill_index, $post_object ) {
    $post = get_post( $post_object );

    $no_index_meta = get_post_meta( $post->ID, 'do_not_index', true );

    if ( ! empty( $no_index_meta ) ) {
        return true;
    }

    return $should_kill_index;
}

add_filter( 'ep_post_sync_kill', 'check_skip_index', 10, 2 );
add_filter( 'ep_post_index_kill', 'check_skip_index', 10, 2 );
add_filter( 'ep_item_sync_kill', 'check_skip_index', 10, 2 );
```

**Comment by angtheod** [comment]
Thank you @mlaroy

**Comment by pushpakpop** [comment]
For those who still stumble upon here, please note that : 

1. Best option is to use `pre_get_posts` hook and apply filtering through Meta Query as mentioned here : https://github.com/10up/ElasticPress/issues/1437#issuecomment-523669618
2. Anytime you are filtering using Meta_Query or Term_Query, the related Taxonomies and meta_fields should be whitelisted for indexing.
