### ISSUE TITLE
Add meta/range capabilities to facet feature.

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#1440]
Right now facet feature just supports taxonomies. Let's add support for meta and ranges.

**Comment by entttom** [comment]
Thats an awesome idea!

**Comment by razorfrog** [comment]
+1

**Comment by shmaltz** [comment]
+1

**Comment by felipeelia** [comment]
As support to meta was recently introduced, I'm breaking up the range part into a new issue: #3118.
