### ISSUE TITLE
no products were found matching your selection

### ISSUE THREAD

**Issue by alifazeli** [10up/ElasticPress#1442]
Hi
I have an Arabic WordPress site with woo-commerce.
Previously i install and test Elasticsearch and Elastic-press and there was no any problem.
but with new version when i enable Elastic-press and index my contents woo-commerce widgets don't show products in my homepage with this error:
no products were found matching your selection.
These are snapshots of my homepage and setting:

Homepage befor enabling Elasticpress:

![image](https://user-images.githubusercontent.com/45519108/63010402-95909680-be9b-11e9-9847-e9bfdabef492.png)
...........
Homepage after enabling Elasticpress:

![Capture3](https://user-images.githubusercontent.com/45519108/63010441-a3461c00-be9b-11e9-86b2-3922a25e2a49.PNG)
...............
![Capture4](https://user-images.githubusercontent.com/45519108/63010453-ab05c080-be9b-11e9-885e-d34af387a0f3.PNG)
...........
![image](https://user-images.githubusercontent.com/45519108/63010548-d4265100-be9b-11e9-975d-969a31b820c6.png)
........
![image](https://user-images.githubusercontent.com/45519108/63010586-e7d1b780-be9b-11e9-9be2-769be23d0dfc.png)

Tnx for support

**Comment by cmmarslender** [comment]
I'm not able to reproduce this with latest ElasticPress, Woocommerce, and the storefront theme. Can you let me know what theme you are using and what settings you have for you homepage as well so I can try and reproduce?

**Comment by alifazeli** [comment]
I use latest woocommerce version, bookie theme (v1.4.2) and WPBakery Page Builder 5.6. There is no problem when i choose sort by date or name but when i choose to sort products by random that massage apears. "no products were found matching your selection"
 
![image](https://user-images.githubusercontent.com/45519108/63441429-a5354f80-c446-11e9-8276-7ec248cfc410.png)

My website: https://ketabpedia.com

**Comment by cmmarslender** [comment]
@alifazeli Can you send me a copy of the theme that I can install locally (I think the theme also bundles the page builder?). You can email me at chris.marslender [at] 10up.com

**Comment by alifazeli** [comment]
@cmmarslender  I sent you my theme
tnx so much

**Comment by soufianejayden1000** [comment]
hello sir i have also this problem when i login to my wordpress wp-admin.php it show product 

when i copier web site link and past it in navigation private to see my blog as costumer it doesn't show the product

**Comment by soufianejayden1000** [comment]
if you see the first screen : SCREENSHOT :                  https://cdn.filestackcontent.com/W3DXzvavTFStOIF7X0DY
and the second screenshot from navigation private :    https://cdn.filestackcontent.com/Z7iSaHXqRICnDTl0CuVz

**Comment by zack-carlson** [comment]
@cmmarslender What was the resolution to this?  This seems to happen when a node drops on ElasticSearch..
