### ISSUE TITLE
Running wp cli index doesn't set site_option for ep_index_meta to pause WP Queries to EP 

### ISSUE THREAD

**Issue by eflorea** [10up/ElasticPress#1448]
**Describe the bug**
Running wp cli index doesn't change the option ep_index_meta to pause WP Queries being integrated with EP so if you run a wp cli command with --setup the data is deleted on ES side and therefor the queries return no results (until EP syncs something)

![Screen Shot 2019-08-20 at 1 44 58 PM](https://user-images.githubusercontent.com/13055601/63383645-0e876680-c352-11e9-9c8b-417f447a0d97.png)

Running the sync through the dashboard works as expected.
![Screen Shot 2019-08-20 at 1 50 40 PM](https://user-images.githubusercontent.com/13055601/63383682-2232cd00-c352-11e9-98a6-c40cbe1e70c9.png)
![Screen Shot 2019-08-20 at 1 50 54 PM](https://user-images.githubusercontent.com/13055601/63383687-23fc9080-c352-11e9-8876-cc5da0ceb4ae.png)

**Steps to Reproduce**

1. Run a wp cli command to index: elasticpress index --setup
2. View any page that has a WP Query that integrates with EP
3. Multiple refreshes might be required but you will get a page/no results found for 1-2 seconds (or until EP synced that data)

**Expected behavior**

The wp cli command sets the flag and all the queries integrated with EP should be paused and ran against WP DB only.

**Notes**
Looking at code it seems that if the plugin is network enabled and running an index only on a specific site it shouldn't pause the EP integration for the other sites.
https://github.com/10up/ElasticPress/blob/develop/includes/utils.php#L123

CC: @christianc1

**Comment by tlovett1** [comment]
Thanks @eflorea. We are looking into this.
