### ISSUE TITLE
Re-factor to Vanilla JS by removing jQuery dependency 

### ISSUE THREAD

**Issue by samikeijonen** [10up/ElasticPress#1456]
**Is your enhancement related to a problem? Please describe.**
In most cases projects don’t use jQuery in the FE anymore and jQuery is kind of a blocker.

**Describe the solution you'd like**
Re-write JS like `autosuggest.js` in Vanilla JS.

**Comment by oscarssanchez** [comment]
Closing as frontend seems to be Vanilla JS per https://github.com/10up/ElasticPress/issues/2074
