### ISSUE TITLE
How to reindex post by ID

### ISSUE THREAD

**Issue by ijakparov** [10up/ElasticPress#1460]
Can't find way to trigger update index for post by id.

**Comment by mustafauysal** [comment]
hi @ijakparov,

something like:
```
wp elasticpress index --include=8,12
```
should work through WP-CLI. 

```
$indexable = \ElasticPress\Indexables::factory()->get( 'post' );
$indexable->index( $post_id, true );
```
if you are writing something that interacts with EP.
