### ISSUE TITLE
Extra params & new filter ep_<action>_<type>_request_path

### ISSUE THREAD

**Issue by koizuminana** [10up/ElasticPress#1464]
**Is your enhancement related to a problem? Please describe.**
1. Index API for ES > 7.0 is wrong.
2. Delete API for ES > 7.0 is wrong.

Both solutionable using filters but not always out of the box.

**Describe the solution you'd like**
1. Add `index` param to `ep_index_<type>_request_path` filter;
2. Add missing filter `ep_delete_<type>_request_path` in `Elasticsearch::delete_document()`;
3. Add `index` param to `ep_bulk_index_request_path` filter;
4. Would be nice to also fix `index` and `delete` api for > 7.0: `/<index>/_doc/<_id>`; 

**Describe alternatives you've considered**
1. For wrong Index API you can use `ep_index_post_request_path` filter to force the correct one `/<index>/_doc/<_id>`;
2. For wrong Delete API, since `ep_delete_<type>_request_path` is not available, use `ep_pre_request_url` filter to force the correct one `/<index>/_doc/<_id>`;
3. For missing `index` in params, extract manually from `$path` param available;

**Comment by felipeelia** [comment]
This was fixed in #1398. Thanks!
