### ISSUE TITLE
Validate mapping currently in index against expected version

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#1471]
Sometimes the mapping fails or gets outdated. It would be good to detect outdated mappings and provide feedback in the admin interface.

**Comment by tlovett1** [comment]
@tott can you explain to me what this is intended to solve? If someone upgrades Elasticsearch, show them a warning they need to reindex? Seems pretty edge case. It would be nice to have a unit test and include as part of a major release.

**Comment by tott** [comment]
This is in relation to #1466.We have had a good amount of cases where things are failing due to invalid mapping, not only from this issue but also prior to this. This will help identify when the mapping is outdated and a reindex should occur
