### ISSUE TITLE
PHP method to reindex a site / all sites

### ISSUE THREAD

**Issue by jgmedialtd** [10up/ElasticPress#1479]
A way of invoking a complete site index via php. At the moment I'm aware of an ajax and an WP CLI mechanic to achieve this but would be great to be able to use PHP also.

**Comment by felipeelia** [comment]
In ElasticPress 4.0 it will be possible using the `IndexHelper::factory()->full_index()` method.

**Comment by felipeelia** [comment]
As #1835 was already merged to the `4.x.x` branch, I'm closing this one out. Thanks!
