### ISSUE TITLE
How to search after acf object relations ?

### ISSUE THREAD

**Issue by bensch777** [10up/ElasticPress#1482]
Hey all,

i am struggling a bit with my search query and maybe someone of you can help me.

**Field-Setup**
I've two custom post types. One is called events and the other one cities. If i create a new event i can select one of my cities, because i used entry object configuration of the acf fields.

**Challenge**
If the user searches after a city e.g. Berlin i want also search for events, which have a relation to this city.

On the post object of the events, i can found "cities" but in this array the number of the city is stored. If i add city to the searchable fields and search for the city id i get the correct results, but this is not the way how the user search ;)

Does someone have an idea, how to solve it or have i to work with helper fields on the event? 

thanks in advance,
bensch

**Comment by tkorsback** [comment]
I'm trying to do the same thing. A city post type have many of the company post type via ACF relationship. I'm thinking "aggs" but I need to read/try some more.

**Comment by oscarssanchez** [comment]
I don't understand fully the User experience for both scenarios, but wouldn't faceting work here ? You would need to create a taxonomy for that though. 

Kind regards,

**Comment by tkorsback** [comment]
@oscarssanchez In my case I would like to include the content from a related post and not just the ID in order to prevent another query for each post in the search result. Like eager loading in Laravel.

**Comment by oscarssanchez** [comment]
Sorry @tkorsback  but i'm still lost. Another query to ES won't matter too much. As long as you are not doing way too many this should be totally ok. Maybe if you can clarify what do you mean you want to include the content from a related post would be great, as I'm thinking that can be done with a More like this query but i might be deviating from the original question ...

**Comment by gregoriopellegrino** [comment]
I have the same problem: I have one post type for videos and one for playlists. With ACF in every playlist there are n videos. I'd like to bring this structure back into ElasticSearch, but I can't figure out how.

**Comment by oscarssanchez** [comment]
Hi @gregoriopellegrino ,

If only one query is needed, you could achieve this by pasting the post content into the ACF field, and later on adding these fields to be searchable fields via `pre_get_posts` filter. This however does not look scalable for me. Another alternative to look at might be the more like this query https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html
