### ISSUE TITLE
Is it running?

### ISSUE THREAD

**Issue by danielslyman** [10up/ElasticPress#1484]
Hey guys,

stupid question:

self-hosted Elasticsearch instance, connection successful.

However, the search results are identical to the regular WP search results. How do I know if this is working?

Greetings,
Daniel

**Comment by dominikkuen** [comment]
Install the debug bar plugin mentioned:
https://github.com/10up/ElasticPress#debugging

**Comment by danielslyman** [comment]
I did it's empty?

**Comment by danielslyman** [comment]
I reinstalled elasticsearch on my server. Connection successful, also tested with " curl -X GET "localhost:9200/" 
The query log however remains empty

**Comment by danielslyman** [comment]
Got it sorted! Thanks

**Comment by MVPoker** [comment]
> Got it sorted! Thanks

How did you resolve it, im facing the same issue.
