### ISSUE TITLE
Autosuggest breaks when all search fields are disabled in Manage Search Fields & Weighting

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#1486]
**Describe the bug**
When disabling all search fields for a post type in Manage Search Fields & Weighting an empty array as shown below gets injected into the autosuggest request causing the request to fail.

**Steps to Reproduce**
1. Install EP 3.1.4 / Core WP stock 2019 theme / default content
2. Activate / configure plugin and ensure autosuggest is enabled
3. navigate to Manage Search Fields & Weighting
4. Disable all search fields for post type page
5. Visit site and type into search box
6. No results will be returned and the request payload will include the following 
                                    
                                     { 
                                       "multi_match":{ 
                                          "query":"testsearch",
                                          "fields":[ 

                                          ],
                                          "fuzziness":1
                                       }
                                    }

**Expected behavior**
Post types with no active search fields should be excluded from Autosuggest payload.

**Additional context**
Given that a 400 error is returned and usually triggering a CORS error this is likely related to : #1184

**Comment by tott** [comment]
This is only partially completed at this point I think. When not selecting any field we should still disable the search altogether. Do you want to capture this separately @tlovett1 ?

**Comment by oscarssanchez** [comment]
Fixed with #1532
