### ISSUE TITLE
[terms] query does not support [1] within lookup element

### ISSUE THREAD

**Issue by fhfournier** [10up/ElasticPress#1492]
Hi,

There is a big problem with the latest version of your plugin. Before that update eveything works fine!

![image](https://user-images.githubusercontent.com/3278753/65183171-e5312780-da30-11e9-9563-93219a043130.png)

```
{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": "piscine",
                        "type": "phrase",
                        "fields": [
                            "post_title",
                            "post_excerpt",
                            "post_content"
                        ],
                        "boost": 4
                    }
                },
                {
                    "multi_match": {
                        "query": "piscine",
                        "fields": [
                            "post_title",
                            "post_excerpt",
                            "post_content"
                        ],
                        "boost": 2,
                        "fuzziness": 0,
                        "operator": "and"
                    }
                },
                {
                    "multi_match": {
                        "query": "piscine",
                        "fields": [
                            "post_title",
                            "post_excerpt",
                            "post_content"
                        ],
                        "fuzziness": 1
                    }
                }
            ]
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": {
                            "1": "page"
                        }
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "post_type.raw": {
                                    "1": "page"
                                }
                            }
                        },
                        {
                            "term": {
                                "post_status": "publish"
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "communications_categories": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.communications_categories.slug"
                    }
                }
            }
        }
    }
}
```

**Comment by tlovett1** [comment]
Which version were you on and which did you update to?

**Comment by fhfournier** [comment]
2.8.2 => 3.1.4

I have 3 website in elasticsearch server (3 index and with version 3.1.4, i have now 6 index)

I had to switch back to 2.8.2 because my result page is broke. All link inside search result display no exerpt and no link. The global $post variable doesnt include permalink or meta data.

Even if i disable "post search" i still have 2 index / site with data and i have resync multiple time.
- beloeilca-1
- beloeilca--post-1

If i sync, **beloeilca-1** contain data and  **beloeilca-post-1** is empty. But when i got update a post, the index **beloeilca-post-1** is change and contain data... Is it normal, i disable "post search"?

And if i enable "post search" my result page works! But because i have 2 index, all post is display in double.

Here my only code to modify elasticpress

```
if ( ! function_exists('activis_ep_index_name') ) :
	function activis_ep_index_name( $index_name, $blog_id ) {
		if( is_search() ) :
			return '*';
		else :
			return $index_name;
		endif;
	}
	add_filter( 'ep_index_name', 'activis_ep_index_name', 1, 2 );
endif;
```

**Comment by novazembla** [comment]
Hello, 

not on upgrading but on a new site I'm also experiencing similar strangeness. I've configured a `EP_INDEX_NAME` in `wp-config.php` but on indexing the site (either via the admin tool and/or via WP CLI) the site creates domainname-post-1 as the index. It seems to be ignoring the configured index name constant. 

Did something change on the 3.1 branch? 

Thanks!

**Comment by fhfournier** [comment]
exactly and also with WP CLI
```
wp elasticpress stats
```

i got sitename-post-1

**Comment by michaelpark716** [comment]
I'm experiencing the same issue.  I've tried both on Elasticpress version 3.1.3 and 3.1.4, 
I get the error below in the debug bar. All my posts are indexed. 

Query Response Code: HTTP 400
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "[terms] query does not support [post] within lookup element",
                "line": 1,
                "col": 5520
            }
        ],
        "type": "parsing_exception",
        "reason": "[terms] query does not support [post] within lookup element",
        "line": 1,
        "col": 5520
    },
    "status": 400
}

**Comment by tlovett1** [comment]
@fhfournier what features do you have active?

**Comment by tlovett1** [comment]
Maybe I'm forgetting something but I don't see anything about an `EP_INDEX_NAME` constant. Is everyone just using the filter?

**Comment by novazembla** [comment]
Oh! I've been using a constant called `EP_INDEX_NAME` in many of my projects for many years. Not sure where this one came from? Could well be that I came up with it myself (as it is an easy helper building custom queries to ElasticSearch). 

Anyhow, this still does unfortunately not explain why the index name has changed after the version upgrade. For years, an update of ElasticPress did not change the index name (after running wp elasticpress index --setup). But suddenly the `-post` has been added. Is that right?

**Comment by oscarssanchez** [comment]
This should be because of our introduction of indexables. We have introduced the `terms`, `post` and `user` indexables

**Comment by roborourke** [comment]
If anyone is hitting this (original) issue it's because the arrays being used to set the `terms` queries are not zero-indexed. This means `json_encode()` will interpret them as objects and not arrays. End result is that Elasticsearch rejects it as a malformed query.

Example:

```json
{
    "terms": {
         "post_type.raw": {
               "1": "page"
          }
    }
}
```

Should be:

```json
{
    "terms": {
         "post_type.raw": [
               "page"
          ]
    }
}
```

Possible mitigation:

Check the arrays you are using when passing arguments to `WP_Query`, make sure you pass them through `array_values()` first.
