### ISSUE TITLE
Taxonomies not indexed on a subsite

### ISSUE THREAD

**Issue by eflorea** [10up/ElasticPress#1497]
**Describe the bug**
On a multi-site install a sub-site that has custom taxonomies are not being indexed. The only way to index them is to run the wp cli command to index only that site.

**Steps to Reproduce**

1. Network activate EP plugin
2. Register a public taxonomy on a sub-site (with a plugin enabled only on that subsite or child theme etc)
3. Run an elasticpress index network wide (with the UI or wp cli)
4. Taxonomies are not being indexed so you cannot filter posts by it etc.

CC: @christianc1

**Comment by asharirfan** [comment]
@brandwaffle I have found the following ticket that discusses the impact of using `switch_to_blog` with other functions that depend on the global arrays like `get_object_taxonomies`.

https://core.trac.wordpress.org/ticket/20541

**Comment by mckdemps** [comment]
Per the comment above, this seems to be a limitation of core when running in network mode. The workaround of per site indexing is the best approach for the time being.
