### ISSUE TITLE
Partial / Fuzzy Search Results

### ISSUE THREAD

**Issue by danielslyman** [10up/ElasticPress#1500]
Hello all,

so relatively new to ES and EP. I installed it on a WooCommerce site and all is working really well so thanks a lot! However, I wish I could somehow make sure queries with spelling errors and partial terms could work. For example: 

One page is called "Fachkataster" but searching "Kataster" does not result in any matches.

I looked around but wasn't able to find out how to achieve this. Elasticpress is installed locally.

Thanks

**Comment by oscarssanchez** [comment]
Hi @danielslyman ,

A bit late here but you may want to play with the fuzzy argument in the query sent to elasticsearch via the `ep_formatted_args` filter
