### ISSUE TITLE
Fix breakpoint on index health point in 3.2

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#1501]
**Is your enhancement related to a problem? Please describe.**
The Index Health dashboard should get better breakpoint treatment at around 1115 px width.
Currently when it switches to a two column to a one column layout there is a breakpoint in which the widgets do not scale to full width for one column as seen in the screenshot at https://i.imgur.com/qdZTtwF.png

**Describe the solution you'd like**
Make the column full width as in the mobile breakpoint

**Designs**
https://i.imgur.com/qdZTtwF.png

**Comment by jeffpaul** [comment]
Closed via 1733
