### ISSUE TITLE
Search Fields & weighting not enabling all relevant taxonomies

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#1503]
When installing the plugin not all public taxonomies are considered for Search Fields & weighting by default.
This can be seen for example when installing Woocommerce and activating ElasticPress. In this case the Products post type and attributes are properly enabled but product categories, tags and shipping classes are not included although these are public taxonomies. Currently only post_tag and category and taxonomies injected through ep_weighting_default_post_type_weights are enabled by default.

**Describe the solution you'd like**
I would expect all public taxonomies to be made searchable by default.

**Comment by felipeelia** [comment]
Related line in code: https://github.com/10up/ElasticPress/blob/3.6.4/includes/classes/Feature/Search/Weighting.php#L134

**Comment by brandwaffle** [comment]
We'll add a filter here to make this customizable by site owners.
