### ISSUE TITLE
PHP Fatal Error ElasticPress 3.2 with WordPress version lower than 5

### ISSUE THREAD

**Issue by lucymtc** [10up/ElasticPress#1505]
**Describe the bug**

While testing new EP version 3.2 a PHP Fatal Error is thrown with WordPress 4.9.11

`Fatal error: Uncaught Error: Call to undefined function ElasticPress\Feature\RelatedPosts\register_block_type() in /var/www/html/wp-content/plugins/ElasticPress/includes/classes/Feature/RelatedPosts/RelatedPosts.php on line 216`

`register_block_type` is called but does not exist. 

**Steps to Reproduce**

1. Install WordPress 4.9.11
2. Install plugin ElasticPress 3.2
3. Activate ElasticPress 3.2

**Expected behavior**

Plugin should activate with no errors.

**Screenshots**

**Environment information**
 - Device: Macbook Pro
 - OS: MacOS 10.13.4
 - Browser and version: Chrome (all)
 - Plugins and version: ElasticPress 3.2
 - Theme and version: Twenty Nineteen 1.4
 - Other installed plugin(s) and version(s): None

**Additional context**

**Comment by adamsilverstein** [comment]
@lucymtc Thanks for the bug report! Hooking the callback on `enqueue_block_editor_assets` instead of `init` should fix this. I'll prepare a PR.

**Comment by adamsilverstein** [comment]
@lucymtc Can you please check if this PR resolves the issue you were seeing: https://github.com/10up/ElasticPress/pull/1506
