### ISSUE TITLE
Error reporting, add nobulk index, fill in documentation for transition from v2 to v3

### ISSUE THREAD

**Issue by triskator** [10up/ElasticPress#1511]
Hi,
I accidentally found out that our site wasn't indexing because it was searching some unrelated posts. Seems that since v2 and something we had this issue, client didn't report it, so I hadn't reason to look until I've worked on new feature including search mechanism. Thing is that it tried to index but failed somewhere at 17000 of 37000 on something. So there was something indexed but not enough, I wouldn't like to be the user actually searching for something and getting weird results. I guess there's some meta too big in some post, but I can't find out because it doesn't show me anything, just that there was an error and it stopped indexing. 

So I would like to ask why there isn't nobulk feature like is in WP CLI to skip invalid posts and then report which ones and why it failed, or at least which ones. It should be obvious looking at meta data for actual post what is causing error but I need at least post id. Not that it just stops in middle and won't index the rest. Client just clicks sync and thinks it will work which should.

Also I've tried updating from v2 to v3 because I was hoping you fixed this in the meantime, client doesn't do updates too often in fear it would break. Well it did break, we have used filter ep_post_sync_args_post_prepare_meta in code and used EP_API::factory()->prepare_meta_types which thrown a fatal error in v3. I couldn't find either the filter or which class or anything I should use for adding custom meta data so I ended up with copying prepare_meta_types and prepare_meta_value_types in functions.php and used that in the filter. I'm not sure if you don't have it indexed on google or not at all in any documentation. I didn't have much time for search because I'm working on the other feature but only thing I've found is that there are some Indexables and that's it. Nothing about them just that I can extend class. Just to note, click is paying for elasticpress.io so it isn't just random custom server where is elasticsearch installed.

I'm not sure if there's better way of adding custom meta or anything, I really didn't have time to look what's new in detail, but I couldn't find anything about transition from v2 to v3, I just found out it doesn't work anymore by the error.

So at the end, it would be nice to have added some kind of error reporting, which posts didn't make it. Then skip the problematic ones or offer nobulk instead in admin and skip them and lastly, there are things that many of us used in previous versions including filters and EP_API to satisfy client needs.  There weren't weights in admin in v2 either until now, thank you for that. Just I had issue with using the filter and EP_API and couldn't find quick way to fix that so it started working.

Thank you for reading this.

**Comment by felipeelia** [comment]
First of all, @triskator, I'm very sorry for the time your issue took to be replied to here. More recent issues have been replied to much faster but, unfortunately, we are taking more time to get to these older ones.

As it's been some years now and we've just released EP 4.0.0, instructions on how to transition from v2 to v3 or v4 don't make much sense anymore. I'm glad to see we've addressed some (if not all) of your concerns and problems in v4.0.0, like error logging for dashboard syncs.

I'm going ahead and closing this one out now, hoping you can give EP 4 a try. Thanks for the feedback!
