### ISSUE TITLE
Control which "_source" fields from index to return

### ISSUE THREAD

**Issue by kmcaloon** [10up/ElasticPress#1513]
So I'm assuming this might already exist but I did not find it in the docs. Is there a way to control which fields are returned from the index?  For instance, I'm looking to replicate Elasticsearch's REST API source filtering feature here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html#mget-source-filtering

The goal is to bypass the typical fields returned by WP_Query and instead just get all the raw data within the index without having to touch WP's database.

I guess related to this is does ElasicPress have an easy way that we can just make our own requests without using WP functions? I'm guessing we would have to just look around the `Elasticsearch.php`, but wasn't sure if there were any more details out there.

**Comment by brandwaffle** [comment]
@kmcaloon you can change the `_source` value to whatever you'd like using the `ep_formatted_args` filter https://github.com/10up/ElasticPress/blob/941b5c69e1b0622babe3c54852e03a1a91b70d33/includes/classes/Indexable/Post/Post.php#L1298

I'm not sure exactly what you're referring to about bypassing WP_Query fields, as by default ElasticPress is essentially skipping the MySQL query and returning results from Elasticsearch. What you do with that data might include loading meta/taxonomy data from WP, but it doesn't have to.

To make a request using ElasticPress, you can call EP's `remote_request` method https://github.com/10up/ElasticPress/blob/27145db9a0b4fe2a41c2f81a51f0919a3a918eb1/includes/classes/Elasticsearch.php#L847. Please note that will use all sorts of WP functions like wp_remote_get, so it might not be what you're talking about. ElasticPress does not have any way to completely bypass WP as it's designed to be a query translation engine for WP, but you can always issue any Elasticsearch JSON query to your endpoint assuming it follows the correct format and then parse the response.
