### ISSUE TITLE
Weighting: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by khelil** [10up/ElasticPress#1515]
**Describe the bug**
After updating to version 3.1.4 (same with 3.2) i'm getting Warning messages on Search page :

Warning: Illegal offset type in isset or empty in ../elasticpress/includes/classes/Feature/Search/Weighting.php on line 370

Warning: Illegal offset type in .../elasticpress/includes/classes/Feature/Search/Weighting.php on line 389

And i'm not getting search results from Elastic, but the classic WP.
Autosuggest is broken also, got a 404 error.

**Steps to Reproduce**
No steps, just broke after 3.1.4 update. Just updated to 3.2 but got same problems

**Environment information**
 - Device: MacBook
 - OS: Mojave
 - Browser and version: Chrome Version 77.0.3865.90
 - Plugins and version: WPML + ACF
 - Theme and version: Sage 8.6 from Roots.io

**Additional context**
Working with a website running locally on Vagrant, indexing et request on Elasticpress.io

**Comment by tlovett1** [comment]
@khelil does the error happen with WPML deactivated?

**Comment by khelil** [comment]
Yep @tlovett1 no more errors when WPML deactivated and search works fine !
Perhaps an issue with untranslated weight fields ?

**Comment by tott** [comment]
I added an initial changeset to address the symptoms. I'm still evaluating if I can identify the cause.

**Comment by brandwaffle** [comment]
@khelil We'd like to include this in our next release (targeted for today) but we'd need to understand if there are any other factors that are causing this issue before we push the code that works around the symptoms. Can you let us know if you've got any custom code per @tott 's question about? Thanks in advance and thanks for submitting this bug report!

**Comment by khelil** [comment]
@brandwaffle @tott sorry guy'z, just saw your message. We have custom code for theme and plugin, we developed both from scratch, but no code is changing the search feature or results. 
In doubt, if you want, send me you emails i can give you access to our repo on github, for you to check.

**Comment by khelil** [comment]
@brandwaffle @tott no more bug here. After updating WPML to Version 4.3.1, no more notices and search results are as expected ! Closing the issue, Thank you 🙏
