### ISSUE TITLE
Posts from trash are showing in search results page

### ISSUE THREAD

**Issue by lapak10** [10up/ElasticPress#1516]
When doing any search, posts from trash are getting displayed on the search results page.
The expected behaviour is posts from trash must be **excluded** from search. Please help

**Comment by tlovett1** [comment]
I'm not seeing this. Is it happening on the front end? What plugins are you using? What features are you using?

**Comment by lapak10** [comment]
Yes it is happening on front-end. Trashed posts are listed in the search results (may be the hook to resync are not getting fired when post is trashed? ), but once they are permanently deleted, only then they are getting removed from the search results page.

I am not certain if this is applicable to every EP user or not, but I fixed it by creating a custom plugin, which is responsible for collecting the IDs of all trashed posts in array, then passing it to $args array as value of `'post__not_in'` key.
