### ISSUE TITLE
Search results only displaying posts  with exact title.

### ISSUE THREAD

**Issue by lapak10** [10up/ElasticPress#1517]
Let suppose there is a post whose title is *ElasticPress is awesome*

When a user make search with exact search string as ElasticPress is awesome only then the above pots is given in search results page.

But searching for *ElasticPress is a awesome* gives no result (which is should display similar posts with similar title)

How can achieve the expected behaviour ?

**Comment by brandwaffle** [comment]
@lapak10 by default, ElasticPress should return the results for "ElasticPress is a awesome" based on fuzzy matching. Can you install the Debug Bar and Debug Bar ElasticPress plugins and share the results of your WP and EP query bodies? Thanks!
