### ISSUE TITLE
Version 3.2 breaks post edit screen in WP 

### ISSUE THREAD

**Issue by digiswede** [10up/ElasticPress#1518]
**Describe the bug**
Updated to Elasticpress version 3.2. 
Now, the post edit screen in admin shows an error message stating that something went wrong with the post.

**Steps to Reproduce**
1. Update from Elasticpress 3.1.4 to 3.2
2. Go to WP Admin > Posts > Any post
3. WP styled error message shows

**Expected behavior**
Edit post screen should load just fine.

**Environment information**
 - WP version 5.2.3
 - (Gutenberg editor)
 - Plugins:
```
+------------------------------------+--------+--------+----------+
| name                               | status | update | version  |
+------------------------------------+--------+--------+----------+
| 404page                            | active | none   | 11.0.4   |
| advanced-custom-fields-pro         | active | none   | 5.8.4    |
| all-in-one-favicon                 | active | none   | 4.7      |
| bladerunner                        | active | none   | 1.7.4    |
| cms-tree-page-view                 | active | none   | 1.6      |
| custom-post-type-widgets           | active | none   | 1.2.0    |
| disable-comments                   | active | none   | 1.10.2   |
| download-monitor                   | active | none   | 4.4.2    |
| duplicate-post                     | active | none   | 3.2.3    |
| easy-google-fonts                  | active | none   | 1.4.4    |
| elasticpress                       | active | none   | 3.1.4    |
| favorites                          | active | none   | 2.3.1    |
| featured-image-column              | active | none   | 0.3.2    |
| google-analytics-dashboard-for-wp  | active | none   | 5.3.9    |
| gravityforms                       | active | none   | 2.4.14.4 |
| gravity-forms-custom-post-types    | active | none   | 3.1.15   |
| gravityformscli                    | active | none   | 1.1      |
| ht-blocks                          | active | none   | 1.0      |
| ht-continuous-scroll               | active | none   | 1.0      |
| ht-team                            | active | none   |          |
| idkollen                           | active | none   | 0.4.9    |
| list-custom-taxonomy-widget        | active | none   | 4.1      |
| mailchimp-for-wp                   | active | none   | 4.6.1    |
| post-expirator                     | active | none   | 2.4.0.1  |
| reading-time-wp                    | active | none   | 2.0.5    |
| real3d-flipbook                    | active | none   | 2.30     |
| redirection                        | active | none   | 4.4.2    |
| rename-media-files                 | active | none   | 1.0.1    |
| resize-image-after-upload          | active | none   | 1.8.6    |
| safe-svg                           | active | none   | 1.9.4    |
| simple-history                     | active | none   | 2.32     |
| soil                               | active | none   | 3.8.1    |
| woocommerce-swish                  | active | none   | 1.0.2    |
| woocommerce-memberships-for-teams  | active | none   | 1.1.3    |
| autodescription                    | active | none   | 4.0.1    |
| user-switching                     | active | none   | 1.5.2    |
| widget-context                     | active | none   | 1.2.0    |
| widget-css-classes                 | active | none   | 1.5.4    |
| woocommerce                        | active | none   | 3.7.1    |
| woo-gutenberg-products-block       | active | none   | 2.4.2    |
| woocommerce-memberships            | active | none   | 1.13.0   |
| woocommerce-my-account-widget      | active | none   | 0.6.5    |
| woocommerce-subscription-downloads | active | none   | 1.1.18   |
| woocommerce-subscriptions          | active | none   | 2.5.3    |
| wordpress-social-stream            | active | none   | 1.5.17   |
| wp-newslist                        | active | none   | 3.2      |
| wp-crontrol                        | active | none   | 1.7.1    |
| wp-fail2ban                        | active | none   | 4.2.7.1  |
| zopim-live-chat                    | active | none   | 1.4.15   |
+------------------------------------+--------+--------+----------+
```

**Comment by tlovett1** [comment]
I'm not able to reproduce. Which EP features do you have active?

**Comment by comzeradd** [comment]
Same here. It seems to hit [this bug](https://wpdevelopment.courses/how-to-fix-activatemode-is-not-a-function-error-in-gutenberg/), but it doesn't happen consistently on all blocks.

**Comment by Doorgeest91** [comment]
Same problem. The issue seems to be connected to the featured image block in Gutenburg. When this block is collapsed the post can be edited like normal.

**Comment by helen** [comment]
I believe this is because of the Related Posts block introduced in 3.2. A temporary fix is to deactivate the Related Posts feature, which AFAIK does not impact indexing, but it will impact blocks and I believe widgets as inserted so please proceed with caution. If any of y'all could add screenshots or specific errors messages that would be helpful for me to see if this is indeed all the same issue.

Here's what I'm observing:

* When attempting to insert a block that uses the media modal (e.g. an image block), you can an error that says "This block has encountered an error and cannot be previewed."
* When editing an existing post that contains an image block, the editor loads properly but once I click into an image block I get the full-screen wipe out with the error that says "The editor has encountered an unexpected error." with the Attempt Recovery, Copy Post Text, and Copy Error buttons.

It does seem to be some kind of issue with Lodash vs. Underscore - inspecting `_` on the console shows me that `_` is Lodash when it should be Underscore, even though `window.lodash = _.noConflict()` is called in the source (inline script attached to the Lodash enqueue).

**Comment by johnReeve** [comment]
@helen, thanks!  

I am having the same problem on several sites.  Turning off the "Related Posts" feature has resolved that for me.

**Comment by adamsilverstein** [comment]
Note: this was fixed in https://github.com/10up/ElasticPress/pull/1524 and included in the latest release of the plugin.
