### ISSUE TITLE
Return instance of WP_Query instead of post array in find_related()

### ISSUE THREAD

**Issue by Slamik** [10up/ElasticPress#1520]
I propose to return WP_Query instance in find_related function instead of post array.

It's more native to Wordpress code style and developer can use standart loop in template or pass WP_Query instance to custom templater class.

**Comment by tlovett1** [comment]
Seems like an interesting idea but this would break backwards compat.

**Comment by Slamik** [comment]
To no to brake backward compatibility you can add an optional parameter. 
For example:
`	public function find_related( $post_id, $return = 5, $instance = false  ) {
		$args = array(
			'more_like'           => $post_id,
			'posts_per_page'      => $return,
			'ep_integrate'        => true,
			'ignore_sticky_posts' => true,
		);

		$query = new WP_Query( apply_filters( 'ep_find_related_args', $args ) );

		if ( $instance )
		    return $query;

		if ( ! $query->have_posts() ) {
			return false;
		}
		return $query->posts;
	}`

**Comment by ayebare** [comment]
Looking into this.
