### ISSUE TITLE
Facet search breaks after update to version 3.2

### ISSUE THREAD

**Issue by co3n** [10up/ElasticPress#1521]
Uncaught Error: Too few arguments to function ElasticPress\Feature\Facets\Facets::set_agg_filters(), 2 passed in /wp-includes/class-wp-hook.php on line 288 and exactly 3 expected in /wp-content/plugins/elasticpress/includes/classes/Feature/Facets/Facets.php on line 92
set_agg_filters()
wp-includes/class-wp-hook.php:288
apply_filters()
wp-includes/plugin.php:208
apply_filters()
wp-content/plugins/elasticpress/includes/classes/Indexable/Post/Post.php:1127
format_args()
wp-content/plugins/elasticpress/includes/classes/Indexable/Post/QueryIntegration.php:210
get_es_posts()
wp-includes/class-wp-hook.php:286
apply_filters()
wp-includes/plugin.php:251
apply_filters_ref_array()
wp-includes/class-wp-query.php:2921
get_posts()
wp-includes/class-wp-query.php:3404
query()
wp-includes/post.php:1961
get_posts()
wp-content/plugins/perzonalization/perzonalization.php:523
{closure}()
wp-includes/class-wp-hook.php:286
apply_filters()
wp-includes/class-wp-hook.php:310
do_action()
wp-includes/plugin.php:465
do_action()
wp-includes/general-template.php:2745
wp_head()
wp-content/themes/elementor-hello-theme-master/header.php:18
require_once()
wp-includes/template.php:722
load_template()
wp-includes/template.php:671
locate_template()
wp-includes/general-template.php:41
get_header()
wp-content/plugins/jet-woo-builder/templates/woocommerce/archive-product.php:20
include()
wp-includes/template-loader.php:78
require_once()
wp-blog-header.php:19
require()
index.php:17
The site is experiencing technical difficulties.

**Comment by jordan26** [comment]
Exactly the same issue here when upgrading to 3.2 too.

**Comment by tlovett1** [comment]
3.2.1 should fix this. Please let me know if the problem persists.
