### ISSUE TITLE
Connect from Amazon web service not working with 3.1.4

### ISSUE THREAD

**Issue by JJPragmatic** [10up/ElasticPress#1523]
It appears like the process outlined at https://github.com/10up/ElasticPress/issues/790#issuecomment-324728774 for connecting and authorizing via IAM roles and AWS no longer works with the latest versions of this plugin, is there a workaround or different approach?

**Comment by oscarssanchez** [comment]
Hi @JJPragmatic , Thanks for submitting, will take a look at this this week.

 Kind regards,

**Comment by brandwaffle** [comment]
Hi @JJPragmatic reading through the previous ticket it seems the code that was tried by one of the commenters never actually worked. We'd certainly welcome any PRs related to enabling this functionality (although it might be better served in a child plugin), but as of now ElasticPress is really only designed to work with Elasticsearch and Shield-style authentication.

**Comment by twhid** [comment]
For anyone looking for ways to hook elasticpress up to AWS elasticsearch service, you can do it. It's relatively simple. In this example, you need to create an IAM user with full rights to the service (using the access policy in Amazon ES), then define that user's key and secret. In this example the key and secret are defined as globals in wp_config.php (`ES_AWS_KEY`, `ES_AWS_SECRET` respectively).

The example below is a plugin that hooks into the `http_request_args` event and mutates the headers (signing and authorizing the request) of external http requests to the Amazon ES host.

```php
<?php

namespace SignAmazonEsRequests;

// In this example we've included the AWS SDK for PHP using the zip file
// see: https://docs.aws.amazon.com/en_pv/sdk-for-php/v3/developer-guide/getting-started_installation.html
// First, we load the AWS SDK autoloader so that we may use the classes
require_once( dirname( __FILE__ ) . '/aws/aws-autoloader.php' );

// If this file is called directly, abort.
if ( !defined( 'WPINC' ) ) {
    die;
}

// require the classes we'll need
use Aws\Signature\SignatureV4;
use Aws\Credentials\Credentials;
use GuzzleHttp\Psr7\Request;

add_filter( 'http_request_args', __NAMESPACE__ . '\\sign_aws_request', 10, 2 );

function sign_aws_request( array $args, string $url ) : array {
    $host = parse_url( $url, PHP_URL_HOST );
    // You'll need to define EP_HOST in wp_config.php for this check to work
    // If you're using AWS Elasticsearch Service, this would be something like:
    // https://search-<domain>-<guid>.<region>.es.amazonaws.com
    // If not requesting elasticpress host, don't sign request
    if ( strpos(EP_HOST, $host) === false ) {
        return $args;
    } 
    // otherwise, sign the request using the AWS SDK and return the $args array
    $request = new Request( $args['method'], $url, $args['headers'], $args['body'] );
    $signer = new SignatureV4( 'es', 'us-east-1' ); // region specific
    if ( defined( 'ES_AWS_KEY' ) ) {
        $credentials = new Credentials( ES_AWS_KEY, ES_AWS_SECRET );
        $signed_request = $signer->signRequest( $request, $credentials );
        $args['headers']['Authorization'] = $signed_request->getHeader( 'Authorization' )[0];
        $args['headers']['X-Amz-Date'] = $signed_request->getHeader( 'X-Amz-Date' )[0];
    } else {
        error_log('ES_AWS_KEY & ES_AWS_SECRET must be defined in wp_config.php');
    }
    return $args;
}
```
