### ISSUE TITLE
Support for Elastic Search 7.x?

### ISSUE THREAD

**Issue by photocurio** [10up/ElasticPress#1525]
I'm wondering if you guys have a timetable for support for Elastic Search 7.x?

**Comment by tlovett1** [comment]
Hopefully in 2019.

**Comment by jayhill90** [comment]
@tlovett1 2019 is almost ending did you mean 2020 or will it be ready be EoY?

**Comment by wss-chadical** [comment]
The broader question I have is: What does adding support for newer releases look like?
Is it a major undertaking? 
Do the maintainers need feedback from users?

The 6.4 limitation is making it difficult to deploy elasticpress in the cloud. Most of the out of the box Bitnami images, google cloud images, etc... are all 6.8 and 7.4 at a minimum. 

We would consider using ElasticPress hosting, but the plans are a bit out of alignment for our needs:
A. Essential is too limited
B. Extended is too expensive
C. Overall a bit expensive.

**Comment by jonathan-dejong** [comment]
I'd also like some info on this :) 
I totally get that this is an open source solution and I deeply respect the time and effort being but into it! 

It looks like 6.4 has already reached a sort of EOL from Elasticsearch tho and EP is not keeping up. Do you need more maintainers? Is this project becoming less of an interest to you guys? 
I understand the fickle nature of OS sometimes but there's also the responsibility of at least keeping the people that depend on the software in the loop on critical stuff.  :)

**Comment by wss-chadical** [comment]
I heard Q2 of 2020

**Comment by brandwaffle** [comment]
We just merged Elasticsearch 7.5 compatibility into the develop branch and are actively seeking testing on non-production sites. Our goal is to merge this into the production plugin by EOY 2019 to ensure we're within the EOL support for 6.4 (which ends Feb 23, 2020 https://www.elastic.co/support/eol).

**Comment by wss-chadical** [comment]
Noice.
@brandwaffle Does that include 7.4?

**Comment by tlovett1** [comment]
Yes, it does.

**Comment by wss-chadical** [comment]
Awesome - I'll give it a go in dev.

**Comment by jonathan-dejong** [comment]
Really nice @tlovett1 ! 
How will these updates tie in with ES shield no longer usable in favor of Xpack? 
https://github.com/10up/ElasticPress/issues/1591
