### ISSUE TITLE
Stuck in an infinite sync state after an error during indexing

### ISSUE THREAD

**Issue by emmerich** [10up/ElasticPress#1533]
**Describe the bug**

After running the index command and receiving a PHP error (such as bad syntax etc.), ElasticPress is stuck in a syncing state.

**Steps to Reproduce**

1. Create a function somewhere in PHP that causes an error. This was my example:
```
function prepare_post_for_indexing($post_args) {
  $post_args->set('meta', array());
  return $post_args;
}
add_filter( 'ep_post_sync_args', 'prepare_post_for_indexing', 1 );
```
2. Run `wp elasticpress index --setup`
3. You'll receive an error for the function you've created (which is normal, it's incorrect)
4. Correct the error (remove the function)
5. Run `wp elasticpress index --setup` again
6. You'll receive an error "An index is already occuring. Try again later." and there's no way of getting out.

**Expected behavior**
Indexing that causes an error should cancel the index operation so that a new one may take place.

**Screenshots**
Dashboard will also show a sync in progress, but with no option to cancel.
![Screenshot 2019-10-23 at 10 30 34](https://user-images.githubusercontent.com/701222/67373593-36788d80-f580-11e9-8f50-65272dd708e8.png)

**Environment information**
ElasticPress `master`
ElasticSearch 6.4
WordPress 5.2.1

**Comment by emmerich** [comment]
After a quick check of the database, it seems that the transient value `ep_wpcli_sync` is set to 1 and not set back to 0. Thus it's line 1177 in `Command.php` which throws the error.

**Comment by tlovett1** [comment]
@emmerich you are 100% correct. As far as I know, there isn't a consistent way to detect fatal error/forced script termination without custom PHP packages. Open to ideas if you have any.

**Comment by emmerich** [comment]
I'll admit PHP isn't my strongpoint, so I'm not sure either.  It's quite a rare case and usually only happens during development, maybe having a WP CLI command to reset the `ep_wpcli_sync` state would be good enough?

**Comment by barryceelen** [comment]
Just a note for anyone running into this issue (like me): `wp transient delete ep_wpcli_sync` will enable you to run a sync again.

@tlovett1 do we need an elasticpress-specific cli command to do this? Alternatively we could add a suggestion to the error message, as it is not immediately apparent that you'd need to clear a transient to get back up and running again if the indexing process terminates unexpectedly.

**Comment by tlovett1** [comment]
@barryceelen seems like a sync reset command would be good. Want to create a PR?

**Comment by Trisky** [comment]
Hi there, this is the first result on Google when you search for the error message. 

> @emmerich you are 100% correct. As far as I know, there isn't a consistent way to detect fatal error/forced script termination without custom PHP packages. Open to ideas if you have any.


in plain PHP we can do 

```PHP
 function myfunc() {
	try {
		$this->indexPosts();
	} finally {
		$this->delete_transient();
	}
}

```

So every time indexPosts throws an exception or finishes successfully, it will call delete_transient() so the indexing is labeled as 'not running' again. 

I think that a PR with this approach would solve the issue in a more graceful way than having a reset command. 
Should I try it out?

**Comment by mi-um** [comment]
> After a quick check of the database, it seems that the transient value `ep_wpcli_sync` is set to 1 and not set back to 0. Thus it's line 1177 in `Command.php` which throws the error.
> 
> For those with this error, you can manually set `ep_wpcli_sync` (`_transient_ep_wpcli_sync` in `wp_options`) to 0 in the database.

If someone is just looking for a quick way out, this helped me (using the WP CLI command):

wp eval 'delete_transient( "ep_wpcli_sync" ); delete_option( "ep_index_meta" ); delete_site_transient( "ep_wpcli_sync" ); delete_site_option( "ep_index_meta" );'

**Comment by oscarssanchez** [comment]
Closing as it seems this got resolved

@Trisky please feel free to submit a PR, thanks!

**Comment by ceejau** [comment]
![ep issue](https://user-images.githubusercontent.com/67996335/203272380-2933fa96-bbad-4cf2-a6a0-912f26211dbd.png)
 I am having a similar issue where this sync is running non-stop without making any progress and without hindering the search functionality on my wordpress website. We were running "wp elasticpress index --setup --per-page=1 --url= " to remove some of the files which were deleted and were coming up in search results. After a while this process started in its own and i cant stop it from the dashboard, it goes on running again after refersing if i try to stop it. I cannot run the wp reindex command from shell as it shows an index is already in progress.
@oscarssanchez  @mi-um @barryceelen

**Comment by JiveDig** [comment]
Same here. Has anyone found a way to kill the sync?

Here's what I've tried:

- Clicked stop via UI.
- Tried to stop via `wp elasticpress delete-index`.
- Deactivated then activated Elasticpress plugin.
- Removed the `EP_HOST` constant from wp-config, and there isn't any value in the DB for the host.
- Restarted nginx.

**Comment by JiveDig** [comment]
Oh geez, missed the comment above. This did work for me. Thanks.

```
wp eval 'delete_transient( "ep_wpcli_sync" ); delete_option( "ep_index_meta" ); delete_site_transient( "ep_wpcli_sync" ); delete_site_option( "ep_index_meta" );'
```
