### ISSUE TITLE
Order Descrending and Modified Edit Result Search Wordpress

### ISSUE THREAD

**Issue by Leceaga** [10up/ElasticPress#1534]
My wordpress search should be answered with the Title and in descending order of modified edit date, but it doesn't work.
The "Search fields & Weighting" tab is set to title 50 and still does not work, the result is shown in the order of oldest and most relevant.

What do I do?

**Comment by tott** [comment]
Hi @Leceaga , have you already tried enabling the "Weight results by date" setting in the Search feature at /wp-admin/admin.php?page=elasticpress ?
Do you run any custom queries or plugins which may alter the search behavior? Can you disable those and retry?
If you already tried this can you install the debug bar elasticpress plugin and take a look at the search request/response that is sent do the server and provide the response listed in the query body alongside the query args as seen in the screenshot https://i.imgur.com/NHXWHMs.png.

**Comment by brandwaffle** [comment]
Closing due to lack of response.
