### ISSUE TITLE
Elasticpress Hooks and Filters Documentation or List

### ISSUE THREAD

**Issue by milnerm** [10up/ElasticPress#1537]
Is there a succinct list or documentation for EP hooks and filters? I'm seeing them noted throughout issues, but can't find the actual documentation, nor a list, nor any kind of resource indicating what in fact they are, when they fire, what variables they take, etc. You know, the regular kind of stuff associated with WP hooks and filters.

**Comment by jordan26** [comment]
Agreed. Could have things added to the Wiki tab or use: https://docs.gitbook.com/

**Comment by kylef000** [comment]
@milnerm 
http://10up.github.io/ElasticPress/
