### ISSUE TITLE
How to treat lower and uppercase the same?

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1538]
If i search for "Pa**R**appa" it will not find "Parappa" only "Pa**R**appa"
if i search for "Pa**r**appa" it will find both "Parappa" and "PaRappa".

I need to find all instances regardeless of the case even when searching in uppercase.
How can i do this?

**Comment by tott** [comment]
I think this is the default behavior of the word_delimiter. To achieve what you want you would need to set the split_on_case_change parameter to false as outlined in https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html

You would need to inject this into the mapping here https://github.com/10up/ElasticPress/blob/develop/includes/mappings/post/5-2.php#L80

You can do this through either the ep_post_mapping_file filter in https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L186
or the ep_post_mapping filter here https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L195

I hope this helps.
