### ISSUE TITLE
ElasticPress Feature Settings - Incorrect JavaScript

### ISSUE THREAD

**Issue by alexholsgrove** [10up/ElasticPress#1541]
__Have you searched for similar issues before submitting this one?__
Yes

__Is this a bug, question or feature request?__
A bug

__Describe the issue you encountered:__
Tying to save feature settings. AJAX call is made to ep_save_feature but the values passed are the existing settings, not the new values entered. The dashboard.js (which is compiled to the /dist/dashboard-script.min.js uses: `const value = jQuery( this ).attr( 'value' );`
I think it should  be `const value = jQuery( this ).val();`

If I alter this in the compiled JS, the settings save correctly.

__Current WordPress version?__
5.2.4

__Current ElasticPress version?__
3.2.1

__Current Elasticsearch version?__
7.1.1

__Where do you host your Elasticsearch server?__
Amazon AWS

__What ElasticPress features do you have currently active?__
Post Search, Autosuggest, Custom Search Results, Related Posts, Facets

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
ACF Pro, Contact Form 7, Flamingo, WordPress SEO

__Steps to reproduce:__
Tried to enable Autosuggest or enter an endpoint URL

__Screenshots, if needed:__
n/a

**Comment by tott** [comment]
Can you test this with the most recent version of ElasticPress and report back if you still have any issues.

**Comment by alexholsgrove** [comment]
It still looks broken and I can't see the JavaScript lines have changed at all. The problem is the jQuery is looking for the attribute "value" rather than getting the actual field value using .val()

For example, I have enabled the "autosuggest" and changed the default class name. When I hit save, it submits the default field values rather than the value I have entered:

<img width="480" alt="Screenshot 2019-11-27 at 14 39 11" src="https://user-images.githubusercontent.com/158899/69732783-27a76c80-1124-11ea-8c55-e455e26f32b2.png">

**Comment by tott** [comment]
Thanks for the follow-up Alex, I'm not able to reproduce the behavior. Could you provide some details about the browser / OS used when you run into the issue?

**Comment by alexholsgrove** [comment]
I'm on MacOS 10.14.6 Mojave and have tested on Chrome 78.0.3904.108 and Safari 13.0.3
jQuery version (jQuery.fn.jQuery) returns 1.12.4 in the console.

I've just taken another screenshot of my console with the jQuery commands attr('value') and .val() to show the difference. if I refresh the settings page, the "autosuggest" returns to disabled and the selector reverts to the default "ep-autosuggest".

If you go to your settings page, change the selector and then run the two jQuery commands, do you see the same value returned?

<img width="751" alt="Screenshot 2019-11-27 at 16 00 39" src="https://user-images.githubusercontent.com/158899/69739267-55de7980-112f-11ea-8531-c1a9db07818a.png">

**Comment by alexholsgrove** [comment]
I've changed themes to twentynineteen and the settings now work correctly. The issue was my theme removed the jQuery migrate library which is required for these settings to work.

Still, it would be worth just changing the JavaScript as per my original comment to just use .val() then it should work with or without jQuery migrate.
