### ISSUE TITLE
Elasticsearch 7.4.x support (6.4 prone to 3 known vulnerabilities)

### ISSUE THREAD

**Issue by dciphered** [10up/ElasticPress#1542]
__Have you searched for similar issues before submitting this one?__
Yes
__Is this a bug, question or feature request?__
Question
__Describe the issue you encountered:__
Hi guys,

I would like to know if (and when) ElasticPress supports Elasticsearch 7.4.x (7.4.2)? Your GitHub documentation specifies that 6.4 is the max version supported however there are 3 known security issues with this version, the latest of which was reported a few months ago, which is a good enough reason not to deploy 6.4.x.

These vulnerabilities don't exist in versions beyond 7.1 so before deploying and configuring ES, I would like to validate whether the plugin has been tested with these versions and if there are any known issues with compatibility.

__Current WordPress version?__
5.2.4

__Current ElasticPress version?__
None yet

__Current Elasticsearch version?__
None yet

__Where do you host your Elasticsearch server?__
This will be a local deployment on the WP app server

**Comment by dciphered** [comment]
Hi guys, can I please get some feedback here. In short, are there any other Elasticsearch versions beyond 6.4 that are supported by the plugin?

I've had to pause on deployment until I can get some validation.

Many thanks.

**Comment by nickdaugherty** [comment]
I believe this is a duplicate of https://github.com/10up/ElasticPress/issues/1525

**Comment by brandwaffle** [comment]
Hi @dciphered we're in the active testing phase for 7.5 compatibility! Please try out the develop branch on your staging/dev sites and let us know how things are working!

**Comment by guy-bouchard** [comment]
Hi,
I've just tested the last 7.5 compatible version of Elasticpres. The month, days and time are correct but years is always 1970.

I tried all the possible options for date and time in WP

Fresh WP 5.3
Fresh elastic 7.5
and new dev branch of elasticpress
