### ISSUE TITLE
Documents fail to index

### ISSUE THREAD

**Issue by photocurio** [10up/ElasticPress#1543]
**Describe the bug**
Documents fail to index on multisite network.
**Steps to Reproduce**

1. Install _Ingest Attachments_ plugin on Elasticsearch.
2. Activate _Documents_ feature on Elasticpress (indexing does work if I have the Documents feature off).
3. Reset mappings with `wp elasticpress put-mapping --network-wide`
4. Index content with `wp elasticpress index --per-page=200 --network-wide`
5. Lots of identical errors:
```
- 570 (Post): 
type: exception
reason: java.lang.IllegalArgumentException: ElasticsearchParseException[Error parsing document in field [_ingest._value.data]]; nested: TikaException[TIKA-198: Illegal IOException from org.apache.tika.parser.microsoft.OfficeParser@6fb19846]; nested: IOException[java.lang.ClassNotFoundException: org.apache.poi.poifs.crypt.agile.AgileEncryptionInfoBuilder]; nested: ClassNotFoundException[org.apache.poi.poifs.crypt.agile.AgileEncryptionInfoBuilder];
type: illegal_argument_exception
reason: ElasticsearchParseException[Error parsing document in field [_ingest._value.data]]; nested: TikaException[TIKA-198: Illegal IOException from org.apache.tika.parser.microsoft.OfficeParser@6fb19846]; nested: IOException[java.lang.ClassNotFoundException: org.apache.poi.poifs.crypt.agile.AgileEncryptionInfoBuilder]; nested: ClassNotFoundException[org.apache.poi.poifs.crypt.agile.AgileEncryptionInfoBuilder];
type: parse_exception
reason: Error parsing document in field [_ingest._value.data]
type: tika_exception
reason: TIKA-198: Illegal IOException from org.apache.tika.parser.microsoft.OfficeParser@6fb19846
type: i_o_exception
reason: java.lang.ClassNotFoundException: org.apache.poi.poifs.crypt.agile.AgileEncryptionInfoBuilder
type: class_not_found_exception
reason: org.apache.poi.poifs.crypt.agile.AgileEncryptionInfoBuilder
processor_type: foreach
```
6. After logging a lot of such errors, indexing fails with `cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received`.

**Expected behavior**

Indexing to complete, documents findable in search.

**Environment information**
 - Device: MacBook Pro, 2015
 - OS: MacOS 10.13.3
 - Browser and version: Chrome 77.0.3865.120
 - Plugins and version: Elasticpress 3.2.1, Debug Bar ElasticPress 1.4
 - Theme and version: Custom theme

**Comment by tlovett1** [comment]
Tested this with ElasticPress.io and was unable to reproduce. Maybe you have the wrong version of ingest attachment installed?

**Comment by dustinrue** [comment]
Hi there. You want to reduce your posts per page setting a lot. Indexing documents is expensive and what you’re seeing is the plugin getting tired of waiting around for Elasticsearch to complete the operation. I recommend trying batches of about 5 and seeing if it helps.

**Comment by photocurio** [comment]
@tlovett1 I have Elasticsearch 6.4.0 and Ingest Attachment 6.4.0 (do these always match?).

@dustinrue yeah good idea.  I change to per-page=5, and I get a lot fewer errors. I still get some errors however.

I sure wish I knew which attachments fail to index.  The 570 is not the document ID.

It would be helpful to be able to sync specific sites (separate thread [here](https://github.com/10up/ElasticPress/issues/1536)).  If indexing fails at site 80, I have to re-index from the beginning.  This creates a lot of unnecessary rewriting of data.

**Comment by photocurio** [comment]
Setting the per-page value to 5 did help.  I also doubled the memory allocation on the elasticsearch servers, which also seems to help. I'm guessing this is a processing power issue.

**Comment by photocurio** [comment]
I see that all the attachment pipeline sets `indexed_chars` to -1 (all characters).  If there is a large file, that could be a problem.  

How can I set the `indexed_chars` value for the attachment pipeline?

**Comment by tott** [comment]
@photocurio you can use the ep_create_pipeline_args filter here https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L1217 to adjust the arguments of the pipeline during creation. In particular you will need to adjust this value https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Documents/Documents.php#L369

**Comment by photocurio** [comment]
I can't get this working.
I've tried this:
`add_filter( 'ep_create_pipeline_args', 'set_index_chars', 10, 2 );
function set_index_chars( $args ) {
	$args = array(
		'processors'  => array(
			array(
				'foreach' => array(
					'processor' => array(
						'attachment' => array(
							'indexed_chars'  => 1000,
						),
					),
				),
			),
		),
	);
	return $args;
}`
