### ISSUE TITLE
Index not updating when publishing new posts

### ISSUE THREAD

**Issue by thomasdiesenreiter** [10up/ElasticPress#1544]
__Have you searched for similar issues before submitting this one?__
Yes, wasn't able to find anything.
__Is this a bug, question or feature request?__
Bug
__Describe the issue you encountered:__
When a user publishes a post, the new post is not added to the index and thereby is not showing up in search. To fix it I have to reindex the whole site manually.
__Current WordPress version?__
5.2.4
__Current ElasticPress version?__
Newest
__Current Elasticsearch version?__
6.4
__Where do you host your Elasticsearch server?__
Selfhost
__What ElasticPress features do you have currently active?__

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__
ACF Pro
Akismet
Core Control
Debug Bar
Debug Bar ElasticPress
ElasticPress
Google XML Sitempas
I Love Social Bookmarking
SB Welcome Email Editor
Search Autocomplete
Simple Tags
SimpleModal Login
User Switching
Virtual Robots.txt
WP Force SSL
wp-jquery-lightbox
WP-Matomo
WP-PostViews

__Steps to reproduce:__

1. Publish post
2. Search for title of post
3. Find nothing

__Screenshots, if needed:__

**Comment by tlovett1** [comment]
Turn on query debugging in the debug bar and see if any errors show up please.

**Comment by tott** [comment]
@thomasdiesenreiter we did not hear back from you in a while and I'm closing this ticket for now. Feel free to reopen this or create a new one once you have the requested infromation
