### ISSUE TITLE
Nonstop Syncing posts

### ISSUE THREAD

**Issue by derunterstrich** [10up/ElasticPress#1545]
**Describe the bug**
Die Syncronisierung der Beiträge ist in einer Dauerschleife gefangen. Nach dem Sync posts, 4840/4840 posts geht es gleich wieder bei Syncing posts 0/4840 weiter.

**Steps to Reproduce**
1. Go to 'Elasticpress Dashboard'
2. Click on 'Update' top right
3. Stile wait
4. It start again 

**Expected behavior**
When everything has been synchronized: stop ;)

**Environment information**
 - Device: Mac
 - OS: MacOS 10.15.1
 - Browser and version: Last firefox, chrome, safari
 - Plugins and version: Version 3.2.1
 - AWS Elasticsearch 6.4.2

**Comment by tott** [comment]
Quick translation: 

> Die Syncronisierung der Beiträge ist in einer Dauerschleife gefangen. Nach dem Sync posts, 4840/4840 posts geht es gleich wieder bei Syncing posts 0/4840 weiter.

The synchronization of posts is caught in a loop. Once the posts are synced 4840/4840 posts the sync starts again with message "Syncing posts 0/4840"

@derunterstrich Wie werden die posts gesynct? In wp-admin oder via wp-cli? Wie es scheint via wp-admin ; Gibt es die Moeglichkeit den Sync via wp-cli anzustossen? Gibt es wp-cron oder andere Zeit-gesteuerte Prozesse die die posts bearbeiten koennten?

can you advise how you are syncing (wp-admin or through wp-cli) , are there any cron jobs which might alter the posts

**Comment by derunterstrich** [comment]
Die Daten können nur über das Admin-Interface aktualisiert werden.
--
The data can only be updated via the admin interface.

**Comment by ognjanovic** [comment]
Similar issue with ElasticPress 3.2.3 (I just updated from latest EP 2.x).

If I use web interface I'm stuck in a loop, reindexing over and over again.

If I use wp-cli everyting works fine, no errors.

**Comment by tott** [comment]
Can you validate if the javascript console in your browser shows any errors in wp-admin where the indexing is shown?

**Comment by ognjanovic** [comment]
> Can you validate if the javascript console in your browser shows any errors in wp-admin where the indexing is shown?

No errors.

**Comment by tott** [comment]
Can you please test if the issue still persists with the most recent ElasticPress version 3.2.6 and if it does let us know the theme and plugins used on your site. Thanks

**Comment by ognjanovic** [comment]
Still the same issue, reindexing as soon as hits the end.
I have more than 500k public posts so it's not something I can just play and runaway :D

**I tried it on another project, much smaller and it works without hastle. You can close the isuue.**

I will try to debug the plugins, but as I said, it works just fine from wp-cli, good enough for me :)

Theme is custom, quite complex, as well as the plugins, but will give my best to find what is the issue.

**Comment by brandwaffle** [comment]
I was able to sync a site through the dashboard with 423,000 test posts in it. I'm closing this for now. Please feel free to open a new ticket if you encounter this issue with ElasticPress 3.3.
