### ISSUE TITLE
Not working with admin-ajax.php driven Search

### ISSUE THREAD

**Issue by dciphered** [10up/ElasticPress#1546]
__Have you searched for similar issues before submitting this one?__
Yes

__Describe the issue you encountered:__
We're experiencing an issue where Elasticpress does not recognise our search queries. We are using a search field that's driven by admin-ajax.php and after enabling debug, I can validate that there are no queries being generated by Elasticpress.

Researching the issue, I stumbled across an older case that was opened on GitHub here: https://github.com/10up/ElasticPress/issues/216 which makes reference to a class-ep-wp-query-integration.php file, I can only assume that this filter was included in the more recent versions of EP.

We've hit a small brick wall with trying to unpack the issue and are in need of some assistance with the problem.

Also, we are using the latest version of ES due to a previous post I left which went unanswered about known vulnerabilities in 6.4.

Many thanks in advance.

__Current WordPress version?__
5.2.4

__Current ElasticPress version?__
3.2.1

__Current Elasticsearch version?__
7.4.2

**Comment by photocurio** [comment]
Is admin-ajax.php timing out?

**Comment by dciphered** [comment]
It doesn't appear to be, the request gets fulfilled as per normal however it's not being parsed by EP/ES

**Comment by tlovett1** [comment]
Use the filter here or enable Protected Content: https://github.com/10up/ElasticPress/blob/7786a708d3c266588a933abdd45ac91762575b30/includes/classes/Feature/Search/Search.php#L72
