### ISSUE TITLE
WooCommerce Product Table Plugin Incompatible?

### ISSUE THREAD

**Issue by theritesite** [10up/ElasticPress#1548]
I assume it is not a bug, submitting as question because couldn't find another good category. The commercial plugin "WooCommerce Product Table" in its current state is incompatible with ElasticPress but had not quite made it to the Wiki page for incompatible plugins.

I will be reaching out to their support team to see if there is a workable solution and will be linking them the github repository for this project.

Thank you for your amazing work with this plugin, I hope I can continue to use it on future projects, as well as get this project on ElasticPress once the table plugin issue is resolved, whether the developers create a fix or we move to a different table solution.

- The Rite Sites

**Comment by tott** [comment]
Thanks for letting us know. It would be great if you could provide us any findings you might have. If there is anything we can do to make this compatible we're happy to assist.
