### ISSUE TITLE
[Request] Most popular search terms and related searchs

### ISSUE THREAD

**Issue by vitoralmeidabr** [10up/ElasticPress#1549]
__Have you searched for similar issues before submitting this one?__
Yes

__Is this a bug, question or feature request?__
Feature Request

__Describe the issue you encountered:__

__Current WordPress version?__
5.2

__Current ElasticPress version?__
Most recent

__Current Elasticsearch version?__
Most recent

__Where do you host your Elasticsearch server?__
AWS

-1 It's possible to generate a list of most popular search terms ?
-2 It's possible to show related searchs when viewing a search result ?

**Comment by brandwaffle** [comment]
@vitoralmeidabr You can view a list of most popular search terms if you connect ElasticPress to Google Analytics or a similar analytics provider that features this info. We have a video tutorial here: https://www.elasticpress.io/blog/2020/01/video-intro-to-elasticpress-search-analytics/

Can you give a bit more detail on the "related searches" feature? Would these be previously-performed searches that use similar words/phrases to the current search terms, or something else?

Thanks for the ideas and for using ElasticPress!

**Comment by vitoralmeidabr** [comment]
Thanks for that tutorial, i will follow this steps, but my real intent is to show to user, bellow search box and aside results, a list with most searched terms. Using GA i will need to do a trick.

Exactly, others searched terms with similar results or used words similiar to current terms.

**Comment by oscarssanchez** [comment]
Hi @vitoralmeidabr ,

It looks like this was closed and later reopened, if by any chance there's still questions please feel free to open a new issue.
Kind regards,
