### ISSUE TITLE
Related Post Block loads editor/theme.css in the frontend 

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#1550]
**Describe the bug**
The Related Post Block Style has wp-edit-blocks as a dependency which causes the editor.css and theme.css from Gutenberg to be loaded in the frontend.

**Steps to Reproduce**
1. Go to a page where the Related Post Block is embeded
2. Search inside source code for related-posts-block-styles
3. See the dependencies editor.min.css/theme.min.css in front of the related block stylesheet

**Expected behavior**
Register seperate styles for the editor and the frontend as described here: https://developer.wordpress.org/block-editor/tutorials/block-tutorial/applying-styles-with-stylesheets/

**Comment by mlaroy** [comment]
thanks @goaround - we'll take a look at this issue

**Comment by tott** [comment]
This issue should be resolved with the recent ElasticPress version. If you should run into any further issues please feel free to reopen this ticket.
