### ISSUE TITLE
Searchterm highlighting

### ISSUE THREAD

**Issue by mlaroy** [10up/ElasticPress#1551]
**Is your enhancement related to a problem? Please describe.**

Currently, search terms aren't made visible in the search results, as it common in search engines to visually demonstrate search result relevance.

**Describe the solution you'd like**

Inject some markup (e.g. span tag) to surround the search term within the content/excerpt provided in the search results for easy styling. Also, the ability to determine which tag is to be used.

**Comment by photocurio** [comment]
I got highlighting working with these two comments:
https://github.com/10up/ElasticPress/issues/684#issuecomment-275834011
https://github.com/10up/ElasticPress/issues/1250

**Comment by oscarssanchez** [comment]
Closing as feature has been implemented.
