### ISSUE TITLE
prepare_meta_value_types() is returning invalid date resulting in DateTimeParseException and MapperParsingException while indexing.

### ISSUE THREAD

**Issue by jschultze** [10up/ElasticPress#1556]
`prepare_meta_value_types()` (/includes/classes/Indexable.php, line 322, version 3.2.2) is trying to calculate a date from any given `$meta_value` that is a string, starting in line 354:

>if ( is_string( $meta_value ) ) {
  $timestamp = strtotime( $meta_value );
  $date     = '1971-01-01';
  $datetime = '1971-01-01 00:00:01';
  $time     = '00:00:01';
  if ( false !== $timestamp ) {
    $date     = date_i18n( 'Y-m-d', $timestamp );
    $datetime = date_i18n( 'Y-m-d H:i:s', $timestamp );
    $time     = date_i18n( 'H:i:s', $timestamp );
  }
  $meta_types['date']     = $date;
  $meta_types['datetime'] = $datetime;
  $meta_types['time']     = $time;
}

When indexing meta values of WooCommerce products, some products had "in stock" values of "20". The value given to `prepare_meta_value_types()` as `$meta_value` is "20.000000".

`$timestamp = strtotime( $meta_value );` returns "-62139672000" fo an input of "20.000000". The condition `if ( false !== $timestamp ) {` does match in this case, so `$date`, `$datetime` and `$time` are generated with this timestamp, resulting in this `$meta_types` array:

>Array
(
    [value] => 20.000000
    [raw] => 20.000000
    [long] => 20
    [double] => 20
    [boolean] => 
    [date] => 0000-11-14
    [datetime] => 0000-11-14 20:00:00
    [time] => 20:00:00
)
`

"0000-11-14" causes the ElasticSearch server to throw the following error while trying to index the data:

`org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [meta._stock.date] of type [date] in document with id`

`Caused by: java.time.format.DateTimeParseException: Text '0000-11-14' could not be parsed: Invalid value for YearOfEra (valid values 1 - 999999999/1000000000): 0`

**Comment by jschultze** [comment]
This is a very specific work around for my current project, but it is possible to reset the wrong values with this hook:

>add_action( 'ep_post_sync_args', function($post_args, $post_id){
    if (isset($post_args['meta']['_stock'][0])) {
        $post_args['meta']['_stock'][0]['date'] = '1971-01-01';
        $post_args['meta']['_stock'][0]['datetime'] = '1971-01-01 00:00:01';
        $post_args['meta']['_stock'][0]['time'] = '00:00:01';
    }
    return $post_args;
}, 10, 2 );

**Comment by tlovett1** [comment]
@jschultze mind emailing me at taylor.lovett@10up.com? I'd love to ask you a few questions about the issue so we could get this solved for others.

**Comment by nickohrn** [comment]
I have also encountered this issue in our integration and am now using a similar workaround to the one that @jschultze proposed above. Here is a, somewhat ineloquent, test case that you can run from the command line using `wp eval` that will output a representation that shows the problem:

```php
$post_id = wp_insert_post([
    "post_content" => "Demonstration",
    "post_status" => "publish",
    "post_title" => "Demonstration",
    "post_type" => "post",
    "meta_input" => ["strtotime_date_failure" => 5569],
]);

if(false === is_wp_error($post_id)) {
    var_export(\ElasticPress\Indexables::factory()->get("post")->prepare_document($post_id));
}
```

The prepared meta values array looks like this:

```array (
    'strtotime_to_date_failure' =>
    array (
        0 =>
        array (
        'value' => '5569',
        'raw' => '5569',
        'long' => 5569,
        'double' => 5569.0,
        'boolean' => false,
        'date' => '5569-01-09',
        'datetime' => '5569-01-09 21:33:12',
        'time' => '21:33:12',
        ),
    ),
)
```

ElasticSearch rejects the `date` and `datetime` values as invalid. There are other values that are valid timestamps that we stored in the post meta table that are transformed into invalid dates when transforming from their string representation using `strtotime`.

**Comment by moraleida** [comment]
I'll take this one @tlovett1

**Comment by brandwaffle** [comment]
@Rahmon when reviewing this, please update all default dates that set 1971 and change to 1970 (actual start of the Unix epoch).

**Comment by jschultze** [comment]
Thanks all for working on this and fixing it! And sorry for my missing reply @tlovett1 - I had to switch projects and completely lacked the time to get into this any further.
