### ISSUE TITLE
Possible bug? ElasticPress making frontend run really slow.

### ISSUE THREAD

**Issue by kevinstaldersmg** [10up/ElasticPress#1557]
We are running ElasticPress on a WooCommerce store as we are developing a site. Currently the store has 30 products, ~1000 product attributes and ~3000 categories. This will soon enough have about 12000 products, couple thousand product categories and about over 1000 product attributes. 

When we have ElasticPress installed and activated, this is causing major slowdowns on the frontend and backend. It is causing Pingdom tools speed score to be about 9 seconds with it activated. When I deactivate ElasticPress, it brings the Pingdom tools speed to about 500ms. It seems that this plugin is causing the frontend(and even the backend) of my website to run really slow.

Attached is are screenshots of what my host saw when they ran New Relic on the server. It seems to be because of prepare_terms? 

![Screenshot 2019-11-10 at 11 42 57 PM](https://user-images.githubusercontent.com/28658268/68916026-4c6a1000-0732-11ea-8990-cac3d4486088.png)
![Screenshot 2019-11-10 at 11 43 05 PM](https://user-images.githubusercontent.com/28658268/68916027-4d02a680-0732-11ea-9cc5-dd5500d668c9.png)

Out of the thousand of product attributes, we will not need to search by all of them, so if limiting the fields/attributes that ElasticPress needs to index will help we can do that. Just need to know how. Ideally if there is something else that can be done that would be ideal.

**Wordpress Version:** 5.2.4
**ElasticPress Version:** 3.2.2
**ElasticSearch Version:** 6.2.1
**Host Elasticsearch Server:** My host uses LXD managed hosts and orchestrated LXC software containers
**ElasticPress Features Activated:** Post Search, Woocommerce, Custom Search Results, 
**Plugins installed:** ACF Pro, Beaver Builder Plugin pro, ElasticPress, Enable Woocommerce GPF Feed item cache, Gravity Forms, NoSpamNX, Redirection, Smush Pro, TaxJar - Sales Tax Automation for Woocommerce, UPS WooCommerce Shipping, WooCommerce, WooCommerce Authorize.net Gateway, WooCommerce Google Product Feed, WP All Import - ACF Add-on, WP All Import - WooCommerce Add-on Pro, WP All Import Pro, Yoast SEO, (Plus some custom plugins)

**Steps to Reproduce:**
Seems to be just having it installed with that many attributes?

**Comment by tott** [comment]
Hi Kevin,

the slowdown in shown in NewRelic makes me think that the indexing is still ongoing and while this might contribute to the issue you might have encountered an edge case bug we fixed with a release this night. Can you try upgrading to 3.2.3 and report back if the issue persists?

Thanks

**Comment by tott** [comment]
This issue should be resolved with the recent ElasticPress version. If you should run into any further issues please feel free to reopen this ticket.

**Comment by tlovett1** [comment]
@kevinstaldersmg is this fixed?

**Comment by kevinstaldersmg** [comment]
Yes. Sorry. I think it wasn't anything related to a ElasticPress plugin
bug. It looks like I may had a debug plugin which turned on debug logs for
elasticpress which slowed everything down. Thanks!

Best,
*Kevin Stalder*
*Development Manager*

Sanctuary - A Digital Marketing Group

Partners In Marketing, Leaders In Growth.

www.sanctuarymg.com


*Connect with me:*


Address:

219 E. Maple St., Ste 125

North Canton, OH 44720

Phone: 330.266.1188

LinkedIn <http://www.linkedin.com/company/sanctuary-marketing-group> |
Facebook <https://www.facebook.com/sanctuarymg> |  Twitter
<https://twitter.com/sanctuarymg/>
