### ISSUE TITLE
ElasticPress not for Widget but main site search bar?

### ISSUE THREAD

**Issue by casinojeffrey** [10up/ElasticPress#1558]
**Describe your question**

Hi there! I just installed and indexed everything via your great elasticpress plugin but now i am struggling. I don't want to add a sidebar-widget for search and faceting but rather use the elasticsearch function via my main search-bar which is built in my theme. How and where do I do that? Faceting can then be done inside the search results in my opinion.

Thank you for your reply in advance.

**Comment by brandwaffle** [comment]
Hi @casinojeffrey as long as your site's theme uses the standard WordPress approach to searching (i.e. it passes in a 's' search parameter), this will be automatically handled by ElasticPress. In other words, search is likely already using ElasticPress! You can always confirm by installing the Debug Bar ElasticPress plugin, which will report all the queries routed to Elasticsearch.
