### ISSUE TITLE
ElasticPress autosuggest causes all WP_Query usage to fail

### ISSUE THREAD

**Issue by Maxdw** [10up/ElasticPress#1560]
ElasticPress 3.2.3 in combination with WordPress 5.0.7 causes all WP_Query usage after the get_search_form() call to fail due to a bug in the autosuggest functionality. 

[This line in Autosuggest.php](https://github.com/10up/ElasticPress/blob/3.2.3/includes/classes/Feature/Autosuggest/Autosuggest.php#L428) adds a filter that is returning [an empty array](https://github.com/10up/ElasticPress/blob/3.2.3/includes/classes/Feature/Autosuggest/Autosuggest.php#L459) that ends up being set in [WP_Query::get_posts](https://github.com/WordPress/WordPress/blob/5.0.7/wp-includes/class-wp-query.php#L2755) and [blocks calls to $wpdb here](https://github.com/WordPress/WordPress/blob/5.0.7/wp-includes/class-wp-query.php#L2788). This is because it is an empty array and not an expected null. It seems this filter does not properly get unset? When I change the empty array returned from the filter to a null things start working again.

**Comment by tott** [comment]
Hi @Maxdw this is concerning but I was not yet able to reproduce this issue. Can you let me know a bit more about the steps you use to trigger this behavior. Are you using a certain theme, which plugins are activated, are there any customizations? How does the issue manifest?

**Comment by Maxdw** [comment]
Hi Tott,

It seems to be very easy to reproduce using the following steps:

- Grab a clean WordPress 5.0.7
- Install ElasticPress 3.2.3 and configure it using a self-hosted ElasticSearch URL
- Make sure the ep_feature_settings option has the autosuggest feature enabled, mine looks like:

```
a:5:{s:6:"search";a:3:{s:16:"decaying_enabled";s:1:"0";s:6:"active";b:1;s:14:"force_inactive";b:0;}s:13:"related_posts";a:2:{s:6:"active";b:1;s:14:"force_inactive";b:0;}s:6:"facets";a:3:{s:10:"match_type";s:3:"all";s:6:"active";b:1;s:14:"force_inactive";b:0;}s:11:"autosuggest";a:3:{s:12:"endpoint_url";s:32:"http://wordpress.test.local:9200";s:6:"active";b:1;s:14:"force_inactive";b:0;}s:14:"searchordering";a:2:{s:6:"active";b:1;s:14:"force_inactive";b:0;}}
```

- Modify the default theme twentynineteen index.php file and run a simple query

```
$query = new WP_Query([
    'post_type' => 'post'
]);

var_dump($query->have_posts());
```

It will dump false due to the reason described in the issue. Deactivate the plugin and it'll return true.

My guess is that you're adding the `posts_pre_query` filter with a priority of 100 and removing it with a priority 10 causing it to not be deleted.

**Comment by tott** [comment]
Thanks for the quick feedback. Could you try if https://github.com/10up/ElasticPress/archive/fix/1560.zip fixes the issue?

**Comment by Maxdw** [comment]
Yep that totally fixed it. I dropped it in, refreshed the homepage and the var_dump now returned true.

**Comment by tott** [comment]
Thanks for the help! We'll get a hotfix release out asap

**Comment by tott** [comment]
This issue should be resolved with the recent ElasticPress version. If you should run into any further issues please feel free to reopen this ticket.
