### ISSUE TITLE
One of the latest updates prevent menus from showing up in the frontend

### ISSUE THREAD

**Issue by florianbrinkmann** [10up/ElasticPress#1562]
**Describe the bug**
After updating EP (I do not know the number I updated from) to the latest version, my main menu showed all pages instead of only a few, and another menu and a menu widget did not show anything. After deactivating ElasticPress, everything worked again.

I used it with a custom Elasticsearch host (hosted on Heroku) and the Related Posts and Autosuggest feature.

**Steps to Reproduce**
I’m not sure how to reproduce it, I hope somebody might know something in the latest releases that has something to do with menus. I guess it is not a general problem, because then someone else would have noticed it before.

**Expected behavior**
The menus are displayed.

**Environment information**
WordPress 5.3 (multisite) with a custom theme, latest EP version, all other plugins were disabled for testing.

**Comment by cmcgee93** [comment]
Give [this](https://github.com/10up/ElasticPress/issues/1560#issuecomment-554672976) a try, seemed to work for me. 🙂

**Comment by florianbrinkmann** [comment]
Thanks @cmcgee93! I saw the issue yesterday, but did not thought it would be related. But it was, it works with the fix :) So, thanks again for the hint! :)

**Comment by cmcgee93** [comment]
@florianbrinkmann No problem, glad I could help!

**Comment by tott** [comment]
This issue should be resolved with the recent ElasticPress version. If you should run into any further issues please feel free to reopen this ticket.
