### ISSUE TITLE
Compatibility with SearchWP Live Ajax Search?

### ISSUE THREAD

**Issue by simplenotezy** [10up/ElasticPress#1564]
Hi,

I would like to know if ElasticPress is compatible with this plugin, which we currently use to show search suggestions to our users: https://wordpress.org/plugins/searchwp-live-ajax-search/

**Comment by tott** [comment]
I think this plugin is likely not compatible with ElasticPress, however ElasticPress comes with its own autosuggest feature so you would not need this plugin anymore.
