### ISSUE TITLE
How to use Wordpress search with external data in my elasticsearch document/index?

### ISSUE THREAD

**Issue by mvdhoek1** [10up/ElasticPress#1567]
Hello 10up,

I've installed elasticsearch 7.2.4 locally together with Kibana (And watched the tutorial). After this I've installed the elasticpress plugin on my Wordpress website (also locally) and configured the settings to the settings of the elasticsearch server. The Wordpress search of my website now uses elastic. I want to create a situation where my Wordpress search includes data from 2 external sources and displays whole bunch together on my search-results page. The external sources are not using elasticsearch.

After hours of research I have some questions about the following steps that I might need to undertake.
1. Should I add/put the external data to my existing document on my local Wordpress website and force the Wordpress search to use this document?
2. Is it possible to install the elasticsearch server on the external sources and somehow combine the documents with my local document and than force the Wordpress search to use all the documents separately or combined?

<img width="1440" alt="Schermafbeelding 2019-11-20 om 13 28 29" src="https://user-images.githubusercontent.com/11852816/69239903-98d2a700-0b9b-11ea-93aa-48f946b83d58.png">

**Comment by tott** [comment]
Hi @mvdhoek1,
This depends a bit on how you would like to build your app. If you would render everything through a WordPress theme it's likely best to import the external sources into WordPress and have ElasticPress take care of indexing and querying these sources. In this scenario I would likely setup a WordPress multisite and use separate sites for each of the external sources (depending on their size). You can then query both sites through ElasticPress.
An other alternative, mainly if you are planning to pull the results directly out of ElasticSearch throught the front-end would be to just create separate ElasticSearch indexes for the external sources and query all required indexes through ElasticSearch directly and combine the results in the front-end. 
I hope this makes sense? 

You can read more about querying multiple indices here https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-search.html#search-multi-index

**Comment by mvdhoek1** [comment]
Hi Tott,

Thank you for replying, we have find a solution with logstash and http polling. 

You can read more about this on their website: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http_poller.html

Example:
`input {
  http_poller {
    urls => {
      test1 => "http://localhost:9200"
      test2 => {
        # Supports all options supported by ruby's Manticore HTTP client
        method => get
        user => "AzureDiamond"
        password => "hunter2"
        url => "http://localhost:9200/_cluster/health"
        headers => {
          Accept => "application/json"
        }
     }
    }
    request_timeout => 60
    # Supports "cron", "every", "at" and "in" schedules by rufus scheduler
    schedule => { cron => "* * * * * UTC"}
    codec => "json"
    # A hash of request metadata info (timing, response headers, etc.) will be sent here
    metadata_target => "http_poller_metadata"
  }
}

output {
  stdout {
    codec => rubydebug
  }
}`
