### ISSUE TITLE
Determine why/how an index was started

### ISSUE THREAD

**Issue by jayhill90** [10up/ElasticPress#1570]
**Describe your question**
The other day a reindex was started mysteriously and subsequently locked up, not completing leaving integrated queries broken. Is there any way to determine why or how an index was triggered? It wasn't done via CLI and no one triggered it via the admin interface.

**Comment by tott** [comment]
@jayhill90 it could be related to a plugin upgrade, feature activation or faulty mapping. Do you have automated updates enabled? Which ElasticSearch version / hosting provider are you using? Did you maybe enable a feature that requires a re-index such as protected content or documents search?

**Comment by jayhill90** [comment]
No automatic updates. we're using 7.4 and Elastic.co. Nothing was touched EP settings side either. Thanks for the suggestions though.

**Comment by brandwaffle** [comment]
@jayhill90 the Stream plugin might help with this by showing you a trace of who (if anyone) kicked off a re-index in the dashboard or changed ElasticPress settings which would cause a reindex.
