### ISSUE TITLE
LIKE meta_query for users with ElasticPress does not match substrings

### ISSUE THREAD

**Issue by alecgeatches** [10up/ElasticPress#1577]
**Describe the bug**

ElasticPress uses `match_phrase` when converting a `meta_query` with a `LIKE` comparison. However, this does not match partial strings, which changes the behavior from standard WordPress queries.

Example:

```php
// First, add a user with 'my-plugin-meta-phone' set to '1235556789'

$meta_query = [[
    'key'     => 'my-plugin-meta-phone',
    'value'   => '555',
    'compare' => 'LIKE',
]];

$user_metas_no_ep_integrate = get_users([
    'meta_query' => $meta_query,
]);

var_dump($user_metas_no_ep_integrate);
// Returns one user

$user_metas = get_users([
    'meta_query'   => $meta_query,
    'ep_integrate' => true,
]);

d($user_metas);
// Returns zero users
```

The WordPress query does a `LIKE "%555%"`-type query that can match substrings in the phone number. The ElasticSearch query (below) uses `match_phrase`, which does not match an inner string.

<details><summary>EP Query - Click to expand:</summary>

```json
{
    "from": 0,
    "size": 10000,
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "match_phrase": {
                                    "meta.my-plugin-meta-phone.value": "555"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "sort": [
        {
            "user_login.raw": {
                "order": "asc"
            }
        }
    ]
}
```

</details>

**Steps to Reproduce**

1. Add a string-type user meta to a user, e.g. `1235556789`
1. Construct a `meta_query` with a `LIKE` comparison for a substring, e.g. `555`:

    ```php
    $meta_query = [[
        'key'     => 'my-plugin-meta-phone',
        'value'   => '555,
        'compare' => 'LIKE',
    ]];
    ```

1. Run the user query with `ep_integrate` on and off.

    ```php
    $user_metas_no_ep_integrate = get_users([
        'meta_query'   => $meta_query,
    ]);

    $user_metas = get_users([
        'meta_query'   => $meta_query,
        'ep_integrate' => true,
    ]);
    ```

1. Notice that the `'ep_integrate' => true` query does not match the user, but does without `ep_integrate`.

**Expected behavior**

Both queries should return one user. The behavior of `'ep_integrate' => true` should follow the WordPress implementation and match substrings.

**Environment information**
 - Device: PC
 - OS: Windows 10 Pro
 - Browser and version: Firefox 70.0.1
 - Plugins and version: ElasticPress 3.2.3
 - Theme and version: Custom theme
 - Other installed plugin(s) and version(s): N/A

**Additional context**

Since `Post` and `User` types both use the same `build_meta_query`, this is may also the case for post matching.

**Comment by tlovett1** [comment]
@alecgeatches I appreciate the thorough report, and you are definitely correct.

Elasticsearch is not good a substring matches similar to SQL like. In order to accomplish that, we'd likely use ngrams. However, those slow things down and take up space so we wouldn't want to add them to every meta value.

I'd suggest creating a special mapping field for whatever you are trying to do. I'm not sure we can do much better with the ElasticPress LIKE support.
