### ISSUE TITLE
Autosuggest triggering in all input[type="search"]

### ISSUE THREAD

**Issue by samikeijonen** [10up/ElasticPress#1579]
**Is your enhancement related to a problem? Please describe.**
I think autosuggest triggering in all `input[type="search"]`. In site there can be other search fields which are not related to ElasticSearch.

**Describe the solution you'd like**
Being able to define which search fields will have autosuggest. This can be class value.

Or set a class which disable autosuggest.

**Comment by MediaMaquina** [comment]
Hi, this option already exist on dashboard -> Elasticpress (unless i didn't understand you?)
![settings](https://user-images.githubusercontent.com/8179611/70236319-01f21700-1765-11ea-9daa-55592d50dddb.png)

**Comment by samikeijonen** [comment]
@MediaMaquina Is this for **additional** fields, not actually replacing the default fields? My hunch is yes but I don't have access to that page in my use case (client site).

**Comment by mlaroy** [comment]
@samikeijonen that's right, this field doesn't replace default fields, but only adds to them. Default fields currently include `.ep-autosuggest`, `input[type="search"]`,  and `.search-field`,

**Comment by felipeelia** [comment]
FWIW, in #2181 (released in EP 3.6.0) this is possible via code using the `ep_autosuggest_default_selectors` filter.
