### ISSUE TITLE
Help getting https to work?

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1584]
So far i got this working via `http://ip:9200` which is OK. But for auto-suggest i need https since the main page is already https and the browser will block http requests on front end.

So i created a sub-domain (i'm using cloudflare, [flexible encryption](https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options) -the one that works without a valid cert at origin- ) 

But when i try to access it i get this error: `https://s.domain.com:9200/test-post-1/post/_search	cURL error 35: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

My setup is **Ubuntu 16.04.6 LTS** 
I installed elasticsearch following this steps: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-16-04

How would i go about enabling https? Any steps or tutorial i could follow? Thanks!

**Comment by brandwaffle** [comment]
Hi @MediaMaquina,

Unfortunately this support list is only for the ElasticPress plugin itself. It sounds like you're dealing with an issue between CloudFlare and the Elasticsearch server you've set up. I'd recommend asking in the Elastic forums or perhaps reaching out to CloudFlare support.

Once HTTPS is up and running for your Elasticsearch instance, ElasticPress will be fully compatible--in fact our ElasticPress.io service is 100% HTTPS-enabled for the exact reason you've outlined (security, especially with autosuggest).
