### ISSUE TITLE
"Custom Search" and "Manage Search Fields & Weighting" don't work for me

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1586]
Hello, this 2 features do not work for me.

1. I created a custom search and the page that is supposed to come up first does not come up at all (type is "page").
2. I set the weight of titles at 100 and content at 1 but still posts with query present in content comes up first and exact match titles come up after on results.

I have this on my functions so maybe it's breaking it? Should i change it? (i use this for AND logic)

```
 function set_to_exact( $formatted_args, $args ) {
    if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
        $formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
        $formatted_args['query']['bool']['must'][0]['multi_match']['operator'] = 'AND';
        unset( $formatted_args['query']['bool']['should'] );
        unset( $formatted_args["query"]["bool"]["must"][0]["multi_match"]["type"] );
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );
```

**Comment by tott** [comment]
Can you try changing the filter to a different priority.
`add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );` to `add_filter( 'ep_formatted_args', 'set_to_exact', 30, 2 );`
The search weighting is applied with priority 20 so it might interfere with your filter when it runs before this.

**Comment by MediaMaquina** [comment]
Thanks it's alright now.
