### ISSUE TITLE
EP 7.4 (develop) Reindex via browse admin works, but not via wp elasticpress command line

### ISSUE THREAD

**Issue by wss-chadical** [10up/ElasticPress#1601]
**Describe the bug**
Using develop branch, ES 7.4 with ingest, Only index settings not turned on are Auto Suggest and User Content.

Running index from wp command line results in "Request Entity Too Large" error.

!! Reindexing works fine via wp browser admin.

**Steps to Reproduce**
wp elasticpress index --setup --show-bulk-errors

**Expected behavior**

**Screenshots**
Console:
```
www-data@2b5210d90032:/app$ wp elasticpress index --setup --show-bulk-errors
Adding post mapping...
Success: Mapping sent
Indexing posts...
Error: Request Entity Too Large
www-data@2b5210d90032:/app$
```
Logs:
```
elastic_1          | [2019-12-13T15:53:55,858][INFO ][o.e.c.m.MetaDataDeleteIndexService] [lando] [pl-wss-dot-com-lando/IwJvEic0QeKb_uxuodZ1pA] deleting index
elastic_1          | [2019-12-13T15:53:55,889][INFO ][o.e.c.m.MetaDataCreateIndexService] [lando] [pl-wss-dot-com-lando] creating index, cause [api], templates [], shards [5]/[1], mappings [_doc]
```

**Environment information**
 - Device: Docker
 - OS: Debian 9
 - Plugins and version: wp develop branch, elastic search 7.4 with ingest plugin
 - Theme and version: custom
 - Other installed plugin(s) and version(s): tons.

**Comment by ethanclevenger91** [comment]
I believe the bulk size is managed independently between the browser index functionality and the CLI version. I imagine they are currently set differently and one is larger than the other. Check your setting in the admin, and use that value for the following:

`wp elasticpress index --setup --show-bulk-errors --per-page=##`

**Comment by wss-chadical** [comment]
Cool, yes I've noticed that the command line is using a different bulk size. I will give that a try.

**Comment by wss-chadical** [comment]
wp elasticpress index --setup --show-bulk-errors --per-page=50
That worked....
