### ISSUE TITLE
Missing terms for non-english posts in index

### ISSUE THREAD

**Issue by rferguson10** [10up/ElasticPress#1605]
I've noticed no issues with english posts terms being included in the index, but sparingly I find a lot of french posts either not having terms included or missing some. 

An interesting point to mention is that when I save a post in question individually (versus bulk index), then the data reaches the index correctly.

The other weird artifact about this situation I've noticed is that while during indexing, I can dump a post I know has terms. It will appear briefly in the index with terms, then towards the end of indexing, the terms portion of the document in the index goes blank.

Elasticpress 3.2.1
Elasticsearch 6.5.4

**Comment by tott** [comment]
@rferguson10 can you advise what type of plugins / methods you are using to achieve the multiple languages. Is it a site per language, are you having multiple languages in one site? Are you using a multi-language plugin?

**Comment by rferguson10** [comment]
This is just a single site with 2 languages via WPML

Both languages are indexed via this hook:

/**
 * Make sure all languages are indexed
 * https://github.com/10up/ElasticPress/issues/477
 */
add_filter('ep_index_posts_args', function($args) {
    return array_merge($args, [
        'suppress_filters' => true
    ]);
});

**Comment by brandwaffle** [comment]
@rferguson10 have you tried a bulk index via WP-CLI with the --show-bulk-errors flag added? We do sometimes see an issue where the total number of distinct meta fields grows too large for Elasticsearch to handle (this often happens with Advanced Custom Fields which builds repeaters as separate fields). It could be that the second language is adding some similar meta and eventually just hitting the ES max.

When you say the post is dumped out mid-index, are you doing that by directly querying your Elasticsearch server? If not, please note that ElasticPress disables itself for queries while running a dashboard index, so if you directly query through WordPress it would be pulling from MySQL at that point, not Elasticsearch. When the index stops, it then uses Elasticsearch (even if the index didn't complete entirely), so if you were to repeat the same query and it routes through EP, you'd then get the result with no terms assuming they weren't properly synced. If you're querying ES directly, then ignore what I just said 😄

**Comment by rferguson10** [comment]
I am using ES directly to query for my search. I've also always run show bulk errors each time I run an index and nothing comes up. I've even set the index index.mapping.total_fields.limit to 9000 to make sure no limits are causing this issue.

**Comment by brandwaffle** [comment]
@rferguson10 ok, we've covered the obvious stuff. Now on to the esoteric 😃 

Are you getting any non-200 results on any of the ES queries when you view the server logs? Do you have logs that show the query body that you could reference by any chance?

If you turn off English and test with just French, are the results the same or different? Have you tried with a small set of test posts to see if a portion of them are also getting messed up or if this only starts happening at scale?

Are the posts that get terms and then have them deleted consistent, or have you noticed any randomness here?

**Comment by brandwaffle** [comment]
@rferguson10 I'm going to close this ticket. If you're still experiencing the issue, feel free to reopen. Thanks!

**Comment by rferguson10** [comment]
After coming back to this on a recent project, I'm finding that the indexing process really depends on the interface language you are on. Having suppress_filters isn't enough within ep_index_posts_args.

I caught this while indexing via wp-cli. 86 posts were being indexed there (all my english posts). Then sometimes I went to the backend to click sync. When doing so, I'd sometimes see 15 posts (my french posts). I couldn't figure out the reason for the difference. I Then used the global language switcher in the top bar to "sync now" in one language, flip to the other and do it again. It seems you have to do both individually. This should really be rectified or pointed out in documentation somewhere. 

This in combination with needing 'suppress_filters' => true to include other languages is a barrier to getting this working for multilingual sites. You'd also need to add the language of the posts to the index, which I'm doing through ep_post_sync_args:

```
$post_args = array('element_id' => $args['ID'], 'element_type' => 'post');
$post_language_info = apply_filters('wpml_element_language_details', null, $post_args);
$args['language_code'] = $post_language_info->language_code ?? 'en';
```

I was only able to find this post of others talking about this as well:
https://wordpress.org/support/topic/wpml-and-custom-post-types/
