### ISSUE TITLE
able to get site_url?

### ISSUE THREAD

**Issue by columbian-chris** [10up/ElasticPress#1608]
Is there was a way I can cURL Elasticsearch indexed via ElasticPress to get wordpress options such as the site URL?

**Comment by brandwaffle** [comment]
@columbian-chris we don't currently index options (the plugin only indexes posts and CPTs, plus optionally users). You could create an options Indexable, however, if you want to store this info in the Elasticsearch index. I would caution though that the latency of connecting to Elasticsearch (even locally) usually makes this less efficient than just querying MySQL (even more so if you have a caching layer in place).

**Comment by columbian-chris** [comment]
Appreciate the answer, @brandwaffle. I'm assuming CPT stands for "custom post type"?

**Comment by brandwaffle** [comment]
@columbian-chris Yup!
