### ISSUE TITLE
Autosuggest endpoint with ElasticPress 3.3 & ElasticSearch 7.5 stopped working

### ISSUE THREAD

**Issue by tamara-m** [10up/ElasticPress#1625]
We have a working autosuggest endpoint using ElasticPress 3.3 and ElasticSearch 5.6, it works perfectly and returns [results correctly as in this example response here](https://gist.github.com/tamara-m/e4903308081a6eae8994d3d5a591ab86)

We are attempting to upgrade to ElasticSearch 7 so created a new deployment with version 7.5.1, and re index the site. 

Regular queries work correctly after the upgrade, however, the autosuggest endpoint stopped working.
For the same request as the example above, it is now returning [no results as shown in this response here](https://gist.github.com/tamara-m/fdb770d0685acb3d0ff609f68b3bdcc3)

We see nothing that points to what the problem can be in logs nor console. 
Something strange is that sometimes the autosuggest endpoint returns 504 gateway timeout, but with no further indication or logs to help us point where the problem can be.

Any ideas, recommendations on how to troubleshoot this issue would be super appreciated. Can share example requests and further details.

**Comment by brandwaffle** [comment]
Hi @tamara-m I'm not sure how much help it will be, but the only thing I can think of (besides a reindex, which is required after activating the Autosuggest feature) is that the mapping has changed with ES 7.x and perhaps you have some code running between the site and the autosuggest endpoint that requires the previous request format? If you can share any details about your autosuggest setup, that would be helpful. Most importantly, is the connection for autosuggest direct from the client browser to your Elasticsearch endpoint, or is there anything in the middle.

You can also try using WP Local Docker v2 (https://github.com/10up/wp-local-docker-v2) and upgrading to the elasticsearch-7.5 image to confirm if the problem happens locally or is related to the network issue that seems to be happening occasionally.

Please note our ability to support specific server configs is somewhat limited, though we do offer hourly consulting via our ElasticPress.io site if you need more hands-on support.

**Comment by tamara-m** [comment]
Hey @brandwaffle thanks so much for the reply. 

First thing I did was indexing, so that should not be it. Also, as mentioned regular searches that are not autosuggest, do return results and with `elasticshearch_success => true`

I dont *think* it's server config related either, as I do get a successful response from ES, just with no hits, but will do the local testing anyway first to rule it out a server issue.

I don't have much code between the site and the autosuggest endpoint really. Using a slightly modified version of https://github.com/grossherr/elasticpress-autosuggest-endpoint (mods to get it to work as that one exactly doesn't work as is) but not much more than what you can see there.

The mapping having changed could be it. 

This is the content of $params that is sent to search() on line 55 from https://github.com/grossherr/elasticpress-autosuggest-endpoint/blob/master/elasticpress-autosuggest-endpoint.php that gets hits back on ES 5.6 but not on 7.x:

https://gist.github.com/tamara-m/a2de0ca014a28977366128c161fb046a

I understand the paid support request, but can I just know if you have tested and know that the new mapping for 7.5 introduced in EP 3.3 does work still works for autosuggest? Or is it untested?

**Comment by brandwaffle** [comment]
Hi @tamara-m, yes, I just tested with EP 3.3 and ES 7.5 using WP Local Docker and I'm seeing autosuggest results. Of course, this is connecting directly from the browser to the Elasticsearch endpoint.

Your endpoint PHP code does seem pretty straightforward and the $params query seems fine at first glance, but in terms of testing, I would ensure that you still don't get results if you plug in your ES server's _search endpoint directly in the ElasticPress menu. If you do get results when querying directly, at least that helps narrow things down.

Hope this helps!

**Comment by brandwaffle** [comment]
Added an explanation of how this functions in #1633 and our testing process with WP Local Docker for ensuring it works.

**Comment by aaronjpitts** [comment]
I'm having the same issue, you can see my staging environment here: I've deactivated all plugins and put it on the twenty twenty theme: https://staging.thewatchpages.com/ The endpoint is set up correctly in nginx, you can see in the network tab it's hitting elastic search but it's returning zero results

`
{"took":1816,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}
`

Running Elastic search 7.5.1 and the latest Wordpress (5.3.2) and Elastic Press (3.3). What could be the issue?

**Comment by tamara-m** [comment]
Did you find the solution on that other thread?
