### ISSUE TITLE
Don't index revisions when protected content indexing is enabled

### ISSUE THREAD

**Issue by nickdaugherty** [10up/ElasticPress#1626]
**Is your enhancement related to a problem? Please describe.**

When enabling the "index protected content" feature, revisions are included in the indexed post types, which can drastically inflate the index size (and time to reindex) without providing much value.

**Describe the solution you'd like**

Revision indexing is disabled by default when protected content is indexed, as having them indexed provides limited or no value in most cases. This is similar to nav menu items, which are already [excluded from protected content indexing](https://github.com/10up/ElasticPress/blob/8b3378838478688a94450ee8668353ec517009f9/includes/classes/Feature/ProtectedContent/ProtectedContent.php#L68).

Revisions could still be indexed if desired, via the `ep_indexable_post_types` filter.

**Comment by brandwaffle** [comment]
@nickdaugherty seems legit. Give me a day or two to think of any exceptions, otherwise this feels like a solid change to add.

**Comment by tlovett1** [comment]
Makes sense to me.

**Comment by petenelson** [comment]
FYI, there is one other open PR #1494 that also deals with indexing revisions.

**Comment by brandwaffle** [comment]
@petenelson that code looks good to me. Can you review, add tests, and merge? If you run out of time, feel free to reassign back to me.

**Comment by tlovett1** [comment]
Resolved in #1640
