### ISSUE TITLE
ngram filter breaks mapping | edge_ngram working

### ISSUE THREAD

**Issue by dominikkuen** [10up/ElasticPress#1631]
**Describe the bug**
Can't add filter of type "ngram" to mapping.
Same settings for type "edge_ngram" work.

```php
function elasticpress_config_mapping( $mapping ) {

    //WORKING
    $mapping['settings']['index']['analysis']['filter']['4_6_grams'] = array(
        'type' => 'edge_ngram',
        'min_gram' => 4,
        'max_gram' => 6,
    );

    //BREAKS MAPPING
    $mapping['settings']['index']['analysis']['filter']['4_6_grams'] = array(
        'type' => 'ngram',
        'min_gram' => 4,
        'max_gram' => 6,
    );

    $mapping['settings']['analysis']['analyzer']['custom_analyzer'] = array(
        'type' => 'custom',
        'tokenizer' => 'whitespace',
        'char_filter' => [
            'html_strip'
        ],
        'filter' => [
            'lowercase',
            'asciifolding',
            '4_6_grams',
        ]
    );

    return $mapping;
}
add_filter( 'ep_config_mapping', 'elasticpress_config_mapping', 10, 2 );
```
**message:**
Adding post mapping...
Error: Mapping failed

**Steps to Reproduce**
1. Add filter of type "ngram" to custom analyzer
2. run wp elasticpress index --setup
3. See error

**Environment information**
EP 3.3
ES 7.5.1

**Comment by brandwaffle** [comment]
@dominikkuen I'm not 100% sure, but at first glance I'm wondering if this is because we don't define the ngram analyzer (but do define an edge_ngram analyzer https://github.com/10up/ElasticPress/blob/941b5c69e1b0622babe3c54852e03a1a91b70d33/includes/classes/Feature/Autosuggest/Autosuggest.php#L161 ). Might be worth adding the appropriate analyzer as well and see if that fixes the issue?

**Comment by dominikkuen** [comment]
@brandwaffle I am not using the autosuggest feature. 
The ngram filter was working with EP 3.2.1 and ES 5.6

**Comment by brandwaffle** [comment]
@dominikkuen ok, this definitely seems related to newer versions of ES. I found this by debugging the mapping call:
```"{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The difference between max_gram and min_gram in NGram Tokenizer must be less than or equal to: [1] but was [2]. This limit can be set by changing the [index.max_ngram_diff] index level setting."}],"type":"illegal_argument_exception","reason":"The difference between max_gram and min_gram in NGram Tokenizer must be less than or equal to: [1] but was [2]. This limit can be set by changing the [index.max_ngram_diff] index level setting."},"s"...```

This led me to try and set the `index.max_ngram_diff` to 2. That seemed to have no effect. When I changed 4 and 6 in the filter to 4 and 5, I am able to map fine. A bit more googling revealed this Github issue https://github.com/ankane/searchkick/issues/1119 which seems to have been closed without comment after another Elasticsearch user reported exactly what I'm seeing (and no effect when changing it as I did).

At this point I'm thinking the limitation might be added to Elasticsearch on purpose (I saw discussion on google of people misusing the min and max settings for really high numbers and causing all sorts of issues. At this point I'm not sure what else I can offer except perhaps filing a bug report on Elastic's Github, unless you can make do with min/max settings that are only off by 1.

**Comment by brandwaffle** [comment]
@dominikkuen I just realized the error I was seeing was from the `user` mapping. When I changed that index setting as well, I was able to index fine. Looks like the solution would be a conditional filter to the `index.max_ngram_diff` to `2` on post mapping (but not user mapping). If you have the Users feature turned off, of course, you can just add the field to the mapping with a filter.

**Comment by brandwaffle** [comment]
@dominikkuen any reason why you're not just filtering the mapping to set that `.index.max_ngram_diff` as I suggested? It's available in `$mapping['settings']` -- you would simply add that declaration as a keyed array element `'index.max_ngram_diff' => 2`
