### ISSUE TITLE
Does fuzziness affect autosuggest ?

### ISSUE THREAD

**Issue by clemorphy** [10up/ElasticPress#1636]
I am modifying the fuzziness through the `ep_fuzziness_arg `filter, and it seems to apply correctly as long as I don't enable autosuggest.

```
function ep_set_fuzzyness() {
    return 0;
}
add_filter( 'ep_fuzziness_arg', 'ep_set_fuzzyness', 10, 0 );
```

But when I enable autosuggest, it seems that fuzziness is on again. Is it the expected behaviour ?

**Comment by brandwaffle** [comment]
@clemorphy Autosuggest does set the fuzziness to 'auto' with a filter running at the same priority level as yours https://github.com/10up/ElasticPress/blob/941b5c69e1b0622babe3c54852e03a1a91b70d33/includes/classes/Feature/Autosuggest/Autosuggest.php#L86

If you set your filter to run later (aka 11 or higer priority) you should get the desired result.

**Comment by clemorphy** [comment]
That was it.
Thank you!
