### ISSUE TITLE
Label or interrupt prompt for reindex button

### ISSUE THREAD

**Issue by jeffpaul** [10up/ElasticPress#1646]
**Is your enhancement related to a problem? Please describe.**
There’s the issue of whether the reindex button needs some clearer labeling and/or an interrupt prompt when clicked. @brandwaffle would much prefer labeling to an interrupt prompt, because plugin users are likely to hit that button several times while configuring the plugin and he would hate to interrupt them every time, but either way something should make it clear what that button does.

**Describe the solution you'd like**

Feedback from @surrealwebs:
> We upgraded from 2.4 to 3.3. I re-indexed via CLI, looked at the dashboard for EP and it was saying we needed to re-sync even though the job had finished successfully via CLI. The button on the EP admin page wasn’t clear (I’m still new to EP) so I didn’t know what that button did. I thought it would refresh and the plugin would check the status of the index and remove the messages. I clicked it and it started indexing. There’s not messaging on the button, no warnings or anything so I was a bit surprised it just started going

> Same with the message about auto-complete being automatically activated and having the re-sync link there as well. I clicked it because I was curious and because I already messed up the index. It starts right away also.

> Ultimately, I ended up doing the index with CLI anyway because it’s faster, even then the message about needed to re-sync didn’t go away.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by claytoncollie** [comment]
Related #2286

**Comment by felipeelia** [comment]
Now that ElasticPress has a new screen specifically for sync and features have a warning related to a required resync, I'm going ahead and closing the ticket. Thank you all!
