### ISSUE TITLE
cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by puntope** [10up/ElasticPress#1650]
**Describe your question**

Hello, I'm trying to index my index but I receive this errors. 

wp elasticpress index --setup

Indexing posts...
Error: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received

OR

wp elasticpress index --offset=50
Indexing posts...
Error: cURL error 52: Empty reply from server

**Comment by brandwaffle** [comment]
@puntope You can try lowering the number of posts synced per HTTP request by specifying `--per-page=1` (or another low number) and increasing from there if you're successful in an initial sync.

**Comment by puntope** [comment]
It works!

**Comment by sebumd** [comment]
I'm syncing ~60k posts on first sync - what's the best way to do this for the first time? There seems to be no way to continue syncing if it fails once, I have to start over..
