### ISSUE TITLE
Identify in which field(s) keywords were found

### ISSUE THREAD

**Issue by clemorphy** [10up/ElasticPress#1651]
Hi

Is there a way to know in which field(s) the searched keywords were found ?
I can't find this information in the EP Query Result displayed in the debug bar, but maybe this can be done with a filter ?

**Comment by oscarssanchez** [comment]
Perhaps something like https://github.com/10up/ElasticPress/pull/1552 could help you in future releases @clemorphy !

**Comment by clemorphy** [comment]
Thanx @oscarssanchez but my need is not to highlight keywords. I would like to know, for each hit, which Wordpress fields contain the searched keywords.

**Comment by oscarssanchez** [comment]
Hi @clemorphy ,

I think you could alter the formatted query that's being sent to elasticsearch with the  `ep_formatted_args` filter, however, i don't know what type of query you would need to do for this particular use case. I found the following in the elastic.co forums: https://discuss.elastic.co/t/hit-counts-within-a-document/19643/6 which doesn't seem to be 100% what you are probably looking for, but could be a good start.
