### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by roditi3811** [10up/ElasticPress#1654]
**Describe the bug**
I am getting this error when searching for products in my Woocommerce store

**Steps to Reproduce**

1. Go to 'the search bar on the website and search for a product'
2. Click on 'search'
3. When inspecting with the WP plugin "Query monitor" i get this error 
4. See error in tab HTTP API errors

**Expected behavior**
I expect to get the search results using elasticsearch, but given this error, i get the results generated by the standard WP search module.

**Screenshots**
![ep_error](https://user-images.githubusercontent.com/60715009/73882340-8991fa00-486a-11ea-8f7f-e26bbbef256b.png)

**Environment information**
 - Device: dedicated server
 - OS: centos 7.7.1908
 - Browser and version: firefox
 - Plugins and version: ElasticPress 3.3, elasticsearch 7.5
 - Theme and version: storefront

**Additional context**
/etc/elasticsearch/elasticsearch.yml

cluster.name: prod
node.name: prod-node-1

bootstrap.memory_lock: true
network.host: server.ip
http.port: 9200
discovery.seed_hosts: ["server.ip"]
cluster.initial_master_nodes: ["prod-node-1"]

/etc/elasticsearch/jvm.options

-Xms15g
-Xmx15g
(the server has 32gb RAM)

firewall-cmd --zone=public --permanent --add-port 9200/tcp

/etc/systemd/system/elasticsearch.service.d/override.conf

[Service]
LimitMEMLOCK=infinity
LimitNPROC=4096
LimitNOFILE=65536

**Comment by brandwaffle** [comment]
@roditi3811 Hi! While we don't provide support for Elasticsearch, I can take a look at the request you're sending through ElasticPress to see if it's correctly formatted. Can you paste the results of the query from the Debug Bar ElasticPress plugin?

**Comment by roditi3811** [comment]
Thanks for the help and the fast response, here is the query result:
`{
    "error": {
        "root_cause": [],
        "type": "search_phase_execution_exception",
        "reason": "",
        "phase": "fetch",
        "grouped": true,
        "failed_shards": [],
        "caused_by": {
            "type": "too_many_buckets_exception",
            "reason": "Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",
            "max_buckets": 10000
        }
    },
    "status": 503
}`

**Comment by brandwaffle** [comment]
@roditi3811 interesting, this indicates the plugin is trying to aggregate across more than 10000 fields, which is quite a lot. Can you share the Query Body (feel free to xxxx out any site-specific information, or if you'd like to send it directly to me please let me know and I'll share contact info)?

**Comment by roditi3811** [comment]
Sure, no worries, here is the query body. The website is quite large, it has over 300K products listed, maybe this can be a problem?

[query_body.txt](https://github.com/10up/ElasticPress/files/4166652/query_body.txt)

**Comment by brandwaffle** [comment]
@roditi3811 The number of products itself shouldn't be an issue, but depending on the way the products are classified it might be. Here's the part of the query I'm focusing on:
```javascript
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                },
                "yith_product_brand": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.yith_product_brand.slug"
                    }
                }
            }
```

The error you're getting is because ElasticPress creates aggregations for each of these WooCommerce attributes so that visitors can filter with them to find products. So, if you have more than 10000 unique brands in `yith_product_brand` it would trigger this error (this can be the case with a jewelry store, used clothing shop, or any other situation where the inventory is very unique and there are few shared brands, sizes, values, etc.).

We can certainly turn off these aggregations via code, or you could increase your Elasticsearch server's `max_buckets` setting https://discuss.elastic.co/t/why-es-doesnt-stop-my-aggregation-but-just-crashes/148170 to slightly larger than the number of distinct entries in each of your `aggs` above. From what I read, they don't recommend this, however, since it could cause performance issues.

If there's a particular field you think is causing this, I'd love to hear more about the business need so I can brainstorm a way to have the plugin handle this.

**Comment by roditi3811** [comment]
Yes, it's true, the website currently has over 20K brands, I think this is the only one causing these problems (there are only 1K product categories and only 6 product tags). I've increased `search.max_buckets` to over 10K and seems to be working now, I just have to be careful about those performance issues in this case.
Is there any way to introduce some limits to taxonomies, categories, etc.? Even on the search results page, when there are a lot of results, I get 10K results, nobody searches through all of them, I think a limit here would also be a plus.

**Comment by brandwaffle** [comment]
@roditi3811 you might want to look at this article https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/

Beyond that, you can reduce the `size` parameter for that aggregation to something like 100 and that would show the "top brands" returned as buckets by Elasticsearch.

**Comment by roditi3811** [comment]
Thanks, I will give it a try and see how it works.
