### ISSUE TITLE
filter eq_formatted_args missing from hook documentation

### ISSUE THREAD

**Issue by colegeissinger** [10up/ElasticPress#1657]
**Is your enhancement related to a problem? Please describe.**
No

**Describe the solution you'd like**
I was in need of adding a highlight to a query EP is running and found best way to modify the ES query via another GitHub issue in the repo. I realized that the `ep_formatted_args` was missing in the generated [hooks documentation sidebar](http://10up.github.io/ElasticPress/). Thought I'd document that here for a future fix/improvement for others.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by tlovett1** [comment]
Good catch. You're welcome to create a PR.

**Comment by felipeelia** [comment]
Closing this one as it was fixed in 3.5.5. Thanks!
