### ISSUE TITLE
Add meta data (ACF) to index

### ISSUE THREAD

**Issue by lolafrerot** [10up/ElasticPress#1658]
Hello !

I recently installed a self-hosted ElasticPress on my website. I have a lot of meta data associated to my posts, created with the ACF Pro plug-in. I tried to use your documentation to add this metadata to the search, but i'm not familiar with the "apply_filter" function. 

Do you have an example of how to add metadata to ElasticSearch?

Thanks a lot, 

Lola

**Comment by mustafauysal** [comment]
Hi @lolafrerot,

The metadata send to index automatically as long as they are registered as post meta. Did you check the actual data on Elasticsearch index?

**Comment by lolafrerot** [comment]
Hi !

My metadata are in the wp_postmeta table, and are stored like this : 
<pre>
meta_id | post_id | meta_key | meta_value
5634    | 405     | adresse  | 6 rue du mage
</pre>

I don't have a user interface to my index (it's a very long json), but when I search my value in it, i can't find it.
I added this code to my function.php file : 
<pre>
add_action( 'pre_get_posts', 'my_search_filter' );
function my_search_filter($query)  {
    if (($query->is_search && !is_admin()) && $query->is_main_query()) {
        $query->set('search_fields', array(
            'post_title','post_excerpt', 'post_content',
            'meta' => array( 'adresse' )
        ));
    }
}
</pre>

But it doesn't work either :(

**Comment by brandwaffle** [comment]
@lolafrerot unfortunately, we would need you to be able to provide debugging information to have a chance to help. Even then, our ability to support self-hosted instances is relatively limited.

I recommend looking through previous Github issues (including closed ones) which will show you how to add private meta to the index and the correct filters to use for this purpose (take a look at ep_formatted_args as a start). As @mustafauysal mentioned, you should definitely start by determining if your meta is being properly indexed, and that does require connecting to your Elasticsearch instance. In all transparency, if you're not able to view data in the index manually, it's unlikely you'll be able to troubleshoot and fix this efficiently.

The Debug Bar ElasticPress plugin can also help you view requests--this will help you determine how your requests look coming from the plugin. Again, it won't replace being able to view your Elasticsearch data, but it's a start.

For custom support, ElasticPress.io does provide hourly development expertise. You can reach out to us on our elasticpress.io website if you'd like to learn more.
