### ISSUE TITLE
Facets break the category pages of Woo

### ISSUE THREAD

**Issue by mustafauysal** [10up/ElasticPress#1662]
**Describe the bug**

When the facet feature is enabled and WooCommerce feature is disabled, product category pages can’t show any results.

**Steps to Reproduce**

1. Enable WooCommerce
2. Enable facets feature
3. Disable WooCommerce feature of EP
4. Visit a product category page

**Expected behavior**

Expected to see products there.

**Screenshots**
https://cloudup.com/cgUFNjWZEpk

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 5.3.2
 - Plugins and version: ElasticPress 3.3, WooCommerce 3.9.2 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Comment by tlovett1** [comment]
Is this related to the child category bug in #1661? In theory we won't need this if we fix that.

**Comment by brandwaffle** [comment]
@tlovett1 I'm thinking if someone doesn't have the WC feature active, we shouldn't take over their queries on WC archive pages. I think that's the approach @mustafauysal is taking here. I might not be thinking through all the potential use-cases though--happy to discuss.

**Comment by mustafauysal** [comment]
@tlovett1 nope, it's not related to that one. 

It seems the root cause is that the facet queries are integrating `WP_Query` when it shouldn't. 
For this particular Woo problem; the ES query doesn't include `product` post_type and that breaks the main query.

Maybe, we shouldn't integrate facet queries to the main query. In that case, maintaining a new query would be challenging for keeping aggregations consistent with the main query, though.

**Comment by tlovett1** [comment]
Totally makes sense. Good call.

**Comment by tlovett1** [comment]
On second thought, what do you think about checking the indexable post types and comparing those to what is set for the query? If the query is grabbing a post type that is not indexable, bail faceting.

**Comment by mustafauysal** [comment]
@tlovett1 We don't know the `post_type` at the archive pages, maybe we should make query integration with `ep_post_formatted_args` instead `pre_get_posts`.

Another problem with that approach is that, `Indexables::factory()->get( 'post' )->get_indexable_post_types()` returns `products` even Woo feature is not active.

But that thought gave me an idea about handling taxonomies. E.g
```
		$builtin_taxonomies = get_taxonomies( array(
			'public'   => true,
			'_builtin' => true,
		), 'names' );

		$facetable_taxonomies = apply_filters( 'ep_facetable_taxonomies', $builtin_taxonomies );
		$queried_object       = get_queried_object();

		if ( $queried_object && property_exists( $queried_object, 'taxonomy' ) && ! in_array( $queried_object->taxonomy, $facetable_taxonomies, true ) ) {
			return false;
		}
```
What do you think about registering facetable taxonomies exclusively?

**Comment by tlovett1** [comment]
@mustafauysal I think I'm just going to merge your original PR for now. We can revisit the taxonomies approach later. Nice work!
