### ISSUE TITLE
Allow EP search queries during non-destructive reindex

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#1668]
**Is your enhancement related to a problem? Please describe.**

Right now, when performing a non-destructive reindex via CLI, the plugin stops using EP for searches. While this makes sense if you've wiped the index, there's no reason in most cases not to keep using EP for searches while reindexing data.
**Describe the solution you'd like**

When performing a non-destructive reindex (aka CLI index without `--setup`), continue to allow search queries to run through EP.

**Designs**

I recommend we add a new wp_option flag in the put_mapping method (or perhaps delete_index method) that runs during CLI and dashboard sync. This flag (say, `ep_mapping_sync`) would then become the one to check for whether or not to allow EP to handle a search or revert back to WP. Other uses of existing transients and flags would remain unchanged for backwards compatibility.

Since the ajax sync currently always does a destructive reindex, we want to ensure that it always sets this `ep_mapping_sync` flag. For CLI, we would set it conditionally if `--setup` is passed in.

NB: we want to test behavior with things like the `put_mapping` CLI command to ensure we don't create weird behavior where the wp_option is not deleted, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by felipeelia** [comment]
Related to https://github.com/10up/ElasticPress/pull/1835

**Comment by rickalee** [comment]
With this solution, would we not need to pass in --setup if we are updating mapping? If not, would it be possible to not delete the current index even when we pass --setup as well?
