### ISSUE TITLE
Custom taxonomy returns all products instead of products in specific taxonomy.

### ISSUE THREAD

**Issue by ovaislak** [10up/ElasticPress#1669]
I am facing a strange problem, I have few custom taxonomy pages but none of them seems to be working after using this plugin.

https://medicalstore.com.pk/manufacturer/novartis/  this link returns all the products that are not tagged to (custom taxonomy ) manufacturer :  novartis

can you please suggest what's wrong here ?

**Comment by ovaislak** [comment]
Please suggest any fix.

**Comment by oscarssanchez** [comment]
Hi @ovaislak ,

There could be a lot of different explanations for this. 

Can you put a list of the environment where you are seeing these issues? It would be great to know plugins installed, themes, and any custom code modifications that are running.

Thanks!

**Comment by oscarssanchez** [comment]
Hi @ovaislak 

We are closing this one as we have not heard back from you. If you are still having issues please feel free to open a new issue.

Kind regards,
