### ISSUE TITLE
All Options are grayed out

### ISSUE THREAD

**Issue by liammaurer** [10up/ElasticPress#1673]
Hi, I recently just installed the plugin and all options for me are grayed out and unclickable. It seemed to accept the host I entered and it said Elasticsearch version is below the minimum required Elasticsearch version 5.0. But now there is no message and just grayed out.

Elasticsearch version: 7.5 (as per documentation)

Elasticpress Version: 3.4

![image](https://user-images.githubusercontent.com/25132161/75131081-06531e00-571d-11ea-8281-0df0a1010b42.png)

**Comment by mustafauysal** [comment]
Hi @liammaurer,

That overlay should appear only when the indexing is running. Do you see any errors on the console of the browser? 

It this error persist when you downgrade to 3.3? Version 3.4 has not been released yet. So, I'd recommend using the latest stable version which is 3.3.

**Comment by oscarssanchez** [comment]
Closing as there was no response back. If the problem has not being solved, please feel free to open a new ticket.
