### ISSUE TITLE
Plugin Internationalization

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#1675]
**Describe the bug**

Our `/lang/elasticpress.pot` is a bit outdated (the current version seems to be generated for EP 2.6). It is not a problem for those who use the plugin from the WP Official Directory (as translate.wordpress.org parses everything) but will be an issue for those willing to translate the plugin from the .pot.
Related to that, we should improve our calls to i18n functions, adding comments where needed, especially where we use placeholders.

**Steps to Reproduce**

- Open `/lang/elasticpress.pot`
- Check references for `bin/wp-cli.php` (this file isn't used anymore)

**Expected behavior**

Probably we should put in place a mechanism to generate a new .pot every time we have a new release.
Using 10updocker, I had to
1. `10updocker shell`
2. `cd wp-content/plugins/elasticpress/`
3. `wp i18n make-pot . lang/elasticpress.pot`

**Comment by jeffpaul** [comment]
I'd similarly recommend documenting release instructions like https://github.com/10up/distributor/blob/develop/CONTRIBUTING.md#release-instructions or https://github.com/10up/wp-newrelic/blob/develop/CONTRIBUTING.md#release-instructions and ensuring it includes the `npm run makepot` command as part of the release process.  Then that process can be used by whoever is shipping EP releases in the future.

**Comment by felipeelia** [comment]
@jeffpaul do you think it's worth creating a new issue to set a CONTRIBUTING.md file? It seems we don't have one in place here yet.
