### ISSUE TITLE
Support date params in WP_Query

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#168]

**Comment by GhostToast** [comment]
I began this with simple data parameters as outlined here: http://codex.wordpress.org/Class_Reference/WP_Query#Date_Parameters

I believe I've hit limitation for ElasticSearch as it stands. Consider the following example: Find all posts from October 15th. This would mean passing `'monthnum' => 10` and `'day' => 15`. In WP_Query, this will actually build out the following SQL statement:

` AND ( 
  ( MONTH( wp_posts.post_date ) = 10 AND DAYOFMONTH( wp_posts.post_date ) = 15 )
)`

However, with ElasticSearch, from what I can find, it only allows for date ranges. So building out a date range to find all posts whose publish dates were in October (of an undetermined year) on the 15th day, is not possible. 

One possible solution would be to have each date parameter be in the mappings, essentially creating a bunch of "meta" fields for these specific queries.

**Comment by tlovett1** [comment]
Thanks @joeyblake ! #224
