### ISSUE TITLE
unset( $filter_callbacks[10][ $hook ] ) in line 1213 of Command.com has no effect

### ISSUE THREAD

**Issue by kemal-endouble** [10up/ElasticPress#1680]
**Bug Description**
Private method stop_the_insanity() in class _Command_ at line 1213 (v3.3) try to unset a property of WP_Hook with the statement: **unset( $filter_callbacks[10][ $hook ] );**. 

In certain situation, this will cause PHP (tested with v7.1.33 & v7.3.6) to emit a notice:
`PHP Notice:  Indirect modification of overloaded element of WP_Hook has no effect in ... 
 elasticpress/includes/classes/Command.php on line 1213`

Result: unset has no effect, $wp_filter array is not changed

**Steps to Reproduce: run the following script**
```
<?php

class WP_Hook implements ArrayAccess
{
    private $a = [];

    public function __construct(array $a) { $this->a = $a; }
    public function offsetSet($key, $val) { if (is_null($key)) {$this->a[] = $val; } else {$this->a[$key] = $val; } }
    public function offsetExists($key) { return isset($this->a[$key]); }
    public function offsetUnset($key) { unset($this->a[$key]); }
    public function offsetGet($key) { return $this->a ?? null; }
}

$foo = new WP_Hook(['10' => ['a' => 1, 'b' => 2]]);
var_export($foo);
echo 'isset: ', isset($foo['10']), PHP_EOL;
unset ($foo['10']['a']);
var_export($foo);

```

**Expected behavior**
The specific hook which was unset should be gone

**Environment information**
 - Device: MacBook Pro 2018
 - OS: Ubuntu & OS-X 10.15.3
 - WordPress version: 5.3.2
 
**Additional context**

**Comment by tlovett1** [comment]
This is fixed in 3.3. Thanks!
