### ISSUE TITLE
Conflict with Advanced Post Types Order plugin

### ISSUE THREAD

**Issue by jeffceriello** [10up/ElasticPress#1681]
On our WordPress/WooCommerce site we are using the plugin Advanced Post Types Order to re-arrange the post types items. I have noticed that with ElasticPress activated the orders on the front end don't reflect the order in the back end anymore. For instance on the products category page the order don't reflect the back end.

Could you please let me know how to resolve or debug this issue? Thanks

**Describe your question**

There seems to be a conflict with Advanced Post Types Order plugin. The order in the front end don't reflect that in the back end.

**Comment by oscarssanchez** [comment]
Hi @jeffceriello ,

As I'm not very familiar with the plugin codebase, my help here is limited. I skimmed through the plugin codebase and it looks like this adds some new parameters to WP_Query which elasticpress does not know how to handle. On the other hand, I don't know how the re-arrangement of posts works here so if you could tell us more or less how that's being done perhaps we could offer better insights.

As of now, and again I don't have experience with this plugin, my first thought is this would not work out of the box with Elasticpress.

What you could do that is easy and quick to keep this plugin enabled without interferring with elasticpress is to disable elasticpress search in the admin dashboard, or limit your queries to run only when you are searching for a search term or filtering via `pre_get_posts`
