### ISSUE TITLE
Filters on EP remote requests not used on initial setup request

### ISSUE THREAD

**Issue by simplisticsca** [10up/ElasticPress#1682]
**Describe the bug**
I've traced it back to elasticpress/elasticpress.php:90 (v3.3) calling Indexables::factory()->register( new Indexable\Post\Post() ) outside of an action callback. This line is executed prior to other plugins and the theme being loaded, meaning that filters are not used on this initial request. Among other things, this prevents Authorization header from being added via the 'ep_format_request_headers' filter for those not hosting with ElasticPress.

The ES version check is too early in the WP lifecycle.

**Steps to Reproduce**
Do not use constant EP_API_KEY. Use filter 'ep_format_request_headers' to add own Authorization header. Go to EP settings page. See notice that EP cannot connect. You will not be able to run an index resync.

**Expected behavior**
Filters will be applied to requests.

**Environment information**
- WP Version 5.3.2
 - Plugin version 3.3

**Additional context**
Suggestion: wrap lines 85-131 of elasticpress.php in an 'init' callback to allow custom integration filters to be added in themes

**Comment by mustafauysal** [comment]
Hi @simplisticsca,

Can you upgrade to version 3.4 and let us know the results? I thought this issue has been addressed since we have started to register indexables with `plugins_loaded` hook.
