### ISSUE TITLE
post_type=product is no passing on the url when using facet to filter searched results

### ISSUE THREAD

**Issue by luciocm** [10up/ElasticPress#1684]
**Describe your question**

Hello, I don't know how can i fix it or if it's a bug because I'm a noob user. 
Well, I have an ecommerce and when I make a product search using elastic search and I try to filter the results with the facet widget the post_type=product is not passed in the url. So, instead the search result show my product search results layout it shows the general wordpress blog results search layout. Instead of being "?s=example&post_type=product&&filter_product_cat=example" it is only "?s=example&filter_product_cat=example". How can I fix it? Any idea?

**Comment by mustafauysal** [comment]
Hi @luciocm, 

You can use `ep_facet_query_string` filter to modify query_string.

Something like:
```
add_filter( 'ep_facet_query_string', function ( $query_string ) {
	$query_string = add_query_arg( 'post_type', 'product', $query_string );

	return $query_string;
} );
```
should work.

**Comment by luciocm** [comment]
That worked, you are awesome.
Thank you!
