### ISSUE TITLE
How to hide the ep-facet-widget with 0 term level?

### ISSUE THREAD

**Issue by luciocm** [10up/ElasticPress#1685]
**Describe your question**

Hey guys, I would like to know if there is a way to hide the "ep-facet-widget" if there is no term level.

**Comment by brandwaffle** [comment]
Hi @luciocm ,

Can you share a bit more detail on this one? Are you looking to hide the widget conditionally on certain pages, or to hide the whole widget if there are no posts tagged with that entire custom taxonomy, or something else?

Thanks for using ElasticPress!

**Comment by luciocm** [comment]
I would like to hide the whole widget if there are no post tagged with the entire custom taxonomy. Example: on my store I've got keyboards and cpu. If i search for computer and filter the category "keyboards" i would like to hide the default facet filter for cpu, like ram and core, because the facet for cpu attributes (ram and core), is empty when I'm searching for keyboards, and it's strange to show "ram" or "core" when I'm filtering for keyboards. It's just an example, I don't have a pc ecommerce.

**Comment by luciocm** [comment]
any solution?

**Comment by oscarssanchez** [comment]
Hi @luciocm ,

What comes to mind to make this happen is to use the `ep_facet_search_widget` filter and mimic the `widget` method,  and if the term count is 0 for each of the terms https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Facets/Widget.php#L101 return an empty string. 

Hope this helps
