### ISSUE TITLE
Weighting Engine changes sometimes fail to save when multiple boxes are checked or unchecked

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#1686]
**Describe the bug**

The Weighting Engine sometimes fails to update checkbox configs when many checkboxes are unchecked or checked and then the page is saved.
**Steps to Reproduce**

1. Go to Weighting Engine.
2. Check a bunch of boxes (at least 7-8)
3. Uncheck all boxes for a post type
4. Repeat until you see the data fail to change on save

**Expected behavior**

Updated checkboxes (either unchecked or checked as performed by user action) should appear.
**Screenshots**

**Environment information**
 WP Local Docker with EP.io and 3.3 (still happens on 3.4 in my testing)
**Additional context**

**Comment by felipeelia** [comment]
Closed via #1688
