### ISSUE TITLE
Intelligently detect product search fields and restrict results in Autosuggest

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#1687]
**Is your enhancement related to a problem? Please describe.**

Currently, WooCommerce product searches show results from the default Autosuggest query, but then a full search (hitting enter to reload the search page) does limit the results as `?post_type=product` is passed into the URL and therefore handled by EP properly.
**Describe the solution you'd like**

Determine when we're on a product search bar when applying Autosuggest, and conditionally limit the search to the product post_type.
**Designs**

**Describe alternatives you've considered**

**Additional context**

This would be a permanent/plugin-wide fix for the issue resolved with custom code in #1684

**Comment by Rahmon** [comment]
A possible workaround here could be to restrict the post type to product when accessing a WooCommerce page:

```php
add_filter(
	'ep_term_suggest_post_type',
	function( $post_types ) {
		if ( is_woocommerce() || is_cart() || is_checkout() || is_account_page() ) {
			return [ 'product' ];
		}

		return $post_types;
	}
);
```

**Comment by JakePT** [comment]
@brandwaffle I've updated the PR #1689 to bring it up to date with develop, and improved the handling of post type inputs in the search form.

@Rahmon I think the issue with that approach is that searches for products aren't necessarily coming only from WooCommerce pages. For example, it's common for shops to have a product search form in the header that only searches the shop, and there's no guarantee that WooCommerce pages don't also have a blog search form or similar. The approach in #1689 handles both those cases.
