### ISSUE TITLE
Acceptance Test Coverage

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#1693]
We need acceptance test coverage via WP Acceptance for most of the functionality in the plugin. To start it would be great to add tests for the following:

- Protected Content feature
- Documents feature
- WooCommerce feature
- Related Content feature
- Users feature
- Facets feature

To learn how WP Acceptance work, start by [reading the docs](https://wpacceptance.readthedocs.io/en/latest/) and looking at the existing [WPA tests in ElasticPress](https://github.com/10up/ElasticPress/blob/develop/tests/wpa/BasicTest.php). It would be nice to break out each feature into it's own test file.

**Comment by ayebare** [comment]
Jumping onto this.

**Comment by ayebare** [comment]
Acceptance tests aren't working for me locally on a windows environment. Setting up in docker instead. Collaborating with Ashar to make sure I don't repeat any of the tests he's done already.

**Comment by jeffpaul** [comment]
Closing this in favor of #2375
