### ISSUE TITLE
How to use ep_retrieve_raw_response

### ISSUE THREAD

**Issue by photocurio** [10up/ElasticPress#1696]
**Describe your question**
I need to get the raw elasticsearch response.  The action ep_retrieve_raw_response sounds like what I need.  I am calling this action from my search.php, in cases where the search returns no results.  My question is: **_how do I get a return value from this action?_**

**Comment by mustafauysal** [comment]
Hi @photocurio,

You can use 
```
add_action( 'ep_retrieve_raw_response', function ( $response ) {
// ...
} );
```

and here are the details: http://10up.github.io/ElasticPress/ep_retrieve_raw_response.html

> I am calling this action from my search.php, in cases where the search returns no results. 

I don't think search.php is the correct place for adding an action. The hook is executed before than utilizing search.php. So, the functions.php would be more appropriate.
