### ISSUE TITLE
Method Not Allowed when indexing posts via wp-cli

### ISSUE THREAD

**Issue by jayhill90** [10up/ElasticPress#1704]
We recently upgraded to ElasticPress 3.4. Since then whenever I try to index my posts I'm receiving a Method Not Allowed error. Running ElasticSearch 7.4 and EP 3.4.  Unfortunately debug-bar and the EP add-on won't return any information around what might be happening. When I index in wp-adamin I just get a success: false message back from admin-ajax.php and a "Method Not Allowed" message when using WP-CLI.

When I downgrade to EP 3.3 some posts will index, however it eventually results in a cURL timeout error.

**Comment by brandwaffle** [comment]
@jayhill90 are you getting any info if you pass in the `--show-bulk-errors` flag?

**Comment by jayhill90** [comment]
No additional output is provided.

```
jay.hill@jay-hill  % wp elasticpress index --per-page=100 --show-bulk-errors
Indexing posts...
Error: Method Not Allowed
```

**Comment by jayhill90** [comment]
I was able to get things working again by downgrading to ElasticPress 3.3. EP 3.4 returns Method Not Allowed messages when trying to index posts.

**Comment by tlovett1** [comment]
Can you try 3.4 with the terms feature disabled?

**Comment by jayhill90** [comment]
Thanks @tlovett1 . Terms was already disabled. The only features I have enabled are related posts, post search, and custom results. I still get back that the method isn't allowed.

**Comment by oscarssanchez** [comment]
Hi @jayhill90 ,

Is this solved in the most recent version? If not please feel free to open a new ticket!
