### ISSUE TITLE
Categorized content on the Autosuggestion results

### ISSUE THREAD

**Issue by imokweb** [10up/ElasticPress#1710]
Hello there! 

I have a successful WordPress + EP and ES integration with a 3rd party ES hosting and an activated Autosuggest option on the EP plugin, this is working fine! http://prntscr.com/rjmote

I want to customize the Autosuggest results like showing Featured Images, and categorized the Custom Post Types on the search results like on this site: http://prntscr.com/rjmqak
- like: Pages, Events, Business Directories etc. 

Can you give me some instructions how is this possible? 

Thank you for your HELP!

**Comment by oscarssanchez** [comment]
Hi @imokweb ,

This would require you to custom code your own version of autosuggest, you could take the current autosuggest code:  https://github.com/10up/ElasticPress/blob/develop/assets/js/autosuggest.js as a base and change it to include the thumbnail, as well as add the categories in the response.

Hope this gives you some direction.
