### ISSUE TITLE
Custom post's and REST API

### ISSUE THREAD

**Issue by arhimed-me-account** [10up/ElasticPress#1711]
Hello there,
I have two questions:

1) I indexed all post's in WP, I have post and custom_post indexed but using debug bar as suggested i see on admin page that elasticpress repalces query's just on admin post page (where all post are listed) http://prntscr.com/rjpwj5 
but on admin page where are all custom_post listed i see that there is no no query replaced 
http://prntscr.com/rjpx3x

On what this depends? 

2) Can we replace query's that run over REST API like /wp-json/wp/v2/posts?per_page=10 with response from elasticpress?

Regards!

**Comment by dnikola** [comment]
Hello,

any replay regarding this questions?

**Comment by oscarssanchez** [comment]
Hi @dnikola , @arhimed-me-account ,

Can you please share more information about this? Are these custom post types hierarchical ? what features do you have activated? what is your current ElasticSearch and ElasticPress version ? I was able to search for orders and products just fine so any information you can give to reproduce this issue will help us a lot in order to troubleshoot. 

Regarding your other question, the query that is being run` /wp-json/wp/v2/posts?per_page=10` should already be using ElasticPress.

**Comment by dnikola** [comment]
Hi @oscarssanchez 

thanks for your kind replay!

Ok let we split this in two questions problems 
-----------------
1)  Custom post's problem
 
I am using elasticpress addon plugin for debug bar to debug query (hope that this is the beast way I  am using, if not please tell me for another tool) 
Here is a SS to see when i open post's page 
http://prntscr.com/ryc1v0
and custom posts page in wp-admin
http://prntscr.com/ryc2et

So this is are information regarding Elasticsearch 
ElasticPress plugin version: 3.4.1 
Elasticsearch version | 6.8.7
-----------------------------------------------------------

2) REST API Problem 

I tried to enable option from your plugin settings and log query's but noting show up there.
Also tried plugin https://github.com/petenelson/wp-rest-api-log
I see from this plugin log that query's like /wp-json/wp/v2/posts?per_page=10 are not served from elasticsearch and query's like wp-json/wp/v2/users/?per_page=100 also, but query's like wp-json/wp/v2/search?search=something are being served from elasticsearch  
Here is complete settings of ElasticPress plugin https://i.imgur.com/aGUzYVy.png


If you need any more info please let me know.
Thanks!

**Comment by dnikola** [comment]
Hello @oscarssanchez 

did you had time to check something regarding this problem? 

Thanks!

**Comment by oscarssanchez** [comment]
Hi @dnikola,

Sorry it has been a while, do you still have this problem with the latest version?

**Comment by dnikola** [comment]
Hi @oscarssanchez ,

yes while, almost year :)

I'll need to check, just tell me what should i need to test question 1 or question 2 from my initial question

**Comment by oscarssanchez** [comment]
Hi @dnikola ,

Actually if both are still happening it would be great to know! 
Thanks!

**Comment by dnikola** [comment]
> Hi @dnikola ,
> 
> Actually if both are still happening it would be great to know!
> Thanks!

I am afraid that situation is same :/ 
do you need any aditional info?

**Comment by oscarssanchez** [comment]
Hi @dnikola ,
Thanks, I was able to reproduce both things :)

@brandwaffle this seems correct, if you register a new post type and you check the custom post list page, the query is not run through ElasticPress. The REST API also does not integrate even if `s` is set like wp-json/wp/v2/posts?s=test&per_page=10

You would need to set the `ep_integrate` param to both scenarios to make them run with ElasticPress

**Comment by dnikola** [comment]
@oscarssanchez 

could you please be more clear about this

> You would need to set the ep_integrate param to both scenarios to make them run with ElasticPress

you mean using add_ action  ‘pre_get_posts’ i should use 'ep_integrate'   => true, so this will work?

Thanks!

**Comment by oscarssanchez** [comment]
Hi @dnikola ,

That's correct!

**Comment by dnikola** [comment]
> Hi @dnikola ,
> 
> That's correct!

ok,

i will check.

**Comment by felipeelia** [comment]
@oscarssanchez @dnikola just as a reminder, for REST API, it should be `wp-json/wp/v2/posts?search=test&per_page=10`, as [in the docs](https://developer.wordpress.org/rest-api/reference/posts/#arguments).

**Comment by oscarssanchez** [comment]
Can confirm the correct way is ?search for the REST API
