### ISSUE TITLE
Ingest Attachment Installed, but not registering in WP admin

### ISSUE THREAD

**Issue by gregkellerman** [10up/ElasticPress#1712]
We have a self-hosted version on AWS using the AWS Elastic Search service. It says ingest attachment is installed, but its saying it is not in the plugin.

ingest-attachment           7.4.2

Also, the link that it is suggesting to install the plugin is going to an unreleased (v8.0) version of the plugin, so its not install-able. 

https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html

Screenshot of plugin feedback:

![Annotation 2020-03-20 141831](https://user-images.githubusercontent.com/51826629/77198844-c54cf000-6ab5-11ea-81de-b6f88afd0990.jpg)

Thoughts?

**Comment by gregkellerman** [comment]
Just checking up on this as there has not been a response for 17 days. Can we get some feedback? Any solutions?

Thanks!

**Comment by steven-klein** [comment]
@gregkellerman I think this is a dupe.  There's a solution posted here: https://github.com/10up/ElasticPress/issues/1020
