### ISSUE TITLE
Add warning + confirmation for destructive WP-CLI commands

### ISSUE THREAD

**Issue by nickdaugherty** [10up/ElasticPress#1713]
**Is your enhancement related to a problem? Please describe.**

When performing destructive CLI commands, such as `wp elasticpress delete-index` or `wp elasticpress index --setup`, there is no warning + confirmation step, so dropping indexes is very easy to do. On large indexes that takes a long time to re-index, this can be a huge problem.

**Describe the solution you'd like**
 
Any destructive WP-CLI command has a warning that indicates what it will do internally along with a confirmation step.

**Describe alternatives you've considered**

#YOLO

**Additional context**

Re-indexing a site with 10k posts after an accidental index deletion only takes a few minutes. Re-indexing a site with 1 million posts will take hours.

**Comment by Rahmon** [comment]
Hi @nickdaugherty .

This is a good feature. I'll add it to a future release.
