### ISSUE TITLE
Show Manage Search Fields & Weighting on Multisites

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#1715]
**Is your enhancement related to a problem? Please describe.**

On WordPress Multisite the Settings for Manage Search Fields & Weighting are only accessible for each site if you now the URL: `/wp-admin/admin.php?page=elasticpress-weighting`

There is no menu entry on each site.

**Describe the solution you'd like**

There is a Menu _Custom Search Results_ I would suggest renaming it to ElasticPress an add there a Submenu for _Manage Search Fields & Weighting_

**Additional context**
I use ElasticPress networkwide

**Comment by lebz** [comment]
The current network search settings aren't applied to the sites settings. is there a way to make sure network search settings are applied on all sites?

**Comment by felipeelia** [comment]
closing this in favor of #3383
