### ISSUE TITLE
Load scripts & styles only when they are really necessary

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#1716]
**Is your enhancement related to a problem? Please describe.**

For Facets, you load scripts & styles with the `wp_enqueue_script` and `wp_enqueue_style` functions. If Facets are activated they will load on every single pageload. Even when there is now active Facet Widget: https://github.com/10up/ElasticPress/blob/master/includes/classes/Feature/Facets/Facets.php#L162

**Describe the solution you'd like**

Way better would be to use the `wp_register_script` / `wp_register_style` functions: https://developer.wordpress.org/reference/functions/wp_register_script/ and call `wp_enqueue_script` and `wp_enqueue_style` only when the script & style is really necessary.

After registering the style/script with all parameters like handle, path, dependencies... all you need for enqueue is the handle. 

I would suggest to call `wp_enqueue_script` and `wp_enqueue_style` when the Widget gets rendered in https://github.com/10up/ElasticPress/blob/master/includes/classes/Feature/Facets/Widget.php#L275

Its even fine to call the enqueue function multiple times. 

**Additional context**
I wrote an article about this topic in german: https://go-around.de/blog/assets-optimiert-laden/ 
Here is one article in english: https://kinsta.com/blog/wp-enqueue-scripts/

**Comment by goaround** [comment]
I created a pull request for the necessary changes: https://github.com/10up/ElasticPress/pull/1717

**Comment by oscarssanchez** [comment]
Closing as #1717 is merged
