### ISSUE TITLE
Querying with both "cat" and "tag" parameters is only passing the "cat" parameter.

### ISSUE THREAD

**Issue by petenelson** [10up/ElasticPress#1718]
**Describe the bug**
When running the following query
```
$query = new \WP_Query(
	[
		'cat' => 123,
		'tag' => 'post-tag',
	]
);
```
the formatted args for Elasticsearch do not include the `post-tag` tag.

**Steps to Reproduce**
Discovered this will working on unit tests for the indexable post class.

**Expected behavior**
Formatted ES args should contain the post_tag taxonomy.

**Additional context**
This appears to be a bug in the switch statement here https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L719
I'll be submitting a PR to address this.

**Comment by petenelson** [comment]
I believe this should also be updated to `term_id` https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L731

**Comment by tlovett1** [comment]
@felipeelia is confirming this is working.

**Comment by tlovett1** [comment]
@felipeelia does this work?

**Comment by dinhtungdu** [comment]
Tested with the latest commit from `develop`, look like the issue has been fixed. both tag and cat are included in the formatted args.
```
                {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "terms.category.term_id": [
                                        "123"
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.post_tag.slug": [
                                        "post-tag"
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.post_tag.slug": [
                                        "post-tag"
                                    ]
                                }
                            }
                        ]
                    }
                },
```
