### ISSUE TITLE
Set timeout & disable fallback

### ISSUE THREAD

**Issue by mabezdek** [10up/ElasticPress#1719]
Hi there,
I have two questions.

1) Is possible to limit the connection timeout? We have currently problems when the app communicates with ElasticSearch and we need to limit the time waiting for response. We are getting the error message like this: Failed to connect to xxxx port 443: Connection timed out, but the request blocks the app maybe for 3-4s and we want to limit the wait time to max 1s. Is it possible?

2) Can we disable the fallback of this timeout, so disable search in MySQL and return empty result? When is ElasticSearch down and doesn't responses, our MySQL is extremely loaded by querying fulltext search.

Thank you.

**Comment by oscarssanchez** [comment]
Hi @mabezdek ,

You are looking to set a timeout when searching, did I get that right?

**Comment by oscarssanchez** [comment]
Hi @mabezdek ,

We are closing this now as we have not heard back from you. If the issue is not solved please feel free to open a new issue.
