### ISSUE TITLE
[illegal_argument_exception] Invalid stemmer class specified: Arabic

### ISSUE THREAD

**Issue by alifazeli** [10up/ElasticPress#1721]
**Describe your question**

Hi
When i index my posts through wp cli, i get this error

```
[illegal_argument_exception] Invalid stemmer class specified: Arabic
- 1708 (Post):
[illegal_argument_exception] Invalid stemmer class specified: Arabic
- 1707 (Post):
[illegal_argument_exception] Invalid stemmer class specified: Arabic
- 1706 (Post):
[illegal_argument_exception] Invalid stemmer class specified: Arabic
- 703 (Post):
[illegal_argument_exception] Invalid stemmer class specified: Arabic
- 701 (Post):
[illegal_argument_exception] Invalid stemmer class specified: Arabic

Number of posts indexed: 0
Error: Number of post index errors: 302118
Adding post mapping...

```

My wordpress language is arabic.

**Comment by tlovett1** [comment]
@moraleida can you take a look?

**Comment by moraleida** [comment]
@tlovett1 can you assign this to me, please?

**Comment by tlovett1** [comment]
@alifazeli  can you see if #1756  fixes your problem?

**Comment by alifazeli** [comment]
Hi @tlovett1 
What should I do?
Just update elasticpress and run index again? or should i change some files before?

**Comment by alifazeli** [comment]
I replaced dashboard.php with new file and It's work. tnx

Processed 305550/307947...
Processed 305900/307947...
Processed 306250/307947...
Processed 306600/307947...
Processed 306950/307947...
Processed 307300/307947...
Processed 307650/307947...
Processed 307947/307947...
Number of posts indexed: 307947
Total time elapsed: 7٬236.912
Success: Done!
Adding post mapping...
