### ISSUE TITLE
Weighting engine not working with Woocommerce search

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#1722]
**Describe the bug**

It looks like the Weighting feature doesn't work properly when doing a product search. As a result, the weighting configuration gets ignored. The reason for this seems to be that when doing a Woocommerce search, `search_fields` get set: 
https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/WooCommerce/WooCommerce.php#L351

Which is why later, this logic will be true and no weighting will get applied: 
https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Weighting.php#L514 

If this logic is removed form the code, weighting is applied successfully. However, some of the default fields set from the feature get lost: `_sku`, `terms.category.name` and `terms.post_tag.name`. 

**Steps to Reproduce**

1.- Activate Woocommerce feature
2.- Add some weighting to the product post type
3.- Do a search with `post_type product` set
4.- With debug bar, see no weighting has been applied

**Expected behavior**
Weigthing should get applied based on weighting settings

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version:   WordPress 5.2
 

 - Plugins and version:  Elasticpress 3.4
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by tlovett1** [comment]
@moraleida can you take a look?

**Comment by felipeelia** [comment]
As I have a recent background with this, I can work on it.

**Comment by felipeelia** [comment]
As we've merged #1801 to fix this one, I'm closing it now.
