### ISSUE TITLE
Search by post id and other filters in Wordpress admin list page are not working.

### ISSUE THREAD

**Issue by appasahebs** [10up/ElasticPress#1723]
Hello,

I have enabled elasticpress in my wordpress website. I am facing problem with Wordpress admin while filter by categories and other filters in post listing page. Also search by post id is not working. Its not matching exact post id.

Am I missing something here?

Thanks

**Comment by oscarssanchez** [comment]
Hi @appasahebs ,

Can you confirm protected content is activated? 

Without it, admin search will not work.

Kind regards,

**Comment by appasahebs** [comment]
> Can you confirm protected content is activated?

Yes protected content is activated.

**Comment by oscarssanchez** [comment]
Thanks @appasahebs ,

Can you please install the elasticpress debug bar:

https://es.wordpress.org/plugins/debug-bar-elasticpress/

And paste the json output for both `query args` and `query result`?
