### ISSUE TITLE
WooCommerce Product Category Case Sensitive

### ISSUE THREAD

**Issue by thachphamw2** [10up/ElasticPress#1724]
Currently we're running ElasticPress on our website, everything is fine, but for the query on Product Category page.

With ElasticPress enabled, the query on Product Category will return 0 products, while deactivated, it will show the product as usual!

**Screenshots**

Here's my Sync settings and weight settings.

![screenshot-zoovibe com-2020 04 05-15_30_00](https://user-images.githubusercontent.com/60785659/78470295-8758f880-7752-11ea-9489-f6221b6b60c6.png)
![screenshot-zoovibe com-2020 04 05-15_31_33](https://user-images.githubusercontent.com/60785659/78470310-a3f53080-7752-11ea-81ca-4b7964bb5cd4.png)

I do not use EP for the other post type, just product only.

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by tlovett1** [comment]
@moraleida can you look?

**Comment by moraleida** [comment]
@tlovett1 can you assign this to me, please?

**Comment by thachphamw2** [comment]
Thank you @moraleida , if you need more information, please let me know, I will provide more.

**Comment by moraleida** [comment]
@thachphamw2 I can't seem to reproduce this issue on WP 5.4 and EP 3.4.1. I'm able to reindex and reach category pages such as /product/clothing or /product/tshirts and see results coming from Elasticsearch.

Do you have any other query customizations that might be interfering with this one?
