### ISSUE TITLE
Query metas in ep_post_sync_args

### ISSUE THREAD

**Issue by puntope** [10up/ElasticPress#1730]
First, thanks all you guys for the work in this community project, is great.
**Describe your question**

I did a hook in `ep_post_sync_args` with a setup in order to have some extra meta.

It's like `$args['meta']['is_sale_product'] = true;` or `$args['meta']['is_sale_product'] = false;` depending on some chekings... basically if the product has sale_price.

Then in the query I want to filter with that meta but looks like it doesn't work, so, probably I'm doing something wrong.

My query is:

```
$params = [
                    'index' => $index_name,
                    'type' => 'post',
                    '_source' => [
                        'post_title',
                    ],
                    'from' => 0,
                    'size' => 3000,
                    'body' => [
                    'query' => [
                        'term' => ['meta.is_sale_product' => true]
                    ]
                ]
 ];


$result = $client->search($params);

```

Thanks!!!!

**Comment by oscarssanchez** [comment]
Hi @puntope,

From what I read I can suggest the following:

* First check if your meta is indeed indexed by looking at your post mappings: http://yourelasticendpoint/_mappings
* Is there a reason to not use a `WP_Query` object to perform this search? For example:

```
new WP_Query( array(
    's'          => 'search phrase',
    'meta_query' => array(
        array(
            'key'   => 'key_name',
            'value' => 'meta value',
            'compare' => '=',
        ),
    ),
) );
```

**Comment by puntope** [comment]
Hello @oscarssanchez thanks for your answer, 

First check if your meta is indeed indexed by looking at your post mappings: http://yourelasticendpoint/_mappings

The metas are there. It's also ok for me to use `_sale_price` default property.

Is there a reason not to use a WP_Query object to perform this search? For example:

Well...  is a legacy project I got recently, so, not sure, the old developer says that he did it to reduce the load on WP. Is that correct? What do you think?

Gracias Oscar

**Comment by oscarssanchez** [comment]
Hi @puntope ,

If you do use a WP_Query object, your search will be done through elasticsearch if you pass the special parameter `ep_integrate => true` . Can you give this a shot and check if this solves your issue?

**Comment by puntope** [comment]
Hello @oscarssanchez sorry for my late response

The mappings are there "_sale_price":{"properties":{"boolean":{"type":"boolean"},

The query using WP_Query doesn't work for me since that means to change all the legacy code of the application to this new way.

What I need is to know how to query the metas using the dsl.

Pseudo Example: 

'body' => ['query' => ['term' => ['meta._sale_price', '>',0]]

I cannot find any documentation about this.
