### ISSUE TITLE
Not correct generating elastic queries for taxonomies

### ISSUE THREAD

**Issue by renakdup** [10up/ElasticPress#1736]
**Describe the bug**
For Custom Taxonomies elasticpress is generating not correct query.

**Steps to Reproduce**
If we want use Custom Taxonomy for our query, we fill $args for wp_query and we get next generated query for elastic:
```
{
  "from": 0,
  "size": 40,
  "query": {
    "match_all": {
      "boost": 1
    }
  },
  "post_filter": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": [
              {
                "terms": {
                  "terms.cutom_tax_name.id": [
                    11111
                  ]
                }
              }
            ]
          }
        },

        {
          "terms": {
            "post_type.raw": [
              "post"
            ]
          }
        },
        {
          "term": {
            "post_status": "publish"
          }
        }
      ]
    }
  }
}
```
And elastic by this query not found some posts, because code formatting terms  `terrms.cutom_tax_name.id` has error. We need use `term_id` instead `id`, because in elastic we field stored under the name `term_id`

**Expected behavior**

**Screenshots**

**Environment information**
 - Browser and version: 
 - WordPress version:  5.3.2
- ElasticPress version 3.4.1
   </details>

**Additional context**

**Comment by renakdup** [comment]
I made pull request with this fix, but I dont understand why linter show errors in other files which I not changed.

https://github.com/10up/ElasticPress/pull/1737

**Comment by felipeelia** [comment]
Hi @renakdup ,

As stated in #1737, per WP Docs, fields should never be `id` but rather `term_id`, `name`, `slug` or `term_taxonomy_id`. See more in https://developer.wordpress.org/reference/classes/wp_query/#taxonomy-parameters

I'm closing this one now but feel free to open a new issue if you find any other possible enhancement. Thanks!
