### ISSUE TITLE
Error: Number of post index errors:

### ISSUE THREAD

**Issue by kevin25** [10up/ElasticPress#1739]
**Describe your question**

Every index got the error like this:

<img width="346" alt="Screen Shot 2020-04-16 at 16 47 19" src="https://user-images.githubusercontent.com/2909982/79443749-7470de80-8004-11ea-82a1-e033e9baaa3e.png">

I tried to disabled all plugins except for WooCommerce plugin. I switched the theme back to the default but still no luck.

I got the warning:

**It looks like one or more of your indices are running on a single node. While this won't prevent you from using ElasticPress, depending on your site's specific needs this can represent a performance issue. Please check the Index Health page where you can check the health of all of your indices.**

> {
    "Versions:": {
        "WordPress": "5.2.3",
        "ElasticPress": "3.4.1",
        "Elasticsearch": "N\/A",
        "WooCommerce": "3.9.3"
    },
    "Active Features": [
        "search",
        "related_posts",
        "woocommerce",
        "facets",
        "searchordering"
    ],
    "Active Plugins": [
        {
            "WC requires at least": "",
            "WC tested up to": "",
            "Woo": "",
            "Name": "Debug Bar ElasticPress",
            "PluginURI": "http:\/\/wordpress.org\/plugins\/debug-bar-elasticpress",
            "Version": "1.4",
            "Description": "Extends the debug bar plugin for ElasticPress queries.",
            "Author": "10up",
            "AuthorURI": "http:\/\/10up.com",
            "TextDomain": "debug-bar-elasticpress",
            "DomainPath": "",
            "Network": false,
            "Title": "Debug Bar ElasticPress",
            "AuthorName": "10up"
        },
        {
            "WC requires at least": "",
            "WC tested up to": "",
            "Woo": "",
            "Name": "Debug Bar",
            "PluginURI": "https:\/\/wordpress.org\/plugins\/debug-bar\/",
            "Version": "1.0",
            "Description": "Adds a debug menu to the admin bar that shows query, cache, and other helpful debugging information.",
            "Author": "wordpressdotorg",
            "AuthorURI": "https:\/\/wordpress.org\/",
            "TextDomain": "debug-bar",
            "DomainPath": "",
            "Network": false,
            "Title": "Debug Bar",
            "AuthorName": "wordpressdotorg"
        },
        {
            "WC requires at least": "",
            "WC tested up to": "",
            "Woo": "",
            "Name": "ElasticPress",
            "PluginURI": "",
            "Version": "3.4.1",
            "Description": "A fast and flexible search and query engine for WordPress.",
            "Author": "10up",
            "AuthorURI": "http:\/\/10up.com",
            "TextDomain": "elasticpress",
            "DomainPath": "\/lang\/",
            "Network": false,
            "Title": "ElasticPress",
            "AuthorName": "10up"
        },
        {
            "WC requires at least": "",
            "WC tested up to": "",
            "Woo": "",
            "Name": "EP Troubleshoot",
            "PluginURI": "",
            "Version": "0.0.1",
            "Description": "Troubleshoot ElasticPress issues.",
            "Author": "Allan Collins",
            "AuthorURI": "http:\/\/10up.com\/",
            "TextDomain": "ep-troubleshoot-master",
            "DomainPath": "",
            "Network": false,
            "Title": "EP Troubleshoot",
            "AuthorName": "Allan Collins"
        },
        {
            "WC requires at least": "",
            "WC tested up to": "",
            "Woo": "",
            "Name": "WooCommerce",
            "PluginURI": "https:\/\/woocommerce.com\/",
            "Version": "3.9.3",
            "Description": "An eCommerce toolkit that helps you sell anything. Beautifully.",
            "Author": "Automattic",
            "AuthorURI": "https:\/\/woocommerce.com",
            "TextDomain": "woocommerce",
            "DomainPath": "\/i18n\/languages\/",
            "Network": false,
            "Title": "WooCommerce",
            "AuthorName": "Automattic"
        }
    ],
    "Indexable Post Types": "N\/A",
    "Indexable Post Status": "N\/A",
    "Cluster Status": "N\/A"
}

**Comment by brandwaffle** [comment]
@kevin25 can you add the `--show-bulk-errors` flag to your CLI command let us know what results you see?

**Comment by kevin25** [comment]
> @kevin25 can you add the `--show-bulk-errors` flag to your CLI command let us know what results you see?

Thank you. I got this error.

[illegal_argument_exception] Limit of total fields [5000] in index [Test-post-1] has been exceeded
- 49445 (Post):

**Comment by kevin25** [comment]
It seems i'm not a lone https://github.com/10up/ElasticPress/issues/1735

**Comment by oscarssanchez** [comment]
Hi @kevin25 ,

My guess from past issues folks have raised is that you have too many post meta keys to map on Elasticsearch, see: https://github.com/10up/ElasticPress/issues/1263 or https://github.com/10up/ElasticPress/issues/1267

If you can confirm this, my suggestion would be to first clean up your database as much as you can from unused post meta If you keep getting the same issue, manually selecting which post meta keys to include would be the next step. In the case you need more than 5000+ fields, you could even raise this number via a filter, but I do not recommend this.

**Comment by kevin25** [comment]
> Hi @kevin25 ,
> 
> My guess from past issues folks have raised is that you have too many post meta keys to map on Elasticsearch, see: #1263 or #1267
> 
> If you can confirm this, my suggestion would be to first clean up your database as much as you can from unused post meta. If you keep getting the same issue, manually selecting which post meta keys to include would be the next step. In the case you need more than 5000+ fields, you could even raise this number via a filter, but I do not recommend this.
> 
> Please let us know how it goes.

Thank you. How can I clean the database? I've never work on this site before. 

Also how to do this:

manually selecting which post meta keys to include would be the next step.

**Comment by oscarssanchez** [comment]
Hi @kevin25 ,

Unfortunately I don't know your codebase and needs of your site as well, so I don't have an exact answer, reply here would be my suggestion:  https://github.com/10up/ElasticPress/issues/1263#issuecomment-482386162

**Comment by kevin25** [comment]
This hasn't been fixed yet. Is there any fixes for this isuse?

**Comment by oscarssanchez** [comment]
Hi @kevin25 , 

Did you have a chance to try the suggestion ? Can you please tell us how it went?

Thanks!
