### ISSUE TITLE
Duplicate non-blocking requests

### ISSUE THREAD

**Issue by adiloztaser** [10up/ElasticPress#1740]
**Describe the bug**
When the user changes the max number of times to attempt failed remote requests with the filter `ep_max_remote_request_tries`,  ElasticPress tries to make non-blocking requests repeatedly because if the request is non-blocking, `wp_remote_request` returns an empty string as a result and empty string is not a valid response.

I think there are two options for solving this problem:
1. find a way to find out that the non-blocking request returns a real error
2. make sure non-blocking requests are not repeat

**Steps to Reproduce**
1. Return a max limit more than 1 with filter `ep_max_remote_request_tries`
2. Add any debug logic into the `Elasticsearch->remote_requst()`. I added failures count to options table `update_option('es_error_count', $failures );` 
3. Update a published post as a draft.
4. See the option value

**Comment by felipeelia** [comment]
Hi @adiloztaser ,
I've tried to replicate this issue but I couldn't. Do you mind sharing with us the details of your environment? WordPress, ElasticPress, ElasticSearch versions, and which web server (Apache, Nginx, or some other) on which version would be helpful.
Thanks!

**Comment by adiloztaser** [comment]
Hi @felipeelia,

I am using ElasticPress 3.4.1 with Elasticsearch 6.3.2 on WordPress 5.3.2

For more detail here is my test patch:

```
diff --git a/wp-content/plugins/elasticpress/includes/classes/Elasticsearch.php b/wp-content/plugins/elasticpress/includes/classes/Elasticsearch.php
index 48a437d4e..5da765bc6 100644
--- a/wp-content/plugins/elasticpress/includes/classes/Elasticsearch.php
+++ b/wp-content/plugins/elasticpress/includes/classes/Elasticsearch.php
@@ -929,6 +929,13 @@ class Elasticsearch {
 			if ( false === $request || is_wp_error( $request ) || ! $is_valid_res ) {
 				$failures++;
 
+				$log = array(
+					'count' => $failures,
+					'args' => $args
+				);
+
+				update_option( 'es_error', json_encode( $log ) );
+
 				/**
 				 * Filter max number of times to attempt remote requests
 				 *
@@ -938,7 +945,7 @@ class Elasticsearch {
 				 * @param  {args} $args Request arguments
 				 * @return {int} New number of tries
 				 */
-				if ( $failures >= apply_filters( 'ep_max_remote_request_tries', 1, $path, $args ) ) {
+				if ( $failures >= apply_filters( 'ep_max_remote_request_tries', 7, $path, $args ) ) {
 					break;
 				}
 			} else {
```

After trigger some non-blocking action (such as saving post which is not published) here is the option result:

`{"count":7,"args":{"method":"DELETE","timeout":15,"blocking":false,"headers":{"Content-Type":"application\/json"}}}`

I hope this will help you.

**Comment by felipeelia** [comment]
Thanks, @adiloztaser. I've opened a PR with a possible fix for this. As non-blocking requests will only fail later in the timeline, I don't think we could do anything other than just make sure non-blocking requests are not repeated.
It would be great if you could give the PR a try and let us know if that works for you too.

**Comment by adiloztaser** [comment]
The PR works as I expected. Thanks for your work. :+1:  @felipeelia
