### ISSUE TITLE
connect to elastic cloud

### ISSUE THREAD

**Issue by israeldahan** [10up/ElasticPress#1742]
if i want to connect elasticpress to elastic cloud? how to connect? where i put username and password?

**Comment by oscarssanchez** [comment]
Hi @israeldahan ,

If you happen to have authentication enabled, you may define `define( 'ES_SHIELD', 'username:password' );` as documentation indicates: http://10up.github.io/ElasticPress/tutorial-security.html

**Comment by oscarssanchez** [comment]
Closing as it looks like this got solved.
