### ISSUE TITLE
Highest compatible versionnumber of elasticsearch for 2.8.2 ?

### ISSUE THREAD

**Issue by david-we** [10up/ElasticPress#1744]
We want to upgrade to elasticsearch 6.8 or higher, because our elasticpress is modified we can not update it to 3.x.x yet. What is the highest version number that works with 2.8.2 ?

__Current ElasticPress version?__
6,3
__Current Elasticsearch version?__
2.8.2
__Where do you host your Elasticsearch server?__
on premise

**Comment by oscarssanchez** [comment]
Hi @david-we ,

It looks like 6.3 would be the Max supported version.
