### ISSUE TITLE
Facets-URL Parameter can lead to DDoS from the Google Bot 

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#1750]
**Describe the bug**

The Facets-Feature can lead to a lot of request from the Google Bot. It adds URL parameter like `filter_category=business-class&filter_post_tag=star-alliance` and with a large set of custom terms there are near to infinite combinations possible.

The Google Bot follows every link and the Facets Widget generates a new link for every option. The search page has not been indexed by Google but it still follows every link.

Here is a very small except from my `access.log`:

<pre>
66.249.64.72 - - [23/Apr/2020:14:57:31 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_period=march,december,august&filter_origins=amsterdam&filter_category=business-class&filter_post_tag=star-alliance,aegean-milesbonus&filter_destinations=asia,southeast-asia,singapore,chennai HTTP/1.1" 200 18837 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.72 - - [23/Apr/2020:14:57:31 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_destinations=dar-es-salaam,asia,japan,nur-sultan,bishkek,nanjing&filter_period=winter-holidays,september HTTP/1.1" 200 18483 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.90 - - [23/Apr/2020:14:57:31 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_origins=netherlands&filter_post_tag=lufthansa&filter_category=flights&filter_period=april,may,december HTTP/1.1" 200 19236 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.68 - - [23/Apr/2020:14:57:31 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_origins=netherlands,amsterdam&filter_post_tag=lufthansa,lot&filter_destinations=asia,almaty,osaka,bishkek HTTP/1.1" 200 18587 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.65 - - [23/Apr/2020:14:57:32 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_origins=netherlands&filter_period=august,september,june,february&filter_destinations=africa,asia,beijing,tokyo,bangkok,nairobi HTTP/1.1" 200 18926 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.70 - - [23/Apr/2020:14:57:32 +0000] "GET /search/alitalia/?s=alitalia&filter_post_tag=aegean-milesbonus,flying-blue,krisflyer,milesmore,milessmiles,skywards,skymiles,united-mileageplus HTTP/1.1" 200 18048 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.76 - - [23/Apr/2020:14:57:32 +0000] "GET /search/alitalia/?s=alitalia&filter_post_tag=executive-club,flying-blue,finnair-plus,milesmore,asiana-club,aadvantage,skywards,eurobonus&filter_category=milespoints HTTP/1.1" 200 18097 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.90 - - [23/Apr/2020:14:57:32 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_origins=netherlands&filter_category=flights&filter_post_tag=united-mileageplus&filter_period=may&filter_destinations=asia,malaysia,iran,singapore,delhi HTTP/1.1" 200 18774 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.64.80 - - [23/Apr/2020:14:57:32 +0000] "GET /search/Lufthansa/?s=Lufthansa&filter_origins=netherlands,london,rotterdam,london-gatwick-lgw&filter_destinations=usa,seattle,kauai-island,miami,orlando&filter_period=november&filter_post_tag=star-alliance,air-canada HTTP/1.1" 200 18395 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
</pre>

The Google Bot has crawled over 200.000 pages per day on my site:

![grafik](https://user-images.githubusercontent.com/5927337/80120128-dc866e00-858a-11ea-91e0-f2064cfd352f.png)

I've added `Disallow: /search/` to my robots.txt but the Facets Widget can used on every site. 

A possible solution would be to add a rel="nofollow" to every option-link but I'am not sure if this is would prevent the Google Bot from following these links. They still can be crawled.

**Comment by oscarssanchez** [comment]
Closing per #1764
