### ISSUE TITLE
Adding filter amount in search filters

### ISSUE THREAD

**Issue by azzyadrac** [10up/ElasticPress#1751]
Hi,

I am trying to get the number of products shown in the filter widgets in the side of WooCommerce when searching.
I have successfully got the amount to show before a filter is applied.
e.g. to calculate the amount there is going to be for a brand before the filter is applied.

The issue I am having is when the filter is applied more products are shown, so the number of products shown with the amount on the filter never match up.

I have tried using post filters with both should and must:

$formatted_args['post_filter']['bool']['should'] = $filters;

Also tried with should match:
$formatted_args['post_filter']['bool'][ 'minimum_should_match' ] = 1;

I have also tried range filters for the prices but still no luck.

any help would be grateful.

Environment information

    Browser and version:
    WordPress version: 5.4
    ElasticPress version 3.4.1

**Comment by oscarssanchez** [comment]
Hi @azzyadrac ,

When you say widget filters, do you mean the facet widget?

If so, I remember a PR that was submitted before 3.0 got released. Perhaps it is a good place to look: https://github.com/10up/ElasticPress/pull/1195

**Comment by azzyadrac** [comment]
Hi @oscarssanchez ,
Thank you for your response.
When I said "Widget filters", I meant the widgets from WooCommerce that I customised.
This was due to the facets not meeting my requirements.

I shall have a look at the PR suggested and see I can use any of the code to assist me.

Again, thank you :)

**Comment by oscarssanchez** [comment]
Closing for now, please feel free to reopen or create a new issue if you find some issues!

**Comment by shmaltz** [comment]
> When I said "Widget filters", I meant the widgets from WooCommerce that I customised.

@azzyadrac  Would you be willing to share the modified woo filters?
