### ISSUE TITLE
Missing data in elasticsearch when syncing.

### ISSUE THREAD

**Issue by emilpriverrc** [10up/ElasticPress#1753]
__Have you searched for similar issues before submitting this one? yes

__Is this a bug, question or feature request? Bug/Question

__Describe the issue you encountered:
We are using Elasticpress to sync data between our local elasticsearch server which is used to search for posts, cars and so on. We miss about 33% of the content. We have 760 posts which should be synced but only 500 is synced. Have tested resync, clear all data on elastic and then sync.

I have been looking for some kind of a sync log to see an error but have not found any, there for I asking for help :D  

__Current WordPress version? 5.3.2

__Current ElasticPress version? 3.4.1 

__Current Elasticsearch version? 7.5.0

__Where do you host your Elasticsearch server? AWS which the whole project is hosted at.

__What ElasticPress features do you have currently active? We have not added anymore then a elasticpress debug plugin

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)? ACF

Would love to get some guidance to solve the problem. Does it exists any log and so on ?

Dear,
Emil

**Comment by oscarssanchez** [comment]
Hi @emilpriverrc ,

This command should provide output when a post fails to index:

wp elasticpress index --show-bulk-errors

**Comment by emilpriverrc** [comment]
hello @oscarssanchez,

Thank you, I did run the command and found the error :D.

Been going through both docs and github project to find something that could make the "total fields" higher. Anyway edit the limit to something higher?

**Comment by oscarssanchez** [comment]
Yes @emilpriverrc 

If you are getting the total fields limit error, my first suggestion is to try to clean up your database from unused meta and exclude any non essential meta, see #1263 or #1267.

If that's not a possibility, the filter to raise the total fields would be `ep_total_field_limit`

Hope this helps

**Comment by emilpriverrc** [comment]
@oscarssanchez Thank you for the help Oscar! We solved the problem :D
