### ISSUE TITLE
News posts not indexed

### ISSUE THREAD

**Issue by paoloburzacca** [10up/ElasticPress#1755]
In my huge website after initial syncing (with WP-CLI) I have 140678 documents indexed, but when new posts are added these are not indexed anymore and my documents count remain always the same. Do I need to reindex manually each night? Do I need to attach to Wordpress save_post action ?

**Comment by oscarssanchez** [comment]
Hi @paoloburzacca ,

Each time you update or save a post it should index/reindex the document. Can you please provide more details about your current site?

**Comment by paoloburzacca** [comment]
I debugged plugin code and I can see that new posts are added to the queue if they are publish, but it's like the queue is not processed

**Comment by oscarssanchez** [comment]
Hi @paoloburzacca ,

Can you provide more details about your site? Unfortunately without more information it is almost impossible to know what could be going wrong.

**Comment by paoloburzacca** [comment]
Hi, I have resolved with a new server and a new Elastic Search installation. The old server had only 2 Gb Ram and somtimes ES crashed, now with 8Gb Ram it's all ok! Thank you

**Comment by oscarssanchez** [comment]
Good to know ! Will close this one then.
