### ISSUE TITLE
WP_IMPORTING check in SyncManager too early

### ISSUE THREAD

**Issue by barryceelen** [10up/ElasticPress#1757]
The SyncManager setup() methods [contain a check if WP_IMPORTING is true](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/SyncManager.php#L30), and do not add their hooks if WP_IMPORTING is true.

It seems this check is performed on the `init` hook, which can be too early: other functionality may define WP_IMPORTING on a later hook.

To improve Elasticpress responding to WP_IMPORTING and prevent the need for other functionality to define WP_IMPORTING on an earlier hook, we could add the conditional to each callback function in the SyncManager classes separately in stead of in the `setup()` function.

An alternative to looking at WP_IMPORTING could be adding a specific filter that prevents indexing.

**Comment by tlovett1** [comment]
Seems like a method should be called in that class that checks that constant. Can you draft a PR?
