### ISSUE TITLE
Media Library search not working with EP and Protected Content indexation enabled.

### ISSUE THREAD

**Issue by mwidmann** [10up/ElasticPress#1758]
**Describe the bug**
I updated to version 3.4.1 recently and users reported that searching for items in the media library didn't return any results anymore.

I investigated and found out that even though attachments are not part of the indexed `post_type`s, ElasticPress reaches out to the elasticsearch server with a query nevertheless. This returns an empty result and thus the search results page is empty.

**Steps to Reproduce**
1. Setup a clean installation of WordPress 5.4.1, leaving all settings as default
1. Install ElasticPress plugin, activate and setup to point to a Elasticsearch server (in our case version 5.6.4)
1. Enable the feature `Protected Content` in ElasticPress Settings.
1. Upload a picture in the media library
1. Index your content
1. In the media library search for the name of that single image you have.

**Expected behavior**
- the images corresponding to the name should be displayed.

**Screenshots**
with ElasticPress enabled:
![image](https://user-images.githubusercontent.com/251322/80725128-f4b63a00-8b02-11ea-9190-e8415bbd70a1.png)

with ElasticPress disabled:
![image](https://user-images.githubusercontent.com/251322/80725222-11527200-8b03-11ea-8af5-07b6ae2e687d.png)

** Environment **

`
### wp-core ###

version: 5.4.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Users\mwidmann\Local Sites\estest\app\public
wordpress_size: loading...
uploads_path: C:\Users\mwidmann\Local Sites\estest\app\public/wp-content/uploads
uploads_size: loading...
themes_path: C:\Users\mwidmann\Local Sites\estest\app\public/wp-content/themes
themes_size: loading...
plugins_path: C:\Users\mwidmann\Local Sites\estest\app\public/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.2
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: C:\Users\mwidmann\Local Sites\estest\app\public/wp-content/themes/twentytwenty

### wp-themes-inactive (2) ###

Twenty Nineteen: version: 1.5, author: the WordPress team
Twenty Seventeen: version: 2.3, author: the WordPress team

### wp-plugins-active (1) ###

ElasticPress: version: 3.4.1, author: 10up

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 i586
httpd_software: nginx/1.16.0
php_version: 7.3.5
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_size: 300M
php_post_max_size: 1000M
curl_version: 7.64.0 OpenSSL/1.1.1b
suhosin: false
imagick_availability: false

### wp-database ###

extension: mysqli
server_version: 5.7.28
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\Users\mwidmann\Local Sites\estest\app\public/wp-content
WP_PLUGIN_DIR: C:\Users\mwidmann\Local Sites\estest\app\public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by mwidmann** [comment]
So I invetigated this a bit further. Seems that the issue results from this line of code called with the `ep_elasticpress_enabled` hook: 

https://github.com/10up/ElasticPress/blob/91f1135e90506a5758f67a28f2273bb598f29bb3/includes/classes/Feature/Search/Search.php#L288 

If `is_search()` is set on `WP_Query` and a keyword is searched for than query integration does get enabled regardless of the post_type being queried.

As a workaround I registerd a hook to `ep_elasticpress_enabled` as well, with priority 11 to ensure it's run after the `ep_elasticpress_enabled` call in Search.php.

```php
add_filter( 'ep_elasticpress_enabled', function ( $enabled, $query ) {
	if ( 'attachment' === $query->query_vars['post_type'] ) {
		return false;
	}
	return $enabled;
}, 11, 2 );
```

a potential fix in Search could be to add the following after 

https://github.com/10up/ElasticPress/blob/91f1135e90506a5758f67a28f2273bb598f29bb3/includes/classes/Feature/Search/Search.php#L289
 
```php
if ( ! empty( $query->query_vars['post_type'] && 'any' !== $query->query_vars['post_type'] ) ) {
	$enabled = in_array( $query->query_vars['post_type'], $this->get_searchable_post_types(), true );
}
```

This checks if the current `post_type` queried is one of the searchable post types and sets `$enabled` to whether it's in the array or not.

**Comment by oscarssanchez** [comment]
Hi @mwidmann 

Thanks for your report, the only way that I could trigger a similar behavior is if I set all queries to be elasticpress enabled:

```
add_action( 'pre_get_posts', 'test' );

function test( $query ) {
    $query->set( 'ep_integrate', true );
    return $query;
}
```

I made a quick video hoping that you can spot if I did not understand your instructions to reproduce: 
https://youtu.be/wnExJBapYK0

Can you please let me know if I missed something ? 

Thanks!

**Comment by mwidmann** [comment]
Hi @oscarssanchez , thank you for the response. This is very strange, but I'll try providing a step-by-step instruction to reproduce the issue. 

The be 100% sure nothing in my regular setup interferes with the installation, I used a sandboxed new installation in [Local](https://localwp.com/). I selected PHP Version 7.3.5 and MySQL 5.7.28. I like Local because it's very easy go test something out in a sandbox.

Usually I run my installations on Docker with a shared wp-content repository between my sites, that's why I needed a clean installation.

![image](https://user-images.githubusercontent.com/251322/81263957-e6a37480-9040-11ea-99d5-f233f150ad00.png)

Once the site is up:
- log in to eptest2.local/wp-admin/
- go to Plugins -> Add New
- Install ElasticPress and activate the plugin
- Go to ElasticPress -> Settings and enter the settings to connect to your ES servers
- Click index your content on the initial setup page
- Go to ElasticPress->ElasticPress and enable Protected Content
  - this will trigger a re-indexation, but that's fine for our 3 pieces of content
- Go to Media -> Library and upload a picture

Try to search for this image from the grid view and it will return the image you searched for. This does the searching through the REST API, I guess.

![image](https://user-images.githubusercontent.com/251322/81264840-6978ff00-9042-11ea-8c8e-a8b6ede5cba0.png)

**BUT** try to switch to the list view and the image cannot be found as ES integrates in the search.

![image](https://user-images.githubusercontent.com/251322/81264890-78f84800-9042-11ea-9b96-2ba3cf0756e6.png)

**Comment by oscarssanchez** [comment]
Hi @mwidmann , I think the list view was what i was missing. I can reproduce this with local and will try out on our normal environments. Thanks for the detailed steps!

**Comment by oscarssanchez** [comment]
Hi @mwidmann ,

Can you check it https://github.com/10up/ElasticPress/pull/1770 solves the issue for you? 

Thanks!

**Comment by mwidmann** [comment]
@oscarssanchez thanks for the PR. It would fix the issue, but open up another one if the user decides to include attachments to the indexed post types in order to make the query faster in the backend, by adding them through the `ep_indexable_post_types` filter.

```php
add_filter( 'ep_indexable_post_types', function ( $post_types ) {
	$post_types[] = 'attachment';
	return $post_types;
} );
```

The originating discussion and my try to fix it pointed out that I need to index attachments to ES, because the DB query would timeout on wp_posts with ~2m entries. Our ES installation does not have the Ingest Attachment plugin and no way of enabling it. So I can't enable the document indexation feature.

This means, this change would kick me back to the beginning. 

I think the safer choice would be to look if the searched for `post_type` is included in the list of indexed post_types as I suggested in https://github.com/10up/ElasticPress/issues/1758#issuecomment-621939573
