### ISSUE TITLE
Documentation to update about Feature API

### ISSUE THREAD

**Issue by gregoriopellegrino** [10up/ElasticPress#1761]
The documentation contains these guidelines for defining an _ep_register_feature_:

http://10up.github.io/ElasticPress/tutorial-feature-api.html

But this warns generates a PHP warning:

`Notice: ep_register_feature is deprecated since version 3.0! Use Feature registration API instead.`

I found this blog post saying that the Feature recording mode has changed:

https://www.elasticpress.io/blog/2019/05/elasticpress-3-0-released/

**Comment by tlovett1** [comment]
That's correct. That needs to be updated.
