### ISSUE TITLE
How to remove_action 'shutdown' for index_sync_queue?

### ISSUE THREAD

**Issue by Slamik** [10up/ElasticPress#1763]
**Describe your question**

I've noticed that index_sync_queue fired every time while my "ajax postview counter" increments value using update_post_meta.

I've tried `remove_action ('shutdown', ['ElasticPress \ Indexable \ Post \ SyncManager', 'index_sync_queue']);` but with no luck.

Is there any way to remove this action correctly?

Thank you in advance!

**Comment by oscarssanchez** [comment]
Hi @Slamik ,

I thought this was correct however a colleague pointed out the right solution for this:

`remove_action('shutdown', array( \ElasticPress\Indexables::factory()->get( 'post' )->sync_manager, 'index_sync_queue' ) );`

Hope this helps

**Comment by Slamik** [comment]
Hi @oscarssanchez ,

Thank you! Works like a charm!
