### ISSUE TITLE
CLI: wp elasticpress list-features shows wrong active/inactive status

### ISSUE THREAD

**Issue by nickdaugherty** [10up/ElasticPress#1765]
**Describe the bug**

When you run the `list-features` command, it doesn't call `is_active()` on the `Feature` object, which bypasses the `ep_feature_active` filter, causing incorrect active/inactive status to be shown.

**Steps to Reproduce**

1. Add a filter like this: `add_filter( 'ep_feature_active', '__return_false' )`
1. Run `wp elasticpress list-features`
1. Notice that previously active Features are still shown as active (despite the filter)
1. Visit the EP dashboard in WP Admin - see that all Features show as disabled

**Expected behavior**

The `ep_feature_active` filter is evaluated in the `list-features` command.

**Comment by tlovett1** [comment]
Thanks for the report! Would love to see a PR.

**Comment by felipeelia** [comment]
Working on it
