### ISSUE TITLE
Woocommerce and missing products with EP

### ISSUE THREAD

**Issue by flaversaver21** [10up/ElasticPress#1772]
**Describe the bug**
ElasticPress 3.2.6 and up from what I can tell have a bug where the sync completes, but products are flat out missing on the front end search AND the backend search. If I update the product (simply click the update button) it will suddenly show up in both searches. If I resync, the issue reoccurs. 

**Steps to Reproduce**
See above. 

**Expected behavior**
See above

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: Latest at 5.4.1. Same with Woocommerce at 4.1

 
 - <details><summary>Site Health Info:</summary>
   `
### wp-core ###

version: 5.4
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%postname%/
https_status: true
user_registration: 1
default_comment_status: open
multisite: false
user_count: 12268
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/toiletpartitions/www
wordpress_size: loading...
uploads_path: /home/toiletpartitions/www/wp-content/uploads
uploads_size: loading...
themes_path: /home/toiletpartitions/www/wp-content/themes
themes_size: loading...
plugins_path: /home/toiletpartitions/www/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Toilet Partitions 1.9.9.3 (toiletpartitions-child)
version: 1.9.9.3
author: Versa
author_website: http://versawebdev.com
parent_theme: Toilet Partitions (toiletpartitions)
theme_features: menus, post-thumbnails, title-tag, automatic-feed-links, post-formats, woocommerce, widgets
theme_path: /home/toiletpartitions/www/wp-content/themes/toiletpartitions-child

### wp-parent-theme ###

name: Toilet Partitions (toiletpartitions)
version: 1.9.9.3
author: Versa
author_website: http://versawebdev.com
theme_path: /home/toiletpartitions/www/wp-content/themes/toiletpartitions

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.2, author: the WordPress team

### wp-mu-plugins (2) ###

0-pj-loader.php: author: (undefined), version: (undefined)
elasticsearch.php: author: (undefined), version: (undefined)

### wp-plugins-active (46) ###

404 Solution: version: 2.22.6, author: Aaron J (latest version: 2.22.9)
Abandoned Cart Lite for WooCommerce: version: 5.7.2, author: Tyche Softwares
Advanced Custom Fields: version: 5.8.9, author: Elliot Condon (latest version: 5.8.11)
AfterShip - WooCommerce Tracking: version: 1.9.18, author: AfterShip
Breadcrumb NavXT: version: 6.4.0, author: John Havlik
Classic Editor: version: 1.5, author: WordPress Contributors
Clickcease - Click Fraud Protection: version: 1.0, author: ClickCease
Contact Form 7: version: 5.1.7, author: Takayuki Miyoshi
Contact Form CFDB7: version: 1.2.4.8, author: Arshid
Disable Comments: version: 1.10.2, author: Samir Shah
Documents Tab WooCommerce: version: 1.0, author: Adrian Dimitrov <dimitrov.adrian@gmail.com>
Duplicate Post: version: 3.2.4, author: Enrico Battocchi
ElasticPress: version: 3.2.6, author: 10up (latest version: 3.4.1)
Email Cart for WooCommerce: version: 1.4.6, author: Rymera Web Co
EmailOctopus: version: 2.1.6, author: EmailOctopus
Export & Import Templates for WPBakery Page Builder: version: 1.0.0, author: Tomiup
Flexible Shipping UPS: version: 1.8.6, author: WP Desk (latest version: 1.8.8)
Loginizer: version: 1.4.3, author: Raj Kothari
Manage Notification E-mails: version: 1.5.0, author: Virgial Berveling (latest version: 1.5.1)
Print Invoice & Delivery Notes for WooCommerce: version: 4.5.5, author: Tyche Softwares
Product Feed PRO for WooCommerce: version: 7.9.8, author: AdTribes.io (latest version: 8.2.0)
PW WooCommerce Bulk Edit Pro: version: 2.190, author: Pimwick, LLC (latest version: 2.205)
Rails Sign In: author: (undefined), version: (undefined)
Really Simple SSL: version: 3.3.1, author: Rogier Lankhorst, Mark Wolters (latest version: 3.3.2)
Redux Framework: version: 3.6.18, author: Team Redux
User Switching: version: 1.5.4, author: John Blackbourn & contributors
WC Multiple Email Recipients: version: 1.2.5, author: Con Schneider
WooCommerce: version: 3.5.4, author: Automattic (latest version: 4.1.0)
WooCommerce AvaTax: version: 1.9.5, author: SkyVerge
WooCommerce Blocks: version: 2.5.15, author: Automattic
WooCommerce Bulk Order Form: version: 3.3.3, author: Ewout Fernhout, Varun Sridharan, Jeremiah Prummer (latest version: 3.3.4)
WooCommerce Email Test: version: 1.10, author: RaiserWeb
WooCommerce Enable Free Shipping on a Per Product Basis: version: 1.0.2, author: Patrick Rauland & eugenf
WooCommerce Google Analytics Integration: version: 1.4.20, author: WooCommerce (latest version: 1.4.21)
WooCommerce Paya Gateway: version: 3.2.2, author: Andrew Benbow
WooCommerce Sequential Order Numbers Pro: version: 1.12.2, author: SkyVerge
WooCommerce Upsells Shortcode: version: 1.0.0, author: SkyVerge
Woo Discount Rules: version: 1.9.6, author: Flycart Technologies LLP (latest version: 1.9.8)
Woodstock Extensions: version: 1.9.5, author: Temash Design
Woo EDD Email Domain Blacklist: version: 2.0.0, author: Md. Kowsar Hossain
WooSidebars: version: 1.4.5, author: WooCommerce
WPBakery Page Builder: version: 5.6, author: Michael M - WPBakery.com
WPC Custom Related Products for WooCommerce: version: 1.3.2, author: WPCodelibrary
YITH WooCommerce Compare: version: 2.3.20, author: YITH (latest version: 2.3.21)
YITH WooCommerce Wishlist: version: 3.0.9, author: YITH (latest version: 3.0.10)
Yoast SEO: version: 13.5, author: Team Yoast (latest version: 14.1)

### wp-plugins-inactive (8) ###

Debug Bar: version: 1.0, author: wordpressdotorg
Debug Bar Extender: version: 0.5, author: Thorsten Ott, Automattic
Debug Bar Remote Requests: version: 0.1.2, author: Matthew Boynes
Error Log Monitor: version: 1.6.9, author: Janis Elsts
Preview E-mails for WooCommerce: version: 1.6.4, author: Digamber Pradhan
Query Monitor: version: 3.5.2, author: John Blackbourn (latest version: 3.6.0)
Store Toolkit for WooCommerce: version: 2.2, author: Visser Labs
WooCommerce Edit Order Numbers: version: 1.1.1, author: UltimateWoo

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2017-05-23 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 16 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 16 GB
	imagick::RESOURCETYPE_MEMORY: 8 GB
	imagick::RESOURCETYPE_THREAD: 4
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.18.16-x86_64-linode118 x86_64
httpd_software: nginx/1.13.1
php_version: 7.2.5 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 32M
php_post_max_size: 32M
curl_version: 7.38.0 OpenSSL/1.0.1t
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.18
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/toiletpartitions/www/wp-content
WP_PLUGIN_DIR: /home/toiletpartitions/www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`
   </details>

**Additional context**

**Comment by brandwaffle** [comment]
@flaversaver21 can you reindex via WP-CLI with the following command and share the results?

`wp elasticpress index --setup --show-bulk-errors`

**Comment by flaversaver21** [comment]
> @flaversaver21 can you reindex via WP-CLI with the following command and share the results?
> 
> `wp elasticpress index --setup --show-bulk-errors`

$ wp elasticpress index --setup --show-bulk-errors
Success: Mapping sent
Success: Mapping sent
Indexing posts...
Processed 350/37110...
Processed 700/37110...
Processed 1050/37110...
Processed 1400/37110...
Processed 1750/37110...
Processed 2100/37110...
Processed 2450/37110...
Processed 2800/37110...
Processed 3150/37110...
Processed 3500/37110...
Processed 3850/37110...
Processed 4200/37110...
Processed 4550/37110...
Processed 4900/37110...
Processed 5250/37110...
Processed 5600/37110...
Processed 5950/37110...
Processed 6300/37110...
Processed 6650/37110...
Processed 7000/37110...
Processed 7350/37110...
Processed 7700/37110...
Processed 8050/37110...
Processed 8400/37110...
Processed 8750/37110...
Processed 9100/37110...
Processed 9450/37110...
Processed 9800/37110...
Processed 10150/37110...
Processed 10500/37110...
Processed 10850/37110...
Processed 11200/37110...
Processed 11550/37110...
Processed 11900/37110...
Processed 12250/37110...
Processed 12600/37110...
Processed 12950/37110...
Processed 13300/37110...
Processed 13650/37110...
Processed 14000/37110...
Processed 14350/37110...
Processed 14700/37110...
Processed 15050/37110...
Processed 15400/37110...
Processed 15750/37110...
Processed 16100/37110...
Processed 16450/37110...
Processed 16800/37110...
Processed 17150/37110...
Processed 17500/37110...
Processed 17850/37110...
Processed 18200/37110...
Processed 18550/37110...
Processed 18900/37110...
Processed 19250/37110...
Processed 19600/37110...
Processed 19950/37110...
Processed 20300/37110...
Processed 20650/37110...
Processed 21000/37110...
Processed 21350/37110...
Processed 21700/37110...
Processed 22050/37110...
Processed 22400/37110...
Processed 22750/37110...
Processed 23100/37110...
Processed 23450/37110...
Processed 23800/37110...
Processed 24150/37110...
Processed 24500/37110...
Processed 24850/37110...
Processed 25200/37110...
Processed 25550/37110...
Processed 25900/37110...
Processed 26250/37110...
Processed 26600/37110...
Processed 26950/37110...
Processed 27300/37110...
Processed 27650/37110...
Processed 28000/37110...
Processed 28350/37110...
Processed 28700/37110...
Processed 29050/37110...
Processed 29400/37110...
Processed 29750/37110...
Processed 30100/37110...
Processed 30450/37110...
Processed 30800/37110...
Processed 31150/37110...
Processed 31500/37110...
Processed 31850/37110...
Processed 32200/37110...
Processed 32550/37110...
Processed 32900/37110...
Processed 33250/37110...
Processed 33600/37110...
Processed 33950/37110...
Processed 34300/37110...
Processed 34650/37110...
Processed 35000/37110...
Processed 35350/37110...
Processed 35700/37110...
Processed 36050/37110...
Processed 36400/37110...
Processed 36750/37110...
Processed 37100/37110...
Processed 37110/37110...
Number of posts indexed: 37110
Indexing users...
Processed 350/12335...
Processed 700/12335...
Processed 1050/12335...
Processed 1400/12335...
Processed 1750/12335...
Processed 2100/12335...
Processed 2450/12335...
Processed 2800/12335...
Processed 3150/12335...
Processed 3500/12335...
Processed 3850/12335...
Processed 4200/12335...
Processed 4550/12335...
Processed 4900/12335...
Processed 5250/12335...
Processed 5600/12335...
Processed 5950/12335...
Processed 6300/12335...
Processed 6650/12335...
Processed 7000/12335...
Processed 7350/12335...
Processed 7700/12335...
Processed 8050/12335...
Processed 8400/12335...
Processed 8750/12335...
Processed 9100/12335...
Processed 9450/12335...
Processed 9800/12335...
Processed 10150/12335...
Processed 10500/12335...
Processed 10850/12335...
Processed 11200/12335...
Processed 11550/12335...
Processed 11900/12335...
Processed 12250/12335...
Processed 12335/12335...
Number of users indexed: 12335
Total time elapsed: 267.403
Success: Done!
Adding post mapping...
Adding user mapping...

**Comment by brandwaffle** [comment]
@flaversaver21 are those last two lines appearing after the `Success: Done!` line? If so, it seems that maybe something is re-triggering the application of the post mapping after the sync is completed. I'm not 100% sure it's related, but it could be why the post needs to be manually updated (this would trigger another individual object sync _after_ the mapping gets changed).

**Comment by flaversaver21** [comment]
Yes they are appearing after. I take it that was unexpected. 
The minute I do a resync from the GUI, those exact same products go missing again. I don't have this issue on our other 99% identical woo site. That site is running same version of EL and EP. Plugins are largely the same too, however not all plugins are updated yet.

**Comment by brandwaffle** [comment]
@flaversaver21 can you try re-running the CLI-index command from earlier but this time Ctrl+C out of the process mid-index? Then try searching for a few products--if it seems like you have some, but an incomplete set, that would support the idea that maybe that mapping is happening after the fact for some reason.

**Comment by brandwaffle** [comment]
@flaversaver21 the GUI sync will automatically disable EP while it's running. When it completes, are the products also gone? I'm looking through code so knowing whether this happens in both CLI and GUI context is definitely helpful.

**Comment by flaversaver21** [comment]
I'll have to test this after hours (5pm pst) . Right now it's busy sales time.

But to your comment, yes when EP is syncing (via GUI) all works normally from what I can tell. Then when the sync completes the products in question are blackholed. I can find them by using a bulk product editor which then allows me to go in and update the product to get it to reappear.

**Comment by flaversaver21** [comment]
Stopped the sync mid process from the CLI and the search seems to work just fine. 

However, I can't run a full sync as it recognizes a sync still in process. Not sure how to get out of this.

**Comment by brandwaffle** [comment]
@flaversaver21 after that partial sync are the results still appearing (at least the ones that got synced)? I want to confirm EP is still taking over that search. It _should_ once the transient is deleted, but confirming via the total number of results being smaller (but not empty) or via the Debug Bar ElasticPress plugin would be ideal.

If we get that squared away, the next step is we can debug when the mapping function runs to figure out why it's happening 2x.

**Comment by flaversaver21** [comment]
Even with it interrupted the sync appeared totally normal. I couldn't find any issues.

**Comment by brandwaffle** [comment]
This line has a filter that you can use for debugging: https://github.com/10up/ElasticPress/blob/2bf808d9da3978c1ef35ff60ce9b3bb87e64cc5f/includes/classes/Command.php#L262

I would just log out whenever that fires to confirm it's happening again at the end. If it is, then I'd put in a check somewhere around here to see that put_mapping_helper is firing each time https://github.com/10up/ElasticPress/blob/2bf808d9da3978c1ef35ff60ce9b3bb87e64cc5f/includes/classes/Command.php#L184

Finally, if that happens at the end of the indexing, I'd debug_backtrace on that same line 184 to see what's calling those methods the second time around.

**Comment by sandrodz** [comment]
I experience the same issue with missing products from categories. Sometimes resyncing with elasticpress helps, sometimes not.

**Comment by sandrodz** [comment]
@flaversaver21 have you resolved your issue with missing products?

**Comment by oscarssanchez** [comment]
Hi @sandrodz ,

Any chance you can share a db dump of it so we can further investigate?
