### ISSUE TITLE
Price filter with search parameters

### ISSUE THREAD

**Issue by torava** [10up/ElasticPress#1776]
I use ElasticPress with WooCommerce. I would like to allow choosing a price range while doing a search. If I search with some terms and then choose max price from WooCommerce's price range widget then search terms will be ignored and only the price range is respected. Could ElasticPress support filtering by a price range along with search terms?

**Comment by oscarssanchez** [comment]
Hi @torava ,
This seems to work from my testing with the latest version of Elasticpress. If you still have problems feel free to open a new issue.
