### ISSUE TITLE
MySQL Load still high

### ISSUE THREAD

**Issue by charinduedirisuriya** [10up/ElasticPress#1777]
I'm doubting that even though elasticpress is setup, my load to the MySQL server has not reduced and I feel like elasticpress is not been used by my quries.

The average response time for a get request like, `/wp-json/wc/v3/products?sku=650260368`
on woo-commerce was around 2 seconds, and under heavy load it takes up to 30 seconds, this is why I choose to install elasticpress. 

I installed the debug tools for elasticpress and the number of queries are shown as 0.
I did some load tests and I did see a very minor slight spike in cpu on my elastic instance during the load test and Wordpress is the only one communicating with it. Even so, how can I assure that elastic press is been used properly and why is my database load still high even doing a load test on a simple GET request like this for woocommerce.

I doubled checked and woocommerce has been enabled on elasticpress end.

How can I reduced my MySQL load to improve response time?
MySQL server : 1cpu, 2GB
Elastic Instance: 1cpu, 2GB.

Load test specs 100 RPS on GET `/wp-json/wc/v3/products?sku=650260368`

Thanks.

**Comment by oscarssanchez** [comment]
Hi @charinduedirisuriya ,

Could you please give us more details ? It is not really clear for me how are you using elasticpress. If you could give us the steps you are following after installing elasticpress, that would be great.

Thanks!

**Comment by charinduedirisuriya** [comment]
After adding the plugin I added the host and enabled woocommerce, and indexed all the data.
![sinppo33](https://user-images.githubusercontent.com/33041881/82163467-094b4e00-98c9-11ea-82b1-5a0e2e91508f.PNG)
![sniop22](https://user-images.githubusercontent.com/33041881/82163469-0a7c7b00-98c9-11ea-9d9f-0bb5dd5b9645.PNG)
![sniop23](https://user-images.githubusercontent.com/33041881/82163470-0b151180-98c9-11ea-8ef7-df5686ad97d5.PNG)
![sniop21](https://user-images.githubusercontent.com/33041881/82163471-0b151180-98c9-11ea-8086-2bc821ac1508.PNG)

Would this help?

**Comment by oscarssanchez** [comment]
Thank you @charinduedirisuriya ,

Can you make a request to your elasticsearch endpoint on the _search endpoint i.e.  https://elasticsearchserver/yourendpoint-post-1/post/_search like the following: 

```
{
    "query": {
        "match_all": {}
    }
}
```

And report what gets returned?

Also, can you confirm the indexing process was successful ? Ideally, if you have access to WP CLI you can run this command:

`wp elasticsearch index --setup --show-bulk-errors`

If all is good, the number on indexed posts as well as no error should come up.

Thanks!

**Comment by charinduedirisuriya** [comment]
{"took":379,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}

Error: 'elasticsearch' is not a registered wp command. See 'wp help' for available commands.

**Comment by oscarssanchez** [comment]
hI @charinduedirisuriya ,

Apologies, the correct command is : `wp elasticpress index --setup --show-bulk-errors`

**Comment by charinduedirisuriya** [comment]
Hi, @oscarssanchez sorry for the late reply,
this is the output I got.

Warning: Function pcntl_signal not available. Make sure to run `wp elasticpress clear-index` in case the process is killed.
Adding post mapping...
Success: Mapping sent
Adding term mapping...
Success: Mapping sent
Indexing posts...
Processed 7/7...
Number of posts indexed: 7
Indexing terms...
Processed 37/37...
Number of terms indexed: 37
Total time elapsed: 2.646
Success: Done!

**Comment by oscarssanchez** [comment]
Thanks @charinduedirisuriya !

It seems that only 7 items got indexed. This might be obvious but can you confirm there's only 7 products/posts you have in your site?

**Comment by charinduedirisuriya** [comment]
@oscarssanchez yes, this is a test server and it only has 7 products.

**Comment by oscarssanchez** [comment]
Thanks @charinduedirisuriya ,

Can you do one sample query and report back the results from the elasticpress debug bar (both the sent JSON and response) ? 

For example: 
```

    $args = array(
        'ep_integrate' => true,
        'post_type'      => 'product',
        'posts_per_page' => 10,
    );

    $query = new WP_Query( $args );
```

**Comment by oscarssanchez** [comment]
Hi @charinduedirisuriya ,

As we have not heard back from you we are now closing this issue. If you still have problems please feel free to open a new one.
