### ISSUE TITLE
Does the ‘sites’ parameter allow negative int for exclusion?

### ISSUE THREAD

**Issue by laiconsulting** [10up/ElasticPress#1781]
Can I do
```
new WP_Query( array(
    's'     => 'search phrase',
    'sites' => array( -2, -3 ),
) );
```
to exclude site 2 and 3?

**Comment by laiconsulting** [comment]
A separate question, can one reindex a particular site, say site 10000, without reindexing those 9999 sites prior to that?

**Comment by oscarssanchez** [comment]
Hi @laiconsulting ,

I have not tried this but perhaps something like wp elasticpress index --setup --url=yoursite would work to only index a particular one ?

As for your original question, without having experience with this particular case i would say this is not integrated yet into elasticpress. Did you have a chance to try it ? It would be great to confirm it!

**Comment by laiconsulting** [comment]
I tried it, it didn't work.
So I guess this is rather a feature request.
I'd like to have everything indexed, but a flexible way to exclude search of certain subsites.

**Comment by oscarssanchez** [comment]
Thanks @laiconsulting , 

I will add the enhancement label to this. If you have a code solution for this in the meantime, please feel free to open a PR!
