### ISSUE TITLE
Elasticpress hangs on indexing.

### ISSUE THREAD

**Issue by laranea** [10up/ElasticPress#1783]
Hi all,

Testing EP on a staging WooCommerce with only a few products but indexing hangs...

[root@spookje webshop]# wp elasticpress index --show-bulk-errors --show-nobulk-errors --show-errors  --per-page=1 --setup
Adding post mapping...
Success: Mapping sent
Indexing posts...
Processed 1/41...
Processed 2/41...
Processed 3/41...
Processed 4/41...
Processed 5/41...
Processed 6/41...
Processed 7/41...
Processed 8/41...
Processed 9/41...
Processed 10/41...
Processed 11/41...
Processed 12/41...
Processed 13/41...
Processed 14/41...
Processed 15/41...
Processed 16/41...
Processed 17/41...
Processed 18/41...
Processed 19/41...
Processed 20/41...
Processed 21/41...
Processed 22/41...
Processed 23/41...
Processed 24/41...
Processed 25/41...
Error: cURL error 28: Operation timed out after 30000 milliseconds with 0 out of -1 bytes received
<p class="lead shortcode-error text-center">Sorry, no pages was found</p><p class="lead shortcode-error text-center">Sorry, no pages was found</p><p class="lead shortcode-error text-center">Sorry, no pages was found</p>

I checked the error log of ES Server, there was no error:
[2020-05-22T04:58:23,061][INFO ][o.e.c.m.MetaDataCreateIndexService] [node-1] [ghostlembreghtsgreenpivotbe-post-1] creating index, cause [api], templates [], shards [5]/[1], mappings [_doc]
[2020-05-22T04:58:25,033][INFO ][o.e.c.m.MetaDataMappingService] [node-1] [ghostlembreghtsgreenpivotbe-post-1/RbC735cLRp2Y-GcfLrUE3w] update_mapping [_doc]
[2020-05-22T04:58:26,115][INFO ][o.e.c.m.MetaDataMappingService] [node-1] [ghostlembreghtsgreenpivotbe-post-1/RbC735cLRp2Y-GcfLrUE3w] update_mapping [_doc]
[2020-05-22T04:58:29,853][INFO ][o.e.c.m.MetaDataMappingService] [node-1] [ghostlembreghtsgreenpivotbe-post-1/RbC735cLRp2Y-GcfLrUE3w] update_mapping [_doc]

I turned on PHP errors in WP, the error log was empty.

I did a WP optimize, to no avail.

[root@spookje webshop]# wp elasticpress stats
====== Stats for: ghostlembreghtsgreenpivotbe-post-1 ======
Documents:  25
Index Size: 824,84 KB
Index Size (including replicas): 824,84 KB
====== End Stats ======

[root@spookje webshop]# wp elasticpress status
====== Status ======
{
  "ghostlembreghtsgreenpivotbe-post-1" : {
    "shards" : [
      {
        "id" : 4,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1590116304065,
        "stop_time_in_millis" : 1590116304268,
        "total_time_in_millis" : 203,
        "source" : { },
        "target" : {
          "id" : "jIEdR4kMTOOkHU2UUoNmsQ",
          "host" : "192.168.0.121",
          "transport_address" : "192.168.0.121:9300",
          "ip" : "192.168.0.121",
          "name" : "node-1"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 149,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 41
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 1,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1590116303104,
        "stop_time_in_millis" : 1590116303703,
        "total_time_in_millis" : 598,
        "source" : { },
        "target" : {
          "id" : "jIEdR4kMTOOkHU2UUoNmsQ",
          "host" : "192.168.0.121",
          "transport_address" : "192.168.0.121:9300",
          "ip" : "192.168.0.121",
          "name" : "node-1"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 316,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 251
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 3,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1590116303135,
        "stop_time_in_millis" : 1590116303781,
        "total_time_in_millis" : 646,
        "source" : { },
        "target" : {
          "id" : "jIEdR4kMTOOkHU2UUoNmsQ",
          "host" : "192.168.0.121",
          "transport_address" : "192.168.0.121:9300",
          "ip" : "192.168.0.121",
          "name" : "node-1"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 422,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 201
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 2,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1590116303156,
        "stop_time_in_millis" : 1590116303833,
        "total_time_in_millis" : 676,
        "source" : { },
        "target" : {
          "id" : "jIEdR4kMTOOkHU2UUoNmsQ",
          "host" : "192.168.0.121",
          "transport_address" : "192.168.0.121:9300",
          "ip" : "192.168.0.121",
          "name" : "node-1"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 468,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 131
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 0,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1590116303232,
        "stop_time_in_millis" : 1590116303832,
        "total_time_in_millis" : 600,
        "source" : { },
        "target" : {
          "id" : "jIEdR4kMTOOkHU2UUoNmsQ",
          "host" : "192.168.0.121",
          "transport_address" : "192.168.0.121:9300",
          "ip" : "192.168.0.121",
          "name" : "node-1"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 401,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 131
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      }
    ]
  }
}

====== End Status ======

1 Node, so health yellow.

✔ /usr/local/etc/elasticsearch
05:23 $ curl -XGET http://localhost:9200/_cat/indices
yellow open ghostlembreghtsgreenpivotbe-post-1 uMXQcXnRSna_Hh2iWCO4Iw 5 1 12 0 558kb 558kb
✔ /usr/local/etc/elasticsearch
05:23 $ curl -XGET http://localhost:9200/_cat/health
1590117830 03:23:50 elasticsearch_kristof yellow 1 1 5 5 0 0 5 0 - 50.0%

Any idea or do you need more information?
Can another WP plugin be halting the index?

I have no idea how to fix this...

I deleted normal posts, then indexed on woocommerce only. It worked!

Then I enabled autosuggest and got this error:

[root@spookje wp-content]# wp elasticpress index --show-errors --allow-root --per-page=1 --setup
PHP Notice:  Constant WP_DEBUG already defined in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 77
Adding post mapping...
Success: Mapping sent
Indexing posts...
Processed 1/29...
Processed 2/29...
Processed 3/29...
Processed 4/29...
Processed 5/29...
Processed 6/29...
Processed 7/29...
Processed 8/29...
Processed 9/29...
Processed 10/29...
Processed 11/29...
Processed 12/29...
Processed 13/29...
Processed 14/29...
Processed 15/29...
Processed 16/29...
Processed 17/29...
Processed 18/29...
Processed 19/29...
Processed 20/29...
Processed 21/29...
Processed 22/29...
Processed 23/29...
Processed 24/29...
<p class="lead shortcode-error text-center">Sorry, no pages was found</p><p class="lead shortcode-error text-center">Sorry, no pages was found</p><p class="lead shortcode-error text-center">Sorry, no pages was found</p><div class="woocommerce">You can't do that

Before I go to production I really need to know what causes a corrupt post or WC product to fail syncing...

Thanks in advance.

**Comment by oscarssanchez** [comment]
Hi @laranea,

Per the first error you get, it would seem as if you have a timeout issue, however, the "Sorry, no pages was found" errors look weird to me. 

Can you search for this string inside your codebase, check if it is generated by a plugin, disable and reindex?

Can you also let us know if you have custom code, or how big your products are? 

Thanks!

**Comment by oscarssanchez** [comment]
Hi @laranea ,

As there was no response we are now closing this. If this issue is still persisting please feel free to open a new ticket and we can check it again!
