### ISSUE TITLE
Is it OK that total number of docs is different than posts that are being synced?

### ISSUE THREAD

**Issue by marcinkrzeminski** [10up/ElasticPress#1787]
**Describe your question**

When I run the sync button within the plugin it says Syncing posts 0/1201. Once that done I check the backend and is says docs count: 516. And this leads me to another question. When I try to search for some content that should be visible in the search results it's not there (the content is stored in an ACF flexible layout field). Is it related? Any suggestions on that?

**Comment by oscarssanchez** [comment]
Hi @marcinkrzeminski 

Numbers may differ as it includes all public post types and if document feature is enabled also your media assets.

We are happy to troubleshoot further if your posts are not getting indexed though, could you please open a support ticket on elasticpress.io ? This way we can give you a more personalized support.

Thanks!

**Comment by marcinkrzeminski** [comment]
Hi @oscarssanchez,

As per your request I just sent a support ticket on elasticpress.io.

Thanks
