### ISSUE TITLE
Search "E-mail" vs "Email"

### ISSUE THREAD

**Issue by sinusiks** [10up/ElasticPress#1791]
We have a post with title "Best E-mail clients for mobile phones"

- When searching for "E-mail" (without quotes) a lot of posts are found, none of them not even including word "mail" in title or content even though title has highest weight set.

- When searching for "Email" without dash, the correct post is found and also a first result.

ElasticPress is configured with default settings, except titles have highest weight set. If user searches for "E-mail" or "mobile e-email" or "mobile client" etc. I would want this post to be one of the first results. What can I do to fine-tune this kind of search?

**Comment by oscarssanchez** [comment]
Hi @sinusiks ,

I think you could test how things look to you by adjusting the fuzziness and also look into Elasticsearch synonyms for the specific Email vs E-mail issue. Perhaps this link can help: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html

**Comment by sinusiks** [comment]
Thanx but can you please tell me how to adjust fuzziness and synonyms? I use default Elasticpress with default Elasticsearch installation - can I solve both in the code or in the elasticsearch configuration? Because I can't find this anywhere through the module settings..

**Comment by oscarssanchez** [comment]
Hi @sinusiks ,

Yes you would need to add this through code. 

Here is a sample on how to set a synonym:

```
add_filter( 'ep_config_mapping', 'search_config_mapping' );

function search_config_mapping( $mapping ) {
// Ensure we have filters and is array.
if ( ! isset( $mapping['settings']['analysis']['filter'] ) || ! is_array( $mapping['settings']['analysis']['filter'] ) ) {
return $mapping;
}
// Ensure we have analyzers and is array.
if ( ! isset( $mapping['settings']['analysis']['analyzer']['default']['filter'] ) || ! is_array( $mapping['settings']['analysis']['analyzer']['default']['filter'] ) ) {
return $mapping;
}
// Define the custom filter.
$mapping['settings']['analysis']['filter']['our_synonym_filter'] = array(
'type' => 'synonym',
'lenient' => true,
'synonyms' => array( 'Look => See' ),
);
// Tell the analyzer to use our newly created filter.
$mapping['settings']['analysis']['analyzer']['default']['filter'] = array_merge( [ 'our_synonym_filter' ], $mapping['settings']['analysis']['analyzer']['default']['filter'] );
return $mapping;
}
```

If you want to add more complexity to this i recommend the following: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html

Hope this helps!

**Comment by oscarssanchez** [comment]
Hi @sinusiks ,

As we have not heard back from you we are now closing this issue. If you still have problems please feel free to open a new one.
