### ISSUE TITLE
Support for newer versions of ElasticSearch (7.7.1)

### ISSUE THREAD

**Issue by alexgarciab** [10up/ElasticPress#1795]
**Is your enhancement related to a problem? Please describe.**
Are there any plans to support newer versions of ElasticSearch, such as 7.7.1? We have it installed, and right now we can not use the plugin, because it only supports up to 7.5

**Describe the solution you'd like**
Add compatibility for newer versions of ElasticSearch, such as 7.7.1

**Comment by vasikgreif** [comment]
Just came across this - ElasticPress won't work on ES 7.7.x, or is it just not officially supported? Any possible issues with it?

**Comment by oscarssanchez** [comment]
Closing as 7.9 is latest supported.
