### ISSUE TITLE
Delete an attachment with the CLI does not tigger ES sync

### ISSUE THREAD

**Issue by photocurio** [10up/ElasticPress#1798]
The issue is the exact same as [WP-CLI Post Delete does not trigger es sync](https://github.com/10up/ElasticPress/issues/152), except I am deleting attachments not posts.

**Steps to Reproduce**
1. Delete an attachment with the CLI. The command is the same as for deleting a post: `wp post delete <id> --force`
2. Search for the attachment in the media library (its gone)
3. Search for the attachment with Elasticsearch (its still there)

**Expected behavior**
When I delete an attachment with the CLI, it should not be findable in search.

**Additional context**
It seems that issue 152 was resolved by hooking ES Sync to `delete_post`.  Maybe Sync can also hook to `delete_attachment`?
Also: when deleting attachments with the CLI, the --force flag must be used, because there is no trash status for attachments.

**Comment by photocurio** [comment]
P.S. can a sync be triggered from the CLI? I could just run a second command, as a workaround.

**Comment by photocurio** [comment]
I tried these:

-  adding `add_action( 'delete_attachment', array( $this, 'action_delete_post' ) );` to SyncManager.php in the elasticpress plugin, at line 42. This does not work.
- I also tried disabling the early return in action_delete_post, thinking maybe attachments were not in $indexable_post_types.  That did not work.

**Comment by photocurio** [comment]
I resolved this in my app by sending a `_delete_by_query` post request to ElasticSearch, right after deleting the attachment.  https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html.  It's not an optimal solution, but it will do.

**Comment by oscarssanchez** [comment]
Hey @photocurio ,

I did some testing here. Turns out this happens on all post types that are force deleted. I will take a look.

**Comment by oscarssanchez** [comment]
Hi @photocurio ,

I made PR https://github.com/10up/ElasticPress/pull/1814 to address this. Can you please give it a shot check if this solves the issue for you?

**Comment by photocurio** [comment]
OMG thank you @oscarssanchez for working on this.  I forgot all about it after I found a workaround.  But I'll test this fix.

**Comment by felipeelia** [comment]
Closing this one as https://github.com/10up/ElasticPress/pull/1968 was merged.
