### ISSUE TITLE
Autosuggest stop working if a DOM change (eg. ajax request) replaces the input box

### ISSUE THREAD

**Issue by gustavo-roganti** [10up/ElasticPress#1807]
I have a Search Form that on submit replaces itself with an updated version, via AJAX.

This has the side effect of replacing the <input type="search"> tag with a new one (same attributes).

This then breaks the Autosuggest: the new input tag doesn't have the event handlers attached to behave as an autosuggest field.

The code that attaches the events is not inside a function, nor is it exposed. If it was, I could call it after my DOM changes, and have the autosuggest enabled on the new tag.

**Comment by tlovett1** [comment]
@oscarssanchez please investigate.

**Comment by amesplant** [comment]
@gustavo-roganti I have recently joined the team here at 10up and am here to try to solve this issue. So just as a recap to make sure that I understand your issue:

You have a Search Form, that is replaced via AJAX once the form is submitted, with a page refresh. When you say that it has a side effect of replacing the tag with a new one, do you mean that the **input** tag is getting rewritten with a new one, and even though the new one has the same attributes, it breaks the Autosuggest?

**Comment by oscarssanchez** [comment]
Hi @gustavo-roganti , 

Have you tried with the most recent version of ElasticPress? please feel free to open a new issue if it is not resolved.
