### ISSUE TITLE
Facet Widget & 3-level deep hierarchical taxonomy

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#1810]
**Describe the bug**

We use the Facet to filter posts based on the custom hierarchical taxonomy Destination e.g.

```
- North America
- - USA
- - - New York
- - - California 
- - - - Los Angeles
- - - Florida
- - - - Miami
- - Canada
- - - Toronto
- - - Vancouver
- Europe
...
```

But in the Facet Widget with Order Terms By Term Name and Term Order Ascending it looks like this:

```
- Europe
- North America
- - Canada
- - - Toronto
- - - Vancouver
...
```

If I change the Term Order to Descending, it looks like this:

```
- North America
- - USA
- - - New York
- - - California 
- - - - Los Angeles
- - - Florida
- - - - Miami
- Europe
...
```

It seems like that only one 2ed level item is allowed. On the 3rd level, more than one Item is fine but not on the 2nd level.

**Steps to Reproduce**
1. Create Items for a hierarchical taxonomy e.g. Category with at least two terms on the 2ed level
2. Apply all the terms to a post
3. Create a Facet Widget for the taxonomy
4. See only one item at the 2ed level

**Expected behavior**

More than on term on the 2ed level

**Screenshots**

Ascending:
![grafik](https://user-images.githubusercontent.com/5927337/85122282-97975480-b226-11ea-9c8a-171154c3df85.png)

Descending:
![grafik](https://user-images.githubusercontent.com/5927337/85122311-a120bc80-b226-11ea-8e80-94367cafedbf.png)

**Environment information**
 - WordPress version: 5.4.2

**Comment by goaround** [comment]
I think the bug has its origin somewhere here: https://github.com/10up/ElasticPress/blob/master/includes/classes/Feature/Facets/Widget.php#L180 but it's quite hard for me to understand this part of the function

**Comment by itGuyFacethesound** [comment]
the bug is originated here : 
https://github.com/10up/ElasticPress/blob/develop/includes/utils.php#L427
($to_process = $term->children + $to_process;)
can be fixed changing the line to 
with 
					$to_process = [...$term->children,...$to_process ]; ( php 7.3, not suggested ) 
or 
					$to_process = merge_array($term->children,$to_process); ( should work everywhere)
