### ISSUE TITLE
"Search Fields & Weighting" Screen on Multisites

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#1811]
**Describe the bug**

Currently, when ElasticPress is Network Active, the "Search Fields & Weighting" submenu item is not displayed under the ElasticPress menu but it is still accessible opening the "Post Search" feature box. The link points to a screen under the subsite Dashboard with no CSS applied.

**Steps to Reproduce**
1. Create a new WordPress multisite installation
2. Network Activate ElasticPress
3. Visit the ElasticPress features screen (wp-admin/network/admin.php?page=elasticpress)
4. Open "Post Search" and click on "Advanced fields and weighting settings"

**Expected behavior**

The screen appearance should be the same it has on single-site installations.

**Screenshots**

![image](https://user-images.githubusercontent.com/184628/85168875-5ceee580-b241-11ea-9ce3-b81a02e3dc74.png)

![image](https://user-images.githubusercontent.com/184628/85168920-6d06c500-b241-11ea-91fd-505fc6650c10.png)

**Environment information**
 - WordPress version: 5.3.2
 - ElasticPress version: 3.4.2

**Comment by oscarssanchez** [comment]
Mmmmm after checking the bug my question is do we want to have this feature "accessible" on multisite installations as it is now? 

My thoughts are that each sub site should have its own weighting configuration. Some sub sites may even have their own custom post types for example and we want to make sure it just applies to those sub sites. Having a global weight settings looks troublesome for me. 

cc @brandwaffle @tlovett1 for discussion.

**Comment by tlovett1** [comment]
The page should not exist and the link should not be shown. Use `EP_IS_NETWORK` constant.
