### ISSUE TITLE
Meta queries after first meta query stripped from nested meta queries

### ISSUE THREAD

**Issue by christianc1** [10up/ElasticPress#1812]
**Describe the bug**
When you are nesting meta queries more than a single level deep, all but the first meta query is stripped out of the deeper queries.

Take for example:
````php
$meta_query = array(
    array(
        array(
            'key' => 'key1',
            'value' => 'on',
        ),
        array(
            'key' => 'key2'
            'value' => 'off'
        ),
        'relation' => 'AND'
    ),
    array(
        'key' => 'key3',
        'value' => 'red',
    ),
    'relation' => 'OR',
);
````
In this example, the meta query on `key2` get's stripped out because of https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable.php#L488

**Steps to Reproduce**

1. Nest multiple meta queries at a depth of 2.
2. Inspect EP request
3. `meta_query[0][1]` is missing.

**Expected behavior**
Meta queries should not disappear. 

**Screenshots**

**Environment information**
 - Device: Macbook Pro
 - OS: MacOS 10.14.6
 - WordPress version: 5.4.2
-  EP Version: 3.4.1

**Comment by christianc1** [comment]
Note, you can workaround this issue by ensuring that `relation` key is the first element in the array, but that's sort of luck.  Happy to submit a patch, but the code causing this issue looks like it's in there to handle another strange edge case.  Maybe we can discuss the original intent more @tlovett1.

**Comment by Jamiewarb** [comment]
Thank you @christianc1 this comment has saved me from more days of pulling my hair out
