### ISSUE TITLE
Widget ob_start/_get_clean visually in div but output is outside

### ISSUE THREAD

**Issue by VoroDk** [10up/ElasticPress#1816]
**Describe the bug**
In the Facets Widget, the terms is visually outputted within `ob_start();` and `$facet_html = ob_get_clean();` wrapped in a div with the class `terms`. The problem is the `$facet_html` is not echoed until after the div is closed, so the visual

```
<div class="terms">
    <input class="facet-search" type="search" ...> <!-- Potentially a search input -->
    <div class="inner">
        <div class="term ..."></div>
        <div class="term ..."></div>
        <div class="term ..."></div>
        <div class="term ..."></div>
    </div> <!-- .inner -->
</div> <!-- .terms -->
```

is actually outputted as:

```
<div class="terms">
    <input class="facet-search" type="search" ...> <!-- Potentially a search input -->
</div> <!-- .terms -->
<div class="inner">
    <div class="term ..."></div>
    <div class="term ..."></div>
    <div class="term ..."></div>
    <div class="term ..."></div>
</div> <!-- .inner -->
```

**Steps to Reproduce**

1. Create any term for any post type
2. Apply term to a post
3. Insert Facet widget with that term
4. See that .terms closes right after the .facet-search input, instead of wrapping the .inner div.

**Expected behavior**
Wrap .inner within .terms

**Screenshots**

**Environment information**
 - Device: MacBook]
 - OS: MacOS 10.15.4
 - Browser and version: Chrome 83.0.4103.106
 - WordPress version: 5.4.1

**Comment by tlovett1** [comment]
What ElasticPress version are you running?

**Comment by VoroDk** [comment]
@tlovett1 Version 3.4.2.

#1780 fixed a mismatch in opening and closing divs regarding `ob_start()` and `ob_get_clean()`.
The original bug actually made sure that the final output was correct, but semantically wrong.
This fix then made it semantically right, but because of the placement of `ob_get_clean()` and the actual echo of the output variable, it outputs outside the intended div.

**Comment by oscarssanchez** [comment]
Can confirm this. Will work on a fix.

**Comment by oscarssanchez** [comment]
Hi @VoroDk can you test #1834 ?
Thanks!

**Comment by VoroDk** [comment]
@oscarssanchez It works as intended in my end!
Thank you
