### ISSUE TITLE
Enabling Indexing of Users & Terms Maps Date/Time Fields as Strings

### ISSUE THREAD

**Issue by dmhendricks** [10up/ElasticPress#1817]
**Describe the bug**

If I activate indexing of Users and/or Terms, the schema for `post_date` and `post_date_gmt` is mapped as [text](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/text.html) rather than [date](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/date.html). This presents a bit of an inconvenience when I try to work with the data in Kibana because it doesn't let me filter posts by date/time, nor add either field as the default Time Filter (since it only allows Date types for this functionality, though perhaps there is a way to get around it that I'm not aware of).

**Steps to Reproduce**

1. `wp elasticpress activate-feature users` and/or `wp elasticpress activate-feature terms`
2. `wp elasticpress put-mapping` / `wp elasticpress index --setup`
3. When I view the data in Kibana, the `post_date` and `post_date_gmt` fields are now mapped as _text_ types (?).

**Expected behavior**

It would be nice if they were mapped as Date (as they are when indexing of Users and/or Terms is _disabled_) so that I may filter the data accordingly in Kibana, et al.

**Environment information**
- OS: Ubuntu 16.04 LTS (4 sites), Ubuntu 20.04+Docker latest (2 sites)
- PHP: 7.0.33 (4 sites), 7.4.7 (2 sites)
- ElasticPress: 3.4.2
- Elasticsearch/Kibana: 7.5.2 (official Docker images)
 - WordPress version: 5.4.2
 - <details><summary>Site Health Info:</summary>
   I have this disabled on all of my sites for security/user annoyance reasons, but can enable it and provide the output if required/relevant.
   </details>

**Additional context**

I had never enabled indexing of these before, but wanted to for speed, so I'm uncertain if it is a new thing or if it was always this way. It appears to be doing this on all of my sites (6 of them, each with different themes/plugins but all with the same versions noted above).

I currently have indexing of Users and Terms disabled on all of the sites because I rely on Kibana for working with data.

Thank you.

**Comment by brandwaffle** [comment]
@dmhendricks thanks for reaching out! From what I can see, the mapping for post_date is 'date' already: https://github.com/10up/ElasticPress/blob/1ad1716700e1be38b332ce08d7d5198dd6208145/includes/mappings/post/7-0.php

Can you share the error you're getting? I'm wondering if maybe the mapping isn't being properly applied and ES is guessing at some fields.

Also, I'd love to know what types of reporting you pull with Kibana. Since EP tracks mostly searches and not real-time data, I can never think of good use-cases for Kibana reporting but I know they're out there and we'd love to make the plugin work better for them.

**Comment by brandwaffle** [comment]
@tlovett1 since you're most familiar with Users/Terms, any chance you could also take a quick look at this one?

**Comment by oscarssanchez** [comment]
Hi @dmhendricks ,

Have you tried with the latest version of Elasticpress? We have been merging a lot of code and might be solving the issue. Please feel free to open a new issue if this is not resolved!

**Comment by victorpintot8** [comment]
Same error here, I'm using version 3.5.5. The mapping is always created using the test field type, instead of date. I debbuged the code, and althought is clearly defined in "7.-0.php" file line 293, for some reason ES ignore that mapping and sets text. Is very annoying, i can't use the autosuggest feature, it throws error 400 bad request "field [post_date_gmt] is of type [indexed,tokenized], but only numeric types are supported".

**Comment by balajidamodare** [comment]
facing the same issue on the latest version of the elasticpress [Version 4.1.0]

**Comment by balajidamodare** [comment]
simply I am indexing data via the command line and its mapping date field as text.
steps to reproduce

wp elasticpress clear-index
wp elasticpress delete-index --yes
wp elasticpress index --show-bulk-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"

Not showing any errors on CLI

**Comment by felipeelia** [comment]
```
wp elasticpress index --show-bulk-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"
```
should actually be
```
wp elasticpress index --setup --yes --show-bulk-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"
```
`--setup` will send the mapping again, as they are deleted by the `delete-index` command you are calling right before.

**Comment by balajidamodare** [comment]
Hi Flipeelia 
Thank you for your reply I have tried and executed it, but the documents are not indexed and it shows the message as Success: Indexing posts....

followed following steps

command:  `wp elasticpress clear-index`
Output : `Success: Index cleared.`
command:  `wp elasticpress delete-index --yes`
Output : `Success: Index deleted`
`Deleting index for posts...`
command:  `wp elasticpress index --setup --yes --show-bulk-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"`
Output : `Success: Indexing posts...`

In Dashboard showing the following Message 
We could not find any data for your Elasticsearch indices. Maybe you need to [sync your content]
