### ISSUE TITLE
  wp elasticpress index  --setup -path=/home/.../ --allow-root shows critical error although indexer is fine when run from plugin dashboard

### ISSUE THREAD

**Issue by iexpertini** [10up/ElasticPress#1821]
Hi Guys, 

Need a help to run the Elasticpress indexer by cron job. As we have 99+ blogs and we can't run this indexer manually. We want to run this by cron.

Today, we tried to do and face the following error:

Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.
Adding post mapping...

Kindly please guide us for this. 

we use following command from root: 

wp elasticpress index  --setup --path=/home/../ --allow-root

Thanks,
HS

![11](https://user-images.githubusercontent.com/38841610/85892839-47fcee00-b80f-11ea-8cc3-31b6f37ff4ee.png)

![ep-error](https://user-images.githubusercontent.com/38841610/85892764-27349880-b80f-11ea-9265-7ddd289ebe74.png)

**Comment by oscarssanchez** [comment]
Hey @iexpertini ,

I could not reproduce this, this works for me without issues: 

`wp elasticpress index --setup --path=/var/www/html/ --allow-root`

I see you have a couple of errors and a fatal one before this message. I would try disabling that "iwj" plugin, as this seems unrelated to elasticpress.

**Comment by iexpertini** [comment]
Hi,

After analysing it further I noticed that ElasticPress also tries to index the pages and all other post types and creating the issues.

So when I define the post type as guided here: http://10up.github.io/ElasticPress/tutorial-wp-cli.html

It works for me with this command from cron: 0 * * * * /usr/local/bin/wp elasticpress index --setup --post-type=my_post_type --path=/home/public_html/myhome --allow-root.
  
A) I recommend ElasticPress to have a feature at front end dashboard which post type we want to index.

B) And it can speed up more - 

It is a bit slow as we have somewhere around 400,000 posts and it takes lot of time to index. Although our server is 128GB and 32 CPUs and 3000 GB Hard disk.

Any help on this please to speed up.

Thanks,
HS

**Comment by oscarssanchez** [comment]
Hi @iexpertini , 

Thanks for the feedback, I'll cc @brandwaffle for the post type frontend enhancement. In the meantime, if you would like to work on this feature and share it, please feel free to make PR as they are always welcome. 

For now, a solution for this would be to use the `ep_indexable_post_types` filter to define your indexable post types programatically. 

As for your other issue, 400,000 is a good number and without knowing what your posts data consist of, it would be hard for me to suggest something to speed up the process. It could also be a problem with your elasticsearch instance and how it is configured. You can always try elasticpress.io to see if it could be related to it, as the service is configured to deliver the best experience with elasticpress. 

Kind regards,
