### ISSUE TITLE
 No products were found matching your selection.

### ISSUE THREAD

**Issue by soufianejayden1000** [10up/ElasticPress#1822]
Hello support how you doing  i have  a  problem  when i login to my wordpress wp-admin.php and move on  to my web site  in shop page it show product however .

when i copier web site link and past it in navigation private to see my web site as costumer it doesn't show the product in shop  page it show only this message No products were found matching your selection.

if you see the first screen : SCREENSHOT :                 https://cdn.filestackcontent.com/W3DXzvavTFStOIF7X0DY
and the second screenshot from navigation private :    https://cdn.filestackcontent.com/Z7iSaHXqRICnDTl0CuVz

**Comment by oscarssanchez** [comment]
Hi @soufianejayden1000 ,

Unfortunately it is difficult to give you an helpful answer without having much more context. As I could not reproduce what you are reporting locally, my first suggestion would be to disable all your plugins but Woocommerce and ElasticPress, and switch to a common theme like storefront, run a reindex and check if the problem persists.

This will help discard an external plugin/theme conflict.

Please let us know how it goes!

**Comment by tlovett1** [comment]
Seems like a caching issue.
