### ISSUE TITLE
index number of shards and replicas should be configurable

### ISSUE THREAD

**Issue by tvcapisani** [10up/ElasticPress#1823]
Actually ElasticPress does force indices creating with 5 primary shards and 1 replica shards each.
It would be nice to have an option to let the users change these default values depending on the ES cluster topology/configuration.

**Comment by brandwaffle** [comment]
@tvcapisani thanks for reaching out! You can set the number of shards and replicas during the initial mapping put (this is when ElasticPress sets the index replica info) with this filter: https://github.com/10up/ElasticPress/blob/ec3fd7ef9ae2c3dbfd658236845c2605a3855b55/includes/classes/Elasticsearch.php#L677

`Array
(
    [settings] => Array
        (
            [index.number_of_shards] => 5
            [index.number_of_replicas] => 1
            [index.mapping.total_fields.limit] => 5000
            [index.max_result_window] => 1000000
            [analysis] => Array
                (
                    [analyzer] => Array
                        (
                            [default] => Array`
