### ISSUE TITLE
Arabic custom mapping

### ISSUE THREAD

**Issue by alifazeli** [10up/ElasticPress#1825]
Hi

I have an arabic Woocomrece website.
I want add some custom mappings to have better results.

A mapping example is here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-mapping-charfilter.html#analysis-mapping-charfilter-analyze-ex

My elasticsearch version is  6.3.2.

My questions:
Is it possible with ElasticPress?
If yes
Which file should i add my custom mapping rules to?

Regards

**Comment by brandwaffle** [comment]
@alifazeli yes, EP offers full access to the entire mapping data via filters, so you can customize as needed. This ticket has an example of adding a filter to customize a new analyzer.

Please note there is also a language selector in the ElasticPress Settings menu of the WP Dashboard, where you can simply select another language and use that analyzer without having to edit code. Hope this helps!
