### ISSUE TITLE
Delete page from edit.php does not remove page from elastic database

### ISSUE THREAD

**Issue by SimonvanWijhe** [10up/ElasticPress#1827]
**Describe the bug**

When deleting a page from `edit.php` the page is not deleted from the elastic database. Instead the post_status is changed to "trash".

This behaviour is different from when the page is deleted on the post page itself. (see screen recording)

**Steps to Reproduce**

1. Go to 'Pages'
2. Click on 'Trash' under the post title.
3. Go to elastic database
4. See that the page is still there and that post_status is changed to 'trash'.

**Expected behavior**

I would expect the page to be removed, just like when the page is deleted from the post page itself.

**Screenshots**

![delete_page_example](https://user-images.githubusercontent.com/41121933/86467657-1071d280-bd36-11ea-887b-1c85f43c4172.gif)

**Environment information**
 - Device: Macbook
 - OS:  MacOS 10.15.5
 - Browser and version: Chrome 83
 - WordPress version: 5.4.2
 - Plugins and version: Elasticpress 3.4.2
 - Theme and version: Twenty Nineteen

**Additional context**

I am using the chrome extension elasticsearch-head to look into our elasticsearch database.

**Comment by edwinsiebel** [comment]
Some additional information:

When deleting a document from the `edit.php` (thus the admin archive view), two requests are done to ES.

First, the actual delete of the document:

```
string 'http://es/{index}/_doc/1564' (length=64)
array (size=4)
  'method' => string 'DELETE' (length=6)
  'timeout' => int 15
  'blocking' => boolean false
  'headers' => 
    array (size=1)
      'Content-Type' => string 'application/json' (length=16)
```

And afterwards, a bulk 'restore'/'save' of the `trashed` post, which is thus not desired:
```
string 'http://es/{index}/_bulk' (length=60)
array (size=4)
  'method' => string 'POST' (length=4)
  'body' => string '{"index":{"_id":1564}}
{"post_id":1564,"ID":1564,"post_title":"test","post_status":"trash"}' (length=1031)
  'timeout' => int 30
  'headers' => 
    array (size=1)
      'Content-Type' => string 'application/json' (length=16)
```

**Comment by edwinsiebel** [comment]
And the culprit:

```php
add_filter( 'wp_redirect', [ $this, 'index_sync_queue_on_redirect' ], 10, 1 );
```

This triggers the `$this->index_sync_queue();`, which sends the _bulk action.

**Comment by tlovett1** [comment]
Do you have the Protected Content feature enabled?

**Comment by edwinsiebel** [comment]
I don't have that enabled. Just the `Post Search`.

**Comment by oscarssanchez** [comment]
Hi @edwinsiebel @SimonvanWijhe ,

I could reproduce this when protected content is not enabled. However, I am wondering if the actual behavior should be the opposite and the bug is the opposite: when you trash a post from the post edit page itself.

It is not fully clear to me whether the `trash` post status belongs to the protected content feature so I will check internally.

**Comment by edwinsiebel** [comment]
Hi @oscarssanchez ,

Using Protected Content seems unusual for this case.

When not using Protected Content, I would think that only 'published' content will be pushed to ES. Trashed items are not published (or publicly available) content.
Thus, either trashing it vai the post edit page itself, or on the overview pages, it should not be pushed to ES (and should be only deleted from ES).

Just my 2 cents.

**Comment by edwinsiebel** [comment]
Any research of improvements on this issue?

**Comment by tlovett1** [comment]
Right, when PC is enabled, the post should remain in ES with a trash status. Otherwise it should be deleted.
