### ISSUE TITLE
Search via Elasticpress not happening 

### ISSUE THREAD

**Issue by sanbalj919** [10up/ElasticPress#1832]
To enhance the Search functionality in our Marketplace, we are leveraging the ElasticPress V3.4.2. Activating the plugin got the Indexing done successfully and no problem with that.

However, search from the Woodmart Header is not going via Elasticpress and no queries to Elasticsearch are triggered(Checked with ElasticPress Debug bar plugin) ?

From application, search query is triggered with default Query string like ?s=example&post_type=product. Could you please let me know what could be going wrong ?

Few of other Plugins:
WooCommerce - V4.2.0
Woodmart - Main theme(Search Widget is also from Woodmart header)
Dokan - V3.0.5
Dokan Pro - V3.0.1
WooCommerce Services - V1.23.1
WooCommerce Core - 1.0.21
Yoast SEO - V14.3

**Comment by brandwaffle** [comment]
@sanbalj919 can you confirm the actual query being sent to the database still contains the ?s parameter? Sometimes we see plugins/themes overriding the default search functionality and creating a custom query. Also, I'm not familiar with Woodmart but if it uses ajax to reload results those queries would not appear on the debug bar.

**Comment by brandwaffle** [comment]
@sanbalj919 and can you confirm the WooCommerce Feature in ElasticPress is active?

**Comment by brandwaffle** [comment]
Closing due to lack of response.
