### ISSUE TITLE
Facets terms searchbox doesn't work

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1836]
**Describe the bug**

When i enter text on the facet search-box to narrow down terms it doesn't do anything.

**Steps to Reproduce**

1. Have facets
2. Type something in the searchbox
3. it doesn't search
4. no js errors or console errors, nothing.

**Expected behavior**

It should narrow down the list of terms of the facet.
**Screenshots**

![facets](https://user-images.githubusercontent.com/8179611/87681708-3c05ab80-c77f-11ea-9428-715c8b3cf089.png)

**Environment information**
 - Device: PC
 - OS: Win 7
 - Browser and version: Version 83.0.4103.116 (Official Build) (64-bit)
 - WordPress version: Version 5.4.2
 
 - Plugins and version: ElasticPress Version 3.4.2
 - Theme and version: Twenty SixteenVersion: 2.1 (child)
 
 - <details><summary>Site Health Info:</summary>
   
   </details>
hack me please. can't ask to make that public. it's dangerous.
**Additional context**

Yes.
This is how i call facets:
`the_widget( 'ElasticPress\Feature\Facets\Widget', $instance, $args );`

**Comment by MediaMaquina** [comment]
I have a staging copy of the site (outdated).
With version 3.0.3 of elasticpress and this works fine.
I'm pretty sure some of the latest updates that messed with facets broke it.

**Comment by oscarssanchez** [comment]
Hi @MediaMaquina ,

I can reproduce this, it seems #1834 solves this for me. Can you give it a try?

Thanks!

**Comment by MediaMaquina** [comment]
@oscarssanchez thank you. Yes that's it.

**Comment by MediaMaquina** [comment]
@oscarssanchez i fins that the search works on the first facet, but not on the second, i have 3 inline.
