### ISSUE TITLE
Documents' content not indexed from wp-admin, works from wp-cli

### ISSUE THREAD

**Issue by pjohanneson** [10up/ElasticPress#1838]
**Describe the bug**
When I re-sync from my site's wp-admin pages, the contents of documents (PDF for sure) are not indexed. If I use `wp elasticsearch index [--url={site url}]`, they are indexed.

**Steps to Reproduce**

I have seen this in both a single site in a Multisite network, and when using network-activated Elasticsearch. 

1. Add a PDF file to the site containing the string "Jezebel".
2. Go to example.com/wp-admin and select the Elasticsearch menu.
3. Click on the "Sync" icon.
4. Search the site for "Jezebel".
5. Nothing found.
6. From the command line, use `wp elasticsearch index`.
7. Search the site for "Jezebel".
8. Item found.

Repeating 3-4 results in 5 again; repeating 6-7 results in 8 again.

**Expected behavior**
Syncing from the server's wp-admin pages should do the same thing as from WP-CLI.

**Screenshots**

**Environment information**
 - Device: Laptop
 - OS: Ubuntu 18.04.4
 - Browser and version: Firefox 78.0.1 (64-bit)
 - WordPress version: 5.4.2
 - <details><summary>Site Health Info:</summary>
  `
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: America/Winnipeg
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
user_registration: false
default_comment_status: open
multisite: true
user_count: 11
site_count: 19
network_count: 1
dotorg_communication: true

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Seventeen (twentyseventeen)
version: 2.3
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, editor-styles, wp-block-styles, responsive-embeds, starter-content, custom-header, widgets
theme_path: /srv/www/vhosts/brandonu.local/wp-content/themes/twentyseventeen

### wp-themes-inactive (11) ###

Brandon University Lockdown: author: Brandon University web team, version: (undefined)
Brandon University 2014: version: 1.0, author: Patrick Johanneson
Brandon University Theme 2016: version: 1.0, author: BU Web Team
The Canadian Journal of Native Studies: version: 1, author: Darcy Margetts
eskobear: version: 1.0.0, author: Greg Misener
SWAAC (fork of Twenty Twelve): version: 1.1, author: the WordPress team
Thematic: version: 1.0.4, author: Ian Stewart & Chris Goßmann
Twenty Fifteen: version: 2.6, author: the WordPress team
Twenty Nineteen: version: 1.6, author: the WordPress team
Twenty Sixteen: version: 2.1, author: the WordPress team
Twenty Twenty: version: 1.4, author: the WordPress team

### wp-mu-plugins (37) ###

Brandon U Admin Bar: author: (undefined), version: (undefined)
Brandon U Disable Comments: author: (undefined), version: (undefined)
Brandon U Elastic Debuggery µ: author: (undefined), version: 1.0.0
Brandon U Menus: author: (undefined), version: (undefined)
Brandon U User Lockout: author: (undefined), version: (undefined)
Brandon U User Site List: author: (undefined), version: (undefined)
Brandon U WP-Login Tweaks (MU): author: (undefined), version: (undefined)
bu-events-settings.php: author: (undefined), version: (undefined)
BU Local IP Range µ: author: (undefined), version: 1.0.0
debug.php: author: (undefined), version: (undefined)
Dump (debugging tool): author: (undefined), version: (undefined)
Eggplant That Up: author: (undefined), version: (undefined)
ep.php: author: (undefined), version: (undefined)
GF Bambora Network Settings (µ): author: (undefined), version: 1.0.0
GF Remove CC µ: author: (undefined), version: 1.0.0
GF Unique Order Number µ: author: (undefined), version: 1.0.0
Global Terms Turn On: author: (undefined), version: (undefined)
Gravity Forms Total Field Conditional Logic µ: author: (undefined), version: 1.0.0
Gravity Forms Validation Message µ: author: (undefined), version: 1.0.0
MCE Lockdown µ: author: (undefined), version: 1.1.0
p3-profiler.php: author: (undefined), version: (undefined)
PJ Rest Restrictions: author: (undefined), version: (undefined)
Remove Quick Edit µ: author: (undefined), version: 1.0.0
restricted-admin.php: author: (undefined), version: (undefined)
Shortened Site Title: author: (undefined), version: (undefined)
simple-history-disable-rss.php: author: (undefined), version: (undefined)
Sitemap Shortcode µ: author: (undefined), version: 1.0.0
SSH FS checker: author: (undefined), version: (undefined)
ssl-on-local.php: author: (undefined), version: (undefined)
SSL WordPress: author: (undefined), version: (undefined)
wp-mail.php: author: (undefined), version: (undefined)
wp-search.php: author: (undefined), version: (undefined)
µ Edit Flow Extensions: author: (undefined), version: (undefined)
µ Gravity Forms CSS/HTML5 force settings: author: (undefined), version: 1.0.0
µ Gravity Forms Export Form Filename: author: (undefined), version: 1.0.0
µ MiraPay Finder: author: (undefined), version: 1.0.0
µ Sort Sites: author: (undefined), version: 1.0.0

### wp-plugins-active (17) ###

Brandon U Asides: author: (undefined), version: 1.2.0
Brandon U Cache Plugins: author: (undefined), version: 1.0.0
Brandon U Conference Theme Extensions: version: 1.1.0, author: Greg Misener and Patrick Johanneson
Brandon U Global Sitemap: author: (undefined), version: (undefined)
Brandon U Gravity Form Extensions: author: (undefined), version: 1.0.0
Brandon U Safety Notices Display: author: (undefined), version: 1.0.0
CMB2: version: 2.7.0, author: CMB2 team
ElasticPress: version: 3.4.2, author: 10up
Email Address Encoder: version: 1.0.21, author: Till Krüss
Fast User Switching: version: 1.4.8, author: Tikweb
Gravity Forms: version: 2.4.19, author: Gravity Forms
Gravity Perks: version: 2.1.9, author: Gravity Wiz
Network Plugin Auditor: version: 1.10.1, author: Katherine Semel
The Events Calendar: version: 5.1.4, author: Modern Tribe, Inc.
User Role Editor: version: 4.55.1, author: Vladimir Garagulya
WordPress Importer: version: 0.7, author: wordpressdotorg
Yoast Duplicate Post: version: 3.2.5, author: Enrico Battocchi & Team Yoast

### wp-plugins-inactive (71) ###

Admin Page Framework - Loader: version: 3.8.20, author: Michael Uno
Akismet Anti-Spam: version: 4.1.6, author: Automattic
Autoptimize: version: 2.7.3, author: Frank Goossens (futtta)
avb: author: (undefined), version: (undefined)
Blubrry PowerPress: version: 8.3.4, author: Blubrry
Books: version: 0.1.0, author: YOUR NAME HERE
Border Control: version: 1.0.4, author: SMILE
Brandon U - MIME Types: author: (undefined), version: 1.1.0
Brandon U Admissions Tools: author: Greg Misener, version: (undefined)
Brandon U CJNS Issue List: author: (undefined), version: 1.0.0
Brandon U Columns: version: 0.1, author: Brandon University (original by Konstantin Kovshenin)
Brandon U Contact Info: author: (undefined), version: 1.0.0
Brandon U Department Promotion: version: 1.0.0, author: Greg Misener
Brandon U Event Extension: author: (undefined), version: 1.2.0
Brandon U Events Remote Calendar: author: (undefined), version: 1.1.0
Brandon U Event Tools: version: 1.0.1, author: Patrick Johanneson
Brandon U Gutenberg Mods: author: (undefined), version: 1.0.0
Brandon U Homecoming Tools: version: 1.1.0, author: Patrick Johanneson
Brandon U Icon Bar: version: 1.0.0, author: Greg Misener
Brandon U Jobs: author: (undefined), version: 1.0.0
Brandon U LDAP Page Protection: author: (undefined), version: 1.1.0
Brandon U Libcal Loader: version: 1.1.0, author: Patrick Johanneson
Brandon U Library Tools: version: 1.0.0, author: Greg Misener
Brandon U Meteor Slides: author: (undefined), version: (undefined)
Brandon U Navigation: version: 0.1, author: Patrick Johanneson
Brandon U Nav Walker: author: (undefined), version: 1.0.0
Brandon U Oasis: author: (undefined), version: 1.0.0
Brandon U Office Hours: author: (undefined), version: 1.0.0
Brandon U Person CPT: author: (undefined), version: 1.1.0
Brandon U Phone Numbers: author: (undefined), version: 1.0.0
Brandon U Research Connection CPTs: version: 1.0.0, author: Greg Misener
Brandon U Residence Calculator: author: (undefined), version: 1.0.0
Brandon U REST Multisite Tools: author: (undefined), version: 1.0.0
Brandon U Safety App: author: (undefined), version: 1.0.0
Brandon U Services: author: (undefined), version: 1.0.0
Brandon U Table Magic: author: (undefined), version: (undefined)
Brandon U Tuition Calculator: author: (undefined), version: 2.0.0
Brandon U Usernames: author: (undefined), version: 1.0.0
Brandon U XML Calendar Snarfer: author: (undefined), version: 1.0.0
Broken Link Checker: version: 1.11.13, author: WPMU DEV
BU Login (JS): author: (undefined), version: 1.0.0
BU MiraPay: version: 2.0.1, author: Patrick Johanneson (Brandon University)
BU Parking Rates: version: 1.1.0, author: Greg Misener (and Patrick Johanneson, probably)
Classic Editor: version: 1.5, author: WordPress Contributors
Custom Meta Boxes: version: 1.0.3, author: Human Made Limited
Debug Bar: version: 1.0.1, author: wordpressdotorg
Debug Bar ElasticPress: version: 1.4, author: 10up
Duo Two-Factor Authentication: version: 2.5.5, author: Duo Security
Edit Flow: version: 0.9.6, author: Daniel Bachhuber, Scott Bressler, Mohammad Jangda, Automattic, and others
Eskobear Customizer Mods: author: (undefined), version: 1.0.0
GP Conditional Pricing: version: 1.2.41, author: Gravity Wiz
GP Limit Dates: version: 1.0.20, author: Gravity Wiz (latest version: 1.0.22)
Gravity Forms Bambora (North America) Gateway (Advanced): version: 1.0.0, author: WP Gateways
Gravity Forms Bambora Payments: author: (undefined), version: 1.1.0
Gravity Forms Simple Add-On: version: 2.1, author: Rocketgenius
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Jetpack by WordPress.com: version: 8.7.1, author: Automattic
MapMyFitness: version: 0.1, author: MapMyFitness
Monkeyman Rewrite Analyzer: version: 1.0, author: Jan Fabry
Oasis Workflow Groups: version: 1.5, author: Nugget Solutions Inc.
Oasis Workflow Pro: version: 7.2, author: Nugget Solutions Inc.
Page Menu Editor: version: 3.1.0, author: Patrick Johanneson (forked from work by Sarah Anderson)
Pre-Publish Checklist: version: 1.1.0, author: Brainstorm Force
PublishPress Checklists: version: 2.1.0, author: PublishPress
Simple Tableau Viz: version: 2.0, author: Gary Hukkeri
Story Custom Post Type: version: 1.0.0, author: Patrick Johanneson
Tabby Responsive Tabs: version: 1.2.3, author: cubecolour
User Switching: version: 1.5.5, author: John Blackbourn & contributors
WooCommerce: version: 4.3.0, author: Automattic
WP Google Maps: version: 8.0.23, author: WP Google Maps (latest version: 8.0.25)
WP Super Cache: version: 1.7.1, author: Automattic

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.15.0-106-generic x86_64
httpd_software: Apache/2.4.29 (Ubuntu)
php_version: 7.2.24-0ubuntu0.18.04.6 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 32M
php_post_max_size: 32M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.30-0ubuntu0.18.04.1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/www/vhosts/brandonu.local/wp-content
WP_PLUGIN_DIR: /srv/www/vhosts/brandonu.local/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: not writable
uploads: writable
plugins: not writable
themes: not writable
mu-plugins: not writable

`
   </details>

**Comment by pjohanneson** [comment]
I found a similar issue in #1305, which was closed without any apparent resolution.

**Comment by pjohanneson** [comment]
To rule out plugin conflicts (because I seem to have a lot of them running on my local instance), I did a clean install of WordPress and tried it out. I'm seeing exactly the same issue on WordPress running TwentyNineteen and Elasticpress only.

## WP Health Check info

`
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /index.php/%year%/%monthnum%/%day%/%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/www/vhosts/ep-test.local
wordpress_size: 39.45 MB (41365792 bytes)
uploads_path: /srv/www/vhosts/ep-test.local/wp-content/uploads
uploads_size: 186.75 KB (191227 bytes)
themes_path: /srv/www/vhosts/ep-test.local/wp-content/themes
themes_size: 3.96 MB (4153984 bytes)
plugins_path: /srv/www/vhosts/ep-test.local/wp-content/plugins
plugins_size: 7.21 MB (7560292 bytes)
database_size: 2.13 MB (2228224 bytes)
total_size: 52.93 MB (55499519 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.4
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: /srv/www/vhosts/ep-test.local/wp-content/themes/twentytwenty

### wp-themes-inactive (2) ###

Twenty Nineteen: version: 1.6, author: the WordPress team
Twenty Seventeen: version: 2.3, author: the WordPress team

### wp-plugins-active (1) ###

ElasticPress: version: 3.4.2, author: 10up

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 4.1.6, author: Automattic
Hello Dolly: version: 1.7.2, author: Matt Mullenweg

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.15.0-106-generic x86_64
httpd_software: Apache/2.4.29 (Ubuntu)
php_version: 7.2.24-0ubuntu0.18.04.6 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 32M
php_post_max_size: 32M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.7.30-0ubuntu0.18.04.1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/www/vhosts/ep-test.local/wp-content
WP_PLUGIN_DIR: /srv/www/vhosts/ep-test.local/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: not writable
uploads: writable
plugins: not writable
themes: not writable

`

**Comment by oscarssanchez** [comment]
Hi @pjohanneson ,

I could not reproduce this locally. 

Can you try the following:

1.- Upload this sample PDF: http://www.africau.edu/images/default/sample.pdf
2.- Activate the documents feature
3.- Index
4.- If protected content is enabled: in the media page search for this string _this is a small demonstration_ or _boring_
5.- If protected content is not enabled: in the frontend, search for _this is a small demonstration_ or _boring_

**Comment by pjohanneson** [comment]
I'm seeing the same issues using the sample PDF. The dashboard indexing doesn't seem to include it; the command-line indexing does.

I'm going to try setting up an Elastic server on my local machine, to see if there's some kind of weird network problem affecting me.

**Comment by pjohanneson** [comment]
Even using Elastic server on my local machine, I get the same effect: indexing from the dashboard doesn't seem to add the document content, but the command line does.

I've got Elasticsearch 6.8.10 running on both sites; do I need to upgrade to the latest version of the search server?

**Comment by oscarssanchez** [comment]
Hi @pjohanneson ,

I just tried this with 6.8.10 and i have no issues whatsoever. You may want to test with https://github.com/10up/wp-local-docker-v2 to rule out specific configurations in your environment.

Kind regards.

**Comment by pjohanneson** [comment]
I have found the source of the issue, and it is indeed to do with my config. However, the issue isn't resolvable (as far as I can tell) using a filter, because it's related to a `WP_Filesystem()` call with no arguments. I'd suggest adding a filterable `$fs_args` array in the `includes/classes/Features/Documents.php` file, which is what it took to make it work for me. Should I do this up as a pull request, or open a new issue?
