### ISSUE TITLE
400 Bad Request ElasticSearch remote_request() in Query Monitor

### ISSUE THREAD

**Issue by DenisFlorin** [10up/ElasticPress#1840]
Hello,

I'm seeing the following errors in Query Monitor:
![image](https://user-images.githubusercontent.com/38504865/87968298-ddb33280-cac8-11ea-86e4-0b050ff6004e.png)

I installed Debug Bar ElasticPress and below are the query body and query result:

`{ "from": 0, "size": 2, "sort": [ { "post_date": { "order": "desc" } } ], "query": { "more_like_this": { "like": { "_id": 381565 }, "fields": [ "post_title", "post_content", "terms.post_tag.name" ], "min_term_freq": 1, "max_query_terms": 12, "min_doc_freq": 1 } }, "post_filter": { "bool": { "must": [ { "terms": { "post_type.raw": [ "post" ] } }, { "terms": { "post_status": [ "publish" ] } } ] } } }`

`{ "error": { "root_cause": [ { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead." } ], "type": "search_phase_execution_exception", "reason": "all shards failed", "phase": "query", "grouped": true, "failed_shards": [ { "shard": 0, "index": "addictivetipscom-post-1", "node": "mj69phKgQsGQ3SuWKNLYfQ", "reason": { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead." } } ], "caused_by": { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.", "caused_by": { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead." } } }, "status": 400 }`

`{ "from": 0, "size": 8, "sort": [ { "post_date": { "order": "desc" } } ], "query": { "more_like_this": { "like": { "_id": 381565 }, "fields": [ "post_title", "post_content", "terms.post_tag.name" ], "min_term_freq": 1, "max_query_terms": 12, "min_doc_freq": 1 } }, "post_filter": { "bool": { "must": [ { "terms": { "post_type.raw": [ "post" ] } }, { "terms": { "post_status": [ "publish" ] } } ] } } }`

`{ "error": { "root_cause": [ { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead." } ], "type": "search_phase_execution_exception", "reason": "all shards failed", "phase": "query", "grouped": true, "failed_shards": [ { "shard": 0, "index": "addictivetipscom-post-1", "node": "mj69phKgQsGQ3SuWKNLYfQ", "reason": { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead." } } ], "caused_by": { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.", "caused_by": { "type": "illegal_argument_exception", "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [post_date] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead." } } }, "status": 400 }`

**Comment by brandwaffle** [comment]
@DenisFlorin this error usually indicates that the ElasticPress mapping failed and therefore Elasticsearch is incorrectly guessing that the post_date is text. Can you try running the following WP CLI command?

`wp elasticpress index --setup --show-bulk-errors` and paste any output if that doesn't fix the problem?

**Comment by DenisFlorin** [comment]
Hi @brandwaffle,

The WP CLI command has fixed my issue. 

Thank you for your help!
