### ISSUE TITLE
Autosuggest is not working

### ISSUE THREAD

**Issue by eriktad** [10up/ElasticPress#1843]
Hi there.
After the last (3.4.3) update autosuggest is not working.

**Describe the bug**

We have JS error on the autosuggest.
This is console output.
![image](https://user-images.githubusercontent.com/10712881/88280360-b477e980-ccf6-11ea-8027-7a30ab9d5df3.png)

This is our admin settings.
![image](https://user-images.githubusercontent.com/10712881/88280416-d2dde500-ccf6-11ea-9a70-ed203f02b85b.png)

And our selector.
`#ep-search input[type=text]`

**Steps to Reproduce**

1. Go to 'developer console'
2. Click on 'Console'
3. Scroll down to ''

**Environment information**
 - Device: All
 - OS: All
 - Browser and version: All
 - WordPress version: 5.4.2
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**
We downgrade to 3.4.2 and its work again.

**Comment by diazoxide** [comment]
Yes its actual. Issue was related to `autosuggest.js` top includes. I noticed that jQuery dependency removed from wordpress enqueue.

**Comment by eriktad** [comment]
Fixed

**Comment by tlovett1** [comment]
What was the solution? Seems like this happens if your search input is not inside a `<form>`?

**Comment by diazoxide** [comment]
We just used input field class name that already used on EP autosuggest JS. After changing issue fixed.
