### ISSUE TITLE
How to enable Shingle Token Filter in Elasticpress?

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1844]
**Describe your question**
Hello my question is the same as this https://stackoverflow.com/questions/38760914/how-to-match-a-word-without-space-with-elasticsearch-data-having-space

How can i do that with elasticpress?

i already got this filter in place:

```
 function set_to_exact( $formatted_args, $args ) {
    if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
        $formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
        $formatted_args['query']['bool']['must'][0]['multi_match']['operator'] = 'AND';
        unset( $formatted_args['query']['bool']['should'] );
        unset( $formatted_args["query"]["bool"]["must"][0]["multi_match"]["type"] );
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );

```

THANKS!

**Comment by oscarssanchez** [comment]
Hi @MediaMaquina ,

From what I could read, elasticsearch would need to create new tokens, meaning the code from stackoverflow should not go into the `ep_formatted_args` filter (used to alter search), but rather at indexing time. So you would need to add a filter to the default mappings. Unfortunately, I am not familiar with the Shingle tokenizer but this is how we added a filter for synonyms, so it might be helpful as an example:

```
function search_config_mapping( $mapping ) {
// Ensure we have filters and is array.
if ( ! isset( $mapping['settings']['analysis']['filter'] ) || ! is_array( $mapping['settings']['analysis']['filter'] ) ) {
return $mapping;
}
// Ensure we have analyzers and is array.
if ( ! isset( $mapping['settings']['analysis']['analyzer']['default']['filter'] ) || ! is_array( $mapping['settings']['analysis']['analyzer']['default']['filter'] ) ) {
return $mapping;
}
// Define the custom filter.
$mapping['settings']['analysis']['filter']['sample_synonym_filter'] = array(
'type' => 'synonym',
'lenient' => true,
'synonyms' => array( 'synonym => synonym' ),
);
// Tell the analyzer to use our newly created filter.
$mapping['settings']['analysis']['analyzer']['default']['filter'] = array_merge( [ 'sample_synonym_filter' ], $mapping['settings']['analysis']['analyzer']['default']['filter'] );
return $mapping;
}
```

**Comment by MediaMaquina** [comment]
Thanks @oscarssanchez for looking into it. I don't understand elasticpress to implement it. Please leave it open in case someone else can in the future, could be an interesting feature.

**Comment by brandwaffle** [comment]
@oscarssanchez can we add the snippet above to the docs and close this ticket since there is no action item on it?
