### ISSUE TITLE
elasticpress plugin is not working on my elasticsearch enabled cloudways server

### ISSUE THREAD

**Issue by vipul1113** [10up/ElasticPress#1846]
__Have you searched for similar issues before submitting this one?__

__Is this a bug, question or feature request?__

__Describe the issue you encountered:__

__Current WordPress version?__

__Current ElasticPress version?__

__Current Elasticsearch version?__

__Where do you host your Elasticsearch server?__

__What ElasticPress features do you have currently active?__

__Other plugins installed (WooCommerce, Simple Redirect Manager, etc..)?__

__Steps to reproduce:__

1.
2.
3.

__Screenshots, if needed:__

**Comment by vipul1113** [comment]
Hello,

I have recently installed elasticpress by 10up and my host cloudways is elasticsearch enabled still plugin is not working i.e no action in search box as it was expected and other features like filtering options and so on .

Kindly guide me how to overcome from this situation.

Kind Regards
Vipul Arora

**Comment by brandwaffle** [comment]
Hi @vipul1113 unfortunately we are unable to provide support for self-hosted Elasticsearch. You can try installing the Debug Bar and Debug Bar ElasticPress plugins, which will tell you which queries are failing and why. If you feel there is a specific error causing the problem, please create a new ticket and fill out the questions in the bug report completely (versions, error messaging seen, etc).

**Comment by vipul1113** [comment]
Hi,

Thank you so much for your email.

I have tried to find error using debug bar, not throwing any error "No quires to show" but Elasticsearch isn't working. could you please suggest next option?

Kindest Regards.
Vipul Arora

**Comment by brandwaffle** [comment]
@vipul1113 again, we are really not in a position to help debug connection issues. However, if you would like us to review or provide support we need the basic info in the bug report as well as any screenshots so we can see what's happening. Keep in mind you need to 1) index your data in the Dashboard and then 2) perform a search to see ElasticPress work.

**Comment by vipul1113** [comment]
Hello,

Thank you so much for your kind response and support.

I already have indexed data of my staging website but nothing works as expected, I am sending you relevant screenshots kindly take a look and guide me how to overcome from this situation. Please find the URL's below

https://i.imgur.com/X9slz58.png

https://i.imgur.com/zagRREo.png

https://i.imgur.com/ahofQHD.png

https://i.imgur.com/gM1Bte4.png

https://i.imgur.com/NHKxqkS.png

https://i.imgur.com/hDRuosl.png

https://i.imgur.com/rdRrKLN.png

https://i.imgur.com/aCklVQh.png

https://i.imgur.com/pXHTgSp.jpg

https://i.imgur.com/94eZIG1.png

Kindest Regards
Vipul Arora
