### ISSUE TITLE
[Qestion] Total field limit for huge amount of meta value mappings

### ISSUE THREAD

**Issue by fabianmarz** [10up/ElasticPress#1849]
**Describe your question**

While the [default](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping.html#mapping-limit-settings) total field limit of Elasticsearch is `1000`, the [default](https://github.com/10up/ElasticPress/blob/develop/includes/mappings/post/7-0.php#L38) for ElasticPress is `5000`. This is caused by the Database design of Wordpress as each meta value is saved as string and therefore each meta value will be mapped to [10 different Elasticsearch fields](https://github.com/10up/ElasticPress/blob/develop/includes/mappings/post/7-0.php#L154-L193). For a recent WooCommerce implementation we ran into the 5k field limit and needed to raise it to >9k.

As this is not recommended by Elasticsearch since this could (and probably will cause memory and performance leaks) I want to know how you guys are handling an enormous amount of Wordpress meta value to field mappings in Elasticsearch. Do you have some mapping boilerplate to override the EP default mappings for some circumstances?

Thanks in advance!

**Comment by oscarssanchez** [comment]
Hi @fabianmarz ,

Usually making a list of meta fields and exclude them from indexing is the preferred path as of now. In case you find some patterns in your post meta, this comment might be useful: 

https://github.com/10up/ElasticPress/issues/1192#issuecomment-575231184
