### ISSUE TITLE
'elasticsearch' is not a registered wp command

### ISSUE THREAD

**Issue by alagirirajesh** [10up/ElasticPress#185]
I am trying to install elasticsearch and have following the instructions as much as possible. But i am getting the above error when i am running the command "wp elasticpress index --setup --network-wide".

Also i am using wpmudev's directory plugin uses custom fields. Can you please let me know if the current version of elasticpress supports custom fields.

Please help. As i did not know where to ask for support writing here. if you can answer or direct me to a place where i can get support should be good.

**Comment by AaronHolbrook** [comment]
Hi @alagirirajesh,
Based on the title of this issue, it sounds like you're actually running the command:

```
wp elasticsearch index --setup --network-wide
```

This will give you the exact message as the title of this issue - because `elasticsearch` is not the name of a command that the *ElasticPress* plugin implements. The command name is `elasticpress`. You should try:

```
wp elasticpress index --setup --network-wide
```

Hope that helps

**Comment by trueinviso** [comment]
I am running `wp elasticpress index --setup` and get the same error.  Running `wp help` I can see that elasticpress is not an option in wp yet.  In the bin/wp-cli.php file I can see that this is where the elasticpress command is supposed to be added to wp-cli, but for whatever reason this code hasn't run yet.  Is there something I need to do to get this file to run?

**Comment by zamoose** [comment]
Did you activate ElasticPress?

**Comment by trueinviso** [comment]
Yes, the problem seems to be that I have wordpress in a subdirectory and it can't find WP_CLI to add the elasticpress command to WP_CLI.

**Comment by nicoladj77** [comment]
I was having the same problem when running it on a [hgv](https://github.com/wpengine/hgv) machine, but in that case you have to run

    wp ep4wpe index --setup --network-wide

**Comment by trueinviso** [comment]
I was able to fix this by changing WP_CONTENT_DIR in wp-config file.

I was using:
     `define('WP_CONTENT_DIR', realpath($_SERVER['DOCUMENT_ROOT'] . '/content'));`
And changed it to:
    `define('WP_CONTENT_DIR', realpath(dirname(__FILE__) . '/content'));`

wp-cli could now find my project and the elasticpress command was added.
