### ISSUE TITLE
Can not get ElasticPress to work

### ISSUE THREAD

**Issue by SWICDEV** [10up/ElasticPress#1850]
**Describe your question**

We have a fully setup server for ElasticSearch. It looks like we can index however the search terms are not registered on any theme we have. The weight does not seem to work as well. We get results of indexing in the Dashboard. We downloaded the Debug bar and Debug Bar ElasticPress. The debug shows no results. Suggestions?

**Comment by oscarssanchez** [comment]
Hi @SWICDEV ,

If you get results when performing a search in the admin dashboard that is good news, it means your content is on elasticsearch! Now to do your queries through elasticsearch, you would need to perform your search via a WP_Query() object and pass the ep_integrate parameter. For more information please refer here: http://10up.github.io/ElasticPress/tutorial-indexables.html

**Comment by SWICDEV** [comment]
Hello,

Thank you for the reply however I am still not able to get the search to work or queries to show up in the ElasticPress Dashboard through ElasticSearch/ElasticPress. 

I have tried a few different things using WP_Query on multiple pages including the search page however I still cannot get a Query to show up in the ElasticPress Dashboard or the search to work. 

I also tried to add the ep_integrate onto the search page as well as in functions.php with variations of the code below:

function elasticpress_search( $wp_query ) { 
    if ( is_search()  ) { 
        $query->set( 'ep_integrate', true ); }     
}

add_action( 'pre_get_posts', 'elasticpress_search' );

I also manually added 'ep_integrate', true to all custom post types and WP_Query.

Any other suggestions?

**Comment by SWICDEV** [comment]
Update: Still not getting the search to work through ElasticPress and still not getting queries in the ElasticSearch dashboard however I have a working version of WP_Query using the below settings. 

$args = array(
   'ep_integrate'   => true,
    'posts_per_page' => 5,
    'post_type' => 'page',
    'orderby'   => 'title menu_order',
    'order'     => 'ASC',
	);

$the_query = new WP_Query( $args );

This is also set 
define( 'SAVEQUERIES', true );

**Comment by SWICDEV** [comment]
Still at it on my end I see X-ElasticPress-Query: true in chrome network tab however still not getting the correct search results and weight does not do anything as well as nothing showing up in ep-query-log or debugger

**Comment by SWICDEV** [comment]
Hello,

I thought I was supposed to post replies to the site however looking at this email it says reply to this email directly. Just in case I should be doing that instead here is the posts I updated on the site. I am still having issues getting the search, ep-query-log, weight and everything to work. I do have the index working it looks like. I am using the Sage theme however have the same thing happen with all themes. https://roots.io/sage/

Thanks,

Melissa

[cid:image001.jpg@01D6770C.6DFA9560]


<https://github.com/SWICDEV>[@SWICDEV]<https://github.com/SWICDEV>WICDEV

Author
SWICDEV<https://github.com/SWICDEV> commented 7 days ago<https://github.com/10up/ElasticPress/issues/1850#issuecomment-673499330> •
edited
Hello,
Thank you for the reply however I am still not able to get the search to work or queries to show up in the ElasticPress Dashboard through ElasticSearch/ElasticPress.
I have tried a few different things using WP_Query on multiple pages including the search page however I still cannot get a Query to show up in the ElasticPress Dashboard or the search to work.
I also tried to add the ep_integrate onto the search page as well as in functions.php with variations of the code below:
function elasticpress_search( $wp_query ) {
if ( is_search() ) {
$wp_query ->set( 'ep_integrate', true ); }
}
add_action( 'pre_get_posts', 'elasticpress_search' );
I also manually added 'ep_integrate', true to all custom post types and WP_Query.
Any other suggestions?

Top of Form
Bottom of Form
[@SWICDEV]<https://github.com/SWICDEV>

Author
SWICDEV<https://github.com/SWICDEV> commented 7 days ago<https://github.com/10up/ElasticPress/issues/1850#issuecomment-673715481>
Update: Still not getting the search to work through ElasticPress and still not getting queries in the ElasticSearch dashboard however I have a working version of WP_Query using the below settings.
$args = array(
'ep_integrate' => true,
'posts_per_page' => 5,
'post_type' => 'page',
'orderby' => 'title menu_order',
'order' => 'ASC',
);
$the_query = new WP_Query( $args );
This is also set
define( 'SAVEQUERIES', true );

Top of Form
Bottom of Form
[@SWICDEV]<https://github.com/SWICDEV>

Author
SWICDEV<https://github.com/SWICDEV> commented 2 days ago<https://github.com/10up/ElasticPress/issues/1850#issuecomment-675687538>
Still at it on my end I see X-ElasticPress-Query: true in chrome network tab however still not getting the correct search results and weight does not do anything as well as nothing showing up in ep-query-log or debugger



Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image004.png@01D6770C.485DD470]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.

**Comment by oscarssanchez** [comment]
Hi @ SWICDEV,

Can you confirm that the indexing is successful from WP-CLI and you get no errors? please run this command: wp elasticpress index --setup --show-bulk-errors 

I have the feeling your indexing didn't complete.

**Comment by SWICDEV** [comment]
Hello,

I still cannot get the search to work right or query to show up in admin panel or in Debug Bar ElasticPress. ☹

It did have some errors however when we fixed the errors and ran it again we got
Warning: Function pcntl_signal not available. Make sure to run `wp elasticpress clear-index` in case the process is killed.

We ran `wp elasticpress clear-index`

Success: Mapping sent
Success: Mapping sent
Indexing posts...
Processed 350/2916...
Processed 700/2916...
Processed 1050/2916...
Processed 1400/2916...
Processed 1750/2916...
Processed 2100/2916...
Processed 2450/2916...
Processed 2800/2916...
Processed 2916/2916...
Number of posts indexed: 2916
Indexing terms...
Processed 350/398...
Processed 398/398...
Number of terms indexed: 398
Total time elapsed: 39.453
Success: Done!
Adding post mapping...
Adding term mapping...

I updated the code a few times with different solutions for WP_Query. I even added some do_actions in a few files see below sample.

  {!!
    // the args
  $args = array(
    'ep_integrate'   => true,
    'posts_per_page' => 5,
    'post_type' => 'page',
    'exact'     => true,
  );
  // the query
  $query = new WP_Query( $args );
  !!}

  <div class="page-header">
    <h1>{!! App::title() !!}</h1>
  </div>

  <?php do_action( 'ep_add_query_log', $query ) ?>

  <?php   do_action( 'elasticpress_loaded' )  ?>

  @if ( $query->have_posts() )
    @while($query->have_posts())
      @php $query->the_post() @endphp
As well as tried
add_action( 'plugins_loaded', function() {
    ep_register_feature( 'slug', array(
        'title' => 'Pretty Title',
        'setup_cb' => 'setup_callback_function',
        'feature_box_summary_cb' => 'summary_callback_function',
        'feature_box_long_cb' => 'long_summary_callback_function',
        'requires_install_reindex' => true,
        'requirements_status_cb' => 'requirements_status_callback_function',
        'post_activation_cb' => 'post_activation_callback_function',
    ) );
} );



Other things to note: https://roots.io/sage/

·         Notice: Trying to access array offset on value of type int in …ourpath….\elasticpress\includes\classes\Command.php on line 958

·         We are using Sage Theme https://roots.io/sage/

·         I shut off two plugins to get the index to complete: (Wanted to make sure I can get ElasticPress to work before troubleshooting why they do not work together.)

PressApps Knowledge Base

Add knowledge base to your existing site in minutes that will decrease customer queries
Version 4.1.2 | By PressApps<https://codecanyon.net/user/pressapps>

ReadSpeaker webReader

ReadSpeaker Enterprise webReader for WordPress Blogs
Version 2.4.4 | By ReadSpeaker International B.v.<http://www.readspeaker.com/> | Visit plugin site<http://www.readspeaker.com/>


·         wp elasticpress status and wp elasticpress stats

o    Notice: Trying to access array offset on value of type int in C:\inetpub\wwwroot\wp-content\plugins\elasticpress\includes\classes\Command.php on line 958

o            "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 0,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 24
        },

o    Notice: Trying to access array offset on value of type int ..OURPATH..\elasticpress\includes\classes\Command.php on line 997
Notice: Trying to access array offset on value of type int ..OURPATH..\elasticpress\includes\classes\Command.php on line 1016
====== Stats for: swicdevswicedu-post-1 ======
Documents:  2916
Index Size: 10.67 MB
Index Size (including replicas): 10.67 MB
====== End Stats ======

Still looking into it and will update here every time I have something new.

Thanks,

Melissa

Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image001.png@01D67ADD.54D0CEE0]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.

**Comment by brandwaffle** [comment]
@SWICDEV I'm not sure if the command output there is from the clear-index flag or the subsequent re-running of the main indexing command, but it appears something is causing the mapping to re-run _after_ indexing, which is essentially erasing the data in the index. You may want to simply run `wp elasticpress index` after the clear-mapping command and see if it successfully indexes but does not include the two lines at the end about re-mapping the data.

**Comment by SWICDEV** [comment]
Hello,

Here is the output

[11:10 AM] David Kronk
Warning: Function pcntl_signal not available. Make sure to run `wp elasticpress clear-index` in case the process is killed. Indexing posts... Processed 350/2916... Processed 700/2916... Processed 1050/2916... Processed 1400/2916... Processed 1750/2916... Processed 2100/2916... Processed 2450/2916... Processed 2800/2916... Processed 2916/2916... Number of posts indexed: 2916 Indexing terms... Processed 350/398... Processed 398/398... Number of terms indexed: 398 Total time elapsed: 34.880 Success: Done!
(1 liked)

Currently testing. However we are still getting the warning. Will let you know if it works or not asap.

Melissa

Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image001.png@01D67D2E.10802710]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.

**Comment by SWICDEV** [comment]
Hello,

Still not getting anything logged into the queries log or anything changing with the search. Is the plugin compatible with the SAGE theme<https://roots.io/sage/>? We also run a VM on a windows server I believe and the elastic search is hosted on a windows server as well.

Thanks,

Melissa

Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image001.png@01D6884D.D23004F0]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.

**Comment by SWICDEV** [comment]
Hello,

I still cannot get the plugin to work and have not received any feedback for a while so I thought I would check in and see if you have any other ideas. We did get the index to fully run.

Thanks,

Melissa

Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image001.png@01D6A177.4A05C2C0]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.


From: Ashforth, Melissa
Sent: Friday, September 11, 2020 3:11 PM
To: '10up/ElasticPress' <reply@reply.github.com>; 10up/ElasticPress <ElasticPress@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [10up/ElasticPress] Can not get ElasticPress to work (#1850)

Hello,

Still not getting anything logged into the queries log or anything changing with the search. Is the plugin compatible with the SAGE theme<https://roots.io/sage/>? We also run a VM on a windows server I believe and the elastic search is hosted on a windows server as well.

Thanks,

Melissa

Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image001.png@01D6A177.4A05C2C0]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.

**Comment by felipeelia** [comment]
Hi @SWICDEV ,

I'm sorry for the late response. Since it's been months since our last interaction here I doubt you're still waiting for some response here but anyway, here are a few things I'd like to suggest to you (and whoever gets to this issue in the future):

- Check if the `WP_HOME` and `WP_SITEURL` constants are relying on something like a `$_SERVER` variable. That would cause problems with indexes names, for example
- Check which cache mechanisms you have in place. There is a chance some cache is intercepting the request and preventing ElasticPress from working
- Disable all plugins except ElasticPress, Debug Bar, and Debug Bar ElasticPress. Also, revert to a default theme like 2021. If things work, reenable everything again one by one.

Thanks!

**Comment by SWICDEV** [comment]
Hello,

That is a correct assumption. We did move on to something else. However that does not mean I might not get back to trying again. Thanks for the information if we try to work with the plugin again I will for sure try these things.

I appreciate the follow up!

Thank you,

Melissa

Melissa Ashforth
Web Site Manager
Southwestern Illinois College
618-235-2700 ext. 5162

[cid:image001.png@01D6FBAB.90067510]

Please remember to submit all SWIC.edu requests into the SWIC.edu Ticket System<https://infoshare.swic.edu/sites/Projects/SWICedu/SitePages/Home.aspx>. Resolve your tickets when completed by going to your tickets<https://infoshare.swic.edu/sites/Projects/SWICedu/Lists/SWICedu%20Redesign%20Issues%20Log/MyItems.aspx> --> Click on the User Acceptance tab edit the ticket and change the issue status to resolved.

**Comment by felipeelia** [comment]
Thanks, @SWICDEV! I'll go ahead and close the ticket for now. If you decide to get back to it and face any issues, please let us know.
