### ISSUE TITLE
When will ElasticPress work with versions higher than 7.5

### ISSUE THREAD

**Issue by lukecav** [10up/ElasticPress#1853]
The max version currently supported is 7.5.
https://github.com/10up/ElasticPress#requirements

The current version of Elasticsearch is 7.8.1.
https://www.elastic.co/downloads/elasticsearch

**Comment by maartendekeizer** [comment]
A few days ago Elasticsearch 7.9.0 is released.
Is there an list of issues that needs to be fixed to get ElasitcPress up and running for newer ES versions?

**Comment by brandwaffle** [comment]
Assigning to @oscarssanchez to test against 7.9 and bump compat if successful.
