### ISSUE TITLE
Error: The element input must not appear as a descendant of the a element.

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1854]
**Describe the bug**

The facets links are not hmtl5 valid.
**Steps to Reproduce**

1. Have facets
2. validate page with https://validator.w3.org/
3. Scroll down to 'Error: The element input must not appear as a descendant of the a element'

```
<a href="/movie/?filter_genre=comedy" rel="nofollow">
    <input type="checkbox">Comedy
</a>
```

**Expected behavior**

it should use valid html.

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by MediaMaquina** [comment]
Also another error with facets:

**Error: Element a is missing required attribute href.**

This happens when we have 
`<a  rel="nofollow">`
On terms that are disabled (no posts with that term). a lacks href.

**Comment by amesplant** [comment]
### Additional A11y Issues to address with this ticket 
**1.3.1**

- This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
facet checkbox: 
`<input type=""checkbox"" checked="""">`

**1.4.3**

- when a facet term is 'inactive' the minimum color contrast fails `.empty-term`

**1.4.11**

- when a facet term is 'inactive' the minimum color contrast fails `.empty-term`

**2.1.1**

- while tabbing through, the checkbox appears to be more of a visual indicator and not a funcitonal one, through the use of the keyboard, when a user tabs through and checks a checkbox, nothing happens as there is not submit button
facet checkbox:
`<input type=""checkbox"" checked="""">`

**2.5.3**

- Text in label element should provides name for input via for attribute. Consider markup to take advantage of labels:
```
<input id=""cat-1"" type=""checkbox"">
    	<label for=""cat-1"">Meal</label>
```

**3.2.2**

- Form does not contain a submit button
- No notification to user what will happen if checkbox is ""checked""

**3.3.2**

- Labels or instructions are not provided when content requires user input.

**4.1.2**

- This checkboxinput element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.
facet checkbox:
`<input type=""checkbox"" checked="""">`

**Comment by amesplant** [comment]
Merge Request pulled and ready for a Back End Engineer to add the form action to properly submit the form when JavaScript is disabled.
