### ISSUE TITLE
How we can index some post_type and escape other post type from update

### ISSUE THREAD

**Issue by iexpertini** [10up/ElasticPress#1855]
Hi there,

We have 5 post type 

Jobs always get updated daily
Salary, posts, pages won't get updated 

But if we run this command it will do only for post type jobs:

wp elasticpress index --setup --post-type=jobs

So we want to run the index from ssh and don't want to update salary,posts and pages.

Thanks,
Ahsan

**Comment by dinhtungdu** [comment]
Hi @iexpertini,

You can index multiple posts type by passing a comma-separated list to the `--post-type` flag, for example:

```
wp elasticpress index --post-type=jobs,another_post_type
```

Hope this helps!

**Comment by iexpertini** [comment]
Yes we use this for all post but my request is we don't want to update again e.g. salary post as it won't change. Where as jobs post changes daily.

**Comment by iexpertini** [comment]
Since salary post don't get updated daily and it has 100k posts and whereas jobs has 200k posts.

So whenever we run this

wp elasticpress index --setup --post-type=jobs,salary

it will delete and reindex all 300k posts.


So idea is since only jobs post updated and avoid load time. I want only jobs post to update and keep salary post as it is.

So in this scenario what command I should use.

Hope this explains

**Comment by dinhtungdu** [comment]
@iexpertini Each time you update a job post, it should reindex that job. Why do you need to index it again? Is the reindexing on update not working for you?

**Comment by iexpertini** [comment]
Yes, if jobs post are updated  / added / deleted it won't automatically sync in Elasticsearch. We thought may be it is because of large number of jobs 200k+.

So the reason we do run cron command to manually update it daily.

**Comment by iexpertini** [comment]
To be honest if that sync happens automatically with that large data of 300k posts it will solve our problem.

**Comment by dinhtungdu** [comment]
@iexpertini Can you try adding this code to wp-config.php and see if EP indexes your posts after create/update:

```
define( 'EP_SYNC_CHUNK_LIMIT', 500 );
```

**Comment by iexpertini** [comment]
I tried this for some time and noted it won't work for me. May be usually 10k jobs deleted and update in 1 hr the automatic process won't work.

Elasticsearch count:  225311 
Actual Post: 245419 

So my idea is running from cron daily jobs and skipping salary

A) If I run this daily what will happened?

wp elasticpress index --post-type=jobs --path=/home/myindexer/public_html/ --allow-root

Will this delete the salary and other post from indexer NOTE I'm not using setup in command

**Comment by iexpertini** [comment]
Can you please confirm I run only this command it will only update jobs post type and don't delete other post type from indexer

wp elasticpress index --post-type=jobs --path=/home/myindexer/public_html/ --allow-root

**Comment by brandwaffle** [comment]
@iexpertini Correct, as long as you don't pass `--setup` then your command will reindex _only_ the jobs post type and will not delete or change other post type entries.
