### ISSUE TITLE
WP-CLI not working full database

### ISSUE THREAD

**Issue by fredroo** [10up/ElasticPress#1858]
**Describe the bug**
when run  nohup wp elasticpress index --post-type="domain"
only some posts are indexed, but not total

**Steps to Reproduce**

1. command line
2. run command  ```nohup wp elasticpress index --post-type="domain```
3. See error success page refresh data

**Expected behavior**
Full Indexed
**Screenshots**

                <button type="button" class="btn btn-success ml-3 mb-2">Refresh Data</button>
        </div>
        <div class="jumbotron mt-3 mb-5">
                Raw Registrar Data<br><br><strong><pre></pre></strong>  </div>

====== Stats for: zoomwhoiscom-post-1 ======
Documents:  92126
Index Size: 74.71 MB
Index Size (including replicas): 74.71 MB
====== End Stats ======

**Environment information**
 - Device: Server CENTOS
 - OS: CENTOS 7
 - Browser and version: Command LINE
 - WordPress version: 5.4.2
Plugin Last Version
Elasticsearch 7.5

How to fix? I need index full database 30GB

**Comment by brandwaffle** [comment]
@fredroo can you post any errors you're seeing or additional information? It's not clear to me what the issue is. Also, are you intending to index only the Custom Post Type "domain"? If you want to index all post types, you should remove that parameter. Also, the first time you run WP-CLI to index you will need to pass in the --setup flag.

**Comment by fredroo** [comment]
@brandwaffle i will put --setup flag to test and back here to put the result with full logs

**Comment by fredroo** [comment]
Warning: mysqli_query(): (HY000/3): Error writing file '/tmp/MYYmS5PF' (Errcode: 28 "No space left on device") in /home/whatismy/public_html/wp-includes/wp-db.php on line 2024
Number of posts indexed: 32550
Total time elapsed: 2,537.792
Success: Done!

@brandwaffle i found the problem, how i can change folder tmp to another place to solve? consider the versions above

**Comment by fredroo** [comment]
i tried change in  /etc/sysconfig/elasticsearch
ES_TMPDIR=/mnt/backup/estmp

but restart elasticsearch not work

someone know how to change with the right way

**Comment by fredroo** [comment]
solved, change mysql tmp dir in my.cnf
