### ISSUE TITLE
Searching by ACF fields

### ISSUE THREAD

**Issue by shaneonabike** [10up/ElasticPress#1863]
**Describe your question**
Basically, I have read through a lot of the documentation, and the tickets here and I _think_ I have properly configured everything for my ACF fields to be indexed. They are coming back during a search so that's awesome.

What I think that I am missing is to properly understand how we can search by values in the ACF fields themselves. I'm happy to build my own facet but in testing I thought I could just do something like:

http://mysite.com/archive/?artists=xyz where artists is the name of the ACF field and xyz is the value.

What happens is that it returns results but it isn't a match to the value I put. Do I need to implement the `ep_formatted_args_query` to allow them? It's not clear as the docs don't really have examples so I'm a bit lost. Sorry and I appreciate any direction you could provide me with.

**Comment by shaneonabike** [comment]
I managed to get a little farther and setup the following bit of code in pre_get_posts

`       if (isset($_GET['artists'])) { 
          $query->set('meta_query', [[
            'key' => 'artists',
            'value'=>$_GET['artists'],
            'compare'=>'=',
          ]]);
`
The problem is that the ACF field is a relationship so it returns not an integer but a bunch of other data. This is being indexed I think so = never really works properly. This leads me to my next question about mapping. I haven't really been able to find a good example of how to setup mapping so that I could just change the indexed data for this field to the id or even the name.

Any help would be amazing

**Comment by shaneonabike** [comment]
Ok I realiized that some of this has to do with the way that ACF fields are being dumped into the actual ElasticSearch data (perhaps a bug). I had setup the field to return the Post ID rather than an entire array / object, and instead it seems that the JSON is being placed into the actual data structure.

I modified that now to ensure that the actual ACF relationship is being setup properly where I use the raw value to include the actual ID and the value to include the post content so that enhances searching.

I also wanted to ask (if anyone could help) whether we have the capacity to choose which value (raw or value) of a field is used when specifying the targeted meta_query. I tried to use artists.raw but that seems to not work properly. When using just artists it's perfect and returns the results I would expect.

Any thoughts?

**Comment by christianc1** [comment]
@shaneonabike ,

You can try the [`ep_post_formatted_args`](http://10up.github.io/ElasticPress/ep_post_formatted_args.html) filter.  That said, I haven't heard of using elasticsearch field mapping types to represent two totally different fields.  By that I mean, it would appear you're doing something like `post_id : meta.raw` and `post_content : meta.value`. Perhaps it is better (elasticsearch is fast) to just run two separate queries?

**Comment by shaneonabike** [comment]
It's totally possible that I am going about this wrong. What I noticed is that ElasticSearch (for ACF fields) simply dumps all the data (I think it's the JSON). So in my case, I have Films that have ACF reference fields (multiple Artists) which are returning the Post ID.

I noticed two issues in my case.
* It was outputting a lot of data that was filling up the index rather than just the IDs
* In some cases, I actually wanted it to search by the Post Title (so I needed that recorded somewhere)

Perhaps, I am going about this all wrong? I have one custom facet whereby I limit the results directly based on an artist so it has to be an exact match. This works fine but in other searches where they type in "Cohen Brothers" it doesn't cause there is no real reference to that artist just IDs. I thought if I dumped the different values into raw and the content it would be best.

Any advice would be great so I can properly integrate with your awesome plugin!
Thanks

**Comment by christianc1** [comment]
Sounds like artists should be taxonomy, but that's an opinion lacking any context.  If it is a taxonomy, you can just make the taxonomy searchable...
```php
add_action( 'pre_get_posts', function( $wp_query ) {
    if ( ! $wp_query->is_search() ) {
        return;
    }

    $search_fields = $wp_query->get( 'search_fields', [] );
    $search_fields['taxonomies'] = [ 'artists' ];
    $wp_query->set( 'search_fields', $search_fields );
} );
```

If you have architected things differently, and artists are not a taxonomy, I might recommend trying to add a meta field to the films in Elasticsearch.  Something like

```php
add_filter( 'ep_prepare_meta_data', function( $meta, $post ) {
    if ( 'film' === $post->post_type {
        // Get the artist names.  You'll have to write this.
        $artist_names = get_artist_names_for_film( $post->ID );
        // Add an artists meta field containing an array of artists name.
        $meta['artists'] = $artist_names;
    }
    return $meta;
}, 10, 2 );
```

Then tell ElasticPress to search this field.

```php
add_filter( 'ep_search_fields', function( $search_fields, $args ) {
    return array_merge( $search_fields, [ 'meta.artists.value' ] );
} );
```

This is all obviously psuedo-code, but maybe will help put you on the right track.  Good luck!

See: 
[ep_prepare_meta_data](http://10up.github.io/ElasticPress/ep_prepare_meta_data.html)
[ep_search_fields](http://10up.github.io/ElasticPress/ep_search_fields.html)

**Comment by shaneonabike** [comment]
That's an interesting point. I think I am going to explore that option as I suspect it would have better integration. I just need to move the content from a CT to a taxonomy I guess (oh boy!). But I do see the advantage because I can restrain to just one artist, which was the reason I was trying to figure out how to use IDs and names. Fuzzy search was for names and IDs was for a drop-down of specific names that would limit the results. It's clear that the taxonomy just does that automagically.

**Comment by shaneonabike** [comment]
Sorry for the radio silence I had to move onto other projects but we are back hooray!

I finally used your second suggestion and it works great for indexing. But I am curious how this can now be searched, because whatever I try it doesn't seem to be working.

Like if I go to http://mysite.org/?artists=shaneonabike but it displays everything and really isn't integrating with the other facets (appending the search to them). Is that normal? I even tried http://mysite.org?artists="%shane%" thinking maybe it needed to be fuzzy

**Comment by shaneonabike** [comment]
Ok! I answered my own question. What I was missing is to actually modify the WP_Query using `pre_get_posts`. For anyone else looking at this essentially when you modify this ElasticPress uses the argument modifications in the search with ElasticSearch. This is really a different behaviour then ApacheSolr, which kind of tripped me up a bit.

Anyway, all you have to do is essentially check for your argument in the URL, add a proper meta_query and viola you are good to go:

`
function my_search_filter($query) {
  if (!is_admin() && $query->is_main_query()) {
    if (isset($_GET['artists'])) {
        $query->set('meta_query', [
            'key' => 'artists',
            'value' => $_GET['artists'],
            'compare' => 'LIKE',
        ]);
    }
  }
}
add_action('pre_get_posts','my_search_filter',1);
`

**Comment by shaneonabike** [comment]
I made another request to see if we couldn't modify the documentation to allow comments and/or modifications. I would love to add more examples to reduce the Github noise of questions. I kept finding old ways of doing things only later to find out that there are new methods or better ways to do things.

**Comment by shaneonabike** [comment]
BTW thanks for your help @christianc1
