### ISSUE TITLE
Related posts show latest published posts

### ISSUE THREAD

**Issue by salvoaranzulla** [10up/ElasticPress#1865]
**Describe the bug**

I have put the following code to show related posts in single.php:

function show_related_posts() {
    $posts = ep_find_related(get_the_ID(), 5);
    $output = [];
    foreach($posts as $post) {
        $output[] = '<a href="'.esc_url(get_permalink($post->ID)).
        '">'.esc_html(get_the_title($post->ID)).
        '</a>';
    }
    return implode('<br/>', $output);
}

echo show_related_posts(); 
               
This code shows always latest posts published. 

I have installed Debug bar and Elasticpress for Debug Bar. 

I think that the problem is in **Query body**:

{
    "from": 0,
    "size": 5,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "more_like_this": {
            "like": {
                "_id": 1206639
            },
            "fields": [
                "post_title",
                "post_content",
                "terms.post_tag.name"
            ]
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "post"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish"
                        ]
                    }
                }
            ]
        }
    }
}

As as you can see, the post are ordered by date DESC.

Elasticsearch doesn't calculate a "score" if the post are ordered by date DESC:

{
    "took": 257,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 10000,
            "relation": "gte"
        },
        "max_score": null,
        "hits": [
            {
                "_index": "pocaranzullaitapp-post-1",
                "_type": "_doc",
                "_id": "1206548",
                "_score": null,

I think that the problem is inside file RelatedPosts.php line 132:

		$query = new WP_Query( apply_filters( 'ep_find_related_args', $args ) );

**Steps to Reproduce**

Show related post in a single page. Install Debug Bar + Elasticpress.

**Expected behavior**

Related post, not latest posts.

If a do a CURL POST without the date DESC, the related posts are OK:

curl -H "Content-Type: application/json" -X POST http://my-elastic-search/pocaranzullaitapp-post-1/_search -d '{
"from": 0,
"size": 5,
"query": {
"more_like_this": {
"like": {
"_id": 1206548
},
"fields": [
"post_title",
"post_content",
"terms.post_tag.name"
]
}
},
"post_filter": {
"bool": {
"must": [
{
"terms": {
"post_type.raw": [
"post"
]
}
},
{
"terms": {
"post_status": [
"publish"
]
}
}
]
}
}
}'

**Environment information**
 - WordPress version: 5.5

**Comment by oscarssanchez** [comment]
Hi @salvoaranzulla ,

I could not reproduce what has been reported. I also noticed some parameters from the request sent are missing from the ones on my testing, specifically these ones: 

`            "min_term_freq": 1,
            "max_query_terms": 12,
            "min_doc_freq": 1`

I don't think the post_date by desc param is the root cause of the problem in this case, as elasticsearch only orders the retrieved posts based on the score. In this case, we are using a more like this query which should be returning the most relevant results already and it is specified to only retrieve 5 posts.

Can you let me know more details to reproduce? It would be great if you can let us know your elasticsearch version as well as any other code you are adding via hooks.

Thanks!

**Comment by salvoaranzulla** [comment]
Hi @oscarssanchez,

Sure. Here all information:

1) We are using ElasticSearch 7.4 on AWS Cloud with WordPress latest version.

2) If we see "post_date by desc param" in our query, ElasticSearch gives us latest published post, not related posts. If we remove it, we see related posts.

3) To fix the problem and to improve related posts, we are using 2 filter: "ep_related_posts_fields" and "ep_formatted_args":

	$priority = 9999;

	add_filter( 'ep_related_posts_fields', 'sa_related_posts_ep_related_posts_fields', $priority, 1 );
	add_filter( 'ep_formatted_args', 'sa_related_posts_ep_formatted_args', $priority, 1 );

with these filters:

function sa_related_posts_ep_related_posts_fields( $fields ) {
	if ( is_array( $fields ) ) {
		$fields[] = 'terms.category.name';
	}

	return $fields;
}

function sa_related_posts_ep_formatted_args( $formatted_args ) {
	if ( is_array( $formatted_args )
	     && array_key_exists( 'query', $formatted_args )
	     && array_key_exists( 'more_like_this', $formatted_args['query'] )
	) {
		if ( array_key_exists( 'sort', $formatted_args ) ) {
			unset( $formatted_args['sort'] );
		}

		$formatted_args['query']['more_like_this']['boost_terms'] = 5;
		$formatted_args['query']['more_like_this']['minimum_should_match'] = "8%";
		$formatted_args['query']['more_like_this']['analyzer'] = "italian";
	}

	return $formatted_args;
}

If we remove the "sort", ElasticSearch gives us related posts.

4) We have found another problem: if ElasticSearch goes to timeout, ElasticPress show us latest posts: https://github.com/10up/ElasticPress/issues/1888

A workaround for this problem is using "ep_es_query_results" to read the response from ElasticSearch, avoiding Mysql.
