### ISSUE TITLE
ElasticPress pings ElasticSearch regularly with updated mappings

### ISSUE THREAD

**Issue by shaneonabike** [10up/ElasticPress#1868]
**Describe the bug**
In the process of debugging a few indexing issues I had outputted a custom filter I had created for `ep_indexable_post_types`. In my logs I can see that ElasticPress is pinging, and updating the server every 2 minutes.

I was wondering if this is by intention or a bug? I have a cron job setup to update the index every 15 minutes, but I don't believe the mapping needs to be updated every two minutes. I would imagine this would create unnecessary jobs with ElasticSearch and also additional load (although low)

**Steps to Reproduce**
1. Setup your custom ep_indexable_post_types call like below
`/**
 * ElasticSearch: Set the CPT types we want
 */
add_filter( 'ep_indexable_post_types', 'indexable_post_types', 10 );
function indexable_post_types( $post_types ) {
  $non_indexable_types = [
    'page' => 'page',
    'elementor_library' => 'elementor_library',
  ];
  $post_types = array_diff_assoc( $post_types, $non_indexable_types );
  error_log( 'types is ' . print_r( $post_types, true ) );
  return $post_types;
}
`
2. Turn on debugging in the wp-config.php file
3. Watch the debug log

**Expected behavior**
The server would only ping ElasticSearch either when a person is actually requesting data and/or when a change is made. Furthermore, that the mappings aren't updated unless a change is made.

**Comment by brandwaffle** [comment]
@shaneonabike the plugin does ping the server every few minutes to ensure it's operational, but it shouldn't be updating any mapping. Can you elaborate on the cron job and what it's doing? By default, ElasticPress uses the save_post hooks to ensure that any posts are synced in real-time when updated in WordPress, so a cron to update things shouldn't be necessary in most cases.

**Comment by shaneonabike** [comment]
I thought that I read somewhere that it was important to setup a cron to update the index frequently. Is that simply done through teh regular cron?

I was doing a cron every 30 minutes with the following `sudo -u www-data wp elasticpress index`

**Comment by brandwaffle** [comment]
@shaneonabike nope, any content updated by WordPress will be auto-synced to ElasticPress/Elasticsearch! The only exception is if you have an import script or something like that that does direct SQL queries rather than using WordPress functions, in which case you might run the indexing command at the end of that import script.

**Comment by shaneonabike** [comment]
Ok well it's commented out again. Can we leave this open for a week or two while I just test to make sure that the original problem I reported has been resolved? I noticed it being sent more than every 30 minutes so I just want to make sure it's not actually a bug. Sound good?

**Comment by shaneonabike** [comment]
Sorry the project got delayed. I can confirm that this stopped happening when I disabled the cron job so it was my misunderstanding.
