### ISSUE TITLE
Cannot add new field types to mapping

### ISSUE THREAD

**Issue by aaronjpitts** [10up/ElasticPress#1871]
Hi guys,

I'm building a custom autosuggest and I need certain fields to have a `search_as_you_type` field, therefore to start, I'm trying to add this to the `post_title` field using the below: 

```
add_filter('ep_post_mapping', function ($mapping) {
    $mapping['mappings']['properties']['post_title']['fields']['search_as_you_type'] = array(
        'type' => 'search_as_you_type',
    );

    return $mapping;
}, 10, 1);
```
I run `wp elasticpress index --setup` and the mapping runs fine. But I can see in kibana this field is not being added. Am I missing something?

Running ES 7.5 and latest version of the plugin.

Thanks,
Aaron

**Comment by aaronjpitts** [comment]
Hey guys, can this not be done?

**Comment by aaronjpitts** [comment]
@tlovett1 I'd appreciate it if you could let me know if this is possible? Many thanks!

**Comment by aaronjpitts** [comment]
Is it too much to ask just for a simple indication of if this is possible? Many thanks in advance

**Comment by brandwaffle** [comment]
@aaronjpitts I can confirm there's nothing in ElasticPress that prevents adding any type of mapping or queries. I've never used the `search_as_you_type` search type so I can't be of much more help, but you might try naming the field something besides `search_as_you_type` just in case it's hitting a reserved word or something.

**Comment by nickchomey** [comment]
@aaronjpitts Did you ever figure this out?
