### ISSUE TITLE
Is there any way to custom autosuggest list?

### ISSUE THREAD

**Issue by jurnet** [10up/ElasticPress#1876]
Hi from france,
First I'm very happy because this plugin works very well for me.
Second , I need to custom the autosuggest list with at the bottom of the list something like a link ALL RESULT.
How Can I do that ?

Thank you

**Comment by brandwaffle** [comment]
@jurnet here's some code from another site that does just that. You may have to slightly edit it depending on the specifics of your site and EP hosting, but it should get you most of the way there:
`
            (function() {
                let filterElasticsearchResponse = false;
                let searchTerm;
                $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                        if( settings.url == window.epas.endpointUrl) {
                            filterElasticsearchResponse = true;
                            searchTerm = settings.headers['EP-Search-Term'];
                        }
                    },
                    dataFilter: function (data, type) {
                        const parsedData = JSON.parse(data);
                        // return if not elasticpress search
                        if( !filterElasticsearchResponse ) {
                            return JSON.stringify(parsedData);;
                        }
                        const { hits } = parsedData;
                        if( !hits ) {
                            return JSON.stringify(parsedData);;
                        }
                        hits.hits.forEach(hit => {
                            const title = hit._source.post_title;
                            const modelNumbers = hit._source.meta.model_number;
                            if( modelNumbers.length ) {
                                hit._source.post_title = `(${modelNumbers[0].value}) - ${title}`;
                            }
                        });
                        // append `ALL RESULTS` when there is more results than displaying
                        const total = hits.total;
                        if (  total > 5 ) {
                            const limitedResults = hits.hits.slice( 0, 5 );
                            const allResultsLink = {
                                _source: {
                                    post_id: Math.floor( Math.random() * 100000 ),
                                    permalink: `/?s=${searchTerm}`,
                                    post_title: `Displaying 5 of ${total} results. View all results.`,
                                }
                            }
                            limitedResults.push( allResultsLink );
                            // reset the array that goes back to EP
                            hits.hits = limitedResults;
                        }
                        const newData = JSON.stringify(parsedData);
                        return newData;
                    }
                });
            })();
		`

**Comment by jurnet** [comment]
> me code from another site that does just that. You may have to slightly edit it depending on the specifics of your site and EP hosting, but it should get you most of the way there:

Thanks , but which file I have to modify ?

**Comment by jurnet** [comment]
Please give us a solution @brandwaffle @jasondewitt @pdewouters @mphillips

**Comment by brandwaffle** [comment]
@jurnet you would add this wherever you add custom JS to your theme. This will enable you to keep your customizations through most plugin updates (although there is always a chance the plugin could alter the behavior of the built-in JS request, which would be noted in a changelog).

I'm not sure about the code example you shared, but you do not need to wrap my example code in any sort of function wrapper--the existing code can simply be dropped into your theme.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!

**Comment by fagiani** [comment]
@brandwaffle thanks for sharing this code snippet.

I believe that due to the issue #1839, jQuery support was removed and the `whatwg-fetch` npm library is being used instead.

Inspecting the source code, although not yet documented, I've been able to find a hook here on line 191:
https://github.com/10up/ElasticPress/blob/1c325e8959da4034d40e2fd6947eccfdac106ec4/assets/js/autosuggest.js#L182-L195

That allows for a simplified implementation from [your comment](https://github.com/10up/ElasticPress/issues/1876#issuecomment-682718173) with the code refactor below:

```javascript
(function() {
  window.epDataFilter = function(data, searchTerm) {
     if( data.hits ) {
       data.hits.hits.forEach(hit => {
           const title = hit._source.post_title;
           const modelNumbers = hit._source.meta.model_number;
           if( modelNumbers && modelNumbers.length ) {
               hit._source.post_title = `(${modelNumbers[0].value}) - ${title}`;
           }
       });
       // append `ALL RESULTS` when there is more results than displaying
       const total = data.hits.total.value;
       if (  total > 5 ) {
           const limitedResults = data.hits.hits.slice( 0, 5 );
           const allResultsLink = {
               _source: {
                   post_id: Math.floor( Math.random() * 100000 ),
                   permalink: `/?s=${searchTerm}`,
                   post_title: `Displaying 5 of ${total} results. View all results.`,
               }
           }
           limitedResults.push( allResultsLink );
           // reset the array that goes back to EP
           data.hits.hits = limitedResults;
       }
     }
     return data;
   }
})();
```

Hopefully this will become useful to others in the future!

Keep Rocking!
