### ISSUE TITLE
Show results only if search terms exists in post_title AND meta_field

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#1879]
Ok, hello everyone!

I am trying to get things sorted out, I have a million questions, but for now I am just missing a key feature I would like some help with.

First of all I have managed to add one of my ACF fields into the search fields and weighting tab using the following filter:

```
add_filter(
	'ep_weighting_fields_for_post_type',
	function( $fields, $post_type ) {
		if ( 'post' === $post_type ) {
			if ( empty( $fields['meta'] ) ) {
				$fields['meta'] = array(
					'label' => 'Custom Fields',
					'children' => array(),
				);
			}
      $key = 'meta.classified_color.value'; // Change my_custom_field here to what you need.
			$fields['meta']['children'][ $key ] = array(
				'key' => $key,
				'label' => 'Common color',
			);
		}
		return $fields;
	},
	10,
	2
);
```

After that I managed using the `ep_formatted_args` filter to alter the `$formatted_args` to ensure that the results include ALL of my terms.

```
[query] => Array
        (
            [bool] => Array
                (
                    [should] => Array
                        (
                            [0] => Array
                                (
                                    [multi_match] => Array
                                        (
                                            [query] =>
                                            [type] => phrase
                                            [fields] => Array
                                                (
                                                    [0] => post_title
                                                    [1] => post_excerpt
                                                    [2] => post_content
                                                )

                                            [boost] => 4
                                        )

                                )

                            [1] => Array
                                (
                                    [multi_match] => Array
                                        (
                                            [query] =>
                                            [fields] => Array
                                                (
                                                    [0] => post_title
                                                    [1] => post_excerpt
                                                    [2] => post_content
                                                )

                                            [boost] => 2
                                            [fuzziness] => 0
                                            [operator] => and
                                        )

                                )

                            [2] => Array
                                (
                                    [multi_match] => Array
                                        (
                                            [query] => 
                                            [fields] => Array
                                                (
                                                    [0] => post_title
                                                    [1] => post_excerpt
                                                    [2] => post_content
                                                )

                                            [fuzziness] => 1
                                            [operator] => and
                                        )

                                )

                        )

                )

        )
```

Essentially I added an operator 'AND' in the 3rd query and manually added the fields I want to search in. Now to the question:

Assuming this post:
post_title: 'Volkswagen'
post_content: 'custom description'
meta.classified_color: 'white'

- One of the values inside the custom meta field, is 'white'. When I search for 'white', I get results.
- When I search for a term like 'Volkswagen custom description' that includes terms that exist in post_title and post_content, I get results.
- When I search for 'Volkswagen white' **I don't get any results**.

I have tried adding 'type=cross_fields' because from what I understood, this is the behavior I am expecting. Something along the lines of:

 '**search for all terms inside all fields and find each one at least once in any field**'.

I guess the real question is how do I properly add fields inside the `ep_formatted_args` filters, unless I need to do it using a different filter?

Looking forward to anyone that can help!

**EDIT**: Actually hardcoding the search_fields breaks my synonym filter - removed and updated the code above :/

**Comment by scooterlord** [comment]
I would expect this to be standard practice, despite the fact I can't do it that is :) Anyone??

**Comment by dinhtungdu** [comment]
> I guess the real question is how do I properly add fields inside the ep_formatted_args filters, unless I need to do it using a different filter?

Hi @scooterlord, I'm sorry for this late response. About your question, you can use `ep_search_fields` to include your custom fields: http://10up.github.io/ElasticPress/ep_search_fields.html.

**Comment by scooterlord** [comment]
@dinhtungdu thanks for your reply. Despite the fact that a whole month has passed I still haven't been able to find a resolution to my problem!

The problem is not elasticpress not searching within the fields, but can't combine these fields as I want. I have tried a million different ways, but still haven't come up with a solution.

Essentially I am looking for a way to search for all the **terms in all fields** and give results only when **ALL of the terms** are **at LEAST on one field**.. aka.. terms using AND in ALL fields.

I don't know if this makes sense. Other plugins are doing this by default! Obviously Elasticsearch (and Elasticpress) have other benefits, so I need to find a solution.

Any suggestions/pointers are welcome!

**Comment by dinhtungdu** [comment]
@scooterlord I can't reproduce your issue. I tested with the `develop` branch of ElasticPress, WordPress 5.5.1, and without any filter hooked. I create a post (default post type) with these arguments:
- Title: Volkswagen
- Post content: custom description
- Custom field (text field) classified_color: white

These searches all give me the correct result:
- Volkswagen
- Volkswagen custom description
- Volkswagen white

**Comment by scooterlord** [comment]
@dinhtungdu thanks for trying to help me out!

The expected result would be just ‘Volkswagen white’. I only want results that include each term at least once in all fields.

**Comment by dinhtungdu** [comment]
@scooterlord I see. I misunderstood your problem. Your problem can be solved by modifying $formatted_query. I tested `cross_fields` and the results seems to match with your need. Note that for both action/filter here, you can exclude other queries based on query var.

```
add_filter( 'ep_formatted_args_query', function( $query, $args ) {
	$inner_query = $query['bool']['should'][1];
	$inner_query['multi_match']['type'] = 'cross_fields';
	unset( $inner_query['multi_match']['fuzziness'] );
	return [
		'bool' => [
			'should' => [ $inner_query ]
		],
	];
}, 10, 2 );

add_action( 'pre_get_posts', function( $query ) {
	$query->set(
		'search_fields',
		[
			'post_title',
			'meta' => [
				'classified_color',
			],
		]
	);
} );
```

**Comment by scooterlord** [comment]
@dinhtungdu 

Awesome! This was _almost_ what I was looking for! However, it is only just now that I learned that cross_fields is not compatible with fuzzy search. So, I guess I will have to see how to adjust my search to work as I want it to.

Thanks a million!
