### ISSUE TITLE
Network wide search not working

### ISSUE THREAD

**Issue by alagirirajesh** [10up/ElasticPress#188]
Have done the following:

1. Have successfully installed elasticpress and is working fine. 
2. This is a multisite where each site is a directory for a specific city. 
3. There is a main site and a sub site where the main site does not have any data. Where the subsite does have data. 
4. Elasticpress is network activated. 

Need to know the following:

1. If i need to implement a single search box for the user to search from across the site how do i go about doing it.
2. If i need to implement a search box for the main site which will search across the network and another search box for the sub sites which will search and display only the local sub-site data.

Please advice. Also if there another forum or community where I can ask questions or do i ask on Github itself.

**Comment by tlovett1** [comment]
You need to provide the `sites` parameter to `WP_Query`. For example to search across all the blogs on the network:
```php
new WP_Query( array(
   'sites' => 'all',
   's' => 'Search terms',
) );
```

Or just to search to specific sites on the network (sites with ID 3 and 5):

```php
new WP_Query( array(
   'sites' => array( 3, 5 ),
   's' => 'Search terms',
) );
```

**Comment by alagirirajesh** [comment]
thank you for your response. But as i am new to this can you please let me know which file am i suppose to edit.

**Comment by AaronHolbrook** [comment]
Hi @alagirirajesh - you definitely do not want to edit any core files, instead create a new plugin or modify your theme's functions.php file and use a WordPress action hook ( `pre_get_posts` ) to modify the search query.

http://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts
