### ISSUE TITLE
Avoid fallback to Mysql on Related Posts

### ISSUE THREAD

**Issue by salvoaranzulla** [10up/ElasticPress#1888]
**Describe the bug**

If we implement related posts on single.php, it seems that if ElasticSearch goes to timeout, ElasticPress does a fallback to Mysql. But Mysql cannot generate related posts and Mysql shows latest published posts. 

Is there a way to disable this behaviour? 

**Steps to Reproduce**

Related Posts in single.php

**Expected behavior**

No related posts shown.

**Comment by dinhtungdu** [comment]
Hi @salvoaranzulla, you can filter the `posts_pre_query` and return an empty array if ES fails.

```
add_filter( 'posts_pre_query', function( $posts, $query ) {
    $query_vars = $query->query_vars;

    // Skip if this isn't a find related query.
    if ( empty( $query_vars['more_like'] ) ) {
        return $posts;
    }

    // Skip if ES found related posts.
    if ( ! empty( $pots ) ) {
        return $posts;
    }
   
    return [];
}, 15, 2 ); // We go after ES.
```
