### ISSUE TITLE
Search seems to match characters not words 

### ISSUE THREAD

**Issue by kgrondell** [10up/ElasticPress#1889]
Overall it is great. One thing I am sure is a config I am missing is that when I search say the word duck (which is not in my products) I get 7 results out of 48,000. If I look at the content of those products it does not include the word "duck" but is does include the letter "d" and the "23-uck-4" or the letters "d","u","c","k" scattered throughout.

What am I missing? My goal was searches for a word or words results would have the whole word or words on the page.

**Comment by dinhtungdu** [comment]
Hi @kgrondell, can you turn off the Autosuggest feature and try searching again?

**Comment by kgrondell** [comment]
Hi @dinhtungdu not sure which Autosuggest feature you are talking about. I do not not see anything like that in the plugin and it is not a default function of woocommerce. I am using AWS elastic search.

**Comment by dinhtungdu** [comment]
@kgrondell You can find it under ElasticPress setting page.

**Comment by kgrondell** [comment]
@dinhtungdu I found it under the main ElasticPress tab and it is already turned off.

**Comment by dinhtungdu** [comment]
@kgrondell Can you posted your Query Args and Query Body here. To get them:
- Install and activate [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/).
- Use the frontend product search, search for "duck".
- Check out the Admin bar > Debug > ElasticPress, you'll find query args and query body.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
