### ISSUE TITLE
Buddyboss and Buddypress integration status?

### ISSUE THREAD

**Issue by jeremystory1** [10up/ElasticPress#1891]
What is the status of this plugin's integration with Buddypress/Buddyboss?  
Will this enable Elastic Search to also search user profiles and extended profile fields?  groups?  buddypress/buddyboss activity posts?  Facet by user buddyboss profile type?

We are about to start development to integrate BB with Elastic Search.  Wondering what, if anything, has been done already.  Perhaps we could just add to your plugin.

**Comment by oscarssanchez** [comment]
Hi @jeremystory1 ,

Currently we do not have any deliberate integration with Buddypress/Buddyboss. I believe we have helped people in the past with it, so I am sure there's some people using at least some features, but am not so sure if it is 100% compatible with ElasticPress. 

It would be great if you can test that and we can add to our documentation your findings. PRs are always welcomed as well if you find an issue and would like to fix it.
