### ISSUE TITLE
Ability to remove the 'ElasticPress Indexing' option on Multisite

### ISSUE THREAD

**Issue by johnbillion** [10up/ElasticPress#1893]
**Is your enhancement related to a problem? Please describe.**

On a Multisite installation, super admin users can uncheck the `ElasticPress Indexing` checkboxes on the Network Admin -> Sites screen. This is undesirable when we want to control this option at the network or site level.

**Describe the solution you'd like**

It would be great if there was a filter to disable this checkbox (and its Ajax handler) so we can prevent super admins from changing this setting for each site.

The setting itself can be enforced via the `blog_option_ep_indexable` filter.

<img alt="" src="https://user-images.githubusercontent.com/208434/93602193-382e1980-f9ba-11ea-94fc-cd8f29e55eae.png">

**Comment by jeffpaul** [comment]
@johnbillion are you expecting to then have the `ElasticPress Indexing` checkbox displayed somewhere in the individual network site settings or are you expecting to programmatically control which sites are indexed and which are not?

**Comment by johnbillion** [comment]
The latter. I'd like to say "switch this off, I got this".
