### ISSUE TITLE
pre_get_posts to modify main_query

### ISSUE THREAD

**Issue by hellzapoppin** [10up/ElasticPress#1898]
I've installed ElasticPress on my Wordpress installation and I my posts have gone.

I am using pre_get_posts to remove one category from main query and I noticed it doesn't work proparly with 

`$query->set('cat', '-1')`

Then I tried 

`$query->set('post__not_in', array(1)) `

With this, at least I was able to see my posts but it is still including the category I've removed.

Then I tried set only the category I wanted with "post__in" and this made my posts gone too

Is this a bug or am I doing something wrong?

**Comment by dinhtungdu** [comment]
Hi @hellzapoppin, can you post the full source code you use to modify the main query here, including the hook and the callback.

**Comment by hellzapoppin** [comment]
Sure

```
function remove_home_category( $query ) {
    if( ( !is_admin() && $query->is_main_query() ) && ( $query->is_search() || $query->is_tag() || !$query->is_category(2631) ) ) {
        $query->set( 'ep_integrate', false );
        $query->set( 'cat', '-2631' );
    }
}
add_action( 'pre_get_posts', 'remove_home_category', 1 );
```
Basically I am trying to remove category 2631 from main query except when we are current on 2631 category page.

When I use "-" (minus) not is returned, I've tried "$query->set( 'post__not_in', '2631' );" and the results are back but it is not removing category 2631 from the main query.

**Comment by dinhtungdu** [comment]
> When I use "-" (minus) not is returned, I've tried "$query->set( 'post__not_in', '2631' );" and the results are back but it is not removing category 2631 from the main query.
Because you're excluding category, you need to use `category__not_in`, not `post__not_int`.

However, using `$query->set( 'cat', '-2631' );` is a valid way, can you try:
- Remove the priority `1` of action call, use `10` or remove it entirely.
- use `categrory__not_in` instead of `post__not_in`.

**Comment by hellzapoppin** [comment]
Sorry, I've made a typo, I said **post__not_in** but I meant **category__not_in** and it is not worked.

It is returning all the results and it is not removing category 2631.

Priority 1 I've set because I saw somewhere someone saying to use it, but I've tried 10 before and it not working as well.

**Comment by dinhtungdu** [comment]
Hi @hellzapoppin, can you share with us the ES query body of the main query when you apply the action above. You can get it by installing Debug Bar and Debug Bar ElasticPress, then Load the blog page, Check Admin bar > Debug > ElasticPress.

Besides, can you check to see if your site has any issue indexing posts?

**Comment by lucalbert** [comment]
Hi,

Same probleme here.
With `$query->set( 'cat', '-767' )`, the ES query look like this:

```json
{
  "post_filter":{
    "bool":{
      "must":[
        {
          "bool":{
            "must":[
              {
                "terms":{
                  "terms.category.term_id":[
                    "-767"
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

with `$query->set( 'category__not_in', array(767) )` the ES query is not modified.

Note that with `post__not_in`, it works perfectly!

(I use Query Monitor and Debug Bar ElasticPress to debug query)

**Comment by hellzapoppin** [comment]
> Debug Bar ElasticPress

Sorry I didnt get an email notifing me about your reply, here is the content:

{
    "from": 5,
    "size": 5,
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        },
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "function_score": {
            "query": {
                "match_all": {
                    "boost": 1
                }
            },
            "functions": [
                {
                    "filter": {
                        "terms": {
                            "_id": [
                                3395943
                            ]
                        }
                    },
                    "weight": 20
                }
            ]
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "post"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "paused",
                            "active",
                            "queued",
                            "finished",
                            "autoresponder"
                        ]
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "post_type.raw": [
                                    "post"
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_status": [
                                    "publish",
                                    "paused",
                                    "active",
                                    "queued",
                                    "finished",
                                    "autoresponder"
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "ep_custom_result": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.ep_custom_result.slug"
                    }
                }
            }
        }
    }
}

I dont see any error, I only noticed the progression bar freeze when it is almost finishing and I have to stop and start it again to finish indexing...

**Comment by hellzapoppin** [comment]
I've reindexed it again right now and it didn't freeze as I mentioned.

But I still can see posts from category 2631 on my main query

**Comment by lucalbert** [comment]
@hellzapoppin,

> Do you mean "category__not_in" or "post__not_in"? For me it's not removing the category I asked for ;/

I'm talking about `category__not_in` which is not working.

But `category__not_in` does not modify anything in the query, while `$query->set ('cat', '-767')` modifies it, but not correctly :-/

In revance `post__not_in` works correctly

**Comment by dinhtungdu** [comment]
@hellzapoppin @lucalbert I checked the source code of EP and find out the the `category__not_in` argument is not supported yet, excluding category using a negative value for `cat` is not working as well, the behavior of `cat` does not fully match what it does in `WP_Query`. Marking this one as a bug. For now, you can try using a tax query to exclude your category.

```
$args = array(
    'post_type' => 'post',
    'tax_query' => array(
        array(
            'taxonomy' => 'category',
            'field'    => 'term_id',
            'terms'    => array( 2631 ),
            'operator' => 'NOT IN',
        ),
    ),
);
```

**Comment by hellzapoppin** [comment]
It is working now, thank you!

EP was working on admin page as well but now it is not.

I just tried 

```
    if(is_admin()) {
        $query->set( 'ep_integrate', true );
    }
```

But it made my pending posts disappear... =/

**Comment by oscarssanchez** [comment]
Hey @hellzapoppin , is protected content enabled? There should be no need to set the ep_integrate param to true if it is. 
Kind regards,

**Comment by hellzapoppin** [comment]
> Hey @hellzapoppin , is protected content enabled? There should be no need to set the ep_integrate param to true if it is.
> Kind regards,

No, it's not.

Not sure what happened now, it no longer working on admin page...

**Comment by hellzapoppin** [comment]
My website has a cron job which runs every day and delete posts older than 15 days using a SQL query.

Using SQL query to delete posts doesnt make ElesticPress reindex and these posts are being showed if you make a search...

**Comment by oscarssanchez** [comment]
Hi @hellzapoppin ,

This should be expected if the SQL query is done without using WordPress functions. My suggestion is to make a script using the wp_delete_post() function.

Kind regards,
