### ISSUE TITLE
Caching Documentation

### ISSUE THREAD

**Issue by padams** [10up/ElasticPress#1900]
**Describe your question**

Can someone provide a pointer documentation about how/if/where ElasticPress caches query results? I'm try to make sure that I don't double cache results pages in varnish if EP is also caching results somewhere.

**Comment by felipeelia** [comment]
Hi @padams ,

First of all, sorry for the late response here. In short, ElasticPress does not cache query results but it gives the developer the opportunity to do that though, through filters like [ep_wp_query_cached_posts](http://10up.github.io/ElasticPress/ep_wp_query_cached_posts.html), for example.

Thanks!
