### ISSUE TITLE
meta_query not working when ElasticPress active

### ISSUE THREAD

**Issue by janw-me** [10up/ElasticPress#1902]
**Describe the bug**
I've created a custom pre_get_posts / custom WP_Query that works without elasticpress and does not work with elasticpress.

**Steps to Reproduce**
1) Install a totally new/clean WordPress
2) install and activate Yoast SEO and Elasticpress
3) create and publish page "Do index" and page "Don't index"
4) on the page "Don't index" in the yoast settings set "Allow search engines to show this Page in search results?" to "no"
5) reindex just in case.
6) search on frontend for "index", find both pages, as expected
7) create pre_get_posts filter:

```
add_action( 'pre_get_posts', 'exclude_noindex_pages', 10, 1 );

function exclude_noindex_pages( WP_Query $query ) {
	$query->query_vars['meta_query'] = array(
		'relation' => 'OR',
		array( 'key' => '_yoast_wpseo_meta-robots-noindex', 'compare' => 'NOT EXISTS', ),
		array( 'key' => '_yoast_wpseo_meta-robots-noindex', 'value' => 1, 'compare' => '!=', ),
		// value 1 is don't include page in robots.txt.
	);
	$query->query_vars['ep_integrate'] = false;
}
```
8) search on frontend for "index", find only "index" pages, as expected.
9) In filter set `$query->query_vars['ep_integrate']` to `true`
10) search on frontend for "index", find both pages, This is not as expected..

**Environment information**
ElasticSearch:6.8.12
Wordpress, Yoast & ElasticPress, latest versions

Is there specific information you need I left out?
I've tried a few things, is this because the post_meta starts with an underscore?
Am I missing something?

Hope you can help me.

**Comment by dinhtungdu** [comment]
@janw-me Because `_yoast_wpseo_meta-robots-noindex` is a protected meta, ElasticPress won't include it in the document by default, you will need to do it by filtering [`ep_prepare_meta_allowed_protected_keys`](http://10up.github.io/ElasticPress/ep_prepare_meta_allowed_protected_keys.html):

```
add_filter( 'ep_prepare_meta_allowed_protected_keys', function( $allowed ) {
    return $allowed + ['_yoast_wpseo_meta-robots-noindex'];
} );
```
