### ISSUE TITLE
Autosuggest highlight error

### ISSUE THREAD

**Issue by jens-aggergren** [10up/ElasticPress#1909]
https://github.com/10up/ElasticPress/blob/41022828f5965a7919dcb3d4f3620f4e9efff7ad/assets/js/autosuggest.js#L244

**Describe the bug**
Erroneous Autosuggest search term highlighting resulting in jarbled markup within the autosuggest result text. 

The culprit is the code starting on line 244 of ```assets/js/autosuggest.js```:

```
        searchParts.forEach((word) => {
            const regex = new RegExp(`(${word.trim()})`, 'gi');
            if (word.length > 1) {
                resultsText = resultsText.replace(
                    regex,
                    `<span class="ep-autosuggest-highlight">$1</span>`,
                );
            }
        });
```
Each _word_ is potentially replaced within in the span element inserted by the previous match. 

**Steps to Reproduce**
For example, if the search string is _"Sauce pan"_, and the result text is _"An easy sauce to make in a pan"_, then the first word, "Sauce", is first replaced within the result title, yielding the following:

_*```An easy <span class="ep-autosuggest-highlight">Sauce</span> to make in a pan```*_

This is correct so far. However, when second word _"pan"_ is subsequently replaced within that string, it results in the following jarbled html, since the replace operation is performed on the result of the previous replacement.

_*```An easy <s<span class="ep-autosuggest-highlight">pan</span>  class="ep-autosuggest-highlight">Sauce</s<span class="ep-autosuggest-highlight">pan</span> > to make in a <span class="ep-autosuggest-highlight">pan</span> ```*_

**Expected behavior**

The correct highlight of the above example should be the following:

_*```An easy <span class="ep-autosuggest-highlight">sauce</span> to make in a <span class="ep-autosuggest-highlight">pan</span>```*_

**Environment information**
 - Plugins and version: 3.4.3 or higher

**Additional context**
I'd would suggest refactoring the code in the following way:

```
const regex = new RegExp(`\\b(${searchParts.join("|")})\\b`, "gi");
resultsText = resultsText.replace(
    regex,
    word => `<span class="ep-autosuggest-highlight">${word}</span>`
);
```

**Comment by dinhtungdu** [comment]
Hi @jens-aggergren, thanks for the report, I can confirm the issue as well as your suggestion. Do you mind crafting a PR for this issue?
