### ISSUE TITLE
PHP Warning due to missing quotes

### ISSUE THREAD

**Issue by thomasdiesenreiter** [10up/ElasticPress#1917]
**Describe the bug**
PHP Warning:  Use of undefined constant EP_IS_NETWORK - assumed 'EP_IS_NETWORK' (this will throw an Error in a future version of PHP) in /var/www/cba/wp-content/plugins/elasticpress/includes/classes/SyncManager.php on line 155

**Steps to Reproduce**

Use current version, look into apache error log

**Expected behavior**
No error

**Screenshots**

**Environment information**
Linux

**Additional context**
Fix it here:
`		if ( defined( 'EP_IS_NETWORK' ) || ! EP_IS_NETWORK ) {`

**Comment by dinhtungdu** [comment]
@thomasdiesenreiter Thanks for reporting this issue! 🎉
