### ISSUE TITLE
Ep-highlight also highlights image alt-description

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#1920]
As the description says, the function also wraps image `alt` tags, thus breaking the image markup.

Example image:
`<img src="https://domain.com/1598628342057-512x512.jpg" alt="test – Pirelli Cinturato P7 215/55/17 Blue">`

End result:
`<img src="https://domain.com/1598628342057-512x512.jpg" alt="test – Pirelli Cinturato P7 <mark class=" ep-highlight"="">215/55/17 Blue"&gt;`

edit: Added example

**Comment by tlovett1** [comment]
Thanks for the report. We'll get this fixed.
