### ISSUE TITLE
Add Warning to version 3.5 that re-index is needed

### ISSUE THREAD

**Issue by tamara-m** [10up/ElasticPress#1923]
The new version of ElasticPress requires that you run a sync. is displaying after updating to 3.5.

I understand this needs to run the equivalent of wp elasticpress index --setup where indexes are dropped and recreated.

If this is so, a warning in the change log, before hitting that update button, would be appreciated, as this has some implications on busy production environments.

Would like to know if my assumption about the reindexing is correct too, if possible.

Thank you!

**Comment by felipeelia** [comment]
Hi @tamara-m,

First of all, sorry for the late response here. Answering your question, in fact, 3.5 didn't need it and we've removed the version number from the list: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Upgrades.php#L156

Regarding having that info in the Changelog, that is an excellent idea. I'm adding that to our release steps (see #2059).

Thanks!

**Comment by tamara-m** [comment]
Thanks @felipeelia 
Is there any link or info about contributing to ElasticPress?

**Comment by felipeelia** [comment]
Hey @tamara-m! In fact, since January 19th we have a [contributing](https://github.com/10up/ElasticPress/blob/develop/CONTRIBUTING.md) file. Would be that what you were looking for?
