### ISSUE TITLE
Add support for date_query

### ISSUE THREAD

**Issue by jonathanbardo** [10up/ElasticPress#193]
WordPress date_query could easily be implemented using [Elasticsearch range](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_ranges.html).

This could give more advanced facets and give potential bloggers more flexibility.

**Comment by tlovett1** [comment]
Is this related to https://github.com/10up/ElasticPress/issues/168?

**Comment by jonathanbardo** [comment]
It's indeed related. I honestly thought I went through the issues before submitting this one. Sorry!

**Comment by AaronHolbrook** [comment]
Closed - duplicate of #168
