### ISSUE TITLE
search highlighting feature causing PHP warning 

### ISSUE THREAD

**Issue by columbian-chris** [10up/ElasticPress#1931]
PHP is throwing an "Illegal offset type" error at me when I include custom meta fields in my search fields options.

To reproduce, notice that the following will work fine:

```php
$args = array(
    's' => 'my search query',
    'search_fields' => array(
        'post_title',
        'post_content',
        'post_excerpt',
    ),
    'ep_integrate' => true,
);
$post_query = new Timber\PostQuery($args);
```

And then when I add the `meta` option to the `search_fields` array, it will produce this error:

```php
$args = array(
    's' => 'my search query',
    'search_fields' => array(
        'post_title',
        'post_content',
        'post_excerpt',
        'meta' => array(
            'custom_meta_field_1',
            'custom_meta_field_2',
        ),
    ),
    'ep_integrate' => true,
);
$post_query = new Timber\PostQuery($args);
```

Location:
- `wp-content/plugins/elasticpress/includes/classes/Feature/Search/Highlighting.php:136`
`ElasticPress\F\S\Highlighting->add_search_highlight_tags()`
- `wp-includes/class-wp-hook.php:289`
`apply_filters('ep_formatted_args')`
- `wp-content/plugins/elasticpress/includes/classes/Indexable/Post/Post.php:1413`
`ElasticPress\I\P\Post->format_args()`
- `wp-content/plugins/elasticpress/includes/classes/Indexable/Post/QueryIntegration.php:263`
`ElasticPress\I\P\QueryIntegration->get_es_posts()`
- `wp-includes/class-wp-hook.php:287`
`apply_filters_ref_array('posts_pre_qu`ery')
- `wp-includes/class-wp-query.php:2951`
`WP_Query->get_posts()`
- `wp-includes/class-wp-query.php:3448`
`WP_Query->query()`
- `wp-includes/class-wp-query.php:3559`
`WP_Query->__construct()`
- `wp-content/plugins/timber-library/lib/QueryIterator.php:42`
`Timber\QueryIterator->__construct()`
- `wp-content/plugins/timber-library/lib/PostGetter.php:134`
`Timber\PostGetter::query_posts()`
- `wp-content/plugins/timber-library/lib/PostQuery.php:39`
`Timber\PostQuery->__construct()`

**Comment by MediaMaquina** [comment]
I can confirm.

**Comment by halmos** [comment]
I'm also having this issue. I believe it stems from 

```php
			foreach ( $fields_to_highlight as $field ) {
				$formatted_args['highlight']['fields'][ $field ] = [
					'pre_tags'            => [ $opening_tag ],
					'post_tags'           => [ $closing_tag ],
					'type'                => 'plain',
					'number_of_fragments' => 0,
				];
```
found at https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Search.php#L244-L250

When a search query contains `meta` or `taxonomies` fields with a nested array, the `foreach` `$field` in the code above  may be an array, not a string as expected. The array throws an array because it is not a valid key type. 

The code needs to be able to address nested array fields names.

**Comment by Christophvh** [comment]
Having the same issue. Any quick workaround without needing to wait for an update?

**Comment by brandwaffle** [comment]
@Christophvh the code in #1935 should serve as an example until 3.5.1 is released, which will be later this week.
