### ISSUE TITLE
notify of required resync while editing feature settings

### ISSUE THREAD

**Issue by columbian-chris** [10up/ElasticPress#1932]
This morning, I enabled the new "Protected Content" option, and then a complete resync began, which immediately killed my entire previous sync.  It then took over an hour to resync, as our site has hundreds of thousands of posts in it.  This is why we only perform a sync in the early morning during the lowest traffic hours.  

So obviously, if I had known that my setting change required a complete resync, I would not have done so at that time of day.  It be so helpful if there was a warning that a resync will be required before saving a change.  For example, when you select the `Enable` radio button under "Protected Content", a warning would appear next to the `Save` button that says "resync required" or something like that.

**Comment by brandwaffle** [comment]
It would also be nice to have a warning message output when a feature requiring a reindex is activated via WP-CLI.

**Comment by felipeelia** [comment]
Closed by #2491
