### ISSUE TITLE
date_query errors if no hits are returned

### ISSUE THREAD

**Issue by photocurio** [10up/ElasticPress#1938]
**Describe the bug**

A date query that fetches posts after a set date will return PHP errors if no results are found.

**Steps to Reproduce**
this in WP Query:
```
function elastic_query( $query ) {
	if ( ! is_admin() && $query->is_main_query() && $query->is_search() ) {
		/**
		 * Get all the search params from the URL.
		 */

		$timeframe = filter_input( INPUT_GET, 'timeframe', FILTER_SANITIZE_SPECIAL_CHARS );

                $qualified_date_range = null;

		if ( 'last_month' === $timeframe ) {
			$qualified_date_range = '1 month ago';
		} elseif ( 'six_months' === $timeframe ) {
			$qualified_date_range = '6 months ago';
		} elseif ( 'two_years' === $timeframe ) {
			$qualified_date_range = '2 years ago';
                } 

		// Get only results from after a date.
		if ( $qualified_date_range ) {
			$query->set(
				'date_query',
				array(
					array(
						'column' => 'post_modified',
						'after'  => $qualified_date_range,
					),
				)
			);
		}
        return $query;
    } else {
        return $query;
    }
}

add_action( 'pre_get_posts', 'elastic_query' );
```
The above produces sends this to ElasticSearch:
```
"post_filter": {
    "bool": {
        "must": [
            {
                "bool": {
                    "must": [
                        {
                            "range": {
                                "post_modified": {
                                    "gt": "2020-09-27 12:22:47"
                                }
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```
If any search results are found, everything is fine.
If no search results are found, we get an error from the ES debug tool:
```
Warning | Invalid argument supplied for foreach() | 1 | content/plugins/elasticpress/includes/classes/Feature/Facets/Facets.php:338 | Plugin: elasticpress
-- | -- | -- | -- | --
Notice | Undefined index: buckets | 1 | +content/plugins/elasticpress/includes/classes/Feature/Facets/Facets.php:338 | Plugin: elasticpress
```

**Expected behavior**
No PHP error messages from the Debug tool.

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 10.15.7
 - Browser and version: Chrome 86.0.4240.111
 - WordPress version: 5.4-alpha-46813
 
 - <details><summary>Site Health Info:</summary>
   
`
### wp-core ###

version: 5.4-alpha-46813
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: false
user_registration: true
default_comment_status: open
multisite: true
user_count: 5052
site_count: 133
network_count: 1
dotorg_communication: cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: FMC4ME Network Portal (fmc4me-portal)
version: 3.15
author: Peter Mumford
author_website: (undefined)
parent_theme: FMCNA Pamplona (fmcna-pamplona)
theme_features: menus, automatic-feed-links, title-tag, post-thumbnails, custom-header, html5, customize-selective-refresh-widgets, widgets
theme_path: /chassis/content/themes/fmc4me-portal

### wp-parent-theme ###

name: FMCNA Pamplona (fmcna-pamplona)
version: 7.29
author: Peter Mumford
author_website: (undefined)
theme_path: /chassis/content/themes/fmcna-pamplona

### wp-themes-inactive (8) ###

FMCNA experience: version: 1.9, author: Peter Mumford 3235181
FMCNA Help Center: version: 1.6, author: Peter Mumford
FMCNA Newsfeed: version: 1.3, author: Peter Mumford
FMCNA USA Map: version: 1.4, author: Peter Mumford 3235181
FMCNA for Web: version: 1.2, author: Peter Mumford
Newshub: version: 7.34, author: Peter Mumford
Twenty Sixteen: version: 2.0, author: the WordPress team (latest version: 2.2)
USA Map: version: 1.3, author: Peter Mumford 3235181

### wp-plugins-active (31) ###

Advanced Custom Fields: Font Awesome: version: 3.1.1, author: mattkeys
Advanced Custom Fields: Multisite Select -f: version: 1.0.0, author: James H-Hall , forked Peter Mumford
Advanced Custom Fields PRO: version: 5.9.0, author: Elliot Condon (latest version: 5.9.1)
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.5.1, author: Automattic
Breadcrumb NavXT: version: 6.5.0, author: John Havlik
Classic Editor: version: 1.6, author: WordPress Contributors
Debug Bar: version: 1.0.1, author: wordpressdotorg (latest version: 1.1)
Debug Bar ElasticPress: version: 1.4, author: 10up
Document Gallery: version: 4.4.3, author: Dan Rossiter
Editor Menu Capability: version: 2.3, author: Peter Mumford
ElasticPress: version: 3.4.3, author: 10up (latest version: 3.5)
ElasticPress Mods: version: 1.1, author: Peter Mumford
Enable Media Replace: version: 3.4.2, author: ShortPixel
FMCNA custom admin: version: 0.86, author: Peter Mumford 3235181
FMCNA Lockdown: author: (undefined), version: (undefined)
FMCNA Show-Hide Groups: version: 2.3, author: Peter Mumford 3235181
GA Google Analytics: version: 20200815, author: Jeff Starr
JSON Basic Authentication: version: 0.1, author: WordPress API Team
Multisite Enhancements: version: 1.5.2, author: Frank Bültge
Real Media Library: version: 4.10.0, author: devowl.io
Redirection: version: 4.8, author: John Godley (latest version: 4.9.1)
Set Modified Dates: version: 1.0.0, author: Peter Mumford
Shortcodes Finder: version: 1.4.3, author: Scribit
Simple Cache: version: 1.7.4, author: Taylor Lovett
Simple CSV/XLS Exporter: version: 1.5.4.1, author: Shambix
Skip Confirmation On (forked by Peter Mumford): version: 1.0.1, author: Fidgety Lizard
Widget CSS Classes: version: 1.5.4, author: C.M. Kendrick
WP Migrate DB Pro: version: 1.9.8, author: Delicious Brains (latest version: 1.9.13)
WP Migrate DB Pro Media Files: version: 1.4.14, author: Delicious Brains (latest version: 1.4.15)
WP Migrate DB Pro Multisite Tools: version: 1.2.6, author: Delicious Brains
WP Migrate DB Pro Theme & Plugin Files: version: 1.0.5, author: Delicious Brains

### wp-plugins-inactive (28) ###

Advanced Excerpt: version: 4.3.7, author: WPKube
Bootstrap 3 Shortcodes (forked by Peter Mumford): version: 4.0.0, author: Michael W. Delaney, Filip Stefansson, Simon Yeldon, Peter Mumford
Bootstrap for Contact Form 7: version: 1.4.8, author: Felix Arntz
Broken Link Checker: version: 1.11.13, author: WPMU DEV (latest version: 1.11.14)
Contact Form 7: version: 5.3, author: Takayuki Miyoshi
Content Aware Sidebars: version: 3.13, author: Joachim Jensen - DEV Institute
Custom Category Templates: version: 0.2.1, author: Hassan Derakhshandeh
Default featured image: version: 1.6.4, author: Jan Willem Oostendorp
Disable Emails: version: 1.7.0, author: WebAware
Flamingo: version: 2.2, author: Takayuki Miyoshi
Force Login forked Peter Mumford: version: 5.3, author: Kevin Vess
Google Tag Manager per Site: author: Peter Mumford, version: (undefined)
iframe: version: 4.5, author: webvitaly
Media Library Assistant: version: 2.82, author: David Lingren (latest version: 2.84)
Media Modal Demo: version: 1.0-beta, author: Dominik Schilling
MemcacheD Is Your Friend: version: 2.0.0, author: Jeffrey Schutzman - - uses code from Ryan Boren, Denis de Bernardy, Matt Martz, Mike Schroder, Scott Taylor
miniOrange SSO using SAML 2.0: version: 20.0.0, author: miniOrange
No Category Base (WPML): version: 1.3, author: Marios Alexandrou
Pretty Links: version: 3.2.1, author: Pretty Links
Query Monitor: version: 3.6.4, author: John Blackbourn
Regenerate Thumbnails: version: 3.1.3, author: Alex Mills (Viper007Bond) (latest version: 3.1.4)
ShortCode Redirect: version: 1.0.02, author: Cartpauj
Slick Slider: version: 0.5.1, author: Philipp Bammes
TablePress: version: 1.12, author: Tobias Bäthge
The Events Calendar: version: 5.2.0, author: Modern Tribe, Inc. (latest version: 5.2.1)
The Events Calendar PRO: version: 4.7.7, author: Modern Tribe, Inc.
Upgrade for Unattach & Re-Attach Media Attachments: version: 1.2.1, author: Laurence Bahiirwa
WP Redis: version: 1.0.1, author: Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive (latest version: 1.1.1)

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.3.0
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.15.0-72-generic x86_64
httpd_software: nginx/1.14.0
php_version: 7.2.34-4+ubuntu18.04.1+deb.sury.org+1 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 900
memory_limit: 512M
max_input_time: 900
upload_max_size: 1024M
php_post_max_size: 1024M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.7.28-0ubuntu0.18.04.4
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /chassis/content
WP_PLUGIN_DIR: /chassis/content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: true
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`
   </details>

**Additional context**

**Comment by brandwaffle** [comment]
@oscarssanchez @felipeelia looks like we need to check for values in the array before using it here: https://github.com/10up/ElasticPress/blob/c056515aaf4a81afba5138700e9d417871d020fc/includes/classes/Feature/Facets/Facets.php#L338
