### ISSUE TITLE
Abide by 'exclude_from_search' flag.

### ISSUE THREAD

**Issue by ryanboswell** [10up/ElasticPress#194]
We launched ElasticPress on our site last night and found that on search pages it was including results from 'public' post types that we had explicitly excluded from search using the 'exclude_from_search' flag when registering the post type.

Looking through the query integration code, it looks like EP simply unsets the post_type query var when not targeting a specific type or types, which doesn't follow the same limitations that WordPress's core get_posts() function imposes, see references below to where these seem to happen in both:
https://github.com/10up/ElasticPress/blob/master/classes/class-ep-wp-query-integration.php#L143
https://github.com/WordPress/WordPress/blob/master/wp-includes/query.php#L2916

I've got a commit up to a forked repository that seems to do the trick on our site of forcing the limitation on search queries only (other queries are allowed to continue unsetting post_type). Had to do a little massaging of the data since get_post_types() didn't seem to return a compatible array originally, there's possibly a more elegant way to do that, but it works:
https://github.com/ryanboswell/ElasticPress/commit/ecba64c120ee2e824aa0ea497053ab0756b096e4

Any thoughts on this? I was wondering if there was any particular reason why this constraint was left out, or if it was just overlooked on accident.

**Comment by tlovett1** [comment]
I think this was just overlooked. It is worth noting changes in the `develop` branch around this logic that will go live in 1.3: https://github.com/10up/ElasticPress/pull/176

Can you rewrite your commit against develop and open a pull request? We can then backport into master if necessary.

**Comment by ryanboswell** [comment]
Thanks for the quick look over, I've gone ahead and rewritten the commit for develop and opened a PR.
https://github.com/10up/ElasticPress/pull/195

**Comment by AaronHolbrook** [comment]
Closed by #195

**Comment by AaronHolbrook** [comment]
Props @ryanboswell
