### ISSUE TITLE
There was an error updating the synonym list.

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#1941]
If no index has been created and I updated synonyms. I receive this error message:

```
There was an error updating the synonym list.
```

**Comment by scooterlord** [comment]
I am also getting the same error, however, I already have an index.

**Comment by embold-given** [comment]
I feel like this was merged and closed without being addressed. The task it was merged with only dealt with the notification message. It doesn't do anything about not being able to add synonyms.

I'm in the same boat as scooterlord. We had a list of synonyms, now it's gone, when we try to save any new ones, we get the message:
`There was an error storing you synoyms.`

We're on 3.5.2, we have an index, I've checked to make sure we have the "fix" from the linked task. The issue persists.
