### ISSUE TITLE
The ep_formatted_args filter?

### ISSUE THREAD

**Issue by mfs-mindsize** [10up/ElasticPress#1944]
I read about the ep_formatted_args filter here:

https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches

But it's not in this list:

http://10up.github.io/ElasticPress/

I does exist. There are three args passed in. I'm sure you know this :)

However, none the args passed in appear to be JSON (as I think I expected). Maybe I'm missing something? Or there's another filter that replaced this one?

**Comment by oscarssanchez** [comment]
Hi @mfs-mindsize , this is still a PHP array, the final JSON is later encoded here: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L291

You would need to make your modifications on the array using PHP, hope this helps!

**Comment by mfs-mindsize** [comment]
@oscarssanchez - Great. Thanks. 

Is there a reason ep_formatted_args isn't listed in the official docs?
