### ISSUE TITLE
Support the full category__not_in parameter in WP_Query

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#1947]
This is related to a bug reported in #1898. Currently we don't support `category__not_in` and there are issues with negative values passed for `cat`. These should be addressed to ensure closer WP_Query compatibility.

**Comment by oscarssanchez** [comment]
Just updating status of this ticket: Implementation is done but still need to add unit tests.

**Comment by oscarssanchez** [comment]
Unit tests added and in for code review.
