### ISSUE TITLE
Plugin conflicts with "WooCommerce Product Filter by WooBeWoo" causing the filtered shop page not found

### ISSUE THREAD

**Issue by kaitoxdd** [10up/ElasticPress#1948]
**Describe the bug**

Enabling ElasticPress is causing my product filter on shop page invalid when using pagination.
My filter is powered by plugin "WooCommerce Product Filter by WooBeWoo".
**Steps to Reproduce**

1. Go to https://woocommerce-497189-1572133.cloudwaysapps.com/shop/
2. Click on 'Filter by Collections' then choose 'Cats' category (or any category with large amount of products)
3. Wait for the filtered products to load, then press page 2
4. You will be redirected to homepage because the filtered page URL is invalid

**Expected behavior**
When ElasticPress is deactivated, the page 2 is loaded as normal: https://prnt.sc/vc979y with the URL: https://www.prettyneatcreative.com/shop/page/2/?filter_cat_0=561&wpf_count=24

**Environment information**
- Conflicted plugin: https://wordpress.org/plugins/woo-product-filter/
 - Device: Desktop
 - OS: Windows 10
 - Browser and version: Chrome 86.0.4240.111
 - WordPress version: 5.5.3
<details><summary>Site Health Info:</summary>
   `
### wp-core ###

version: 5.5.3
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /blog/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 69832
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html
wordpress_size: loading...
uploads_path: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Flatsome Child (flatsome-child)
version: 3.0
author: UX Themes
author_website: (undefined)
parent_theme: Flatsome (flatsome)
theme_features: core-block-patterns, post-thumbnails, woocommerce, title-tag, automatic-feed-links, customize-selective-refresh-widgets, sensei, html5, menus, post-formats, wc-product-gallery-lightbox, widgets
theme_path: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content/themes/flatsome-child
auto_update: Disabled

### wp-parent-theme ###

name: Flatsome (flatsome)
version: 3.12.3
author: UX-Themes
author_website: http://www.uxthemes.com/
theme_path: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content/themes/flatsome
auto_update: Disabled

### wp-themes-inactive (1) ###

Storefront: version: 2.8.0, author: Automattic,Auto-updates disabled

### wp-mu-plugins (1) ###

skip-cdn-images.php: author: (undefined), version: (undefined)

### wp-plugins-active (74) ###

Advanced Order Export For WooCommerce: version: 3.1.6, author: AlgolPlus, Auto-updates disabled
Advanced Shipment Tracking for WooCommerce: version: 3.1.4, author: zorem, Auto-updates disabled
Akismet Anti-Spam: version: 4.1.7, author: Automattic, Auto-updates disabled
Autonami Marketing Automations Connectors: version: 1.2.0, author: WooFunnels, Auto-updates disabled
Autonami Marketing Automations For WordPress: version: 1.2.2, author: BuildWooFunnels, Auto-updates disabled
Autonami Marketing Automations Pro: version: 1.2.2, author: WooFunnels, Auto-updates disabled
Bridge Connector: author: (undefined), version: 1.0.0, Auto-updates disabled
Category Editor: version: 3.8.2, author: Kevin Heath, Auto-updates disabled
Code Snippets: version: 2.14.0, author: Code Snippets Pro, Auto-updates disabled
Custom Product Tabs for WooCommerce: version: 1.7.6, author: YIKES, Inc., Auto-updates disabled
Custom Product Tabs Pro: version: 1.2.2, author: YIKES, Inc., Auto-updates disabled
Duplicate Page: version: 4.3, author: mndpsingh287, Auto-updates disabled
Elementor: version: 3.0.11, author: Elementor.com (latest version: 3.0.12), Auto-updates disabled
Elementor Pro: version: 3.0.5, author: Elementor.com, Auto-updates disabled
Etsy Integration for WooCommerce: version: 1.1.0, author: CedCommerce, Auto-updates disabled
ExportFeed for WooCommerce Product To Etsy: version: 3.2.1.0, author: ExportFeed.com, Auto-updates disabled
F4 Shipping Phone and E-Mail for WooCommerce: version: 1.0.9, author: FAKTOR VIER, Auto-updates disabled
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: version: 2.17.1, author: XLPlugins, Auto-updates disabled
Finale Email Countdown Timer: version: 1.2.0, author: XLPlugins, Auto-updates disabled
Finale WooCommerce Deal Pages: version: 1.4.1, author: XLPlugins, Auto-updates disabled
Google Tag Manager for Wordpress: version: 1.11.5, author: Thomas Geiger, Auto-updates disabled
Hotjar: version: 1.0.8, author: Hotjar, Auto-updates disabled
HTML in Category Descriptions: version: 1.2.3, author: Arno Esterhuizen, Auto-updates disabled
Interact Quiz Embed: version: 3.0.7, author: The Quiz Collective Inc., Auto-updates disabled
Judge.me Product Reviews for WooCommerce: version: 1.3.8, author: Judge.me, Auto-updates disabled
Kadence WooCommerce Email Designer: version: 1.4.3, author: Kadence WP, Auto-updates disabled
KingSumo Giveaways: version: 1.8.10, author: KingSumo, Auto-updates disabled
Klaviyo: version: 2.3.5, author: Klaviyo, Inc., Auto-updates disabled
LuckyWP Table of Contents: version: 2.1.4, author: LuckyWP, Auto-updates disabled
MyThemeShop Theme & Plugin Updater: version: 3.0.3, author: MyThemeShop, Auto-updates disabled
Next-Cart Product Data Feed: version: 1.0.0, author: Next-Cart, Auto-updates disabled
Next-Cart SEO URLs: version: 1.0.0, author: Next-Cart, Auto-updates disabled
Nextend Social Login: version: 3.0.25, author: Nextendweb, Auto-updates disabled
Perfmatters: version: 1.5.8, author: forgemedia (latest version: 1.6.4), Auto-updates disabled
Product Input Fields for WooCommerce: version: 1.2.7, author: Tyche Softwares, Auto-updates disabled
Rank Math SEO: version: 1.0.51, author: Rank Math, Auto-updates enabled
Redis Object Cache: version: 2.0.15, author: Till Krüss, Auto-updates disabled
Richpanel for WooCommerce: version: 2.2.3, author: Richpanel, Auto-updates disabled
Sezzle WooCommerce Payment: version: 3.1.1, author: Sezzle, Auto-updates disabled
Shortcodes Ultimate: version: 5.9.4, author: Vladimir Anokhin, Auto-updates disabled
Simple History: version: 2.37.2, author: Pär Thernström, Auto-updates disabled
Smush Pro: version: 3.7.1, author: WPMU DEV, Auto-updates disabled
Thrive Quiz Builder: version: 2.3.2.3, author: <a href="https://thrivethemes.com">Thrive Themes</a> (latest version: 2.3.3.3), Auto-updates disabled
Tracking Per Item Add-on: version: 1.3.7, author: zorem, Auto-updates disabled
UpStroke: WooCommerce One Click Upsells: version: 2.2.5, author: buildwoofunnels, Auto-updates disabled
UpStroke PowerPack: version: 1.5.0, author: WooFunnels, Auto-updates disabled
WooCommerce: version: 4.6.1, author: Automattic, Auto-updates disabled
WooCommerce Admin: version: 1.6.2, author: WooCommerce (latest version: 1.6.3), Auto-updates disabled
WooCommerce Email Customizer Plus: version: 1.2.3, author: Flycart, Auto-updates disabled
WooCommerce Modal Fly Cart + Ajax add to cart: version: 1.4.4, author: aThemeArt, Auto-updates disabled
WooCommerce Multi Currency Premium: version: 2.1.9.4, author: VillaTheme (latest version: 2.1.10.1), Auto-updates disabled
WooCommerce New Customer Report: version: 1.1.0, author: SkyVerge, Auto-updates disabled
WooCommerce PayPal Checkout Gateway: version: 2.1.0, author: WooCommerce, Auto-updates disabled
WooCommerce Product Filter by WooBeWoo: version: 1.3.9, author: WooBeWoo, Auto-updates disabled
WooCommerce Product Recommendations: version: 1.4.7, author: SomewhereWarm, Auto-updates disabled
WooCommerce Product Variations Swatches Premium: version: 1.0.2.4, author: VillaTheme, Auto-updates disabled
WooCommerce Sequential Order Numbers: version: 1.9.5, author: SkyVerge, Auto-updates disabled
WooCommerce Smart Coupons: version: 4.11.0, author: StoreApps (latest version: 4.12.0), Auto-updates disabled
WooCommerce Stripe Gateway: version: 4.5.3, author: WooCommerce, Auto-updates disabled
WooCommerce Thank You Page - NextMove: version: 1.14.0, author: XLPlugins, Auto-updates disabled
WooCommerce Thank You Page - NextMove Power Pack: version: 1.2.0, author: XLPlugins, Auto-updates disabled
WooCommerce Update Variations In Cart: version: 1.8.4, author: StoreApps, Auto-updates disabled
WooCommerce Upload Files: version: 57.9, author: Lagudi Domenico, Auto-updates disabled
WooCommerce Zapier: version: 2.0.5, author: OM4, Auto-updates disabled
WooSidebars: version: 1.4.5, author: WooCommerce, Auto-updates disabled
WooSMS - SMS module for WooCommerce: version: 2.0.27, author: BulkGate SMS gateway, Auto-updates disabled
WordPress Users & WooCommerce Customers Import Export(BASIC): version: 2.0.1, author: WebToffee, Auto-updates disabled
WP-Sweep: version: 1.1.3, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WPMU DEV Dashboard: version: 4.10.5, author: WPMU DEV, Auto-updates disabled
WP Rocket: version: 3.7.4, author: WP Media, Auto-updates disabled
WP Rollback: version: 1.7.1, author: Impress.org, Auto-updates disabled
YITH WooCommerce Dynamic Pricing and Discounts Premium: version: 1.7.0, author: YITH (latest version: 1.7.1), Auto-updates disabled
YITH WooCommerce Wishlist Premium: version: 3.0.15, author: YITH, Auto-updates disabled
Zapier for WordPress: version: 1.0.2, author: Zapier, Auto-updates disabled

### wp-plugins-inactive (9) ###

AeroCheckout: Custom WooCommerce Checkout Pages: version: 2.0.10, author: WooFunnels, Auto-updates disabled
ElasticPress: version: 3.5.1, author: 10up, Auto-updates disabled
Envato Market: version: 2.0.5, author: Envato, Auto-updates disabled
Header and Footer Scripts: version: 2.2.1, author: Digital Liberation, Auto-updates disabled
Product Feed PRO for WooCommerce: version: 8.8.0, author: AdTribes.io (latest version: 8.9.9), Auto-updates disabled
Query Monitor: version: 3.6.4, author: John Blackbourn, Auto-updates disabled
Save For Later For WooCommerce: version: 1.5.0, author: StoreApps, Auto-updates disabled
Smart Offers: version: 3.13.3, author: StoreApps, Auto-updates disabled
WooCommerce Product Bundles: version: 6.3.5, author: SomewhereWarm (latest version: 6.4.2), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 10M
upload_max_filesize: 10M
max_effective_size: 10 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 31 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 31 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.9.0-13-amd64 x86_64
httpd_software: Apache/2.4.25 (Debian)
php_version: 7.4.11 64bit
php_sapi: fpm-fcgi
max_input_variables: 9000
time_limit: 180
memory_limit: 512M
max_input_time: 180
upload_max_filesize: 10M
php_post_max_size: 10M
curl_version: 7.52.1 OpenSSL/1.0.2u
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.15-MariaDB-1:10.4.15+maria~stretch-log
client_version: mysqlnd 7.4.11

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content
WP_PLUGIN_DIR: /home/491423.cloudwaysapps.com/htqbqxyyxw/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### luckywp-table-of-contents ###

domVersion: 20031129
libxmlVersion: 2.9.9
intlVersion: 7.4.11
icuVersion: 65.1
settings: {"lwptoc_general":{"min":"2","depth":"6","hierarchical":true,"numeration":"none","numerationSuffix":"none","title":"Table of Contents","toggle":true,"labelShow":"show","labelHide":"hide","hideItems":false,"smoothScroll":true,"smoothScrollOffset":"24"},"lwptoc_appearance":{"width":"auto","float":"none","titleFontSize":"default","titleFontWeight":"bold","itemsFontSize":"90%","colorScheme":"light","backgroundColor":null,"borderColor":null,"titleColor":null,"linkColor":"#c64747","hoverLinkColor":"#c64747","visitedLinkColor":"#c64747"},"lwptoc_autoInsert":{"enable":true,"position":"top","postTypes":["post"]},"lwptoc_processingHeadings":{"postTypes":null},"lwptoc_misc":{"skipHeadingLevel":null,"skipHeadingText":null,"hashFormat":"asheading","hashConvertToLowercase":false,"hashReplaceUnderlinesToDashes":false,"wrapNoindex":false,"useNofollow":false,"showMetaboxPostTypes":null,"listMarkupTags":"div","containerClass":null}}

`
   </details>

**Comment by abdullah1908** [comment]
Hi @kaitoxdd ,

Thanks for reporting the issue. Unfortunately the [site demo](https://woocommerce-497189-1572133.cloudwaysapps.com/shop/) you shared with us is not working at our end. Can you please make it active again so we can have a closer look.

We are also trying to replicate this issue at our end & will get back to you once its done.

Best Regards,

**Comment by kaitoxdd** [comment]
Hello @abdullah1908 ,

I deleted the site demo because I think this support thread is inactive. Also, your latest version of ElasticPress doesn't work with Cloudways elasticsearch so I uninstalled your plugin already.

**Comment by abdullah1908** [comment]
@kaitoxdd ,

We are really sorry for the delayed response as we have a lot tickets in queue. Would you mind to create a new ticket where you can explain what exactly the issue you are facing with Cloudways Elasticsearch? In case if you couldn't configure properly. Cloudways team explained very well about [ElasticPress configuration](https://www.cloudways.com/blog/elasticsearch-on-wordpress/) at their blog.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
