### ISSUE TITLE
How to return only the parent of an attachment

### ISSUE THREAD

**Issue by AlaplayaW** [10up/ElasticPress#1950]
Hello,
I have a CPT (using ACF fields), that have a title, some other taxonomies and a pdf attached file (it's also an attachment file because i need that ElasticPress search in it). When I do a search, when a word is in the CPT title and in the PDF content, I have 2 results in my list. But it is the same CPT (the CPT and it's pdf). I only need to retrieve the CPT title (that contains the pdf file).
Here, my first result is the attached file of my third result.
I want to search words in my entire PDF content, but i only want to see his parent in my search list.
 How can I do that please?

<img width="861" alt="Capture d’écran 2020-11-03 à 18 30 54" src="https://user-images.githubusercontent.com/48011006/98022171-8f226d80-1e05-11eb-8208-153781de5f2f.png">
`<?php

            $args = [
                'post_type' => 'resources',
                'post_per_page' => 0,
                'tax_query' => [],
                'meta_query' => [
                    'relation' => 'AND',
                ],
            ];

            if (isset($_GET['keyword'])) {
                if (!empty($_GET['keyword'])) {
                    $args['s'] = sanitize_text_field( $_GET['keyword'] );
                }
            }

            if (isset($_GET['authors'])) {
                if (!empty($_GET['authors'])) {
                    $args['tax_query'][] = [
                        'taxonomy' => 'authors',
                        'field' => 'slug',
                        'terms' => array( sanitize_text_field( $_GET['authors'] )),
                    ];
                }
            }

            if ($is_search) {
                $query = new WP_Query($args);
            } ?>

            <?php if ($is_search): ?>
                <?php if ($query->have_posts()) : ?>

                    <?php while ($query->have_posts()) : $query->the_post();
                        $file = get_field('resource_pdf_file');
                        $link = $file['url'];
                        $icon = $file['icon'];
                        $current = $post->ID;
                        $parent = $post->post_parent;
                        ?>
                        <?php if($parent == 0) {
                            $result = $current;
                        } else {
                            $result = $parent;
                        }
                        ?>
                        <article class="resources-item-list">
                            <img src="<?php echo $icon; ?>" alt="pdf icon">
                            <h4>
                                <a href="<?php echo $link; ?>"
                                   target="_blank"><?php echo get_the_title($result); ?></a>
                            </h4>
                        </article>`

**Comment by dinhtungdu** [comment]
Close this one as duplicate with #1951
