### ISSUE TITLE
How to display only the parent owner of an attachment pdf file?

### ISSUE THREAD

**Issue by AlaplayaW** [10up/ElasticPress#1951]
Hello, 
I have a CPT (using ACF fields), that have a title, some other taxonomies and a pdf attached file (it's also an attachment file because i need that ElasticPress search in it). When I do a search, when a word is in the CPT title and in the PDF content, I have 2 results in my list. But it is the same CPT (the CPT and it's pdf). I only need to retrieve the CPT title (that contains the pdf file). 
The first result is the attached file of the third one. I need to search words in the whole PDF file, but I only want to see in the results, the parent Post, so the third one. How can I do that pleaaaase?

<img width="861" alt="Capture d’écran 2020-11-03 à 18 30 54" src="https://user-images.githubusercontent.com/48011006/98022779-52a34180-1e06-11eb-8985-a7678aa7b517.png">

`<?php

            $args = [
                'post_type' => 'resources',
                'post_per_page' => 0,
                'tax_query' => [],
                'meta_query' => [
                    'relation' => 'AND',
                ],
            ];

            if (isset($_GET['keyword'])) {
                if (!empty($_GET['keyword'])) {
                    $args['s'] = sanitize_text_field( $_GET['keyword'] );
                }
            }

            if (isset($_GET['authors'])) {
                if (!empty($_GET['authors'])) {
                    $args['tax_query'][] = [
                        'taxonomy' => 'authors',
                        'field' => 'slug',
                        'terms' => array( sanitize_text_field( $_GET['authors'] )),
                    ];
                }
            }

            if ($is_search) {
                $query = new WP_Query($args);
            } ?>

            <?php if ($is_search): ?>
                <?php if ($query->have_posts()) : ?>

                    <?php while ($query->have_posts()) : $query->the_post();
                        $file = get_field('resource_pdf_file');
                        $link = $file['url'];
                        $icon = $file['icon'];
                        $current = $post->ID;
                        $parent = $post->post_parent;
                        ?>
                        <?php if($parent == 0) {
                            $result = $current;
                        } else {
                            $result = $parent;
                        }
                        ?>
                        <article class="resources-item-list">
                            <img src="<?php echo $icon; ?>" alt="pdf icon">
                            <h4>
                                <a href="<?php echo $link; ?>"
                                   target="_blank"><?php echo get_the_title($result); ?></a>
                            </h4>
                        </article>`

**Comment by oscarssanchez** [comment]
If i understood correctly @AlaplayaW , you have a custom post type where you can upload a PDF file right? If the file is being uploaded to your media library, that would be indexed as a post type attachment. In this case your CPT just has a relationship with the attachment, but the attachment itself is a separate post type.

**Comment by AlaplayaW** [comment]
Yeah that's it ! But I need that the search return the parent post, (that have taxonomies). So I could make an advanced search with taxonomies.

**Comment by AlaplayaW** [comment]
I need to index the attachment content for the parent post of the attachment, in which case the search results will include the post the file is attached to.

**Comment by AlaplayaW** [comment]
@oscarssanchez Is it possible to adapt this hack to ElasticPress ?
[https://searchwp.com/documentation/knowledge-base/append-document-content-to-parent-post-content/](url)

**Comment by oscarssanchez** [comment]
@AlaplayaW  I guess you could add the content of the PDF as post meta, like how we do in the documents feature: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Documents/Documents.php

However, I don't think that would be a good thing to do, especially if you have big PDF's and they are attached to multiple posts.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
