### ISSUE TITLE
Sorting by date not working

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#1952]
Hi, I successfully set up Elastic Search and installed the ElasticPress plugin, created the index, and set up the "Search Fields and Weighting" for my custom post type and taxonomy.

My problem is that when a search is made, the posts show up out of chronological order. I'm assuming they are showing up based on the "score" of the search? I tried adding `apply_filters( 'ep_set_default_sort', 'date', 'DESC' );` to my functions.php to change the sort order (is that the correct place to put it?) but it did nothing.

What can I do to make my default search show all the latest posts first?

Thanks!!

**Comment by brandwaffle** [comment]
@shmaltz to use filters you'll want to call `add_filter` with the appropriate arguments and then write a function to return the word "date." Something like 
`add_filter( 'ep_set_default_sort', 'ep_sort_by_date', 10, 2 );
function ep_sort_by_date( $sort, $order ) {
                                 array(
					'date' => array(
						'order' => 'DESC',
					),
				),
}`

Please note this code is not tested and may contain typos.

**Comment by felipeelia** [comment]
As the answer has been answered, and the issue didn't receive any replies for the last month, we are now closing the ticket. If you have any further questions feel free to leave a comment here or open a new issue. Thanks!

**Comment by binu-mobiux** [comment]
Thank you @brandwaffle for the snippet. Got it working in our setup with a minor tweak (post_date_gmt instead of date):
```
add_filter( 'ep_set_default_sort', 'ep_sort_by_date', 10, 2 );
function ep_sort_by_date( $sort, $order ) {
    return array(
        'post_date_gmt' => array(
            'order' => 'DESC',
        ),
    );
}
```
