### ISSUE TITLE
Non-Wordpress indices

### ISSUE THREAD

**Issue by etbassler** [10up/ElasticPress#1954]
**Describe your question**

Is it possible for ElasticPress to pull in indices from non-Wordpress sources? I'm looking to combine a Wordpress index and a Salesforce index into the search results on my Wordpress site.

**Comment by oscarssanchez** [comment]
You may be able to achieve this @etbassler but you would need to query the index directly. You won't be able to use a WP_Query object in this case.

**Comment by felipeelia** [comment]
As the answer has been answered, we are now closing the ticket. If you have any further questions feel free to leave a comment here or open a new issue. Thanks!
