### ISSUE TITLE
User Friendly Dashboard (Don't require WP CLI to do an index)

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#197]
I think this is a blocker for a lot of people, we should revisit how we can do indexing without needing WP CLI.

**Comment by pyroAdrian** [comment]
Any news with this issue ? I am willing to move the app in wpengine but I don't have any option to index the data.

**Comment by tlovett1** [comment]
@pyroAdrian you can ask WP Engine support to run the WP CLI command.

**Comment by pyroAdrian** [comment]
@tlovett1 I already ask them to run the wp cli, but they are saying that is not possible to run CLI commands for user plugins

**Comment by GhostToast** [comment]
@pyroAdrian I actually had a discussion with WPEngine spawned by this comment, and their answer was "Yes, we can run a wp-cli command that uses a user built plugin.  We have done this for other customers in the past.  They just need to make sure the plugin is active."

However, the account in question is on a rather high-end plan. I'm not sure if that is a factor.

**Comment by markjaquith** [comment]
How expensive are the indexing HTTP requests? Couldn't there just be an XHR-powered admin screen that tells the server to do, say, 10 of the indexing requests, and on success, tells the server to do the next 10?

It looks like `_index_helper()` could be further abstracted so that it calls method available outside of WP-CLI that accepts an offset in addition to posts-per-page.

1. [ ] Abstract the indexing function so it can be used outside of WP-CLI.
2. [ ] Create a wp-admin screen, appropriately cap-checked, that uses XHR to keep firing index commands with an increasing offset, until there are no more posts.

Is that is? Any caveats?

**Comment by tlovett1** [comment]
@markjaquith The index requests aren't that expensive. Elasticsearch also has bulk indexing so you can index multiple posts in one request. You could even use non-blocking requests (possibly after confirming the first one is successful).

**Comment by tuanmh** [comment]
I highly support the idea of @markjaquith. This is the same as the plugin "Regenerating Thumbnails' is doing. 

We can run into problem if using WP_CLI in cloud environment. I have to ssh to an instance and do indexing there but I have no idea when this instance is going to be terminated - so indexing can be interrupted in half-way and this happened could be of times to me already.

**Comment by tlovett1** [comment]
Reviving this :)

**Comment by tlovett1** [comment]
@ChrisWiegman working on this.

**Comment by JoseTomasTocino** [comment]
What's the status on this? I'm planning on installing Elasticpress on a network of many WordPress sites (not a multisite but individual sites) and it would be great if wp-cli weren't needed.

**Comment by tlovett1** [comment]
It's in the develop branch and pretty stable. Any testing you could do would be helpful.

**Comment by JoseTomasTocino** [comment]
Well I've just tried it and it works properly, using a blank wordpress site and a Docker container for the ElasticSearch. Looking forward to seeing it in the release branch!

**Comment by lkraav** [comment]
Did 2.1 fix this but the issue was unclosed?

**Comment by Ritesh-patel** [comment]
@lkraav yes, in 2.1 you don't require WP CLI to do indexing, it can be done in WordPress dashboard.
