### ISSUE TITLE
WP_Filesystem() requires arguments in some environments

### ISSUE THREAD

**Issue by pjohanneson** [10up/ElasticPress#1972]
**Describe the bug**

Our environment uses SSH2 to update WordPress files, plugins, etc. In the Documents feature (`includes/classes/Feature/Document.php`), `WP_Filesystem()` is called with no arguments, causing it to return false and shortcut the indexing of document contents.

Adding a `$args` array to the `WP_Filesystem()` call, to provide username, public & private keys, and hostname, fixes the problem.

**Environment information**
 - Device: HP Laptop
 - OS: Ubuntu 20.04
 - Browser and version: Any modern browser
 - WordPress version: 5.5.2
 
 
 - <details><summary>Site Health Info:</summary>
 `
### wp-core ###

version: 5.5.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /index.php/%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/www/vhosts/ep-test.local
wordpress_size: loading...
uploads_path: /srv/www/vhosts/ep-test.local/wp-content/uploads
uploads_size: loading...
themes_path: /srv/www/vhosts/ep-test.local/wp-content/themes
themes_size: loading...
plugins_path: /srv/www/vhosts/ep-test.local/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.5
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: /srv/www/vhosts/ep-test.local/wp-content/themes/twentytwenty
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Nineteen: version: 1.7, author: the WordPress team,Auto-updates disabled
Twenty Seventeen: version: 2.4, author: the WordPress team,Auto-updates disabled

### wp-mu-plugins (3) ###

Attachment Debuggery µ: author: (undefined), version: (undefined)
Dump (debugging tool): author: (undefined), version: (undefined)
ElasticPress debugging µ: author: (undefined), version: 1.0.0

### wp-plugins-active (3) ###

Debug Bar: version: 1.1.2, author: wordpressdotorg, Auto-updates disabled
Debug Bar ElasticPress: version: 1.4, author: 10up, Auto-updates disabled
ElasticPress: version: 3.5.1, author: 10up, Auto-updates disabled

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 4.1.7, author: Automattic, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-42-generic x86_64
httpd_software: Apache/2.4.41 (Ubuntu)
php_version: 7.4.3 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.22-0ubuntu0.20.04.2
client_version: mysqlnd 7.4.3

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/www/vhosts/ep-test.local/wp-content
WP_PLUGIN_DIR: /srv/www/vhosts/ep-test.local/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: not writable
uploads: writable
plugins: not writable
themes: not writable
mu-plugins: not writable

`
   </details>

**Additional context**
This is the reason for #1838.

**Comment by felipeelia** [comment]
This was fixed by #1973 . Thanks @pjohanneson !
