### ISSUE TITLE
Is it possible to filter by multiple authors?

### ISSUE THREAD

**Issue by con322** [10up/ElasticPress#1974]
**Describe your question**
I see `author` and `author_name` `WP_Query` parameters are supported however i was wondering if any of the other author parameters are supported? Specifically I am wanting to filter results by multiple author ID's using the `author__in ` parameter.

Is this possible at the moment or a feature request?

If not currently supported how would you suggest I go about this? I thought I could possible use the `ep_es_query_results` check if author's parameter exists and then filter them with some additional logic at that point.

Thanks :)

**Comment by dinhtungdu** [comment]
Hi @con322, currently, ElasticPress doesn't support `author__in` and `author__not_in` parameters. I created #1976 to address this issue. Thanks for the report!

**Comment by dinhtungdu** [comment]
@con322 It may take time for a new version to release, so in the meantime, you can use this snippet to support `author__in` parameter:
```php
add_filter( 'ep_post_formatted_args', function( $formatted_args, $args, $wp_query) {
    $use_filters = empty( $formatted_args['post_filter'] ) ? false : true;
    $filter = $use_filters ? $formatted_args['post_filter'] : [];
    if ( ! empty( $args['author__in'] ) ) {
        $filter['bool']['must'][]['bool']['must'] = array(
            'terms' => array(
                'post_author.id' => array_values( (array) $args['author__in'] ),
            ),
        );

        $use_filters = true;
    } elseif ( ! empty( $args['author__not_in'] ) ) {
        $filter['bool']['must'][]['bool']['must_not'] = array(
            'terms' => array(
                'post_author.id' => array_values( (array) $args['author__not_in'] ),
            ),
        );
        $use_filters = true;
    }

    if ( $use_filters ) {
        $formatted_args['post_filter'] = $filter;
    }

    return $formatted_args;
}, 10, 3 );
```
