### ISSUE TITLE
Ignore posts in Related Posts feature

### ISSUE THREAD

**Issue by altendorfme** [10up/ElasticPress#1975]
Hi!

We want to use the infinite scroll with results from ElasticPress related posts, but to avoid conflicts it would be necessary to use a filter to ignore the previously loaded postIds.

Any idea?

`ElasticPress\Features::factory()->get_registered_feature( 'related_posts' )->find_related( $post_id, 1 )`

**Comment by dinhtungdu** [comment]
Hi @altendorfme, you can mimic what `find_related` does to solve your problem. Basically, `find_releate` is a custom query. And to get paged results, you need to inject `offset` to the query. For example, you can create a custom function and use it in your ajax callback like below. Note that we do have a filter to  change the query arguments in `find_relate` function, but fo your problem, I think a custom function is better fit.

```php
function find_related_paged( $post_id, $return = 5, $page = 1 ) {
	$args = array(
		'more_like'           => $post_id,
		'offset'              => ($page - 1) * $return,
		'posts_per_page'      => $return,
		'ep_integrate'        => true,
		'ignore_sticky_posts' => true,
	);

	$query = new WP_Query( $args );

	if ( ! $query->have_posts() ) {
		return false;
	}
	return $query->posts;
}
```

**Comment by altendorfme** [comment]
Hi @dinhtungdu very thanks!
This will solve what I need! ;)
