### ISSUE TITLE
Exclude ElasticPress use from archive pages

### ISSUE THREAD

**Issue by seldimi** [10up/ElasticPress#1981]
Is there any way to limit ElasticPress functionality so it will for search results page and not in product archives?

**Comment by CyberCr33p** [comment]
+1 for this.

**Comment by oscarssanchez** [comment]
Hi @seldimi ,

You could probably hook into `pre_get_posts` and check if it is an archive page, if it is, set the `ep_enabled` argument to `false`

Hope this helps
