### ISSUE TITLE
Dequeue highlighting-style.css

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#1982]
Hello,

I want to dequeue the script that adds the `highlighting-style` class - there's no point to have an additional server request, nor you can properly combine it with other css without the nagging about the map file.

I tried `wp_dequeue_style('searchterm-highlighting');` but for some reason it doesn't work. Any ideas?

**Comment by felipeelia** [comment]
Hi @scooterlord ,

Sorry for the late response here but I was able to dequeue the script using the following snippet:

```
add_action(
	'wp_enqueue_scripts',
	function() {
		wp_dequeue_style( 'searchterm-highlighting' );
	},
	11
);
```

Can you please give it a try? Also, for future visitors of this GitHub issue, worth mentioning that the CSS file will be included only if the highlight functionality is enabled.

Thanks!

**Comment by scooterlord** [comment]
Hello, yes, this works! Thank you very much! Looks like it needed the correct priority to work!
