### ISSUE TITLE
Ordering of features

### ISSUE THREAD

**Issue by Rahmon** [10up/ElasticPress#1983]
**Describe the solution you'd like**
On the Features page, the features are listed in the order as they are registered and there is no way to change this order. I would like that the plugin has a way to change the ordering of the features and to chose if a feature should be on the left or right side.

**Additional context**
I'm developing a feature that registers other features (subfeatures) and I would like to keep the main feature on the left side and the subfeatures on the right side. So, preserving the order, the boxes will appear in a consistent way on the features screen.

**Comment by tott** [comment]
Hi Ramon, this definitely is something that could use some work. Do you think you could provide a MR for a potential implementation?

**Comment by Rahmon** [comment]
Yes. I'll do that.
