### ISSUE TITLE
Search Results Not Updating

### ISSUE THREAD

**Issue by benleeth** [10up/ElasticPress#1984]
I have added ElasticPress to a site (production only) and I'm not returning any different results than without. 

API with ElasticPress
[wp-json Production](https://indychamber.com/wp-json/wp/v2/member-listings?t=2020-11-25T18%3A04%3A02.963Z&search=design%20on%20tap&per_page=10)

API without ElasticPress
[wp-json Staging](https://indychambstage.wpengine.com/wp-json/wp/v2/member-listings?t=2020-11-25T18%3A04%3A02.963Z&search=design%20on%20tap&per_page=10)

Weight settings
![Screen Shot 2020-11-25 at 1 34 45 PM](https://user-images.githubusercontent.com/3288142/100268530-2ec5ae00-2f23-11eb-8255-fb936dd63a12.png)

Can anyone tell me what I'm doing wrong or what maybe the cause?

**Comment by felipeelia** [comment]
Hey @benleeth !

As we had the chance to fix your problem through our [consulting services](https://www.elasticpress.io/elasticpress-consulting/), I'm now closing this issue. If you'd like to share the snippet we've come up with, feel free to do it in a comment here :)

Thanks!
