### ISSUE TITLE
Elasticpress not connecting to remote Elasticsearch instance

### ISSUE THREAD

**Issue by freshlinx** [10up/ElasticPress#1993]
I have installed Elasticpress v7.10 on a clean VPS running Ubuntu 18.04.

When I curl localhost:9200 from the machine I get a valid response showing that Elasticsearch is running. I have opened port 9200 using `ufw allow 9200` and the status confirms that port 9200 is open. Elasticsearch is configured by default to work on port 9200 and this has been confirmed by my internal curl request.

The problem is that when I try to connect remotely using the IP of the VPS and port 9200 (`curl 185.143.45.163:9200`) I get response "curl: (7) Failed to connect to 185.143.45.163 port 9200: Connection refused"

Is there something I have missed with configuring Elasticsearch?

/etc/elasticsearch/elasticsearch.yml:

```
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 185.143.45.163
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.seed_hosts: ["host1", "host2"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
```

Your guidance would be very much appreciated.

Kind regards

**Comment by brandwaffle** [comment]
@freshlinx unfortunately we're unable to provide support for Elasticsearch or your server's networking config here. I can confirm that a properly configured Elasticsearch cluster will work with ElasticPress. You might want to try your question on the Elasticsearch forums, or you could also use WP Local Docker or another setup that includes a working Elasticsearch endpoint.
