### ISSUE TITLE
Does EP support wildcard queries? For example: *apple*

### ISSUE THREAD

**Issue by dominikkuen** [10up/ElasticPress#1995]
**Does ElasticPress support wildcard queries?**

I am not able to find anything related to that question in the documentation or source code of the plugin.
The only thing I was able to find is related to wilcard query removal for user searches via filter (ep_user_search_remove_wildcards)
```
GET index-name/_search 
{
  "query": {
    "query_string": {
      "fields": [
        "post_title"
        ],
      "query": "*apple*",
      "default_operator": "AND"
    }
  }
}

```
Any suggestion is highly appreciated as I don't want to implement the "same" functionality via synonym expansions for 1000s of keywords.

**Comment by brandwaffle** [comment]
@dominikkuen yes, you can issue a Wildcard query https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html. The reason we avoid this in the plugin is because it can be relatively slow, but there's no reason it shouldn't work.

**Comment by felipeelia** [comment]
As the answer has been answered, and we didn't have any movement in the issue for a while now, I'm closing the ticket. If you have any further questions feel free to leave a comment here or open a new issue. Thanks!
