### ISSUE TITLE
Can i use your plugin with amazon elasticsearch?

### ISSUE THREAD

**Issue by sovabarmak** [10up/ElasticPress#1996]
Can i use your plugin with amazon elasticsearch?
i tried as here https://github.com/10up/ElasticPress/issues/1523#issuecomment-554398396
but not working for me

**Comment by KalmanG** [comment]
Perhaps an answer to your question.

https://github.com/10up/ElasticPress/issues/790#issuecomment-742082342

**Comment by brandwaffle** [comment]
In order to avoid the header issue, we are going to remove the EP-Search-Term header for non ElasticPress.io requests. Also, for EP.io compatibility we need to mime encode the header see #790

**Comment by brandwaffle** [comment]
@KalmanG the EP-Search-Term header will no longer be sent as of version 3.5.2. Can you test and see if this resolves your issue?

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Thanks!
