### ISSUE TITLE
Strange fields indexing

### ISSUE THREAD

**Issue by dimaggioalessandro** [10up/ElasticPress#1998]
Hi,
my installation has lots of meta.

For each meta, on Elasticsearch DB, are created multiple versions for each data type:
- meta.abstract.boolean
- meta.abstract.date
- meta.abstract.datetime
- meta.abstract.double
- meta.abstract.long
- meta.abstract.raw
- meta.abstract.time
- meta.abstract.value

This is causing _index.mapping.total_fields.limit_ to exceed the default limit of 5000.

Is it normal that all these fields are created?

Thank you

**Comment by Rahmon** [comment]
Hi @dimaggioalessandro.

By default, the ElasticPress will index all public post meta (keys that don't start with an "_" ). You can exclude public meta data using the filter [ep_prepare_meta_data](http://10up.github.io/ElasticPress/ep_prepare_meta_data.html).

**Comment by dimaggioalessandro** [comment]
Ok thank you, I will try. But is it normal that the same meta data is indexed in 8 different forms?

**Comment by Rahmon** [comment]
Yes. The ElasticPress can index public post meta in a variety of formats.

**Comment by felipeelia** [comment]
Hi there! As the question has been answered, I'm closing the issue now.

Further info can be found in the following links:
- [I get the error "Limit of total fields [???] in index [???] has been exceeded"](https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-)
- [How to exclude metadata from indexing](https://elasticpress.zendesk.com/hc/en-us/articles/360052019111)

Thanks!
