### ISSUE TITLE
Weighting and WooCommerce 

### ISSUE THREAD

**Issue by mfs-mindsize** [10up/ElasticPress#2001]
The EP weight settings for WC products do not getting applied to searches does vie the WC Search widget, that is post_type=product.  

**Steps to Reproduce**

1. Install and activate Debug Bar, as well as the EP Debug Bar add-on.
2. Add the (Site) Search widget, as well as a Product Search widget somewhere (e.g., sidebar). 
3. Use the Site search and review the Query Body. You'll see weighting applied.
4. Use the Product Search and review the Query Body. No weighting.

Or do a Site Search and then add &post_type=product to the URL. 

**Expected behavior**

When &post_type=product the weights - as defined on the EP Search fields & Weighting page - will be used for a product search query. 

**Additional context**
This issue appears to be related to:

Issue 1722 [Weighting engine not working with Woocommerce search](https://github.com/10up/ElasticPress/issues/1722) 
PR 1801[ [WooCommerce] Add Fields to the Weighting Dashboard](https://github.com/10up/ElasticPress/pull/1801)

However, we found that we could fix the issue by:

[Weighting.php](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Weighting.php) > method: do_weighting() > 

```
		if ( isset( $args['search_fields'] ) && ! empty( $args['search_fields'] ) ) {
			return $formatted_args;
		}
```
If we remove this conditional (read: wrapped it in another conditional with a filter that returns a bool - so we could toggle it on and off) we were able to get weights add to product searches.

**Comment by mgratch** [comment]
@tlovett1 @moraleida I thought it was worth pointing out that #1801 #1722 are only loosely related to this ticket. Where those tickets are related to weighting WC attributes via the dashboard. This ticket is related to making use of weighting when using any search directly associated with WC. i.e. If you use the WooCommerce included search widget or the default search included with the storefront theme search queries will automatically include `post_type=product` and therefore weighting will not be applied.

**Comment by felipeelia** [comment]
Hi @mgratch , now that #1801 is merged, can you please try the code in the develop branch?

With the change made [here](https://github.com/felipeelia/ElasticPress/blob/b632170a9d8bd4a3c4a3a703dd61a263c4d004d1/includes/classes/Feature/WooCommerce/WooCommerce.php#L436), the WooCommerce feature is not setting `search_field` anymore, then that `if` you pointed out won't be true.

Thanks!
