### ISSUE TITLE
No mapping found for [term_id.long] in order to sort on

### ISSUE THREAD

**Issue by cbratschi** [10up/ElasticPress#2005]
**Describe the bug**

The following error is reported by ElasticSearch:

No mapping found for [term_id.long] in order to sort on

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by cbratschi** [comment]
I could not find term_id.long fieldsin Kibana.

**Comment by cbratschi** [comment]
Yes, reindexing was done using the CLI command.

Elasticsearch is version: 7.9.3

**Comment by felipeelia** [comment]
Did you use the --setup flag, @cbratschi ? That is needed to send the mapping.

**Comment by cbratschi** [comment]
Yes, setup was used:

```
~/wp-cli/wp-cli.phar elasticpress index --setup --show-bulk-errors
```

**Comment by cbratschi** [comment]
The error happens with this query for instance:

```
Args: {
   "body": "{\"from\":0,\"size\":20,\"sort\":[{\"term_id.long\":{\"order\":\"asc\"}}],\"query\":{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"basel\",\"type\":\"phrase\",\"fields\":[\"name\",\"slug\",\"taxonomy\",\"description\"],\"boost\":4}},{\"multi_match\":{\"query\":\"basel\",\"fields\":[\"name\",\"slug\",\"taxonomy\",\"description\"],\"boost\":2,\"fuzziness\":0,\"operator\":\"and\"}},{\"multi_match\":{\"fields\":[\"name\",\"slug\",\"taxonomy\",\"description\"],\"query\":\"basel\",\"fuzziness\":1}}]}},\"post_filter\":{\"bool\":{\"must\":[{\"term\":{\"taxonomy.raw\":\"region\"}},{\"bool\":{\"must_not\":{\"terms\":{\"term_id\":[461302]}}}}]}}}",
   "method": "POST",
   "headers": {
       "Content-Type": "application\/json"
   }
}

Query args: {
   "taxonomy": [
       "region"
   ],
   "object_ids": null,
   "orderby": "term_id",
   "order": "ASC",
   "hide_empty": false,
   "include": [],
   "exclude": [
       461302
   ],
   "exclude_tree": [],
   "number": 20,
   "offset": 0,
   "fields": "all",
   "count": false,
   "name": "",
   "slug": "",
   "term_taxonomy_id": "",
   "hierarchical": false,
   "search": "basel",
   "name__like": "",
   "description__like": "",
   "pad_counts": false,
   "get": "",
   "child_of": 0,
   "parent": "",
   "childless": false,
   "cache_domain": "core",
   "update_term_meta_cache": false,
   "meta_query": "",
   "meta_key": "",
   "meta_value": "",
   "meta_type": "",
   "meta_compare": ""
}
```

The only thing special is that there is also a search term and an excluded taxonomy term. We log all errors and only see errors where a search text is being used in combination with our custom "region" taxonomy.

**Comment by cbratschi** [comment]
I am also seeing this sync error:

[28-Jan-2021 14:29:32 UTC] PHP Notice:  Trying to get property 'term_id' of non-object in /home/xyz/public_html/cms/wp-content/plugins/elasticpress/includes/classes/Indexable/Term/SyncManager.php on line 110

**Comment by felipeelia** [comment]
Thanks for the info @cbratschi . I'll try to replicate the issue locally and I'll be back to you here in the next few days.

**Comment by bogdanarizancu** [comment]
I am also getting the same notice when using Advanced Bulk Editor plugin to bulk save variation attributes:
`Notice: Trying to get property 'term_id' of non-object in ...plugins/elasticpress/includes/classes/Indexable/Term/SyncManager.php on line 114`

I am currently using my own patch for this:

```--- a/web/app/plugins/elasticpress/includes/classes/Indexable/Term/SyncManager.php
+++ b/web/app/plugins/elasticpress/includes/classes/Indexable/Term/SyncManager-new.php
@@ -110,6 +110,10 @@ class SyncManager extends SyncManagerAbstract {
                foreach ( $terms as $term ) {
                        $term = get_term( $term );

+                       if (!is_a($term, 'WP_Term')) {
+                               continue;
+                       }
+
                        if ( ! current_user_can( 'edit_term', $term->term_id ) ) {
                                return;
                        }

**Comment by felipeelia** [comment]
Thanks, @cbratschi, and @bogdanarizancu. I was able to replicate the issue. In fact, we'll have to work on some of these fields, and we'll concentrate that effort in #2044, so I'll close this one. (Please follow that issue to receive any updates about it)

While it is not properly fixed and shipped into a new ElasticPress release, this snippet will help you to have things working again:

```
add_filter(
	'ep_term_formatted_args',
	function ( $args ) {
		if ( empty( $args['sort'] ) ) {
			return $args;
		}

		foreach ( $args['sort'] as &$sort ) {
			foreach ( $sort as $field => $sort_clause ) {
				unset( $sort[ $field ] );
				$field          = preg_replace( '/(.*?)\.long/', '$1', $field );
				$sort[ $field ] = $sort_clause;
			}
		}
		return $args;
	}
);
```

Thanks!
