### ISSUE TITLE
click on autosuggest highlighted word doesn't work

### ISSUE THREAD

**Issue by amanank** [10up/ElasticPress#2008]
**Describe the bug**

In the autosuggest dropdwon clicking on the <mark> text doesn't do anything

**Steps to Reproduce**

1. Enable autosuggest with `$options['action'] = 'select';` i.e. populate search box
2. Type search
3. Click on the marked part of options
4. The autosuggest is closed without updating search box

**Expected behavior**

The selected option text should be populated in search box and form submitted

**Screenshots**

![image](https://user-images.githubusercontent.com/10206965/102939982-30917b80-44a7-11eb-811c-2fa5c5d5bba0.png)

hardcoded `"MARK"` can be replaced by `epas.highlightingTag` i.e.
```
const target = event.target.tagName==epas.highlightingTag 
				? event.target.parentElement 
				: event.target;
```

**Comment by felipeelia** [comment]
Thanks @amanank ! I've created a Pull Request with that code (and a small adjustment).
