### ISSUE TITLE
Implement Geolocation

### ISSUE THREAD

**Issue by GhostToast** [10up/ElasticPress#201]
@tlovett1 Please let me know if this would be better accomplished as a fork, add-on plugin, or if this belongs in the core ElasticPress plugin.

Anyway, the ability to find "things" based on Latitude/Longitude is becoming increasingly important. WPEngine recently went public with a built-in GeoIP which automatically determines a user's location. Being able to utilize this (and geo info from other services) through ElasticPress would be great. Here are some relevant URLs.

http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/geopoints.html
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-filter.html
https://github.com/wpengine/geoip

**Comment by AaronHolbrook** [comment]
Discussed this in hipchat

**Comment by tlovett1** [comment]
@AaronHolbrook what are you guys thinking here? I'm leaning towards separate plugin.

**Comment by AaronHolbrook** [comment]
@tlovett1 yea - this makes a lot of sense as a supporting plugin to EP.

Leaving open for now - feel free to close once this plugin repo has been created.

**Comment by dmcdonald-lhwh** [comment]
Any new developments on geolocation searching with the elasticpress plugin?

I'm interested in distance search and sorting by distance.

Thanks
Dana

**Comment by tlovett1** [comment]
It's something that has definitely been done but not bundled as part of the plugin.

**Comment by pratham2003** [comment]
Can someone provide me a bit more info on this? I'm bit new to elastic press.
How do I set a field or group of field (lat & lng?) as geopoint in the first place?

**Comment by wxactly** [comment]
Hey all - I couldn't find anything out there for geolocation with ElasticPress, so I went ahead and threw something together:

https://github.com/thinkshout/ep-geo

We're currently in development for a project that needs geo query integration with WordPress and ElasticSearch. So, this plugin works for our use case at this point in our project, but it will surely need some more love if it has any hope of being useful in the general case. Nonetheless, I wanted to put this out there in case someone wanted to take a look or take it for a spin!

**Comment by AaronHolbrook** [comment]
Nice work @wxactly ! Way to bring it together in a simple module

**Comment by eriteric** [comment]
Is this possible now? Can we do a radius search in elasticpress?
