### ISSUE TITLE
Show all query results

### ISSUE THREAD

**Issue by j040n3t0** [10up/ElasticPress#2010]
The current version of ElasticPress Plugin is limited only 10000 results, because this is a elasticsearch pattern, but is possible to change the search pattern to show all results.

**File:** Elasticsearch.php
**Line:** 258

Old version:
`$path = $index . '/_search';`
New version:
`$path = $index . '/_search?track_total_hits=true';`

**Comment by felipeelia** [comment]
Hi @j040n3t0 ,

Thank you for opening this issue! Although it is an interesting point, I don't think it'll be something meaningful for all users at this point. For those willing to achieve that, the following snippet can help:

```
add_filter(
	'ep_search_request_path',
	function ( $path ) {
		if ( str_ends_with( $path, '_search' ) ) {
			$path .= '?track_total_hits=true';
		}
		return $path;
	}
);
```

I'm closing the issue now but if you have any other ideas, feel free to create new ones. They are always welcome!
