### ISSUE TITLE
Slow Query using ElasticPress

### ISSUE THREAD

**Issue by vedagames** [10up/ElasticPress#2013]
Hi!
I have installed ElasticPress on My Dedicated Server.
I have installed Plugin Called ElasticPress. Connected to my server
indexing got completed. I have enabled ElasticPress For my woocommerce From Dashboard Settings. Now I need any additional step like modify any search related files etc? I have added debug bar suggested by ElasticPress and Seen that its connecting my ElasticSearch server and query for product that I have searched and time for query is like 799 MS. But My site still take about 2 minutes for display result. I can also see that when I search, its still call mysql database. Let me know if anyone here can help me for same.
Thanks!

**Comment by brandwaffle** [comment]
@vedagames unfortunately, other plugins, themes, and even layout builders can add significant overhead on WordPress sites, and it seems you're seeing this on your search. For example, some plugins re-query each post to render meta on the page, or other non-performant actions.

If you see other queries that are complex and running slowly in MySQL (over 500ms is a good benchmark), you can run these through ElasticPress as well by adding the **ep_integrate => true** parameter to WP_Query, usually via a **pre_get_posts** hook. However, if what you have is a lot of smaller MySQL queries, you might actually slow things down by moving too many queries to ElasticPress, as there is a baseline latency in connecting to and querying Elasticsearch.

It's also worth noting 799MS is not a very fast response time for that query, so you might also have performance/tuning issues with Elasticsearch.
