### ISSUE TITLE
Enhancement: implement 'NOT LIKE' operator for meta_query

### ISSUE THREAD

**Issue by Thalvik** [10up/ElasticPress#2015]
Hello,

In postmeta table, I have an ACF field for type check boxes. These check boxes allow more that one value to be selected. Then the field is saved in postmeta table as serialized data, like so:

`a:2:{i:0;s:7:"value_1";i:1;s:7:"value_2";}`

When I want to query a post with specific value, I would just put a meta query with 'LIKE' operator:

```php
$args['meta_query'][] = [
    'key' => 'options',
    'value' => 'value_1',
    'compare' => 'LIKE',
];
```

However, if I want to use a 'NOT LIKE' operator, for example to search for only 'value_1' and not 'value_2':

```php
$args['meta_query'][] = [
    'key' => 'options',
    'value' => 'value_1',
    'compare' => 'LIKE',
];

$args['meta_query'][] = [
    'key' => 'options',
    'value' => 'value_2',
    'compare' => 'NOT LIKE',
];
```

this is parsed as terms query passed to ElasticSearch, because the operator for 'NOT LIKE' is not implemented in Indexable.php class and because of default switch when parsing meta_query in build_meta_query function.

I would like to implement a 'NOT LIKE' operator in this function like this for example:

```php
} elseif ( in_array($compare, ['like', 'not like'], true)) {
```

and then in the actual switch for it:

```php
case 'not like':
if ( isset( $single_meta_query['value'] ) ) {
    $terms_obj = array(
        'bool' => array(
            'must_not' => array(
                array(
                    'match_phrase' => array(
                        $meta_key_path => $single_meta_query['value'],
                    ),
                ),
            ),
        ),
    );
}
break;
```

With this condition, my query works as expected.

There are currently no other alternatives for querying serialized data for ACF as far I know, so this is the only way I got it to work. I would like your opinion if should be implemented also in next version of ElasticPress. Thanks.

P.S. Plugin works great for me, thanks for all your work :)

**Comment by brandwaffle** [comment]
@Rahmon to estimate effort and feasibility.

**Comment by abdullah1908** [comment]
@Thalvik thanks for this suggestion. We will definitely take this under consideration and could see this being part of a future release as a part of an additional feature module similar to the WooCommerce one. We will update the ticket as we decide on a path forward.
