### ISSUE TITLE
Add custom meta

### ISSUE THREAD

**Issue by infospherebv** [10up/ElasticPress#2018]
We are checking out the Elasticpress plugin to add fast filters to a customer's webshop. The filters are stored in custom tables as the use of the standard taxonomies in a large amount has a high impact on the performance of a Woo webshop.

The customer has around 900 different custom meta item. Mainly becouse this contains a huge amount of different product types which all have their own meta. We tried adding this meta to the Elastics index however this exceeds the maximum amount of 5000. We this this is because all meta use sub meta values for value, raw, boolean, date, datetime and time. Which makes the custom meta items to become 900 x 6 = 5400 in total and that really blows up the index.

We currently use the filter 'ep_prepare_meta_data' to add the custom meta items to the index. I am however wondering if it is possible to also add an extra tree of meta to the index next to "terms" and "meta" such as "filters" in which we could then only store one single value in stead of the 6 that are currently in meta. We would like to know if and how this could be done or if there is an alternative. Also if it is possible to add the extra tree of data, what would we have to define in the config mapping using the "ep_config_mapping" filter. I hope that someone can help us with this.

**Comment by Rahmon** [comment]
Hi @infospherebv .

Sorry for the late response here. I'm investigating what's a good approach in this case. I'll try to put a snippet together in the next few days and share it with you here, okay? 

If you had the chance to achieve that already, please let us know and, if possible, share it here :)

Thanks!

**Comment by Rahmon** [comment]
Hi @infospherebv .

I think that to add an extra tree of meta you can add a new field to the document and let Elasticsearch determine the datatype and automatically adds the new field to the type mapping. 

For example, to add the field `custom_filters` you can use the filter `ep_post_sync_args`:

```php
add_filter( 
	'ep_post_sync_args',
	function(  $post_args, $post_id  ) {
			$post_args['custom_filters'] = array(
				'filter1' => 'computer',
			);

		return $post_args;
	},
	10,
	2
);
```
When you run the indexing, all posts will have this new field `custom_filters.filter1` with the value `computer`.

You can check it running:
```shell
curl -XGET "http://elasticpress.test:80/__elasticsearch/_search" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match_all": {}
  },
  "_source": ["custom_filters"]
}'
```
To include this field in the search, you need to enable it using the filter `ep_weighting_configuration_for_search`:

```php
add_filter(
	'ep_weighting_configuration_for_search',
	function( $weight_config ) {
		$weight_config['post']['custom_filters.filter1'] = array(
			'enabled' => 1,
			'weight'  => 1,
		);


		return $weight_config;
	}
);
```

If you want more control over the mapping, maybe you can add a [dynamic template](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/dynamic-templates.html) using the filter `ep_config_mapping`.

Can you please test that and let us know your findings? Thanks.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
