### ISSUE TITLE
Check for 'http://' prefix and prepend if not present

### ISSUE THREAD

**Issue by zamoose** [10up/ElasticPress#202]
Just wasted a good bit of time trying to debug why an EP setup wasn't working -- turns out `define('EP_HOST', '[IP address]:[port]');` is treated *completely* differently than `define('EP_HOST', 'http://[IP address]:[port]');`

Either the docs should be updated to reflect this necessity, or the code should prepend a protocol specifier.

**Comment by tlovett1** [comment]
Submit a PR? The docs specify http://

**Comment by tlovett1** [comment]
@zamoose ping :)
