### ISSUE TITLE
PHP - checking tags and deleting from index upon post create or update

### ISSUE THREAD

**Issue by neilb400** [10up/ElasticPress#2021]
Hi there,

I'm trying to adapt the code in [this comment in post 253](https://github.com/10up/ElasticPress/issues/253#issuecomment-98881570) to delete a post from the index on our site upon creation or update and it contains either or both of two specific tags.

The adapted code so far is:

```
function oursite_elastic_ep_stop_sync( $return_val, $post_args, $post_id ) {
	$stop_index = $return_val;
	$oursitetags = get_the_tags( $post_id );
	if ($oursitetags) {
		foreach($oursitetags as $oursitetag) {
			if ( $oursitetag->term_id == 256 || $oursitetag->term_id == 259 ) {
				$stop_index = true;
			}
		}
	}
    if ( true === $stop_index ) {
		// What goes here?
        return true;
    }

    return $return_val;
}

add_filter( 'ep_post_sync_kill', 'oursite_elastic_ep_stop_sync', 10, 3 );
```

The code in the (admittedly a bit dated) issue refers to calling a function ep_delete_post() but that apparently doesn't exist.  I  wonder what the up-to-date call is to carry out the deletion from the index, please?

**Comment by brandwaffle** [comment]
@neilb400 at first glance it looks like this code should cause EP to skip indexing this post. The only reason you'd need to delete anything in this case is if you have already indexed, then add this code. In that case a full reindex should clear the posts and they should not be reindexed. Have you debugged to ensure your function is returning true?

Also, I'd avoid directly referencing the tag IDs if you can--you can always get the ID from the slug, which will work even if you delete and re-add the tag, for example.

**Comment by neilb400** [comment]
> @neilb400 at first glance it looks like this code should cause EP to skip indexing this post. The only reason you'd need to delete anything in this case is if you have already indexed, then add this code. In that case a full reindex should clear the posts and they should not be reindexed. Have you debugged to ensure your function is returning true?

Thanks for the reply.  Yes, there is separate filtering code in place, which works well on a full re-index.  What I am trying to achieve is immediately deleting a single post from the index without a full re-index if one or both of those tags are added to an existing post.  It looked possible based on the post I referenced, but maybe it isn't possible or necessary.

> Also, I'd avoid directly referencing the tag IDs if you can--you can always get the ID from the slug, which will work even if you delete and re-add the tag, for example.

Fair point!

**Comment by brandwaffle** [comment]
@neilb400 gotcha, that makes sense! To delete the post based on the conditional during (re)sync, you'll want to call this function:
`\ElasticPress\Indexables::factory()->get( 'post' )->delete( POST_ID );`

Let me know if your function works with that change!

**Comment by neilb400** [comment]
> Let me know if your function works with that change!

Yes, perfectly.  Thank you so much for the answer.

**Comment by brandwaffle** [comment]
Nice! I'm closing out this ticket. If you have any other questions, feel free to open a new one. Thanks for using ElasticPress!
