### ISSUE TITLE
Elasticsearch version 7.10.1 not supported

### ISSUE THREAD

**Issue by Louiseh86** [10up/ElasticPress#2025]
Hi, we have installed version 3.5.1 from the WordPress plugins repository but I get the error below when activated:

" Your Elasticsearch version 7.10.1 is above the maximum required Elasticsearch version 7.9. ElasticPress may or may not work properly. "

I am unable to sync and there is no noticeable improvement in search speed, so I guess its not working.

Are you still providing support for this plugin and if so will you be making it compatible with Elasticsearch version 7.10.1 ?

Thank you

**Comment by brandwaffle** [comment]
Hi @Louiseh86,

Unlike WordPress, Elasticsearch often introduces breaking changes, so we have to test extensively before bumping the maximum supported version. Please note 7.9 is fully supported and approximately 4 months old--it's the version we recommend you use right now.

You can also use 7.10.1, but note you may see occasionally unexpected behavior. If you would like to contribute back to this free plugin, you can always submit those as bug reports and we will work towards making the plugin compatible.

I would also note that, to avoid compatibility issues or setting up and maintaining your own Elasticsearch instance (not to mention the implications of things like autosuggest URL security), we offer our ElasticPress.io service. Should you decide to run your own instance, this is certainly possible, but you will need to be able to debug any unexpected behavior specific to your install.
