### ISSUE TITLE
Enabling x-pack with external elasticsearch server

### ISSUE THREAD

**Issue by Ignasrimkunas** [10up/ElasticPress#2026]
Hello! I've got an external Elasticsearch server running on a VPS, the question is, how to do I go about implementing x-pack with my WordPress running on shared hosting? I know how to enable x-pack and got the passwords generated although when this feature is enabled ElasticPress comes with "There is a problem with connecting to your Elasticsearch host". Do you know how to pass the credentials generated by Elasticsearch server to ElasticPress plugin so connection is made. 

Any suggestions of making my Elasticsearch server secure and working only with my EP installation is welcome 
**Describe your question**

**Comment by brandwaffle** [comment]
@Ignasrimkunas you can use the ES_SHIELD parameter in wp-config.php:

`define( 'ES_SHIELD', 'username:password' );`

If you are planning to self-host Elasticsearch and activate Autosuggest, please be conscious of security implications.

**Comment by Ignasrimkunas** [comment]
Thank you! Works like a charm, will be sure to test this out with HTTPS as well. I'm not planning on using autosuggest.

**Comment by PointPubMedia** [comment]
@Ignasrimkunas 

We are having the same setup as you but we are unable to connect EP to ES, we are having 401 error, about missing authentication credentials for REST request...

**Comment by mailshuxin** [comment]
> @Ignasrimkunas you can use the ES_SHIELD parameter in wp-config.php:
> 
> `define( 'ES_SHIELD', 'username:password' );`
> 
> If you are planning to self-host Elasticsearch and activate Autosuggest, please be conscious of security implications.

Thank you very much for your help.
