### ISSUE TITLE
Related posts in template with filter.

### ISSUE THREAD

**Issue by APLJ1976** [10up/ElasticPress#2038]
With some help i have Elasticpress / Elastic search up and running at my server.

I am not a programmer, so please bear with me. I have a lot of posts and YARRP (related posts plugin) seems to slow down the website a lot, so i want to use the Elasticpress related posts feature. but i don't know how to actually implement it in the template.
I read i have to use below

`ElasticPress\Features::factory()->get_registered_feature( 'related_posts' )->find_related( $post_id, $return = 5 );`

1) How can i turn that in to a loop that displays these 5 related posts?
2) Can i also filter by post type and use it twice in a template? So for example show related 'products' and show related 'articles' on the same page where 'products' and 'articles' are CPT

**Comment by brandwaffle** [comment]
Hi @APLJ1976,

Related Posts is available as a Widget as well as a Block Editor Block to make it easy to add to your site with no code whatsoever!

To filter the query by a post type, you would want code something like this (please note this code has not been tested and should not be added to a production site without testing on staging first):
```
add_filter( 'ep_formatted_args', 'ep_filter_related_posts', 11, 2 );
function ep_filter_related_posts( $formatted_args, $args ) {
  if ( !isset( $formatted_args['query']['more_like_this'] && !empty( $formatted_args['query']['more_like_this'] ) {
    return $formatted_args;
  }

  $formatted_args['query']['filter'] = array(
    'match' => array(
      'post_type.raw' => 'products'
    );
  );
}
````
You'll likely need some additional logic to determine what type of related posts you're on (products vs articles) in addition to what I have there (i.e. it contains the more_like_this clause), but this example should get you on the right track.

If you do need direct engineering support to help implement this, we do also offer [consulting services](https://www.elasticpress.io/elasticpress-consulting).
