### ISSUE TITLE
Error when bulk indexing

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#204]
Getting an error part way through index: 

Performed: `wp elasticpress index --setup`
After 50 or so batches sent, received error: `Operation timed out after 5001 milliseconds with 0 bytes received`

Is this a CURL error? Is their a timeout setting I can edit?

May want to include handling of this error in Readme

**Comment by tlovett1** [comment]
Seems like `wp_remote_request` is timing out. For now, you can filter `http_request_timeout` and set it to something like 30. I'll write a patch to help.

**Comment by psorensen** [comment]
Filtering `http_request_timeout` did the trick. Thanks.
