### ISSUE TITLE
Related posts showing nothing or last posts.

### ISSUE THREAD

**Issue by APLJ1976** [10up/ElasticPress#2046]
I have related posts active in my template, but i have two issues.

1) When it works last posts are shown and not related posts. 
2) Sometimes nothing is displayed at all and debugging shows this message "Invalid argument supplied for foreach()"

I copied the curl request: 
`curl -XPOST -H 'Content-Type: application/json' -d '{"from":0,"size":5,"sort":[{"post_date":{"order":"desc"}}],"query":{"more_like_this":{"like":{"_id":438977},"fields":["post_title","post_content","terms.post_tag.name"],"min_term_freq":1,"max_query_terms":12,"min_doc_freq":1}},"post_filter":{"bool":{"must":[{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}}]}}}' 'http://localhost:9200/mysitecom-post-1/_search'`

Query result from query monitor:

`{
    "took": 6,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 0,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    }
}`

I am a bit lost on where to start to findout how come there are no related posts returned just the last (or nothing).

**Comment by felipeelia** [comment]
Hi @APLJ1976 ,

Looking at the query being sent, I can see:
1. It is searching just for products
2. It is using the post/product with ID 438977 to compare
3. It is searching just for titles, contents, and post tags.

Is that what you really want to get done? If so, do you have those three fields properly set for your products? A few other things that may help us to understand better your problem:
- Which Elasticsearch version are you using
- Did you make a complete reindex already?
- How many products do you have

Thanks!

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
