### ISSUE TITLE
How can we cap the number of results?

### ISSUE THREAD

**Issue by neilb400** [10up/ElasticPress#2055]
Is it possible to alter the query from EP so that the Elastic appliance is asked to cap the number of results if there is more than a particular number found (500 in our intended use case)?

In other words, if there is going to be more than 500 results returned by the appliance, we only want the 500 most relevant / oldest / newest (depending on what the end user has chosen) to be returned.

We would prefer it to be "native" so that EP and WP see 500 results, rather than any workarounds at the website end, if that's possible.

I hope that makes sense but I'm happy to clarify anything.

Thanks in advance.

**Comment by brandwaffle** [comment]
Hi @neilb400,

ElasticPress will respect the value set by the WP_Query, which usually comes from the posts per page setting in your WordPress Dashboard, but could be overridden by another plugin for any particular query. That said, ElasticPress tries to do exactly what you're describing--inherit the per_page parameter of a query in order to ensure that the number of results returned by Elasticsearch is the same as the number returned by WordPress.

**Comment by neilb400** [comment]
Thank you for the response.

How about capping the total number of results across all pages, when pagination is in use?

The setting in WP is 14 results per page, so we want WP to see that only 500 results have been returned from the query and:

- this number to be reflected in the "X search results found for:" line shown to the user
- there is nothing beyond page 36 of the results

Essentially we want the query to never return more than 500 results and for this to work with pagination.

Is that possible?

**Comment by felipeelia** [comment]
Hi @neilb400 ,

It seems it could be achieved through the `ep_es_query_results` filter, changing the `found_documents` value.

https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L407
http://10up.github.io/ElasticPress/ep_es_query_results.html

The code would be something similar to this:

```
add_filter(
	'ep_es_query_results',
	function( $results ) {
		$results['found_documents'] = ( $results['found_documents'] > 500 ) ? 500 : $results['found_documents'];
		return $results;
	}
);
```

Can you please give it a try and let us know if that works for you? Thanks!

**Comment by neilb400** [comment]
> Can you please give it a try and let us know if that works for you? Thanks!

Yes - perfect.  Thank you; that's very much appreciated.
