### ISSUE TITLE
My custom query in elasticpress

### ISSUE THREAD

**Issue by maverick-gdf** [10up/ElasticPress#2058]
I would like to index custom mysql tables in elasticpress. It's possible to do it?

**Comment by abdullah1908** [comment]
@maverick-gdf 

ElasticPress uses an Indexable class which can be extended to connect any custom table in WordPress to use Elasticsearch. You can take a look at the Post, Term, or User Indexables (which are built into the plugin) for examples. It’s not a small undertaking, however, so keep that in mind. However EP [dev documentation](http://10up.github.io/ElasticPress/tutorial-indexables.html) can also be helpful for you.

**Comment by felipeelia** [comment]
HI @maverick-gdf,

Just to expand @abdullah1908 's reply here a bit:

To index the data, you can use an existent Indexable, create a new one, or directly index on ES. Ultimately, you will need to properly format your data and then call the `\ElasticPress\Elasticsearch::factory()->index_document()` function passing the index, the type, and the document/data you want to index. That will store your data on Elasticsearch.

To have it returned on whatever ES query you'll run, you'll have to tweak that query using a filter. That could be `ep_formatted_args`, `ep_post_formatted_args`, `ep_user_formatted_args_query`, or `ep_term_formatted_args_query`, for example. You can also give a look at the `QueryIntegration` classes, like `ElasticPress\Indexable\Post\QueryIntegration` for some inspiration.

As this is a bit outside of the scope of what ElasticPress aims to offer, I'll go ahead and close the issue. Thanks!
