### ISSUE TITLE
ElasticPress is (apparently) messing with my product filters

### ISSUE THREAD

**Issue by Rayuaz** [10up/ElasticPress#2060]
I recently installed ElasticPress on my woocommerce store, and it's working fine -- the product page is showing normally, and the search bar is working fine with the new elastic capabilities. However, when I try to use the product filters, nothing shows up, the query simply doesn't work. If I deactivate Elasticpress, however, the filters work normally. [This is the query](https://codeshare.io/GAwO4x) [1]:

I tried using the debug bar to see if there were any errors happening during the query, and it didn't point at anything different. The only "errors" it pointed out were [these undefined indexes](https://i.ibb.co/dp3zhsR/image.png), which I don't belive have anything to do with the problem, because they happen with or without Elastic.

[This is](https://codeshare.io/axNEkX) [2] the generated query without any filters active (just the default woocommerce query, which works without any problems).

[This is](https://codeshare.io/2p3Eg9) [3] the generated query when I set the "autor" filter as "Arcane Minis", and the "orderby" to "popularity".

And lastly, [this is](https://codeshare.io/2B9QbK) [4] the filtered query without elastic press.

The temporary "solution" I found to the problem was adding `$q->set('ep_integrate', false);` to my query, so that it disables EP when the filters are active, but this is far from ideal, because I _want_ EP's functionalities to work with my filters.

**-- EDIT --**

After some more fiddling around, I have narrowed the problem to custom taxonomies. When I try to filter the elasticpress search results by category or price, it works fine. The problem only happens when I try to filter by custom taxonomies. 

The most helpful source of information about this I could find was [this thread](https://github.com/10up/ElasticPress/issues/1576), but I tried to implement the suggested solution and it didn't work. On the debug bar it gives me a response code `HTTP 400`. I tried many different permutations of the provided piece of code, but none of them worked, and I don't have enough programming knowledge really understand what it is even supposed to do.

**-- The codes --**

**[1] -** The .php file that generates the query

    <?php

    defined( 'ABSPATH' ) || exit;

    global $wp_query;

    add_action( 'woocommerce_product_query', 'tpk_archive_query' );

    function tpk_archive_query( $q ){

        if($_GET['js'] == 'y') {
            $cat = explode(',', esc_attr($_GET['categorias']));
            $a = explode(',', esc_attr($_GET['artistas']));
            $ta = explode(',', esc_attr($_GET['tamanhos']));
            $c = explode(',', esc_attr($_GET['colecoes']));
            $t = explode(',', esc_attr($_GET['tags']));
            $preco = explode(',', esc_attr($_GET['preco']));
            $operador = strtoupper(esc_attr($_GET['op']));
            $orderby = explode('-', esc_attr($_GET['orderby']));
        } else {
            $cat = esc_attr($_GET['cat']);
            $a = esc_attr($_GET['a']);
            $ta = esc_attr($_GET['ta']);
            $c = esc_attr($_GET['c']);
            $t = esc_attr($_GET['t']);
        }

        if((esc_attr($_GET['orderby']) && !empty(esc_attr($_GET['orderby'])))) {

            if($orderby[0] == 'preco') {

                $q->set('orderby', 'meta_value_num');
                $q->set('meta_key', '_price');
                $q->set('order', $orderby[1]);

            } else {

                $q->set('orderby', $orderby[0]);
                $q->set('order', $orderby[1]);

            }

        }

        $args = [
            'relation' => 'AND',
        ];

        if((esc_attr($_GET['cat']) && !empty(esc_attr($_GET['cat'])))) {
            
            $category = [
                'taxonomy' => 'product_cat',
                'field' => 'slug',
                'terms' => $cat,
                'operator' => 'IN'
            ];

            array_push($args, $category);
        } elseif(esc_attr($_GET['categorias']) && !empty(esc_attr($_GET['categorias']))) {

            if(in_array('kits', $cat)) {

                $categorias = ['relation' => 'OR',];

                foreach ($cat as $cate) {

                    if($cate != 'kits') {

                        $kitCat = 'kits-' . $cate;

                        $cate = [$cate, $kitCat];

                        $pima = [
                            'taxonomy' => 'product_cat',
                            'field' => 'slug',
                            'terms' => $cate,
                            'operator' => 'IN'
                        ];
                        
                        array_push($categorias, $pima);

                    }

                }

            } else {

                $categorias = [
                    'taxonomy' => 'product_cat',
                    'field' => 'slug',
                    'terms' => $cat,
                    'operator' => 'IN'
                ];

            }

            array_push($args, $categorias);

        }

        if((esc_attr($_GET['a']) && !empty(esc_attr($_GET['a']))) || (esc_attr($_GET['artistas']) && !empty(esc_attr($_GET['artistas'])))) {
            $artistas = [
                'taxonomy' => 'autor',
                'field' => 'slug',
                'terms' => $a,
                'operator' => 'IN'
            ];

            array_push($args, $artistas);
        }

        if((esc_attr($_GET['ta']) && !empty(esc_attr($_GET['ta']))) || (esc_attr($_GET['tamanhos']) && !empty(esc_attr($_GET['tamanhos'])))) {
            $tamanho = [
                'taxonomy' => 'tamanho',
                'field' => 'slug',
                'terms' => $ta,
                'operator' => 'IN'
            ];

            array_push($args, $tamanho);
        }

        if((esc_attr($_GET['c']) && !empty(esc_attr($_GET['c']))) || (esc_attr($_GET['colecoes']) && !empty(esc_attr($_GET['colecoes'])))) {
            $colecao = [
                'taxonomy' => 'colecao',
                'field' => 'slug',
                'terms' => $c,
                'operator' => 'IN'
            ];

            array_push($args, $colecao);
        }

        if((esc_attr($_GET['t']) && !empty(esc_attr($_GET['t']))) || (esc_attr($_GET['tags']) && !empty(esc_attr($_GET['tags'])))) {
            
            if(!$operador) {
                $operador = 'OR';
            }
            $tags = ['relation' => $operador,];

            foreach ($t as $tag) {
                $poma = [
                    'taxonomy' => 'product_tag',
                    'field' => 'slug',
                    'terms' => $tag,
                    'operator' => 'IN'
                ];
                
                array_push($tags, $poma);
            }

            array_push($args, $tags);
        }

        $q->set('tax_query', $args);

        if((esc_attr($_GET['preco']) && !empty(esc_attr($_GET['preco'])))) {

            $min_price = $preco[0];
            $max_price = $preco[1];

            $q->set('meta_query', [
                [
                    'key' => '_price',
                    'value' => [$min_price, $max_price],
                    'compare' => 'BETWEEN',
                    'type' => 'NUMERIC'
                ]
            ]);

        }

    }

**[2] -** The JSON query without any active filters

    {
    "query": {
        "post_type": "product"
    },
    "query_vars": {
        "post_type": "product",
        "error": "",
        "m": "",
        "p": 0,
        "post_parent": "",
        "subpost": "",
        "subpost_id": "",
        "attachment": "",
        "attachment_id": 0,
        "name": "",
        "pagename": "",
        "page_id": 0,
        "second": "",
        "minute": "",
        "hour": "",
        "day": 0,
        "monthnum": 0,
        "year": 0,
        "w": 0,
        "category_name": "",
        "tag": "",
        "cat": "",
        "tag_id": "",
        "author": "",
        "author_name": "",
        "feed": "",
        "tb": "",
        "paged": 0,
        "meta_key": "",
        "meta_value": "",
        "preview": "",
        "s": "",
        "sentence": "",
        "title": "",
        "fields": "",
        "menu_order": "",
        "embed": "",
        "category__in": [],
        "category__not_in": [],
        "category__and": [],
        "post__in": [],
        "post__not_in": [],
        "post_name__in": [],
        "tag__in": [],
        "tag__not_in": [],
        "tag__and": [],
        "tag_slug__in": [],
        "tag_slug__and": [],
        "post_parent__in": [],
        "post_parent__not_in": [],
        "author__in": [],
        "author__not_in": [],
        "orderby": "popularity",
        "order": "ASC",
        "meta_query": [],
        "tax_query": {
        "relation": "AND"
        },
        "wc_query": "product_query",
        "posts_per_page": 48
    },
    "tax_query": {
        "queries": [],
        "relation": "AND",
        "queried_terms": [],
        "primary_table": null,
        "primary_id_column": null
    },
    "meta_query": false,
    "date_query": false,
    "post_count": 0,
    "current_post": -1,
    "in_the_loop": false,
    "comment_count": 0,
    "current_comment": -1,
    "found_posts": 0,
    "max_num_pages": 0,
    "max_num_comment_pages": 0,
    "is_single": false,
    "is_preview": false,
    "is_page": false,
    "is_archive": true,
    "is_date": false,
    "is_year": false,
    "is_month": false,
    "is_day": false,
    "is_time": false,
    "is_author": false,
    "is_category": false,
    "is_tag": false,
    "is_tax": false,
    "is_search": false,
    "is_feed": false,
    "is_comment_feed": false,
    "is_trackback": false,
    "is_home": false,
    "is_privacy_policy": false,
    "is_404": false,
    "is_embed": false,
    "is_paged": false,
    "is_admin": false,
    "is_attachment": false,
    "is_singular": false,
    "is_robots": false,
    "is_favicon": false,
    "is_posts_page": false,
    "is_post_type_archive": true,
    "thumbnails_cached": false
    }

**[3] -** The generated query with "autores -> Arcane Minis" and "orderby -> popularity"

    {
    "query": {
        "orderby": "",
        "post_type": "product"
    },
    "query_vars": {
        "orderby": "popularity",
        "post_type": "product",
        "error": "",
        "m": "",
        "p": 0,
        "post_parent": "",
        "subpost": "",
        "subpost_id": "",
        "attachment": "",
        "attachment_id": 0,
        "name": "",
        "pagename": "",
        "page_id": 0,
        "second": "",
        "minute": "",
        "hour": "",
        "day": 0,
        "monthnum": 0,
        "year": 0,
        "w": 0,
        "category_name": "",
        "tag": "",
        "cat": "",
        "tag_id": "",
        "author": "",
        "author_name": "",
        "feed": "",
        "tb": "",
        "paged": 0,
        "meta_key": "",
        "meta_value": "",
        "preview": "",
        "s": "",
        "sentence": "",
        "title": "",
        "fields": "",
        "menu_order": "",
        "embed": "",
        "category__in": [],
        "category__not_in": [],
        "category__and": [],
        "post__in": [],
        "post__not_in": [],
        "post_name__in": [],
        "tag__in": [],
        "tag__not_in": [],
        "tag__and": [],
        "tag_slug__in": [],
        "tag_slug__and": [],
        "post_parent__in": [],
        "post_parent__not_in": [],
        "author__in": [],
        "author__not_in": [],
        "order": "ASC",
        "meta_query": [],
        "tax_query": {
        "0": {
            "taxonomy": "autor",
            "field": "slug",
            "terms": [
            "arcane-minis"
            ],
            "operator": "IN"
        },
        "relation": "AND"
        },
        "wc_query": "product_query",
        "posts_per_page": 48
    },
    "tax_query": {
        "queries": [],
        "relation": "AND",
        "queried_terms": [],
        "primary_table": null,
        "primary_id_column": null
    },
    "meta_query": false,
    "date_query": false,
    "post_count": 0,
    "current_post": -1,
    "in_the_loop": false,
    "comment_count": 0,
    "current_comment": -1,
    "found_posts": 0,
    "max_num_pages": 0,
    "max_num_comment_pages": 0,
    "is_single": false,
    "is_preview": false,
    "is_page": false,
    "is_archive": true,
    "is_date": false,
    "is_year": false,
    "is_month": false,
    "is_day": false,
    "is_time": false,
    "is_author": false,
    "is_category": false,
    "is_tag": false,
    "is_tax": false,
    "is_search": false,
    "is_feed": false,
    "is_comment_feed": false,
    "is_trackback": false,
    "is_home": false,
    "is_privacy_policy": false,
    "is_404": false,
    "is_embed": false,
    "is_paged": false,
    "is_admin": false,
    "is_attachment": false,
    "is_singular": false,
    "is_robots": false,
    "is_favicon": false,
    "is_posts_page": false,
    "is_post_type_archive": true,
    "thumbnails_cached": false
    }

[4] - The generated query with the same active filters as before, but without ElasticPress active

    {
    "query": {
        "orderby": "",
        "post_type": "product"
    },
    "query_vars": {
        "orderby": "popularity",
        "post_type": "product",
        "error": "",
        "m": "",
        "p": 0,
        "post_parent": "",
        "subpost": "",
        "subpost_id": "",
        "attachment": "",
        "attachment_id": 0,
        "name": "",
        "pagename": "",
        "page_id": 0,
        "second": "",
        "minute": "",
        "hour": "",
        "day": 0,
        "monthnum": 0,
        "year": 0,
        "w": 0,
        "category_name": "",
        "tag": "",
        "cat": "",
        "tag_id": "",
        "author": "",
        "author_name": "",
        "feed": "",
        "tb": "",
        "paged": 0,
        "meta_key": "",
        "meta_value": "",
        "preview": "",
        "s": "",
        "sentence": "",
        "title": "",
        "fields": "",
        "menu_order": "",
        "embed": "",
        "category__in": [],
        "category__not_in": [],
        "category__and": [],
        "post__in": [],
        "post__not_in": [],
        "post_name__in": [],
        "tag__in": [],
        "tag__not_in": [],
        "tag__and": [],
        "tag_slug__in": [],
        "tag_slug__and": [],
        "post_parent__in": [],
        "post_parent__not_in": [],
        "author__in": [],
        "author__not_in": [],
        "order": "ASC",
        "meta_query": [],
        "tax_query": {
        "0": {
            "taxonomy": "autor",
            "field": "slug",
            "terms": [
            "arcane-minis"
            ],
            "operator": "IN"
        },
        "relation": "AND"
        },
        "wc_query": "product_query",
        "posts_per_page": 48
    },
    "tax_query": {
        "queries": [],
        "relation": "AND",
        "queried_terms": [],
        "primary_table": null,
        "primary_id_column": null
    },
    "meta_query": false,
    "date_query": false,
    "post_count": 0,
    "current_post": -1,
    "in_the_loop": false,
    "comment_count": 0,
    "current_comment": -1,
    "found_posts": 0,
    "max_num_pages": 0,
    "max_num_comment_pages": 0,
    "is_single": false,
    "is_preview": false,
    "is_page": false,
    "is_archive": true,
    "is_date": false,
    "is_year": false,
    "is_month": false,
    "is_day": false,
    "is_time": false,
    "is_author": false,
    "is_category": false,
    "is_tag": false,
    "is_tax": false,
    "is_search": false,
    "is_feed": false,
    "is_comment_feed": false,
    "is_trackback": false,
    "is_home": false,
    "is_privacy_policy": false,
    "is_404": false,
    "is_embed": false,
    "is_paged": false,
    "is_admin": false,
    "is_attachment": false,
    "is_singular": false,
    "is_robots": false,
    "is_favicon": false,
    "is_posts_page": false,
    "is_post_type_archive": true,
    "thumbnails_cached": false
    }

**Comment by abdullah1908** [comment]
Hey @Rayuaz ,

First of all thank you so much for taking out time to create a ticket. We'll surely try the same stuff at our end & then get back to you.

Happy Monday!

**Comment by felipeelia** [comment]
Hey @Rayuaz ,

Are you also using the [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugin? It is a Debug Bar add-on that shows some information about ElasticPress and Elasticsearch.

When you have that enabled, can you please send us the Elasticsearch query (it is under `Query Body` on Debug Bar ElasticPress)?

We are aware of a problem with ordering and terms, and a possible solution was posted [here](https://github.com/10up/ElasticPress/issues/2005#issuecomment-771875260). I'm not sure if this is related to your specific case but with the Query Body (and any possible error that could be displayed by the plugin) we will know.

Thanks

**Comment by Rayuaz** [comment]
Thanks for the response, guys.

The first thing I noticed when I got the ES debugger, is that when it works, it generates two queries, and when it doesn't, it generates only one. I have no idea if that's a relevant information, though.

[This](https://codeshare.io/5Pyo6M) [1] is the first generated query without any filters.
[This](https://codeshare.io/5RNk94) [2] is the second generated query without any filters.

[This](https://codeshare.io/aJ3eEE) [3] is the first generated query when I filter by "product-cat -> personagens" (which is a default woocommerce taxonomy) and "orderby -> popularity"
[This](https://codeshare.io/5OrbQr) [4] is the second generated query when I filter by "product-cat -> personagens" and "orderby -> popularity"

[This](https://codeshare.io/5Qj3wx) [5] is the one and only query generated when I filter by "autor -> Arcane Minis" (which is a custom taxonomy) and "orderby -> popularity"

**-- The codes --**

[1] The first generated query without any filters.
```
{
    "from": 0,
    "size": 48,
    "sort": [
        {
            "meta.total_sales.double": {
                "order": "desc"
            }
        },
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "post_type.raw": [
                                    "product"
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_status": [
                                    "publish",
                                    "acf-disabled"
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                },
                "autor": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.autor.slug"
                    }
                },
                "colecao": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.colecao.slug"
                    }
                },
                "tamanho": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.tamanho.slug"
                    }
                },
                "ep_custom_result": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.ep_custom_result.slug"
                    }
                },
                "pa_material": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_material.slug"
                    }
                },
                "pa_variacao": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_variacao.slug"
                    }
                }
            }
        }
    }
}
```

[2] Second query without any filters

```
{
    "from": 0,
    "size": 10000,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "terms.product_type.slug": [
                                        "simple",
                                        "grouped",
                                        "external",
                                        "variable"
                                    ]
                                }
                            },
                            {
                                "bool": {
                                    "must": [
                                        {
                                            "terms": {
                                                "terms.product_visibility.slug": [
                                                    "exclude-from-catalog"
                                                ]
                                            }
                                        },
                                        {
                                            "terms": {
                                                "terms.product_visibility.slug": [
                                                    "exclude-from-search"
                                                ]
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    },
    "_source": {
        "includes": [
            "post_id"
        ]
    }
}
```

[3] First query filtered by product-category and orderby
```
{
    "from": 0,
    "size": 48,
    "sort": [
        {
            "meta.total_sales.double": {
                "order": "desc"
            }
        },
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "terms.product_cat.slug": [
                                        "personagens"
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.product_cat.slug": [
                                        "personagens"
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "terms": {
                                            "terms.product_cat.slug": [
                                                "personagens"
                                            ]
                                        }
                                    },
                                    {
                                        "terms": {
                                            "terms.product_cat.slug": [
                                                "personagens"
                                            ]
                                        }
                                    },
                                    {
                                        "terms": {
                                            "terms.product_cat.slug": [
                                                "personagens"
                                            ]
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_type.raw": [
                                    "product"
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_status": [
                                    "publish",
                                    "acf-disabled"
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                },
                "autor": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.autor.slug"
                    }
                },
                "colecao": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.colecao.slug"
                    }
                },
                "tamanho": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.tamanho.slug"
                    }
                },
                "ep_custom_result": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.ep_custom_result.slug"
                    }
                },
                "pa_material": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_material.slug"
                    }
                },
                "pa_variacao": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_variacao.slug"
                    }
                }
            }
        }
    }
}
```

[4] Second query filtered by product-category and orderby
```
{
    "from": 0,
    "size": 10000,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "terms.product_type.slug": [
                                        "simple",
                                        "grouped",
                                        "external",
                                        "variable"
                                    ]
                                }
                            },
                            {
                                "bool": {
                                    "must": [
                                        {
                                            "terms": {
                                                "terms.product_visibility.slug": [
                                                    "exclude-from-catalog"
                                                ]
                                            }
                                        },
                                        {
                                            "terms": {
                                                "terms.product_visibility.slug": [
                                                    "exclude-from-search"
                                                ]
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    },
    "_source": {
        "includes": [
            "post_id"
        ]
    }
}
```

[5] The query filtered by Autores and orderby
```
{
    "from": 0,
    "size": 48,
    "sort": [
        {
            "meta.total_sales.double": {
                "order": "desc"
            }
        },
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "terms.autor.slug": [
                                        "arcane-minis"
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "terms": {
                                            "terms.autor.slug": [
                                                "arcane-minis"
                                            ]
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_type.raw": [
                                    "product"
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_status": [
                                    "publish",
                                    "acf-disabled"
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                },
                "autor": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.autor.slug"
                    }
                },
                "colecao": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.colecao.slug"
                    }
                },
                "tamanho": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.tamanho.slug"
                    }
                },
                "ep_custom_result": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.ep_custom_result.slug"
                    }
                },
                "pa_material": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_material.slug"
                    }
                },
                "pa_variacao": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.pa_variacao.slug"
                    }
                }
            }
        }
    }
}
```

**Comment by felipeelia** [comment]
Hi @Rayuaz , sorry but is not clear to me which of those 5 queries fail. The 5th one? Thanks!

**Comment by Rayuaz** [comment]
> Hi @Rayuaz , sorry but is not clear to me which of those 5 queries fail. The 5th one? Thanks!

Yes, the 5th is the problematic query. Queries 1 and 2 are generated when I browse the products page without any active filters. Queries 3 and 4 are generated when I activate filters based on default woocommerce taxonomies, such as `product_cat`. The 5th query is generated when I active filters based on my custom taxonomies, such as `autor`.

**Comment by felipeelia** [comment]
Hi @Rayuaz ,

Can you please share with us the code you are using to create that custom taxonomy? Also, in Debug Bar what is the content of the Query Results section for that query?

Thanks

**Comment by Rayuaz** [comment]
I'm just going to paste the snippet of code for the "autor" taxonomy, since the others follow this same template:

    function tpk_taxonomies_autores() {
    
        register_taxonomy('autor', ['product'], [
            'hierarchical' => false,
            'labels' => [
                'name' => 'Autor',
                'singular_name' => 'Autor',
                'search_items' => 'Search Autor',
                'all_items' => 'All Autores',
                'edit_item' => 'Edit Autor',
                'update_item' => 'Update Autor',
                'add_new_item' => 'Add New Autor',
                'new_item_name' => 'New Autor Name',
                'menu_name' => 'Autores'
            ],
            'show_ui' => true,
            'show_admin_column' => true,
            'query_var' => true,
            'rewrite' => ['slug' => 'autor']
        ]);
    
    }
    
    add_action('init', 'tpk_taxonomies_autores');

and the results for the failed query:

    {
        "took": 6,
        "timed_out": false,
        "_shards": {
            "total": 5,
            "successful": 5,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
            "total": {
                "value": 0,
                "relation": "eq"
            },
            "max_score": null,
            "hits": []
        },
        "aggregations": {
            "terms": {
                "doc_count": 0,
                "tamanho": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "ep_custom_result": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "product_tag": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "colecao": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "product_cat": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "post_format": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "pa_variacao": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "category": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "product_shipping_class": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "autor": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "pa_material": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                },
                "post_tag": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": []
                }
            }
        }
    }

**Comment by felipeelia** [comment]
Hi @Rayuaz ,

Thanks for the reply. I've tried to replicate the problem here but I could not. Can you please try to index your products again? There is a chance something is going wrong with the indexing process and products with that taxonomy assigned are not being indexed.

If you have access to WP-CLI, this would be the command:
`wp elasticpress index --show-errors`

Please let us know the return of the command and/or if it fixes the problem, okay?

**Comment by Rayuaz** [comment]
Well, I guess this is kind of embarrassing, but yeah, re-indexing everything worked. Thank you so much for your help, and sorry for wasting your time!

**Comment by felipeelia** [comment]
Not a problem at all @Rayuaz! I'm happy to know it worked for you.

I'm now closing the issue but feel free to open another one if you have any other problem with the plugin. Thanks!
