### ISSUE TITLE
Ability to filter indexer

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#207]
Is this possible? Example scenario:

When using [Advanced Custom Fields relationship field](http://www.advancedcustomfields.com/resources/relationship/), the data saved in the custom field is the ID of the related post. It would be nice if the developer could include post information from the related post in the Elasticsearch entry. In other words, hook into the indexer and include additional fields to be indexed.

**Comment by mikaelmattsson** [comment]
This is allready possible.
`ep_post_sync_args` to manipulate the data from each post before it is put into ES and `ep_config_mapping` to add more mappings.

**Comment by AaronHolbrook** [comment]
@mikaelmattsson is 100% correct, if you would like to add additional fields that are not already being brought over (ElasticPress natively brings over any non-protected, i.e. non underscore prefixed meta fields) you simply need to filter the `ep_post_sync_args` filter and add them yourself.
