### ISSUE TITLE
Age related decaying and not including older posts in results

### ISSUE THREAD

**Issue by neilb400** [10up/ElasticPress#2073]
Hi, could someone please let me know whether the following two post age-related scenarios are possible?

1. Being able to adjust the amount that newer articles score towards a relevance search, so that the chances of newer articles appearing near the top of such a search is increased (not just an on/off weighting toggle)
2. Being able to adjust the maximum age of returned posts on a relevance search.  (We can't just not index them because on a date-based search we want all posts to come back).

Many thanks.

**Comment by felipeelia** [comment]
Hi @neilb400 ,

Those two things can be achieved by changing the decay function ElasticPress creates in its queries. When we search for something using Elasticsearch, it'll apply a score to each result. The decay function applied to the post date will help to manipulate that score.

Here is a snippet that you can adapt to your needs:

```
add_filter( 'epwr_boost_mode', function() { return 'multiply'; } );
add_filter( 'epwr_offset', function() { return '15d'; } );
add_filter( 'epwr_scale', function() { return '30d'; } );
add_filter( 'epwr_decay', function() { return 0.5; } );
```

Basically, per line, what the snippet is doing is:
1. Changing the way the score is manipulated. The default is `sum` but that often doesn't change the query as needed;
2. Changing the min date when the score should start to be changed. Posts newer than 15 days will have their score at max;
3. Changing the max date when the score should be changed. Posts older than 30 days will receive the minimum modifier, between 15d and 30d they'll have the function applied.
4. The factor to be applied to the decay change. The default is 0.25, making it 0.5 you'll make the effect more pronounced.

Here is an article that may help to understand better those parameters: https://www.elastic.co/pt/blog/found-function-scoring

I'm going to close the issue now but please let us know if you need any other information okay? Thanks!

**Comment by felipeelia** [comment]
One important thing I forgot to mention:

In order to have all of these working, you need to be sure `Weight results by date` is `Enabled` in the `Post Search` box in the ElasticPress Features screen.
