### ISSUE TITLE
Refactor backend JS to remove jQuery dependency

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#2074]
**Is your enhancement related to a problem? Please describe.**

Currently the front end has been detached from a jQuery dependency, but not the backend. We made an attempt at this in #1663 but ended up pulling in the code from there only for the front-end parts of the plugin (mainly Autosuggest.

**Describe the solution you'd like**

Pull changes as needed from #1663 to refactor the admin dashboard parts of the plugin to remove the jQuery dependency.
**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by felipeelia** [comment]
As of ElasticPress 4.0.0, jQuery is a dependency only for:

- [ ] https://github.com/10up/ElasticPress/blob/develop/assets/js/notice.js (21 lines)
- [ ] https://github.com/10up/ElasticPress/blob/develop/assets/js/settings.js (46 lines)
- [ ] https://github.com/10up/ElasticPress/blob/develop/assets/js/sites-admin.js (28 lines)
- [ ] https://github.com/10up/ElasticPress/blob/develop/assets/js/weighting.js (20 lines)
