### ISSUE TITLE
Partial search for WooCommerce SKU with numbers in it

### ISSUE THREAD

**Issue by mathiasoem** [10up/ElasticPress#2076]
I have a WooCommerce store where i would like to be able to search for partial hits on product SKU's.
This works fine when the search query does not contain a number.

Searching for "FI-PH" returns all products with sku's starting with "FI-PH", e.g. FI-PH034, FI-PH023 and so on.

But when adding numbers to the search query, e.g. "FI-PH0" no results are returned.

When hitting the full SKU results are also returned, e.g. searching for "FI-PH023" returns the product with SKU "FI-PH023".

I have tried adding edge_ngram to the default filters, but then no results are returned at all.

Any help would be appreciated.

**Comment by felipeelia** [comment]
Hi @mathiasoem ,

As you probably have already figured out, to achieve that you will need to:

1. Add the ngram field to the mapping somehow
2. Reindex everything
3. Change the query sent to Elasticsearch in a way to include the new ngram field.

Can you please share the code you've used for #1 and #3 and also confirm you did #2? Thanks!

**Comment by aronvandervalk** [comment]
@mathiasoem I have the exact same issue, where partial matching of a SKU with numbers in it does not work. Do you have an example of the implementation of the ngram field?

**Comment by aronvandervalk** [comment]
@mathiasoem Thanks for your reply. Sorry to hear it did not work out.

@felipeelia Could you create an example of an ngram mapping filter on a custom ACF field?
