### ISSUE TITLE
Enhance error handling when syncing errors occur.

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#2095]
Based on the recent issues I had (https://github.com/10up/ElasticPress/issues/2083), it was suggested by @felipeelia to open a new enhancement ticket, so here goes:

- When anything happens while syncing - either good or bad - the message disappears after a few seconds, which essentially means that you have to sit on your screen while doing the sync - I am certain there are other ways to review it - maybe by examining logs, etc - but... why? Please make the message stay on screen.
- More importantly, in such cases, why halt the procedure completely? Adding an action like 'Too many requests: Retry?` would be a lot better.
- To take things one step further you could provide some additional details upon completion, like a small table with stats like Total sync time, sync time per item etc, so that people can evaluate which option works best for them on their environments.

**Comment by Rahmon** [comment]
Related with #2132

**Comment by felipeelia** [comment]
FWIW, I'm planning to (partially) implement these changes in #1835.

**Comment by felipeelia** [comment]
As #1835 was already merged to the `4.x.x` branch and this will be in the upcoming 4.0.0 Beta version, I'm closing this one out. Thanks!
