### ISSUE TITLE
Schedule a full sync using custom function and wp-cron?

### ISSUE THREAD

**Issue by joliverwestbrook** [10up/ElasticPress#2097]
I'm working on an implementation of EP with a database where posts are not always updated or modified the regular way, as referenced [here](https://github.com/10up/ElasticPress/issues/1259#issuecomment-465514833). 

So what I'm aiming to do is kick off a full sync, from the site's functions file according to a schedule and a few other status functions I have ready.

What would be the way to do this? Is there a function which would make the most sense, and be possible, to invoke from within the theme's functions?

**Comment by smidgedy** [comment]
this is perhaps old, but another user had a [similar looking issue](https://github.com/10up/ElasticPress/issues/1148 ) and the solution was to call `ep_sync_post()` on each post as they're getting added (wherever that may be from).

**Comment by joliverwestbrook** [comment]
Thanks @smidgedy! It appears, in looking at the source code, the proper (current) function name is `action_sync_on_update`? I did not find a function named `ep_sync_post` or any reference to that string in the entire plugin.

**Comment by joliverwestbrook** [comment]
UPDATE: I'm opting to simply iterate through relevant posts/post-types and update a new meta called something like meta_update_last with a timestamp which reflects the relevant posts meta was updated, which then triggers the built-in EP sync function for meta, however, I noticed it filters to only post and page types, mine are cpts, so it's necessary in the new function to hook into the post type filter for EP and merge the cpts into the array in the format: `'cpt_slug' => 'cpt_slug'`

All is working now, with the update to that single meta a sync for the entire posts meta is triggered.
