### ISSUE TITLE
Elasticsearch defaults to 10 aggregation terms returned

### ISSUE THREAD

**Issue by jamesmehorter** [10up/ElasticPress#210]
This isn't an issue really, but maybe it's worth noting somewhere in the EP docs?

By default only 10 aggregation term buckets are returned for each aggregation, which could confuse someone who is using EP out of the box. Scroll down to the 'size' section here: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

If someone needs more than 10 aggregation term buckets in the Elasticsearch response, and they're manually running a WP_Query they can simply pass the `size` argument..

```
$my_query = new WP_Query( array(
    's' => 'foo',
    'aggs' => array(
        'my-taxonomy' => array(
            'terms' => array(
                'size' => 100,
                'field' => "terms.my-taxonomy.slug",
            ),
        ),
    ),
) );
```

However, if someone is just using the builtin query on their search.php page and they need more than 10 aggregation term buckets in the response they'll need to tap into the ep_formatted_args filter like so:

```
function formatted_args( $formatted_args ) {

    // Increase ES aggregation default of 10
    foreach ( $formatted_args['aggs']['tax']['aggs'] as $key => $aggregation_data ) {
        $formatted_args['aggs']['tax']['aggs'][ $key ]['terms']['size'] = 100;
    }

    // Return the newly formatted args
    return $formatted_args;
}

// Intercept the query args
add_filter( 'ep_formatted_args', 'formatted_args', 10, 1 );
```

Hope that helps!

**Comment by jamesmehorter** [comment]
Adding this as a wiki page instead

**Comment by psorensen** [comment]
Thanks,  James!

**Comment by tlovett1** [comment]
@jamesmehorter perhaps aggregations should return posts_per_page results by default?

**Comment by jamesmehorter** [comment]
@tlovett1 possibly! However, posts_per_page is used for the actual hits returned correct?

Consider the following.. You use a category taxonomy as an aggregation and Es returns the default 10 hits, AND the top 10 category terms (aggregation term buckets) used by the hits. However, what if there are actually 25 category terms used by the hits? That's the situation I had run into which all this spurred out of—a search page where we display a sidebar of available taxonomy terms to filter the query by, and only 10 of the available term buckets were displaying.

**Comment by tlovett1** [comment]
Yea, I agree this just needs some documentation.

**Comment by adorr** [comment]
@jamesmehorter thanks for this, I spent a long time trying to debug why I was only seeing 10 results in my aggregation.

**Comment by mojovski** [comment]
thank you very much!

**Comment by mpateldrivin** [comment]
@jamesmehorter Do you have any idea to set the bucket size to maximum for term aggregation in elastic search 5?

**Comment by maggienj** [comment]
@mpateldrivin in the code, we can evaluate the value for the size.... instead of simply setting a "MAXIMUM_LIMIT" constant.  
We used to use MAXIMUM_LIMIT constant earlier... 
Recently, we have changed it to dynamically adjust the "size" value in "terms" aggregation .   
Depending on whichever source language you use to manipulate these values, we can dynamically set the "size":value....

**Comment by mpateldrivin** [comment]
@maggienj Thank you. Appreciate it
