### ISSUE TITLE
Add filters for easier search algorithm manipulation

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#2101]
In its current form alteration of the search algorithm and search query generated is fairly troublesome and adding filters in the indexable where appropriate ie https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L1108 would allow alteration of the query without iteration over the generated ElasticSearch query.

**Comment by felipeelia** [comment]
@tott a couple of questions that may arise:

1. Isn't ep_formatted_args_query good enough? I know you ran into some problems while using only that.
2. Given the fact that the weighting is added later, here is another point I'd like to suggest a new filter:
https://github.com/10up/ElasticPress/blob/0e04363ca3288be08ba4563bc692aa8854ec939d/includes/classes/Feature/Search/Weighting.php#L436 What do you think?

**Comment by tott** [comment]
The issue I have with ep_formatted_args is that you need to iterate over the whole array in order to catch all the different post types and such. That's why i'd like to have one in there to basically alter the template used for this. 

As for the second one - yes, this definitely makes sense.
