### ISSUE TITLE
Index Failing

### ISSUE THREAD

**Issue by switchbl4de** [10up/ElasticPress#2106]
We are reaching a "Maximum execution time" when running and index. Is there a way to bulk index in groups (it can get to like 14k and then it has issues)?

**Comment by felipeelia** [comment]
Hi @switchbl4de ,

You can change the number of items sent per request in two ways:

1. Via Dashboard:
If you go to the Dashboard -> ElasticPress -> Settings, you'll see the `Content Items per Index Cycle` field. Make that number smaller, you'll have faster requests.

2. Via WP-CLI:
If you are indexing via WP-CLI, you can use the `--per-page` parameter. For example: `wp elasticpress index --setup --per-page=100 --show-errors`.

I'm going to close the issue now but feel free to reopen if that doesn't solve your problem, okay? Thanks!

**Comment by switchbl4de** [comment]
Hi @felipeelia 

I still get error using those suggestions. I have tried those as well from the WP CLI docs. Any more commands you got that I can try? Maybe just a certain number of groups at once?

**Comment by felipeelia** [comment]
Hi @switchbl4de ,

If you use `wp elasticpress index --setup --nobulk --show-errors` or `wp elasticpress index --setup --per-page=1 --show-errors`, it will send just one item per request, which would make them as fast as possible. If they are still timing out, it'd be needed to debug what is the post/user/term that is causing it to fail or if it is possible to increase the timeout limit on both ends.

When you run it via WP-CLI you only get `Maximum execution time` as the error?

**Comment by switchbl4de** [comment]
Yes. I can index on my local but on Pantheon I get the Maximum execution time errors. They cannot raise it and the wp-config override doesn't seem to work. Checking into PHP errors to see if that is why it cannot continue. But on my local it runs just fine.

I tried the nobulk and still times out

**Comment by felipeelia** [comment]
Yeah, @switchbl4de , I'm sorry to read that but it seems you'll need help from the Pantheon's folks. Is it possible to increase memory instead? That can help to make things faster. Let me know what you find in those PHP logs, it may give us an idea of what can be consuming too much time.
