### ISSUE TITLE
Wordpress Custom Database Table with Elasticpress

### ISSUE THREAD

**Issue by ejdevspot** [10up/ElasticPress#2109]
Hi Everyone!

I have some problem on the development side, can we index custom database table in wordpress? I need to know how can I implement that because I have a custom table that connects to post, is it possible to do a join query both posts table and custom table using Elasticpress?

Thank you!

**Comment by felipeelia** [comment]
Hi @ejdevspot ,

Normally, when people need to index some custom database table we suggest them to create a new Indexable: http://10up.github.io/ElasticPress/tutorial-indexables.html.

In your case, you can use the `[ep_post_sync_args_post_prepare_meta](http://10up.github.io/ElasticPress/ep_post_sync_args_post_prepare_meta.html)` filter  to add the content of your custom table to the post while indexing, and then use the [`ep_formatted_args_query`](http://10up.github.io/ElasticPress/ep_formatted_args_query.html) or the [`ep_formatted_args`](http://10up.github.io/ElasticPress/ep_formatted_args.html) filters to change the Elasticsearch query. Remember: you'll have to go through two parts: adding the info for the indexing process and then changing the ES query to fetch it.

**Comment by ws256** [comment]
Hi @felipeelia ! If there is a link to the manual with examples, please add.
