### ISSUE TITLE
Search keywords order

### ISSUE THREAD

**Issue by dappi** [10up/ElasticPress#2113]
So I have Woocommerce and elasticpress on my site. My product name is for example: Miyaki Adidas Runner Men White

Now when I search "adidas runner" one of the results will be the product Miyaki Adidas Runner Men White. But then if I do a search "adidas runner miyaki", the search gives 0 results. Any idea why is that? I though elasticsearch should understand this is same search as "adidas runner miyaki" and should give a result that product page Miyaki Adidas Runner Men White.

**Comment by felipeelia** [comment]
Hi @dappi ,

It may be related to the more strict search algorithm we put in place in version 3.5. Can you please try switching it to the previous algorithm?

You can do that through some different ways:
1. Add `add_filter( 'ep_search_algorithm_version', function() { return '3.4'; } );` to your theme's functions.php file OR
2. Run this WP-CLI command `wp elasticpress set-algorithm-version --version=3.4` OR
3. Install the [ElasticPressLabs plugin](https://github.com/10up/ElasticPressLabs) and change it there.

Thanks

**Comment by dappi** [comment]
@felipeelia Thanks, that fixed it!
