### ISSUE TITLE
Elasticpress not used for search

### ISSUE THREAD

**Issue by sinhrodev** [10up/ElasticPress#2119]
Our elasticpress setup looks fine, index health is fine, everything is indexed.... But when users make a search (e.g. domain.com/?s=keyword), our mysql still has heavy load. When inspecting (show full processlist) we see a lot of long-running queries such as:

Creating sort index                  | SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND (((wp_posts.post_title LIKE '%keyword%') OR (wp_posts.post_excerpt LIKE '%keyword%') OR (wp_posts.post_content LIKE '%keyword%')))  AND (wp_posts.post_password = '')  AND wp_posts.post_type IN ('post', 'page', 'attachment') AND (wp_posts.post_status = 'publish')  ORDER BY wp_posts.post_title LIKE '%keyword%' DESC, wp_posts.post_date DESC LIMIT 0, 11   

So I guess Elasticpress is not used for search at all but search is simply performed on a mysql. Since we have quite a huge database (over 50.000 posts and at least so much attachments) these queries take quite a few seconds to execute. 

How can I debug this and make search work using elasticpress?

**Comment by johnbillion** [comment]
https://github.com/10up/debug-bar-elasticpress might be able to help

**Comment by felipeelia** [comment]
Hi @sinhrodev,

As @johnbillion said, [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) can help you debugging that. Just to expand the answer a bit, this plugin is an add-on for [Debug Bar](https://wordpress.org/plugins/debug-bar/), so you'll want to install that one too if you don't have it yet.

At last, you can try disabling all plugins, switching back to a default WordPress theme, and reenable everything one by one to detect what is causing this issue. To help you with that, I recommend using the "Troubleshooting Mode" of the [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin.

I'll keep the issue open for a while, so if you find the reason for your problem we'd highly appreciate it if you could come back here and share it with us, okay?

Thank you and @johnbillion!

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!

**Comment by sinhrodev** [comment]
Sorry for a late reply, I didn't receive any notifications from this issue on my email and missed it.

I installed Debug bar as well as Elasticpress debug bar plugin and now I see that Elasticsearch is returning HTTP 400 errors with explanation: "failed to create query: failed to parse setting [DecayFunctionParser.scale] with value [1y] as a time value: unit is missing or unrecognized".

If I disable "weight results by date" option in Elasticpress settings then everything works fine (except that results are not weightet by date obviously).

I am using latest Elasticpress (3.5.6) and Elasticsearch 7.11.0.

**Comment by dnikola** [comment]
@sinhrodev 

I hade same error, downgrade to version 7.9.x reindex and you will be fine.

In plugin requirements also write that max supported version is 7.9.x
