### ISSUE TITLE
Autosuggest: Uncaught (in promise) TypeError: t.replace is not a function

### ISSUE THREAD

**Issue by fagiani** [10up/ElasticPress#2126]
**Describe the bug**

After the installation of the plugin and a WP-CLI setup index, enabling the autosuggest feature, when typing any text on the
search field, the error below will show on the browser's console:
```
helpers.js:40 Uncaught (in promise) TypeError: t.replace is not a function
    at o (helpers.js:40)
    at B (autosuggest.js:154)
    at autosuggest.js:570
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
```

**Steps to Reproduce**

1. Install ElasticPress plugin
2. Index via WP-CLI command
3. Enable autosuggest feature
4. Go to the WP page where you have a search field
5. Type anything within it
6. See the error within the browser's console

**Expected behavior**
The search autosuggest results would show off

**Screenshots**
![Screen Shot 2021-03-11 at 11 08 55 AM](https://user-images.githubusercontent.com/2450/110799847-5f272300-825a-11eb-82e9-babb449e0eb3.png)
![Screen Shot 2021-03-11 at 11 11 43 AM](https://user-images.githubusercontent.com/2450/110800081-9a295680-825a-11eb-9b33-eaac90ab5d9c.png)

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 10.15.7
 - Browser and version: Chrome 88.0.4324.192 (Official Build) (x86_64)
 - WordPress version: 4.9.16
 
 - Plugins and version: [Akismet 3.1.5, ElasticPress 3.5.5, Posts View Counter 1.2.11, S3 Uploads 2.2.2, Sunny 2.2.1]
 - Theme and version: Custom theme

**Additional context**
Looking at the screenshots, you may notice the field comes with an empty array and it was expecting a string.

After disabling the "Facets" feature the autosuggest worked but it caused the whole index to be purged and synchronization process started from scratch which was not expected.

**Comment by felipeelia** [comment]
Hi @fagiani,

ElasticPress always enqueue the minified version of the JavaScript file, so I'm imagining those screenshots are the result of some debugging you were trying to do, right? Or are you trying to enqueue the file in a different way, perhaps adding it to a custom deployment setup?

The string it is trying to use is the Elasticsearch query, exposed by the `wp_localize_script()` call [here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Autosuggest/Autosuggest.php#L416) via the `window.epas.query` variable.

If you are trying to include the autosuggest file in a different way than the plugin does, you'll have to make sure to make that variable is available somehow.

I'll keep the issue open for a while, so if you have any follow-up questions let us know. Also, if you want to share more about your setup, that would be nice too :) Thanks

**Comment by fagiani** [comment]
Hey @felipeelia,

I am not doing any custom includes. I've pretty much installed the plugin and it will add the CSS and the JS along with the others within the HTML... I am not sure how or why the code I've got is not minified... when I hover over the stack trace it will show something like `webpack:///.assets/js/utils/helpers.js:40` and `webpack:///.assets/js/autosuggest.js:154`.

In the `<head>` tag I see:
```
<link rel="stylesheet" href="https://www.mysite.com/wp-content/plugins/elasticpress/dist/css/autosuggest-styles.min.css?ver=3.5.5">
```

and after the `</footer>` tag I see:

```
<script type='text/javascript'>
/* <![CDATA[ */
var epas = {"query":"{\"from\":0,\"size\":16,\"sort\":[{\"_score\":{\"order\":\"desc\"}}],\"query\":{\"function_score\":{\"query\":{\"bool\":{\"should\":[{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.post_tag.name^1\",\"terms.category.name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.post_tag.name^1\",\"terms.category.name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"post\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"page\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"envelopamento\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"publicidades\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"boracorrer\"}}]}}]}},\"functions\":[{\"exp\":{\"post_date_gmt\":{\"scale\":\"14d\",\"decay\":0.25,\"offset\":\"7d\"}}}],\"score_mode\":\"avg\",\"boost_mode\":\"sum\"}},\"post_filter\":{\"bool\":{\"must\":[{\"terms\":{\"post_type.raw\":[\"post\",\"page\",\"envelopamento\",\"publicidades\",\"boracorrer\"]}},{\"term\":{\"post_status\":\"publish\"}}]}}}","placeholder":"ep_autosuggest_placeholder","endpointUrl":"https:\/\/www.mysite.com\/es-search\/_search","selector":".ep-autosuggest","action":"navigate","mimeTypes":[],"triggerAnalytics":"1","addSearchTermHeader":""};
/* ]]> */
</script>
<script type='text/javascript' src='https://www.mysite.com/wp-content/plugins/elasticpress/dist/js/autosuggest-script.min.js?ver=3.5.5'></script>
```

The site is available publicly if you would like to take a quick look. I just didn't know if this is the appropriate place to point to it.

As I've pointed out in the first comment, when I disable the "Facets" feature it will just work.

For this site, I am not sure we need Facets so maybe it will be fine but my intention is to contribute to fixing an eventual bug and improve this great plugin!

It would be timely then to report while I am involved on this project and am able to reproduce if that can become useful to you somehow.

I really appreciate your attention!

Keep Rocking!

**Comment by felipeelia** [comment]
Hello again @fagiani! If the site is publicly available, then you can leave the link here, no problem. And thanks for willing to help, that really helps us to improve the plugin. Thanks again!

**Comment by fagiani** [comment]
@felipeelia it is [this site](https://www.blogdobg.com.br) but I'd have to coordinate with you enabling the Facets feature in order to you to be able to reproduce the issue. Feel free to send me an email so I can enable it for a while.

Thanks a bunch!

**Comment by felipeelia** [comment]
Hi @fagiani ,

Would it be possible to have it not working for an entire day or, even better, create a staging environment from it?

**Comment by hedqvist** [comment]
Also Experiencing this issue:
```
Uncaught (in promise) TypeError: t.replace is not a function
    at o (helpers.js:40)
    at B (autosuggest.js:154)
    at autosuggest.js:549
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)```
    
    Any idea of what it can be?

**Comment by fagiani** [comment]
@hedqvist a couple of things that I'd check which I've noticed could be potentially related with this specific behavior:

- Are you currently reindexing your data via WP-CLI or the WP Admin's Sync top bar?
- Is "Facets" feature currently enabled?

Hope it helps!

**Comment by hedqvist** [comment]
> @hedqvist a couple of things that I'd check which I've noticed could be potentially related with this specific behavior:
> 
> 
> 
> - Are you currently reindexing your data via WP-CLI or the WP Admin's Sync top bar?
> 
> - Is "Facets" feature currently enabled?
> 
> 
> 
> Hope it helps!

Facets is currently disabled and re-indexing is Done via admin panel 😅

**Comment by felipeelia** [comment]
@hedqvist , is that site public? If so, do you mind sharing its URL here so we can give a look?

**Comment by felipeelia** [comment]
It would be great if we could reproduce it in a local environment or look at it happening on a public site. Would it be possible for you (and/or @fagiani ) to disable all other plugins, use a default WP theme and try to pinpoint what plugin or theme causes the problem? Troubleshooting mode of the [Health Check plugin](https://wordpress.org/plugins/health-check/) can help a lot with that (it'll disable things just for your user). Thanks in advance.

**Comment by fagiani** [comment]
@felipeelia sorry for taking so long. I've just set the staging to reflect the error within the browser's console.

![Screen Shot 2021-03-31 at 10 34 00 AM](https://user-images.githubusercontent.com/2450/113152562-a0cd3d00-920c-11eb-9ac3-2e4a86014fe0.png)

You can check it out [here](https://staging.blogdobg.com.br/) throughout the day.

I can follow up with your last comment's suggestions later this week to help troubleshooting.

**Comment by fagiani** [comment]
@felipeelia sorry about that. For clarity, one of the ways I am able to reproduce that behavior is when reindexing and therefore I’ve started that. Somehow it has paused and I’ve just restarted it. Hopefully you will be able to catch it now.

**Comment by felipeelia** [comment]
Hi @fagiani, thanks for that! Yes, I'm able to reproduce it locally when I visit the site during an index. In fact, as we have the code developed now, autosuggest (and any other EP search functionality) should not be triggered while indexing, so we should have a check for that before enqueuing the JS file.

It should be a matter of adding a test like [this](https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Indexable/Post/QueryIntegration.php#L40) in the [Autosuggest::enqueue_scripts()](https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Feature/Autosuggest/Autosuggest.php#L324) method. Something like:

```
public function enqueue_scripts() {
	if ( Utils\is_indexing() ) {
		return;
	}
```

Would you be interested in testing that and crafting a PR if it works?

Thanks!

**Comment by hedqvist** [comment]
So this only seems to happen when Indexing is running or did I misunderstand something?

Because we have did re-run the indexing until complete and autosuggest still does not seem to work properly for us at https://rorfokus.se/

**Comment by hedqvist** [comment]
After further deepdiving this seems to be related to a custom function.
```add_filter( 'ep_skip_query_integration', 'admin_skip_es' );
function admin_skip_es() {
	if( is_admin() || is_product() ){
    	return true;
	}
}
```

We want to only use EP for autosuggest hence we disable the integration on all other requests, but this causes "elasticpress-autosuggest-js-extra" to have the query as empty array instead of the actual query.

@felipeelia Any other idea on how to only use EP for autosuggest?

**Comment by hedqvist** [comment]
It seems to work if we use the following:
```
add_filter( 'ep_skip_query_integration', '__return_true' );

add_filter( 'ep_autosuggest_options', 'redlight_ep_autosuggest_option' );
function redlight_ep_autosuggest_option($options) {
	$options['query'] = "{\"from\":0,\"size\":10,\"sort\":[{\"_score\":{\"order\":\"desc\"}}],\"query\":{\"function_score\":{\"query\":{\"bool\":{\"should\":[{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"post\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"page\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^50\",\"post_excerpt^30\",\"post_content^40\",\"meta._sku.value^1\",\"terms.pwb-brand.name^45\",\"terms.product_cat.name^35\",\"terms.product_tag.name^20\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^50\",\"post_excerpt^30\",\"post_content^40\",\"meta._sku.value^1\",\"terms.pwb-brand.name^45\",\"terms.product_cat.name^35\",\"terms.product_tag.name^20\",\"post_title.suggest^49\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"product\"}}]}}]}},\"functions\":[{\"exp\":{\"post_date_gmt\":{\"scale\":\"14d\",\"decay\":0.25,\"offset\":\"7d\"}}},{\"weight\":0.001}],\"score_mode\":\"sum\",\"boost_mode\":\"multiply\"}},\"post_filter\":{\"bool\":{\"must\":[{\"terms\":{\"post_type.raw\":[\"post\",\"page\",\"product\"]}},{\"terms\":{\"post_status\":[\"publish\",\"wc-partial-shipped\"]}}]}}}";

	return $options;
	
	
}
```

This allows us to turn of ES for anything else than autosuggest.

**Comment by felipeelia** [comment]
Hi @hedqvist,

Yes, that would happen only during a re-index (when autosuggest shouldn't be used anyway, as the results would probably be emptier than expected, as the content is wiped out and indexed again).

Although your code will work, hardcoding the query that way you may lose any future change we can make to that query. The following code will conditionally skip the EP integration and is an alternative solution:

```
add_filter(
	'ep_skip_query_integration',
	function( $skip, $query ) {
		if (
			! $query->is_search() ||
			empty( $query->get( 's' ) ) ||
			apply_filters( 'ep_autosuggest_query_placeholder', 'ep_autosuggest_placeholder' ) !== $query->get( 's' )
		) {
			return true;
		}
		return $skip;
	},
	10,
	2
);
```
