### ISSUE TITLE
Content in reusable blocks is not searched

### ISSUE THREAD

**Issue by johnbillion** [10up/ElasticPress#2127]
Steps to reproduce:

1. Insert a paragraph into a post containing some unique text
2. Save the paragraph as a reusable block
3. Publish the post
4. On the front end, search the site for the text
5. Observe there are no results

Reusable blocks can contain content that should be discoverable via search.

This is probably a wider problem that affects shortcodes and server-side rendered blocks too, but let's focus on one thing at a time.

**Comment by felipeelia** [comment]
Thanks, @johnbillion , I can confirm that bug.

We already index a "translated" version of the post content in the `post_content_filtered` field. While we don't have a proper fix applied in the plugin, here is a workaround for those with this problem:

```
add_filter(
	'ep_weighting_configuration_for_search',
	function( $weight_config ) {
		foreach ( $weight_config as &$post_type_config ) {
			if ( isset( $post_type_config['post_content'] ) ) {
				$post_type_config['post_content_filtered'] = $post_type_config['post_content'];
			}
		}
		return $weight_config;
	}
);
```

**Comment by johnbillion** [comment]
Thanks, that's what the Altis team have decided to do too: https://github.com/humanmade/altis-enhanced-search/pull/160

**Comment by felipeelia** [comment]
We've created a new article documenting this: https://elasticpress.zendesk.com/hc/en-us/articles/4402857301389
