### ISSUE TITLE
Adding more fields to the autosuggest results

### ISSUE THREAD

**Issue by fagiani** [10up/ElasticPress#2128]
I was looking at the JS code that builds the autosuggest list and found that only the `post_title` is set to `text` field of the formatted hits as seen below:

https://github.com/10up/ElasticPress/blob/1c325e8959da4034d40e2fd6947eccfdac106ec4/assets/js/autosuggest.js#L427-L443

Is there any way to override this method somehow to add other fields like the post date? 

Also, is it something that you'd be considering abstracting for a future version? I'd be interested in contributing with a PR if I had some general guidance.

**Comment by felipeelia** [comment]
Hi @fagiani ,

Thanks for bringing that up! We'll discuss it internally and reply back to you here in a few days.

FWIW, in addition to that method, we also have to keep in mind the `updateAutosuggestBox` function (the one which actually builds the autosuggest HTML code). We already filter the data received from the Elasticsearch server using:

```
if (typeof window.epDataFilter !== 'undefined') {
	return window.epDataFilter(data, searchTerm);
}
```

So probably we could use a similar approach here.

**Comment by fagiani** [comment]
Interestingly I've found that exactly piece of code earlier and actually worked to add the date to the results! :)

Thanks a lot!
