### ISSUE TITLE
Overriding autosuggest query size

### ISSUE THREAD

**Issue by fagiani** [10up/ElasticPress#2131]
While the `WP_Query()` results size is desired to stay as is, I'd like to be able to set a smaller number to the autosuggest results. 

Inspecting the code, I was able to find the `filter` below (although in the [docs](https://10up.github.io/ElasticPress/ep_epio_autosuggest_es_query.html) it is listed as an `action`)

https://github.com/10up/ElasticPress/blob/a38768e6828e991e46454be34466449252f8f557/includes/classes/Feature/Autosuggest/Autosuggest.php#L684-L691

Based on instructions for another filter [in this issue](https://github.com/10up/ElasticPress/issues/2122#issuecomment-796754476) I've tried to come up with the following code to change it:

```php
function autosuggest_override_results_limit( $es_search_query ) {
  if ( ! empty( $es_search_query ) ) {
    $es_search_query['size'] = 5;
  }
  return $es_search_query;
}
add_filter( 'ep_epio_autosuggest_es_query', 'autosuggest_override_results_limit');
```
I'd then expect the code after the `</footer>` to become something like:
```html
<script type='text/javascript'>
/* <![CDATA[ */
var epas = {"query":"{\"from\":0,\"size\":5,\"sort\":\"...\"},...};
/* ]]> */
</script>
```

But that didn't happen... I'm obviously missing something here.

Any clues on the right approach to achieve that would be highly appreciated!

**Comment by felipeelia** [comment]
Hi @fagiani ,

That filter won't help you. As its name suggests, it is related to the ElasticPress.io service only, not with the overall functionality of the plugin.

To achieve what you want, you can use the following snippet:

```
add_action(
	'pre_get_posts',
	function( $query ) {
		if ( ! is_admin() &&
			$query->is_search() &&
			apply_filters( 'ep_autosuggest_query_placeholder', 'ep_autosuggest_placeholder' ) === $query->get( 's' )
		) {
			$query->set( 'posts_per_page', 2 );
		}
	}
);
```

The autosuggest query is cached, so if you don't see the change immediately, you can wait five minutes, or go to the weighting engine dashboard and click on Save.

Also, are you already using Debug Bar and Debug Bar ElasticPress plugins to help you with debugging? Those plugins are great to check things like that, without having to go to the page source code :)

**Comment by fagiani** [comment]
@felipeelia That worked great! Thanks.
