### ISSUE TITLE
Duplicate Hook - Leads to triggering action two times (with sideffects)

### ISSUE THREAD

**Issue by superdummy** [10up/ElasticPress#214]
Hello, 

first of all, great Plugin, love it! Thanks for developing it.

I think i discovered a bug: The Hook "ep_post_sync_args" is triggered in two methods (see bolow) in sequence. This leads to buggy behaviour when attaching to this hook. As logic gets executed two times right after each other!

Background = What I want to do and resulting buggy behaviour: 
I need to manipulate the Data that is passed on to Elasticsearch.  I use a lot of "private" PostMetaValues starting with underscore. And I have to include them somehow.
I think the cleanst solution is to add additional Metafields for indexing just right before the data is send to Elasticsearch. And this seems to be best done in the function prepare_post()'s hook ep_post_sync_args . But with the current implementation of EP this leads to an effective callsequence of: 

	$post_args = apply_filters( 'ep_post_sync_args', $post_args, $post_id ); => in prepare_post()
	return $post_args;
    $post_args = apply_filters( 'ep_post_sync_args', ep_prepare_post( $post_id ), $post_id ); => in sync_post()

Within three lines of code, the filter is executed twice. My logic is idempotent, but this is a huge waste of resources and can lead to severe problems if my logic would not be idempotent...

Would be great if you have a look at it. I think  the filter in sync_post should be thrown out? Having it in prepare_post()  should be sufficient?

Thanks very much!

Fore Reference: This are the two methods stated above:

	public function sync_post( $post_id ) {

		$post_args = apply_filters( 'ep_post_sync_args', ep_prepare_post( $post_id ), $post_id );

		$response = ep_index_post( $post_args );

		return $response;
	}
	
	
	public function prepare_post( $post_id ) {
		$post = get_post( $post_id );

		$user = get_userdata( $post->post_author );

		if ( $user instanceof WP_User ) {
			$user_data = array(
				'raw'          => $user->user_login,
				'login'        => $user->user_login,
				'display_name' => $user->display_name,
				'id'           => $user->ID,
			);
		} else {
			$user_data = array(
				'raw'          => '',
				'login'        => '',
				'display_name' => '',
				'id'           => '',
			);
		}

		$post_date = $post->post_date;
		$post_date_gmt = $post->post_date_gmt;
		$post_modified = $post->post_modified;
		$post_modified_gmt = $post->post_modified_gmt;

		if ( apply_filters( 'ep_ignore_invalid_dates', true, $post_id, $post ) ) {
			if ( ! strtotime( $post_date ) ) {
				$post_date = null;
			}

			if ( ! strtotime( $post_date_gmt ) ) {
				$post_date_gmt = null;
			}

			if ( ! strtotime( $post_modified ) ) {
				$post_modified = null;
			}

			if ( ! strtotime( $post_modified_gmt ) ) {
				$post_modified_gmt = null;
			}
		}

		$post_args = array(
			'post_id'           => $post_id,
			'post_author'       => $user_data,
			'post_date'         => $post_date,
			'post_date_gmt'     => $post_date_gmt,
			'post_title'        => get_the_title( $post_id ),
			'post_excerpt'      => $post->post_excerpt,
			'post_content'      => apply_filters( 'the_content', $post->post_content ),
			'post_status'       => $post->post_status,
			'post_name'         => $post->post_name,
			'post_modified'     => $post_modified,
			'post_modified_gmt' => $post_modified_gmt,
			'post_parent'       => $post->post_parent,
			'post_type'         => $post->post_type,
			'post_mime_type'    => $post->post_mime_type,
			'permalink'         => get_permalink( $post_id ),
			'terms'             => $this->prepare_terms( $post ),
			'post_meta'         => $this->prepare_meta( $post ),
			//'site_id'         => get_current_blog_id(),
		);

		$post_args = apply_filters( 'ep_post_sync_args', $post_args, $post_id );

		return $post_args;
	}

**Comment by superdummy** [comment]
Update:
It would further be brilliant to have a "late option" to cancel/skip sending any data to Elastic (based on the full content. This allows for example for special checks based on interdependencies of data attributes.)

So the ideal fix (for my first post and this second post) could be:


public function sync_post( $post_id ) {

               //removed:  $post_args = apply_filters( 'ep_post_sync_args', ep_prepare_post( $post_id ), $post_id );
		$post_args = ep_prepare_post( $post_id );

                if ( null === $post_args) {
                     return null; //Not shure what is Best practice to return here
                }

  	      return ep_index_post( $post_args );

	}

Explanation: As a WP best practice, this allows "shortcircuting/killing" any further execution, if the filter does return null. So it here allows to skip indexing the post based on the filter processing/result. 

Thanks!

**Comment by tlovett1** [comment]
How does this look? #215

**Comment by tlovett1** [comment]
A fix for this has been merged.

**Comment by AaronHolbrook** [comment]
props @superdummy for a good find - thanks for the bug report!

**Comment by superdummy** [comment]
absolutely great, thanks very much!!
