### ISSUE TITLE
maybe_switch_to_blog is called to early

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#2147]
**Describe the bug**

I really like the feature of ElasticPress that its possible to display post from other websites in a multisite installation.

But there is a problem with the call to `maybe_switch_to_blog` on the `the_post` here https://github.com/10up/ElasticPress/blob/c58e7f4a5a68efec71bf54f797fff54d3aa2f5f5/includes/classes/Indexable/Post/QueryIntegration.php#L54 

`the_post` action runs before every post but also quite early to get meta information for the page title... Even on the front page or categories... If the first post in the main query is from another website, the meta information, the website title, menus, widgets... will be taken from the wrong website.

**Steps to Reproduce**
1. Add two websites to a multisite, add different titles and create some posts.
2. Include posts from another website in the main loop with `$query->set( 'sites', [ 1, 2 ] `);`
3. Be sure that the first post in the main query is from another site.
4. See the page title from the other site

**Expected behavior**

I would suggest adding the action `maybe_switch_to_blog` with the action `loop_start` to e.g.

```
add_action( 'loop_start' function () {
    add_action( 'the_post', array( $this, 'maybe_switch_to_blog' ), 10, 1 );
} );
```

... to make sure the maybe_switch_to_blog does not run to early.

**Comment by felipeelia** [comment]
Hi @goaround ,

Thanks for opening the issue! We're already addressing it in #2121, so I'll close this one and ask you to share any new information you may have there.
