### ISSUE TITLE
Add weight to post types, or remove a specific post type from date weight order.

### ISSUE THREAD

**Issue by fagianijunior** [10up/ElasticPress#2150]
hello,
thanks for this plugin and for your efforts to do it better.

**Is your enhancement related to a problem? Please describe.**

I has some post types, like: cat, dog, breed ... I am using "Weight results by date", and the post types cat and dog is updated constantly, but breed has very old dates, then I need to show breeds in the firsts results, if the query match with it, and the anothers posts with date weight order.

**Describe the solution you'd like**

Same as atributes has weight, the post types needs has a weigth too, or, some way to remove the post type (breed) from the date order.

**Describe alternatives you've considered**
I tried to find in the javascript if I can do a customQuery, but I can't found anything on it that can change the weight to a post type or remove it from the date weight. 
```[javascript]
  window.epas.customQuery = "{\"from\":0,\"size\":5,\"sort\":[...],...};
```
Maybe overwriting a custom query on functions.php can do it?

**Comment by mckdemps** [comment]
@fagianijunior We're not aware of a way to apply different weights in a single query when it comes to post date. Would it be possible to split this into two separate queries or are you aware of any elasticsearch query parameters that can accomplish this?

**Comment by fagianijunior** [comment]
We are done this hack on the javascript:

This code has some hack, the page has two input type="search" the first search on all post types with quotation first, the another only on quotation.
Depending on the ID of the input search, this do the specific search. const cepas force it.
```<script type="text/javascript">
	const cepas="{\"from\":0,\"size\":5,\"sort\":[{\"_score\":{\"order\":\"desc\"}}],\"query\":{\"function_score\":{\"query\":{\"bool\":{\"should\":[{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\",\"terms.indice.name^1\",\"meta.cotacao_cod.value^100\"],\"boost\":3}},{\"multi_match\":{\"query\":\"ep_autosuggest_placeholder\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\",\"terms.indice.name^1\",\"meta.cotacao_cod.value^100\",\"post_title.suggest^1\"],\"type\":\"phrase\",\"slop\":5}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"quotation\"}}]}}]}},\"functions\":[{\"exp\":{\"post_date_gmt\":{\"scale\":\"14d\",\"decay\":0.5,\"offset\":\"7d\"}}}],\"score_mode\":\"avg\",\"boost_mode\":\"multiply\"}}}";
	var epCustomInput = false;
	window.epas.customQuery = cepas;
	const {fetch: whatwgFetch} = window;
	window.fetch = async (...args) => {
		if (window.epCustomInput) {
			const { customQuery, placeholder } = window.epas;
			const replacement = document.getElementById(window.epCustomInput).value;
			args[1].body = customQuery.replace(new RegExp(placeholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), replacement);
```

Talking about "weight to post types":
Here will change the filter to search first on post_type 'quotation' in the same query. On autosuggest it's working well.
I seeing how to change the query from the search page, when user search with <ENTER> key.
```		} else {
			parsedBody = JSON.parse(args[1].body);
			parsedBody.query.function_score.functions.unshift({ "filter": { "match" : { "post_type.raw": "quotation" } }, "weight": 20 });
			args[1].body = JSON.stringify(parsedBody);
		}
```

```
		
		return await whatwgFetch(...args);
	}

	var epSearchInputs = document.getElementsByTagName("input");
	for ( i=0; i < epSearchInputs.length; i++ ) {
		if (epSearchInputs[i].type == "search") {
			epSearchInputs[i].addEventListener("focus", function() {
				if(this.id == "search-input") {
					window.epCustomInput = false;
				} else {
					window.epCustomInput = this.id;
				}
			});
		}
	}
</script>
```

**Comment by fagiani** [comment]
@mckdemps I am not sure if there is a better way to achieve that, but based on this code:

https://github.com/10up/ElasticPress/blob/9dfe8331d8a69bee0d964fc6815aecdee4c3b38d/includes/classes/Feature/Search/Search.php#L126

We were able to call the same `ep_formatted_args` filter via the theme's `functions.php` using a higher weight and achieve it like this for the search results:

```php
function weight_post_type_raw($formatted_args, $args) {        
    array_unshift($formatted_args['query']['function_score']['functions'],  ['filter' => ["match" => ["post_type.raw" => "quotation"]], 'weight' => 20 ]);

    return $formatted_args;
}

add_filter( 'ep_formatted_args', 'weight_post_type_raw', 12, 2 );
```

Hopefully that would become useful to others in the future, both for the autosuggest ([via JS](https://github.com/10up/ElasticPress/issues/2150#issuecomment-819627524)  as @fagianijunior described) and to the actual results.

Thanks for your attention here!

**Comment by Rahmon** [comment]
@fagianijunior Did you try the solution described above?

**Comment by fagianijunior** [comment]
Yes, and it is in production now. Works fine.
