### ISSUE TITLE
BUG: failed to parse setting [DecayFunctionParser.scale] with value [1y] as a time value

### ISSUE THREAD

**Issue by sinhrodev** [10up/ElasticPress#2152]
**Describe the bug**
I installed Debug bar as well as Elasticpress debug bar plugin because search queries were making huge load on a database (instead of searching in Elasticsearch). After that I see that Elasticsearch is returning HTTP 400 errors with explanation: "failed to create query: failed to parse setting [DecayFunctionParser.scale] with value [1y] as a time value: unit is missing or unrecognized".

**Steps to Reproduce**

1. enable "weight results by date" option in Elasticpress post settings
2. search anything

I am using latest Elasticpress (3.5.6) and Elasticsearch 7.11.0.
If I disable "weight results by date" option, search works fine and fast except it is returning mostly very old posts instead of most recent.

**Comment by felipeelia** [comment]
Hi @sinhrodev ,

It seems you are changing the `scale` value through the `epwr_scale` filter, is that right? If so, can you try to change that `1y` you have to `365d`? _Year_ doesn't seem to be a valid unit as per Elasticsearch docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units

**Comment by sinhrodev** [comment]
thanks, this was it - it was some custom plugin that we didn't even know we had that changed this setting..
I am marking this as closed
