### ISSUE TITLE
BUG: Double quote inside a html tag atribute break the tag.

### ISSUE THREAD

**Issue by fagianijunior** [10up/ElasticPress#2154]
**Describe the bug**
On doing a search with the highlight enabled, it add some quotation marks  (") inside a attribute of a html tag "data-share-title" and it break the HTML.

EX.:
<div class="inline-share" data-share-link="https://mysite.com.br/my-awesome-post/" data-share-title="My <strong class="ep-highlight">awesome</strong> post">
With the extra double quote mark, it expose the end of value in the view.

**Steps to Reproduce**

1. Enable highlight on settings
2. Do a search
3. View the `awesome</strong> post">` text exposed in the search page view.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/464154/113186102-9d967900-922d-11eb-8833-a0f53c8545bb.png)

**Environment information**
 - Device: DELL
 - OS: Ubuntu 20.04
 - Browser and version: Opera 75.0.3969.93, Chrome and Firefox too.
 - WordPress version: 5.7

**Additional context**

 - It can be fixed sanitizing this text before adding the text in the html tag attribute.

 - Inverting the double quote to a single quote mark and vice verse on the file ´include/classes/feature/Search/Search.php:265´
    $opening_tag = '<' . $highlight_tag . ' class="' . $highlight_class . '">';
    to
    $opening_tag = "<" . $highlight_tag . " class='" . $highlight_class . "'>";

 - Or something better :)

**Comment by felipeelia** [comment]
Hi @fagianijunior, do you mind explaining how you are adding that `data-share-title` attribute there? Thanks

**Comment by fagianijunior** [comment]
@felipeelia 
Sorry man,
It is a fault from my theme, I add <?php echo strip_tags(get_the_title()); ?> to fix it.

thank you,
