### ISSUE TITLE
BUG: Undefined variable: $closed in includes/classes/Elasticsearch.php

### ISSUE THREAD

**Issue by nickdaugherty** [10up/ElasticPress#2155]
**Describe the bug**

The new `\ElasticPress\Elasticsearch::update_index_settings()` method can throw an undefined variable notice for `$closed` as it is may not be initialized before being referenced in these lines: https://github.com/10up/ElasticPress/blob/aa1d42fa202f804b74bec710dab46eceb8309353/includes/classes/Elasticsearch.php#L838-L847

**Steps to Reproduce**

```\ElasticPress\Elasticsearch::factory()->update_index_settings( $index_name, $settings );```

**Expected behavior**

No PHP warning - `$closed` should be defined to `false` or `null` early in `\ElasticPress\Elasticsearch::update_index_settings()`

**Comment by pschoffer** [comment]
@felipeelia  I upstreamed the fix we have done on our fork in #2159
