### ISSUE TITLE
Disable MySQL fallback for search

### ISSUE THREAD

**Issue by cbratschi** [10up/ElasticPress#2160]
**Is your enhancement related to a problem? Please describe.**

I am handing this in as a feature request but in my opinion this is more likely a bug because websites using ElasticPress are larger ones where SQL search queries are slow.

Currently if a timeout occurs on the ElasticSearch instance, ElasticPress will automatically fall back to a MySQL search query. On our site for instance such a MySQL search takes about 90 seconds whereas ElasticSearch returns results in a fraction of a second. So whenever there's an issue with our ElasticSearch instance the whole server will go down. This happens during re-indexing too which we perform over night for instance.

ElasticPress defines no separate timeout for search queries and there is no hook available to easily modify the current value of 4 seconds.

**Describe the solution you'd like**

The following workaround just returns empty search results:

```
                         /**
			 * ES failed. Go back to MySQL.
			 */
			if ( false === $ep_query ) {
				$query->elasticsearch_success = false;
				
				//never fallback to MySQL
				if (!empty($query_vars['s'])) {
					return [];	
				}
				
				return null;
			}
```

The elasticsearch_success value could be used to display a warning on the search result page.

The original code is here:

https://github.com/10up/ElasticPress/blob/c58e7f4a5a68efec71bf54f797fff54d3aa2f5f5/includes/classes/Indexable/Post/QueryIntegration.php#L299

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbratschi** [comment]
The same features were requested here:

https://github.com/10up/ElasticPress/issues/1719

**Comment by felipeelia** [comment]
Hi @cbratschi,

Thanks for creating the issue! Although your use case is common, falling back to MySQL is what is expected for a good portion of the plugin users. So, the best way to have that would be wrapping the code inside a filter, something like:

```
/**
 * Filter whether to fallback to MySQL or not
 *
 * @hook ep_fallback_to_mysql
 * @param  {boolean} $show True to fallback
 * @return {boolean} New value
 */
if ( apply_filters( 'ep_fallback_to_mysql', true ) ) {
... your code
}
```

Would you like to craft a PR with that?

**Comment by cbratschi** [comment]
Hi @felipeelia,

Yes, this should be backwards compatible. I will create a PR.

**Comment by cbratschi** [comment]
See https://github.com/10up/ElasticPress/pull/2197.

**Comment by felipeelia** [comment]
I'm closing this one out as it can be achieved using the `posts_pre_query` filter and a check for `$query->elasticsearch_success`. If `elasticsearch_success` is not set or is false (meaning that ElasticPress didn't work for some reason), returning an empty array would make WordPress short-circuit the DB call.
An alternative version of the snippet shared [here](https://github.com/10up/ElasticPress/pull/2197#issuecomment-845940181) would be:
```
function ep_custom_avoid_fallback_mysql( $posts, $query ) {
	if ( ! isset( $query->elasticsearch_success ) || false === $query->elasticsearch_success ) {
		return [];
	}
	return $posts;
}
add_filter( 'posts_pre_query', 'ep_custom_avoid_fallback_mysql', 11, 2 );
```
