### ISSUE TITLE
BUG: remote_request is used before theme hooks are initialized by wp

### ISSUE THREAD

**Issue by halmos** [10up/ElasticPress#2161]
**Describe the bug**

The `\ElasticPress\Elasticsearch` method `remote_request` is invoked by the Elasticpress plugin before the theme is loaded and has a chance to add filters for `ep_do_intercept_request` and `ep_intercept_remote_request`. 

As a result it is not possible to add authentication headers to the request before the request is made. 
The `remote_request` appears to be called by `get_elasticsearch_info` at plugin load. Without the authentication headers, the response returns a `403` error. It looks like the result is then cached and as a result the dashboard reports an error that elasticsearch could not be reached and the plugin is blocked from functioning. 

I was able to find a workaround by adding a call to `\ElasticPress\Elasticsearch::factory()->get_elasticsearch_version( true);`
after my plugin loads, forcing the cached error to be cleared. 

**Steps to Reproduce**

- add a filter for `ep_intercept_remote_request`
- add a filter  and `ep_do_intercept_request` and add authentication headers. 
- try to connect to a elasticsearch install that requires authentication
- in the Elasticpress dashboard you will find an error. 
e.g.:

```
add_filter('ep_intercept_remote_request', 'handle_intercept_remote_request', 0, 1);
add_filter('ep_do_intercept_request', 'handle_do_intercept_request', 10, 4);

 function handle_intercept_remote_request() {
    return true;
}

function handle_do_intercept_request($response, $query, $args, $failures) {

    unset($args['headers']['EP-Search-Term']);

    $request = new Request( $args['method'], $query['url'], $args['headers'], $args['body'] ?? "" );
    $signer = new SignatureV4( 'es', 'us-east-1' ); // region specific

    $credentials_info = \get_credentials();
    $credentials = new Credentials( $credentials_info['key'], $credentials_info['secret'] );

    $signed_request = $signer->signRequest( $request, $credentials );
    $args['headers']['Authorization'] = $signed_request->getHeader( 'Authorization' )[0];
    $args['headers']['X-Amz-Date'] = $signed_request->getHeader( 'X-Amz-Date' )[0];
   
    $response = wp_remote_request( $query['url'], $args );
    return $response;
}

```

**Expected behavior**

Either there needs to be hold on remote requests until after the theme has loaded, or the `get_elasticsearch_info` needs to be called again after the theme has loaded.

**Comment by felipeelia** [comment]
Thanks for bringing it up, @halmos!

The problem is related to [this line](https://github.com/10up/ElasticPress/blob/3.5.6/elasticpress.php#L146):

```
add_action( 'plugins_loaded', __NAMESPACE__ . '\register_indexable_posts' );
```

Changing that `plugins_loaded` to `after_setup_theme` makes it work without any apparent side-effect (`init` seems to be too late). Obviously, it would require some thorough testing as it is a central point of the plugin. I wonder if we'd like to move it from the plugin territory though.

We'll discuss the next steps internally and share the final decision here.

**Comment by felipeelia** [comment]
Hi @halmos,

We've talked about it internally and it seems -at least in general- to be something that should be handled in a plugin rather than into the theme. But just to be sure we are not missing anything, do you mind sharing your use case and if for whatever reason it wouldn't be possible for you?

Thanks in advance!

**Comment by halmos** [comment]
Hi @felipeelia,

Thanks for taking some time to consider this. I can see your point that this might be considered a plug-in concern. However, in our particular case, the authentication credentials provider is a core feature of the theme itself and so it would not be possible to have those available in a plugin before the theme loads.

**Comment by felipeelia** [comment]
Got it, @halmos .

In that case, you could achieve that by writing a small plugin (or even a mu-plugin) changing the action used:

```
add_action(
	'plugins_loaded',
	function () {
		remove_action( 'plugins_loaded', 'ElasticPress\register_indexable_posts' );
		add_action( 'after_setup_theme', 'ElasticPress\register_indexable_posts' );
	},
	9
);
```

I've tested it here and it worked as expected. Can you please give it a try too? Thanks.

**Comment by halmos** [comment]
ok thanks - However, I wonder if the issue is less to do with the particular load sequence and more todo with the fact that the dashboard relies on stale data. It might make sense for the plugin to call `get_elasticsearch_info` once the theme has loaded to give opportunity for theme hooks to be invoked before displaying an error.

**Comment by mckdemps** [comment]
Can you give an example of where you would need to invoke theme-specific hooks? Typically, features like authentication should be added via a plugin as opposed to in a theme, so we're wondering if there's an additional use case we're not considering.
