### ISSUE TITLE
BUG: Index creation failure if the siteurl contains uppercase characters

### ISSUE THREAD

**Issue by teoteo** [10up/ElasticPress#2166]
During the first sync, the index creation on elasticsearch fails if the siteurl contains an uppercase character without feedback errors.

**Steps to Reproduce**
1. Create a WordPress site in a subfolder with uppercase name like https://mysite.ext/MYFOLDER
2. Install ElasticPress plugin, then sync
3. A PUT like http://myelasticserver.ext:9200/mysiteextMYFOLDER-post-1 is sent
3. The index is not created without a feedback

Using postman with the same sample with Postman I get
**PUT http://myelasticserver.ext:9200/mysiteextMYFOLDER-post-1**

```
{
    "error": {
        "root_cause": [
            {
                "type": "invalid_index_name_exception",
                "reason": "Invalid index name [mysiteextMYFOLDER-post-1], must be lowercase",
                "index_uuid": "_na_",
                "index": "mysiteextMYFOLDER-post-1"
            }
        ],
        "type": "invalid_index_name_exception",
        "reason": "Invalid index name [mysiteextMYFOLDER-post-1], must be lowercase",
        "index_uuid": "_na_",
        "index": "mysiteextMYFOLDER-post-1"
    },
    "status": 400
}
```

**Expected behavior**
Index creation or detailed error message

The calls to elasticsearch server should be converted in lowercase, so: 

**PUT http://myelasticserver.ext:9200/mysiteextmyfolder-post-1**

```
{
    "acknowledged": true,
    "shards_acknowledged": true,
    "index": "mysiteextmyfolder-post-1"
}
```

**Environment information**
 - Device: iMac
 - OS: MacOS 11.2.3
 - Browser and version: Safari 14.0.3
 - WordPress version: 5.7
 
 - ElasticPress version: 3.5.6
 - Elasticsearch version: 7.12.0
 - Where do you host your Elasticsearch server? CentOS 7.x
 - What ElasticPress features do you have currently active? Post Search, Protected Content, Custom Search Results
 - Plugins and version: 
 - Theme and version: 
 
 <details><summary>Site Health Info:</summary>
`
### wp-core ###

version: 5.7
site_language: en_US
user_language: en_US
timezone: +02:00
permalink: /%category%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 6
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/scm/public_html **this is the actual path so solve the issue. Before it was /home/scm/public_html/SCM**
wordpress_size: 1.10 GB (1177964168 bytes)
uploads_path: /home/scm/public_html/wp-content/uploads
uploads_size: 162.64 MB (170543630 bytes)
themes_path: /home/scm/public_html/wp-content/themes
themes_size: 19.13 MB (20060998 bytes)
plugins_path: /home/scm/public_html/wp-content/plugins
plugins_size: 44.43 MB (46584754 bytes)
database_size: 5.94 MB (6225920 bytes)
total_size: 1.32 GB (1421379470 bytes)

### wp-active-theme ###

name:  (scm)
version: undefined
author: Anonymous
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, custom-header, widgets
theme_path: /home/scm/public_html/wp-content/themes/scm
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 2.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.7, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.2, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

akeeba-backup-coreupdate.php: author: (undefined), version: (undefined)

### wp-plugins-active (10) ###

Active Directory Integration for Intranet sites: version: 3.6.3, author: miniOrange, Auto-updates enabled
Advanced Custom Fields PRO: version: 5.9.5, author: Elliot Condon, Auto-updates disabled
Akeeba Backup for WordPress: version: 7.5.6, author: Akeeba Ltd, Auto-updates enabled
Debug Bar: version: 1.1.2, author: wordpressdotorg, Auto-updates disabled
Debug Bar ElasticPress: version: 1.4, author: 10up, Auto-updates disabled
ElasticPress: version: 3.5.6, author: 10up, Auto-updates enabled
Login with Azure (Azure SSO): version: 1.4.3, author: miniOrange, Auto-updates enabled
PublishPress Capabilities Pro: version: 2.0.1, author: PublishPress, Auto-updates disabled
PublishPress Permissions Pro: version: 3.5.2, author: PublishPress, Auto-updates enabled
PublishPress Revisions Pro: version: 2.5.3, author: PublishPress, Auto-updates enabled

### wp-plugins-inactive (4) ###

Advanced Custom Fields: version: 5.9.5, author: Elliot Condon, Auto-updates enabled
Akismet Anti-Spam: version: 4.1.9, author: Automattic, Auto-updates enabled
Enable jQuery Migrate Helper: version: 1.3.0, author: The WordPress Team, Auto-updates enabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-02-24 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 20M
upload_max_filesize: 20M
max_effective_size: 20 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 62 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 62 GB
	imagick::RESOURCETYPE_MEMORY: 31 GB
	imagick::RESOURCETYPE_THREAD: 8
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 3.10.0-1127.19.1.el7.x86_64 x86_64
httpd_software: Apache/2.4.46 (Unix) OpenSSL/1.0.2k-fips
php_version: 7.4.16 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 200M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 20M
php_post_max_size: 20M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.4.18-MariaDB
client_version: mysqlnd 7.4.16

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/scm/public_html/wp-content
WP_PLUGIN_DIR: /home/scm/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`
   </details>

**Additional context**

**Comment by felipeelia** [comment]
Good catch @teoteo , thanks. Do you mind crafting a PR adding something like `$index_name = strtolower( $index_name );` in https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Indexable.php#L114?

In the meantime, it seems you could get it working with the following code. Can you please test it?
```
add_filter(
	'ep_index_name',
	function( $index_name ) {
		return strtolower( $index_name );
	}
);
```
