### ISSUE TITLE
QUESTION: Custom fields with Advanced Custom Fields plugin. How to manage it?

### ISSUE THREAD

**Issue by teoteo** [10up/ElasticPress#2167]
Reading this article [Custom Fields and Weighted Search with ElasticPress — Part 2](https://www.elasticpress.io/blog/2020/06/custom-fields-and-weighted-search-with-elasticpress-part-2/) I can add some of the required field added using [Advanced Custom Fields](https://www.advancedcustomfields.com) plugin.
I’ve added some of those 
```
		// Change my_custom_field here to what you need.
		$key = 'meta.content_0_columns_content.value';
		
		$fields['meta']['children'][ $key ] = array(
			'key'   => $key,
			'label' => __( 'Text block', 'textdomain' ),
		);	
```
in **epio_blog_add_custom_field_ep_weighting** function.

When there are multiple custom fields in a post, the content index is increased, so the additional custom fields are ignored (content_0_columns, content_1_columns, content_2_columns, etc.)
<img width="515" alt="db" src="https://user-images.githubusercontent.com/789650/114385532-6f4f5c80-9b90-11eb-847a-a6a5f7047b46.png">

**Question**
Do you have suggestions to manage those kind of custom fields in ElasticPress?

**Comment by teoteo** [comment]
Also considering all custom fields as a single search and weighting field is a welcome solution.

**Comment by felipeelia** [comment]
Hi @teoteo,
Dealing with repeatable fields is part of our plans but it won't happen in the near future. In the meantime, you can solve your problem by excluding all your `content_N_columns_content` and then creating a new metadata field with all values separated by a comma just in the Elasticseach index, using the `ep_prepare_meta_data` filter. Here are some links that can help you:

https://elasticpress.zendesk.com/hc/en-us/articles/360052019111-How-to-exclude-metadata-from-indexing
https://10up.github.io/ElasticPress/ep_prepare_meta_data.html

Thanks!

**Comment by Rahmon** [comment]
Another approach here could be something similar to what is made in [ElasticPressLabs](https://github.com/10up/ElasticPressLabs) adding a RegEx to allow patterns to be included in the search. The problem with this approach is that Elasticsearch could reach out to the field limit (5000 - `total_fields.limit`).

The approach pointed by Felipe seems appropriate in this case especially to prevent the issue above. Other than that, it makes sense to group the content of repeatable fields.
