### ISSUE TITLE
Ability to override the autosuggest selector, not just append to it

### ISSUE THREAD

**Issue by johnbillion** [10up/ElasticPress#2168]
**Is your enhancement related to a problem? Please describe.**

We're using the autosuggest feature on a site. The `autosuggest.js` file that handles this [contains a hardcoded list of selectors to target](https://github.com/10up/ElasticPress/blob/9dfe8331d8a69bee0d964fc6815aecdee4c3b38d/assets/js/autosuggest.js#L388-L390), with the `epas.selector` option appended to the end. We'd like to override this list of selectors completely because some pages contain a search input (`input type="search"`) which should not be targeted for autosuggest because it is used for another purpose.

**Describe the solution you'd like**

I'd like another option added to [the options](https://github.com/10up/ElasticPress/blob/aa1d42fa202f804b74bec710dab46eceb8309353/includes/classes/Feature/Autosuggest/Autosuggest.php#L380-L397) which can be filtered with [the `ep_autosuggest_options ` filter](https://github.com/10up/ElasticPress/blob/aa1d42fa202f804b74bec710dab46eceb8309353/includes/classes/Feature/Autosuggest/Autosuggest.php#L427-L437) which overrides the list of selectors completely for more fine grained control.

Maybe this option could be called `selectors` and if it's specified then it overrides the hardcoded list + selector.

**Comment by fagianijunior** [comment]
You read this issue? It will help you.
https://github.com/10up/ElasticPress/issues/2135
