### ISSUE TITLE
BUG: Does not respect a specific meta_query field

### ISSUE THREAD

**Issue by simplenotezy** [10up/ElasticPress#2176]
**Describe the bug**
In my normal WP_Query requests, I have a query that looks like this:

```
{
   "post_type":"product",
   "posts_per_page":26,
   "orderby":"meta_value_num",
   "lang":"en",
   "tax_query":{
      "relation":"AND",
      "0":{
         "relation":"AND",
         "0":{
            "taxonomy":"pa_material",
            "field":"slug",
            "compare":"IN",
            "terms":[
               "gold"
            ]
         }
      }
   },
   "paged":1,
   "meta_query":{
      "relation":"AND",
      "0":{
         "relation":"OR",
         "0":{
            "key":"_discontinued",
            "compare":"NOT EXISTS"
         },
         "1":{
            "key":"_discontinued",
            "value":1,
            "compare":"!=",
            "type":"NUMERIC"
         }
      }
   },
   "meta_key":"total_sales",
   "order":"desc"
}
```

And that usually works just fine. However, we noticed that after activating ElasticPress, ALL products would show up, even the ones that had `_discontinued=0`

Not sure what is wrong with this, however, it keeps us from switching to Elasticpress.io.

**Environment information**
 - WordPress version: 5.5.1
 - ElasticPress version: 
 - Elasticsearch version: 
 - Where do you host your Elasticsearch server? elasticpress.io

**Additional context**
I can provide more information if needed, but since it's pretty time consuming and I believe not relevant to this case, I have omitted it. Just let me know if I was wrong.

**Comment by oscarssanchez** [comment]
Hi @simplenotezy , our GitHub support is focused on plugin bugs and doesn’t extend to query-specific errors like the one you’re seeing here. since you’re an ElasticPress.io subscriber we can help you with this problem through our ticketed support. would you mind opening this as a ticket here https://www.elasticpress.io/ and we’ll get back to you there with some things to try?

**Comment by simplenotezy** [comment]
@oscarssanchez Alright, I'll do that. Thanks for reply.
