### ISSUE TITLE
QUESTION: Elasticsearch 7.12 + xpack security

### ISSUE THREAD

**Issue by PointPubMedia** [10up/ElasticPress#2183]
Hi,

First, is it true that elasticpress doesn't support ES 7.12 and that would explain why we can't connect to it ?

We are having an ES cluster, other software are working fine (ex. Kibana and rsyslog) and can connect and send data but with elasticpress we are having a 401 error!

**Comment by oscarssanchez** [comment]
Hi @PointPubMedia as per documentation the max supported version is 7.9 https://github.com/10up/ElasticPress#requirements 

You can define credentials like this: `define( 'ES_SHIELD', 'username:password' ); ` If you are planning to self-host Elasticsearch and activate Autosuggest, please be conscious of security implications

**Comment by PointPubMedia** [comment]
@oscarssanchez Already put the ES_SHIELD variable in place but with ES 7.12, we are having a 401 error!

So the problem is coming from the fact that we are using 7.12 ?

**Comment by PointPubMedia** [comment]
@oscarssanchez Found something maybe useful for you guys!

Just try elasticpress on another WP we are having, and the plugin works a little bit better.

We are still having the issue with the initial connection (I think it's the check the feature) BUT we are able to push an index in ES!
