### ISSUE TITLE
Support for m1 compatible Elastic Search 7.10.2

### ISSUE THREAD

**Issue by svandragt** [10up/ElasticPress#2185]
There's a [docker image now](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode) for Elasticsearch 7.10.2 which [alledgedly starts supporting the Apple m1 arm architecture](https://stackoverflow.com/a/65994297/997). [ElasticPress officially supports up to 7.9](https://github.com/10up/ElasticPress/blame/develop/README.md#L23).  (I don't have access to an m1 to test).

```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.10.2
```

**Is your enhancement related to a problem? Please describe.**
Setting up a m1 for WordPress development is held back by not being able to use EP.

**Describe the solution you'd like**
Test and confirm 7.10.2 support (or newer). 🙌 Thanks :)

**Comment by felipeelia** [comment]
Hi, @svandragt. If you have the chance to test it before we do, please let us know the results of your tests, okay? Thanks!

**Comment by mckdemps** [comment]
Feel free to reopen this if you get a chance to test out 7.10.2. Otherwise, we will bump compatibility when possible.
