### ISSUE TITLE
QUESTION: Wordpress's theme requires custom PHP code (elasticsearch shortcode) to theme's  functions.php file to load elasticpress search form.

### ISSUE THREAD

**Issue by amitghy** [10up/ElasticPress#2186]
**Kindly help me by providing elasticsearch shortcode for the below custome PHP [code](https://gist.github.com/jmabbas/8289878312d9e740e081ccf6a24555ff) of wordpress theme's function.php file so that I can use elasticsearch with my theme**

`function electro_navbar_search() {
	echo do_shortcode( 'Your seach shortcode' );
}

function electro_product_search() {
	if ( is_woocommerce_activated() ) { ?>
		<div class="site-search asdf">
			<?php echo do_shortcode( 'Your seach shortcode' );
			?>
		</div>
	<?php
	}
}`

**Comment by felipeelia** [comment]
Hi @amitghy ,

Can you please explain what exactly you are trying to achieve? ElasticPress should automatically integrate with your WordPress search after being properly configured, and generally, no changes in your theme would be required.

**Comment by amitghy** [comment]
I am using Electro Wordpress theme and by default it doesn't support elasticpress in its home page navigation search bar. We need to replace elasticsearch from the custom search bar available in Electro theme through its child theme's functions.php file. For that we need to add shortcode of elasticsearch in its functions.php file of child theme. So kindly provide me with the shortcode.

**Comment by felipeelia** [comment]
Hi @amitghy,

As that is a paid theme and we don't have access to its code, the help you need is outside of the scope of the support we provide here. If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!
