### ISSUE TITLE
BUG: Synonyms + additional terms return resuls like OR instead of AND

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#2187]
Hello everyone!

So, I've been struggling the whole day with this and the only conclusion I reached is that this must be a bug.

I have created a list of synonyms like the following - I will use actual keywords for convenience:
synonyms: `gearbox, shifter`

When I search for the following:
'Toyota engine'

I get expected results like:
Toyota AND engine

However, when I search for something inside the synonyms list, any term NOT in the synonym list is ignored. So if I search for:
`Toyota gearbox`

I get EVERYTHING that includes 'gearbox' OR 'shifter' OR 'Toyota' while the expected result would be:
('gearbox' OR 'shifter') AND 'Toyota'

I would assume that the synonym filter takes any group of keywords in the provided array and combines it with any additional keywords using the same logic as the initial query.

Is there a way to retrieve the results I am expecting? I tried adding a custom filter and changing the order, but still had no luck.

**Comment by felipeelia** [comment]
Hi @scooterlord, thanks for opening the issue. Which search algorithm are you using? Also, can you confirm that posts with `('gearbox' OR 'shifter') AND 'Toyota'` receives a better score than posts with `'gearbox' OR 'shifter' OR 'Toyota'`? Thanks.

**Comment by scooterlord** [comment]
Hello @felipeelia and thanks for your response! In fact, no, they don’t get better scoring.

I seem to have found what is wrong though. Everything seems to be broken when synonyms are multi-words... in the example above I was kind of translating from my own language where a synonym for gearbox is two words. 

So what break things is when a synonym consists of two word alternatives, like:
‘Gearbox, gear shifter’ 

I found this by trial and error and making tests but it is reproducible.

**Comment by felipeelia** [comment]
Hi @scooterlord ,

So, I've set my synonyms like this:
![image](https://user-images.githubusercontent.com/184628/117309584-ef4ba800-ae58-11eb-9496-d478f53a6778.png)

Then I've created two posts:
- Toyota Engine and
- Honda Gearbox

When I search for "gear shifter" I receive them both. If I search for "toyota gear shifter" I receive only the "Toyota Engine" one.

Can you explain how are your tests different from the above so we can try to reproduce the issue? Thanks.

**Comment by scooterlord** [comment]
Hello @felipeelia and once more thanks for being so thorough with this and looking into this.

I am using a function to import the synonyms list because it is huge but it’s more or less what you dictate. Do you get the expected results also when you search for  ‘Toyota gearbox’?

**Comment by felipeelia** [comment]
"Toyota gearbox" is a problem for me here indeed, @scooterlord. I've managed to get some results coming after I changed the search algorithm version to 3.4 but it seems that the more restricted version we have now by default doesn't work well with synonyms that contain more than one word.

We'll discuss it internally and I'll update you here with our findings. Thanks!

**Comment by mckdemps** [comment]
We will be opening a new issue with the solution.

**Comment by felipeelia** [comment]
This seems to be related to the multi word synonyms problem: https://github.com/elastic/elasticsearch/issues/32694#issuecomment-411897037

**Comment by scooterlord** [comment]
@felipeelia Hello again and thanks for your response. I added the filter above and re-indexed, the problem seems to have been gone - hopefully nothing else is broken. Should I investigate further?

Thank you once more for your help!

**Comment by mckdemps** [comment]
@felipeelia Let's implement the synonym graph approach at query time and note in the next release that we will be deprecating synonym creation at index time.

**Comment by scooterlord** [comment]
@mckdemps Can you please explain the difference between the two?

Also would I have to remove the snippet found in this thread in the next update?

**Comment by felipeelia** [comment]
To summarize, if a `default` analyzer is defined in the mapping, it'll be used on both occasions: index and search (overriding the `standard` analyzer used by default). If a `default_search` analyzer is defined, then it is possible to have different analyzers set for both. @brandwaffle do we want to introduce that or would it be good enough to change the synonyms type for the `default` analyzer? (this way affecting both).

IMO, although it makes more sense to think about synonyms at search time, introducing a `default_search` analyzer could add yet another layer of complexity in the mapping.
