### ISSUE TITLE
nativ geospatial search support

### ISSUE THREAD

**Issue by jdeserableexelcia** [10up/ElasticPress#2189]
Hi,
Great plugin!
Do you plan to support geospatial search natively?
Thank you
Regards,
Julien

**Comment by felipeelia** [comment]
Hi @jdeserableexelcia! Yes, we have plans for it but it won't happen in the near future. In the meantime, we are working on it in the ElasticPressLabs plugin: https://github.com/10up/ElasticPressLabs/pull/3 You can follow that plugin (and specifically that PR) to check our progress on that. Thanks!

**Comment by jdeserableexelcia** [comment]
Thank you for your reply and this interesting PR
