### ISSUE TITLE
How to integrate ElasticPress with custom taxonomy

### ISSUE THREAD

**Issue by leroile22** [10up/ElasticPress#2190]
I have built a website with WP Job Manager and ElasticPress.
The post type of jobs is job_listing and the taxonomy I want to use is job_listing_type.
My problem is that I cannot make the taxonomy job_listing_type searchable on the configuration screen: 
![Captureeed](https://user-images.githubusercontent.com/83457611/116698911-3d7a2a80-a9c5-11eb-98f0-5af484b03512.PNG)
Should I use the following filter to index the job_listing_type taxonomy in the database, and how: https://10up.github.io/ElasticPress/ep_indexable_post_types.html

**I am willing to pay a hundred bucks if someone can fix this problem for me (or more).**

**Comment by felipeelia** [comment]
Hi @leroile22,

Probably that is not a public taxonomy. You can either
1. Create some code to change WP Job Manager to make it public OR
2. Use the `ep_weighting_fields_for_post_type` filter to add it to the Weighting Dashboard and then `ep_sync_taxonomies` to have its terms indexed in that post type.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation.

Thanks!
