### ISSUE TITLE
QUESTION: Facet Filters Question

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2193]
I have a few questions regarding the facet filtering:

1. Is there a function I can use to reset all filters? For example, if the user selects 3 filters and wants to reset them by pressing a button.
2. Is it possible to display a list of all the currently selected filters?
3. If we have 30 facet filters on a product archive page, but some of them don't apply to the currently viewed category, is it possible to not load that facet on that page? Basically, I only want to load filters on a page if there are available options in that filter.

Thank you!

**Comment by felipeelia** [comment]
Hi @shmaltz,

1. Facets add some parameters to your query string, like `filter_category`. So, you can create a link for the same page without those parameters set.
2. You can iterate over those parameters to build that list
3. In theory, if there are no terms to display, the widget would be hidden: https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Feature/Facets/Widget.php#L104 Can you explain further your use case for it?

Thanks

**Comment by shmaltz** [comment]
Thanks for your reply @felipeelia 

In regards to 3, I have one sidebar area with attribute filters for products in all categories. If I go to a category page and none of the products in that category have a particular attribute, I don't want that attribute facet to load on that category page. This is a pretty standard feature in most filter plugins, and I am just curious if I can get it to work this way with ES.

Also, is there a list of filter/facet and search plugins that are compatible with ElasticSearch? Or could you please recommend some? The ones I tried don't work as they use their own index.

Thank you!

**Comment by felipeelia** [comment]
Hey @shmaltz ,

For your first paragraph, I'd like to understand more (with real examples if possible) how you have things set up. For the second one, what exactly are you trying to achieve?

Thanks

**Comment by gillespieza** [comment]
Sorry to reopen this, but I don't understand the answer to #1, @[felipeelia](https://github.com/felipeelia). I have the facets widget in my sidebar, so it appears on all my archive-type pages. Did you mean crate a hard-coded link to the same page without the parameters? Because that won't work in a dynamic sidebar?

**Comment by oscarssanchez** [comment]
Hi @gillespieza ,

You should be able to create a dynamic link to the same page, respecting other parameters by removing the $_GET `filter_like` parameters and recreating the link with one of WordPress functions. That's just a quick thought but there's probably more ways to go about it. 

You can use the `ep_facet_search_widget` to inject that custom link.
