### ISSUE TITLE
QUESTION: Stop indexing post metadata

### ISSUE THREAD

**Issue by DenisFlorin** [10up/ElasticPress#2195]
Hello, everyone!

How can I stop indexing post metadata?

Thank you!

**Comment by Rahmon** [comment]
Hi @DenisFlorin 

You can use the [ep_prepare_meta_excluded_public_keys](https://10up.github.io/ElasticPress/ep_prepare_meta_excluded_public_keys.html) filter. Take a look at [this answer](https://github.com/10up/ElasticPress/issues/1759#issuecomment-625838333) in another issue to see an example.
