### ISSUE TITLE
BUG: Facet Filter Checkbox

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2202]
When using the Facet Filter to filter product attributes, clicking in the actual checkbox next to a term does nothing. Only if you click the actual term text will the filter filter/unfilter.

The checkbox should actually trigger/untrigger the filter, as this is what the user expects.

**Comment by felipeelia** [comment]
Hi @shmaltz,

Do you have a live URL where we could see it happening? Also, in our next release, we're going to remove those checkboxes and changing them to a div with a certain style. Would it be possible for you to give a try of the code in the develop branch? Thanks!

**Comment by shmaltz** [comment]
Interestingly enough, the checkboxes are now working properly. Possibly because I re-indexed everything.

**Comment by felipeelia** [comment]
Nice to know, @shmaltz . Thanks!
