### ISSUE TITLE
QUESTION: How to implement access restrictions?

### ISSUE THREAD

**Issue by phntxx** [10up/ElasticPress#2205]
Hi,
I've recently stumbled across this plugin and instantly fell in love with it.
There is, however, one big problem that I can't find a solution to: I can't get ElasticPress to hide content from unauthorized users.

My question thus is: Is there any way to restrict search results depending on the role of the user (or any metric along these lines)?

I did see the feature "Protected content" in the features list for ElasticPress, but I could not find any valuable information about it. Maybe that's what I'm looking for?

**Describe your question**

I'll provide a brief example:
Let's say we have two users - one being a subscriber, the other one being an administrator - and one post (let's title it "Foobar"). Ideally, I'd like ElasticPress to show no results to the subscriber when searching for "Foobar" and show the post to the administrator when they search for "Foobar".

Any help would be much appreciated. If this is the wrong place to ask this question, please refer me to the correct one.

Kind regards
Bastian

**Comment by felipeelia** [comment]
Hi @phntxx ,

So, "Protected Content" should be used for people that want to index non-published posts or WooCommerce orders, for example. 

That said, and answering your question, ElasticPress takes WP_Queries and transforms them into Elasticsearch queries. So, if you build your WP_Query taking the current user roles into account, that would be reflected in the ES query built by EP.

If you have any concrete case in which that is failing, please let us know, okay? Thanks
