### ISSUE TITLE
BUG? Facets order after selection

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2207]
**Describe the bug**

A facet widget will always alphabetically order children terms of a selected term, even if order by count was selected.

**Steps to Reproduce**

1. Create a facet widget and configure it to order by Count / Descending
2. Visit the search page
3. See the children terms ordered by count
2. Select the parent term
3. See the children terms now ordered by term name

**Expected behavior**

It is not clear if that is by design or a bug.

**Comment by brandwaffle** [comment]
@felipeelia I can't imagine this is intended. Let's treat as a bug and resolve.

**Comment by oscarssanchez** [comment]
After some testing the ordering is not even working correctly without the term being selected. Working on a fix for it.
