### ISSUE TITLE
QUESTION: Any way to change rel="nofollows" to follow

### ISSUE THREAD

**Issue by dappi** [10up/ElasticPress#2208]
Is there any way to change the link's rel nofollows to follow? I was looking code and searching some filters that I could modify the links but seem everything is "hard" coded and no filters used at all? :o Did I miss something? I would expect 10plus plugin would follow more Wordpress way of doing things.

**Comment by brandwaffle** [comment]
@dappi are you talking about the links in the Facets Widget? If so, there are significant performance reasons not to make those followable links, as Google and other search engines will crawl those URLs resulting in your site having to serve every filter possibility (usually uncached). These links are also not something that should be followed for SEO purposes.

If I'm missing a use case, please feel free to share. For what it's worth, the plugin has lots of filters in places we feel they're necessary or helpful, and we always accept pull requests, so if something isn't up to your standards you're welcome to help improve that.
