### ISSUE TITLE
Archive Sort order issue

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2209]
I added the following snippet to my plugin in order to change the default sort order of the WooCommerce product archives to `menu_order` like it is at default (because with EP enabled, the sorting is not `menu_order`), however this is not working.

```
add_filter('ep_set_default_sort', 'bar_ep_woo_sort', 10, 2);
function bar_ep_woo_sort($sort, $order)
{
    return array(
        'menu_order' => array(
            'order' => 'ASC',
        ),
    );
}
```
I added the function to a custom plugin (I am using Oxygen Builder which doesn't use functions.php)
I have other functions (unrelated to ElasticPress) in my custom plugin and they all work flawlessly.

Any idea why this function won't work?

Thanks!

**Comment by shmaltz** [comment]
Update: I managed to get everything to index properly, and I think it worked because I added the **--setup** flag to the wp-cli command.

I still need help with ordering, as everything is out of order.

**Comment by felipeelia** [comment]
Hi @shmaltz, can you please install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/), visit that page, open the Debug Bar, and let us know how the query and its result look like?

Also worth pointing out that that filter will be used only if `orderby` is empty and if it is not a search ([here](https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Indexable/Post/Post.php#L664)):
```
// Default sort for non-searches to date.
if ( empty( $args['orderby'] ) && ( ! isset( $args['s'] ) || '' === $args['s'] ) ) {
	/**
	 * Filter default post query order by
	 *
	 * @hook ep_set_default_sort
	 * @param  {string} $sort Default sort
	 * @param  {string $order Order direction
	 * @return  {string} New default
	 */
	$args['orderby'] = apply_filters( 'ep_set_default_sort', 'date', $order );
}
```

So, there is a chance you'll need to use `pre_get_posts` to reset that orberby instead of using this filter.

**Comment by shmaltz** [comment]
Hi @felipeelia, I used the following `pre_get_posts`, and it seems to be working so far (THANKS!), however I do get a PHP notice: `Undefined offset: 0`. Any idea how I can fix that?

```
add_action( 'pre_get_posts', 'bar_woo_order' );
function bar_woo_order( $query ) {
	if ( ! is_admin() && $query->is_main_query() ) {
		if ( is_post_type_archive( 'product' ) || is_product_category() || is_product_tag() ) {
            $query->set( 'orderby', array( 'menu_order' => 'ASC') );
		}
	}
}
```

Also, in general, would there be any benefit (performance or otherwise) in using `ep_set_default_sort` over `pre_get_posts`, or do they accomplish the same thing?

**Comment by felipeelia** [comment]
Hi @shmaltz, I'm happy to know it is working!

Do you have any additional details of that error? The line where it is happening, etc? It doesn't seem to be coming from that snippet.

And it should not affect performance at all. They just happen to work in different scenarios.

**Comment by shmaltz** [comment]
Hi @felipeelia, 
This is what I get from Query Monitor:

```
Notice	Undefined offset: 0	     Plugin: woocommerce

wp-content/plugins/woocommerce/includes/class-wc-query.php:536
WC_Query->get_catalog_ordering_args()
wp-content/plugins/woocommerce/includes/class-wc-query.php:468
WC_Query->product_query()
wp-content/plugins/woocommerce/includes/class-wc-query.php:370
WC_Query->pre_get_posts()
wp-includes/class-wp-hook.php:292
do_action_ref_array('pre_get_posts')
wp-includes/class-wp-query.php:1784
WP_Query->get_posts()
wp-includes/class-wp-query.php:3465
WP_Query->query()
wp-includes/class-wp.php:629
WP->query_posts()
wp-includes/class-wp.php:752
WP->main()
wp-includes/functions.php:1291
wp()
wp-blog-header.php:16
```

When I disable the snippet, the error goes away.

**Comment by felipeelia** [comment]
Hey @shmaltz ,

It comes from WooCommerce. You can try to change your snippet to this:
```
add_action( 'pre_get_posts', 'bar_woo_order' );
function bar_woo_order( $query ) {
	if ( ! is_admin() && $query->is_main_query() ) {
		if ( is_post_type_archive( 'product' ) || is_product_category() || is_product_tag() ) {
			$query->set( 'orderby', 'menu_order' );
			$query->set( 'order', 'ASC' );
		}
	}
}
```

If that doesn't help, then you'd need to investigate WooCommerce code a bit more. This is the line where it fails, by the way: https://github.com/woocommerce/woocommerce/blob/5.3.0/includes/class-wc-query.php#L536

As it is something that falls outside ElasticPress code, I'm going ahead and closing the issue but feel free to leave a comment and/or reopen if needed. Thanks!

**Comment by shmaltz** [comment]
Hey @felipeelia,

I still get the same error with that snippet.

I really appreciate you trying though!

**Comment by shmaltz** [comment]
Hey @felipeelia,

It seems if I use that snippet that the ordering doesn't even take effect.

I really appreciate you trying though! Thanks!
