### ISSUE TITLE
Plugin conflicts with "Related Products for WooCommerce" (By Vagelis P.) causing the related products disappear !

### ISSUE THREAD

**Issue by leduy2701** [10up/ElasticPress#2212]
**Describe the bug**
Enabling ElasticPress is causing all related products disappear.
The Related Products powered by plugin "Related Products for WooCommerce".

**Steps to Reproduce**

1. Go to https://gta5modaz.com
2. Click random on a product
3. Scroll down to the end
4. You can see the related products (these related products appear because I've turned off the Elasticpress plugin)

**Expected behavior**
When ElasticPress is activated, the Related products disappear !

**Screenshots**

**Environment information**
 - Conflicted plugin: https://wordpress.org/plugins/woo-product-filter/
 - WordPress version: 5.7.2

**Comment by felipeelia** [comment]
Hi @leduy2701, can you please install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/), visit that page, open the Debug Bar, and let us know how the query and its result look like?

Also, did you already try ElasticPress's native "Related Posts" feature? Does it work for your case?
