### ISSUE TITLE
Am I missing something for pagination?

### ISSUE THREAD

**Issue by jonathan-dejong** [10up/ElasticPress#222]
Hi!

Just implemented EP on a clients multisite network and boy I love it.. 
I can't seem to get pagination to work tho. 

This is  my slightly condensed pre_get_posts function to retrieve posts for the search results (sorry about the bad indentation):
```
	        $query->set( 'posts_per_page', 20 );
		        
		       $query->set('post_type', array(
			        'post',
			        'page',
			        'espresso_events'
		        ));
		        
		        //Search in every site
		        $sites = wp_get_sites();
		        $excluded_sites = get_blog_option(1, 'options_network_excluded_sites');
		        $site_ids = array();
		        //but first, exclude the sites we don't want
		        foreach($sites as $key => $site){
			        if(in_array($site['blog_id'], $excluded_sites)){
				        unset($sites[$key]);
			        }else{
				        $site_ids[] = $site['blog_id'];
			        }
		        }
		        //if there are sites left, lets search in them!
		        if(!empty($site_ids)){
			        $query->set('sites', $site_ids);
		        }
		        
	        	        
			//Fix pagination
	        $args = wp_parse_args($query);
	        if ( get_query_var('paged') ) {
	        	$paged = get_query_var('paged');
	        } elseif ( get_query_var('page') ) {
	        	$paged = get_query_var('page');
	        } else {
	        	$paged = 1;
	        }
			$query->set('paged', $paged);
			
	        
	        //Make sure to search some meta fields as well
	        $query->set('search_fields', array(
		        'post_title',
		        'post_content',
		        'post_excerpt',
		        'meta' => array(
			        'page_alternate_title',
			        'page_ingress'
		        )
	        ));
	        
	        return;
```

However it doesn't seem to work and I'm thinking it might be due to the global search? 
To be clear, the search returns 20 results ONLY even tho I'm quite sure there are plenty more. Looking at the global wp_query object both the found_posts parameter and max_num_pages are set to 0 while post_count is correct with 20. 

Note that I've also tried leaving out the manual $paged setting with the same results. I will try it with just a single site search and report back.

**Comment by jonathan-dejong** [comment]
Nope. Just tried with a completely vanilla search (no custom settings with pre_get_posts) and I'm still not seeing any pagination and found_posts and max_num_pages are both 0.

**Comment by allan23** [comment]
Hi Jonathan,

The pre_get_posts action gets called when ElasticPress indexes your site. With your code above, you are limiting the indexing to 20 posts.

My suggestion would be to wrap your code with the following IF statement:
```
if ( $query->is_main_query() ) {  
    // Your code here.
} 
```
This will allow your code to kick in on a main search instead of on every single WP Query throughout the site (frontend and backend).

Let me know if that resolves your issue.

**Comment by jonathan-dejong** [comment]
Hi Allan, 

Actually I have the code above wrapped in
` if(is_search()) `
so my pre_get_posts action only applies on a search which is what I want. I just left that part out for readability sake :) 

This is the entirety inside the pre_get_posts function with some other stuff that's not related left out:

```
if ( is_admin() || ! $query->is_main_query() )
	        return;
	
		//alter search for regular search page
	    if ( is_search() ) {
		    
		    //set posts per page to 15
	        $query->set( 'posts_per_page', 20 );
	        
	        //If we're searching for a specific post type
	        if(isset($_GET['post_type'])){
		        $query->set( 'meta_query', array(
		        	array(
		        		'key' => 'doc_event_toggle',
		        		'value' => 1,
		        		'compare' => '!='
		        	)
		        ));
		        
		        $query->set('post_type', $_GET['post_type']);
		        
	        }else{
		        
		        $query->set('post_type', array(
			        'post',
			        'page',
			        'espresso_events'
		        ));
		        
		        //Search in every site
		        $sites = wp_get_sites();
		        $excluded_sites = get_blog_option(1, 'options_network_excluded_sites');
		        $site_ids = array();
		        //but first, exclude the sites we dont want
		        foreach($sites as $key => $site){
			        if(in_array($site['blog_id'], $excluded_sites)){
				        unset($sites[$key]);
			        }else{
				        $site_ids[] = $site['blog_id'];
			        }
		        }
		        //if there are sites left, lets search in them!
		        if(!empty($site_ids)){
			        $query->set('sites', $site_ids);
		        }
		        		        
	        }
	        
			//Fix pagination
	        $args = wp_parse_args($query);
	        if ( get_query_var('paged') ) {
	        	$paged = get_query_var('paged');
	        } elseif ( get_query_var('page') ) {
	        	$paged = get_query_var('page');
	        } else {
	        	$paged = 1;
	        }
			$query->set('paged', $paged);

	        //Make sure to search some meta fields as well
	        $query->set('search_fields', array(
		        'post_title',
		        'post_content',
		        'post_excerpt',
		        'meta' => array(
			        'page_alternate_title',
			        'page_ingress'
		        )
	        ));
	        
	        return;
	    }
```

You say that the posts_per_page is actually limiting the indexing to 20 posts, is that really how it works? If so it's very much different than how posts_per_page works in a regular query.. it should still find the total number of posts and support pagination.

**Comment by allan23** [comment]
Thanks for the code clarification Jonathan. I can see that your code does not affect indexing, so we are good on that front.

While running your code on a local multisite install with four sites with 108 posts total, I was not able to replicate your pagination issue.

```
    [post_count] => 20
    [current_post] => -1
    [in_the_loop] => 
    [comment_count] => 0
    [current_comment] => -1
    [found_posts] => 108
    [max_num_pages] => 6
```

I'm using the Twenty Fifteen theme on WP 4.1.1, no other plugins other than ElasticPress.

Is there anything special about your install that I need to do in order to replicate your issue? (Plugins, theme, etc.?)

**Comment by jonathan-dejong** [comment]
Hi allan,

Sorry I've been sick with the flu for some time now.. 

Hmm.. I'm using EventEspresso for events which might be messing with the query.. I'll try disabling it. 
Other than that I have a pretty extensive list of plugins both custom made and from the community. I'm also using a custom theme but I can't imagine that being the issue since this is the only filter I have that manipulates the queries..

**Comment by jonathan-dejong** [comment]
Hi,

So I came back to this issue a few days ago and suddenly the pagination worked but showed an massive amount of found posts (so again it was wrong). But I did a reindex and it's now working. So I guess something went wrong with the first indexing or something..
