### ISSUE TITLE
BUG: All facet widgets get removed when disabling and re-enabling plugin

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2220]
I noticed that when I temporarily disable the ElasticPress plugin (when debugging), and re-enable it, that all my facet widgets are gone and I have to set them all up again (around 70 facets!) from scratch.

Is there any way to save the facets/widgets so it doesn't clear?

Other plugins seem to not clear when disabling/re-enabling.

**Comment by felipeelia** [comment]
Hi @shmaltz,

I could not reproduce this error. Are you by any chance creating the widget area conditionally based on ElasticPress being active or not? It would be great if you could provide the steps to reproduce the problem in a fresh install. Thanks!

**Comment by shmaltz** [comment]
Hi @felipeelia,

The widget ares are always available - whether ElasticPress is enabled are not.

Here is my widget code:

```
function bar_register_filter_sidebars() {
    // Sidebar 1
    register_sidebar( array(
         'name' => 'Sidebar 1',
         'id' => 'sidebar-1',
         'before_widget' => '<div id="sidebar-1">',
         'after_widget' => '</div>',
         'before_title' => '',
         'after_title' => '',
     ) );
     // Sidebar 2
     register_sidebar( array(
        'name' => 'Sidebar 2',
        'id' => 'sidebar-2',
        'before_widget' => '<div id="sidebar-2">',
        'after_widget' => '</div>',
        'before_title' => '',
        'after_title' => '',
    ) );
 }
 add_action( 'widgets_init', 'bar_register_filter_sidebars' );
```

**Comment by felipeelia** [comment]
Hi @shmaltz,

I could not reproduce the problem even with those custom sidebars. Can you see the problem happening in a fresh install or just in the site you are working on?
