### ISSUE TITLE
QUESTION: How often do I need to index?

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2221]
I couldn't find this in the docs, so asking here:

1. How often do I have to run the index?

2. Are new/edited posts automatically incrementally added to the index, or do I have to manually re-index the whole index?

3. If I have to manually run the index,  is there a way to trigger it with cron?

**Comment by Rahmon** [comment]
Hi @shmaltz 

1. _**How often do I have to run the index?**_

- You need to index one time. But some settings change require a re-index.

2. _**Are new/edited posts automatically incrementally added to the index, or do I have to manually re-index the whole index?**_

- When you add a new post or edit an existing one they are automatically indexed. You don't need to re-index.

3. _**If I have to manually run the index, is there a way to trigger it with cron?**_

- The plugin makes available [wp-cli](https://10up.github.io/ElasticPress/tutorial-wp-cli.html) commands e.g. `wp elasticpress stats` that returns basic stats on Elasticsearch instance. So you can use them to make some kind of automatization.

**Comment by shmaltz** [comment]
Thank you!
