### ISSUE TITLE
BUG: Woocommerce Search By SKU problem.

### ISSUE THREAD

**Issue by Milan-Nikolic** [10up/ElasticPress#2224]
Hello everyone, I have problems with searching products by sky on this website https://tougetuning.com/ which uses your plugin ElasticPress only for products search.
  When I try to search for "HS11" string I get following results:
  Product 1 : sku -  "HS11STIDTG"
  Product 2 : sku -  "HS11STIGTP"
  Product 3 : sku -  "HS11STIGTT"
  Product 4 : sku -  "HS11STIGM4ST"
  Product 5 : sku -  "HS11STIGM4SS"
  Product 6 : sku -  "HS11STIG3S"
  Product 7 : sku -  "HS11STIG3T"
  Product 8 : sku -  "HS11STI5TG4ST"
  Also I get 6 products with "HS" and "11" found in product title.
  So far that works fine.
  Problem occurs when I try to search for "HS11S" ( I just added one more letter to the end of the string but still all 8 products from above should match ).
  Instead of having similar result I get only Product 6 with sku "HS11STIG3S" and then woocommerce redirect me to that one because it is the only result.
  When I try to type "HS11STI"
  Then I also get one result but now different product - Product 8 with sky "HS11STI5TG4ST".
  If you need some additional information please let me know. Thanks!

**Comment by felipeelia** [comment]
Hi @Milan-Nikolic, thanks for opening the issue. Did you already try to change the SKU field weight in ElasticPress's Weighting Dashboard Screen? Also, it would be great if you could install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) and send us the query and the results for the first search.

Thanks!

**Comment by Milan-Nikolic** [comment]
Hello, thanks for the quick response.
Yes, I tried with changing weight of SKU field but nothing changes.
Of course, here are debug logs for first and second search also:
https://drive.google.com/file/d/1_C95oQaqumdz3xMY8avXD7ZQjKpfmV0h/view?usp=sharing
https://drive.google.com/file/d/1F9gtRqMaW1qgGbdTbhV8jv5SEwiatRYk/view?usp=sharing

**Comment by felipeelia** [comment]
Thanks @Milan-Nikolic,

As per the [Elasticsearch docs about word delimiter token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html), ES will automatically split tokens at letter-number transitions (see `split_on_numerics` there). So, what seems to be happening is that basically when you index something like `HS11STIG3S`, by default Elasticsearch will split it into `HS`, `11`, `STIG`, `3`, and `S`. When you search for `HS11S` that will match the 1st, 2nd, and the last group exactly what doesn't happen to any other.

To change that you'll need to create a new analyzer in the mapping, setting that `split_on_numerics` to false and then apply it to the `meta.sku` field.

Can you please give it a try and let us know the results? Thanks

**Comment by felipeelia** [comment]
Hello again @Milan-Nikolic, I forgot to add it in my last reply but you'll probably need to also add an ngram analyzer to that field, so it will also tokenize it letter by letter.
