### ISSUE TITLE
QUESTION: Is there any way to abort a WP-CLI Index?

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2227]
Is there any way to abort a WP-CLI started Index?

I tried deleting the index and it said "An Index is already occurring. Try again later".

I also tried clicking the **X** on the top right corner of the EP features page, but it did nothing.

**Comment by Rahmon** [comment]
Hi @shmaltz 

You can try to run `wp elasticpress clear-index`. If it doesn't work,  you could try deleting the ep_index_meta option.

**Comment by shmaltz** [comment]
Thank you @Rahmon. 

I believe I tried both of those, but the indexing continued. It did end up stopping eventually though, just not sure why.

**Comment by Rahmon** [comment]
Ok shmaltz :smiley: 

We are going to go ahead and close out this issue. If anything else comes up, please feel free to submit a new issue and we’ll take a look.
