### ISSUE TITLE
QUESTION: Slow when many taxonomy terms

### ISSUE THREAD

**Issue by juansanchezfernandes** [10up/ElasticPress#2228]
So my website has Woocommerce and I have +50k products and thousands "normal" pages/posts. I have also almost 97k product category terms and 50k post category terms. I'm using elastricpress for my facet search. But search gets slow when user select 5-6 terms for the search. Anyways to make it quicker? Would it be quicker if my elasticsearch would be on separate server? Currently the site and the elasticsearch reside on same dedicated server.

**Comment by felipeelia** [comment]
Hi @juansanchezfernandes ,

Did you already try to install [Query Monitor](https://wordpress.org/plugins/query-monitor/) to profile queries being sent to MySQL? There is a change not all queries are using Elasticsearch. Also, [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) can help you to identify queries being sent to ES and their timings. Worth noting that despite its name, the plugin will also work with Query Monitor.
