### ISSUE TITLE
Variable Product Sku Indexing

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2231]
It currently seems as though the SKUs of the variations of a variable product are not indexed. Only the SKU of the parent product is indexed.

Is there a reason for this, and is this something that can be implemented?

**Comment by felipeelia** [comment]
Hi @shmaltz ,

That happens because WooCommerce doesn't register the product_variation as public. You can change that and make them appear in search results with the following snippet. Basically, it will start indexing product variations and add them as a searchable post type. After you put this snippet in your codebase, you'll need to reindex.
"Product Variation" will be a new section in the Weighting Dashboard, so you will need to visit that screen, select SKU as searchable, and save.

```
function ep_custom_index_and_search_prod_variations( $post_types ) {
	$post_types['product_variation'] = 'product_variation';
	
	return $post_types;
}
add_filter( 'ep_indexable_post_types', 'ep_custom_index_and_search_prod_variations' );
add_filter( 'ep_searchable_post_types', 'ep_custom_index_and_search_prod_variations' );

function ep_custom_add_sku_field_weighting_prod_variations( $fields, $post_type ) {
	if ( 'product_variation' === $post_type ) {
		$key = 'meta._sku.value';

		$fields['attributes']['children'][ $key ] = array(
			'key'   => $key,
			'label' => __( 'SKU', 'textdomain' ),
		);
	}

	return $fields;
}
add_filter(
	'ep_weighting_fields_for_post_type',
	'ep_custom_add_sku_field_weighting_prod_variations',
	10,
	2
);
```

**Comment by shmaltz** [comment]
@felipeelia Worked perfectly. Thanks!

Any reason this isn't built into the core WooCommerce feature?

**Comment by felipeelia** [comment]
I think we could include it into the plugin at some point but that is just one of the possible strategies. Someone could, for example, prefer to index variations SKUs with the parent product, so in the search results, only the parent product would be displayed. I'll bring that up internally so we can come up with some next steps on it. Thanks!

**Comment by brandwaffle** [comment]
@felipeelia I'm curious how WooCommerce makes these variations searchable (if it does). If it's doing something to look through non-public posts and that's how it shows/matches on variation titles, etc. then I think we should make it at least an option to explicitly index variations in the WooCommerce Feature.

**Comment by felipeelia** [comment]
@brandwaffle with ElasticPress disabled I can't find anything searching by a product variation sku or description.

**Comment by moorewebx** [comment]
This is fantastic and worked great to index my variation skus.  However, it is returning every single variation in the search results rather than just returning the parent product when searching.  How would I get it to index all variations but only return the parent product when searching?
