### ISSUE TITLE
BUG: When using get_terms it doesn't obey parent = 0

### ISSUE THREAD

**Issue by juansanchezfernandes** [10up/ElasticPress#2232]
On my site I have following:

$terms = get_terms( array( 'taxonomy' => $taxonomy, 'parent' => 0, 'hide_empty' => true,  ) );

Works perfectly, it gets the terms that don't have any parents. 
Now if I add  'ep_integrate' => true, it's doesn't obey the parent = 0 anymore. It gets all the possible terms.

$terms = get_terms( array( 'taxonomy' => $taxonomy, 'parent' => 0, 'hide_empty' => true,  'ep_integrate' => true, ) );

**Comment by Rahmon** [comment]
Hi @juansanchezfernandes 

I did some tests and seems it is working as expected. Could you provide more information about your environment?

**Comment by juansanchezfernandes** [comment]
What information you need about my environment?

Latest WordPress, Woocommerce and Elasticpress plugin in use.

**Comment by Rahmon** [comment]
@juansanchezfernandes What's the Elasticsearch version?

**Comment by juansanchezfernandes** [comment]
Elasticsearch Version 7.13.1

**Comment by felipeelia** [comment]
Hey @juansanchezfernandes, can you please install [Debug Bar](https://wordpress.org/plugins/debug-bar) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugins, copy the content of Query Args, Query Body and Results into a pastebin, and share with us? Thanks.

**Comment by juansanchezfernandes** [comment]
@felipeelia Here

Query Args: https://pastebin.com/LyHeF7De
Query Body: https://pastebin.com/RwQDdyUD
Results: https://pastebin.com/kZyZK9rn
