### ISSUE TITLE
Native ACF UI field management.

### ISSUE THREAD

**Issue by danharper83** [10up/ElasticPress#2234]
It would be useful to be able to control ACF data in the Manage Search Fields & Weighting UI

I would like to be able to select in the UI which ACF fields I want to add to the index, currently all metadata is added to the index making the field mappings on my site really large. Also some of the ACF fields aren't relevant to search and are for display purposes etc.

I've seen that there are some hooks to prevent or allow specific fields but it would be nice to have it in the UI.

Probably a feature or extra plugin?

Happy to have go at a pull request or plugin if somebody can guide me on what the best approach would be to do that.

Thanks Dan

**Comment by felipeelia** [comment]
Hey @danharper83 , sorry for the late response here. We do have plans to handle ACF fields (and meta fields in general) but we are still deciding on the UX of it. We have another plugin called [ElasticPress Labs](https://github.com/10up/ElasticPressLabs), where users already can manage their meta fields using regular expressions.

As we already have #1690 related to this same issue, I'm going ahead and closing this one. Thanks!
