### ISSUE TITLE
QUESTION: Search returning less relevant results

### ISSUE THREAD

**Issue by DenisFlorin** [10up/ElasticPress#2236]
Hello,

Do you have any ideas why the search is returning less relevant results?

![image](https://user-images.githubusercontent.com/38504865/122961929-90e97300-d38d-11eb-9ecb-6853d134fdda.png)

We have posts with the words from the search in the title, but the search returns irrelevant results.

Let me know if it's not clear or if you need any other information.

Best regards,

**Comment by Rahmon** [comment]
Hi @DenisFlorin 

Did you try to change the algorithm version?
```php
add_filter( 'ep_search_algorithm_version', function() { return '3.4'; } );
```

> As of version 3.5 of ElasticPress, there are two options for search algorithms. The default is the new 3.5 algorithm, which searches for the existence of all words in the search first, then returns results based on how closely those words appear. The 3.4 and earlier algorithm uses a fuzzy match approach which includes results that have misspellings, and also includes matches on only some of the words in the search (vs all words appearing somewhere in the result, even if not directly next to one another).



Ref: https://elasticpress.zendesk.com/hc/en-us/articles/360051783011-Search-Algorithm-Options
