### ISSUE TITLE
BUG: WooCommerce shop orders listing is empty when WooCommerce feature is enabled

### ISSUE THREAD

**Issue by lucalbert** [10up/ElasticPress#2239]
**Describe the bug**

When the WooCommerce functionality is enabled, the order list is empty in the backoffice (but the actual number of orders is displayed for each status).

In the ElasticSearch index, there is no content of type "shop_order" (even after a resynchronization).

**Steps to Reproduce**

1. Go to ElasticSearch > Features
2. Enabled WooCommerce feature and reindex data
3. Go to WooCommerce > Orders
4. The order list table is empty

**Expected behavior**

See the list of orders

**Screenshots**

![image](https://user-images.githubusercontent.com/6500267/123398467-dd0e0080-d5a3-11eb-84a8-0d5839daf3eb.png)

**Environment information**
 - WordPress version: 5.7.2
 - ElasticPress version: 3.5.6
 - Elasticsearch version: 5.6.16
 - Where do you host your Elasticsearch server? private
 - What ElasticPress features do you have currently active? Post Search, WooCommerce, Protected Content, Related Posts, Facets, Custom Search Results, Integration WPML with ElasticPress

**Comment by felipeelia** [comment]
Hi @lucalbert,

I couldn't reproduce the error, so can you please go through the following steps and let us know the outputs?
1. Index via WP-CLI to check any possible errors with: `wp elasticpress index --setup --show-errors`
2. Install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/)
3. Visit the order list screen, open Debug Bar ElasticPress and share with us the queries and their results.

Thanks!
