### ISSUE TITLE
BUG: Command Line Undefined Variable Warning Notice Flood

### ISSUE THREAD

**Issue by notjustcode-sp** [10up/ElasticPress#2240]
When performing a command line sync in blocks of 350 we get the following notice three times:

`Warning: Request Entity Too Large`

Followed by a warning flood:

`PHP Notice:  Undefined variable: item in elasticpress/includes/classes/Command.php on line 960`

Followed by a further flood:

```
PHP Notice: Undefined index: type in elasticpress/includes/classes/Command.php on line 1021
PHP Notice: Undefined index: reason in elasticpress/includes/classes/Command.php on line 1022
PHP Notice: Undefined index: type in elasticpress/includes/classes/Command.php on line 1027
```

We can see that the _$attempts_ for loop is hitting the **continue** statement on line 941 meaning that we never get to the **if/else** statement on line 944.

This means that when we get to line 959 _$index_objects_ hasn't been reset (line 951) and _$item_ does not exist (line 945) hence the warning flood.

Whilst the **foreach** of line 959 could be guarded with a check to see if $_item_ is set, we're not sure whether this is appropriate as we don't understand enough about the code to know what this **foreach** is doing and why it's using $_item_.

**Steps to Reproduce**
1. Visit top level WP directory.
2. Run the command: 
`wp elasticpress index --setup`

3. Observe the warning flood.

**Expected behavior**
Warning that the Request entity is too large without the flood of "undefined variable" warning messages.

**Environment information**
 - Device: Desktop PC 
 - OS: Debian 10 buster
 - WordPress version: 5.7.2
 - ElasticPress version: 3.5.6
 - Elasticsearch version: 7.13.2
 - Where do you host your Elasticsearch server? localhost

**Comment by felipeelia** [comment]
Hi @notjustcode-sp, actually, the warning flood happens because Elasticsearch doesn't send that info for the error you are having (it does for some others). The if/else is there to remove errored objects from the full list and works as expected.

You do have a point though. The plugin shouldn't assume `$error` has a `type` or a `reason` inside `output_index_errors`. Can you please check if #2243 fixes the error for you? Thanks

**Comment by notjustcode-sp** [comment]
Hi @felipeelia, unfortunately #2243 does not fix the issue:

```
$ wp elasticpress index --setup                        
Adding post mapping...
Success: Mapping sent
Indexing posts...
Processed 350/1450...
Warning: Request Entity Too Large
Warning: Request Entity Too Large
Warning: Request Entity Too Large
PHP Notice:  Undefined variable: item in /wp-content/plugins/elasticpress/includes/classes/Command.php on line 960
Notice: Undefined variable: item in //wp-content/plugins/elasticpress/includes/classes/Command.php on line 960
... x350 warnings!
```

The if/else that removes errored objects is never reached because of the **continue** statement on line 941.

This means that when we get to line 959 _$index_objects_ does exist, but _$item_ does not exist. It's the foreach on line 959 that's causing the flood we're reporting here.

As previously stated, we're not sure why this foreach statement is using _$item_ on line 960 as we don't know what the purose of this foreach statement is.

**Comment by felipeelia** [comment]
You are absolutely right, @notjustcode-sp, sorry. That `$item` there was really wrong. Can you please give #2243 another try? I've pushed a new commit there that (1) should address the warning flood problem and (2) give correct details for each failed document.

Thanks!

**Comment by notjustcode-sp** [comment]
Success!

No PHP warning flood:

```
Adding post mapping...
Success: Mapping sent
Indexing posts...
Processed 350/1450. Last Object ID: 14221
Warning: Request Entity Too Large
Warning: Request Entity Too Large
Warning: Request Entity Too Large
Processed 700/1450. Last Object ID: 12861
Warning: Request Entity Too Large
...
```

We thought _$item_ looked wrong, but didn't know enough about the code to fix it!

Thanks!
