### ISSUE TITLE
Tracking indexing status per-post

### ISSUE THREAD

**Issue by ryanboswell** [10up/ElasticPress#225]
We recently ran into an odd issue where some posts were not synced/indexed to Elasticsearch for some reason, there wasn't any log information (that we could find) to indicate the exact reason.  But we had a few server issues around the time this happened, and it's possible that the part of the request that indexed these posts was aborted and so they were skipped, since we has similar issues with other plugins that run operations in the 'background'.

In confirming/diagnosing this, I had to run a lot of manual queries comparing posts in WP to documents in ES and sort through things. There's some issues with this in that it's very time-consuming and hard to do.

A thought that might help with this is to add a protected meta value to posts after they are indexed (or re-indexed on save) that stores the timestamp of when they were last updated in ES. Since it's a protected meta key, it won't be needlessly indexed in ES, but we could run a one-time query in WordPress or MySQL for posts without that key set to find posts that are missing from ES. Emphasis on a one-time query (as a debug/help measure) and not a regular thing since meta key searches are horribly inefficient in WordPress.

With that information we can better determine if it's a glitch or issue with a few specific posts or widespread and that can help determine the route to get those posts into the index (ie. just go in and manually re-save a dozen posts, or perform a full re-index to catch a few hundred or thousand).

Thoughts?

**Comment by tlovett1** [comment]
We used to have this but decided to pull it out. I'm okay with putting it back. @AaronHolbrook ?

**Comment by ryanboswell** [comment]
Maybe have it as optional for 'advanced' users that want it or when doing testing?

**Comment by AaronHolbrook** [comment]
As it seems to be more for debugging purposes, and a pretty unorthodox debugging method at that, I don't think it would make sense to do this by default. @ryanboswell you could easily use a filter in EP or even just on transition_post_status yourself to add a protected meta key timestamp.

**Comment by ethanclevenger91** [comment]
I'd actually like to see this re-opened with admin interfaces to go with it. It would open the door to running an index of only un-indexed content as well. 

For instance, I'm indexing content on a site w/ 290K documents. It's running in an auto-scaling environment, so occasionally a box is killed while the CLI process is running. My only mechanism for picking up where it left off is to use `--offset=######` where the number is copied and pasted from the progress output from the last attempt.

It seems it would be reasonable to be able to run `wp elasticsearch index --only-unindexed` or something like that to just pull posts that haven't already been indexed, and a meta key would be needed for that. 

This could be extended to the admin panel with a "% indexed" chart and similar only-unindexed indexing functionality.
