### ISSUE TITLE
One custom post type are not being indexed

### ISSUE THREAD

**Issue by shaneonabike** [10up/ElasticPress#2251]
**Describe your question**
Basically, I have quite a few custom post types that are properly indexing. As well, I have set it up to index properly all my ACF fields too. For now everything seems to work super well. Once of my Custom Post Types is called Local, but this seems to never actually index unless I force it through the wp-cli.

Is there some way to debug this further to see which ID is being indexed and turn on further debug messages with ElasticPress. My only initial guess is that local is some reserved word or something?

**Comment by felipeelia** [comment]
Hi @shaneonabike,

Is that Custom Post Type public? By default, ElasticPress will only index CPTs marked as public: https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Indexable/Post/Post.php#L112

**Comment by shaneonabike** [comment]
Yep both public and public_queryable set to true, which is why I find this really strange issue. I'm going to re-index tomorrow and see if I can't see anything in the logs of elasticsearch. I find it hard to know which IDs are being indexed since there isn't an advanced debug.

**Comment by felipeelia** [comment]
Doesn't `wp elasticpress index --setup --no-bulk --show-errors` help you with that?

**Comment by shaneonabike** [comment]
No actually it says that it indexes everything cleanly. There are some deprecation warnings but that's due to a few plugins which is fine. That's what I find weird I can't see _which posts_ are being indexed. Maybe there is a hook missing I could spew out an message in the error_logs?

**Comment by felipeelia** [comment]
You could use the `ep_after_bulk_index` action, for example, checking `$object_ids` and `$result` (see [here](https://github.com/10up/ElasticPress/blob/3.6.0/includes/classes/Indexable.php#L341)). Does that help @shaneonabike?

**Comment by shaneonabike** [comment]
Hey @felipeelia I gave that a shot and cannot see any major errors besides a Redis connection lose, and 
```
Warning: array_keys() expects parameter 1 to be array, null given in /wp-includes/wp-db.php on line 2275
PHP Warning:  implode(): Invalid arguments passed in /wp-includes/wp-db.php on line 2275
Warning: implode(): Invalid arguments passed in /wp-includes/wp-db.php on line 2275
PHP Notice:  wpdb::prepare was called <strong>incorrectly</strong>. The query argument of wpdb::prepare() must have a placeholder. $
Notice: wpdb::prepare was called <strong>incorrectly</strong>. The query argument of wpdb::prepare() must have a placeholder.
```

The second is quite odd. Again, it never indexed the post IDs of the custom type I have as I searched the output for their ID numbers. There was no error messages really besides what was posted above.

Then when I forced the specific post type the items are indexed without issue, which is kind of strange... no errors nothing.

**Comment by felipeelia** [comment]
Hi @shaneonabike , it seems for some reason the posts are not even included as something that should be indexed, is that right? Did you already try to hook a function to the `ep_index_posts_args` filter and check how the WP_Query args look like?
