### ISSUE TITLE
Elasticsearch 8.0 analysis changes

### ISSUE THREAD

**Issue by maciejmackowiak** [10up/ElasticPress#2254]
In ES 8.0 version the edgeNGram token filter name will be removed.
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

All edgeNGram filters should be replaced with edge_ngram.
https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_analysis_changes

https://github.com/10up/ElasticPress/search?q=edgeNGram

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by felipeelia** [comment]
Hi @maciejmackowiak ,

Thanks for opening this issue. When ES 8.0 gets released we probably will need new mapping files. In the meantime, it seems we could replace it with `edge_ngram` in ES 7.0 mappings, though. Do you want to craft a Pull Request with that? Thanks!

**Comment by felipeelia** [comment]
As the changes needed for ES 7.0 were made in ElasticPress 3.6.2, I'm closing this issue now.
