### ISSUE TITLE
If using fields => ids in WP_Query, ElasticPress nullifies the request

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#227]
Just stumbled across this one.

**The Problem**
----------------------

Given a `WP_Query` arg array of the following:

```
$args = array(
  'post_type' => 'post',
  'fields' => 'ids',
  's' => 'findme',
);
```

ElasticPress runs and may / may not find posts. However, in WP's own `query.php` on L:3433: https://github.com/WordPress/WordPress/blob/bce851dcf25439a74c3f7ce42bb784c84ca8f3cc/wp-includes/query.php#L3433

`get_posts` actually just takes the request SQL and determines the number of found posts and returns immediately.

This deviates from what ElasticPress is expecting, which intentionally causes the SQL query to be nullified (`1 = 0`) because it wants to refill it later in `the_posts` filter down on http://github.com/WordPress/WordPress/blob/bce851dcf25439a74c3f7ce42bb784c84ca8f3cc/wp-includes/query.php#L3631 
where it refills the query object with all the posts it found.

**Ways forward**
-----------------------

I think during our filter of `posts_request`, we check to see if the user is requesting one of these early return fields `ids` or `id=>parent` and return a valid SQL query that will supply the IDs and site IDs of the posts returned. The problem with this that I see is that even though we could supply the IDs for cross site, the only field return is IDs, which doesn't provide a way for us to indicate which blog the post ID came from.

**Comment by joeyblake** [comment]
```id=>parent``` is easy enough to add the ```site_id``` to the results. So the consensus needs to be on how best to handle splitting up multi site id returns. What makes the most sense? Splitting the ids results up into 

```
'posts' => array(
    [$site_id] => array($ids),
    [$next_site_id] => array($ids)
)
```

Or do we nullify a search for ids on a multi-site search, and require using either 'id=>parent' or a new param 'id=>site' in those instances?

Or

**Comment by tlovett1** [comment]
So we are going to pass on this one for the following reasons:
1. This is useful for MySQL since it makes queries more performant. This isn't necessary for Elasticsearch
1. We can't really make this work with cross-site searches since we need a site id with the post id.
1. Seems like this isn't possible anyway with the final mapping of `get_post` in the main `WP_Query` query method.

Thanks to @AaronHolbrook for the report and @joeyblake for investigating.
