### ISSUE TITLE
I need to return results for titles of products that contain hyphens

### ISSUE THREAD

**Issue by danharper83** [10up/ElasticPress#2271]
Hi,

When a customer searches for products by model number they use product numbers both with and without the hyphen. For example I have a product with a title of DJM-V10. 

I need the product to be returned whether the customer searches
DJMV10 or DJM-V1O 

In both upper and lower case.

Reading the elasticsearch documentation this is possible by changing the word delimiter token filter https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html

I think the default one in elasticpress is `word_delimiter` where as I need to use `synonym_graph` instead. Is it possible to change this just for the title field on the product post type for example?

Cheers Dan

**Comment by Rahmon** [comment]
Hi @danharper83 

Did you try to change the algorithm version?
```php
add_filter( 'ep_search_algorithm_version', function() { return '3.4'; } );
```

> As of version 3.5 of ElasticPress, there are two options for search algorithms. The default is the new 3.5 algorithm, which searches for the existence of all words in the search first, then returns results based on how closely those words appear. The 3.4 and earlier algorithm uses a fuzzy match approach which includes results that have misspellings, and also includes matches on only some of the words in the search (vs all words appearing somewhere in the result, even if not directly next to one another).

However, in case you want to make some tests changing the [filters](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenfilters.html) used by ElasticPress you can do it using the filter [ep_post_mapping](https://10up.github.io/ElasticPress/ep_post_mapping.html).

Ref: https://elasticpress.zendesk.com/hc/en-us/articles/360051783011-Search-Algorithm-Options
