### ISSUE TITLE
One specific custom post type hangs on indexing

### ISSUE THREAD

**Issue by rolandp** [10up/ElasticPress#2273]
**Describe your question**
Something similair to issue https://github.com/10up/ElasticPress/issues/2251, except in my case indexing the troublesome Custom Post Type hangs the entire process (PHP with wp cli, PHP-FPM through the edit page).

Curiously there seems to be a problem with the name of the Custom Post Type (jobs), because doing a SQL update query to change the CPT from jobs to, for instance, temp makes the posts index as normal. Unfortunately changing the name of the CPT isn't an option, since the code base relies on that name too much.

There must be a reason that this happens just with this specific CPT name.

So far I've tried:
- disabling custom filters;
- checking nginx error logs (empty);
- different combinations of versions. (This used to work with Elasticsearch 6.2.4 but this isn't supported after my upgrade anymore);
- checking elasticsearch indexing and regular logs: no info;
- running the CLI with --debug and --show-errors: process hangs so no output

Used versions:
Elasticpress: 3.6 (happens with all versions checked down to 3.2)
Elasticsearch: 7.1.1 (highest recommended version)

**Question**
What can I do to investigate the cause of this problem?

**Comment by Rahmon** [comment]
Hi @rolandp 

Just to be sure, when you change the name of CPT from `job` to `temp` it works?

**Comment by rolandp** [comment]
> Hi @rolandp
> 
> Just to be sure, when you change the name of CPT from `job` to `temp` it works?

@Rahmon That's correct. Manually changing the `post_type` from 'jobs' to 'temp' (or anything other than 'jobs' makes the posts get indexed without a problem. That indicates to me that i have some code that interferes with the indexing of 'jobs' posts.

**Comment by Rahmon** [comment]
@rolandp 

I tested using Elasticsearch versions 5 and 7 and I couldn't reproduce the error. You can try the command `wp elasticpress index --post-type=jobs --show-errors` to see if you can a clue of what is happening.
