### ISSUE TITLE
BUG: only the "post" indexable is acted upon when a site's status changes

### ISSUE THREAD

**Issue by dustinrue** [10up/ElasticPress#2275]
**Describe the bug**
When a site in a multisite setup is updated so that it is archived, deleted or marked as spam, only the "post" indexable will be acted upon because it is the only indexable that adds actions for those items (https://github.com/10up/ElasticPress/blob/3.6.1/includes/classes/Indexable/Post/SyncManager.php#L53 vs https://github.com/10up/ElasticPress/blob/3.6.1/includes/classes/Indexable/Term/SyncManager.php#L37). This leaves data on the backend server.

**Steps to Reproduce**

1. Have a multisite
2. Create an additional site
3. Enable some other indexable in the dashboard, such as terms
4. Index all sites
5. Note the indexes created in the backend
6. Mark a site as deleted
7. Note the index that still exist in the backend will include indexable items other than post

**Expected behavior**

All indexes should be removed from the backend server/service

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - ElasticPress version: 
 - Elasticsearch version: 
 - Where do you host your Elasticsearch server? 
 - What ElasticPress features do you have currently active? 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by felipeelia** [comment]
Let's have it fixed on Terms AND Comments, as it seems it would generate the same error.
