### ISSUE TITLE
BUG: Does Elasticpress is overriden if we implemented a custom search instead of the default one?

### ISSUE THREAD

**Issue by realleoman** [10up/ElasticPress#2277]
**Describe the bug**
We implemented this snippet to make a custom search on WP only for the Title instead of the default one.

```
function __search_by_title_only( $search, $wp_query )
{
    global $wpdb;
    if(empty($search)) {
        return $search; // skip processing - no search term in query
    }
    $q = $wp_query->query_vars;
    $n = !empty($q['exact']) ? '' : '%';
    $search =
    $searchand = '';
    foreach ((array)$q['search_terms'] as $term) {
        $term = esc_sql($wpdb->esc_like($term));
        $search .= "{$searchand}($wpdb->posts.post_title LIKE '{$n}{$term}{$n}')";
        $searchand = ' AND ';
    }
    if (!empty($search)) {
        $search = " AND ({$search}) ";
        if (!is_user_logged_in())
            $search .= " AND ($wpdb->posts.post_password = '') ";
    }
    return $search;
}
add_filter('posts_search', '__search_by_title_only', 500, 2);
```

The issue we are having is that we are thinking the ElasticSearch server is not being called when searching for any word so (we think) the database is being called instead

**Steps to Reproduce**

1. Go to zocalo.com, and click on the magnifier icon at the right
2. Type any word: "pegasus" is a good one
3. You will get a few results with a Thumbnail (maybe less than 30) but it takes a lot of time to show. (more than 4-5 seconds). 
4. If you enter a new word (Mexico), it will take more than 34 seconds to return results
5. Please nevermind the additional list for results shown below. That is using another plugin.

**Expected behavior**
1. We are looking to optimize the query time to the database since we have around 2Million records and we need to deliver content from the search real quick

**Screenshots**

**Environment information** (this is applicable for any OS and Operating System
 - ElasticPress version: 3.5.4
 - Elasticsearch version: 7.9
 - Where do you host your Elasticsearch server? Digital Ocean
 - What ElasticPress features do you have currently active? Post Search - Theme and version: Custom Theme
 
 - <details><summary>Site Health Info:</summary> (see image below) We don't have an INFO Tab in the Index Health section
<img width="1314" alt="Screen Shot 2021-07-21 at 5 20 45 PM" src="https://user-images.githubusercontent.com/699501/126567473-4e68ff7d-a547-49d4-99dc-19322922f278.png">

   </details>

**Comment by Rahmon** [comment]
Hi @realleoman 

If you want to search only for the Title, you can set up it accessing WP Dashboard -> ElasticPress ->  Search Fields & Weighting.

Another approach could be using the filters [ep_search_fields](https://10up.github.io/ElasticPress/ep_search_fields.html) or [ep_weighting_configuration_for_search](https://10up.github.io/ElasticPress/ep_weighting_configuration_for_search.html).

Adding a custom WHERE clause will not change the Elasticsearch query (see [supported WP_Query parameters by ElasticPress](https://10up.github.io/ElasticPress/tutorial-indexables.html)).

**Comment by realleoman** [comment]
Hi @Rahmon  Thanks for your answer. Actually, we have created in WordPress to only search by Title but my main question is if this custom search does not override the Elasticpress search.

**Comment by brandwaffle** [comment]
@realleoman ElasticPress won't work with that query as @Rahmon mentioned since it's using direct SQL rather than applying parameters to WP_Query. You can confirm if ElasticPress is handling any query by installing the Debug Bar and Debug Bar ElasticPress plugins and viewing the query results. More info is available here https://elasticpress.zendesk.com/hc/en-us/articles/360052023891-I-would-like-to-run-custom-WP-Query-calls-through-ElasticPress-How-can-i-do-this- and https://elasticpress.zendesk.com/hc/en-us/articles/360050720172-Using-the-Debug-Bar-ElasticPress-Plugin
