### ISSUE TITLE
BUG: Facet Widget not included in the Legacy Widget Block

### ISSUE THREAD

**Issue by goaround** [10up/ElasticPress#2278]
**Describe the bug**

As of WordPress 5.8 the Widgets are block-based, but there is a Legacy Widget Block availably to display the old widgets. But the Facet Widget is missing there and at the moment there is no Block availably. The Related Post Widget is present.

**Steps to Reproduce**
1. Upgrade to WordPress 5.8
2. Go to Widgets
3. Select the Legacy Widget Block
4. See the list of legacy widgets without the Facet Widget

**Expected behavior**

The Facet Widget should be availably in the Legacy Widget Block for now.

**Screenshots**

![Bildschirmfoto 2021-07-22 um 10 40 01](https://user-images.githubusercontent.com/5927337/126611759-dd9f1af9-12ec-4c8b-ac51-3b5f4b0497cc.png)

**Environment information**
 - WordPress version: 5.8

**Comment by Rahmon** [comment]
Hi @goaround 

I can see the widget in the Legacy Widget Block. Did you activate the Facets feature?

![image](https://user-images.githubusercontent.com/6010232/126820679-f492d4a3-12b6-48d2-b5bb-781774d5b48e.png)

**Comment by goaround** [comment]
@Rahmon I found the issue on my site. Thank you, works now.
