### ISSUE TITLE
Start Sync and related icon links need title and/or aria-label

### ISSUE THREAD

**Issue by claytoncollie** [10up/ElasticPress#2286]
This is my first time using this plugin and was looking for the re-index option and came across the `start-sync` icon in the top right corner of the Settings screen. Being totally new to this plugin, I didn't know for sure that this was what I wanted. Adding either a `title` attribute or `aria-label` or some sort of tooltip would give the user a bit more information before clicking the icon.

File reference: https://github.com/10up/ElasticPress/blob/aa1d42fa202f804b74bec710dab46eceb8309353/includes/partials/header.php#L29

I have a PR ready to get the conversation started. Just need write access to this repo to send it up.

**Comment by Rahmon** [comment]
@felipeelia this is related to #1835, right?

**Comment by felipeelia** [comment]
Somewhat related, yes, @Rahmon but can be worked right after we merge the new IndexHelper code we're creating for 3.7.0.
