### ISSUE TITLE
orderby date not working

### ISSUE THREAD

**Issue by jonathan-dejong** [10up/ElasticPress#229]
Hi!

Got this site where I use EP with a network query using ep_integrate. It's working just fine except it wont order by date instead of relevance (atleast I assume it's using relevance, it's not a search query). You can see the results here: http://kfsk.se/nyheter/

And this is the query:

```
<?php
                              $args = array(
					'ep_integrate' => true,
					'post_type' => 'post',
					'posts_per_page' => 3,
					'orderby' => 'date',
					'order' => 'DESC',
					'meta_query' => array(
						'relation' => 'OR',
						array(
							'key' => 'post_to_page_hide',
							'compare' => 'NOT EXISTS'
						),
						array(
							'key' => 'post_to_page_hide',
							'value' => 1,
							'compare' => '!='
						)
					)
				);
				
				//Search in every site
		        $sites = wp_get_sites();
		        $excluded_sites = get_blog_option(1, 'options_network_excluded_sites');
		        $site_ids = array();
		        //but first, exclude the sites we dont want
		        foreach($sites as $key => $site){
			        if(in_array($site['blog_id'], $excluded_sites)){
				        unset($sites[$key]);
			        }else{
				        $site_ids[] = $site['blog_id'];
			        }
		        }
		        //if there are sites left, lets search in them!
		        if(!empty($site_ids)){
			        $args['sites'] = $site_ids;
		        }
				$global_postquery = new WP_Query($args);

?>
```

I can't see anything wrong with it but for some reason it just doesn't want to change the orderby..

**Comment by jonathan-dejong** [comment]
I've also tried simplifying it by removing the meta_query and still no dice. 
It works when I change the orderby to title or name.. those both work as expected. But not date.

**Comment by psorensen** [comment]
see #206, this addition has already merged into develop branch.

**Comment by tlovett1** [comment]
This will be merged into the next version of EP.

**Comment by jonathan-dejong** [comment]
Ah okay great news!
Bit confusing as the docs says it supports it already :) 

Any thoughts on when the next stable will come or is it possible to use dev branch on a live site?

**Comment by jonathan-dejong** [comment]
Never mind. I just integrated the changes myself until it comes in stable :) 

A headsup, it seems ordering by date and setting the order parameter to ASC disables the date ordering. Atleast in a multisite setup when querying multiple sites

**Comment by tlovett1** [comment]
Sorry the doc shouldn't say that. Develop branch *should* be stable. We are hoping to release the next version in the next month.

Regarding date ordering, if this is an issues, can you open up a new issue?
