### ISSUE TITLE
Add a help text for field "Weight results by date"

### ISSUE THREAD

**Issue by Rahmon** [10up/ElasticPress#2291]
**Is your enhancement related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When the field "Weight results by date" is enabled the Elasticsearch will not compute the decay function for documents that were created with a distance less than 7 seven days (default value defined by ElasticPress) from the origin (current date). This is a way to boost the most recent documents.

Although this is interesting for pages and posts, it couldn't be for products. Especially when the algorithm version 3.4 is used. So,  my suggestion is to add a help text for the field "Weight results by date" to clarify this behavior.

Example how it happens:

- Enable "Weight results by date" field, WooCommerce feature and, algorithm version 3.4
- Create three products: Eanie, Beanie, and Beanie with Logo
- Change the published date for Beanie and Beanie with Logo for a month behind
- Search for "Beanie"

Results:

1. Eanie
2. Beanie
3. Beanie with Logo

Disabling "Weight results by date" the result for the same search is:

1. Beanie
2. Beanie with Logo
3. Eanie

**Designs**

**Describe alternatives you've considered**
Detecting if WooCommerce Feature and "Weight results by date" field is enabled, then show a warning in the Post Search feature.

**Additional context**

**Comment by felipeelia** [comment]
Closed by #3462
