### ISSUE TITLE
Delete an elasticsearch document

### ISSUE THREAD

**Issue by DenisFlorin** [10up/ElasticPress#2296]
Hello,

I have a problem when I delete a post from the website.

The post still appears in search results probably because is also stored in the elasticsearch database.

![Selection-157 (1)](https://user-images.githubusercontent.com/38504865/128735040-d63ddfbc-1ac2-44ea-aeb3-e68f6d9416f6.png)

Do you have any idea how I can delete that index?

Looking at the code in ElasticPress I saw the below function, but I’m not sure if I can do something from the WordPress interface.

	public function delete_document( $index, $type, $document_id, $blocking = true ) {
		if ( version_compare( $this->get_elasticsearch_version(), '7.0', '<' ) ) {
			$path = $index . '/' . $type . '/' . $document_id;
		} else {
			$path = $index . '/_doc/' . $document_id;
		}

		$request_args = [
			'method'   => 'DELETE',
			'timeout'  => 15,
			'blocking' => $blocking,
		];

		$request = $this->remote_request( $path, $request_args, [], 'delete' );

		if ( ! is_wp_error( $request ) ) {
			$response_body = wp_remote_retrieve_body( $request );

			$response = json_decode( $response_body, true );

			if ( ! empty( $response['found'] ) ) {
				return true;
			}
		}

		return false;
	}

**Comment by Rahmon** [comment]
Hi @DenisFlorin 

ElasticPress automatically removes a post from Elasticsearch when it is deleted. 

You can check if the function [action_delete_post](https://github.com/10up/ElasticPress/blob/62ca2ee8803bf6ff36aa10949f2662e62f294d03/includes/classes/Indexable/Post/SyncManager.php#L187) is called when a post is deleted. This function is added in the WordPress hook `delete_post`.
