### ISSUE TITLE
Bump minimum PHP to 7.0 for EP 3.7

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#2300]
PHP version updated to min 5.6 in 3.6.2. See #2292

**Comment by ActuallyConnor** [comment]
Hey @brandwaffle I have made a PR for this issue [https://github.com/10up/ElasticPress/pull/2394](https://github.com/10up/ElasticPress/pull/2394). Let me know if you have any questions or would like me to change anything.

**Comment by felipeelia** [comment]
Closed by #2485
