### ISSUE TITLE
Setting Multiple Indexes with Different Analysers for a Multilingual Website

### ISSUE THREAD

**Issue by simohammedhttp** [10up/ElasticPress#2308]
Hello,

I have a multilingual website using PolyLang. I want to properly integrate ElasticPress with PolyLang. Unfortunately, I can’t find how to do it.

I want to achieve these two requirements:

1/ Instruct ElasticPress to create a separate index per language and use the correct analyzer (filtering, tokenizing, stop words, stemming, …).

2/ Instruct ElasticPress to choose a specific index according to the current language and also to use the correct analyzer when looking for related articles or searching for some terms.

I know how to grab the current locale with PolyLang (en, fr, es, …) in functions.php but I don’t know how to instruct ElasticPress to correctly index/search in a multilingual environment.

**Comment by Rahmon** [comment]
Hi @simohammedhttp 

There is an integration with WPML and I think the following links could help you (even you're using PolyLang):
- https://wpml.org/documentation/plugins-compatibility/using-elasticpress-on-your-multilingual-site/
- https://github.com/OnTheGoSystems/wpml-elasticpress/

**Comment by simohammedhttp** [comment]
Hi @Rahmon , thanks. I already saw these pages when doing my research, but they are made for WPML which has its own ecosystem. PolyLang is a free and widely used plugin but I couldn't find any documentation related to its integration with ElasticPress.

**Comment by mckdemps** [comment]
We're not aware of any existing PolyLang ElasticPress connector but the WPML approach would likely serve as a good template if you'd like to write your own.

**Comment by TommyKolkman** [comment]
Hi @simohammedhttp, did you ever get this working? Quite stuck on this for a client.

**Comment by simohammedhttp** [comment]
Hi, unfortunately I gave up using Elastic Search, it means that I don't have multiligual full search feature in my blogs.
