### ISSUE TITLE
QUESTION: Support for nested aggregations

### ISSUE THREAD

**Issue by Shrimpstronaut** [10up/ElasticPress#2309]
**Describe your question**

I'm currently trying to implement nested aggregations when querying my Elasticsearch instance using the Elasticpress plugin.
Unfortunately I'm unable to do so and after looking through the source code, I'm pretty sure this feature is not available.

I have found the relevant code inside of https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L1692

```php
/**
* Aggregations
*/
if ( isset( $args['aggs'] ) && ! empty( $args['aggs']['aggs'] ) ) {
	$agg_obj = $args['aggs'];

	// Add a name to the aggregation if it was passed through
	if ( ! empty( $agg_obj['name'] ) ) {
		$agg_name = $agg_obj['name'];
	} else {
		$agg_name = 'aggregation_name';
	}

	// Add/use the filter if warranted
	if ( isset( $agg_obj['use-filter'] ) && false !== $agg_obj['use-filter'] && $use_filters ) {

		// If a filter is being used, use it on the aggregation as well to receive relevant information to the query
		$formatted_args['aggs'][ $agg_name ]['filter'] = $filter;
		$formatted_args['aggs'][ $agg_name ]['aggs']   = $agg_obj['aggs'];
	} else {
		$formatted_args['aggs'][ $agg_name ] = $agg_obj['aggs'];
	}
}
```

This will only check for the first aggregation inside the query, but will ignore any nested aggregations.

Is there anything I'm missing or should I instead set up a feature request?

**Comment by Rahmon** [comment]
Hi @Shrimpstronaut 

You can customize the query sent to Elasticsearch using the filter [ep_formatted_args](https://github.com/10up/ElasticPress/blob/bc8e16588b6ccf0b2edb7ff6a5c6b847f2078780/includes/classes/Indexable/Post/Post.php#L1722).

**Comment by Shrimpstronaut** [comment]
Hey @Rahmon,
thanks for the reply. I will be using the [ep_formatted_args](https://github.com/10up/ElasticPress/blob/bc8e16588b6ccf0b2edb7ff6a5c6b847f2078780/includes/classes/Indexable/Post/Post.php#L1722) filter to alter the query.
