### ISSUE TITLE
BUG: Using post_tag in query is setting the slug param in a wrong format

### ISSUE THREAD

**Issue by pabamato** [10up/ElasticPress#2310]
**Describe the bug**

[From the WP_Query docs](https://developer.wordpress.org/reference/classes/wp_query/#tag-parameters), if you use slugs as the matching param, you can pass params in two formats:

- Array of slugs
- String of comma separated slugs

On https://github.com/10up/ElasticPress/blob/trunk/includes/classes/Indexable/Post/Post.php#L844,
The params gets converted to an array, so looks like you can not query for multiple values.

Same wrong format on https://github.com/10up/ElasticPress/blob/trunk/includes/classes/Indexable/Post/Post.php#L852
Also, looks like this is being added with the correct format later on https://github.com/10up/ElasticPress/blob/trunk/includes/classes/Indexable/Post/Post.php#L906
'post_tag' is the query_var for that particular taxonomy

**Steps to Reproduce**

Query posts passing multiple post_tags:
Having a site with 2 posts(post1, post2) and 2 terms in post_tags(slug1,slug2):
post1 ->slug1
post2 ->slug2
```
$args_for_multiple_slugs_array_format = [
	'post_tag' => [
		'slug1',
		'slug2',
	],
];
$args_for_multiple_slugs_string_formnat = [
	'post_tag' => 'slug1,slug2',
];
$posts_query = new \WP_Query( $args_for_multiple_slugs_array_format );
$posts_query = new \WP_Query( $args_for_multiple_slugs_string_formnat );
```

**Expected behavior**
Both queries should return 2 posts since it should match posts having either slug1 or slug2.

**Screenshots**

**Environment information**
 - Device: MacBook
 - OS:  MacOS 11.14.0
 - Browser and version: any
 - WordPress version: 5.8
 
 - ElasticPress version: 3.6.1
 - Elasticsearch version: 5.6.16
 - Where do you host your Elasticsearch server? 10updocker
 - What ElasticPress features do you have currently active? -
 - Plugins and version:N/A
 - Theme and version: N/A
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by pabamato** [comment]
Adding additional details for replicating the issue:
- Default WordPress install with twenty-twentyone theme.
- Filtering the main query and passing post_tag is causing an error in the ElasticPress endpoint
If I pass post_tag within 'tax_query', is working as expected

![image](https://user-images.githubusercontent.com/4009928/129832327-a8cb0e6c-d586-4bb2-b3ac-953d652a364e.png)
![image](https://user-images.githubusercontent.com/4009928/129832545-28ece9e3-847e-458b-99b4-231e84e92f15.png)
![image](https://user-images.githubusercontent.com/4009928/129833079-bff12a98-65e3-401f-bdd8-88f71e797949.png)

![image](https://user-images.githubusercontent.com/4009928/129832790-9c234876-9e30-4cf6-8f7f-687b0da987be.png)

**Comment by pabamato** [comment]
If that helps to speed-up the debug process, I created a gist having a site export xml file and part of the code I'm using:
https://gist.github.com/pabamato/9825b1c1494eb10f44c4619529196e1b

**Comment by oscarssanchez** [comment]
Hey @pabamato did

```
$args_for_multiple_slugs_array_format = [
	'ep_integrate' => true,
	'post_tag' => [
		'slug1',
		'slug2',
	],
];

$posts_query = new \WP_Query( $args_for_multiple_slugs_array_format );
```

work for you?

When I tested this I got a 400 with this error:

```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "[terms] unknown token [END_ARRAY] after [terms.post_tag.slug]",
                "line": 1,
                "col": 312
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[1:312] [bool] failed to parse field [must]",
        "caused_by": {
            "type": "x_content_parse_exception",
            "reason": "[1:312] [bool] failed to parse field [must]",
            "caused_by": {
                "type": "parsing_exception",
                "reason": "[terms] unknown token [END_ARRAY] after [terms.post_tag.slug]",
                "line": 1,
                "col": 312
            }
        }
    },
    "status": 400
}
```

This seems to be because of bad formatting from the plugin. I just want to check if it is something that recently broke. And I could confirm that string of comma separated slugs does not work. Working on a fix towards it.

**Comment by oscarssanchez** [comment]
Once merged https://github.com/10up/ElasticPress/pull/2341 should address the identified problems.
