### ISSUE TITLE
BUG: `is_site_indexable` sync check can prevent indexing in certain multisite contexts

### ISSUE THREAD

**Issue by chrisvanpatten** [10up/ElasticPress#2318]
**Describe the bug**
#1910 introduced some code to check if a site is indexable before allowing the sync manager to be set up for the given Indexable type.

However, the implementation of this code creates an issue in certain multisite contexts, because it makes the check before hooking the appropriate actions/filters for the sync operation.

For instance, imagine a WP-CLI command which is designed to find posts across multiple sites, matching a certain set of criteria, and then publish each post (which should trigger an indexing event for each post):

```php
$site_ids = get_sites( /* some criteria */ );

foreach ( $site_ids as $site_id ) {
    switch_to_blog( $site_id );

    $query = new WP_Query( /* some args */ );

    foreach ( $query->posts as $post ) {
        wp_update_post( [ 'ID' => $post->ID, 'post_status' => 'publish' ] );
    }

    restore_current_blog();
}
```

Now imagine that the root site in your network (site ID 1) has indexing disabled (as it is in our case).

Running that command, you would expect that the posts are updated accordingly and synced to Elasticsearch for the sites which have sync enabled. However, this is not the case: when the request lifecycle starts and Elasticpress is initialized, the `can_index_site()` check [fails](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/SyncManager.php#L44-L46) (because site ID 1 has indexing disabled) which subsequently prevents the hooks from being added for all additional sites, because `switch_to_blog` only changes some context data; it doesn't restart the entire request/reinitialize plugins.

A likely fix for this is to copy the `can_index_site` guard clause into _each hooked function_. This way, the hooks are always hooked, but exit early if the current site has indexing disabled… rather than not being hooked at all if the site originating the request has indexing disabled.

**Steps to Reproduce**
1. Create a process to publish or modify published content (or any other action which would typically trigger a sync operation) for multiple sites in a multisite network
2. Initialize that process from a site with indexing disabled (typically the "root" site, blog ID 1)
3. Observe that the hooks are never added, and thus are never triggered

**Expected behavior**
The sync hooks should be hooked for all sites in a network, and check the indexable status within the hook callback.

**Environment information**
 - WordPress version: 5.8
 - ElasticPress version: latest
 - Elasticsearch version: 7.1.1

**Comment by felipeelia** [comment]
Hi @chrisvanpatten, thanks for opening the issue. We will discuss the problem during our next internal sync and update you with any decisions.

In the meantime, did you already explore a solution like this?
```
add_action(
	'switch_blog',
	function() {
		$sync_manager = \ElasticPress\Indexables::factory()->get( 'post' )->sync_manager;

		if ( ! has_action( 'wp_insert_post', [ $sync_manager, 'action_sync_on_update' ] ) && $sync_manager->can_index_site() ) {
			$sync_manager->setup();
		}
	}
);
```

**Comment by chrisvanpatten** [comment]
@felipeelia We did some exploration around that but haven't implemented it yet (although we will — I just wanted to file this report first).

It's also worth noting that with the guard clause implemented today, you can also end up back with the original problem from #1910 surfacing if you run your WP CLI command with the `--url` flag pointing to a site which has indexing turned on (or any time you originate a request from a site with indexing on, then `switch_to_blog` and run some kind of publish/edit/etc. operation). The site with indexing enabled will be used as the original "context" for the request, which means all the hooks will be hooked for _all_ sites, and EP will try to run indexing operations even if indexing was disabled.

**Comment by felipeelia** [comment]
Yeah, totally true @chrisvanpatten, and in fact something I was already aware of. Probably we should come up with an "unsetup" method calling remove_filter, etc. A little bit of thinking out loud here but having a guard clause in all places would fix the problem indeed but I sense we could go with a simpler solution. Not exactly sure about what that would be yet though :)

Thank you for all the inputs and ideas, by the way!
