### ISSUE TITLE
Emails about errors, even when there were not any errors

### ISSUE THREAD

**Issue by cmmarslender** [10up/ElasticPress#232]
Just reindexed a multisite, and got a bunch of emails (one per site) about indexing errors, even when a site didn't have any actual errors. 

See screenshots:
https://cloudup.com/cuXQ4sX9udk

**Comment by tlovett1** [comment]
@cmmarslender it must have been trying to index posts that don't exist:
https://github.com/10up/ElasticPress/blob/develop/bin/wp-cli.php#L433

How is the database setup? Is there multiple DB servers? Perhaps, they are out of sync.

**Comment by cmmarslender** [comment]
Does have multiple DB servers, but I dont think they were out of sync - Maybe a possibility.

I was reindexing a multisite, and after double checking the emails, the very first email I got (which I ignored, assuming it was empty like the rest....) actually had posts. Maybe there is an issue with doing this network wide, where ```$this->failed_posts``` is not cleared for each site or something like this? Haven't look at the code is too much detail here, so maybe clearing ```$failed_posts``` is happening somewhere, just not seeing it at first glance.

**Comment by tlovett1** [comment]
@EduardMaghakyan can you explain how this fixes the bug?

**Comment by EduardMaghakyan** [comment]
@tlovett1 Well as far as I've understood send_bulk_errors is called for each site and if $this->failed_posts is not empty the email is sent. So if $this->failed_posts is not empty one site email will be sent for that site and for all sites which are indexed afterwards, even if there aren't any failed posts.

**Comment by tlovett1** [comment]
Awesome thanks
