### ISSUE TITLE
BUG: Latest Woocommerce price filter uncompatible with ElasticPress

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#2321]
**Describe the bug**

It looks like the latest Woocommerce price filter widget is not yet compatible with ElasticPress. With the introduction of the widget block area, there's now two widgets, the legacy one and the latest one:

![Screen Shot 2021-08-19 at 17 11 52](https://user-images.githubusercontent.com/31049169/130251572-7d2f02f6-b854-4e3b-ba5a-aae5d7f63675.png)

**Steps to Reproduce**

1. With ElasticPress Woocommerce feature turned on go to widgets
2. Add the two price widgets and save
3. Go to the store page and attempt to filter with both. Only the legacy one is working

**Expected behavior**

ElasticPress should work with the latest one as well.

**Screenshots**

**Environment information**
 - Device:  Mac
 - OS: Catalina
 - Browser and version: 
 - WordPress version: 5.8
 
 - ElasticPress version: develop branch
 - Elasticsearch version: EPIO
 - Where do you host your Elasticsearch server? 
 - What ElasticPress features do you have currently active? Woocommerce, Search, Users, Terms, Autosuggest, Documents
 - Plugins and version: Woocommerce 5.6
 - Theme and version: Storefront <--- latest one
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by felipeelia** [comment]
@oscarssanchez did you manage to make it work even with ElasticPress completely disabled? For me, it fires an AJAX request but does nothing with the product list.

**Comment by mckdemps** [comment]
This is a problem with the woocommerce plugin: https://github.com/woocommerce/woocommerce/issues/30555
