### ISSUE TITLE
Date based post-meta queries

### ISSUE THREAD

**Issue by svandragt** [10up/ElasticPress#2327]
**Is your enhancement related to a problem? Please describe.**
Hello folks! We have a requirement for date-based post-meta queries (imagine listing a schedule for an agenda) and patched the code into EP to support the functionality to sort by datetime post-meta. We'd like to upstream this if you're interested in this use case. Feel free to discuss, if there is interest then I'm happy to submit a PR. 

**Describe the solution you'd like**
The project is not open but imagine the following generalised usecase:

```php
add_action( 'pre_get_posts', 'sort_by_date' );

// generalised usecase
function sort_by_date( WP_Query $query ) : void {
	if ( is_not_an_event_list() ) {
		return;
	}

	$query->set( 'meta_key', 'event_start_datetime' );
	$query->set( 'orderby', 'meta_value_datetime' );
	$query->set( 'order', 'ASC' );
	$query->set( 'ep_integrate', true );
}
```

The patch contents are:
```diff
This patches ElasticPress to support date-based meta queries

@package 10up/elasticpress

--- includes/classes/Indexable/Post/Post.php
+++ includes/classes/Indexable/Post/Post.php
@@ -1634,6 +1634,14 @@ class Post extends Indexable {
 							),
 						);
 					}
+				} elseif ( 'meta_value_datetime' === $orderby_clause ) {
+					if ( ! empty( $args['meta_key'] ) ) {
+						$sort[] = array(
+							'meta.' . $args['meta_key'] . '.datetime' => array(
+								'order' => $order,
+							),
+						);
+					}
 				} else {
 					$sort[] = array(
 						$orderby_clause => array(
```

Credit goes to @shadyvb 

**Describe alternatives you've considered**
We're currently patching the code into EP using [vaimo/composer-patches](https://github.com/vaimo/composer-patches) and would review the functionality after every EP update, if the upstream is not accepted.

**Comment by tomjn** [comment]
@felipeelia can we reopen this? This is still an issue, your previous response isn't actionable, and the parameter that isn't working is a core API `meta_value_datetime`.

In particular what is the purpose of `$query->set( 'orderby', 'meta.event_start_datetime.datetime' );` specifically? Can you shed some understanding/explanation around that?  Would this not cripple any WP site the moment ES is offline, turned off, or overloaded?
