### ISSUE TITLE
Orderby Date with order ASC disables orderby

### ISSUE THREAD

**Issue by jonathan-dejong** [10up/ElasticPress#233]
Hi,

Opening new issue regarding the new orderby date feature. I've implemented the code changes myself to the current stable version since I needed this for a live site. 

I'm querying regular posts from ~8 sites in a multisite network and setting the orderby parameter to "date". When also setting the order parameter to "ASC" the orderby parameter no longer works (with date, others work as expected).

**Comment by EduardMaghakyan** [comment]
Hey @jonathan-dejong ,

Can you please help me to reproduce this issue?
I'm using this query arguments
$args = array(
	's' => 'Apricot',
	'sites'			=> 'all',
	'date_query' => array(
		array(
			'after'     => 'April 1st, 2015',
			'before'    => array(
				'year'  => 2015,
				'month' => 4,
				'day'   => 9,
				'hour'  => 11,
				'minute'  => 25,
				'second'  => 8,
			),
			'inclusive' => false,
		),
	),
	'orderby' => 'date',
	'order' => 'asc'
);

this works on 6 sites in a mulitisite network

**Comment by jonathan-dejong** [comment]
Hi Eduard,

you can see the code I use here: https://github.com/10up/ElasticPress/issues/229

**Comment by EduardMaghakyan** [comment]
Hey @jonathan-dejong , thanks and sorry for such a late response :) have you tried with the latest code from develop branch? I think that's already fixed there.

**Comment by jonathan-dejong** [comment]
Hi,

Nope haven't tried it since then. I don't change the order for my client so the only reason I would try it would be to debug. If you think it's been fixed I'll take your word for it :) 

So you can close this issue if you want to.
