### ISSUE TITLE
BUG: `index.max_shingle_diff` check in `Post::determine_mapping_version()`

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2332]
**Describe the bug**

Inside the [new `Indexable/Post/Post::determine_mapping_version()`](https://github.com/10up/ElasticPress/blob/3.6.2/includes/classes/Indexable/Post/Post.php#L300) method the plugin checks for `$mapping[ $index ]['settings']['index.max_shingle_diff']`, as set [in the mapping](https://github.com/10up/ElasticPress/blob/3.6.2/includes/mappings/post/7-0.php#L62). In fact, Elasticsearch returns the mapping as a perfect array, so we should check `$mapping[ $index ]['settings']['index']['max_shingle_diff']` actually.

**Additional context**
Props to @pschoffer

**Comment by joshbenham09** [comment]
I will give a look at this as soon as I can.

**Comment by felipeelia** [comment]
We've discovered that:
1. As our mapping for ES 7+ doesn't have a `$mapping[ $index ]['mappings']['post']` entry, everything using it will be ES 6-.
2. In fact, that if should be `if ( isset( $mapping[ $index ]['settings']['index']['max_shingle_diff'] ) ) {`
