### ISSUE TITLE
Search field in facet doesn't do anything

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2339]
Ever since the latest update (v3.6.2 ), I noticed that the search field located in each facet doesn't do anything. It doesn't filter down the option in the facet, nor are there any errors in console when typing in it.

Yes, I cleared my cache and re-indexed after updating.

**Comment by oscarssanchez** [comment]
Hi @shmaltz ,

I couldn't reproduce. Do you have custom code added vía a filter like `ep_facet_search_widget` ?

**Comment by shmaltz** [comment]
@oscarssanchez I am not using `ep_facet_search_widget` however I am using the following snippets: https://gist.github.com/shmaltz/5bc60cdf4fff48c33f17262b70073214

**Comment by felipeelia** [comment]
@shmaltz are/were you seeing any JS errors in console by any chance?

**Comment by shmaltz** [comment]
@felipeelia There are no errors in console, and no requests are made in the network tab.

We are using autosuggest btw.

I tried in chrome and firefox.

**Comment by felipeelia** [comment]
Thanks @shmaltz. Is this publicly available somewhere we could give a look? The facet widget search does not trigger an ajax request, it simply shows/hides the terms already in the dom.

**Comment by shmaltz** [comment]
@felipeelia Here you go: https://dlpx.ca/6mxfw

**Comment by felipeelia** [comment]
Got it, @shmaltz. ElasticPress will need one of [these two classes](https://github.com/10up/ElasticPress/blob/develop/assets/js/facets.js#L31) (`.widget_ep-facet` or `.wp-block-elasticpress-facet`) added to the widget wrapper, so it detects the presence of the input and know which elements should be filtered. Adding that should make the JS to trigger in the correct places.

**Comment by shmaltz** [comment]
Thank you @felipeelia I will check that out!

**Comment by shmaltz** [comment]
Adding the class fixed the issue. Thanks @felipeelia !
