### ISSUE TITLE
BUG: cannot specify port 9200 for self-hosted elastic search

### ISSUE THREAD

**Issue by bsabalaskey** [10up/ElasticPress#2354]
**Describe the bug**
There is no way to specify port 9200 for connecting to a self-hosted elasticsearch instance.

**Steps to Reproduce**
The settings page for self hosted always uses port 80. Using a specified port like http://LOCAL_IP:9200 fails. The system always reports port 80 failed to connect. That part is accurate as the default port for elasticsearch is 9200, there is nothing running on port 80 on the searchserver.

1. Enter elasticsearch Host URL of http://local_ip:9200
2. Click on Save Changes
3. Fails to connect as the error message always complains about port 80 not being reachable

**Expected behavior**
Expect to be able to specify the TCP port, i.e. 9200 using the colog syntax.
The default should be 9200 for self-hosted.

**Screenshots**
none.

**Environment information**
 - Device: any
 - OS: Window 10 pro
 - Browser and version: Chrome latest
 - WordPress version: 5.8.1
 - Elasticsearch version: 7.14 / 7.X
 - Where do you host your Elasticsearch server? locally on the same LAN as a dev server (IP 10.*.*.*)
 - What ElasticPress features do you have currently active? None yet, cannot get it to start
 - Plugins and version: 3.6.2
 - Theme and version: custom theme
 - <details><summary>Site Health Info:</summary>
   PHP 7.4.23
  16G RAM
   </details>

**Additional context**
Don't tell me to run on port 80.

**Comment by felipeelia** [comment]
Hey @bsabalaskey, thanks for opening the issue. That `http://LOCAL_IP:9200` really should work, as we don't do any changes in the Elasticsearch server address. Do you mind sharing a screenshot of how that error message looks like? Thanks!

**Comment by bsabalaskey** [comment]
The error message said port 80 was not connecting. That is incorrect. The elasticsearch instance on the other server (on the LAN) was not set, per the defaults from install, to allow connectivity from other server, hence it would show up locally in the elastic server with netstat, but not connect to the WordPress instance on that other server. Once elasticsearch was changed to allow outside connections on port 9200, then the http://ELASTIC_IP_ON_LAN:9200 did work.

Please update your error message to show the proper port when it cannot connect.

Also, that WordPress settings page got "stuck" such that it was all disabled. I had to refresh the page so as to re-enter the connectivity data from port 80 to port 9200.

**Comment by felipeelia** [comment]
@bsabalaskey, ElasticPress does not have a message containing "80" in it, hence why I asked you to share a screenshot with the error. The exact message and how it looks like would be important for us to track down the origin of it.

I'm glad to see you have everything figured out. I'll go ahead and close the issue but if you can get that screenshot and share it with us, it would be great. Thanks!

**Comment by scottbuscemi** [comment]
I experienced this same error. Seems like it'd be ideal to have a separate field for "port" to make it clear where to enter in the port number for self-installs.

Without a port being entered in the URL, the default http port 80 is attempted.


<img width="1079" alt="Screenshot 2023-07-30 at 11 31 14 AM" src="https://github.com/10up/ElasticPress/assets/4336848/27e6e163-5d75-4bcf-8bb3-2293b57c8699">
