### ISSUE TITLE
BUG: Anonymous/logged out comments are not indexed

### ISSUE THREAD

**Issue by tomjn** [10up/ElasticPress#2356]
**Describe the bug**

When `wp_insert_comment` is called, a function is fired which maybe indexes the comment, but it has a capability check. If the user does not have the ability to edit comments, the function returns.

This is great for updating comments, but the same function is used for comment creation, breaking comments left by logged out users.

https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Comment/SyncManager.php#L56-L66

The capability check in question: https://github.com/10up/ElasticPress/commit/9267d247ee34d030c5e2eb9beb7f2fc47e6286a3

**Steps to Reproduce**

1. Leave a comment as a logged out user on a post

**Expected behavior**

The  guest comment should be indexed, it is not.

**Environment information**
 - Device: Macbook
 - OS: MacOS 11
 - Browser and version: Chrome 92 ( and others )
 - WordPress version: 5.8
 - ElasticPress version: `"10up/elasticpress": "^3.6"`
 - Elasticsearch version: 7.9.1
 - Where do you host your Elasticsearch server? 
 - What ElasticPress features do you have currently active? 

**Additional context**

We have a custom comment type for reactions, and found recently after updates that anonymous/guest users could no longer  use this feature. On closer inspection it turns out it was not being indexed in ES. We know this because Elasticpress is disabled for queries when `is_admin` is true andd WP Admin reported the correct data, the frontend/REST API which has it enabled however did not update.

**Comment by mckdemps** [comment]
@tomjn Thanks for submitting this, we're going to get it slotted in for a future release.

**Comment by tomjn** [comment]
@mckdemps awesome, I created a PR but I'm not 100% sure of its efficacy, it may be a good starting point rather than a full solution

**Comment by tomjn** [comment]
I also think the capability checkss could be problematic, e.g. if a comment is edited because a plugin modified it automatically, even though the user does not have that capability, in that situation Elasticpress would not index the modification and it would desync
