### ISSUE TITLE
QUESTION: Index scheduled post

### ISSUE THREAD

**Issue by cgomezed** [10up/ElasticPress#2361]
Hi, 
Can I force to index a scheduled post? I need to get these posts in admin searches to compose a future page, but EP doesn't index them until post is published.

Regards,
César.

**Comment by felipeelia** [comment]
Hi @cgomezed! If you turn on the "Protected Content" feature all posts will be indexed (including drafts and schedules, for example) and displayed in admin searches.
I'll go ahead and close the issue but if you have a specific use case where that is not working please let us know, okay? Thanks

**Comment by cgomezed** [comment]
Thanks @felipeelia, the problem is we have around 700000 posts and enabling this feature fires a reindex. Can I index only a set of post?

Best Regards.
