### ISSUE TITLE
negative site parameter?

### ISSUE THREAD

**Issue by natostanco** [10up/ElasticPress#237]
Is is possible to use a negative value with the site parameter as to specify search all blogs minus this one?

**Comment by AaronHolbrook** [comment]
That is not currently how the system works.

You could however, pass an array of all blogs excluding the current one and it would do what you're looking to achieve.

**Comment by natostanco** [comment]
Yes but assuming the array is very large, pretty much the entire multisite and you want to exclude just a handful of blogs, wouldn't that be a little too much for a simple exclusion?

**Comment by natostanco** [comment]
So from what I understand in order to only exclude some sites, you would have to perform the search on the global index, and filter out the specified site_ids
