### ISSUE TITLE
BUG: Woo Commmerce Product Search broken

### ISSUE THREAD

**Issue by dianfishekqi** [10up/ElasticPress#2371]
Hello all,

Woocommerce blocks have implemented [their own search functionality ](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5f34c86072936ac908a93c49881775d21df69a6a/src/StoreApi/Utilities/ProductQuery.php#L31) which elasticpress ignores leading to incorrect results (On the handpicked products block you can't access products if they're not on the first 100 products), changing `search` to `s` fixes the issue, maybe we should add a case to interpret search as s in the woocommerce feature, or disable ep_integration on these queries.

**Comment by felipeelia** [comment]
Hi @dianfishekqi. I made a few tests locally but I'd like to understand better what is your ask here. It seems ElasticPress is NOT used, right? Are you wanting to _enable_ the integration for that query? Thanks!

**Comment by dianfishekqi** [comment]
@felipeelia  ElasticPress is enabled by default unless you set `ep_integrate` to `false`, elastic press does not handle the search param as it is not something standard, we have to options to disable `ep_integrate` for that query or alias `search` to `s`

**Comment by felipeelia** [comment]
Hi @dianfishekqi. ElasticPress would not be enabled by default for queries that don't have `s` nor `ep_integrate` set. Can you please give us a step-by-step of how we can reproduce it and how you are debugging it? Also, which features do you have enabled? Thanks

**Comment by oscarssanchez** [comment]
Hi @dianfishekqi 

A screencast would be great! I've tried to reproduce this by generating products via WPCLI but I still don't understand the scenario where you would not get the product you are looking for. 

Thanks!

**Comment by dianfishekqi** [comment]
Hello @oscarssanchez, here is a screencast of the issue; as you can see after changing the search param of [wc-query](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5f34c86072936ac908a93c49881775d21df69a6a/src/StoreApi/Utilities/ProductQuery.php#L31) from `search` to `s` it returns more products, the solution might be just disabling the ep_integration on these searches, or altogether disable ep_integrate on all queries which include unknown keys (compare against a whitelist of wp_query params).



https://user-images.githubusercontent.com/4225509/150213052-dfed666b-b349-4934-bd79-e06b439ba3e7.mp4

**Comment by oscarssanchez** [comment]
Thanks @dianfishekqi ! 

I could reproduce it now. I'll add the bug label to this.

**Comment by dianfishekqi** [comment]
Hello @felipeelia ,@mckdemps,
I would be happy to submit a PR for this bug!
Possible solutions I can think of are:
1. Support the `search` param if in WooCommerce queries by aliasing it to `s`
2. Disable `ep_integration` on WP_ADMIN queries for `products`

Thanks,

**Comment by felipeelia** [comment]
Hey @dianfishekqi, that is actually excellent timing as I am giving a look into this problem *at this exact moment* haha. I'll get back to you with my findings and our preferred solution. Thanks!

**Comment by felipeelia** [comment]
Hi @dianfishekqi, I've just created #2620 fixing the issue. Would you have an environment where you could test that? As it is now using EP 4.0 code, you'll need to `npm install && npm run build` to have CSS and JS properly working. Thanks

**Comment by felipeelia** [comment]
Closed by #2620
