### ISSUE TITLE
How to get data via WP_Query & Ajax? 

### ISSUE THREAD

**Issue by marcinkrzeminski** [10up/ElasticPress#2376]
**Describe your question**

Hi,

I'm having a hard time to get this working. I have created a custom REST endpoint since I've read your suggestion somewhere else that this is the recommended way instead of the `wp-ajax.php`. Here's my snippet that I'm testing out at the moment. 

```php
add_action( 'rest_api_init', function () {
  register_rest_route( 'ep/v1', '/pagination/', array(
  'methods'  => 'POST',
  'callback' => 'handle_request',
  'args'     => [
	  'post_type' => [
		  'required' => true,
	  ],
	  'paged'     => [
		  'required' => true,
	  ],
	  'nonce'     => [
		  'required' => true,
	  ]
  ],
  ) );
} );

handle_request( $request ) {
  $post_type = $request->get_param( 'post_type' );
  $paged     = $request->get_param( 'paged' );
  $nonce     = $request->get_param( 'nonce' );
  
  $nonce_name = 'pagination-' . $post_type;
  if ( ! wp_verify_nonce( $nonce, $nonce_name ) ) {
	  return new \WP_REST_Response( __( 'Pagination nonce did not verify', KS_DOMAIN ), 400 );
  }
  
  $args = array(
	  'ep_integrate' => true,
	  'post_type'    => $post_type === 'all' ? 'any' : $post_type,
  );
  
  print_r( $args );
  $query = new \WP_Query( $args );
  print_r( $query );
}
```

Posts are freshly indexed. I'm getting `0` when checking for `$query->post_count`

Any idea what am I doing wrong here?

**Comment by felipeelia** [comment]
Hi @marcinkrzeminski,

I've tested your code and it worked fine. What do you get in `$query->elasticsearch_success`? Also, can you please try to reindex using the WP-CLI command and checking if any error is returned? The command would be `wp elasticpress index --setup --show-errors`. Thanks!
