### ISSUE TITLE
Custom search settings question

### ISSUE THREAD

**Issue by marcinkrzeminski** [10up/ElasticPress#2382]
Hi,

I'd like to ask if something like this is possible. Here's the scenario

1. I have industry and countries as a CPT that is related with another custom post types via ACF. 
2. On top of that I have some shared taxonomies (default as well as custom). 

When I search for a country, say Germany and a post_format term like Podcast, I get Germany as a third result in a row. I'd expect to have this in the first place. For both all or any in facet match type, the result is the same. Should I reindex once the match type is changed?

**Comment by felipeelia** [comment]
Hi @marcinkrzeminski, did you already try to change the values in the Weighting Dashboard (WP Dashboard -> ElasticPress -> Search Fields & Weighting)? Increasing the value of Title under your CPT attributes and saving should bring matching results to a better position in the list.

**Comment by marcinkrzeminski** [comment]
@felipeelia after some debugging I have discovered that there was an orderby in the query which was causing the problem.
