### ISSUE TITLE
BUG: PDF Attachment remain indexed after parent post status no longer published

### ISSUE THREAD

**Issue by NTmurfg25** [10up/ElasticPress#2383]
If a post has a PDF Attachment and this post is published then indexing occurs fine. When this post status is changed from published the attached  PDF remains indexed and searchable. Parent post is not searchable or indexed. We are using Ingest Attachment plugin

**Steps to Reproduce**

1. Create post with PDF attachment
2. Publish post
3. Change post status to draft
4. Use search on website front end with text contained in pdf

**Expected behavior**

PDF Attached to unpublished post should not be in search results or searchable from front end.

**Environment information**
 
 - WordPress version: 5.5.3 

As a work around I have used the post_updated hook. Then I use  this to index.

`$indexable = \ElasticPress\Indexables::factory()->get( 'post' );

$indexable->delete( $postid, false );
$indexable->put_mapping();`

At this point the index gets removed when the post status is changed from published.

I want to add the PDF document in after the post has been republished. I have tried 

` $indexable = \ElasticPress\Indexables::factory()->get( 'post' );
     
       $indexable->index( $postid, true );
       $indexable->put_mapping();
`
with no luck. 

I also tried the bulk index with the single `
$Indexables::factory()->get( 'post' )->bulk_index($postid);
`

I basically want to know how to add an index for a pdf attachment to Elastic search using elastic press

**Comment by mckdemps** [comment]
@NTmurfg25 ElasticPress actually matches WordPress' behavior here. If a post with an attachment is deleted in WordPress, the attachment still exists and is publicly available.
