### ISSUE TITLE
BUG: Some keywords aren't showing results for pages

### ISSUE THREAD

**Issue by JohnSplendid** [10up/ElasticPress#2399]
**Describe the bug**

Some keywords aren't showing results for pages. E.g the word Betreuung (this is a German site, so the language is that.)

I know this word is in the content, and ElasticPress will show results for other post types. Just not pages

**Steps to Reproduce**

1. Go to 'https://www.splendid-internet.de/'
2. Click on 'the search icon in the header'
3. Type in  'Betreuung'
4. You will see results, but none of them are for pages

**Expected behavior**

When I type the word Betreuung, results should appear for pages, not just blog and other post types.

**Screenshots**

![Screenshot 2021-10-11 165428](https://user-images.githubusercontent.com/92320498/136812317-ba52d0fd-c395-479c-935e-f3d0ad797966.png)

![Screenshot 2021-10-11 170220](https://user-images.githubusercontent.com/92320498/136812810-63fa348e-5b7f-4098-b3d4-e68d7ceaa500.png)

**Environment information**

 - Device: Lenovo ThinkPad
 - OS: Windows 10
 - Browser and version:  Chrome 94.0.4606.81
 - WordPress version: 5.8
 - ElasticPress version: 3.6.3
 - Elasticsearch version: 5.6.16
 - Where do you host your Elasticsearch server? Third Party server
 - What ElasticPress features do you have currently active? Post Search, Autosuggest
 - Theme and version: _splendid_s 1.0.0 (underscores.me)

Thanks

John

**Comment by felipeelia** [comment]
Hey @JohnSplendid,

It looks like you are using an ACF block and ES is not indexing the text as content but rather as a comment. Can you please follow what we suggested in this article and let us know if that works? https://elasticpress.zendesk.com/hc/en-us/articles/4402857301389 Thanks!

**Comment by JohnSplendid** [comment]
Hi @felipeelia

Thanks for the response. I'll check out your solution.

**Comment by JohnSplendid** [comment]
Hi @felipeelia 

Sorry for the late reply. Just wanted to report that your solution fixed our problem, so this issue can be marked as solved.

Thanks for the help.

John

**Comment by felipeelia** [comment]
Awesome, @JohnSplendid, thanks for taking the time to get back to us!
