### ISSUE TITLE
QUESTION: Slow taxonomy archive

### ISSUE THREAD

**Issue by antqook** [10up/ElasticPress#2413]
My site has Woocommerce and few custom taxonomies. Custom taxonomies takes a long time to load. Though Debug bar indicates that Elasticpress is working and is fast, but still the page load takes long.
If I turn Elasticpress the page loading time is same. It takes 13-16 seconds to load the taxonomy archive page. Debug bar says Elasticsearch query took 180ms and other WP queries 19,4ms only.
The taxonomy has 60k terms and few thousand posts/products attached but that shouldn't be the cause for slowness, especially with Elasticsearch in use.

Query args: https://pastebin.com/BZrtaewQ
Query body: https://pastebin.com/sYkqPMMH
Query result: https://pastebin.com/fM7bMsbc

We have New Relic running on the site and it shows very slow WebTransaction /Tax -cars.
<img width="851" alt="Screenshot 2021-10-15 at 9 23 02" src="https://user-images.githubusercontent.com/92582405/137482705-cac94583-9730-4225-a626-34ab501af8c1.png">

Any idea what could be causing this?

**Comment by felipeelia** [comment]
Hi @antqook! ElasticPress won't pass all the queries through Elasticsearch as it is not guaranteed it will be faster than MySQL (for example, if MySQL is in the same server and ES is an external call, latency will be an important factor.)

In New Relic, did you identify that SQL query as the problematic one? You could use the `pre_get_terms` action to add `ep_integrate` as `true` to make it run with ES but the best approach would be tuning up your MySQL.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!
