### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by CarletonTorpin** [10up/ElasticPress#2427]
**Describe the bug**

When search results are displayed from the ElasticPress search box, the results display in a dropdown box which is cut-off by another section of my website. 

Same issue with menu header search box, but the results dropdown box is rendered behind everything, so it's totally inaccessible. 

**Steps to Reproduce**

Visit the homepage at https://bildirstaging.wpengine.com.
Scroll down to the search box located below the slider.
Type "pool cue" into the search box. 
See the results and scroll down to see how they display behind some elements, but not others. 

Search for "pool cue" in the top header menu search box. 
See that the results dropdown box is there, but it is located behind everything else on the website. 

**Expected behavior**
When users type a term into the search box, they get a dropdown menu that covers up the content beneath it, instead of behind it. 

**Screenshots**
Here is a screen shot of me typing "pool" into the search box beneath the slider, showing the results are displayed behind other parts of the website, instead of on top of them: https://share.getcloudapp.com/L1uegmy9

**Environment information**
 - Device: M1 iMac 
 - OS: MacOS 11.6
 - Browser and version: Safari Version 15.0
 - WordPress version:  5.8.1 

 - Where do you host your Elasticsearch server? https://wpe-bildirstaging.us-east-2.wpe.clients.hosted-elasticpress.io
 - What ElasticPress features do you have currently active? Post Search, Autosuggest, WooCommerce, Related Posts, Facets
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   `
### wp-core ###

version: 5.8.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 7
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /nas/content/live/bildirstaging
wordpress_size: loading...
uploads_path: /nas/content/live/bildirstaging/wp-content/uploads
uploads_size: loading...
themes_path: /nas/content/live/bildirstaging/wp-content/themes
themes_size: loading...
plugins_path: /nas/content/live/bildirstaging/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Thrive Theme Builder (thrive-theme)
version: 3.1.3
author: Thrive Themes
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, menus, html5, customize-selective-refresh-widgets, post-formats, tve-wc-mini-cart, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /nas/content/live/bildirstaging/wp-content/themes/thrive-theme
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (6) ###

Force Strong Passwords - WPE Edition: version: 1.6.4, author: Jason Cosper
WPE ElasticPress Autosuggest Logger: version: 1.0.0, author: WP Engine
WP Engine Cache Plugin: version: 1.0.1, author: WP Engine
WP Engine Seamless Login Plugin: version: 1.5.5, author: WP Engine
WP Engine Security Auditor: version: 1.0.10, author: wpengine
WP Engine System: version: 5.0.0, author: WP Engine

### wp-plugins-active (28) ###

Autoptimize: version: 2.9.2, author: Frank Goossens (futtta), Auto-updates disabled
Caxton: version: 1.27.0, author: PootlePress, Auto-updates disabled
Duplicate Page: version: 4.4.5, author: mndpsingh287, Auto-updates disabled
ElasticPress: version: 3.6.4, author: 10up, Auto-updates disabled
Envato Market: version: 2.0.6, author: Envato, Auto-updates disabled
Product Description on Shop Page: version: 1.0.1, author: KoalaApps, Auto-updates disabled
Product Slider Pro for WooCommerce: version: 2.7.1, author: ShapedPlugin, Auto-updates disabled
Rank Math SEO: version: 1.0.74, author: Rank Math, Auto-updates disabled
Rank Math SEO PRO: version: 2.18.0, author: Rank Math, Auto-updates disabled
ShortPixel Image Optimizer: version: 4.22.6, author: ShortPixel, Auto-updates disabled
Slider Revolution: version: 6.5.9, author: ThemePunch, Auto-updates disabled
Smart Slider 3 Pro: version: 3.5.1.1, author: Nextend, Auto-updates disabled
Storefront Pro Blocks: version: 3.2.0, author: Pootlepress, Auto-updates disabled
Thrive Architect: version: 3.3.3, author: <a href="http://www.thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
Thrive Automator: version: 0.4, author: <a href="https://thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
Thrive Comments: version: 2.1, author: <a href="https://thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
Thrive Product Manager: version: 1.2.7, author: Thrive Themes, Auto-updates disabled
Variation Swatches for WooCommerce: version: 1.1.19, author: Emran Ahmed, Auto-updates disabled
Variation Swatches for WooCommerce - Pro: version: 1.1.18, author: Emran Ahmed, Auto-updates disabled
WooCommerce: version: 5.8.0, author: Automattic, Auto-updates disabled
WooCommerce Blocks: version: 6.1.0, author: Automattic, Auto-updates disabled
WooCommerce Product Reviews Pro: version: 1.15.4, author: SkyVerge, Auto-updates disabled
WooCommerce Tab Manager: version: 1.12.2, author: SkyVerge, Auto-updates disabled
WooCommerce TM Extra Checkout Options: version: 1.7.6, author: themeComplete, Auto-updates disabled
WooCommerce TM Extra Product Options: version: 5.1, author: themeComplete, Auto-updates disabled
WP Engine Smart Plugin Manager: version: 5.6.3, author: WP Engine, Auto-updates disabled
YITH Infinite Scrolling Premium: version: 1.5.2, author: YITH, Auto-updates disabled
YITH WooCommerce Ajax Search Premium: version: 1.10.0, author: YITH, Auto-updates disabled

### wp-plugins-inactive (19) ###

Additional Variation Images Gallery for WooCommerce: version: 1.2.8, author: Emran Ahmed, Auto-updates disabled
Additional Variation Images Gallery for WooCommerce - Pro: version: 1.2.7, author: Emran Ahmed, Auto-updates disabled
Advanced Product Fields Extended for WooCommerce: version: 1.7.6, author: StudioWombat, Auto-updates disabled
Akismet Anti-Spam: version: 4.2.1, author: Automattic, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Enable Media Replace: version: 3.6.0, author: ShortPixel, Auto-updates disabled
Extendons: WooCommerce & Light Speed POS Integration: version: 1.0.0, author: Extendons, Auto-updates disabled
Genesis Blocks Pro: version: 1.6.0, author: WP Engine, Auto-updates disabled
Gravity Forms: version: 2.5.5.1, author: Gravity Forms, Auto-updates disabled
Gravity Forms Styles Pro: version: 3.0, author: Warp Lord, Auto-updates disabled
Product Slider for WooCommerce: version: 2.4.0, author: ShapedPlugin, Auto-updates disabled
Re-add text underline and justify: version: 0.3, author: Brice Capobianco, Auto-updates disabled
Slider Revolution WP Gallery Add-On: version: 2.0.3, author: ThemePunch, Auto-updates disabled
WooCommerce Affirm Gateway: version: 1.1.10, author: WooCommerce, Auto-updates disabled
WooCommerce Dynamic Pricing & Discounts: version: 2.4.3, author: RightPress, Auto-updates disabled
WooCommerce Lead Time: version: 1.5.3, author: Barn2 Plugins, Auto-updates disabled
WP AutoTerms: version: 2.4.8, author: WP AutoTerms, Auto-updates disabled
YITH Infinite Scrolling: version: 1.5.3, author: YITH, Auto-updates disabled
YITH WooCommerce Request A Quote Premium: version: 3.1.3, author: YITH, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.4.4
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 137 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-1049-gcp x86_64
httpd_software: Apache
php_version: 7.4.24 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_filesize: 50M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.35-38-log
client_version: mysqlnd 7.4.24

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/bildirstaging/wp-content
WP_PLUGIN_DIR: /nas/content/live/bildirstaging/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_unicode_ci

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### epio_autosuggest ###

`
   </details>

**Additional context**

**Comment by felipeelia** [comment]
Hi @CarletonTorpin, one of those issues is happening because your theme is applying the CSS "overflow" rule to the search forms. You can fix that by adding something like this to a child theme or in Customizer's Additional CSS:

```
.thrv-search-form, .thrv-search-form form {
    overflow: visible;
}
```
I could not reproduce the other one (autosuggest being displayed behind other elements) but that seems to be related to the z-index property.

As that is something related to your theme specifically, if you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation.
