### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by christianostrem** [10up/ElasticPress#2429]
**Describe the bug**

I found something that i think is a bug in the result printed by the_excerpt() in wp.

If you look at the result i have pasted her you can see that there is no space between the tag, header and the text.
I have set the tag and the header in {} so that you can see what is the tag and header.

**The the result:**

{Prosjekter og satsinger}{Utvalgte kulturlandskap i jordbruket}Utvalgte kulturlandskap i jordbruket (UKL) er en tverrfaglig, felles satsing mellom Landbruks- og matdepartementet og Klima- og miljødepartementet. Så langt er 46 områder fra hele landet valgt ut. Kart finner...

**Original result without {}:**
Prosjekter og satsingerUtvalgte kulturlandskap i jordbruketUtvalgte kulturlandskap i jordbruket (UKL) er en tverrfaglig, felles satsing mellom Landbruks- og matdepartementet og Klima- og miljødepartementet. Så langt er 46 områder fra hele landet valgt ut. Kart finner...

**A better result would have been a text with spaces in between the tag, header and text.**
Like this:
Prosjekter og satsinger Utvalgte kulturlandskap i jordbruket Utvalgte kulturlandskap i jordbruket (UKL) er en tverrfaglig, felles satsing mellom Landbruks- og matdepartementet og Klima- og miljødepartementet. Så langt er 46 områder fra hele landet valgt ut. Kart finner...

**Maby even with a punctation like this:**
Prosjekter og satsinger. Utvalgte kulturlandskap i jordbruket. Utvalgte kulturlandskap i jordbruket (UKL) er en tverrfaglig, felles satsing mellom Landbruks- og matdepartementet og Klima- og miljødepartementet. Så langt er 46 områder fra hele landet valgt ut. Kart finner...

**Steps to Reproduce**
You can se the result here. We are not doing anything special with the plugin.
https://www.riksantikvaren.no/?s=Utvalgte+kulturlandskap

**Expected behavior**
It would be nice if the tag, header was seperated from the text by spacing and and maby punctaion. 

**Screenshots**

![Sok_tekst](https://user-images.githubusercontent.com/1935128/139210578-b4c135a9-8b22-4619-a27a-fe8cbd60d048.png)

**Environment information**
 - WordPress version: 5.8.1
 - ElasticPress version: 3.6.4
 - Where do you host your Elasticsearch server? localhost

**Comment by felipeelia** [comment]
Hi @christianostrem, does it work differently if you deactivate ElasticPress? Also, can you please share the part of your theme responsible for outputting those elements? Thanks.
