### ISSUE TITLE
Support https connections

### ISSUE THREAD

**Issue by zamoose** [10up/ElasticPress#243]
Not sure what needs to happen to support this, but specifying an https URL for the `EP_HOST` bombs out, even though the Elasticsearch instance is up.

**Comment by zamoose** [comment]
Specifically, `wp elasticpress index` reports

`
Error: Unable to reach Elasticsearch Server! Check that service is running.
`

**Comment by zamoose** [comment]
Investigating further:
@tlovett1 hopped on to the test box and re-ran the index command using root and --allow-root and it completed. Trying various combinations of https/http, with port, without port, if `EP_HOST` had :443 specified, it would bomb if run as `sudo -u apache`, but would run as root. 

I'm confused. This may not actually be an issue, or it may well be.

**Comment by zamoose** [comment]
If I can't reproduce, I'll close this out as an aggravating Heisenbug. Suspecting system packages/Apache* is at fault.

*When in doubt, always blame Apache.

**Comment by tlovett1** [comment]
Blaming Apache works for me.

**Comment by zamoose** [comment]
Closing as invalid.
