### ISSUE TITLE
400 Bad Request: No mapping found for...

### ISSUE THREAD

**Issue by chrismask** [10up/ElasticPress#2434]
![Screenshot_447](https://user-images.githubusercontent.com/79385435/139913189-376212b6-1192-42f8-a5a4-d2779a28262e.jpg)
![Screenshot_446](https://user-images.githubusercontent.com/79385435/139913196-3c8608d5-f483-4901-b942-c48f1834b35f.jpg)
Hello, i have this weird issue when using elasticpress on some search queries and the result is database taking 4s to find results for simple words so I have to fix. I contacted my host support and told me this is mapping issue, as seen on screenshots too but i have tried all different settings for syncing posts etc and there is no fix.
I don't know if this is a forum just for stating bugs and fixes, but this might be a bug, because on the versions before, this wasn't a problem. Can you help?

**Comment by felipeelia** [comment]
Hi @chrismask!

It seems you are trying to sort by a meta field called `_listing_views_count` but as that starts with a `_`, it's automatically excluded.

You can add it using the `ep_prepare_meta_allowed_protected_keys` filter: http://10up.github.io/ElasticPress/ep_prepare_meta_allowed_protected_keys.html

This code is not tested but should be enough to achieve what you need:
```
function ep_2434_add_custom_meta( $keys ) {
	$keys[] = '_listing_views_count';
	return $keys;
}
add_filter( 'ep_prepare_meta_allowed_protected_keys', 'ep_2434_add_custom_meta' );
```

Thanks!
