### ISSUE TITLE
Is it possible to search and orderby?

### ISSUE THREAD

**Issue by erezgreenberg** [10up/ElasticPress#2437]
Is it possible to search **AND** orderby? For some reason when adding any search term the orderby doesn't work. If I remove the search term then orderby works.

Here is a simplistic example:

```
    $the_query = new WP_Query(
        array(
            'ep_integrate' => true,
            'post_type'      => 'product',
            'post_status'    => 'publish',
            'posts_per_page' => 12,
            'paged' => 1, 
            's' => 'foo', // if I remove this then orderby works 100%, otherwise ordering is random
            'order' => 'title',
            'orderby' => 'DESC',
        )
    );
```

**Comment by felipeelia** [comment]
Hi @erezgreenberg,

That should work out of the box. I don't know if that is a typo just in your example but the `order` and `orderby` parameters should look like this:

```
'order'   => 'DESC',
'orderby' => 'title',
```

If even changing that it doesn't work, please install the Debug Bar and Debug Bar ElasticPress plugins and share with us the query and its results so we can help you further. Thanks

**Comment by erezgreenberg** [comment]
@felipeelia 

Sorry that was a typo, I am indeed doing

```
'order'   => 'DESC',
'orderby' => 'title',
```

Below are 2 files of the debug info from these 2 queries respectively:

   ```
// query 1 with keyword - the orderby does not work
 $wp_query_results = new WP_Query(
        array(
            'ep_integrate' => true,
            'post_type'      => 'product',
            'post_status'    => 'publish',
            's' => 'product',
            'orderby' => 'title',
            'order' => 'DESC',
        )
    );

// query 2 without keyword - the orderby works
 $wp_query_results = new WP_Query(
        array(
            'ep_integrate' => true,
            'post_type'      => 'product',
            'post_status'    => 'publish',
            'orderby' => 'title',
            'order' => 'DESC',
        )
    );
```

[debug-info-with-search-keyword.txt](https://github.com/10up/ElasticPress/files/7489951/debug-info-with-search-keyword.txt)
[debug-info-without-search-keyword.txt](https://github.com/10up/ElasticPress/files/7489952/debug-info-without-search-keyword.txt)

**Comment by felipeelia** [comment]
I could not reproduce the error in a fresh install @erezgreenberg. In fact, it seems something is modifying the WP_Query before EP uses it, as I can see orderby set as false (`["orderby"]=> bool(false)`). It may be a good idea to install the [Health Check](https://wordpress.org/plugins/health-check/) plugin, enable its Troubleshooting mode and disable all plugins except WooCommerce and ElasticPress, switch to a default theme, and check if the behavior changes.

Can you please do that and let us know the results? Thanks.

**Comment by erezgreenberg** [comment]
Hi @felipeelia thanks, but I find it strange that another plugin would interfere with this. Also it works without the `s` parameter. So if you are correct then another plugin is somehow interfering when there is an `s` parameter

Regardless, I will try what you suggest and feed back

Thanks :-)
