### ISSUE TITLE
BUG: get_term_tree() can lead to an infinite loop

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2449]
**Describe the bug**

It seems [Utils/get_term_tree()](https://github.com/10up/ElasticPress/blob/develop/includes/utils.php#L345) can lead to an infinite loop in certain scenarios. As it receives a list of terms and organizes it in a hierarchical way, iterating over the list until all child terms are appended to their parents, if a parent category is missing in the initial list, the function will loop through the list indefinitely.

**Steps to Reproduce**

This still needs some tests but that could happen in a heavy cached site where a parent category is deleted.

**Expected behavior**

The function should not go into an infinite loop.

**Comment by ragboy** [comment]
We are seeing this issue, with a site of 500k products. can't use facets.
