### ISSUE TITLE
BUG: Header Menus Activating Behind Search-Results Dropdown

### ISSUE THREAD

**Issue by CarletonTorpin** [10up/ElasticPress#2451]
**Describe the bug**

ElasticPress search results display in a dropdown box, and when visitors hover over certain parts of that Search-Results dropdown box, it also activates a Navigation-Menu Dropdown behind the Navigation-Menu dropdown box. 

**Steps to Reproduce**

Visit the homepage at https://billiardsstage.wpengine.com
Type "predator cue" into the search box in the header menu.
See the results, and hover your cursor over some of the results that overlap the blue header menu.
Now there are two separate dropdown which coexist on top of each other, which makes both of them hard to use.

**Expected behavior**

When the mouse cursor moves over the Search-Results dropdown, I would like the Search-Results dropdown to remain on screen (this is currently how it is working) and I would like the Navigation-Menu dropdown to activate only when there is no Search-Results dropdown box already being displayed (this is the aspect that I would like to change)

**Screenshots**
Here is a screen shot of me typing "predator cue" into the search box beneath the slider, showing that the Navigation-Menu dropdown has activated because I moved my mouse over the Search-Results dropdown. 

https://www.dropbox.com/s/ttqiflobffh75bh/DropdownMenuIssue.png?dl=0
<img width="1631" alt="DropdownMenuIssue" src="https://user-images.githubusercontent.com/93228648/141175103-ed8f1bdb-6c7a-4f40-8f13-069222866a93.png">

**Additional Support Information**

I am currently communicating with the makers of the theme I'm using (which is called Thrive). 

The theme's engineers have told me that they can see that the Custom Menu Sub-menu container is overlapping the auto-suggest list in their theme's Search Element. 

The theme maker tried adjust this by using CSS, but they could not find the target element.

**Environment information**

Device: M1 iMac

OS: MacOS 12.0.1

Browser and version: Safari Version 15.1

WordPress version: 5.8.1

Where do you host your Elasticsearch server? https://wpe-billiardsdire1.us-east-2.wpe.clients.hosted-elasticpress.io

What ElasticPress features do you have currently active? Post Search, Autosuggest, WooCommerce, Related Posts, Facets

### wp-core ##

#

version: 5.8.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 11
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /nas/content/live/billiardsstage
wordpress_size: loading...
uploads_path: /nas/content/live/billiardsstage/wp-content/uploads
uploads_size: loading...
themes_path: /nas/content/live/billiardsstage/wp-content/themes
themes_size: loading...
plugins_path: /nas/content/live/billiardsstage/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Thrive Theme Builder (thrive-theme)
version: 3.2
author: Thrive Themes
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, menus, html5, customize-selective-refresh-widgets, post-formats, tve-wc-mini-cart, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /nas/content/live/billiardsstage/wp-content/themes/thrive-theme
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (6) ###

Force Strong Passwords - WPE Edition: version: 1.8.0, author: Jason Cosper
WPE ElasticPress Autosuggest Logger: version: 1.0.0, author: WP Engine
WP Engine Cache Plugin: version: 1.0.5, author: WP Engine
WP Engine Seamless Login Plugin: version: 1.5.5, author: WP Engine
WP Engine Security Auditor: version: 1.0.10, author: wpengine
WP Engine System: version: 5.0.1, author: WP Engine

### wp-plugins-active (22) ###

Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Duplicate Page: version: 4.4.5, author: mndpsingh287, Auto-updates disabled
ElasticPress: version: 3.6.4, author: 10up, Auto-updates disabled
Product Description on Shop Page: version: 1.0.1, author: KoalaApps, Auto-updates disabled
Product Slider Pro for WooCommerce: version: 2.7.2, author: ShapedPlugin, Auto-updates disabled
Rank Math SEO: version: 1.0.76, author: Rank Math, Auto-updates disabled
Rank Math SEO PRO: version: 3.0.0, author: Rank Math, Auto-updates disabled
Thrive Architect: version: 3.4, author: <a href="http://www.thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
Thrive Product Manager: version: 1.2.7, author: Thrive Themes, Auto-updates disabled
TinyPNG - JPEG, PNG & WebP image compression: version: 3.3, author: TinyPNG, Auto-updates disabled
Variation Swatches for WooCommerce: version: 1.1.19, author: Emran Ahmed, Auto-updates disabled
Variation Swatches for WooCommerce - Pro: version: 1.1.18, author: Emran Ahmed, Auto-updates disabled
WooCommerce: version: 5.9.0, author: Automattic, Auto-updates disabled
WooCommerce Affirm Gateway: version: 1.1.10, author: WooCommerce, Auto-updates disabled
WooCommerce Authorize.Net Gateway: version: 3.6.2, author: SkyVerge, Auto-updates disabled
WooCommerce Blocks: version: 6.2.0, author: Automattic, Auto-updates disabled
WooCommerce Product Reviews Pro: version: 1.15.4, author: SkyVerge, Auto-updates disabled
WooCommerce Tab Manager: version: 1.12.2, author: SkyVerge, Auto-updates disabled
WooCommerce TM Extra Checkout Options: version: 1.7.6, author: themeComplete, Auto-updates disabled
WooCommerce TM Extra Product Options: version: 5.1, author: themeComplete, Auto-updates disabled
WP Engine Smart Plugin Manager: version: 5.8.0, author: WP Engine, Auto-updates disabled
WP Rocket: version: 3.10.1, author: WP Media, Auto-updates disabled

### wp-plugins-inactive (26) ###

10WEB manager: version: 1.4.13, author: 10Web, Auto-updates disabled
Additional Variation Images Gallery for WooCommerce: version: 1.2.8, author: Emran Ahmed, Auto-updates disabled
Additional Variation Images Gallery for WooCommerce - Pro: version: 1.2.7, author: Emran Ahmed, Auto-updates disabled
Advanced Product Fields Extended for WooCommerce: version: 1.7.6, author: StudioWombat, Auto-updates disabled
Akismet Anti-Spam: version: 4.2.1, author: Automattic, Auto-updates disabled
Autoptimize: version: 2.9.2, author: Frank Goossens (futtta), Auto-updates disabled
Enable Media Replace: version: 3.6.2, author: ShortPixel, Auto-updates disabled
Envato Market: version: 2.0.6, author: Envato, Auto-updates disabled
Extendons: WooCommerce & Light Speed POS Integration: version: 1.0.0, author: Extendons, Auto-updates disabled
Gravity Forms: version: 2.5.5.1, author: Gravity Forms, Auto-updates disabled
Gravity Forms Styles Pro: version: 3.0, author: Warp Lord, Auto-updates disabled
Re-add text underline and justify: version: 0.3, author: Brice Capobianco, Auto-updates disabled
ShortPixel Image Optimizer: version: 4.22.6, author: ShortPixel, Auto-updates disabled
Slider by 10Web: version: 2.2.49, author: 10Web, Auto-updates disabled
Smart Manager For WooCommerce – Stock Management, Bulk Edit & more...: version: 5.29.0, author: StoreApps, Auto-updates disabled
Storefront Pro Blocks: version: 3.2.0, author: Pootlepress, Auto-updates disabled
Thrive Automator: version: 0.5, author: <a href="https://thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
Thrive Comments: version: 2.2, author: <a href="https://thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
WooCommerce Dynamic Pricing & Discounts: version: 2.4.3, author: RightPress, Auto-updates disabled
WooCommerce Lead Time: version: 1.5.3, author: Barn2 Plugins, Auto-updates disabled
Woocommerce XML Feeds: version: 1.0.7, author: Spyros Vlachopoulos, Auto-updates disabled
WP AutoTerms: version: 2.4.8, author: WP AutoTerms, Auto-updates disabled
YITH Infinite Scrolling: version: 1.5.3, author: YITH, Auto-updates disabled
YITH Infinite Scrolling Premium: version: 1.5.2, author: YITH, Auto-updates disabled
YITH WooCommerce Ajax Search Premium: version: 1.10.0, author: YITH, Auto-updates disabled
YITH WooCommerce Request A Quote Premium: version: 3.1.3, author: YITH, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.4.4
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 137 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-1049-gcp x86_64
httpd_software: Apache
php_version: 7.4.24 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_filesize: 50M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.35-38-log
client_version: mysqlnd 7.4.24

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/billiardsstage/wp-content
WP_PLUGIN_DIR: /nas/content/live/billiardsstage/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_unicode_ci

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### epio_autosuggest ###

`

**Comment by felipeelia** [comment]
Hi @CarletonTorpin

Although it is great to see you here again, the objective of this repository is to track and fix bugs specifically related to the plugin. Both issues you opened (this and #2427) are actually something specific to your website/theme.

Going back to the problem you are facing, it is happening due to the element displayed in the image. Removing the z-index:0 fixes the issue.

![issue-2451](https://user-images.githubusercontent.com/184628/141478145-b68851c8-5cd0-4e7e-9ca6-8c0c639a70cc.png)

As that is something related to your theme specifically, if you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation.
