### ISSUE TITLE
QUESTION: How to add 'post_date' field for article attributes and manage assigning weights ?

### ISSUE THREAD

**Issue by yuzhiyingYZY** [10up/ElasticPress#2452]
Hi, 
Here are two questions for a rookie.
1.  Is it possible to add 'post_date' field to 'ElasticPress->Search Fields & Weighting' by modifying the source code function to manage the menu?
2. I followed "https://www.elasticpress.io/blog/2020/06/custom-fields-and-weighted-search-with-elasticpress-part-2/" to add 'post_date' field, and which is showed up at 'ElasticPress->Search Fields & Weighting' page, but when I tried to make a search, then found out it didn't work, and the search was based on mysql not by Elasticsearch.
Since I am a new starter for Elasticsearch, I am looking forward to your reply.

**Comment by felipeelia** [comment]
Hi @yuzhiyingYZY,

For dates, we have a date decay functionality, that you can enable here:

![image](https://user-images.githubusercontent.com/184628/141479775-6768c75a-11d1-4f61-b3e4-50063feb1b68.png)

If that does work as you expect, you can tweak it using the filters outlined in [this comment](https://github.com/10up/ElasticPress/issues/2073#issuecomment-776155310).

Also worth noting that you can use the [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugins to debug your queries.

Thanks!
