### ISSUE TITLE
QUESTION: does Self-Hosted works?

### ISSUE THREAD

**Issue by Matteoa99** [10up/ElasticPress#2455]
Hi, I have a debian 11 machine where I installed elasticsearch 7.9.3 and i load my wordpress site.

I configured elasticsearch assigning a cluster and a node name, but when I try to add my server to elastipress configuration I have this error: “There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again, or you may need to change your settings.”

I set this elasticsearch url to plug-in http://localhost:9200

How can I fix the issue?
Thanks

**Comment by dustinrue** [comment]
Please confirm that Elasticsearch is running on the same server as your site (so it really is at localhost) and that Elasticsearch is running properly. Newer versions of Elasticsearch are more picky about the configuration being correct and will crash or restart if it is incorrect.
