### ISSUE TITLE
YITH WooCommerce Ajax Product Filter compatibility

### ISSUE THREAD

**Issue by jessiemele** [10up/ElasticPress#2460]
I am using YITH WooCommerce Ajax Product Filter for filtering products and am having an issue where my product categories grid pages are having issues when sorted by price. When you choose sort by price it shows that there are no products in situations where the products are all WooCommerce variable products (https://www.avalonflooring.com/products/hardwood). If there are WooCommerce simple products, it just sorts those (https://www.avalonflooring.com/products/hardwood). It looks like it is only sorting simple products across the board when choosing sort by price, all other filters seem to be working fine. If I disable the ElasticPress plugin it works fine.

**Comment by felipeelia** [comment]
Hey @jessiemele,

As we've met about this problem, all follow-ups will happen through other platforms, and it was something related to your setup, I'm closing this GitHub issue. Thanks!
