### ISSUE TITLE
QUESTION: Indexing ACF fields

### ISSUE THREAD

**Issue by przestrzal** [10up/ElasticPress#2465]
Hello EP team,

i'm using ElasticPress for my backend app, because i need to speed up WP Query when  there's a lot of posts and i need to query them with "meta_query". Pure WP queries are very slow without any power ups...

I'm using ACF to manage whole posts fields and i see that EP on default is syncing every ACF registered fields. Could you tell me how to choose which fields should be indexing and which should not? I can't find any documentation about it.

Thank you in advance for your help.

**Comment by felipeelia** [comment]
Hi @przestrzal,

You can use the snippet provided in [this article](https://elasticpress.zendesk.com/hc/en-us/articles/360052019111-How-to-exclude-metadata-from-indexing) or manage that with the [ElasticPress Labs](https://github.com/10up/ElasticPressLabs) plugin. Thanks!

**Comment by przestrzal** [comment]
Thx.
