### ISSUE TITLE
Create a php based proxy for instant search 

### ISSUE THREAD

**Issue by mckdemps** [10up/ElasticPress#2477]

**Comment by lkraav** [comment]
Hi. Could opening comment be edited to provide clarity on what exactly does issue title mean?

**Comment by felipeelia** [comment]
This work is happening in https://github.com/10up/elasticpress-proxy

**Comment by felipeelia** [comment]
Closing this one out as the code in the [ElasticPress Proxy repo](https://github.com/10up/elasticpress-proxy) is already in a fully functional state.
