### ISSUE TITLE
BUG: Broken Search Pagination on Hierarchical Post Types

### ISSUE THREAD

**Issue by tfrommen** [10up/ElasticPress#2480]
**Describe the bug**
When searching a hierarchical post type in the admin, for example, Pages (`/wp-admin/edit-php?post_type=page`), the pagination is broken. This is becacuse of a combined bug in WordPress in ElasticPress.

**Steps to Reproduce**

1. Go to Pages in the admin: `/wp-admin/edit-php?post_type=page`
2. Search for a word or phrase where you have lots of posts that include this.
3. Use pagination buttons to navigate to, say, page 3.
4. This will result in a request error for Elasticsearch.

**Expected behavior**
Pagination when searching hierarchical post types should just work.

**Screenshots**

**Environment information**
(This is irrelevant because the two places in WordPress and ElasticPress code have been introduced years and years ago, see further down.)

**Additional context**
The reason for this issue is the `from` argument in the query, which is `-2` (for page 3).

This is because [ElasticPress uses `posts_per_page` to calculate the offset](https://github.com/10up/ElasticPress/blob/a39cb492400854173d65e33acd605883b01cfcaf/includes/classes/Indexable/Post/Post.php#L1659), `POSTS_PER_PAGE * ( PAGE - 1 )`. For hierarchical post types, however, this value is [overwritten to `-1` by WordPress](https://github.com/WordPress/wordpress-develop/blob/db8df6b8e8041e697acb9bd63e28ca35908e2a85/src/wp-admin/includes/post.php#L1230) (most probably to fetch **all** posts so that posts to be shown on the current page that have a parent can be listed with their parent post).

Now, with `posts_per_page` being `-1`, this will lead to `-1 * ( PAGE - 1 )`, which is the following:
- Page 2: `-1`
- Page 3: `-2`
- Page 4: `-3`
- ...

Negative `from` values will lead to a null pointer exception, and thus a request error.

I **think** a fix for this would be to ensure that `from` is greater or equal to `0`. That means, if `posts_per_page` is `-1`, just set `from` to `0`, and it should all work. The actual pagination (i.e., showing the correct posts from all the posts fetched) will then be done by WordPress anyway.

**Comment by felipeelia** [comment]
Hi @tfrommen, thanks for opening this issue! I'm able to reproduce the problem and your suggested fix seems to work fine. Do you have the availability to create a PR with that?

**Comment by tfrommen** [comment]
@felipeelia done that over in https://github.com/10up/ElasticPress/pull/2511.
