### ISSUE TITLE
BUG: Synonyms lost  

### ISSUE THREAD

**Issue by Etheliene** [10up/ElasticPress#2487]
**Describe the bug**
I have a huge list of synonyms that I have worked into the given plugin fields. When I save and reload the synonyms still appear, if I restart the server or visit back a few days later all the synonyms are gone. This is the third time this happened.

**Steps to Reproduce**

**Expected behavior**
The Synonyms should be saved to the database or some sort of storage so they don't dissappear.

**Environment information**
 - Device:  PC
 - OS: WIN10
 - Browser and version: Chrome 96.0.4664.45 
 - WordPress version: 5.8.2
 
 - <details><summary>Site Health Info:</summary>
`
### wp-core ###

version: 5.8.2
site_language: de_DE_formal
user_language: de_DE_formal
timezone: Europe/Berlin
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1300
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/vhosts/rechtsanwalt.com/httpdocs
wordpress_size: loading...
uploads_path: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content/themes
themes_size: loading...
plugins_path: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
maintenance.php: true

### wp-active-theme ###

name: Hello Elementor Child (hello-theme-child-master)
version: 1.0.1
author: Elementor Team
author_website: https://elementor.com/
parent_theme: Hello Elementor (hello-elementor)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content/themes/hello-theme-child-master
auto_update: Deaktiviert

### wp-parent-theme ###

name: Hello Elementor (hello-elementor)
version: 2.4.1
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
theme_path: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content/themes/hello-elementor
auto_update: Deaktiviert

### wp-themes-inactive (5) ###

Racom 2021: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
: author: Anonymous, version: (undefined), Automatische Aktualisierungen deaktiviert
Twenty Nineteen: version: 2.1, author: WordPress-Team, Automatische Aktualisierungen deaktiviert
Twenty Twenty: version: 1.8, author: WordPress-Team, Automatische Aktualisierungen deaktiviert
Twenty Twenty-One: version: 1.4, author: WordPress-Team, Automatische Aktualisierungen deaktiviert

### wp-mu-plugins (1) ###

SecuPress COOKIEHASH: author: (undefined), version: 2.0

### wp-plugins-active (66) ###

ACF Frontend (Premium): version: 3.0.36, author: Shabti Kaplan, Automatische Aktualisierungen deaktiviert
ACF QuickEdit Fields: version: 3.1.6, author: Jörn Lund, Automatische Aktualisierungen deaktiviert
ActiveCampaign: version: 8.1.8, author: ActiveCampaign, Automatische Aktualisierungen deaktiviert
ActiveCampaign Email Preference Center: version: 2.0.9, author: E-Moxie, Automatische Aktualisierungen deaktiviert
Admin Columns Pro: version: 5.6.2, author: AdminColumns.com (latest version: 5.6.3), Automatische Aktualisierungen deaktiviert
Advanced Custom Fields PRO: version: 5.11, author: Delicious Brains (latest version: 5.11.4), Automatische Aktualisierungen deaktiviert
Advanced Post Queries: version: 1.0.15, author: Shabti Kaplan, Automatische Aktualisierungen deaktiviert
Akismet Anti-Spam: version: 4.2.1, author: Automattic, Automatische Aktualisierungen aktiviert
Borlabs Cookie - Cookie Opt-in: version: 2.2.31, author: Benjamin A. Bornschein, Borlabs, Automatische Aktualisierungen deaktiviert
Classic Editor: version: 1.6.2, author: WordPress Contributors, Automatische Aktualisierungen deaktiviert
Debug Bar: version: 1.1.2, author: wordpressdotorg, Automatische Aktualisierungen deaktiviert
Dynamic.ooo - Dynamic Content for Elementor: version: 2.0.9, author: Dynamic.ooo (latest version: 2.1.2), Automatische Aktualisierungen deaktiviert
ElasticPress: version: 3.6.5, author: 10up, Automatische Aktualisierungen deaktiviert
Ele Custom Skin: version: 3.1.4, author: Dudaster.com, Automatische Aktualisierungen deaktiviert
Elementor: version: 3.4.8, author: Elementor.com, Automatische Aktualisierungen deaktiviert
Elementor Pro: version: 3.5.1, author: Elementor.com, Automatische Aktualisierungen deaktiviert
Enhancer for WooCommerce Subscriptions: version: 2.9, author: FantasticPlugins, Automatische Aktualisierungen deaktiviert
Essential Addons for Elementor: version: 4.9.6, author: WPDeveloper, Automatische Aktualisierungen deaktiviert
Essential Addons for Elementor - Pro: version: 4.4.11, author: WPDeveloper, Automatische Aktualisierungen deaktiviert
Facebook for WordPress: version: 3.0.6, author: Facebook, Automatische Aktualisierungen deaktiviert
Germanized for WooCommerce: version: 3.6.1, author: vendidero (latest version: 3.7.2), Automatische Aktualisierungen deaktiviert
Germanized for WooCommerce Pro: version: 3.3.5, author: vendidero, Automatische Aktualisierungen deaktiviert
Gravity Forms: version: 2.5.15, author: Gravity Forms, Automatische Aktualisierungen deaktiviert
Gravity Forms User Registration Add-On: version: 4.4.8, author: Gravity Forms, Automatische Aktualisierungen deaktiviert
Loco Translate: version: 2.5.5, author: Tim Whitlock, Automatische Aktualisierungen deaktiviert
Meks Quick Plugin Disabler: version: 1.0, author: Meks, Automatische Aktualisierungen deaktiviert
Perfmatters: version: 1.8.0, author: forgemedia (latest version: 1.8.1), Automatische Aktualisierungen deaktiviert
PowerPack Pro for Elementor: version: 2.7.1, author: Team IdeaBox - PowerPack Elements, Automatische Aktualisierungen deaktiviert
Query Monitor: version: 3.7.1, author: John Blackbourn, Automatische Aktualisierungen deaktiviert
Racom: Anwaltsblog CPT: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Racom: Change Posts to Rechtsnews: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Racom: Lexikon CPT: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Racom: Marktplatz-Recht CPT: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Racom: Ratgeber CPT: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Racom: Register Fachbeitrag CPT: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Racom: Urteil CPT: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
racom_cockpit_newsfeed_cpt: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
racom_kanzlei_cpt: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
racom_rae_cpt: version: 1.0, author: Jennifer Eberlei, Automatische Aktualisierungen deaktiviert
Site Reviews: version: 5.17.8, author: Paul Ryley, Automatische Aktualisierungen deaktiviert
Thanks Redirect for WooCommerce: version: 3.0, author: Nitin Prakash, Automatische Aktualisierungen deaktiviert
Ultimate Addons for Elementor: version: 1.35.1, author: Brainstorm Force, Automatische Aktualisierungen deaktiviert
UpdraftPlus - Backup/Restore: version: 1.16.66, author: UpdraftPlus.Com, DavidAnderson, Automatische Aktualisierungen deaktiviert
User Role Editor: version: 4.60.2, author: Vladimir Garagulya, Automatische Aktualisierungen deaktiviert
User Switching: version: 1.5.8, author: John Blackbourn & contributors, Automatische Aktualisierungen deaktiviert
WooCommerce: version: 5.9.0, author: Automattic, Automatische Aktualisierungen deaktiviert
WooCommerce - Autocomplete Orders: version: 1.1.4, author: Serious Plugins, Automatische Aktualisierungen deaktiviert
WooCommerce PDF Invoices & Packing Slips: version: 2.10.6, author: Ewout Fernhout, Automatische Aktualisierungen aktiviert
WooCommerce Stripe Gateway: version: 5.8.1, author: WooCommerce, Automatische Aktualisierungen aktiviert
WooCommerce Subscriptions: version: 3.1.6, author: WooCommerce, Automatische Aktualisierungen deaktiviert
WooCommerce Zapier: version: 2.2.2, author: OM4 Software, Automatische Aktualisierungen deaktiviert
WP All Import - ACF Add-On: version: 3.3.5, author: Soflyy, Automatische Aktualisierungen deaktiviert
WP All Import Pro: version: 4.7.1, author: Soflyy, Automatische Aktualisierungen deaktiviert
WP Crontrol: version: 1.12.0, author: John Blackbourn & crontributors, Automatische Aktualisierungen deaktiviert
WP Frontend Delete Account: version: 1.5.9, author: Sanjeev Aryal, Automatische Aktualisierungen deaktiviert
WP GraphQL: version: 1.6.7, author: WPGraphQL, Automatische Aktualisierungen deaktiviert
WPGraphQL for Advanced Custom Fields: version: 0.5.2, author: WPGraphQL, Jason Bahl, Automatische Aktualisierungen deaktiviert
WP Job Manager: version: 1.35.2, author: Automattic, Automatische Aktualisierungen deaktiviert
WP Mail SMTP Pro: version: 2.5.3, author: WPForms, Automatische Aktualisierungen deaktiviert
WP Notification Bell: version: 1.3.8, author: SPlugins (latest version: 1.3.9), Automatische Aktualisierungen deaktiviert
WP Rocket: version: 3.10.3, author: WP Media, Automatische Aktualisierungen deaktiviert
WP Rocket | Cache Search Results: author: WP Rocket Support Team, version: (undefined), Automatische Aktualisierungen deaktiviert
WP to Buffer Pro: version: 4.7.2, author: WP Zinc, Automatische Aktualisierungen deaktiviert
Yoast SEO: version: 17.7.1, author: Team Yoast, Automatische Aktualisierungen deaktiviert
Yoast SEO: News: version: 13.0, author: Team Yoast, Automatische Aktualisierungen deaktiviert
Yoast SEO Premium: version: 17.4, author: Team Yoast, Automatische Aktualisierungen deaktiviert

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Nicht verfügbar
imagemagick_version: Nicht verfügbar
imagick_version: Nicht verfügbar
file_uploads: File uploads is turned off
post_max_size: 80M
upload_max_filesize: 32M
max_effective_size: 32 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-91-generic x86_64
httpd_software: Apache
php_version: 7.4.3 64bit
php_sapi: fpm-fcgi
max_input_variables: 60000
time_limit: 1200
memory_limit: 4068M
max_input_time: 60
upload_max_filesize: 32M
php_post_max_size: 80M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.31-MariaDB-0ubuntu0.20.04.1
client_version: mysqlnd 7.4.3

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content
WP_PLUGIN_DIR: /var/www/vhosts/rechtsanwalt.com/httpdocs/wp-content/plugins
WP_MEMORY_LIMIT: 2048M
WP_MAX_MEMORY_LIMIT: 2048M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### wp_mail_smtp ###

version: 2.5.3
debug: Keine Debug-Hinweise gefunden.
db_tables: racom_wp_wpmailsmtp_tasks_meta, racom_wp_wpmailsmtp_emails_log
pro_install_date: Feb 4, 2021 @ 3:46pm
email_log_entries: 113

`
   </details>

**Comment by felipeelia** [comment]
Hi @Etheliene,

Synonyms are stored in the database as a Custom Post Type named `ep-synonym`. Can you please:

1. Save your synonyms and check if the post is created in your database? `SELECT * FROM wp_posts WHERE post_type = 'ep-synonym';` is the SQL query for that. If you have more than one, that is okay.
2. Based on the answer for #1, restart your server and check if/how that changed.

The [Stream](https://wordpress.org/plugins/stream/) plugin can also help to detect how/when/if the post is updated. Unfortunately, the entry won't have any "synonyms" word in it but if you see any `"" post draft saved` entry, you can see if the "View" link points to an ep-synonym link.

**Comment by felipeelia** [comment]
@Etheliene I've created #2517 addressing that problem but while that is not incorporated in a version release, you can apply the fix I added there as [a comment](https://github.com/10up/ElasticPress/pull/2517#issuecomment-992780290). Thanks!
