### ISSUE TITLE
QUESTION: How to realize fuzzy search?

### ISSUE THREAD

**Issue by FunnyRyan** [10up/ElasticPress#2488]
**Describe your question**

When searching for multiple keywords, if there is no precise keyword result, can it return the aggregate result of the keyword query after the word segmentation?

**Comment by felipeelia** [comment]
HI @FunnyRyan,

You can try adding [this snippet](https://gist.github.com/felipeelia/f4f5dcf4684461d48efe70920cbffdfe) to your theme's functions.php to add a "cross_fields" search. The new search algorithm we've introduced in [ElasticPress 4.0.0 Beta 1](https://github.com/10up/ElasticPress/releases/tag/4.0.0-beta.1) can also help you with that if you want to give it a try (don't use it in production environments yet, okay?)

Another option is to use the old algorithm. To do that you can use the following WP-CLI command or install [ElasticPressLabs](https://github.com/10up/ElasticPressLabs) to change it in the interface.
`wp elasticpress set-algorithm-version --version='3.4'`

I'm going ahead and closing the issue now but feel free to leave a comment with the results you get. Thanks!

**Comment by FunnyRyan** [comment]
thank you for the answer  : )
