### ISSUE TITLE
Google web story plugin - search console errors 

### ISSUE THREAD

**Issue by iastermee** [10up/ElasticPress#2494]
Hello, 
I have the following errors in the search console, regarding "google web stories"

1.) Custom JavaScript is not allowed.
2.) HTML Event attributes, aka 'on*', are not allowed in AMP. Instead, use 'amp-bind'

Help me to solve these issues

**Comment by felipeelia** [comment]
Hi @iastermee, do you have a public URL where we could see that problem happening and how they are related to ElasticPress?
