### ISSUE TITLE
Use form and button elements for Feature settings forms, remove jQuery dependency from related JavaScript

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#2496]
**Is your enhancement related to a problem? Please describe.**
The current feature settings boxes are input fields with certain classes and data-field-name attributes, as well as an anchor element which is used to submit the form. When this link is click JS gathers the field data using the field classes and sends it to an AJAX endpoint.

This arrangement made the changes required for #2491 more difficult than verbose than it needed to be, and it has side effects like not being able to press Enter to submit the form.

**Describe the solution you'd like**
Wrap the feature settings fields in a form element, replace the anchor with a proper submit button, and optimise the JavaScript to handle form data. This would be an opportunity to rewrite dashboard.js without jQuery, and remove a bunch of unnecessary markup from the settings fields.

**Comment by felipeelia** [comment]
Closed by #2503
