### ISSUE TITLE
BUG: Incompatibility with WooCommerce Brands

### ISSUE THREAD

**Issue by slaxxarn** [10up/ElasticPress#2502]
**Describe the bug**
When filtering on category pages with WooCommerce brands layered nav widget, nothing is shown because elasticpress adds a second tax query with field = slug and operator = and / or. While woocommerce brand adds/uses term_id as field and IN as operator.

<img width="239" alt="Skärmavbild 2021-12-08 kl  08 57 58" src="https://user-images.githubusercontent.com/15977552/145170534-b60059ad-f8bb-4ebb-a48f-fe60741edd96.png">

The issue is in Facet.php and row 326 - 333. You add a tax query with field = slug and operator = AND / OR

```php
foreach ( $selected_filters['taxonomies'] as $taxonomy => $filter ) {
	$tax_query[] = [
		'taxonomy' => isset( $attribute_taxonomies[ $taxonomy ] ) ? $attribute_taxonomies[ $taxonomy ] : $taxonomy,
		'field'    => 'slug',
		'terms'    => array_keys( $filter['terms'] ),
		'operator' => ( 'any' === $settings['match_type'] ) ? 'or' : 'and',
	];
}
```

**Steps to Reproduce**
1. Add a brand
2. Add products to the newly added brand
3. Add the woocommerce brand layered nav widget in sidebar
4. Go to the category page and filter
5. Nothing is shown

**Expected behavior**
Don't add another tax query if a tax query for the same taxonomy already exists.

**Comment by felipeelia** [comment]
Related to #2129

**Comment by slaxxarn** [comment]
Hi @oscarssanchez,

We're using version 1.6.14 of the plugin. But widgets filtering by IN operator should not work if elasticpress is enabled, as you add a seperate tax query with AND or OR. 

As I stated previously, could you not just check if a query for the taxonomy already exist before adding another one?

Will look into and test some other variations tomorrow, don't really have the time right not. Will get back in this issues after som testing.
