### ISSUE TITLE
Implement shareable URLs for Instant Results

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#2506]
**Is your enhancement related to a problem? Please describe.**

In its current state, it's not possible to share, bookmark or link directly to Instant Results search results. This is because the search results modal is triggered by an intercepted form submission and handled entirely in the client, and there's no ability to open Instant Results from the URL.

**Describe the solution you'd like**

Performing searches in the Instant Results modal should update the URL in the browser's address bar. This will allow users to share or bookmark the URL for a particular set of results. Consequently, visiting these URLs needs to automatically open the Instant Results modal with the search term, pagination and filters pulled from the URL and pre-populated.

With this behaviour in place it would also make sense to implement the browser history APIs so that the user can navigate backwards and forwards between search queries and pagination. It would also make sense if going backwards or forwards would also open or close the modal. This would also update the URL.

One challenge would be naming the URL parameters so that they do not interfere with any core URL parameters, leading to WordPress returning a 404 status. It may also be desirable for the resulting URL to perform a matching search within WordPress, so that if JavaScript is disabled, or of Instant Results has since been disabled, the URL performs some of its functionality.

**Comment by felipeelia** [comment]
Closed by #2604
