### ISSUE TITLE
QUESTION: Autosuggest with self hosted elastic

### ISSUE THREAD

**Issue by Matteoa99** [10up/ElasticPress#2513]
Hi, i would like to configure to autossugest with with self hosted elastic.
I have configure plug-in how is this picture but it seems not working.

![Immagine 2021-12-10 175522](https://user-images.githubusercontent.com/16364422/145611912-bbfc3cd8-ed86-41a3-808a-9944ac6449b1.png)

Does someone can help me? 
Thanks

**Comment by felipeelia** [comment]
Hi @Matteoa99,

ElasticPress will send an Elasticsearch query to that Endpoint URL, so:

1. It needs to be something accessible by the user, not by your webserver.
2. Generally you'll want to send that query to your posts index but we **strongly** advise against simply making your ES server public and pointing people to your index, as it can be a major security problem (people could, for example, erase all your data)

More on that [here](https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups). As setting up security rules and/or sanitizing ES queries are outside of the scope of the plugin, I'm closing the issue now. Thanks

**Comment by Matteoa99** [comment]
Thank for reply and for security advice, I will apply it later.
But I still can't understand why this endpoint url in not correct:  http://127.0.01:9200/searchcronachemaceratesiit-post-1

**Comment by Matteoa99** [comment]
> Hi @Matteoa99,
> 
> ElasticPress will send an Elasticsearch query to that Endpoint URL, so:
> 
> 1. It needs to be something accessible by the user, not by your webserver.
> 2. Generally you'll want to send that query to your posts index but we **strongly** advise against simply making your ES server public and pointing people to your index, as it can be a major security problem (people could, for example, erase all your data)
> 
> More on that [here](https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups). As setting up security rules and/or sanitizing ES queries are outside of the scope of the plugin, I'm closing the issue now. Thanks

Thank for reply and for security advice, I will apply it later.
But I still can't understand why this endpoint url in not correct: http://127.0.01:9200/searchcronachemaceratesiit-post-1

**Comment by nicoladj77** [comment]
@Matteoa99 it looks like you are running an elastic search server on your computer and trying to fetch data from it from a public install. That will not work.

**Comment by Matteoa99** [comment]
> @Matteoa99 it looks like you are running an elastic search server on your computer and trying to fetch data from it from a public install. That will not work.

So what I have to put in _Endpoint URL_ to use autosuggest considering that I have install my wp and elastic in the same computer? I can't find anything on the documentation. Thanks

**Comment by nickchomey** [comment]
@Matteoa99 Did you ever figure out what to use in _Endpoint URL_?
