### ISSUE TITLE
Can Elasticpress Index Custom Database Tables?

### ISSUE THREAD

**Issue by renegademarketer** [10up/ElasticPress#2514]
I’m considering using ElasticPress as the search solution for a new project. However, I need to be able to include data from my own and some third-party plugins that use custom database tables. Most of the data doesn't have a corresponding frontend custom post type.

I read on the Elasticpress Tutorial: Indexables page that in future versions we can create our own custom Indexables by extending the Indexable class.

Question: Is that possible now? And if so, is there any documentation on how to accomplish this?

**Comment by oscarssanchez** [comment]
Hi @renegademarketer ,

Yes, you should be able to create your own Indexables, see 
http://10up.github.io/ElasticPress/tutorial-indexables.html.

An indexable is defined as any queryable object, so you will need to construct one from scratch or extend an existing class, like what WooCommerce does with BlocksWpQuery. After this, you can extend the Indexable class to create your own Indexables.

Alternatively, you can also index any data from custom tables to a fresh index you create and query the index. However, this would basically mean you won't use ElasticPress that much. Elastic has a lot of documentation on how to build indices, index documents and run queries: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html

**Comment by renegademarketer** [comment]
Thanks for the answer and references!
