### ISSUE TITLE
QUESTION: Stop post ID from returning a single result if match is found via filter

### ISSUE THREAD

**Issue by lewisSkyline** [10up/ElasticPress#2515]
Not sure if this should go under question/feature:

We have a client that uses ElasticPress for WooCommerce/order search. We've used filters to add some custom meta keys to the search fields, these include some custom order numbers and invoice PDF numbers. 

The problem we have found is that if an order (/post) ID matches the search query, then it just returns that single result and doesn't continue with the search.

Perhaps this is an edge case, but could we get a filter to turn this behavior off? Or should we be doing things differently and not adding other numerical fields to the search?

Could a filter be added to turn off single results when 'exact matches' are found for WooCommerce Orders?

**Comment by oscarssanchez** [comment]
Hi @lewisSkyline ,

Could you please give an example of this? If possible, please provide as well:

1.- WP_Query args
2.- ElasticPress formatted query (vía the ElasticPress debug bar)
3.- ElasticSearch query result (vía the ElasticPress debug bar)

Thanks!

**Comment by felipeelia** [comment]
Hi @lewisSkyline,

IIRC, the current WooCommerce behavior will search for orders directly into the database, and when ElasticPress captures the query, it is already just the IDs returned by that MySQL query.

This seems to be the related function: https://github.com/woocommerce/woocommerce/blob/67a81463e4ab848ee099db53a60197c8bfaa8d49/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L514

You can use the `woocommerce_shop_order_search_fields` filter to add your meta field to the fields searched by WooCommerce. Alternatively, you can use the `woocommerce_shop_order_search_results` filter to build a more custom logic.

Can you please try that and let us know how it goes? Thanks!
