### ISSUE TITLE
Dynamic number of documents sent to Elasticsearch

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2519]
**Is your enhancement related to a problem? Please describe.**

Currently, we send a fixed number of posts/users/terms/comments (documents) to Elasticsearch. That fixed number can lead us to two different problems:
1. Sending too many documents can return a "Request Entity Too Large", i.e., EP tried to send too many documents in the same _bulk request OR
2. The opposite: sending just 10 documents when we could be sending 100.

**Describe the solution you'd like**

We can fix that by creating a "buffer". Keeping in mind that Elasticsearch defaults to 100MB as max_content_length, we would
1. Create an empty string (the request body), let's say `$request_body`
2. For each document check if its size + `strlen( $request_body )` exceeds max_content_length
3. If it does not exceed, add it to $request_body and move to the next one
4. If it does exceed, send the request, empty the buffer and add posts to it.

We should also account for timed-out requests. If it happens, we can split the request in two and try again.

That way we would be fixing both scenarios, as we wouldn't send a request too big nor underuse a request that could carry more documents.

**Additional Context**

This is a rethink of #1949

**Comment by jeffpaul** [comment]
Note that we should prop folks from #1949 should #2519 be the resulting PR that's actually merged into a release.
