### ISSUE TITLE
QUESTION: CPT vs Custom Table for hundreds of thousands of records?

### ISSUE THREAD

**Issue by kmcaloon** [10up/ElasticPress#2520]
Hey all, not sure if this is the right place to ask a question like this. I'm about to start migrating a huge database with hundreds of thousands of records with custom meta, taxonomies, etc. I am considering using custom tables so that the post and post meta tables aren't overcrowded and we run into a performance nightmare. However we will also be leveraging ElasticPress for our database queries. Some things I'm wondering are:

1. If we did go with custom tables, how much of an undertaking would it be to get everything to work smoothly with EP?
2. Would leveraging EP for queries mitigate the large post and post meta concerns?

**Comment by felipeelia** [comment]
Hi @kmcaloon! That would require some deeper thought but you would need to *at least* change how the document is built before being sent to Elasticsearch in the [prepare_document method](https://github.com/10up/ElasticPress/blob/3.6.5/includes/classes/Indexable/Post/Post.php#L361). As the code doesn't account for an edge case like yours, you would be probably better served with a custom indexable (I saw your comment in the other issue, will get back to you there in a second.)

For item number 2, yeah, it can help but
(1) you would need to store them in the MySQL database anyway as it is considered the source of truth for the plugin, meaning that anytime your ES data could be fully rebuilt from MySQL. And
(2) you might have an error like [this](https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-) if you have too many different "keys". It is okay if you have 300k documents with a `my-custom-meta` field but you will have problems if you have only 2 documents with 1k different keys, like `my-custom-meta-1`, `my-custom-meta-2`, ..., `my-custom-meta-1000`.

These are just some initial thoughts. Some discovery time would be needed to understand your use case in depth and plan accordingly. If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!

**Comment by kmcaloon** [comment]
Thanks @felipeelia. I'm considering possibly scheduling an appointment for the call. I don't think those two items you mentioned should be a problem, and that custom tables might help save on the db size. I've actually been digging around 10up's engineering docs to see how you all approach custom tables but couldn't find much. Will follow up in need be on the other issue.

Thanks again!
