### ISSUE TITLE
Create a Elasticpress plugin for self-hosted Elasticsearch with onetime payment or subscription

### ISSUE THREAD

**Issue by vverloop** [10up/ElasticPress#2539]
It should be nice if there is a specific Elasticpress Wordpress plugin for self-hosted Elasticsearch.
With support for the latest Elasticsearch version, more frequent updates.
Also with an extensive documentation to create the right working endpoint for Autosuggest feature.

I like to pay for that. I want to host Elasticsearch myself.
This way Elasticsearch with Wordpress/Woocommerce gets more popular and i think Elasticpress gets more customers for managed hosting.

Also official integration and support with FacetWP plugin should be nice.
So you can make the fastest and best looking Facets.
Or update the Elasticpress Facet Widget to have the best looks and features.

Now it is unclear how to get it working. A lot of speaking about it in blogs and forums, but not someone with a working example.

I think this is the next trending topic with Woocommerce.

And support for W3 Total Cache is very important!
With extensive documentation, where does it conflicts.

**Comment by vverloop** [comment]
Please update your Documentation. It is going  about Elasticsearch version 3.x

**Comment by vverloop** [comment]
To be honest, i think the managed hosting of elasticpress.io have out of dates software versions.

**Comment by vverloop** [comment]
Let's get Elastricpress plugin great again! Elasticsearch + Wordpress should me it, the master combination.
But self-hosted with subscription, i want to pay for it.

**Comment by brandwaffle** [comment]
@vverloop ElasticPress works with self-hosted instances of Elastic. Minimum versions of Elasticsearch are specified on the plugin page and require at least Elasticsearch 5.x, not 3.x. Please note this repo is for the plugin only and we do not provide any support for self-hosted Elasticsearch instances.
