### ISSUE TITLE
Indexing WooCommerce Orders?

### ISSUE THREAD

**Issue by MarkGavalda** [10up/ElasticPress#254]
Thanks for your work on this plugin!
One of the weakest points of WC is that its orders search function takes ages when you have a lot of orders. It would be great to leverage ES for this too!

**Comment by tlovett1** [comment]
Thanks for the suggestion!

**Comment by AaronHolbrook** [comment]
Hey @MarkGavalda - work was started on an admin search integration over at [https://github.com/10up/ElasticPress-Admin](https://github.com/10up/ElasticPress-Admin). It's a working prototype and any PRs are welcome.
