### ISSUE TITLE
QUESTION: HTTPS Self-Hosted

### ISSUE THREAD

**Issue by Matteoa99** [10up/ElasticPress#2542]
Hi,
I have a self-hosted elasticsearch, using http protocoll elasticpress can connect to my elasticsearch instance.
By configuring the elasticsearch server to use https without authentication; from the browser everything goes well but if I put the https address on the elasticpress setting it can't connect to the elastic server.
How can I fix it?
Thanks

**Comment by oscarssanchez** [comment]
Hi @Matteoa99 ,

I could not reproduce with what I got from your report. Would you mind providing more detailed steps so we can try to reproduce as well?

Thanks!

**Comment by maiorano84** [comment]
What kind of certificate are you using for your connection to ElasticSearch? Is it self-signed?

**Comment by Matteoa99** [comment]
Hi, I have fix the problem using a not self generate certificate.
