### ISSUE TITLE
QUESTION: Custom facets

### ISSUE THREAD

**Issue by Matteoa99** [10up/ElasticPress#2543]
Hi, 
I would like to know if is it possible create custom facets in order to perform date range search. 
Thanks

**Comment by felipeelia** [comment]
Hi @Matteoa99! Unfortunately, it is not possible right now but we have plans to implement it in the future (see #1840). I'm closing the issue now (as we already have 1840 to cover it) but if you have any specific scenario in mind or any comment or suggestion in general, please let us know, okay? Thanks!
