### ISSUE TITLE
Accessing returned aggs.

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#255]
How is this done? May be worth documenting/including in a wiki entry. I'd be glad to do so once I learn how it's done.

**Comment by Stayallive** [comment]
Hey @psorensen,

Maybe you already found it but let me know about this for an explanation:

ElasticPress exposes a hook `ep_retrieve_aggregations` which can be used to access the aggs.

I have the following code in my search wrapper:

```php
class Elasticsearch {

	/**
	 * Aggregations result from the last executed search.
	 *
	 * @var array|null
	 */
	public static $aggregations = null;

	/**
	 * Hooks and filters.
	 */
	public function __construct() {
		add_action( 'ep_retrieve_aggregations', array( $this, 'ep_retrieve_aggregations' ), 10, 1 );
	}

        /**
	 * Save the aggregation results from the last executed query.
	 *
	 * @param $aggregations
	 */
	public static function ep_retrieve_aggregations( $aggregations ) {
		self::$aggregations = $aggregations;
	}

}
```

Which allow me to do `Elasticsearch::$aggregations` and get the aggs as returned by ElasticSearch after the query has executed.
