### ISSUE TITLE
QUESTION: Plugin not working 

### ISSUE THREAD

**Issue by MrPHPProgrammer** [10up/ElasticPress#2552]
Hello

Elasticsearch (http://localhost:9200) is working but the ElasticPress plugin is not working. 

Why is the search no different from the results without the plugin? 

Thanks!

**Comment by brandwaffle** [comment]
@MrPHPProgrammer as I previously replied to your Discussion question, these are the resources you'll want to review:

- https://elasticpress.zendesk.com/hc/en-us/sections/360010672272-Getting-Started
- https://elasticpress.zendesk.com/hc/en-us/articles/360050720172-Using-the-Debug-Bar-ElasticPress-Plugin

This issue list is limited to support for plugin bugs and feature requests. We are unable to provide support for connectivity issues or basic plugin setup in this forum.

**Comment by MrPHPProgrammer** [comment]
Thanks, everything was solved by changing the search algorithm to 3.4

add_filter( 'ep_search_algorithm_version', function() { return '3.4'; } );

**Comment by leaffly** [comment]
> @MrPHPProgrammer as I previously replied to your Discussion question, these are the resources you'll want to review:
> 
>     * https://elasticpress.zendesk.com/hc/en-us/sections/360010672272-Getting-Started
> 
>     * https://elasticpress.zendesk.com/hc/en-us/articles/360050720172-Using-the-Debug-Bar-ElasticPress-Plugin
> 
> 
> This issue list is limited to support for plugin bugs and feature requests. We are unable to provide support for connectivity issues or basic plugin setup in this forum.

Dear Sir, 
I meet the same issue, and I have checked almost all guide and manuals as well as others issues in github, also tried more solutions but the issue still exist.
I can see the data update when sync to ES, but the result of search is nothing. 
I use debug bar, the log is blank with "No queries to show".

I have find the solutions for more days, could you give me some advices?
