### ISSUE TITLE
QUESTION: ElasticPress works only for logged in users

### ISSUE THREAD

**Issue by chris-boyle24** [10up/ElasticPress#2556]
Running ElasticPress latest on Wordpress 5.7.4 with W3TotalCache. EP is attached to an external ElasticSearch server running 7.16 on an AWS EC2 instance. Was able to index 45,000+ posts after some issues and EP Debug indicates all is working - but only when logged in. We have an issue with search going through Wordpress' built-in search and not through ElasticPress. This seems to happen when the search is performed by a non-logged in user - you can see the (rather ugly...) search query in MySQL SHOW FULLPROCESSLIST results.

W3 Total Cache has "Don't cache pages for logged in users enabled" checked and Cache URIs with query string parameters *unchecked* under its General Settings. We use page cache, object and browser cache with Memcached (database caching is disabled). I've also specifically blocked search.php and /?s=* under never cache the following pages.

I'm assuming that when users are logged in, W3TC is being bypassed allowing ElasticPress to handle search. Non-logged in user requests are processed through W3TC which intercepts / interferes with WP_Query requests somewhere, even with the above settings in place. Is there anywhere else in W3TC (or Wordpress) I should be looking at?

**Comment by oscarssanchez** [comment]
Hi @chris-boyle24 ,

This seems to be working for me locally. I tested using elasticpress.io and trying a query while not logged in, in incognito mode. In general I don't recall having an issue with cache, but also don't recall specifically working with W3TC. Have you tried disabling W3TC to narrow the problem down to it?

**Comment by chris-boyle24** [comment]
Hi,

If I disable W3TC all search requests go through ElasticSearch. As with
most sites, we need caching in place for performance reasons.

Chris

**Comment by oscarssanchez** [comment]
Hi @chris-boyle24 ,

I just tried activating W3TotalCache and it seems it is working for me. Can you please share as much information as you can for us to try to reproduce the problem? Our bug report template is a good example of useful information for us: 

https://github.com/10up/ElasticPress/issues/new?assignees=&labels=bug&template=1-bug-report.md&title=BUG%3A+

Thanks!
