### ISSUE TITLE
BUG: Creating a post, then deleting a post in the same thread causes ES out of sync

### ISSUE THREAD

**Issue by tcrsavage** [10up/ElasticPress#2568]
**Describe the bug**
If a post object is created (`wp_insert_post`) THEN a different post object is deleted (`wp_trash_post`) in the same thread, the created post is never sent to the ES index.

**Steps to Reproduce**

1. Create a post (will be added to the EP sync queue)
2. Delete a different post in the same php thread (e.g. use case: cron job syncing content from 3rd party)

**Expected behavior**
Created post should be available in ES index

**Additional context**
Issue seems to have been introduced here through `action_delete_post`
Sync queue is cleared immediately without processing when a post is deleted
https://github.com/10up/ElasticPress/blame/develop/includes/classes/Indexable/Post/SyncManager.php#L243

**Comment by felipeelia** [comment]
Hi @tcrsavage! The code in #2575 should fix this problem, can you please test it and let us know? Thanks
