### ISSUE TITLE
How to select custom fields to be indexed, excluding all others?

### ISSUE THREAD

**Issue by pedlima** [10up/ElasticPress#2579]
Is there a way to achieve that instead of excluding one by one? I have hundreds of custom fields so a function to select which custom fields will be indexed instead of using the function ep_prepare_meta_excluded_public_keys, something that would do the opposite.

**Comment by felipeelia** [comment]
Hi @pedlima,

You can use the `ep_prepare_meta_data` filter, as we've outlined in this article: https://elasticpress.zendesk.com/hc/en-us/articles/360052019111-How-to-exclude-metadata-from-indexing

Thanks

**Comment by pedlima** [comment]
FLAWLESS!!! Incredible. Thank you so much. :)
