### ISSUE TITLE
QUESTION: Is there a way to go straight into product when we search for SKU?

### ISSUE THREAD

**Issue by pedlima** [10up/ElasticPress#2581]
Previously we were using Relevanssi and whenever we searched for a SKU, we went straight into single product page.

Right now, if we search for a SKU, it shows us the shop page with some results (including the one with the SKU).

Strange thing is, NOTHING else nowhere have the SKU, so is it possible that this is also indexing the "related products" inside single product page?

How can I have this going straight into single product page when I search for SKU?

**Comment by brandwaffle** [comment]
Hi @pedlima thanks for filing this ticket!

We'll need a bit more information in order to help with this ticket. Can you please share an example of the query performing your SKU search using the Debug Bar ElasticPress plugin, as well as the results of that query? In both cases we'll want the Elasticsearch JSON vs the WordPress array.

Thanks in advance!

**Comment by pedlima** [comment]
Hi @brandwaffle thank you for your quick answer.

Unfortunately that plugin was not registering my search query, I can't understand why.

[This is my query](https://americana.pt/?s=P121057&post_type=product)

I did used Query Monitor and filtering by ElasticPress, these were the queries:

![image](https://user-images.githubusercontent.com/27860888/152057428-996faeae-6ece-4ab4-8593-1369d83d4f7a.png)

Then filtering by WordPress Core I get this:

![image](https://user-images.githubusercontent.com/27860888/152057848-cad83733-533a-4b67-af9d-b95f708946c6.png)
![image](https://user-images.githubusercontent.com/27860888/152057912-7dba8f02-b06c-4fb5-966e-6d5c9bf429c0.png)

If you want me to see any other queries or if you want backoffice access, just let me know.

Thanks!

**Comment by felipeelia** [comment]
Hi @pedlima,

I think what I @brandwaffle meant is the Elasticsearch query (and not the MySQL queries.) If you install the Debug Bar ElasticPress plugin, it will add another tab to query monitor where those queries will be visible.

In any case, WooCommerce has a code to redirect to a product when the search 
only returns one result: https://github.com/woocommerce/woocommerce/blob/6.1.1/plugins/woocommerce/includes/wc-template-functions.php#L58

As ElasticPress will find more than one result based on its tokenization/fuzzy matches, etc., WooCommerce won't do that redirect. You could force it though, with some PHP code. I didn't test it but this should serve as an initial draft for you:

```
add_function(
	'pre_get_posts',
	function( $query ) {
		if ( is_admin() || ! $query->is_main_query() || ! $query->is_search() ) {
			return;
		}

		$product_by_sku = wc_get_product_id_by_sku( get_search_query() );
		if ( ! empty( $product_by_sku ) ) {
			wp_safe_redirect( get_permalink( $product_by_sku ), 302 );
		}
	}
);
```

**Comment by pedlima** [comment]
It did not worked and I've tried with multiple other options and never worked. :(

Also, search is very slow but for that I will open a new issue.
