### ISSUE TITLE
How to add the product filter in archive

### ISSUE THREAD

**Issue by pranavmtn** [10up/ElasticPress#2582]
Hi, 

i have started using this plugin.
I have done the integration part. Also indexing.

Could you please explain, how to make this works as a category filter in woocommerce archive/shop page?

Note that i am using storefront

I cannot see any doc related to this.

Thanks very much!!

**Comment by brandwaffle** [comment]
Hi @pranavmtn,

You can find info about setting up a site for WooCommerce/ElasticPress integration here: https://elasticpress.zendesk.com/hc/en-us/articles/4402653066637-Site-Search-Personas
