### ISSUE TITLE
QUESTION: How to implement ngram field filter on ACF field

### ISSUE THREAD

**Issue by aronvandervalk** [10up/ElasticPress#2593]
Hi,

I am currently experiencing the issue that when a search is performed, the partial matches of a custom field holding a SKU, does not return, see https://github.com/10up/ElasticPress/issues/2076. Apparently this has to do with the fact that the SKU ends on a series of numbers and we need to tell EP to explicitly return partial matches on numbers, using the [ngram field filter](http://10up.github.io/ElasticPress/ep_autosuggest_ngram_fields.html).

Could anyone provide an example how to implement this filter on an ACF custom field? I cannot find any code implementation examples. 

Thanks in advance!

**Comment by felipeelia** [comment]
Hi @aronvandervalk,

As I said in the issue you linked, to achieve what you want these steps will be needed:

1. Add the ngram field to the mapping somehow
2. Reindex everything
3. Change the query sent to Elasticsearch in a way to include the new ngram field.

Although the goal of this repo is not to share snippets to fix specific problems, as this is a feature frequently asked by the users, I've put together this gist with the code needed: https://gist.github.com/felipeelia/e8157156751a021c89ff41c468ac5e4d

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. As any additional action won't happen here on GitHub, I'm closing the issue now. Thanks.
