### ISSUE TITLE
Meta returned by WP_Query

### ISSUE THREAD

**Issue by przestrzal** [10up/ElasticPress#2594]
Hi everyone,

i'm wondering if is there any possibility to define via WP_Query args which meta fields should by returned by query like it's possible doing raw query to Elasticsearch?

I have a lot of registered meta for many custom post types and every query is consuming a lot of RAM, so i'm looking for any solution using EP to make a queries which will return less unnecessary meta (used in other post type).

Thanks in advance for your help.

**Comment by oscarssanchez** [comment]
Hi @przestrzal do you mean something like: 

https://developer.wordpress.org/reference/classes/wp_query/#return-fields-parameter

If this is correct, as this is not a standard `WP_Query` I doubt it can be done as of now.

**Comment by przestrzal** [comment]
@oscarssanchez unfortunetelly it's not im looking for. This param switch result from object/ids/parent=>id pair

WP_Query with `ep_integrate` set to `true` returns all meta. I want to skip those which are corresponding to other post types.

**Comment by felipeelia** [comment]
Hi @przestrzal,

You can achieve that by changing the ES query directly. Something like the following code:

```
add_filter(
	'ep_post_formatted_args',
	function ( $formatted_args ) {
		$formatted_args['_source'] = [ 'post_title', 'meta._manage_stock' ];
		return $formatted_args;
	}
);
```

If you are looking for something else, let us know okay? Thanks.

**Comment by przestrzal** [comment]
@felipeelia thank you very much! It is exactly what i was looking for!
