### ISSUE TITLE
BUG: User search request yields users who do not exist in the current site

### ISSUE THREAD

**Issue by tfrommen** [10up/ElasticPress#2599]
**Describe the bug**
When searching for users, the ElasticPress query may yield users who do not exist in the current site.

This is not obvious by default, but when using some more involved configuration, for example, using autosuggest/ngram.

**Steps to Reproduce**

1. Have a multisite installation.
1. Create a user with login `test`.
1. Do not add that user to any site.
1. On some site, navigate to the Users page, `/wp-admin/users.php`.
1. Search for "test".
1. You will see the user appear as a result. This is wrong!

In order for this to fail, you will need something like the following filter callback running in your site:

```php
add_filter( 'ep_user_formatted_args_query', function ( $query, $args ) {

	$query['bool']['should'][] = [
		'multi_match' => [
			'query' => $args['s'] ?? $args['search'],
			'fields' => [
				'user_login.suggest',
			],
		],
	];

	return $query;
}, 10, 2 );
```

**Expected behavior**

The query should only yield users who exist in the current site.

**Screenshots**

**Environment information**
This bug is independent of the environment.

**Additional context**

**Comment by tfrommen** [comment]
👋 Hey, hello,

it's been a while, and I don't see anything happening here or on the PR.
Is there anything wrong with the reported issue and/or proposed fix?

Thanks! 😀

**Comment by felipeelia** [comment]
Hi @tfrommen,

Absolutely nothing wrong. We have solely focused our attention on the 4.0.0 release in the last month but now that that is already made available we will get back to the Pull Requests list and merge them accordingly. Thanks for your patience.
