### ISSUE TITLE
QUESTION: How do I restrict search results to a product category or term if the search is initiated from that term's archive template?

### ISSUE THREAD

**Issue by gillespieza** [10up/ElasticPress#2608]
**Describe your question**
I have 2 categories in my shop - parts, and whole goods. There are thousands and thousands of part numbers (and only a handful of whole goods), and I don't want them "contaminating" my whole good results, or vice versa.

If I create a custom product search form in, for example, taxonomy-product_cat-{term}.php, can I restrict the search results to that category?

I have already included a product search form in my taxonomy_product_cat.php template, using:
``` add_action( 'woocommerce_archive_description', 'my_get_product_search' ); ```

**Comment by felipeelia** [comment]
Hi @gillespieza,

That will require some custom code. Basically, you'd have to:
1. Add a hidden input to that custom form, so the target URL becomes `?s=term&post_type=product&product_cat=<product_cat>`
2. Capture the WP_Query being executed in the search term using pre_get_posts
3. Adapt the query adding the tax_query you need.

Once you have done that, ElasticPress will automatically detect the change in WP_Query and act accordingly. For development purposes, I recommend you to temporarily disable ElasticPress, have it work with WordPress core only, and then reenable EP, so you can rule it out if you face any problems.
