### ISSUE TITLE
Add Instant Results to WordPress.org Repository readme

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2629]
In https://wordpress.org/plugins/elasticpress/ we display a list of features available in the plugin. We will need to add Instant Results and its description when we release 4.0.

**Comment by brandwaffle** [comment]
**Instant Results**: A built for WordPress search experience that bypasses WordPress for optimal performance. Instant Results routes search queries through a dedicated API, separate from WordPress, returning results up to 10x faster than previous versions of ElasticPress.

**Comment by brandwaffle** [comment]
<img width="1294" alt="Screen Shot 2022-03-07 at 9 10 28 AM" src="https://user-images.githubusercontent.com/663228/157083443-331a3f5c-baad-4183-8cff-1d10f4864a08.png">

**Comment by felipeelia** [comment]
Closed by #2638
