### ISSUE TITLE
Supporting 'like' query in post meta

### ISSUE THREAD

**Issue by tuanmh** [10up/ElasticPress#263]
It seems that currently EP does not support 'LIKE' query against post meta data. This is actually a need as sometimes we don't want to match exact by using 'term' but using 'match'. This could be really handy. I can do a PR if desired.

**Comment by tlovett1** [comment]
Have you looked at the `search_fields` parameter?

**Comment by tuanmh** [comment]
Yes. I'm using it for one of my post_meta fields. However, in our app, we have a search query which queries against the search fields and another query using in filter. For example:
- ``Introduction``: main query on fields ``post title, post content, post_meta.subtitle``
- ``elasticpress``: a filter, something like ``elasticpress`` on other fields, e.g. ``post_meta.ABC``

So it's basically the same as other operators but it requires a 'match' not 'term'.

**Comment by tuanmh** [comment]
Something like this commit (05a8b0b) would be really appreciated. 

```php
						case 'like':
							if ( isset( $single_meta_query['value'] ) ) {
								$terms_obj = array(
									'query' => array(
										"match" => array(
											'post_meta.' . $single_meta_query['key'] => $single_meta_query['value'],
										)
									),
								);
							}
							break;
```

**Comment by tlovett1** [comment]
@tuanmh can you open a PR?

**Comment by tuanmh** [comment]
@tlovett1 I will add the test ASAP.

**Comment by tuanmh** [comment]
Closing via c142064 and 99d334c
