### ISSUE TITLE
QUESTION: How to implement search results to exclude specified categories? 

### ISSUE THREAD

**Issue by FunnyRyan** [10up/ElasticPress#2632]
**Describe your question**

Using wordpress search query exclusion method not working

E.g  https://www.mydomain.com/?s=keyword&cat=-20

it does't work~~~~~~~

**Comment by oscarssanchez** [comment]
Hi @FunnyRyan ,

This works for me. Can you make sure you are using the latest 4.0 release and can you confirm no code could be altering the request via pre_get_posts or perhaps some elasticpress customization ? You might want to confirm with a fresh WP installation.
