### ISSUE TITLE
QUESTION: How to search for parts of terms

### ISSUE THREAD

**Issue by arnowelzel** [10up/ElasticPress#2635]
**Describe your question**

When searching for a term, there are only hits if the term is entered completely.

Examples:

"next" will not find "nextcloud"
"port" will not find "portexpander"

And so on.

However the normal WordPress search has no problem finding text if you just enter part of a word.

Is there any way to change this behaviour? I did not find any setting for this.

**Comment by oscarssanchez** [comment]
Hi @arnowelzel ,

I just tested this with the latest release 4.0 and had no issues creating a post with title "nextcloud" and searching for "next".

As a first step, can you confirm you are on the latest release and you have performed reindexing and it was successful (meaning no errors in the logs)?

If this is correct, can you confirm there's no additional code that might be hooking into ElasticPress?

Finally, you might want to install `debug bar` and `debug bar elasticpress` and paste the output of `Query Body` and `Query Result`, this can help checking what is going on.

**Comment by arnowelzel** [comment]
Yes, I am using the latest version - I never haved used ElasticPress before, so I did a fresh install anyway.

Just to be sure I deleted the plugin, deleted the indexes in ElastiSearch and reinstalled everything. Now it seems to work. However, I did not change any setting at all this time in ElasticPress.

About Debug Bar - this plugin seems to be dead: https://wordpress.org/plugins/debug-bar/

Last update is 1 year ago and is only tested up to WordPress 5.5.9. At least I would exepect the compatibility information of the plugin updated if it is still maintained.

Also note that ElastiPress warned about using ElasticSearch 7.17 since only 7.10 is supported. However 7.17 is the current version and I can't (and won't) downgrade that since this is the current version provided by the Debian repository. Also see https://www.elastic.co/de/downloads/past-releases#elasticsearch

**Comment by arnowelzel** [comment]
Ok, now another problem shows up:

When using "next" it will find all kinds of posts - even ones which don't have "next" anywhere like this one:

https://arnowelzel.de/projekte/elektronik/hdsp-211x

But not if using "nextc". In this case only one post will be found:

https://arnowelzel.de/onlyoffice-mit-nextcloud

But others not, even tey also contain the word "Nextcloud":

https://arnowelzel.de/nextcloud-talk-mit-coturn-und-eigenem-signaling-server
https://arnowelzel.de/nextcloud-talk-high-performance-backend-jetzt-open-source

and so on.

Maybe ElasticSearch is meant to work this way - but this makes no sense for me. The simpler internal WordPress search has no problem finding fragments of words and it won't report https://arnowelzel.de/projekte/elektronik/hdsp-211x as a match for the search term "next".

Maybe it has to do with using ElasticSearch 7.17 - but since this is the current version of ElasticSearch 7 and I also use that for other applications as well, I can't change this.

Nice idea - but it seems for me ElasticPress is no option at the moment.

**Comment by felipeelia** [comment]
Hi @arnowelzel,

Search algorithms applied to Elasticsearch can have some nuances that probably should be adapted to your use case.

For example: although not perfectly, Elasticsearch will try to match misspelled words. So, using the examples you shared, searching for "next" would potentially match "text", a word that I can see several times in that post and that only contains one letter of difference. These fuzzy matches wouldn't work the same way for "nextc".

Partial matches require an [ngram analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenizer.html), so Elasticsearch knows it has to store each segment of each word as a potential search term. That comes with a performance penalty, so we only apply that to post titles when autosuggest is enabled (we don't recommend having that applied to post content, for example.)

Regarding Elasticsearch versions, all those things were introduced in older versions and should not be a problem. Regarding the compatible versions, I explained how we manage that in [this comment](https://github.com/10up/ElasticPress/issues/2671#issuecomment-1078972274).

If you ever want to give ElasticPress/Elasticsearch another try, I recommend you to:
1. Make sure you set the correct language in ElasticPress settings
2. If you want to disable fuzziness, add `add_filter( 'ep_match_fuzziness', '__return_zero' );` to your codebase
3. Enable autosuggest, so partial matches to titles will work

Thanks!

ps.: [Debug Bar](https://wordpress.org/plugins/debug-bar/) is a plugin maintained by the WordPress.org team and generally does not need updates -- we've contacted them about that anyway. For those with the same concern, [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) also works with [Query Monitor](https://wordpress.org/plugins/query-monitor/).
