### ISSUE TITLE
BUG: All WooCommerce Orders showing up under individual accounts after sync/update

### ISSUE THREAD

**Issue by tomburtless** [10up/ElasticPress#2657]
**Describe the bug**
Recently updated our ElasticPress to 4.0.0 and re-synced our data to find that when clicking on the Orders tab within the My Account section of WooCommerce all of the orders in the system (regardless of user) were showing up.  If I attempted to view any account's order that was not owned by me I would get invalidated but the listing of data was obviously inaccurate and very worrying.

**Steps to Reproduce**

1. Click on Features under Elastic Press
2. Click Allow Protected Content 
4. Re-sync the data
5. Go to My Account > Orders
6. See all orders in the system

**Expected behavior**
I expected that only the orders for my account would show up.

**Screenshots**
I cannot give screenshots yet as the data that was being shown is real, live data.

**Environment information**
Wordpress Version: 5.9.2

**Additional context**
If I disable the syncing of Protected Content, this issue goes away.  I'm hoping we can index and sync that data in our system though.

**Comment by brandwaffle** [comment]
@tomburtless thanks for submitting this report--we're taking a look right away.

**Comment by brandwaffle** [comment]
@tomburtless thanks again for submitting this issue. We've released EP 4.0.1 to address this bug and also are adding this scenario to our testing matrix.
