### ISSUE TITLE
QUESTION: Multiselect dropdown using ElasticPress Autosuggest feature.

### ISSUE THREAD

**Issue by aamir2007** [10up/ElasticPress#2661]
I want to implement multiselect dropdown using ElasticPress Autosuggest feature in Wordpress. I am building a custom form for front end ad posting. Please advice How can I use speed of ElasticPress autosuggest to populate dropdown of my Multiselect field with custom taxonomies like categories and tags. Is there any option, hook or filter for this purpose or will I have to do it all custom.
Note: I have already implemented Autosuggest on site that populate results from custom post type and is working alright.

Regars,
Aamir

**Comment by felipeelia** [comment]
Hi @aamir2007,
Unfortunately, most of it will need to be based on custom code. In general terms, you would need to enable the Terms feature, and do to a WP_Term_Query what autosuggest does with WP_Query.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation.
