### ISSUE TITLE
BUG:  WooCommerce - No Orders show up in My Account > Orders section

### ISSUE THREAD

**Issue by tomburtless** [10up/ElasticPress#2663]
**Describe the bug**
Hi - I put in the bug report yesterday that all WooCommerce orders were showing up in any individuals My Account > Orders section.  I updated to the newest version and ran a re-sync of the data on our staging environment and saw no orders in that section.

I tried it out on various account types and with various other plugins disabled and the root of the cause seems to be ElasticPress.

**Comment by felipeelia** [comment]
Thanks for the quick reply @tomburtless. Looking at the query, it should bring all orders that match:

- meta._customer_user is 10733 or 1;
- post IDs are not 119698, 119699, or 3225464
- post type is either shop_order or shop_order_refund
- post status is any of wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed

The strangest thing for me there is the list of post IDs is should not match. Can you compare that with the list of orders you were expecting to see?
If your order ID is not in that list, that probably means the order was not indexed. To test that, you can run:
`wp elasticpress index --indexables=post --include=<order_id> --show-errors`
If it tried to index the order, you will see `Processed posts 0 - 1 of 1. Last Object ID: <order_id>` in the output. If that doesn't show up, you might want to run `wp elasticpress list-features` to double-check which features ElasticPress is considering enabled.

Can you please check all that and get back to us with your findings? Thank you very much!

**Comment by tomburtless** [comment]
So I ran the index wp cli on an order that should show up in the My Account > Orders list:

Success: Indexing posts...
Skipping 0 posts...
Processed posts 0 - 1 of 1. Last Object ID: 119950
Success: Number of posts indexed: 1
Success: Sync complete
Total time elapsed: 0.090
Success: Done!


I refreshed My Account > Orders and I'm still not seeing any orders listed.  I listed out features: 


Active features:
search
related_posts
woocommerce
facets
searchordering
terms
protected_content
autosuggest

Everything is showing up as expected.  I've re-indexed our data 3 times over at this point and the orders are still not showing up.  

I've deactivated most plugins except for ElasticPress and WooCommerce and the orders are still not showing up.  There's no additional functionality in our main theme's functions.php file that would be changing any of this either.

**Comment by felipeelia** [comment]
Thanks for getting back to us again @tomburtless. So, can you now please run `wp elasticpress request '<posts_index_name>/_doc/119950'` and share the results with us? That will tell us what Elasticsearch has indexed for that order. You can find the real `<posts_index_name>` visiting the Health screen.

**Comment by felipeelia** [comment]
Hi @tomburtless, did you have the chance to run the command I suggested? Thanks!
