### ISSUE TITLE
QUESTION: ElasticPress works on ajax search but does not work on normal search

### ISSUE THREAD

**Issue by leomp3** [10up/ElasticPress#2668]
Hi,

I installed your excellent plugin on a self-hosted VPS.
The issue is the following: I could make it work on the ajax search, but it doesn’t work on the normal search, during 2 days I tried every fix that I found but unfortunately no solution worked in my case.

This creates a problem because, when the user on the ajax search, click on view all products or click the enter key, site shows a message that it didn’t found anything.

However, when I change my theme “Barberry” to the Wordpress theme “Twenty Seventeen” that has not ajax search, ElasticPress then works fine. I can’t understand what’s happening wrong.

Here are the ElasticPress Bar logs:

Barberry theme log with error code 400:

More	Start	Duration	Method	URL	Code
Toggle	620.7 ms	7.9 ms	POST	http://localhost:9200/mysiteeu-post-1/post/_search	400

`Array
(
    [url] => http://localhost:9200/mysiteeu-post-1/post/_search
    [args] => Array
        (
            [method] => POST
            [timeout] => 5
            [redirection] => 5
            [httpversion] => 1.0
            [user-agent] => WordPress/5.8.4; https://mysite.eu/en/
            [reject_unsafe_urls] => 
            [blocking] => 1
            [headers] => Array
                (
                    [Content-Type] => application/json
                )

            [cookies] => Array
                (
                )

            [body] => {"from":0,"size":72,"sort":[{"post_type":{"order":"desc"}}],"query":{"bool":{"should":[{"multi_match":{"query":"skuull","type":"phrase","fields":["post_title","post_excerpt","post_content"],"boost":3}},{"multi_match":{"query":"skuull","fields":["post_title","post_excerpt","post_content"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"skuull","type":"cross_fields","fields":["post_title","post_excerpt","post_content"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_cat.slug":["uncategorized","uncategorized-es","uncategorized-sv","uncategorized-nl","uncategorized-de","uncategorized-it","uncategorized-da","uncategorized-fr","family-friends","famille-et-amis","familie-og-venner","familie-en-vrienden","familie-freunde","famiglia-e-amici","familia-y-amigos","familj-vanner"]}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}},{"term":{"post_lang":"en"}}]}}}
            [compress] => 
            [decompress] => 1
            [sslverify] => 1
            [sslcertificates] => /home/mysite/public_html/wp-includes/certificates/ca-bundle.crt
            [stream] => 
            [filename] => 
            [limit_response_size] => 
            [time_start] => 1647820689.7217
            [_redirection] => 5
            [time_stop] => 1647820689.7296
            [duration] => 7.936954498291
        )

    [r] => Array
        (
            [headers] => Requests_Utility_CaseInsensitiveDictionary Object
                (
                    [data:protected] => Array
                        (
                            [content-type] => application/json; charset=UTF-8
                            [content-encoding] => gzip
                            [content-length] => 376
                        )

                )

            [body] => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [post_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"mysiteeu-post-1","node":"7_hfsLaXRh604sSBVtVuLw","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [post_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
            [response] => Array
                (
                    [code] => 400
                    [message] => Bad Request
                )

            [cookies] => Array
                (
                )

            [filename] => 
            [http_response] => WP_HTTP_Requests_Response Object
                (
                    [response:protected] => Requests_Response Object
                        (
                            [body] => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [post_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"mysiteeu-post-1","node":"7_hfsLaXRh604sSBVtVuLw","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [post_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
                            [raw] => HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-encoding: gzip
content-length: 376

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [post_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"mysiteeu-post-1","node":"7_hfsLaXRh604sSBVtVuLw","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [post_type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
                            [headers] => Requests_Response_Headers Object
                                (
                                    [data:protected] => Array
                                        (
                                            [content-type] => Array
                                                (
                                                    [0] => application/json; charset=UTF-8
                                                )

                                            [content-encoding] => Array
                                                (
                                                    [0] => gzip
                                                )

                                            [content-length] => Array
                                                (
                                                    [0] => 376
                                                )

                                        )

                                )

                            [status_code] => 400
                            [protocol_version] => 1.1
                            [success] => 
                            [redirects] => 0
                            [url] => http://localhost:9200/mysiteeu-post-1/post/_search
                            [history] => Array
                                (
                                )

                            [cookies] => Requests_Cookie_Jar Object
                                (
                                    [cookies:protected] => Array
                                        (
                                        )

                                )

                        )

                    [filename:protected] => 
                    [data] => 
                    [headers] => 
                    [status] => 
                )

        )

    [class] => Requests
    [stack_trace] => Array
        (
            [0] => Debug_Bar_WP_Http->after_http_request
            [1] => WP_Hook->apply_filters
            [2] => WP_Hook->do_action
            [3] => do_action('http_api_debug')
            [4] => WP_Http->request
            [5] => wp_remote_request
            [6] => ElasticPress\Elasticsearch->remote_request
            [7] => ElasticPress\Elasticsearch->query
            [8] => ElasticPress\Indexable->query_es
            [9] => ElasticPress\Indexable\Post\QueryIntegration->get_es_posts
            [10] => WP_Hook->apply_filters
            [11] => apply_filters_ref_array('posts_pre_query')
            [12] => WP_Query->get_posts
            [13] => WP_Query->query
            [14] => WP->query_posts
            [15] => WP->main
            [16] => wp
            [17] => require('wp-blog-header.php')
        )

)`

Barberry cURL copy with error code 400:

`curl -XPOST -H 'Content-Type: application/json' -d '{"from":0,"size":72,"sort":[{"post_type":{"order":"desc"}}],"query":{"bool":{"should":[{"multi_match":{"query":"skuull","type":"phrase","fields":["post_title","post_excerpt","post_content"],"boost":3}},{"multi_match":{"query":"skuull","fields":["post_title","post_excerpt","post_content"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"skuull","type":"cross_fields","fields":["post_title","post_excerpt","post_content"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_cat.slug":["uncategorized","uncategorized-es","uncategorized-sv","uncategorized-nl","uncategorized-de","uncategorized-it","uncategorized-da","uncategorized-fr","family-friends","famille-et-amis","familie-og-venner","familie-en-vrienden","familie-freunde","famiglia-e-amici","familia-y-amigos","familj-vanner"]}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}},{"term":{"post_lang":"en"}}]}}}' 'http://localhost:9200/mysiteeu-post-1/post/_search'`

Twenty Seventeen theme log with code 200 and working fine:

`Array
(
    [url] => http://localhost:9200/mysiteeu-post-1/post/_search
    [args] => Array
        (
            [method] => POST
            [timeout] => 5
            [redirection] => 5
            [httpversion] => 1.0
            [user-agent] => WordPress/5.8.4; https://mysite.eu/en/
            [reject_unsafe_urls] => 
            [blocking] => 1
            [headers] => Array
                (
                    [Content-Type] => application/json
                )

            [cookies] => Array
                (
                )

            [body] => {"from":0,"size":9,"sort":[{"_score":{"order":"desc"}}],"query":{"bool":{"should":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"skuull","type":"phrase","fields":["post_title^20","meta._sku.value^30","terms.product_cat.name^10","terms.product_tag.name^15"],"boost":3}},{"multi_match":{"query":"skuull","fields":["post_title^20","meta._sku.value^30","terms.product_cat.name^10","terms.product_tag.name^15"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"skuull","type":"cross_fields","fields":["post_title^1","meta._sku.value^1","terms.product_cat.name^1","terms.product_tag.name^1"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"product"}}]}}]}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}},{"term":{"post_lang":"en"}}]}}}
            [compress] => 
            [decompress] => 1
            [sslverify] => 1
            [sslcertificates] => /home/mysite/public_html/wp-includes/certificates/ca-bundle.crt
            [stream] => 
            [filename] => 
            [limit_response_size] => 
            [time_start] => 1647742436.6182
            [_redirection] => 5
            [time_stop] => 1647742436.6467
            [duration] => 28.55396270752
        )

    [r] => Array
        (
            [headers] => Requests_Utility_CaseInsensitiveDictionary Object
                (
                    [data:protected] => Array
                        (
                            [content-type] => application/json; charset=UTF-8
                            [content-encoding] => gzip
                            [content-length] => 13290
                        )

                )

            [body] => [omitted]
            [response] => Array
                (
                    [code] => 200
                    [message] => OK
                )

            [cookies] => Array
                (
                )

            [filename] => 
        )

    [class] => Requests
    [stack_trace] => Array
        (
            [0] => Debug_Bar_WP_Http->after_http_request
            [1] => WP_Hook->apply_filters
            [2] => WP_Hook->do_action
            [3] => do_action('http_api_debug')
            [4] => WP_Http->request
            [5] => wp_remote_request
            [6] => ElasticPress\Elasticsearch->remote_request
            [7] => ElasticPress\Elasticsearch->query
            [8] => ElasticPress\Indexable->query_es
            [9] => ElasticPress\Indexable\Post\QueryIntegration->get_es_posts
            [10] => WP_Hook->apply_filters
            [11] => apply_filters_ref_array('posts_pre_query')
            [12] => WP_Query->get_posts
            [13] => WP_Query->query
            [14] => WP->query_posts
            [15] => WP->main
            [16] => wp
            [17] => require('wp-blog-header.php')
        )

)`

I am really out of options. I tried disable all my child theme functions with no avail. I tried the CLI command wp elasticpress index --setup –show-bulk-errors but it works fine with no errors.

Many thanks for your help,
Leonardo

**Comment by felipeelia** [comment]
Hi @leomp3,

The first query is trying to order by post_type, which is not supported. (Note that the first query has
`"sort":[{"post_type":{"order":"desc"}}]` there and the working one has
`"sort":[{"_score":{"order":"desc"}}]`.)

You have two options: order by `_score` (which would order results based on Elasticsearch applied score) or order by `post_type.raw`, which is mapped as a keyword field and should work fine (although this is probably NOT what you want to order by.)

I'm going ahead and closing the issue out but feel free to leave any following up questions or comments.

**Comment by leomp3** [comment]
Hi felipeelia,

I am trying to change the sort order to _score trough these ElasticPress hooks, but none is working. The sort order doesn't change from post_type and I really can't find in the theme where this setting "sort by post_type" comes from. It's not explicit.

`add_filter( 'ep_set_sort', 'ep_sort_by_score', 10, 2 );

function ep_sort_by_score( $sort, $order ) {
  $sort = array(
    array(
      '_score' => array(
        'order' => $order,
      ),
    ),
  );
  return $sort;
}

add_filter( 'ep_set_default_sort', 'ep_sort_by_score_default', 10, 2 );

function ep_sort_by_score_default( $sort, $order ) {
  $sort = array(
    array(
      '_score' => array(
        'order' => $order,
      ),
    ),
  );
  return $sort;
}`

Can you tell me what I'm doing wrong?

Thanks for your help,
Leonardo

**Comment by leomp3** [comment]
I also tried this hook but with no avail.

`add_action( 'pre_get_posts', 'score_default_sort' );

function score_default_sort( $query ) {
global $pagenow;
  if ( is_search() || ( $pagenow == 'edit.php' ) ) {
    $query->set( 'orderby', '_score' );
    $query->set( 'order', 'DESC' );
  }
}`

**Comment by leomp3** [comment]
Hi @felipeelia,

Many thanks for your help. It worked very well for some time, the ajax and the normal search together, but then for no reason nothing works anymore, not even the ajax search. I reindexed everything, restarted elasticsearch. I'm going nuts!

My ElasticPress hooks in my functions file:

```
# BEG ElasticPress

# To make ElasticPress work
add_filter( 'ep_format_request_headers', function ( $headers ) {
  $headers[ 'Accept-Encoding' ] = 'gzip';
  return $headers;
} );

# To make ElasticPress search the SKU
function update_search_fields( array $fields, array $args ) {
  $fields[ 'meta._sku.value' ] = array(
    'type' => 'keyword',
  );
  return $fields;
}
add_filter( 'ep_search_fields', 'update_search_fields', 11, 2 );

# Enable ajax search
function ep_integrate_woocommerce_ajax_search( $is_integrated, $context ) {
  if ( 'search' === $context ) {
    return true;
  }
}
add_filter( 'ep_is_integrated_request', 'ep_integrate_woocommerce_ajax_search', 10, 2 );

# Define default sort order to _score
function score_default_sort( $query ) {
  if ( is_search() ) {
    $query->set( 'orderby', '_score' );
    $query->set( 'order', 'DESC' );
  }
}
add_action( 'pre_get_posts', 'score_default_sort', 10000 );

# Change operator 'and' by 'or' for search results
function set_to_exact( $formatted_args, $args ) {
  if ( !empty( $formatted_args[ 'query' ][ 'bool' ][ 'should' ] ) &&
    is_array( $formatted_args[ 'query' ][ 'bool' ][ 'should' ] )
  ) {
    foreach ( $formatted_args[ 'query' ][ 'bool' ][ 'should' ] as $key => $value ) {
      if ( !empty( $value[ 'multi_match' ][ 'fuzziness' ] ) &&
        'auto' === $value[ 'multi_match' ][ 'fuzziness' ]
      ) {
        $formatted_args[ 'query' ][ 'bool' ][ 'should' ][ $key ][ 'multi_match' ][ 'operator' ] = 'or';
      }
    }
  }
  return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );

# Remove all metadata not in the regex
add_filter( 'ep_prepare_meta_data', function ( $meta ) {
  foreach ( $meta as $key => $value ) {
    if ( !preg_match( '/^(post_title|product_cat|product_tag|_sku)$/', $key ) ) {
      unset( $meta[ $key ] );
    }
  }
  return $meta;
} );

# END ElasticPress
```

And this is the error 400 that I'm getting

```
Array
(
    [url] => http://localhost:9200/printfuneu-post-1/post/_search
    [args] => Array
        (
            [method] => POST
            [timeout] => 5
            [redirection] => 5
            [httpversion] => 1.0
            [user-agent] => WordPress/5.8.4; https://printfun.eu/en/
            [reject_unsafe_urls] => 
            [blocking] => 1
            [headers] => Array
                (
                    [Content-Type] => application/json
                    [Accept-Encoding] => gzip
                )

            [cookies] => Array
                (
                )

            [body] => {"from":0,"size":72,"sort":[{"_score":{"order":"desc"}}],"query":{"bool":{"should":[{"multi_match":{"query":"skuull","type":"phrase","fields":{"0":"post_title","1":"post_excerpt","2":"post_content","meta._sku.value":{"type":"keyword"}},"boost":3}},{"multi_match":{"query":"skuull","fields":{"0":"post_title","1":"post_excerpt","2":"post_content","meta._sku.value":{"type":"keyword"}},"boost":1,"fuzziness":"auto","operator":"or"}},{"multi_match":{"query":"skuull","type":"cross_fields","fields":{"0":"post_title","1":"post_excerpt","2":"post_content","meta._sku.value":{"type":"keyword"}},"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_cat.slug":["uncategorized","uncategorized-es","uncategorized-sv","uncategorized-nl","uncategorized-de","uncategorized-it","uncategorized-da","uncategorized-fr","family-friends","famille-et-amis","familie-og-venner","familie-en-vrienden","familie-freunde","famiglia-e-amici","familia-y-amigos","familj-vanner"]}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}},{"term":{"post_lang":"en"}}]}}}
            [compress] => 
            [decompress] => 1
            [sslverify] => 1
            [sslcertificates] => /home/printfun/public_html/wp-includes/certificates/ca-bundle.crt
            [stream] => 
            [filename] => 
            [limit_response_size] => 
            [time_start] => 1647892484.3112
            [_redirection] => 5
            [time_stop] => 1647892484.3179
            [duration] => 6.7040920257568
        )

    [r] => Array
        (
            [headers] => Requests_Utility_CaseInsensitiveDictionary Object
                (
                    [data:protected] => Array
                        (
                            [content-type] => application/json; charset=UTF-8
                            [content-encoding] => gzip
                            [content-length] => 148
                        )

                )

            [body] => {"error":{"root_cause":[{"type":"parsing_exception","reason":"[multi_match] query does not support [fields]","line":1,"col":143}],"type":"parsing_exception","reason":"[multi_match] query does not support [fields]","line":1,"col":143},"status":400}
            [response] => Array
                (
                    [code] => 400
                    [message] => Bad Request
                )

            [cookies] => Array
                (
                )

            [filename] => 
            [http_response] => WP_HTTP_Requests_Response Object
                (
                    [response:protected] => Requests_Response Object
                        (
                            [body] => {"error":{"root_cause":[{"type":"parsing_exception","reason":"[multi_match] query does not support [fields]","line":1,"col":143}],"type":"parsing_exception","reason":"[multi_match] query does not support [fields]","line":1,"col":143},"status":400}
                            [raw] => HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-encoding: gzip
content-length: 148

{"error":{"root_cause":[{"type":"parsing_exception","reason":"[multi_match] query does not support [fields]","line":1,"col":143}],"type":"parsing_exception","reason":"[multi_match] query does not support [fields]","line":1,"col":143},"status":400}
                            [headers] => Requests_Response_Headers Object
                                (
                                    [data:protected] => Array
                                        (
                                            [content-type] => Array
                                                (
                                                    [0] => application/json; charset=UTF-8
                                                )

                                            [content-encoding] => Array
                                                (
                                                    [0] => gzip
                                                )

                                            [content-length] => Array
                                                (
                                                    [0] => 148
                                                )

                                        )

                                )

                            [status_code] => 400
                            [protocol_version] => 1.1
                            [success] => 
                            [redirects] => 0
                            [url] => http://localhost:9200/printfuneu-post-1/post/_search
                            [history] => Array
                                (
                                )

                            [cookies] => Requests_Cookie_Jar Object
                                (
                                    [cookies:protected] => Array
                                        (
                                        )

                                )

                        )

                    [filename:protected] => 
                    [data] => 
                    [headers] => 
                    [status] => 
                )

        )

    [class] => Requests
    [stack_trace] => Array
        (
            [0] => Debug_Bar_WP_Http->after_http_request
            [1] => WP_Hook->apply_filters
            [2] => WP_Hook->do_action
            [3] => do_action('http_api_debug')
            [4] => WP_Http->request
            [5] => wp_remote_request
            [6] => ElasticPress\Elasticsearch->remote_request
            [7] => ElasticPress\Elasticsearch->query
            [8] => ElasticPress\Indexable->query_es
            [9] => ElasticPress\Indexable\Post\QueryIntegration->get_es_posts
            [10] => WP_Hook->apply_filters
            [11] => apply_filters_ref_array('posts_pre_query')
            [12] => WP_Query->get_posts
            [13] => WP_Query->query
            [14] => WP->query_posts
            [15] => WP->main
            [16] => wp
            [17] => require('wp-blog-header.php')
        )

)
```

cURL request

`curl -XPOST -H 'Content-Type: application/json' -H 'Accept-Encoding: gzip' -d '{"from":0,"size":72,"sort":[{"_score":{"order":"desc"}}],"query":{"bool":{"should":[{"multi_match":{"query":"skuull","type":"phrase","fields":{"0":"post_title","1":"post_excerpt","2":"post_content","meta._sku.value":{"type":"keyword"}},"boost":3}},{"multi_match":{"query":"skuull","fields":{"0":"post_title","1":"post_excerpt","2":"post_content","meta._sku.value":{"type":"keyword"}},"boost":1,"fuzziness":"auto","operator":"or"}},{"multi_match":{"query":"skuull","type":"cross_fields","fields":{"0":"post_title","1":"post_excerpt","2":"post_content","meta._sku.value":{"type":"keyword"}},"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_cat.slug":["uncategorized","uncategorized-es","uncategorized-sv","uncategorized-nl","uncategorized-de","uncategorized-it","uncategorized-da","uncategorized-fr","family-friends","famille-et-amis","familie-og-venner","familie-en-vrienden","familie-freunde","famiglia-e-amici","familia-y-amigos","familj-vanner"]}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}},{"term":{"post_lang":"en"}}]}}}' 'http://localhost:9200/printfuneu-post-1/post/_search'`

I'm sorry to bother you with all this, I'm usually very capable of fixing code issues, but I'm really lost here.

Thanks,
Leonardo

**Comment by felipeelia** [comment]
Hi @leomp3,

If you check the error, you'll see the reason is `"[multi_match] query does not support [fields]"`. Although not obvious, Elasticsearch expects `fields` to be an array, but the code you have in your `update_search_fields` function will make it become an object. Try this instead:
```
function update_search_fields( array $fields, array $args ) {
	$fields[] = 'meta._sku.value';
	return $fields;
}
add_filter( 'ep_search_fields', 'update_search_fields', 11, 2 );
```

Although we do our best to help as much as possible, debugging custom code is outside of the scope of what we do in this repository. If you’re interested in further assistance, we would be happy to help you! You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks

**Comment by leomp3** [comment]
Hi @felipeelia,

Wow! it worked immediately! :) I cannot thank you enough!

I completely understand and I would like to subscribe to a elasticpress.io package, and the consulting can be very helpful too, although we are starting our business right now, but as soon our business start growing it will make sense to subscribe. I can't imagine a serious ecommerce business without a proper search, otherwise the WordPress default search will be a conversion killer, and Elasticsearch seems to me the best technology with its high flexibility. It's like having a mini Google inside our site :)

Best regards and thanks again,
Leonardo

**Comment by leomp3** [comment]
Hi @felipeelia,

Unfortunately I had to disable ElasticPress on my site because for some very obscure reason when I have ElasticPress enabled my Italian language categories does not have any products, showing the message "Non è stato trovato nessun prodotto che corrisponde alla tua selezione." The ElasticPress debug bar doesn't show any errors either.

This happens without even running any ElasticPress especifique code on the functions.php file.

Regards,

**Comment by leomp3** [comment]
The issue happens even changing to other theme.
