### ISSUE TITLE
BUG: ElasticPress Facets Widgets not appearing/functioning

### ISSUE THREAD

**Issue by laurelstreng** [10up/ElasticPress#2674]
**Describe the bug**

- Using the latest version of ElasticPress with the latest version of WordPress core (or any version of core v5.8 and up that includes the new Widgets block editor), the ElasticPress Facet Widgets are not appearing or functioning as expected on the front-end of the site.
- There is a PHP Notice on the WordPress Appearance > Widgets page: ``Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.8.0.) in /code/web/wp/wp-includes/functions.php on line 5768``. This notice goes away once the ElasticPress plugin has been deactivated.
- I was able to downgrade to ElasticPress v3.6.6, while the PHP Notice is still appearing, the Widgets function as expected

**Steps to Reproduce**

1. Go to Appearance > Widgets
2. See error: `Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.8.0.) in /code/web/wp/wp-includes/functions.php on line 5768`
3. When using the ElasticPress Facet Widgets, I am able to add/save them in the Dashboard, however they do not load or function as expected on the front end of the site with the latest version 4+

**Expected behavior**

- ElasticPress Facet Widgets should load and function as expected

**Screenshots**

**Environment information**
 - WordPress version: 5.9.2
 - ElasticPress version: 4.0.0
 - Elasticsearch version: 7.11.2
 - Where do you host your Elasticsearch server? elastic.co
 - What ElasticPress features do you have currently active? Post Search, Facets, Custom Search Results, Related Posts, Terms
 

<details><summary>Site Health Info:</summary>
   ### wp-core ###
version: 5.9.2
  site_language: en_US
  user_language: en_US
  timezone: America/New_York
  permalink: /blog/%postname%/
  https_status: true
  multisite: false
  user_registration: 0
  blog_public: 1
  default_comment_status: closed
  environment_type: production
  user_count: 276
  dotorg_communication: true
  
  ### wp-paths-sizes ###
  
  wordpress_path: /code/web/wp
  wordpress_size: loading...
  uploads_path: /code/web/wp-content/uploads
  uploads_size: loading...
  themes_path: /code/web/wp-content/themes
  themes_size: loading...
  plugins_path: /code/web/wp-content/plugins
  plugins_size: loading...
  database_size: loading...
  total_size: loading...
  
  ### wp-dropins (1) ###
  
  object-cache.php: true
  
  ### wp-active-theme ###
  
  name: WDG Wordpress Theme (chemonics)
  version: 0.7.0
  author: The Web Development Group
  author_website: (undefined)
  parent_theme: none
  theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, html5, title-tag, menus, widgets, editor-style
  theme_path: /code/web/wp-content/themes/chemonics
  
  ### wp-themes-inactive (3) ###
  
  Twenty Twenty: version: 1.9, author: the WordPress team
  Twenty Twenty-One: version: 1.5, author: the WordPress team
  Twenty Twenty-Two: version: 1.1, author: the WordPress team
  
  ### wp-mu-plugins (2) ###
  
  Define ACF JSON Location: author: (undefined), version: (undefined)
  WP-CFM Customization: author: (undefined), version: (undefined)
  
  ### wp-plugins-active (34) ###
  
  ACF Content Analysis for Yoast SEO: version: 3.0.1, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast
  ACF to REST API: version: 3.3.3, author: Aires Gonçalves
  AddToAny Share Buttons: version: 1.8.4, author: AddToAny
  Advanced Custom Fields PRO: version: 5.12, author: Delicious Brains
  Better Click To Tweet: version: 5.10.1, author: Ben Meredith
  Broken Link Checker: version: 1.11.16, author: WPMU DEV
  Classic Editor: version: 1.6.2, author: WordPress Contributors
  Click To Tweet: version: 1.4, author: CoSchedule
  Display Environment Type: version: 1.3, author: Roy Tanck
  Disqus for WordPress: version: 3.0.22, author: Disqus
  Editorial Access Manager: version: 0.3.2, author: Taylor Lovett
  ElasticPress: version: 4.0.0, author: 10up (latest version: 4.0.1)
  Export All URLs: version: 4.3, author: Atlas Gondal
  External Header Footer: version: 1.0.1, author: Sully Syed
  FacetWP: version: 3.9.5, author: FacetWP, LLC (latest version: 3.9.6)
  Getty Images: version: 4.0.13, author: gettyImages
  Gravity Forms: version: 2.5.16, author: Gravity Forms
  Jarvis: version: 1.0.6, author: The Web Development Group, David Everett, Joan Piedra, Kurtis Shaner, Doug Axelrod
  My Eyes Are Up Here: version: 1.1.10, author: interconnect/it
  Native PHP Sessions for WordPress: version: 1.2.4, author: Pantheon
  Pantheon Advanced Page Cache: version: 1.0.0, author: Pantheon
  Pantheon HUD: version: 0.3.1, author: Pantheon
  PublishPress Future: version: 2.7.3, author: PublishPress
  Reading Time WP: version: 2.0.10, author: Jason Yingling
  Redirection: version: 5.2.3, author: John Godley
  Safe SVG: version: 1.9.10, author: 10up
  Simple Post Expiration: version: 1.0.1, author: Pippin Williamson
  Thumbs Rating: version: 4.1.0, author: Ricard Torres
  Update Weight Metadata por Persons: version: 1.0, author: Agileana
  WebP Express: version: 0.25.0, author: Bjørn Rosell
  Wordfence Security: version: 7.5.8, author: Wordfence (latest version: 7.5.9)
  WP-CFM: version: 1.7.4, author: Forum One
  WP Redis: version: 1.2.0, author: Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive
  Yoast SEO: version: 18.3, author: Team Yoast (latest version: 18.4.1)
  
  ### wp-media ###
  
  image_editor: WP_Image_Editor_Imagick
  imagick_module_version: 1690
  imagemagick_version: ImageMagick 6.9.10-86 Q16 x86_64 2020-01-13 https://imagemagick.org
  imagick_version: 3.5.1
  file_uploads: File uploads is turned off
  post_max_size: 100M
  upload_max_filesize: 100M
  max_effective_size: 100 MB
  max_file_uploads: 20
  imagick_limits: 
	  imagick::RESOURCETYPE_AREA: 126 GB
	  imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	  imagick::RESOURCETYPE_FILE: 24576
	  imagick::RESOURCETYPE_MAP: 126 GB
	  imagick::RESOURCETYPE_MEMORY: 63 GB
	  imagick::RESOURCETYPE_THREAD: 1
  imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
  gd_version: bundled (2.1.0 compatible)
  gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
  ghostscript_version: 9.27
  
  ### wp-server ###
  
  server_architecture: Linux 5.10.90+ x86_64
  httpd_software: nginx/1.16.1
  php_version: 7.4.27 64bit
  php_sapi: fpm-fcgi
  max_input_variables: 10000
  time_limit: 0
  memory_limit: 512M
  max_input_time: 900
  upload_max_filesize: 100M
  php_post_max_size: 100M
  curl_version: 7.61.1 OpenSSL/1.1.1k
  suhosin: false
  imagick_availability: true
  pretty_permalinks: true
  
  ### wp-database ###
  
  extension: mysqli
  server_version: 10.0.23-MariaDB-log
  client_version: mysqlnd 7.4.27
  max_allowed_packet: 67108864
  max_connections: 1024
  
  ### wp-constants ###
  
  WP_HOME: https://chemonics.com
  WP_SITEURL: https://chemonics.com/wp
  WP_CONTENT_DIR: /code/web/wp-content
  WP_PLUGIN_DIR: /code/web/wp-content/plugins
  WP_MEMORY_LIMIT: 40M
  WP_MAX_MEMORY_LIMIT: 512M
  WP_DEBUG: false
  WP_DEBUG_DISPLAY: false
  WP_DEBUG_LOG: /code/web/wp-content/uploads/debug.log
  SCRIPT_DEBUG: false
  WP_CACHE: false
  CONCATENATE_SCRIPTS: undefined
  COMPRESS_SCRIPTS: undefined
  COMPRESS_CSS: undefined
  WP_ENVIRONMENT_TYPE: production
  DB_CHARSET: utf8
  DB_COLLATE: undefined
  
  ### wp-filesystem ###
  
  wordpress: not writable
  wp-content: not writable
  uploads: writable
  plugins: not writable
  themes: not writable
  mu-plugins: not writable
   </details>

**Additional context**

**Comment by felipeelia** [comment]
Hi @laurelstreng, thanks for opening the issue. When you say "they do not load or function as expected on the front end", do they display any error (either in Developer Tools' Console or in the server error logs)?

**Comment by laurelstreng** [comment]
Hey @felipeelia 👋🏻  When I am using the ElasticPress Facet Widget(s) I'm running into the following:
- No errors in Dev Tools Console
- Not seeing any errors in the logs (it is hosted with Pantheon)
- The only errors/notices I found was the one: `Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.8.0.) in /code/web/wp/wp-includes/functions.php on line 5768`

**Comment by laurelstreng** [comment]
@felipeelia I found the 10up debug bar plugin and will try installing that to see if I can find any additional information 👍🏻 

https://github.com/10up/debug-bar-elasticpress

**Comment by felipeelia** [comment]
Hey @laurelstreng, thanks for getting back to us. The only reference we have to `wp-editor` is actually made by the Related Posts widget, not by the Facets one, so I'd doubt that is the main cause of the problem.

The Debug Bar ElasticPress problem will tell you if you have any problems in an Elasticsearch query, so let me know if that is the case or if you don't see any query being fired at all. Thanks!
