### ISSUE TITLE
Does OpenSearch work with ElasticPress?

### ISSUE THREAD

**Issue by nickchomey** [10up/ElasticPress#2675]
I see that ElasticPress supports up to version 7.10.2. Does this mean that it allows for us to connect to an OpenSearch server, which was forked from ElasticPress 7.10.2?

**Comment by felipeelia** [comment]
Hey @nickchomey! Just to keep the information in one place, I've answered your question [here](https://github.com/10up/ElasticPress/issues/2671#issuecomment-1078972274). Thanks!

**Comment by nickchomey** [comment]
For anyone else who stumbles here, I just watched this video that did an excellent job of putting things into perspective about ElasticSearch vs Amazon OpenSearch. https://www.youtube.com/watch?v=F1oKcMefb0A

My concerns about elastic seem to have been unfounded and I'm happy to use it going forward. Moreover, they have a massive focus on actual community (conferences, youtube channel, meetups, etc..). They're an organization that I'd like to align myself with, as opposed to Amazon..
