### ISSUE TITLE
BUG: Learn More link on the Sync page doesn't go anywhere

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#2693]
**Describe the bug**
The "Learn More" link on the Sync page, beneath the button, is missing a URL and doesn't go anywhere.

**Steps to Reproduce**

1. Visit the Sync page.
2. Click on 'Learn More'.

**Expected behavior**
It should open a link of some kind, or open a panel with more information.

**Comment by felipeelia** [comment]
A draft for that new page is being created [here](https://elasticpress.zendesk.com/knowledge/articles/5205632443533/en-us?brand_id=360004525512).

**Comment by brandwaffle** [comment]
https://elasticpress.zendesk.com/hc/en-us/articles/5205632443533 published
