### ISSUE TITLE
BUG: Query Loop Block does not order by score in FSE

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2694]
**Describe the bug**

While using the new Twenty Twenty-Two theme, search results will always be ordered by date, instead of by Elasticsearch score.

**Comment by felipeelia** [comment]
Issue opened in Gutenberg: https://github.com/WordPress/gutenberg/issues/39285

**Comment by felipeelia** [comment]
@oscarssanchez do you mind checking if this is still a problem?

**Comment by oscarssanchez** [comment]
@felipeelia couldn't reproduce doing this:

1.- Create a post with title "test"
2.- Create a post with unrelated title and content "test"
3.- Using Twenty Twenty-Two theme search for "test"
4.- The post with title test comes first

**Comment by felipeelia** [comment]
@oscarssanchez does it come first even when the post "test" has an old date?

**Comment by oscarssanchez** [comment]
@felipeelia yes, I tested manually changing the date to a day before creation and it still did show up
