### ISSUE TITLE
BUG: Hide last sync element info box if there's no info to display

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#2695]
**Describe the bug**

When you don't have info to display, the box is still shown:

<img width="2391" alt="Screen Shot 2022-03-31 at 12 17 53" src="https://user-images.githubusercontent.com/31049169/161144064-b5cc0218-365f-4d2c-8da7-29fec333ac16.png">

**Steps to Reproduce**

1. Fresh install of EP
2. Go to sync page
3. See box empty

**Expected behavior**

The box should not be shown.

**Comment by felipeelia** [comment]
We could go a bit further here and check if the needed indices already exist. If they don't, the "Full Sync" would need to be the only option available.
