### ISSUE TITLE
[SOLVED] How to set "split_on_numerics" to false? (for proper SKU search in WooCommerce)

### ISSUE THREAD

**Issue by pedlima** [10up/ElasticPress#2696]
I searched everywhere and couldn't find it.

Where can this be changed?

My SKUs have numbers and letters (not all, though) and it's not delivering the expected results because sometimes the searched SKU doesn't even appear in first - actually what I would want would be for the search to get me directly to that product page, but unfortunately I've already tried a lot of things and it only works if I turn off ElasticPress, never with EP activated).

**Comment by oscarssanchez** [comment]
Hi @pedlima ,

You can use the `ep_formatted_args` filter to modify the formatted array before it gets converted to JSON, you might also want to try to look for exact matches if you detect a special pattern/is shop page, or give SKU's more weight. The functionality you describe that takes you to the product page feels more like something you'll need to custom code.

**Comment by pedlima** [comment]
> Hi @pedlima ,
> 
> You can use the `ep_formatted_args` filter to modify the formatted array before it gets converted to JSON, you might also want to try to look for exact matches if you detect a special pattern/is shop page, or give SKU's more weight. The functionality you describe that takes you to the product page feels more like something you'll need to custom code.

Thank you for your answer but how can I use that filter to apply "split_on_numerics"? I can't find any examples and documentation is not that good.

**Comment by oscarssanchez** [comment]
Apologies @pedlima , It seems `split_on_numerics` is actually a parameter to set in the mapping, for this you might want to try `ep_config_mapping`. Examples can be found in the synonyms feature: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Synonyms.php#L355 

Best,

**Comment by pedlima** [comment]
> 

Thank you for your quick answer, but I still have no idea how to use this to implement what I want! :(

I only see examples for synonyms and that's nothing what I am looking for...

**Comment by pedlima** [comment]
[oscarssanchez](https://github.com/oscarssanchez) Ok, so I tried this and it doesn't seem to be working, can you please help me out?

```
function configMapping($mapping){
    // bail early if $mapping is missing or not array
    if ( ! isset( $mapping ) || ! is_array( $mapping ) ) {
        return false;
    }

    // ensure we have filters and is array
    if (! isset( $mapping['settings']['analysis']['filter'] )
        || ! is_array( $mapping['settings']['analysis']['filter'] )) {
        return false;
    }

    // ensure we have analyzers and is array
    if (! isset( $mapping['settings']['analysis']['analyzer']['default']['filter'] )
        || ! is_array( $mapping['settings']['analysis']['analyzer']['default']['filter'] )) {
        return false;
    }

    // define the custom filter
    $mapping['settings']['analysis']['filter']['my_custom_word_delimiter_filter'] = array(
        'type'                  => 'word_delimiter',
        'split_on_case_change'  => false,
        'split_on_numerics'     => false
    );

    // tell the analyzer to use our newly created filter
    $mapping['settings']['analysis']['analyzer']['default']['filter'][] = 'my_custom_word_delimiter_filter';
    return $mapping;
}
add_filter('ep_config_mapping', 'configMapping', 10, 1);
```

**Comment by pedlima** [comment]
@oscarssanchez Could you please give me a hand here? It will be much appreciated. :)

**Comment by pedlima** [comment]
@oscarssanchez I'm sorry to insist, but I would really appreciate some help with this. If you want, I can open a new issue, but I think it makes no sense. Thank you very much in advance!

**Comment by felipeelia** [comment]
Hi @pedlima! Although we strive to help ElasticPress users in our GitHub issues, our main purpose here is to identify potential enhancements or bugs in the plugin and plan their development accordingly.
That said, looking at the code you wrote that should've worked but a more detailed scope and investigation of your codebase would be needed to go further. That would be something outside of our scope here and we would handle it via a consultation. If you are interested in that, please access https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment, we definitely will be happy to help you.
Thanks!

**Comment by pedlima** [comment]
This one was tough, but here is the solution for this!

First, you will need to use SSH to access the server where you have ElasticSearch installed.

After that, you will want to perform these commands:

- This one will first close your index, only then you can perform changes:
`curl -X POST http://localhost:9200/YOUR-INDEX/_close?pretty`

- This one will put the filter for "word_delimiter":
```
curl -X PUT "localhost:9200/YOUR-INDEX/_settings?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "tokenizer": "keyword",
          "filter": [ "word_delimiter" ]
        }
      }
    }
  }
}'
```

- Then we put the filters we want, like so:
```
curl -X PUT "localhost:9200/aYOUR-INDEX/_settings?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "tokenizer": "keyword",
          "filter": [ "my_custom_word_delimiter_filter" ]
        }
      },
      "filter": {
        "my_custom_word_delimiter_filter": {
          "type": "word_delimiter",
          "type_table": [ "- => ALPHA" ],
          "split_on_case_change": false,
          "split_on_numerics": false,
          "stem_english_possessive": true
        }
      }
    }
  }
}'
```

- Last but not least, you will want to open your index again, so here we go:
`curl -X POST http://localhost:9200/YOUR-INDEX/_open?pretty`

I had to perform all these steps because my index was already created, otherwise it would be basically like we see on the example page here: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-word-delimiter-tokenfilter.html

**Comment by felipeelia** [comment]
Thanks @pedlima. For future reference, the close/update/open mechanism is available in the plugin via the [`Elasticseach\update_index_settings()`](https://github.com/10up/ElasticPress/blob/4.1.0/includes/classes/Elasticsearch.php#L904) method. An example of usage is available in [`Synonyms\update_synonyms()`](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Synonyms.php#L456).

**Comment by pedlima** [comment]
@felipeelia awesome, didn't knew about it. Thanks! :)
