### ISSUE TITLE
BUG: Installation Workflow and initial sync

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2706]
**Describe the bug**

There are actually two:

- [x] During the installation process, if the user does not select any feature during step 3, the "Save Feature" button only reloads the page. 
- [x] During the initial sync (the one automatically made after clicking on the step 4 button), the screen won't be properly set as done, i.e., make the progress bar green and hide the pause/stop buttons. (There is a chance this is fixed by #2704)

**Additional context**

This can be reproduced in an easier way using code from #2705.

**Credits**

Props @jakemgold.

**Comment by brandwaffle** [comment]
@tlovett1 are you thinking if someone checks none of the boxes we should warn them that nothing will be active and then move past install, or should we be indicating we're requiring they check at least one box?

**Comment by JakePT** [comment]
@felipeelia As discussed with @brandwaffle we will address the first point by displaying a standard browser alert that reads:

>It looks like you’re trying to use ElasticPress’s advanced features only. If you’d like to activate basic search, please select Cancel and activate the Post Search Feature. Otherwise, please click Ok to configure advanced features.

And continuing will proceed to the Features page without starting a sync.
