### ISSUE TITLE
Indexed number not reflected in ElasticSearch

### ISSUE THREAD

**Issue by Stayallive** [10up/ElasticPress#271]
Hey,

I am working with this plugin now for a few weeks, with pleasure... however I just realised a problem.

When indexing our pretty large posts table we notice a big inconsistency.
```Indexed 13950/38034 entries. . .```

While ElasticSearch says:
```
"docs": {
    "num_docs": 7978,
    "max_doc": 7978,
    "deleted_docs": 0
},
```

The number 38034 should be correct by our own calculations, this is the number of articles with published status which should end up in ElasticSearch. But it looks like only 6 out of 10 articles are making it into the index.

Is this a known issue or has this come up in the past?

I am going to debug this soon so if you have some pointers on how to tackle that please do let me know!

**Comment by tlovett1** [comment]
@Stayallive any update on this?

**Comment by Stayallive** [comment]
@tlovett1, I am seeing lot's of `MapperParsingException[failed to parse]; nested: StackOverflowError;` no clue yet from what :)

**Comment by Stayallive** [comment]
Okay walk of shame here... I messed something up while rewriting our custom categories to actual categories... causing above mentioned errors... 😨
