### ISSUE TITLE
QUESTION: Can't search posts by author

### ISSUE THREAD

**Issue by bitobeats** [10up/ElasticPress#2714]
I have elasticpress installed and working on a client's website for months now. Thanks for the awesome plugin!

Today I needed to include authors as a field to be searched when a user uses the search form.
I tried activating it in "Manage Search Fields & Weighting" panel and then resynced the plugin by clicking the "two arrows in a circle" icon.

Still, it doesn't work. Can someone help, please?

**Comment by oscarssanchez** [comment]
Hi @vitorrloureiro ,

Can you please

1.- Try without any custom code you could be injecting? (third party plugins, custom theme etc preferably with a theme like twentytwenty) and if the issue persists
2.- Install debug bar and debug bar elasticpress plugins, then provide the query body relevant to the query you have problems with?

This should shed some light how the query is being formatted. For me the fields seem to be correct with a standard installation:

  ```
                                                      "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "post_author.display_name^1",
                                                            "terms.post_tag.name^1",
                                                            "terms.category.name^1",
                                                            "terms.ep_custom_result.name^9999"
                                                        ],
```

Thanks!
