### ISSUE TITLE
BUG: find_related() not limiting

### ISSUE THREAD

**Issue by altendorfme** [10up/ElasticPress#2715]
In version 4.1.0 when using: `ElasticPress\Features::factory()->get_registered_feature( 'related_posts' )->find_related( $postID, 4 );`, the defined limit is not being respected, it is always showing the default of 5 posts.

**Environment information**
 - WordPress version: 5.9.3
 - ElasticPress version: 4.1.0
 - Elasticsearch version: 7.2.0
 - Where do you host your Elasticsearch server? Bonsai.io

**Comment by felipeelia** [comment]
Thanks for opening the issue, @altendorfme!

So, it seems [this line](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/RelatedPosts/RelatedPosts.php#L151) should be
```
$query = $this->get_related_query( $post_id, $return );
```

While we don't release a version fixing that, the [ep_find_related_args](https://github.com/10up/ElasticPress/blob/f801fe2f4bba2f4f9252755f9def4a54a2e8aa27/includes/classes/Feature/RelatedPosts/RelatedPosts.php#L136) filter can be used. Something like the following code should be enough:
```
add_filter(
    'ep_find_related_args',
    function ( $args ) {
        $args['posts_per_page'] = 4;
        return $args;
    }
);
```

**Comment by altendorfme** [comment]
Hi @[felipeelia](https://github.com/felipeelia), fix worked perfectly ;)
