### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by HypeAU** [10up/ElasticPress#2716]
hi

How would I only retrieve last 6 months of related posts using this method?

	$related_posts=	ElasticPress\Features::factory()->get_registered_feature( 'related_posts' )->find_related(get_the_ID(), $return = 5 );
 

thnx
Bill

**Comment by oscarssanchez** [comment]
Hi @HypeAU  You could probably use the `ep_find_related_args` filter

and add a date query similar to this to the args:

```
			'date_query' => array(
				array(
					'after'   => '-6 month',
				),
			)
```

**Comment by HypeAU** [comment]
Hi Oscar, thanks for your assistance.
I'm new to Elasticpress and find it a little confusing at times, so thanks again for your patience.
I get a critical error when I run the below code 
[https://findcheap.com.au/coloured-jumbo-braiding-hair-extensions-braids-twist-hight-temperature-kanekalon/](https://findcheap.com.au/coloured-jumbo-braiding-hair-extensions-braids-twist-hight-temperature-kanekalon/
) what am I doing wrong? thnx



function related_single_page( $formatted_args, $args ) {
if ( is_single(202514) && 'post' == get_post_type() ) { // testpage
 echo "---";
    $formatted_args['query']['date_query']['after'] = '-2 month';
}
return $formatted_args; 
}
add_filter( 'ep_find_related_args', 'related_single_page', 10, 2 );

**Comment by felipeelia** [comment]
Hi @HypeAU,

If you look at [ep_find_related_args](http://10up.github.io/ElasticPress/ep_find_related_args.html) documentation, you'll see that it actually filters the WP_Query args, not the Elasticsearch query. So your code should probably look like this:
```
function related_single_page( $args ) {
	if ( is_single( 202514 ) && 'post' == get_post_type() ) { // testpage
		echo '---';
		$args['date_query'] = array(
			array(
				'after' => '-2 month',
			),
		);
	}
	return $args;
}
add_filter( 'ep_find_related_args', 'related_single_page' );
```

I'm going ahead and closing the ticket now but if you try that and it doesn't work, feel free to come back here with any error code you receive or any additional info that may be helpful to debug the problem. Thanks!

**Comment by HypeAU** [comment]
That worked. Thank you so much.

woow,  I didn't realise this
> you'll see that it actually filters the WP_Query args, not the Elasticsearch query. 

To make an even better product, if you include examples just like the one you provided above on eg these pages
http://10up.github.io/ElasticPress/ep_find_related_args.html
just like WP does with their documentation that would be amazing
