### ISSUE TITLE
Indexing new items

### ISSUE THREAD

**Issue by blenkhn** [10up/ElasticPress#2717]
**Is your enhancement related to a problem? Please describe.**
The problem is that when I add anything new.  Whether it be a product, order, user etc. it is not findable right away. 

**Describe the solution you'd like**
I would like to be able to find the new items right away products especially.  Having them searchable on the front and back end is important.

**Designs**
Not required, it is all there already

**Describe alternatives you've considered**
possibly a button that will index just the new items since the last index.

**Comment by felipeelia** [comment]
Hi @blenkhn,

Out of the box, ElasticPress already indexes all the new content, i.e., all products, orders, etc. created using WordPress core functionality will be indexed by default.

Are you seeing specific errors or isn't this functionality working in general? If so, did you already try to [set WordPress to log errors](https://wordpress.org/support/article/debugging-in-wordpress/) and then give a look at what is recorded?

**Comment by blenkhn** [comment]
The new products are not showing up right away in the searches.  Do you think that mysql might be caching the results and not updating right away?

**Comment by felipeelia** [comment]
Hi @blenkhn,

I don't think MySQL would be caching it (and ElasticPress wouldn't use that cache anyway) but you could be accidentally caching it with a plugin or your CDN (like Cloudflare) depending on how you have it set up.

Do you have any examples (with URLs) of the problem you are seeing?

**Comment by blenkhn** [comment]
I will look and see if there is a caching system like nginx working in the system.  I think I turned it off though.  After reindexing elasticpress it still happens right away and doesn't seem to take effect till the next day which now suggests a server cache to make it faster to deliver pages

**Comment by felipeelia** [comment]
Got it, @blenkhn. I'll close the issue for now but if you find something different please let us know and we can reopen it if needed.
