### ISSUE TITLE
--network-wide commands stop after 100 sites

### ISSUE THREAD

**Issue by foofy** [10up/ElasticPress#272]
The index, put-mapping, and delete-index commands, when used with the --network-wide flag, stop working after 100 sites. This is because EP_API::get_sites() uses wp_get_sites() which only returns 100 sites by default:

https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1063

**Comment by AaronHolbrook** [comment]
Nice catch @foofy

**Comment by tlovett1** [comment]
I think we just need to document this. Thoughts?

**Comment by AaronHolbrook** [comment]
I think this should be documented and a filter added for the arguments array that is used to call `wp_get_sites()`.

https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1088

Right now you could filter it yourself and return it, but it's redundant and wasteful. A filter would be a good fix.

**Comment by AaronHolbrook** [comment]
cc @GhostToast
