### ISSUE TITLE
After Upgrading to version 4 search function completely times and no longer functions

### ISSUE THREAD

**Issue by HypeAU** [10up/ElasticPress#2723]
Hi
I upgraded my live site from version 3 to 4, reindexed all data and search failed to function at all. 
I'll need to work on my staging area.

just wondering if theres any changes we need to make, when upgrading from version 3 to 4.

thanks

**Comment by felipeelia** [comment]
Hi @HypeAU,

Do you get any errors in your logs? When you install the [debug plugins](http://10up.github.io/ElasticPress/tutorial-debugging.html), do you see any queries being sent? How is your sync screen looking right now?
