### ISSUE TITLE
BUG: Type error in console when searching

### ISSUE THREAD

**Issue by MarijnvSprundel** [10up/ElasticPress#2725]
**Describe the bug**
When you have autosuggest enabled and press enter to search for something, a type error briefly appears before being redirected to the results page.

**Steps to Reproduce**

1. Go to a site with an elastic press search engine with autosuggest working.
2. Put something random in the search bar.
3. Without using your arrow keys, press enter.

**Expected behavior**
A type error briefly appearing in the console. For me it just said: 'uncaught' but in another environment it gave Uncaught TypeError: n[o] is undefined

**Additional context**
The solution to this problem is in autosuggest.js between line 480 and 481:

`case 13: // Enter`
`  if (results[currentIndex].classList.contains('selected')) {`

add this:

`if(typeof currentIndex === 'undefined')break;`

**Comment by felipeelia** [comment]
Thanks, @MarijnvSprundel, I'm able to reproduce the problem here as well. Do you want to craft a PR with the suggested solution?
