### ISSUE TITLE
QUESTION: Since _order_key populates post_password, is excluding order contents intentional?

### ISSUE THREAD

**Issue by ecaron** [10up/ElasticPress#2726]
In WooCommerce, the `wc_generate_order_key` value gets stored in the `post_password` field ([reference code is here](https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php#L76)).

This causes, when indexing orders, the `ep_post_sync_args` filter to call `remove_fields_from_password_protected` - causing the system to not index the actual content of the order.

While a workaround would be adding the `ep_pc_skip_post_content_cleanup` filter, here's my question: **Is this intended behavior, that orders with an `_order_key` in their meta should be excluded from the admin searchable index, or should I submit a bug?**

**Comment by felipeelia** [comment]
Hi @ecaron, thank you very much for the heads up! I've created #2728 to address this problem. Do you think you'd have a chance to give it a try and let us know if that fixes the problem for you as well? Thanks!

**Comment by ecaron** [comment]
@felipeelia I was able to download the modified files, remove my add_filter, and re-index the database. I can confirm that this fixes the problem. Great work!
