### ISSUE TITLE
Synced content via CLI but when we publish new contents those are not crawling on multisite setup

### ISSUE THREAD

**Issue by balajidamodare** [10up/ElasticPress#2730]
**Describe your question**

I have synced the required contents on the ES instance through a plugin on a multisite setup. is there I need to take care of when the plugin using on a multisite setup?
It was working perfectly fine on a single-site setup

bellow are the details

ES self-hosted version: 7.10.2
ElasticPress version: 4.1.0
PHP Version: 7.4.28
Worpress Version: 5.9.2

**Comment by oscarssanchez** [comment]
Hi @balajidamodare ,

When you say you have  _synced the required contents on the ES instance through a plugin_ do you refer with the help of another plugin that is not ElasticPress?

In this multisite setup, have you made sure the index site toggle is checked for the sites you want to index?

**Comment by balajidamodare** [comment]
Hi, Oscar Sanchez S.
I am using the ElasticPress plugin only.
synced the required contents means the half of the content I have synced using wp CLI commands
for eg : wp elasticpress index --network-wide --show-bulk-errors --post-type="videos, news, articles"

the post type I have specified here and synced those ones 
so any specific settings to sync newly created posts automatically for multisite? I checked for a single-site setup and it was synced automatically but not synced for multisite.

**Comment by balajidamodare** [comment]
Hi, Oscar Sanchez S.
I have another question.
does ElasticPress supports the AWS [OpenSearch](https://opensearch.org/) ?

**Comment by felipeelia** [comment]
Hi @balajidamodare,

Any new posts should be automatically created for either single-site or multisite. Do you have a concrete example you could share?

Regarding Opensearch, the short answer is yes. More info can be seen here: https://github.com/10up/ElasticPress/issues/2671#issuecomment-1078972274
