### ISSUE TITLE
Refine the Settings Config Screen

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2739]
**Is your enhancement related to a problem? Please describe.**

There is some room for improvement on the Settings screen:
- For EP.io clients, `Subscription ID` and `Subscription Username` will always be the same
- Alignments, in general, seem a little off

**Describe the solution you'd like**
In addition to the points above, the screen should probably receive a holistic review from a UX engineer.

**Designs**
To be created.

**Comment by nickolas-kola** [comment]
UX deliverable created, please refer to internal channels.
