### ISSUE TITLE
QUESTION: How do I tweak the way the results are displayed when using the facet widget?

### ISSUE THREAD

**Issue by gillespieza** [10up/ElasticPress#2741]
I have a custom template to display my products in their categories (it pulls in a little more info than just the featured post and title). But when I use the facet widget to filter by a facet, the resulting page does not have my customisations. What hooks or filters do I need to look at using?

**Comment by felipeelia** [comment]
Hi @gillespieza, would it be possible to share the URLs and what kind of customization you are talking about?

**Comment by gillespieza** [comment]
Hi @felipeelia [felipeelia](https://github.com/felipeelia)

Here you go: https://gearysgarage.com/product-category/agricultural-equipment/tractors-loaders/
And you'll find the filters in the sidebar to the right

**Comment by felipeelia** [comment]
Got it @gillespieza. Would it be possible for you to share that custom template you are using?
