### ISSUE TITLE
QUESTION: Zero Results for queries without spaces.

### ISSUE THREAD

**Issue by glamble007** [10up/ElasticPress#2743]
We have users searching on our woocommerce store phrases like:
Almondmilk
Oatmilk
sugarfree
glutenfree

We do sell these products, however the words appear separated in the product titles as follows:
Almond Milk
Oat Milk
Gluten-Free
Sugar Free

We are trying to solve this using synonyms, however it does not seem to be a long term solution. Do you have any suggestions?

**Describe your question**

**Comment by felipeelia** [comment]
You can try one of the older search algorithms @glamble007. To change it you can either use a WP-CLI command (`wp elasticpress set-algorithm-version --version=3.4` or `wp elasticpress set-algorithm-version --version=3.5`) or you can install the [ElasticPressLabs plugin](https://github.com/10up/ElasticPressLabs/) to change it via Dashboard.
