### ISSUE TITLE
BUG: compare_mappings() never gets called

### ISSUE THREAD

**Issue by nickchomey** [10up/ElasticPress#2746]
This issue has been edited from the original. I discovered that I was mostly wrong, but there still remains an issue. 

It appears that compare_mappings() in wp-content/plugins/elasticpress/includes/classes/Indexable.php doesn't ever seem to be called/referred-to in the plugin. I don't know what it is really supposed to do, but I don't think it is able to do anything as-is.

I hope this helps.

**Comment by felipeelia** [comment]
Thanks, @nickchomey. During the 3.6.x releases, we put together some mechanisms to check mapping versions and compare them with what is present in the Elasticsearch server. FWIW, that check is currently executed in [this line](https://github.com/10up/ElasticPress/blob/4.1.0/includes/classes/AdminNotices.php#L653). The current code only checks for ES versions though, not changes made in the mapping through EP versions.
That said, the mapping checks are something that will eventually have to be revisited, hence why we have that `@todo` in https://github.com/10up/ElasticPress/blob/4.1.0/includes/classes/Indexable.php#L1085.

I'm going ahead and closing the issue now as these checks will need to be handled via a separate issue when the time comes.
