### ISSUE TITLE
ElasticPress is returning entire document content in the search results

### ISSUE THREAD

**Issue by nickchomey** [10up/ElasticPress#2747]
I have uploaded about 10 large pdf documents (books) to my otherwise empty site and they have been successfully indexed by ElasticPress.

However, the search results seemed a bit slow to me (given what I've heard about ElasticSearch!). When I inspect the Query Result with the Debug Bar tool, I can see that the _entire_ contents of the documents - some of which are over 500,000 words - are returned.

I tried changing the `ep_max_result_window` default value from 1,000,000 to 100 and that doesn't help. Am I mistaken about what `ep_max_result_window` is supposed to do? Is there something else that I could change to have ElasticPress return only a small window/excerpt surrounding the match in the document? Or, better yet, could it return an array of excerpts/"windows" that surround the matched terms in the document?

And a related question: how do we make use of the document content in the search results? Right now only the document title is displayed in the search results whereas excerpts are displayed for normal posts.

**Comment by nickchomey** [comment]
> And a related question: how do we make use of the document content in the search results? Right now only the document title is displayed in the search results whereas excerpts are displayed for normal posts.

I now see that I can use a variety of filters to grab and use the document content:
* ep_get_hits_from_query
* ep_valid_response
* ep_retrieve_raw_response
* ep_retrieve_the_{type}
* ep_es_query_results

The final one or two are probably the best to use as the $documents array contains each document returned (likely just 1 in my case). the content, specifically, being here `$documents[0]["attachments"][0]["attachment"]["content"]`?

Anyway, I suppose my initial question still remains: is there 
a) a way to prevent ElasticPress from returning numerous 500,000 word document content arrays to begin with?, and
b) specifically to have it return an array of relevant excerpts/windows/contexts of the, say, 50 words on either side of a match in the document?

Of course I could do this all via some custom code in PHP, and then delete the rest of the text such that only a few hundred words per post get sent to/displayed in the client, but I'd love to leverage the power of elastic if possible!

**Comment by nickchomey** [comment]
I'll close this for now as I've just discovered these issues and links that will probably solve this for me:
https://github.com/10up/ElasticPress/issues/2635
https://github.com/10up/ElasticPress/issues/1250
https://github.com/10up/ElasticPress/issues/684
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-highlighting

I post an update if I find anything useful/different from what they did there.

**Comment by AndersonatAMC** [comment]
Is there a solution? It's still printing so many words in search results.

**Comment by nickchomey** [comment]
I forget exactly, but I'm pretty certain  you need to pass the `_source` field in the request and just return the fields you want. I don't recall the elasticpress hook that you need to use, but just search their documentation

**Comment by nickchomey** [comment]
http://10up.github.io/ElasticPress/ep_pre_request_args.html this one might work. There's 4 or 5 hooks prior to the request being sent, if I recall correctly. Just browse the source code
