### ISSUE TITLE
QUESTION: Multisite?  

### ISSUE THREAD

**Issue by blenkhn** [10up/ElasticPress#2750]
I am interested to know how well elasticpress works in a multisite environment.

**Describe your question**
Initially I was having user indexing issues now it fails with an out of memory error and all I did was add another site to the network.  IS this a possibility?  I now have an out of memory issue.  I have 36gb of memory.....

mmap() failed: [12] Cannot allocate memory
Fatal error: Out of memory (allocated 3750981632) (tried to allocate 272445440 bytes) in /wp-includes/wp-db.php on line 1582
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.

**Comment by felipeelia** [comment]
Hi @blenkhn. We have ElasticPress running in some very big multisite networks without any problems.

Although your server may have 36GB of memory, it seems MySQL is configured to use ~3GB. If you saw that error during a sync process, you can decrease the amount of memory used in the sync process lowering the number of "Content Items per Index Cycle" in the settings screen. If you had that in some other scenario, we would need to know more about it, like steps to reproduce, active plugins, etc.
