### ISSUE TITLE
QUESTION: Pagination limit?

### ISSUE THREAD

**Issue by rafaucau** [10up/ElasticPress#2752]
I have 40k posts on the website. I use pagination on the home page (displays 60 posts per page) and I noticed that the page count is much lower when I enable Elasticpress. The page count is 167 but it should be 769. 

I have re-indexed several times but it has not helped. 
The oldest posts are definitely indexed as I am able to search for them and they show up in categories and tags.
It looks like Elastic's limit is 10k posts.

I'm wondering if it's something with the plugin or the Elasticsearch configuration?

![image](https://user-images.githubusercontent.com/25438601/167718324-f8184af8-4242-4c08-9530-d922e15bd410.png)

Before:
![image](https://user-images.githubusercontent.com/25438601/167719333-f0d845c3-6d65-48ac-8c1a-39b4c6a67a94.png)

Elastic:
![image](https://user-images.githubusercontent.com/25438601/167719413-dfb127ef-576a-4b66-8c4e-2a45587956bc.png)

**Comment by felipeelia** [comment]
Hi @rafaucau! That is an Elasticsearch configuration indeed: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-your-data.html#track-total-hits

You can have the actual total number being returned using the following snippet:
```
add_filter(
    'ep_formatted_args',
    function( $formatted_args ) {
        $formatted_args['track_total_hits'] = true;
        return $formatted_args;
    }
);
```
Keep in mind that that comes with a (probably small) performance penalty, okay? Thanks!

**Comment by DeflateAwning** [comment]
Why isn't this a configuration option within the plugin? I would like it to be.

**Comment by felipeelia** [comment]
A PR with that configuration will be most welcomed, @DeflateAwning.
