### ISSUE TITLE
BUG: Unable to change settings on connection failure

### ISSUE THREAD

**Issue by Zyles** [10up/ElasticPress#2758]
**Describe the bug**

Unable to change the settings. Everything is greyed out.

![image](https://user-images.githubusercontent.com/1741593/168089729-a1a42d1b-4dd9-4f6a-99d9-212d4273d8a9.png)

**Steps to Reproduce**

1. Insert elasticsearch URL for third party
2. Authentication failed
3. Everything is greyed out unable to change settings

**Expected behavior**

Able to change settings.

**Screenshots**

![image](https://user-images.githubusercontent.com/1741593/168089845-7f03baa9-17bd-4a86-837d-2fef7fca7af9.png)

**Environment information**
 - WordPress version: 5.9.3
 
 - ElasticPress version: 4.1.0
 - Elasticsearch version: OpenSearch 1.2
 - Where do you host your Elasticsearch server? AWS
 - What ElasticPress features do you have currently active? Autosuggest, WooCommerce
 - Theme and version: Woodmart

**Comment by felipeelia** [comment]
Hi @Zyles,

Would it be possible for you to share the contents of the `ep_index_meta` option? You can get that by running `wp option get ep_index_meta`. If you have ElasticPress enabled for the entire network, then you'd need to run `wp site option get ep_index_meta`. Thanks in advance.
