### ISSUE TITLE
BUG: No mapping found for [post_title.sortable] in order to sort on

### ISSUE THREAD

**Issue by Zyles** [10up/ElasticPress#2759]
**Describe the bug**

Trying to get this plugin to work on a Woocommerce install unsuccessfully.

Navigating to a category the debug bar gives me a 400 error with:

```
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "No mapping found for [post_title.sortable] in order to sort on",
                "index_uuid": "QluUTYMmRYesgQxh0z-jCg",
                "index": "devstore-post-1"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "devstore-post-1",
                "node": "aWn-NA4WQ8KwPaA4PmkDFg",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "No mapping found for [post_title.sortable] in order to sort on",
                    "index_uuid": "QluUTYMmRYesgQxh0z-jCg",
                    "index": "devstore-post-1"
                }
            }
        ]
    },
    "status": 400
}
```

```
$ wp elasticpress stats
====== Stats for: devstore-post-1 ======
Documents:  1405
Index Size: 6,20 MB
Index Size (including replicas): 20,69 MB
====== End Stats ======
```

Also the ElasticPress widget does not output anything:
![image](https://user-images.githubusercontent.com/1741593/168103182-2241f779-1b14-4f48-b374-1f2f445de3ad.png)

**Steps to Reproduce**

1. Install elasticpress and elasticsearch
2. Sync data
3. Try to get it to work

**Expected behavior**

Working install.

**Screenshots**

**Environment information**
 - WordPress version: 5.9.3
 
 - ElasticPress version: 4.1.0
 - Elasticsearch version: 7.10
 - Where do you host your Elasticsearch server? AWS
 - What ElasticPress features do you have currently active? Autosuggest, WooCommerce
 - Theme and version: Storefront

**Comment by brandwaffle** [comment]
@Zyles this error is usually the result of the mapping not being properly sent during initial indexing. Can you try a "Delete all data and sync" and paste the results of any logs or errors (assuming the problem persists)? Thanks!

**Comment by Zyles** [comment]
Okay thanks, now it works after resyncing.

The facet widget for categories shows up now. However I find no widget product filter that supports advanced custom fields.

Is there no built in feature for this?

**Comment by Zyles** [comment]
Now when I ran the delete and sync again I get:

```
===============================
80
Deleting data…
81
Indexing posts...
82
Mapping failed
```

And sometimes `Too many requests` (default install).

**Comment by brandwaffle** [comment]
@Zyles the Facets are designed to work with WordPress taxonomies and WooCommerce product attributes. In general, since meta fields (including Advanced Custom Fields) aren't normalized data, we don't recommend using them for Facets. It is possible with custom code, however, if you have a set of data that's reasonably limited.

If you have access to WP-CLI on your WordPress install, you can try running a sync via WP-CLI and including the `--show-errors` flag to get more info as the where/how the sync is failing. Alternatively, you should see errors in the Sync screen if you choose Show Log and then click over to Errors.
