### ISSUE TITLE
BUG: Search by Product SKU not working with standard url param pattern

### ISSUE THREAD

**Issue by btweedy2879** [10up/ElasticPress#2764]
**Describe the bug**

Searching by sku does not seem to work when using the standard url param search (https://v1tactical.com/?s=KEKSA&post_type=product#search).  Autosuggest works but as soon as the user hits the enter key, an empty result is returned. 

**Steps to Reproduce**

1. Go to v1tactical.com
2. Click on the search icon in the upper right hand corner
3. Type in "KEKSA".  Autosuggest results will appear.
4. Hit enter key.
5. Results page shows "No products were found matching your selection."

**Expected behavior**

Results page would show a list of products who's SKU contains the characters KEKSA.

**Screenshots**

**Environment information**
 - Device: Macbook Pro
 - OS: MacOS 11.6
 - Browser and version: Chrome 101.0.4951.54
 - WordPress version: 5.9.3
 
 - ElasticPress version: 4.1.0
 - Elasticsearch version: 7.13.2
 - Where do you host your Elasticsearch server? v1tactical.com (Self hosted)
 - What ElasticPress features do you have currently active? Post Search, Autosuggest, WooCommerce, Related Posts, Facets, Terms, Custom Search Results 
 - Plugins and version: Can provide if necessary
 - Theme and version: Custom Theme
`
### wp-core ###

version: 5.9.3
site_language: en_US
user_language: en_US
timezone: America/Phoenix
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 12979
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/v1tactical/public_html
wordpress_size: 17.47 GB (18762081604 bytes)
uploads_path: /home/v1tactical/public_html/wp-content/uploads
uploads_size: 6.31 GB (6778275616 bytes)
themes_path: /home/v1tactical/public_html/wp-content/themes
themes_size: 12.47 MB (13072951 bytes)
plugins_path: /home/v1tactical/public_html/wp-content/plugins
plugins_size: 255.07 MB (267463552 bytes)
database_size: 4.16 GB (4466149836 bytes)
total_size: 28.21 GB (30287043559 bytes)

### wp-dropins (1) ###

maintenance.php: true

### wp-active-theme ###

name: V1tactical (nextfly)
version: 1.2
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, custom-background, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /home/v1tactical/public_html/wp-content/themes/nextfly
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

installatron_hide_status_test.php: author: (undefined), version: (undefined)

### wp-plugins-active (51) ###

Advanced Custom Fields: Font Awesome: version: 4.0.3, author: Matt Keys, Auto-updates disabled
Advanced Custom Fields PRO: version: 5.11.4, author: Delicious Brains (latest version: 5.12.2), Auto-updates disabled
Advanced Database Cleaner: version: 3.0.4, author: Younes JFR., Auto-updates disabled
All in One SEO: version: 4.2.0, author: All in One SEO Team, Auto-updates disabled
Auctions for WooCommerce: version: 1.6, author: WPInstitut, Auto-updates disabled
CAPTCHA 4WP: version: 7.0.6.1, author: WP White Security, Auto-updates disabled
Cloudflare: version: 4.9.1, author: Cloudflare, Inc., Auto-updates disabled
Credova Financial: version: 1.7.2, author: Credova (latest version: 1.7.3), Auto-updates disabled
Duplicate Menu: version: 0.2.2, author: Jonathan Christopher, Auto-updates disabled
Easy Accordion: version: 2.1.12, author: ShapedPlugin, Auto-updates disabled
ElasticPress: version: 4.1.0, author: 10up, Auto-updates disabled
Email Subscribers & Newsletters: version: 5.3.14, author: Icegram, Auto-updates disabled
Email Users: version: 4.8.8, author: Mike Walsh & MarvinLabs, Auto-updates disabled
Emma For WordPress: version: 1.3.3, author: Ah So, Auto-updates disabled
Favorites: version: 2.3.2, author: Kyle Phillips, Auto-updates disabled
Firearms Finder: version: 1.0.0, author: BT Interactive, Auto-updates disabled
Font Awesome: version: 4.1.1, author: Font Awesome, Auto-updates disabled
Google Analytics for WordPress by MonsterInsights: version: 8.5.2, author: MonsterInsights, Auto-updates disabled
Jetpack: version: 10.9, author: Automattic, Auto-updates disabled
Lipseys: version: 1.0.0, author: BT Interactive, Auto-updates disabled
Page Links To: version: 3.3.6, author: Mark Jaquith, Auto-updates disabled
Preview E-mails for WooCommerce: version: 2.0.2, author: Digamber Pradhan, Auto-updates disabled
Product Filters for WooCommerce: version: 1.2.2, author: WooCommerce (latest version: 1.3.1), Auto-updates disabled
Really Simple SSL: version: 5.3.2, author: Really Simple Plugins, Auto-updates disabled
Rocket Maintenance Mode & Coming Soon Page Builder: version: 4.3, author: wpexpertsio, Auto-updates disabled
Transients Manager: version: 2.0.2, author: WPBeginner, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.22.12, author: UpdraftPlus.Com, DavidAnderson, Auto-updates disabled
User Switching: version: 1.5.8, author: John Blackbourn & contributors, Auto-updates disabled
V1Tactical: version: 1.0.0, author: BT Interactive, Auto-updates disabled
WC Search Orders By Product: version: 1.6, author: WPHEKA, Auto-updates disabled
WooCommerce: version: 6.4.1, author: Automattic (latest version: 6.5.1), Auto-updates disabled
WooCommerce Admin Manual Giftcard: version: 1.0.2, author: BT Interactive, Auto-updates disabled
WooCommerce Converge Lightbox: version: 1.0.0, author: BT Interactive, Auto-updates disabled
WooCommerce Elavon Converge Gateway: version: 2.11.5, author: SkyVerge, Auto-updates disabled
WooCommerce Gift Cards: version: 1.10.3, author: WooCommerce, Auto-updates disabled
Woocommerce M.A.P. (Minimum Advertised Price): version: 1.0, author: David Barnes, Auto-updates disabled
WooCommerce Name Your Price: version: 3.3.9, author: Kathy Darling, Auto-updates disabled
WooCommerce PDF Invoices & Packing Slips: version: 2.14.5, author: WP Overnight, Auto-updates disabled
WooCommerce Points and Rewards: version: 1.7.8, author: WooCommerce, Auto-updates enabled
WooCommerce Shipping & Tax: version: 1.25.27, author: WooCommerce (latest version: 1.25.28), Auto-updates disabled
WooCommerce Sync for QuickBooks Online - by MyWorks Software: version: 2.5.5, author: MyWorks Software, Auto-updates disabled
WooCommerce UPS Shipping Plugin with Print Label: version: 4.5.0, author: PluginHive, Auto-updates disabled
WooCommerce V1tactical Gateway: version: 1.0.2, author: BT Interactive, Auto-updates disabled
WooCommerce Waitlist: version: 2.3.2, author: Neil Pie, Auto-updates disabled
Woocommerce Waitlist Dashboard: version: 1.0.0, author: Anchor Interactive, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
WordPress Users & WooCommerce Customers Import Export(BASIC): version: 2.2.9, author: WebToffee, Auto-updates disabled
WP-PageNavi: version: 2.94.0, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WP Crontrol: version: 1.12.1, author: John Blackbourn & crontributors, Auto-updates disabled
WPForms: version: 1.7.4.1, author: WPForms, Auto-updates disabled
WP Mail SMTP: version: 3.4.0, author: WPForms, Auto-updates disabled

### wp-plugins-inactive (2) ###

Premmerce Product Search for WooCommerce (Premium): version: 2.1.7, author: premmerce, Auto-updates disabled
WP All Export: version: 1.3.3, author: Soflyy (latest version: 1.3.4), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 90M
max_effective_size: 90 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-1160.62.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.29 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 1000
memory_limit: 3072M
max_input_time: 240
upload_max_filesize: 90M
php_post_max_size: 512M
curl_version: 7.83.0 OpenSSL/1.1.1o
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.38
client_version: mysqlnd 7.4.29
max_allowed_packet: 268435456
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/v1tactical/public_html/wp-content
WP_PLUGIN_DIR: /home/v1tactical/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 3072M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### aioseo (1) ###

noindexed: Author Archives, Date Archives, Categories (category)

### jetpack ###

site_id: 166488179
ssl_cert: No
time_diff: false
version_option: 10.4:1639529276
old_version: 9.9:1626379541
public: Public
master_user: No master user set.
current_user: #1 btweedy79
tokens_set: None
blog_token: Not set.
user_token: Not set.
version: 10.9
jp_plugin_dir: /home/v1tactical/public_html/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"HTTP_X_REAL_IP","segments":0,"reverse":false}
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: 67
sync_lag: 11 weeks, 3 days, 19 hours, 14 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/v1tactical.com","siteurl":"https:\/\/v1tactical.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: {"8":{"name":"test__connection_token_health","label":false,"short_description":"Blog token validation failed.","long_description":"<p>A healthy connection ensures Jetpack essential services are provided to your WordPress site, such as Stats and Site Security.<\/p><p><span class=\"dashicons fail\"><span class=\"screen-reader-text\">Error<\/span><\/span> Blog token validation failed.<\/p><p><strong>We recommend reconnecting Jetpack.<\/strong><\/p>","severity":"critical","action":"https:\/\/v1tactical.com\/wp-admin\/admin.php?page=jetpack#\/reconnect","action_label":"Reconnect Jetpack now","show_in_site_health":true,"pass":false,"group":["default"],"type":"direct"}}

### wp_mail_smtp ###

version: 3.4.0
license_key_type: lite
debug: No debug notices found.

### wpforms ###

version: 1.7.4.1
lite: Sep 13, 2019 @ 10:41am
pro: Sep 18, 2019 @ 10:44am
upload_dir: Writable
db_tables: wp_wpforms_entries, wp_wpforms_entry_fields, wp_wpforms_entry_meta, wp_wpforms_tasks_meta
total_forms: 1
total_entries: 334
license_status: Valid
license: Basic
license_location: option

`

**Additional context**
This was previously working and seemed to stop when we recently updated elasticpress to the current version.

**Comment by felipeelia** [comment]
Hi @btweedy2879,

It seems you have some incompatibility issue going on. If you go to https://v1tactical.com/?s=KEKSA (without the `post_type=product`) it is possible to see products in the results list.

Would it be possible for you to disable all the plugins with the exception of ElasticPress and WooCommerce, enable a WordPress default theme and test it? You can use the `Health Check & Troubleshooting` plugin and its troubleshooting mode to disable that only for your user: https://wordpress.org/plugins/health-check/

If things start working, you can enable them back one by one to see when it breaks again. Let us know the results, okay? Thanks!
