### ISSUE TITLE
Features page: status and colors

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2770]
**Is your enhancement related to a problem? Please describe.**

Currently, features have a status and a color that are not super intuitive: not-filled vs. filled means active or not, colors are related to requirements, warning, etc.

**Describe the solution you'd like**

Some UX changes to make it more clear to the final user.

**Comment by nickolas-kola** [comment]
UX deliverable created, please refer to internal channels.

**Comment by felipeelia** [comment]
Closed by the new UI implemented in EP 5.0
