### ISSUE TITLE
Autosuggest: Document window.epAutosuggestItemHTMLFilter

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2776]
**Is your enhancement related to a problem? Please describe.**

Although it is currently possible to change the autosuggest output, we don't have that properly documented.

**Describe the solution you'd like**
 An addition to the [Theme Integration page](http://10up.github.io/ElasticPress/tutorial-theme-integration.html) seems the best place to explain how to use the [window.epAutosuggestItemHTMLFilter function](https://github.com/10up/ElasticPress/blob/4.1.0/assets/js/autosuggest.js#L269).

An example I've recently shared that can serve as a starting point:
```
window.epAutosuggestItemHTMLFilter = function(itemHTML, doc, i, value) {
    return '<li><a href="' + doc._source.permalink + '"><img src="' + doc._source.thumbnail.src + '">' + doc._source.post_title + '</a></li>';
}
```

**Comment by MARQAS** [comment]
I'll look into this and will add documentation on how to use it properly.
