### ISSUE TITLE
QUESTION: Support for Elasticsearch 7.17.3

### ISSUE THREAD

**Issue by cmoa-webmaster** [10up/ElasticPress#2778]
Hello @felipeelia 

I was wondering when future versions of Elasticsearch would be supported. In short, we use elastic co using elasticsearch with Kibana and the only options for versions of Elasicsearch is 7.17.3 and sadly lower versions aren't supported. After, I was able to successfully connect to it, I got a warning that said "Your Elasticsearch version 7.17.3 is above the maximum required Elasticsearch version 7.10. ElasticPress may or may not work properly." Now I know 7.17.3 is obscure, but it is the lowest elasticsearch version option that https://cloud.elastic.co/ offers.

P.S. I am not sure if I had ever thanked you for your previous help. In short, our old elasticsearch version was deprecated and the verified connection details had readonly permission. Thus preventing it from resyncing with the elasticsearch database. The data was mixed with other data, so I understand why they made a user with that permission only.

**Comment by felipeelia** [comment]
Hey @cmoa-webmaster,

I've briefly talked about this in [this comment](https://github.com/10up/ElasticPress/issues/2671#issuecomment-1078972274). FWIW, we plan to increase the ES versions supported in 4.3.0, but so far the tests we've performed inform us that it should work with the latest ES. Thanks!

**Comment by cmoa-webmaster** [comment]
Thank you @felipeelia
