### ISSUE TITLE
Unapproved comments are being indexed

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#2783]
**Describe the bug**
When the Comments feature is enabled all comments are synced regardless of approval status. Only approved comments should sync.

Only approved comments are displayed, as expected, it's just the indexing that's affected.

**Steps to Reproduce**
1. Enable Comments feature.
2. Add a number of comments.
3. Check Index Health, and the number of documents in the comments index will match the number of comments.
4. Un-approve several comments.
5. Check Index Health, and the number of documents will be the same.
6. Add a comment that is unapproved by default, such as an anonymous comment.
7. Check Index Health, and the number of documents will show a new comment.
8. Approve the unapproved comments.
9. Check Index Health, the number of documents will be unchanged.
 
**Expected behaviour**
The number of indexed comments should reflect only approved comments.

**Comment by felipeelia** [comment]
As this only happens when Protected Content is enabled and is the expected behavior, I'm closing it out.
