### ISSUE TITLE
QUESTION: It looks like one or more of your indices are running on a single node. While this won't prevent you from using ElasticPress, depending on your site's specific needs this can represent a performance issue.

### ISSUE THREAD

**Issue by RetroGameTalk** [10up/ElasticPress#2785]
I got this warning: It looks like one or more of your indices are running on a single node. While this won't prevent you from using ElasticPress, depending on your site's specific needs this can represent a performance issue.
**Describe your question**

My question is what steps, exactly do I need to do to add more nodes? I'm a beginner.

Thanks.

**Comment by felipeelia** [comment]
Hi @MediaMaquina. Installing and configuring Elasticsearch is something that falls outside of the support we provide here. You can follow the ES documentation located in the link below but we won't be able to help you further than pointing you to that. Thanks!

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/add-elasticsearch-nodes.html
