### ISSUE TITLE
BUG: Admin menu bar items are not clickable. 

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#2788]
**Describe the bug**
The admin bar menu items are not clickable when the Instant Result popup is open. 

**Steps to Reproduce**
1. Enable the Instant Results feature. 
2. Navigate to the front end and search anything. 
3. While the popup is open, the menu bar items are not clickable. 

**Expected behavior**
The menu bar items must be clickable even when the popup is open

**Comment by MARQAS** [comment]
I can take care of it @felipeelia
