### ISSUE TITLE
Slow initial indexing

### ISSUE THREAD

**Issue by hriad** [10up/ElasticPress#279]
Hello,
Indexing is really slow. After more than two hours, 10.000 posts have been indexed out of 100.000. Boxes hosting the site / database / Elasticsearch are all reporting normal load and plenty of free RAM, so the issue does not seem resources related.

**Comment by tlovett1** [comment]
How much RAM does your box have? This is probably an issue with Elasticsearch configuration not EP.

**Comment by psorensen** [comment]
@hriad might be worth offloading ES. Bonsai.io offers a free plan. It's only 1g memory/storage, however, I use it on one of my sites to host 180k posts with considerable traffic. Works great.

**Comment by hriad** [comment]
@tlovett1 1GB RAM on the ES box. I might have an idea about what happened, today I checked the output from the wp cli index command. It was reporting that script execution timed out for a certain blog post, and it was point at one of my plugin shortcode. Does it mean that EP fetch every post and run through all shortcodes it finds? If it's the case it might explain the slow indexing, and how could one disable this behaviour as I dont need my shortcodes to be processed.

@psorensen That looks interesting, I'll check them out soon.

**Comment by tlovett1** [comment]
@hriad you could write some code to not process shortcodes here: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L420

Also, I'd recommend 2GB of RAM.

**Comment by hriad** [comment]
That's exactly what I was looking for, thanks for the help @tlovett1
