### ISSUE TITLE
Search products by their variations' SKUs

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2790]
**Is your enhancement related to a problem? Please describe.**

Currently, searching for a product variation SKU does not match its parent.

**Describe the solution you'd like**

Now that #2763 is merged and `meta._variations_skus` is available, we could add a new field to the Weighting Dashboard, allowing admin users to enable or not that field to be searchable.

**Comment by MARQAS** [comment]
I can look into this @felipeelia
