### ISSUE TITLE
BUG: Facet block doesn't render anything on frontend for single post

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#2797]
**Describe the bug**

Facet block doesn't render anything on the frontend for the single post , but it does render the result in the post edit screen.

**Steps to Reproduce**

1. Add Facet block in new post. 
2. The block does render the render in the edit screen but not on the frontend.

**Comment by felipeelia** [comment]
We should probably prevent people from adding that block on single posts/pages, as it doesn't make much sense to facet anything there.
