### ISSUE TITLE
Limit WooCommerce integration

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2809]
**Is your enhancement related to a problem? Please describe.**

Currently, the [translate_args](https://github.com/10up/ElasticPress/blob/4.2.0/includes/classes/Feature/WooCommerce/WooCommerce.php#L238) and the [should_integrate_with_query](https://github.com/10up/ElasticPress/blob/4.2.0/includes/classes/Feature/WooCommerce/WooCommerce.php#L1090) methods are too broad. For example, running:

```
		$posts = get_posts(
			[
				'post_type' => 'product',
				'post__in'  => [ 1, 2, 3 ],
			]
		);
```
Will add `ep_integrate` to the query. If the theme has 3 or 4 calls like that, it would result in 3 or 4 external requests, most likely making performance worst rather than helping it.

**Describe the solution you'd like**

We need to limit that integration to requests that really make sense, obviously allowing users to overwrite that if needed.

**Comment by burhandodhy** [comment]
All the required changes have been made in the https://github.com/10up/ElasticPress/pull/3259

**Comment by felipeelia** [comment]
Closing this in favor of #3259
