### ISSUE TITLE
BUG: WC search filters widgets not working properly when using synonyms

### ISSUE THREAD

**Issue by pedlima** [10up/ElasticPress#2818]
We noticed that whenever we use a synonym, it seems that the search filters on the shop do not represent the current search results at all.

One of many examples is this:

1. If we search for "bolsa multiusos" we get these filters on the left: https://americana.pt/?s=bolsa+multiusos&post_type=product
2. But if we search for "bolsas multiusos" (which is set in options as a a synonym of the above) we only get these fields on the left: https://americana.pt/?s=bolsas+multiusos&post_type=product

This, obviously, should had the exact same filters on the left, since it's a synonym. And it's not.

Here's the site health information:

`
### wp-core ###

version: 6.0
site_language: pt_PT
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 4022
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/americana/public_html
wordpress_size: 572,82 MB (600640532 bytes)
uploads_path: /home/americana/public_html/wp-content/uploads
uploads_size: 73,20 GB (78595450382 bytes)
themes_path: /home/americana/public_html/wp-content/themes
themes_size: 121,49 MB (127394086 bytes)
plugins_path: /home/americana/public_html/wp-content/plugins
plugins_size: 271,47 MB (284655310 bytes)
database_size: 2,90 GB (3109208064 bytes)
total_size: 77,04 GB (82717348374 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
maintenance.php: true

### wp-active-theme ###

name: Americana Child (americana-child)
version: 1.0.0
author: MAIDOT
author_website: https://maidot.pt
parent_theme: Woodmart (americana)
theme_features: core-block-patterns, woocommerce, wc-product-gallery-zoom, widgets-block-editor, post-thumbnails, post-formats, automatic-feed-links, title-tag, html5, menus, editor-style, editor-styles, align-wide, widgets
theme_path: /home/americana/public_html/wp-content/themes/americana-child
auto_update: Disabled

### wp-parent-theme ###

name: Woodmart (americana)
version: 6.3.0
author: XTemos
author_website: http://themeforest.net/user/xtemos
theme_path: /home/americana/public_html/wp-content/themes/americana
auto_update: Disabled

### wp-themes-inactive (2) ###

Americana: version: 5.3.6, author: MAIDOT, Auto-updates disabled
Twenty Twenty-One: version: 1.5, author: the WordPress team (latest version: 1.6), Auto-updates disabled

### wp-mu-plugins (1) ###

Elementor Safe Mode: version: 1.0.0, author: Elementor.com

### wp-plugins-active (45) ###

Admin Menu Editor Pro: version: 2.14.2, author: Janis Elsts (latest version: 2.17), Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Contact Form 7: version: 5.5.6, author: Takayuki Miyoshi (latest version: 5.5.6.1), Auto-updates disabled
Contact Form CFDB7: version: 1.2.6.4, author: Arshid, Auto-updates disabled
CTX Feed: version: 4.4.58, author: WebAppick (latest version: 4.4.65), Auto-updates disabled
Disable Blog: version: 0.5.0, author: Joshua Nelson, Auto-updates disabled
ElasticPress: version: 4.2.0, author: 10up, Auto-updates disabled
Elementor: version: 3.6.4, author: Elementor.com (latest version: 3.6.5), Auto-updates disabled
Elementor Pro: version: 3.6.5, author: Elementor.com (latest version: 3.7.1), Auto-updates disabled
Fix menu hierarchy: version: 0.1, author: Kyllaz, Auto-updates disabled
Flexible Checkout Fields: version: 3.2.2, author: WP Desk (latest version: 3.2.3), Auto-updates disabled
Free Shipping Label: version: 2.3.1, author: Devnet, Auto-updates disabled
Honeypot for Contact Form 7: version: 2.1, author: Nocean, Auto-updates disabled
Loco Translate: version: 2.6.1, author: Tim Whitlock (latest version: 2.6.2), Auto-updates disabled
maicore Core: version: 2.0, author: MaiDot, Auto-updates disabled
Maidot - LINK: version: 1.0, author: MaiDot, Auto-updates disabled
Multiple Shipping Address Woocommerce: version: 1.2, author: Maidot, Auto-updates disabled
NIF (Num. de Contribuinte Português) for WooCommerce: version: 4.2.6, author: Webdados, Auto-updates disabled
Popup Maker: version: 1.16.7, author: Popup Maker, Auto-updates disabled
Portugal States (Distritos) for WooCommerce: version: 3.0.3, author: Webdados, Auto-updates disabled
Pre* Party Resource Hints: version: 1.8.12, author: Sam Perrow (latest version: 1.8.13), Auto-updates disabled
Radio Buttons and Swatches for WooCommerce: version: 2, author: Maidot, Auto-updates disabled
Rank Math SEO: version: 1.0.90, author: Rank Math, Auto-updates enabled
Rank Math SEO PRO: version: 3.0.6, author: Rank Math (latest version: 3.0.13), Auto-updates enabled
Safe SVG: version: 2.0.1, author: 10up, Auto-updates disabled
ShortPixel Image Optimizer: version: 4.22.9, author: ShortPixel, Auto-updates disabled
SIBS - WooCommerce: version: 2.3.6, author: SIBS, Auto-updates disabled
Smart Image Resize PRO: version: 1.7.6.4, author: Nabil Lemsieh, Auto-updates disabled
SUMO Waitlist: version: 3.5, author: Fantastic Plugins, Auto-updates disabled
Tidio Chat: version: 5.0.0, author: Tidio Ltd., Auto-updates disabled
WC Pickup Store: version: 2, author: Maidot, Auto-updates disabled
WooCommerce: version: 6.4.1, author: Automattic (latest version: 6.5.1), Auto-updates disabled
WooCommerce Abandoned Cart Recovery Premium: version: 1.0.8, author: VillaTheme (latest version: 1.0.9), Auto-updates disabled
WooCommerce Email Template Customizer Premium: version: 1.1.6, author: VillaTheme (latest version: 1.1.9), Auto-updates disabled
WooCommerce Extra Product Sorting Options: version: 2.9.0, author: SkyVerge, Auto-updates disabled
WooCommerce Force Default Variant: version: 1.5.2, author: HappyKite, Auto-updates disabled
WooCommerce Order Communication: version: 1.0.0, author: DevDiggers, Auto-updates disabled
Woodmart Core: author: (undefined), version: 1.0.31, Auto-updates disabled
WP All Export - WooCommerce Export Add-On Pro: version: 1.0.4, author: Soflyy, Auto-updates disabled
WP All Export Pro: version: 1.7.5, author: Soflyy (latest version: 1.7.6), Auto-updates disabled
WP All Import - WooCommerce Import Add-On Pro: version: 3.3.0, author: Soflyy (latest version: 3.3.1), Auto-updates disabled
WP All Import Pro: version: 4.7.2, author: Soflyy (latest version: 4.7.3), Auto-updates disabled
WP Mail SMTP: version: 3.3.0, author: WPForms (latest version: 3.4.0), Auto-updates disabled
WP Performance Score Booster: version: 2.2, author: Dipak C. Gajjar, Auto-updates disabled
YITH WooCommerce Custom Order Status Premium: version: 1.2.13, author: YITH (latest version: 1.11.0), Auto-updates disabled

### wp-plugins-inactive (5) ###

Debug Bar: version: 1.1.2, author: wordpressdotorg (latest version: 1.1.3), Auto-updates disabled
Debug Bar ElasticPress: version: 2.1.0, author: 10up, Auto-updates disabled
iThemes Security: version: 8.1.0, author: iThemes (latest version: 8.1.2), Auto-updates disabled
WooCommerce Dynamic Pricing & Discounts: version: 2.4.3, author: RightPress, Auto-updates disabled
Wordfence Security: version: 7.5.9, author: Wordfence (latest version: 7.5.10), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 512M
max_effective_size: 512 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-110-generic x86_64
httpd_software: nginx/1.20.2
php_version: 7.4.28 64bit
php_sapi: fpm-fcgi
max_input_variables: 100000
time_limit: 1200
memory_limit: 16384M
max_input_time: 400
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.2.43-MariaDB-1:10.2.43+maria~bionic
client_version: mysqlnd 7.4.28
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/americana/public_html/wp-content
WP_PLUGIN_DIR: /home/americana/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 16384M
WP_MAX_MEMORY_LIMIT: 16384M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### wp_mail_smtp ###

version: 3.3.0
license_key_type: lite
debug: No debug notices found.
lite_install_date: May 19, 2021 @ 10:10pm

`

**Comment by felipeelia** [comment]
Hi @pedlima,

It seems you are not using ElasticPress facets but WoodMart's layered navigation. That element probably does not integrate with ElasticPress aggregations out-of-the-box, more likely running a different SQL query using the search term in the query string.

If it is not possible for you to use ElasticPress Facets for some reason, I recommend you to reach out to the theme author and check with them which would be the hooks available to make that integration happen. Thanks.

**Comment by pedlima** [comment]
Hi @felipeelia 

Thank you for your feedback. Indeed that's what was the case here. :)
