### ISSUE TITLE
Filter search and format results?

### ISSUE THREAD

**Issue by trident60** [10up/ElasticPress#282]
Hello,
Great plugin - it works perfectly!

That said, let me be a bit boring and tell you what I've been struggling to do ;)

90K posts - each post is an app from iTunes or Android Play. Each post has custom fields - pricing, free, release date, etc…

I'm trying to put a search in place that will allow the end user to do a "normal" keyword search but I'd like them to also be able to select or, at the least, have in the results, the ability to filter via category, tag, and some custom fields.

I'd also like to be able to format the results differently as they now appear 9 to a page with pagination at the bottom showing the many more pages of results. Ideally I'd like to be able to configure this so that I can do something like - have results display vertically, have facets display to the side of the results allowing the user to say "Oh, I just want to see apps that were released in the last year…" - or whatever ;)

Having tried Solr, and WPSolr (wouldn't display facets), OpenSemantic Search -doesn't work at all, Solr with LucidWorks Fusion (to confusing for me - I'm not a developer) - pretty much have tried everything! lol

ElasticPress works great - it indexes VERY fast - and so far it's as close to a solution as I've found. 

But can it do those things I need done - without me having to learn to be a developer? is there any documentation on this? I've tried installing another WP seach plugin - search and filter for instance - thinking it would just hitch a ride on the ElasticPress WP-Query - but no joy. Any other plugin for WP searching seemed to just bypass EP.

I have plenty of infrastructure, servers, etc…and WP and EP and ES are all running on an Ubuntu 14.04 Trusty, MariaDB 10.x, PHP5.9? (the latest) with a plenty of ram&disk…and this is the last piece of my puzzle…of course it's the piece I can't find!

Is there any hope? :)

Thanks for your time!
Rob
ps…my test site is at jersite.cloudapp.net

**Comment by AaronHolbrook** [comment]
Hi @trident60,
Sounds like you're definitely looking to implement [aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations.html) as well as some template/thematic changes.

To answer your first question, yes ElasticPress definitely supports the ability to send and receive aggregations, however it definitely requires some modifications of your query and your query handling to pull off. (Either you should be a developer, or find one to help you).

The other portion - your thematic changes - again would make the most sense to have a developer assist you in this regard.

Probably not the answer you wanted to hear, but I hope it helps to get you where you need to go.

Thanks,
Aaron
