### ISSUE TITLE
Compatibility with JetSmartFilters

### ISSUE THREAD

**Issue by jimhuds** [10up/ElasticPress#2829]
I'm running a web store with WooCommerce and Crocoblocks JetPlugins suite. ElasticPress has made everything a lot faster apart from the AJAX products filters from JetSmartFilters. Integration with JetSmartFilters would be very useful. Or if it's already possible, then some sort of instructions on how to enable it would be great. Thanks

**Comment by felipeelia** [comment]
Hi @jimhuds, it is great to read that ElasticPress made things a lot faster!

You are talking about this plugin here, right? https://crocoblock.com/plugins/jetengine-wp/

Unfortunately, we cannot access the codebase to Premium plugins thus restricting our ability to efficiently assist in regard to this issue. As their basic plan comes with premium support, we recommend reaching out directly to them and letting them see which would be the best way to have that integration created.

Thanks!
