### ISSUE TITLE
QUESTION: Is there a way to use fuzziness only on strings but NOT on numbers/integers?

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#2832]
Hello everyone!

I am looking for a way to alter the search query to only use fuzziness in _string parts_ of the query, but when it comes to numbers I want them to be searched as input. Fuzziness has a lot of advantages but when people are looking for numbers, they are usually specific.

So, using the default search algorithm and searching for a `post id `gives multiple _similar_ results and there are cases that the `post id` in question is not the top result.

Also, giving an example for buying a tire - ideal search term: `Pirelli 215/55/17`

- There is a probability that some people might write `pirelli` wrong
- When they are searching for a specific tire dimension, they want to see **extactly that** and not something _like that_

**Comment by scooterlord** [comment]
Can anyone provide help with this one? Any direction/pointers would be nice.

I am wondering if there can be some kind of _graceful fallback_ for this one as an alternative, ie:

- if exact matches are found, only show those
- if exact matches are _not_ found, show results with fuzziness

**Comment by oscarssanchez** [comment]
You can explore something like https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-types-tokenfilter.html#_settings_example_5 @scooterlord 

Alternatively, if your use case is post_id, why not add that field to be searchable and increase its weight compared to other ones?

**Comment by scooterlord** [comment]
Hello @oscarssanchez and thank you for your reply. I am _afraid_ to use a different tokenizer, as in, everything else works as expected - and not really sure it would solve my problem.

...one of the problems was indeed post_id, but managed to overcome it in the following way - I take the search term, check if it's an integer, and if it is, I change the query param to have 0 fuzziness. The problem however continues if the term is a string with a number or more than one numbers.

If there's no other solution, I was trying to implement something along the lines of splitting the search term to string and numbers and separataly weight those. What this does not resolve is the 'fallback' search queries that would produce unwanted results.

Any other ideas? TBH I would expect a simple parameter to exclude something from fuzziness.

edit: Now that I read more carefully I saw that you pasted a link for a filter. That would not affect my initial tokenizer/analyzer right? How would I use that though? Assuming that I can use it, I need both types of tokens (strings + numbers), how would I proceed with my query next? I apologize if what I am asking is something obvious, I am not that advanced in ES so, trying to make my way through.

**Comment by felipeelia** [comment]
Hi @scooterlord.

It seems you will need to split the search terms into different parts and apply different types and fuzziness to them. If you give a look at the code that starts in [this line](https://github.com/10up/ElasticPress/blob/4.2.1/includes/classes/Indexable/Post/Post.php#L1414) you will see that we always treat the entire string as a whole.

You'll need to use the [ep_formatted_args_query](https://github.com/10up/ElasticPress/blob/4.2.1/includes/classes/Indexable/Post/Post.php#L1601) filter to override that, getting the `$search_text` and splitting it into different parts if needed. Then, you'll need to apply the same `multi_match` clauses we have to both parts (pure numbers and strings) tweaking it accordingly.

Unfortunately, this is all we can give you at this time, so I'm going ahead and closing the ticket. If you come up with a solution and want to share it here for future users with similar problems, that would be great. Thanks.
