### ISSUE TITLE
Searches are only looking for posts despite other features/indexes being enabled 

### ISSUE THREAD

**Issue by nickchomey** [10up/ElasticPress#2844]
I have turned on a variety of features (comments, users, terms etc..) and they index with no problems. However, when I do a search from the nav bar search box in my theme, only the posts are searched (confirmed via debug bar).

Is there a particular setting or filter that I need to use to enable returning results based on all available indexes?

**Comment by nickchomey** [comment]
After doing a bit of debugging, the WP_User/Term/Comment_Query are run, but when the `integrate_search_queries` functions get evaluated, `query_vars['search']` is empty for everything except posts so `$enabled` always returns `false`.

For context, right now I'm just using the Twenty Twenty-One theme and searching from a blank page with the gutenberg search block.

Should this be working, or is it necessary to modify the search block or theme, or hook into the various queries and add `ep_integrate`?

**Comment by nickchomey** [comment]
Here's the curl request from Debug Bar. As you can see, it only searches the post-1 index.

`curl -XPOST -H 'Content-Type: application/json' -d '{"from":0,"size":100,"sort":[{"_score":{"order":"desc"}}],"query":{"bool":{"should":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"ipsum","type":"phrase","fields":["post_title^1","post_excerpt^1","post_content^1","post_author.display_name^1","terms.category.name^1","terms.post_tag.name^1"],"boost":3}},{"multi_match":{"query":"ipsum","fields":["post_title^1","post_excerpt^1","post_content^1","post_author.display_name^1","terms.category.name^1","terms.post_tag.name^1"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"ipsum","type":"cross_fields","fields":["post_title^1","post_excerpt^1","post_content^1","post_author.display_name^1","terms.category.name^1","terms.post_tag.name^1"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"post"}}]}},{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"ipsum","type":"phrase","fields":["post_title^1","post_excerpt^1","post_content^1","post_author.display_name^1"],"boost":3}},{"multi_match":{"query":"ipsum","fields":["post_title^1","post_excerpt^1","post_content^1","post_author.display_name^1"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"ipsum","type":"cross_fields","fields":["post_title^1","post_excerpt^1","post_content^1","post_author.display_name^1"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"page"}}]}}]}},"post_filter":{"bool":{"must":[{"terms":{"post_type.raw":["post","page"]}},{"terms":{"post_status":["publish"]}}]}}}' 'http://localhost:9200/domaincom-post-1/_search'
`

**Comment by felipeelia** [comment]
Hi @nickchomey, thanks for opening the issue.

Those are the intended behaviors.

- As WP_Query, the other Indexables (WP_Term_Query, etc.) will only integrate with ElasticPress if it is performing a search or if `ep_integrate` is explicitly set. The WP_Query being the most common use case, there are also some edge cases like Facets, etc. where EP is leveraged in that case but all those should be considered exceptions.

- We do not perform cross Indexables searches due to different reasons like different mappings, and how that would have to be handled in the code (a WP loop also displaying terms and users is something not common at all.) We have #2676 to partially cover that use case but that is not currently in our roadmap.

**Comment by nickchomey** [comment]
@felipeelia Thanks very much for the confirmation and explanation!

For a bit of context, I've been working on an ElasticPress-BuddyPress Integration (#3) for a couple weeks and I have successfully indexed some of the BuddyPress data types by extending the Feature and Indexable classes, but such a Feature would only really be useful if you could do a site-wite search across all of the EP Indexables (BP groups, member profiles, activity posts, bbPress Forum Posts, CPTs, etc...) at once. So, before going further to create Indexables for the rest of the BP data types, I'd like to ensure that I can even achieve such a thing. 

So, do you have any general recommendation for what I would need to do in order to have a single `?s=` search across multiple/all Indexables? I'm thinking that I'll have to 
1. roll up my sleeves and trace the WP code using Xdebug to find a filter that I can use to reliably hijack the search process and insert a custom function that will run the appropriate EP index searches, and 
2. Create a custom search results page that appropriately parses, sorts, etc... each index result. 

I certainly don't expect you to solve this for me, but any tips to push me in the right direction would be very much appreciated. 

Thanks!

**Comment by nickchomey** [comment]
Actually, please ignore this. I've started investigating the possibility of piggybacking off of an existing open-source BuddyPress search plugin/mechanism which should be able to do all of the heavy lifting as far as integrating with WP goes.

All I'll need to do is 
1. create indexables and mappings for the relevant data types. I dont see this being too difficult now that I have it roughly working for BP Groups.
2. Figure out how to replace the SQL query with an EP/ES JSON query

I will post questions related to this in #3, and hopefully you wizards can point me in the right direction!

Thanks!
