### ISSUE TITLE
Sync error messages linking to documentation

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2847]
**Is your enhancement related to a problem? Please describe.**

Right now, if the user syncing content via Dashboard has too many meta fields, for example, and receives a `Limit of total fields [???] in index [???] has been exceeded` error, the plugin does not offer any additional help.

**Describe the solution you'd like**

In this specific case, we could link them to [this article](https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-). In general, at the end of a failed sync, we could create a notice saying "It seems your sync failed" and a list of useful links (generated by matching error messages.)

**Additional context**

This will only help users during the sync process. For problems happening during searches, we probably will have to use Debug Bar ElasticPress (https://github.com/10up/debug-bar-elasticpress/issues/28)

**Comment by nickolas-kola** [comment]
UX deliverable created, please refer to internal channels.
