### ISSUE TITLE
Error Log for is_search

### ISSUE THREAD

**Issue by allenmoore** [10up/ElasticPress#285]
We're receiving the following in the error logs related to the ```elasticpress_enabled()``` function:

```2015/05/13 04:20:49 [error] 32735#0: *5417370 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function is_search() on a non-object in /var/www/html/yourdomain.com/wordpress/wp-content/plugins/elasticpress/classes/class-ep-api.php on line 1100" while reading upstream, client: 66.249.79.206, server: yourdomain.com, request: "GET /groups/fappo/members/ HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "yourdomain.com"```

**Comment by tlovett1** [comment]
I think this is a bug in "query stacking": https://github.com/10up/ElasticPress/blob/bfa16e55e1478ac44260a60da4fd7acc224a992a/classes/class-ep-wp-query-integration.php#L110

**Comment by allan23** [comment]
This is most likely caused by BuddyPress in bp-groups/bp-groups-template.php on line 3799 when it sends an instance of BP_Groups_Group_Members_Template in the 'loop_start' hook:
```
/**
 * Fires if the current member item is the first in the members list.
 *
 * @since BuddyPress (1.0.0)
 * @since BuddyPress (2.3.0) `$this` parameter added.
 *
 * @param BP_Groups_Group_Members_Template $this Instance of the current Members template.
 */
do_action( 'loop_start', $this );

```
A possible solution to this would be to check for the is_search() method in the retrieved $query object:
```
if ( method_exists( $query, 'is_search' ) && $query->is_search() ) {
```
