### ISSUE TITLE
Elastpress Sync Triggering Unexpectedly

### ISSUE THREAD

**Issue by greg-carter1924** [10up/ElasticPress#2866]
Elasticpress sync is being triggered unexpectedly and we're trying to figure out why. We're getting support from 10Up. So far, we have been unable to determine why this is happening.

We have checked with our developers and no external events outside the server environment are scheduled. We're in the WP Engine environment, and WP Engine support could not answer this question either.

The WP Control Plugin shows a list of 38 Crons running daily or weekly.
Could one of the Crons be triggering the Sync?

@brandwaffle @felipeelia

**Comment by felipeelia** [comment]
As this problem was not in the plugin but rather in the overall setup I'm going ahead and closing out the issue. Thanks!
