### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by HypeAU** [10up/ElasticPress#2870]
**Describe the bug**
I just updated to the latest version and got this

( ! ) Notice: Undefined index: server_type in  public_html/wp-content/plugins/elasticpress/includes/classes/Elasticsearch.php on line 1326
--

1 | 0.0030 | 772400 | {main}( ) | .../index.php:0
2 | 0.0030 | 772792 | require( '/public_html/wp-blog-header.php ) | .../index.php:17
3 | 0.0030 | 773176 | require_once( '/public_html/wp-load.php ) | .../wp-blog-header.php:13
4 | 0.0030 | 773520 | require_once( '/public_html/wp-config.php ) | .../wp-load.php:50
5 | 0.0032 | 775920 | require_once( '/public_html/wp-settings.php ) | .../wp-config.php:68
6 | 0.1048 | 7663880 | do_action( $hook_name = 'plugins_loaded' ) | .../wp-settings.php:461
7 | 0.1048 | 7664256 | WP_Hook->do_action( $args = [0 => ''] ) | .../plugin.php:476
8 | 0.1048 | 7664256 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | .../class-wp-hook.php:331
9 | 0.1121 | 8088000 | ElasticPress\register_indexable_posts( '' ) | .../class-wp-hook.php:307
10 | 0.1123 | 8092080 | ElasticPress\Indexable\Post\Post->__construct( ) | .../elasticpress.php:102
11 | 0.1125 | 8094928 | ElasticPress\SyncManager->__construct( $indexable_slug = 'post' ) | .../Post.php:55
12 | 0.1126 | 8105624 | ElasticPress\Indexable\Post\SyncManager->setup( ) | .../SyncManager.php:66
13 | 0.1126 | 8106304 | ElasticPress\Elasticsearch->get_elasticsearch_version( $force = ??? ) | .../SyncManager.php:47
14 | 0.1126 | 8106304 | ElasticPress\Elasticsearch->get_elasticsearch_info( $force = FALSE ) | .../Elasticsearch.php:217
15 | 0.1126 | 8171840 | ElasticPress\Elasticsearch->set_elasticsearch_info( $force = FALSE ) | .../Elasticsearch.php:1406

**Comment by HypeAU** [comment]
thats funny just disappeared :) my bad

**Comment by cbratschi** [comment]
We have the same issue:

https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L1326
