### ISSUE TITLE
BUG: PHP 8.1 deprecated errors

### ISSUE THREAD

**Issue by BWBama85** [10up/ElasticPress#2873]
**Describe the bug**
```
Deprecated	Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Cookie/Jar.php:63
Plugin: elasticpress
Deprecated	Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Cookie/Jar.php:73
Plugin: elasticpress
Deprecated	Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Cookie/Jar.php:89
Plugin: elasticpress
Deprecated	Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Cookie/Jar.php:102
Plugin: elasticpress
Deprecated	Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Cookie/Jar.php:111
Plugin: elasticpress
Deprecated	Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:40
Plugin: elasticpress
Deprecated	Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:51
Plugin: elasticpress
Deprecated	Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:68
Plugin: elasticpress
Deprecated	Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:82
Plugin: elasticpress
Deprecated	Return type of Requests_Utility_CaseInsensitiveDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	
wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:91
Plugin: elasticpress
```

**Steps to Reproduce**

I am not able to get this to show up on every page load so not exactly sure what triggers it. I did catch it on one page load, but when I refreshed the page the errors disappeared. 

**Expected behavior**
No deprecated errors

**Environment information**
 - WordPress version: 6.0
 
 - ElasticPress version: 4.2.1
 - Elasticsearch version: 7.10.2-1
 - Where do you host your Elasticsearch server? Centos 7 OVH server
 - What ElasticPress features do you have currently active? Post Search, Related Posts, Custom Search Results]
 

<details><summary>Site Health Info:</summary>
   `
### wp-core ###

version: 6.0
site_language: en_US
user_language: en_US
timezone: America/Chicago
permalink: /%post_id%/%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 324
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/nginx/domains/bamapolitics.com/public
wordpress_size: loading...
uploads_path: /home/nginx/domains/bamapolitics.com/public/wp-content/uploads
uploads_size: loading...
themes_path: /home/nginx/domains/bamapolitics.com/public/wp-content/themes
themes_size: loading...
plugins_path: /home/nginx/domains/bamapolitics.com/public/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: Wordpress Bootstrap 5 (wordpress-bootstrap-5)
version: 5.2.2
author: Brent Wilson
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, menus, post-thumbnails, title-tag, automatic-feed-links, html5, custom-logo, widgets
theme_path: /home/nginx/domains/bamapolitics.com/public/wp-content/themes/wordpress-bootstrap-5
auto_update: Enabled

### wp-themes-inactive (1) ###

Twenty Twenty-Two: version: 1.2, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

WP Migrate DB Pro Compatibility: version: 1.2, author: Delicious Brains

### wp-plugins-active (28) ###

Advanced Custom Fields PRO: version: 5.12.2, author: Delicious Brains, Auto-updates disabled
Advanced Database Cleaner: version: 3.1.1, author: Younes JFR., Auto-updates disabled
Autoptimize: version: 3.0.4, author: Frank Goossens (futtta), Auto-updates enabled
Bama Politics Essentials: version: 3.16.8, author: Brent Wilson, Auto-updates enabled
Breadcrumb NavXT: version: 7.0.2, author: John Havlik, Auto-updates enabled
Cache Enabler: version: 1.8.9, author: KeyCDN, Auto-updates enabled
Cloudflare: version: 4.10.1, author: Cloudflare, Inc., Auto-updates enabled
Contact Form 7: version: 5.6, author: Takayuki Miyoshi, Auto-updates enabled
ElasticPress: version: 4.2.1, author: 10up, Auto-updates enabled
EWWW Image Optimizer: version: 6.6.0, author: Exactly WWW, Auto-updates enabled
Git Updater: version: 11.0.3, author: Andy Fragen, Auto-updates enabled
Hypernotes: version: 1.0.1, author: Ella van Durpe, Auto-updates enabled
OneSignal Push Notifications: version: 2.2.7, author: OneSignal, Auto-updates enabled
Paid Memberships Pro: version: 2.8.3, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Add PayPal Express Add On: version: .6, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Advanced Levels Page Shortcode Add On: version: .2.4, author: Stranger Studios, Auto-updates enabled
Paid Memberships Pro - Email Confirmation Add On: version: 0.6, author: Paid Memberships Pro, Auto-updates enabled
Query Monitor: version: 3.9.0, author: John Blackbourn, Auto-updates enabled
Redis Object Cache: version: 2.0.26, author: Till Krüss, Auto-updates enabled
Simple Author Box Premium: version: 2.3.20, author: WebFactory Ltd, Auto-updates enabled
The SEO Framework: version: 4.2.5, author: The SEO Framework Team, Auto-updates enabled
The SEO Framework - Extension Manager: version: 2.5.3, author: The SEO Framework Team, Auto-updates enabled
UpdraftPlus - Backup/Restore: version: 1.22.12, author: UpdraftPlus.Com, DavidAnderson, Auto-updates enabled
WP Crontrol: version: 1.12.1, author: John Blackbourn & crontributors, Auto-updates disabled
WP Migrate: version: 2.3.2, author: Delicious Brains (latest version: 2.3.3), Auto-updates disabled
WP Offload SES: version: 1.5.6, author: Delicious Brains, Auto-updates disabled
WP Sendy Newsletter Generator: version: 1.0.1, author: Brent Wilson, Auto-updates enabled
WP Subscribe To Posts: version: 2.0.12, author: Brent Wilson, Auto-updates enabled

### wp-media ###

image_editor: EWWWIO_GD_Editor
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-54 Q16 x86_64 17322 https://legacy.imagemagick.org
imagick_version: @PACKAGE_VERSION@
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 3.10.0-1160.66.1.el7.x86_64 x86_64
httpd_software: nginx/1.21.6
php_version: 8.1.7 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 60
memory_limit: 1024M
max_input_time: 60
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.4.25-MariaDB
client_version: mysqlnd 8.1.7
max_allowed_packet: 67108864
max_connections: 600

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/nginx/domains/bamapolitics.com/public/wp-content
WP_PLUGIN_DIR: /home/nginx/domains/bamapolitics.com/public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pmpro ###

pmpro-cron-jobs: pmpro_license_check_key (2022-06-30 16:28:05) | 
pmpro_cron_stripe_subscription_updates (2022-06-30 16:28:05) | 
pmpro_cron_admin_activity_email (2022-06-30 16:30:00) | 
pmpro_cron_expire_memberships (2022-06-30 16:37:57) | 
pmpro_cron_expiration_warnings (2022-07-01 11:27:05) | 
pmpro_cron_credit_card_expiring_warnings (2022-07-05 11:27:04)
pmpro-gateway: Stripe [stripe]
pmpro-gateway-env: Live/Production [live]
pmpro-orders: 295 orders
pmpro-discount-codes: 0 discount codes
pmpro-membership-levels: {
    "1": {
        "id": "1",
        "name": "Free Membership",
        "description": "Our free membership level allows you to follow bills, elected officials, candidates, and elections and receive updates via email when the the page is updated.",
        "confirmation": "",
        "initial_payment": 0,
        "billing_amount": 0,
        "cycle_number": "0",
        "cycle_period": "",
        "billing_limit": "0",
        "trial_amount": 0,
        "trial_limit": "0",
        "allow_signups": "1",
        "expiration_number": "0",
        "expiration_period": ""
    },
    "2": {
        "id": "2",
        "name": "Ad-Free Experience",
        "description": "Support Bama Politics and browse the site ad-free. The Ad-Free Experience gives you access to all free features of the site but also removes all ads for you while you are logged into your account. Your support helps me continue to work on the website.",
        "confirmation": "",
        "initial_payment": 5,
        "billing_amount": 5,
        "cycle_number": "1",
        "cycle_period": "Month",
        "billing_limit": "0",
        "trial_amount": 0,
        "trial_limit": "0",
        "allow_signups": "1",
        "expiration_number": "0",
        "expiration_period": ""
    },
    "3": {
        "id": "3",
        "name": "Founding Member",
        "description": "For a one-time payment, the Founding Member upgrade gives you access to all free membership features and all future premium features on Bama Politics. Founding Members will also never see advertisements. Your payment helps me continue to build Bama Politics.",
        "confirmation": "",
        "initial_payment": 60,
        "billing_amount": 0,
        "cycle_number": "0",
        "cycle_period": "",
        "billing_limit": "0",
        "trial_amount": 0,
        "trial_limit": "0",
        "allow_signups": "1",
        "expiration_number": "0",
        "expiration_period": ""
    }
}
pmpro-custom-templates: No template overrides
pmpro-getfile-usage: PMPRO_GETFILE_ENABLED is not set
pmpro-htaccess-cache-usage: Off - No .htaccess file
pmpro-pages: 
	account: https://www.bamapolitics.com/membership-account/
	billing: https://www.bamapolitics.com/membership-account/membership-billing/
	cancel: https://www.bamapolitics.com/membership-account/membership-cancel/
	checkout: https://www.bamapolitics.com/membership-account/membership-checkout/
	confirmation: https://www.bamapolitics.com/membership-account/membership-confirmation/
	invoice: https://www.bamapolitics.com/membership-account/membership-invoice/
	levels: https://www.bamapolitics.com/membership-account/membership-levels/
	login: https://www.bamapolitics.com/login/
	member_profile_edit: https://www.bamapolitics.com/membership-account/your-profile/
pmpro-library-conflicts: No library conflicts detected.

`</details>

**Comment by felipeelia** [comment]
Although the log points to ElasticPress, it is actually something handled by WordPress's core itself.

A similar issue was [reported in the WP-CLI repo](https://github.com/wp-cli/wp-cli/issues/5613). There I found that the WP core team is handling this upgrade via this ticket in Trac: https://core.trac.wordpress.org/ticket/54504

As unfortunately there is nothing we could do on our side, I'm going ahead and closing the ticket. Thanks!
