### ISSUE TITLE
ElasticPress is integrating all main queries

### ISSUE THREAD

**Issue by columbian-chris** [10up/ElasticPress#2874]
Is this a feature of a recent update?  All of a sudden the main query throughout the different pages on my site I've looked into are using ElasticPress, acting like it has `ep_integrate` set to true in them.

Using:
ElasticPress 4.2.1
Elasticsearch 7.9.3 (also tested on 7.17.3)
Wordpress 6.0 (also tested on 5.9.3)
PHP 7.4.30

**Comment by columbian-chris** [comment]
I reverted the plugin back to 4.2.0 and am not experiencing the same issue.  I'm going to try wiping the index and resyncing in the middle of the night (using 4.2.1).

**Comment by felipeelia** [comment]
@columbian-chris can you please list the features you have enabled? We've made a change to make Facets available in taxonomy archives IIRC and that could be increasing the number of pages being integrated with EP.

**Comment by columbian-chris** [comment]
@felipeelia Features enabled: Post Search, Facets, Custom Search Results, Related Posts

Does this mean that a resync should be possibility be required with 4.2.1?

**Comment by felipeelia** [comment]
No, @columbian-chris, that should not be related to resyncs.

In #2837 we've addressed a problem where the Facets widget would not show up in taxonomy archives. In order to display that widget, we need to run the main query through EP, so we had to expand the list of archive pages where we were setting both `ep_integrate` and `ep_facet` as `true`.

 If you don't want your queries going through EP in those archive pages, you could override that using the `ep_is_facetable` filter.

Can you give that a try? By the way, just out of curiosity, is there a specific reason why you do not want EP integrated into those queries? Thanks!

**Comment by columbian-chris** [comment]
Thanks, I'm not going to waste time and resources try doing a resync then.  I will give [that override](https://10up.github.io/ElasticPress/ep_is_facetable.html) a shot, although I'm not quite certain yet how to apply it.  If I use it in my theme's functions.php file, will it disable EP from all queries unless I manually pass the query using the `ep_integrate` parameter?

I would in theory love to have everything run through ElasticPress for the performance, but when I initially tried to do that when I first started using it, we were receiving more and more complaints that content was missing in places.  I had continuing issues with archives and ended up deactivating them one by one until we decided to mostly use EP for our public search function, which using database query alone without EP stacks on 10-20 seconds of page load time.  To give you an idea of the size of this site, we currently have (at the time of this writing) 1,006,721 rows in our wp_posts table and 3,841,793 rows in our wp_post_meta table.  I was doing a sync via a cron job once a week and was still getting complaints about missing posts that should have been synced, so I've been doing a full wipe and resync once a week to increase stability.  Really the only reason why I discovered this issue is that we were receiving complaints from certain archive pages that it wasn't displaying posts from the last couple of days (since the time that I upgraded the plugin from 4.2.0 to 4.2.1).  This missing content would suddenly appear after disabling the EP plugin.

**Comment by columbian-chris** [comment]
I did a resync and it does seem to be showing the posts in the archive page it wasn't before the sync.  But also I'm looking at another archive page and it isn't showing new posts that were entered after the sync.  So it seems like I might have an issue with new posts being saved to my Elasticsearch index.

**Comment by felipeelia** [comment]
Hey @columbian-chris, sorry for not getting back to you earlier. In ElasticPress 4.2.1 (released yesterday) we've narrowed down a bit how Facets would change the main query but I don't think that will help with your problem, unfortunately.

> If I use it in my theme's functions.php file, will it disable EP from all queries unless I manually pass the query using the ep_integrate parameter?

No. There is a couple of reasons why ElasticPress would be automatically integrated on a query: a regular search query, a query with ep_integrate, or a potentially facetable query, for example. Using the ep_is_facetable filter you would only affect the last factor, i.e., if a query is a search, that would still be integrated.

I'd strongly recommend to you investigate why those posts are not being indexed. [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) has a logger that can be enabled to capture faulty queries. So, if you enable that and save a post, the error will be captured.

If these posts are added via a bigger import process, the WP_IMPORTING constant being set, for example, would prevent EP from syncing new posts. More in this other issue: https://github.com/10up/ElasticPress/issues/2654

As the problem derailed a bit from the original issue, I'm going ahead and closing the issue but feel free to leave additional comments/questions, okay? Thanks!

**Comment by columbian-chris** [comment]
Thank you, @felipeelia.  Does the [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugin log to PHP or to WP's debug file (/wp-content/debug.log) or somewhere else?

**Comment by felipeelia** [comment]
To make it easier for beginner users, it will store messages into a WP option @columbian-chris. That said, once you have error messages logged, don't forget to turn the logger off.
