### ISSUE TITLE
BUG: LiteSpeed Cache's Object Cache

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2876]
**Describe the bug**

It seems Object Cache set by [LiteSpeed Cache](https://wordpress.org/plugins/litespeed-cache/) will make ElasticPress syncs to get stuck.

The first object of this issue needs to be an investigation of the problem (see if we can reproduce it or not) and also check if it affects general setups with object cache enabled.

Related to #2805

**Comment by MARQAS** [comment]
I am unable to recreate this issue, I tried with both Caching plugins (LiteSpeed Cache and Redis Object Cache ). 

- Is indexing working properly with LiteSpeed Cache? Yes
- Is indexing working fine with Redis Object Cache? Yes
- Are all the features of ElasticPress working as expected including the WooCommerce when Object cache is enabled? Yes
- Are you able to index using wp cli commands? Yes
- Is indexing working for both Multi site and single sites environment? Yes

I am going ahead and closing this ticket as I did not find any issues with Object cache. Thanks!
