### ISSUE TITLE
BUG: Synonyms break syncs when a dot is used in the term

### ISSUE THREAD

**Issue by craigpearson** [10up/ElasticPress#2878]
**Describe the bug**
Indexing issues are created when using "." character in synonyms, both sets and alternates. Suspected that this causes issues as Elasticsearch uses dot notation for queries.

Example use case:

When categorising WooCommerce products for duvets / quilts, each product would have a Tog rating, this is denoted by "10.5 Tog" or "7.5 Tog" etc

As a user may not know the correct tog rating for a duvet we may want to set up a set / alternate synonym such as:

**Primary Search Term**: Summer
**Alternates**: 4.5 Tog, 7.5 Tog

Upon index this will throw issues such as:

```
Warning: 135160 (Post): [illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=24,endOffset=28,lastStartOffset=27 for field 'post_name'
```

```
Warning: 139299 (Post): [illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=891,endOffset=895,lastStartOffset=894 for field 'post_content_filtered'
```

**Steps to Reproduce**
1. In WooCommerce create a product that has the phrase "4.5 Tog" in the title, or in the unfiltered_post_content

2. Assign a category of "4.5 Tog"

3. Create a Synonym (either set or alternate), where the primary search term is "Summer" and synonyms are "4.5 Tog" and "7.5 tog" 

4. Index posts via GUI or WP CLI

**Expected behavior**
Index is supposed to happen

**Environment information**
 - Device: N/A
 - OS: N/A
 - Browser and version: N/A
 - WordPress version: 5.9
 - ElasticPress version: 4.2
 - Elasticsearch version: 7.10
 - Where do you host your Elasticsearch server? Self hosted
 - What ElasticPress features do you have currently active? Post Search, Autosuggest, WooCommerce, Protected Content, Facets, Terms, Custom Search Results

![Screenshot 2022-07-01 at 11 13 12](https://user-images.githubusercontent.com/1629114/176875393-fd54b918-77d2-4de9-aa06-9db2951129ba.png)

**Comment by felipeelia** [comment]
Hi @craigpearson,

This is most probably related to #2877. While we don't have that done, you could try to tweak the word delimiter token filter a bit. A starting point could be the following code:

```
add_filter(
	'ep_post_mapping',
	function( $mapping ) {
		try {
			$mapping['settings']['analysis']['filter']['ewp_word_delimiter']['type_table'] = [ ". => DIGIT" ];
		} catch ( \Throwable $th ) {
			/* noop */
		}
		return $mapping;
	}
);
```

You'll need to add that to your codebase and resync (deleting all data.) Can you give that a try and let us know if that fixes your problem? Thanks.
