### ISSUE TITLE
QUESTION: My blog page is showing products and posts instead of just posts

### ISSUE THREAD

**Issue by gillespieza** [10up/ElasticPress#2879]
**Describe your question**
I have my site set up to use a static home page, with a separate page for blog posts. When ElasticPress is enabled, all my products and my posts show on my news page, instead of just the posts. 

I've looked at WP_Query using Query Monitor and Debug Bar, and the SQL is correct (returns only the 6 posts I have). I can't ferret out where the additional hundreds of products are being pulled in from...

This is happening with both my theme and the Twenty Twenty-Two default theme.

**Comment by oscarssanchez** [comment]
Hi @gillespieza ,

I couldn't reproduce this, would you mind sharing more details if possible please? The "Environment information" section is a good place to start:


**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - ElasticPress version: 
 - Elasticsearch version: 
 - Where do you host your Elasticsearch server? 
 - What ElasticPress features do you have currently active? 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>


Thanks!

**Comment by oscarssanchez** [comment]
Hi @gillespieza ,

I could actually reproduce this today, seems this is happening when you have the facet feature activated. If you are not using this feature for now, I would deactivate it or if you are using it, perhaps something like explicitly setting the post types might help in this case as a workaround while we fix this issue. Something like:

```
add_action('pre_get_posts', function ($query) {
    if ($query->is_home()) {
        $query->set('post_type', 'post');
    }
}, 1);
```
