### ISSUE TITLE
QUESTION: ElasticPress 4.2.1 reporting "server software is not supported"

### ISSUE THREAD

**Issue by dmhendricks** [10up/ElasticPress#2882]
Since upgraded to ElasticPress 4.2.1, I'm getting the "server software is not supported" notice on both of the 2 sites I tried it on. The message suggests checking the [requirements](https://github.com/10up/ElasticPress#requirements), however, the environment meets the minimum requirements listed, and I don't recall getting this message with previous versions.

What is the best way to find the incompatibility?

**Site 1**

- Elasticsearch 7.9.3
- WordPress 6.0
- **PHP 8.1.6**
- Nginx 1.18
- WooCommerce is _not_ installed

**Site 2**
_(same as above except the PHP version)_

- Elasticsearch 7.9.3
- WordPress 6.0
- **PHP 7.4.1**
- Nginx 1.18
- WooCommerce is _not_ installed

Thank you.

**Comment by columbian-chris** [comment]
I had this issue also after upgrading to 4.2.1 from 4.2.0 and it actually stopped showing the notice after a short amount of time for some reason.  I also am testing on another site where I'm using Elasticsearch 7.17.3 which is greater than the maximum supported version and it isn't throwing the notice for me.

**Comment by coenve** [comment]
I got the same, running 7.5.1. I would like to upgrade to 7.17.5. I think it's been a while since they updated the versions in the requirements. Maybe its time for a review?
