### ISSUE TITLE
QUESTION: epwr_decay : How to use post's post_modified_gmt instead of post_date_gmt

### ISSUE THREAD

**Issue by HypeAU** [10up/ElasticPress#2884]
Hi guys, I have posts published from 2020 but recently updated that don't show up when searched... I need the decay functions to work on post_modified_gmt not post_date_gmt for post type posts. How do I do this? thanks

My current settings are below which work  fine for published date:
add_filter( 'epwr_boost_mode', function() { return 'multiply'; } );
 add_filter( 'epwr_offset', function() { return '91d'; } ); // 90 days is good since amazon and ebay prices may not change often
 add_filter( 'epwr_scale', function() { return '123d'; } );
 add_filter( 'epwr_decay', function() { return 0.26; } );

**Comment by felipeelia** [comment]
Hey @HypeAU,

Currently, we do not have a filter to change that specifically but here is a snippet you could use to change it:

```
add_filter(
	'ep_formatted_args',
	function( $formatted_args, $args ) {
		$decay_function = apply_filters( 'epwr_decay_function', 'exp', $formatted_args, $args );
		try {
			if ( $formatted_args['query']['function_score']['functions'][0][ $decay_function ]['post_date_gmt'] ) {
				$formatted_args['query']['function_score']['functions'][0][ $decay_function ]['post_modified_gmt'] = $formatted_args['query']['function_score']['functions'][0][ $decay_function ]['post_date_gmt'];
				unset( $formatted_args['query']['function_score']['functions'][0][ $decay_function ]['post_date_gmt'] );
			}
		} catch ( \Throwable $th ) {
			/* no-op */
		}
		return $formatted_args;
	},
	99,
	2
);
```

I'm going ahead and closing this one in favor of #2896. Thanks!
