### ISSUE TITLE
QUESTION: Search reports no results found for some queries, but they work if EP is deactivated  or EP 3.6.1 is active

### ISSUE THREAD

**Issue by DenisFlorin** [10up/ElasticPress#2885]
Hello, everyone! 

Thank you in advance for taking the time to read this issue.

So,

We have a website where ElasticPress 4.0+ doesn't work well anymore after upgrading from ElasticPress 3.6.1. For example, searching for the word "spyhunter" with EP 4.0 gives no results:

![image](https://user-images.githubusercontent.com/38504865/178298987-cee60777-bd09-4104-b470-283d683cd0e5.png)

If the website has the plugin deactivated or is using EP 3.6.1, the result is shown as expected:

![image](https://user-images.githubusercontent.com/38504865/178299473-d539210d-0de4-4e52-8f11-50df8631eb94.png)

Please let me know what other information I can send to you.

After upgrading to ElasticPress 4.0, I reindexed the content. We are using version 7.10.2 for ElasticSearch.

Kind regards,

**Comment by felipeelia** [comment]
Hi @DenisFlorin,

When you reindex, do you see any errors? Also, does it return any results when you search for `spy hunter`? At last, we've changed the search algorithm in EP v4, and that may be playing a part here.

You can change the search algorithm being used with the following WP-CLI command:
`wp elasticpress set-algorithm-version --version='3.5'`
to change it back you can use
`wp elasticpress set-algorithm-version --default`

Can you try those and let us know the results? Thanks!

**Comment by DenisFlorin** [comment]
Hello @felipeelia,

Thank you for your time reading the issue and feedback.

I tried to search for the keyword "spy hunter", but no results were found. When I reindexed the content, I looked over the process, and I didn't see any errors.

Changing back to the algorithm version 3.5 seems to work. Will this version be removed in the future?

Kind regards,

**Comment by felipeelia** [comment]
We don't have any plans to remove that version @DenisFlorin. In fact, plans are to make things easier to change the algorithm being used.

The fact that it is not finding any post using 4.0's algorithm is weird, though, because it should be finding a simple term. Do you mind sharing how you have the weighting dashboard set and double check if English is set as the language on the Settings page?

**Comment by DenisFlorin** [comment]
Hi @felipeelia,

Attached are the screenshots with the weighting dashboard.
![2022-07-18_15-11](https://user-images.githubusercontent.com/38504865/179508732-05bdd2d9-7f45-45af-b29b-fed18b78b346.png)
![2022-07-18_15-11_1](https://user-images.githubusercontent.com/38504865/179508762-88fb0b09-f604-42c9-a797-76d4a8c12470.png)


The English language is set as the language in Settings.
![2022-07-18_15-12](https://user-images.githubusercontent.com/38504865/179508858-24c00330-ec9f-42cb-a60b-1c8134853b47.png)


If you want, I can give access to the development website to have a look over this "problem".

Kind regards,

**Comment by felipeelia** [comment]
I should've been clearer @DenisFlorin, sorry. I meant ElasticPress's Settings Page, not WordPress :)

Do you think it would be possible for you to install [the debugging plugins](http://10up.github.io/ElasticPress/tutorial-debugging.html), revert it to the 4.0 search algorithm, and share with us the Query Args and Body contents of Debug Bar ElasticPress? Thanks!
