### ISSUE TITLE
After bulk index is complete, ensure all posts were indexed

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#289]
It's possible to have the index operation complete and only have a small portion of posts indexed.

This may be fixed by the addition of #286, but it would still be nice to do a final check against `num_docs` reported by the index to ensure what we think we sent over was actually received.

**Comment by Stayallive** [comment]
It looks like #287 fixed the silently non synced posts for me.

I had one post missing in about 40k and that errored out nicely in 1.5.

And since there is the `ep_post_sync_kill` filter this might not even be reliable.
