### ISSUE TITLE
QUESTION: Search by Product SKU not working with standard url param pattern

### ISSUE THREAD

**Issue by btweedy2879** [10up/ElasticPress#2895]
**Describe your question**

Our site has a custom theme that seems to be causing an issue with Searching by sku.  It does not seem to work when using the standard url param search (https://v1tactical.com/?s=KEKSA&post_type=product#search). Autosuggest works but as soon as the user hits the enter key, an empty result is returned.  

I have narrowed the issue to the theme as switching to one of the default themes solves the problem.   

WP, Woocommerce and the elasticpress plugin are all the most recent versions.  

I installed the debug toolbar and see an error that says No mapping found for [meta._sort_order.long] in order to sort on.  

My question is, is there a way I can somehow solve this by inserting some additional data into every query?   

I'm trying to avoid having to go through all of my theme code (there's a lot) and try to track down what's causing this.   As a note, everything was working fine until we recently updated WP, WC and PHP from 7.2 to 7.4.

I have included all of the output from the debugging toolbar below.  

**DEBUG PANEL:** 
 Array
(
    [url] => http://localhost:9200/v1tacticalcom-post-1/_search?track_total_hits=true
    [args] => Array
        (
            [method] => POST
            [timeout] => 5
            [redirection] => 5
            [httpversion] => 1.0
            [user-agent] => WordPress/5.9.3; https://v1tactical.com
            [reject_unsafe_urls] => 
            [blocking] => 1
            [headers] => Array
                (
                    [Content-Type] => application/json
                )

            [cookies] => Array
                (
                )

            [body] => {"from":0,"size":20,"sort":[{"meta._sort_order.long":{"order":"asc"}}],"query":{"function_score":{"query":{"bool":{"should":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"KEKSA","type":"phrase","fields":["post_title^1","post_excerpt^1","post_content^1","meta._sku.value^10","terms.product_cat.name^1","terms.manufacturer.name^1","terms.caliber.name^1","terms.model.name^1","terms.finish.name^1","terms.actions.name^1","terms.product_family.name^1","terms.product_frame.name^1","terms.ep_custom_result.name^9999"],"boost":3}},{"multi_match":{"query":"KEKSA","fields":["post_title^1","post_excerpt^1","post_content^1","meta._sku.value^10","terms.product_cat.name^1","terms.manufacturer.name^1","terms.caliber.name^1","terms.model.name^1","terms.finish.name^1","terms.actions.name^1","terms.product_family.name^1","terms.product_frame.name^1","post_title.suggest^1","term_suggest^1"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"KEKSA","type":"cross_fields","fields":["post_title^1","post_excerpt^1","post_content^1","meta._sku.value^1","terms.product_cat.name^1","terms.manufacturer.name^1","terms.caliber.name^1","terms.model.name^1","terms.finish.name^1","terms.actions.name^1","terms.product_family.name^1","terms.product_frame.name^1","terms.ep_custom_result.name^1"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"product"}}]}}]}},"functions":[{"exp":{"post_date_gmt":{"scale":"14d","decay":0.25,"offset":"7d"}}},{"weight":0.001000000000000000020816681711721685132943093776702880859375}],"score_mode":"sum","boost_mode":"multiply"}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_type.slug":["auction"]}},{"terms":{"terms.product_cat.slug":["gift-card"]}},{"terms":{"terms.auction_visibility.term_taxonomy_id":[7224,7227,7226]}}]}},{"bool":{"must":[{"exists":{"field":"meta._sort_order"}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}}]}},"aggs":{"terms":{"filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_type.slug":["auction"]}},{"terms":{"terms.product_cat.slug":["gift-card"]}},{"terms":{"terms.auction_visibility.term_taxonomy_id":[7224,7227,7226]}}]}},{"bool":{"must":[{"exists":{"field":"meta._sort_order"}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}}]}},"aggs":{"category":{"terms":{"size":10000,"field":"terms.category.slug"}},"post_tag":{"terms":{"size":10000,"field":"terms.post_tag.slug"}},"post_format":{"terms":{"size":10000,"field":"terms.post_format.slug"}},"product_cat":{"terms":{"size":10000,"field":"terms.product_cat.slug"}},"product_tag":{"terms":{"size":10000,"field":"terms.product_tag.slug"}},"product_shipping_class":{"terms":{"size":10000,"field":"terms.product_shipping_class.slug"}},"manufacturer":{"terms":{"size":10000,"field":"terms.manufacturer.slug"}},"caliber":{"terms":{"size":10000,"field":"terms.caliber.slug"}},"model":{"terms":{"size":10000,"field":"terms.model.slug"}},"finish":{"terms":{"size":10000,"field":"terms.finish.slug"}},"actions":{"terms":{"size":10000,"field":"terms.actions.slug"}},"product_family":{"terms":{"size":10000,"field":"terms.product_family.slug"}},"product_frame":{"terms":{"size":10000,"field":"terms.product_frame.slug"}},"special_option":{"terms":{"size":10000,"field":"terms.special_option.slug"}},"ep_custom_result":{"terms":{"size":10000,"field":"terms.ep_custom_result.slug"}},"pa_3-8":{"terms":{"size":10000,"field":"terms.pa_3-8.slug"}},"pa_4-0":{"terms":{"size":10000,"field":"terms.pa_4-0.slug"}},"pa_4-5":{"terms":{"size":10000,"field":"terms.pa_4-5.slug"}},"pa_barrel-length":{"terms":{"size":10000,"field":"terms.pa_barrel-length.slug"}},"pa_caliber-option":{"terms":{"size":10000,"field":"terms.pa_caliber-option.slug"}},"pa_requires_ffl":{"terms":{"size":10000,"field":"terms.pa_requires_ffl.slug"}}}}},"track_total_hits":true}
            [compress] => 
            [decompress] => 1
            [sslverify] => 1
            [sslcertificates] =>
            [stream] => 
            [filename] => 
            [limit_response_size] => 
            [time_start] => 1657841775.0301
            [_redirection] => 5
            [time_stop] => 1657841775.0347
            [duration] => 4.565954208374
        )

    [r] => Array
        (
            [headers] => Requests_Utility_CaseInsensitiveDictionary Object
                (
                    [data:protected] => Array
                        (
                            [warning] => 299 Elasticsearch-7.13.2-4d960a0733be83dd2543ca018aa4ddc42e956800 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security."
                            [content-type] => application/json; charset=UTF-8
                            [content-encoding] => gzip
                            [content-length] => 307
                        )

                )

            [body] => {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [meta._sort_order.long] in order to sort on","index_uuid":"qzWbblEOQFyuv7GisK0DTw","index":"v1tacticalcom-post-1"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"can_match","grouped":true,"failed_shards":[{"shard":0,"index":"v1tacticalcom-post-1","node":"u7xfkOsRTDijB2eve-hyJQ","reason":{"type":"query_shard_exception","reason":"No mapping found for [meta._sort_order.long] in order to sort on","index_uuid":"qzWbblEOQFyuv7GisK0DTw","index":"v1tacticalcom-post-1"}}]},"status":400}
            [response] => Array
                (
                    [code] => 400
                    [message] => Bad Request
                )

            [cookies] => Array
                (
                )

            [filename] => 
            [http_response] => WP_HTTP_Requests_Response Object
                (
                    [response:protected] => Requests_Response Object
                        (
                            [body] => {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [meta._sort_order.long] in order to sort on","index_uuid":"qzWbblEOQFyuv7GisK0DTw","index":"v1tacticalcom-post-1"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"can_match","grouped":true,"failed_shards":[{"shard":0,"index":"v1tacticalcom-post-1","node":"u7xfkOsRTDijB2eve-hyJQ","reason":{"type":"query_shard_exception","reason":"No mapping found for [meta._sort_order.long] in order to sort on","index_uuid":"qzWbblEOQFyuv7GisK0DTw","index":"v1tacticalcom-post-1"}}]},"status":400}
                            [raw] => HTTP/1.1 400 Bad Request
Warning: 299 Elasticsearch-7.13.2-4d960a0733be83dd2543ca018aa4ddc42e956800 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security."
content-type: application/json; charset=UTF-8
content-encoding: gzip
content-length: 307

{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [meta._sort_order.long] in order to sort on","index_uuid":"qzWbblEOQFyuv7GisK0DTw","index":"v1tacticalcom-post-1"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"can_match","grouped":true,"failed_shards":[{"shard":0,"index":"v1tacticalcom-post-1","node":"u7xfkOsRTDijB2eve-hyJQ","reason":{"type":"query_shard_exception","reason":"No mapping found for [meta._sort_order.long] in order to sort on","index_uuid":"qzWbblEOQFyuv7GisK0DTw","index":"v1tacticalcom-post-1"}}]},"status":400}
                            [headers] => Requests_Response_Headers Object
                                (
                                    [data:protected] => Array
                                        (
                                            [warning] => Array
                                                (
                                                    [0] => 299 Elasticsearch-7.13.2-4d960a0733be83dd2543ca018aa4ddc42e956800 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security."
                                                )

                                            [content-type] => Array
                                                (
                                                    [0] => application/json; charset=UTF-8
                                                )

                                            [content-encoding] => Array
                                                (
                                                    [0] => gzip
                                                )

                                            [content-length] => Array
                                                (
                                                    [0] => 307
                                                )

                                        )

                                )

                            [status_code] => 400
                            [protocol_version] => 1.1
                            [success] => 
                            [redirects] => 0
                            [url] => http://localhost:9200/v1tacticalcom-post-1/_search?track_total_hits=true
                            [history] => Array
                                (
                                )

                            [cookies] => Requests_Cookie_Jar Object
                                (
                                    [cookies:protected] => Array
                                        (
                                        )

                                )

                        )

                    [filename:protected] => 
                    [data] => 
                    [headers] => 
                    [status] => 
                )

        )

    [class] => Requests
    [stack_trace] => Array
        (
            [0] => Debug_Bar_WP_Http->after_http_request
            [1] => WP_Hook->apply_filters
            [2] => WP_Hook->do_action
            [3] => do_action('http_api_debug')
            [4] => WP_Http->request
            [5] => wp_remote_request
            [6] => ElasticPress\Elasticsearch->remote_request
            [7] => ElasticPress\Elasticsearch->query
            [8] => ElasticPress\Indexable->query_es
            [9] => ElasticPress\Indexable\Post\QueryIntegration->get_es_posts
            [10] => WP_Hook->apply_filters
            [11] => apply_filters_ref_array('posts_pre_query')
            [12] => WP_Query->get_posts
            [13] => WP_Query->query
            [14] => WP->query_posts
            [15] => WP->main
            [16] => wp
            [17] => require('wp-blog-header.php')
        )

)

  **ELASTICPRESS PANEL:** 

  curl -XPOST -H 'Content-Type: application/json' -d '{"from":0,"size":20,"sort":[{"meta._sort_order.long":{"order":"asc"}}],"query":{"function_score":{"query":{"bool":{"should":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"KEKSA","type":"phrase","fields":["post_title^1","post_excerpt^1","post_content^1","meta._sku.value^10","terms.product_cat.name^1","terms.manufacturer.name^1","terms.caliber.name^1","terms.model.name^1","terms.finish.name^1","terms.actions.name^1","terms.product_family.name^1","terms.product_frame.name^1","terms.ep_custom_result.name^9999"],"boost":3}},{"multi_match":{"query":"KEKSA","fields":["post_title^1","post_excerpt^1","post_content^1","meta._sku.value^10","terms.product_cat.name^1","terms.manufacturer.name^1","terms.caliber.name^1","terms.model.name^1","terms.finish.name^1","terms.actions.name^1","terms.product_family.name^1","terms.product_frame.name^1","post_title.suggest^1","term_suggest^1"],"boost":1,"fuzziness":"auto","operator":"and"}},{"multi_match":{"query":"KEKSA","type":"cross_fields","fields":["post_title^1","post_excerpt^1","post_content^1","meta._sku.value^1","terms.product_cat.name^1","terms.manufacturer.name^1","terms.caliber.name^1","terms.model.name^1","terms.finish.name^1","terms.actions.name^1","terms.product_family.name^1","terms.product_frame.name^1","terms.ep_custom_result.name^1"],"boost":1,"analyzer":"standard","tie_breaker":0.5,"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"product"}}]}}]}},"functions":[{"exp":{"post_date_gmt":{"scale":"14d","decay":0.25,"offset":"7d"}}},{"weight":0.001000000000000000020816681711721685132943093776702880859375}],"score_mode":"sum","boost_mode":"multiply"}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_type.slug":["auction"]}},{"terms":{"terms.product_cat.slug":["gift-card"]}},{"terms":{"terms.auction_visibility.term_taxonomy_id":[7224,7227,7226]}}]}},{"bool":{"must":[{"exists":{"field":"meta._sort_order"}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}}]}},"aggs":{"terms":{"filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[6]}},{"terms":{"terms.product_type.slug":["auction"]}},{"terms":{"terms.product_cat.slug":["gift-card"]}},{"terms":{"terms.auction_visibility.term_taxonomy_id":[7224,7227,7226]}}]}},{"bool":{"must":[{"exists":{"field":"meta._sort_order"}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","acf-disabled"]}}]}},"aggs":{"category":{"terms":{"size":10000,"field":"terms.category.slug"}},"post_tag":{"terms":{"size":10000,"field":"terms.post_tag.slug"}},"post_format":{"terms":{"size":10000,"field":"terms.post_format.slug"}},"product_cat":{"terms":{"size":10000,"field":"terms.product_cat.slug"}},"product_tag":{"terms":{"size":10000,"field":"terms.product_tag.slug"}},"product_shipping_class":{"terms":{"size":10000,"field":"terms.product_shipping_class.slug"}},"manufacturer":{"terms":{"size":10000,"field":"terms.manufacturer.slug"}},"caliber":{"terms":{"size":10000,"field":"terms.caliber.slug"}},"model":{"terms":{"size":10000,"field":"terms.model.slug"}},"finish":{"terms":{"size":10000,"field":"terms.finish.slug"}},"actions":{"terms":{"size":10000,"field":"terms.actions.slug"}},"product_family":{"terms":{"size":10000,"field":"terms.product_family.slug"}},"product_frame":{"terms":{"size":10000,"field":"terms.product_frame.slug"}},"special_option":{"terms":{"size":10000,"field":"terms.special_option.slug"}},"ep_custom_result":{"terms":{"size":10000,"field":"terms.ep_custom_result.slug"}},"pa_3-8":{"terms":{"size":10000,"field":"terms.pa_3-8.slug"}},"pa_4-0":{"terms":{"size":10000,"field":"terms.pa_4-0.slug"}},"pa_4-5":{"terms":{"size":10000,"field":"terms.pa_4-5.slug"}},"pa_barrel-length":{"terms":{"size":10000,"field":"terms.pa_barrel-length.slug"}},"pa_caliber-option":{"terms":{"size":10000,"field":"terms.pa_caliber-option.slug"}},"pa_requires_ffl":{"terms":{"size":10000,"field":"terms.pa_requires_ffl.slug"}}}}},"track_total_hits":true}' 'http://localhost:9200/v1tacticalcom-post-1/_search?track_total_hits=true'

**Comment by felipeelia** [comment]
Hi @btweedy2879,

Your theme is trying to order results using the `_sort_order` meta field. As that field's key start with a `_`, it is not indexed by default, causing the error you are seeing.

You can try to add the following snippet to your codebase and resync your content again:
```
add_filter(
	'ep_prepare_meta_allowed_protected_keys',
	function ( $meta_keys ) {
		$meta_keys[] = '_sort_order';
		return $meta_keys;
	}
);
```
