### ISSUE TITLE
QUESTION: how to index millions of comments?

### ISSUE THREAD

**Issue by bsabalaskey** [10up/ElasticPress#2897]
**Describe your question**

Instead of creating a bug report initially, I wanted to ask how to enable searching of comments where there are quite a lot of them. I have a database of over 1.5 million comments. When I run the WP CLI (wp elasticpress index), the result is a message of 'Killed' . Running the Delete All Data and Sync process from the admin screen, I get a "Sync failed" message. There is no index created. If I do not enable the comments indexing, that runs OK with some 80K posts of various custom post types, although that takes many hours as advertised. I did try changing the posts per run down to 100 instead of 350 default but that didn't help. I even increased PHP 7.4 memory limit to 1024M (1G).

Is there any filter hook or other method to chunk the indexing to support such a large number? Writing custom code for that is no problem.

I run my own instance of Elasticsearch server, currently 7.17.

**Comment by oscarssanchez** [comment]
@bsabalaskey did you get any meaningful errors on the sync page?

**Comment by bsabalaskey** [comment]
Sorry, no other details, Just 'Killed' on WP CLI and 'Sync failed' in the backend log window. My WP server has 8G RAM with about 3.25G available. My Elasticsearch server has 16G RAM with about 6G free.

**Comment by bsabalaskey** [comment]
@oscarssanchez After putting in some debug code and looking at server stats (with glances), this is clearly an out of memory issue for large datasets, so Linux kills the process. RAM usage goes up for every per-page chunk, so it looks like some forced garbage collection is minimally needed to stop using so much RAM.

**Comment by bsabalaskey** [comment]
@oscarssanchez The offending statement is the WP comment query trying to get a total comment count, which tries to read all the millions of comments into memory and thus blows up even after many GB. That statement is in the query_db() method in includes/classes/Indexable/Comment/Comment.php.
```
$all_query = new WP_Comment_Query( $all_query_args );
$total_objects = count( $all_query->comments );
```

So I wrote an SQL optimized version of that which just gets the count and doesn't use astronomical amounts of RAM. Then comment import works, although it takes a very long time with 1.5 million records. I am getting about 150 comments per second imported using a per-page of 1200. Here is my updated code (this depends on post_type always being set, which it should be for any normal site):

```
global $wpdb;
$sql = "SELECT COUNT(c.comment_ID) FROM `{$wpdb->comments}` c JOIN `{$wpdb->posts}` p ON (p.ID = c.comment_post_ID) ";
if ( ! empty( $all_query_args['post_type'] ) ) {
   if ( ! is_array( $all_query_args['post_type'] ) ) {
     $all_query_args['post_type'] = array( $all_query_args['post_type'] );
   }
   $sql .= "WHERE p.post_type IN ('" . implode( "','", $all_query_args['post_type'] ) . "') ";
}
if ( ! empty( $all_query_args['post_status'] ) ) {
   if ( ! is_array( $all_query_args['post_status'] ) ) {
     $all_query_args['post_status'] = array( $all_query_args['post_status'] );
   }
   $sql .= "AND p.post_status IN ('" . implode( "','", $all_query_args['post_status'] ) . "') ";
}
if ( ! empty( $all_query_args['status'] ) ) {
   if ( ! is_array( $all_query_args['status'] ) ) {
     $all_query_args['status'] = array( $all_query_args['status'] );
   }
   $sql .= "AND c.comment_approved IN ('" . implode( "','", $all_query_args['status'] ) . "') ";
}
if ( ! empty( $all_query_args['type'] ) ) {
   if ( ! is_array( $all_query_args['type'] ) ) {
     $all_query_args['type'] = array( $all_query_args['type'] );
   }
   $sql .= "AND c.comment_type IN ('" . implode( "','", $all_query_args['type'] ) . "') ";
}	
$total_objects = $wpdb->get_var( $sql );
```

**Comment by felipeelia** [comment]
That is great, thanks for sharing @bsabalaskey. I've opened #2903 now with a similar approach but leveraging WordPress's native functionalities. Would it be possible for you to give that change a try?

Fwiw, another possible approach would be the following snippet. With that in place, we'd retrieve only IDs instead of full objects:
```
add_filter(
	'ep_comment_all_query_db_args',
	function( $args ) {
		$args['fields'] = 'ids';
		return $args;
	}
);
```

Thanks!

**Comment by bsabalaskey** [comment]
Your update works fine for me (https://github.com/10up/ElasticPress/pull/2903), thanks. Since I know SQL well, I wrote the most optimized query for huge comment numbers and made the DB server do all the work.
