### ISSUE TITLE
Partial Exact Match Search Query

### ISSUE THREAD

**Issue by sirmbhe** [10up/ElasticPress#2904]
Hi.

I have an issue to tackle on my wordpress search result using Elasticsearch/Elasticpress.

I notice that if I look for a word, for example : Abbott
The search result that came up is: Abbott, Abnett, and even Betty.

The same stuff happen when I am doing search on 2 words or more.
Is there any way to narrow down the search result, giving me only the exact word that I search?

I am trying to follow the guide on this page: [https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/](https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/)
But the result is. Some word is giving the proper result, but for some other word it isn't giving any result at all.

Thank you

**Comment by felipeelia** [comment]
Hey @sirmbhe.

Can you please try with the following snippet?
```
add_filter( 'ep_match_fuzziness', '__return_zero' );
```

That should disable fuzziness for the search algorithm we are using on ElasticPress 4.0.

I am going to close the issue right now but if you still face any problems please let us know and we can reopen if needed. Thanks!
