### ISSUE TITLE
BUG: Custom posts don't appear in Related Posts 

### ISSUE THREAD

**Issue by salvoaranzulla** [10up/ElasticPress#2905]
**Describe the bug**

My ElasticPress indexes posts and custom posts. Custom posts appear in search, but the custom posts don't appear in Related Posts. It seems that Related Posts shows only posts. 

**Steps to Reproduce**

I have created a custom post with the same content and title of a regular post. In the custom post page, Related Post shows the link to regular post, but not vice versa. 

**Expected behavior**

Custom posts in Related Posts, if custom posts are indexed from ElasticPress

**Comment by felipeelia** [comment]
Hey @salvoaranzulla,

You can change that using the following snippet:
```
add_filter(
	'ep_find_related_args',
	function( $args ) {
		$args['post_type'] = [ 'post', 'page' ];
		return $args;
	}
);
```
replacing `page` with your custom post type slug.
