### ISSUE TITLE
ElasticPress is affecting TTFB

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2910]
I have a large WooCommerce site with ElasticPress, and noticed that with the ElasticPress plugin enabled, the product category archive has a TTFB of 1.9s, however if I disable EP, I get a TTFB of only 425ms. (Measured with GTMetrix)

My Woo archive page has around 40 taxonomy facets, and the site has around 60k products.

Is there any way to find out what is causing this major slow down?

Thanks!

**Comment by lkraav** [comment]
> Is there any way to find out what is causing this major slow down?

So what was it?
