### ISSUE TITLE
BUG: synchronisation problem in my enviroment (elasticsearch cluster)

### ISSUE THREAD

**Issue by IIM-Andreas** [10up/ElasticPress#2918]
**Describe the bug**
When I publish a new post it's not found after a while in the searchbox from elasticpress.

**Expected behavior**
The post is found in the searchbox.

**Environment information**
 - Browser and version: 103.0.5060.134
 - WordPress version: 6.0
 - ElasticPress version: 4.2.2
 - Elasticsearch version: 6.3
 - Where do you host your Elasticsearch server? Timme-Hosting
 - What ElasticPress features do you have currently active? Post Search, Autosuggest, Related Posts

**Additional context**
Hi we have 3 servers. Each runs a WordPress, a database and an ElasticSearch node. The 3 ElasticSearch nodes are connected to form a cluster. ElasticPress accesses its own ElasticSearch Node (localhost in ElasticPress settings). 
Does ElasticPress even create the indexes correctly with replication across the cluster?
Or does each ElasticPress per server keep its own autonomous indexes that are not coupled?

**Comment by dustinrue** [comment]
Beyond telling you in its server health report, ElasticPress is unaware of if it is connecting to a single node or a cluster. Assuming your cluster is configured properly, and it is indeed acting as a cluster, the data is automatically spread across the available nodes. By default, EP requests 5 shards and 1 replica. 

If you are having data go missing you will want to ensure your cluster is formed properly, operating in a stable fashion and that you don't have any custom code that would cause issues like deleting or incorrectly updating content.
