### ISSUE TITLE
BUG: Search Results Showing That Don't Contain The Search Term

### ISSUE THREAD

**Issue by adam-vanbuskirk** [10up/ElasticPress#2920]
**Describe the bug**
When searching for a term on our site (topclassactions.com), the results contain many posts that do not contain the search term. You can use _**kashima**_ as an example. We have a DB of 3GB+ in Prod. The lower life cycle (Dev & Staging) return the correct results. The plugin is not. modified. I cannot figure out why our search returns bad results in Prod. 

When this would happen previosuly, I would rebuild the index and it would fix itself. Now, rebuilding or syncing the index doesn't even fix it.

**Steps to Reproduce**

1. Go to topclassactions.com
2. Click the hour glass at the top right, enter kashima, an press enter.
3. Click on page 6 in the pagination and find the post titled Kellog Hit with Class Action Lawsuit Over 'Real Fruit' Claims and do a control F for kashima and you won't find it. There are several other examples in that same search feed that don't contain the term.

**Expected behavior**
It should only return posts that contain the search term, in this case kashima

**Screenshots**
![image](https://user-images.githubusercontent.com/94007137/182447421-5e331d45-7b76-4d02-9984-e0bcce802ac3.png)
![image](https://user-images.githubusercontent.com/94007137/182447493-b3520f0e-cb61-4fbf-8270-f3b22231a2ae.png)

**Environment information**
 - WordPress version: 5.9.3
 - ElasticPress version: 4.2.2
 - Elasticsearch version: 7.9.3
 - What ElasticPress features do you have currently active? Post Search, Facets

**Comment by felipeelia** [comment]
Hi @adam-vanbuskirk,

This is not a bug. By default, Elasticsearch will try to find _similar_ words and not only exact matches. Looking at your screenshot I can see _Kashi_  and that is just two letters different from _**Kashi**ma_.

If you want to disable that behavior, you can use the following snippet:
```
add_filter( 'ep_match_fuzziness', '__return_zero' );
```

To read more about Elasticsearch Fuzziness, you can access [their docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/common-options.html#fuzziness).

**Comment by kevinlisota** [comment]
@felipeelia the `ep_match_fuzziness` filter is deprecated, replaced by `ep_post_match_fuzziness`. However, returning zero to the new filter does not turn off fuzzy matching. What is the equivalent snippet for 4.3.0?
