### ISSUE TITLE
QUESTION: How to modify the mapping for postmeta keys/values?

### ISSUE THREAD

**Issue by nickchomey** [10up/ElasticPress#2921]
**Describe your question**
I am indexing some postmeta fields for custom post types and have successfully used the various filters to select which keys to index. However, an ES field is generated for many different data types due to the dynamic_template in the mapping file. I can't figure out how to override this to only map `'type' => 'keyword'`. 

When I use the `ep_post_mapping` filter and do the following 

```
$mapping['mappings']['properties']['meta']['properties']['_bbp_forum_id'] = ['type' => 'keyword'];
unset($mapping['mappings']['dynamic_templates']['template_meta_types']);
```

I just get the following error:
```
 [mapper_parsing_exception] failed to parse field [meta._bbp_forum_id] of type [keyword] in document with id '3739'. Preview of field's value: '{date=1970-01-01, datetime=1970-01-01 00:00:01, boolean=false, double=3735, raw=3735, time=00:00:01, value=3735, long=3735}'
```

It will only index if I leave the dynamic mapping as-is, OR index it outside of the `meta` object field by using the `ep_post_sync_args_post_prepare_meta` filter and something like `$post_args['_bbp_forum_id']  = (int) $post_meta['_bbp_forum_id'];`

Any tips?

Here's the relevant segment of the mapping file.

```
array(
'template_meta_types' => array(
	'path_match' => 'meta.*',
	'mapping'    => array(
		'type'       => 'object',
		'properties' => array(
			'value'    => array(
				'type'   => 'text',
				'fields' => array(
					'sortable' => array(
						'type'         => 'keyword',
						'ignore_above' => 10922,
						'normalizer'   => 'lowerasciinormalizer',
					),
					'raw'      => array(
						'type'         => 'keyword',
						'ignore_above' => 10922,
					),
				),
			),
			'raw'      => array( /* Left for backwards compat */
				'type'         => 'keyword',
				'ignore_above' => 10922,
			),
			'long'     => array(
				'type' => 'long',
			),
			'double'   => array(
				'type' => 'double',
			),
			'boolean'  => array(
				'type' => 'boolean',
			),
			'date'     => array(
				'type'   => 'date',
				'format' => 'yyyy-MM-dd',
			),
			'datetime' => array(
				'type'   => 'date',
				'format' => 'yyyy-MM-dd HH:mm:ss',
			),
			'time'     => array(
				'type'   => 'date',
				'format' => 'HH:mm:ss',
			),
		),
	),
),
),
```

**Comment by oscarssanchez** [comment]
Hi @nickchomey ,

Based on the error you are getting, it seems that even though you have defined the mapping explicitly you'd still need to modify the value created by prepare_meta_types()  https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable.php#L643

You might want to use the `ep_post_sync_args` to modify the data that's sent to ES for the document's meta. 

Hopefully this will solve your issue!

**Comment by nickchomey** [comment]
@oscarssanchez Thanks for the help! In the end, I decided to just index the handful of metakeys as normal fields, outside of the `meta` nested field - it just seemed much easier to deal with in every way...
