### ISSUE TITLE
BUG: Wrong error message

### ISSUE THREAD

**Issue by orasik** [10up/ElasticPress#2922]
**Describe the bug**
I have many posts to sync to ElasticSearch (500,000). I tried to sync using the plugin admin page.

After reaching 99% progress, I received an error:

`Sync Failed.  The response is not a valid JSON response.`

I tried again using the CLI, and it looked as if it was working fine, but when I checked the plugin admin page, I noticed it was showing sync failed even when the CLI process was working fine.

Then I decided to check the database for `ep_last_index` and `ep_last_cli_index`, and here I noticed this error:

```
Maximum execution time of 300 seconds exceeded
```

Which I believe is related to my PHP execution limit.

It would have been great if this error was showing on the plugin admin interface, as it would save several hours of debugging.

**Steps to Reproduce**
Have a large number of posts where syncing will take more than the PHP execution limit.
1. Go to 'ElasticPress -> Sync'
2. Click on 'Sync Now'
3. Wait for `x` seconds (based on your PHP Execution limit variable.
4. See sync failed without showing the error.

**Expected behavior**
Show the error listed in `ep_last_index` and `ep_last_cli_index` options.

**Comment by felipeelia** [comment]
Hey @orasik, thanks for opening the issue. I could partially reproduce the problem and opened #2927, it seems to fix the problem.

Would it be possible for you to run that sync via Dashboard with Chrome's Developer Tools opened and check in the Network tab what is the response from the failing AJAX request? That will help us to understand why you are getting that `The response is not a valid JSON response.` message.
