### ISSUE TITLE
QUESTION: Customizing the appearance of related posts

### ISSUE THREAD

**Issue by ChekhWasTaken** [10up/ElasticPress#2929]
**Describe your question**
From what i understood from looking thru the code for the related posts widget in `wp-content/plugins/elasticpress/includes/classes/Feature/RelatedPosts/Widget.php`, it seems that there is no straightforward way to customize the looks of the related posts, i.e. adding styles and a thumbnail. 

could you please point me to the right direction here?

**Comment by felipeelia** [comment]
Hi @ChekhWasTaken,

If you need a more detailed presentation, I recommend you to use one of these two functions:

```
\ElasticPress\Features::factory()->get_registered_feature( 'related_posts' )->find_related( $post_id, $return = 5 )
```
or
```
\ElasticPress\Features::factory()->get_registered_feature( 'related_posts' )->get_related_query( $post_id, $return = 5 )
```
More info in our docs: https://10up.github.io/ElasticPress/tutorial-features.html#related-posts
