### ISSUE TITLE
QUESTION: Auto create indices

### ISSUE THREAD

**Issue by altendorfme** [10up/ElasticPress#2936]
The server I'm using doesn't give me permission to _auto_create indices_, is there a way to set this manually?

`2222497 (Post): [security_exception] action [indices:admin/auto_create] is unauthorized for user [xyz]`

**Comment by felipeelia** [comment]
Hi @altendorfme, the indices should not be created automatically but by a specific call. Is there any specific scenario where you are getting that? Do you have the indices already created? (Visiting the Index Health subpage would list the indices you have.) If you don't have them already, you'll need to pass the `--setup` flag to the WP-CLI `index` command.

**Comment by altendorfme** [comment]
Hi @felipeelia you're right, the `--setup` was missing, but now I have another problem.

```
$ wp elasticpress index --setup --show-errors
Indexing with setup option needs to delete Elasticsearch index first, are you sure you want to delete your Elasticsearch index? [y/n] y
Success: Indexing posts…
```

Success appears, but indexing does not start.

```
$ wp elasticpress status

====== Status ======
{ }

====== End Status ======
```

```
$ wp elasticpress stats
Warning: sitecom-post-1 is not currently indexed.
```

**Comment by altendorfme** [comment]
Problem solved!

I needed to declare the ep-prefix:

`wp elasticpress index --setup --ep-prefix=prefixthatwesentyou`

It is also possible to define

`EP_PREFIX_INDEX` on wp-config.
