### ISSUE TITLE
QUESTION: How to update the index when uploading and deleting post with PHP?

### ISSUE THREAD

**Issue by leroile22** [10up/ElasticPress#2946]
**Describe your question**

I am not able to find a way to add, update or delete a post from the index using a PHP function. Do functions like these exist in this plugin: add_elastic_index($post_id), delete_elastic_index($post_id), update_elastic_index($post_id)?

In the documentation, it is stated that IndexHelper class is the central point of the process for all methods available (WP Dashboard and WP-CLI). I conclude that I would need to call the IndexHelper class to modify the index, is it the way to go?

**Comment by leroile22** [comment]
I try to read the code, I am not gonna lie I don't understand anything; there are too many classes.

If someone with knowledge on this can help, I can pay a fair price.

**Comment by felipeelia** [comment]
Hey @leroile22,

The code you want is this:
```
\ElasticPress\Indexables::factory()->get( 'post' )->index( $post_id, true );
```

The IndexHelper is the central point of the sync process that goes through *all* posts. To sync only one, that call there should do it. Ideas on how we could document that better and PRs with the addition are welcomed! Thanks.

**Comment by leroile22** [comment]
Thank you very much for the information,

I have sent CHF 20 to the PayPal account associated with your Github.

**Comment by felipeelia** [comment]
Hey @leroile22, I really appreciate the gesture, but I am just doing my job here and happily reimbursed you. Don't hesitate to pay it forward though and help someone who needs it today :slightly_smiling_face:
