### ISSUE TITLE
QUESTION: Does Related Posts feature learn from user interaction?

### ISSUE THREAD

**Issue by danylfilatov** [10up/ElasticPress#2956]
When ep shows related posts - does it always query posts that have same words in content / title, or does it also adapt to user interaction? Does it learn from "click behaviour"? Does it track which posts users click on most from the ones presented in related posts widget, and suggest those posts more, or is related posts query simply static and is only about same words found in other posts?

I found that this feature uses More Like This query from elasticsearch, but wasn't able to understand whether that query indexes click count / rates posts or not.

**Comment by felipeelia** [comment]
Hey @danylfilatov, thanks for opening the issue. It does not take user clicks into account, which would need an update of the post info in Elasticsearch on every interaction and could cause some performance penalties, especially for bigger sites.

By default, it will take into account the post title, content, and tags but you can change that behavior using the `ep_related_posts_fields` filter. See the code [here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/RelatedPosts/RelatedPosts.php#L73).
