### ISSUE TITLE
Use EP for building dashboard content lists

### ISSUE THREAD

**Issue by ChrisWiegman** [10up/ElasticPress#296]
One additional use I would like to see for EP/ES is to use it to build the post/pages/etc content lists instead of via WordPress. The advantage here is these can be some very troublesome spots on large sites due to the inefficiencies of the queries involved. Replacing the lists with results from EP could really boost performance. 

Thoughts?

**Comment by zamoose** [comment]
Maybe extend WP_List_Table?

**Comment by tlovett1** [comment]
@ChrisWiegman in the admin, front, or both?

**Comment by zamoose** [comment]
@tlovett1 admin, mainly, since it's uncacheable.

**Comment by tlovett1** [comment]
Got it. This would be a good extension plugin.

**Comment by tlovett1** [comment]
I know @AaronHolbrook started this https://github.com/10up/ElasticPress-Admin
