### ISSUE TITLE
Facets resets/removes Woocommerce default sorting orderby= query string

### ISSUE THREAD

**Issue by ouch-digital** [10up/ElasticPress#2960]
Hey EP Team, firstly thank you for creating such an amazing plugin. 

This is a little feature request to persist the orderby= query string when filtering facets in EP.

When sorting using Woocommerce orderby= (sort by price, relevance etc), when selecting a EP facet, the WC orderby query string is removed when the new page is loaded.

**Describe the solution you'd like**

It would be great if this persisted after refresh in the same way that the search s= query string is retained.

A possible solution might be to include the orderby= query into the new page refresh using $referer = wp_get_referer();

Thanks in advance and have a great day.

**Comment by felipeelia** [comment]
Hey @ouch-digital,

Thanks for the idea! We will add that in a future release. In the meantime, you can use the following snippet:
```
add_filter(
	'ep_facet_allowed_query_args',
	function ( $args ) {
		$args[] = 'orderby';
		return $args;
	}
);
```

I am marking this as a `good first issue`, as the solution in the plugin should be as simple as adding `orderby` to [this array](https://github.com/10up/ElasticPress/blob/94cb4f5fef76d28e10a3e09099997095c142145b/includes/classes/Feature/Facets/Facets.php#L502).

**Comment by ouch-digital** [comment]
Thank you! @felipeelia

That's awesome. Have a great day. I will continue to let you know if I find any small ways I can contribute to the project.

Warm regards
