### ISSUE TITLE
Is it possible to disable facets selected terms at the top?

### ISSUE THREAD

**Issue by piotrkunicki** [10up/ElasticPress#2966]
Currently when I'm using facet widget or block, when I select i.e. the last term - it's moved to the top after page refresh..

Is it possible to disable this feature? I've found order_by_selected function in Renderer.php file but unfortunately disabling it doesn't change anything..

**Comment by felipeelia** [comment]
Hey @piotrkunicki,

Unfortunately, with the current codebase that is not possible. You can rewrite the HTML completely with the [ep_facet_search_widget](http://10up.github.io/ElasticPress/ep_facet_search_widget.html) filter tough.

If you want to send us a PR making the usage of `order_by_selected` optional, that would be great. Thanks!
