### ISSUE TITLE
Documentation for #294

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#297]
#294 needs documentation.

**Comment by tlovett1** [comment]
@bordoni mind doing this?

**Comment by bordoni** [comment]
I can do it, but if there are any mentions to the `--network-wide` on the Wiki I don't have permissions to change, someone else will have to change it there.

**Comment by tlovett1** [comment]
I don't think it has any mentions.

**Comment by bordoni** [comment]
:wink:
