### ISSUE TITLE
QUESTION: Index by content and by cpt label

### ISSUE THREAD

**Issue by Finnstax** [10up/ElasticPress#2977]
Hey! We're using EP on our page and wondered the following thing:

Is it possible to index not only by content, but also by cpt label?

E.g. we have a custom post type that is called 'Job', where we save our current job listings.

If the user searches for 'job' we want the user to find all the content where 'job' is in the title, excerpt, etc. but we also want the user to find all entries of the cpt.

Is there way to add these elements?

Thanks in advance!

**Comment by felipeelia** [comment]
Hey @Finnstax,

ElasticPress already indexes the post_type slug. If that matches with the label, you could use the following snippet (largely inspired in [this blog post](https://www.elasticpress.io/blog/2020/06/custom-fields-and-weighted-search-with-elasticpress-part-2/)) to enable it as a field in the Weighting Dashboard:

```
function epio_blog_add_custom_field_ep_weighting( $fields ) {
	$key = 'post_type';

	$fields['attributes']['children'][ $key ] = array(
		'key'   => $key,
		'label' => __( 'Post Type', 'textdomain' ),
	);

	return $fields;
}
add_filter( 'ep_weighting_fields_for_post_type', 'epio_blog_add_custom_field_ep_weighting' );
```

After adding that, you will be able to make that field searchable.
