### ISSUE TITLE
QUESTION: How to add Post to sync queue?

### ISSUE THREAD

**Issue by leroile22** [10up/ElasticPress#2994]
**Describe your question**

Currently, I use the following code to add a post to the index:

- ElasticPress\Indexables::factory()->get('post' )->index( $post_id, true );

However, this is heavy as I need to index 1 million posts per day. I would like instead to add the posts to the queue AND set the the queue trigger to be 500 (index once 500 posts are in the queue). So far, I have the following:

- ElasticPress\Indexables::factory()->get( 'post' )->add_to_queue( $post_id );

I think I need to call the sync manager, I have tried a few variations with no success. I also have no idea how to set the queue limit to be 500?

**Comment by oscarssanchez** [comment]
Hi @leroile22 ,

You are probably looking for `EP_SYNC_CHUNK_LIMIT` https://github.com/10up/ElasticPress/blob/develop/includes/classes/SyncManager.php#L129
