### ISSUE TITLE
QUESTION: WP_User_Query not working

### ISSUE THREAD

**Issue by yarovikov** [10up/ElasticPress#2995]
Hi there.

I have last WP version 6.0.2 and ElasticPress plugin 4.3.0.
So,  a need search for users (username, description and more fields). I have full index without any errors but with this code is not any results:

```
$wp_user_query = new WP_User_Query([
    'search' => esc_attr($query_str),			
    'number' => 10,			
    'ep_integrate' => true,
]);
```

Has anyone had a similar problem? Thanks 🙌

**Comment by yarovikov** [comment]
Hi again

I'v used following code. It's works.

```
$wp_user_query = new WP_User_Query([
	'search' => esc_attr($query_str),	
	'search_columns' => [
		'user_nicename',
		'display_name'
	],
	'search_fields' => [
		'meta' => [
			'display_name',
			'first_name',
			'last_name',
			'description',			
		],
	],
	'ep_integrate' => true,
]);
```

But i have mismatched results searching by user name. How can i fix this?

Thanks

**Comment by felipeelia** [comment]
Hi @yarovikov,

What do you mean by mismatched results? By default, it will allow some fuzziness in the results, so for example if someone searches for `yarovokov` it would also match `yarovikov`, as it has only 1 char difference. Is that what you are referring to?

Also, looking at the code that [interprets the search fields to be used](https://github.com/10up/ElasticPress/blob/4.3.0/includes/classes/Indexable/User/User.php#L390-L467), you could merge both `search_columns` and `search_fields` in a single array.

**Comment by ws256** [comment]
Hi @felipeelia
To make the parameters relevant, we used the parameter `'orderby' => 'relevance'` WP_User_Query
But I would like to use other sorting options as well.
quote from documentation "You can sort by multiple fields as well i.e. title meta.my_key.raw"
`'orderby' => 'relevance meta.my_key.long',`
Only one sort option works, the one listed first. 
If you use parameters
`'orderby' => 'title meta.my_key.raw',`
i get error 400 bad request. Other combinations can also cause this error.
Tell me why so?
