### ISSUE TITLE
QUESTION: How to re-rank searching results based on number of page views?

### ISSUE THREAD

**Issue by AndersonatAMC** [10up/ElasticPress#2996]
Hi I'm using ElasticPress and have bought ElasticPress.io subscription. Now the searching is fast, but I want the searching index re-rank based on number of page views, i.e. if a page has been visited many more times, it should show up at the top of searching results. May I ask if there is any way to do it? Thank you.

**Comment by ws256** [comment]
Usually the number of views is fixed in a custom field. Sort by it. orderby parameter.
https://github.com/terrence-gonsalves/elasticsearch-indexer#user-content-supported-wp_query-parameters

**Comment by oscarssanchez** [comment]
Hi @AndersonatAMC ,

Your indexed documents do not store page views as a field, so this is something you "might" want to add manually using a custom field, like it was suggested.

That said, you'll have to take into account the scalability of that approach.

Say you have 70,000 posts and you get 100,000 visits each day. To accurately know whether a page has more views than others you'll need to update post meta 100,000 x 70,000, this will also trigger the same amount of reindexing operations of your fields in ElasticSearch, which can easily cause more harm than good. So my first thought is not to go with it.

We'd be happy to work with you on ElasticPress.io if you want to shoot us a message in our support chat, maybe we'd be able to find an alternative approach to better your search experience.
