### ISSUE TITLE
QUESTION: I maintain a news website and I have problem with saving the big categories (Wordpress)

### ISSUE THREAD

**Issue by catalinoprea** [10up/ElasticPress#2999]
**Saving / editing big categories**
When editing the big categories (the categories that have thousands of articles associated) the server enters in timeout (I cannot alter this) because of indexing. How can I stop elasticpress from indexing on category / tag (taxonomy) edit ?

I suppose that there is an action / filter which I can use, but the list is huge and the description is laconic. 

Please help.

**Comment by felipeelia** [comment]
Hey @catalinoprea, you can stop ElasticPress from indexing on a taxonomy edit:

```
add_filter( 'ep_skip_action_edited_term', '__return_true' );
```

If you want to make that decision based on the number of posts associated with the term in question, you can use a code like this:

```
function ep_2999_skip_action_edited_term( $skip, $term_id, $tt_id, $taxonomy, $object_ids ) {
	if ( count( $object_ids ) > 100 ) { // Change 100 to the number you want
		return true;
	}
	return $skip;
}
add_filter( 'ep_skip_action_edited_term', 'ep_2999_skip_action_edited_term', 10, 5 );
```

Just keep in mind that you will need to manually sync everything once you have made all the changes you need.
