### ISSUE TITLE
QUESTION: I cannot show the facets in the side bar

### ISSUE THREAD

**Issue by pranavstorepro** [10up/ElasticPress#3003]
The facets and Related Posts are not appearing in the side bar

**Describe your question**
I have configured Elastic press and search is working very well.But ,the facets and related posts in the side bar widget never shows!

https://prnt.sc/c8E95sUsF5iK
https://prnt.sc/3snnio06u3DB

I researched a bit,but unable to solve.Am i missing something.I have activated storefront theme to check ,if there is any conflct.But it is not.
Apperciates your help!
Pranav

**Comment by mazharrehman** [comment]
I have the same issue, After update ElasticPress 3.6.6 to 4^ than facets is not working any more.

**Comment by pranavstorepro** [comment]
It'd worked automatically.
@glow7020 ,my case update not caused the issue!
Thanks

**Comment by oscarssanchez** [comment]
Hi @pranavstorepro , @glow7020 

Can you please share some steps to reproduce? There are cases where faceting and related posts is not supposed to show anything.

Thanks!
