### ISSUE TITLE
BUG:  Adding synonyms causes indexing to fail

### ISSUE THREAD

**Issue by mcarfgit** [10up/ElasticPress#3005]
**Describe the bug**
The elasticpress.io plugin is installed in a Woocommerce store with approx 10,500 products.  When synonyms are added within the elasticpress plugin admin screen, indexing throws an error.   Removing the synonyms allows the indexing to run as expected.

Here's a screen shot showing the error:

![image](https://user-images.githubusercontent.com/113728942/190788737-1b96a9d0-5278-4551-bfaa-0a483f5acb64.png)

Environment info:

![image](https://user-images.githubusercontent.com/113728942/190790145-977ff3b6-7d41-4921-a446-d01dc664642c.png)

Using Bonsai.io as Elasticsearch host

**Comment by felipeelia** [comment]
Hi @mcarfgit, what are the synonyms you are setting? This might be related to #2877.
