### ISSUE TITLE
Need to include product attribute search for some product categories in the facet

### ISSUE THREAD

**Issue by pranavstorepro** [10up/ElasticPress#3013]
Hi,

I just need a help to configure product attributes inside product categories in facets.

for example in the side bar facet appears as this https://imgur.com/a/k3xBo42 .I need to add attributes for some of these categories,which should look like a another search facet just below

I was checking its possibilty using the hook ep_facet_search_widget,but could not make it

Any Idea on this?

Thanks
Pranav

**Comment by oscarssanchez** [comment]
Hi @pranavstorepro ,

If I understand correctly you want the facet to be as an example:

`Upper Parts -> Pistols -> red`

This is not possible and would require some custom coding.

You are right that you'll need to use `ep_facet_search_widge`t to achieve it. You might need to either check for all posts that have the pa (as I remember this is post meta, not a sub category) or check the aggregations, which ElasticPress uses to build the facet data.

Alternatively, you might want to add another facet just for the product attributes. This way things might be cleaner and you still will be able to just facet by the options available for the specific filtering scenario.
