### ISSUE TITLE
Strange JSON error on woocommerce place order

### ISSUE THREAD

**Issue by jeremylugros** [10up/ElasticPress#3014]
Hi team,
after the plugin was installed, synced, and configured, we have tested and found an error when order was placed on checkout page. 
The page started loading, and then the session expired right after.
The developer console shows and error on the request response, of an unexpected character on the JSON data.
Analyzing the response, the order was successfully placed, but all the order-received page content was coming with the usual json response. 

For example, this would be the usual response: 

{"result":"success","redirect":"https:\/\/www.yyyyy.com.br\/checkout\/order-received\/2270151\/?key=wc_order_uQbacazevG9dJ","order_id":2270151} 

But then, the response was:

{"result":"success","redirect":"https:\/\/www.yyy.com.br\/checkout\/order-received\/2270152\/?key=wc_order_NpeVJElsIncrV","order_id":2270152}<style>.elementor-2268320 .elementor-element.elementor-element-7aa2b0b5{transition:background 0.3s, border 0.3s, border-radius 0.3s, box-shadow 0.3s;margin:0px 0px 80px 0px;}.elementor-2268320 .elementor-element.elementor-element-7aa2b0b5 > .elementor-background-overlay{transition:background 0.3s, border-radius 0.3s, opacity 0.3s;}.elementor-2268320 .elementor-element.elementor-element-226a4968 > .elementor-element-"

... and many many other lines, with all the rest of the page content.

After some tests with other users and the same error,
the plugin was deactivated and the json response was normal again.

Any idea why this is happening?
We´ve tried in one of the tests syncing protected data, but the error happened all the same.

The site is running on a wordpress / woocommerce install, on cyberpanel / ubuntu.
Elastic search is on latest version. 
We´re also using Litespeed cache, together with Redis object cache.

Site health details below (everything is green/checked/ok)
Versão do WooCommerce: 		5.6.2
Pacote do WooCommerce REST API: 		5.6.2 /home/yyyy.com/public_html/wp-content/plugins/woocommerce/includes
Pacote do Blocos do WooCommerce: 		5.5.1 /home/yyyy.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Pacote do Agendador de ações: 		3.4.0 /home/yyyy.com/public_html/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler
WooCommerce Admin package: 		2.5.2 /home/yyyy.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Diretório gravável de registros: 		/home/yyyy.com/public_html/wp-content/uploads/wc-logs/
Versão do WordPress: 		6.0.2	
WordPress multisite: 		–
Limite de memória do WordPress: 		768 MB	
Modo de depuração do WordPress: 		
WordPress cron: 		–
Idioma: 		pt_BR
Cache de objeto externo: 		
Ambiente do servidor
Informações do servidor: 		LiteSpeed
Versão do PHP: 		7.4.30	
Tamanho máximo para post no PHP: 		15 MB
Limite de tempo do PHP: 		80
Máximo de entrada de variáveis (max input vars) do PHP: 		1000
Versão do cURL: 		7.68.0, OpenSSL/1.1.1f
SUHOSIN instalado: 		–
Versão do MySQL: 		5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1	
Tamanho máximo de upload: 		15 MB
O fuso horário padrão é UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte string: 		
Requisição remota do tipo POST: 		
Requisição remota do tipo GET: 		
Banco de dados
Versão do banco de dados do WooCommerce: 		5.6.2
Prefixo do banco de dados 	  	wp_ws4m908v40_	
Tamanho total do banco de dados 	  	2592.56MB
Tamanho dos dados do banco de dados 	  	1636.85MB
Tamanho do índice do banco de dado 	  	955.71MB
wp_ws4m908v40_woocommerce_sessions 	  	Dados: 35.06MB + Índex: 2.02MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_api_keys 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_attribute_taxonomies 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_downloadable_product_permissions 	  	Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_order_items 	  	Dados: 17.55MB + Índex: 4.52MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_order_itemmeta 	  	Dados: 96.64MB + Índex: 110.28MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_tax_rates 	  	Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_tax_rate_locations 	  	Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_shipping_zones 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_shipping_zone_locations 	  	Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_shipping_zone_methods 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_payment_tokens 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_payment_tokenmeta 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_log 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
cache_data 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
Produtos 	  	Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
Produtos3 	  	Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
tiny 	  	Dados: 0.08MB + Índex: 0.00MB + mecanismo InnoDB
woof_query_cache 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_cielo_api_jrossetto 	  	Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_404_to_301 	  	Dados: 4.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_acfw_store_credits 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_actionscheduler_actions 	  	Dados: 10.02MB + Índex: 14.23MB + mecanismo InnoDB
wp_ws4m908v40_actionscheduler_claims 	  	Dados: 0.38MB + Índex: 0.22MB + mecanismo InnoDB
wp_ws4m908v40_actionscheduler_groups 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_actionscheduler_logs 	  	Dados: 8.52MB + Índex: 7.03MB + mecanismo InnoDB
wp_ws4m908v40_ac_abandoned_cart_history_lite 	  	Dados: 4.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_ac_email_templates_lite 	  	Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_ac_guest_abandoned_cart_history_lite 	  	Dados: 0.23MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_ac_sent_history_lite 	  	Dados: 0.11MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_berocket_termmeta 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_bv_fw_requests 	  	Dados: 6.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_bv_ip_store 	  	Dados: 0.17MB + Índex: 0.22MB + mecanismo InnoDB
wp_ws4m908v40_bv_lp_requests 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_cielo_webservice_check 	  	Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_commentmeta 	  	Dados: 0.19MB + Índex: 0.27MB + mecanismo InnoDB
wp_ws4m908v40_comments 	  	Dados: 60.59MB + Índex: 44.09MB + mecanismo InnoDB
wp_ws4m908v40_correios_postcodes 	  	Dados: 1.52MB + Índex: 0.52MB + mecanismo InnoDB
wp_ws4m908v40_duplicator_pro_entities 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_duplicator_pro_packages 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_e_events 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_e_submissions 	  	Dados: 0.02MB + Índex: 0.27MB + mecanismo InnoDB
wp_ws4m908v40_e_submissions_actions_log 	  	Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_ws4m908v40_e_submissions_values 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_ff_scheduled_actions 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_entry_details 	  	Dados: 0.39MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_forms 	  	Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_form_analytics 	  	Dados: 23.05MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_form_meta 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_logs 	  	Dados: 0.50MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_submissions 	  	Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fluentform_submission_meta 	  	Dados: 0.23MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_fsmpt_email_logs 	  	Dados: 9.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_iqblock_logging 	  	Dados: 2.42MB + Índex: 0.36MB + mecanismo InnoDB
wp_ws4m908v40_links 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_litespeed_avatar 	  	Dados: 0.19MB + Índex: 0.13MB + mecanismo InnoDB
wp_ws4m908v40_litespeed_img_optm 	  	Dados: 1.52MB + Índex: 0.27MB + mecanismo InnoDB
wp_ws4m908v40_litespeed_img_optming 	  	Dados: 1.02MB + Índex: 0.23MB + mecanismo InnoDB
wp_ws4m908v40_litespeed_url 	  	Dados: 1.52MB + Índex: 1.66MB + mecanismo InnoDB
wp_ws4m908v40_litespeed_url_file 	  	Dados: 2.13MB + Índex: 7.20MB + mecanismo InnoDB
wp_ws4m908v40_ms_snippets 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_newsletter_automated 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_options 	  	Dados: 28.27MB + Índex: 8.34MB + mecanismo InnoDB
wp_ws4m908v40_options_schow 	  	Dados: 6.52MB + Índex: 1.52MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_charge 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_configuration 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_customer 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_hub_install_token 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_order 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_saved_card 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pagarme_module_core_transaction 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_pgly_pix 	  	Dados: 1.52MB + Índex: 0.06MB + mecanismo InnoDB
wp_ws4m908v40_postmeta 	  	Dados: 408.89MB + Índex: 250.53MB + mecanismo InnoDB
wp_ws4m908v40_postmeta_copy 	  	Dados: 377.91MB + Índex: 241.66MB + mecanismo InnoDB
wp_ws4m908v40_posts 	  	Dados: 56.44MB + Índex: 21.25MB + mecanismo InnoDB
wp_ws4m908v40_po_plugins 	  	Dados: 24.55MB + Índex: 1.42MB + mecanismo InnoDB
wp_ws4m908v40_redirects 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_relevanssi 	  	Dados: 8.31MB + Índex: 13.28MB + mecanismo InnoDB
wp_ws4m908v40_relevanssi_log 	  	Dados: 28.56MB + Índex: 25.58MB + mecanismo InnoDB
wp_ws4m908v40_relevanssi_stopwords 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_css 	  	Dados: 0.13MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_css_bkp 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_layer_animations 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_revslider_layer_animations_bkp 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_revslider_navigations 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_revslider_navigations_bkp 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_revslider_sliders 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_sliders_bkp 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_slides 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_slides_bkp 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_static_slides 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_revslider_static_slides_bkp 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_searchwp_index 	  	Dados: 13.03MB + Índex: 25.52MB + mecanismo InnoDB
wp_ws4m908v40_searchwp_log 	  	Dados: 0.17MB + Índex: 0.28MB + mecanismo InnoDB
wp_ws4m908v40_searchwp_status 	  	Dados: 0.25MB + Índex: 0.34MB + mecanismo InnoDB
wp_ws4m908v40_searchwp_tokens 	  	Dados: 1.52MB + Índex: 4.55MB + mecanismo InnoDB
wp_ws4m908v40_simple_history 	  	Dados: 1.52MB + Índex: 0.64MB + mecanismo InnoDB
wp_ws4m908v40_simple_history_contexts 	  	Dados: 14.50MB + Índex: 7.03MB + mecanismo InnoDB
wp_ws4m908v40_snippets 	  	Dados: 0.25MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_termmeta 	  	Dados: 0.20MB + Índex: 0.25MB + mecanismo InnoDB
wp_ws4m908v40_terms 	  	Dados: 0.13MB + Índex: 0.16MB + mecanismo InnoDB
wp_ws4m908v40_term_relationships 	  	Dados: 3.52MB + Índex: 2.52MB + mecanismo InnoDB
wp_ws4m908v40_term_taxonomy 	  	Dados: 0.14MB + Índex: 0.17MB + mecanismo InnoDB
wp_ws4m908v40_tm_taskmeta 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_tm_tasks 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_usermeta 	  	Dados: 111.64MB + Índex: 75.20MB + mecanismo InnoDB
wp_ws4m908v40_users 	  	Dados: 3.52MB + Índex: 4.55MB + mecanismo InnoDB
wp_ws4m908v40_wc_admin_notes 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_wc_admin_note_actions 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_wc_category_lookup 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_wc_customer_lookup 	  	Dados: 3.52MB + Índex: 3.03MB + mecanismo InnoDB
wp_ws4m908v40_wc_download_log 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_wc_order_coupon_lookup 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_wc_order_product_lookup 	  	Dados: 17.55MB + Índex: 19.06MB + mecanismo InnoDB
wp_ws4m908v40_wc_order_stats 	  	Dados: 3.52MB + Índex: 4.55MB + mecanismo InnoDB
wp_ws4m908v40_wc_order_tax_lookup 	  	Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_ws4m908v40_wc_product_attributes_lookup 	  	Dados: 0.05MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_wc_product_download_directories 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_wc_product_meta_lookup 	  	Dados: 1.52MB + Índex: 1.11MB + mecanismo InnoDB
wp_ws4m908v40_wc_rate_limits 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_wc_reserved_stock 	  	Dados: 0.16MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_wc_tax_rate_classes 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_wc_webhooks 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_gpf_google_taxonomy 	  	Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_recommendations 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woocommerce_session_activity 	  	Dados: 167.67MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woodmart_wishlists 	  	Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woodmart_wishlist_products 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_woomotiv_custom_popups 	  	Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_woomotiv_stats 	  	Dados: 0.17MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_wpmailsmtp_debug_events 	  	Dados: 0.14MB + Índex: 0.00MB + mecanismo InnoDB
wp_ws4m908v40_yith_wcwl 	  	Dados: 0.20MB + Índex: 3.94MB + mecanismo InnoDB
wp_ws4m908v40_yith_wcwl_lists 	  	Dados: 0.28MB + Índex: 6.92MB + mecanismo InnoDB
wp_ws4m908v40_yoast_indexable 	  	Dados: 42.58MB + Índex: 29.34MB + mecanismo InnoDB
wp_ws4m908v40_yoast_indexable_hierarchy 	  	Dados: 5.52MB + Índex: 7.55MB + mecanismo InnoDB
wp_ws4m908v40_yoast_migrations 	  	Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_ws4m908v40_yoast_primary_term 	  	Dados: 0.25MB + Índex: 0.27MB + mecanismo InnoDB
wp_ws4m908v40_yoast_seo_links 	  	Dados: 1.38MB + Índex: 0.48MB + mecanismo InnoDB
wp_ws4m908v40_yoast_seo_meta 	  	Dados: 0.17MB + Índex: 0.00MB + mecanismo InnoDB
Números dos tipos de post
attachment 	  	6673
br_labels 	  	6
cms_block 	  	31
custom-css-js 	  	11
customize_changeset 	  	4
elementor_library 	  	10
ep-synonym 	  	1
err-review-reminders 	  	540
event 	  	6
jc-import-files 	  	2
jc-imports 	  	1
location 	  	1
nav_menu_item 	  	274
notificationx 	  	2
oembed_cache 	  	188
page 	  	47
popup 	  	1
popup_theme 	  	6
post 	  	97
postman_sent_mail 	  	70
product 	  	4849
product_variation 	  	1409
revision 	  	571
safecss 	  	1
shipping_rules 	  	1
shop_coupon 	  	128
shop_order 	  	29059
shop_order_refund 	  	338
socialproof 	  	1
spucpt 	  	1
static_block 	  	2
tribe_events 	  	36
tribe_rsvp_tickets 	  	3
tribe_venue 	  	1
tribe-ea-record 	  	9
vc_settings_preset 	  	9
vtprd-rule 	  	2
wafs 	  	2
wc_product_tab 	  	142
wccf_checkout_field 	  	2
wccf_user_field 	  	6
wcct_countdown 	  	9
woodmart_sidebar 	  	1
woodmart_slide 	  	10
ywar_reviews 	  	3
ywtm_tab 	  	1
Segurança
Conexão segura (HTTPS): 		
Esconder erros para visitantes 		
Plugins ativados (74)
Additional Order Filters for WooCommerce 	  	por Anton Bond – 1.10
BBQ Firewall 	  	por Jeff Starr – 20220517
Tracking Update 	  	por Jeremy Christopher – 1.0.0
Change wp-admin login 	  	por Nuno Morais Sarmento – 1.1.0
Widgets Clássicos 	  	por Colaboradores do WordPress – 0.3
Code Snippets 	  	por Code Snippets Pro – 3.2.0
Simple Custom CSS and JS 	  	por SilkyPress.com – 3.40
Customer Reviews for WooCommerce 	  	por CusRev – 5.3.7
Debug Bar ElasticPress 	  	por 10up – 2.1.1
Debug Bar 	  	por wordpressdotorg – 1.1.3
Disable Bloat for WordPress & WooCommerce 	  	por Disable Bloat – 3.0.3
Disable Gutenberg 	  	por Jeff Starr – 2.7
Disable New User Notifications 	  	por Thomas Griffin – 2.0.0
Disable XML-RPC 	  	por Philip Erb – 1.0.1
Duplicate Page 	  	por mndpsingh287 – 4.4.9
Elementor 	  	por Elementor.com – 3.7.6
Email Address Encoder 	  	por Till Krüss – 1.0.22
301 Redirects 	  	por WebFactory Ltd – 2.72
Fluent Forms 	  	por Contact Form - WPManageNinja LLC – 4.3.12
Flying Scripts 	  	por WP Speed Matters – 1.2.3
CAOS 	  	por Daan from Daan.dev – 4.4.3
OMGF 	  	por Daan from Daan.dev – 5.3.7
iQ Block Country 	  	por Pascal – 1.2.18
jQuery T(-) Countdown Widget 	  	por twinpictures, baden03 – 2.3.23
Cielo Webservice API 3.0 - Jrossetto 	  	por Juliano Rossetto – 2.2
LiteSpeed Cache 	  	por LiteSpeed Technologies – 5.2.1
WooCommerce Load More Products 	  	por BeRocket – 1.1.9.5
Loco Translate 	  	por Tim Whitlock – 2.6.2
Clearsale Start - Loja5 	  	por Loja5.com.br – 1.0
Mautic For Fluent Forms 	  	por WPManageNinja LLC – 1.0.3
Perfect Brands for WooCommerce 	  	por QuadLayers – 2.2.4
Plugin Organizer 	  	por Jeff Sterup – 10.1.6
Re-Add Text Justify Button 	  	por Salvatore Cordiano – 0.1.4
Regenerate Thumbnails 	  	por Alex Mills (Viper007Bond) – 3.1.5
Relevanssi 	  	por Mikko Saari – 4.17.1
Repeat Order for Woocommerce 	  	por polyres – 1.2.0
SearchWP Custom Results Order 	  	por SearchWP – 1.3.6
SearchWP Live Ajax Search 	  	por SearchWP, LLC – 1.7.2
SearchWP WooCommerce Integration 	  	por SearchWP – 1.3.10
SearchWP 	  	por SearchWP – 4.2.3
Server IP & Memory Usage Display 	  	por Apasionados, Apasionados del Marketing – 2.1.0
Sticky Popup 	  	por Numix Technologies, Gaurav Padia, Asalam Godhaviya – 1.2
Alternar usuários 	  	por John Blackbourn & contributors – 1.7.0
WC Correios Status Updater 	  	por Fernando Acosta – 1.6.1
WC Tabela de Frete Offline 	  	por Fernando Acosta – 1.4.1
WC Boleto Parcelado 	  	por Fernando Acosta – 1.4.3
WebP Express 	  	por Bjørn Rosell – 0.25.5
Adicione ao carrinho com Ajax para WooCommerce 	  	por QuadLayers – 1.3.5
WooCommerce Boleto e PIX PagHiper 	  	por PagHiper Pagamentos – 2.2.1
Bulk Table Editor for WooCommerce 	  	por Consortia – 2.2.13
Woo Custom Emails 	  	por wp3sixty – 2.2
Pagamento Moip for WooCommerce 	  	por Apiki WordPress – 1.4.7.1
Abandoned Cart Lite for WooCommerce 	  	por Tyche Softwares – 5.13.0
WooCommerce Advanced Free Shipping 	  	por Jeroen Sormani – 1.1.5
WooCommerce Extended Coupon Features FREE 	  	por Soft79 – 3.2.9
Checkout Field Editor for WooCommerce (Pro) 	  	por ThemeHigh – 3.4.0
Claudio Sanches - Correios for WooCommerce 	  	por Claudio Sanches – 3.8.0
DOMINATION! Let WooCommerce take control of your dashboard 	  	por Claudio Sanches – 1.2.0
Brazilian Market on WooCommerce 	  	por Claudio Sanches – 3.7.2
Pixel Manager for WooCommerce 	  	por SweetCode – 1.21.0
WooCommerce Google Analytics Pro 	  	por SkyVerge – 1.12.0
Reminder for WooCommerce Unpaid Orders 	  	por MB Création – 2.7.2
WooCommerce Recommendation Engine 	  	por Element Stark – 3.2.9
Woocommerce Ultimate Reports 	  	por WooPro – 3.2
WooCommerce 	  	por Automattic – 5.6.2 (atualização para a versão 6.9.3 está disponível)
Woodmart Core 	  	por – 1.0.34
Yoast SEO 	  	por Equipe da Yoast – 19.6.1
WP Crontrol 	  	por John Blackbourn e colaboradores – 1.14.0
WP Disable 	  	por optimisation.io - jody nesbitt – 1.6.1
WP Last Modified Info 	  	por Sayan Datta – 1.8.4
WP Mail SMTP 	  	por WPForms – 3.5.2
WP Mautic 	  	por Mautic community – 2.4.2
Perfect Images (Retina, Thumbnails, Replace) 	  	por Jordy Meow – 6.2.9
Plugins inativos (22)
Asset CleanUp: Page Speed Booster 	  	por Gabe Livan – 1.3.8.5
Disable Cart Fragments 	  	por Optimocha – 2.1.1
ElasticPress 	  	por 10up – 4.3.0
Fluid Checkout for WooCommerce - Lite 	  	por Fluid Checkout – 2.0.7
Lazy Load for Videos 	  	por Kevin Weber – 2.16.5
Linear Checkout for WooCommerce by Cartimize 	  	por Cartimize – 1.1.6
Mautic WooCommerce Marketing Automation 	  	por MakeWebBetter – 3.0.0
Minimal Coming Soon & Maintenance Mode 	  	por WebFactory Ltd – 2.35
NotificationX 	  	por WPDeveloper – 2.5.5
NotificationX Pro 	  	por WPDeveloper – 2.5.4
Pagar.me for WooCommerce 	  	por Pagar.me, Claudio Sanches – 2.5.0
PublishPress Future 	  	por PublishPress – 2.7.7
Query Monitor 	  	por John Blackbourn – 3.10.1
Safe SVG 	  	por 10up – 2.0.3
Simple History 	  	por Pär Thernström – 3.3.0
Slider Revolution 	  	por ThemePunch – 6.5.25
WooCommerce Advanced Product Labels 	  	por BeRocket – 1.2.3.8
WooCommerce Custom Fields 	  	por RightPress – 2.3.4
WooCommerce Tab Manager 	  	por SkyVerge – 1.1.1
Woomotiv - Live Sales Notification for Woocommerce 	  	por Sabri Taieb – 3.4.1
WP Rollback 	  	por GiveWP.com – 1.7.2
XT Floating Cart for WooCommerce Pro 	  	por XplodedThemes – 2.6.8
Plugins avançados (2)
advanced-cache.php 	  	advanced-cache.php
object-cache.php 	  	object-cache.php
Plugins que você deve usar (1)
Plugin Organizer MU 	  	por Jeff Sterup – 10.1.6
Configurações
API habilitada: 		
Forçar SSL: 		
Moeda 		BRL (R$)
Posição da moeda 		left_space
Separador de milhares 		.
Separador decimal 		,
Número de casas decimais 		2
Taxonomias: Tipos de produto 		dgfw_gift (dgfw_gift), external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomias: Visibilidade de produto 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Conectado ao WooCommerce.com: 		–
Páginas do WooCommerce
Base da loja:		#94 - /loja/
Carrinho:		#95 - /cart/
Finalização de compra:		#96 - /pagamento/
Minha conta:		#97 - /minha-conta/
Termos e condições:		Página não definida
Tema
Nome: 		Woodmart Child
Versão: 		1.0.0
URL do autor: 		http://xtemos.com
Tema filho: 		
Nome do tema ascendente: 		Woodmart
Versão do tema ascendente: 		6.5.4
URL do autor do tema ascendente: 		http://themeforest.net/user/xtemos
Suporte ao WooCommerce:

**Comment by oscarssanchez** [comment]
Hi @jeremylugros ,

Can you confirm this only happens with Woocommerce and ElasticPress activated? I see 74 plugins listed on your site which seems like way too many. If you could help us narrow down, post a screenshare etc to reproduce this that would be great. Thanks!
