### ISSUE TITLE
[SOLVED] Deleted products still showing in ElasticSearch, although they do NOT even exist in WP database (tested with DebugBar ElasticPress)

### ISSUE THREAD

**Issue by pedlima** [10up/ElasticPress#3017]
If we look into [this website](https://americana.pt) we will see some products without image (those are in draft), and therefore when we click on them, it gives us a 404 error.

Same happens when we access a tax page, like [this one](https://americana.pt/mochilas-estojos-e-carteiras/)

But if we search for a name of products that are in draft, although they do not appear in search results, there is left the blank space on the bottom (right above the pages numbers) and the total count actually counts with these that do not show, [here's an example](https://americana.pt/?s=bolsa+de+cintura&post_type=product)

So something is not right here and this actually happens since the very begining that we have this installed.

We already used the Debug Bar and tried many different approaches tosolve this issue, but all with no success.

Is this a bug or are we simply missing something here?

**Comment by oscarssanchez** [comment]
I can't reproduce with the information shared. @pedlima please fill in the bug template so we can attempt to reproduce with better accuracy. 

Thanks!

**Comment by pedlima** [comment]
> I can't reproduce with the information shared. @pedlima please fill in the bug template so we can attempt to reproduce with better accuracy.
> 
> Thanks!

Thank you first of all for your care in answering and help.

Could you please let me know what more you need me to let you know in order to help you, helping me?

I mean the" bug template" should have: Bug description (is there), Steps ro Reproduce (I've explained how to reproduce the problem), Expected behavior (also stated this part), Screenshots (I sent links to see it happening live, it's better than screenshots) and Environment information (ok, this is the only part I haven't gave you and here it is:

WordPress 6.0.2
ElasticPress 4.2.0
WooCommerce 6.4.1

Server
PHP 7.4.28
max vars 100000
max memory 16384M
max upload 512M

**Comment by pedlima** [comment]
@oscarssanchez any idea of what this could be? Thank you so much.

**Comment by pedlima** [comment]
@oscarssanchez Any news on this? Please.

**Comment by pedlima** [comment]
So, [these products](https://ibb.co/R9rRw2J) do not even exist in database (at all, they are simply not there).

So when we turn off ElasticPress, those results disappear.

BUT, for some reason, ElasticSearch is NOT receiving that information and therefore, showing these results as "publish", which is obviously not true at all.

**Comment by pedlima** [comment]
Thank you for NO help at all.

Anyway, in order to help the community, here's the solution that worked for me.

We use crons to fire some actions, such as indexing using WP-CLI Commands. So one command we were using on the crontab is this, for instance:

`30 06 * * * sh /home/dev/public_html/elasticpress-cron.sh
`
And inside that shell file, we had this:

```
#!/bin/bash

cd /home/dev/public_html/
/usr/local/bin/wp elasticpress index
```

Problem is, using the command "wp elasticpress index" it only indexes new content, it does not delete anything. Therefore, the old and deleted products were still showing although they should NOT appear.

This was even causing the index to actually respond slower (I can't explain this part, but we did noticed a performance improvement).

So we just had to use this command instead: wp elasticpress index --setup --yes

With this, it now deletes and reindexes everything, everyday. :)

And it works like a charm.

This is it. Hope this helps someone else in the future.

**Comment by felipeelia** [comment]
Hi @pedlima,

ElasticPress out-of-the-box keeps products in sync in real time. Whenever a post is inserted, changed, or deleted there is code to sync that with Elasticsearch (see [here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/SyncManager.php#L55).) That said, no one should be indexing the entire content daily.

If that code is not working as it should, then something else is preventing it to do so. Posts or products could be inserted directly into the database, plugins could bypass WordPress hooks to speed up things, all that is possible. As additional info, the difference between `index` and `index --setup` is that the latter will delete the Elasticsearch index, recreate it, and send everything again, hence why it worked for you.

Lastly, I do want to address here the `Thank you for NO help at all.` phrase. First, passive-aggressive sentences like that do not do any good to anyone. Second -- and this is a problem in the Open Source environment -- there is an expectation level to be set: we do **not** promise responses in a specific timeframe, we strive to reply as fast as possible but GitHub issues do not have an SLA. If you think things are taking too much time to move, open source is _open_ for a reason: as the code is open you can find the problem, fix it, and either submit a Pull Request or create a fork of the plugin. Third, and most important, it is [not the first time we are having this conversation](https://github.com/10up/ElasticPress/issues/2703#issuecomment-1105406945). I am sure we all can work together to make this space better but that will not happen with this kind of behavior. Thanks for understanding.

**Comment by pedlima** [comment]
Hi @felipeelia ,

Thank you for your answer but as you can see, an explanation like the one you just gave would have helped a LOT and would have literally saved days of research from my side.

But, unfortunately, you only answered 27 days after my initial post and you talk about "SLA".... seriously?

Again, I do know what "open source" is, community, etc. if I didn't knew, I wouldn't invest my precious time to let others know about my solution.

Honestly in your case I would say "sorry and thank you" to someone using your plugin (for free or not, doesn't matter) that was patient enough to wait 27 days for some help and ended up solving the problem and took his time to help the community with his solution.

But hey, that's me and probably I'm just a little bit dumb! :)

I wish you all the best but do take care on your approaches in the future. Sometimes the line between what's "right" or "wrong" is very thin and for someone else looking into this, you might not look as being 100% correct and you do represent a business here, so...

**Comment by brandwaffle** [comment]
@pedlima I just wanted to let you know that we're very proud of how @felipeelia represents 10up. In the future, I recommend you look to the documentation for ElasticPress, which clearly explains all of the questions you had and would have saved you a lot of time (and prevented you from having to verbally attack folks trying to help you).

**Comment by pedlima** [comment]
@brandwaffle Good to know. Wish you guys all the best.
