### ISSUE TITLE
BUG: Admin product stock status filtering not working

### ISSUE THREAD

**Issue by jakgsl** [10up/ElasticPress#3027]
**Describe the bug**

Stock filtration on admin Product List page has no effect. All other filters (categories etc, work).
To note, this is happening on another site with a similar setup.

**Steps to Reproduce**

1. Go to Products
2. Filter by stock status (with test products in, out of stock, and back order)

**Expected behavior**

Products to be filtered correctly by stock status

**Screenshots**

**Environment information**
 - Device: All
 - OS: All
 - Browser and version: All
 - WordPress version: 6.0.1
 
 - ElasticPress version: 6.0
 - Elasticsearch version: 7.15.0
 - Where do you host your Elasticsearch server? UKFAST (same box)
 - What ElasticPress features do you have currently active? All of them

![2022-09-27-171524_3840x1080_scrot](https://user-images.githubusercontent.com/44027449/192580034-3df8df0d-550a-4427-8167-888ed080dd3b.png)

**Comment by oscarssanchez** [comment]
Confirmed the bug. Protected content must be activated to reproduce it.

**Comment by jakgsl** [comment]
That's great - is there something I can turn on/off for the moment to fix?
Is there anything I can do to help fix this?

**Comment by felipeelia** [comment]
@jakgsl any chance you can give #3036 a try and confirm it fixes the issue? Thanks!

**Comment by jakgsl** [comment]
@felipeelia Hi, yes this has completely corrected the issue.

Great stuff,

Regards,
