### ISSUE TITLE
http basic auth

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#303]
I'm using qbox.io to host my index. I've also created a JS search interface which uses `elasticsearch.jquery.js` to get ajaxed results.

Qbox offers a http authentication which 

>Makes data "readonly" by password protecting all non-search operations. Typically used in JavaScript applications, since cluster endpoints are exposed to the end-user.

But I still need to authenticate EP to do the indexing. Is this possible?

**Comment by tuanmh** [comment]
Do a quick search through 'Closed' issue, check it out mate https://github.com/10up/ElasticPress/issues/283
