### ISSUE TITLE
BUG: ep_post_match_fuzziness value overridden by default value of deprecated ep_match_fuzziness value

### ISSUE THREAD

**Issue by marc-kohde** [10up/ElasticPress#3033]
**Describe the bug**

The deprecated filter `ep_match_fuzziness` is run after its replacement filter `ep_post_match_fuzziness` despite the first filter being defined with `add_filter` and returning a value.

As such, fuzziness is always set to "auto", the default value for the deprecated filter.

**Steps to Reproduce**

1. Add the filter

```php
add_filter('ep_post_match_fuzziness', function ($fuzziness): int {
  return 1;
});
```

When the search is performed this is called (Version_400.php line 87):

```php
apply_filters( "ep_{$indexable_slug}_match_fuzziness", 'auto', $search_fields, $query_vars ),
```

Then this is called (Version_400.php line 162):

```php
$query['bool']['should'][1]['multi_match']['fuzziness'] = apply_filters_deprecated(
  'ep_match_fuzziness',
  [ 'auto', $search_fields, $query_vars ],
  '4.3.0',
  'ep_post_match_fuzziness'
);
```

...which overrides the previous value to "auto".
 
**Expected behavior**

If the replacement filter is defined, then the deprecated filter should not be called.

**Environment information**
 - WordPress version: 6.0.2
 - ElasticPress version: 4.3.1

**Comment by kevinlisota** [comment]
I assume this is related to my question [here](https://github.com/10up/ElasticPress/issues/2920#issuecomment-1261524183)

**Comment by felipeelia** [comment]
Hey @marc-tt, thanks for opening the issue. I've created a PR changing a bit how those filters work and now the deprecated filters will honor the value set with the newer filters. And yes, @kevinlisota, that is related to your question, thanks for that.
