### ISSUE TITLE
QUESTION: Result drop down showing only 9 product

### ISSUE THREAD

**Issue by KusalDay** [10up/ElasticPress#3034]
In the drop-down list, when I search for something that gives a result, the maximum results are 9 products. I want to show all the results and more than 10 using scrolling to see the result.

**Comment by felipeelia** [comment]
By drop-down list you mean Autosuggest? If so, you can change the number of posts displayed with the following snippet:
```php
add_action(
	'pre_get_posts',
	function( $query ) {
		if ( 'ep_autosuggest_placeholder' === $query->get( 's' ) ) {
			$query->set( 'posts_per_page', 20 );
		}
	}
);
```

To add a scroll to the list, you can use something like this:
```css
.ep-autosuggest {
    max-height: 20rem;
    overflow: auto;
}
```
