### ISSUE TITLE
BUG: missing products in category page

### ISSUE THREAD

**Issue by wongkediri** [10up/ElasticPress#3035]
**Describe the bug**

Missing some products in category page:
the number of products on the category page is different from the query results, the number of products is less than actual

**Steps to Reproduce**

1. Woocommerce admin Go to Products -> Categories check 'count' column
2. click view to see category page in frontend & compare the result

**Expected behavior**
its happen for some categories, the number of missing product also varies

**Screenshots**

**Environment information**
 - WPEngine hosting
 -  Wordpress 6.0.2
 - Woocommerce 6.9.4
 - PHP 7.4.30
 - ElasticPress 4.3.1 from WPE

**Comment by felipeelia** [comment]
Hi @wongkediri,

I can't reproduce the error locally. Do you happen to know when the numbers start to differ? Would it be possible for you to delete and sync all your content again and keep an eye on those numbers and reach out saying the exact event that does not update the count?

Thanks!
