### ISSUE TITLE
Improvement: allow recursively terms indexing

### ISSUE THREAD

**Issue by tuanmh** [10up/ElasticPress#304]
Hi guys, thanks again for a great and extensible plugin. Just a suggestion. With current terms indexing, we run into a problem that if a post's term (e.g. ``optimization``) is under other terms, for example: ``computer science -> performance -> optimization``, we will not be able to search for that post under ``computer science`` or ``performance`` term. Hence, it would be handy if we can also allow 'computer science', 'performance' in the list of terms along with 'optimization'. 

It may not be suitable with other people though, so I suggest we enable both options by exposing the a filter so it can be overridden.

**Comment by tuanmh** [comment]
This ccee471 can give you brief idea on this.

**Comment by tuanmh** [comment]
I don't think I made it clear, let me put it in this way. Let's say, we have this hierarchy:
Computer Science
-- Optimization (post A)
---- Performance (post B,C)
------ Algorithms (post D)

Currently, when searching posts under optimisation will only yield: post A, while logically to someones to return A, B, C, D. Searching performance will return only B and C but it should be B,C D. 

The enhancement would be supporting the feature but also exposing a filter to make sure that people can still stay with current implementation. 

Let me know if it makes sense @tlovett1

**Comment by tlovett1** [comment]
@tuanmh makes sense to me. I'm not sure of the implications this could have though. Waiting for review from @allan23

**Comment by allan23** [comment]
@tuanmh It looks like you still have line that is not PHP 5.3 compatible: test-single-site.php line 282. I see that your unit test is checking the post via ep_get_post(), can you also write a unit test to utilize WP_Query?

@tlovett1 This does make sense if someone wants to determine a post's term hierarchy. Further unit testing is needed.

**Comment by tuanmh** [comment]
> It looks like you still have line that is not PHP 5.3 compatible: test-single-site.php line 282. I see that your unit test is checking the post via ep_get_post(), can you also write a unit test to utilize WP_Query?

I'm quite busy these days but will find time to finish them this weekend. Thanks for pointing that out!

**Comment by tuanmh** [comment]
ok, finally I can settle down and have the unit tests fixed with new tests added as recommended by @allan23 . @tlovett1 could you please review this, thanks!
