### ISSUE TITLE
QUESTION: WordPress with API-Data: Crawler possible?

### ISSUE THREAD

**Issue by casinojeffrey** [10up/ElasticPress#3043]
**Describe your question**

Hi there. I have about 7400 posts as posts and custom post types.

also i have about 75k of pages displayed live via an api. therefore i need a solution to scrape / crawl my wordpress website for content on a daily basis and include this data to my search bar.

can this be done with elasticpress & the elasticpress plugin?

thank you for your reply in advance and best regards.

**Comment by oscarssanchez** [comment]
Hi @casinojeffrey ,

I don't understand your question, do you mean you want to scrape content, put that later into your WordPress site and make that available for search, or the opposite, you have another website unrelated to WordPress, and you want to scrape its content? I also don't understand what you mean by including the data to your search bar.

Thanks!

**Comment by casinojeffrey** [comment]
@oscarssanchez Thank you for your reply. So let me try to rephrase it then:
- everything is inside 1 wordpress site
- but the 75k pages are no posts/custom posts and are only being displayed via an api-plugin
- "including the data to my search" was my try to say that i want the 75k pages added to the elastic-database so users will be able to search for them.

hope that clarifies the topic

**Comment by casinojeffrey** [comment]
@oscarssanchez is it ok to post a reminder here? sorry if it shouldn't be done, just checking in

**Comment by oscarssanchez** [comment]
@casinojeffrey if those 75k pages are no posts/custom posts then the plugin doesn't know how to index those or search them. 

There's a couple of approaches you could follow thinking out loud.

- Create those 75k pages in your WordPress site, let ElasticPress then index them and they should be searchable as well. If you need to change the permalink for them to link to another site it should be possible.
- Create a new index with similar fields as the post index and index that data with ES. Later on, combine the formatted request that EP sends to ping both indices an return hits, although this will require you to take into account many more things.
