### ISSUE TITLE
Widget get_terms() optimization

### ISSUE THREAD

**Issue by mae829** [10up/ElasticPress#3046]
**Is your enhancement related to a problem? Please describe.**
On enterprise level websites, some taxonomies can reach large number count (10k+). I know it can be up to the client to clean that up but sometimes that will just not happen.
The large number of terms results in the call to [get_terms()](https://github.com/10up/ElasticPress/blob/25058386304cde1281a2c4df4719a35476b797ea/includes/classes/Feature/Facets/Types/Taxonomy/Renderer.php#L83) in the facets widget to be a large SQL query and updating the cache (when available) due to `get_terms()` functionality itself.

**Describe the solution you'd like**
- Passing the `update_term_meta_cache` argument as true in the default arguments for `get_terms()`.

**Describe alternatives you've considered**
- Using `global $ep_facet_aggs` to limit the requested terms to the ones that actually have results.

**Additional context**
The `ep_facet_search_get_terms_args` filter definitely allows for optimization so possibly just passing the `update_term_meta_cache` as true argument in the defaults might suffice.

Implementation from above:
```php
<?php
add_filter( 'ep_facet_search_get_terms_args', function( $query_args, $args, $instance ) {
	global $ep_facet_aggs;

	$query_args['update_term_meta_cache'] = false;

	if ( ! empty( $instance['facet'] ) && ! empty( $ep_facet_aggs[ $instance['facet'] ] ) ) {
		$query_args['slug'] = array_keys( $ep_facet_aggs[ $instance['facet'] ] );
	}

	return $query_args;
}, 10, 3 );
```

**Comment by felipeelia** [comment]
Hey @mae829, thanks for the suggestion. Do you mind sending us a PR changing the get_terms call to pass `update_term_meta_cache` false? Thanks!

**Comment by mae829** [comment]
@felipeelia sure thing.

PR created over at #3060
