### ISSUE TITLE
QUESTION: How can I use ajax to get response form elasticsearch

### ISSUE THREAD

**Issue by Vaibhav2608** [10up/ElasticPress#3047]
**Describe your question**

I am on the woocommerce project which have 10k products approx, in which we want to give some filter by meta fields. I followed the guide line i cheked, non of our meta_key starts with `_`. For template we create html structure and fire ajax query if someone enter any thing html input though jquery. As wordpress basic coding structure we hook ajax action with php function which uses wp_query and has `ep_integrate=>true` is passed. but still the response takes 3s sometimes 9s also.

```
$value = $_POST['value'];
	$meta_query = array();
	foreach($value as $meta_queries => $meta_value){
		if($meta_queries!= 'purity' && $meta_queries!= 'price' && $meta_value !=''){
			$meta_query[] = array(
				'key' => $meta_queries, // meta key
				'value' => $meta_value,
							
			);
		}else{
			if(is_array($meta_value)){
				$meta_query[] = array(
					'key' => $meta_queries, // meta key
					'value' => $meta_value,
					'compare' => 'between',
					'type'	=>	'number'
				);
			}
			 
		}
	}
	$meta_query['relation'] = 'AND';
	
	$args = array(
		'ep_integrate' => true,
		'post_type' => 'product',
		'meta_query' => $meta_query,
		'orderby'    => 'rand',
		'posts_per_page' => 20,
		'pagination'	=> true,  
		
	);
	$wc_query = new WP_Query($args);

```
$value is the all the filter values which i tested, they have the value. 

I don't know where I commit mistake.

Is there any way where in can see the ajax is result coming form elastic search please let, I have installed Query Monitor but didn't show my ajax request.

**Comment by oscarssanchez** [comment]
Hi @Vaibhav2608 ,

There could be many reasons for your problem. If you are unsure if the results are coming from Elasticsearch, you will see the elasticsearch_success property defined in the WP_Query object. See for example: https://github.com/10up/ElasticPress/blob/develop/tests/php/indexables/TestPost.php#L418

I'd start checking that. You could also log the request sent to elastic and the response, it could also be that your query is being formatted wrongly and search is defaulting to MySQL.

**Comment by Vaibhav2608** [comment]
Hi @oscarssanchez ,

Well my ajax function did send the query every time but i didn't find my query in Elasticpress query log. in response of my query i get this
`{"query":{"ep_integrate":true,"post_type":"product","meta_query":{"0":{"key":"cas_number","value":"99627-0"},"relation":"AND"},"orderby":"rand","posts_per_page":20,"pagination":true},"query_vars":{"ep_integrate":true,"post_type":"product","meta_query":{"0":{"key":"cas_number","value":"99627-0"},"relation":"AND"},"orderby":"rand","posts_per_page":20,"pagination":true,"error":"","m":"","p":0,"post_parent":"","subpost":"","subpost_id":"","attachment":"","attachment_id":0,"name":"","pagename":"","page_id":0,"second":"","minute":"","hour":"","day":0,"monthnum":0,"year":0,"w":0,"category_name":"","tag":"","cat":"","tag_id":"","author":"","author_name":"","feed":"","tb":"","paged":0,"meta_key":"","meta_value":"","preview":"","s":"","sentence":"","title":"","fields":"","menu_order":"","embed":"","category__in":[],"category__not_in":[],"category__and":[],"post__in":[],"post__not_in":[],"post_name__in":[],"tag__in":[],"tag__not_in":[],"tag__and":[],"tag_slug__in":[],"tag_slug__and":[],"post_parent__in":[],"post_parent__not_in":[],"author__in":[],"author__not_in":[],"ignore_sticky_posts":false,"suppress_filters":false,"cache_results":false,"update_post_term_cache":true,"lazy_load_term_meta":true,"update_post_meta_cache":true,"nopaging":false,"comments_per_page":"50","no_found_rows":false,"order":""},"tax_query":{"queries":[],"relation":"AND","queried_terms":[],"primary_table":"wp_posts","primary_id_column":"ID"},"meta_query":{"queries":{"0":{"key":"cas_number","value":"99627-0"},"relation":"OR"},"relation":"AND","meta_table":"wp_postmeta","meta_id_column":"post_id","primary_table":"wp_posts","primary_id_column":"ID"},"date_query":false,"request":"\n\t\t\t\t\tSELECT SQL_CALC_FOUND_ROWS  wp_posts.ID\n\t\t\t\t\tFROM wp_posts  INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id )\n\t\t\t\t\tWHERE 1=1  AND ( \n  ( wp_postmeta.meta_key = 'cas_number' AND wp_postmeta.meta_value = '99627-0' )\n) AND ((wp_posts.post_type = 'product' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'archived' OR wp_posts.post_status = 'future' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' \nOR wp_posts.post_status = 'private')))\n\t\t\t\t\tGROUP BY wp_posts.ID\n\t\t\t\t\tORDER BY RAND()\n\t\t\t\t\tLIMIT 0, 20\n\t\t\t\t","posts":[],"post_count":0,"current_post":-1,"in_the_loop":false,"comment_count":0,"current_comment":-1,"found_posts":0,"max_num_pages":0,"max_num_comment_pages":0,"is_single":false,"is_preview":false,"is_page":false,"is_archive":true,"is_date":false,"is_year":false,"is_month":false,"is_day":false,"is_time":false,"is_author":false,"is_category":false,"is_tag":false,"is_tax":false,"is_search":false,"is_feed":false,"is_comment_feed":false,"is_trackback":false,"is_home":false,"is_privacy_policy":false,"is_404":false,"is_embed":false,"is_paged":false,"is_admin":true,"is_attachment":false,"is_singular":false,"is_robots":false,"is_favicon":false,"is_posts_page":false,"is_post_type_archive":true,"thumbnails_cached":false}`

I think my query is didn't hit elastic search, it response seems coming from MySQL. I don't know about the right format for elastic search query. My query argument look like
```
[
   "ep_integrate" => true, 
   "post_type" => "product", 
   "meta_query" => [
         [
            "key" => "cas_number", 
            "value" => "99627-05" 
         ], 
         "relation" => "AND" 
      ], 
   "orderby" => "rand", 
   "posts_per_page" => 20, 
   "pagination" => true 
];  
```

If its wrong then please let me know the right format.
I followed https://10up.github.io/ElasticPress/tutorial-indexables.html for building.

**Comment by oscarssanchez** [comment]
Hi @Vaibhav2608 ,

That seems correct to me, can you verify this query works in a non-ajax context? For that, i'd recommend installing our debug bar elasticpress plugin. More on that here: https://www.elasticpress.io/blog/2017/05/debugging/

Thanks!

**Comment by Vaibhav2608** [comment]
Hi @oscarssanchez ,

The same query is working for non-ajax context.
	
```
$args = array(
		"ep_integrate" => true, 
		"post_type" => "product", 
		"meta_query" => array(
			array(
				"key" => "cas_number", 
				"value" => "99627-05",
				'compare' => 'like' 
			), 
			 "relation" => "AND"
		), 
		"orderby" => "rand", 
		"posts_per_page" => 20, 
		"pagination" => true 
	);
	
	$wc_query = new WP_Query($args);
```


For this query, response have `[elasticsearch_success] => 1` thus this coming from elastic search. I checked it on init action hook. But same query in ajax will give result in 5s and elastic press debug bar don't have my query.

I don't understand where I have been wronged and what to do.

Please help

**Comment by Vaibhav2608** [comment]
Hi @oscarssanchez ,

I came across filter `add_filter( 'ep_ajax_wp_query_integration', '__return_true' );` after that my ajax query have `[elasticsearch_success] => 1` but response is still taking 2sec. Is it possible to get result with in less then 1sec. 

Thank you

**Comment by Vaibhav2608** [comment]
Why does this has results in no product where as same query in sql returns 135 products. Even other fields too.
```
WP_Query Object
(
    [query] => Array
        (
            [post_type] => product
            [meta_query] => Array
                (
                    [0] => Array
                        (
                            [key] => purity
                            [value] => Array
                                (
                                    [0] => 16
                                    [1] => 89
                                )

                            [compare] => between
                        )

                )

            [posts_per_page] => -1
            [ep_integrate] => 1
            [suppress_filters] => 
        )

    [query_vars] => Array
        (
            [post_type] => product
            [meta_query] => Array
                (
                    [0] => Array
                        (
                            [key] => purity
                            [value] => Array
                                (
                                    [0] => 16
                                    [1] => 89
                                )

                            [compare] => between
                        )

                )

            [posts_per_page] => -1
            [ep_integrate] => 1
            [error] => 
            [m] => 
            [p] => 0
            [post_parent] => 
            [subpost] => 
            [subpost_id] => 
            [attachment] => 
            [attachment_id] => 0
            [name] => 
            [pagename] => 
            [page_id] => 0
            [second] => 
            [minute] => 
            [hour] => 
            [day] => 0
            [monthnum] => 0
            [year] => 0
            [w] => 0
            [category_name] => 
            [tag] => 
            [cat] => 
            [tag_id] => 
            [author] => 
            [author_name] => 
            [feed] => 
            [tb] => 
            [paged] => 0
            [meta_key] => 
            [meta_value] => 
            [preview] => 
            [s] => 
            [sentence] => 
            [title] => 
            [fields] => 
            [menu_order] => 
            [embed] => 
            [category__in] => Array
                (
                )

            [category__not_in] => Array
                (
                )

            [category__and] => Array
                (
                )

            [post__in] => Array
                (
                )

            [post__not_in] => Array
                (
                )

            [post_name__in] => Array
                (
                )

            [tag__in] => Array
                (
                )

            [tag__not_in] => Array
                (
                )

            [tag__and] => Array
                (
                )

            [tag_slug__in] => Array
                (
                )

            [tag_slug__and] => Array
                (
                )

            [post_parent__in] => Array
                (
                )

            [post_parent__not_in] => Array
                (
                )

            [author__in] => Array
                (
                )

            [author__not_in] => Array
                (
                )

            [cache_results] => 
            [tax_query] => Array
                (
                )

            [suppress_filters] => 
            [ignore_sticky_posts] => 
            [update_post_term_cache] => 1
            [lazy_load_term_meta] => 1
            [update_post_meta_cache] => 1
            [nopaging] => 1
            [comments_per_page] => 50
            [no_found_rows] => 
            [order] => DESC
        )

    [tax_query] => WP_Tax_Query Object
        (
            [queries] => Array
                (
                )

            [relation] => AND
            [table_aliases:protected] => Array
                (
                )

            [queried_terms] => Array
                (
                )

            [primary_table] => wp_posts
            [primary_id_column] => ID
        )

    [meta_query] => WP_Meta_Query Object
        (
            [queries] => Array
                (
                    [0] => Array
                        (
                            [key] => purity
                            [value] => Array
                                (
                                    [0] => 16
                                    [1] => 89
                                )

                            [compare] => between
                        )

                    [relation] => OR
                )

            [relation] => AND
            [meta_table] => wp_postmeta
            [meta_id_column] => post_id
            [primary_table] => wp_posts
            [primary_id_column] => ID
            [table_aliases:protected] => Array
                (
                    [0] => wp_postmeta
                )

            [clauses:protected] => Array
                (
                    [wp_postmeta] => Array
                        (
                            [key] => purity
                            [value] => Array
                                (
                                    [0] => 16
                                    [1] => 89
                                )

                            [compare] => BETWEEN
                            [compare_key] => =
                            [alias] => wp_postmeta
                            [cast] => CHAR
                        )

                )

            [has_or_relation:protected] => 
        )

    [date_query] => 
    [request] => 
			SELECT   wp_posts.*
			FROM wp_posts  INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id )
			WHERE 1=1  AND ( 
  ( wp_postmeta.meta_key = 'purity' AND wp_postmeta.meta_value BETWEEN '16' AND '89' )
) AND ((wp_posts.post_type = 'product' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'archived' 
OR wp_posts.post_status = 'private')))
			GROUP BY wp_posts.ID
			ORDER BY wp_posts.post_date DESC
			
		
    [posts] => Array
        (
        )

    [post_count] => 0
    [current_post] => -1
    [in_the_loop] => 
    [comment_count] => 0
    [current_comment] => -1
    [found_posts] => 0
    [max_num_pages] => 0
    [max_num_comment_pages] => 0
    [is_single] => 
    [is_preview] => 
    [is_page] => 
    [is_archive] => 1
    [is_date] => 
    [is_year] => 
    [is_month] => 
    [is_day] => 
    [is_time] => 
    [is_author] => 
    [is_category] => 
    [is_tag] => 
    [is_tax] => 
    [is_search] => 
    [is_feed] => 
    [is_comment_feed] => 
    [is_trackback] => 
    [is_home] => 
    [is_privacy_policy] => 
    [is_404] => 
    [is_embed] => 
    [is_paged] => 
    [is_admin] => 
    [is_attachment] => 
    [is_singular] => 
    [is_robots] => 
    [is_favicon] => 
    [is_posts_page] => 
    [is_post_type_archive] => 1
    [query_vars_hash:WP_Query:private] => cb2f186f575c35e16df73a37820aa75f
    [query_vars_changed:WP_Query:private] => 1
    [thumbnails_cached] => 
    [stopwords:WP_Query:private] => 
    [compat_fields:WP_Query:private] => Array
        (
            [0] => query_vars_hash
            [1] => query_vars_changed
        )

    [compat_methods:WP_Query:private] => Array
        (
            [0] => init_query_flags
            [1] => parse_tax_query
        )

    [num_posts] => 0
    [elasticsearch_success] => 1
)

```

**Comment by Vaibhav2608** [comment]
I think this issue is due to `wp_query`, is there any other way around to achieve same thing.
