### ISSUE TITLE
Autosuggest not working

### ISSUE THREAD

**Issue by devteam-pisarek** [10up/ElasticPress#3052]
Autosuggest not working.
What configuration I have set
Enable elastipress autosuggest feature
Set custom autosuggest selector as per requirement
Endpoint URL : /autosuggest
I'm using a third-party elasticsearch host URL which is on amazonaws.com

So when I type any text in the search field, the request goes to 404 https://ecsdev.participaction.com/autosuggest 
If I change the endpoint URL with the same third-party host URL, then I still get failed connection error
And also both the time I get 
Failed to fetch (autosuggest-script.min.js?ver=e1b508e65c69c72dd862ada6fe8558d9:1:1298)

So please help me, if I set any wrong settings to resolve this issue.

Thanks in advance.

**Comment by oscarssanchez** [comment]
Hi @devteam-pisarek ,

Autosuggest endpoint should be a publicly available endpoint to the end user (for example, the post index endpoint). We discourage that however, as there's security reasons to not make that available for the end user. See: https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups

As this support is outside the scope of this plugin I'll close this one. We do offer consultation on ES if that's something you'd be interested, and ES hosting as well (that should not require additional work for you to use Autosuggest safely) over at https://elasticpress.io
