### ISSUE TITLE
Lots of notices in regular search query since 1.5

### ISSUE THREAD

**Issue by paulhuisman** [10up/ElasticPress#306]
Hi,

I'm seeing alot of notices since upgrading to 1.5 from 1.4.

This happens in a regular search query:

Notice: Undefined index: comment_count in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: comment_status in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: ping_status in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: menu_order in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: comment_count in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: comment_status in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: ping_status in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: menu_order in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: comment_count in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: comment_status in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: ping_status in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

Notice: Undefined index: menu_order in /Users/paul/projects/fc-corporate/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 313

etcetera

**Comment by tlovett1** [comment]
I think we need to check if these properties exist before adding them to the post since we added fields to the indexed document.

Also, we need to update the mapping to account for a few fields that we missed.

@allan23 can you take care of this?

@paulhuisman re-indexing will most likely fix this for you now.

**Comment by paulhuisman** [comment]
Thanks for your swift response. Re-indexing helped!
