### ISSUE TITLE
Search Woocommerce order by id

### ISSUE THREAD

**Issue by amanfredini76** [10up/ElasticPress#3067]
Hi, in my Elasticpress istance the order search doesn't work with order ID.

Why?

It return another set of order

**Comment by felipeelia** [comment]
Hi @amanfredini76,

Can you please install the [Debug Plugins](http://10up.github.io/ElasticPress/tutorial-debugging.html) and share with us the query information (query args, query body, and query results)? You can paste them into https://pastebin.com/ and share only the link, so it is easier to read.

The WooCommerce feature will also search for that number in a [set of different fields](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/WooCommerce/WooCommerce.php#L410). When you say "It return another set of order", does that mean the order with that ID is not returned or it is returned but with some others?
