### ISSUE TITLE
BUG: Problem with Indexing via CLI

### ISSUE THREAD

**Issue by gwhitehead** [10up/ElasticPress#3070]
To give you a background, the site we have has a lot of Post Meta data that is being indexed. We found that we have to do groups of Post ID index requests via the CLI in order to get through it all. We are using the --lower-limit-object-id and --upper-limit-object-id= commands. Since we are on a WP Engine hosting environment we believe we are limited by time so we have to break it up in groups of 10k or 5k posts IDs.  

There are times where we are running "wp elasticpress index --show-errors --lower-limit-object-id=0 --upper-limit-object-id=10000" and we get the error "Error: An index is already occurring. Try again later.". I would then fire the "wp elasticpress stop-indexing" command to try to tell elasticpress to stop indexing the site so I can initialize it how I need to.  We have also tried to use " wp elasticpress index --setup --show-errors --lower-limit-object-id=0 --upper-limit-object-id=10000" in the first one to setup and clear the index at the same time. There has been a few times where this hikups

What we wanted to see is to be able to fire an index even by grouping Post IDs from the CLI after stopping the index. 

Here is a screenshot of what I was seeing while trying to fight with the indexing process in one of our WP Engine environments.
https://www.screencast.com/t/sLzyuZLad

**Comment by oscarssanchez** [comment]
Thanks for opening this @gwhitehead !

I wonder if the first issue is related to object cache not being updated with the sync meta information that the indexing finished. As for the other ones, If I recall correctly your site has a lot of PDFs as well. Sometimes these could be heavy and if there's more than a couple per batch, I think that could explain the reason of the timeouts.

One way to check this could be to try to index on your staging site with the documents feature disabled. Can you give it a try to validate this?

**Comment by gwhitehead** [comment]
Could very well have been this object caching within the hosting environment.
