### ISSUE TITLE
BUG:  Gallery Shortcode

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3080]
Hi all. 

**Describe the bug**
I found this bug, if a standard gallery shortcode is used in a published post on the site, there will be an error during indexing.
https://codex.wordpress.org/Gallery_Shortcode

**Steps to Reproduce**

1. Create a post containing a shortcode [gallery]
2. Start creating an index

**Expected behavior**
It is expected that the progress bar will reach 100% and there will be a message in the logs about the successful completion.

**Environment information**
 - WordPress version: 6.0.2
 - ElasticPress version: 4.3.0
 - Elasticsearch version: 7.10.2
 - Local

**Comment by oscarssanchez** [comment]
Hey @ws256 ,

I tried to reproduce this but I am unable. Can you please try to reproduce from your end with a fresh install and if you can reproduce, would you mind sharing a screencast to see the steps you are taking?

Thanks!
