### ISSUE TITLE
Sync is getting stuck

### ISSUE THREAD

**Issue by LucyTech** [10up/ElasticPress#3086]
I am trying to sync the index on my website but I'm just seeing this in the log file: 
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0

**Comment by oscarssanchez** [comment]
Hey @LucyTech ,

I'd try these WP CLI commands:

`wp elasticpress stop-indexing`

And then

`wp elasticpress index --setup --show-errors`

This will unstuck your index and attempt a new indexing operation. Hopefully that solves it.
