### ISSUE TITLE
Sync is getting stuck

### ISSUE THREAD

**Issue by LucyTech** [10up/ElasticPress#3087]
I am trying to sync the index on my website but I'm just seeing this in the log file: 
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0

**Comment by oscarssanchez** [comment]
Closing as it is a duplicate of https://github.com/10up/ElasticPress/issues/3086
