### ISSUE TITLE
Search suggestions don't match the search query

### ISSUE THREAD

**Issue by mediachip-ux** [10up/ElasticPress#3088]
Hello, our website is [here](https://www.specialistsales.com.au) - elasticpress/elastic search is doing some strange things and not showing relevant suggestions. 

For example if you search for 'red marker dye' other products or completely unrelated products will populate well before any of the red marker dyes are shown.

Also, we find that the suggestion box takes a very very long time to pop up.

We are using this for Woocommerce and can't seem to configure the settings to make it function like it should.

![red marker dye search](https://user-images.githubusercontent.com/116787139/198203609-d9b25bda-7fb1-4221-8b4d-2b53339dea7c.png)

Any help would be great!

**Comment by oscarssanchez** [comment]
Hi @mediachip-ux ,

It seems your autosuggest is not the one from ElasticPress. I'd probably check what WP_Query is being sent to EP to format by logging it and/or log the formatted args that are being sent as a request by ElasticPress. From there it will be easier to translate what is the request asking and infer why you get the results you currently get.

**Comment by mediachip-ux** [comment]
Thanks will try to look at the WP_Query.

I also am curious to understand why it is that our search results and the autosuggest would include totally unrelated products items? It seems that when you start typing, the autosuggest includes a latest product (totally unrelated)

The EP search weight really doesn't help me configure this. :(

Thank you

**Comment by felipeelia** [comment]
Hey @mediachip-ux, can you please go to wp-admin/admin.php?page=elasticpress, open the "Post Search" box, set "Weight results by date" as Disabled, save it and test the results again? Generally, that helps with the wrong order of products, especially when we see the behavior of more recent products being prioritized. Thanks!
