### ISSUE TITLE
Attachment post type not indexed on publish

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#309]
When adding media via the media uploader or post editor, attachment is not indexed. 

Steps to replicate:

1. Filter `ep_indexable_post_types` to include 'attachment'
2. Filter `ep_indecable_post_status` to include 'inherit'
3. Run `wp elasticpress index --setup`. (attachments are indexed)
4. Upload attachment via media uploader or post editor. (attachment not indexed*)

*Changes are not sent to the ES index when a attachment post type is created or edited, however it is removed from the ES index after being deleted from WP.

**Comment by tuanmh** [comment]
This is because saving an 'attachment' will never invoke ``wp_insert_post`` which is being used to sync a post to ES. A workaround would be in your plugin hook into both ``edit_attachment`` and ``add_attachment``. It should fix the problem. This is what've doing at the moment.

**Comment by tlovett1** [comment]
@allan23 any ideas here?

**Comment by tlovett1** [comment]
@tuanmh nice catch. Enabling attachments will be possible in 1.6 via filters exactly how you assumed @psorensen .
