### ISSUE TITLE
QUESTION: Facet by Meta Block – Serialized data? Which hook to use?

### ISSUE THREAD

**Issue by jonasborneland** [10up/ElasticPress#3096]
I'm trying to use a metafield which contains serialized data. Right now the Facet by Meta output is like:
a:2:{i:0;s:3:"110";i:1;s:3:"116";}
a:2:{i:0;s:3:"122";i:1;s:3:"128";}
a:2:{i:0;i:68;i:1;i:74;}
a:2:{i:0;i:80;i:1;i:86;}
a:1:{i:15;s:3:"134";}
a:2:{i:0;i:74;i:1;i:80;}
a:3:{i:6;s:2:"80";i:7;s:2:"86";i:8;s:2:"92";}
a:2:{i:6;s:2:"80";i:7;s:2:"86";}
a:4:{i:9;s:2:"98";i:10;s:3:"104";i:11;s:3:"110";i:12;s:3:"116";}
a:4:{i:11;s:3:"110";i:12;s:3:"116";i:13;s:3:"122";i:14;s:3:"128";}
a:1:{i:0;s:2:"44";}
a:2:{i:0;i:104;i:1;i:110;}
Any clue on how to make it work? Is there a hook to change it maybe before indexing?

Here is how it should be working:
In the edit area of my WC product, theres some meta fields with checkboxes to choose which clothing-sizes the product is matching:
[x] size 110 [x] size 116 [o] size 122 [o] size 126

In the top of this message, this line: a:2:{i:0;s:3:"110";i:1;s:3:"116";}
is telling that the product match size 110 and size 116.

The Facet by Meta output should be listing just a list of sizes, and when you click on one size, it should show products which is matching that size.
So the Facet by Meta output should just be showing like:
110
116
122
128

I hope it makes sense to you, and you could help me with a clue on which hooks to use to archive this? 😊 Thanks a lot for your help!

**Comment by felipeelia** [comment]
Hey @jonasborneland, thanks for opening the issue. With the current codebase, I'm afraid that is not possible. One thing you could do is create a new FacetType to cover that use case. The new class could extend the Meta\FacetType class, and change at least these two methods:

- get_meta_values (so you display the proper list of different values) and
- add_query_filters (so you can apply the proper selection)

I _think_ you could even use the same Renderer class being used by the regular Meta block.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!

**Comment by felipeelia** [comment]
Oh, I forgot to say but installing the [Debugging plugins](https://10up.github.io/ElasticPress/tutorial-debugging.html) can help you a lot to understand what info Elasticsearch received and how you could use that to filter results.

**Comment by jonasborneland** [comment]
Thank you very much for the answer, I will be looking into this :)
