### ISSUE TITLE
Handle WP_Query caching

### ISSUE THREAD

**Issue by spacedmonkey** [10up/ElasticPress#3099]
**Is your enhancement related to a problem? Please describe.**
In WordPress 6.1, caching is enabled by default in WP_Query. See https://github.com/WordPress/wordpress-develop/commit/7f7d616d822b79c952cbd6a3046a6f6a8aa5a35e. Caching could effect this plugin.

**Describe the solution you'd like**
Disable caching for WP_Query query caching if elastic search in play.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by oscarssanchez** [comment]
Hi @spacedmonkey ,

Thanks for this, I didn't notice issues on my testing, did you noticed a problem or is it more like a heads up?

Thanks!

**Comment by spacedmonkey** [comment]
It is a heads up. But it is likely that some testing or tweaks will be required.
