### ISSUE TITLE
Post meta saved on the 'save_post' hook is never up-to-date in Elasticsearch

### ISSUE THREAD

**Issue by Faison** [10up/ElasticPress#310]
I ran into an issue recently where a post's meta wasn't saved in Elasticsearch after creating the post, but would show up in Elasticsearch after updating said post once. This lead me to find something that seems kind of like a big deal:

ElasticPress syncs a post with Elasticsearch on the `transition_post_status` hook, which happens several hooks before the `save_post` hook. This means that any custom meta saved or updated on the `save_post` hook will never be up-to-date in Elasticsearch.

You can use the following steps and gist in order to reproduce this issue:

*(stick in functions.php or include it)* https://gist.github.com/Faison/0d6f77d440873186fcff

1. Go to the "Add New Post" screen
2. Fill out the Title and Content with anything
3. Put the value `test1` in the EP Test Field
4. Publish the post
5. Check what is stored in Elasticsearch by going to the direct url for the post in Elasticsearch (something like http://192.168.50.4:9200/sitedev-1/post/2813?pretty - where 2813 is the post id of the new post, sitedev-1 is the ES index, and the ip address is the IP address for your elasticsearch server)
6. You'll notice that `eptest_test_meta_key` does not exist for the new post
7. Edit the post published in step 4
8. Update EP Test Field to the value `test12`
9. Update the post
10. Check what is stored in Elasticsearch the same way you did in step 5
11. Check the value stored for `eptest_test_meta_key`, it will be `test1`, which is one update behind.

Currently, I'm not sure what the best solution to this issue is, but I wanted to bring this up here while I put some thought into it.

Thanks,
Faison

**Comment by tlovett1** [comment]
This is related to #264. @allan23 can you investigate?

**Comment by tuanmh** [comment]
> ElasticPress syncs a post with Elasticsearch on the transition_post_status hook, which happens several hooks before the save_post hook. This means that any custom meta saved or updated on the save_post hook will never be up-to-date in Elasticsearch.

We had this problem before and actually had several workaround to make it work properly. But I'm pretty sure that EP 1.5 does not use that hook anymore, now it's using ``wp_insert_post`` which is even below ``wp_save_post`` https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-sync-manager.php#L22. Updating to 1.5 would help.

**Comment by Faison** [comment]
@tuanmh That did it. Somehow I missed the update, so this ticket is completely a non-issue. Good choice of hook, that's actually the one I was going to suggest if it wasn't already fixed.

Thanks again!

**Comment by tlovett1** [comment]
Woot
