### ISSUE TITLE
BUG: Autosuggest doesn't allow click through when you customized the itemHTML value

### ISSUE THREAD

**Issue by praggmatica** [10up/ElasticPress#3107]
**Describe the bug**
After using the wp.hooks.addFilter() functionality on ep.Autosuggest.itemHTML filter, I can click on the item itself when the autosuggest list comes through, but it does not go to the page link.

**Steps to Reproduce**
1. Install ElasticPress 4.3.1 and WordPress 6.0.3
2. Setup ElasticPress install with the ElasticPress.io host and Autosuggest, Post Search, and Facets turned on, everything else disabled.
3. Add to your theme's javascript file functionality under "Customize Suggestion Markup" as seen on this documentation and change the HTML to different markup than the example: https://10up.github.io/ElasticPress/tutorial-theme-integration.html. Retain the class names such as .autosuggest-link.

**Expected behavior**
When I click on a link provided by the Autosuggest, I expect to my browser to be directed to that page.

**Environment information**
 - Device: Kinsta server
 - OS: Ubuntu
 - Browser and version: Any browser
 - WordPress version: 6.0.3
 - ElasticPress version: 4.3.1
 - Elasticsearch version: ?
 - Where do you host your Elasticsearch server? elasticpress.io
 - What ElasticPress features do you have currently active? Post Search, Autosuggest, Facets

**Additional context**
Unfortunately I can't provide specific theme or website details, but it's a custom WordPress classic theme (non-block).

I was able to determine that the issue was the plugin because if I remove the e.preventDefault(); line from the autosuggest-script.min.js file (it's on line 317 in the uncompressed file under assets > js > autosuggest > index.js), the links operate as expected.

If I remove the customization to ep.Autosuggest.itemHTML and leave the e.preventDefault(); in the min.js file, the links also operate as expected.

**Comment by JakePT** [comment]
Hi @praggmatica, are you able to share the code you're using to change the markup? Also, you mention you retained the class names, but are you retaining the other attributes that are required, as per the documentation?

>Note that the `class`, `id`, `role`, `aria-selected`, `data-url`, and `tabindex` attributes in the returned markup must match the default values for those attributes, as they do in the example, to ensure that Autosuggest functions as normal.

**Comment by praggmatica** [comment]
Sure, here's the code I'm using:

```
const autosuggestItemHTMLFilter = (itemHTML, option, index, searchText) => {
    var title = option._source.post_title;
    var escapedText = title;
    var excerpt = option._source.post_excerpt;
    var thumbnail = option._source.thumbnail;
    var resultsText = escapedText;
  
    if( thumbnail != 'undefined' && thumbnail != null ) {
      thumbnail = '<span class="image"><img src="' + thumbnail.src + '"></span>';
    } else {
      thumbnail = '<span class="image"></span>';
    }

    var convertedHTML = $.parseHTML(itemHTML);
  
    $(convertedHTML).find('.autosuggest-link').empty().append(thumbnail + '<span class="text"><span class="title">' + resultsText + '</span><span class="excerpt">' + excerpt + '</span></span>');
  
    itemHTML = $(convertedHTML).prop('outerHTML');
    
    return itemHTML;
  };
  wp.hooks.addFilter('ep.Autosuggest.itemHTML', 'THEMENAME/autosuggestListHTMLFilter', autosuggestItemHTMLFilter);
```

I did consider that maybe my HTML was not formatted correctly with the right parameters, so I thought if I just replace the inside of the <a> tag rather than rewriting the whole <li> (originally I had it the way the example shows with this different inside piece with the thumbnail and such), maybe it would fix the problem. But unfortunately, it still won't click through unless I remove this or remove the preventDefault call in the min.js.

Also, where it says "THEMENAME", that is replaced with the folder name of my active theme.

Thanks!

**Comment by JakePT** [comment]
Hi @praggmatica, thanks for sharing the code. That was super helpful. It looks like there is indeed a bug in click handling with Autosuggest. In its current form it doesn't like elements inside the `.autosuggest-link` element. So if you omit the `<span>` elements around the text then it should be possible to click the suggestion, but clicking on the image may still cause issues. We'll work on implementing a fix but we'll just need to make sure we don't break any existing filters.

**Comment by praggmatica** [comment]
> Hi @praggmatica, thanks for sharing the code. That was super helpful. It looks like there is indeed a bug in click handling with Autosuggest. In its current form it doesn't like elements inside the `.autosuggest-link` element. So if you omit the `<span>` elements around the text then it should be possible to click the suggestion, but clicking on the image may still cause issues. We'll work on implementing a fix but we'll just need to make sure we don't break any existing filters.

Thank you, I appreciate this! I'll keep my temp fix (took out the preventDefault in the min file) until the release comes out.
