### ISSUE TITLE
QUESTION: Autosuggest is not working

### ISSUE THREAD

**Issue by pranavstorepro** [10up/ElasticPress#3112]
Installed ElasticPress 4.3.1 configured the search and its working fine.

But the Auto-suggest is not working.

This is the setup,i followed https://prnt.sc/kfHkozNApvG3
using elementor search form

Any idea,why it is not working
There is no errors in the console or requests in Network tab

Thanks!

**Comment by felipeelia** [comment]
Hi @pranavstorepro, you will need to provide an Endpoint URL to have it working. That would be a *public* URL, directly accessible to all your users, so please take security into account. We have more info about it in [this article](https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups) (under the Autosuggest header.) More info can be also read in [this GitHub issue](https://github.com/10up/ElasticPress/issues/2518).
