### ISSUE TITLE
BUG: WC product admin area search custom meta

### ISSUE THREAD

**Issue by jonasborneland** [10up/ElasticPress#3116]
**Describe the bug**

Hi
I have a barcode field which is '_wpm_gtin_code' and I have added it through `add_filter(	'ep_weighting_fields_for_post_type'`
The field is also made searchable in Search Fields & Weighting. The '_wpm_gtin_code' is also whitelisted in ep.

The barcode is working for the searchfield in the frontend – but it wont show any results searching in the admin area of wc products.

The code I've used:
```
add_filter( 'ep_prepare_meta_whitelist_key', function( $allow, $meta_key ){
    $meta_keys = ['_wpm_gtin_code']; // meta keys you want to allow
    return in_array( $meta_key, $meta_keys );
}, 8, 2 );

function epio_blog_add_custom_field_ep_weighting( $fields, $post_type ) {
	if ( 'product' === $post_type ) {
		if ( empty( $fields['meta'] ) ) {
			$fields['meta'] = array(
				'label'    => 'Custom Fields',
				'children' => array(),
			);
		}
		$key = 'meta._wpm_gtin_code.value';
		$fields['meta']['children'][ $key ] = array(
			'key'   => $key,
			'label' => __( 'EAN stregkoder', 'textdomain' ),
		);
	}
	return $fields;
}
add_filter(	'ep_weighting_fields_for_post_type', 'epio_blog_add_custom_field_ep_weighting',	10,	2);
```

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - ElasticPress version: 
 - Elasticsearch version: 
 - Where do you host your Elasticsearch server? 
 - What ElasticPress features do you have currently active? 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by felipeelia** [comment]
Hey @jonasborneland, to have that working on the admin side you will need to use the `ep_woocommerce_admin_products_list_search_fields` filter too. Something like this:

```
add_filter(
	'ep_woocommerce_admin_products_list_search_fields',
	function ( $wc_admin_search_fields ) {
		$wc_admin_search_fields['meta'][] = '_wpm_gtin_code';

		return $wc_admin_search_fields;
	}
);
```

The current documentation of that filter is actually wrong but we will update it for the next release already. Thanks!

**Comment by jonasborneland** [comment]
Hi @felipeelia 

Thank you so much for the answer!
It does work, however it's not working on variant products.
If searching a barcode for a simple product, it does work.
But searching for a barcode belonging to a variant/size it won't match anything

Is it possible to make it work with variant products? :)

Or is it possible to disable ep for the admin area product search?

**Comment by jonasborneland** [comment]
@felipeelia Any idea how I can get admin search to include the barcode on variations? :)
The snippet you sent, works perfect for simple products, but not variations.
The frontend works for both simple and variable products, so seems only to be admin search that dosen't include variations

**Comment by felipeelia** [comment]
Hi @jonasborneland, that is not so easy to debug, so I'll outline the steps here so you can have something to start with.

### Check how the product variation is indexed in Elasticsearch
- Install the [debug plugins](https://10up.github.io/ElasticPress/tutorial-debugging.html)
- Search for something in the admin that does return the product variation you want
- In Debug Bar ElasticPress, check the Query Results and see how that product variation is indexed
1. If the product variation is not indexed at all, you might need to make some changes to have the product variation indexed
2. Looking at the information of the product variation indexed in Elasticsearch, determine if the meta field you need is already indexed. Again, if that specific field is not indexed for variations, you might need some change in the code

### Check why it is not returned by the search
- Make the search by barcode
- In Debug Bar ElasticPress, check the Query body
- Determine if the barcode field is in the list of fields searched specifically for product variations
- Make the necessary changes to have it added
----

Unfortunately, that is as far as we can go without having a codebase and database dump copy. If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks.
