### ISSUE TITLE
QUESTION: search on multiple indexes (cross domain search) is not possible using third-party elasticsearch service?

### ISSUE THREAD

**Issue by moisb** [10up/ElasticPress#3117]
hello, I can't pay for ElasticPress monthly plan, but I need the user to be able to fetch results from site A and site B at the same time. I used WPSolr for that, but that plugin has bad performance and numerous bugs.
**So I tried the following:** I created an index/deployment on Elastic.co, I installed ElasticPress on the 2 sites, and connected them both to the same index I created, I synchronized the 2 sites on this same index, **but unfortunately each site only shows its own results**, not the other's.

anyway, I need a search that the user does on site A, to show results from site A and site B, and vice versa. how do I do it?

**Comment by felipeelia** [comment]
Hi @moisb, if those two sites are part of the same multisite installation, you can activate ElasticPress at the network level and change the main WP_Query, adding the `'sites'` parameter. (More info [here](https://10up.github.io/ElasticPress/tutorial-indexables.html#post-indexable)). In ElasticPress 4.4.0 that parameter will be deprecated in favor of `'site__in'` and `'site__not_in', so keep that in mind.

If those sites are not in the same network/installation, you can try to use the `ep_query_request_path` filter to change the URL targeted by the request to change the index names that should be used. Depending on how your data is structured, you will also want to tweak the results using WordPress's `posts_pre_query` filter (with a priority higher than 10, so you can use whatever ElasticPress returned.)

In both of those scenarios, you would be using different indices for each site.

Although this is a very interesting use case, it falls outside of the support we provide here on GitHub. If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!
