### ISSUE TITLE
Password protected posts

### ISSUE THREAD

**Issue by Stayallive** [10up/ElasticPress#312]
I was wondering what the thought is on password protected posts...

They are currently indexed just fine, I think this should or be noted in the docs or be excluded by default with an option to include them.

**Comment by tlovett1** [comment]
Do password protected posts show up in normal WP search?

**Comment by Stayallive** [comment]
Yep, should have checked that first, they do show up in normal WP search.

So should there be an Wiki entry or some sorts with a `ep_post_sync_kill` filter example?

**Comment by tlovett1** [comment]
A wiki entry would definitely be cool.
