### ISSUE TITLE
QUESTION: Auto index and delete (sync) when importing with wpallimport in real-time

### ISSUE THREAD

**Issue by spithash** [10up/ElasticPress#3140]
hello there, I am reading here and there that for auto indexing and auto deleting products programmatically, I  have to use these two functions:

\ElasticPress\Indexables::factory()->get( 'post' )->index( $post_id, true )
\ElasticPress\Indexables::factory()->get( 'post' )->delete( $post_id, true )

Is there anyone who've done something similar? Maybe some function to run inside the theme's funcions.php?

I've tried this one which doesn't work:

```
function sync_on_product_save(){
  $product_Id = get_the_ID();
  ElasticPress\Indexables::factory()->get( 'post' )->index( $product_Id, true );
  return;
}
add_action('woocommerce_update_product', 'sync_on_product_save', 10, 1);
```

I see that the function gets executed but nothing happens. 

All I want to do is make sure syncing works in real time for both indexing and deleting woocommerce products, I am importing thousands of products 24/7 

Thank you for the fantastic work you are providing.

**Comment by felipeelia** [comment]
Hi @spithash, you should not need any custom code to have products synced with Elasticsearch, so it seems to be something specific to WP All Import. In [this comment](https://github.com/10up/ElasticPress/issues/2654#issuecomment-1067195922), I left some settings that you might want to change to see if that helps. Can you please try that and let us know the results? Thanks!

**Comment by spithash** [comment]
As a matter of fact, I had both options turned on, I disabled them and now it works my friend :)

I can confirm everything is working as it should.

Thank you very much!
