### ISSUE TITLE
TESTRESULT: Using ElasticPress with Elasticsearch 8.4.2 in Elastic Cloud

### ISSUE THREAD

**Issue by felix-lessoer** [10up/ElasticPress#3141]
In the readme you asked to add a issue when testing with newer versions of Elasticsearch.
I am using ElasticPress with Elasticsearch Version 8.4.2 by Elastic Cloud and I am able to replace the normal Wordpress Search using it.

I can't say if all the features are working perfectly well, but so far it looks good.
If you like to have a look: [Elastic Content Share](https://elastic-content-share.eu/)

If you need to setup an Elastic Cloud Cluster with ElasticPress do this:
1.) Sign Up with Elastic Cloud
2.) Use the Elasticsearch Endpoint and enter it under "3rd Party" Elasticsearch Server within the ElasticPress configuration
![image](https://user-images.githubusercontent.com/35069463/203052952-1db2c23d-f9cd-42f9-b8c0-2bf74af54bca.png)

3.) Go to your `wp-config.php` file and add ES Shield configuration. For me it was important to not put it at the end of the file to make it work. Also make sure that your user has appropriate permissions. Using default elastic user is working, but may be a security risk.
`define( 'ES_SHIELD', '<username>:<password>' );`

**Comment by MonGMZ** [comment]
Hi,
I've tested with new elastic v8.5.1 and it seems to work fine, except for the autosuggest. Did you try to make it work @felix-lessoer ? Thanks

**Comment by felix-lessoer** [comment]
Hi,

I see that I have autosuggested search terms based on the search terms that where already used. 
However it seems not using Elasticsearch auto completion feature for that.

**Comment by abdulraheemalick** [comment]
Hey @felix-lessoer, I can also confirm Autosuggest is not working with 8.5.1

Were you able to come up with a workaround or fix?

**Comment by MonGMZ** [comment]
> Hi,
> 
> I see that I have autosuggested search terms based on the search terms that where already used. However it seems not using Elasticsearch auto completion feature for that.

Could it be the web browser's autocomplete history?

**Comment by harrywang** [comment]
8.7.0 worked (data synced to es server by following your instruction @felix-lessoer - thanks!!)
<img width="947" alt="Screenshot 2023-06-12 at 2 52 13 PM" src="https://github.com/10up/ElasticPress/assets/595772/6c62d839-fe89-41b6-b07d-53bc23247a30">

**Comment by jerasokcm** [comment]
I tried the steps suggested by @felix-lessoer to make Elasticpress work with Elasticsearch 8.10.4, but it is not working in my case.  
Do you add the port 9243 at the end of the URL?
I'm using the user "elastic" and the password generated during the Elastic Cloud deployment. Is that correct?

**Comment by felix-lessoer** [comment]
@jerasokcm can you share which error you are facing?

**Comment by jerasokcm** [comment]
Hello, @felix-lessoer 
The Elasticsearch host URL is not saved in the configuration page, after trying to use the Elastic Cloud URL/port. Since connection to the server is not possible, it reverts to the previous value (a local hosted Elasticsearch instance, which works fine http://10.100.0.4:9200).
