### ISSUE TITLE
QUESTION: Sync running non-stop without making any progress

### ISSUE THREAD

**Issue by ceejau** [10up/ElasticPress#3142]
![ep issue](https://user-images.githubusercontent.com/67996335/203272380-2933fa96-bbad-4cf2-a6a0-912f26211dbd.png)
 I am having a similar issue where this sync is running non-stop without making any progress and without hindering the search functionality on my wordpress website. We were running "wp elasticpress index --setup --per-page=1 --url= " to remove some of the files which were deleted and were coming up in search results. After a while this process started in its own and i cant stop it from the dashboard, it goes on running again after refersing if i try to stop it. I cannot run the wp reindex command from shell as it shows an index is already in progress.

**Comment by felipeelia** [comment]
@ceejau, what version of the plugin are you using? To stop an ongoing sync you can run `wp elasticpress clear-index`. Then, to start a new sync, use `wp elasticpress index --setup --per-page=1 --show-errors --url=<URL>` to see if there is any error happening. It is important to note that that --url parameter should receive a URL and not be sent empty.

**Comment by ceejau** [comment]
does the wp elasticpress clear index affect the existing indices anyways? as in will it clear it and affect the search results?

**Comment by ceejau** [comment]
> @ceejau, what version of the plugin are you using? To stop an ongoing sync you can run `wp elasticpress clear-index`. Then, to start a new sync, use `wp elasticpress index --setup --per-page=1 --show-errors --url=<URL>` to see if there is any error happening. It is important to note that that --url parameter should receive a URL and not be sent empty.

version 4.2.  will the command delete the existing indices or cause the search functionality to break?

**Comment by felipeelia** [comment]
No, unfortunately, the command name is a bit misleading (and will be changed to `clear-ongoing-sync` in ElasticPress 4.4.0) but it won't affect any index in Elasticsearch, it will just unstuck the sync process.

Also, please use the latest version of the plugin, we've added some error handling in that already.

**Comment by ceejau** [comment]
> No, unfortunately, the command name is a bit misleading (and will be changed to `clear-ongoing-sync` in ElasticPress 4.4.0) but it won't affect any index in Elasticsearch, it will just unstuck the sync process.
> 
> Also, please use the latest version of the plugin, we've added some error handling in that already.

This issue is currently in my live site, can I test the command in lower instances? I do not have this issue there though. What could be the cause of the issue? Could it be that i might have run the command without the url in --url=<URL> parameter or any other sytax error in " wp elasticpress index --setup --per-page=1 --show-errors --url=<URL> " . Just checking to see if i can replicate it.

**Comment by ceejau** [comment]
> wp elasticpress clear-index

I ran this command . Still the process is stuck

![image](https://user-images.githubusercontent.com/67996335/203755541-044e0b63-80d3-4bd0-a378-1f69266b869c.png)
version in use

**Comment by felipeelia** [comment]
@ceejau did you already try running those commands after upgrading the plugin to the latest version? Also, are you using object cache? If so, you might need to flush your cache.

**Comment by ceejau** [comment]
> wp elasticpress clear-index

@felipeelia is there any resource or guide on checking and flushing object cache ?

**Comment by felipeelia** [comment]
[`wp cache flush`](https://developer.wordpress.org/cli/commands/cache/flush/) is the easiest way to flush it. To debug it further, it is needed to check how WordPress is getting the `ep_index_meta` option value. Checking how it replies to a call to `wp option get ep_index_meta` and how it is looking in the database might clarify which layer is returning the wrong result.

Also, we've made a change in ElasticPress 4.4.1 that might fix this issue.
