### ISSUE TITLE
Non stop syncing

### ISSUE THREAD

**Issue by ceejau** [10up/ElasticPress#3144]
![image](https://user-images.githubusercontent.com/67996335/203313836-c2701c95-32e3-4933-b859-b0b9b7a02b90.png)
I am having an similar issue where this sync is running non-stop without making any progress and without hindering the search functionality on my wordpress multisite website. We were running "wp elasticpress index --setup --per-page=1 --url= " to remove some of the files which were deleted and were coming up in search results. After a while this process started in its own and Icant stop it from the dashboard, it goes on running again after refreshing if i try to stop it. I cannot run the wp reindex command from shell as it shows an index is already in progress.
@oscarssanchez @mi-um @barryceelen

**Comment by felipeelia** [comment]
@ceejau please stop opening new issues and leaving comments in existing ones, this will **not** speed up the process of getting back to you. I will close this issue in favor of #3142, and we will get back to you there as soon as possible. Thanks for understanding.
