### ISSUE TITLE
QUESTION: How to Change the Number of Autosuggest Results

### ISSUE THREAD

**Issue by abdulraheemalick** [10up/ElasticPress#3146]
**Describe your question**

Hi.

I use Elasticpress for our Woocommerce site and I've been able to tweak it for our use case. However, I am having trouble with one issue.

I need to change the number of results returned by the Autosuggest feature.

While testing, I noticed that it matches the WordPress Reading setting 'Blog Page return `x` Articles'

I am using Breakdance for our site which doesn't have great Search page customization options. It also depends on the same setting.

I have set this to `A` because I want our Search results page to to display `A` results in order to have `A` results and avoid customers from navigating much to find a result.

However, with the `A` setting, Autosuggest takes more than 2 seconds to load and it returns a messy list of results (overflows).

With a lower setting of say `B`, Autosuggestions load in sub 300ms speeds.

Is the a way I can set the number of results for the Autosuggest endpoint separately from the WordPress setting.

Found a similar question here - https://wordpress.org/support/topic/search-results-count-2/ but not sure if they ever made it to GitHub

**Comment by oscarssanchez** [comment]
@devTheodul we have a handy set of filters in the plugin. You are looking for this one https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Autosuggest/Autosuggest.php#L578

**Comment by abdulraheemalick** [comment]
Gee thanks. @oscarssanchez 

Guess, I was looking in the wrong place and the wrong filter name.
