### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by paoloburzacca** [10up/ElasticPress#3153]
![immagine_2022-11-23_221327625](https://user-images.githubusercontent.com/1489602/203647083-1f2fb78a-58ff-4a5b-b96c-7f0b8e5d98ae.png)

I have issues on initial syncing. I tried several times, both with browser and Wp Cli.
They stop at the same point as you see in picture. It seems it tries to sync always the same post and not going on. I cannot find any error in log

Wp Cli blocks forever here, the PHP process remains active.
"Processed posts 149000 - 150000 of 176365".

How can i solve?

Thank you

**Comment by oscarssanchez** [comment]
Hey @paoloburzacca ,

Try these commands in order

```
wp elasticpress stop-indexing
wp elasticpress clear-index
wp elasticpress index --setup --per-page=1 --show-errors
```

**Comment by paoloburzacca** [comment]
same problem...cli is stopped, web sync still going with same last object
id in loop.
no error showed

[image: image.png]

Il giorno gio 24 nov 2022 alle ore 18:26 Oscar Sanchez S. <
***@***.***> ha scritto:

**Comment by oscarssanchez** [comment]
@paoloburzacca , does the sync starts from 0 or from 149000 - 150000 ?

If it is the latter, can you try a CLI sync with offsetting those posts? say start from 150001.  

As a side note, it seems you are syncing 1,000 items per cycle, can you lower that down to default if that's the case?

**Comment by felipeelia** [comment]
In addition to that, can you please share with us:
1. The version of ElasticPress being used
2. If you have Object Cache enabled

There is an ongoing issue with a similar problem: https://github.com/10up/ElasticPress/issues/3142

**Comment by 9bureau** [comment]
ElasticSearch version: 7.10.2
ElasticPress version: 4.3.1
Php version: 7.4

in Wp Health Status I see this next to : Elastic Search Last Sync errors (by Dashboard Sync)
0: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

But it is an old sync, then I tried several times with wp cli

about Object Cache  I don't know...I use Wp Rocket

**Comment by paoloburzacca** [comment]
ElasticSearch version: 7.10.2
ElasticPress version: 4.3.1
Php version: 7.4

in Wp Health Status I see this next to : Elastic Search Last Sync errors
(by Dashboard Sync)
0: Allowed memory size of 134217728 bytes exhausted (tried to allocate
20480 bytes)

But it is an old sync, then I tried several times with wp cli

about Object Cache I don't know...I use Wp Rocket

Il giorno lun 28 nov 2022 alle ore 13:13 Felipe Elia <
***@***.***> ha scritto:

**Comment by oscarssanchez** [comment]
Hi @paoloburzacca ,

Your hosting provider or developer should be able to help you with determining if you have Object cache or not.

For now you can try to run this SQL

`SELECT * FROM 'wp_options' WHERE 'option_name' LIKE '%ep_%'`

And delete the options that start with the `ep` prefix. You might need to set your host again.
