### ISSUE TITLE
QUESTION: Empty / blank pagination pages

### ISSUE THREAD

**Issue by spithash** [10up/ElasticPress#3160]
Hello there, I am having an issue with the pagination on my site.

While everything works great in real-time when importing products with wp all import, I mean new products are shown on the store and search results, and deleted products disappear correctly, the paginated pages remain there as if I still have those products that got deleted.

For example, if my store has 1000 products and the pagination goes up to 100 pages, if I delete 50 products, the pagination still shows 100 pages where it should only show 95, leaving 5 empty pages in the pagination.

They remain there empty and the only way to make them go away is to "Delete all Data and Start a Fresh Sync".

Can someone suggest something to test and solve this?

(Note that I'm not using either "Protected Content" or "Terms" in my index, just "WooCommerce" in ElasticPress Features settings page)

Thank you very much.

**Comment by oscarssanchez** [comment]
@spithash  That probably means the import plugin is bypassing normal WordPress functions/hooks as ElasticPress integrates with post deletion. See https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/SyncManager.php#L60 

I think there's a couple things you can do:

* Ask the WP All import developers if they integrate wtih the delete hook, ask them more specifics about their integration, probably something they will have to fix, or something you might need to add like https://github.com/10up/ElasticPress/issues/2654#issuecomment-1067195922
*  If they don't integrate, check if they have a hook and write some custom code similar to `action_delete_post()` to account for your particular need.
* If they do integrate and you are doing the right things it might be a bug in ElasticPress, filling the bug report template with steps to reproduce so we can fix would be great. 

Alternatively, we also offer some paid consulting time if you would like to do that as well https://www.elasticpress.io/elasticpress-consulting/

**Comment by spithash** [comment]
Thank you, I will ask the folks from wpallimport about that and I'll come back

By the way, I do have both WP_IMPORTING and "Increase speed by disabling do_action calls in wp_insert_post during import" settings to off, no issue with that...

**Comment by spithash** [comment]
Hello again,

I asked the team @ wpallimport and they said that:

> We use wp_delete_post to delete posts (see https://developer.wordpress.org/reference/functions/wp_delete_post/), which fires the delete_post hook

**Comment by oscarssanchez** [comment]
Hi @spithash ,

Can you fill in the Bug report template for us to reproduce? Being as detailed as possible (for example, we don't know how are you doing the import on the WP all import plugin, settings etc) definitely help us with troubleshooting. Another one that is really helpful is to try to reproduce it on your own with a data set that you synthetically create, and share the details on how you created the data for us to do the same.

You'll probably want to open a new issue so that it is easier for you to select the template. I'll close this one for now. 

Thanks!
