### ISSUE TITLE
ElasticPress 4.4.0 issues

### ISSUE THREAD

**Issue by paoloburzacca** [10up/ElasticPress#3168]
With new 4.4.0 version, I cannot open admin Sync page, it loads until I found timeout error on logs.
Sync seems to work with wp cli, but in status report page, the last sync shows me only syncs done from wp dashboard.

**Comment by paoloburzacca** [comment]
file: /wp-content/plugins/elasticpress/includes/classes/Indexable/Post/Post.php
row:  2429
error type: E_ERROR
error msg: Maximum execution time of 300 seconds exceeded

**Comment by paoloburzacca** [comment]
in my site the query "_SELECT DISTINCT meta_key FROM {$wpdb->postmeta} ORDER BY meta_key_" in that line gives me this output:

**193992 rows in set (21.774 sec)**

if i change in 

_SELECT DISTINCT meta_key FROM {$wpdb->postmeta} WHERE meta_key  NOT LIKE '%oembed%' ORDER BY meta_key;_

my output is:

**191 rows in set (4.773 sec)**

**Comment by felipeelia** [comment]
Hi @paoloburzacca,

In ElasticPress 4.4.0 we introduced a check that runs that query. The check is related to the number of fields that will be sent to Elasticsearch, so we can foresee a field limit break before the sync happens. To bypass that check, you can add the following snippet to your codebase:

```php
if ( defined( 'EP_IS_NETWORK' ) && EP_IS_NETWORK ) {
	add_filter( 'pre_site_option_ep_hide_too_many_fields_notice', '__return_true' );
} else {
	add_filter( 'pre_option_ep_hide_too_many_fields_notice', '__return_true' );
}
```

Regarding the Status Report page and the Last Sync section, I can't reproduce this problem. Here are some questions so we can better understand what could be going on:
- Are you in a multisite? If so, is ElasticPress active in the entire network? 
- Did you try to deactivate any cache plugins?

PS.: Please, next time you need to open a bug report, use the template we provide: https://github.com/10up/ElasticPress/issues/new?assignees=&labels=bug&template=1-bug-report.yml&title=BUG%3A+ Thanks

**Comment by rafaucau** [comment]
I have the same problem. After upgrading to EP 4.4.0, the Status Report page and the Last Sync section loads very slowly.
I'm not on multisite.

![image](https://user-images.githubusercontent.com/25438601/205464079-0200fa35-ba63-4226-bfef-a497678a321b.png)
![image](https://user-images.githubusercontent.com/25438601/205602762-a2d8396b-6231-4ff1-9b5d-90770a6f1f4c.png)

**Comment by rafaucau** [comment]
![image](https://user-images.githubusercontent.com/25438601/205602469-9bb3a10f-c01f-4ba4-9ca0-560adff409dd.png)

**Comment by felipeelia** [comment]
Hi @rafaucau,

Did you try the code I shared in [this comment](https://github.com/10up/ElasticPress/issues/3168#issuecomment-1332007860)?

**Comment by rafaucau** [comment]
Hi @felipeelia 
Unfortunately, this code didn't help.

![image](https://user-images.githubusercontent.com/25438601/205686566-be4039ff-b511-440a-8ef2-093ec53fd417.png)

Are you sure the hook names are correct? I can't find them in the ElasticPress code.

---

Adding `NOT LIKE '_oembed%'` to the queries helped.

**Comment by rafaucau** [comment]
@felipeelia It looks like v4.4.1 does not fix this issue
`/wp-admin/admin.php?page=elasticpress-status-report#failed-queries`
![image](https://user-images.githubusercontent.com/25438601/211918848-5f90399d-28e5-47fb-815e-5a2fe546bc86.png)

I also tried with filters:
```php
add_filter( 'transient_ep_meta_field_keys_post', '__return_false' );
add_filter( 'transient_ep_meta_field_keys', '__return_false' );
```

**Comment by felipeelia** [comment]
Hey @rafaucau,

That is unfortunate. Can you please try the following code:

```php
add_filter( 'ep_post_pre_meta_keys_db', '__return_empty_array' );
add_filter( 'ep_post_pre_meta_keys_db_per_post_type', '__return_empty_array' );
```

That will prevent ElasticPress from running all the meta keys-related SQL queries (but will empty the "Indexable Content" section.) If even with that it still times out it might indicate it is actually struggling with something else, like the post count or getting the fields limit from your Elasticsearch server.

**Comment by rafaucau** [comment]
HI @felipeelia,
Thanks, after adding these filters the status page loads quickly.
