### ISSUE TITLE
Instant Results vs Autosuggest

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#3174]
### Describe your question

What is the difference between Instant Results and Autosuggest? 

Don't they both provide instant results?

Also, if I'm self hosted and already have a proxy set up for Autosuggest, do I need anything else to use Instant Results?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Hi @shmaltz , there's a couple of resources to clarify what instant results do:

https://www.elasticpress.io/blog/2022/03/introducing-instant-results-wordpress-fastest-search-ever/
https://elasticpress.zendesk.com/hc/en-us/articles/360050447492-Configuring-ElasticPress-via-the-Plugin-Dashboard#:~:text=Instant%20Results%20(ElasticPress%204.0%2B),enter%20queries%20and%20filter%20results.

As noted in the first article you'll need to install the proxy for Instant results https://github.com/10up/elasticpress-proxy

**Comment by JakePT** [comment]
Just as some additional information, Autosuggest provides the list of suggestions as you type into a search field:

![Screenshot 2022-12-02 at 6 02 41 am](https://user-images.githubusercontent.com/4100733/205137830-82887092-e13f-49dd-b660-35f4607f9c6f.png)

Whereas Instant Results is a more full featured search that displays a paginated list of search results with thumbnails and descriptions and support for faceted search/filters. It is displayed in a popup when the search form is submitted:

![Screenshot 2022-12-02 at 6 05 25 am](https://user-images.githubusercontent.com/4100733/205138320-6cf0877b-b2f0-46de-ae97-431d7d014a16.png)

In its current form it is essentially a replacement for your search results page.

**Comment by shmaltz** [comment]
Got it. Thanks!

Would be cool if these 2 features could somehow be merged, so as we were typing our search, the autosuggest would show more details like the photo and price, just like the instant results does.

**Comment by JakePT** [comment]
@shmaltz If you're comfortable coding we have some documentation on customising the display of Autosuggest, including adding images: https://10up.github.io/ElasticPress/tutorial-theme-integration.html

With that I'm going to go ahead and close this ticket, since I believe we've answered your question.
