### ISSUE TITLE
Weight results by date and WooCommerce Products

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#3177]
### Is your enhancement related to a problem? Please describe.

If "Weight results by date" is enabled, the search results for WooCommerce products are often not what is intended, as usually the publish date of a product should not interfere with its position in search.

### Describe alternatives you've considered

We could disable that behavior in product-only WP Queries. To do that we could 
1. Create a new setting in the WooCommece feature
2. Change the existent setting in the Post Search feature to Enabled/Disabled/Disabled in product queries (to be displayed only when the WC feature is enabled)
3. Disable it via code and add a filter to change that (following the ["decisions, not options" philosophy](https://wordpress.org/about/philosophy/#decisions))

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NV607FOX** [comment]
Going with option 2 (with a 4th option to disable weighting in any query that includes products)

**Comment by MARQAS** [comment]
Steps we can follow to get this done:
- Check if WC is activated or not and add new settings: 
Something like:
```
	$woocommerce = Features::factory()->get_registered_feature( 'woocommerce' );
			if (  $woocommerce->is_active() ) {
				// Let's add new options
			}
```
			
- Add a new function to figure out which option is selected
- Based on that function, return the args without formatting them. 
- Files to make the changes: `weight_recent in Search.php` and  `do_weighting in weighting.php`
