### ISSUE TITLE
Move the Users Indexable to ElasticPress Labs

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#3180]
### Is your enhancement related to a problem? Please describe.

As stated in [ElaticPress 4.4.0 changelog](https://github.com/10up/ElasticPress/releases/tag/4.4.0), we will be moving the Users Indexable to [ElasticPress Labs](https://github.com/10up/ElasticPressLabs). In order to make that happen, we will need to move the indexable to EP Labs *before* we release EP 5.0.0 (and those two versions will have to coexist for a while, using the EPLabs version if both are available.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickchomey** [comment]
I'm not sure what the right place is to ask this, but this seems as good as any.

Is there an issue or discussion somewhere that goes into some more detail about why Users is being moved to Labs, and Terms and Comments are being hidden? I'm not at all opposed to this, but just want to have a better understanding of the rationale and plans for EP going forward - particularly for what 5.0 will bring. 

Also, does this affect Features and Indexables at all? I make use of those for indexing, syncing and querying custom tables with ElasticPress. 

Thanks!

**Comment by felipeelia** [comment]
Hey @nickchomey, here are some answers for you:

- The Features and Indexables classes are not going to change. I've introduced a visibility concept in #3334 but that won't change anything for custom features.
- The reason behind moving the Users feature to EP Labs is security: as we can not be responsible for everybody's setups and being users a so sensitive feature, we understand it is best placed in a more "Experimental" plugin.
- Regarding Terms and Comments, people often enable those without a real need (especially "Terms" tends to confuse people with "Do I need this to sync a post term?" which is not the case at all.)

**Comment by nickchomey** [comment]
Thanks very much! That makes sense.
