### ISSUE TITLE
pre_get_posts to only show top level CPT is not working while ep_integrate is true

### ISSUE THREAD

**Issue by JiveDig** [10up/ElasticPress#3181]
### Describe your question

I have a CPT called 'food'. On the main `is_post_type_archive( 'food' )` I'm trying to show only top level posts. 

In `pre_get_posts` I have `$query->set( 'post_parent', 0 );`. It only works when I add `$query->set( 'ep_integrate', false );`.

I've re-indexed but still the same issue. Am I missing something else to use `pre_get_posts` with a core archive query and EP?

Thanks :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JiveDig** [comment]
To clarify, this works:

```
add_action( 'pre_get_posts', function( $query ) {
	// Bail if in the Dashboard.
	if ( is_admin() ) {
		return;
	}

	// Bail if not the main query.
	if ( ! $query->is_main_query() ) {
		return;
	}

	// Bail if not the archive we want to target.
	if ( ! is_post_type_archive( 'food' ) ) {
		return;
	}

	// Order by title.
	$query->set( 'orderby', 'title' );
	$query->set( 'order', 'ASC' );
	$query->set( 'post_parent', 0 );
	$query->set( 'ep_integrate', false );
});
```

But this does not:

```
add_action( 'pre_get_posts', function( $query ) {
	// Bail if in the Dashboard.
	if ( is_admin() ) {
		return;
	}

	// Bail if not the main query.
	if ( ! $query->is_main_query() ) {
		return;
	}

	// Bail if not the archive we want to target.
	if ( ! is_post_type_archive( 'food' ) ) {
		return;
	}

	// Order by title.
	$query->set( 'orderby', 'title' );
	$query->set( 'order', 'ASC' );
	$query->set( 'post_parent', 0 );
});
```

The orderby and order work regardless of ep_integrate. Only the post_parent is affected here.

**Comment by felipeelia** [comment]
Hi @JiveDig, this is probably because we are checking if post_parent is empty [here](https://github.com/10up/ElasticPress/blob/4.4.0/includes/classes/Indexable/Post/Post.php#L1723). We should instead check if that is set or not, and then cast it to an integer in the `'post_parent' => $args['post_parent'],`  line.

Would you like to open a PR with that change? Thanks!

**Comment by JiveDig** [comment]
Thanks @felipeelia. Simple bug and fix, I just submitted a PR. Feel free to change/edit as needed :)
