### ISSUE TITLE
Enable "attachment content type" indexing (not document content)

### ISSUE THREAD

**Issue by clemorphy** [10up/ElasticPress#3189]
### Describe your question

Hi

I know you can index documents content by using the ES ingest attachment plugin.
I don't need to search inside the documents content.
I only need to treat WP attachments like any other post type, and search in their title and description.
I tried to use this : 
`add_filter( 'ep_indexable_post_types', function ( $post_types ) {
	$post_types[] = 'attachment';
	return $post_types;
} );`
But it doesn't seem to work.

Is there a way to simply search in attachments title / description?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clemorphy** [comment]
I tried to enable the "ES attachment plugin" and the "Documents" feature in ElasticPress.
It allows to index content of the documents (not what I need), but still not their title and description (what I need).

**Comment by felipeelia** [comment]
Hey @clemorphy,

If you have added the attachment ES plugin and enabled the Documents feature, that should be enough. Make sure you have title, content, and excerpt under "Media" enabled in the Weighing Dashboard.

If you don't want to use the ES plugin, there is some additional code you will need to add:
1. The `ep_indexable_post_types` filter will add the post type but you will also need to add the `inherit` post status with the `ep_indexable_post_status` filter
2. To make it searchable, you will need to use the `ep_searchable_post_types` filter
3. You will need to add the `inherit` post status to the search query as well

All those changes are made in the [Documents Feature PHP file](https://github.com/10up/ElasticPress/blob/4.4.0/includes/classes/Feature/Documents/Documents.php#L44), it is worth checking how the plugin handles that.

I've created this gist with all those changes: https://gist.github.com/felipeelia/ddea93b887d905cadabf7f6211f5c54a Make sure to do a full sync after you have added the code.

**Comment by clemorphy** [comment]
Hi @felipeelia 

Thank you very much for the gist, it was really helpfull.
The part I was missing was :
> **Add the `inherit` post status to a search query, so it can also find attachments**

I can now make attachments titles and excerpts searchable and have my attachments visible in my search results. With no need to enable the ES "Ingest Attachment plugin" nor the EP "Documents feature".
Thanx again!
