### ISSUE TITLE
BUG: All public methods in Command class are treated as a wpcli command

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#3193]
### Describe the bug

The `Command` class has a few methods whose visibility is public, and WP CLI treated these methods as a command. For example, if we run `wp elasticpress custom_get_transient` , WordPress treats this [method](https://github.com/10up/ElasticPress/blob/4.0.0/includes/classes/Command.php#L1214) as a command and eventually ends with the errors. 

### Steps to Reproduce

Run WP CLI command `wp elasticpress custom_get_transient`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Expanding on this a little bit:
- The visibility can't be changed, as the function needs to be hooked into a WordPress filter (WP wouldn't be able to call a protected method, for example.)
- We can circumvent that problem by making the method `static` and hook it using `add_filter( 'pre_transient_ep_wpcli_sync_interrupted', [ __CLASS__, 'custom_get_transient' ], 10, 2 );` (`__CLASS__` vs. `$this`.)
- Running `wp help elasticpress` can help us identify all the methods that need to be changed.
- It is not possible to have two methods with the same name (one static, the other not), so to release this in phases we could:
   - 4.5.0:
      - Create new static methods with slightly different names
      - Add a _ doing_it_wrong() call in the current ones
  - 5.0.0:
      - Remove the older methods
