### ISSUE TITLE
Send options for dashboard syncs

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#3195]
### Is your enhancement related to a problem? Please describe.

Currently, users syncing via WP-CLI have a lot of options: which indexables to sync, post types, ID ranges, etc. Unfortunately, any of those are available for people syncing via the dashboard. 

### Describe alternatives you've considered

We need to:
- Expand the AJAX call that starts an index to send more fields
- Add the ability (a filter perhaps?) to change how that AJAX request is sent

### Related Links
- [WP-CLI options](https://10up.github.io/ElasticPress/tutorial-wp-cli.html)
- [AJAX action](https://github.com/10up/ElasticPress/blob/4.4.0/includes/classes/Screen/Sync.php#L93)
- [AJAX request sent](https://github.com/10up/ElasticPress/blob/e590bc70c69227d45180be0fbba6b9afb211f5da/assets/js/sync/hooks.js#L176)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
As discussed we're going to close this one out. Any filter we add now would only be relevant for the admin-ajax.php action which is probably going to be replaced with a REST API endpoint to support future features, meaning that it would cease to work when that happens.
