### ISSUE TITLE
Deactivate queries when ElasticSearch is down

### ISSUE THREAD

**Issue by leroile22** [10up/ElasticPress#3197]
### Is your enhancement related to a problem? Please describe.

We use ElasticPress for a reason: queries without ElasticSearch would make our server explode.

Unfortunately, when ElasticSearch is down, queries with ep_integrate=true are passed to MySQL, meaning that it will instantly make the server explode.

I would suggest passing a dummy request instead. If not possible by default, is it possible to modify it with a custom code?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Hi @leroile22 ,

When ES fails, In the method hooked to `posts_pre_query` https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/QueryIntegration.php#L354  you have a handy property there: `$query->elasticsearch_success = false`, you may reference it to alter the query, or in your use case it seems you could just return something that's not null per the `posts_pre_query` hook docs:  `Return a non-null value to bypass WordPress' default post queries.`
