### ISSUE TITLE
BUG: Evaluate other assoc_args as booleans

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#3199]
### Describe the bug

With #3185 we can validate values strictly. There are other areas of improvement to implement this for example:

	public function get_last_cli_sync( $args, $assoc_args ) {

		$last_sync = Utils\get_option( 'ep_last_cli_index', array() );

		if ( isset( $assoc_args['clear'] ) ) {
			Utils\delete_option( 'ep_last_cli_index' );
		}

		$this->pretty_json_encode( $last_sync, $this->filter_boolean( $assoc_args['pretty'] ) );
	}

As of now, the original problem we were solving for the pretty flag seems to be true for other scenarios like this. 
		

### Steps to Reproduce

1.- Pass any value to the --clear flag for get-last-cli-sync
2.- It should delete the ep_last_cli_index option

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Re thinking about this, I think we actually want the opposite of what was committed originally. In case of flags 

`[--pretty]`

We actually should not allow any values to be passed, instead of validating if a value that was passed is a boolean

`--pretty=true`

Unless we want to explicitly make the user set those.

@felipeelia thoughts?

**Comment by felipeelia** [comment]
I think we would want either `--pretty` or `--pretty=true` to work the same @oscarssanchez.

Expanding it a little bit (and admittedly thinking out loud a bit), if we consider a `--verbose` parameter, for example:
1. It could be a simple boolean, so `--verbose` and `--verbose=true` would work the same
2. In the future we could expand that to also accept `--verbose=<level>`
With that in mind, the only thing that really would deny `--verbose` is `--verbose=false`.

Makes sense?
