### ISSUE TITLE
Stop the Sync process if mapping failed

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#3204]
### Describe the bug

Currently, if the mapping fails due to an error, the sync process continues and ends with a success message.

This is not ideal, and we should halt the sync operation and display the error message as soon as mapping fails.

### Steps to Reproduce

1. Add this filter `add_filter( 'ep_config_mapping_request', '__return_false' );` to force the mapping failed
2. Try to sync from dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@JakePT we will need some final FEE work here, as although the PR makes it fail when the mapping failed, there is no visual feedback of that to the user.
