### ISSUE TITLE
While indexing content using WP CLI, only 4 documents were indexed.

### ISSUE THREAD

**Issue by mahesh-spinx** [10up/ElasticPress#3205]
### Describe your question

While indexing content using WP CLI, only 4 documents were indexed.
See this screenshot - https://prnt.sc/3CPTZjWjzQmO

We have many pages, custom post types,s and attachments. see this screenshot while we sync data from wp-admin user interface - https://prnt.sc/rinYrPR8yjV8 total of 9512 posts for sync.

Sync is working till 74% of using the browser but after that, it's having the issue of byte limit, after that we reduce the number of posts per index cycle but it will show Too many request errors.

How i can do it using WP CLI, any setting where I can change this setting and increase it?

Here is the status of Elasticpress, Let me know if any changes on this.

====== Status ======
{
  "spinxlocalprojectsamptpmemberwebsitewebwp-post-1" : {
    "shards" : [
      {
        "id" : 2,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1671001348170,
        "stop_time_in_millis" : 1671001348257,
        "total_time_in_millis" : 86,
        "source" : { },
        "target" : {
          "id" : "pOywYmBETPyUQzJp-qdAaA",
          "host" : "127.0.0.1",
          "transport_address" : "127.0.0.1:9300",
          "ip" : "127.0.0.1",
          "name" : "DEV09"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 42,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 33
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 1,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1671001348150,
        "stop_time_in_millis" : 1671001348238,
        "total_time_in_millis" : 86,
        "source" : { },
        "target" : {
          "id" : "pOywYmBETPyUQzJp-qdAaA",
          "host" : "127.0.0.1",
          "transport_address" : "127.0.0.1:9300",
          "ip" : "127.0.0.1",
          "name" : "DEV09"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 38,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 33
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 3,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1671001348162,
        "stop_time_in_millis" : 1671001348248,
        "total_time_in_millis" : 85,
        "source" : { },
        "target" : {
          "id" : "pOywYmBETPyUQzJp-qdAaA",
          "host" : "127.0.0.1",
          "transport_address" : "127.0.0.1:9300",
          "ip" : "127.0.0.1",
          "name" : "DEV09"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 45,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 32
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 4,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1671001348344,
        "stop_time_in_millis" : 1671001348409,
        "total_time_in_millis" : 64,
        "source" : { },
        "target" : {
          "id" : "pOywYmBETPyUQzJp-qdAaA",
          "host" : "127.0.0.1",
          "transport_address" : "127.0.0.1:9300",
          "ip" : "127.0.0.1",
          "name" : "DEV09"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          },
          "total_time_in_millis" : 30,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 26
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
        }
      },
      {
        "id" : 0,
        "type" : "EMPTY_STORE",
        "stage" : "DONE",
        "primary" : true,
        "start_time_in_millis" : 1671001348181,
        "stop_time_in_millis" : 1671001348285,
        "total_time_in_millis" : 104,
        "source" : { },
        "target" : {
          "id" : "pOywYmBETPyUQzJp-qdAaA",
          "host" : "127.0.0.1",
          "transport_address" : "127.0.0.1:9300",
          "ip" : "127.0.0.1",
          "name" : "DEV09"
        },
        "index" : {
          "size" : {
            "total_in_bytes" : 0,
            "reused_in_bytes" : 0,
            "recovered_in_bytes" : 0,
            "percent" : "0.0%"
          },
          "files" : {
            "total" : 0,
            "reused" : 0,
            "recovered" : 0,
            "percent" : "0.0%"
          "total_time_in_millis" : 42,
          "source_throttle_time_in_millis" : 0,
          "target_throttle_time_in_millis" : 0
        },
        "translog" : {
          "recovered" : 0,
          "total" : 0,
          "percent" : "100.0%",
          "total_on_start" : 0,
          "total_time_in_millis" : 43
        },
        "verify_index" : {
          "check_index_time_in_millis" : 0,
          "total_time_in_millis" : 0
      }
    ]
  }
}

====== End Status ======

Can you please help me with this issue? 

Thanks
Mahesh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Can you please share the error output @mahesh-spinx you are getting in CLI? you should use the flag --show-errors for this

**Comment by mahesh-spinx** [comment]
Thanks for your reply.

Yes, I am using WP CLI and I do troubleshoot the sync issue and found the solution. The issue was a conflict with the Advance access manager plugin I deactivated the plugin and after that sync is working using WP CLI. 

I have another issue during the sync process which is the timeout issue. see this screenshot - https://prnt.sc/iXy_lZ1gk2UY

Can you help me to how I can increase **"Index Document Request Timeout" & "Default Requests Timeout "** - https://prnt.sc/lM7vHE_9LL49
 
How I can increase the **bytes_limit** in elastic search?  we have some big pdf around 20 MB and it's having 300 pages. so during the indexing elastic press throws the error of memory limit let us know how we will resolve this issue. I send you a status report screenshot please check it and let us know your thoughts.  - https://drive.google.com/file/d/1gei2o5hSqcI9gOHf40bRw9-ememm07VF/view?usp=sharing

{
    "error": {
        "root_cause": [
            {
                "type": "circuit_breaking_exception",
                "reason": "[parent] Data too large, data for [<http_request>] would be [2026987504/1.8gb], which is larger than the limit of [1973865676/1.8gb], real usage: [2026987504/1.8gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=130232290/124.1mb, accounting=4065556/3.8mb]",
                "bytes_wanted": 2026987504,
                "bytes_limit": 1973865676,
                "durability": "TRANSIENT"
            }
        ],
        "type": "circuit_breaking_exception",
        "reason": "[parent] Data too large, data for [<http_request>] would be [2026987504/1.8gb], which is larger than the limit of [1973865676/1.8gb], real usage: [2026987504/1.8gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=130232290/124.1mb, accounting=4065556/3.8mb]",
        "bytes_wanted": 2026987504,
        "bytes_limit": 1973865676,
        "durability": "TRANSIENT"
    },
    "status": 429
}

-----------------------------------------------------------------

And one another question 
How I can index only failed documents and posts, without indexing the whole data? because while run **wp elasticpress sync** it will sync all the data.


Thanks
Mahesh

**Comment by felipeelia** [comment]
Hey @mahesh-spinx, here are some answers for you. If you have any follow-up questions, please open a new issue, okay? Thanks.

> How I can increase "Index Document Request Timeout" & "Default Requests Timeout"?

You can do that using the `ep_index_document_timeout` and `bulk_request_timeout` filters.

> How I can increase the bytes_limit in elastic search?

We do not provide support related to infrastructure or Elasticsearch configurations. I found this article that can be a good starting point though: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/fix-common-cluster-issues.html#circuit-breaker-errors

> How I can index only failed documents and posts, without indexing the whole data?

` wp elasticpress sync --include=1,2,3 --indexables=post --show-errors` will do that for you. You can also save them in the WordPress dashboard, which will trigger the sync for that specific content.
