### ISSUE TITLE
Renaming "Last Sync" 

### ISSUE THREAD

**Issue by tomioflagos** [10up/ElasticPress#3208]
### Is your enhancement related to a problem? Please describe.

The new Status Report page has a section and sub-section with the Last Sync title, this seems more of a UX issue

### Designs

![7b135471-fff2-491f-9134-7e6107ee159e](https://user-images.githubusercontent.com/120570968/207757516-c230b0fe-cb9c-4d95-9ea9-e135ca351a14.png)

### Describe alternatives you've considered

Other suggestions:
Section Title: Last Sync
Sub Section:  DD-MMM-YYYY Time

The sub-section can be expanded to see the details of the sync.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Decisions we need to make here:
1. Should it be titled with the start or end time?
2. Whatever we choose for 1, should it be repeated or not inside the collapsible?
