### ISSUE TITLE
BUG: Search in multisite for 'sites' => 'current'

### ISSUE THREAD

**Issue by anders-naslund** [10up/ElasticPress#3225]
### Describe the bug

After upgrading to Elasticpress 4.4.0 we are no longer able to search within the 'current' site,  all requests seams to be using the Main site URL

### Steps to Reproduce

If the search quests is using:
```
new WP_Query( array(
    's'     => 'search phrase',
    'sites' => 'current',
) );
```
It doesn't work !

But if it's changed to:
```
new WP_Query( array(
    's'     => 'search phrase',
    'sites' => get_current_blog_id(),
) );
```
It starts working correctly again

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Hi @anders-naslund ,

By what you said, it seems this would be a regression? If so, can you let us know which version was working correctly for you?

**Comment by anders-naslund** [comment]
4.3.1 was working fine,
looks like it might have to do with changes in [includes/classes/Indexable/Comment/QueryIntegration.php]

Changed to use 'sites__in' according to the release note but still 'current' is not working so if that's not going to work anymore you might need to update this article. 
https://elasticpress.zendesk.com/hc/en-us/articles/360052027951-How-can-I-search-across-multiple-sites-in-a-multi-site-
