### ISSUE TITLE
YITH WooCommerce Ajax Product Filter don't function when ElasticPress is active?

### ISSUE THREAD

**Issue by eastwood09** [10up/ElasticPress#3231]
### Describe your question

Hi there, 
I have a filter setup for my eCommerce site.
The filter works 100% fine when elasticPress is deactivated.
When I activate it again, whenever I click on something to filter, it just loads with no endpoint.

A good search directed me to a snippet of code that I can add to my theme's functions.php. This also hasn't worked.

https://elasticpress.zendesk.com/hc/en-us/articles/4409880508813-YITH-WooCommerce-Ajax-Product-Filter-Compatibility

Any help with this issue will be greatly appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MARQAS** [comment]
Hi @eastwood09,
It seems that the code given on the link will only work if widget is activated on the site, if you are not using widgets, can you try to disable ElasticPress on those filters using the below code?

```
function ep_prevent_using_ep_on_yith_wcan_unfiltered_args( $query_param ) {
	$query_param['ep_integrate'] = false;
	return $query_param;
}

add_filter( 'yith_wcan_filtered_products_query', 'ep_prevent_using_ep_on_yith_wcan_unfiltered_args' );
```

If the above code doesn't work, can you try disabling it via the filter given in ElasticPress plugin by checking if yith filter is selected? Something like this:
```
function ep_prevent_using_ep_on_yith_wcan( $ep_skip_query_integration, $query ) {

	if ( ! empty( $query->get( 'yith_wcan_query' ) ) ) {
		return true;
	}
	return $ep_skip_query_integration;
}
add_filter( 'ep_skip_query_integration', 'ep_prevent_using_ep_on_yith_wcan', 10, 2 );
```
