### ISSUE TITLE
Failed queries

### ISSUE THREAD

**Issue by altendorfme** [10up/ElasticPress#3236]
### Describe your question

Hello,

I'm getting alerts that queries fail, but when parsing the queries: [Imgur](https://imgur.com/kxWeGKx)
How to disable ElasticPress Notices?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @altendorfme, thanks for opening the issue. Would you mind sending a screenshot of the collapsible opened? I'd like to see why that was considered a failure. In the meantime, you can use the `ep_query_logger_should_log_query` filter to decide which queries should or should not be logged. Thanks!

**Comment by altendorfme** [comment]
> Hey @altendorfme, thanks for opening the issue. Would you mind sending a screenshot of the collapsible opened? I'd like to see why that was considered a failure. In the meantime, you can use the `ep_query_logger_should_log_query` filter to decide which queries should or should not be logged. Thanks!

![iKb1KnpPq2](https://user-images.githubusercontent.com/1530032/210400636-a6a57662-20d8-466f-ab43-d83de06b394d.png)

**Comment by felipeelia** [comment]
That is interesting @altendorfme, Elasticsearch is considering the search term too complex. If I'm not mistaken, the website at hand is in Brazilian Portuguese and doesn't have content in the language searched. I think you have a couple of possibilities here:

1. Block searches for non-latin search terms at a WP level, so EP won't ever be triggered by those.
2. Use the `ep_query_logger_should_log_query` filter to analyze the query body and simply ignore it if the reason type is `fuzzy_terms_exception`.
3. Disable query logging completely (`add_filter( 'ep_query_logger_should_log_query', '__return_false' );`). I would not recommend this approach, though.

As there isn't much we can do in this specific case I'm going ahead and closing the ticket but please share any additional information you may find and we can reopen it. Thanks.

**Comment by altendorfme** [comment]
@felipeelia Even disabling it completely: `add_filter( 'ep_query_logger_should_log_query', '__return_false' );`
I keep getting alerts/notices in Admin
