### ISSUE TITLE
Elasticpress Wordpress plugin not connecting to VPS server

### ISSUE THREAD

**Issue by blimbasha** [10up/ElasticPress#3238]
### Describe your question

Hi, 

**Backend**: 
I am using a VPS to run Elasticsearch. 

**Frontend:** 
The frontend/production of my site (Wordpress) is hosted on a Shared hosting. 

**What I wanted to do:** 
I want to the wordpress to remain where it is in the shared hosting, and connect to the Elasticsearch instance on the VPS. 

**What worked:** 
When I host a replica of the site within the VPS, it all works fine within Elasticpress plugin. The indexing goes smoothly, and searching works great as well. 

**What doesn't work (yet):** 
When I point to the VPS server within Elasticpress, it never succeeds to connect. 
My entry for the Elasticsearch url is as follows: http://"vps server ip":9200

So far I have updated the elasticsearch.yml file with network.host: 0.0.0.0.
But still doesn't seem to connect.

Appreciate your advice. Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @blimbasha, I'm sorry but that kind of information and advice is outside this repo's scope (we just provide support for the plugin, nothing related to infrastructure.) You can try opening a new topic in the Elastic forum (or search for existent ones like [this topic](https://discuss.elastic.co/t/how-to-access-elasticsearch-on-a-remote-machine/182264), for example.) Good luck!
