### ISSUE TITLE
Add filters for modifying Registered Indexables

### ISSUE THREAD

**Issue by nickchomey** [10up/ElasticPress#3239]
## Is your enhancement related to a problem? Please describe.

I would like to prevent Posts from being indexed while debugging things, but it doesn't seem to be possible because it is registered automatically in https://github.com/10up/ElasticPress/blob/develop/elasticpress.php#L102. This happens regardless of whether Post Search is disabled. 
![image](https://user-images.githubusercontent.com/88559987/210079586-c8f207ce-199e-4cd2-935b-ca533380c5f5.png)

I suppose this is all fine - surely 99.9% of sites want to index Posts. But, the real issue, it seems to me, is that there isn't any filter for modifying the Registered Indexables. There should be.

### Option 1: Add filters to the IndexHelper for the global and non_global indexables

https://github.com/10up/ElasticPress/blob/develop/includes/classes/IndexHelper.php#L134

Something like this:
```
$global_indexables     = apply_filters ('ep_global_indexables', $this->filter_indexables( Indexables::factory()->get_all( true, true ) ) );
$non_global_indexables = apply_filters ('ep_non_global_indexables', $this->filter_indexables( Indexables::factory()->get_all( false, true ) ) );
```

### Option 2: Use/implement/fix the `IndexHelper->filter_indexables()` function
[This function](https://github.com/10up/ElasticPress/blob/develop/includes/classes/IndexHelper.php#L254) appears like it is supposed to actually do what I'm looking for. There are two problems with it though:

1. The problem is that it looks for `$this->args['indexables']` which doesn't get passed in when a sync is generated from the WP admin dashboard. 

A full re-index is triggered here https://github.com/10up/ElasticPress/blob/develop/includes/classes/Screen/Sync.php#L93, but it doesn't pass an `indexables` arg to the `full_index()` function. 

2. If I manually add an `indexables` arg there, it still doesn't work because the `filter_indexables()` function seems to be buggy/broken.

```
IndexHelper::factory()->full_index(
	[
		'method'        => 'dashboard',
		'put_mapping'   => ! empty( $_REQUEST['put_mapping'] ),
		'output_method' => [ $this, 'index_output' ],
		'show_errors'   => true,
		'network_wide'  => 0,
		'indexables'	=> []
	]
);
```

The problem is the `empty( $this->args['indexables'] ) || ` part. If the args['indexables'] is empty, it just returns true and includes all indexables. If it isn't empty then the array is evaluated. 

I suppose this is reasonable enough - by default, pass an empty array and therefore include all indexables. But, if you don't want to include ANY indexables for whatever debugging purposes, there's no real way to do this (other than to just include a random "indexable" that won't get matched).

The solution seem to be to create a filter for passing an 'indexables' arg with some sort of comment to describe how it works
```
IndexHelper::factory()->full_index(
	[
		'method'        => 'dashboard',
		'put_mapping'   => ! empty( $_REQUEST['put_mapping'] ),
		'output_method' => [ $this, 'index_output' ],
		'show_errors'   => true,
		'network_wide'  => 0,
		'indexables'	=> apply_filters( 'ep_filter_indexables' , array() ),  //all registered Indexables will be indexed if left blank. To exclude all indexables, pass any value in the filter
	]
);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @nickchomey, we are already studying a redesign of the dashboard sync where the user could select which Indexables they want. You made me curious though: if you are not passing any indexable, what would you expect to happen if you trigger a sync?

**Comment by nickchomey** [comment]
Haha, I don't even remember now! Surely there was _some_ logic behind it though, however warped. Perhaps I had some edge-case debugging idea in mind? Maybe I was just trying to be thorough and ended up over-thinking this non-issue "edge-case" because I was too deep "in the weeds"?

I can't really think of any reason to not pass any indexables to an indexing action. 

Anyway, surely you'd agree that the filter I've proposed would be useful and easy to implement? In the event that someone does have a use for such a non-indexable indexing action, they can just pass `indexables = ['random string'];` with the filter.

**Comment by nickchomey** [comment]
Now that I think about this some more, I actually prefer Option 1 in my OP - just add a filter for each of the global and non-global indexables. Except it we should just get rid of the `$this->filter_indexables()` function altogether, 

This
```
$global_indexables     = apply_filters ('ep_global_indexables', $this->filter_indexables( Indexables::factory()->get_all( true, true ) ) );
$non_global_indexables = apply_filters ('ep_non_global_indexables', $this->filter_indexables( Indexables::factory()->get_all( false, true ) ) );
```

should become this:

```
$global_indexables     = apply_filters ('ep_global_indexables', Indexables::factory()->get_all( true, true ) );
$non_global_indexables = apply_filters ('ep_non_global_indexables', Indexables::factory()->get_all( false, true ) );
```

This is because it would just be a double/redundant filter. 

This would also solve my "problem" with wanting to pass 0 indexables, while also making it easier to actually filter the indexables than my suggested option 2, where you need to populate the default blank array (index all indexables) with the slugs of the indexables you want to exclude. Its very confusing. Better to just pass the array, manipulate it as desired (add/remove indexables) and return it. Seemingly every other EP filter works like this, so why not here as well?

**Comment by felipeelia** [comment]
Hey @nickchomey, I'm sorry but I'm having a hard time to understand the use case here.

I totally agree we need to give developers a way to change Indexables being sent during a sync via the dashboard (see #3195) but I honestly can't think what a sync without any Indexables should do: the whole point of a sync is exactly iterating over Indexables (potentially) deleting their index, recreating it, and sending the data.

Your issue gave me an idea though: we probably should have a filter to change all the args passed ([here](https://github.com/10up/ElasticPress/blob/4.4.1/includes/classes/IndexHelper.php#L72).) That would also allow changing which Indexables should be worked.

**Comment by nickchomey** [comment]
Perhaps I wasn't clear in my previous reply, but syncing with zero indexables is just a random, probably non-existent, edge-case. Please forget I ever mentioned it (though, again, it shouldn't have any effect on implementing the requested filter).

Again, the core of this Issue/Request/Suggestion is for adding filter(s) to allow us to change which Indexables are being synced. My initial desire for this was to remove the `Post` indexable, which, as of now, is always synced - even if you disable Post search. But the same filter could be used to filter other registered Indexables. 

But, your suggestion to put a filter for the `$args` on line 72 seems like a better solution than those that I proposed - rather than just allowing for modifying the Indexables, it would allow to modify all of the args. It would also work for full_index requests generated from the CLI (which [calls the same](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Command.php#L826) `IndexHelper::factory()->full_index()` function as the dashboard [Sync mechanism](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Screen/Sync.php#L93).

So, it would be great if you could add that filter in the next release!
