### ISSUE TITLE
QUESTION: Using Instant Results with facets to avoid page reload.

### ISSUE THREAD

**Issue by chermant** [10up/ElasticPress#3241]
### Describe your question

Hello here !

Is there a way to use Instant Results with facets to avoid page reload and get the speed of response like with search bar ? 

Regards.
Clément.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @chermant, I'm not entirely sure what you mean, but you can use Facets in Instant Results by selecting them from the Feature settings:

![Screenshot 2023-01-05 at 6 40 42 pm](https://user-images.githubusercontent.com/4100733/210727171-229697c5-de40-4e14-a713-2310575c86be.png)

These behave just like the Facet widgets, but inside the Instant Results modal and without a page reload.

If you're asking whether it's possible to use the regular Facet _widgets_ on your regular search page without a page reload, this isn't currently possible.
