### ISSUE TITLE
Restricting access to ElasticPress for non-administrator users

### ISSUE THREAD

**Issue by JonathanHolvey** [10up/ElasticPress#3252]
### Describe your question

I'm trying to lock down the ability of non-administrator users to access and change settings in the ElasticPress admin pages, such as:

- admin.php?page=elasticpress
- admin.php?page=elasticpress-settings
- admin.php?page=elasticpress-sync
- etc

I've found that users with the editor role have full access to these admin pages, and can change any of the ElasticPress plugin's settings contained within. What is the recommended way of restricting access to these pages to only certain roles?

The WordPress way of managing permissions is through capabilities, but I can't see any capabilities being exposed by the ElasticPress plugin.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @JonathanHolvey,

I am not able to reproduce that with a fresh installation of ElasticPress. Are you using a plugin to change capabilities and roles?

ElasticPress [uses the `manage_options`](https://github.com/10up/ElasticPress/blob/4.4.0/includes/dashboard.php#L666) to check if the user is allowed to access its pages or not. For network activated mode, it will check `manage_network`.

**Comment by JonathanHolvey** [comment]
Thanks for the feedback. It turned out that the `manage_options` capability had indeed been added to the role in question.
