### ISSUE TITLE
Can elasticpress search the contents from WP plugins such as wpForo？

### ISSUE THREAD

**Issue by leaffly** [10up/ElasticPress#3258]
### Describe your question

Dear，
I am interesting with this plugin because I want to implement search function that can search all of the contents of the WP.
When I install elasticpress, I found it cant search anything in wpForo contents.
It looks like no index sync to elasticsearch of the wpForo contents.
Could you help me？
Thanks very much.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @leaffly,

ElasticPress automatically integrates with all plugins that use the WordPress content API, i.e., all plugins that use WP_Query to get content from WordPress database tables. Unfortunately, it seems WpForo does not use WordPress's functionality but rather creates its own tables and searches them using direct SQL queries (see [here](https://plugins.trac.wordpress.org/browser/wpforo/tags/2.1.5/includes/install-sql.php) and [here](https://plugins.trac.wordpress.org/browser/wpforo/tags/2.1.5/classes/Forums.php#L126), for example.)

That said, although it would be possible to integrate that plugin with ElasticPress, that would require a large amount of custom code, at the point that the majority of the plugin would have to be rewritten.
