### ISSUE TITLE
Are you planning to officially support OpenSearch in a future release?

### ISSUE THREAD

**Issue by mmgc84** [10up/ElasticPress#3260]
### Describe your question

For the last few months I have been using OpenSearch and as of today I have been able to integrate
WordPress 6.1.1 + Php 8.0 + Woocommerce 7.2.2 + OpenSearch 1.3.7 + ElasticPress 4.4.

I can't say if all the features are working perfectly well, but so far I have not noticed errors.

Are you planning to officially support OpenSearch in a future release? 
Is there any way to turn off this warning: _Your server software is not supported. To learn more about server compatibility please [visit our documentation_ ? 

I remain attentive to your comments

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
That is great news, @mmgc84, thanks for sharing it. Regarding when we are going to officially support it and why that didn't happen already, please refer to [this comment](https://github.com/10up/ElasticPress/issues/2671#issuecomment-1078972274). We are still working on this.

Regarding the notice, you can dismiss it or use a snippet like `add_filter( 'pre_option_ep_hide_different_server_type_notice', '__return_true' );`.
