### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by ketmarket** [10up/ElasticPress#3262]
### Describe the bug

After ticking a category and unticking it, the search window closes unintenionally

Technical observations:
**Backendquery**: https://ketmarket.eu/wp-content/plugins/elasticpress-proxy/proxy.php throws 400 error
**Error spotted**:
_Correct request_: https://ketmarket.eu/wp-content/plugins/elasticpress-proxy/proxy.php?highlight=em&offset=0&orderby=relevance&order=desc&per_page=6&search=test+2&relation=and&tax-at_biz_dir-category=59
_Correct request_: [https://ketmarket.eu/wp-content/plugins/elasticpress-proxy/proxy.php?highlight=em&offset=0&orderby=relevance&order=desc&per_page=6&search=test+2&relation=and](https://ketmarket.eu/wp-content/plugins/elasticpress-proxy/proxy.php?highlight=em&offset=0&orderby=relevance&order=desc&per_page=6&search=test+2&relation=and&tax-at_biz_dir-category=59)
_Incorrect request (which has no value for last GET param)_: https://ketmarket.eu/wp-content/plugins/elasticpress-proxy/proxy.php?highlight=em&offset=0&orderby=relevance&order=desc&per_page=6&search=test+2&relation=and&tax-at_biz_dir-category=

### Steps to Reproduce

1. Go to https://ketmarket.eu/
2. Search "news" in the header menu bar and press enter
3. Tick "Reports" in category filter
4. Untick "Reports" in category filter
(see screen recording: https://ketmarket.eu/wp-content/uploads/2023/01/elacticpress-bug.mov)

### Screenshots, screen recording, code snippet

![error-log-browser](https://user-images.githubusercontent.com/122673166/212469842-3c318def-5006-460a-9ca8-6860844c698f.png)

### Environment information

Browser: Google Chrome 108.0.5359.124 (arm64)

### WordPress and ElasticPress information

**WordPress Version** 6.1.1
**Elasticsearch Version** 8.5.3 (self hosted)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @ketmarket,

The PHP Proxy we provide through https://github.com/10up/elasticpress-proxy serves only as a starting point and we do not offer support for it (you are responsible for changing that proxy to fit your needs and security.)

That said, the problem you are describing was fixed in [this PR](https://github.com/10up/elasticpress-proxy/pull/5), so make sure your version of that plugin is updated with that code.
