### ISSUE TITLE
How can I confirm if the search function is using elasticPress？

### ISSUE THREAD

**Issue by leaffly** [10up/ElasticPress#3263]
### Describe your question

Hi，
I configured the elasticPress and sync completed.
`Starting sync…
Indexing posts…
Processed posts 0 - 33 of 33. Last Object ID: 1
Number of posts indexed: 33
Indexing users (globally)…
Processed users 0 - 6 of 6. Last Object ID: 1
Number of users indexed: 6
Sync complete`
But I cant search the post which is already sync to ES via my search function in home page.
So, I am not sure if my search function uses the this plugin.
could you give me a hand, please?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leaffly** [comment]
I checked the guide "When enabled, ElasticPress Autosuggest will automatically add itself to any input[type="search"] elments on the page, as well as any elements with the .ep-autosuggest or .search-field classes.", so I dont change anything of source code.

**Comment by leaffly** [comment]
I install debug bar elasticpress, it displays "No queries to show" after I search something via search function in the homepage.

**Comment by RetroGameTalk** [comment]
I personally can tell it's working because i use Query Monitor plugin and i can see in it an "HTTP API call (1)"
And i also can see that WP_Query->get_posts() Main Query disappeared from the top of the list when sorted by time.
I hope it helps, somehow. not an expert.

PS: This is how i integrate it. Set 'ep_integrate' to true.
http://10up.github.io/ElasticPress/tutorial-indexables.html

**Comment by leaffly** [comment]
> I personally can tell it's working because i use Query Monitor plugin and i can see in it an "HTTP API call (1)" And i also can see that WP_Query->get_posts() Main Query disappeared from the top of the list when sorted by time. I hope it helps, somehow. not an expert.
> 
> PS: This is how i integrate it. Set 'ep_integrate' to true. http://10up.github.io/ElasticPress/tutorial-indexables.html

Thanks for you sharing, I will check it again.

**Comment by felipeelia** [comment]
Hi all. The Debug Bar ElasticPress adds a new panel in Debug Bar and/or Query Monitor, so that would be the easiest way to check if a query was sent to ES or not.

@leaffly, just to be sure we are talking about the same thing, autosuggest is the typeahead functionality we have and is not responsible for the site search. Can you please share with us the URL of your search page and the contents of your ElasticPress Status Report? Thanks.

**Comment by leaffly** [comment]
> Hi all. The Debug Bar ElasticPress adds a new panel in Debug Bar and/or Query Monitor, so that would be the easiest way to check if a query was sent to ES or not.
> 
> @leaffly, just to be sure we are talking about the same thing, autosuggest is the typeahead functionality we have and is not responsible for the site search. Can you please share with us the URL of your search page and the contents of your ElasticPress Status Report? Thanks.

follow is my ElasticPress Status report

<details><summary>ElasticPress Status report</summary>
## WordPress ##

### WordPress Environment ###
wp_version: 6.0
home_url: https://domain.com
site_url: https://domain.com
is_multisite: false
theme: Personal CV Resume (1.0.4)
plugins: Akismet Anti-Spam (4.2.4), Atomic Blocks - Gutenberg Blocks Collection (2.9.0), Awesome Support (6.1.2), Classic Editor (1.6.2), CM Answers (3.1.6), Display Posts (3.0.2), ElasticPress (4.4.1), Hello Dolly (1.7.2), Hide My WP Ghost Lite (5.0.17), Login or Logout Menu Item (1.2.2), MangBoard WP (1.7.4), OneLogin SAML SSO (3.4.0), One User Avatar (2.3.9), Open External Links in a New Window (1.43), Posts By Shortcode (1.2), Really Simple SSL (5.3.5), Sticky Header (1.2.2), SyntaxHighlighter Evolved (3.6.2), The Paste (1.1.0), wpForo (2.0.9), WP Mail SMTP (3.5.1), and WP Statistics (13.2.5)
revisions: all

### Server Environment ###
php_version: 7.4.32
memory_limit: 40M
timeout: 30



## Indexable Content ##

### SAIT SW Portal — https://domain.com ###
post_count: 3
page_count: 12
ticket_count: 4
cma_thread_count: 5
attachment_count: 8
ticket_reply_count: 1
ticket_history_count: 1
ticket_log_count: 0
post_meta_keys: 0
page_meta_keys: 1
ticket_meta_keys: 2
cma_thread_meta_keys: 0
attachment_meta_keys: 0
ticket_reply_meta_keys: 0
ticket_history_meta_keys: 0
ticket_log_meta_keys: 0
total-all-post-types: 3
distinct-meta-keys: ep_exclude_from_search, auto_delete_attachments, and auto_delete_attachments_type



## ElasticPress ##

### Settings ###
host: http://localhost:9200
index_prefix: 
language: en_US
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30



## Failed Queries ##



## Elasticsearch Indices ##

### swpsaitsamsungdsnet-post-1 ###
health: yellow
status: open
index: swpsaitsamsungdsnet-post-1
uuid: iN93mjn3SySZpPStuwVXtQ
pri: 5
rep: 1
docs.count: 34
docs.deleted: 0
store.size: 253.6kb
pri.store.size: 253.6kb
total_fields_limit: 5000

### swpsaitsamsungdsnet-user ###
health: yellow
status: open
index: swpsaitsamsungdsnet-user
uuid: 2fcubwLlR3OsslDLcar1lQ
pri: 5
rep: 1
docs.count: 9
docs.deleted: 0
store.size: 316.9kb
pri.store.size: 316.9kb
total_fields_limit: 5000



## Last Sync ##

### 2023/01/31 9:28:39 am ###
method: WP Dashboard
end_date_time: 2023/01/31 9:29:06 am
total_time: 0 hours, 0 minutes, 28 seconds
total: 43
synced: 43
skipped: 0
failed: 0
errors: array (
)



## Feature Settings ##

### Autosuggest ###
active: true
autosuggest_selector: .ep-autosuggest
endpoint_url: 
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Protected Content ###
active: true
force_inactive: false

### Related Posts ###
active: true
force_inactive: false

### Users ###
active: true
force_inactive: false

</details>

**Comment by felipeelia** [comment]
Autosuggest will only work when you add an Endpoint URL. As you are self-hosting Elasticsearch, you will need to take extra care with security, as that URL needs to be public facing. See more in [this article](https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups) and other (closed) issues in this repo, like [this one](https://github.com/10up/ElasticPress/issues/2513).
