### ISSUE TITLE
Security privilege issue -  [security_exception] action [indices:admin/auto_create] is unauthorized for user [d************y] with roles [d************y] on indices [d************y-post-1], this action is granted by the index privileges [auto_configure,create_index,manage,all]

### ISSUE THREAD

**Issue by daryltavernor** [10up/ElasticPress#3268]
### Describe your question

Hi there

Are we are having issues with the self hosted version. We are getting the following error when we try to do a full reset via both cli and through the interface:

[security_exception] action [indices:admin/auto_create] is unauthorized for user [d************y] with roles [d************y] on indices [d************y-post-1], this action is granted by the index privileges [auto_configure,create_index,manage,all]

We have tried doing a full Sync, a reset, and adding a prefix via cli, however, still getting the same issues.

We are also getting the following error in the query log:

Query Response Code: HTTP 403

We are authenticating the user via wp-config which seems to connect ok but we just can't get it to index.

Any help would be greatly appreciated

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @daryltavernor,

It seems the user is not able to create an index. If you still get that error while calling `wp elasticpress put-mapping` it is a misconfiguration in your Elasticsearch server. I found a similar problem [here](https://discuss.elastic.co/t/action-indices-admin-create-is-unauthorized-for-user/303458) where the indices field should be `*`, and you can try that as well.

As we do not provide support for infrastructure-related problems, I'm going to close the issue now.
