### ISSUE TITLE
log4j - Upgrade Elasticsearch to 7.16?

### ISSUE THREAD

**Issue by Retro64XYZ** [10up/ElasticPress#3269]
### Describe your question

Hello,

The README states that this project requires elasticsearch no higher than 7.10. Is it possible to get to 7.16 so we can eliminate all Log4J issues? I am currently running Elasticsearch inside a Docker container but Snyk is still reporting Log4J issues at 7.10.

Any tips or recommendations?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @Retro64XYZ,

We do have plans to update that number but unfortunately, we are not ready to do that yet. From what we've tested and heard from other developers the plugin works fine with any 7.x version, so you are welcome to give it a try and let us know the results. There is more in [this comment here](https://github.com/10up/ElasticPress/issues/2671#issuecomment-1078972274) (although a bit old, the comment is still true.)

If everything works fine you can either dismiss the notice or add this line of code to remove the notice completely:

```php
add_filter( 'pre_option_ep_hide_es_above_compat_notice', '__return_true' );
```
