### ISSUE TITLE
Exclude field from mapping

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3270]
### Describe your question

Hello.
I have a lot of users and too much junk in the index. Example: manageedit-pagecolumnshidden, wp_user-settings, wp_user_level, wp_yoast_notifications et al. 
Used a filter: `ep_prepare_user_meta_excluded_public_keys`
It only excludes meta fields. And I have 200+ of them. Two questions.
1. There is a filter "only allowed fields"
2. If the field is not meta, for example user_email, how can it be excluded from indexing?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @ws256,

You can use the [ep_prepare_user_meta_data](http://10up.github.io/ElasticPress/ep_prepare_user_meta_data.html) filter to manipulate all meta fields. In [this article](https://elasticpress.zendesk.com/hc/en-us/articles/360052019111-How-to-exclude-metadata-from-indexing) you will find an example of how to do that with posts. It is just a matter of adapting that to users and the metadata you want.

To exclude a field from the mapping you will need to do a few things:
1. Remove the field from the mapping sent to Elasticsearch using the `ep_user_mapping` filter
2. Use the `ep_user_sync_args` filter to remove the field from the user before ElasticPress sends it to Elasticsearch
3. Do a full sync (Delete all Data and Start a Fresh Sync), so the old index is deleted and a new one (with the new mapping) is created.
