### ISSUE TITLE
How can I increase the results count for Instant Results?

### ISSUE THREAD

**Issue by PHdeOliveira** [10up/ElasticPress#3274]
### Describe your question

Sorry for the novice question, but how can I increase the Instant Results count? Currently, the default is 6 per page. I'd like this to be much higher.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @PHdeOliveira, we actually don't have a great way to do that right now, but we'll look at adding something in a future version.
