### ISSUE TITLE
Local development using ElasticPress with Local by Flywheel

### ISSUE THREAD

**Issue by PHdeOliveira** [10up/ElasticPress#3276]
### Describe your question

Is there a way to use ElasticPress for Local development that's not done through Docker? I use[ Local by Flywheel](https://localwp.com/) to develop locally.

Any documentation or insight?

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @PHdeOliveira, we actually don't have a great way to do that right now, but we'll look at adding something in a future version.

**Comment by felipeelia** [comment]
Hey @PHdeOliveira, unfortunately, we don't have any good answers for the moment that doesn't involve docker. Ultimately, it seems installing Elasticsearch directly on the host machine is the best solution for now. As infrastructure is not really in the scope of this repo I'm going ahead and closing the issue but I'll keep a close eye on any news about it. If we find any good solution we'll also make sure to update [our docs about development](https://10up.github.io/ElasticPress/tutorial-development.html). Thanks!

**Comment by nickchomey** [comment]
@PHdeOliveira Give [Devilbox](http://devilbox.org/) a try. Running it in Ubuntu on WSL2 finally solved my Windows-based local development problems, in every regard. The v3 beta releases make it even easier to use.
