### ISSUE TITLE
Query posts by thumbnail not available because it's a protected meta key

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/ElasticPress#328]
The EP_API::prepare_meta method removes meta keys which are protected. That unfortunately leaves out the ability to still query by posts that have thumbnails (a common occurrence).

Original:

```php
	/**
	 * Prepare post meta to send to ES
	 *
	 * @param object $post
	 *
	 * @since 0.1.0
	 * @return array
	 */
	public function prepare_meta( $post ) {
		$meta = (array) get_post_meta( $post->ID );

		if ( empty( $meta ) ) {
			return array();
		}

		$prepared_meta = array();

		foreach ( $meta as $key => $value ) {
			if ( ! is_protected_meta( $key ) ) {
				$prepared_meta[$key] = maybe_unserialize( $value );
			}
		}

		return $prepared_meta;
	}
```

With filter and _thumbnail_id added would be something like this (with inline hook doc):

```php
	/**
	 * Prepare post meta to send to ES
	 *
	 * @param object $post
	 *
	 * @since 0.1.0
	 * @return array
	 */
	public function prepare_meta( $post ) {
		$meta = (array) get_post_meta( $post->ID );

		if ( empty( $meta ) ) {
			return array();
		}

		$prepared_meta = array();

		$allowed_protected_keys = apply_filters( 'ep_prepare_meta_allowed_protected_keys', array( '_thumbnail_id' ), $post );

		foreach ( $meta as $key => $value ) {
			if ( ! is_protected_meta( $key ) || in_array( $key, $allowed_protected_keys ) ) {
				$prepared_meta[$key] = maybe_unserialize( $value );
			}
		}

		return $prepared_meta;
	}
```

**Comment by FreshFlesh** [comment]
Because this is very specific and someone could argue that some other protected metas should also be indexed by default, may be it is better to set this meta as unprotected using is_protected_meta filter?

```php
add_filter( 'is_protected_meta', 'my_index_thumbnail_meta', 10, 3 );

function my_index_thumbnail_meta( $protected, $meta_key, $meta_type ) {
    if ( $meta_key == '_thumbnail_id' ) {
        $protected = false;
    }
    return $protected;
}
```

**Comment by sc0ttkclark** [comment]
I wouldn't want to change how WordPress it works itself here -- is_protected_meta would do that.

The filter I've proposed in ep_prepare_meta_allowed_protected_keys would allow anyone to allow indexing of other protected meta keys in a much more clear way for EP itself and devs using it.

**Comment by FreshFlesh** [comment]
I understand that someone might want to index a meta while keeping it protected in WP itself, so having a dedicated filter for EP only might be the solution!

I am still unsure about having `array( '_thumbnail_id' )` as the default value though..

Did i miss something or your code is missing a condition on `$allowed_protected_keys`?

**Comment by sc0ttkclark** [comment]
Sorry, updated my code with `if ( ! is_protected_meta( $key ) || in_array( $key, $allowed_protected_keys ) ) {` as I originally intended it to have.

**Comment by tlovett1** [comment]
I think adding a filter to allow specific keys is a great idea. Not a huge fan of having a non-empty default though.

**Comment by sc0ttkclark** [comment]
Is EP indexing the featured thumbnail or whether it has a thumbnail already? If not, I feel like the non-empty default makes sense in this case -- since the thumbnail (and maybe even page template, but that's a big stretch) is a common meta_query for most of the sites I've worked on (at 10up and in recent years)

**Comment by tlovett1** [comment]
@sc0ttkclark since the post meta key `_thumbnail_id` is private, it is not indexed by default. I could probably be convinced that it should be.

**Comment by sc0ttkclark** [comment]
If you could probably be convinced that it should be, we should whitelist it :)
