### ISSUE TITLE
Unable to sync ElasticPress results in Worpress

### ISSUE THREAD

**Issue by ciprian-pap** [10up/ElasticPress#3280]
### Describe your question

Hi there,
We are having a problem regarding the ElasticPress Wordpress plugin Sync feature. 

We have this warning: Some ElasticPress queries failed in the last 24 hours. Please visit the [Status Report page] for more details.

We tried running the Sync manually from ElasticPress>Sync>Sync Now. The sync process is starting but, after a while, it stops and returns this error: Something went wrong. Find troubleshooting steps at https://elasticpress.zendesk.com/hc/en-us/sections/360010868652-Troubleshooting.

Our server admin team found out in the error log this>

<details><summary>Error Log</summary>
Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /home/domain_name/public_html/wp-includes/formatting.php:3425\nStack trace:\n#0 /home/domain_name/public_html/wp-includes/class-wp-hook.php(308): convert_smilies('&lt;h2><img decodi...')\n#1 /home/domain_name/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('&lt;h2><img decodi...', Array)\n#2 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/Indexable/Post/Post.php(503): apply_filters('the_content', '<h2><img src=\"i...')\n#3 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/Indexable.php(372): ElasticPress\Indexable\Post\Post->prepare_document(75914)\n#4 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/IndexHelper.php(645): ElasticPress\Indexable->bulk_index_dynamically(Array)\n#5 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/IndexHelper.php(428): ElasticPress\IndexHelper->index_next_batch()\n#6 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/IndexHelper.php(323): ElasticPress\IndexHelper->index_objects()\n#7 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/IndexHelper.php(79): ElasticPress\IndexHelper->process_sync_item()\n#8 /home/domain_name/public_html/wp-content/plugins/elasticpress/includes/classes/Screen/Sync.php(99): ElasticPress\IndexHelper->full_index(Array)\n#9 /home/domain_name/public_html/wp-includes/class-wp-hook.php(308): ElasticPress\Screen\Sync->action_wp_ajax_ep_index('')\n#10 /home/domain_name/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)\n#11 /home/domain_name/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#12 /home/domain_name/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_ep_inde...')\n#13 {main}\n thrown
</details>

They told us this is an error message indicating that a function called "Count()" is being passed an argument of the wrong type.

Can you help us with some additional checks or fixes?

Regards,
Ciprian

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @kortex123,

That count() call is made by WordPress itself, in its `convert_smilies()` function. Here is the link to the call: https://github.com/WordPress/WordPress/blob/6.1.1/wp-includes/formatting.php#L3425

It seems the function is called while ElasticPress is processing your content to send it to Elasticsearch. During that process, EP will call `apply_filters( 'the_content', $post->post_content )` and as `convert_smilies` is a function hooked to that filter, it is called.

You have a couple of options:
- Investigate why that call is failing. You have a post whose content starts with `<h2><img...`. You can check if that is displayed correctly or not and go from there.
- Disable smilies in Settings > Writing
- Programmatically remove that function from the the_content filter with something like `remove_filter( 'the_content', 'convert_smilies', 20 );`

If you can get back to us with the full content of that post so we can try to reproduce the problem, that would be great. Thanks

**Comment by ciprian-pap** [comment]
Hi @felipeelia!
Thanks a lot for you help. I did checked the articles and, indeed, we have a lot of old articles, migrated from Joomla that have `<h2><img...`

On Joomla we had a relative URL to article images, not the full URL. The first article image, was wrapped in a H2 tag like this: `<h2><img src="images/stories/2016/03/27/image_name.jpg"/>` for example.

There are tens of thousands of articles in this situation and, unfortunely, on migration we lost the folder with images. Could this be the problem? 

The Sync feature worked fine until we got our of space on server and the free space went under 8%. Our server administration team told us at that point that the problem was this: https://stackoverflow.com/questions/50609417/elasticsearch-error-cluster-block-exception-forbidden-12-index-read-only-all. 

We got rid of unused files and now we have a lot of space, but the Sync feature doesn't work again. 

Regarding the other points: 

- Disable smilies in Settings > Writing - I didn't found this option in Wordpress 6.1.1
- Programmatically remove that function from the the_content filter with something like remove_filter( 'the_content', 'convert_smilies', 20 ); - Could you tell me how to do this?
- If you can get back to us with the full content of that post so we can try to reproduce the problem, that would be great - Is it ok for you to paste here the content or I must give you an article link?

Regards,
Ciprian

**Comment by felipeelia** [comment]
Hey @kortex123, thanks for the info!

To programmatically remove that function from the the_content filter, all you'd have to do is add this line to your theme's functions.php file:

```php
remove_filter( 'the_content', 'convert_smilies', 20 );
```

You could also use a [plugin like this one](https://wordpress.org/plugins/insert-php-code-snippet/). Add it in any of those ways and run a sync again, things should work.

And regarding how to share it, you can share the link or copy its HTML contents in pastebin.com and share the link, whatever works better for you.

**Comment by ciprian-pap** [comment]
Hi, @felipeelia!
Thank you very much for the fix. I added the line in the theme's functions.php file, started a fresh sync and this time worked.

Many thanks!
