### ISSUE TITLE
Plugin Conflict with WP ROCKET

### ISSUE THREAD

**Issue by PHdeOliveira** [10up/ElasticPress#3285]
### Describe your question

Looks like some css break when using WP Rocket together with ElasticPress. I've tried excluding all of the /dist/css/(.*).css styles, but it still breaks the site.

Has anyone successfully used both of these plugins together?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @PHdeOliveira, do you mind sharing more details on exactly what breaks and in which file? If you have a public website where we can see it happening it would be even better. Thanks.

**Comment by stevesearer** [comment]
@PHdeOliveira I can confirm that we successfully use ElasticPress and WP Rocket plugins together
