### ISSUE TITLE
Term counts not showing in facet widget

### ISSUE THREAD

**Issue by clemorphy** [10up/ElasticPress#3286]
Hi

Term counts are not showing in my facet widget. Is it normal?
I saw this from 2019 https://github.com/10up/ElasticPress/pull/1195
Is this feature only available in the develop branch and not in the stable release?

**Comment by felipeelia** [comment]
Hey @clemorphy,

That PR was closed and never merged, so that is not available even in develop. You can use the following snippet to display term counts while we don't have that added back in the plugin:

```php
add_filter(
	'ep_facet_widget_term_label',
	function ( $label, $term ) {
		return "{$label} ({$term->count})";
	},
	10,
	2
);
```

**Comment by clemorphy** [comment]
Thanks @felipeelia 
That's exactly what I needed.

**Comment by anjulahettige** [comment]
We'll be adding a new option for this.
