### ISSUE TITLE
How to measure the performance of the ElasticPress plugin?

### ISSUE THREAD

**Issue by mmgc84** [10up/ElasticPress#3297]
### Describe your question

Hey team :wave: 
I'm using WordPress 6.1.1 + Php 8.0 + Woocommerce 7.2.2 + OpenSearch 1.3.7 + ElasticPress 4.4 and I would like to know how can I measure the performance of the site with the plugin enabled against the performance of the site with the plugin disabled.

Is there a good way to measure the performance of the ElasticPress plugin? I don't have enough data in my database, so I'm looking for a way to fill up a table with dummy data and see how much EP can help with the queries. Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @mmgc84, the easiest way would be to install a plugin like Query Monitor and compare results. You could also use an APM  software (Application Performance Monitoring). The latter would give you some historical data after a while but it obviously harder to set up than a simple plugin.
