### ISSUE TITLE
Filter for hideAutosuggestBox()

### ISSUE THREAD

**Issue by mindaugasbudreika** [10up/ElasticPress#3298]
### Is your enhancement related to a problem? Please describe.

Currently there is no easy way to modify the autosuggest dropdown closing/hiding behaviour other than patching the minified plugin files. 

### Designs

**Option 1:**
Introduction of 2 filters for lists and containers inside hideAutosuggestBox() function.

Before
```
const lists = document.querySelectorAll('.autosuggest-list');
const containers = document.querySelectorAll('.ep-autosuggest');
```

After:
```
const lists = applyFilters('ep.Autosuggest.XXXX', document.querySelectorAll('.autosuggest-list'));
const containers = applyFilters('ep.Autosuggest.YYYY', document.querySelectorAll('.ep-autosuggest'));
```

**Option 2:**

Creating single filter for basic interception:
```
function hideAutosuggestBox() {
    if (applyFilters('ep.Autosuggest.hideAutosuggestBox', false)) {
        return true;
    } 
    ...
```

I'm open for any solution as long as I could intercept autosuggest dropdown hide attempt and would have opportunity to stop it. 

### Describe alternatives you've considered

- Use patched ElasticPress version. Hard to update, need to keep a copy around when needed instead of downloading one from wordpress.org.
- Dequeueing autosuggest JS and serving copy from theme/custom plugin. Impractical, would be hard to maintain compatibility with multiple/newer EP versions.
- Setting up filter on window.epasAPI. Same issue as with option above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @mch0lic, those sound like good additions to the plugin. Could you please expand a little more on what you are trying to accomplish with that? Also, PRs are welcome! Thanks

**Comment by mindaugasbudreika** [comment]
@felipeelia The ultimate goal in my case to improve the dropdown behaviour on mobile. Currently there is more than enough filters to create really awesome autosuggest dropdowns but its hard to work around the mobile usability issues without ability to control circumstances under which the dropdown should be closed.

I've decided to patch the JS and use option 2 in the mean time. I'm happy to create a PR for ether of these options as long as we can agree on best option.

**Comment by JakePT** [comment]
@mch0lic Are you able to elaborate ob the mobile usability issues you're experiencing. If there are issues we'd like to resolve them in the plugin without requiring the use of the filter. Also if you could give an example of how you would use option 1 to solve your issue that would be great.
