### ISSUE TITLE
Show taxonomy archive pages in search results

### ISSUE THREAD

**Issue by towercity** [10up/ElasticPress#3299]
### Describe your question

Is it possible to include taxonomy archive pages in ElasticPress search results? For our site, for example, we'd like to use the search results re-ordering to make certain taxonomy term archives appear as the top result when you search for term.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @towercity, currently it is not possible to add taxonomy archive pages as search results in ElasticPress. We have #2676 to keep it registered as a possible enhancement but unfortunately, that is not planned for our near future. Thanks!
