### ISSUE TITLE
Prevent "Exclude from search results" section from being added

### ISSUE THREAD

**Issue by clemorphy** [10up/ElasticPress#3311]
### Describe your question

Hi

I don't want my users to be able to exclude content from search, so I don't need the "exclude from search results" section on the add / edit pages.

How can I prevent this section from being added?

Removing this action may work (with `remove_action`), but I'm not sure how to do it since it's in a class : 
`add_action( 'post_submitbox_misc_actions', [ $this, 'output_exclude_from_search_setting' ] );`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @clemorphy,

The instance of that class is accessible by calling `\ElasticPress\Features::factory()->get_registered_feature( 'search' );`. The code below will hide the box on both classic and block editors:

```php
add_action(
	'init',
	function() {
		$search = \ElasticPress\Features::factory()->get_registered_feature( 'search' );
		remove_action( 'enqueue_block_editor_assets', [ $search, 'enqueue_block_editor_assets' ] );
		remove_action( 'post_submitbox_misc_actions', [ $search, 'output_exclude_from_search_setting' ] );
	},
	99
);
```

**Comment by clemorphy** [comment]
Hello @felipeelia 

Once again thank you. I didn't know how to get access to the instance of the class.
Thanx for the code snippet, exactly what I needed.

❤👏

**Comment by stevesearer** [comment]
@felipeelia Thanks for this snippet!

We added the following as Fatal Errors were occurring in some cases when utilizing REST API:

```
if (!class_exists('\ElasticPress\Features')) {
     return;
}
```
