### ISSUE TITLE
Hide Custom Post Type From Main Search Results

### ISSUE THREAD

**Issue by digidoda** [10up/ElasticPress#3315]
### Describe your question

I have a site I'm working on where we would like one custom post type to not appear in the main search results, but still be searchable from the specific post type category archive page search box.

Is this something that can be done?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @digidoda,

That will depend on how that specific post type category archive page search box is built but generally, that could be done either by using the `ep_searchable_post_types` filter or tweaking the WP_Query via the `pre_get_posts` and changing the post_type value.

For the EP filter you could use something like this (obviously just a starting point):
```php
add_filter(
	'ep_searchable_post_types',
	function ( $types ) {
		global $wp_query;

		if ( $wp_query->is_search() ) {
			unset( $types['post'] );
		}

		return $types;
	}
);
```
