### ISSUE TITLE
Make ElasticPress queries failed notices dismissible 

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#3322]
### Is your enhancement related to a problem? Please describe.

As of now, these notices are not dismissible, they can become disturbing to users if they for example, are aware of them and actively working them, but want to get rid of them in the meantime for the editorial team etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anjulahettige** [comment]
We should dismiss the notice and bring it back when a new error is logged. (once a new error is logged, the dismiss option should be deleted)

Disable the notice for non-admins.
