### ISSUE TITLE
BUG: Blocks that use postId context crash indexing

### ISSUE THREAD

**Issue by tomjn** [10up/ElasticPress#3325]
### Describe the bug

1. I have a dynamic block that requires the `postId` context to render post specific content.
2. This context is only provided if the global `$post` object is set. This is fine because my block is only available in posts, and is inside a post.
3. ElasticPress does not set the current post so `$post` is undefined
4. ElasticPress uses `the_content` filter to retrieve my posts content
5. WP tries to render the block and the callback tries to use `postId` expecting an integer
6. the block renderer recieves a `null` and the application crashes

### Steps to Reproduce

Attempt to index a site that uses the `postId` in a block renderer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomjn** [comment]
Noting that adding `global $post` to the top of the post document preparer allowed indexing to complete:

```php
	public function prepare_document( $post_id ) {
		global $post;
```

**Comment by felipeelia** [comment]
Good catch @tomjn. Do you mind opening a Pull Request with that change? Thanks

**Comment by tomjn** [comment]
note that while this does improve things, I'm not 100% sure it solves the problem. My initial attempt also involved trying to set the current post the same way `the_post` does which did nothing
