### ISSUE TITLE
meta_value_* orderby core parameters are missing from Elasticpress

### ISSUE THREAD

**Issue by tomjn** [10up/ElasticPress#3326]
### Describe the bug

> ‘meta_value‘ – Note that a ‘meta_key=keyname‘ must also be present in the query. Note also that the sorting will be alphabetical which is fine for strings (i.e. words), but can be unexpected for numbers (e.g. 1, 3, 34, 4, 56, 6, etc, rather than 1, 3, 4, 6, 34, 56 as you might naturally expect). Use ‘meta_value_num‘ instead for numeric values. You may also specify ‘meta_type‘ if you want to cast the meta value as a specific type. Possible values are ‘NUMERIC’, ‘BINARY’, ‘CHAR’, ‘DATE’, ‘DATETIME’, ‘DECIMAL’, ‘SIGNED’, ‘TIME’, ‘UNSIGNED’, same as in ‘$meta_query‘. When using ‘meta_type’ you can also use ‘meta_value_*’ accordingly. For example, when using DATETIME as ‘meta_type’ you can use ‘meta_value_datetime’ to define order structure.

These parameters are missing, only `meta_value_num` and `meta_value` have been implemented.

### Steps to Reproduce

Set the `orderby` value to `meta_value_date` or one of the other orderby meta type values

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Thanks for opening the issue @tomjn. Although we try to keep EP as compatible as possible with all WordPress functionalities, there is a few things that we are still working on. If you want, a Pull Request adding this would be more than welcome.
