### ISSUE TITLE
BUG: composer.json is missing in the zipped up release builds

### ISSUE THREAD

**Issue by tomjn** [10up/ElasticPress#3332]
### Describe the bug

If you include this plugin via composer it will download it as a generic library and is unaware it's a WP plugin.

The installed version no longer contains a `composer.json`

### Steps to Reproduce

Require `10up/elasticpress` with a stable released version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @tomjn, do you mind expanding a bit on what you are trying to achieve? If I run `composer require
10up/elasticpress`, it will add a new `"10up/elasticpress": "^4.4"` line to my composer.json file with the following section in composer.lock:

```json
{
    "name": "10up/elasticpress",
    "version": "4.4.1",
    "source": {
        "type": "git",
        "url": "https://github.com/10up/ElasticPress.git",
        "reference": "4e9a33ae12a229dd33a6edebd03d6f4936c12e04"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/10up/ElasticPress/zipball/4e9a33ae12a229dd33a6edebd03d6f4936c12e04",
        "reference": "4e9a33ae12a229dd33a6edebd03d6f4936c12e04",
        "shasum": ""
    },
    "require": {
        "php": ">=7.0"
    },
    "require-dev": {
        "10up/phpcs-composer": "dev-master",
        "phpcompatibility/phpcompatibility-wp": "*",
        "phpunit/phpunit": "^9.5",
        "wpackagist-plugin/woocommerce": "*",
        "yoast/phpunit-polyfills": "^1.0"
    },
    "type": "wordpress-plugin",
    "extra": {
        "installer-paths": {
            "vendor/{$name}/": [
                "type:wordpress-plugin",
                "type:wordpress-theme"
            ]
        }
    },
    "notification-url": "https://packagist.org/downloads/",
    "license": [
        "GPL-2.0-only"
    ],
    "authors": [
        {
            "name": "Taylor Lovett",
            "email": "taylorl@get10up.com"
        },
        {
            "name": "10up",
            "homepage": "https://10up.com"
        },
        {
            "name": "Aaron Holbrook",
            "email": "aaron@10up.com",
            "homepage": "https://aaronjholbrook.com"
        }
    ],
    "description": "Supercharge WordPress with Elasticsearch.",
    "keywords": [
        "elasticpress",
        "elasticsearch",
        "plugin",
        "search",
        "wordpress"
    ],
    "support": {
        "issues": "https://github.com/10up/ElasticPress/issues",
        "source": "https://github.com/10up/ElasticPress/tree/4.4.1"
    },
    "time": "2023-01-10T18:03:59+00:00"
},
```

As you can see, the type there is right (`wordpress-plugin`.) Adding plugins distributed by wpackagist will also point to zip files.

**Comment by tomjn** [comment]
The project I'm on moves certain packages into a `plugins-mu` subfolder based on package name and type, however when I upgraded to v4 the package was only present in the main `vendor` folder, and had no `composer.json`. I had specified `^4.4.1` as the package requirement.

Switching to WP Packagists version sidestepped the problem

**Comment by tomjn** [comment]
If you download the zip file on the 4.4.1 release from the releases page you'll see it has no `composer.json` file:

<img width="289" alt="Screenshot 2023-02-21 at 21 13 41" src="https://user-images.githubusercontent.com/58855/220460020-0951b88f-cdf1-4451-b67b-72f96fe3d045.png">

**Comment by felipeelia** [comment]
The final package downloaded by composer does not need a composer.json file (plugin versions distributed by WP Packagist won't have it either.)

It is worth mentioning that Composer does not understand `type:wordpress-plugin` by default, it is needed to require the [`composer/installers`](https://github.com/composer/installers) package to have that working. If you have any plugin being fetched by WP Packagist, that package is automatically required.

With all that said, I did a test myself using the following section in a composer.json that contains both the 10up/elasticpress package and a WPackagist plugin and things worked as expected:
```json
	"extra": {
		"installer-paths": {
			"../../plugins/{$name}/": [
				"type:wordpress-plugin"
			],
			"../../mu-plugins/{$name}/": [
				"type:wordpress-muplugin"
			],
			"../../themes/{$name}/": [
				"type:wordpress-theme"
			]
		}
	},
```

**Comment by tomjn** [comment]
true but wpackagist has all that information in a composer repository via I assume Satis, I'm not so sure Github is generous enough to do the same with releases

The way we have it set up here was like this:

```json
        "installer-paths": {
            "content/plugins-mu/vendor/{$name}/": [
                .......
                "10up/elasticpress",
```

The reasons it's there are historical

**Comment by felipeelia** [comment]
@tomjn do you mind sending the entire composer.json file? Also, are you requiring the `installer-paths` package? That is needed if you want to use "installer-paths".
