### ISSUE TITLE
Allow querying taxonomies by more than just slug

### ISSUE THREAD

**Issue by cmmarslender** [10up/ElasticPress#335]
Currently, this is restricted to use only the "slug" field - Sometimes, we might know IDs or Names, and want to search by those

https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L747

**Comment by bordoni** [comment]
We could include some, Parent related search in this enhancement, or is it too much?

**Comment by cmmarslender** [comment]
My specific case was trying to include results from a list of a few taxonomy ids, but I would think the long term goal here should be to mirror as much of the tax query support for WP_Query as we can ¯\_(ツ)_/¯

**Comment by mustafauysal** [comment]
:+1:

**Comment by sc0ttkclark** [comment]
PR submitted
