### ISSUE TITLE
Facet not working on category page.

### ISSUE THREAD

**Issue by JMWa36** [10up/ElasticPress#3360]
### Describe your question

I have installed ElasticPress on my website and would like to utilize its facet feature. While it works fine on search results, I'm having difficulty getting it to work properly on category pages that contain multiple products. Specifically, when I select a color facet, such as navy, it redirects me to the homepage and adds "?ep_filter_pa_colour=navy" to the end of the URL.

For example, if I'm on the category page for long-sleeve products:

https://example.com/?product_cat=long-sleeve

and then select the navy color facet, I'm redirected to:

https://example.com/?ep_filter_pa_colour=navy

Is there a way to make ElasticPress facets work on category pages, or are they only designed to work on search result pages?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @JMWa36,

I'm able to reproduce the problem but it seems to affect only sites not using "pretty" permalinks. While we work on fixing it, you can have it working with the following snippet:

```php
add_filter(
	'ep_facet_allowed_query_args',
	function ( $args ) {
		$args[] = 'product_cat';
		return $args;
	}
);
```

Thanks!
