### ISSUE TITLE
BUG: ep_user_formatted_args_query 400 Bad Request

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3366]
### Describe the bug

Hello everyone, I wanted to change the order of user output. And remove the limit on the number of 10000 (in the WP console)

```
<?php
add_filter( 'ep_user_formatted_args_query', 'ep_user_formatted_args_query', 25, 3 );

function ep_user_formatted_args_query ( $formatted_args, $query_vars, $query ) {
//	$formatted_args['track_total_hits'] = true;
	$query_vars['orderby'] = 'user_email';
    return $query_vars;
}
?>
```

But it doesn't work. The debugger shows 400 Bad Request.

### Steps to Reproduce

1. Enable the filter in the plugin or template functions.
2. Go to the admin section users /wp-admin/users.php  and perform a search

### WordPress and ElasticPress information

WordPress Version 6.1.1
PHP Version 8.0.21
ElasticPress 4.4.1
Elasticsearch Version 7.10.2 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@ws256 The `ep_user_formatted_args_query` filter is used to change the Elasticsearch query. In that, you'll want to change the `sort` property, not `orderby`. That said, the best way to achieve what you want is to change the WP_User_Query using the `pre_get_users` action.
