### ISSUE TITLE
BUG: delete a post

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3367]
### Describe the bug

Hi, everybody!

If you delete a post from the general list on the page /wp-admin/edit.php it will not disappear until you refresh the page.

The entry should disappear from the list immediately after deletion. If you turn off the Elastic Press plugin, everything works as expected.

### Steps to Reproduce

1. go to /wp-admin/edit.php
2. delite post 
3. refresh page

### Environment information

FF 110

### WordPress and ElasticPress information

WordPress Version 6.1.1
PHP Version 8.0.21
ElasticPress 4.4.1
Elasticsearch Version 7.10.2 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @ws256, this problem is already being tracked in https://github.com/10up/ElasticPress/issues/1415. There you'll find a temporary solution for it. Thanks!
