### ISSUE TITLE
How to filter posts by category and certain ACF fields for Related Posts query

### ISSUE THREAD

**Issue by yanodnoralov** [10up/ElasticPress#3371]
### Describe your question

Hello, I'm using this function to render related posts within my theme.
`\ElasticPress\Features::factory()->get_registered_feature('related_posts')->find_related($post_id, $return = 5);`

Looking at my ES query, I need to adjust a few things. I need to only include posts that 

- are in a particular category
- particular post type
- and have the same value set in one of their ACF fields

<img width="1139" alt="Screen Shot 2023-03-04 at 9 55 27 PM" src="https://user-images.githubusercontent.com/7436604/222942508-e8832f26-0326-4c73-8384-37800bf4e5e9.png">

How do I go about modifying this? Is there a PHP filter? I used `elastic_search_related_fields` for modifying the 'more like this' fields successfully. Is there a similar filter I can use for post filtering? I can't seem to find it in the documentation. 

This is specifically for the "related posts" feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @yanodnoralov,

You can tweak the WP_Query executed by that function using the [ep_find_related_args](https://10up.github.io/ElasticPress/ep_find_related_args.html) filter.
