### ISSUE TITLE
BUG: Showing incorrect data, WooCommerce orders

### ISSUE THREAD

**Issue by codafweb** [10up/ElasticPress#3381]
### Describe the bug

We have a quite large WooCommerce site with 130.000+ orders.
Lately we have experienced ElasticPress showing incorrect data.
1. 'Completed' orders are showing in 'Processing' tab, in the query result they are returned as 'Processing' by ElasticPress.
2. A ton of 'Processing' orders are missing from 'Processing' tab.
Might happen with other statuses as well, we just noticed it with 'Processing'.

Both issues are instantly fixed when disabling ElasticPress.

I have tried to:
1. Delete all data and run a fresh full sync multiple times, but this does not fix the issue. It will return different results afterwards, but still cases of before mentioned issues, and shortly after they start piling up again.
2. Check status reports from the syncs. They all show 100% 'Synced', 0 in 'Skipped', 'Failed' or 'Error'.
3. Checked with Debug Bar, in the query result 'Completed' orders are indeed being returned as 'Processing' in the query from ElasticPress.

**Native WordPress:**
![native_wordpress](https://user-images.githubusercontent.com/57766861/223759159-8abb3410-415a-44f8-b8a0-d6d5739da758.jpg)
Shows correct data.

**ElasticSearch WordPress**
![elasticpress_wordpress](https://user-images.githubusercontent.com/57766861/223759232-f6785358-9cf2-465c-a7cd-25e665e423d2.jpg)
Missing orders and showing 'Completed' orders.

### Steps to Reproduce

Unknown

### Environment information

ElasticPress: Version 4.4.1
WordPress: Version 6.0.3
WooCommerce: Version 7.3.0 

Web server | LiteSpeed
PHP SAPI | litespeed

Extension | mysqli
Server version | 8.0.30-22
Client version | mysqlnd 8.0.26

### WordPress Environment ###
wp_version: 6.0.3
is_multisite: false
theme: Twenty Twenty-One (1.7)
revisions: all

### Server Environment ###
php_version: 8.0.26
memory_limit: 40M
timeout: 600

### XXX.XXX — https://XXX.XXX ###
post_count: 65
page_count: 27
product_count: 11,345
ht_faq_count: 535
ct_template_count: 7
shipping_condition_count: 1
payment_condition_count: 2
attachment_count: 38,190
scheduled-action_count: 0
product_variation_count: 63
shop_order_count: 130,123
shop_order_refund_count: 4,109
shop_coupon_count: 124
shop_order_placehold_count: 0
pys_event_count: 0
wpcf7_contact_form_count: 3
wcpf_project_count: 1
wcpf_item_count: 5
itsec-dashboard_count: 1
itsec-dash-card_count: 8
wcs_ruleset_count: 3
post_meta_keys: 5
page_meta_keys: 49
product_meta_keys: 63
ht_faq_meta_keys: 0
ct_template_meta_keys: 40
shipping_condition_meta_keys: 4
payment_condition_meta_keys: 3
attachment_meta_keys: 3
scheduled-action_meta_keys: 0
product_variation_meta_keys: 30
shop_order_meta_keys: 122
shop_order_refund_meta_keys: 4
shop_coupon_meta_keys: 19
shop_order_placehold_meta_keys: 0
pys_event_meta_keys: 0
wpcf7_contact_form_meta_keys: 0
wcpf_project_meta_keys: 2
wcpf_item_meta_keys: 2
itsec-dashboard_meta_keys: 2
itsec-dash-card_meta_keys: 2
wcs_ruleset_meta_keys: 2
total-all-post-types: 259
distinct-meta-keys: _thumbnail_id, enclosure, id, b2bking_product_customrows_group_115775, b2bking_product_customrows_group_b2c, qode_page_background_image_fixed, qode_show-page-title, qode_show-sidebar, _wpb_vc_js_status, qode_page_background_color, qode_margin_after_title, ct_other_template, ct_template_archive_post_types_all, ct_template_categories, ct_template_categories_all, ct_template_tags, ct_template_tags_all, ct_template_custom_taxonomies, ct_template_custom_taxonomies_all, ct_template_authors_archives_all, ct_template_index, ct_template_front_page, ct_template_blog_posts, ct_template_date_archive, ct_template_search_page, ct_template_inner_content, ct_template_404_page, ct_template_all_archives, ct_template_archive_among_taxonomies, ct_template_apply_if_archive_among_taxonomies, ct_template_archive_post_types, ct_template_apply_if_archive_among_cpt, ct_template_authors_archives, ct_template_apply_if_archive_among_authors, ct_template_single_all, ct_template_post_types, ct_template_exclude_ids, ct_template_include_ids, ct_template_taxonomies, ct_use_template_taxonomies, ct_template_post_of_parents, ct_template_apply_if_post_of_parents, ct_template_order, ct_builder_shortcodes, ct_builder_json, oxygen_lock_post_edit_mode, ct_builder_shortcodes_revisions, ct_builder_shortcodes_revisions_dates, ct_page_settings, qns_page_header_image_url, _backorders, _crosssell_ids, _default_attributes, _downloadable, _height, _length, _manage_stock, _price, _product_image_gallery, _product_version, _purchase_note, _regular_price, _sale_price, _sale_price_dates_from, _sale_price_dates_to, _sku, _sold_individually, _stock, _stock_status, _tax_class, _tax_status, _upsell_ids, _virtual, _wc_average_rating, _weight, _width, b2bking_category_users_textarea, b2bking_group_0, b2bking_group_115775, b2bking_group_b2c, b2bking_product_pricetiers_group_115775, b2bking_product_pricetiers_group_b2c, b2bking_product_visibility_override, b2bking_regular_product_price_group_115775, b2bking_sale_product_price_group_115775, b2bking_show_information_table, b2bking_show_pricing_table, b2bking_user_, total_sales, wc_productdata_options, wcgs_row_id, wpfoof-exclude-product, wpfoof-identifier_exists, ep_exclude_from_search, fb_product_group_id, fb_product_item_id, fb_visibility, inline_featured_image, _product_attributes, vtprd_wholesale_visibility, floor_area_calc_enabled, selected_images_categories, fb_product_description, fpmp_pro_area, fpmp_pro_vol, Lagerplacering, qty_per_meter, thp_upsellpopup_template, _visibility, ct_preview_url, ct_parent_template, excluded_shipping_methods, shipping_condition_rules, excluded_payment_gateways, payment_condition_rules, wp-smpro-smush-data, wp-smush-lossy, litespeed-optimize-size, attribute_gift-card-amount, attribute_pa_farve, attribute_pa_maal, attribute_pa_stoerrelse, _billing_address_1, _billing_address_2, _billing_city, _billing_company, _billing_country, _billing_email, _billing_first_name, _billing_last_name, _billing_phone, _billing_postcode, _billing_state, _customer_user, _order_key, _shipping_address_1, _shipping_address_2, _shipping_city, _shipping_country, _shipping_first_name, _shipping_last_name, _shipping_postcode, _shipping_state, GLS Private, full_captured_amount, full_refunded_amount, Pakkeshop, pys_enrich_data_analytics, is_vat_exempt, intent_id, session_id, ss_shipping_order_agent_no, ss_shipping_order_parcels, PENSOPAY_PAYMENT_CANCELLED, PENSOPAY_PAYMENT_ID, PENSOPAY_PAYMENT_LINK, TRANSACTION_ORDER_ID, mailchimp_woocommerce_is_subscribed, mailchimp_woocommerce_campaign_id, mailchimp_woocommerce_landing_site, wcal_abandoned_cart_id, carrier, package_number, tracking_url, Udleveringssted, dibs_customer_card, dibs_payment_method, dibs_payment_type, subscriptions, failed_attemps, is_a_renew, next_payment_attempt, b2bking_custom_field_115830, QUICKPAY_PAYMENT_ID, QUICKPAY_PAYMENT_LINK, shipmondo_pickup_point, pys_enrich_data, anyday_payment_last_status, anyday_payment_transaction, anyday_payment_transactions, ean_punit_number, ean_reference_person, ean_requisition_number, EAN-number, eanapi_formatted_response, eanapi_punit_formatted_response, viabill_status, 7ff3ea09-2520-4dfa-bc93-e57d2a49060f_anyday_captured_payment, 8509ac03-bafa-4680-81d8-77080a375ad0_anyday_refunded_payment, 784d3ea3-af0b-479c-9c9a-509a2be2b06b_anyday_refunded_payment, b851a149-eb9d-426e-acd7-1b4c50537a14_anyday_captured_payment, pys_fb_cookie, viabill_captured_amount, e015104a-3a00-426f-a96d-1a542b2d3520_anyday_captured_payment, df637aa4-96e6-4890-9544-20d24b328563_anyday_captured_payment, 4a9e99e7-53ae-4618-bf85-1da3c4bb2917_anyday_captured_payment, 7c5f4e37-06f0-4a63-90ba-89b79eb8ead9_anyday_captured_payment, 4803278c-d2d2-4cfe-8455-f1a96b7600bb_anyday_captured_payment, 844f1e9a-2f0a-4163-8028-6527a5d2b731_anyday_captured_payment, 0b03ec97-e3e5-4425-b2f2-b56176e1f8bd_anyday_captured_payment, df76f7ad-a1fb-4302-9333-7b724f82dafc_anyday_captured_payment, a0dc5189-98fe-4b9a-be1a-c258ce659bf0_anyday_captured_payment, 27ce4525-03f0-4dbe-a24e-618043cce55e_anyday_captured_payment, de602ac7-5afc-44a5-8dc1-6118789582c4_anyday_captured_payment, 3664dc66-9ceb-46e4-bfc3-d955cfa6cf7f_anyday_captured_payment, 024fbc25-59f1-472f-a4d1-ca08236e74c9_anyday_captured_payment, 3ac0854b-a21e-41e1-8bff-e8a4aaeb1436_anyday_refunded_payment, 7abf0203-8d0b-4fe9-822a-32ebff1b6e20_anyday_captured_payment, 8f03c4f8-ba1e-4ed9-b08d-023525257544_anyday_captured_payment, 1be03a28-6acc-4e0f-9e75-ab51529e1aac_anyday_captured_payment, 84546127-b17f-4550-994b-3a0202bea455_anyday_captured_payment, cbebcc62-5092-441e-bd39-aa5fdf43e7f3_anyday_captured_payment, c463b755-6c98-4b3a-8ca4-d67380f9ab73_anyday_captured_payment, 1b23384f-9af2-4c15-a0ac-6fbecd82720f_anyday_captured_payment, 08fec84c-8f83-4783-87f7-603bc43e2d1a_anyday_captured_payment, 12beac58-6446-4e5c-b5d1-3bfdceb7f902_anyday_captured_payment, 3afa938f-1213-4cc8-b43c-b227a686ffaf_anyday_captured_payment, 5496d92b-d415-47ae-8c50-9519e52ed9a0_anyday_captured_payment, b4d85d9e-a36d-4179-a7e4-20bac3e3777c_anyday_captured_payment, 87ea0f29-bb78-4b3e-a253-8fb09a3d63ae_anyday_captured_payment, 1304a1a7-ff0c-445a-8f32-d684597af1ea_anyday_captured_payment, 7d5b7a66-e5f3-48e3-8609-eae69882e3e1_anyday_captured_payment, f736030e-426b-4380-b920-6073217ce12a_anyday_captured_payment, 018b966c-edc8-4f93-8751-dec8c9e296db_anyday_captured_payment, bc3caf6f-2614-49fb-b2ff-1b4e5f17a146_anyday_captured_payment, 19290bf4-bb31-4090-be8e-c5492a0844ed_anyday_captured_payment, af3ccf9c-879f-4045-9979-1edab52b90e0_anyday_captured_payment, 33b8d8cc-80dd-4e44-ae15-611d5a1e98e5_anyday_captured_payment, b4d61c20-91d9-4bdc-a593-6d2f16e98ea9_anyday_captured_payment, 8df312ee-0038-4893-99fd-7350d9a1ea11_anyday_captured_payment, f6a83965-f7b3-4ebd-aac5-addf58c188ed_anyday_captured_payment, 0539f0c0-c655-4ff9-ab77-50b5d744010a_anyday_captured_payment, 12f864df-fee5-4c53-9254-3bb765bd22de_anyday_captured_payment, d9fa8b77-267f-4661-b100-873c332068df_anyday_captured_payment, 4497652c-7fb9-4d0b-84db-01acf0d0d6c1_anyday_captured_payment, dcf99d89-5f74-45db-b43b-f947225a8540_anyday_captured_payment, d02c074c-f034-4cfb-a28c-35b2e2de2467_anyday_captured_payment, 6c4827e9-b65c-42c0-a457-f202c08d41c0_anyday_captured_payment, 8fa37f98-fa07-4c3d-bb6d-c4bfe1d1ec87_anyday_captured_payment, 17611615-c469-46f2-82b1-100e00dcce0e_anyday_captured_payment, 3624ea8d-1a7e-49cc-becd-5a7601850977_anyday_captured_payment, discount_type, coupon_amount, individual_use, usage_limit, usage_limit_per_user, limit_usage_to_x_items, usage_count, date_expires, free_shipping, exclude_sale_items, minimum_amount, ywsbs_limited_for_payments, b2bking_customer_user_role, product_categories, product_ids, maximum_amount, wcpf_entity_options, and wcpf_entity_key

### Settings ###
host: http://localhost:9200
index_prefix: 
language: da_DK
per_page: 1000
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### XXX-post-1 ###
health: yellow
status: open
index: XXX-post-1
uuid: eUHOVhbARUmeVXYnsUxd4w
pri: 5
rep: 1
docs.count: 105949
docs.deleted: 33521
store.size: 647.2mb
pri.store.size: 647.2mb
total_fields_limit: 5000

### 2023/03/05 7:19:42 pm ###
method: WP Dashboard
end_date_time: 2023/03/05 8:09:15 pm
total_time: 0 hours, 49 minutes, 33 seconds
total: 105745
synced: 106745
skipped: 0
failed: 0
errors: array (
)

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Protected Content ###
active: true
force_inactive: false

### WooCommerce ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@codafweb, orders are synced in Elasticsearch as soon as they change status. The problem you are seeing could happen in some scenarios like:

- Some code is bypassing hooks executing after the order status changes: You'd need to check your plugins and any custom code you may have. For this, I recommend you create a staging env, disable all your plugins, and test the order status sync enabling one by one.
- Some code is failing after the order is saving the order in the database. Giving a look at your error logs may happen to identify the issue.

Can you please go through those 2 steps and let us know your findings? Thanks
