### ISSUE TITLE
Refine ElasticPress blocks

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#3384]
ElasticPress currently features 5 blocks:

- Related Posts (ElasticPress)
- Search Comments (ElasticPress)
- Facet by Taxonomy (ElasticPress)
- Facet by Meta (ElasticPress)
- Facet by Meta Range - Beta (ElasticPress)

I think there's a number of things we can do to improve the quality of these blocks:

- [x] **Recategorize blocks.**
Move the blocks into an "ElasticPress" block category.
- [x] **Update block names.**
Remove "(ElasticPress)" from the block name. Consider updating the terminology of the Facet blocks. It's not really correct to say "Facet by", instead "Filter by Taxonomy Facet" would be more correct.
- [x] **Update controls for consistency with core.**
Update "ASC/DESC" radio buttons for sorting with a dropdown with friendlier options like "Newest to oldest".
- [x] **Support customisation.**
Add support for non-experimental [block features](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/):
  - [x] Alignment.
  - [x] Background, text, and link colors.
  - [x] Sticky.
  - [x] Spacing.
  - [x] Font size and line height.
- [x] **Consolidate the Facet blocks.**
Currently there is a bunch of duplicated information and functionality between these blocks which could be reduced by implementing them as variations of a single block.
- [x] **Add new icons.**
Currently the Related Posts block has no icon, so it uses the generic lego block, the search comments block has a generic search icon whose style is inconsistent with core search blocks, and the facet blocks all use the same icon that doesn't represent the difference between the list and range blocks. Unique icons with a consistent style would make the blocks appear more professional.
- [ ] **Support inner blocks.**
Add inner block support to the Facet blocks so that headings etc. can be added that will be automatically hidden when the facet is not available.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Added `needs discussion` so we can assess if it is something we can have for EP 4.6.

**Comment by JakePT** [comment]
@felipeelia This includes renaming the facet blocks to "Filter by". Should we be renaming the Facets feature also?

Also, I’ve noticed we’ve added a Post Type facet block while this was in progress, but the post type facet is based on the old facet block implementation, so it isn’t up to the standards of the updated blocks. Should we hold off merging until we can do a pass on the post type facet, or should I create a new issue for that to be done?

**Comment by oscarssanchez** [comment]
@JakePT  I've applied the changes and opened a PR to merge into feature/3384 https://github.com/10up/ElasticPress/pull/3553 can you review please?
