### ISSUE TITLE
Making aggregations for multivalue ACF fields

### ISSUE THREAD

**Issue by selim13** [10up/ElasticPress#3387]
### Describe your question

Hello!

I'm trying to use Elasticpress to make aggregations over ACF fields, to count their values usage for all the posts,
but having a problem with [multivalue select](https://www.advancedcustomfields.com/resources/select/) ones as they are being indexed with their raw serialized value. For example, the multivalue color selection field:
```json
{
  "post_title" : "Flower",
  "meta" : {
    "color" : [
      {
        "date" : "1970-01-01",
        "datetime" : "1970-01-01 00:00:01",
        "boolean" : false,
        "raw" : "a:2:{i:0;s:5:\"peach\";i:1;s:5:\"white\";}",
        "time" : "00:00:01",
        "value" : "a:2:{i:0;s:5:\"peach\";i:1;s:5:\"white\";}"
      }
    ]
  }
}
```
What I'm trying to archive, is to build a list of colors like this:
* White: 10
* Peach: 5
* Red: 1

I suppose for that I will need to have such the field to be indexed as a keyword array, but don't know how to do that.
Can you give me an advice for my problem?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @selim13! Yes, you'll need a new field. You will need to add that field to the mapping (see [here for an example of how we do it](https://github.com/10up/ElasticPress/blob/4.5.0/includes/classes/Indexable/Post/Post.php#L2781)), then use the `ep_post_sync_args_post_prepare_meta` filter to add the value of that field to each document. That would be enough to make it available so you can aggregate it. Thanks!
