### ISSUE TITLE
Complex query with multiple Post Types don't seem to be resulting with proper weighting and relevance

### ISSUE THREAD

**Issue by ghost** [10up/ElasticPress#3391]
### Describe your question

Hello guys.
I'm trying to make this work for some weeks now. I apologize if there's something similar already opened, but I didn't find it.

Okay, I have a real complex search page with a lot of filters and I am making an AJAX request to the backend, that provides me the what I want.

Recently I added new post types to this query and it isn't resulting as expected. Here's the query (after mounted):

```
'ep_integrate'   => true,
'paged'          => 1,
'post_type'      =>
	[
		'page',
		'collection',
		'collection_highlight',
		'event',
		'exhibition',
		'person',
		'press_release',
		'teacher_resource',
	],
'posts_per_page' => 12,
'orderby'        =>
	[
		'relevance',
		'meta.hasImage.boolean'           => 'DESC',
		'meta.exhibition_start_date.date' => 'DESC',
		'meta.event_start_date.date'      => 'ASC',
		'meta.press_release_date.date'    => 'DESC',
	],
'search_fields'  =>
	[
		'post_title',
		'post_content',
		'post_excerpt',
		'meta' =>
			[
				'exhibition_short_description',
				'event_short_description',
				'collectionArtists',
				'collectionTerms',
				'dated',
				'displayName',
				'forwardDisplay',
				'histAttributions',
				'objectMedium',
				'objectNumber',
			],
	],
's'              => '\'maps\''
```

The weighting is configured inside WordPress with `ep_weighting_fields_for_post_type`, but what is happening is that: The weight for the `Page Title` for `Page` post type is the heavier possible (100), in comparison to 20, or 30, for the other post types... In this example, I'm searching for 'Maps', which is the title of a page, and it's coming almost on page 15!

The search is bringing me Collections first, even if the content isn't relevant at all.

Is there anything I need to do? Because it seems like Elastic Press can't measure the relevance between different Post Types.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @arctouch-fernandogarcia,

ElasticPress won't use the weighting configured in the dashboard if you pass `'search_fields'`. See [here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Weighting.php#L576). Do you mind trying to remove that and then using something like `add_filter( 'ep_enable_do_weighting', '__return_true' );` just before making the query call, so EP knows that query will use the weighting dashboard settings?

**Comment by ghost** [comment]
Hey @felipeelia 

I added, but nothing changed...

```
add_filter('ep_enable_do_weighting', '__return_true');

$searchResults = new WP_Query($searchQueryArgs);
```

**Comment by felipeelia** [comment]
Did you remove 'search_fields'? Also, under certain circumstances, you might need to add `add_filter( 'ep_admin_wp_query_integration', '__return_true' );` there as well. BTW, are you sure that query is being integrated with EP? if so, do you mind sharing the resultant Elasticsearch query?

**Comment by ghost** [comment]
No way... Man, all this time I was thinking that if you don't pass the 'search_field' arg, then EP will not look into the correct fields. Because it was happening at first, but I didn't realize that after properly configuring this within admin I have to remove... So after removing that, the results are all coming properly weighted. 

I guess if the fields are all checked to be searched inside Admin's Weighting config, then the search will work good, right? 

Aarg, sorry for the dumb question.

It's all good now.
Thank you so much!
