### ISSUE TITLE
Very slow queries in page overview page when using many meta fields

### ISSUE THREAD

**Issue by simonbinder** [10up/ElasticPress#3392]
### Describe your question

Hello,
we use ElasticPress in a Multisite environment with a lot of subsites.

After setting up ElasticPress, we noticed that for one subsite the posts overview page took significantly longer to load, in specific the ElasticSearch query took around 1.5 seconds. We were able to reduce this time to around 0.1 seconds by following [this guide](https://elasticpress.zendesk.com/hc/en-us/articles/360052019111-How-to-exclude-metadata-from-indexing). 

Currently we have above 80 ACF fields in use on the site. For the moment we are fine with excluding the fields as we don't need to query by ACF fields, but we might need to do it in the future.

Now to my question: While I can see that this the number of fields is quite a lot, I wouldn't have expected such a difference in performance when removing the meta fields from the indexing. Shouldn't the ElasticSearch indexing improve the speed of such queries more significantly? Or is this the expected behavior when the number of meta fields is large? 

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @simonbinder! When you say "posts overview page" do you mean the front-end list of posts or the list in the admin dashboard? Also, how are you measuring the ES query time? Lastly, do you mind sharing the contents of your Status Report? Thanks!

**Comment by simonbinder** [comment]
Hi @felipeelia, I was referring to the posts page in the admin dashboard. To measure the time, I was looking at the time the API Call to _search was taking according to the Query Monitor plugin. 

Here is also the status report. Unfortunately I had to remove some information (like all the other subsites) and other information that I am not allowed to share. Also the indices part is missing as the ES user we are using is lacking the permissions for the _cat/indices API that can't be granted due to they way our Elasticsearch cluster are set up. I hope you can still gather all information that is interesting for you.

## WordPress ##

### WordPress Environment ###
wp_version: 6.0.3

### Server Environment ###
php_version: 7.4.33
memory_limit: 64M
timeout: 300


## Indexable Content ##


### this ist the concerned subsite ###
post_count: 927
page_count: 10
attachment_count: 295
scheduled-action_count: 0
acf-field-group_count: 13
acf-field_count: 83
post_meta_keys: 0
page_meta_keys: 0
attachment_meta_keys: 0
scheduled-action_meta_keys: 0
acf-field-group_meta_keys: 0
acf-field_meta_keys: 0
total-all-post-types: 0
distinct-meta-keys: 


## ElasticPress ##

### Settings ###
language: en_US
per_page: 50
network_active: true

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30



## Failed Queries ##



## Last Sync ##

### 2023/03/15 11:18:37 am ###
method: WP Dashboard
end_date_time: 2023/03/15 11:30:41 am
total_time: 0 hours, 12 minutes, 4 seconds
total: 23946
synced: 23946
skipped: 0
failed: 0
errors: array (
)

## Feature Settings ##

### Protected Content ###
active: true
force_inactive: false

### Terms ###
active: true
force_inactive: false

**Comment by felipeelia** [comment]
Thanks @simonbinder. Can you please install the [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugin (it is compatible with Query Monitor too), go to that admin page, and share the requests info with us?

The number of fields indexed should interfere with that page speed, so you might have a different problem popping up there.
