### ISSUE TITLE
Autosuggest not working with cloud.elastic.io and version 8.6.2

### ISSUE THREAD

**Issue by ghost** [10up/ElasticPress#3396]
We are running ElasticPress version 4.5.10 with Elastic Cloud (8.6.2) and the searches are working but autosuggest is not working.  We have tried forcing the version to 7.10 in wp-config.php but that did not help.

**Comment by burhandodhy** [comment]
Hi @mvelev8,

Currently, ElasticPress can work with Elasticsearch up to version 7.10. We didn't test the plugin with Elasticsearch 8.6.2. As the search is working properly, we believe the autosuggest feature should be working too. We believe there is some settings issue that is causing the problem. Would you mind sharing the list below?

- How have you configured the autosuggest feature?
- Error message you are getting for autosuggest
- ElasticPress Status Report

Regards,
Burhan

**Comment by ghost** [comment]
Thanks, 

We have it using the same URL as the search however, the search allows for authentication whereas the autosuggest does not seem to support it.

These are the console errors we are seeing:

mydomain.es.ca-central-1.aws.elastic-cloud.com/:1          Failed to load resource: the server responded with a status of 405 ()
autosuggest-script.js?ver=20b402caee6e6073ba22:1 Error
    at h (autosuggest-script.js?ver=20b402caee6e6073ba22:1:3231)
    at async autosuggest-script.js?ver=20b402caee6e6073ba22:1:6360


## Failed Queries ##



## WordPress ##

### WordPress Environment ###
wp_version: 6.1.1
home_url: https://mydomain.com
site_url: https://mydomain.com
is_multisite: false
theme: MyTheme (1.0.0)
plugins: Advanced Custom Fields PRO (6.0.7), Classic Editor (1.6.2), Data Tables Generator by Supsystic (1.10.26), Debug Bar (1.1.4), Debug Bar ElasticPress (2.1.1), Dynamic Featured Image (3.7.0), ElasticPress (4.5.0), MemberPress Corporate Accounts (1.5.19), MemberPress Developer Tools (1.2.4), MemberPress Pro 30 (Legacy) (1.9.26), Ninja Forms (3.6.20), Ninja Forms - Conditional Logic (3.1), Ninja Forms - Excel Export (3.3.2), Ninja Forms - File Uploads (3.3.12), Ninja Forms - Layout & Styles (3.0.29), Ninja Forms - Mailchimp (3.3.6), Post SMTP (2.4.5), Proxy Cache Purge (5.1.3), Slider Revolution (6.2.22), User Switching (1.7.0), Wordfence Security (7.9.1), WP-Polls (2.77.0), WP Activity Log (4.4.3.2), WP Crontrol (1.15.2), and Yoast SEO (20.3)
revisions: all

### Server Environment ###
php_version: 7.4.33
memory_limit: 40M
timeout: 240



## Indexable Content ##

### Workforce WindsorEssex — https://wfwe.elev8webstudio.com ###
post_count: 891
page_count: 83
post_meta_keys: 28
page_meta_keys: 41
total-all-post-types: 105
distinct-meta-keys: dfiFeatured, slide_template, enclosure, ...., and lastname



## ElasticPress ##

### Settings ###
host: https://mydomain.es.ca-central-1.aws.elastic-cloud.com:443
index_prefix: 
language: en_CA
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30



## Elasticsearch Indices ##

### myindex-post-1 ###
health: green
status: open
index: myindex-post-1
uuid: <redacted>
pri: 5
rep: 0
docs.count: 1031
docs.deleted: 1
store.size: 9.2mb
pri.store.size: 9.2mb
total_fields_limit: 5000



## Last Sync ##

### 2023/03/16 4:53:20 pm ###
method: WP Dashboard
end_date_time: 2023/03/16 10:32:49 am
total_time: 17 hours, 39 minutes, 30 seconds
total: 0
synced: 0
skipped: 0
failed: 0
errors: array (
  0 => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'security_exception',
        'reason' => 'missing authentication credentials for REST request [/myindex-post-1]',
        'header' => 
        array (
          'WWW-Authenticate' => 
          array (
            0 => 'Basic realm="security" charset="UTF-8"',
            1 => 'Bearer realm="security"',
            2 => 'ApiKey',
          ),
        ),
      ),
    ),
    'type' => 'security_exception',
    'reason' => 'missing authentication credentials for REST request [/myindex-post-1]',
    'header' => 
    array (
      'WWW-Authenticate' => 
      array (
        0 => 'Basic realm="security" charset="UTF-8"',
        1 => 'Bearer realm="security"',
        2 => 'ApiKey',
      ),
    ),
  ),
)



## Feature Settings ##

### Autosuggest ###
active: true
autosuggest_selector: input[type=search]
endpoint_url: https://mydomain.es.ca-central-1.aws.elastic-cloud.com
force_inactive: false
trigger_ga_event: 1

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: true
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Related Posts ###
active: true
force_inactive: false

**Comment by ghost** [comment]
What needs to be done to make the authentication work with the autosuggest feature?  Search is working fine.

**Comment by burhandodhy** [comment]
Hi @mvelev8,

The autosuggest endpoint is supposed to be a publicly available Elasticsearch endpoint. As that imposes a security risk that needs to be thoroughly investigated, we don't provide support for that in this forum. You can read our article about it ([here](https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups)) for further info. That said, we are now closing the issue. Thank you.

Regards,
Burhan

**Comment by jerasokcm** [comment]
Please, @mvelev8 , confirm which configuration you are using to connect to Elastic Cloud, since you say that at least the searching is working.
In my case, the connection to the server is not established.
What format do you use for the host URL in the configuration page?
How do you define user/password or other connection parameters?
Thanks in advance.

**Comment by ghost** [comment]
Hi, we resolved this issue months ago.

I do not recall what the fix was, sorry.

Matt Vermette
IT Manager

ELEV8 WEB STUDIO

Email: ***@***.******@***.***>
Office: 519-997-2431, x705
Web: elev8webstudio.com<http://elev8webstudio.com>


From: jerasokcm ***@***.***>
Date: Monday, November 20, 2023 at 12:33
To: 10up/ElasticPress ***@***.***>
Cc: Matt Vermette ***@***.***>, Mention ***@***.***>
Subject: Re: [10up/ElasticPress] Autosuggest not working with cloud.elastic.io and version 8.6.2 (Issue #3396)

Please, @mvelev8<https://github.com/mvelev8> , confirm which configuration you are using to connect to Elastic Cloud, since you say that at least the searching is working.
In my case, the connection to the server is not established.
What format do you use for the host URL in the configuration page?
How do you define user/password or other connection parameters?
Thanks in advance.
