### ISSUE TITLE
Default WP Search Query Slow

### ISSUE THREAD

**Issue by bd-viget** [10up/ElasticPress#3398]
### Describe your question

Hi! I'm working on a project that uses ElasticPress & ElasticPress.io. I didn't set it up so I'm a little out-of-the-loop when it comes to how this works and verifying it's working correctly. When visiting the default WordPress search page (`mysite.com/?s=query`), it takes a very long time to load (~7s-9s). Upon investigating, it appears the standard WP Query is running in the background, even though the results are supposed to be coming from ElasticPress. I'm pretty sure the results I'm seeing are directly from WordPress.

Here is some of the info in the Debug Bar: [https://3cd.co/GGu7rLvn](https://3cd.co/GGu7rLvn)

When I enable the Query Log (WP Admin > ElasticPress > Query Log), nothing shows after running a few searches.

I recently reset the index thinking that could have been the issue, but still getting the same results/performance. I should also mention for this site, we have multiple environments (local, development, staging) and I'm currently working on the local environment. I don't know if the index is shared across the environments or if that has anything to do with it.

Is ElasticPress supposed to be overriding the default WP Query on the `is_search()` page?

I can post my Status Report if necessary, but I'll need to first scrub it of client information. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @bd-viget,

ElasticPress uses Elasticsearch out of the box for the search page. From the screenshot, it seems the main search query is integrated with ElasticPress, but in some cases we've seen different queries running to get the search results. To narrow down the issue, we suggest activating the default WordPress Twenty Twenty-Three theme on the staging site or locally, disabling all the plugins, and checking if WordPress still uses the MySQL query for search.

 
Also, do you mind logging in to [ElasticPress.io](https://elasticpress.io/) and opening a support ticket there so we can sort your issue on a priority basis?


Regards,
Burhan

**Comment by felipeelia** [comment]
As we didn’t have any movement on this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know in an EP.io ticket. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
