### ISSUE TITLE
customize_changeset_uuid= added to all URLs

### ISSUE THREAD

**Issue by alex-james** [10up/ElasticPress#3402]
In WP 4.9 changesets were introduced (see: https://make.wordpress.org/core/2017/11/03/new-features-and-enhancements-with-customizer-changesets-in-4-9/) this means when logged into the backend, pages can be previewed and tracked through a UUID using the parameter customize_changeset_uuid=<uuid> which is automatically added to the URL.

The issue is that when not logged in and even when browsing incognito, since activating elasticPress I can see ?customize_changeset_uuid= being appended to the URL of every page. If I deactivate elasticPress and browse incognito the parameter is not added to the URL.

WP Version: 6.1.1
ElastcPress: 4.5.0

**Comment by burhandodhy** [comment]
Hi @alex-james,

Do you mind sharing the contents of your Status Report? It will help us narrow down the root cause of the problem.

Regards,
Burhan

**Comment by alex-james** [comment]
Hi Burhan,

No problem, see below:

## Failed Queries ##



## WordPress ##

### WordPress Environment ###
wp_version: 6.1.1
home_url: https://www.securiflex.co.uk
site_url: https://www.securiflex.co.uk
is_multisite: false
theme: SFX Theme ()
parent_theme: Twenty Twenty-Two (1.3)
plugins: Advanced Custom Fields PRO (5.12.3), AIOSEO - Image SEO (1.1.6), AIOSEO - IndexNow (1.0.8), AIOSEO - Link Assistant (1.0.14), AIOSEO - Local Business (1.2.15), AIOSEO - News Sitemap (1.0.13), AIOSEO - Redirects (1.2.8), All in One SEO Pro (4.3.3), Breeze (2.0.17), ElasticPress (4.5.0), ElasticPressOverrides (1.0.0), ElasticPress Proxy (1.0.0), Epim Integration (1.0.0), Google Analytics for WordPress by MonsterInsights (8.13.1), Gravity Forms (2.6.9), Gravity Forms CLI (1.4), Gravity Forms reCAPTCHA Add-On (1.1.1), MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall (4.87), Social Media and Share Icons (Ultimate Social Media) (2.8.0), User Role Editor (4.63.2), WooCommerce Google Analytics Integration (1.6.2), WP All Export - ACF Export Add-On Pro (1.0.5), WP All Export - WooCommerce Export Add-On Pro (1.0.6), WP All Export Pro (1.8.1), WP All Import - ACF Add-On (3.3.8), WP All Import - WooCommerce Import Add-On Pro (3.3.4), WP All Import Pro (4.7.8), WP Crontrol (1.15.1), and WP Store Locator (2.2.236)
revisions: all

### Server Environment ###
php_version: 7.4.33
memory_limit: 40M
timeout: 300



## Indexable Content ##

### Securi-Flex — https://www.securiflex.co.uk ###
post_count: 1
page_count: 50
product_count: 923
category_count: 65
article_count: 33
post_meta_keys: 1
page_meta_keys: 0
product_meta_keys: 27
category_meta_keys: 17
article_meta_keys: 16
total-all-post-types: 58
distinct-meta-keys: yoast-structured-data-blocks-images-cache, _sku, _regular_price, total_sales, _tax_status, _tax_class, _manage_stock, _backorders, _sold_individually, _virtual, _downloadable, _product_image_gallery, _stock, _stock_status, _wc_average_rating, _product_version, _price, _product_attributes, epim_API_ID, epim_product_group_name, epim_variation_ID, epim_Qty_Break_1, epim_Qty_Break_2, epim_Qty_Break_3, epim_Qty_Price_1, epim_Qty_Price_2, epim_Qty_Price_3, _thumbnail_id, pbsl_wc_category_term_id, pbsl_page_layput, delivery, guides_and_tips, usps, attributes, product_info_table, product_filters, available_colours_attribute_code, price_from, price_from_item, image_gallery, ep_exclude_from_search, guides_and_tips_0_guides_and_tips_article, guides_and_tips_1_guides_and_tips_article, guides_and_tips_2_guides_and_tips_article, recommended_products_0_recommended_product, recommended_products_0_subcategory_link, recommended_products_1_recommended_product, recommended_products_1_subcategory_link, recommended_products_2_recommended_product, recommended_products_2_subcategory_link, recommended_products, related_articles_0_related_article, related_articles, related_articles_1_related_article, related_articles_2_related_article, recommended_products_3_recommended_product, recommended_products_3_subcategory_link, and related_articles_3_related_article



## ElasticPress ##

### Settings ###
host: http://localhost:9200
index_prefix:
language: en_GB
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30



## Elasticsearch Indices ##

### securiflexcouk-post-1 ###
health: yellow
status: open
index: securiflexcouk-post-1
uuid: ymTkxxCWRT-IzxfxA_Aoqg
pri: 5
rep: 1
docs.count: 1072
docs.deleted: 195
store.size: 58.9mb
pri.store.size: 58.9mb
total_fields_limit: 5000



## Last Sync ##

### 2023/03/23 8:58:52 am ###
method: WP Dashboard
is_full_sync: No
end_date_time: 2023/03/23 8:59:32 am
total_time: 0 hours, 0 minutes, 40 seconds
total: 1072
synced: 1072
skipped: 0
failed: 0
errors: array (
)



## Feature Settings ##

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Instant Results ###
active: true
facets: post_type,tax-pa_overall-al-foil-shield,tax-pa_overall-colour,tax-pa_overall-diameter-2-mm,tax-pa_overall-diameter-mm,tax-pa_overall-sheath,tax-pa_overall-tape-material
force_inactive: false
highlight_tag:
match_type: all
per_page: 10
term_count: 1

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Related Posts ###
active: true
force_inactive: false

### WooCommerce ###
active: true
force_inactive: false
orders: 0


Kind regards

Alex


------ Original Message ------
From "Burhan Nasir" ***@***.******@***.***>>
To "10up/ElasticPress" ***@***.******@***.***>>
Cc "Alex Lancaster" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 3/24/2023 12:18:52 PM
Subject Re: [10up/ElasticPress] customize_changeset_uuid= added to all URLs (Issue #3402)


Hi @alex-james<https://github.com/alex-james>,

Do you mind sharing the contents of your Status Report? It will help us narrow down the root cause of the problem.

Regards,
Burhan

**Comment by felipeelia** [comment]
@alex-james can you please share the content of that ElasticPressOverrides plugin? The behavior you are seeing is not something we can replicate in a clean install.

**Comment by alex-james** [comment]
No problem, there are some CSS overrides, setting the number of results to 25 as per your guidelines together with some JS to modify the markup for the search results but nothing that should affect the URL of the page,

Kind regards

Alex Lancaster


------ Original Message ------
From "Felipe Elia" ***@***.******@***.***>>
To "10up/ElasticPress" ***@***.******@***.***>>
Cc "Alex Lancaster" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 4/13/2023 7:26:31 PM
Subject Re: [10up/ElasticPress] customize_changeset_uuid= added to all URLs (Issue #3402)


@alex-james<https://github.com/alex-james> can you please share the content of that ElasticPressOverrides plugin? The behavior you are seeing is not something we can replicate in a clean install.

**Comment by alex-james** [comment]
[Link to module (expires in 7 days)](https://we.tl/t-HYWcEKK5lm)

**Comment by felipeelia** [comment]
Thanks, @alex-james. Yes, that plugin shouldn't be causing you this problem. Here are a couple of questions that might help us to understand the problem better:

1. Is the customize_changeset_uuid parameter added to all href attributes throughout the site or is it added once you visit a page (like, you go to a page without it and are redirected to a URL with it)?
2. Can you please install the [Debug Bar ElasticPress](https://10up.github.io/ElasticPress/tutorial-debugging.html) plugin, visit a search page results, and share the requests info with us? It'll help us to see how the data is being stored in the Elasticsearch server.

Thanks!

**Comment by alex-james** [comment]
Sorry I've been tied up with other projects, any chance this can be re-opened and I'll fetch the information on Thur? If not I'll raise as a new issue.

**Comment by alex-james** [comment]
@felipeelia sorry for the delay in coming back to you on this and thank you for re-opening. I can confirm that the URL parameter is added after requesting the URL, so I can browse incognito to http://mysite.com/ and when the page loads the URL in the browser bar is showing as: [http://mysite.com?customize_changeset_uuid](http://mysite.com/?customize_changeset_uuid)

I have added the plugin to my local dev copy, there doesn't seem to be much of interest in the response header, so I presume it is the response JSON you are interested in? I've added the response for a query that returned 5 results, let me know if you need any more from me.

https://we.tl/t-buplQR4Hkn

**Comment by alex-james** [comment]
Any updates on this one @felipeelia? After the end of the week I'll be tied up on other projects for a couple of weeks, so please don't close if I don't come back to you immediately. I'll be back on this after tomorrow on 18th May.

**Comment by robertboniface** [comment]
Hi all, I'm a junior developer working alongside @alex-james on this project. As he's tied up, can you please liase any updates with me? Thanks in advance :)

**Comment by robertboniface** [comment]
Hi all,

I've figured out why "customize_changeset_uuid=" is being added to the end of every URL (**_although, the issue is not totally solved._**)

We created a bespoke plugin called "ElasticPressOverrides" which has been built to handle the instant search in way that we'd like (namely, at least in my junior perspective, enqueuing js & css files and limiting the total number of search results.)

Within the "enqueue_scripts" function, there's an array that included the following:

`array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-block-editor', 'customize-preview' )`

After further investigation, I found that "customize_changeset_uuid=" is added to the end of preview URL's (particularly, when building a page in Gutenberg.)

I then removed 'customise-preview' from the array, so now it is as follows:

`array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-block-editor' )`

This has **_almost_** solved the issue. Now, it **no longer** renders "customize_changeset_uuid=" at the end of every URL, yet it will still render a "**?**".

This time, it is **not** related to the ElasticPressOverrides plugin as the issue is still present even after disabling the plugin.

Any ideas?

**Comment by felipeelia** [comment]
@LeashFox Can you please:

1. Share with us the ElasticPressOverrides plugin content, this time in a way that the link doesn't expire? Pastebin.com used to be a good alternative for that.
2. Exactly when the `?` is added? Only when clicking on a link in Instant Results or every time?

**Comment by robertboniface** [comment]
Good morning @felipeelia. 

I've attached the contents of the ElasticPressOverrides plugin as per your request.

**elastic-search.css**: 
https://pastebin.com/tdGvVPQq

**elastic-search.js**:
https://pastebin.com/C6Evgnya

**elasticpress-overrides.php**:
https://pastebin.com/YqFaJDQY

**composer.json**:
https://pastebin.com/7C4RmY0e

Please let me know if there's anything else I can help with?

Thanks,
Robert

**Comment by robertboniface** [comment]
@felipeelia, I forgot to mention that the "?" occurrs when I click on category/subcategory pages (which are custom post types) rather than on results.

The issue disappears when the elasticpress plugin is disabled, and the elasticpress-overrides no longer has an affect.

Would you like me to raise this as a separate ticket as it's no longer in relation to "customize_changeset_uuid=" being added at the end of every URL?
