### ISSUE TITLE
need js hook for open auto suggestion in new tab

### ISSUE THREAD

**Issue by ravikantdk** [10up/ElasticPress#3406]
### Describe your question

Hello,

I want to open auto suggested link in a new tab. How can I do the same using JS hook.
Also how can I know the available JS hooks for elastic press plugin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
@ravikantdk The available JavaScript hooks are all covered in the Theme Integration section of the docs, here: https://10up.github.io/ElasticPress/tutorial-theme-integration.html

To open Autosuggest links in a new tab I would refer to the _Customize Suggestion Markup_ section and isntead of adding the date, add a `target="_blank"` attribute to the link.

**Comment by ravikantdk** [comment]
Hello @JakePT  I tried that too(adding target attribute to the link) but didn't work. That's why I asked for the additional hook if available.

Also, I would like to know, how to keep the auto-suggestion container open(or when the user clicks back on the search field that time open the auto-suggestion container again with the previous result).

**Comment by JakePT** [comment]
Hi @ravikantdk, on double checking the code you're correct, changing the href attribute won't work because Autosuggest doesn't use the link, it actually just uses JS to open the URL directly. Unfortunately this behaviour is not filterable, nor is the behaviour around when the suggestions list is visible. I'll reopen this issue so that we can look at what fixes we could make to resolve these issues.

**Comment by JakePT** [comment]
I think what we can do here is on this line:

```
if (epas.action === 'navigate') {
	return goToAutosuggestItem(input.value, element.dataset.url);
}
```

Use `applyFilters` to apply a JS filter that would allow developers to replace the callback function used when navigating to an Autosuggest item. In this example that could be a function that opens the URL in a new tab. It would look like this:

```
if (epas.action === 'navigate') {
	const navigateCallback = applyFilters('ep.Autosuggest.navigateCallback', goToAutosuggestItem);

	return navigateCallback(input.value, element.dataset.url);
}
```

Developers could then replace the `goToAutosuggestItem()` with their own function at accepts the search term and item URL as parameters:

```
const myNavigateCallback = (searchTerm, url) => {
	window.open(url, '_blank');
};

addFilter(
	'ep.Autosuggest.navigateCallback',
	() => myNavigateCallback,
);
```

Steps required to implement:

- Add the filter as described in this comment.
- Add inline documentation for the hook.
- Update theme integration docs with documentation for the hook, and an example.
- Add E2E tests (see Instant Results tests for an example of testing a JS hook).

**Comment by ravikantdk** [comment]
I appreciate the team's attention to the feedback and their commitment to incorporating it into the latest release.

Thank you for considering my suggestion.
