### ISSUE TITLE
Add "did you mean... ?" support to Instant Results

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#3409]
### Is your enhancement related to a problem? Please describe.

#2089 will add support for search suggesters to ElasticPress queries. This will automatically add the necessary parameters to the Elasticsearch query saved as the search template for use by Instant Results. Once this is done support for displaying the returned suggestions should be added to Instant Results.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anjulahettige** [comment]
We are going to add a new option inside the instant results box with the first two options of Did you mean.
