### ISSUE TITLE
Maximum results per post type

### ISSUE THREAD

**Issue by joeprongen** [10up/ElasticPress#3415]
So, we are searching posts, pages and products in the same search bar.

We limit the results on 10, but actually, we have like 3 tabs for the result window, showing posts pages and products.
Now we want to show like 4 pages maximum, 4 posts maximum or 4 products maximum.
But when investigating the query, for most results it would show 10 pages, or 10 products.
Only if we set the limit to 100 / 200 it would come up with some products or pages.

Ofcourse this is intended behaviour, but would it be possible to max size the post type queries?
so a maximum for 4 on the post type pages, and then it would search for products / post etc.

In this way we have results for all tabs, instead of having to show "no products found" just because the pages have 10 results with a higher score.

Thanks in advance

**Comment by felipeelia** [comment]
Hi @joeprongen! Unfortunately, that is not possible with ElasticPress out-of-the-box.

Elasticsearch has an endpoint (_msearch) that accepts multiple search queries in a single request, and that would be the best way to achieve what you want (see #2934 for more.) That would require some custom code though, and that falls outside the scope of this forum.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!
