### ISSUE TITLE
Displaying post featured image in auto-suggest

### ISSUE THREAD

**Issue by ravikantdk** [10up/ElasticPress#3418]
### Describe your question

Hello,

I want to display the featured(thumbnail) image of the post in auto-suggest along with the post title.

If there is any JS hook available then please let me know OR do let me know if there is any workaround.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @ravikantdk, we've covered that topic in this section of our documentation: https://10up.github.io/ElasticPress/tutorial-theme-integration.html#customize-suggestion-markup
