### ISSUE TITLE
BUG: Not working with ACF Fields plus admin-ajax.php

### ISSUE THREAD

**Issue by ghost** [10up/ElasticPress#3427]
### Describe the bug

I had a perfectly working search functionality but I was using non-secure AJAX requests and then I decided to use WP out-of-the-box AJAX handler. 

Right after doing that, the search stopped working and some research lead me to add `add_filter('ep_ajax_wp_query_integration', '__return_true');`, which worked.

But now I noticed that the Search Fields & Weighting settings also stopped being applied. I tried a lot to make it work, but maybe this is some filter problem and/or EP limitation.

### Steps to Reproduce

1. Use WP AJAX (https://copyprogramming.com/howto/using-wp-ajax-and-wp-ajax-nopriv-hooks)
2. Try to add custom fields to your query, using Search Fields & Weighting

### Screenshots, screen recording, code snippet

Search Weighting Registering:

```php
// Adding custom fields to Elastic Press Search Weighting
add_filter(
  'ep_weighting_fields_for_post_type',
  function($fields, $post_type) {
    // Collection Post Type
    if ($post_type == 'collection') {
      $fields = mountCustomFieldsForWeighting($fields, [
        'Artists'                 => 'meta.collectionArtists.value',
        'Culture'                 => 'meta.culture.value',
        'Classification'          => 'meta.classification.value',
        'Collection Terms'        => 'meta.collectionTerms.value',
        'Credit Line'             => 'meta.creditLine.value',
        'Date Acquired'           => 'meta.dateAcquired.value',
        'Dated'                   => 'meta.dated.value',
        'Description'             => 'meta.description.value',
        'Display Date'            => 'meta.displayDate.value',
        'Display Name'            => 'meta.displayName.value',
        'Exhibitions'             => 'meta.exhibitions.value',
        'First Name'              => 'meta.firstName.value',
        'Forward Display'         => 'meta.forwardDisplay.value',
        'Historical Attributions' => 'meta.histAttributions.value',
        'Location Description'    => 'meta.locationDescription.value',
        'Medium'                  => 'meta.medium.value',
        'Nationality'             => 'meta.nationality.value',
        'Object ID'               => 'meta.objectID.value',
        'Object Description'      => 'meta.objectDescription.value',
        'Object Medium'           => 'meta.objectMedium.value',
        'Object Name'             => 'meta.objectName.value',
        'Object Number'           => 'meta.objectNumber.value',
        'On View'                 => 'meta.onView.value',
        'Style'                   => 'meta.style.value',
        'Web Image'               => 'meta.webImage.value',
      ]);
    }
    
    return $fields;
  }, 10, 2
);

function mountCustomFieldsForWeighting ($fields, $keys) {
  if (empty($fields['meta'])) {
    $fields['meta'] = [
      'label'    => 'Post Type ACF',
      'children' => []
    ];
  }
  
  foreach ($keys as $label => $key) {
    $fields['meta']['children'][$key] = [
      'key'   => $key,
      'label' => __($label, 'icelander-child')
    ];
  }
  
  return $fields;
}
```

Query Args:
```php
$searchQueryArgs = [
  'ep_integrate'   => true,
  'paged'          => $paged,
  'post_type'      => $queryType,
  'posts_per_page' => $postsPerPage,
  'orderby'        => $searchOrderFields,
];

if (array_key_exists('s', $searchFields)) {
  $searchQueryArgs['s'] = $searchFields['s'];
}

$searchResults = new WP_Query($searchQueryArgs);
```

### Environment information

- Device: MacBook Pro (16-inch, 2021)
- OS: MacOS Monterey 12.6.3 (21G419)
- Browser and Version: Google Chrome Version 111.0.5563.146 (Official Build) (arm64)

### WordPress Environment ###
wp_version: 6.2
home_url: https://high.org
site_url: https://high.org
is_multisite: false
theme: Icelander Child (1.0.0)
parent_theme: Icelander (1.6.2)
plugins: Admin Columns (4.6.1), Advanced Custom Fields PRO (6.0.7), ElasticPress (4.5.0), GTM4WP (1.16.2), Post Duplicator (2.28), Post Types Order (2.0.2), PublishPress Future (2.9.2), Really Simple SSL (6.2.3), S3 Uploads (3.0.3), WordPress Importer (0.8), WP Crontrol (1.15.2), WP Engine Smart Plugin Manager (5.13.28), WP Migrate (2.6.3), Yoast SEO (20.4), and Yoast SEO Premium (20.4)
revisions: 0

### Server Environment ###
php_version: 8.0.28
memory_limit: 40M
timeout: 3600

### High Museum of Art — https://high.org ###
collection_count: 13,729
collection_highlight_count: 67
event_count: 54
exhibition_count: 187
page_count: 174
person_count: 9
press_release_count: 174
teacher_resource_count: 78
attachment_count: 4,538
acf-field-group_count: 38
acf-field_count: 545
collection_meta_keys: 43
collection_highlight_meta_keys: 43
event_meta_keys: 43
exhibition_meta_keys: 43
page_meta_keys: 43
person_meta_keys: 43
press_release_meta_keys: 43
teacher_resource_meta_keys: 43
attachment_meta_keys: 43
acf-field-group_meta_keys: 43
acf-field_meta_keys: 43
total-all-post-types: 43
distinct-meta-keys: exhibition_short_description, exhibition_start_date, exhibition_end_date, exhibition_is_traveling, exhibition_is_digital, event_short_description, event_location, event_start_date, event_end_date, event_start_time, event_end_time, event_is_daily_event, event_is_weekly, event_weekdays, culture, classification, collectionArtists, collectionTerms, creditLine, dateAcquired, dated, description, displayDate, displayName, exhibitions, firstName, forwardDisplay, hasImage, histAttributions, locationDescription, medium, nationality, objectDescription, objectMedium, objectName, objectNumber, onView, style, webImage, collectionAreaID, dateBegin, dateEnd, and press_release_date

### Settings ###
host: https://eshighwp.es.us-east-1.aws.found.io
index_prefix: 
language: en_US
per_page: 500
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### highorg-post-1 ###
health: green
status: open
index: highorg-post-1
uuid: 4Bt_4aEOQ2GC35v3h2CpUg
pri: 1
rep: 1
docs.count: 19593
docs.deleted: 0
store.size: 112.9mb
pri.store.size: 56.4mb
total_fields_limit: 2500

### 2023/04/04 8:08:06 pm ###
method: WP Dashboard
is_full_sync: Yes
end_date_time: 2023/04/04 8:11:32 pm
total_time: 0 hours, 3 minutes, 26 seconds
total: 19593
synced: 19593
skipped: 0
failed: 0
errors: array (
)

### Autosuggest ###
active: true
autosuggest_selector: 
endpoint_url: 
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Protected Content ###
active: true
force_inactive: false

### Related Posts ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
Hey, I added another filter here and now it's working (`ep_enable_do_weighting`):

```php
// Integrate with admin ajax queries
add_filter("ep_ajax_wp_query_integration", function() {
  return true;
}, 10);

// Enable Weighting on admin ajax
add_filter("ep_enable_do_weighting", function() {
  return true;
}, 10);
```

Is this the expected behavior? Because the weighting works fine everywhere else, but using WP ajax, only if I explicitly enables it.

**Comment by felipeelia** [comment]
Hey @arctouch-fernandogarcia, thanks for sharing the solution. And yes, that is the expected behavior, as AJAX requests handled by WordPress are considered to be "admin" requests (the endpoint is admin-ajax.php after all.)
