### ISSUE TITLE
delete_post called at enter new post-new.php in wp-admin

### ISSUE THREAD

**Issue by EkAndreas** [10up/ElasticPress#343]
ElasticPress causes two error calls when creating a new post i wp-admin.
The hook delete_post is triggered twice and there is nothing to delete from index when creating a new post :-)

**Comment by tlovett1** [comment]
Would you mind demonstrating this problem with a test?

**Comment by EkAndreas** [comment]
Yes, reproduce the error like this:
1. Plain WordPress installation with ElasticPress configurated to ES.
2. Install and activate Query Monitor to watch requests.
3. Click "Add New" under Posts in WordPress wp-admin.
4. Follow the red flag from Query Monitor in the admin bar. There are two http-requests failing to ES.

**Comment by EkAndreas** [comment]
Http Request: DELETE http://127.0.0.1:9200/newsflowdevwp-1//post/22
Response: 404
Call Stack:
WP_Http->request()
wp_remote_request()
EP_API->remote_request()
ep_remote_request()
EP_API->delete_post()
ep_delete_post()
EP_Sync_Manager->action_delete_post()
EP_Sync_Manager->action_sync_on_update()
do_action('wp_insert_post')
wp_insert_post()
get_default_post_to_edit()

**Comment by tlovett1** [comment]
Hmmm ok. We will investigate.

**Comment by allan23** [comment]
I can confirm that an unnecessary HTTP request is happening when WP creates a post with the auto-draft status. PR to follow.

**Comment by sc0ttkclark** [comment]
PR looks good

**Comment by EkAndreas** [comment]
Whats PR?

**Comment by sc0ttkclark** [comment]
Pull Request, a code change that gets integrated into the code after review and any additional tweaks.
