### ISSUE TITLE
Autosuggest - Woocommerce - Take total_sales into effect

### ISSUE THREAD

**Issue by joeprongen** [10up/ElasticPress#3437]
### Describe your question

Hi Guys, thanks for the great work!

How would we take the meta total_sales into effect from woocommerce product meta?

We would like to order the products a bit more on popularity.
Ordering it totally on total_sales only gives the same results, so it would be more like a modifier maybe that enhances the score a bit.

Ofcourse just a number doesnt really say something, so we would have the idea to add all total sales together for all products, say like once a day. so say all product total sales would be 1000.
Then product A which has a total sales of 10 would be 1 percent of total sales.

Then we would like to alter the autosuggest query to use that number 1 and maybe multiply it with X and add that to total score of the product.
Then we would have the perfect combination of weight scoring and popularity.

I think i would have to use the formatted_args filter, but then i get a little stuck from there.

Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @joeprongen. That is an interesting use case but be aware that you may end up in a scenario where the total_sales for a month is 100 but a product that has been around for a year might have 1000 sales already (total of all time.)

An example of calculation (vaguely) similar to what you want is the date decay we apply to results. You can see it in the [Search::weight_recent()](https://github.com/10up/ElasticPress/blob/4.5.1/includes/classes/Feature/Search/Search.php#L454) method. It uses the `'function_score'` parameter to inject a -- you guessed it right -- a function to change the score :)

The best way to develop such functionalities is to get the query the way you want first, sending it directly to Elasticsearch (using a program like Postman or Kibana.) Then you use WordPress filters to reflect those changes in WP. You can use [Debug Bar ElasticPress](https://10up.github.io/ElasticPress/tutorial-debugging.html) to check what the query being sent by WP looks like too.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation.
