### ISSUE TITLE
Facets not showing

### ISSUE THREAD

**Issue by nicolas-wl** [10up/ElasticPress#3439]
### Describe your question

No facets are showing on my WooCommerce sidebar.
Looking at the debug bar, I'm getting this error:

`[body] => {"error":
{"root_cause":[{
"type":"query_shard_exception",
"reason":"No mapping found for [oldest_to_recent] in order to sort on",
"index_uuid":"iqouUt54Ruadf-cAAOP0BQ",
"index":"mysitecom-post-1"}],
"type":"search_phase_execution_exception",
"reason":"all shards failed",
"phase":"query",
"grouped":true,
"failed_shards":[{"shard":0,"index":"mysitecom-post-1","node":"15K_73f1T3KgJ8-c8zmDSA","reason":{"type":"query_shard_exception","reason":"No mapping found for [oldest_to_recent] in order to sort on","index_uuid":"iqouUt54Ruadf-cAAOP0BQ","index":"mysitecom-post-1"}}]},"status":400}`

How to fix this?

(sync was successful, autosuggest is also working)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @nicolas-wl! As the error is saying, the Elasticsearch query is trying to use the `'oldest_to_recent'` field to order your results but it is not part of the mapping.

Can you please share the entire requests' info from Debug Bar ElasticPress, so we can understand how and why that value is being used?
