### ISSUE TITLE
Mapping failed

### ISSUE THREAD

**Issue by crebacz** [10up/ElasticPress#344]
Hello

I upgraded to 1.6 and was trying to reindex my site.  It deleted the current index as expected, but then WP-CLI return the message Error: Mapping Failed.  Not sure what causes this or how to troubleshoot. 

Any suggestions on how to proceed?

**Comment by tlovett1** [comment]
What version of Elasticsearch are you running?

**Comment by crebacz** [comment]
The most recent 1.6

-------- Original Message --------

**Comment by tlovett1** [comment]
Elasticsearch not ElasticPress

**Comment by crebacz** [comment]
I'm sorry.

Version 1.4.2

**Comment by tlovett1** [comment]
First, can you try upgrading to the latest version?

**Comment by crebacz** [comment]
I have been trying to figure out how to update and embarrassingly I have not been able to do so.  I know you don't support elasticsearch itself...but do you know of a resource that explains the proper steps?  If not, i will keep looking.

I was wondering, worst case scenario, and I am not able to update to the latest version, what does that mean with respect to using this plugin?

Thanks as always for your time and effort.



-------- Original Message --------

**Comment by allan23** [comment]
@crebacz Here are a few resources:

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

http://stackoverflow.com/questions/9497223/how-to-upgrade-a-running-elasticsearch-older-instance-to-a-newer-version

I know this isn't much to go off of, but I'm hoping it will be enough to point you in the right direction.

**Comment by edbloom** [comment]
Hey @allan23  - I got the same error running ES 2.0 - downgrading to ES 1.7.3 resolved the issue so I'm guessing there's something new in 2.0 breaking ElasticPress.

**Comment by sarahannedaigle** [comment]
In the Elasticsearch 2.0 video they mentioned there are several breaking changes. Any idea what elements might be the issue? 

Sarah

**Comment by tlovett1** [comment]
This bug is confirmed. Expect a fix today.

**Comment by natostanco** [comment]
getting mapping failed too on latest elasticpress (2.0 ) and elasticsearch (2.3.4)

**Comment by tlovett1** [comment]
Can you manually POST the JSON to Elasticsearch and tell us what the error message is?

**Comment by natostanco** [comment]
I tried the plugin from git and it indexed everything fine so maybe you fixed it along the way
