### ISSUE TITLE
BUG: WooCommerce Custom Ordering + Name not working

### ISSUE THREAD

**Issue by lfinsaas** [10up/ElasticPress#3440]
### Describe the bug

WooCommerce Default Sort (Custom Ordering + Name) does not work. We expect to be able to sort the products by menu_order, but when ElasticPress is enabled, the shop does not respect the menu_order and sorts the products alphabetically.

When we disable ElasticPress, the Shop sorts by menu_order, as expected.

### Steps to Reproduce

We cannot let the shop remain purely alphabetical, nor can we disable ElasticPress. Thus, we're sorting the shop by Popularity until this is resolved (meaning we can't show steps to reproduce). Here is the site: https://jaxengrey.com/shop/ 

### WordPress and ElasticPress information

Wordpress: 6.2
ElasticPress: 4.5.1 
WooCommerce: 7.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi, @lfinsaas. Please install [Debug Bar ElasticPress](https://10up.github.io/ElasticPress/tutorial-debugging.html), visit the page where you want to sort products that way, and share with us the Requests' Info. Also, can you please share the Report Status content? Thanks.

**Comment by lfinsaas** [comment]
Here are the outputs:

Here's the setting in Customizer:

<img width="815" alt="Screenshot 2023-04-17 at 12 07 42" src="https://user-images.githubusercontent.com/36778320/232454203-5834e619-62fe-4148-b326-c333f3095028.png">


REQUEST:
shop

QUERY STRING:
post_type=product

MATCHED REWRITE RULE:
shop/?$

MATCHED REWRITE QUERY:
post_type=product

<img width="1280" alt="Screenshot 2023-04-17 at 12 04 40" src="https://user-images.githubusercontent.com/36778320/232453415-a4a00cc3-77e1-4df9-86dd-7ef4d7f6b174.png">


## QUERIES INFO ##

### HTTPS://JAXENGREY.COM/SHOP (2023-04-17 04:55:20) ###
ES_REQ: POST ..../_SEARCH
REQUEST_ID: ....
QUERY_TIME: 285.449028015
WP_ARGS: ARRAY (
  'POST_TYPE' => 'PRODUCT',
  'ERROR' => '',
  'M' => '',
  'P' => 0,
  'POST_PARENT' => '',
  'SUBPOST' => '',
  'SUBPOST_ID' => '',
  'ATTACHMENT' => '',
  'ATTACHMENT_ID' => 0,
  'NAME' => '',
  'PAGENAME' => '',
  'PAGE_ID' => 0,
  'SECOND' => '',
  'MINUTE' => '',
  'HOUR' => '',
  'DAY' => 0,
  'MONTHNUM' => 0,
  'YEAR' => 0,
  'W' => 0,
  'CATEGORY_NAME' => '',
  'TAG' => '',
  'CAT' => '',
  'TAG_ID' => '',
  'AUTHOR' => '',
  'AUTHOR_NAME' => '',
  'FEED' => '',
  'TB' => '',
  'PAGED' => 0,
  'META_KEY' => '',
  'META_VALUE' => '',
  'PREVIEW' => '',
  'S' => '',
  'SENTENCE' => '',
  'TITLE' => '',
  'FIELDS' => '',
  'MENU_ORDER' => '',
  'EMBED' => '',
  'CATEGORY__IN' => 
  ARRAY (
  ),
  'CATEGORY__NOT_IN' => 
  ARRAY (
  ),
  'CATEGORY__AND' => 
  ARRAY (
  ),
  'POST__IN' => 
  ARRAY (
  ),
  'POST__NOT_IN' => 
  ARRAY (
  ),
  'POST_NAME__IN' => 
  ARRAY (
  ),
  'TAG__IN' => 
  ARRAY (
  ),
  'TAG__NOT_IN' => 
  ARRAY (
  ),
  'TAG__AND' => 
  ARRAY (
  ),
  'TAG_SLUG__IN' => 
  ARRAY (
  ),
  'TAG_SLUG__AND' => 
  ARRAY (
  ),
  'POST_PARENT__IN' => 
  ARRAY (
  ),
  'POST_PARENT__NOT_IN' => 
  ARRAY (
  ),
  'AUTHOR__IN' => 
  ARRAY (
  ),
  'AUTHOR__NOT_IN' => 
  ARRAY (
  ),
  'SEARCH_COLUMNS' => 
  ARRAY (
  ),
  'ORDERBY' => 'MENU_ORDER TITLE',
  'ORDER' => 'ASC',
  'META_QUERY' => 
  ARRAY (
  ),
  'TAX_QUERY' => 
  ARRAY (
    'RELATION' => 'AND',
    0 => 
    ARRAY (
      'TAXONOMY' => 'PRODUCT_VISIBILITY',
      'FIELD' => 'TERM_TAXONOMY_ID',
      'TERMS' => 
      ARRAY (
        0 => 7,
        1 => 9,
      ),
      'OPERATOR' => 'NOT IN',
    ),
    1 => 
    ARRAY (
      'TAXONOMY' => 'PRODUCT_TAG',
      'FIELD' => 'SLUG',
      'TERMS' => 
      ARRAY (
        0 => 'CLEARANCE',
      ),
      'OPERATOR' => 'NOT IN',
    ),
  ),
  'WC_QUERY' => 'PRODUCT_QUERY',
  'POSTS_PER_PAGE' => 18,
  'EP_INTEGRATE' => TRUE,
  'EP_FACET' => TRUE,
  'AGGS' => 
  ARRAY (
    'NAME' => 'TERMS',
    'USE-FILTER' => TRUE,
    'AGGS' => 
    ARRAY (
      'CATEGORY' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.CATEGORY.SLUG',
        ),
      ),
      'POST_TAG' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.POST_TAG.SLUG',
        ),
      ),
      'HYPERSPACE_VENDORS' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.HYPERSPACE_VENDORS.SLUG',
        ),
      ),
      'PRODUCT_CAT' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PRODUCT_CAT.SLUG',
        ),
      ),
      'PRODUCT_TAG' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PRODUCT_TAG.SLUG',
        ),
      ),
      'PA_COLOR' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PA_COLOR.SLUG',
        ),
      ),
      'PA_INSEAM' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PA_INSEAM.SLUG',
        ),
      ),
      'PA_SIZE' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PA_SIZE.SLUG',
        ),
      ),
      'COLLECTION_TYPE' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.COLLECTION_TYPE.SLUG',
        ),
      ),
      'SC_COUPON_CATEGORY' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.SC_COUPON_CATEGORY.SLUG',
        ),
      ),
      'FB_PRODUCT_SET' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.FB_PRODUCT_SET.SLUG',
        ),
      ),
      'PORTFOLIO-TAG' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PORTFOLIO-TAG.SLUG',
        ),
      ),
      'PORTFOLIO-CATEGORY' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PORTFOLIO-CATEGORY.SLUG',
        ),
      ),
      'PRODUCT-BRANDS' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PRODUCT-BRANDS.SLUG',
        ),
      ),
      'PA_INDIGO' => 
      ARRAY (
        'TERMS' => 
        ARRAY (
          'SIZE' => 10000,
          'FIELD' => 'TERMS.PA_INDIGO.SLUG',
        ),
      ),
    ),
  ),
  'SUPPRESS_FILTERS' => FALSE,
  'IGNORE_STICKY_POSTS' => FALSE,
  'CACHE_RESULTS' => TRUE,
  'UPDATE_POST_TERM_CACHE' => TRUE,
  'UPDATE_MENU_ITEM_CACHE' => FALSE,
  'LAZY_LOAD_TERM_META' => TRUE,
  'UPDATE_POST_META_CACHE' => TRUE,
  'NOPAGING' => FALSE,
  'COMMENTS_PER_PAGE' => '50',
  'NO_FOUND_ROWS' => FALSE,
)
STATUS_CODE: 200
BODY: {"FROM":0,"SIZE":18,"POST_FILTER":{"BOOL":{"MUST":[{"BOOL":{"MUST_NOT":[{"TERMS":{"TERMS.PRODUCT_VISIBILITY.TERM_TAXONOMY_ID":[7,9]}},{"TERMS":{"TERMS.PRODUCT_TAG.SLUG":["CLEARANCE"]}}]}},{"TERMS":{"POST_TYPE.RAW":["PRODUCT"]}},{"TERMS":{"POST_STATUS":["PUBLISH","ACF-DISABLED"]}}]}},"QUERY":{"MATCH_ALL":{"BOOST":1}},"SORT":[{"MENU_ORDER":{"ORDER":"ASC"}},{"POST_TITLE.SORTABLE":{"ORDER":"ASC"}}],"AGGS":{"TERMS":{"FILTER":{"BOOL":{"MUST":[{"BOOL":{"MUST_NOT":[{"TERMS":{"TERMS.PRODUCT_VISIBILITY.TERM_TAXONOMY_ID":[7,9]}},{"TERMS":{"TERMS.PRODUCT_TAG.SLUG":["CLEARANCE"]}}]}},{"TERMS":{"POST_TYPE.RAW":["PRODUCT"]}},{"TERMS":{"POST_STATUS":["PUBLISH","ACF-DISABLED"]}}]}},"AGGS":{"CATEGORY":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.CATEGORY.SLUG"}},"POST_TAG":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.POST_TAG.SLUG"}},"HYPERSPACE_VENDORS":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.HYPERSPACE_VENDORS.SLUG"}},"PRODUCT_CAT":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PRODUCT_CAT.SLUG"}},"PRODUCT_TAG":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PRODUCT_TAG.SLUG"}},"PA_COLOR":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PA_COLOR.SLUG"}},"PA_INSEAM":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PA_INSEAM.SLUG"}},"PA_SIZE":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PA_SIZE.SLUG"}},"COLLECTION_TYPE":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.COLLECTION_TYPE.SLUG"}},"SC_COUPON_CATEGORY":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.SC_COUPON_CATEGORY.SLUG"}},"FB_PRODUCT_SET":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.FB_PRODUCT_SET.SLUG"}},"PORTFOLIO-TAG":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PORTFOLIO-TAG.SLUG"}},"PORTFOLIO-CATEGORY":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PORTFOLIO-CATEGORY.SLUG"}},"PRODUCT-BRANDS":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PRODUCT-BRANDS.SLUG"}},"PA_INDIGO":{"TERMS":{"SIZE":10000,"FIELD":"TERMS.PA_INDIGO.SLUG"}}}}}}
RESULT: ARRAY (
  'TOOK' => 71,
  'TIMED_OUT' => FALSE,
  '_SHARDS' => 
  ARRAY (
    'TOTAL' => 1,
    'SUCCESSFUL' => 1,
    'SKIPPED' => 0,
    'FAILED' => 0,
  ),
  'HITS' => 
  ARRAY (
    'TOTAL' => 
    ARRAY (
      'VALUE' => 720,
      'RELATION' => 'EQ',
    ),
    'MAX_SCORE' => NULL,
    'HITS' => 
    ARRAY (
      0 => 
      ARRAY (
        '_INDEX' => 'WPE-JAXENGREY-LFC8LS64--JAXENGREYCOM-POST-1',
        '_TYPE' => '_DOC',
        '_ID' => '101333',
        '_SCORE' => NULL,
        '_SOURCE' => 
        ARRAY (
          'POST_ID' => 101333,
          'ID' => 101333,
          'POST_AUTHOR' => 
          ARRAY (
            'RAW' => 'HYPERSPACE',
            'LOGIN' => 'HYPERSPACE',
            'DISPLAY_NAME' => 'HYPERSPACE',
            'ID' => 5,
          ),
          'POST_DATE' => '2023-04-04 10:27:39',
          'POST_DATE_GMT' => '2023-04-04 15:27:39',
          'POST_TITLE' => 'ADLER TAPERED CLASSIC',
          'POST_EXCERPT' => '',
          'POST_CONTENT_FILTERED' => '',
          'POST_CONTENT' => '',
          'POST_STATUS' => 'PUBLISH',
          'POST_NAME' => 'ADLER-TAPERED-CLASSIC-5',
          'POST_MODIFIED' => '2023-04-06 12:58:10',
          'POST_MODIFIED_GMT' => '2023-04-06 17:58:10',
          'POST_PARENT' => 0,
          'POST_TYPE' => 'PRODUCT',
          'POST_MIME_TYPE' => '',
          'PERMALINK' => 'HTTPS://JAXENGREY.COM/PRODUCT/ADLER-TAPERED-CLASSIC-5/',
          'TERMS' => 
          ARRAY (
            'HYPERSPACE_VENDORS' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 3988,
                'SLUG' => 'CITIZENS-OF-HUMANITY',
                'NAME' => 'CITIZENS OF HUMANITY',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 3988,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":3988,"SLUG":"CITIZENS-OF-HUMANITY","NAME":"CITIZENS OF HUMANITY","PARENT":0,"TERM_TAXONOMY_ID":3988,"TERM_ORDER":0}',
              ),
            ),
            'PRODUCT_CAT' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 2596,
                'SLUG' => 'DENIM-PANTS',
                'NAME' => 'DENIM PANTS',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2596,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2596,"SLUG":"DENIM-PANTS","NAME":"DENIM PANTS","PARENT":0,"TERM_TAXONOMY_ID":2596,"TERM_ORDER":0}',
              ),
              1 => 
              ARRAY (
                'TERM_ID' => 2597,
                'SLUG' => 'JEANS',
                'NAME' => 'JEANS',
                'PARENT' => 2596,
                'TERM_TAXONOMY_ID' => 2597,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2597,"SLUG":"JEANS","NAME":"JEANS","PARENT":2596,"TERM_TAXONOMY_ID":2597,"TERM_ORDER":0}',
              ),
            ),
            'PRODUCT_TAG' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 3980,
                'SLUG' => 'OUTDOOR',
                'NAME' => 'OUTDOOR',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 3980,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":3980,"SLUG":"OUTDOOR","NAME":"OUTDOOR","PARENT":0,"TERM_TAXONOMY_ID":3980,"TERM_ORDER":0}',
              ),
            ),
            'PA_COLOR' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 4440,
                'SLUG' => 'SIERRA',
                'NAME' => 'SIERRA',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 4440,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":4440,"SLUG":"SIERRA","NAME":"SIERRA","PARENT":0,"TERM_TAXONOMY_ID":4440,"TERM_ORDER":0}',
              ),
            ),
            'PA_SIZE' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 2575,
                'SLUG' => '30',
                'NAME' => '30',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2575,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2575,"SLUG":"30","NAME":"30","PARENT":0,"TERM_TAXONOMY_ID":2575,"TERM_ORDER":0}',
              ),
              1 => 
              ARRAY (
                'TERM_ID' => 2576,
                'SLUG' => '31',
                'NAME' => '31',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2576,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2576,"SLUG":"31","NAME":"31","PARENT":0,"TERM_TAXONOMY_ID":2576,"TERM_ORDER":0}',
              ),
              2 => 
              ARRAY (
                'TERM_ID' => 2577,
                'SLUG' => '32',
                'NAME' => '32',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2577,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2577,"SLUG":"32","NAME":"32","PARENT":0,"TERM_TAXONOMY_ID":2577,"TERM_ORDER":0}',
              ),
              3 => 
              ARRAY (
                'TERM_ID' => 2578,
                'SLUG' => '33',
                'NAME' => '33',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2578,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2578,"SLUG":"33","NAME":"33","PARENT":0,"TERM_TAXONOMY_ID":2578,"TERM_ORDER":0}',
              ),
              4 => 
              ARRAY (
                'TERM_ID' => 2579,
                'SLUG' => '34',
                'NAME' => '34',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2579,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2579,"SLUG":"34","NAME":"34","PARENT":0,"TERM_TAXONOMY_ID":2579,"TERM_ORDER":0}',
              ),
              5 => 
              ARRAY (
                'TERM_ID' => 2616,
                'SLUG' => '35',
                'NAME' => '35',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2616,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2616,"SLUG":"35","NAME":"35","PARENT":0,"TERM_TAXONOMY_ID":2616,"TERM_ORDER":0}',
              ),
              6 => 
              ARRAY (
                'TERM_ID' => 2580,
                'SLUG' => '36',
                'NAME' => '36',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2580,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2580,"SLUG":"36","NAME":"36","PARENT":0,"TERM_TAXONOMY_ID":2580,"TERM_ORDER":0}',
              ),
              7 => 
              ARRAY (
                'TERM_ID' => 2581,
                'SLUG' => '38',
                'NAME' => '38',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2581,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2581,"SLUG":"38","NAME":"38","PARENT":0,"TERM_TAXONOMY_ID":2581,"TERM_ORDER":0}',
              ),
              8 => 
              ARRAY (
                'TERM_ID' => 2582,
                'SLUG' => '40',
                'NAME' => '40',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 2582,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":2582,"SLUG":"40","NAME":"40","PARENT":0,"TERM_TAXONOMY_ID":2582,"TERM_ORDER":0}',
              ),
            ),
            'PRODUCT-BRANDS' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 3989,
                'SLUG' => 'CITIZENS-OF-HUMANITY',
                'NAME' => 'CITIZENS OF HUMANITY',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 3989,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":3989,"SLUG":"CITIZENS-OF-HUMANITY","NAME":"CITIZENS OF HUMANITY","PARENT":0,"TERM_TAXONOMY_ID":3989,"TERM_ORDER":0}',
              ),
            ),
            'PRODUCT_TYPE' => 
            ARRAY (
              0 => 
              ARRAY (
                'TERM_ID' => 4,
                'SLUG' => 'VARIABLE',
                'NAME' => 'VARIABLE',
                'PARENT' => 0,
                'TERM_TAXONOMY_ID' => 4,
                'TERM_ORDER' => 0,
                'FACET' => '{"TERM_ID":4,"SLUG":"VARIABLE","NAME":"VARIABLE","PARENT":0,"TERM_TAXONOMY_ID":4,"TERM_ORDER":0}',
              ),
            ),
          ),
          'META' => 
          ARRAY (
            '_SKU' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '4206',
                'RAW' => '4206',
                'LONG' => 4206,
                'DOUBLE' => 4206,
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            'TOTAL_SALES' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '0',
                'RAW' => '0',
                'LONG' => 0,
                'DOUBLE' => 0,
                'BOOLEAN' => FALSE,
              ),
            ),
            '_TAX_STATUS' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'TAXABLE',
                'RAW' => 'TAXABLE',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_TAX_CLASS' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'NON-TAXABLE',
                'RAW' => 'NON-TAXABLE',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_MANAGE_STOCK' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'NO',
                'RAW' => 'NO',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_BACKORDERS' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'NO',
                'RAW' => 'NO',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_SOLD_INDIVIDUALLY' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'NO',
                'RAW' => 'NO',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_VIRTUAL' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'NO',
                'RAW' => 'NO',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_DOWNLOADABLE' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'NO',
                'RAW' => 'NO',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_PRODUCT_IMAGE_GALLERY' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '101330,101331,101332',
                'RAW' => '101330,101331,101332',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_THUMBNAIL_ID' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '101329',
                'RAW' => '101329',
                'LONG' => 101329,
                'DOUBLE' => 101329,
                'BOOLEAN' => FALSE,
                'DATE' => '2023-04-13',
                'DATETIME' => '2023-04-13 10:13:29',
                'TIME' => '10:13:29',
              ),
            ),
            '_STOCK' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => NULL,
                'RAW' => NULL,
                'BOOLEAN' => FALSE,
              ),
            ),
            '_STOCK_STATUS' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'INSTOCK',
                'RAW' => 'INSTOCK',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_WC_AVERAGE_RATING' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '0',
                'RAW' => '0',
                'LONG' => 0,
                'DOUBLE' => 0,
                'BOOLEAN' => FALSE,
              ),
            ),
            '_PRODUCT_ATTRIBUTES' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'A:2:{S:8:"PA_COLOR";A:6:{S:4:"NAME";S:8:"PA_COLOR";S:5:"VALUE";S:0:"";S:8:"POSITION";I:0;S:10:"IS_VISIBLE";I:0;S:12:"IS_VARIATION";I:1;S:11:"IS_TAXONOMY";I:1;}S:7:"PA_SIZE";A:6:{S:4:"NAME";S:7:"PA_SIZE";S:5:"VALUE";S:0:"";S:8:"POSITION";I:0;S:10:"IS_VISIBLE";I:0;S:12:"IS_VARIATION";I:1;S:11:"IS_TAXONOMY";I:1;}}',
                'RAW' => 'A:2:{S:8:"PA_COLOR";A:6:{S:4:"NAME";S:8:"PA_COLOR";S:5:"VALUE";S:0:"";S:8:"POSITION";I:0;S:10:"IS_VISIBLE";I:0;S:12:"IS_VARIATION";I:1;S:11:"IS_TAXONOMY";I:1;}S:7:"PA_SIZE";A:6:{S:4:"NAME";S:7:"PA_SIZE";S:5:"VALUE";S:0:"";S:8:"POSITION";I:0;S:10:"IS_VISIBLE";I:0;S:12:"IS_VARIATION";I:1;S:11:"IS_TAXONOMY";I:1;}}',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_PRODUCT_VERSION' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '7.5.1',
                'RAW' => '7.5.1',
                'BOOLEAN' => FALSE,
                'DATE' => '2023-04-13',
                'DATETIME' => '2023-04-13 07:05:01',
                'TIME' => '07:05:01',
              ),
            ),
            'HYPERSPACE_ITEM_TYPE' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'JEANS',
                'RAW' => 'JEANS',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            'HYPERSPACE_UPC' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '',
                'RAW' => '',
                'BOOLEAN' => FALSE,
              ),
            ),
            'HYPERSPACE_STYLE_NAME' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '',
                'RAW' => '',
                'BOOLEAN' => FALSE,
              ),
            ),
            'HYPERSPACE_STYLE_NUMBER' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '',
                'RAW' => '',
                'BOOLEAN' => FALSE,
              ),
            ),
            'FB_PRODUCT_GROUP_ID' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '5840428999418571',
                'RAW' => '5840428999418571',
                'LONG' => 5840428999418571,
                'DOUBLE' => 5840428999418571,
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_DEFAULT_ATTRIBUTES' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => 'A:1:{S:8:"PA_COLOR";S:6:"SIERRA";}',
                'RAW' => 'A:1:{S:8:"PA_COLOR";S:6:"SIERRA";}',
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_PRICE' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '228',
                'RAW' => '228',
                'LONG' => 228,
                'DOUBLE' => 228,
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
            ),
            '_VARIATIONS_SKUS' => 
            ARRAY (
              0 => 
              ARRAY (
                'VALUE' => '157860',
                'RAW' => '157860',
                'LONG' => 157860,
                'DOUBLE' => 157860,
                'BOOLEAN' => FALSE,
                'DATE' => '1970-01-01',
                'DATETIME' => '1970-01-01 00:00:01',
                'TIME' => '00:00:01',
              ),
           [ and so on ]

<img width="1280" alt="Screenshot 2023-04-17 at 12 05 17" src="https://user-images.githubusercontent.com/36778320/232453697-ad17e6fc-7344-46bb-9624-677f58c7c87b.png">

Maybe there's something going on with our WP-Cron job?

<img width="1227" alt="Screenshot 2023-04-17 at 12 02 40" src="https://user-images.githubusercontent.com/36778320/232453080-fa29bb65-4fdf-4bd6-9577-740036815941.png">

**Comment by felipeelia** [comment]
@lfinsaas, looking at the query being sent, it is possible to see `"SORT":[{"MENU_ORDER":{"ORDER":"ASC"}},{"POST_TITLE.SORTABLE":{"ORDER":"ASC"}}`, which means the sort is being applied to the ES query as well. As you've trimmed the query results, it is not possible to check what Elasticsearch has as the menu_order value for each document, so do you mind sending the full report this time? You can download the file and attach it, if you prefer.

**Comment by lfinsaas** [comment]
Here is the full query! 

[jg-query-results.txt](https://github.com/10up/ElasticPress/files/11295242/jg-query-results.txt)

Yeah, I noticed that the query did look correct... but the actual results don't seem to be hooking into the menu_order in the backend. Additionally, when I disable ElasticPress, the results do sort properly, to the menu_order results.

**Comment by creative-andrew** [comment]
I am facing exactly the same issue.

**Comment by navidabdi** [comment]
Hey @felipeelia,
We also have a similar issue with one of our projects.

When the menu order is set to something like = 999999 the product is shown at the end:
![image](https://github.com/10up/ElasticPress/assets/32398454/30b7068c-cdd5-4103-8fba-b8c31590657b)

But when the menu order is set to something like = -1 or any negative number the expected result is that this product should be shown at the top of the other products but this is not the case, and I've checked the query_results and I couldn't find any product with menu order of -1 or any negative number.
![image](https://github.com/10up/ElasticPress/assets/32398454/1667c0c3-f060-4bc5-b008-14fe53448f1d)

**Comment by felipeelia** [comment]
@lfinsaas and @creative-andrew, do you mind sending your ElasticPress Status Reports? If the number of products is greater than the number set in ElasticPress's Content Items per Index Cycle setting, you'll need to resync after changing the products ordering, as stated in this notice, displayed at the Products Sorting admin screen:

![image](https://github.com/10up/ElasticPress/assets/184628/83a58997-22de-4c96-a981-c7ba146cb478)

@navidabdi I could reproduce that problem, thanks! I've opened #3468 addressing it.

**Comment by creative-andrew** [comment]
@felipeelia, no need. My problem is exactly the same one as the one reported by @navidabdi.
