### ISSUE TITLE
Check if post id is sync

### ISSUE THREAD

**Issue by aloisejulian** [10up/ElasticPress#3442]
### Describe your question

 I was wondering if there's a way of checking which posts are synced and which ones are not... Something like ep_synced_status($post_id) or something like that. 
 
 Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @aloisejulian, unfortunately, we don't have a method for that yet. Depending on what you are trying to achieve, that can be a little tricky: if you want to simply check if the post exists in both places, that is easier. If you want to be sure all data are synced, you'll need to check all post meta, etc.

You can use something like `\ElasticPress\Indexables::factory()->get( 'post' )->get( <post_id> )` to get the post from ES and compare. Would that be enough for your use case?

**Comment by aloisejulian** [comment]
Yes, thanks.  I finally used multi_get and compare the ids. Thanks.
