### ISSUE TITLE
BUG: EP interfers with get_post_type() on CPT archive page

### ISSUE THREAD

**Issue by clemorphy** [10up/ElasticPress#3450]
### Describe the bug

When EP is enabled, WP native function get_post_type is not returning what I expect on a CPT archive page, unless one content of this CPT is indexed with EP.
I had the issue with EP 4.4.1. Upgrading to to 4.5.1 didn't fix it.

### Steps to Reproduce

1. Create a CPT, and publish at least one content with it.
2. Create an archive page for this CPT and dump the result of `get_post_type()`. It should return the CPT name.
3. Install and enable EP without indexing anything. As long as no content of this CPT is indexed in EP, the dump now returns false, and not the CPT name. As soon as a CPT content is indexed in EP, it returns again the CPT name correctly.

The issue is that I don't index some of my CPT, so on their archive page, I don't get a correct value from `get_post_type()`

### WordPress Environment ###
wp_version: 6.2
home_url: http://localhost
site_url: http://localhost
is_multisite: false
theme: mrc2023 ()
plugins: ALS Icons list (0.1), ALS Media Usage (0.1), ALS Private Content (0.1), AuthLDAP (2.4.10), Contact Form 7 (5.6.4), Custom Permalinks (2.4.0), Duplicate Page (4.4), ElasticPress (4.5.1), Elasticpress Autosuggest Endpoint (0.3), Enable Media Replace (3.6.3), HappyFiles Pro (1.7), LH User Taxonomies (1.60), MCE Table Buttons (3.3), Multiple Roles per User (1), Post Types Order (1.9.3.9), ReOrder Posts within Categories (2.9.2), Revisionize (2.3.4), The Events Calendar (6.0.11), Theme Switcha (3.2), User Switching (1.7.0), WP-Polls (2.75.6), wpDataTables (3.3), WP Ultimate CSV Importer (6.0.5), et YIKES Simple Taxonomy Ordering (2.3.4)
revisions: all

### Server Environment ###
php_version: 7.4.22
memory_limit: 40M
timeout: 30

### Site Name — http://localhost ###
post_count: 1
page_count: 6
tribe_events_count: 6
descriptif_produit_count: 17
actualite_count: 7
mise_a_jour_count: 11
reporting_count: 26
chiffres_cles_count: 6
kpis_collecte_count: 3
barometre_count: 2
lien_utile_count: 4
referent_rc_count: 17
espaces_metiers_count: 4
actus_metiers_count: 6
pages_metiers_count: 11
majs_metiers_count: 8
reponses_types_count: 6
emailing_national_count: 3
message_bilan_count: 2
etape_count: 4
actus_pj_ent_count: 4
contacts_diffusion_count: 2 241
numeros_actuals_count: 3
pages_actuals_count: 1
tutoriel_count: 5
webinaire_count: 1
accesbo_count: 2
delaitraitement_count: 3
listepj_count: 2
attachment_count: 147
post_meta_keys: 0
page_meta_keys: 5
tribe_events_meta_keys: 1
descriptif_produit_meta_keys: 10
actualite_meta_keys: 5
mise_a_jour_meta_keys: 4
reporting_meta_keys: 2
chiffres_cles_meta_keys: 2
kpis_collecte_meta_keys: 1
barometre_meta_keys: 2
lien_utile_meta_keys: 1
referent_rc_meta_keys: 4
espaces_metiers_meta_keys: 7
actus_metiers_meta_keys: 3
pages_metiers_meta_keys: 2
majs_metiers_meta_keys: 3
reponses_types_meta_keys: 0
emailing_national_meta_keys: 4
message_bilan_meta_keys: 0
etape_meta_keys: 4
actus_pj_ent_meta_keys: 1
contacts_diffusion_meta_keys: 0
numeros_actuals_meta_keys: 15
pages_actuals_meta_keys: 1
tutoriel_meta_keys: 3
webinaire_meta_keys: 2
accesbo_meta_keys: 2
delaitraitement_meta_keys: 0
listepj_meta_keys: 0
attachment_meta_keys: 0
total-all-post-types: 61
distinct-meta-keys: use_builder, builder, picto_titre, ep_exclude_from_search, icon, desc_prod_builder, seo, boite_outils_liens, picto_produit, intro_affichage, alerte_affichage, alerte_titre, alerte_message, intro_message, cacher_image, validation, email_notif, liste_liens, lien_contenu, nom_document, fichier, image_pole, liste_kpis, chiffre, liste_chiffres, published_at, lien_url, nom, prenom, telephone, email, carousel_max, liste_entrees, hide_from_nav, liste_referents, restreindre_laccs_aux_rles_suivants, restricted_access, full_width, capture, lien_online, stats, objet, description, libelle_cta, statut, lien_cta, date_actu, edito_titre, edito_texte, projets_text, projets_url, metiers_text, metiers_url, liste_contenus, colorset, image_bandeau, edito_image, edito_video, edito_cta_url, edito_cta_label, et video_url

### Settings ###
host: http://mrc_wsl_elastic:9200
index_prefix: 
language: fr_FR
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### localhost-post-1 ###
health: yellow
status: open
index: localhost-post-1
uuid: 66K6ZRgZSuez74JK7rCgRQ
pri: 5
rep: 1
docs.count: 21
docs.deleted: 0
store.size: 492.8kb
pri.store.size: 492.8kb
total_fields_limit: 5000

### 2023/04/19 11:41:06   ###
method: WP Dashboard
is_full_sync: Yes
end_date_time: 2023/04/19 11:41:07  
total_time: 0 heure, 0 minute, 2 secondes
total: 21
synced: 21
skipped: 0
failed: 0
errors: array (
)

### Autosuggest ###
active: true
autosuggest_selector: .ep-autosuggest
endpoint_url: http://localhost/wp-json/elasticpress/autosuggest
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
> Install and enable EP without indexing anything.

@clemorphy Enabling EP without indexing anything is not a behavior we support, after all the plugin _needs_ content to be indexed. 

Did you already try to use the [ep_indexable_post_types](https://10up.github.io/ElasticPress/ep_indexable_post_types.html) and [ep_searchable_post_types](https://10up.github.io/ElasticPress/ep_searchable_post_types.html) filters to exclude those CPT from EP?

**Comment by clemorphy** [comment]
hi @felipeelia 

> Enabling EP without indexing anything is not a behavior we support, after all the plugin needs content to be indexed.

Ok fair enough, let me write the steps in a different way : 

1. Create a CPT, and publish at least one content with it.
2. Create an archive page for this CPT and dump the result of get_post_type(). It should return the CPT name.
3. Install and enable EP and index some content, except the ones from this CPT
4. As long as no content of this CPT is indexed in EP, the dump now returns false, and not the CPT name. As soon as a CPT content is indexed in EP, it returns again the CPT name correctly.

> Did you already try to use the [ep_indexable_post_types](https://10up.github.io/ElasticPress/ep_indexable_post_types.html) and [ep_searchable_post_types](https://10up.github.io/ElasticPress/ep_searchable_post_types.html) filters to exclude those CPT from EP?

I don't really want to exclude those CPT from EP or from the search results. I just need to have a correct return from get_post_type() even if no content of a CPT is indexed (while other CPT have indexed content of course, if I use EP, this is obviously to have some content indexed, but all CPTs don't always have one content indexed).

**Comment by felipeelia** [comment]
Hi @clemorphy,

At that point, you would be in an "out of sync" state. And without EP, if you create a CPT and don't create any content, WordPress core would also return "false" if you call `get_post_type()`.

> if I use EP, this is obviously to have some content indexed, but all CPTs don't always have one content indexed

This is actually not correct, as content is automatically indexed while they are published. If that is not happening in your case, then you have a different problem to tackle.

The `get_post_type()` function needs a post to work, and if no post is found, it can't detect which post type is being used. If you want to get the post type slug in its archive, you should use `get_query_var( 'post_type' );` or the snippet below to get its object (taken from the `post_type_archive_title()` function):

```php
$post_type = get_query_var( 'post_type' );
if ( is_array( $post_type ) ) {
	$post_type = reset( $post_type );
}

$post_type_obj = get_post_type_object( $post_type );
```
