### ISSUE TITLE
elatic sdk for 8.x

### ISSUE THREAD

**Issue by aperez900907** [10up/ElasticPress#3451]
### Is your enhancement related to a problem? Please describe.

is in the roadmap of the plugin development the implementation of the communications and queries to the elastic host throw the official php sdk and support 8.x version?
Thanks!!!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @aperez900907, thanks for asking. Support to 8.x is in our roadmap but we don't have any plans to start using the official php SDK.
