### ISSUE TITLE
cannot run PhraseQuery error

### ISSUE THREAD

**Issue by jzzaj** [10up/ElasticPress#3452]
### Describe your question

Hi

I have disabled word frequency relevance in the mapping which now causes the following error:

`field "post_title" was indexed without position data; cannot run PhraseQuery (phrase=post_title:"ep autosuggest placehold")`

Autosuggest works fine but I would like to fix this error so that it doesn't display. I've modified the autosuggest placeholder query but the error still happens. I've also tried to remove the post_title field from the placeholder query fields and still the same error.
The ElasticPress debugger for this error has no mention of a phrase query or post_title in the fields. I can't find where `phrase=post_title:"ep autosuggest placehold"` is being called from.

Everythings works fine but I'd just like to fix this error. Any advice appreciated. Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @jzzaj, can you please share:

1. How you've disabled word frequency relevance in the mapping
2. The ElasticPress Status Report contents

Thanks

**Comment by jzzaj** [comment]
Thanks felipeelia

I disabled word frequency relevance by adding the line below into the 'ep_post_mapping' filter:

`$mapping["mappings"]["properties"]["post_title"]["index_options"] = "docs";`

Please see below for the ElasticPress status report:

## Failed Queries ##

error: field "post_title" was indexed without position data; cannot run PhraseQuery (phrase=post_title:"ep autosuggest placehold")
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors. 
es_req: POST {{removed}}/_search
query_time: 0.35595893859863
wp_args: array (
  'post_type' => 
  array (
    0 => 'product',
    1 => 'product_variation',
  ),
  'post_status' => 'publish',
  's' => 'ep_autosuggest_placeholder',
  'ep_integrate' => true,
  'posts_per_page' => 10,
  'error' => '',
  'm' => '',
  'p' => 0,
  'post_parent' => '',
  'subpost' => '',
  'subpost_id' => '',
  'attachment' => '',
  'attachment_id' => 0,
  'name' => '',
  'pagename' => '',
  'page_id' => 0,
  'second' => '',
  'minute' => '',
  'hour' => '',
  'day' => 0,
  'monthnum' => 0,
  'year' => 0,
  'w' => 0,
  'category_name' => '',
  'tag' => '',
  'cat' => '',
  'tag_id' => '',
  'author' => '',
  'author_name' => '',
  'feed' => '',
  'tb' => '',
  'paged' => 0,
  'meta_key' => '',
  'meta_value' => '',
  'preview' => '',
  'sentence' => '',
  'title' => '',
  'fields' => '',
  'menu_order' => '',
  'embed' => '',
  'category__in' => 
  array (
  ),
  'category__not_in' => 
  array (
  ),
  'category__and' => 
  array (
  ),
  'post__in' => 
  array (
  ),
  'post__not_in' => 
  array (
  ),
  'post_name__in' => 
  array (
  ),
  'tag__in' => 
  array (
  ),
  'tag__not_in' => 
  array (
  ),
  'tag__and' => 
  array (
  ),
  'tag_slug__in' => 
  array (
  ),
  'tag_slug__and' => 
  array (
  ),
  'post_parent__in' => 
  array (
  ),
  'post_parent__not_in' => 
  array (
  ),
  'author__in' => 
  array (
  ),
  'author__not_in' => 
  array (
  ),
  'search_columns' => 
  array (
  ),
  'cache_results' => false,
  'tax_query' => 
  array (
  ),
  'suppress_filters' => false,
  'ignore_sticky_posts' => false,
  'update_post_term_cache' => true,
  'update_menu_item_cache' => false,
  'lazy_load_term_meta' => true,
  'update_post_meta_cache' => true,
  'nopaging' => false,
  'comments_per_page' => '50',
  'no_found_rows' => false,
  'search_terms_count' => 1,
  'search_terms' => 
  array (
    0 => 'ep_autosuggest_placeholder',
  ),
  'search_orderby_title' => 
  array (
    0 => 'wp_posts.post_title LIKE \'%ep\\\\_autosuggest\\\\_placeholder%\'',
  ),
  'order' => 'DESC',
)
status_code: 500
body: {"from":0,"size":10,"post_filter":{"bool":{"must":[{"terms":{"post_type.raw":["product","product_variation"]}},{"term":{"post_status":"publish"}},{"bool":{"must_not":[{"terms":{"meta.ep_exclude_from_search.raw":["1"]}}]}}]}},"query":{"bool":{"should":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"ep_autosuggest_placeholder","type":"cross_fields","fields":["post_title^1","terms.product_cat.name^1","terms.pa_colour.name^1","terms.ic_col.name^1","terms.pa_capacity.name^1","terms.pa_case.name^1"],"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"product"}}]}},{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"ep_autosuggest_placeholder","type":"cross_fields","fields":["post_title^1","post_content^1","post_excerpt^1","post_author.display_name^1"],"operator":"and"}}]}}],"filter":[{"match":{"post_type.raw":"product_variation"}}]}}]}},"sort":[{"_score":{"order":"desc"}}]}
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'illegal_state_exception',
        'reason' => 'field "post_title" was indexed without position data; cannot run PhraseQuery (phrase=post_title:"ep autosuggest placehold")',
      ),
    ),
    'type' => 'search_phase_execution_exception',
    'reason' => 'all shards failed',
    'phase' => 'query',
    'grouped' => true,
    'failed_shards' => 
    array (
      0 => 
      array (
        'shard' => 0,
        'index' => '{{removed}}',
        'node' => '{{removed}}',
        'reason' => 
        array (
          'type' => 'illegal_state_exception',
          'reason' => 'field "post_title" was indexed without position data; cannot run PhraseQuery (phrase=post_title:"ep autosuggest placehold")',
        ),
      ),
    ),
    'caused_by' => 
    array (
      'type' => 'illegal_state_exception',
      'reason' => 'field "post_title" was indexed without position data; cannot run PhraseQuery (phrase=post_title:"ep autosuggest placehold")',
      'caused_by' => 
      array (
        'type' => 'illegal_state_exception',
        'reason' => 'field "post_title" was indexed without position data; cannot run PhraseQuery (phrase=post_title:"ep autosuggest placehold")',
      ),
    ),
  ),
  'status' => 500,
)

## WordPress ##

### WordPress Environment ###
wp_version: 6.2
home_url: {{removed}}
site_url: {{removed}}
is_multisite: false
parent_theme: GeneratePress (3.3.0)
plugins: Classic Editor (1.6.3), Debug Bar (1.1.4), Debug Bar ElasticPress (3.0.0), GP Premium (2.3.1), WooCommerce (7.5.1), WP Mail SMTP (3.7.0), WP Show Posts (1.1.4) and YITH WooCommerce Wishlist (3.19.0)
revisions: 0

### Server Environment ###
php_version: 8.2.4RC1
memory_limit: 256M
timeout: 120



## ElasticPress ##

### Settings ###
host: {{removed}}
index_prefix: 
language: en_GB
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30



## Elasticsearch Indices ##

### {{removed}} ###
health: green
status: open
index: {{removed}}
uuid: {{removed}}
pri: 1
rep: 0
docs.count: 4502
docs.deleted: 0
store.size: 10.6mb
pri.store.size: 10.6mb
total_fields_limit: 5000



## Last Sync ##

### 2023/04/19 8:55:52 pm ###
method: WP Dashboard
is_full_sync: Yes
end_date_time: 2023/04/19 8:59:26 pm
total_time: 0 hours, 3 minutes, 34 seconds
total: 4502
synced: 4502
skipped: 0
failed: 0
errors: array (
)



## Feature Settings ##

### Autosuggest ###
active: true
autosuggest_selector: .autosuggest
endpoint_url: {{removed}}
force_inactive: false
trigger_ga_event: 0

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### WooCommerce ###
active: true
force_inactive: false
orders: 0

**Comment by felipeelia** [comment]
Hey @jzzaj, I could not reproduce that error. Do you mind sharing with us all the custom codes you have? Thanks

**Comment by jzzaj** [comment]
Hi felipeelia

I also cannot reproduce this on a test system without any additional custom code. I'll look into it further and find what additional code is causing it and then let you know.

Thanks
