### ISSUE TITLE
Sorting by multiple meta fields and swedish chars

### ISSUE THREAD

**Issue by klingberg** [10up/ElasticPress#3453]
### Describe your question

Hi!

I have trouble with sorting my custom post type (using Version 4.5.2) by two meta fields (first_name and last_name).
With this simple alteration I can manage to sort my post type on last name and sorting by swedish chars is working as expected.

```
add_filter('rest_contact_query', function($args, $request) {
    $args['orderby'] = 'meta_value';
    $args['meta_key'] = 'last_name';

    return $args;
}, 10, 2 );
```

When I try to add sorting by two meta fields swedish chars is no longer sorted in the correct order ("å" is treated as "a" etc).

```
add_filter('rest_contact_query', function($args, $request) {
    $args['meta_query'] = array(
        'relation' => 'AND',
        'first_name_clause' => array(
            'key'     => 'first_name',
            'compare' => 'EXISTS',
        ),
        'last_name_clause' => array(
            'key'     => 'last_name',
            'compare' => 'EXISTS',
        ),
    );

    $args['orderby'] = array(
        'last_name_clause' => 'ASC',
        'first_name_clause' => 'ASC',
    );

    return $args;
}, 10, 2 );
```

By changing the orderby argument to the code below the sorting of swedish chars is correct but for some reason the last 20 posts just seem to fall out of the expected sorting order and end up randomly at the end of the list.

```
$args['orderby'] = array(
    'last_name_clause.keyword' => 'ASC',
    'first_name_clause.keyword' => 'ASC',
);

```

I have also tried to change the collation on the wp_postmeta table but with no better result.

Not sure if this is a bug or if it's just me doing things incorrectly? If you have any suggestions on how to solve this problem it would be greatly appreciated!

Best regards!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @klingberg,

I think the reason you are getting the incorrect results is that ElasticPress has a [known bug](https://github.com/10up/ElasticPress/issues/3369) when ordering by the named meta query, thus the query failed and fell back to WordPress. Try to alter the `orderby`  to this and let us know if that works.


```
$args['orderby'] = array(
    'meta.last_name.value.sortable' => 'ASC',
    'meta.fist_name.value.sortable' => 'ASC',
);
```


Also, you can use the [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugin to debug the Elasticsearch queries. Through this, you can easily find out what’s wrong with the query. You can learn more [here](https://10up.github.io/ElasticPress/tutorial-debugging.html).

Regards,
Burhan
