### ISSUE TITLE
Partial Match with Phrase

### ISSUE THREAD

**Issue by aloisejulian** [10up/ElasticPress#3456]
### Describe your question

I am looking a way of having an exact match but also a partial:
I am using:

- Wordpres 6
- ElasticPress 4.5.2
- ElastiCPress Labs With Search Algorithm Version 3.5
- I deactivated the snowball filter

With all this, the exact match is working fine but for example:

if I search for SUN I didn't get SUNflower or SUNshine
if I search for FLOWER I didn't get the result of sunFLOWER or FLOWEReist

So, I tried to activate ngram, not successful... But I read that ngram will not resolve the problem of searching back, such as sunFLOWER. So, I am trying to use regex like title => '.*' . $args['s'] . '.*' but not successfully:

`add_filter( 'ep_formatted_args', function( $formatted_args, $args ) {
    // Verificar si se está realizando una búsqueda
    if ( ! empty( $args['s'] ) ) {
        // Agregar la opción de búsqueda con regex a la consulta
        $formatted_args['query']['regexp']['post_title'] = '.*' . $args['s'] . '.*';
    }
    return $formatted_args;
}, 10, 2 );`

OR

`$formatted_args['query']['function_score']['query']['bool']['should'][] = [
			'regexp' => [
				"post_title" => '.*' . $args['s'] . '.*',
			]
		];`
		
Any suggestion to resolve my problem?
THANKS!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @aloisejulian, any reason why you deactivated the snowball filter? Also, do you mind sharing your ElasticPress Report Status with us? Thanks.

**Comment by felipeelia** [comment]
FWIW, we've worked with the user via a Zendesk Ticket, and tweaking the ngram field usage solved the issue.

**Comment by oscarssanchez** [comment]
Just giving the solution we used here re: ngram usage:


 function add_gram_analyzer( $mapping ) {
$mapping['settings']['analysis']['analyzer']['julian_analyzer'] = array(
'type'      => 'custom',
'tokenizer' => 'julian_tokenizer',
'filter'    => array(
'lowercase'
),
);

$mapping['settings']['analysis']['tokenizer']['julian_tokenizer'] = array(
"type" => "ngram",
"min_gram" => 3,
"max_gram" => 4,
"token_chars" => array(
"letter",
"digit"
)
);

$mapping['mappings']["properties"]["post_title"]['analyzer'] = "julian_analyzer";

return $mapping;
}

add_filter( 'ep_post_mapping', 'add_gram_analyzer' );
