### ISSUE TITLE
BUG: Indexing job stalls and becomes orphaned if ep_post_sync_args contains PHP error

### ISSUE THREAD

**Issue by dwatts3624** [10up/ElasticPress#3458]
### Describe the bug

It looks like the CLI and UI don't have a good way to handle certain PHP errors when using the `ep_post_sync_args` filter.  Warnings seem to go through fine and it does feed back errors from ES correctly but if the problem is actually in PHP while building up the bulk payload the sync job will stall and become orphaned.

As an example, create the filter with an obvious PHP error:
```php
add_filter( 'ep_post_sync_args', function( $post_args, $post_id ) {

  $post_args['test'] = undefined_function();

  return $post_args;
}, 10, 2 );
```

Then try running the CLI command: 
`wp elasticpress sync --show-errors`

This will echo out `Success: Indexing posts…` and then the terminal will just return but that command leaves the transient in place so it thinks the sync is still running.  I have to run `wp elasticpress clear-sync` to try again.

A similar thing happens in the UI where the `admin-ajax.php` indexing call gets interrupted and returns nothing.
```sh
curl 'REDACTED/wp-admin/admin-ajax.php' \
  REDACTED \
  --data-raw $'------WebKitFormBoundaryoraXeGS3vIP73SyV\r\nContent-Disposition: form-data; name="action"\r\n\r\nep_index\r\n------WebKitFormBoundaryoraXeGS3vIP73SyV\r\nContent-Disposition: form-data; name="put_mapping"\r\n\r\n0\r\n------WebKitFormBoundaryoraXeGS3vIP73SyV\r\nContent-Disposition: form-data; name="nonce"\r\n\r\n53e5743da9\r\n------WebKitFormBoundaryoraXeGS3vIP73SyV--\r\n' \
  --compressed
```

Enabling debugging via display and log showed no errors.  I tried adding try/catches to my code and the EP source directly with no luck.

Ultimately I needed to get this release out so I found the error through a process of elimination directly on the server since the code was working fine locally (the error had to do with data on production that was different on my local and my document customizations were producing PHP errors as a result).

Hoping a fix here could save someone else some time down the line since I just spent 4 hours commenting code and re-running the sync.  Not your teams' fault.  The plugin is great!  The error was mine.  But some error reporting here would go a long way!

### Steps to Reproduce

1. Create `ep_post_sync_args` filter that will produce a PHP error
2. Run `wp elasticpress sync --show-errors` via the CLI or run sync in the UI
3. The sync should fail and become orphaned with no errors logged anywhere

### Environment information

- ElasticPress.io for ES hosting
- ElasticPress 4.5.2
- WordPress 6.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @dwatts3624,


I tried the example code you shared, and ElasticPress does show the error message. ElasticPress has a solution that utilizes the error_get_last [function](https://github.com/10up/ElasticPress/blob/develop/includes/classes/IndexHelper.php#L1290) to capture and display the specific details of the error. By leveraging this function, we retrieve the PHP error information and display it in the CLI. Please see the attached screenshot.

![image](https://github.com/10up/ElasticPress/assets/7139602/0a0afe0e-f232-4181-b754-66e20fb2df1e)


Regarding the sync from the admin panel, the error message is conveniently accessible in the browser’s console, presented in JSON format. Additionally, you can also view the error within the response of the Ajax request.


Regards,
Burhan
