### ISSUE TITLE
BUG: Dist folder removed??

### ISSUE THREAD

**Issue by izzygld** [10up/ElasticPress#3459]
### Describe the bug

Latest version of the plugin the entire `/dist` folder was removed.

was this intentionally?

causing lots of 404 error paths

### Steps to Reproduce

Install latest plugin,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @izzygld, how did you install the latest version of the plugin? Did you get it from wordpress.org or did you try and download it from GitHub?

**Comment by izzygld** [comment]
via `composer 10up/elasticpress`

**Comment by burhandodhy** [comment]
Hi @izzygld,

My guess is that the issue you are facing is related to the **[prefer-stable](https://getcomposer.org/doc/04-schema.md#prefer-stable)** setting in your `composer.json` file. It seems that prefer-stable is not set to true, which could be causing Composer to attempt to download an unstable version of ElasticPress from the develop branch.

The develop branch has unstable code that is purely used for development purposes and is not meant to be used in production. I recommend you set prefer-stable to true in your composer.json file. After making this change, run `composer require 10up/elasticpress` to ensure that Composer uses the stable version of ElasticPress.

If you still want to use the `develop` branch, then you need to run `run install && npm run build` commands to generate the `dist` directory.

Regards
Burhan
