### ISSUE TITLE
BUG: Bulk Indexing a Custom Indexable

### ISSUE THREAD

**Issue by stevesearer** [10up/ElasticPress#3460]
### Describe the bug

We have a custom Indexable that we use to add GA4 Event data to Elasticsearch for analytics reports we run:

```
class EventIndexable extends ElasticPress\Indexable {
  public function __construct() {
    $this->slug = 'event';
    $this->labels = [
      'singular' => __( 'Event', 'textdomain' ),
      'plural' => __( 'Events', 'textdomain' ),
    ];
  }

  public function get_type() {
    return 'event'; 
  }

  public function query_db( $args ) {
    return [];
  }

  public function prepare_document( $event_data ) {
    $document = [
    	'ID' => $event_data['event_id'],
    	'event_id' => $event_data['event_id'],
        'report_id' => $event_data['report_id'],
    ];

    return $document;
  }

}
```

So far we have successfully been able to index individual documents using:

```
$document = $indexable->prepare_document( $event_data );
$result = $indexable->index( $document );
```

However, when we try to use `$indexable->bulk_index( $documents );` with properly formatted JSON we receive the error below:

`{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}`

When we error_log($documents) it logs JSON, but it seems that our use of bulk_index() isn't quite working properly. When we error_log($body) within ElasticPress/includes/classes/Elasticsearch.php it is indeed empty :

```
$request_args = array(
	'method'  => 'POST',
	'body'    => $body,
	'timeout' => apply_filters( 'ep_bulk_index_timeout', 30 ),
);
```

In a different project, we have successfully used bulk_index() by giving it IDs:

`\ElasticPress\Indexables::factory()->get( 'post' )->bulk_index($ids);`

So I'm thinking the issue lies with passing incorrect data (JSON instead of ids) to bulk_index().

There isn't much information out there about custom Indexables or bulk_index, so I figured I would jump in here to see if anyone has thoughts.

### Steps to Reproduce

1. Create a custom Indexable
2. Send some JSON using bulk_index()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @stevesearer,

ElasticPress has two classes with that same method name: [Elasticsearch::bulk_index()](https://github.com/10up/ElasticPress/blob/4.5.2/includes/classes/Elasticsearch.php#L1083) and [Indexable::bulk_index()](https://github.com/10up/ElasticPress/blob/4.5.2/includes/classes/Indexable.php#L329).

While the Indexable's method accepts an array of IDs, the Elasticsearch one accepts a Newline Delimited JSON object, reflecting [what Elasticsearch expects to receive](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-bulk.html). With that said, if you are trying to communicate to Elasticsearch directly, you should send a ndjson and use `Elasticsearch::factory()->bulk_index( $index_name, $indexable_slug, $ndjson );`
