### ISSUE TITLE
BUG: Sync not working properly with multisite

### ISSUE THREAD

**Issue by javier-orellana-pro** [10up/ElasticPress#3471]
### Describe the bug

The bug has been detected with multisite using Multilingualpress although it might occur in other multisite environment.

Multilingualpress provides a mechanism to replicate a post  from one site to other sites. When we are editing a post, we select one or more sites where the current post will be copied. When the replication process is launched, it changes the context to the target site and order the creation/update of the post. 

In this very moment, when the update operation is triggered, if the post is allowed to be indexed, ElasticPress stores the post ID in a queue in order to be processed. 

What happens? the queue does not store any data indicating which site each ID belongs to. This produces a queue with several post IDs belonging to different sites, but all of them will be processed against the same site. This way, Elastic will index records that should not be indexing.

### Steps to Reproduce

1. Go to the edit page of a post (e.g. Site 1 - ID 21259)
2. Using multilingualpress, select one site where the current post will be copied (e.g Site1 to Site3)
3. Update the post

The current post (21259) will be updated in site 1. This ID will be stored in a queue.
The target post (20782) will be created in the site 3 and this ID will be stored in a queue.

The queue will process the ID 21259 and 20782, both in site 1. If 20782 is an attachment, it will be indexed. But the post 20782 of site 3 will not be synced.

### WordPress and ElasticPress information

Tested in:
ElasticPress 4.3.1 and 4.5.2
MultilingualPress 4.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by javier-orellana-pro** [comment]
Hi @burhandodhy. How can I help you?

**Comment by felipeelia** [comment]
Closed by #3689.
