### ISSUE TITLE
Enhancement: Default methods for Facet Block class 

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#3472]
### Is your enhancement related to a problem? Please describe.

I've found similar blocks of code like the following in the Block classes from different facets:

	public function check_facets_meta_rest_permission() {
		if ( ! current_user_can( 'edit_theme_options' ) ) {
			return new \WP_Error( 'ep_rest_forbidden', esc_html__( 'Sorry, you cannot view this resource.', 'elasticpress' ), array( 'status' => 401 ) );
		}

		return true;
	}

In other facet types that seem to be repeating the same code. I think we can improve this by having an abstract Block class that can be extended. If the rest permissions need to change the method can be redeclared without a problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
This could also be extended to other classes/methods like Renderer

    protected function order_values( array $values, string $orderby = 'count', $order = 'desc' ) : array {
		    $orderby = strtolower( $orderby );
		    $orderby = in_array( $orderby, [ 'name', 'count' ], true ) ? $orderby : 'count';
    
		    $order = strtoupper( $order );
		    $order = in_array( $order, [ 'ASC', 'DESC' ], true ) ? $order : 'DESC';
    
		    $values = wp_list_sort( $values, $orderby, $order, true );
    
		    $selected = [];
		    foreach ( $values as $key => $value ) {
			    if ( $value['is_selected'] ) {
				    $selected[ $key ] = $value;
				    unset( $values[ $key ] );
			    }
		    }
		    $values = $selected + $values;
    
		    return $values;
	    }

**Comment by itsajay1029** [comment]
Can I work on this @oscarssanchez ?

**Comment by oscarssanchez** [comment]
Hey @itsajay1029 that would be great thanks!
