### ISSUE TITLE
I need to add a radio button under search

### ISSUE THREAD

**Issue by Swaraj088** [10up/ElasticPress#3474]
### Describe your question

I am trying to add a radio button under search so the user can choose between an Exact match or a Broad match. In my elastic search file, I have added: 

`/**
 *  Sort results by Exact match
 */
function lmp_set_to_exact( $formatted_args, $args ) {
    if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
        $formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
        $formatted_args['query']['bool']['must'][0]['multi_match']['operator'] = 'AND';
        unset( $formatted_args['query']['bool']['should'] );
        unset( $formatted_args["query"]["bool"]["must"][0]["multi_match"]["type"] );
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'lmp_set_to_exact', 10, 2 );`

I want to run the above function only when the user has selected the Exact Match, can you please help me with what I can do? thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @Swaraj088,

Thank you for reaching out to us regarding your custom code on GitHub. Upon reviewing it, we have noticed that you need to incorporate a check that ensures your code only executes when there is an exact match.

The check would look like this:

```
function lmp_set_to_exact( $formatted_args, $args ) {
    // Check if the user has selected the Exact Match option
    if ( isset( $_GET['search_type'] ) && $_GET['search_type'] === 'exact' ) {
        // Your code here
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'lmp_set_to_exact', 10, 2 );
```


Also, we do not provide direct assistance for custom code. Our support services primarily focus on assisting users with bugs in our plugin and related functionalities.

If you would like to discuss your issue with an ElasticPress expert, we recommend checking out the ElasticPress consultancy service at https://www.elasticpress.io/elasticpress-consulting/.

Regards,
Burhan
