### ISSUE TITLE
same site - same index - different domain's

### ISSUE THREAD

**Issue by dnikola** [10up/ElasticPress#3475]
### Describe your question

Hello people,

we have one wp instance where it is served like www.domain.tld for desktop and m.domain.tld for mobile version of site.
with one of last updates we noticed that using mobile version is not using ElasticSearch and it was throwing an error in debug bar about field set. 
It looks like indexes are created per domain 
domaintld-posts-1
mdomaintild-posts-1
and the rest for tax and comments..

what we have tried to do is to define a exact index using filters 
http://10up.github.io/ElasticPress/ep_index_name.html
- the problems is giving exact name will not work for taxonomies, comments, using wildcard wont work...
http://10up.github.io/ElasticPress/ep_index_prefix.html
- the problem is that that it add desired word in front of index name so we have names like 
ourword-domaintld-posts-1
ourword-mdomaintild-posts-1

Any possible solution to use same index for two different domains?

Regards

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @dnikola,

It appears that you have implemented the appropriate filter to modify the index names, but I recommend reviewing your code to ensure everything is set up correctly. I’m sharing the example code of how the filter would like to be implemented.

```
add_filter( 'ep_index_name', function(  $index_name, $blog_id, $indexable ) {

	return $indexable->slug . '_index';
}, 10, 3 );

```

Just remember that after making the code changes, you will need to resync all the content to ensure the modifications take effect.

Regards,
Burhan
