### ISSUE TITLE
Facets not shown on Dokan vendor page

### ISSUE THREAD

**Issue by nicolas-wl** [10up/ElasticPress#3488]
### Describe your question

I'm trying to integrate EP with Dokan. My facets are not showing up on the store pages.
I've already checked if EP is actually altering the WP_query and it does.

```
function custom_ep_integrate_on_vendor_store($query)
{
    if ($query->is_main_query() && dokan_is_store_page()) {
        $query->set('ep_integrate', true);
    }
}
add_action('pre_get_posts', 'custom_ep_integrate_on_vendor_store', 100);
```
UPDATE: 
The Dokan store pages are not archives hence facets won't work.
I tried to bypass this behaviour with the `ep_is_facetable` filter but this results in a WOD

```
add_filter('ep_is_facetable', array($this, 'bypass_dokan'), 10, 2);
function bypass_dokan($bypass, $query){
      if (dokan_is_store_page()) {
            return true;
      }
      
      return $bypass;
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @nicolas-wl, a WOD usually means a fatal error in PHP or some code calling `die()` in the middle of the process. Do you mind sharing what is the error you get in your error logs, if any? Thanks
