### ISSUE TITLE
BUG: WooCommerce _sale_price not in autosuggest

### ISSUE THREAD

**Issue by nicolas-wl** [10up/ElasticPress#3496]
### Describe the bug

Autosuggest response is missing `_sale_price` meta. 
There's only `_sale_price_dates_from` and `_sale_price_dates_to`

When a product is discounted `_price` is 'overridden' with the actual sale price and there's no way to get the original price of the product. (which i want to show in the autosuggest box)

<img width="828" alt="Screenshot 2023-06-12 at 22 06 32" src="https://github.com/10up/ElasticPress/assets/59285722/95a6c81f-02a3-42d1-b9c5-ae1eda9bb2d5">

### Steps to Reproduce

1. Type any product name into your autosuggest box
2. Check the EP endpoint response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Hi @nicolas-wl 

I could not reproduce this, I do get back _sale_price, _price and _regular_price just fine from the Autosuggest response. Would you mind testing again with latest EP version and Woocommerce feature activated?

Thanks!
