### ISSUE TITLE
BUG: attempting to conduct a search for posts with bracket in the title results in instant Results not displaying brackets

### ISSUE THREAD

**Issue by tomi10up** [10up/ElasticPress#3497]
### Describe the bug

When attempting to conduct a search for posts with bracket in the title, I've encountered an issue with the Instant Results feature.

### Steps to Reproduce

The steps to reproduce the issue are as follows:

Create and save a post with the title "Cannon Shot (Far)".
Conduct a search for "Cannon Shot".
Clear the suggestion presented by the Instant Results feature.
Upon performing these steps, the search results unexpectedly alter.

The results change Cannon Shot (Far) to Cannon Shot (Far

**The closing bracket becomes missing.

### Screenshots, screen recording, code snippet

[0398ff31-4c55-4fd1-912e-c06cab09e1df.webm](https://github.com/10up/ElasticPress/assets/108893208/eaa2005c-b80d-4adb-8d20-3f87a2dfecc9)

### WordPress and ElasticPress information

`
### wp-core ###

version: 6.2.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/bigsur/Local Sites/elasticpress/app/public
wordpress_size: 129.66 MB (135962564 bytes)
uploads_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/uploads
uploads_size: 6.46 MB (6769713 bytes)
themes_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/themes
themes_size: 37.56 MB (39384693 bytes)
plugins_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/plugins
plugins_size: 83.37 MB (87416631 bytes)
database_size: 2.77 MB (2899968 bytes)
total_size: 259.81 MB (272433569 bytes)

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.3 (latest version: 1.4)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, wp-block-styles, editor-style
theme_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/themes/twentytwentytwo
auto_update: Disabled

### wp-themes-inactive (5) ###

Konte: version: 2.2.3, author: UIX Themes, Auto-updates disabled
Shopwise: version: 1.6.7, author: KlbTheme (Sinan ISIK), Auto-updates disabled
Storefront: version: 4.2.0, author: Automattic (latest version: 4.3.0), Auto-updates disabled
Twenty Twenty-One: version: 1.7, author: the WordPress team (latest version: 1.8), Auto-updates disabled
Twenty Twenty-Three: version: 1.0, author: the WordPress team (latest version: 1.1), Auto-updates disabled

### wp-plugins-active (3) ###

ElasticPress: version: 4.6.0, author: 10up, Auto-updates disabled
FacetWP: version: 4.1.8, author: FacetWP, LLC (latest version: 4.2.1), Auto-updates disabled
WP Reset: version: 1.97, author: WebFactory Ltd, Auto-updates disabled

### wp-plugins-inactive (9) ###

Ajax Search Pro: version: 4.25.1, author: Ernest Marcinko, Auto-updates disabled
Debug Bar: version: 1.1.4, author: wordpressdotorg, Auto-updates disabled
Debug Bar ElasticPress: version: 3.0.0, author: 10up, Auto-updates disabled
Disable Gutenberg: version: 2.9, author: Jeff Starr, Auto-updates disabled
ElasticPress Labs: version: 2.1.0, author: 10up, Auto-updates disabled
Elementor: version: 3.12.0, author: Elementor.com (latest version: 3.13.4), Auto-updates disabled
Konte Addons: version: 2.1.7, author: UIX Themes, Auto-updates disabled
SearchWP: version: 4.0.18, author: SearchWP, Auto-updates disabled
WooCommerce: version: 7.3.0, author: Automattic (latest version: 7.8.0), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-46 Q16 x86_64 5ef3d4d66:20220816 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 32 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 32 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: Unable to determine
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 22.3.0 x86_64
httpd_software: Apache/2.4.43 (Unix)
php_version: 8.1.9 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 512M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.84.0 (SecureTransport) OpenSSL/1.1.1q
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.1.9
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content
WP_PLUGIN_DIR: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### ep-last-sync ###

method: WP Dashboard
is_full_sync: Yes
start_date_time: 2023/06/15 4:50:05 pm
end_date_time: 2023/06/15 4:50:18 pm
total_time: 0 hours, 0 minutes, 13 seconds
total: 3
synced: 3
skipped: undefined
failed: undefined
errors: 

### epio-autosuggest ###

post-types: post and page
post-status: publish
search-fields: post_title, post_excerpt, and post_content
returned-fields: ''

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
FWIW, if there is no search term and that post is returned by Elasticsearch, it comes without that last `)` in the highlight section:

```json
{
    ...
    "hits": {
        ...
        "hits": [
            ...
            {
                ...
                "_source": {
                    ...
                    "post_title": "Cannon Shot (Far)",
                    ... 
                },
                "highlight": {
                    "post_title": [
                        "Cannon Shot (Far"
                    ],
                    "post_content_plain": [
                        ...
                    ]
                }
            }
        ]
    },
    ...
}
```

**Comment by oscarssanchez** [comment]
The problem seems to be related to the highlighter type. Changing it to unified seems to resolve this issue.
