### ISSUE TITLE
BUG: Yoast Search Crawl Optimization Breaks Search Results

### ISSUE THREAD

**Issue by mikezielonka** [10up/ElasticPress#3504]
### Describe the bug

Yoast site search crawl settings cause poor results

https://yoast.com/features/crawl-settings/

### Steps to Reproduce

Enable yoast's search optimization features under settings (its now in the free version).

Re-index the content.  The results will no longer be accurate 

Turn the search index optimizations features off and re-index and its back to normal.

### Screenshots, screen recording, code snippet

![Screenshot by Dropbox Capture](https://github.com/10up/ElasticPress/assets/1565502/c203ac3a-280f-46a3-b907-504fc84d391a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@mikezielonka do you mind giving specific examples of what you are seeing as a bug? I went through the steps you shared but the results remained the same. Thanks

**Comment by mikezielonka** [comment]
Just to confirm it still happens on my cake school dot com which uses yoast premium (but its a free feature now).  This is a customer of mine so if access is needed, happy to help with that. 

enabled the options in yoast

![Screenshot by Dropbox Capture](https://github.com/10up/ElasticPress/assets/1565502/235a6fcd-2eab-44a7-b5a4-f9a6453d3fa7)

re-synced 

![Screenshot by Dropbox Capture](https://github.com/10up/ElasticPress/assets/1565502/509d1f07-cba4-46dd-a63e-d891c73ab3e9)

Results look good.  I now can't duplicate it :(   Since I reported it the site had updates ran, which is the 1 thing that changed.

I'll leave the yoast settings on and check again in the morning.

**Comment by felipeelia** [comment]
Closing this one out @mikezielonka as we talked about it and that was not reproducible anymore. Thanks!
