### ISSUE TITLE
BUG: Page appearing in CPT more_like query

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#3505]
### Describe the bug

Our site uses a WP_Query instance to retrieve related posts for a custom post type. We don't use the new helper function, but our WP_Query args are setup like so:

```
            $args = array(
                'post_type' => 'mycpt',
                'post_status' => 'publish',
                'more_like' => $post_id,
                'posts_per_page' => 4,
                'ep_integrate' => true,
                'ignore_sticky_posts' => true,
                'orderby' => 'relevance',
            );
```
This worked perfectly up through version 4.4.1. As of version 4.5.0, we are getting an errant page appearing in the query results. The query is structured specifically to only include `mycpt` but there is a page being returned. I inspected the WP_Query object, and indeed there is a page and its ID appearing in the list, despite the query arg restricting it to `mycpt`.

I've also tried an `orderby` parameter of `_score` giving the same result.

### Steps to Reproduce

Run a custom WP_Query with more_like and ep_integrate, where that query restricts to only a specific custom post type. Do this in version 4.4.1 and compare it to 4.5.0. From 4.5.0 forwards, pages can be included in the more_like query results.

Deleting and resyncing the index does not fix this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @kevinlisota,

Can you please install the [ElasticPress Debug Bar Plugin](https://elasticpress.zendesk.com/hc/en-us/articles/16670678802189-Debugging), visit the page where the query is being sent, and share with us the contents of the EP Debug Bar panel? Thanks

**Comment by kevinlisota** [comment]
Here you go. The more_like returns 4 query results, as instructed, but one of the four is a page, not the CPT mandated by WP_Query parameters. This starts occurring after version 4.4.1, and still exists in version 4.6.0
[## Queries info ##.zip](https://github.com/10up/ElasticPress/files/11849322/Queries.info.zip)

**Comment by felipeelia** [comment]
Hi @kevinlisota, looking at that query it does not seem to be returning any page. It returns 4 workshops (40, 13163, 15031, and 15025.) I see ID #40 really looks like a page -- actually the homepage -- but the post_type returned is workshops, as you can see.

If you go to https://muenchworkshops.com/wp-admin/post.php?post=40&action=edit and that is really a page, it is probably related to some other code you might be running. You could try to re-save it and/or run a full sync. If any of that works, you'll need to disable all your plugins, activate a default theme, and enable them back one by one (running syncs in between) to see what could be triggering this issue.

I'll close the issue for now, but if you have the chance to figure out what is going on, please come back to us as it could help people with similar problems. Thanks!
