### ISSUE TITLE
BUG: Sync with failed objects (Password protected MS Office Documents) is incomplete in 4.6.0

### ISSUE THREAD

**Issue by wildberrylillet** [10up/ElasticPress#3510]
### Describe the bug

Password protected content, for example XLSX files, are leading to incomplete syncs.

This error was probably introduced in 4.0.0, 3.6.6 is not affected

Elasticsearch generates the following error:
`:{"type":"parse_exception","reason":"Error parsing document in field [_ingest._value.data]","caused_by":{"type":"encrypted_document_exception","reason":"Unable to process: document is encrypted"}}}},{"index":{"_index":"xxx-post-1","_type":"_doc","_id":"159873","status":400,"error":{"type":"parse_exception","reason":"Error parsing document in field [_ingest._value.data]","caused_by":{"type":"encrypted_document_exception","reason":"Unable to process: document is encrypted"}}}}]},{"took":0,"ingest_took":73,"errors":true,"items":[{"index":{"_index":"xxx-post-1","_type":"_doc","_id":"159872","status":400,"error":{"type":"parse_exception","reason":"Error parsing document in field [_ingest._value.data]","caused_by":{"type":"encrypted_document_exception","reason":"Unable to process: document is encrypted","caused_by":{"type":"encrypted_document_exception","reason":"document is encrypted, password is invalid - use Biff8EncryptionKey.setCurrentUserPasswort() to set password before opening"}}}}}]}`

ElasticPress doesn't handle this error correctly, it does not process the next batch, but repeatedly processes the batch with the password protected content.

### Steps to Reproduce

1. prepare a wordpress content store with 1000 objects
2. add a password protected MS Office document to the content store
3. enable document indexing
4. change batch size to 500
5. start the sync

The sync completes, but only the last 500 documents are indexed, they are processed twice

### Screenshots, screen recording, code snippet

Sync is "stuck" on failed objects, leading to an incomplete index, because it repeatedly processes the batch with failed objects
![image](https://github.com/10up/ElasticPress/assets/16671282/a96b14f8-8b16-409f-bf07-04a6fe7d15cb)

After applying the following fix to Indexhelper.php: index_next_batch() ...
![image](https://github.com/10up/ElasticPress/assets/16671282/1110f091-bf7c-45c2-8aa6-bb8a03c4dc69)

... it seems to be working again.
![image](https://github.com/10up/ElasticPress/assets/16671282/41a275bf-a87b-40e9-8a19-20d7e4433709)

### WordPress Environment ###
wp_version: 5.9.7
is_multisite: false
parent_theme: Twenty Fifteen (3.4)
plugins: ElasticPress (4.6.0)
revisions: all

### Server Environment ###
php_version: 7.4.33
memory_limit: 1024M
timeout: 120

### xxx ###
post_count: 0
page_count: 10.034
attachment_count: 25.332
post_meta_keys: 0
page_meta_keys: 10
attachment_meta_keys: 1
total-all-post-types: 10

### Settings ###
host: http://localhost:9200
index_prefix: 
language: xx_xx
per_page: 500
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @sebastianhong,

ElasticPress will try to process failed documents 3 times for syncs started via dashboard and only once for syncs started via WP-Dashboard (it is possible to change that using the [ep_index_batch_attempts_number](https://10up.github.io/ElasticPress/ep_index_batch_attempts_number.html) filter.)

In your case, what does happen after the error is repeated 3 times? Also, would it be possible for you to give it a try using the WP-CLI, so we can compare results? Thanks

**Comment by wildberrylillet** [comment]
The full log for the sync via dashboard:
`
Starting delete and sync…
Indexing posts…
Mapping sent
Processed posts 0 - 500 of 35366. Last Object ID: 636443
Processed posts 500 - 1000 of 35366. Last Object ID: 580045
Processed posts 1000 - 1500 of 35366. Last Object ID: 469259
Processed posts 1500 - 2000 of 35366. Last Object ID: 170091
Processed posts 2000 - 2500 of 35366. Last Object ID: 163993
Processed posts 2500 - 3000 of 35366. Last Object ID: 161883
Processed posts 3000 - 3500 of 35366. Last Object ID: 160888
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159874 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159873 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159872 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
159871 (Post): [parse_exception] Error parsing document in field [_ingest._value.data]
Number of posts index errors: 256
Sync complete
`
The batch window 3500-4000 contains the faulty documents.
This window is indexed 64 times.
Afterwards the sync completes, even thought there are about 32K unprocessed documents.

This index is incomplete, it should be about 35K documents.
![image](https://github.com/10up/ElasticPress/assets/16671282/3f0341b5-32d9-4ade-af70-cbb394bdb918)


Sorry, I tried the wp-cli, but it failed to connect to the EP_HOST.

**Comment by wildberrylillet** [comment]
after setting the env:
`set no_proxy=127.0.0.1`
the wp-cli works.

index over cli works as expected!

`
Success: Indexing posts…
Processed posts 0 - 500 of 35366. Last Object ID: 636443
Processed posts 500 - 1000 of 35366. Last Object ID: 580045
Processed posts 1000 - 1500 of 35366. Last Object ID: 469259
Processed posts 1500 - 2000 of 35366. Last Object ID: 170091
Processed posts 2000 - 2500 of 35366. Last Object ID: 163993
Processed posts 2500 - 3000 of 35366. Last Object ID: 161883
Processed posts 3000 - 3500 of 35366. Last Object ID: 160888
Processed posts 3500 - 4000 of 35366. Last Object ID: 159481
Processed posts 4000 - 4500 of 35366. Last Object ID: 158981
Processed posts 4500 - 5000 of 35366. Last Object ID: 158481
Time elapsed: 00:01:40.200000
Memory Usage: 385.06mb (Peak: 431.42mb)
Processed posts 5000 - 5500 of 35366. Last Object ID: 157981
Processed posts 5500 - 6000 of 35366. Last Object ID: 157480
Processed posts 6000 - 6500 of 35366. Last Object ID: 156975
Processed posts 6500 - 7000 of 35366. Last Object ID: 92684
Processed posts 7000 - 7500 of 35366. Last Object ID: 91913
Processed posts 7500 - 8000 of 35366. Last Object ID: 91413
Processed posts 8000 - 8500 of 35366. Last Object ID: 90875
Processed posts 8500 - 9000 of 35366. Last Object ID: 89807
Processed posts 9000 - 9500 of 35366. Last Object ID: 88740
Processed posts 9500 - 10000 of 35366. Last Object ID: 87859
Time elapsed: 00:02:22.860000 (+42.665)
Memory Usage: 410.96mb (Peak: 431.42mb)
Processed posts 10000 - 10500 of 35366. Last Object ID: 87249
Processed posts 10500 - 11000 of 35366. Last Object ID: 77449
Processed posts 11000 - 11500 of 35366. Last Object ID: 76283
Processed posts 11500 - 12000 of 35366. Last Object ID: 75679
Processed posts 12000 - 12500 of 35366. Last Object ID: 74845
Processed posts 12500 - 13000 of 35366. Last Object ID: 74342
Processed posts 13000 - 13500 of 35366. Last Object ID: 73802
Processed posts 13500 - 14000 of 35366. Last Object ID: 73275
Processed posts 14000 - 14500 of 35366. Last Object ID: 72744
Processed posts 14500 - 15000 of 35366. Last Object ID: 71964
Time elapsed: 00:04:11.470000 (+108.607)
Memory Usage: 625.28mb (Peak: 681.56mb)
Processed posts 15000 - 15500 of 35366. Last Object ID: 69731
Processed posts 15500 - 16000 of 35366. Last Object ID: 65754
Processed posts 16000 - 16500 of 35366. Last Object ID: 64360
Processed posts 16500 - 17000 of 35366. Last Object ID: 61982
Processed posts 17000 - 17500 of 35366. Last Object ID: 60667
Processed posts 17500 - 18000 of 35366. Last Object ID: 60100
Processed posts 18000 - 18500 of 35366. Last Object ID: 59521
Processed posts 18500 - 19000 of 35366. Last Object ID: 58306
Processed posts 19000 - 19500 of 35366. Last Object ID: 57662
Processed posts 19500 - 20000 of 35366. Last Object ID: 57162
Time elapsed: 00:06:37.730000 (+146.261)
Memory Usage: 1032.15mb (Peak: 1094.31mb)
Processed posts 20000 - 20500 of 35366. Last Object ID: 56661
Processed posts 20500 - 21000 of 35366. Last Object ID: 56082
Processed posts 21000 - 21500 of 35366. Last Object ID: 55183
Processed posts 21500 - 22000 of 35366. Last Object ID: 54682
Processed posts 22000 - 22500 of 35366. Last Object ID: 54169
Processed posts 22500 - 23000 of 35366. Last Object ID: 53664
Processed posts 23000 - 23500 of 35366. Last Object ID: 53164
Processed posts 23500 - 24000 of 35366. Last Object ID: 52663
Processed posts 24000 - 24500 of 35366. Last Object ID: 52163
Processed posts 24500 - 25000 of 35366. Last Object ID: 51654
Time elapsed: 00:07:35.590000 (+57.863)
Memory Usage: 1091.36mb (Peak: 1138.15mb)
Processed posts 25000 - 25500 of 35366. Last Object ID: 51154
Processed posts 25500 - 26000 of 35366. Last Object ID: 48257
Processed posts 26000 - 26500 of 35366. Last Object ID: 47692
Processed posts 26500 - 27000 of 35366. Last Object ID: 47192
Processed posts 27000 - 27500 of 35366. Last Object ID: 45495
Processed posts 27500 - 28000 of 35366. Last Object ID: 44984
Processed posts 28000 - 28500 of 35366. Last Object ID: 44482
Processed posts 28500 - 29000 of 35366. Last Object ID: 43965
Processed posts 29000 - 29500 of 35366. Last Object ID: 43464
Processed posts 29500 - 30000 of 35366. Last Object ID: 42963
Time elapsed: 00:08:49.360000 (+73.767)
Memory Usage: 1149.82mb (Peak: 1210.21mb)
Processed posts 30000 - 30500 of 35366. Last Object ID: 41942
Processed posts 30500 - 31000 of 35366. Last Object ID: 41437
Processed posts 31000 - 31500 of 35366. Last Object ID: 33488
Processed posts 31500 - 32000 of 35366. Last Object ID: 32980
Processed posts 32000 - 32500 of 35366. Last Object ID: 32475
Processed posts 32500 - 33000 of 35366. Last Object ID: 31967
Processed posts 33000 - 33500 of 35366. Last Object ID: 31373
Processed posts 33500 - 34000 of 35366. Last Object ID: 30868
Processed posts 34000 - 34500 of 35366. Last Object ID: 30348
Processed posts 34500 - 35000 of 35366. Last Object ID: 29810
Time elapsed: 00:10:14.270000 (+84.909)
Memory Usage: 1199.27mb (Peak: 1228.59mb)
Processed posts 35000 - 35366 of 35366. Last Object ID: 23913
Success: Number of posts indexed: 35362
Success: Sync complete
Total time elapsed: 00:10:18.303000
Success: Done!
`

dashboard sync is broken

**Comment by wildberrylillet** [comment]
#3557 looks good to me, index is complete!

![image](https://github.com/10up/ElasticPress/assets/16671282/c33eca61-6fc1-483a-b34f-bcb7e323c497)

![image](https://github.com/10up/ElasticPress/assets/16671282/73f39b02-6a02-4d0e-a740-a53aa8724f8a)

![image](https://github.com/10up/ElasticPress/assets/16671282/15194e4f-cbc3-4c93-abba-7791c266d298)
