### ISSUE TITLE
No results because of 1 word

### ISSUE THREAD

**Issue by clintonbosch** [10up/ElasticPress#3511]
### Describe your question

I have elasticpress on my site and get results for the following 2 queries:

/?s=farag+elias (33 results)

/?s=farag+v+elias (33 results)

Even a misspel:

/?s=fara+v+elias (33 results)

But this return nothing

/?s=farag+vs+elias (0 results)

Why is that? Can I fix it? I even tried making ‘v’ an alternative for ‘vs’ and that did not work either.

[elasticpress-report.txt](https://github.com/10up/ElasticPress/files/11834339/elasticpress-report.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @clintonbosch,

I was able to work around that creating an alternative in the Synonyms page, setting "vs" as the primary term and "v" as the alternative. Is that something you tried already?

![image](https://github.com/10up/ElasticPress/assets/184628/529fce03-a837-4853-a0dc-30a9fd36fdc5)

**Comment by clintonbosch** [comment]
HI @felipeelia 

I tried exactly that but it did not work.
![image](https://github.com/10up/ElasticPress/assets/731276/517cebc7-707d-44d3-8465-aee67805fdd1)

![image](https://github.com/10up/ElasticPress/assets/731276/58bfacb6-3096-48c2-9f67-e59cd4110acb)

![image](https://github.com/10up/ElasticPress/assets/731276/6ce06215-11a9-4395-bb87-3d54599d02a5)

Try it here https://www.squash.tv/?s=farag+vs+elias

**Comment by felipeelia** [comment]
That is weird @clintonbosch. I've tried that in a local and it just worked. Before we dig deeper into that, I want to rule out some basic stuff:
- Do you have titles enabled in the Weighting Dashboard, right?
- Did you run a full sync after changing that synonym? Although that should not be required, we had cases in the past where that helped (more on #2877)

If you did all that, do you mind installing Debug Bar ElasticPress as described in [this article](https://elasticpress.zendesk.com/hc/en-us/articles/16670678802189-Debugging)? Then visit that search page and share with us the file that is generated after you click on "Download Requests Info". Thanks

**Comment by clintonbosch** [comment]
Thanks for the response @felipeelia , I did a fresh sync but that did not help. Will install debug bar and see if that helps resolve. Will let you know

**Comment by felipeelia** [comment]
@clintonbosch I'll close this one for now but feel free to add a comment here once you have the chance, and we can reopen it. Thanks!
