### ISSUE TITLE
BUG: Deprecated: Creation of dynamic property ElasticPress\Feature\WooCommerce\Orders::$index

### ISSUE THREAD

**Issue by akshaydalvi4** [10up/ElasticPress#3513]
### Describe the bug

I am currently using WordPress 6.2.2 and PHP 8.4.2. When I updated to the latest version of the ElasticPress plugin, I received the following error message: "Deprecated: Creation of dynamic property ElasticPress\Feature\WooCommerce\Orders::$index". How can I resolve this issue?

### Steps to Reproduce

1) Update latest WordPress 
2) Update php 8.4.2
3) Activate the ElasticPress plugin

### Screenshots, screen recording, code snippet

Deprecated: Creation of dynamic property ElasticPress\Feature\WooCommerce\Orders::$index is deprecated in C:\xampp\htdocs\wordpress\wp-content\plugins\elasticpress\includes\classes\Feature\WooCommerce\Orders.php on line 29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @akshaydalvi4, this will be fixed by #3507
