### ISSUE TITLE
Change keyboard layout

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3520]
### Describe your question

Hello! Tell me, has the function of changing the keyboard layout been implemented when the user enters a search query in the wrong layout?
example https://github.com/papahigh/elasticsearch-keyboard-layout

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi there! No, @ws256, we do not have anything like that. For that, you would need to install that in the Elasticsearch server first, and only then use ElasticPress's filters to change the query to use it.
