### ISSUE TITLE
BUG: shortcode in the page

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3522]
### Describe the bug

Hi all! 
Perhaps the work with shortcodes has changed?

### Steps to Reproduce

I have a post_type=page page in my template that uses a shortcode to display specific post_type=post posts.
After the last update of the plugin, in the admin part in the general list of posts page /wp-admin/edit.php?post_type=post  post_type=page is displayed. If you remove the shortcode, this page disappears and behaves as expected.
Perhaps the work with shortcodes has changed?

### WordPress Environment ###
wp_version: 6.2.2
home_url: 
site_url: 
is_multisite: false
theme: vms (2022)
plugins: Autoremove Attachments (1.3.1), Classic Editor (1.6.3), Cyr-To-Lat (5.5.2), Disable New User Notifications (2.0.0), ElasticPress (4.6.0), Force Regenerate Thumbnails (2.1.2),  Media Cleaner (Pro) (6.6.4), Query Monitor (3.12.3), Rename Users (1.2), WordPress Social Login (3.0.4) and Yoast SEO (20.10)
revisions: all

### Server Environment ###
php_version: 8.1.18
memory_limit: 1024M
timeout: 30

## Indexable Content ##

post_count: 150 274
page_count: 38
attachment_count: 457 412
post_meta_keys: 24
page_meta_keys: 9
attachment_meta_keys: 3
total-all-post-types: 26

### Settings ###
host: local:9200
index_prefix: 
per_page: 200
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### site-post-1 ###
health: green
status: open
index: site-post-1
uuid: 
pri: 5
rep: 1
docs.count: 607765
docs.deleted: 86932
store.size: 5.3gb
pri.store.size: 2.7gb
total_fields_limit: 5000

### site-user ###
health: green
status: open
index: site-user
uuid: 
pri: 5
rep: 1
docs.count: 1439068
docs.deleted: 7687
store.size: 1.8gb
pri.store.size: 923mb
total_fields_limit: 5000

### 2023/06/20 8:13:01 дп ###
method: WP Dashboard
is_full_sync: Yes
end_date_time: 2023/06/20 11:32:37 дп
total_time: 3 часа, 19 минут, 37 секунд
total: 2042408
synced: 2042724
skipped: 0
failed: 0
errors: array (
)

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Protected Content ###
active: true
force_inactive: false

### Related Posts ###
active: true
force_inactive: false

### Users ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @ws256. We will need more info to help you with your problem. Do you mind sharing the source code of that shortcode? Also, if I am getting this right, you are seeing posts listed in the Pages list of the WordPress dashboard, is that right? Thanks

**Comment by ws256** [comment]
@felipeelia One page with this shortcode, in the list of posts in the WordPress dashboard.

```
<?php
$num_posts = wp_count_posts('post');
$num_posts = $num_posts->pending;
$num_posts = sprintf(_n('%s', '%s', $num_posts), number_format_i18n($num_posts));
$arg = [
	'posts_per_page' => -1,
	'post_status' => 'pending',
	'order' => 'ASC',
	'ignore_sticky_posts' => 1
];
$q = new WP_Query($arg);
$i = 0;
?>

Total post pending approval - <?php echo $num_posts; ?>
	
	<?php if ($q->have_posts()) { ?>
		<table class="feature-posts-table">
			<tbody>
				<tr>
					<th valign="middle">№</th>
					<th valign="middle">Date</th>
					<th valign="middle">Author</th>
					<th valign="middle">Title</th>
				</tr>
			
				<?php while ($q->have_posts()) { ?>
					
					<?php $q->the_post(); ?>
					<?php $i++; ?>					
					
					<tr>
						<td valign="top" class="nembertab"><?php echo $i; ?></td>
						<td valign="top"><?php the_time('Y-m-d'); ?></td>
						<td valign="top"><?php the_author_posts_link(); ?></td>
						<td valign="top"><?php the_title(); ?></td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	
	<?php } else { ?>
		None
	<?php } ?>
	<?php wp_reset_postdata();
```

**Comment by felipeelia** [comment]
@ws256 I didn't test it myself but the problem could be related to that last `wp_reset_postdata()` call, which misbehaves in some admin scenarios (see [this comment](https://developer.wordpress.org/reference/functions/wp_reset_postdata/#comment-6443) and [this trac ticket](https://core.trac.wordpress.org/ticket/18408).)

Would it be possible for you to include something like this at the beginning of the shortcode and check if that fixes it?
```php
if ( is_admin() ) { return; }
```

Also, does it work fine if you disable ElasticPress?
