### ISSUE TITLE
Elastic as a Recommendation Engine

### ISSUE THREAD

**Issue by Alexpalix** [10up/ElasticPress#3523]
### Describe your question

Hi I am not techie. I wondered if you could help. I have seen a few blogs that show you how to turn elastic into a recommendation engine, for example https://towardsdatascience.com/how-to-build-a-recommendation-engine-quick-and-simple-aec8c71a823e, like I say I dont know the technical side, would elasticpress support this? Thank you. Alex

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @Alexpalix, although that is not in our roadmap I personally think that is a super interesting use case. It won't be simple to set it up though, and some planning and (a lot of) custom code may be involved.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!
