### ISSUE TITLE
BUG: iOS Javascript error

### ISSUE THREAD

**Issue by Luke-SF** [10up/ElasticPress#3536]
### Describe the bug

Elasticpress JS is failing on iPhone:

/wp-content/plugins/elasticpress/dist/js/autosuggest-script.js?ver=0d438134ad0d7572e118

"Syntax error: Unexpected token '.'". User agent:

"Mozilla/5.0 (iPhone; CPU iPhone OS 12_5_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1"

### Steps to Reproduce

Try any page with this search script, on iPhone?

### Environment information

User agent:

"Mozilla/5.0 (iPhone; CPU iPhone OS 12_5_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1"

### Autosuggest ###
active: true
autosuggest_selector: 
endpoint_url: 
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: false
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Related Posts ###
active: true
force_inactive: false

### WooCommerce ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Luke-SF** [comment]
Is this something that has a fix or workaround? Perhaps build process could use something like this to work on Safari? https://stackoverflow.com/a/72199339

**Comment by JakePT** [comment]
Hi @Luke-SF, from your error message it looks like you're running Safari in iOS 12. At this point iOS 12 is almost 5 years old, and all iOS devices sold in the last 7 years are capable of updating to iOS 15 or higher. As such it has negligible market share. In fact, in most statistics I could find it basically disappeared several years ago. Therefore we don't plan on making any changes to support that iOS version. 

If your device is an iPhone 6s or newer, I recommend updating to the latest iOS version, which should resolve the issue.
