### ISSUE TITLE
BUG: ReactDOM.render is no longer supported in React 18. Use createRoot instead.

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#3544]
### Describe the bug

WordPress 6.2 ships with version 18 of React and because of this few of the ElasitcPress components throws the warning  `Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead`

The process of upgrading this is simple. We need to use the `createRoot` instead of `render` https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/

For example, this code 

```
import { render } from '@wordpress/element';
 
const el = document.getElementById( 'root' );
render( <App />, el );
```

Will become this 

```
import { createRoot } from '@wordpress/element';
 
const el = document.getElementById( 'root' );
const root = createRoot( el );
root.render( <App /> );
```

### Steps to Reproduce

1. Use WordPress 6.2+
2. Activate the Instant Results feature
3. Check the browser console for warning 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Do we need to test the current WordPress version to switch between those two calls @burhandodhy @JakePT ?
