### ISSUE TITLE
Dashboard search in Post 

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3555]
### Describe your question

Hi all!
In the general list of posts (/wp-admin/edit.php), the search works correctly.
If you select the post type "draft" and start searching (/wp-admin/edit.php?post_status=draft&post_type=post), the search results are not role relevant and unpredictable.
Does everyone have it?

The latest version of the plugin and wordpress.
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @ws256,

I tested, and the search functionality is functioning correctly for Draft posts. Could you please share the ElasticPress Query Body and Result so I can check what’s happening? Also, it’s worth noticing that ElasticPress utilizes fuzziness in the search, which can introduce variations in the results. This means that the search might return posts that closely match the search term, even if they are not exact matches.

Regards,
Burhan
