### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by Alexpalix** [10up/ElasticPress#3563]
### Describe your question

Hi

Does the server hosting for elastic have to be the same as the hosting for the wp website with elasticpress installed?

Kind regsrds

Alex

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @Alexpalix,

Elastic does not need to be on the same server as the WordPress website but they need to be able to connect to each other. Once you have the connection details it should be just a matter of going to ElasticPress' Settings screen and filling it out there:

![image](https://github.com/10up/ElasticPress/assets/184628/2d3b2a44-a921-4941-ab6c-778d576f30eb)
 
If you didn't choose an Elasticsearch hosting provider yet, I suggest [ElasticPress.io](https://www.elasticpress.io/), which is totally designed for ElasticPress/WordPress websites. If you are considering to self-host it, I recommend reading this article: https://elasticpress.zendesk.com/hc/en-us/articles/4413938931853-Considerations-for-self-hosted-Elasticsearch-setups
