### ISSUE TITLE
1 index per 1 CPT

### ISSUE THREAD

**Issue by przestrzal** [10up/ElasticPress#3569]
### Is your enhancement related to a problem? Please describe.

From what I can see, ElasticPress uses 1 common index for all "post types" that are declared in WP.

My WP instance has many objects (different 'post types') that have multiple meta fields of their own, resulting in 1 common index growing enormously (has multiple columns), which often exceeds the default ElasticSearch column limit.

Does ElasticPress allows configuration where each "post type" has its own index with its own set of columns?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
No, it does not @przestrzal, but your Elasticsearch index does not need to be an exact mirror of your codebase, it should have only the fields that you need to be searchable. To control the list of meta fields that should be indexed you can use the [ep_prepare_meta_excluded_public_keys](https://10up.github.io/ElasticPress/ep_prepare_meta_excluded_public_keys.html) filter or ep_prepare_meta_data, as explained in this article: https://elasticpress.zendesk.com/hc/en-us/articles/360052019111-How-to-exclude-metadata-from-indexing

To make those meta fields searchable, you can follow this blog post: https://www.elasticpress.io/blog/2020/06/custom-fields-and-weighted-search-with-elasticpress-part-2/
