### ISSUE TITLE
BUG: Site performance drops while plugin is active but not configured

### ISSUE THREAD

**Issue by scottbuscemi** [10up/ElasticPress#3570]
### Describe the bug

If the plugin is active but having trouble indexing for the first time, site performance degrades and the internal REST API does not work. Admin pages take 10+ seconds to load.

### Steps to Reproduce

1. Install the plugin and choose the self-hosted option
2. Enter in an IP address for the server that does not work
3. Try indexing the site
4. Attempt to browse the WP Admin or use the REST API

### Screenshots, screen recording, code snippet

<img width="893" alt="Screenshot 2023-07-30 at 11 46 11 AM" src="https://github.com/10up/ElasticPress/assets/4336848/bdcabcca-a585-4c26-aa35-6bcdaa99b268">

### Environment information

- WP Engine server
- PHP 8.0
- ElasticPress 4.6.1
- WordPress 6.2.2

### https://sitename.com (2023-07-30 11:40:51) ###
error: 
recommended_solution: 
es_req: PUT http://146.190.147.21:9200/sitename-post-1
request_id: f8e6321f1f414a0fa44898901845baf6
query_time: 7163.77520561
wp_args: array (
)
status_code: 
body: {"settings":{"index.number_of_shards":5,"index.number_of_replicas":1,"analysis":{"analyzer":{"default":{"tokenizer":"standard","filter":["ep_synonyms_filter","standard","ewp_word_delimiter","lowercase","stop","ewp_snowball"],"language":"english"},"shingle_analyzer":{"type":"custom","tokenizer":"standard","filter":["lowercase","shingle_filter"]},"ewp_lowercase":{"type":"custom","tokenizer":"keyword","filter":["lowercase"]},"edge_ngram_analyzer":{"type":"custom","tokenizer":"standard","filter":["lowercase","edge_ngram"]}},"filter":{"shingle_filter":{"type":"shingle","min_shingle_size":2,"max_shingle_size":5},"ewp_word_delimiter":{"type":"word_delimiter","preserve_original":true},"ewp_snowball":{"type":"snowball","language":"english"},"edge_ngram":{"side":"front","max_gram":10,"min_gram":3,"type":"edgeNGram"},"ep_synonyms_filter":{"type":"synonym_graph","lenient":true,"synonyms":["sneakers, tennis shoes, trainers, runners","shoes => sneaker, sandal, boots, high heels"]}}}},"mappings":{"post":{"_meta":{"mapping_version":"pre-5-0.php"},"date_detection":false,"dynamic_templates":[{"template_meta":{"path_match":"post_meta.*","mapping":{"type":"multi_field","path":"full","fields":{"{name}":{"type":"string","index":"analyzed"},"raw":{"type":"string","index":"not_analyzed","include_in_all":false}}}}},{"template_meta_types":{"path_match":"meta.*","mapping":{"type":"object","path":"full","properties":{"value":{"type":"string","fields":{"sortable":{"type":"string","analyzer":"ewp_lowercase","include_in_all":false},"raw":{"type":"string","index":"not_analyzed","include_in_all":false}}},"raw":{"type":"string","index":"not_analyzed","include_in_all":false},"long":{"type":"long","index":"not_analyzed"},"double":{"type":"double","index":"not_analyzed"},"boolean":{"type":"boolean","index":"not_analyzed"},"date":{"type":"date","format":"yyyy-MM-dd","index":"not_analyzed"},"datetime":{"type":"date","format":"yyyy-MM-dd HH:mm:ss","index":"not_analyzed"},"time":{"type":"date","format":"HH:mm:ss","index":"not_analyzed"}}}}},{"template_terms":{"path_match":"terms.*","mapping":{"type":"object","path":"full","properties":{"name":{"type":"string","fields":{"raw":{"type":"string","index":"not_analyzed"},"sortable":{"type":"string","analyzer":"ewp_lowercase"}}},"term_id":{"type":"long"},"term_taxonomy_id":{"type":"long"},"parent":{"type":"long"},"slug":{"type":"string","index":"not_analyzed"},"facet":{"type":"string","index":"not_analyzed"},"term_order":{"type":"long"}}}}},{"term_suggest":{"path_match":"term_suggest_*","mapping":{"type":"completion","analyzer":"default"}}}],"_all":{"analyzer":"simple"},"properties":{"post_id":{"type":"long","index":"not_analyzed","include_in_all":false},"ID":{"type":"long","index":"not_analyzed","include_in_all":false},"post_author":{"type":"object","properties":{"display_name":{"type":"string","fields":{"raw":{"type":"string","index":"not_analyzed"},"sortable":{"type":"string","analyzer":"ewp_lowercase"}}},"login":{"type":"string","fields":{"raw":{"type":"string","index":"not_analyzed"},"sortable":{"type":"string","analyzer":"ewp_lowercase"}}},"id":{"type":"long","index":"not_analyzed"},"raw":{"type":"string","index":"not_analyzed","include_in_all":false}}},"post_date":{"type":"date","format":"YYYY-MM-dd HH:mm:ss","include_in_all":false},"post_date_gmt":{"type":"date","format":"YYYY-MM-dd HH:mm:ss","include_in_all":false},"post_title":{"type":"multi_field","fields":{"post_title":{"type":"string","analyzer":"standard","store":"yes"},"raw":{"type":"string","index":"not_analyzed","include_in_all":false},"sortable":{"type":"string","analyzer":"ewp_lowercase","include_in_all":false},"suggest":{"type":"string","analyzer":"edge_ngram_analyzer","search_analyzer":"standard"}}},"post_excerpt":{"type":"string"},"post_content":{"type":"string","analyzer":"default"},"post_status":{"type":"string","index":"not_analyzed"},"post_name":{"type":"multi_field","fields":{"post_name":{"type":"string"},"raw":{"type":"string","index":"not_analyzed","include_in_all":false}}},"post_modified":{"type":"date","format":"YYYY-MM-dd HH:mm:ss","include_in_all":false},"post_modified_gmt":{"type":"date","format":"YYYY-MM-dd HH:mm:ss","include_in_all":false},"post_parent":{"type":"long","index":"not_analyzed","include_in_all":false},"post_type":{"type":"multi_field","fields":{"post_type":{"type":"string"},"raw":{"type":"string","index":"not_analyzed","include_in_all":false}}},"post_mime_type":{"type":"string","index":"not_analyzed","include_in_all":false},"permalink":{"type":"string"},"guid":{"type":"string","index":"not_analyzed"},"terms":{"type":"object"},"post_meta":{"type":"object"},"meta":{"type":"object"},"date_terms":{"type":"object","properties":{"year":{"type":"integer"},"month":{"type":"integer"},"m":{"type":"integer"},"week":{"type":"integer"},"day":{"type":"integer"},"dayofweek":{"type":"integer"},"dayofweek_iso":{"type":"integer"},"dayofyear":{"type":"integer"},"hour":{"type":"integer"},"minute":{"type":"integer"},"second":{"type":"integer"}}},"thumbnail":{"type":"object","properties":{"ID":{"type":"long"},"src":{"type":"text"},"width":{"type":"integer"},"height":{"type":"integer"},"alt":{"type":"text"}}},"term_suggest":{"type":"string","analyzer":"edge_ngram_analyzer","search_analyzer":"standard"}}}}}
result: 

### https://sitename.com (2023-07-30 11:40:44) ###
error: 
recommended_solution: 
es_req: DELETE http://146.190.147.21:9200/sitename-post-1
request_id: 8e0a858d226e4796a9ab456f355fc36c
query_time: 7249.22800064
wp_args: array (
)
status_code: 
body: 
result: 

### WordPress Environment ###
wp_version: 6.2.2
home_url: https://sitename.com
site_url: https://sitename.com
is_multisite: false
theme: sitename (1.0.0)
plugins: Advanced Custom Fields PRO (6.1.7), Bugsnag Error Monitoring (1.6.3), Classic Editor (1.6.3), Cloudflare (4.12.2), Disable Gravity Forms Fields (1.4), ElasticPress (4.6.1), Elementor (3.14.1), Gravity Forms (2.7.11), Gravity Forms Signature Add-On (4.5), Gravity PDF (6.6.0), ManageWP - Worker (4.9.17), oEmbed Gist (4.9.1), Post Types Order (2.0.9), Recent Posts Widget Extended (2.0.2), Redirection (5.3.10), Two Factor Authentication (1.14.16), Ultimate Image Optimization Helpers (0.2.10), and Yoast SEO (20.11)
revisions: 0

### Server Environment ###
php_version: 8.0.29
memory_limit: 40M
timeout: 3600

### sitename — https://sitename.com ###
post_count: 37
page_count: 24
e-landing-page_count: 0
elementor_library_count: 2
attachment_count: 105
acf-taxonomy_count: 0
acf-post-type_count: 0
acf-field-group_count: 4
acf-field_count: 15
post_meta_keys: 0
page_meta_keys: 1
e-landing-page_meta_keys: 0
elementor_library_meta_keys: 0
attachment_meta_keys: 0
acf-taxonomy_meta_keys: 0
acf-post-type_meta_keys: 0
acf-field-group_meta_keys: 0
acf-field_meta_keys: 0
total-all-post-types: 1
distinct-meta-keys: homepage_header

### Settings ###
host: http://146.190.147.21:9200
index_prefix: 
language: en_US
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### sitename-post-1 ###
0: true

### 2023/07/30 11:40:25 am ###
method: WP Dashboard
is_full_sync: Yes
end_date_time: 2023/07/30 11:40:51 am
total_time: 0 hours, 0 minutes, 26 seconds
total: 0
synced: 0
skipped: 0
failed: 0
errors: array (
  0 => 'cURL error 28: Failed to connect to 146.190.147.21 port 9200: Connection timed out',
)

### Autosuggest ###
active: true
autosuggest_selector: 
endpoint_url: 
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

### Protected Content ###
active: true
force_inactive: false

### Related Posts ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scottbuscemi** [comment]
<img width="1366" alt="Screenshot 2023-07-30 at 12 27 16 PM" src="https://github.com/10up/ElasticPress/assets/4336848/a6db9109-790f-4ae7-8ffe-d044f300a27c">

Each admin page takes about 15 seconds to load because of the failed HTTP calls. Perhaps these can only start happening once an initial sync/index is successful?

**Comment by felipeelia** [comment]
Thanks for opening the issue @scottbuscemi. After an internal discussion, for ElasticPress 5.0 we will implement a validation that will not allow to save the Hosting settings if it is not possible to connect to the Elasticsearch server, that should help at least alleviate the problem.

**Comment by felipeelia** [comment]
Closed by #3684.
