### ISSUE TITLE
Snyc Times Out with Self Hosting

### ISSUE THREAD

**Issue by oiver555** [10up/ElasticPress#3576]
### Snyc Times Out with Self Hosting

Kind of new to this but I believe I got everything right. However when I enter my Self Host URL and try to sync I get this response
![image](https://github.com/10up/ElasticPress/assets/69017748/c718c4d7-19ba-4cc2-9c33-29ec7fd27883)

Ok so first I got a VPN from my host (hostinger) and installed elastic search on my Ubuntu server. I followed the instructions [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html) to the T. After I start the elastic search instance, here is what I see when I run this  sudo systemctl status elasticsearch command

![image](https://github.com/10up/ElasticPress/assets/69017748/23ede9c5-430a-4c93-8101-4b5783ca3441)
Ok so from here I enter my VPN url followed by a :9200 like how you see below. I have already tried using both http and https just to be sure if it would make a difference... (I replaced the real VPN url with a fake one for the screenshot)
![image](https://github.com/10up/ElasticPress/assets/69017748/86879f76-63cd-4920-847e-b0575a1745ce)

Also too I am running a wordpress multisite, not sure if that is a factor in all this. In any case if there is something I have missed to do, or some setting you would like to see just let me know! Or if everything looks right to you tell me also!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @oiver555, being in a multisite should not be a problem. ElasticPress works well on those too.

Helping with infrastructure problems is outside of the scope of this repository, so we can't help you with that part. Just make sure you can send a curl call from the machine hosting WordPress to the machine hosting Elasticsearch. Good luck!
