### ISSUE TITLE
Search Exact / Partial / ALL words

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/ElasticPress#358]
The ability to customize per WP_Query or filter for the global setting, if search terms should be looking at exact, check for existence of ANY words in the search query, or for ALL words (not exact).

Ability to turn off fuzzy matching would be nice too.

If anyone has a beat on the ElasticSearch args I should be looking at, I'll get on my way towards a PR.

**Comment by tlovett1** [comment]
This just relates to the query type: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-queries.html
