### ISSUE TITLE
Have more than 90K posts but synced only 45k articles

### ISSUE THREAD

**Issue by jayeshma** [10up/ElasticPress#3588]
### Describe your question

Hi Team,
We have around 90k articles and when we click on sync, only 45k articles getting synced.
can you please us to understand how sync work?
is there anything we can do to sync all missing articles?

We are using plugin with version 3.6.3

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @jayeshma,

That is a very outdated version. Is there any reason why you are not using the most recent version of the plugin? For your question, are all those articles the same post type? If they are not, are your custom post types public?

This page has some information about the sync process (that has changed in EP 4.0): https://elasticpress.zendesk.com/hc/en-us/articles/16672117103501-Sync-Process

**Comment by jayeshma** [comment]
Hi @felipeelia,

Thank you so much for your response.

We started to work on existing project where plugin version is older, we have proposed to update plugin to latest version which might fix issue.
All articles are having same post type and we are not using custom post type.

Till we update plugin version, do you have any idea on what can cause to not syncing all articles?

Thank you

**Comment by felipeelia** [comment]
@jayeshma, unfortunately, I don't have any idea. One thing you could try is to reduce the number of posts indexed per cycle (in the Settings screen) but that is just a guess.

As we don't provide support for older versions, I'm going to close the issue for now but if you upgrade it and still face the same issue, feel free to leave a message and we can reopen it. Thanks.

**Comment by jayeshma** [comment]
Thank you @felipeelia for looking into this. 
We will do as you suggested.
