### ISSUE TITLE
Showing relevant excerpt in search results list

### ISSUE THREAD

**Issue by paulhuisman** [10up/ElasticPress#359]
Is it possible to return a relevant excerpt of a PDF indexed file?

For example somewhere in the indexed pdf it's about the term _velocity_.

The passage around this term will be shown in the search results.

**Comment by lukaspawlik** [comment]
Hi @paulhuisman,

Have you found an answer for your question? If you still need our help then feel free to reopen this ticket. I am closing it for now.
