### ISSUE TITLE
Error: [1:175] [terms_lookup] unknown field [publish]

### ISSUE THREAD

**Issue by deepshah983** [10up/ElasticPress#3608]
### Describe your question

Hello,

We have used the ElasticPress plugin on our website.
Site URL - https://staging.capemaycountyherald.com/

We have set up the ElasticPress configurations in the plugin.
We have used ElasticSearch host - http://localhost:9200.
We have set up Elastic search on our server itself.
Our Server is Ubuntu 22.04 with a server pilot server.
ElasticSearch details are below:
{
  "name" : "herald-staging",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "8McX-hz5SWK8DyRUnBytpw",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

ElasticPress Debug Log:

CURL Url - 
curl -XPOST -H 'Content-Type: application/json' -H 'X-ElasticPress-Request-ID: 4b962fa599fc409181bc659e669f8f6c' -d '{\"from\":0,\"size\":7,\"post_filter\":{\"bool\":{\"must\":[{\"terms\":{\"post_type.raw\":[\"post\",\"page\",\"e-landing-page\",\"article\",\"spout_off\",\"herald_author\"]}},{\"terms\":{\"post_status\":{\"publish\":\"publish\",\"inherit\":\"inherit\"}}},{\"bool\":{\"must_not\":[{\"terms\":{\"meta.ep_exclude_from_search.raw\":[\"1\"]}}]}}]}},\"query\":{\"function_score\":{\"query\":{\"bool\":{\"should\":[{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"phrase\",\"fields\":[\"post_title^14\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\",\"terms.ep_custom_result.name^9999\"],\"boost\":3}},{\"multi_match\":{\"query\":\"wildwood\",\"fields\":[\"post_title^14\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\",\"post_title.suggest^1\",\"term_suggest^1\"],\"operator\":\"and\",\"boost\":1,\"fuzziness\":\"auto\"}},{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"cross_fields\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.category.name^1\",\"terms.post_tag.name^1\",\"terms.ep_custom_result.name^1\"],\"boost\":1,\"analyzer\":\"standard\",\"tie_breaker\":0.5,\"operator\":\"and\"}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"post\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^9999\"],\"boost\":3}},{\"multi_match\":{\"query\":\"wildwood\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"operator\":\"and\",\"boost\":1,\"fuzziness\":\"auto\"}},{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"cross_fields\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^1\"],\"boost\":1,\"analyzer\":\"standard\",\"tie_breaker\":0.5,\"operator\":\"and\"}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"page\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^9999\"],\"boost\":3}},{\"multi_match\":{\"query\":\"wildwood\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"operator\":\"and\",\"boost\":1,\"fuzziness\":\"auto\"}},{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"cross_fields\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^1\"],\"boost\":1,\"analyzer\":\"standard\",\"tie_breaker\":0.5,\"operator\":\"and\"}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"e-landing-page\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.post_tag.name^1\",\"terms.category.name^1\",\"terms.ep_custom_result.name^9999\"],\"boost\":3}},{\"multi_match\":{\"query\":\"wildwood\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.post_tag.name^1\",\"terms.category.name^1\",\"post_title.suggest^1\",\"term_suggest^1\"],\"operator\":\"and\",\"boost\":1,\"fuzziness\":\"auto\"}},{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"cross_fields\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.post_tag.name^1\",\"terms.category.name^1\",\"terms.ep_custom_result.name^1\"],\"boost\":1,\"analyzer\":\"standard\",\"tie_breaker\":0.5,\"operator\":\"and\"}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"article\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^9999\"],\"boost\":3}},{\"multi_match\":{\"query\":\"wildwood\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"operator\":\"and\",\"boost\":1,\"fuzziness\":\"auto\"}},{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"cross_fields\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^1\"],\"boost\":1,\"analyzer\":\"standard\",\"tie_breaker\":0.5,\"operator\":\"and\"}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"spout_off\"}}]}},{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"phrase\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^9999\"],\"boost\":3}},{\"multi_match\":{\"query\":\"wildwood\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"post_title.suggest^1\"],\"operator\":\"and\",\"boost\":1,\"fuzziness\":\"auto\"}},{\"multi_match\":{\"query\":\"wildwood\",\"type\":\"cross_fields\",\"fields\":[\"post_title^1\",\"post_excerpt^1\",\"post_content^1\",\"post_author.display_name^1\",\"terms.ep_custom_result.name^1\"],\"boost\":1,\"analyzer\":\"standard\",\"tie_breaker\":0.5,\"operator\":\"and\"}}]}}],\"filter\":[{\"match\":{\"post_type.raw\":\"herald_author\"}}]}}]}},\"functions\":[{\"exp\":{\"post_date_gmt\":{\"scale\":\"14d\",\"decay\":0.25,\"offset\":\"7d\"}}},{\"weight\":0.001}],\"score_mode\":\"sum\",\"boost_mode\":\"multiply\"}},\"sort\":[{\"_score\":{\"order\":\"desc\"}}],\"aggs\":{\"terms\":{\"filter\":{\"bool\":{\"must\":[{\"terms\":{\"post_type.raw\":[\"post\",\"page\",\"e-landing-page\",\"article\",\"spout_off\",\"herald_author\"]}},{\"terms\":{\"post_status\":{\"publish\":\"publish\",\"inherit\":\"inherit\"}}},{\"bool\":{\"must_not\":[{\"terms\":{\"meta.ep_exclude_from_search.raw\":[\"1\"]}}]}}]}},\"aggs\":{\"category\":{\"terms\":{\"size\":10000,\"field\":\"terms.category.slug\"}},\"post_tag\":{\"terms\":{\"size\":10000,\"field\":\"terms.post_tag.slug\"}},\"article_layout\":{\"terms\":{\"size\":10000,\"field\":\"terms.article_layout.slug\"}},\"home_page_display\":{\"terms\":{\"size\":10000,\"field\":\"terms.home_page_display.slug\"}},\"town\":{\"terms\":{\"size\":10000,\"field\":\"terms.town.slug\"}},\"post_type\":{\"terms\":{\"size\":10000,\"field\":\"post_type.raw\"}}}}}}' 'http://127.0.0.1:9200/stagingcapemaycountyheraldcom-post-1/_search'

Here is the text file for the System report.
https://drive.google.com/file/d/1UKUHo9Zv7e4p-VhYik3o-Tisheoeh18C/view?usp=sharing

Kindly resolve this issue ASAP.

Thanks
Deep

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@deepshah983, `post_status` should be an array of simple values, not an indexed array. So you will need to change your queries from:
```php
'post_status' => 
  array (
    'publish' => 'publish',
    'inherit' => 'inherit',
  ),
```
to
```php
'post_status' => array( 'publish', 'inherit' );
```
