### ISSUE TITLE
BUG: Unable to translate strings diplayed in instant result modal

### ISSUE THREAD

**Issue by cristianorevil** [10up/ElasticPress#3614]
### Describe the bug

When instant results are enabled, the modal show multimples string that can't be translated: eg "Close", "Price", x results for.

Also with WPML fratture string localization that string are note identified and cannot be replaced

### Steps to Reproduce

Enable instant result

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @cristianorevil, I had a quick look and I can see this strings in our .pot language file, so they should be translatable. This may be a limitation of WPML not being able to translate strings in JavaScript. I found this message on their support forums from last year which seems to confirm that their string translation feature is not compatible with the way JavaScript localization is supported in WordPress: https://wpml.org/forums/topic/wpml-doesnt-display-js-string-translations-for-plugin/#post-11150497

I suggest contacting WPML for support with this issue.

**Comment by cristianorevil** [comment]
@JakePT Thank you, so i can use  pot file to rtanslate the string? I need yo build the plugin or simple palcing .po and .mo file in wordpress language folder?

**Comment by felipeelia** [comment]
Hi @cristianorevil, placing the .po/.mo files in the WP language folder should be enough. Also, if WPML doesn't work for you in this case, I've tested it with Loco Translate just now, and it worked. Thanks for opening the issue!
