### ISSUE TITLE
BUG: Issue with very outdated PSR\Container dependency

### ISSUE THREAD

**Issue by junaidbhura** [10up/ElasticPress#3615]
### Describe the bug

I get the following error when trying to use ElasticPress with some custom code which uses a more recent version of `Psr\Container`

```
...
must be compatible with Psr\Container\ContainerInterface::get($id)
...
```

### Steps to Reproduce

1. Include `psr/container:1.1` or greater into your project using Composer
2. Enable the ElasticPress plugin
3. You will see a fatal error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
To avoid problems like this, we should probably wrap our dependencies using something like https://github.com/BrianHenryIE/strauss

**Comment by felipeelia** [comment]
Although I still think we should implement Strauss, I'm having a hard time reproducing the problem here. @junaidbhura do you mind sharing the full error message, please? Thanks.
