### ISSUE TITLE
BUG: Incorrect result when WooCommerce settings Default product sorting set to Popularity

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#3617]
### Describe the bug

When "Default product sorting" settings is set to "Popularity". The shop page doesn't return the popular products. The problem is that the `order` in a query is set to `asc`

```
    "sort": [
        {
            "meta.total_sales.double": {
                "order": "asc"
            }
        },
        {
            "post_date": {
                "order": "asc"
            }
        }
    ]
```

This issue caused by this change in this snippet https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/WooCommerce/Products.php#L919 compare to what 4.6.0 has https://github.com/10up/ElasticPress/blob/4.6.0/includes/classes/Feature/WooCommerce/WooCommerce.php#L516

### Steps to Reproduce

1) Set the "Default product sorting" settings set to "Popularity"
2) Go to shop page. The popular post wouldn't be listed
3) Select any other sorting option.
4) Again, select the Popularity and this time it will display the correct result.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
While #3619 isn't merged and released, adding this snippet to functions.php fixes the issue:

```php
/**
 * Fix WooCommerce Products ordering by popularity in ElasticPress 4.7.0
 *
 * @param \WP_Query $query The WP Query
 */
function ep_custom_woocommerce_popularity_order( $query ) {
	if ( ! defined( 'EP_VERSION' ) || '4.7.0' !== EP_VERSION ) {
		return;
	}

	$orderby = $query->get( 'orderby', null );
	if ( 'popularity' !== $orderby ) {
		return;
	}

	$query->set( 'order', 'DESC' );
}
add_action( 'pre_get_posts', 'ep_custom_woocommerce_popularity_order', 10 );
```
