### ISSUE TITLE
Ability to disable fuzziness through the plugin UI

### ISSUE THREAD

**Issue by anjulahettige** [10up/ElasticPress#3620]
### Is your enhancement related to a problem? Please describe.

Currently, the only way to disable fuzziness in search is to add the following code snippet:
`add_filter( 'ep_post_match_fuzziness', '__return_zero' );`

We have observed requests from users, especially those managing websites that require precise search results, requesting to disable fuzziness to ensure only exact matches are displayed. (eg. research portals) 

While the above snippet does work, it is a roadblock for non-technical users to disable or enable fuzziness as needed for their search easily. The ability to do this through the plugin UI makes this more accessible to users. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Closing this one as it was decided that these fine-tuning options will be introduced only when we give users a way to switch between search algorithms (see #2086.) Although ElasticPressLabs provides a way to switch between algorithms of previous EP versions, the plan for #2086 is to provide different options for different types of sites, like e-commerce, blogs, etc.
