### ISSUE TITLE
Replace Sync AJAX callback with REST API endpoint

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#3627]
### Is your enhancement related to a problem? Please describe.

To support more features on the Sync page, we should replace the admin-ajax.php callbacks with a REST API endpoint for syncing, with support for more at least these arguments supported by the CLI:

- `offset`
- `indexables`
- `post-type`
- `include`
- `upper-limit-object-id`
- `lower-limit-object-id`

The endpoint should support `POST` requests for triggering or continuing a sync, and `GET` for getting the status of a sync in progress. Both requests should return the sync status, including:

- The sync trigger (eg. manual, CLI).
- Log messages.
- Total items to be synced.
- Total items synced.
- Sync status.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Closed by #3643
