### ISSUE TITLE
stopwords support

### ISSUE THREAD

**Issue by mustafauysal** [10up/ElasticPress#363]
stopwords feature would be nice for mappings.

**Comment by tlovett1** [comment]
@mustafauysal mapping is completely customizable via filters. What are you missing?

**Comment by mustafauysal** [comment]
@tlovett1 I was looking filter in mappings.php file directly. Sorry, I've realized now.

**Comment by shadyvb** [comment]
For future reference, this plugin would let developers manage stopwords via the native WordPress filter `wp_search_stopwords`, and integrates with said filters above to update ElasticPress mapping accordingly: https://github.com/humanmade/elasticpress-stopwords

**Comment by stefanmm** [comment]
> For future reference, this plugin would let developers manage stopwords via the native WordPress filter `wp_search_stopwords`, and integrates with said filters above to update ElasticPress mapping accordingly: https://github.com/humanmade/elasticpress-stopwords

That plugin is outdated. Any other suggestions? I would like to see stopwords natively integrated into ElasticPress.
