### ISSUE TITLE
No mapping found for [featured] in order to sort on

### ISSUE THREAD

**Issue by ghost** [10up/ElasticPress#3631]
### Describe your question

Plugin: WP Job Manager

Process:
- Installed ElasticPress
- Done Sync
- Search for a Job
- Error Occured (see below).
- Recommended Solution from Status Report: The field featured was not found. Make sure it is added to the list of indexed fields and run a new sync to fix the issue.

How do I add the "sort on: feature" field? I only found information how to add meta fields  not how to add search field.

I tried the solution [here](https://github.com/10up/ElasticPress/issues/3535), but it didn't work.

```
{
  "page": 1,
  "order": "ASC",
  **"orderby": "featured",**
  "jm-ajax": "get_listings",
  "error": "",
```

```

	
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "No mapping found for [featured] in order to sort on",
        "index_uuid": "MJqeqYj5Ra-rGV0LWUDycg",
        "index": "testserver-post-1"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "can_match",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "testserver-post-1",
        "node": "ejHehfBUQOetBrWFeWLmXA",
        "reason": {
          "type": "query_shard_exception",
          "reason": "No mapping found for [featured] in order to sort on",
          "index_uuid": "MJqeqYj5Ra-rGV0LWUDycg",
          "index": "testserver-post-1"
        }
      }
    ]
  },
  "status": 400
}

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
WooCommerce stores the featured information in a taxonomy and sorting by it is not supported by default. It can be achieved by using this snippet:

```php
add_filter(
	'ep_formatted_args',
	function( $formatted_args, $args, $query ) {
		if ( is_admin() || ! $query->is_main_query() ) {
			return $formatted_args;
		}
		$formatted_args['sort'] = [
			[
				'terms.product_visibility.slug' => [ 'missing' => '_last' ],
			],
		];
		return $formatted_args;
	},
	11,
	3
);
```

Just keep in mind it is a starting point and you'll likely need to tweak it to fit your needs.
