### ISSUE TITLE
New ElasticPress.io install getting Error: ... [3000]/[3000] maximum shards open

### ISSUE THREAD

**Issue by jimmarion** [10up/ElasticPress#3636]
### Describe your question

Full error message:

```
wp elasticpress sync --setup --yes
Success: Indexing posts…
Sync cleared.
Error: Mapping failed: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [3000]/[3000] maximum shards open;
Mapping has failed, which will cause ElasticPress search results to be incorrect. Please click `Delete all Data and Start a Fresh Sync` to retry mapping.
```

I tried the `Delete all Data and Start a Fresh Sync`, but got the same message. This is a new install, so there is no indexed data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @jimmarion, can you please open a ticket through your ElasticPress.io account? Thanks!

**Comment by jimmarion** [comment]
Thank you, @felipeelia! I'm not sure how to do that, as I purchased ElasticPress.io through WPEngine's eCommerce package. Therefore, I don't have an ElasticPress.io account.

**Comment by jimmarion** [comment]
I'll work with the WPEngine team to resolve it, unless others have ideas to contribute.

**Comment by burhandodhy** [comment]
Hi @jimmarion,

WP Engine has already initiated a ticket on your behalf. We prefer to maintain all communication within that ticket, which is why I'm going to close this one.

Regards,
Burhan
