### ISSUE TITLE
Getting PHP warning by command: wp elasticpress sync

### ISSUE THREAD

**Issue by beljp** [10up/ElasticPress#3642]
### Describe your question

Hello, 

I've installed ElasticPress forr my woocommerce website. When im sync in the dashboard it's looking good. But when im checking Index Health page it kep sying: 

We could not find any data for your Elasticsearch indices. Maybe you need to [sync your content]

When i try to sync by SSH and command i do this: wp elasticpress sync then i get this warning: "PHP Warning:  Undefined array key "index" in /home/u64935p171151/domains/happypiercings.com/public_html/wp-includes/class-wp-list-util.php on line 170"
<img width="989" alt="Schermafbeelding 2023-09-17 om 13 21 41" src="https://github.com/10up/ElasticPress/assets/4181017/72edf814-a351-4e8f-b647-a8ae58f0329a">

Do you know what is the problem in this case?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beljp** [comment]
I have disabled all plugin's and set the theme to original. Still get these error.

**Comment by burhandodhy** [comment]
Hi @beljp,

Could you please run `wp elasticpress get-cluster-indices` command and share the result?   

Regards,
Burhan

**Comment by beljp** [comment]
Thanks for your reply:

{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [indices:monitor\/settings\/get] and User [name=web0157_u64935p171151, backend_roles=[zxcs_customers], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [indices:monitor\/settings\/get] and User [name=web0157_u64935p171151, backend_roles=[zxcs_customers], requestedTenant=null]"},"status":403}≠≠≠

I've added this to my wp-config.php

define( 'EP_INDEX_PREFIX', 'web0157_u64935p171151' );
define( 'ES_SHIELD', 'web0157_u64935p171151:password' );
define( 'EP_HOST', 'https://elasticstack.zxcs.nl:9200' );

My hosting company thinks im not working with the prefix or something 
You are using outside prefix: indices:monitor/recovery. It need to be like ; indices:web0157_u64935p171151monitor/recovery my hosting company says.

**Comment by felipeelia** [comment]
@beljp it actually requests `_cat/indices?format=json` to get a list of all your indices. If you need to change that to something else to make it compatible with your hosting company, you'll need to use the `ep_pre_request_args` filter changing it accordingly. As this is specific to your hosting company and how they handle their ES indices, I'm closing this ticket. Thanks
