### ISSUE TITLE
Compatibility with Cloudways

### ISSUE THREAD

**Issue by oferpbg0** [10up/ElasticPress#3644]
### Describe your question

currently Cloudways are providing ElasticSearch v7.17
per the ElasticPress plugin documentation, the max ElasticSearch version supported is v7.10

does this mean we cannot run ElasticPress plugin on our Cloudways hosted WP site?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickchomey** [comment]
It should work. In fact, I havent had issues when using elasticsearch 8.x

**Comment by felipeelia** [comment]
@oferpbg0 it should work indeed. In ElasticPress 5.0 we are going to remove the upper limit of ES-compatible versions, as we didn't have any problems with ES 8.x so far.
