### ISSUE TITLE
'Exclude from search results' not working as expected

### ISSUE THREAD

**Issue by rorytassell** [10up/ElasticPress#3645]
### Describe your question

Carry on from: https://github.com/10up/ElasticPress/pull/3100

I am trying to exclude a number of pages (all ideally), and the logical step would be to toggle 'ON' the setting for 'Exclude from search results'.

However, when I switch this on, the pages are still appearing in the search results.

<img width="611" alt="Screenshot 2023-09-20 at 14 20 50" src="https://github.com/10up/ElasticPress/assets/75035909/86982c2e-32ac-4020-ae2f-3b2fe840413c">

Now, for my setup it's a little complicated but not too wild...

I'm using Elementor as the page builder and JetEngine to create the listings. I have an Elementor 'Search Results' template setup, and in that template sits my JetEngine Listings grid which displays the results.

I initially thought that JetEngine Listing might be the issue, but I've testing it and the results are definitely showing from Elasticpress query and NOT JetEngine. This is due to setting JetEngine to display posts as 'archive posts' which is effectively using the native functions - I hope! lol.

Any ideas on this?

Happy to furnish with more information if you tell me what you need.

Many Thanks!
Rory

**UPDATE:** This is actually working as expected with one slight issue. If you went onto the search results via the usual empty query "?s=" the pages would show up. Now this might be just how it is, but it wasn't behaviour I was expecting. As when you toggle 'Exclude from search results' you'd expect it to never been seen in the search results page. Is that reasonable?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@rorydesign you have a good point there. If someone goes to "?s=" what should be displayed in your opinion? I'd expect nothing at all, as it is a search but we are not searching for anything. A page listing everything would be somewhere else, not attached to anything search-related.

**Comment by rorytassell** [comment]
> @rorydesign you have a good point there. If someone goes to "?s=" what should be displayed in your opinion? I'd expect nothing at all, as it is a search but we are not searching for anything. A page listing everything would be somewhere else, not attached to anything search-related.

I have two views on this. A lazy view, and a more detailed 'proper' option.

**The lazy version**
Simply display all posts in date order (as per someone's setup i.e. pages or posts excluded etc). Not ground-breaking, but easy to implement and avoids having to implement too much.

**The 'proper' job version**
If a user searches for nothing, then pointing them in the direction makes sense. Things like: "Have you tried searching 'Keyword'?" or "Here's what other people are searching for" - and have this trackable by the amount of queries match in any given period of time as an example.

OR Simply display an error/polite notice pointing out that no search query has been made and invite the user to try again - probably the most logical in terms of work involved and simplicity.
