### ISSUE TITLE
BUG: Sync from Backend locks up system

### ISSUE THREAD

**Issue by gwhitehead** [10up/ElasticPress#3646]
### Describe the bug

I have a unique situation where the website that is utilizing ElasticPress is a system that has a lot of data in a lot of ACF fields. The system is not able to fire a sync from the backend of the website. If a sync is attempted to be started from the backend of the website, the front end of the website shows console.log errors saying "wp is not defined". Sometimes I am able to stop the sync in the backend of the website but there are times where it does not stop. Attempting to stop via the CLI using "wp elasticpress stop-sync" doesn't stop a sync either. Which can be seen when after it saying it was able to fire the command, I try to initialize an index sync via the CLI and specifying a set of post ID's to limit the crawl it says that an index is currently in progress. 

Here is the console.log that shows when the sync is running. I believe this happens cause it is attempting to reach out to the elasticpress system and is not able to while the sync in the backend of the website is happening.
![console log-image](https://github.com/10up/ElasticPress/assets/620144/dcafd31a-8466-495d-b304-0c642f880590)

Is there a way to set the sync from the backend of the website to fire in blocks instead of attempting to queue the entire system or whatever it is doing right now? 

Yesterday I was able to finally get the sync to stop via the backend of the website which then allowed me to fire the syncing via the CLI. 

### Steps to Reproduce

Start a sync via the ElasticPress WordPress admin area.
Attempt to let it run.
WP CLI stop-sync command does not stop the sync if a sync has been started via the WordPress admin area.
Sync from admin area isn't able to process when there is a ton of data points.  Around 16k posts entries with around 570k postmeta data points

### WordPress and ElasticPress information
Can Provide if requested.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@gwhitehead some questions for you:
1. What is that custom.js file? That is not ElasticPress-related
2. Do you have any other errors in the console?
3. Once you've synced a site via CLI you shouldn't need to re-sync it again via dashboard. Do you have a need of periodically resync your site?

Answering your question
> Is there a way to set the sync from the backend of the website to fire in blocks instead of attempting to queue the entire system or whatever it is doing right now?

It does not try to load the entire queue, it does fire it in blocks (you can change the number of posts per cycle in the Settings screen.)

**Comment by gwhitehead** [comment]
1. The custom.js file has some customizations to limit the number of results and also customize the results shown via the ElasticPress popup/suggested results. After I was able to finalize the crawling manually via the CLI, the console error went away. I was just mentioning that this error was showing while the backend of the website was running an unsuccesful sync that it was unable to run this WP command.
2. no other console errors.
3. I am not sure how you do sync data, does it sync as data is saved into the elasticpress database? I believe it works like that but not 100% sure.  

The issue is the backend sync actually locks the ElasticPress system up and is no longer able to serve data via the suggested results. We have never been able to allow the sync to run via the backend of the website.

**Comment by felipeelia** [comment]
@gwhitehead the number you have in the "Content Items per Index Cycle" setting is the number of posts ElasticPress will load into memory to send to Elasticsearch. So, let's say you have 350 there, ElasticPress and WordPress will try to load and process 350 posts (calling all the necessary filters and actions), and send them to Elasticsearch. After that is done, EP and WP will load 350 more, and so on.

If, for whatever reason, processing that number of posts is too much, you should reduce that. Did you already try with something like 10 or 20? Also, if you are running full syncs (deleting all the data), all searches will fall back to MySQL, and in some cases that could be a problem for the website infrastructure.
