### ISSUE TITLE
current_user_can edit_post check in sync manager keeps system generated events from syncing

### ISSUE THREAD

**Issue by jeichorn** [10up/ElasticPress#366]
I created hooks to archive woocommerce orders, and everything works fine, except new orders aren't indexed because of that check at:

https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-sync-manager.php#L86

I'm not sure what the rational behind the check is, but it would be great to have some flexibility here.

**Comment by tlovett1** [comment]
Hmm, what role do users have that are indexing to ES?

**Comment by jeichorn** [comment]
The user isn't logged in at this point, so it has no roles.

**Comment by allan23** [comment]
@jeichorn Can you please provide some example code of what you are doing so we can reproduce?

**Comment by jeichorn** [comment]
@allan23 its pretty simple

```
// make orders indexable
add_filter( 'ep_indexable_post_types', function( $post_types )
{
    $post_types[] = 'shop_order';
    return $post_types;
});

add_filter( 'ep_indexable_post_status', function( $post_status )
{
    return array(
        'publish',
        'wc-cancelled',
        'wc-completed',
        'wp-failed',
        'wc-on-hold',
        'wc-pending',
        'wc-processing',
        'wc-refunded',
    );
});
```

There is a bunch more in add_filter( 'ep_post_sync_args', function( $args, $post_id ) and then of course on the query side, but none of that gets run because of the check.  The goal here is to index WooCommerce orders and search for them on the admin side, because all the postmeta fun makes order search super slow.

It just happens that the order objects get created without a logged in user (at least most of the time)

**Comment by allan23** [comment]
Thanks @jeichorn. I'll take a look to try to reproduce.

**Comment by allan23** [comment]
@jeichorn sorry about the delay, but it appears that you can use the 'woocommerce_payment_complete' action hook to force the new order to be indexed.

```
add_action( 'woocommerce_payment_complete', function($post_id) {
	if ( function_exists( 'ep_sync_post' ) ) {
		ep_sync_post( $post_id );
	}
} );
```

Let me know if that resolves your issue.

**Comment by jeichorn** [comment]
@allan23 I will give that a try, thanks
