### ISSUE TITLE
BUG: Missing dependencies

### ISSUE THREAD

**Issue by devhaozi** [10up/ElasticPress#3673]
### Describe the bug

Query Monitor shows EP missing dependencies.
![image](https://github.com/10up/ElasticPress/assets/115467771/493f6c94-6f52-4d6c-aaf0-1e505efdf973)

Cause by this:
![image](https://github.com/10up/ElasticPress/assets/115467771/7210410d-aba4-417f-9c9e-bec9da4989d1)

### Steps to Reproduce

1. Active EP and bbPress.
2. Go to site frontend.
3. See this error.

### Screenshots, screen recording, code snippet

![image](https://github.com/10up/ElasticPress/assets/115467771/493f6c94-6f52-4d6c-aaf0-1e505efdf973)

![image](https://github.com/10up/ElasticPress/assets/115467771/7210410d-aba4-417f-9c9e-bec9da4989d1)

### Environment information

Device: PC
OS: Windows 11
Browser: Edge

### WordPress and ElasticPress information

WordPress 6.3.1 network mode
EP 4.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@devhaozi I tried but I could not reproduce the problem. Are you seeing that same error in a clean installation?
