### ISSUE TITLE
No premission on shared ES server

### ISSUE THREAD

**Issue by beljp** [10up/ElasticPress#3674]
### Describe your question

Hello all, 

Thank you in advance for your help!

Im getting an error: Error: no permissions for [indices:monitor/settings/get]
After contact my hosting provider they tell me this: 

I need to change this [indices:monitor/settings/get] to [indices:[username]monitor/settings/get]

I need to add [username] because of shared es server. I have tested ep_pre_request_url and ep_pre_request_args but it isn't working. Does anybody here know how i can do this?

<img width="1204" alt="image" src="https://github.com/10up/ElasticPress/assets/4181017/883ef75a-1101-46d2-b008-a3f6ebf8b791">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beljp** [comment]
i have tried this already 

`// Voeg de ElasticPress-configuratie toe aan je theme's functions.php-bestand
add_filter('ep_pre_request_args', 'add_prefix_to_ep_indices');

function add_prefix_to_ep_indices($args) {
    // Voeg je prefix toe aan de indexnaam
    $prefix = 'web0157_u64935p171151'; // Vervang dit met je eigen prefix
    $args['index'] = $prefix . '_' . $args['index'];
    return $args;
}`

**Comment by beljp** [comment]
Even i tried this function: 


`// Voeg de ElasticPress-configuratie toe aan je theme's functions.php-bestand
add_filter('ep_index_post_request_args', 'custom_ep_index_post_request_args');

function custom_ep_index_post_request_args($args) {
    // Voeg de prefix toe aan de indexnaam
    $prefix = 'web0157_u64935p171151';
    $index_name = $args['index'];

    // Controleer of het al een prefix heeft om dubbele toevoeging te voorkomen
    if (strpos($index_name, $prefix) !== 0) {
        $args['index'] = $prefix . '_' . $index_name;
    }

    return $args;
}`

**Comment by beljp** [comment]
I have an update on my problem. It looks like the function 


`define( 'EP_INDEX_PREFIX', 'web0157_u64935p171151' );`


doesn't always work. See also image
<img width="1100" alt="Schermafbeelding 2023-10-03 om 12 17 24" src="https://github.com/10up/ElasticPress/assets/4181017/95609049-9253-40b0-8362-f9b1d69056d5">

**Comment by felipeelia** [comment]
@beljp as explained in #3642, ElsaticPress actually requests `_cat/indices?format=json` to get a list of all your indices. If something needs to be changed in that specific call, you must change it accordingly using the `ep_pre_request_args` filter.

Regarding the EP_INDEX_PREFIX constant, that is only used in calls that require an index name. That is not the case for those `_cat/indices` requests, so what you see in that screenshot is expected.

As we do not provide support for infrastructure-specific questions, I'm going to close this issue now.
