### ISSUE TITLE
Add Mapping for Users

### ISSUE THREAD

**Issue by johnpbloch** [10up/ElasticPress#369]

**Comment by bordoni** [comment]
It would be incredibly nice to see a "faster" way to search for users using roles. I mean, Currently it's a mess.

**Comment by beatelite** [comment]
Agree with this. I'll be using this for a user directory on the front end so sorting by custom user-registered taxonomies and roles would be great.

**Comment by dkotter** [comment]
Don't think this will get in for the 1.9 release, but any update here @johnpbloch?

**Comment by johnpbloch** [comment]
@dkotter The work in the `feature/user-search` branch has been refreshed up to the latest state of the `develop` branch. It's a little light on tests and could use more testing. It has near-parity with the WP_User_Query object, but I'm sure there are areas where that could be improved.

**Comment by tuanmh** [comment]
Would love to have this feature @johnpbloch. Would you be happy if I evaluate the branch and PR if needed?

**Comment by allan23** [comment]
@tuanmh Are you still interested in reviewing this branch for a PR?

**Comment by tuanmh** [comment]
@allan23 yes, sure, I'll have a look this weekend.

**Comment by tlovett1** [comment]
Update?

**Comment by tlovett1** [comment]
Pushing this from 2.0.
