### ISSUE TITLE
I get the error “Limit of total fields [???] in index [???] has been exceeded”

### ISSUE THREAD

**Issue by iqbrb11** [10up/ElasticPress#3694]
### Describe your question

hello..

when i do Sync Now It works for a limited period and then stops

**[illegal_argument_exception] Limit of total fields [5000] has been exceeded**

At the top is this message :

Your website content has more public custom fields than Elasticsearch is able to store. Check our articles about [Elasticsearch field limitations](https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-) and [how to index just the custom fields you need](https://elasticpress.zendesk.com/hc/en-us/articles/360052019111) before trying to sync.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @iqbrb11, the message displayed includes some links, which you've even copied here, that describe what causes the error and offers some solutions. Have you read them and tried any of the solutions? There's not much more that can be said than what's already in those links.
