### ISSUE TITLE
BUG: With WPML Elasticpress Plugin active all index have been deleted (also index not related to website)

### ISSUE THREAD

**Issue by cristianorevil** [10up/ElasticPress#3697]
### Describe the bug

Hi have a single elasticsearch server where are connected miltiples websites. Any website has our cutsom index. All works fine except if i have installed WPML Elasticpress plugin, in this casi if in one website i click on "Delete all Data and Start a Fresh Sync" button, all indexes (also indexes for the other websites are deleted). Without wpml elasticpress plugin installed all works fine (not all indexes are deleted). 

In the log if WPML Elasticrepss plugin is installed i see:
Starting delete and sync…

In the log if WPML Elasticrepss plugin is NOT installed i see:
Starting sync…

### Steps to Reproduce

Add 2 website to same elasticsearch server
Create index for 2 websites
Add WPML Plugin to both websites
in one website click on "Delete all Data and Start a Fresh Sync" button 
Check on the other website if the index still present

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @cristianorevil, can you please open an issue at https://github.com/OnTheGoSystems/wpml-elasticpress? The WPML team can help you with that.

For reference, the code that will need to be changed is in the [`clearAllIndices()`](https://github.com/OnTheGoSystems/wpml-elasticpress/blob/master/src/Manager/Indices.php#L169) method.
