### ISSUE TITLE
Terms, Protected Content, and the Gutenberg Tag/Parent Page Lookup

### ISSUE THREAD

**Issue by mgurtzweiler** [10up/ElasticPress#3699]
### Describe your question

I am attempting improve the admin search experience for our writers by using ElasticPress (EP) for "Protected content" (posts and media search) but am running into issues with the various Gutenberg dropdowns (Tags, Parent Pages specifically).

If i enable Terms EP is used for the AJAX call that runs when a user types into the "Add New Tag" field returns (what i am guessing is...) matches based on Title AND description and is limited to 20 items. Most of the time none of these results have the keyword in the title. The field does not show any matches because while the tags may match the keyword in the description field, the title does not contain the keyword. 

In this example we have a gaming focused site with around 3000 tags (we use tags for the Game, Publisher, Genre, etc) 

/wp-json/wp/v2/tags?context=view&per_page=20&_fields=id%2Cname&search=playstation&_locale=user

Response from API request: 

```
[
    {
        "id": 956,
        "name": "50 Cent: Bulletproof"
    },
    {
        "id": 2126,
        "name": "Angry Birds Trilogy"
    },
    {
        "id": 1515,
        "name": "Assassin's Creed Chronicles: China"
    },
    {
        "id": 1016,
        "name": "Astro Boy: The Video Game"
    },
    {
        "id": 843,
        "name": "Band Hero"
    },
    {
        "id": 525,
        "name": "Batman: Arkham VR"
    },
    {
        "id": 918,
        "name": "Bionic Commando Rearmed 2"
    },
    {
        "id": 2008,
        "name": "Bladestorm: The Hundred Years' War"
    },
    {
        "id": 1857,
        "name": "BlazBlue: Chrono Phantasma Extend"
    },
    {
        "id": 2027,
        "name": "Blitz: The League"
    },
    {
        "id": 1436,
        "name": "Borderlands: The Handsome Collection"
    },
    {
        "id": 1118,
        "name": "Call of Duty: Modern Warfare 2"
    },
    {
        "id": 1753,
        "name": "Crysis 3"
    },
    {
        "id": 2220,
        "name": "Dance Dance Revolution"
    },
    {
        "id": 765,
        "name": "Darkstalkers Resurrection"
    },
    {
        "id": 290,
        "name": "Dead Nation"
    },
    {
        "id": 344,
        "name": "Dead or Alive 5"
    },
    {
        "id": 1093,
        "name": "Dead or Alive 5: Last Round"
    },
    {
        "id": 394,
        "name": "Dead Space"
    },
    {
        "id": 2107,
        "name": "Dino Crisis"
    }
]
```

Each of these mention Playstation in the tag description but obviously not in the title. 

A similar issue presents itself with the "Parent Page" selector when creating or editing Pages. Matches are returned based on a search of all available data, but the dropdown only displays and expects a title match. Becomes an issue once you have more than the 100 pages the AJAX call is hardcoded to.

I've tried to disable EP from being used for REST and AJAX requests via this hook but it looks like this doesn't stop EP from being used. I've verified that the filter is returning false by the error logging.

```
add_filter('ep_is_integrated_request', 'fwp_disable_ep_for_rest', 3, 99);
function fwp_disable_ep_for_rest($is_integrated, $context,  $types ) {
	$doing_rest = defined( 'REST_REQUEST' );
	$doing_ajax = defined('DOING_AJAX');
	if($doing_rest or $doing_ajax) {
		error_log("REST_REQUEST[{$doing_rest}] / DOING_AJAX[{$doing_ajax}]: {$context}");
		return false;
	}
	return $is_integrated;
}
```

I'm running out of ideas here. Any suggestions? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mgurtzweiler** [comment]
If i disable Terms in the Features this is the result of a tag search for "play" 

/wp-json/wp/v2/tags?context=view&per_page=20&_fields=id%2Cname&search=play&_locale=user

```
[
    {
        "id": 45,
        "name": "Action role-playing"
    },
    {
        "id": 5466,
        "name": "free-to-play"
    },
    {
        "id": 1110,
        "name": "NBA 2K Playgrounds 2"
    },
    {
        "id": 2156,
        "name": "NBA Playgrounds"
    },
    {
        "id": 5441,
        "name": "play"
    },
    {
        "id": 2985,
        "name": "PlayerUnknown's Battlegrounds"
    },
    {
        "id": 2371,
        "name": "PlayerUnknown's Battlegrounds (PUBG)"
    },
    {
        "id": 201,
        "name": "Playground Games"
    },
    {
        "id": 17,
        "name": "PlayStation"
    },
    {
        "id": 134,
        "name": "PlayStation 2"
    },
    {
        "id": 25,
        "name": "PlayStation 3"
    },
    {
        "id": 8,
        "name": "PlayStation 4"
    },
    {
        "id": 2417,
        "name": "PlayStation 4 Pro"
    },
    {
        "id": 249,
        "name": "PlayStation 5"
    },
    {
        "id": 1746,
        "name": "PlayStation All-Stars Battle Royale"
    },
    {
        "id": 487,
        "name": "PlayStation Network"
    },
    {
        "id": 2960,
        "name": "PlayStation Plus"
    },
    {
        "id": 343,
        "name": "PlayStation Portable"
    },
    {
        "id": 586,
        "name": "PlayStation TV"
    },
    {
        "id": 120,
        "name": "PlayStation Vita"
    }
]
```

I've tried disabling EP for everything via this filter, but it doesn't actually disable EP for these dropdown searches. 

```
add_filter('ep_elasticpress_enabled', function( $enabled, $query ) { 
	error_log('returning false for ep_elasticpress_enabled');
	return false;		
}, 2, 11);
```

**Comment by mgurtzweiler** [comment]
This seems to fix the issue with tags but seems pretty heavy handed. Wish there was a way to better detect that the rest request was looking only at name (well ID and name according to the query params in `/wp-json/wp/v2/tags?context=view&per_page=20&_fields=id%2Cname&search=play&_locale=user` => &_fields=id,name but I don't think EP has ID as a searchable field) and correct the fields to match. 

```
// fix it so tag lookups work in the editor
add_filter('ep_term_search_fields', 'fwp674_only_search_name_for_rest_request', 2, 10);
function fwp674_only_search_name_for_rest_request($search_fields, $query_vars) {
	if(defined( 'REST_REQUEST' ) && REST_REQUEST) {
		$search_fields = array('name');
	}
	return $search_fields;
}
```

**Comment by felipeelia** [comment]
Hi @mgurtzweiler, thanks for opening the issue and giving so many details about it! The `_fields=id%2Cname` part doesn't mean "searchable fields" but, in fact, "returned fields", so we couldn't use that. I do agree that EP should detect that query and search as WP would search. We will give it a look and try to add it to our roadmap (perhaps EP 5.1.0)

In the meantime, your solution (although yeah, a bit heavy-handed) should be the way to work around the issue.
