### ISSUE TITLE
Filtering by an array of blog IDs yields no results in 1.6 [Multisite]

### ISSUE THREAD

**Issue by goblindegook** [10up/ElasticPress#370]
It seems that passing an array of blog IDs to the `sites` query var is no longer possible in 1.6 on a multisite install, only the `all` and `current` keywords yield results. If I provide an array, I get an empty result set.

I reverted the plugin to 1.5.1 and can confirm that search results are being returned correctly using that version.

**Comment by allan23** [comment]
Thanks @goblindegook, we'll take a look.

**Comment by natostanco** [comment]
actually it returns values from the current blog only

**Comment by tlovett1** [comment]
Hmm, the test seems to be passing - https://github.com/10up/ElasticPress/blob/develop/tests/test-multisite.php#L225

**Comment by allan23** [comment]
@goblindegook I cannot reproduce your issue. Can you please provide the code you are using for this query?
