### ISSUE TITLE
Support of Latest Elastic Release 8.1.0

### ISSUE THREAD

**Issue by Alexpalix** [10up/ElasticPress#3705]
### Describe your question

Hi 10Up

How are you? I am non-tech. I just wondered does it matter that you support Elastic up to vs7 when they have now released v8? Or can i use your plugin with vs8 without any issue?

Kind regards

Alex

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @Alexpalix, we've received some test results (like #3141, for example) saying it works fine with Elasticsearch 8. In fact, we are changing the way we phrase our requirements in ElasticPress 5.0: we will keep a minimum version and remove the maximum, just stating ES 7.x is the version we officially test the plugin.

If you see anything while using Elasticsearch 8, please let us know!
