### ISSUE TITLE
Index Health keeps reporting that the indices do not exist

### ISSUE THREAD

**Issue by jordijansen** [10up/ElasticPress#3710]
### Describe your question

Hi,

The Index Health keeps reporting:

We could not find any data for your Elasticsearch indices. Maybe you need to [sync your content](https://hx96z8m3n2-staging.onrocket.site/wp-admin/admin.php?page=elasticpress-sync)?

If I fully sync Elasticpress all the data shows up on our Elasticsearch server, no problem there. But incremental syncing is also not working.

I've tried uninstalling the plugin and installing it again, no luck. Any thing I can try out? I see no errors in the logging (WP_DEBUG is on).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@jordijansen can you please share your ElasticPress Status Report with us? Also, the output of the `wp elasticpress get-cluster-indices --pretty` command can help us to get with which names the indices are being created. Thanks

**Comment by jordijansen** [comment]
```
wp elasticpress get-cluster-indices --pretty
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
{
    "error_id": "a5a6e6df-b0d9-48e1-8a17-54204006e952",
    "errors": [
        {
            "code": 90,
            "message": "Unauthorized access"
        }
    ]
}
```

```
Removed
```

**Comment by felipeelia** [comment]
Thanks @jordijansen. As you can see, you probably have an access problem at hand. ElasticPress is trying to get the indices you have in your server but it can't. As problems with infrastructure are not part of our scope in this repository I'm going to close the issue for now but feel free to leave any comments, and hopefully, others with the same problem can join the conversation.

**Comment by jordijansen** [comment]
Ok, can you tell me what Elasticsearch operation elasticpress is trying to do when I call get-cluster-indices? So I can check with our Elasticsearch provider.

**Comment by felipeelia** [comment]
Sure, it is a request to the `_cat/indices?format=json` endpoint:

https://github.com/10up/ElasticPress/blob/develop/includes/classes/Command.php#L423
https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L1771

**Comment by jordijansen** [comment]
[felipeelia](https://github.com/felipeelia) do you have an overview of all endpoints used by Elasticpress?

Our elastic search provider is asking for this (so they potentially allow those endpoints).
