### ISSUE TITLE
Mapping Failed Error in ElasticPress Plugin Configuration with AWS OpenSearch

### ISSUE THREAD

**Issue by akshaydalvi4** [10up/ElasticPress#3715]
### Describe your question

Hello, I have installed the ElasticPress (Version [4.7.2)]) plugin on my WordPress site, and I am trying to configure this plugin with AWS OpenSearch. I have added all necessary information in the plugin configuration, but after every attempt, I am encountering an error (Mapping failed. In the Shingle TokenFilter, the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to [3], but it is [4]. This limit can be set by changing the [index.max_shingle_diff] index level setting). I have tried changing the index and other settings, but the error persists. I have also attempted to delete all synced data, but the same error occurs. Please help me in resolving this problem or guide me if there are specific settings I need to adjust

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tdwesten** [comment]
Hi @akshaydalvi4,

We encountered the same error while using opensearch v2.11.0 for local development. The error was resolved by manually setting "index.max_shingle_diff" to 10. However, a new error occurred:

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "The [standard] token filter has been removed."
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "The [standard] token filter has been removed."
    },
    "status": 400
}
```

Let me know if you need further assistance.

**Comment by akshaydalvi4** [comment]
The error was resolved by manually setting the "index.max_shingle_diff." Can you please guide me on how to resolve this manually? I am using WordPress 6.3.2 and ElasticPress version 4.7.2. Provide detailed steps to resolve this error and configure OpenSearch with the ElasticPress plugin

**Comment by tdwesten** [comment]
Hi @akshaydalvi4, 

We did this: 
<img width="1724" alt="Scherm­afbeelding 2023-10-20 om 13 47 11" src="https://github.com/10up/ElasticPress/assets/224501/ac8247b0-27ae-41b8-8fc2-e0516607fc5d">

**Comment by felipeelia** [comment]
Hi @akshaydalvi4 and @tdwesten,

You can change the max_shingle_diff value using the `ep_max_shingle_diff` filter. Something like this:

```php
add_filter( 'ep_max_shingle_diff', function() { return 10; } );
```

@tdwesten were you able to fix the other error you got?

**Comment by tdwesten** [comment]
@felipeelia, thank you for your response.

The `ep_max_shingle_diff` doesn't work due to the use of the `pre-5-0.php` mappings. Because the version of Opensearch is `2.9.0` see the version check overhere: https://github.com/10up/ElasticPress/blob/5bad1550ee55a0677cae8c23e60eac273987f13a/includes/classes/Indexable/Post/Post.php#L322

<img width="426" alt="Scherm­afbeelding 2023-10-20 om 16 40 23" src="https://github.com/10up/ElasticPress/assets/224501/b65ac70d-6693-4974-b49d-13d49ff0b437">

When i force ElasticPress to use the `7-0.php` mapping it works.

**Comment by felipeelia** [comment]
@tdwesten oh, you should have this code added to your codebase: https://elasticpress.zendesk.com/hc/en-us/articles/16677288265741-Compatibility (perhaps that even dismisses the need of adding the first code I shared)

**Comment by tdwesten** [comment]
Darn, I missed that!

```
Adding post mapping…
Success: Mapping sent
Adding user mapping…
Success: Mapping sent
```

**Comment by tdwesten** [comment]
For those who find this through the Google search engine, when using OpenSearch, you need to set the `ep_elasticsearch_version` to `7.10`.

```php
add_filter(
    'ep_elasticsearch_version',
    function() {
        return '7.10';
    }
);
```

**Comment by felipeelia** [comment]
Awesome, @tdwesten! With this missing piece in place, I'm closing the issue now. Thanks!

**Comment by amuhareb** [comment]
> For those who find this through the Google search engine, when using OpenSearch, you need to set the `ep_elasticsearch_version` to `7.10`.
> 
> add_filter(
>     'ep_elasticsearch_version',
>     function() {
>         return '7.10';
>     }
> );

You rock! thank you.
