### ISSUE TITLE
On upgrade ensure feature settings are the correct type

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#3716]
### Is your enhancement related to a problem? Please describe.

In Features some settings use an Enabled/Disabled control, but these are inconsistently saved as either a 0 or 1 string, or a boolean. When implementing the settings schema these were made consistent as 0 or 1 strings. As part of the 5.0.0 update we will need to update a user's feature settings to make sure that these settings have the correct value.

The process should be to loop over the setting schema for each feature, and update the setting values based on the setting `type`.

- `checkbox` settings should have a string value. Any found boolean values should be updated to a string value of 0 or 1.
- `radio` settings should have a string value. Any found boolean values should be updated to a string value of 0 or 1.

The changes may require updating the code the checks these settings to check for the appropriate value. Some of this was already done as part of #3712 to solve failing tests, but this adjustment may still need to be made anywhere if there's gaps in the test coverage.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Closed by #3730
