### ISSUE TITLE
Featured image is not pulled

### ISSUE THREAD

**Issue by Keithdatascience** [10up/ElasticPress#3723]
### Is your enhancement related to a problem? Please describe.

I tried with related posts, but featured images are not pulled. Only text bodies, titles are available. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @Keithdatascience,

It seems like you might be utilizing the ElasticPress find_related() function. If that's the case, you can get the thumbnail by passing the related post ID to the WordPress function [get_the_post_thumbnail_url()](https://developer.wordpress.org/reference/functions/get_the_post_thumbnail_url/)

Regards,
Burhan
