### ISSUE TITLE
Update Screenshots for ElasticPress 5 for WP.Org Listing

### ISSUE THREAD

**Issue by anjulahettige** [10up/ElasticPress#3732]
### Is your enhancement related to a problem? Please describe.

As we're changing the user interface of the plugin in version 5, we need to update the [screenshots](https://github.com/10up/ElasticPress/tree/develop/.wordpress-org) used for the [WordPress.Org Plugin Listing](https://wordpress.org/plugins/elasticpress/). 

This should happen once the copy for the new UI has been finalized. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Updated in [00eaa5b](https://github.com/10up/ElasticPress/pull/3717/commits/00eaa5b89b6bf48b95bde24fa7c767781c0ddab6)
