### ISSUE TITLE
ep_integrate doesn't seem to function

### ISSUE THREAD

**Issue by donbowman** [10up/ElasticPress#3742]
[dbg.log](https://github.com/10up/ElasticPress/files/13222163/dbg.log)
### Describe your question

On my site when i do ?s=foo, it goes through elasticpress w/o trouble.
Now, trying to use with "the plus blocks for gutenberg" and their search block, I have modified the WP_Query to add the `ep_integrate => true`, the array below is pased to WP_Query.
However, this goes through mysql (i can tell this from the logs on my elastic search).

This is coming into wordpress via /wp-admin/admin-ajax.php, to action=tpgb_search. Its in the tpgb_search action i've made the change. I've printed the array as it constructs the WP_Query, so i know its there.

Any suggestion on how to debug this? I have attached some trace I added in `elasticpress_enabled()`, namely dumping the $query out at the top of the function.

```
Array
(
    [post_type] => page
    [suppress_filters] =>
    [ignore_sticky_posts] => 1
    [orderby] => relevance
    [posts_per_page] => 5
    [post_status] => publish
    [ep_integrate] => 1
    [post__in] => Array
        (
            [0] => 0
        )

    [tax_query] => Array
        (
            [relation] => AND
            [0] => Array
                (
                    [0] => Array
                        (
                            [taxonomy] => category
                            [field] => term_id
                            [terms] => Array
                                (
                                    [0] => 900086
                                    [1] => 1140036
                                    [2] => 990037
                                    [3] => 960036
                                )

                            [include_children] => 1
                            [operator] => IN
                        )

                )

        )

    [offset] =>
)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @donbowman,

The code executed in the AJAX callback operates within the WordPress admin interface. Simply adding `ep_integrate => 1` to WP_Query is insufficient because ElasticPress interprets it as an admin dashboard query.

To enable ElasticPress in the admin ajax, you must set the `ep_ajax_wp_query_integration` filter to `true` https://10up.github.io/ElasticPress/ep_ajax_wp_query_integration.html

Regards,
Burhan
