### ISSUE TITLE
Strip tags when indexing meta fields that contains html markup

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#3751]
### Describe your question

Nice work on the 5.0 meta updates.

I have a variety of ACF WYSIWYG text fields stored in post meta. Those fields contain HTML markup, sometimes quite a bit of it, and we use those meta fields for related posts and searches.

I see in the ElasticPress Debug bar that the value for these meta fields is simply the raw value of the meta field, including all of the HTML tags. I don't want HTML tags used for matching in searches. For post content, there is a plain version that can be used that strips all tags. Is there an equivalent for strip tags on meta fields or a filter where I need to prepare the meta before indexing to strip all tags?

A similar but related question for serialized meta fields. I have a meta field that stores an array, so the database has a serialized string. Looking at the Debug Bar results, the value of this meta field shows the serialized string. Once again, I don't want searches to match on characters that are part of the serialization.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @kevinlisota,

You can use either the [`ep_prepare_meta_data`](https://github.com/10up/ElasticPress/blob/5.0.0/includes/classes/Indexable/Post/Post.php#L871) filter or [`ep_prepared_post_meta`](https://github.com/10up/ElasticPress/blob/5.0.0/includes/classes/Indexable/Post/Post.php#L904) to achieve that.

For HTML tags you can use WP's `wp_strip_all_tags` function (as we do when Instant Results is active [here](https://github.com/10up/ElasticPress/blob/5.0.0/includes/classes/Feature/InstantResults/InstantResults.php#L753).) For serialization, that generally shouldn't be a problem, but you can always unserialize it and json_encode it instead.
