### ISSUE TITLE
Problem with connecting host

### ISSUE THREAD

**Issue by nitinprakash8** [10up/ElasticPress#3753]
### Describe your question

I was trying to connect ElasticSearch cloud platform with the plugin but it does throws error that error in connecting with host.
Please let me know how i can get connected with my ES and sync the WP data to index.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@nitinprakash8 you will need to make sure the webserver running your website can connect to your Elasticsearch server, and the best way to do that is to send a curl call in the server terminal. From there you'll be able to debug it and fix whichever connection problem may be happening.

As infrastructure configuration is not part of the scope of this repository, I'm closing the issue now. Thanks
