### ISSUE TITLE
BUG: cli sync issue

### ISSUE THREAD

**Issue by mindaugasbudreika** [10up/ElasticPress#3754]
### Describe the bug

I'm using wp cli to periodically sync WooCommerce products but it occasionally fails without any indication of what went wrong. It happens at least once or twice a week.

Here is the sync command I execute (as cron job, from shell script):
`wp elasticpress sync --quiet --per-page=10 --include=$POST_IDS`

$POST_IDS is a list of products ids that have to be updated.

Here is output from `wp elasticpress get-ongoing-sync-status --pretty` I've ran today (2023-11-06):
```
{
    "method": "cli",
    "put_mapping": false,
    "offset": 0,
    "pagination_method": "offset",
    "start": true,
    "sync_stack": [],
    "network_alias": [],
    "start_time": 1698969849.9410069,
    "start_date_time": "2023-11-03T03:04:09+03:00",
    "totals": {
        "total": 0,
        "synced": 0,
        "skipped": 0,
        "failed": 0,
        "total_time": 0,
        "errors": []
    },
    "current_sync_item": {
        "url": "https:\/\/www.domain.com",
        "blog_id": 1,
        "indexable": "post",
        "put_mapping": false,
        "found_items": 3,
        "total": 3,
        "synced": 0,
        "skipped": 0,
        "failed": 0,
        "errors": [],
        "shown_skip_message": true
    },
    "from": 0,
    "found_items": 3,
    "indexing": true,
    "items_indexed": 0,
    "url": "https:\/\/www.domain.com",
    "total_items": 3,
    "slug": "post"
}
```

And here is the output of the `wp elasticpress get-last-sync ---pretty`:
```
{
    "total": 7,
    "synced": 7,
    "skipped": 0,
    "failed": 0,
    "total_time": 0.54802298545837402,
    "errors": [],
    "end_date_time": "2023-11-03T03:03:11+03:00",
    "start_date_time": "2023-11-03T03:03:10+03:00",
    "end_time_gmt": 1698969791,
    "method": "cli"
}
```

I

### Steps to Reproduce

I'm not aware of any steps to trigger this issue on demand.

### WordPress Environment ###
wp_version: 6.2
home_url: https://www.domain.com
site_url: https://www.domain.com/wp
is_multisite: false
theme: SV Child (1.0.0)
parent_theme: Sage Starter Theme (8.5.1)
plugins: Advanced Custom Fields PRO (6.1.6), Badge control system (2.0.0), ElasticPress (4.4.1), ElasticPress - Custom Autosuggest (2.0.3), Flat Rate per State/Country/Region for WooCommerce (2.8), FormCraft (3.9.3), Formcraft Events Add-On (1.0.0), FormCraft KD Theme Add-On (1.0.4), Formcraft Omnisend Add-On (1.0.0), FormCraft reCaptcha Add-On (1.8), Formcraft Webhooks Add-On (1.0.0), Google Tag Manager (1.0.3), Gravitec.net - Web Push Notifications (2.9.0), GuardGiant Brute Force Protection (2.2.4), Insert Headers and Footers (1.6.0), Klarna Checkout for WooCommerce (2.11.4), Klarna Order Management for WooCommerce (1.8.1), Custom After Cart Popup (1.2.1), Custom Cash on Pickup (1.0.0), Custom Checkout Cross Sell (3.1.1), Custom Coffee drinks (1.1.0), Custom Coffee passport (1.1.0), Custom Coupon Manager (1.3.0), Custom custom cat banner (2.1), Custom Delivery Time (1.0.0), Custom Extended Discount Coupons (2.0.2), Custom Extended Warranty (1.0.2), Custom FAQs (1.0.1), Custom Google Analytics (1.1.0), Custom google FAQ (1.2.0), Custom Instagram Posts (1.0.2), Custom Marketing Tools (1.0.0), Custom Merchant Feeds (3.0.0), Custom Miele Smart Advisor (1.0.2), Custom NPS Export (3.0.0), Custom Product Compare (1.2.1), Custom Product Cross Sells (1.0.0), Custom Product FAQs (1.1.0), Custom QR (1.0.0), Custom REST API (1.4.0), Custom Setup (1.0.0), Custom Taste Guide (1.1.0), Custom Top Banners (1.1.0), Custom Video List (1.1.0), Custom VIP Membership (1.2.0), Custom Webhooks (1.0.0), Custom WooCommerce Coffee Machines (1.2.2), Custom WooCommerce Reviews (1.3.0), Mollie Payments for WooCommerce (7.3.12), Omnisend for Woocommerce (1.13.3), Page Builder by SiteOrigin (2.16.5), Product Filters for WooCommerce (1.4.1), Redis Object Cache (2.4.3), REST API Log (1.6.8), Safe SVG (2.0.3), SiteOrigin Premium (1.9.0), SiteOrigin Widgets Bundle (1.31.0), TinyMCE Advanced (5.0.0), Watu PRO (6.7.4), WooCommerce (7.9.0), WooCommerce Address Book (2.5.0), Woocommerce Category (1.2.0), WooCommerce Coupon Generator (1.2.0), Woocommerce Gateway Invisible (1.1.0), Woocommerce Products Per Page (1.2.7), WooCommerce Social Login (2.13.0), Woo Discount Rules (2.6.0), Woo Discount Rules PRO 2.0 (2.6.0), WordPress Importer (0.7), WordPress Sentry (6.27.0), WP Mail SMTP (3.1.0), WP Rocket (3.12.0.5), Yoast Duplicate Post (4.5), and Yoast SEO (20.3)
revisions: all

### Server Environment ###
php_version: 8.1.24
memory_limit: 40M
timeout: 120

### Domain — https://www.domain.com/wp ###
product_count: 4,128
ep_custom_autosuggest_count: 151
product_meta_keys: 11
ep_custom_autosuggest_meta_keys: 4
total-all-post-types: 15
distinct-meta-keys: _sku, total_sales, _weight, _length, _width, _height, _stock_status, _wc_average_rating, _wc_review_count, product_eol, search_thumbnail, ep_exclude_from_search, url, autosuggest_weight, and autosuggest_thumbnail

### Settings ###
host: https://elastic2.domain.com:443
index_prefix: 
language: sv_SE
per_page: 15
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### domaincomwp-post-1 ###
health: yellow
status: open
index: domaincomwp-post-1
uuid: _gW8anEdRgSdgbYTrxMLrg
pri: 5
rep: 1
docs.count: 4265
docs.deleted: 913
store.size: 34.2mb
pri.store.size: 34.2mb
total_fields_limit: 5000

### 2023/11/03 3:03:10 am (In Progress) ###
method: WP-CLI
end_date_time: 2023/11/03 3:03:11 am
total_time: 0 hours, 0 minutes, 1 second
total: 7
synced: 7
skipped: 0
failed: 0
errors: array (
)

### Autosuggest ###
active: true
autosuggest_selector: ep-autosuggest
endpoint_url: https://www.domain.com/es-search
force_inactive: false
trigger_ga_event: 0

### Custom Autosuggest Items ###
active: true
autosuggest_selector: ep-autosuggest
endpoint_url: https://www.domain.com/es-search
force_inactive: false
items: 10
show_thumbnails: 1

### Custom Search Results ###
active: true
force_inactive: false

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: true
highlight_excerpt: 0
highlight_tag: span

### WooCommerce ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mindaugasbudreika** [comment]
I'm happy to setup additional logging or do troubleshooting on my own but I need some pointers on where to start.

**Comment by felipeelia** [comment]
@mch0lic, when you say "it occasionally fails without any indication of what went wrong", how do you know it failed? Also, instead of `--quiet`, is there any reason why you are not running it with `--show-errors` and sending the output to a log file?

**Comment by mindaugasbudreika** [comment]
@felipeelia 

> how do you know it failed?

Autosuggest dropdown stops working. I haven't checked if actual search page is still getting results from elastic, I will do it next time, but there are a few thousand products and they regularly updated (stock, price, info) via WooCommerce REST API. It would be nearly impossible that nothing has to be updated for 3 days. I would expect last (re)index to be within an hour at any time of the day.

PS: This is what I run to get search working again.
`wp elasticpress clear-sync` 
`wp elasticpress sync --per-page=50`

> Also, instead of --quiet, is there any reason why you are not running it with --show-errors and sending the output to a log file?

Flag was set to reduce logging when it worked well, but it's worth enabling error logging now and see if anything gets logged.

Any other tips? It might take up to a week before it crashes again, so if there are any other options for logging I could try to switch them on as well.

Thanks!

**Comment by felipeelia** [comment]
Hi @mch0lic,

You can now remove that `clear-sync` call and simply add a `--force` flag to the sync command (it would become `wp elasticpress sync --per-page=50 --force --yes`.)

Having the output of the sync will help, and also, any new entries in your error-log that would match with the time a sync was performed.
