### ISSUE TITLE
configuring ElasticSearch to work with ElasticPress in wordpress light sail instance

### ISSUE THREAD

**Issue by rhusny** [10up/ElasticPress#3756]
### Describe your question

1. I installed Elastic search into wordpress lightsail instance with the URL wegmanbrothers.com runing on Wordpress version 6.3.2, PhP Version 8.1.16,Server version 10.6.12-MariaDB and Client version mysqlnd 8.1.16 using the command [sudo apt install elasticsearch]
and then configured [sudo nano /etc/elasticsearch/elasticsearch.yml] to have [network.host: 127.0.0.1] and [http.port: 9200].
2. I then installed ElasticPress plugin in the wordpresss admin lightsail instance and set the ElasticSearch Host Url= [http://127.0.0.1:9200 ](http://127.0.0.1:9200/) and finished the set up including the indexing.
3. However when searching the title of a specific post , the search result are; it shows all the posts instead of the individual post searched.
4 When I check on the Elastic press Status Report I get a failed query as attached on the file bellow
[elasticpress-report.txt](https://github.com/10up/ElasticPress/files/13307130/elasticpress-report.txt)
May you help me with assistance regarding this.
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickchomey** [comment]
This issue is almost certain to get closed. 

But you should try using the elasticpress debug bar extension to get more info.

https://elasticpress.zendesk.com/hc/en-us/articles/360050720172-Using-the-Debug-Bar-ElasticPress-Plugin

**Comment by felipeelia** [comment]
Those requests are timing out @rhusny (upgrading your ElasticPress version to 5.0 will give you a better message every time it happens.) That indicates a problem with the communication of your webserver and your Elasticsearch instance.

As infrastructure problems are not part of the scope of this repository (you were right, @nickchomey!), I'm going to close the issue now but in addition to that article 👆, you can also SSH into your terminal and make sure 127.0.0.1:9200 is responding properly.
