### ISSUE TITLE
BUG: Persistent "ElasticPress queries failed" Warning After Plugin Update to Version 5.0

### ISSUE THREAD

**Issue by rafaucau** [10up/ElasticPress#3757]
### Describe the bug

After updating the ElasticPress plugin to version 5.0, I've encountered a persistent warning in the WordPress Dashboard stating: "Some ElasticPress queries failed in the last 24 hours. Please visit the Status Report page for more details."

While the plugin appears to be functioning normally, the recurring warning is causing some concern. Attached are screenshots detailing the issue, with the failed query log indicating a "request body is required" error with a 400 HTTP status code.

### Steps to Reproduce

I don't know

### Screenshots, screen recording, code snippet

![image](https://github.com/10up/ElasticPress/assets/25438601/85bbdc1e-386e-40e2-85f5-0c3f63ccbe9f)
![2023-11-11 101145](https://github.com/10up/ElasticPress/assets/25438601/9df205a3-5a5b-4d3f-95d2-892e74aec9ab)

### WordPress and ElasticPress information

<details>

<summary>Status Report:</summary>

### https://**********/?post=657021&action=edit&meta-box-loader=1&meta-box-loader-nonce=3ac2b79204&_locale=user (2023-11-11 09:54:38) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST https://***.***.***.***:9200/**********wp-post-1/_bulk
request_id: 553b1ff5eb7a4d269935c84327c209b1
query_time: 202.9881477356
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://**********/?post=657021&action=edit&meta-box-loader=1&meta-box-loader-nonce=3ac2b79204&_locale=user (2023-11-11 09:53:58) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST https://***.***.***.***:9200/**********wp-post-1/_bulk
request_id: 34354b28357c466488d532a0e5259645
query_time: 203.01198959351
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://********** (2023-11-11 09:47:01) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST https://***.***.***.***:9200/**********wp-post-1/_bulk
request_id: 32aefb3774be494682c704e394760e8f
query_time: 202.84414291382
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://**********/?post=657021&action=edit&meta-box-loader=1&meta-box-loader-nonce=fc5e493dfc&_locale=user (2023-11-11 09:45:56) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST https://***.***.***.***:9200/**********wp-post-1/_bulk
request_id: d8c0c551277f45ef941d96fe165e5068
query_time: 202.68297195435
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://********** (2023-11-11 09:17:20) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST https://***.***.***.***:9200/**********wp-post-1/_bulk
request_id: 550e5f6a56a2461eab8408dbde00bbcc
query_time: 203.04393768311
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### WordPress Environment ###
wp_version: 6.3.2
is_multisite: false
plugins: Code Syntax Block (3.1.1), Conditional Menus (1.2.3), Disqus for WordPress (3.0.23), ElasticPress (5.0.0), GN Publisher (1.5.10), Index WP MySQL For Speed (1.4.14), LiteSpeed Cache (5.7.0.1), oEmbed Infogram (1.1.3), oEmbed Plus (1.7), Performant Translations (1.0.6), PWA (0.7.1), Rank Math SEO (1.0.205), Rank Math SEO PRO (3.0.48), Redis Object Cache (2.4.4), Safe SVG (2.2.1), Share a Draft (1.5), Simple Local Avatars (2.7.5), Term Management Tools (2.0.1), Two Factor (0.8.2), Yoast Duplicate Post (4.5)
revisions: all

### Server Environment ###
php_version: 8.2.8
memory_limit: 256M
timeout: 300

## Indexable Content ##

post_count: 58,981
page_count: 11
youtube_count: 371
attachment_count: 225,627
acf-taxonomy_count: 0
acf-post-type_count: 0
acf-ui-options-page_count: 0
acf-field-group_count: 6
acf-field_count: 21
acp_deals_count: 88
rm_content_editor_count: 1
rank_math_schema_count: 16
post_meta_keys: 0
page_meta_keys: 0
youtube_meta_keys: 0
attachment_meta_keys: 0
acf-taxonomy_meta_keys: 0
acf-post-type_meta_keys: 0
acf-ui-options-page_meta_keys: 0
acf-field-group_meta_keys: 0
acf-field_meta_keys: 0
acp_deals_meta_keys: 0
rm_content_editor_meta_keys: 0
rank_math_schema_meta_keys: 0
total-all-post-types: 0
distinct-meta-keys: 

### Settings ###
host: https://***.***.***.***:9200
index_prefix: 
language: site-default
per_page: 1200
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### **********wp-post-1 ###
health: yellow
status: open
index: **********wp-post-1
uuid: zeAVRriZS0edJ9N6BrjELQ
pri: 5
rep: 1
docs.count: 285119
docs.deleted: 29110
store.size: 993.1mb
pri.store.size: 993.1mb
total_fields_limit: 5000
analyzer_language: polish
stop_language: _polish_
snowball_language: English

### 2023/11/08 4:17:54 pm ###
method: WP-CLI
is_full_sync: No
end_date_time: 2023/11/08 4:43:43 pm
total_time: 0 hours, 25 minutes, 49 seconds
total: 58928
synced: 58928
skipped: 0
failed: 0
errors: array (
)
trigger: 
final_status: success

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple

weighting: array (
  'post' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 74,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 10,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'terms.post_tag.name' => 
    array (
      'enabled' => true,
      'weight' => 12,
    ),
    'terms.category.name' => 
    array (
      'weight' => 17,
      'enabled' => true,
    ),
    'meta._wp_page_template.value' => 
    array (
      'weight' => 0,
      'enabled' => false,
    ),
  ),
  'page' => 
  array (
    'post_title' => 
    array (
      'weight' => 10,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'terms.category.name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
  ),
  'youtube' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'terms.post_tag.name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'terms.category.name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
  'rm_content_editor' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
  ),
)

### Protected Content ###
active: true
force_inactive: false

### Related Posts ###
active: true
force_inactive: false

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Thanks for opening the issue @rafaucau! I'm closing this one in favor of #3755 that describes the same bug.
