### ISSUE TITLE
Error connecting to Elastic Cloud with Elasticsearch 7.17.15

### ISSUE THREAD

**Issue by jerasokcm** [10up/ElasticPress#3772]
### Describe the bug

I'm unable to connect to the ElasticSearch instance v7.17.15, running on Elastic Cloud. An error raises.

### Steps to Reproduce

1. Install ElasticPress plugin
2. Go to the setting of the plugin
3. Fill the host URL field with the Elastic Cloud one: https://mytest.kb.us-east-2.aws.elastic-cloud.com:9243 
4. Set variables in the wp-config.php file: 
define('ES_SHIELD', 'elastic:EEwkctQ3DxUUUfaj9GbOYD59');. 
Also tried to define the host there: 
define('EP_HOST', 'https://mytest.kb.us-east-2.aws.elastic-cloud.com:9243');
5. The WP backend shows error:
Cannot modify header information - headers already sent by (output started at /var/www/html/web/app/plugins/elasticpress/includes/classes/Elasticsearch.php:1465)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@jerasokcm, we don't provide support for problems related to infrastructure. You'll need to make sure you can connect to your Elasticsearch server using that username and password *from the web server running your website*, and it can send a request to the `_nodes/plugins` endpoint and get a proper result.
