### ISSUE TITLE
Expose developer hook to allow customization of filter markup to allow wrapping/containerization

### ISSUE THREAD

**Issue by tropicandid** [10up/ElasticPress#3774]
### Is your enhancement related to a problem? Please describe.

The `ep_facet_taxonomy_value_html` hook permits the modification of the html markup of filters individually. However, this is rather narrow and prevents customization of the whole collection. For example, in my case, I needed to modify the display to be contained in a dropdown container and there was no way to allow further div wrapping with this hook other than by injecting with javascript or adding an additional external custom block wrapper around an internal filter by taxonomy block. . 

### Describe alternatives you've considered

Recommendation that the $item parameter could be modified to be the collection of filters and the $html parameter be the compilation of all of the filters to be rendered that way the final markup can be managed for all filters within a taxonomy in a unified way. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @tropicandid,

I recommend using the `ep_facet_search_widget` [filter](https://10up.github.io/ElasticPress/ep_facet_taxonomy_value_html.html) instead. This will allow you to modify the HTML of the facet block. 

An alternative is to create a new class by extending the`\ElasticPress\Feature\Facets\Renderer`. Modify the `render` method according to your requirements and then use `ep_facet_renderer_class` [filter](https://10up.github.io/ElasticPress/ep_facet_renderer_class.html) to call your new class.


Regards,
Burhan
