### ISSUE TITLE
Allow facet blocks on all post types

### ISSUE THREAD

**Issue by JiveDig** [10up/ElasticPress#3775]
### Is your enhancement related to a problem? Please describe.

We have a custom setup that uses pages and CPTs for our own sidebars/template parts, etc. and I'm currently unable to use the facet blocks in our classic/hybrid theme because they only seem to be available on wp_template and wp_template_part post types.

### Describe alternatives you've considered

I'm currently attempting to use `allowed_block_types_all` and similar filters but not having any success.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JiveDig** [comment]
FWIW, I spent a while digging to try to figure out where these blocks were being limited to only template parts and couldn't find any reference in this repo. Probably PEBKAC, but I'm stuck.

**Comment by felipeelia** [comment]
@JiveDig can you please comment out [these lines](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Facets/Facets.php#L115-L117) and check if it works? If it does, can you create a Pull Request adding a new filter there? Thanks!

**Comment by JiveDig** [comment]
Took me a while, but we've been using this and it works well. Feel free to rename or tweak as-needed. Thanks for considering!
