### ISSUE TITLE
BUG: request body is required 

### ISSUE THREAD

**Issue by RaptureForums** [10up/ElasticPress#3779]
### Describe the bug

I am getting the following error message in my Wordpress admin area saying that "Some ElasticPress queries failed in the last 24 hours."

When I visit the error page and visit the error message it says: We did not recognize this error. Please consider opening a [GitHub Issue](https://github.com/10up/ElasticPress/issues/new/choose) so we can add it to our list of supported errors.

### Steps to Reproduce

It shows in my admin area in Wordpress.

### Screenshots, screen recording, code snippet

<html><body>

Error | request body is required
-- | --
Recommended Solution | We did not recognize this error. Please consider opening a GitHub Issue so we can add it to our list of supported errors.
Elasticsearch Request | POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
Request ID | d00e298a5935445bb73d8b86399cbc71
Time Spent (ms) | 0.7030963897705078
WP Query Args | []
HTTP Status Code | 400
Query Body |  
Query Result | {   "error": {     "root_cause": [       {         "type": "parse_exception",         "reason": "request body is required"       }     ],     "type": "parse_exception",     "reason": "request body is required"   },   "status": 400 }

</body>
</html>Error	
request body is required
Recommended Solution	
We did not recognize this error. Please consider opening a [GitHub Issue](https://github.com/10up/ElasticPress/issues/new/choose) so we can add it to our list of supported errors.
Elasticsearch Request	
POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
Request ID	
d00e298a5935445bb73d8b86399cbc71
Time Spent (ms)	0.7030963897705078
WP Query Args	

[]

HTTP Status Code	400
Query Body	
Query Result	

{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "request body is required"
      }
    ],
    "type": "parse_exception",
    "reason": "request body is required"
  },
  "status": 400
}

### Environment information

Dell tower.
Firefox 120.0.1

<html><body>

PHP Version | 8.1.26
-- | --
Memory Limit | 40M
Maximum Execution Time | 600

</body>
</html>

<html><body>

WordPress Version | 6.4.1
-- | --
Home URL | *edited out*
Site URL | *edited out*
Multisite | false
Theme | Total (5.11)
Active Plugins | Classic  Editor (1.6.3), Classic Widgets (0.3), Cloudflare (4.12.2), Code  Snippets (3.6.2), Donorbox Donation Form (7.1.9), ElasticPress (5.0.0),  GTranslate (3.0.5), LiteSpeed Cache (5.7.0.1), Shortcode For Current  Date (2.2.0), Slider Revolution (6.6.18), Templatera (2.1.0), Total  Theme Core (1.8.1), Wordfence Security (7.11.0), WPBakery Page Builder  (7.2), WP RSS Aggregator (4.23.4), and Yoast SEO (21.6)
Revisions allowed | all

</body>
</html>

### https://www.raptureforums.com (2023-12-01 21:06:37) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
request_id: d00e298a5935445bb73d8b86399cbc71
query_time: 0.70309638977051
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://www.raptureforums.com (2023-12-01 21:00:33) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
request_id: bc97d132fabb48d59ee5bd42e41526b7
query_time: 0.63109397888184
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://www.raptureforums.com (2023-12-01 20:59:41) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
request_id: 7468345650e54cabbcbb4c780a0b0f88
query_time: 0.52285194396973
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://www.raptureforums.com (2023-12-01 20:59:41) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
request_id: e7262bcc3fb448259a827f6353def258
query_time: 0.86379051208496
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### https://www.raptureforums.com (2023-12-01 20:55:48) ###
error: request body is required
recommended_solution: We did not recognize this error. Please consider opening a <a href="https://github.com/10up/ElasticPress/issues/new/choose">GitHub Issue</a> so we can add it to our list of supported errors.
es_req: POST http://localhost:9200/raptureforumscom-post-1/post/_bulk
request_id: 88f956da2453443da0faac7ce9ecb1fe
query_time: 1.0449886322021
wp_args: array (
)
status_code: 400
body: 
result: array (
  'error' => 
  array (
    'root_cause' => 
    array (
      0 => 
      array (
        'type' => 'parse_exception',
        'reason' => 'request body is required',
      ),
    ),
    'type' => 'parse_exception',
    'reason' => 'request body is required',
  ),
  'status' => 400,
)

### WordPress Environment ###
wp_version: 6.4.1
home_url: https://www.raptureforums.com
site_url: https://www.raptureforums.com
is_multisite: false
theme: Total (5.11)
plugins: Classic Editor (1.6.3), Classic Widgets (0.3), Cloudflare (4.12.2), Code Snippets (3.6.2), Donorbox Donation Form (7.1.9), ElasticPress (5.0.0), GTranslate (3.0.5), LiteSpeed Cache (5.7.0.1), Shortcode For Current Date (2.2.0), Slider Revolution (6.6.18), Templatera (2.1.0), Total Theme Core (1.8.1), Wordfence Security (7.11.0), WPBakery Page Builder (7.2), WP RSS Aggregator (4.23.4), and Yoast SEO (21.6)
revisions: all

### Server Environment ###
php_version: 8.1.26
memory_limit: 40M
timeout: 600

### Rapture Forums — https://www.raptureforums.com ###
post_count: 16,187
page_count: 140
portfolio_count: 16
testimonials_count: 3
post_meta_keys: 1
page_meta_keys: 1
portfolio_meta_keys: 0
testimonials_meta_keys: 0
total-all-post-types: 1
distinct-meta-keys: ep_exclude_from_search

### Settings ###
host: http://localhost:9200
index_prefix: 
language: site-default
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### raptureforumscom-post-1 ###
health: yellow
status: open
index: raptureforumscom-post-1
uuid: gDxCGpb9TdWfUsls8oXr3A
pri: 5
rep: 1
docs.count: 16346
docs.deleted: 2875
store.size: 261.3mb
pri.store.size: 261.3mb
total_fields_limit: 5000
analyzer_language: english
stop_language: _english_
snowball_language: English

### 2023/11/20 7:27:16 am ###
method: WP Dashboard
is_full_sync: No
end_date_time: 2023/11/20 7:28:42 am
total_time: 0 hours, 1 minute, 26 seconds
total: 16314
synced: 16314
skipped: 0
failed: 0
errors: array (
)
trigger: manual
final_status: success

### Custom Search Results ###
active: true
force_inactive: false

### Filters ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: 1
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple
synonyms: <pre># Defined sets ( equivalent synonyms).
sneakers, tennis shoes, trainers, runners

# Defined alternatives (explicit mappings).
shoes => sneaker, sandal, boots, high heels</pre>
weighting: array (
  'post' => 
  array (
    'post_title' => 
    array (
      'weight' => 100,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 50,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'terms.category.name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'terms.post_tag.name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
  'page' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
  'portfolio' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
  'testimonials' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
  'mailmunch_page' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
  'vc4_templates' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
  ),
)

### Related Posts ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @RaptureForums,

Thank you for bringing up the issue. It has already been [reported](https://github.com/10up/ElasticPress/issues/3755) and fixed at [here](https://github.com/10up/ElasticPress/pull/3770). The fix will be included in the upcoming ElasticPress version. Since no further action is required, I will be closing this ticket.

Regards,
Burhan

**Comment by RaptureForums** [comment]
Hello,

I would like to request that the report be deleted from the Github as I thought that report was private and I was made aware that it was not. 

 

I don’t feel comfortable with all my technical information made “out there” on the topic as the plugin told me to consider bringing it to your attention about the bug.

 

Can someone please delete my bug report. I sure would appreciate it.

 

Thank you.
