### ISSUE TITLE
After enabling Elasticpress plugin - All schduled posts fail "Missed schedule"

### ISSUE THREAD

**Issue by izzygld** [10up/ElasticPress#3785]
### Describe your question

After enabling the Elasticpress wonderful plugin.
We noticed that Scheduled Posts don't work anymore.

Has anyone come across a similar issue?

![Screenshot 2023-12-07 at 13 13 00](https://github.com/10up/ElasticPress/assets/12534341/886367a0-81f6-4087-8583-4ee77c5969ed)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@izzygld can you please share your ElasticPress Status Report? You can get it by going to your WP Dashboard, then ElasticPress > Status Report. Rather than copying and pasting it here, it'd be preferable if you could download the file and upload it. Thanks!
