### ISSUE TITLE
Seeing daily errors with Elasticpress

### ISSUE THREAD

**Issue by bfrye26** [10up/ElasticPress#3786]
### Describe your question

Seeing very strange site errors daily; they look like the following:

https://site*******/?post=1055280&action=edit&meta-box-loader=1&meta-box-loader-nonce=516220df8d&_locale=user (2023-12-06 16:53:14)

in the error it reports the following:

{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "request body is required"
      }
    ],
    "type": "parse_exception",
    "reason": "request body is required"
  },
  "status": 400
}

It seems to happen at random, so any ideas would be amazing!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Thanks for opening the issue @bfrye26. It should be fixed by https://github.com/10up/ElasticPress/pull/3770 (released in EP 5.0.1) now.
