### ISSUE TITLE
WP Plugin : blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];

### ISSUE THREAD

**Issue by Dolzhykov** [10up/ElasticPress#3788]
### Describe your question

I've been having errors in the WP plugin for 1-2 months.
Can you help?

{
  "took": 0,
  "errors": true,
  "items": [
    {
      "index": {
        "_index": "fa-post-1",
        "_type": "post",
        "_id": "3753",
        "status": 403,
        "error": {
          "type": "cluster_block_exception",
          "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
        }
      }
    },
    {
      "index": {
        "_index": "fa-post-1",
        "_type": "post",
        "_id": "3736",
        "status": 403,
        "error": {
          "type": "cluster_block_exception",
          "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
        }
      }
    },

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @Dolzhykov, that error is not related to the plugin but to your Elasticsearch server -- it seems the Elasticsearch user (the one you set in ElasticPress settings) does not have enough permissions, or your index is full. As we do not provide support related to infrastructure, unfortunately, this is as much as we can help you with that problem. Good luck!
