### ISSUE TITLE
BUG: Post GUIDs appear to be regenerated sometimes with ElasticPress search enabled

### ISSUE THREAD

**Issue by DeflateAwning** [10up/ElasticPress#3790]
### Describe the bug

BUG: Post GUIDs appear to be regenerated sometimes with ElasticPress search enabled. This is an issue, as it breaks integrations with consumers of the RSS feeds. For example, the [dlvr.it social media service](https://dlvr.it) ends up reposting the same story when ElasticPress is enabled.

### Steps to Reproduce

1. Enable ElasticPress.
2. See that post GUIDs change by looking at the database.
3. See that posts get reposted on services integrated with RSS feeds (e.g., the [dlvr.it social media service](https://dlvr.it)).

### Environment information

Server-side issue. Client info not relevant. 

### WordPress and ElasticPress information

<details>
### WordPress Environment ###
wp_version: 6.3.2

### Server Environment ###
php_version: 8.2.12
memory_limit: 128MB
timeout: 43300

### SITE - redacted ###
post_count: 38,197
page_count: 36
post_meta_keys: 0
page_meta_keys: 0
total-all-post-types: 0
distinct-meta-keys: 

### Settings ###
host: redacted
index_prefix: 
language: site-default
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### redacted ###
health: yellow
status: open
index: redacted
uuid: redacted
pri: 5
rep: 1
docs.count: 38231
docs.deleted: 1
store.size: 794.8mb
pri.store.size: 794.8mb
dataset.size: 794.8mb
total_fields_limit: 5000
analyzer_language: english
stop_language: _english_
snowball_language: English

### 2023/11/15 9:47:33 pm ###
method: WP Dashboard
is_full_sync: Yes
end_date_time: 2023/11/15 10:05:36 pm
total_time: 0 hours, 18 minutes, 3 seconds
total: 38230
synced: 38230
skipped: 0
failed: 0
errors: array (
)
trigger: features
final_status: success

### Autosuggest ###
active: true
autosuggest_selector: 
endpoint_url: 
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Filters ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: strong
synonyms_editor_mode: simple
synonyms: <pre># Defined sets (equivalent synonyms).
sneakers, tennis shoes, trainers, runners

# Defined alternatives (explicit mappings).
shoes => sneaker, sandal, boots, high heels</pre>
weighting: array (
  'post' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'terms.post_tag.name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'terms.category.name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'page' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
)

### Related Posts ###
active: true
force_inactive: false

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @DeflateAwning. As this is not a problem we can reproduce in a fresh install of ElasticPress, can you please share:

1. How does the GUID change? Which pattern they follow, etc.
1. The full list of plugins you are using
2. The steps needed to reproduce that problem
