### ISSUE TITLE
BUG: Autosuggest race condition between "blur" and "click" events

### ISSUE THREAD

**Issue by romanberdnikov** [10up/ElasticPress#3794]
### Describe the bug

Everything is working fine when I use a mouse. But I can't click the dropdown links when I use a touchpad (single tap) on a laptop. It seems like 200ms timeout isn't enough. 300ms is fine.

```
		input.addEventListener('blur', function () {
			window.setTimeout(hideAutosuggestBox, 200);
		});
```

### Steps to Reproduce

1) Go to https://demo.elasticpress.io/
2) Type something in the 'Search ...' input
3) Try to open any link by tapping on it

### Environment information

Windows 11
Version 120.0.6099.72 (Official Build) (64-bit)

### WordPress and ElasticPress information

ep 4.7.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @romanberdnikov, thanks for opening the issue! I was able to reproduce the problem as well, we'll try to have it fixed for ElasticPress 5.1.0. Would you like to open a Pull Request with that fix? Thanks!
