### ISSUE TITLE
BUG: When the plugin is enabled, only the first 1000 pages of stories are shown on the `/category/<category>/` page

### ISSUE THREAD

**Issue by DeflateAwning** [10up/ElasticPress#3795]
### Describe the bug

When the plugin is enabled, only the first 1000 pages of stories are shown on the `/category/<category>/` page.

So, for example, if you have 40,000 stories, the plugin somehow manages to make that page only show the first 1000 pages. 

This seems like a weird bug to have, as this plugin shouldn't have a mechanism to modify this sort of thing. 

I'm convinced it's related to this issue (https://github.com/10up/ElasticPress/issues/3790); this one should be more easily reproducible. 

### Steps to Reproduce

1. Create a WordPress blog with about 40,000 articles.
2. Navigate to the `/category/<a valid category>/` page.
3. See that the pagination button at the bottom shows >1000 pages (maybe about 2900 pages).
4. Activate ElasticPress.
5. Navigate back to that page, and see that there are only 1000 pages. 

### Environment information

N/A

### WordPress and ElasticPress information

Present in v5.0.0 and v5.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@DeflateAwning we will need you to share your Status Report. Also, install our [Debugging Add-On](https://elasticpress.zendesk.com/hc/en-us/articles/16670678802189-Debugging), visit the category page, open the ElasticPress debug panel, click on "Download Requests Info" and share the file with us. Thanks

**Comment by DeflateAwning** [comment]
Were you unable to reproduce the issue as depicted? What's the best way to get in touch with you directly?

**Comment by felipeelia** [comment]
No, I wasn't (also, keep in mind that we do ask for the Status Report in the issue template you filled out.) Regarding communication, this is the best place to talk about the open-source project. If you need any personalized work you can schedule an appointment for consultation here: https://www.elasticpress.io/elasticpress-consulting/

**Comment by DeflateAwning** [comment]
Unfortunately I can't just share server dumps publicly. What I wrote is enough to reproduce the issue, as far as I can tell though.

Searching through the codebase, it appears that there are many filters which filter to 10,000 results (which would limit to 1,000 pages at 10 results per page): 
![image](https://github.com/10up/ElasticPress/assets/11021263/c5d5dfc9-0e3b-4cdb-8973-c4d6754c7a63)

It seems like these limits should be raised or removed, if ElasticPress is embeding itself so deeply in WordPress that loading post lists by category goes through the ElasticPress filters/hooks

**Comment by felipeelia** [comment]
You can work around that problem using the snippet I shared here: https://github.com/10up/ElasticPress/issues/2752#issuecomment-1122956582
