### ISSUE TITLE
ElasticPress does not search for substrings

### ISSUE THREAD

**Issue by DomPich** [10up/ElasticPress#3796]
### Describe the bug

As the title states I have a problem that ElasticPress does not search for substrings within ACFs.

I am currently using ElasticSearch version 7.10.1 and ElasticPress version 4.7.0.

For example if I'm searching for **MySubstring** it will only find results where the whole word **MySubstring** is matched but not SomethingAtTheStart**MySubstring**, **MySubstring**SomethingAtTheEnd, SomethingAtTheStart**MySubstring**SomethingAtTheEnd.

[This post](https://elasticpress.zendesk.com/hc/en-us/articles/16671887174541-Indexables) suggests that a fuzzy search is executed by default on meta fields when using an approach like this

```
new WP_Query( array(
    's'             => 'meta search phrase',
    'search_fields' => array(
        'post_title',
        'post_content',
        'post_excerpt',
        'meta' => array( 'meta_key_1', 'meta_key_2' ),
    ),
) );
```

As the docs state: 

```
Applies the current search to post meta.
The following will fuzzy search across post_title, post_excerpt, post_content, and post meta keys meta_key_1 and meta_key_2
```

The search itself is working for whole words, but as I said not for substrings.

I've already tried to search for a solution but couldn't find any solution.

I am not able to use a LIKE query like [this post](https://github.com/10up/ElasticPress/issues/1863#issuecomment-734317783) suggests, because I'm using repeater fields with a non deterministic number of entries like `repeaterName_1_fieldName`, `repeaterName_2_fieldName`, `repeaterName_3_fieldName`, ... , `repeaterName_N_fieldName`

Thank you guys in advance.

### Steps to Reproduce

1. Use ElasticSearch version 7.10.1 and ElasticPress version 4.7.0.
2. Stick to [this post](https://elasticpress.zendesk.com/hc/en-us/articles/16671887174541-Indexables) for using a fuzzy search approach
3. Do not change anything within the worpdress default search

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Partial matches in Elasticsearch can be achieved using different functionalities like wildcards or ngrams, @DomPich. This post gives an overview of all that: https://opster.com/guides/elasticsearch/how-tos/elasticsearch-query-partial-match/

For wildcards, you could tweak the WP_Query `s` parameter to include those (not recommended on big sets of data.) For ngrams, you can give it a look at how we use it for autosuggest: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Autosuggest/Autosuggest.php#L150 We add a couple of new fields to the mapping (a full sync is required after changing it), and then we start searching on both `post_title` and `post_title.suggest`.
