### ISSUE TITLE
Sort posts by date in meta field

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#3797]
### Describe your question

I have a custom post type in which each post has a meta field `new_sort_order` with a date.
I am using a `pre_get_posts` function to alter my sort order to use those dates, but it is very slow on a large website (+70k posts).
I was wondering if using ElasticPress could help speed up the queries if I somehow index or map that custom field.

Can EP help with this, and would I have to manually tell EP to index/map the custom field?
Also, would I have to manually add EP to the `pre_get_posts` query?

Here's my `pre_get_posts`:

```
function sort_posts_by_date($query) {
    if (!is_admin() && $query->is_main_query() && ($query->is_post_type_archive('movies') || $query->is_tax('characters') || $query->is_tax('actors'))) {
        $query->set('meta_key', 'new_sort_order');
        $query->set('orderby', 'meta_value_date');
        $query->set('order', 'DESC');
    }
}
add_action('pre_get_posts', 'sort_posts_by_date');
```

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @shmaltz. In ElasticPress 5 you'll need to go to the Weighting Dashboard and add that field to the list of meta fields to be indexed -- that will already make it to be indexed in several different formats, dates included. Then, run a sync (so your meta field is indexed.) The custom code you have there should already be enough to make ElasticPress translate it to an Elasticsearch query argument.

**Comment by shmaltz** [comment]
Thank you @felipeelia .

I added the meta field, but I'm assuming I don't want it to show up in search results because it's just a date, so if I uncheck `Searchable` will it still be indexed?

**Comment by felipeelia** [comment]
Yup, @shmaltz

**Comment by shmaltz** [comment]
Thank you!
