### ISSUE TITLE
Bulk Exclude from search results option

### ISSUE THREAD

**Issue by instocklabels** [10up/ElasticPress#3798]
### Describe your question

![exclude](https://github.com/10up/ElasticPress/assets/154472072/d40e962f-6eaa-4c50-a629-9a59883b3c75)

We use WordPress with woocommerce with ElasticPress plug-in. When editing a product page, there's an option within the publish area where you can checkbox to exclude from search results. We have several hundred pages that we need to do this to. Is there a bulk way to do this or do we need to go to each page one by one? Another option that would work for us is a way to exclude a specific product category as well. Any help would be appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @instocklabels. That functionality relies on a meta field called `ep_exclude_from_search` (see [here](https://github.com/10up/ElasticPress/blob/afbb9a5a39f118fd118f9407dc05eac8c1fbf378/includes/classes/Feature/Search/Search.php#L794).) You can add that as true to all the posts you need and run a full sync. That will update the posts in Elasticsearch, making ElasticPress exclude them from the search.
