### ISSUE TITLE
How to search for protected content in frontend?

### ISSUE THREAD

**Issue by Serverfox** [10up/ElasticPress#3802]
### Describe your question

Thanks for supporting ElasticPress!!

I want protected contents to be searchable in frontend. Protected Content is enabled and indexed and I can search such content when logged in as admin. When not logged in or even when the (allways identical) password for post protection has been submitted protected content is not showing up in search results.

However, I want my students to be able to search through all of my blog posts regardless whether protected or not.  
In Wordpress I've enabled searching for protected content with a hook like this:

`add_filter( 'posts_search', 'include_password_posts_in_search' );

function include_password_posts_in_search( $search ) {
    global $wpdb;
    if( !is_user_logged_in() ) {
        $pattern = " AND ({$wpdb->prefix}posts.post_password = '')";
        $search = str_replace( $pattern, '', $search );
    }
    return $search;
}
`
I wonder, if there's a similar solution for ElasticPress. [https://elasticpress.zendesk.com/hc/en-us/articles/360061855552-Can-t-see-private-posts-on-the-frontend-if-logged-in-and-have-the-correct-capability](url) didn't solve the issue.

Appreciate your support!

Kind regards

Jürgen

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Serverfox** [comment]
With help of the debug plugin I found a post filter in the query body like this:

            "must_not": [
                {
                    "exists": {
                        "field": "post_password"
                    }
                }
            ]
Is there a way to discard this "must_not" from search queries?

Thanks for your support

**Comment by burhandodhy** [comment]
Hi @Serverfox,

Certainly, you can display password-protected posts in the search results for all users by removing the filter that the Protected Content feature added. You can use the following snippet, and it will resolve the issue.

```
/**
 * Allow the Password Protected posts in the search results.
 */
add_filter(
	'ep_post_formatted_args',
	function ( $formatted_args ) {
		$protected_content = \ElasticPress\Features::factory()->get_registered_feature( 'protected_content' );
		remove_filter( 'ep_post_formatted_args', [ $protected_content, 'exclude_protected_posts' ] );

		return $formatted_args;
	},
	9
);

```

Regards,
Burhan

**Comment by Serverfox** [comment]
Awesome, this is the solution. THank you very much for your help!!
