### ISSUE TITLE
Media not found in backend

### ISSUE THREAD

**Issue by Serverfox** [10up/ElasticPress#3806]
### Describe your question

EleasticPress is a great enhancement when searching on frontend or when searching posts on backend.

However, I'm facing issues when searching for **media** files in the **backend**. 

E.g. there's a file "dice15PRotGruenBlau.svg" in my media library. Before installing ElasticPress this file was found by typing just "dice". Now I need to type the full name exactly to retrieve this file.

Any Idea, how to settle?

Thanks for your help and best regards

Jürgen  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @Serverfox,

ElasticPress does not use Elasticsearch for media searches in the admin panel. It's possible that there might be other third-party code contributing to the issue. Have you had an opportunity to test it without ElasticPress?

Using Elasticsearch for the media search query would be a valuable addition. Therefore, I am keeping this issue open until we integrate it into the plugin.

Regards,
Burhan

**Comment by Serverfox** [comment]
Thanks, Burhan, for getting back to the issue.

I've checked with ElasticPress Query Log and it seems as if media queries are being routed throug ElasticPress (see log file below).

When disabling ElasticPress media queries are getting back to normal.

Please note, I'm using Ivory Search plugin mainly for the sake of AJAX live search. Also im using code like this to enable ELasticPress queries within AJAX:

// Enable ajax search for ElasticPress Plugin
add_action('pre_get_posts', function() {
		// Add this to enable EP integration with AJAX requests
		add_filter( 'ep_ajax_wp_query_integration', '__return_true' );

		// Add this to apply the weighting fields configuration to your queries
		add_filter( 'ep_enable_do_weighting', '__return_true' );
});


NB: I'm using Elastic Search self hosted V8.11.4.

## Queries info ##

### https://schulblog.net/?page=ep-query-log (2024-01-18 16:09:56) ###
es_req: POST http://127.0.0.1:9200/schulblognetfus-post-2/_search
request_id: daa15319ae894a0e9619a85397e7d780
query_time: 24.173974990845
wp_args: array (
  'm' => '0',
  'cat' => '0',
  's' => 'dice15',
  'paged' => 1,
  'post_type' => 'attachment',
  'posts_per_page' => 20,
  'post_status' => 'inherit,private',
  'error' => '',
  'p' => 0,

**Comment by felipeelia** [comment]
Hi @Serverfox, I tried to reproduce the problem but I was able to find the file (ElasticPress will integrate searches for media files without any custom code if the library is in "List" mode.)

We will need to you share a few things with us:
1. Your full status report
2. The full output of `wp elasticpress get-mapping --pretty`
3. The full query log of that query you are seeing being fired

Thanks

**Comment by Serverfox** [comment]
Hi Felipe,

please find three files attached.

1) elastic-report.txt
2) get-mapping.txt
3) debug-bar-elastic-report.txt

Appreciate your support!

[elasticpress-report.txt](https://github.com/10up/ElasticPress/files/14066002/elasticpress-report.txt)

[get-mapping.txt](https://github.com/10up/ElasticPress/files/14066001/get-mapping.txt)

[debug-bar-elasticpress-report.txt](https://github.com/10up/ElasticPress/files/14065990/debug-bar-elasticpress-report.txt)
