### ISSUE TITLE
Documents search with self hosted elasticsearch V8.12

### ISSUE THREAD

**Issue by Serverfox** [10up/ElasticPress#3816]
### Describe your question

Thank you for supporting ElasticPress, a great enhancement for WP search.

I'm running a self hosted ES instance in V8.12.0 which is doing a great job in my blog https://schulblog.net/fus/

I wonder, if there is a way to activate **Documents Search** in EP. At this point in time EP blocked this feature as the **Attachement Ingest Plugin is not installed**, being included by default in ES since V8. Is there a workaround to enable Documents anyway?

Thanks for your help and best regards

Jürgen

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Serverfox** [comment]
I found a filter like below described in https://github.com/10up/ElasticPress/issues/1020#issuecomment-557356017 but it wouldnt help in my case:

> Anyone who finds this and doesn't want to edit the ElasticPress source, they've included a filter that thus far seems to be sufficient. I'll update if I have any issues. Keep in mind this is only helpful if you do, in fact, have the ingest attachment plugin setup on your ES instance and it isn't being reported properly, as is the case with AWS right now.
> 
> ```
> add_filter( 'ep_elasticsearch_plugins', function( $plugins ) {
>     $plugins['ingest-attachment'] = true;
>     return $plugins;
> });
> ```

I wonder if there is a simple solution like the above.

**Comment by jerasokcm** [comment]
I faced a similar problem, using a dockerized instance of Elasticsearch 8.7.1, which also includes in the core the functionality provided by the ingest document plugin.
In my case, I used the filter mentioned by @Serverfox and then could index the documents without any issues, avoiding modifications of the Elasticpress code.

**Comment by Serverfox** [comment]
Hi @jerasokcm , thanks for your confirmation. How did you employ this filter? Can you share details? Thank you

**Comment by jerasokcm** [comment]
> Hi @jerasokcm , thanks for your confirmation. How did you employ this filter? Can you share details? Thank you

I just copied that snippet and pasted in the functions.php file of my theme.
