### ISSUE TITLE
BUG: Scheduled Post Not Synced Automatically

### ISSUE THREAD

**Issue by lapak10** [10up/ElasticPress#3817]
### Describe the bug

I observed that scheduled posts are not getting synced automatically (tested on ElasticPress version 5.0.1) when they are published according to the set schedule. The issue seems to affect the synchronization process, preventing the scheduled posts from being reflected in the intended manner.

It seems to me we have not added the proper hook to handle than, when I add the hook manually directly into the plugin's code, it works then after. (Screenshot Attached)

### Steps to Reproduce

1. Set up a scheduled post with a future date and time.
2. Wait for the scheduled time to arrive and observe the post publication.

<img width="1457" alt="Screenshot 2024-01-22 at 7 05 30 PM" src="https://github.com/10up/ElasticPress/assets/525740/b2a7f1ce-ef49-4f91-a04e-11b18e35504f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @lapak10,

I tried it and couldn't replicate the issue on my end. When a post is published, it's automatically synced to Elasticsearch. However, it's possible that there could be some third-party code interfering with the default WordPress flow. To troubleshoot this, have you tried replicating the issue on a dev site with all plugins deactivated?

Additionally, concerning your question about the hook, `wp_insert_post`, it is also triggered when the post status is changed. Therefore, there is no issue there.

Regards,
Burhan
