### ISSUE TITLE
BUG: Media search returns no return in admin dashboard if 

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#3821]
### Describe the bug

Media search returns no result in the admin dashboard if the `Documents` and `Protected Content` features is enabled and the site has the `ep_ajax_wp_query_integration` filter set to true.

The problem is happening because the documents feature adds the mime type filter to search query 

```
 "terms": {
                        "post_mime_type": [
                            "application\/pdf",
                            "application\/vnd.ms-powerpoint",
                            "application\/vnd.openxmlformats-officedocument.presentationml.presentation",
                            "application\/vnd.ms-excel",
                            "application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application\/msword",
                            "application\/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            ""
                        ]
                    }
```

### Steps to Reproduce

1. Add the `add_filter( 'ep_ajax_wp_query_integration', '__return_true' );` in your codebase.
2. Make sure `Protected Content` and `Documents` are enabled 
3. Search for the media name

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Serverfox** [comment]
Thank you for taking care!!
