### ISSUE TITLE
BUG: Sends too many request to elastic if there are no result for search query

### ISSUE THREAD

**Issue by Amenocy** [10up/ElasticPress#3826]
### Describe the bug

Hi, 
i am using elasticPress with woocommerce, and I found a bug when you search for a keyword that doesn't have any response in Elstaic,( i mean any result for that search) , elasticpress keeps sending requests. I tested with both self-hosted and managed service. 
normally a search has 2 request to the elastic server, but in this case: Total ElasticPress Queries: 333 and Total Blocking ElasticPress Query Time: 24696 ms. 
note that autoSuggest is activated. but disabling that doesn't solve the issue, the total number of requests is the same, and blocking time is reduced. to 19seconds

### Steps to Reproduce

install woocommerce and elasticpress
search for something doesn't have any result in my case : https://site.com/?s=good+or+bad&post_type=product

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amenocy** [comment]
first request is like this: `{
    "from": 0,
    "size": 30,
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must_not": [
                            {
                                "terms": {
                                    "terms.product_visibility.term_taxonomy_id": [
                                        6
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish"
                        ]
                    }
                },
                {
                    "bool": {
                        "must_not": [
                            {
                                "terms": {
                                    "meta.ep_exclude_from_search.raw": [
                                        "1"
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "query": {
        "function_score": {
            "query": {
                "bool": {
                    "should": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "bool": {
                                            "should": [
                                                {
                                                    "multi_match": {
                                                        "query": "good or bad",
                                                        "type": "phrase",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "meta._sku.value^1",
                                                            "meta._variations_skus.value^1",
                                                            "terms.product_brand.name",
                                                            "terms.product_cat.name",
                                                            "terms.product_tag.name"
                                                        ],
                                                        "boost": 3
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "good or bad",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "meta._sku.value^1",
                                                            "meta._variations_skus.value^1",
                                                            "terms.product_brand.name",
                                                            "terms.product_cat.name",
                                                            "terms.product_tag.name"
                                                        ],
                                                        "operator": "and",
                                                        "boost": 1,
                                                        "fuzziness": "auto"
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "good or bad",
                                                        "type": "cross_fields",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "meta._sku.value^1",
                                                            "meta._variations_skus.value^1",
                                                            "terms.product_brand.name",
                                                            "terms.product_cat.name",
                                                            "terms.product_tag.name"
                                                        ],
                                                        "boost": 1,
                                                        "analyzer": "standard",
                                                        "tie_breaker": 0.5,
                                                        "operator": "and"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ],
                                "filter": [
                                    {
                                        "match": {
                                            "post_type.raw": "product"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
            "functions": [
                {
                    "exp": {
                        "post_date_gmt": {
                            "scale": "14d",
                            "decay": 0.25,
                            "offset": "7d"
                        }
                    }
                },
                {
                    "weight": 0.001
                }
            ],
            "score_mode": "sum",
            "boost_mode": "multiply"
        }
    },
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ]
}`

but rest of them ( tested up to 4 ) are : 
`{
    "from": 0,
    "size": 10000,
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must_not": [
                            {
                                "terms": {
                                    "terms.product_visibility.term_taxonomy_id": [
                                        6
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    },
    "query": {
        "function_score": {
            "query": {
                "bool": {
                    "should": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "bool": {
                                            "should": [
                                                {
                                                    "multi_match": {
                                                        "query": "good+or+bad",
                                                        "type": "phrase",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "meta._sku.value^1",
                                                            "meta._variations_skus.value^1",
                                                            "terms.product_brand.name",
                                                            "terms.product_cat.name",
                                                            "terms.product_tag.name"
                                                        ],
                                                        "boost": 3
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "good+or+bad",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "meta._sku.value^1",
                                                            "meta._variations_skus.value^1",
                                                            "terms.product_brand.name",
                                                            "terms.product_cat.name",
                                                            "terms.product_tag.name"
                                                        ],
                                                        "operator": "and",
                                                        "boost": 1,
                                                        "fuzziness": "auto"
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "good+or+bad",
                                                        "type": "cross_fields",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_excerpt^1",
                                                            "post_content^1",
                                                            "meta._sku.value^1",
                                                            "meta._variations_skus.value^1",
                                                            "terms.product_brand.name",
                                                            "terms.product_cat.name",
                                                            "terms.product_tag.name"
                                                        ],
                                                        "boost": 1,
                                                        "analyzer": "standard",
                                                        "tie_breaker": 0.5,
                                                        "operator": "and"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ],
                                "filter": [
                                    {
                                        "match": {
                                            "post_type.raw": "product"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
            "functions": [
                {
                    "exp": {
                        "post_date_gmt": {
                            "scale": "14d",
                            "decay": 0.25,
                            "offset": "7d"
                        }
                    }
                },
                {
                    "weight": 0.001
                }
            ],
            "score_mode": "sum",
            "boost_mode": "multiply"
        }
    },
    "_source": {
        "includes": [
            "post_id"
        ]
    },
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ]
}`

**Comment by felipeelia** [comment]
Hi @Amenocy, we will need your ElasticPress Status Report to understand what could be going on in your case. ElasticPress out-of-the-box would not try the same query over and over again if a result was not found.
