### ISSUE TITLE
BUG: test_use_language_in_setting_for_multisite() unit test is failing on WP 6.4.3

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#3828]
### Describe the bug

On WordPress 6.4.3 `test_use_language_in_setting_for_multisite` test is failing. 

### Steps to Reproduce

Run `/vendor/bin/phpunit tests/php/TestDashboard.php --filter test_use_language_in_setting_for_multisite`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
I spent some time on this one, and the problem comes from the `delete_expired_transients` method. We are not the first ones facing this [same issue](https://wordpress.stackexchange.com/questions/378088/wp-insert-site-is-triggering-database-error-in-a-unit-test).
