### ISSUE TITLE
Configure results when searching documents

### ISSUE THREAD

**Issue by jerasokcm** [10up/ElasticPress#3829]
### Describe your question

The "documents" feature is working fine, but the results include links to the respective files in the media storage. 
Is there a way to configure EP so that only retrieves the parent post of the attachment and not the direct link to the document?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
The snippet below should do that for you, @jerasokcm:

```php
add_filter(
	'attachment_link',
	function ( $link, $post_id ) {
		$post = get_post( $post_id );
		if ( ! $post || empty( $post->post_parent ) ) {
			return $link;
		}
		return get_permalink( $post->post_parent );
	},
	10,
	2
);
```

**Comment by jerasokcm** [comment]
> The snippet below should do that for you, @jerasokcm:
> 
> ```
> add_filter(
> 	'attachment_link',
> 	function ( $link, $post_id ) {
> 		$post = get_post( $post_id );
> 		if ( ! $post || empty( $post->post_parent ) ) {
> 			return $link;
> 		}
> 		return get_permalink( $post->post_parent );
> 	},
> 	10,
> 	2
> );
> ```

Thanks. The filter does the job.
However, this is a general WP filter. So, I wonder if there is a way to apply it only if ElasticPress is installed/activated.
