### ISSUE TITLE
Bulk index status relapses to not showing total after a certain point

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#383]
Noticed this while performing a rather large index today with 27,492 posts.

After the 13,650th post, the total being reported instead showed just the latest number.

<img width="353" alt="screen shot on 2015-10-16 at 06-43-28" src="https://cloud.githubusercontent.com/assets/953022/10540850/756acd44-73d1-11e5-949e-7d2c229b930c.png">

This is a somewhat minor issue, but would be nice to resolve for a more accurate gauge of progress during bulk indexing.

**Comment by tlovett1** [comment]
@allan23 mind looking at this?

**Comment by allan23** [comment]
@AaronHolbrook Can you let me know what kind of post types you are indexing? Single-site or Multi-site? EP Version? 

Can this be replicated over and over again?

(I'm trying to find a way to reproduce this and I might be missing something.)

**Comment by AaronHolbrook** [comment]
Post post types, multi-site, but individually indexing each single site. EP version is 1.6.




Can be replicated every single time. Seems to require a LOT of posts

**Comment by allan23** [comment]
@AaronHolbrook I've tried different ways to reproduce this and I'm coming up short. Anything else I can try to reproduce?

**Comment by AaronHolbrook** [comment]
How many posts are you trying to index?

Wish I could give you more, it was reproducing every time on sites with a very large number of posts.

**Comment by allan23** [comment]
@AaronHolbrook I have finally reproduced it! Running an index on ES 2.0 / WP 4.4 multisite, I am seeing that the total post count goes down as the the current number of indexed posts goes up.

<img width="241" alt="screen shot 2015-12-09 at 9 17 13 pm" src="https://cloud.githubusercontent.com/assets/1326772/11706867/43da4444-9eba-11e5-867e-056328d3362b.png">

Now comes the tricky part of figuring out why.

**Comment by AaronHolbrook** [comment]
Hmm @allan23 that's still not the same bug as reported though, but it's possible related.

Let me know what you find!
