### ISSUE TITLE
Index documents hosted elsewhere in the cloud

### ISSUE THREAD

**Issue by jerasokcm** [10up/ElasticPress#3830]
### Describe your question

Let's say I have a CPT called "video". This post type has a meta field "transcript", that points to a PDF file hosted in Amazon S3. Is there a way to configure ElasticPress to send the document to be indexed by ES, so that the parent post is displayed in the results when searching some terms that are present in the PDF file?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@jerasokcm We've recently merged into our ElasticPress Labs plugin, a feature that might help you achieve that. See this PR for more info: https://github.com/10up/ElasticPressLabs/pull/94

It is not released yet, but you should be able to test it using the code in that PR.

**Comment by jerasokcm** [comment]
> @jerasokcm We've recently merged into our ElasticPress Labs plugin, a feature that might help you achieve that. See this PR for more info: [10up/ElasticPressLabs#94](https://github.com/10up/ElasticPressLabs/pull/94)
> 
> It is not released yet, but you should be able to test it using the code in that PR.

Thanks. I will give it a try.

**Comment by jerasokcm** [comment]
@felipeelia Any plans to release this feature to production?

**Comment by felipeelia** [comment]
It was released in March as an ElasticPress Labs feature, @jerasokcm. See https://github.com/10up/ElasticPressLabs/releases/tag/2.3.0
