### ISSUE TITLE
Integrate WooCommerce Categories to Instant Result

### ISSUE THREAD

**Issue by godlesowned** [10up/ElasticPress#3834]
### Describe your question

Hello, I just integrated ElasticPress with Instant Results (self hosted). Currently it only showing products in modal. Is there any option to search also in WooCommerce Categories?
I want to create something like this:
<img width="819" alt="image" src="https://github.com/10up/ElasticPress/assets/12765198/c94614a0-6358-4ae7-b23a-cdd0dff74eed">

So right now I have: Products, and now I need also WooCommerce Categories & WooCommerce Brands and show brand logo, everything should be in modal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Unfortunately not, @godlesowned. Displaying categories as search results is an enhancement we are tracking in this [issue here](https://github.com/10up/ElasticPress/issues/2676).
