### ISSUE TITLE
Elasticpress Search Count

### ISSUE THREAD

**Issue by greg-carter1924** [10up/ElasticPress#3836]
### Describe your question

Hello, I have elasticpress search installed on a wordpress site. Where in the dashboard of my wordpress site can I get a report of the searches done on the site. I would like to see any of the following:

- Number of searches done using elasticpress
- Specific queries performed showing what user searched for

Thank you, Greg

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @greg-carter1924,

ElasticPress does not have that functionality, but you can use services like Google Analytics to track that data. You can see how to do that in this article: https://elasticpress.zendesk.com/hc/en-us/articles/23858857181581-Tracking-search-terms-with-Google-Analytics
