### ISSUE TITLE
Search into attributes of products

### ISSUE THREAD

**Issue by astronedev** [10up/ElasticPress#3838]
### Describe your question

Example:
Client is searching "shoes" and it showing all shoes. But how to set Elasticpress & Insta results to include also query like "shoes s" and then it will only be showing products with keyword shoes and also which have size attribute s?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @astronedev, it will depend a bit on how your solution was set up. Before we dig further, can you confirm you have the attribute selected as searchable in the Search Fields & Weighting dashboard?

**Comment by astronedev** [comment]
Yes:
<img width="1353" alt="image" src="https://github.com/10up/ElasticPress/assets/160131024/88a96c8c-9f6f-4179-8fdd-b6a5cae16b21">
It's this one with 40 weight.

You can check here: https://egodev.astrone.dev/
Type "Spodnie" and you will see: SPODNIE GUESS DRESOWE CZARNE on this products there is S size attribute (rozmiar in polish language)
and no type "Spodnie s" and there is no results.

**Comment by felipeelia** [comment]
Hi @astronedev, that could be a problem with the proxy. Can you please share the search template it is generating? If you didn't change that part of it, it should be located at your wp uploads folder, named "ep-custom-proxy-credentials.php" (remove the credentials before sharing it.)
