### ISSUE TITLE
Select language per index

### ISSUE THREAD

**Issue by paulhuisman** [10up/ElasticPress#384]
Is it possible to add the appropriate language per index?

I'd like to have two indexes, english and dutch.

Obviously both should have the proper token stop filters.

**Comment by tlovett1** [comment]
This is definitely possible with Elasticsearch. With ElasticPress, it might take some research/work. Love to see what you figure out!

**Comment by phpanos** [comment]
Did you find a solution to this @paulhuisman? I would need this as well.
