### ISSUE TITLE
Run sync task programmatically

### ISSUE THREAD

**Issue by jerasokcm** [10up/ElasticPress#3840]
### Describe your question

Hello.
I'm using a plugin that fetches data from an external API and then creates multiple CPT posts. 
It seems that Elasticsearch automatic sync is not fired in this scenario. Is there a way to force ElasticPress to fire a sync task from inside my plugin code?

Thanks in advance for your guidance. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@jerasokcm if you are using wp_insert_post() that should work, unless you are [setting the WP_IMPORTING constant](https://github.com/10up/ElasticPress/blob/a89026501f64c8521525e8c3169cd93b27809659/includes/classes/SyncManager.php#L283).

You can also call `\ElasticPress\Indexables::factory()->get( 'post' )->index( $post_id, true );` to index a specific post if you need.
