### ISSUE TITLE
Adding extra fields to the index

### ISSUE THREAD

**Issue by danharper83** [10up/ElasticPress#3841]
### Describe your question

I want to get an ACF repeater field to index into a single field.

I was using `ep_post_mapping` to add the new mapping and then `ep_prepare_meta_data` to loop through all the repeater data and then add it into the meta array but this has stopped working.

I've updated to the latest version of the plugin and this has all stopped working so I'm not sure which are the correct hooks to use to accomplish what I want.

Cheers Dan

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @danharper83, you have the correct filters there. Do you mind sharing the whole custom code you wrote?
