### ISSUE TITLE
sort search results by post type?

### ISSUE THREAD

**Issue by columbian-chris** [10up/ElasticPress#3842]
### Describe your question

Is there a way to return ElasticPress search results by post type?  For example, can I get search results back that list pages first in order before posts?  I tried setting the weight under the title attribute of Pages on the "Manage Search Fields & Weighting" settings page of the plugin, but it didn't seem to make any difference.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@columbian-chris did you already try to sort by post_type in your WP_Query? That should be translated to the ES Query that EP generates and, theoretically, should work just fine.

**Comment by columbian-chris** [comment]
@felipeelia You know, I actually did not know that you could pass "type" into WP Query's "orderby" option.  That did work.

My only question then is - would I be able to order results by individual post types instead of just choosing DESC or ASC?  I need results from one post type to be listed before the others and they're unfortunately not in alphabetical order.

**Comment by felipeelia** [comment]
@columbian-chris This is tricky, but it seems you could achieve that using a couple of different ways:

- One would be using script sorting in your Elasticsearch query (some examples [here](https://stackoverflow.com/questions/58522821/elasticsearch-sorting-by-custom-item-weight), [here](https://discuss.elastic.co/t/sorting-or-ordering-by-specific-values/67244), and [here](https://stackoverflow.com/questions/69089142/custom-sort-order-by-ids-as-array-in-elastic-search)),
- You could try to use some weight, as [in this example](https://stackoverflow.com/questions/45963284/custom-sorting-in-elasticsearch) OR
- (perhaps the simpler approach if you don't want to work on the Elasticsearch side of things) You could use the `ep_prepare_meta_data` to add a meta data to the post (let's say `ep_post_type`) and add the value based on the order you want to give. For example, if it is a page,  `ep_post_type` would be `1`, if it is a post, the value would be `2`, etc. Then, you simply order by that meta field.
