### ISSUE TITLE
Plugin can't connect to self-hosted elasticsearch 

### ISSUE THREAD

**Issue by remoteboy** [10up/ElasticPress#3843]
### Describe your question

Have just installed a self-hosted version of elasticsearch on the same box as my wordpress installation. When I try to set up the plugin I get this error message - 

`There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again or you may need to change your settings.`

I've tried setting my Elasticsearch host URL to a couple of different options - http://127.0.0.1:9200, https://127.0.0.1:9200, http://localhost:9200, https://localhost:9200 - but they all return the same response - 

`It was not possible to connect to your Elasticsearch server. Your settings were reverted.`

I can confirm that Elasticsearch is running by checking the service status 

```
elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-02-22 11:24:55 UTC; 12min ago
       Docs: https://www.elastic.co
   Main PID: 10342 (java)
      Tasks: 86 (limit: 9379)
     Memory: 4.3G
```

I've installed the debugging plugin but that doesn't give me any additional information. 

I'm wondering whether I'm missing a piece of the puzzle. Is there somewhere I need to create a username and password or an access token to allow WordPress to talk to the server? Are there any permissions I need to check?

I'm running WordPress 6.4.3. My PHP version is 8.2.15, running on Ubuntu 22.04.

Would appreciate any help. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @remoteboy. Sorry to read you have this problem, but help with infrastructure is outside of our scope here. Anyway, as a general pointer, you should be able to debug it by SSH'ing into your web server (the one that hosts WordPress) and making a wget or a curl call to your Elasticsearch server. The moment you have that call working, WP should also be able to communicate to ES -- if that is not the case, you'll have to investigate your WP site to see if it is not altering your outgoing requests.

Good luck!

**Comment by BugTickler** [comment]
@remoteboy Did you manage to solve the problem? I have the same problem. I've tried everything, but to no avail. I was able to connect the plugin only by completely disabling SSL in elasticsearch.yml,

```
xpack.security.http.ssl:
    enabled: false
xpack.security.transport.ssl:
    enabled: false
```
