### ISSUE TITLE
Adopt Block API version 3

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#3853]
### Is your enhancement related to a problem? Please describe.

As of WordPress 6.3:

>The post editor will be iframed if all registered blocks have a Block API version 3 or higher and the editor has no classic meta boxes below the blocks. Adding version 3 support means that the block should work inside an iframe, though the block may still be rendered outside the iframe if not all blocks support version 3.

Since ElasticPress' blocks use version 2, it will prevent this behaviour for sites that are otherwise compatible.

The only work involved is increasing the version number and verifying that the blocks work as expected in an iframe. ElasticPress' blocks do not do anything that wouldn't work in an iframe, so I don't anticipate any more work than that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
I'd love to see this get reprioritized. This has a real impact on sites not that WordPress 6.7 is in the wild since this is now preventing the iframed editor. 

@dkotter could you maybe help the team here get their E2E tests in the iframed editor figured out? 🤔
