### ISSUE TITLE
"Did you mean?" not working

### ISSUE THREAD

**Issue by akif-git** [10up/ElasticPress#3858]
### Describe your question

Hello,

I have integrated Elastic Search using ElasticPress on my wordpress website. I am hosting my ElasticSearch server on ElasticCloud. I have successfully synced my website with my ElasticSearch server. However, After following all the instructions for the "Did you mean?" installation, it doesn't seem to work. I don't see any option for "Did you mean...?" when I write an incorrect search. Can I get an update please? Also, after syncing how am I supposed to know my ElasticSearch is working?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @akif-git, can you please share the exact steps you went through to implement Did You Mean? To check if Elasticsearch is working you can use our ElasticPress Debugging Add-On Plugin, as explained in [this article](https://elasticpress.zendesk.com/hc/en-us/articles/360050720172-Using-the-ElasticPress-Debugging-Add-On-Plugin).
