### ISSUE TITLE
BUG: Searching order ID or invoice ID of order is not working

### ISSUE THREAD

**Issue by callanerd** [10up/ElasticPress#3860]
### Describe the bug

Searching order ID or invoice ID of order is not working

### Steps to Reproduce

Log into backend
click on woocommerce->order
search for BUG: Searching order ID or invoice ID not working, giving zero result

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @callanerd. Did you make any changes in your configurations since we talked about it in #3707?
