### ISSUE TITLE
Trying to display all posts except for one. (post__not_in not working)

### ISSUE THREAD

**Issue by Mono-Code** [10up/ElasticPress#387]
My project requires that I display similar posts to the one currently being viewed. Although I'm able to perform a search query (using the article's title), the article itself keeps popping up as a similar article (makes sense) but when I try to pass "post__not_in" with this article's ID it doesn't seem to be working. I have found a work-around for the time being, but what would you suggest as being the best solution for handling something like this within ElasticPress?

**Comment by allan23** [comment]
@Mono-Code Can you please copy/paste the WP_Query you are using?

**Comment by Mono-Code** [comment]
Sure thing, here you go:

$similar_query = new WP_Query( 
	 array(
		's' => get_the_title(),
		'post__not_in' => array($post->ID),
		 'showposts' => 4,
		 'post_status' => 'publish',
		 'orderby'=>'relevance',
		 'order'=>'DESC',
	 )
 );

**Comment by psorensen** [comment]
also having this issue.

**Comment by allan23** [comment]
@Mono-Code & @psorensen  - I am unable to replicate this issue. The only way I can get the post to be returned is if the wrong post ID is passed into the post__not_in array.

Is there any further information that you can provide?

**Comment by isaacrajaei** [comment]
Try this `get_queried_object_id()`
