### ISSUE TITLE
How to properly configure Protected Content for selfhosting?

### ISSUE THREAD

**Issue by rstrah** [10up/ElasticPress#3899]
Now, when you turn on this function, the search also shows unpublished materials, how can I fix this?

I expected from this function that it would speed up the search in the admin area (not public materials). As a result, I get visibility of them for everyone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@rstrah, that is not how the feature behaves with a fresh install. A couple of questions that might help you debug the problem:

1. Are you getting the same results for logged and non-logged-in users?
2. Do you have any custom code that tweaks the main WP_Query object?

**Comment by rstrah** [comment]
@felipeelia , hi 
1) Yes
2) No

**Comment by rstrah** [comment]
I have a problem

**Comment by felipeelia** [comment]
@rstrah, when you say it is display things it should not, you mean they are password protected, they are part of a custom post type or something different?

**Comment by rstrah** [comment]
Post not released yet (planned/draft)
