### ISSUE TITLE
BUG:  Synchronization error with change of url (and/or) post content

### ISSUE THREAD

**Issue by rstrah** [10up/ElasticPress#3902]
### Describe the bug

After synchronisation in scheduled notes (but maybe not in scheduled notes too) with shortcode ([SHORTCODES ULIMATE - THE #1 SHORTCODES PLUGIN](https://ru.wordpress.org/plugins/shortcodes-ultimate/)) content and url may change. This shortcode (https://prnt.sc/SgQyEbXdHUYD) is used. Usually in this shortcode are specified either specific posts or for example one heading. The number of posts is usually 2-3. After synchronisation, the url (and / or) content is changed to the news that was pulled in this shortcode at the time of synchronisation.

### Steps to Reproduce

1) Schedule a post
2) Add a shortcode [su_posts id="1463207,1463123" posts_per_page="2" post_type="news" taxonomy="news-list" order="desc" ignore_sticky_posts="yes"] to the end of the post (example shortcode ).
3) Make at least 5 such posts (don't forget to add shortcodes)
4) Run synchronisation and see how some posts have mixed url (and/ or) content.

### WordPress Environment ###
wp_version: 6.5.2
is_multisite: false
theme:  ()
plugins: Ajax Search Lite (4.11.5), Autoptimize (3.1.11), Carbon Fields (3.6.0), Classic Editor (1.6.3), Classic Widgets (0.3), Conditional Widgets (3.1), Contact Form 7 (5.9.3), Cyr-To-Lat (6.1.0), Easy Add Thumbnail (1.1.3), Easy Table of Contents (2.0.65), ElasticPress (5.0.2), ElasticPress Proxy (1.0.0), Health Check & Troubleshooting (1.7.0), Images to WebP (4.7), Instant Indexing (1.1.18), MAIL.RU Informer (3.0.1), Missed Scheduled Posts Publisher by WPBeginner (2.0.0), Perfecty Push Notifications (1.6.2), Post SMTP (2.9.1), ProfilePress (4.15.6), QSM - reCAPTCHA (1.0.8), Query Monitor (3.16.2), Quiz And Survey Master (9.0.1), Rank Math SEO with AI Best SEO Tools (1.0.217), Redis Object Cache (2.5.2), Remove CPT base (6.5), RSS for Yandex Turbo (1.32), Shortcodes Ultimate (7.1.4), TotalRating Pro (1.8.4), User Role Editor (4.64.2), What The File (1.6.0), Wordfence Security (7.11.5), WP Activity Log (4.6.4), WPAdCenter (2.5.6), WP Crontrol (1.16.3), WP Fastest Cache (1.2.5), WP Help (1.7.5), XML Sitemap & Google News (5.4.8), Yandex.News Feed by Teplitsa (1.12.5), Zen Feed (0.8.0), Статистика по журналистам (0.0.1), Статистика по новостям (0.3) и ТОП-3 Минск && Итоги (0.0.1)
revisions: all

### Server Environment ###
php_version: 8.2.14
memory_limit: 512M
timeout: 60

## Indexable Content ##
post_count: 0
page_count: 17
event_count: 0
newspaper_count: 1 939
district_count: 9
cae_count: 177
prm_count: 74
aaq_count: 38
aqq-appeals_count: 17
meri_count: 679
authors-column_count: 1 906
video_count: 4 668
programs_count: 16
news_count: 198 036
qsm_quiz_count: 2
wpadcenter-ads_count: 10
post_meta_keys: 0
page_meta_keys: 0
event_meta_keys: 0
newspaper_meta_keys: 0
district_meta_keys: 0
cae_meta_keys: 0
prm_meta_keys: 0
aaq_meta_keys: 0
aqq-appeals_meta_keys: 1
meri_meta_keys: 0
authors-column_meta_keys: 0
video_meta_keys: 0
programs_meta_keys: 0
news_meta_keys: 0
qsm_quiz_meta_keys: 0
wpadcenter-ads_meta_keys: 0
total-all-post-types: 1
distinct-meta-keys: ep_exclude_from_search

### Settings ###
host: http://127.0.0.1:9200/
index_prefix: 
language: ru_RU
per_page: 2000
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### sitecom-post-1 ###
health: yellow
status: open
index: sitecom-post-1
uuid: UhJTY0b2QKCM60Y5xl_4Rg
pri: 5
rep: 1
docs.count: 655913
docs.deleted: 5810
store.size: 5.2gb
pri.store.size: 5.2gb
dataset.size: 5.2gb
total_fields_limit: 5000
analyzer_language: russian
stop_language: _russian_
snowball_language: Russian

### 2024/04/24 9:50:30 дп ###
method: WP Dashboard
is_full_sync: No
end_date_time: 2024/04/24 9:50:32 дп
total_time: 0 часов, 0 минут, 3 секунды
total: 17
synced: 17
skipped: 0
failed: 0
errors: array (
)
trigger: manual
final_status: success

### Autosuggest ###
active: true
autosuggest_selector: input[type="text"], .ep-search-input
endpoint_url: 
force_inactive: false
trigger_ga_event: 1

### Custom Search Results ###
active: true
force_inactive: false

### Did You Mean ###
active: true
force_inactive: false
search_behavior: list

### Instant Results ###
active: true
facets: 
force_inactive: false
highlight_tag: mark
match_type: any
per_page: 10
search_behavior: list
term_count: 1

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 1
highlight_excerpt: 1
highlight_tag: mark
synonyms_editor_mode: simple
synonyms: <pre># Defined sets (equivalent synonyms).
sneakers, tennis shoes, trainers, runners

# Defined alternatives (explicit mappings).
shoes => sneaker, sandal, boots, high heels</pre>
weighting: array (
  'post' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.post_tag.name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.category.name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'page' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 99,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 80,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 80,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'event' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 20,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 10,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 15,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 5,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'newspaper' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'district' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 100,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 45,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 40,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'cae' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'prm' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'aaq' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'aqq-appeals' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'meri' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 65,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 60,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 55,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'authors-column' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 35,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 25,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 20,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 30,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'video' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 75,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 70,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 70,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'programs' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'news' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 100,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 85,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 90,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 95,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
    'terms.news-list.name' => 
    array (
      'enabled' => true,
      'weight' => 30,
    ),
    'terms.news-district.name' => 
    array (
      'enabled' => true,
      'weight' => 30,
    ),
  ),
  'qsm_quiz' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
)

### Related Posts ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@rstrah, after a post is indexed in Elasticsearch, ElasticPress will not change or update it until the post itself is updated in WordPress. That said, if you update a post that indirectly affects the computed content of another post, you'll need to reindex this other post, so its computed content is registered in Elasticsearch.

**Comment by rstrah** [comment]
@felipeelia Hi. We didn't understand each other a little. Elastic breaks scheduled posts and swaps their url and content
