### ISSUE TITLE
Indexing failing with type mapping error

### ISSUE THREAD

**Issue by sunnydadigs** [10up/ElasticPress#3905]
### Describe your question

Hello,

I am trying to index the Wordpress site with elasticpress and I used this function to connect the multiple Wordpress sites to the index and it failed with the following error 

Mapping failed: Validation Failed: 1: type is missing;
Mapping has failed, which will cause ElasticPress search results to be incorrect.

Followed this article to connect 2 sites andsearch on both sites vice-versa.

https://www.forumone.com/insights/blog/searching-multiple-wordpress-sites-elasticsearch/#

any clue?

2024-04-30 12:41:12 Starting delete and sync…
2024-04-30 12:41:12 Indexing posts…
2024-04-30 12:41:13 Mapping failed: Validation Failed: 1: type is missing;
Mapping has failed, which will cause ElasticPress search results to be incorrect. Please click `Delete all Data and Start a Fresh Sync` to retry mapping.
2024-04-30 12:41:13 Sync failed

curl -XGET -H 'Content-Type: application/json' -H 'X-ElasticPress-Request-ID: 25e5b0a30fbc4edb9751bc5e9e3aaff3' 'http://127.0.0.1:9200/http://127.0.0.1:9200'

curl -XGET -H 'Content-Type: application/json' -H 'X-ElasticPress-Request-ID: 7c81dda2e92d4c588ac29a0f689338b3' 'http://127.0.0.1:9200/http://127.0.0.1:9200/_settings?flat_settings=true'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
That blog was written in 2016, and things changed quite a bit in the plugin. Looking at the URL being requested you have the server being added twice (it should be `'http://127.0.0.1:9200/_settings?flat_settings=true` instead of `'http://127.0.0.1:9200/http://127.0.0.1:9200/_settings?flat_settings=true`), so you should start by fixing that.
