### ISSUE TITLE
How to change the index ?

### ISSUE THREAD

**Issue by rstrah** [10up/ElasticPress#3906]
### Describe your question

At the moment the site dev index is used, how can it be changed ?
https://minsknews.by/_search

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
I'm not sure I understood your question, @rstrah. What is that address and exactly where it is being used?

**Comment by rstrah** [comment]
@felipeelia, HI. This is the endpoint of local server Autosuggest. In it I see that the index of my dev site is used and not the main one. Instead of devminsknewsby-post-1 there should be minsknewsby-post-1. How to fix it ?

**Comment by rstrah** [comment]
i have problem

**Comment by felipeelia** [comment]
Indices are created by ElasticPress using the current site domain, @rstrah. If you run the sync process from the main site, it will create an index with the correct name. If you want to tweak that logic, you can use the [`ep_index_name`](https://10up.github.io/ElasticPress/ep_index_name.html) filter.

**Comment by rstrah** [comment]
Post not released yet (planned/draft)

**Comment by rstrah** [comment]
The problem is that full indexing has already been launched, but it did not produce anything.
https://prnt.sc/4uhQDrYBcLKb
