### ISSUE TITLE
Combining elastic search with tax_query

### ISSUE THREAD

**Issue by jacobmasters** [10up/ElasticPress#3908]
### Is your enhancement related to a problem? Please describe.

I've a simple external page which just includes the wp-config file and disables all themes/most plugins to just run a simple get_posts search:

`<?
define('WP_USE_THEMES', false);
define('plugins-searchonly',true);
require("../wp-config.php");
remove_filter('pre_get_posts', 'pre_get_filter');
$args = array('ep_integrate' => true,'posts_per_page' => -1,'post_type' => 'attachment','post_status' => 'any');
$args = array_merge( $args, array('s' => $_GET['search']));
$taxquery = array('tax_query' => array( array('taxonomy' => 'image-association','field' => 'slug', 'terms' => array('folio'))));
$args = array_merge($args,$taxquery);
 $folios = get_posts($args) ;
?>`

Currently wp-admin searches to attachments use Elasticsearch, so the index is in place, but using the stripped back code above does not and returns 0, does any global variable or wordpress element need including for it to work in this way?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobmasters** [comment]
Started this as a headless issue, but in further testing its actually the tax_query addition to the search query that's throwing this out and resulting 0 results, is there a way to combine the two or do i need to filter after search?

**Comment by felipeelia** [comment]
If you are sure ElasticPress is being loaded, that code should work, @jacobmasters. Is that `image-association` taxonomy indexable? If not, you may need to use the `ep_sync_taxonomies` filter to add it to the list.
