### ISSUE TITLE
Failed Queries Log disable

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3916]
### Describe your question

Hello! 
How to disable query logging?   I have some requests with a time exceeding 5s. I can’t repeat it, but 10+ requests per day are written to the log. If you try to repeat the request, it will be completed quickly. I don't know why they are fixed.
Example:  Time Spent (ms)	5003.54790687561

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
You have a couple of ways to achieve that, @ws256:

## Disable it completely

You can use the `ep_query_logger_queries_to_keep` filter to make it never log anything:

```php
add_filter( 'ep_query_logger_queries_to_keep', '__return_zero' );
```

## Conditionally log queries

You can also use the `ep_query_logger_should_log_query` to decide if a query should or should not be logged. See [this line of code](https://github.com/10up/ElasticPress/blob/5a3d8a3e706144054701571b974e1a9e59c6904c/includes/classes/QueryLogger.php#L389C61-L389C87) to see how the filter works.

## Replace the QueryLogger class

If you want to change how the query logging mechanism works, you can replace the default QueryLogger object instance with something custom, using the `ep_query_logger` filter. [This](https://github.com/10up/ElasticPress/blob/5a3d8a3e706144054701571b974e1a9e59c6904c/elasticpress.php#L215) is the related line.
