### ISSUE TITLE
Unable to get Autosuggest working on Cloudways WordPress installation

### ISSUE THREAD

**Issue by richblythtribus** [10up/ElasticPress#3923]
### Describe your question

We are having a lot of issues getting the autosuggest feature working unfortunately and seem to be going round in circles with Cloudways' technical support.

We have created a 'clean' application with a new installation of WordPress, the only plugins active are ElasticPress, Query Monitor and the ElasticPress Debugger. The active theme is Twentytwentyfour. The intention is to get it working on this application and mirror the fix on our 'actual' application on the same server.

The ElasticSearch Host URL is set via wp-config as http://127.0.0.1:9200
Autosuggest selector is set to .wp-block-search__input 
Endpoint URL has been set (by Cloudways) to wordpress-1257291-4550149.cloudwaysapps.com:9200/wordpress12572914550149cloudwaysappscom-post-1/_search

Previously we tried the endpoint as http://127.0.0.1:9200 - which resulted in console errors when trying to trigger the autosuggest feature. Now, nothing happens at all.

**Steps to reproduce;**
Use the search on https://wordpress-1257291-4550149.cloudwaysapps.com/ to query ‘Hello’ (do not press search/hit return)

**Expected results**
The ‘Hello world’ post is a returned as a suggestion per the ElasticPress Autosuggest feature (See https://wordpress-1257291-4550149.cloudwaysapps.com/wp-admin/admin.php?page=elasticpress)

**Status report**
### WordPress Environment ###
wp_version: 6.5.3
home_url: https://wordpress-1257291-4550149.cloudwaysapps.com
site_url: https://wordpress-1257291-4550149.cloudwaysapps.com
is_multisite: false
theme: Twenty Twenty-Four (1.1)
plugins: ElasticPress (5.1.0), ElasticPress Debugging Add-On (3.1.0), and Query Monitor (3.16.2)
revisions: all

### Server Environment ###
php_version: 8.2.19
memory_limit: 40M
timeout: 300

### wordpress-1257291-4550149.cloudwaysapps.com — https://wordpress-1257291-4550149.cloudwaysapps.com ###
post_count: 4
page_count: 1
post_meta_keys: 0
page_meta_keys: 0
total-all-post-types: 0
distinct-meta-keys: 

### Settings ###
host: http://127.0.0.1:9200
index_prefix: 
language: en_GB
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### wordpress12572914550149cloudwaysappscom-post-1 ###
health: yellow
status: open
index: wordpress12572914550149cloudwaysappscom-post-1
uuid: H9YYu0VdQwyfjbV_Llgy6Q
pri: 5
rep: 1
docs.count: 5
docs.deleted: 0
store.size: 101kb
pri.store.size: 101kb
total_fields_limit: 5000
analyzer_language: english
stop_language: _english_
snowball_language: English

### 2024/05/30 2:13:11 pm ###
method: WP Dashboard
is_full_sync: No
end_date_time: 2024/05/30 2:13:12 pm
total_time: 0 hours, 0 minutes, 2 seconds
total: 5
synced: 5
skipped: 0
failed: 0
errors: array (
)
trigger: manual
final_status: success

### Autosuggest ###
active: true
autosuggest_selector: .wp-block-search__input
endpoint_url: wordpress-1257291-4550149.cloudwaysapps.com:9200/wordpress12572914550149cloudwaysappscom-post-1/_search
force_inactive: false
trigger_ga_event: 0

### Did You Mean ###
active: true
force_inactive: false
search_behavior: 0

### Filters ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: 1
highlight_excerpt: 1
highlight_tag: mark
synonyms_editor_mode: simple
synonyms: <pre># Defined synonyms.
runner, running shoe, sneaker, tennis shoe, trainer

# Defined hyponyms.
blue => blue, aqua, azure, cerulean, cyan, ultramarine

# Defined replacements.
supposably => supposedly
flustrated => flustered, frustrated
intensive purposes => intents and purposes</pre>
weighting: array (
)

### Related Posts ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @richblythtribus,

I noticed that the autosuggest endpoint value on your site is empty. You can test this by entering `epas.endpointUrl` in the browser console.

<img width="1140" alt="image" src="https://github.com/10up/ElasticPress/assets/7139602/cd2b6233-17fa-46fa-86e1-5e7f60d2a343">

It appears that the Autosuggest URL was added without the HTTP protocol. Could you please add this URL `http://wordpress-1257291-4550149.cloudwaysapps.com:9200/wordpress12572914550149cloudwaysappscom-post-1/_search` in the settings and try. We discoverd its actually a bug  and already opened a ticket for this https://github.com/10up/ElasticPress/issues/3927

Additionally, it seems that SSL is not working for the Autosuggest URL, which might cause some issue. You can check the errors in browser browser console. 


Regards,
Burhan

**Comment by richblythtribus** [comment]
Thank you,

I have updated that setting and now get the following console errors when attempting to use autosuggest -
