### ISSUE TITLE
BUG: Anyway to improve indexing of cpt's?

### ISSUE THREAD

**Issue by gwhitehead** [10up/ElasticPress#3938]
### Describe the bug

Running a website that has WPML and ACF installed. Quite a few different post types set up within the website. Even if I do a wp-cli sync with the --setup flag and specifying certain post types it doesn't seem to completely index all items.  After running the setup sync via the cli, I was only able to get it to index some of the Product post types by going into the product and hitting the save button. 

So I am wondering is there a better way to tell the system to index or reindex an entire post type.

### Steps to Reproduce

SSH into the box.
Fire "wp elasticpress sync --post-type=product" or "wp wmpl_elasticpress sync --post-type=product" with or without the --setup flag to reset existing entries.
Test search still didn't have some things showing in its results.
Go into product and resaved and it then appeared into the search results.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @gwhitehead, what happens if you try to index those specific products passing `--include=<post_id>` to the WP-CLI command? Also, does it work if you completely disable WPML?

**Comment by gwhitehead** [comment]
I keep going back and forth with this issue. There is times that we run into a post that has been published, its post type is set to be indexed via Elasticpress. An appropriate weight has been set for the items within the post. Yet the item is not indexed on the initial publishing of said item. We are not able to truly track down what is causing this item to not be listed in the search results or in the auto-suggest.

Most of the time, resaving the item allows it to then start showing up in the autosuggest and also search results.  But we do not know that an item is missing until usually someone is doing a search for a specific product and at that time we realize it is not in the system.  @felipeelia suggest of indexing a specific post ID would probably reindex the item via the WP CLI but we don't know something is needing to be reindexed until we try to search for a published item.

I wonder if doing a command line sync whether the setup flag is used or not would then reindex everything but possibly miss something that we do not know has been missed. 

Is there a way to check a specific posts index status or maybe a tool that can give us a list of items that are not in the ElasticPress system?

**Comment by felipeelia** [comment]
Replying to #3955 here.

@gwhitehead Are you running those wp-cli calls with the `--show-errors` flag? Perhaps there is an error going on and you are not seeing it.

> Now the continuation of my issue. There are times that Custom Post Types are not indexed even though published. There is times that we run into a post that has been published, its post type is set to be indexed via Elasticpress. An appropriate weight has been set for the items within the post. Yet the item is not indexed on the initial publishing of said item. We are not able to truly track down what is causing this item to not be listed in the search results or in the auto-suggest.

One clarification is needed here. On Elasticsearch/ElasticPress there are two main moments: index-time and search-time. Weights are only applied during search-time and won't have any relation with problems during indexing a content.

In ElasticPress > Status Report there is a section called "Failed Queries". In that section you should be able to see any request to Elasticsearch that has failed.

> I wonder if doing a command line sync whether the setup flag is used or not would then reindex everything but possibly miss something that we do not know has been missed.

The setup flag deletes everything every time. The only it could miss something is if it either fails (hence why the --show-errors flag is so important) or if something is intentionally skipped (by some custom code, for example.)  The full reference of the wp-cli command can be seen [here](https://10up.github.io/ElasticPress/tutorial-wp-cli.html).

> Is there a way that we can have a reporting page and/or system that shows us items that should be showing in search results that are not actually in the Elasticpress DB? Or is there functionality in the system that can allow me to query the Elasticpress for index status based on ID?

There is not. You can always fire queries to your Elasticsearch server directly but, obviously, it will only return the IDs that are indexed.
