### ISSUE TITLE
Searching for wildcards in search_fields meta

### ISSUE THREAD

**Issue by paulhuisman** [10up/ElasticPress#394]
Hi there,

I'm using ElasticPress with Advanced Custom Fields, and right now my query looks like this:

``` php
$args = array(
  's'              => $context['search_query'],
  'posts_per_page' => 10,
  'paged'          => $paged,
  'search_fields'  => array(
    'post_title',
    'meta' => array(
      'teaser_text',
      'building_blocks_0_text',
      'building_blocks_1_text',
      'building_blocks_2_text',
      'building_blocks_3_text',
      // etc
    ),
  ),
);

$query = new WP_Query($args);
```

Is there a away to add a wildcard like `building_blocks_%_text` so i don't have to add every field id?

**Comment by tlovett1** [comment]
Nope, not right now. This could definitely be a future enhancement.

**Comment by pratham2003** [comment]
I was trying to build an API for autocomplete based only on post_title and the following worked for me.
```php
function set_es_search_args( $ep_formatted_args, $args ) {
  if( isset( $args['autocomplete'] ) && $args['autocomplete'] ) {
    $ep_formatted_args['query'] = array( 'wildcard' => array( 'post_title' => $args['s'] ) );
  }
  return $ep_formatted_args;
}
add_filter( 'ep_formatted_args', 'set_es_search_args', 300, 2 );
```
After that all I have to do is pass 'autocomplete' => true and pass the search term as 's' parameter with wildcard characters '*' or '?' as mentioned on this link : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html

e.g. if you wanted to search for partial words the search term should be like *ight*

**Comment by breadadams** [comment]
As a bit of a workaround on _your_ end @paulhuisman you could do something like the following:

```
$field_count = 10;

for ($i = 0; $i <= $field_count; $i++) {
    $args['search_fields']['meta'][] = "building_blocks_{$i}_text";
}
```

You could also modify it into a simple reusable function if you've got multiple field names to add to the array

**Comment by paulhuisman** [comment]
Thanks for the tip, this is how i fixed it back in the day as well ;)

**Comment by lolafrerot** [comment]
> Hi there,
> 
> I'm using ElasticPress with Advanced Custom Fields, and right now my query looks like this:
> 
> ```
> $args = array(
>   's'              => $context['search_query'],
>   'posts_per_page' => 10,
>   'paged'          => $paged,
>   'search_fields'  => array(
>     'post_title',
>     'meta' => array(
>       'teaser_text',
>       'building_blocks_0_text',
>       'building_blocks_1_text',
>       'building_blocks_2_text',
>       'building_blocks_3_text',
>       // etc
>     ),
>   ),
> );
> 
> $query = new WP_Query($args);
> ```
> 
> Is there a away to add a wildcard like `building_blocks_%_text` so i don't have to add every field id?

Hello, i'm using ACF too but I miss the step of the filter or the function to use.. Where do you put this code ?

Thanks a lot, 

Lola

**Comment by felipeelia** [comment]
For those interested in this feature, it is available in ElasticPress Labs: https://github.com/10up/ElasticPressLabs/
