### ISSUE TITLE
Unified Extensibility APIs in WordPress 6.6

### ISSUE THREAD

**Issue by vikrampm1** [10up/ElasticPress#3942]
WordPress 6.6 unified the different slots and extensibility APIs between the post and site editors.

Please check the extension and validate the following along with the version bump issue:

- [ ] Check if the plugin is integrating twice, once with wp.editPost and once using wp.editSite
- [ ] If yes, then update those to use wp.editor global variable (@wordpress/editor package or wp-editor script handle) as noted here https://make.wordpress.org/core/2024/06/18/editor-unified-extensibility-apis-in-6-6/

**Comment by kirtangajjar** [comment]
I had a look at this and we only use `@wordpress/edit-post` and not `edit-site`, so we don't need to do anything here.
