### ISSUE TITLE
PHP 8.2: Warnings about deprecated usage of strtolower

### ISSUE THREAD

**Issue by MattWilliamsDev** [10up/ElasticPress#3944]
While running a network-wide `sync`, we saw numerous instances of `Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/wp-content/plugins/elasticpress/includes/classes/IndexHelper.php on line 297`.

Some of the items we were syncing did not have `label['plurals']` defined, leading to `null` being passed to `esc_html( strtolower( $indexable->labels['plural'] ) )`, spurring the warning. While this can certainly be avoided in the implementation, I also believe simple steps could be taken to safeguard against this warning.

**Comment by burhandodhy** [comment]
Hi @MattWilliamsDev,

Thank you for reporting the bug. We will try to have it fixed in the next version. Would you like to open a Pull Request with the fix? Thanks!

**Comment by MattWilliamsDev** [comment]
> Hi @MattWilliamsDev,
> 
> Thank you for reporting the bug. We will try to have it fixed in the next version. Would you like to open a Pull Request with the fix? Thanks!

I will try and put something in tomorrow if possible. Holiday today.

**Comment by burhandodhy** [comment]
Hi @MattWilliamsDev,

I looked into this issue and found that it can only occur when you have a custom indexable that doesn't have the plural label because all defined Indexable have a plural label, for example https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L51

Could you please check if that’s the case for you?

Regards,
Burhan

**Comment by MattWilliamsDev** [comment]
It definitely was the cause. Sorry I forgot to update that here.

**Comment by burhandodhy** [comment]
Hi Matt,

The warning is generated by custom code, not the plugin itself. You simply need to set the `plural` label in your code. Since no further action is required on our side, we will proceed with closing this issue.

Regards,
Burhan
