### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by aharalambopoulos** [10up/ElasticPress#3946]
![Screenshot 2024-07-11 at 12 22 11](https://github.com/10up/ElasticPress/assets/52575846/4e8d3d53-e810-4423-8a1a-6dad59652f00)
### Describe the bug

When I'm trying to sync following error message appears.
2024-07-11 12:20:05
Sync paused
2024-07-11 12:20:09
Resuming sync…
2024-07-11 12:20:09
Permission denied. Reload the sync page and try again.
2024-07-11 12:20:09
Sync failed

### Steps to Reproduce

goto to sync 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@iastinf that is generally caused by wrong permissions in your Elasticsearch installation. Are you sure your website server can connect to your Elasticsearch server? The best way to test that is to go to your site terminal and try to make a curl request to your ES server.

**Comment by aharalambopoulos** [comment]
@felipeelia  My website can connect to the elasticserver. Everything works great. I'm afraid this is a harmful error/warning, or not.

**Comment by felipeelia** [comment]
If all syncs fail, I'm afraid it can not connect to your Elasticsearch server, @iastinf. You can install our [Debugging Add-on](https://www.elasticpress.io/documentation/article/using-the-elasticpress-debugging-add-on-plugin/) and visit a search page to see if ElasticPress is able to send queries to your ES server and if it is responding accordingly.

**Comment by aharalambopoulos** [comment]
using the Query Monitor I didn't see any error

grep status_code  debug-bar-elasticpress-report.txt 
status_code: 200
status_code: 200
status_code: 200

![Screenshot 2024-07-11 at 16 14 42](https://github.com/10up/ElasticPress/assets/52575846/bb3b8c8c-a3ae-436d-8564-1029ac0fa33f)

**Comment by aharalambopoulos** [comment]
Problem fixed:
The setup consists of one NGINX reverse proxy acting as L7-LB in front of a multi-node cluster running WP.

After adding the lines in the nginx's config

upstream all_backends{
     ip_hash;	
     keepalive 8;
....
}

to enable the sticky sessions, the problem was solved.
Thank you @felipeelia  for your time. 
Have a great day and WE
