### ISSUE TITLE
When is ElasticPress getting post data?

### ISSUE THREAD

**Issue by markzero** [10up/ElasticPress#395]
I guess `ep_search` function is used for getting data from Elasticsearch through it's API.

But the variable `$new_posts` is always empty after this line:

https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-wp-query-integration.php#L256

Filter `ep_wp_query_search_cached_posts` exists nowhere, so when does it get inside the following IF statement and fill `posts_by_query` property?

**Comment by allan23** [comment]
Hi @markzero, sorry for the late reply. As explained in #337, you can use the ``ep_wp_query_non_cached_search`` action to cache results and then feed them to the ``ep_wp_query_search_cached_posts``.

I hope this makes sense. Let me know if you need further clarification.
