### ISSUE TITLE
EP_CREDENTIALS not applied in the the case of locally hosted elasticsearch

### ISSUE THREAD

**Issue by dingo-d** [10up/ElasticPress#3950]
### Describe your question

I'm trying to play around with elasticsearch, so I've set it up locally, and I can go to `localhost:5601`, and see the dashboard.

To avoid certificate issues, I've also applied the solution from [this comment](https://github.com/10up/ElasticPress/issues/594#issuecomment-262495332). 

But my installation uses username and password, and it looks like adding

```php
define('EP_CREDENTIALS', 'elastic:abcd12345');
```

doesn't work, as I keep getting

> There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again, or you may need to change your settings.

When I don't add it I get 

> There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again, or you may need to change your settings. Response Code: 401 Response error: Unauthorized

The cURL request being made (from query monitor debugger) is:

```bash
curl -XGET -H 'Content-Type: application/json' -H 'X-ElasticPress-Request-ID: 15a8a278881340e884e26badf73588d8' 'https://localhost:9200/_nodes/plugins'
```

When I do it from my terminal like this:

```bash
curl -XGET -k -u "elastic:abcd12345" -H 'Content-Type: application/json' -H 'X-ElasticPress-Request-ID: 5e02ec3e696b429aaf328f9ebc1d7341' 'https://localhost:9200/_nodes/plugins'
```

It works.

I could modify the `wp_remote_request` arguments. But I'm not sure that's the right way.

Also just setting the URL from the admin doesn't work. Only setting it via constant in `wp-config.php` works 🤷🏼‍♂️ 

I'm not sure if `EP_CREDENTIALS` constant is used just to connect to your SaaS solution or if it's used for local installations as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @dingo-d. Yes, EP_CREDENTIALS is meant to be used for our service. In your case, you'll likely need to define the ES_SHIELD constant. Something like this in your wp-config.php file:

```php
define( 'ES_SHIELD', '<username>:<password>' );
```

Can you give that a try and let us know if it worked?

**Comment by dingo-d** [comment]
In the end I just set up local elastic not to use SSL, and that worked, but from the code I think the above solution would be correct. I'll try to set it up with the certs later on after some more tinkering with it, so I'll close the issue.

Thanks for the help!
