### ISSUE TITLE
Is it possible to index custom taxs with public=false?

### ISSUE THREAD

**Issue by yarovikov** [10up/ElasticPress#3960]
### Describe your question

Hi there, 

I have a small problem: i need to index cpt with taxonomies. But i'v got

```
register_taxonomy('blog-category', 'blog', [
            'hierarchical' => true,
            'show_admin_column' => true,
            'public' => false, // this because of i'm using ajax filter, i don't need category pages
            'show_ui' => true,
            'show_in_rest' => true,
        ]);
```

Maybe there is some filter to add that manually? Thanks :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @yarovikov, you'll need the [`ep_sync_taxonomies`](https://10up.github.io/ElasticPress/ep_sync_taxonomies.html) filter to index them with your cpt, and then [`ep_weighting_fields_for_post_type`](https://10up.github.io/ElasticPress/ep_weighting_fields_for_post_type.html) to add the taxonomy to the Weighting Dashboard.

**Comment by yarovikov** [comment]
> Hi @yarovikov, you'll need the [`ep_sync_taxonomies`](https://10up.github.io/ElasticPress/ep_sync_taxonomies.html) filter to index them with your cpt, and then [`ep_weighting_fields_for_post_type`](https://10up.github.io/ElasticPress/ep_weighting_fields_for_post_type.html) to add the taxonomy to the Weighting Dashboard.

Thanks, work ❤️
