### ISSUE TITLE
BUG: Slow query in Sync Settings page

### ISSUE THREAD

**Issue by majiix** [10up/ElasticPress#3965]
### Describe the bug

On visiting Sync Settings page while query monitor is active i get this slow query in the log for elasticPress:

Query:
```
SELECT DISTINCT meta_key
FROM wp_postmeta
WHERE meta_key NOT LIKE '\\_%'
LIMIT 800
```

Caller:
`ElasticPress\I\P\Post->get_distinct_meta_field_keys_db()`

### Steps to Reproduce

1- Activate query monitor
2- activate elasticpress
3- visit sync settings page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Thanks for opening the issue @majiix. That comes from `AdminNotices::process_too_many_fields_notice()` and we'll work on a change to have it work better on EP 5.0 (since the meta field calculation can be done differently now.)

In the meantime, this snippet should skip that check:

```php
add_filter( 'pre_option_ep_hide_too_many_fields_notice', '__return_true' );
```
