### ISSUE TITLE
Custom search reslut slug

### ISSUE THREAD

**Issue by alifazeli** [10up/ElasticPress#3967]
### Describe your question

Hi
I want to change default WordPress search result slug from [domain.com/?s=search_term] to something like  [domain.com/niches/search_term].
For next pages, It will be like [domain.com/niches/search_term/2/] or [domain.com/niches/search_term/page/2/], something like categories and tags pages.

Does it affect ElasticPress function in some way?

Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @alifazeli,

No, as long as the site relies on WP Query for searching, ElasticPress will continue to function seamlessly.

Regards,
Burhan
