### ISSUE TITLE
Disabling or controling fuzziness for term search

### ISSUE THREAD

**Issue by ognjanovic** [10up/ElasticPress#3970]
### Describe your question

Hi,

I'm trying to prevent fuzziness for term search in edit post screen (where search is done via the rest api like this /wp-json/wp/v2/tags?context=view&per_page=20&_fields=id%2Cname&search=testing&_locale=user), but filters from the docs are not working, even the full disabling using this bellow is not working

`add_filter( 'ep_term_match_fuzziness', '__return_zero' );`

I also tried `ep_term_fuzziness_arg` returnig 0 from the callback function, as well as `ep_term_formatted_args`, but the last one is not fired at all during this search.

This is the log of the query and as you can see there is the last `multi_match` part where fuzziness is always set to 1

`"query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": "testing",
                        "type": "phrase",
                        "fields": [
                            "name",
                            "slug",
                            "taxonomy",
                            "description"
                        ],
                        "boost": 4
                    }
                },
                {
                    "multi_match": {
                        "query": "testing",
                        "fields": [
                            "name",
                            "slug",
                            "taxonomy",
                            "description"
                        ],
                        "boost": 2,
                        "fuzziness": 0,
                        "operator": "and"
                    }
                },
                {
                    "multi_match": {
                        "fields": [
                            "name",
                            "slug",
                            "taxonomy",
                            "description"
                        ],
                        "query": "testing",
                        "fuzziness": 1
                    }
                }
            ]
        }
    }`

Any help?

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @ognjanovic,

The `add_filter( 'ep_term_fuzziness_arg', '__return_zero' );` filter should work. I have tested it, and it’s functioning as expected. Could you please let me know how you are adding this filter? It needs to be added outside of any other filter. For example, you can add it directly to the theme's `functions.php` file.

Regards,
Burhan

**Comment by ognjanovic** [comment]
Hi @burhandodhy ,

Yes, it's in the themes `functions.php`.

Funny, but when I used `ep_term_fuzziness_arg` with a callback function that returns 0 it didn't work, and now with `__return_zero` it works. Damn.

Thanks.
