### ISSUE TITLE
BUG: passing null value to prepare_date_items() leads to deprecation warning in strtotime()

### ISSUE THREAD

**Issue by barryceelen** [10up/ElasticPress#3971]
### Describe the bug

The `$post_date` variable [passed to `Post->prepare_date_items()`](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L512) in `Post->prepare_document()` [can be `null`](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L464). `Post->prepare_date_items()` [uses that value in a `strtotime()` call](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L621). Passing `null` to `strtotime()` results in a PHP deprecation warning.

`...Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in...`

### Steps to Reproduce

Indexing a post with `$post->post_date` set to `0000-00-00 00:00:00` or an otherwise invalid `$post->post_date` value results in the `$post_date` variable being set to `null`:

https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L463

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Thanks @barryceelen! Any chance you can open a PR with the fix?
