### ISSUE TITLE
BUG: Breaks default "menu order" sorting of woocommerce categories without a search

### ISSUE THREAD

**Issue by TwoLoonSoftware** [10up/ElasticPress#3973]
### Describe the bug

ElasticPress should not affect the sort order of non-search categories.

Products order can be set with "menu order" in WooCommerce.
Installing the ElasticPress plugin keeps this standard WooCommerce functionality from working.

### Steps to Reproduce

1. Set the menu order of products for a woocommerce category to something arbitrary but manually defined
2. Install ElasticPress
3. Enable "WooCommerce"
4. See that the previous order of the category products is no longer correct

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi [TwoLoonSoftware](https://github.com/TwoLoonSoftware),

I followed the steps you mentioned; however, I'm unable to replicate the issue. To investigate further, could you please share the Elasticsearch query body and result? You can obtain both by installing the 'ElasticPress Debugging Addon'. You can learn more about it [here](https://www.elasticpress.io/documentation/article/using-the-elasticpress-debugging-add-on-plugin/).

Regards,
Burhan
