### ISSUE TITLE
BUG: Elasticpress Sync time get error 

### ISSUE THREAD

**Issue by amitdipal** [10up/ElasticPress#3974]
### Describe the bug

 I have changed the endpoint and tried to sync data, but it gets an error, moves into an infinite loop, and the site gets down.
 current index 
 
**site has old indexes** 
localdevlendingtreecom8000cms-post-1green 
search-applog-prodgreen 
search-phrase-prodgreen 
localhost8081cms-1green 
mywwwlendingtreecomcms-1green 
search-applog-devgreen 
poweredbylendingtreecomcms-post-1green 
localhost8000cms-post-1green 
wplendingtreecomcms-1green 
lendingtreecomcms-1green 
.kibana-4green 
search-nonwp-prodgreen 
preprodlendingtreecomcms-post-1green 
lendingtreecomcms-post-1green 
localhost8000cms-1

**Total Documents: 3071274**
**Total Size: 2.9GB**

Question: Why is the old index list too much? Does it need this much while the new point is set?  why does it sync show on prod like localhost, and nonoprod, these are why shows in the index list of prod.  Is it needed or fresh sync with the current site is fine please suggest
**old endpoint configure** with **elastic search 2.3.2**
Elasticsearch Host URL: **new endpoint** (which is configured **elastic search 7.10.2**) set and try to sync it get an error after 450 document sync.  and some database queries load continuously and the db gets high and the site gets down. so what way we will change the endpoint? and sync all data  OR sync all data needed?

no error was found in sumo.  but it stopped syncing, an error while sync displayed once.

please suggest what we should do. does need to sync all indexes.  OR any way error did not occur while syncing Total Documents: 3071274  

### Steps to Reproduce

Elasticsearch Host URL: new endpoint (which is configured elastic search 7.10.2) set and try to sync it get an error after 450 document sync. and some database queries load continuously and the db gets high and the site gets down. so what way we will change the endpoint? and sync all data OR sync all data needed?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @amitdipal,

Could you please try to sync via the WP-CLI command `wp elasticpress sync --setup --yes --show-errors  --force`? This command will display an error if one occurs.

If the command fails, try passing a lower value, such as 50, to the `per-page` flag. You can learn more about the available flags here https://10up.github.io/ElasticPress/tutorial-wp-cli.html

Regards,
Burhan

**Comment by amitdipal** [comment]
We don't use wp-cli because it runs in a AWS ECS and Fargate. can you please suggest on this

**Comment by amitdipal** [comment]
Hello @burhandodhy  please answer about this 

We don't use wp-cli because it runs in a AWS ECS and Fargate. can you please suggest on this

**Comment by amitdipal** [comment]
Hello @burhandodhy, We don't use wp-cli because it runs in an AWS ECS and Fargate. can you please suggest on this

**Comment by burhandodhy** [comment]
Hi @amitdipal,

It's difficult to determine the cause of the issue without the CLI command. It might be related to third-party code. Could you deactivate all plugins except ElasticPress to check if the issue persists? We recommend performing this test on a non-production site.

Regards,
Burhan
