### ISSUE TITLE
Using Elastic for Categories

### ISSUE THREAD

**Issue by majiix** [10up/ElasticPress#3978]
### Describe your question

Hi,
I have more than 3K categories for woocommerce. i wanted to know is it possible to use elastic plugin to index categories and query them in future? how is it possible?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @majiix! You can use our Term Indexable to do that. More here: https://www.elasticpress.io/documentation/article/indexables/#term-indexable
