### ISSUE TITLE
BUG: WooCommerce drag&drop product order not synced for shops with more than 350 products

### ISSUE THREAD

**Issue by alexanderaltendorfer** [10up/ElasticPress#3988]
### Describe the bug

When ordering WooCommerce products via drag&drop, their menu_order is updated and the affected products need to be synced to ElasticPress. The ElasticPress plugin handles this in https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/WooCommerce/Products.php#L572

However, the function bails out if the total product count is larger than the "Content Items per Index Cycle" setting (default 350). This means that the sync does not start at all for large shops. Increasing the "Content Items per Index Cycle" setting temporarily fixes the issue, but at some point would result in timeouts or memory issues.

For a more robust solution, the syncing should be handled in batches that are handled asynchronously in the background.

### Steps to Reproduce

1. Install ElasticPress and WooCommerce
2. Enable WooCommerce integration in ElasticPress
3. Create more than 350 products
4. Change order of a product via drag&drop in the products admin table
5. The order on the frontend is not changed when queried via EP

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
To change the current behavior we have to implement sync in the background, which is not a small lift. Thank you for opening the issue, @alexanderaltendorfer, but I'll close this one now, as this issue will definitely come up again when we come up with a reliable way to sync whole sites in the background.
