### ISSUE TITLE
ElasticPress Query Log

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3989]
### Describe your question

Hi all!

ElasticPress Query Log - Logging is disabled in the settings.
Status Report page in the logs it registers requests that are executed longer than 5s elasticpress-status-report#failed-queries
Requests are registered randomly. Out of 10,000 are written to the log 5.

The question is:
Why does it still write to the journal when the log is turned off?
How do I change this limit?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
ElasticPress Query Log comes from [ElasticPress Debugging Add-On](https://github.com/10up/debug-bar-elasticpress), it is not an ElasticPress default functionality.

The queries stored in the Status Report, on the other hand, are ElasticPress's core related. You can use the `ep_query_logger_queries_to_keep` filter to change that limit. Please note that setting it to 0 will not disable logging, but simply remove the limit, logging everything.

If you want to disable the Status Report queries log (although we don't recommend doing so), you can use the `ep_query_logger_allowed_log_types` filter, with something like `add_filter( 'ep_query_logger_allowed_log_types', '__return_empty_array' );`.
