### ISSUE TITLE
Comments Index

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#4003]
### Describe your question

Hi all. The description of the plugin says:
`Comments: Indexes your comments and provides a widget with type-ahead search functionality. It works with WooCommerce product reviews out-of-the-box.`
But I do not see comments indexation in the settings of the parameters. There are no separate index, there are no weights, the ElasticLab is turned on. Woocommerce is not included.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @ws256, the Comments feature will create a new index for comments and will be used when you run a WP_Comment_Query with the 'search' parameter or 'ep_integrate' as true. At this time, we do not provide a dashboard to weigh separate fields, you'll need custom code for that.

Does that answer all your questions? Thanks!
