### ISSUE TITLE
BUG:  Issue with WordPress Default Media Attachment PDF Search Functionality via WP AJAX

### ISSUE THREAD

**Issue by mahesh-spinx** [10up/ElasticPress#4004]
### Describe the bug

I am experiencing an issue when performing keyword searches via AJAX in the default WordPress media attachment PDFs. Specifically, when using the WP_Query with ElasticPress integration, the search results do not appear in the AJAX callback. However, the same query works correctly when the page is reloaded. This is specific for attachment post

Could you please assist in resolving this issue or provide guidance on how to troubleshoot the AJAX search functionality with ElasticPress?

I added ajax function code for your reference.

Thank you for your support.

### Steps to Reproduce

```
function attach_search_datatable() {	
        add_filter( 'ep_ajax_wp_query_integration', '__return_true' );
        add_filter( 'ep_enable_do_weighting', '__return_true' );
	 
	$args = array(
	'post_type'      => 'attachment',
	'posts_per_page' => 10,        
	's'               => 'document', 
	'ep_integrate'    => true        		
	);
	
	$query = new WP_Query( $args );
	if ( $query->have_posts() ) :
		while ( $query->have_posts() ) : $query->the_post();
			echo '<a href="' . get_permalink() . '">' . get_the_title() . '</a><br>';
		endwhile;
		

		wp_reset_postdata();
	else :
		echo 'No PDFs found.';
	endif;
	
	wp_die();
}
add_action('wp_ajax_nopriv_attach_search_datatable', 'attach_search_datatable');
add_action('wp_ajax_attach_search_datatable', 'attach_search_datatable');
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
The code looks right, @mahesh-spinx, I'd only check the post status. You can follow [this article](https://www.elasticpress.io/documentation/article/using-the-elasticpress-debugging-add-on-plugin/#debugging-ajax-and-rest-api-responses) to troubleshoot AJAX requests.
