### ISSUE TITLE
BUG: query logging memory hog

### ISSUE THREAD

**Issue by davidsword** [10up/ElasticPress#4006]
### Describe the bug

Big bulk operations in the WP-CLI context on an environment where `WP_DEBUG` is `true` can, in some use cases, result in an unsustainable growth of this query logging:

https://github.com/10up/ElasticPress/blob/72e9dc0debc7a7f37d4164362f1024e64d7f3750/includes/classes/Elasticsearch.php#L1738-L1740

A filter should be added to the conditional for this query logging so the logging can be explicitly disabled for these bulk operations without having to change the `WP_DEBUG` constant, ex:

```diff
public function add_elasticpress_version_to_user_agent( $user_agent ) {
	 * @param array $query Query to log.
	 */
	protected function add_query_log( $query ) {
-		if ( ( defined( 'WP_DEBUG' ) && WP_DEBUG ) || ( defined( 'WP_EP_DEBUG' ) && WP_EP_DEBUG ) ) {
+		$disable_logging = apply_filters( 'ep_disable_query_logging', false );
+		if ( ! $disable_logging && ( ( defined( 'WP_DEBUG' ) && WP_DEBUG ) || ( defined( 'WP_EP_DEBUG' ) && WP_EP_DEBUG ) ) ) {
			$this->queries[] = $query;
		}
```

### Steps to Reproduce

This doesn't happen on out of the box EP installs, but can happen in certain use cases. For us at VIP it happens out of the box for how we're using EP (more on this later), to replicate:

- setup local wp site [using `vip dev-env`](https://docs.wpvip.com/vip-local-development-environment/), ensure "Enable Elasticsearch"
- set vip-config.php to

```php
define( 'WP_DEBUG', true );
define( 'VIP_ENABLE_VIP_SEARCH', true ); // Enable Enterprise Search
define( 'VIP_ENABLE_VIP_SEARCH_QUERY_INTEGRATION', true ); // Integrate search queries with Enterprise Search
```

- have some posts on the site
- create following wpcli cmd

```php
if ( defined('WP_CLI') && WP_CLI ) {
    class Test_CLI_Command {

        public function ing( $args, $assoc_args ) {
            global $wpdb;

            wp_defer_term_counting( true );
            $counter = 0;
            // loop forever to replicate a huge sites bulk operation
            while ( true ) {
                $posts = get_posts( [
                    'post_type' => 'post',
                    'posts_per_page' => -1,
                    'fields' => 'ids',
                ] );
                foreach ( $posts as $post_id ) {
                    update_post_meta( $post_id, 'test', rand() );

                    \WP_CLI::line( "MEMORY: " . round(memory_get_peak_usage() / 1024 / 1024, 2) . "MB" );
                    
                    $counter++;
                    if ($counter % 100 === 0 ) {
                        \WP_CLI::line("batch of 100 done");

                        // memory cleanup 
	                $wpdb->queries = array();
                    }
                }
            }
        }
    }
    WP_CLI::add_command( 'test', 'Test_CLI_Command' );
}
```

- run the cmd `wp test ing`
- notice the slow growth of memory usage (about +0.01mb every handful of posts)
- comment out this https://github.com/10up/ElasticPress/blob/72e9dc0debc7a7f37d4164362f1024e64d7f3750/includes/classes/Elasticsearch.php#L1739
- run cmd again, notice no slow growth of memory

This is happening specifically on VIP's use case because:

- [updated_post_meta in custom cli script triggers this](https://github.com/Automattic/vip-go-mu-plugins-built/blob/4d1d391fdcc962d295b335bf2df9ff154ff13826/search/elasticpress/includes/classes/Indexable/Post/SyncManager.php#L59)
- [EP does a kill_sync check on that callback](https://github.com/Automattic/vip-go-mu-plugins-built/blob/4d1d391fdcc962d295b335bf2df9ff154ff13826/search/elasticpress/includes/classes/Indexable/Post/SyncManager.php#L151)
- [kill_sync runs this filter](https://github.com/Automattic/vip-go-mu-plugins-built/blob/4d1d391fdcc962d295b335bf2df9ff154ff13826/search/elasticpress/includes/classes/SyncManager.php#L233) 
- [which VIP taps into here](https://github.com/Automattic/vip-go-mu-plugins/blob/87ffe8c418151b0fa041395be1b967cbcd0681d6/search/includes/classes/class-search.php#L633)
- [where VIP does an index_exists check](https://github.com/Automattic/vip-go-mu-plugins/blob/87ffe8c418151b0fa041395be1b967cbcd0681d6/search/includes/classes/class-search.php#L2221)
- [index_exists makes a remote request here](https://github.com/Automattic/vip-go-mu-plugins-built/blob/4d1d391fdcc962d295b335bf2df9ff154ff13826/search/elasticpress/includes/classes/Elasticsearch.php#L1029)
- [which then gets unsustainably logged here](https://github.com/Automattic/vip-go-mu-plugins-built/blob/4d1d391fdcc962d295b335bf2df9ff154ff13826/search/elasticpress/includes/classes/Elasticsearch.php#L1252
)

We reviewed how we've hooked into this for the index check, but we believe it would be best to have a filter for this query logging so this logging can be disabled entirely in the WP-CLI context without using the wider-use WP_DEBUG constant.

### Screenshots, screen recording, code snippet

see above

### WordPress and ElasticPress information

WP 6.6
EP 4.2.2

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Makes sense, @davidsword. Would you or your team have the availability to craft a PR with that new filter?

**Comment by rebeccahum** [comment]
@felipeelia Done in #4019
