### ISSUE TITLE
WP Sync CLI - limit-object-id

### ISSUE THREAD

**Issue by EnigmaPatrick** [10up/ElasticPress#4013]
### Describe your question

Hey,

I'm a bit confused by the documentation here; 

[--upper-limit-object-id=<ID>]: Upper limit of a range of IDs to be indexed. If indexing IDs from 30 to 45, this should be 45
[--lower-limit-object-id=<ID>]: Lower limit of a range of IDs to be indexed. If indexing IDs from 30 to 45, this should be 30

When it refers to object-id, what specifically is it referring to - post_id? document count? 

Thanks for your help!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Those would be the post (comment, term, or user) ID, @EnigmaPatrick.
