### ISSUE TITLE
How modify/extend term data appended to post ES document

### ISSUE THREAD

**Issue by creative-andrew** [10up/ElasticPress#4015]
### Describe your question

Hi! 

I am working with the ElasticPress plugin and have encountered a limitation when trying to extend or modify the term data that is appended to the post Elasticsearch document.

The current implementation in the `get_formatted_term()` method does not provide a way to add or modify the data included in the Elasticsearch document for terms:

https://github.com/10up/ElasticPress/blob/53990f8c488af660592dc10a7cb0104dc4b90b6d/includes/classes/Indexable/Post/Post.php#L758

From what I can tell, there is no filter or hook available to modify or extend the `$formatted_term` array.

Feature Request:
I propose adding a filter, e.g., `ep_get_formatted_term`, to allow developers to extend or modify the term data before it is appended to the Elasticsearch document. 

I would like for this particular case, fetch and include the permalink for each of the term.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by creative-andrew** [comment]
Nevermind, I think I can just do it with `$post_args = apply_filters( 'ep_post_sync_args', $post_args, $post_id );` which comes afterwards.

**Comment by felipeelia** [comment]
Yup, that is the way to go, @creative-andrew!

**Comment by creative-andrew** [comment]
@felipeelia 

After doing the following 

```php
add_filter('ep_post_sync_args', function($args){
    if ($args['post_type'] === 'product' && !empty($args['terms'])) {
      foreach ($args['terms'] as $taxonomy => $terms) {
        $args['terms'][$taxonomy] = array_map(function ($term) use ($taxonomy) {
            $permalink = get_term_link($term['slug'], $taxonomy);
            $term['permalink'] = !is_wp_error($permalink) ? $permalink : '';
            return $term;
        }, $terms);
      }
    }
}, 10, 2);
```

I get the following error:

`"mapper_parsing_exception"`
`"object mapping for [terms.product_cat.permalink] tried to parse field [permalink] as object, but found a concrete value"`

Am I missing something?
