### ISSUE TITLE
BUG: cpt is not indexed when using ajax on the front

### ISSUE THREAD

**Issue by yarovikov** [10up/ElasticPress#4016]
### Describe the bug

Hi there
I have 2 cpt. No any problem when i add/delete in admin panel. But when user uses ajax (wp_insert_post/wp_trash_post) i see these posts on the front after deleting or not see when added. 
Any way to fix it? Thanks 

### Steps to Reproduce

- add cpt via ajax
- check on the front

### WordPress Environment ###
wp_version: 6.7.1
is_multisite: false
theme: VMS Sage (1.0.0)
plugins: ElasticPress (5.1.3), ElasticPress Debugging Add-On (3.1.0), ElasticPress Labs (2.3.0), Query Monitor (3.16.4), Term Management Tools (2.0.1), WP Crontrol (1.17.0) и Yoast SEO (23.9)
revisions: all

### Server Environment ###
php_version: 8.3.10
memory_limit: 40M
timeout: 900

## Indexable Content ##

post_count: 162 548
page_count: 32
blog_count: 100
task_count: 52
service_count: 53
attachment_count: 475 520
wp_font_family_count: 0
wp_font_face_count: 0
post_meta_keys: 11
page_meta_keys: 1
blog_meta_keys: 1
task_meta_keys: 0
service_meta_keys: 0
attachment_meta_keys: 0
wp_font_family_meta_keys: 0
wp_font_face_meta_keys: 0
total-all-post-types: 11
distinct-meta-keys: ads_plot_compound, ads_plot_format, ads_ratio, file_count_download, views, wpfp_favorites, is_3d, is_student_work, ep_exclude_from_search, plot_type и likes

### Settings ###
host: https://185.12.95.219:9200
index_prefix: 
language: ru_RU
per_page: 300
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### ..wp-post-1 ###
health: green
status: open
uuid: Yjf15HuoQDuqIEEJXscHxA
pri: 5
rep: 1
docs.count: 638302
docs.deleted: 159204
store.size: 6.6gb
pri.store.size: 3.3gb
total_fields_limit: 5000

### vmasshtaberuwp-user ###
health: green
status: open
uuid: mC-qalHuQbqUSruQUm4InQ
pri: 5
rep: 1
docs.count: 996086
docs.deleted: 35226
store.size: 1.5gb
pri.store.size: 798.1mb
total_fields_limit: 5000

### 2024/11/23 11:54:22 дп ###
method: WP Dashboard
is_full_sync: No
end_date_time: 2024/11/23 11:54:24 дп
total_time: 0 часов, 0 минут, 2 секунды
total: 102
synced: 102
skipped: 0
failed: 0
errors: array (
)
trigger: manual
final_status: success

### Did You Mean ###
active: true
force_inactive: false
search_behavior: list

### Post Search ###
active: true
decaying_enabled: 0
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple
synonyms: <pre># Defined synonyms

# Defined hyponyms.

# Defined replacements.</pre>
weighting: array (
  'post' => 
  array (
    'post_title' => 
    array (
      'weight' => 100,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 30,
    ),
    'post_excerpt' => 
    array (
      'weight' => 0,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 0,
      'enabled' => false,
    ),
    'terms.post_tag.name' => 
    array (
      'enabled' => true,
      'weight' => 40,
    ),
    'terms.category.name' => 
    array (
      'enabled' => true,
      'weight' => 30,
    ),
    'meta.ads_plot_compound.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.ads_plot_format.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.ads_ratio.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.plot_type.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.file_count_download.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.views.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.wpfp_favorites.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.is_3d.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.is_student_work.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
    'meta.likes.value' => 
    array (
      'weight' => 0,
      'enabled' => true,
    ),
  ),
  'page' => 
  array (
    'post_title' => 
    array (
      'weight' => 100,
      'enabled' => true,
    ),
    'post_content' => 
    array (
      'weight' => 60,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
  ),
  'blog' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 100,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 40,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
  ),
  'task' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
  ),
  'service' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_content' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'post_excerpt' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
    'author_name' => 
    array (
      'enabled' => true,
      'weight' => 1,
    ),
  ),
)

### Protected Content ###
active: true
force_inactive: false

### Related Posts ###
active: true
force_inactive: false

### Search Algorithm Version ###
active: true
force_inactive: false
search_algorithm_version: 4.0

### Users ###
active: true
force_inactive: false

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @yarovikov, can you please share the entire code you are using to call those functions?
It won't index your posts if you have the WP_IMPORTING constant set, for example.

As EP adds all new posts to a queue and index everything when the shutdown function is called, you may need to call `ElasticPress\Indexables::factory()->get( 'post' )->sync_manager->index_sync_queue();` directly from your code in some cases.

**Comment by yarovikov** [comment]
Hi @felipeelia thanks, but i'm getting false here for all cpt excluding 'post'

```
$factory = Indexables::factory();
$indexable = $factory->get('task');
dd($indexable);
```

i'v checked regisered cpt via ep_indexable_post_types, i see there all my cpt

Array
(
    [post] => post
    [page] => page
    [blog] => blog
    [task] => task
    [service] => service
)

**Comment by felipeelia** [comment]
In this case, you'll want to use `get( 'post' )` to all CPTs, @yarovikov. That slug is the EP Indexable, which is the same for all posts, pages, and CPTs. Other indexables are 'user', 'comment', and 'term', for example.

**Comment by yarovikov** [comment]
@felipeelia unfortunately it doesn't work

https://github.com/user-attachments/assets/b191c486-20ee-4dfb-be3a-3b8dd50fef91

ajax:

```php
public function deleteTask(): void
    {
        $task_id = (int) ($_POST['task_id'] ?? '');
        
        // ...some checks

        wp_trash_post($task_id);

        wp_send_json_success();
        wp_die();
    }

```

tasks block on the front:

```php
$args = [           
            'post_type' => ['task'],
            'post_status' => 'publish',
            'posts_per_page' => static::PER_PAGE,
            'fields' => 'ids',
            'ep_integrate' => true,
        ];

$query = new WP_Query($args);
$posts = $query->posts;
```

`'ep_integrate' => false` works as expected

**Comment by ws256** [comment]
I have the same problem. You have to manually reindex the CTP.

**Comment by felipeelia** [comment]
@ws256 @yarovikov I've tried to reproduce the problem locally and could not. This is the code I'm using:

```php
function create_post_type() {
	register_post_type(
		'movie',
		[
			'labels'      => [
				'name'          => __( 'Movies' ),
				'singular_name' => __( 'Movie' ),
			],
			'public'      => true,
			'has_archive' => true,
			'taxonomies'  => [ 'category' ],
			'show_in_rest' => true,
		]
	);
}
add_action( 'init', 'create_post_type' );

add_action(
	'wp_ajax_nopriv_ep_test',
	function() {
		wp_trash_post( 83 );

		wp_send_json_success();
		wp_die();
	}
);

if ( ! is_admin() ) {
	$args = [
		'post_type'      => [ 'movie' ],
		'post_status'    => 'publish',
		'posts_per_page' => 10,
		'fields'         => 'ids',
		'ep_integrate'   => true,
	];

	$query = new \WP_Query( $args );
	echo '<pre>';
	print_r( $query );
	echo '</pre>';
	die();
}
```

Then I create a movie and publish it. If I send a POST request to /wp-admin/admin-ajax.php with action=ep_test, 100% of time I see the result of WP_Query changing the way I'd expect.

That said, unless you provide the full steps (including code) to reproduce the error in a fresh EP/WP install, we won't be able to help you much with your problem.

**Comment by yarovikov** [comment]
Hi @felipeelia. So strange 

But currently this was decided my problem  

```
wp_trash_post($task_id);

Indexables::factory()->get('post')->delete($task_id);

wp_send_json_success();

wp_die();
```

**Comment by felipeelia** [comment]
Great, @yarovikov, thanks for sharing.
