### ISSUE TITLE
Initial indexing fails due to fatal error with 'WP_Widget'

### ISSUE THREAD

**Issue by tvanantwerp** [10up/ElasticPress#402]
When I run `wp elasticpress index --setup`, I get this error:

```
Fatal error: Class 'WP_Widget' not found in /var/www/html/wp-content/plugins/wordpress-popular-posts/wordpress-popular-posts.php on line 56
```

I haven't got a clue why the WordPress Popular Posts widget would even be involved with the ElasticPress indexing. I deleted the WPP plugin entirely, and it didn't help. Here's the message I got after that:

```
Fatal error: Class 'WP_Widget' not found in /var/www/html/wp-includes/widgets/class-wp-widget-pages.php on line 17
```

I just updated to WordPress 4.4, so maybe there's a breaking change in there I'm not aware of? I don't know why widgets come into play for indexing in the first place.

**Comment by philipnewcomer** [comment]
@tvanantwerp I just experienced that issue this morning. You need to update WP-CLI to be compatible with WordPress 4.4. See https://github.com/wp-cli/wp-cli/issues/2225
