### ISSUE TITLE
BUG: exclude individual posts from search meta box has disappeared

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#4022]
### Describe the bug

The "Exclude from search results" checkbox is no longer active in the post editor. This is the checkbox that sets `ep_exclude_from_search` meta field for individual posts you want to exclude from search.

### Steps to Reproduce

I'm using WP 6.7.1 and ElasticPress 5.1.3. When I open the post editor, the "Exclude from search results" option is no longer present. It was working just a few weeks ago, so without more debugging, I assume a WP update may have affected this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
I've just tested and using WP 6.7.1 and EP 5.1.3, I can still see the checkbox. We'll need you to send us your Status Report and if you have any errors in your browser's Console, @kevinlisota.
