### ISSUE TITLE
BUG: Wrong scope for 'All filters' string so it cannot be translated

### ISSUE THREAD

**Issue by arturomonge** [10up/ElasticPress#4023]
### Describe the bug

In `sidebar-toggle.js`, the string 'All filters' has the scope `elasticoress` instead of `elasticpress` so it cannot be translated.

https://github.com/10up/ElasticPress/blob/51d6e4688b7f044ecffd1931ee3d759fe611348e/assets/js/instant-results/components/tools/sidebar-toggle.js#L24

### Steps to Reproduce

Go to `sidebar-toggle.js` and review the string context in line 24 for the string `All filters`.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Good catch, @arturomonge! Do you want to open a PR to fix that typo? Thanks in advance!
