### ISSUE TITLE
BUG: Fuzziness Not Updated to Zero When Using "Default" Algorithm

### ISSUE THREAD

**Issue by burhandodhy** [10up/ElasticPress#4026]
### Describe the bug

When the plugin is using the "Default" algorithm, the query continues to have the fuzziness set to "auto", even after attempting to set it to 0 using the following filter:

`add_filter( 'ep_post_match_fuzziness',  '__return_zero' ); `

This is happening because this [filter](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Autosuggest/Autosuggest.php#L86) override these value we set through `ep_post_match_fuzziness` filter

### Steps to Reproduce

1. Set the Algorithm to default `wp elasticpress set-algorithm-version --version=default`
2. Add the filter to set the fuzziness `add_filter( 'ep_post_match_fuzziness',  '__return_zero' ); `
3. Perform a search on frontend and check the query body. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
For the default algorithm, the filter would be `ep_post_fuzziness_arg` (see [here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/SearchAlgorithm/DefaultAlgorithm.php#L112)). Did you try with that filter instead, @burhandodhy ?

**Comment by felipeelia** [comment]
Updated the [related documentation article](https://www.elasticpress.io/documentation/article/how-to-disable-fuzziness/) now.
