### ISSUE TITLE
Indexing Conflicts

### ISSUE THREAD

**Issue by codingideas** [10up/ElasticPress#403]
When I run wp elasticpress index from command line I get this: 

Fatal error: Class 'WP_Widget' not found in /wp-content/plugins/gravityforms/widget.php on line 16

I deactivate gravityforms 

Fatal error: Class 'WP_Widget' not found in /wp-content/plugins/akismet/class.akismet-widget.php on line 5

When I deactivate akismet I get this:

Fatal error: Class 'WP_Widget' not found in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-widget.php on line 11 

### WordPress Environment ###

WC Version: 2.5.0
Log Directory Writable: ✔  /public_html/wc-logs/
WP Version: 4.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.15
PHP Post Max Size: 350 MB
PHP Time Limit: 600
PHP Max Input Vars: 8000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.0
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (22) ###

Advanced Custom Fields: Options Page: by Elliot Condon – 1.2.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.3
Disqus Comment System: by Disqus  – 2.84
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Gravity Forms: by rocketgenius – 1.9.15
Monarch Plugin: by Elegant Themes – 1.2
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
What The File: by Never5 – 1.5.2
WooCommerce Ecommerce tracking for Google and Facebook: by Multidots – 1.0.1
WooCommerce Beta Tester: by Mike Jolley – 1.0.0
WooCommerce Custom Field Product Search: by Alvaro Neto – 1.0.0
WooCommerce Affirm Gateway: by WooThemes – 1.0.0
WooCommerce Amazon Payments Advanced Gateway: by WooThemes – 1.4.6
WooCommerce PayPal Express Gateway: by WooThemes / SkyVerge – 3.5.1
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.2 – 1.10.7 is available
WooCommerce Google Product Feed: by Lee Willis – 5.2.1
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.3.1 – 1.4.2 is available
WooCommerce: by WooThemes – 2.5.0-beta-1
WooThemes Helper: by WooThemes – 1.5.9
WP-Lister Pro for eBay: by Matthias Krok – 2.0.9.15
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #40325 - /shop/
Cart: #1160 - /cart/
Checkout: #1161 - /checkout/
My Account: #1163 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: WooCommerce 101
Version: 0.1.0
Child Theme: ✔
Parent Theme Name: mad
Parent Theme Version: 0.1.0
WooCommerce Support: ✔

### Templates ###

Overrides: madwoo-child-101/cart/cart-totals.php
madwoo-child-101/cart/cart.php
madwoo-child-101/cart/shipping-calculator.php
madwoo-child-101/content-product.php version 1.6.4 is out of date. The core version is 2.5.0
madwoo-child-101/woocommerce/loop/orderby.php
madwoo-child-101/woocommerce/single-product/meta.php
madwoo-child-101/woocommerce/single-product/price.php version 1.6.4 is out of date. The core version is 2.4.9
madwoo-child-101/woocommerce/single-product/product-thumbnails.php
madwoo-child-101/woocommerce/single-product/tabs/additional-information.php
madwoo-child-101/woocommerce/single-product/tabs/description.php
madwoo-child-101/woocommerce/single-product/tabs/tabs.php
madwoo-child-101/woocommerce/single-product.php

**Comment by tlovett1** [comment]
You need to upgrade WP-CLI to the latest version.

**Comment by codingideas** [comment]
how do I do that?
