### ISSUE TITLE
Include "no Wordpress" Content

### ISSUE THREAD

**Issue by marexx** [10up/ElasticPress#4030]
### Describe your question

Wordpress 6.6.2
ElasticPress 5.1.3 

we want to use ElasticPress on our Site. Is it possible to also include content from an API.
we display a lot of "Reviews" as PDF and HTML on our page. They are no WP POSTs and the PDFs are not in the Wordpress library. Is it possible to index them as well with elasticpress, or do we have to index by ourselfs?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @marexx, displaying external entities as search results is not a simple task, as WordPress and ElasticPress will quite often try to call functions and filters like `post_link` on entities that are not real WP_Post. An easier (but not always possible) approach is to create a CPT in WP and redirect users to the external URL.

You can also leverage the External Content feature from [EP Labs](https://github.com/10up/ElasticPressLabs) to consume data from APIs and index it as meta fields in Elasticsearch. More about it [here](https://www.elasticpress.io/blog/2024/03/pew-research-center-external-files-as-a-source-for-your-search/).

**Comment by marexx** [comment]
mmh, i'm not sure if i understand.
can i enter in this "meta fields with externals urls" the api call?

I managed to index a folder with PDFs via a py script. Into a second index. Can I add this index to elastic press, or should i index the PDFs into the same index, which is already used by elasticpress?
