### ISSUE TITLE
BUG: ep_exclude_from_search is not saved on custom post types.

### ISSUE THREAD

**Issue by maartenhunink** [10up/ElasticPress#4034]
### Describe the bug

The `Exclude from search results` checkbox unchecks itself automatically when you save a custom post type. This does work as intended on normal post types, but not on custom ones.

Tested on a fresh install without any other plugins.

### Steps to Reproduce

1. Add a custom post type to your theme/project
2. Go to create/edit a post
3. Check the 'Exclude from search results
4. Click Publish/Save

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/6ef8fd40-7dd5-49c7-8e8d-a89956116580

### WordPress and ElasticPress information

Latest wordpress and eliasticpress

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@maartenhunink can you please check if the value sticks if you add support to `'custom-fields'` to your CPT? Like this, for example:

```php
	register_post_type(
		'movie',
		[
			'labels'       => [
				'name'          => __( 'Movies' ),
				'singular_name' => __( 'Movie' ),
			],
			'public'       => true,
			'has_archive'  => true,
			'taxonomies'   => [ 'category' ],
			'show_in_rest' => true,
			'supports' => [ 'title', 'editor', 'custom-fields' ], <-- This line here
		]
	);
```

**Comment by maartenhunink** [comment]
Ah, that fixes it indeed! Thanks a lot for looking into it so quickly and providing the solution. 

It might be helpful to add this to the documentation somewhere?

Thanks!

**Comment by felipeelia** [comment]
Sure thing, @maartenhunink. After the release I'll add it to our documentation, thanks
