### ISSUE TITLE
Multisite requires manual index when adding new sites

### ISSUE THREAD

**Issue by bswatson** [10up/ElasticPress#405]
Sites can be setup and indexed from the command line, but the expectation is that ElasticPress should automatically pull in content from the new site.

**Comment by tlovett1** [comment]
Yep, tough problem to solve. I think once @ChrisWiegman's dashboard is merged in, this will make sense to address.

**Comment by dkotter** [comment]
The admin dashboard is now merged in, which makes it really easy to index a new site. But that indexing still is user initiated, so I agree it would be nice to figure out a way to automate this. The tricky part of this is sometimes you might not want every new site indexed, so any solution here would need the ability to turn it off. Would love to see a PR here.
