### ISSUE TITLE
keep getting database conection error when running wpcli commands for EP

### ISSUE THREAD

**Issue by beatelite** [10up/ElasticPress#413]
I installed the plugin (master branch) and activated it on an MS install. 

I installed the wpCLI according the instructions

I defined my constant  using my bonsai ES hosting:

 ```
define( 'EP_HOST', 'https://NulledBonsaiUserInfoHere.bonsai.io' );
```

I ran 

```
wp elasticpress index --setup
```

I get back

```
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Database Error</title>
 
</head>
<body>  
        <h1>Error establishing a database connection</h1>
</body>
</html>
```

I'm using wp 4.4 

Any suggestions?

**Comment by allan23** [comment]
@beatelite Are you able to successfully run WP-CLI commands in general? 
(Example: ``wp post list --post_type=post --posts_per_page=5`` )

**Comment by beatelite** [comment]
No, I keep getting the same error. Weird. Suggestions?

**Comment by allan23** [comment]
Sounds like an issue with your WP-CLI install. Might want to try setting that up again and verify that you are running from your WordPress install's root directory.
