### ISSUE TITLE
Checking WP_Query->query instead of WP_Query->query_vars

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#420]
In `ep_elasticpress_enabled`, we are checking `WP_Query->query` instead of `WP_Query->query_vars`. I feel like we should be checking `WP_Query->query_vars`. Thoughts? @ChrisWiegman @allan23

**Comment by ChrisWiegman** [comment]
After poking around a bit I don't see any reason why this was implemented this way. I've opened PR #436 to address. In testing the switch seems to work just fine.

**Comment by dkotter** [comment]
Tested out the PR and worked great. This has been merged so I'm closing this out now. Thanks!
