### ISSUE TITLE
meta_query returns empty with 'sites' => 'all'

### ISSUE THREAD

**Issue by natostanco** [10up/ElasticPress#424]
Passing an array of sites returns posts correctly, but doing a broad search with `sites => all` returns no posts.

**Comment by ChrisWiegman** [comment]
Hi @natostanco,

I've been testing this a bit this afternoon and have not been able to reproduce. Do you have an snippet of the code you can share to show us the query you're trying? Also, can you please confirm the version of both ElasticPress and Elasticsearch you are trying this on?

**Comment by jaisgit** [comment]
I have noticed this as well. At this stage it looks like sync via wp-admin network dashboard doesn't create the global alias in the site indexes.
