### ISSUE TITLE
What is the default search query in Elasticpress

### ISSUE THREAD

**Issue by prashanttct07** [10up/ElasticPress#427]
Hi Team,

I was working for this plugin quite a while, So have a query like what is the default query which gets fired if I do any text search.

Here default search query means whether it is Query_string query, or match query or term query or any other query.

**Comment by dkotter** [comment]
Hey @prashanttct07, thanks for the question.

If I'm understanding the question correctly, if you were to install this plugin on any WordPress and you had Elasticsearch active and working properly, if you were to then go and run a normal search on that site, ElasticPress will then intercept that search query and pass that along to Elasticsearch, bypassing WordPress all together.

This means ElasticPress will take the search query and send that along to the Elasticsearch server via a remote request, sending along some args. Those args should look like this, if you searched for the word "test":

```
{"from":0,"size":10,"sort":[  
   {  
      "_score":{  
         "order":"desc"
      }
   }
],
"query":{  
   "bool":{  
      "should":[  
         {  
            "multi_match":{  
               "query":"test",
               "fields":[  
                  "post_title",
                  "post_excerpt",
                  "post_content"
               ],
               "boost":2,
               "fuzziness":0
            }
         },
         {  
            "multi_match":{  
               "fields":[  
                  "post_title",
                  "post_excerpt",
                  "post_content"
               ],
               "query":"test",
               "fuzziness":2,
               "operator":"or"
            }
         }
      ]
   }
},
"filter":{  
   "and":[  
      {  
         "terms":{  
            "post_type.raw":[  
               "post",
               "page",
               "attachment"
            ]
         }
      }
   ]
}
}
```

These args will perform a search for up to 10 items, sorted by the score, and the query ran will do a multi match on the post_title, post_excerpt and post_content fields. It will also run a multi match query on those same fields but with the fuzziness parameter set. We don't set the type of multi match query, so it goes to the default of best_fields: https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-multi-match-query.html#type-best-fields

Hopefully that answers your question but if not, please let me know. Thanks!
