### ISSUE TITLE
WP-CLI Status Command Failing

### ISSUE THREAD

**Issue by ChrisWiegman** [10up/ElasticPress#433]
wp elasticpress status fails with the following message using Elasticsearch 2.1:

====== Status ======
{
  "error" : {
    "root_cause" : [ {
      "type" : "illegal_argument_exception",
      "reason" : "No feature for name [_status]"
    } ],
    "type" : "illegal_argument_exception",
    "reason" : "No feature for name [_status]"
  },
  "status" : 400
}

====== End Status ======

**Comment by dkotter** [comment]
Checked with Elasticsearch v1.7.2 and did not get this error. Plan on updating Elasticsearch soon and will re-test at that point.

**Comment by dkotter** [comment]
Just upgraded to Elasticsearch v2.1.1 and now get the exact same error.

**Comment by ChrisWiegman** [comment]
Ah ha! That's what I figured. I'll get a PR in for this tomorrow.

**Comment by jonathan-dejong** [comment]
Any news on this? Just updated to latest ElasticSearch and Elasticpress. 
It seems to work on the site but in the terminal it throws this error.

**Comment by dkotter** [comment]
Just made a PR to fix this issue. Once that's reviewed and merged in, should be good here.
