### ISSUE TITLE
ElasticSearch Protected with Shield

### ISSUE THREAD

**Issue by tegonsalves** [10up/ElasticPress#441]
I was wondering if it is possible to connect EP to an ElasticSearch Server that has been protected with the Shield plugin?

**Comment by dkotter** [comment]
@tegonsalves So I'm not familiar with the Shield plugin. Anyway you can link me to it so I can take a look? Thanks!

**Comment by tegonsalves** [comment]
It adds username/password authentication to ElasticSearch -
https://www.elastic.co/products/shield

On 10 February 2016 at 23:29, Darin Kotter <notifications@github.com> wrote:

> @tegonsalves <https://github.com/tegonsalves> So I'm not familiar with
> the Shield plugin. Anyway you can link me to it so I can take a look?
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/10up/ElasticPress/issues/441#issuecomment-182699179>.
>



-- 
Terrence Gonsalves

**Comment by rveitch** [comment]
Subscribed, I have the same question.

**Comment by rveitch** [comment]
I decided to tackle this one myself this weekend.  Pull request  #456 adds Shield login username:password basic authentication headers to requests if `ES_SHIELD` is defined in your wp-config.php file.

**Value Format:** `username:password` (colon separated)
**Example:** `define( 'ES_SHIELD', 'es_admin:password' );`

**Comment by dkotter** [comment]
The PR has been merged in, targeted for a 1.9 release.
