### ISSUE TITLE
Multisite indexing (custom taxonomies?)

### ISSUE THREAD

**Issue by phpanos** [10up/ElasticPress#444]
I'm trying to use this plugin on a multisite install but when trying to index the site I get the following error:

```
wp elasticpress index --setup --network-wide
Warning: ElasticPress is already deactivated.
Adding mapping for site 1...
Success: Mapping sent
Adding mapping for site 2...
Success: Mapping sent
Adding mapping for site 3...
Success: Mapping sent
Adding mapping for site 4...
Success: Mapping sent
Indexing posts network-wide...
Processed 8/8 entries. . .
Number of posts indexed on site 1: 8
Processed 350/867 entries. . .
Processed 700/867 entries. . .
Processed 867/867 entries. . .
Number of posts indexed on site 2: 867
Processed 350/4170 entries. . .
PHP Fatal error:  Call to a member function filter() on boolean in /var/www/projects/site.com/wp-includes/taxonomy.php on line 805
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:723
PHP   6. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:320
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:313
PHP   8. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:294}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:294
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:294
PHP  10. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:52}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  11. ElasticPress_CLI_Command->index() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  12. ElasticPress_CLI_Command->_index_helper() /var/www/projects/site.com/wp-content/plugins/ElasticPress/bin/wp-cli.php:244
PHP  13. WP_Query->__construct() /var/www/projects/site.com/wp-content/plugins/ElasticPress/bin/wp-cli.php:339
PHP  14. WP_Query->query() /var/www/projects/site.com/wp-includes/query.php:4129
PHP  15. WP_Query->get_posts() /var/www/projects/site.com/wp-includes/query.php:4018
PHP  16. _prime_post_caches() /var/www/projects/site.com/wp-includes/query.php:3621
PHP  17. update_post_caches() /var/www/projects/site.com/wp-includes/post.php:5889
PHP  18. update_object_term_cache() /var/www/projects/site.com/wp-includes/post.php:5567
PHP  19. wp_get_object_terms() /var/www/projects/site.com/wp-includes/taxonomy.php:3615
PHP  20. array_map() /var/www/projects/site.com/wp-includes/taxonomy.php:2417
PHP  21. get_term() /var/www/projects/site.com/wp-includes/taxonomy.php:2417
```

This happens on WordPress version 4.4. I then tried on WP version 4.3.3 and it worked.

The site has custom taxonomies.

Is this a known issue? Let me know if I can provide more information.

Thanks!

**Comment by dkotter** [comment]
@phpanos So I just tried to reproduce this on a multisite instance that also has custom taxonomies and didn't get any error.

Looking at your error message, it's coming from a core WordPress file, so seems like potentially a bug in WordPress itself. But any other information you can provide that we could use to debug further would be great. What version of ElasticPress are you running? Any customizations you're doing, through filters or otherwise, to how ElasticPress will index things? Anything special about the custom taxonomies that your using? Thanks!

**Comment by phpanos** [comment]
@dkotter Thank you for your fast reply! Did you use the latest version of wordpress when testing? 

I don't have too much insight in this site since I didn't build it, but the only special thing about the custom taxonomies seem to be that you can select a language for them since WPML is installed. But I did deactivate all of the plugins and the same error appeared. 

I am using ElasticSearch version 2.2.0. I commented out the only two filters I've added to ElasticPress with the same result.

I too think it could be wordpress itself or maybe a combination of wp and a specific plugin.

I don't think I have any more debugging info for now. I will continue development on this older wp version and will try to test further once I'm done with my task (in a few weeks probably).

**Comment by dkotter** [comment]
All right, thanks for the extra info. Do you know what version of the ElasticPress plugin you're running? Would like to see if that's a factor here or not. Otherwise just keep us informed with any additional information you have and we can keep looking into this.

**Comment by phpanos** [comment]
Of course! I'm using version 1.8. Thanks for looking into this!

**Comment by dkotter** [comment]
Still have not been able to reproduce this, testing on both 1.8 and the develop version of ElasticPress (soon to be 1.9 version). So at this point I'll just wait for more information, and hopefully that will lead us closer to a solution.

**Comment by tlovett1** [comment]
I would try updating WP CLI.
