### ISSUE TITLE
GUI reindex fails when APCu

### ISSUE THREAD

**Issue by jaisgit** [10up/ElasticPress#446]
FYI
The GUI reindex fails when using APCu Object Cache Backend plugin.

`Feb 11 11:49:16 host httpd: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Property APCu_Object_Cache::$cache does not exist' in /var/www/wp-content/plugins/elasticpress/classes/class-ep-index-worker.php:173
Stack trace:
#0 /var/www/wp-content/plugins/elasticpress/classes/class-ep-index-worker.php(173): ReflectionProperty->__construct(Object(APCu_Object_Cache), 'cache')
#1 /var/www/wp-content/plugins/elasticpress/classes/class-ep-index-worker.php(84): EP_Index_Worker->_index_helper()
#2 /var/www/wp-content/plugins/elasticpress/classes/class-ep-index-gui.php(135): EP_Index_Worker->index()
#3 /var/www/wp-content/plugins/elasticpress/classes/class-ep-index-gui.php(217): EP_Index_GUI->_run_index()
#4 [internal function]: EP_Index_GUI->action_wp_ajax_ep_launch_index('')
#5 /var/www/wp-includes/plugin.php(496): call_user_func_array(Array, Array)
#6 /var/www/wp-admin/admin-ajax.php(86): do_action('wp_ajax_ep_laun...')
 in /var/www/wp-content/plugins/elasticpress/classes/class-ep-index-worker.php on line 173`

**Comment by dkotter** [comment]
Hi @jaisgit, thanks for the error report. I don't have APCu setup anywhere to test, but just created a PR that I hope fixes this: #448. If you could, can you check that PR out and see if it fixes your error? Also, if you could check both on the PR and on the develop branch to see if you get the same error when using the cli command, as it does the same thing with the `ReflectionProperty`, so would like to verify if this fixes that as well, if it actually does throw an error in the first place.

Thanks!

**Comment by jaisgit** [comment]
That does fix the error with ACPu. I'm not sure if there was any errors via cli but a `wp elasticpress index --network-wide `  doesn't seem index all sites only the first one.

**Comment by dkotter** [comment]
All right, just pushed the same fix to the cli command. Can you try running that one more time and see if works better now? Thanks!

**Comment by jaisgit** [comment]
I can confirm that `$ wp elasticpress index --network-wide` now says it indexes all sites but I don't see any logs in elasticsearch showing the activity where I do with the admin GUI index method.

**Comment by dkotter** [comment]
All right, merged in #448 which fixes the original issue here.

When you say you don't see the logs, do you mean you're not seeing any logs in the admin when you use the cli command? If so, I think that's expected, though maybe something we can fix. I would recommend opening another issue if you think it's something we should look into.

Thanks!
