### ISSUE TITLE
Follow up on possible issues found during #446

### ISSUE THREAD

**Issue by jaisgit** [10up/ElasticPress#449]
During the testing of #446 and in reference to my comment:

> I can confirm that $ wp elasticpress index --network-wide now says it indexes all sites but I don't see any logs in elasticsearch showing the activity where I do with the admin GUI index method.

I wanted to clarify that I was referring to the Elasticsearch instance logs and not WP admin GUI progress. 

Should running `$ wp elasticpress index --network-wide` without the `--setup` command work the same as clicking on the index button in the WP GUI?
If so, I'm seeing the Elasticsearch activity in logs with the GUI button but I don't when running the cli command.

Cheers.

**Comment by tlovett1** [comment]
It should work almost the same. Please test again with 2.1 in the develop branch. Feel free to re open.
