### ISSUE TITLE
`post__in` and `fields` support?

### ISSUE THREAD

**Issue by mgibbs189** [10up/ElasticPress#451]
Hello,

Does EP currently support (or plan to support) the `post__in` and `fields` parameters?

E.g. `'fields' => 'ids'` to return an array of post IDs, and `'post_in' => array( 1, 2, 3 )` to only search through specific posts.

Thanks

**Comment by tlovett1** [comment]
`post__in` is supported. `fields => 'ids'` support is not possible until this [trac ticket](https://core.trac.wordpress.org/ticket/35476) goes through.

**Comment by mgibbs189** [comment]
@tlovett1 Thanks, just submitted PR https://github.com/10up/ElasticPress/pull/452 to add `post__in` to the documentation.

Keep up the good work!
