### ISSUE TITLE
Ability to search using exact phrase/keyword 

### ISSUE THREAD

**Issue by chauhankrishan** [10up/ElasticPress#454]
Hi Team,

I have configured elasticpress and elasticsearch on my local machine. My requirement is that i would like to search multiword terms as exacht phrase/keyword search, but elasticpress is not giving me back instead it return multiple results in response to search result. 

would it be possible to search using elasticpress wordpress plugin and if yes, then how?

My multi word search terms would be eg: "upwards-only rent review"; "rights to light"; "right to manage" and it's should return me exact match.
This means i have to put the hack in elasticpress if multiword terms in quote or [] bracket in that case search exact phrase otherwise run normal.

Could you please help me here, as i am new to wordpress.  How i can achieve above. Your help will be much appreciated.

**Comment by allan23** [comment]
Possibly related: #358

**Comment by tuanmh** [comment]
We will need to add another query type: `phrase` with possiblly higher `boost` than 2 two current queries. This will make sure exact match posts will always sit above other posts. 

Current:

```php
$query = array(
			'bool' => array(
				'should' => array(
					array(
						'multi_match' => array(
							'query' => '',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_boost', 2, $search_fields, $args ),
							'fuzziness' => 0,
						)
					),
					array(
						'multi_match' => array(
							'fields' => $search_fields,
							'query' => '',
							'fuzziness' => apply_filters( 'ep_fuzziness_arg', 2, $search_fields, $args ),
							'operator' => 'or',
						),
					)
				),
			),
		);
```

Suggestion:
```php
$query = array(
			'bool' => array(
				'should' => array(
					array(
						'multi_match' => array(
							'query' => '',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_boost', 2, $search_fields, $args ),
							'fuzziness' => 0,
						)
					),
					array(
						'multi_match' => array(
							'fields' => $search_fields,
							'query' => '',
							'fuzziness' => apply_filters( 'ep_fuzziness_arg', 2, $search_fields, $args ),
							'operator' => 'or',
						),
					),
					array(
						'multi_match' => array(
							'query' => '',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_phrase_boost', 4, $search_fields, $args ),
							'fuzziness' => apply_filters( 'ep_match_phrase_fuzziness', 0, $search_fields, $args ),
							'type' => 'phrase'
						)
					)

				),
			),
		);
```

**Comment by tlovett1** [comment]
The match phrase query is now used by default.
