### ISSUE TITLE
Not returning results from all sites

### ISSUE THREAD

**Issue by benbakelaar** [10up/ElasticPress#457]
Hello all, I am new to ElasticSearch, but not to Wordpress.

I followed all the directions here:
https://www.saotn.org/install-elasticsearch-on-centos-6-7/

I checked out everything here:
https://wordpress.org/plugins/elasticpress/installation/

I read the README.md file in full.

I ran the setup for network:
wp elasticpress index --setup --network-wide

I checked over these Google search results:
https://sammaye.wordpress.com/2013/12/19/things-i-have-learnt-in-the-first-5-minutes-of-using-elastic-search/
http://www.slideshare.net/tlovett1/wordpress-searchelasticsearch
https://theshipyard.se/elasticsearch-elasticpress-wordpress/

I grepped for the WP_Query function:
[root@linuxweb2 htdocs]# grep -r 'new WP_Query( array' . 

And updated files in my Divi theme:
./wp-content/themes/Divi/et-pagebuilder/et-pagebuilder.php:     $query = new WP_Query( array( 

But no matter what, I only get search results from 1 site.
http://research.scilsnet.rutgers.edu/?s=conference

This is a WPMU instance. The root URL is site ID=1. From what I have read, it should return results from all sites? I must be missing something. But also, the documentation lacks a connection to the front end. The documentation reviews in great detail how you can write all kinds of queries using PHP code. But I would think the primary use case would be the built-in search form/function in Wordpress widgets being used to return search results for all sites. Somehow, this isn't working "out of the box" unless I missed a step somewhere.

**Comment by tlovett1** [comment]
By default it won't return content from all sites. You need to pass `'sites' => 'all'` to the WP_Query object
