### ISSUE TITLE
Configuring EP_Host from the dashboard

### ISSUE THREAD

**Issue by JoseTomasTocino** [10up/ElasticPress#458]
It would be great it the URL for the elasticsearch server could be configured from within the dashboard instead of having to modify `wp-config.php`.

**Comment by dkotter** [comment]
This is now possible using the Admin GUI that is merged into the develop branch, and will be the main feature of the 1.9 release. I would recommend checking that out if you want to see how that works. Any feedback on that process is more than welcome. Thanks!
<img width="548" alt="screen shot 2016-03-03 at 3 26 15 pm" src="https://cloud.githubusercontent.com/assets/916738/13511860/638ae6f4-e154-11e5-9e13-5bb0208772ab.png">

**Comment by JoseTomasTocino** [comment]
That's great! :D When is 1.9 expected to be released?

**Comment by dkotter** [comment]
Soon! The plan was this week but since it's already Friday, probably early next week.

**Comment by theDanielJLewis** [comment]
We're now far past 1.9, but this dashboard feature seems to be missing.

**Comment by tlovett1** [comment]
This is in the dashboard.

**Comment by theDanielJLewis** [comment]
Yes, it's in the dashboard. I see it, but it's not editable on a single-site WordPress installation. It says that it is defined in wp-config.php, which is wasn't. But I did manually add it to wp-config.php and it displayed the proper value in the dashboard.

**Comment by tlovett1** [comment]
If the EP_HOST constant is defined anywhere, it will not be editable in the dashboard. If it doesn't let you edit it, that constant must be defined somewhere.
