### ISSUE TITLE
Multi-Site Domain Mapping Indexing

### ISSUE THREAD

**Issue by Promaethius** [10up/ElasticPress#461]
I'm using the WPMUDEV domain mapping addon. Indexing works find for my multisite but the indices are as subdomains. When I initiate a search from the site as a subdomain, the search queries as normal. When initiated from the mapped domain, it cannot find the index and returns no results. Sometimes, unpopulated indexes pop up for my mapped domains. Any help would be appreciated!

**Comment by Promaethius** [comment]
ElasticPress creates indecies by either looking at the populated site table or by looking at the URL the site is working from. This is why I would have a index of both the subdomain and the mapped version. While I haven't looked at the code itself to find a solution, as of 1.9 and the inclusion of the GUI, activating the plugin on a per site basis and indexing each individually creates and populates the correct index.

**Comment by mikelking** [comment]
Unfortunately, it does not work with a origin-push configured CDN.
