### ISSUE TITLE
Support tax_query operator "NOT IN" o "IN" exclude include tax on WP_query

### ISSUE THREAD

**Issue by miguelalvagarcia** [10up/ElasticPress#463]
Hi, I need to make a WP_Query excluding or including taxonomies. Currently I do not see ElasticPress has support in the field of "operator" for tax_query. And the search have to do need to include or exclude taxonomies, how I can exclude taxonomies with ElasticPress with WP_Query?

Now: 
<pre>
			$search_query['tax_query'] = array(
				'relation' => 'AND',
				array(
					'taxonomy' => 'product_cat',
					'field' => 'term_id',
					'terms' => $descendants,
					'operator' => 'NOT IN' //or 'IN'
				)
			);
			$search = new WP_Query($search_query);
</pre>

**Comment by mustafauysal** [comment]
Hi @miguelalvagarcia ,

I did similar thing before.  You can use  `ep_formatted_args` filter.

For example;
```
$args['filter']['and'][]['bool']['must_not'][][]['terms']['terms.post_tag.slug'] = array('slug1','slug2'...)
```

**Comment by miguelalvagarcia** [comment]
hi @mustafauysal 

thank you very much works perfectly!
