### ISSUE TITLE
How to use the autosuggest?

### ISSUE THREAD

**Issue by ColonelOwl** [10up/ElasticPress#465]
I found in the index implementation autosuggest, but I do not understand how to use. Help me please

**Comment by tlovett1** [comment]
Someone should create a module :)

**Comment by AaronHolbrook** [comment]
This should be a good starting point: https://github.com/10up/ElasticPress-Autosuggest

**Comment by nqzhang** [comment]
I follow [https://github.com/10up/ElasticPress-Autosuggest](url) and what should i fill in the Endpoint Url in the plugin settings
![image](https://user-images.githubusercontent.com/12559853/35606706-7f2e9b5e-068b-11e8-9926-81849ef227ae.png)

**Comment by robert1112** [comment]
Hi it's a bit long ago but did you find answers for endpoint url? Thank you.
