### ISSUE TITLE
ElasticPress improperly indexes oembed content

### ISSUE THREAD

**Issue by ChrisWiegman** [10up/ElasticPress#467]
Rather than just indexing the URL, as is stored in the WordPress posts table for post content, the application of the "the_content" filter at https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L503 causes WordPress to index the oembed output, not just the URL. This has the result of breaking things like TinyMCE when it is used to retrieve backend content.

**Comment by AaronHolbrook** [comment]
Think this is somewhat related to #293

**Comment by tlovett1** [comment]
@Ritesh-patel anything worth looking at here?

**Comment by Ritesh-patel** [comment]
@tlovett1 ElasticPress still indexes oembed content due to `the_content` filter. I wonder if use of `ep_post_sync_args` or  `ep_post_sync_args_post_prepare_meta` filters can do the work.

**Comment by tlovett1** [comment]
Not sure why indexed EP content would be shown in the editor. Closing for now.
