### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by BenChirlin** [10up/ElasticPress#471]
Hello. Loving the plugin but I was wondering if there was an easy way to get some benchmarking out. Specifically I'm interested in how much this plugin helps improve complex `WP_Query` performance, such as those with multiple taxonomy and/or meta arguments within them.

I've been trying to get some rough benchmarks just using debug bar console with `microtime`, a `WP_Query`, and `ep_integrate = true`. However the performance time for `ep_integrate = true` and `ep_integrate = false` are so similar I'm not even convinced Elastic is being used.

Is there an easy way to test the efficiency of the plugin as well as when Elastic queries are actually being processed? I did instal the Elasticpress debug bar query plugin but was hoping to test without having to build a page for each test. Thanks.

**Comment by AaronHolbrook** [comment]
Hey @BenChirlin that's great, glad you're loving the plugin!

I think without load on a server, and depending on what version of PHP you're using (7 is very quick), you may not see much difference.

However, the place this really starts to shine is on massive installs that have a lot of traffic where sending numerous uncached db queries would be a big hit on the db server. Instead they get sent to the elasticsearch server, which is much more performant.

I think if you want a true comparison you should compare mysql to elasticsearch itself - that isolates out any inconsistency from WordPress and PHP.

Additionally, if you're not already, you should do it in order of magnitudes of 1000s of queries (so you can see the difference).

Perhaps the siege benchmarking utility could be of some use to you as well: https://www.joedog.org/siege-home/.

Keep us posted with what you find, I'd love to see what you find out!

**Comment by BenChirlin** [comment]
Thanks. I'll take a look.
