### ISSUE TITLE
problem with memory

### ISSUE THREAD

**Issue by severfire** [10up/ElasticPress#473]
`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /home/username/public_html/wp-content/plugins/elasticpress/classes/class-ep-api.php on line 167`

seems like my db is too big to handle... or should it be optimized other way?

**Comment by tlovett1** [comment]
Which version of EP are you using?

**Comment by finalwebsites** [comment]
I get the same error if I use more than one word for the search. I'm using the latest version of EP (1.9) + the woocommerce extension (1.1.4)

**Comment by tlovett1** [comment]
Might need to up the memory for the server.

**Comment by rcespa** [comment]
I am facing the same problem while building the index from the GUI. I raised the memory_limit up to 4096M and then I tried the command line option with no success:

`[root@vmiXXXXX interline]# wp --allow-root elasticpress index
Warning: ElasticPress is already deactivated.
Indexing posts...
Segmentation fault (core dumped)`

Running Nginx 1.10, php-fpm 5.6, latest git versions for both EP and EP WooCommerce on VPS with 6 dedicated cores, 40GB RAM, 800GB SSD storage, CentOS 6.8, php-fpm and php 5.6 grabbed from Remi Collect repository.

2.443 products and product variations, 1.491 drafts and 951 published.
(I'm using woocommerce to sell travel packages. The drafts are "packages" - product variations - that reached their departure date and are hidden from the frontend).

I tried disabling APC (older version of PHP got some problems with APC enabled) but that was not the solution.

Any help is appreciated!

**Comment by rcespa** [comment]
I don't know if my segfault problem is related to memory, but I confirm I have the problem with PHP 5.6 & 5.5. 
Everything is ok with CentOS 6.8 stock PHP packages.

**Comment by rcespa** [comment]
I'm testing the 2.1 and this is what happens:

 1. if I try to run the index from the Web UI, I only get a non specific
    "An error occured while syncing"
 2. I can run the index command via wp-cli (with ElasticPress
    WooCommerce disabled)
 3. I can run the index command via wp-cli (with ElasticPress
    WooCommerce enabled)

As far as I can understand, ElasticPress WooCommerce is no longer 
needed: I can see the option to index WooCommerce in the settings page.

Unfortunately as soon as I activate ElasticPress, FacetWP stops working 
but this is not new to me: I already contacted FacetWP developer in the 
past about this conflict between EP and FacetWP.

Regards,
Roberto

**Comment by tlovett1** [comment]
@rcespa can you tell me what sort of error message happens in the AJAX request for 1?

**Comment by rcespa** [comment]
@tlovett1 Hi!
Sorry for the delay, I abandoned ElasticPress for a while and now I'm back on it.
This morning I started to test it again with a fresh download from github.
I enabled only the EP plugin and completely removed the elasticpress-woocommerce plugin.

First of all, I needed to set max stack size to unlimited for user nginx (the same user is the owner of nginx and php-fpm processes). If not, I get a segfault almost immediately.

After setting the stack size to unlimited (via /etc/security/limits.conf) I tried to run the first index via command line and via web UI.
Via cli the index starts but I know it is running only monitoring the system by htop; memory usage starts to ramp up and after some minutes the process get killed.
Again, I'm testing it on a VPS with 40GB of RAM and SSD vdisk.

I tried the nobulk and posts_per_page (with values 100 and, later, 20) options with no success.
The site is part of a WP MultiSite installation and php-fpm memory limit (when running via webUI) is set at 2048M.
The error logged is: 

```
PHP message: PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 130968 bytes) in /var/www/html/Sites/example.com/wp-includes/post.php on line 1983" while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: www.example.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "www.example.com", referrer: "http://www.example.com/wp-admin/admin.php?page=elasticpress"
```

I tried to strace the process (when launched via cli) but the only output I can see is an infinite sequence of:

`brk(0x.....) = 0x.....`
where the hex number is constantly raising.
As far as I can understand, the process is allocating more and more memory.

I also tried to monitor the process: I started the import (again using wp-cli):
```
[root@example.com example.com]# date; wp elasticpress index  --url="http://www.example.com"; date
ven  5 ago 2016, 14.27.38, CEST
Indexing posts...
Killed
ven  5 ago 2016, 15.14.30, CEST
```
As you can see the process ran for about 45 minutes before being killed by the kernel for OOM.
While it was "indexing", I ran on a different shell the following command:

`while true; do date; wp elasticpress stats  --url="http://www.example.com" 2>&1 | grep Documents; sleep 10; done`

but the output was always the same:
```
ven  5 ago 2016, 15.10.38, CEST
Documents:  0
```

No document got indexed during 45 minutes of index creation.

**Comment by rcespa** [comment]
Everytime the process gets killed because of OOM, the webUI is blocked with message "WP CLI sync is occuring. Refresh the page to see if it's finished"

Deactivating and reactivating the plugin fixes this annoying problem.

I wanted to do some more tests:

1. with all EP modules deactivated, I indexed only the "page" post_type; it worked!

1. with all EP modules deactivated, I indexed only the "post" post_type; it worked!

1. with all EP modules deactivated, I indexed only the "product" post_type; it worked!

1. with all EP modules deactivated, I indexed only the "product_variation" post_type; BOOM!


I enabled the woocommerce module and ran the same tests again:

1. with all EP modules deactivated, I indexed only the "page" post_type; it worked!

1. with all EP modules deactivated, I indexed only the "post" post_type; it worked!

1. with all EP modules deactivated, I indexed only the "product" post_type; it worked!

1. with all EP modules deactivated, I indexed only the "product_variation" post_type; BOOM!

Definitely we have a problem with product variations.

**Comment by rcespa** [comment]
I looked at the code, specially to /bin/wp-cli.php and I made some tests on _index_helper method.
Some dirt debug (print_r, echo, etc.) let me understand that the_post() is not iterating over the posts returned by the query.

The query is correctly executed (and I can execute it straight in mysql with no problems), the $query object contains everything but the loop stops at its first iteration. Using nobulk option leads to same result.
The only working case is with posts-per-page=1, but running more that 12K queries against mysql would be silly!

In my very specific situation, the first post is an attachment and the second one is a product variation.

Curiously, changing the order clause from DESC to ASC seems to solve the problem.

**Comment by tlovett1** [comment]
How many posts need to be indexed?

**Comment by rcespa** [comment]
about 30.000 posts (products and product variations)

**Comment by photoboothowners** [comment]
We have a large shop that has thousands of variations. Unfortunately after much excitement we've found that EP is making our site unusable due to excessive memory usages. We allowed up to 2GB per requests on our VPS and still experience memory overages. 

Has there been any progress on this issue with extensive memory usage with variations? This plugin seems so promising.

**Comment by tlovett1** [comment]
@photoboothowners if you have a site where we could see this in action, please free to shoot me an email.

**Comment by futurmat** [comment]
I have the very same problem as @rcespa had. As soon as I include "product_variation" as content-type the indexing fails instantly. 
I changed DESC to ASC in /bin/wp-cli.php as proposed above which allowed me to index 6300 of 18000 items. However, I'm not able to index the remaining elements.

**Comment by tlovett1** [comment]
What error message are you getting?

**Comment by futurmat** [comment]
Sorry, I'm new to using elasticpress. I don't get any error on the command line:
```
wp elasticpress index --setup --post-type=page,product,product_variation
Success: Index deleted
Success: Mapping sent
Indexing posts...
Processed 350/18031 entries. . .
Adding mapping...
Deleting index...
```

**Comment by futurmat** [comment]
I think this problem is related to #714. As soon as I comment out `$wp_actions = array();` indexing seems to work fine (so far).
