### ISSUE TITLE
Searching/handling WPML translations

### ISSUE THREAD

**Issue by petermartin** [10up/ElasticPress#474]
How does ElasticPress handle translated content? I'm digging through my indexes now, seems like it's not being indexed?

**Comment by tlovett1** [comment]
Depends how the plugin saves that data. Can you remind me where/how WPML saves translated content?

**Comment by petermartin** [comment]
All of the posts are in the posts table, but there is a separate "icl_translations" table where they're all matched up to languages and linked to the original. Seems like the issue is probably a conflict with the way that WPML modifies WP_Query?
