### ISSUE TITLE
Indexing Isuess with WPML

### ISSUE THREAD

**Issue by tegonsalves** [10up/ElasticPress#477]
I have upgraded to EP 1.9 and have WPML active and I noticed that when I index the site through the admin that it will only index the content of the language that I am currently on. So in my case English content if I'm on the English side and French content if I'm on the French side. When doing this through the command line it will only index English content.

**Comment by petermartin** [comment]
Good catch. I'm seeing this too - I thought the alternate languages weren't being indexed at all, but you're correct that it will index whatever the active language is.

**Comment by paulhuisman** [comment]
Is there a fix for this? Or do i have to downgrade?

**Comment by tlovett1** [comment]
@allan23 can you look into this?

**Comment by tlovett1** [comment]
Not compatible with WPML (yet).

**Comment by MarcusFuto** [comment]
Does this mean that if I use wpml as a translation tool, I can not (yet) use elasticsearch?

**Comment by tegonsalves** [comment]
@MarcusFuto 
 
See this [thread](https://wordpress.org/support/topic/wpml-and-custom-post-types/) for a suggestion on implementing ElasticPress with WPML

**Comment by philperusse** [comment]
For anybody else landing here with this problem, WPML now adds a post_lang attribute the posts' mappings. (I'm using 3.9.4)

It also adds a post_filter argument to the request itself so it considers this post_lang in ElasticPress queries.

One problem remains : the indexing is still for a unique language as described in this issue.

To resolve this, add a filter to suppress WPML's filter on the indexing 

`
add_filter('ep_index_posts_args', function($args) {
    return array_merge($args, [
        'suppress_filters' => true,
    ]);
});
`
