### ISSUE TITLE
Query log only possible with WP_DEBUG

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#478]
I think in 1.9 we only add to the query log when `WP_DEBUG` is on. This makes it extremely difficult to debug production sites. I realize it's a performance fix, but we need a way around this ASAP.

**Comment by lukaspawlik** [comment]
@tlovett1 I propose adding additional option in GUI "enable debug mode" which would define if we should log queries (only for logged users) even with `WP_DEBUG` disabled. I estimate this for ~2 hrs.

**Comment by tlovett1** [comment]
I'd rather just have a filter rather than an option that 95% of users won't use.
