### ISSUE TITLE
AWS Elasticsearch

### ISSUE THREAD

**Issue by gonbasaldua** [10up/ElasticPress#486]
Hi, we are going to use AWS Elasticsearch Service (https://aws.amazon.com/es/elasticsearch-service/).

- Will this plugin work for us?
- Is it prepared to work with AWS Authentication?

Thanks!

**Comment by lkbr** [comment]
I use it and haven't ran into any issues yet. For authentication, we didn't change anything on the WordPress end and just whitelist our server IP using the basic "Allow access to the domain from specific IP(s)" template.

The only thing I'm worried about is that they use Elasticsearch 1.5.2. I'm wondering when thats going to bite me.

**Comment by tlovett1** [comment]
I don't see why that wouldn't work. Although ES 1.5.2 is a bit scary.

**Comment by pmahmoudzadeh** [comment]
Hi, we are going to use AWS Elasticsearch Service (https://aws.amazon.com/es/elasticsearch-service/).

Will this plugin work for us?
Is it prepared to work with AWS Authentication?

I have the same question. Can you please answer the above questions. Thanks!
