### ISSUE TITLE
Question: Windows server.. will it work?

### ISSUE THREAD

**Issue by jonathan-dejong** [10up/ElasticPress#488]
Hi!

We have a client with a Windows server (not our idea stop yelling at me!). 
While I know elasticsearch will work on it.. will elasticpress? 

Just want to make sure before pitching the switch to elasticsearch/press :) 
They have ALOT of content and complex queries so this setup is pretty perfect for them.. 

Thanks!

**Comment by mustafauysal** [comment]
Hi,

ElasticPress interacting with Elasticsearch by [HTTP API](https://codex.wordpress.org/HTTP_API). So It wouldn't be a problem.

**Comment by jonathan-dejong** [comment]
Hi Mustafa,

Thanks! That's what I figured but not being a server-kinda-guy I felt compelled to make sure.
