### ISSUE TITLE
Add support for WP REST API

### ISSUE THREAD

**Issue by jakejackson1** [10up/ElasticPress#491]
It would be great if ElasticPress support could be also applied to doing searches via the WP REST API.

**Comment by tlovett1** [comment]
Hmmm, the WP REST API uses WP_Query so if you are searching via the REST API, ElasticPress should integrate.

**Comment by jakejackson1** [comment]
That's what I thought too, but when I search my custom post type via the REST API and compare the results to the native WP search while using the `post_type` GET attribute (so it also only searches the custom post type) there's a vast difference in the results. I disabled all unnessisary plugins and double checked there was no plugin conflict but the problem persisted.

**Comment by mustafauysal** [comment]
Hi @jakejackson1 ,

Did you check custom posts exist in your index? (if not `ep_indexable_post_types` filter can help)
Can you share example query string?

We are using ElasticPress with WP REST API for a long while and we don't have that problem.

**Comment by jakejackson1** [comment]
I just ensured that particular custom post type is included in the index. 

I also used xdebug to sniff out what's different in the query variable array between the standard and REST API searches. 

Here's the dump of the standard search:

```
Array
(
    [s] => shortcode
    [post_type] => v4_docs
    [error] => 
    [m] => 
    [p] => 0
    [post_parent] => 
    [subpost] => 
    [subpost_id] => 
    [attachment] => 
    [attachment_id] => 0
    [name] => 
    [static] => 
    [pagename] => 
    [page_id] => 0
    [second] => 
    [minute] => 
    [hour] => 
    [day] => 0
    [monthnum] => 0
    [year] => 0
    [w] => 0
    [category_name] => 
    [tag] => 
    [cat] => 
    [tag_id] => 
    [author] => 
    [author_name] => 
    [feed] => 
    [tb] => 
    [paged] => 0
    [meta_key] => 
    [meta_value] => 
    [preview] => 
    [sentence] => 
    [title] => 
    [fields] => 
    [menu_order] => 
    [embed] => 
    [category__in] => Array
        (
        )

    [category__not_in] => Array
        (
        )

    [category__and] => Array
        (
        )

    [post__in] => Array
        (
        )

    [post__not_in] => Array
        (
            [0] => 7152
            [1] => 5642
        )

    [post_name__in] => Array
        (
        )

    [tag__in] => Array
        (
        )

    [tag__not_in] => Array
        (
        )

    [tag__and] => Array
        (
        )

    [tag_slug__in] => Array
        (
        )

    [tag_slug__and] => Array
        (
        )

    [post_parent__in] => Array
        (
        )

    [post_parent__not_in] => Array
        (
        )

    [author__in] => Array
        (
        )

    [author__not_in] => Array
        (
        )

    [cache_results] => 
    [ignore_sticky_posts] => 
    [suppress_filters] => 
    [update_post_term_cache] => 1
    [update_post_meta_cache] => 1
    [posts_per_page] => 10
    [nopaging] => 
    [comments_per_page] => 50
    [no_found_rows] => 
    [search_terms_count] => 1
    [search_terms] => Array
        (
            [0] => shortcode
        )

    [search_orderby_title] => Array
        (
            [0] => wp_posts.post_title LIKE '%shortcode%'
        )

    [order] => DESC
)
```

And here's the same dump when doing the REST API search:

```
Array
(
    [s] => shortcode
    [paged] => 1
    [order] => DESC
    [orderby] => date
    [post_type] => v4_docs
    [author__in] => Array
        (
        )

    [author__not_in] => Array
        (
        )

    [post__in] => Array
        (
        )

    [post__not_in] => Array
        (
            [0] => 7152
            [1] => 5642
        )

    [posts_per_page] => 10
    [date_query] => Array
        (
        )

    [ignore_sticky_posts] => 1
    [error] => 
    [m] => 
    [p] => 0
    [post_parent] => 
    [subpost] => 
    [subpost_id] => 
    [attachment] => 
    [attachment_id] => 0
    [name] => 
    [static] => 
    [pagename] => 
    [page_id] => 0
    [second] => 
    [minute] => 
    [hour] => 
    [day] => 0
    [monthnum] => 0
    [year] => 0
    [w] => 0
    [category_name] => 
    [tag] => 
    [cat] => 
    [tag_id] => 
    [author] => 
    [author_name] => 
    [feed] => 
    [tb] => 
    [meta_key] => 
    [meta_value] => 
    [preview] => 
    [sentence] => 
    [title] => 
    [fields] => 
    [menu_order] => 
    [embed] => 
    [category__in] => Array
        (
        )

    [category__not_in] => Array
        (
        )

    [category__and] => Array
        (
        )

    [post_name__in] => Array
        (
        )

    [tag__in] => Array
        (
        )

    [tag__not_in] => Array
        (
        )

    [tag__and] => Array
        (
        )

    [tag_slug__in] => Array
        (
        )

    [tag_slug__and] => Array
        (
        )

    [post_parent__in] => Array
        (
        )

    [post_parent__not_in] => Array
        (
        )

    [cache_results] => 
    [suppress_filters] => 
    [update_post_term_cache] => 1
    [update_post_meta_cache] => 1
    [nopaging] => 
    [comments_per_page] => 50
    [no_found_rows] => 
    [search_terms_count] => 1
    [search_terms] => Array
        (
            [0] => shortcode
        )

    [search_orderby_title] => Array
        (
            [0] => wp_posts.post_title LIKE '%shortcode%'
        )

)
```

The two interesting differences that stood out where the `paged` and `orderby` keys. I forced `paged` to be `0` which had no effect, but when I unset `orderby` the search results were exactly the same. 

Now, the search on the REST API uses the standard endpoint structure `/wp-json/wp/v2/v4_docs/?search=shortcodes` which means it's defaulting to the ordering by date, while the standard search doesn't appear to include an orderby. That suggests there's a bug in the REST API – unless ElasticPress manipulates the orderby at some stage...

**Comment by mustafauysal** [comment]
When you unset orderby keys, ElasticPress sorts by relevance in descending order. 

>That suggests there's a bug in the REST API – unless ElasticPress manipulates the orderby at some stage.

I don't think there is a bug, sorting could be different for REST API. You can use `ep_formatted_args` to formatting orders.

**Comment by jakejackson1** [comment]
Thanks for the feedback.

> I don't think there is a bug, sorting could be different for REST API.

The whole idea of the REST API is to replicate WordPress' native features in API format. So if the native search doesn't set an `orderby` by default you would think the REST API shouldn't do so by default either. 

In any case, I'll check out `ep_formatted_args` and see if I can't make both results consistent.

**Comment by jakejackson1** [comment]
I ended up using a filter to modifying the REST API arguments and unsetting the `orderby` parameter for searches. 

For anyone else interested, the code I used was:

```
apply_filters( 'rest_v4_docs_query', function( $args, $request ) {

	/* If doing a search we'll unset the orderby argument */
	if ( isset( $request['params']['GET']['search'] ) ) {
		unset( $args['orderby'] );
	}

	return $args;
}, 10, 2 );
```

`v4_docs` in the filter name refers to the post type you want to modify.
