### ISSUE TITLE
Version 1.9 tells me, it is '1.8'

### ISSUE THREAD

**Issue by dnaber-de** [10up/ElasticPress#495]
The tag 1.9 has the version number `1.8` in it's plugin header which leads to confusion when using this plugin via composer:
https://github.com/10up/ElasticPress/blob/1.9/elasticpress.php#L6
Also the constant `EP_VERSION` is defined to `1.8`.

Also, semantic version numbers would be nice. E.g. `1.9.0` instead of `1.9`.

**Comment by tlovett1** [comment]
@allan23 you see this one?

**Comment by dnaber-de** [comment]
For what I see, you just needed to bump the version to 1.9.1 from the current master (5e8852e) and tag it with 1.9.1.

**Comment by tlovett1** [comment]
This is fixed

**Comment by dnaber-de** [comment]
Thanks.
