### ISSUE TITLE
Elasticpress uses "OR" operator to do searches. No options to use "AND" operator

### ISSUE THREAD

**Issue by ShariqKhan2012** [10up/ElasticPress#500]
When I search for say "Leather shoes", it shows up results containing any of these words.
So all these results come up:
1. leather shoes
2. leather jackets
3. sports shoes

Whereas, I would expect search results to show up only "leather shoes"

I used ElasticPress Debugbar and found out the operator being used is "OR". Hence the above results
Is there a way I can restrict ElasticPress to use "AND" operator for search queries?

Thanks.

**Comment by tlovett1** [comment]
It weights AND matches (phrase match) above OR. You can always filter in and change the matching algorithm.
