### ISSUE TITLE
Option to Use WordPress Search?

### ISSUE THREAD

**Issue by jmusal** [10up/ElasticPress#505]
I have a strange use case that I don't see supported in the docs or quick look at the codebase, but I want to make sure.

I'd like to continue to use the WP search feature by default, but offer a second search that leverages EP/ES (for reasons that I won't get into).  Basically, I'm interested in some way to say "use EP" or "use traditional" that I could build some logic around if needed - does anything like that exist?

**Comment by mphillips** [comment]
To bypass ES for some queries, try returning true for the 'ep_skip_query_integration' filter.

**Comment by jmusal** [comment]
Thank you!  That looks perfect for what I'm trying to do, and I'm sorry that I missed it before asking the question.

**Comment by mphillips** [comment]
No worries. :)
