### ISSUE TITLE
Wiki Request --- intro to searching over custom post types

### ISSUE THREAD

**Issue by denised** [10up/ElasticPress#520]
The wiki page https://github.com/10up/ElasticPress/wiki/Use-Cases doesn't mention "searching over custom post types" as an envisioned use case --- though looking at the code and issues list, it pretty clearly is.

Assuming that is the case, it would really be nice if there were a 1 paragraph intro on the wiki indicating how to get started doing this.

I'll even volunteer to write (some) of it, if people are interested --- but since I'm starting with zero knowledge right now, assume I will have to go through a learning curve to figure it out...

**Comment by tlovett1** [comment]
Writing that would be very helpful!

**Comment by felipeelia** [comment]
As we don't use the Wiki anymore and post_type is covered in the Supported WP_Query Parameters list [here](http://10up.github.io/ElasticPress/tutorial-indexables.html), I'm now closing this one. Thanks!
