### ISSUE TITLE
Endless loop crash if wrong host is input

### ISSUE THREAD

**Issue by blindpet** [10up/ElasticPress#521]
I am testing this for somebody running Apache. I put just localhost (not the correct http://ip:port format) as the host and it saved, then it started making a lot of php calls and crashed Mysql and elasticsearch.

The only thing that stopped the crash was deleting the plugin, however on reinstallation the looping crash continued and I had to restart.

Could you add a failsafe so if the host doesn't meet the specifications it doesn't save?

**Comment by tlovett1** [comment]
Please see if you can reproduce in the develop version of the plugin.

**Comment by blindpet** [comment]
Sorry Taylor, the VPS I was testing this on is no more. It may have been related to the other issue I posted. Starting from scratch worked fine. It may have been related to the caching of the value if it is set as a transient which I asked over in the other issue.

**Comment by tlovett1** [comment]
Yes it is unfortunately. I'd suggest giving 2.1 in the develop branch a try.

**Comment by blindpet** [comment]
OK, did you change the parsing so invalid urls don't get set? Some sort of failsafe would be great.

**Comment by tlovett1** [comment]
The way urls are tested/set is completely different.
