### ISSUE TITLE
Passing sites={site_id} in query string fails to select correct index in multisite setup

### ISSUE THREAD

**Issue by jaisgit** [10up/ElasticPress#531]
When specifying site ids in the query string the code in class-el-api.php:137
`} elseif ( is_int( $scope ) ) {`
is not resolving to true as the argument is a string.

Eg... http://address/to/wp_site_1/?s=search_term&sites=2
Returns results from only the current site_id e.g. 1.

Changing the code to:
`} elseif ( is_numeric( $scope ) ) {`
fixes this behaviour.

I'm not sure if it breaks any other functionality.

**Comment by tlovett1** [comment]
Can you create a PR?

**Comment by jaisgit** [comment]
Sorry, I'm unfamiliar with that process at the moment.

**Comment by jaisgit** [comment]
I have added PR #533
