### ISSUE TITLE
Messup with search and woocommerce

### ISSUE THREAD

**Issue by Namke** [10up/ElasticPress#535]
Hi there, 

I installed latest develop branch today and seem it is totally messup with search function, page always return first page but other than that no page was listed.
Product in WooCommerce return in some sort of random way, sometime nothing, especially on front store, almost return nothing all the time except when it request to show all products.

Is there are anything required beside install ElasticPress, sync and then index by wp-cli?

**Comment by tlovett1** [comment]
Try syncing via the dashboard? Remember, 2.1 (develop) deprecates the EP WooCommerce plugin as it bundles it.

**Comment by Namke** [comment]
Yes I tried several approach, with reindex, sync in dashboard (by enable/disable the features), reinstall (new) Elastic Search instance and such, but nothing work, bit confusing now.

Both 2.1 and develop branch having same issues to me, and yes I don't install EP Woocommerce plugin, just ElasticPress only.

**Comment by tlovett1** [comment]
Do you have a link to where I could see the problem? Perhaps you could email me credentials to a staging environment?
