### ISSUE TITLE
Documentation unclear about continous indexing behaviour

### ISSUE THREAD

**Issue by shivno** [10up/ElasticPress#541]
What happens with the posts created/changed in the meantime when i either:

- disable the plugin for a short time
- run the initial index which takes a few minutes

it is unclear for me if every post is picked up then?

**Comment by kingkool68** [comment]
> What happens with the posts created/changed in the meantime when i disable the plugin for a short time?

No new posts will be indexed if the are created or modified when the plugin is disabled. If you look at the [`setup()`](https://github.com/10up/ElasticPress/blob/b553a2ef5d9c9b70748a889eef6c30aebf1a0111/classes/class-ep-sync-manager.php#L35-L46) method of the `EP_SyncManager` class you'll see all the different events ElasticPress hooks in to to perform a sync. If the plugin is disabled then ElasticPress can't be listening to these events which means new/modified posts aren't synced with Elastic Search.


There is

**Comment by tlovett1** [comment]
If new posts are created during a sync, behavior is a bit unpredictable. @kingkool68 is right about the plugin being disabled.
