### ISSUE TITLE
Indexing bulk IDs in wp-cli

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#542]
Ran across an issue recently where it would've been very beneficial to be able to pipe in specific IDs to index directly instead of just the post type (say using xargs from wp-cli which could be used to retrieve a list of IDs matching some criteria: post type, category, term, date, etc).

There were only 350 items out of the 4,600 published items that needed to be indexed (think events that are published, however only 350 events are in the future or are really 'valid', all other events are published but will never be used/seen).

**Comment by rveitch** [comment]
To expand on this, it would also be useful to specify an individual site ID to index on multisite networks.  I have a use case on a 400 site network where this would be very useful. Currently we only support a limit via `--network-wide=5` (limit to the first 5 sites).  Offset is only applied to posts, so (last I checked) it's also not possible to start or restart a network-wide reindex at a certain offset point, it will always start over from the first site.

I know this should probably be ultimately be broken out to its own issue, and submitting a PR for this has been on my todo list.

**Comment by felipeelia** [comment]
Revisiting this a few years later, it seems we covered all the scenarios:
- For specific IDs we now have `--include`, `--upper-limit-object-id`, and `--lower-limit-object-id`
- For specific sites it's possible to use `--url=<site_url>`
More in the [WP-CLI docs](http://10up.github.io/ElasticPress/tutorial-wp-cli.html). Thanks!
