### ISSUE TITLE
Filtering Search Scope

### ISSUE THREAD

**Issue by rveitch** [10up/ElasticPress#544]
Is there a non-query argument based method for setting the search scope?  The use case would be always defining the scope as 'all' to enable cross-site search on all sites of a multisite network.  This was addressed by @ChrisWiegman in #364, but was not implemented at the time. In the current code base I did not notice any filter hooks for this before the `$formatted_args` and `$scope` are passed to `ep_search()`. I currently use this solution and it is perfect for my use case so I would be happy to submit a PR for it.  Apologies if I happened to miss anything in my assessment, or if there are solid reasons for only handling this in the filters related to query arguments.

Example use:
```php
function filter_ep_search_scope( $scope ) {
	$scope = 'all';
	return $scope;
}
add_filter( 'ep_search_scope', 'filter_ep_search_scope' );
```

**Comment by tlovett1** [comment]
You could always filter here: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L160

I'm fine with a filter on scope.

**Comment by rveitch** [comment]
Thanks @tlovett1.  My concern with the `ep_search_request_path()` filter was that it is applied after the `ep_get_network_alias()` or `ep_get_index_name( $site_id )` functions that define the `$index` for the search request path, so filtering the scope before that point removes the need to handle any  potential re-adjustments to the index path. I've submitted PR #544 with some short documentation. Thanks again for your help and response.
