### ISSUE TITLE
Wrong (single) post is retrieved if ep_integrate is true

### ISSUE THREAD

**Issue by rcespa** [10up/ElasticPress#546]
Hi, I'm trying to set up EP with my WP+WooCommerce installation in a MultiSite environment.
In this network there is a "master" site and a set of "slave" sites.

The idea is to import a set of data in the master site (using WPAllImport), index the products with EP, and use the multisite query ability so that a product is searched "locally" at first and on the master site if not available.
In this way any slave site can enrich its own catalogue with other products while sharing the catalogue with the master.

As of now, I am able to index the products and their variations and I'm able to retrieve results from other sites in my network.
I am able to correctly retrieve products from the master site index and to show them on the slave site home page. I still need to correct the URLs returned because they point to the original site, but it's a giant leap forward for me.

The problem is that when I click on post fetched from the master index (after altering the URL to match the slave site domain name, of course), the post does not obviously exist in the slave MySQL db. I tried to use the ep_integrate magic one more time, adding 

```
if ( ( $query->query['post_type'] == 'product' || $query->query['post_type'] == 'product_variation' ) ) {
                $query->set('ep_integrate', true);
                $query->set('sites', array($my_site_id, 8 ) );
                return $query;
        }
```
to my pre_get_posts filter.

Now I get some results but they are completely useless: instead of the requested post, I get another post absolutely not related.

With a trial & error approach I tried to add a post to the slave site. 
It shows up correctly on the home page and if I click on it, it is fetched and displayed correctly.

I added a second post to the slave site. Again, everything looks good but, unfortunately, if I click on the first local post, I always get the second post.

Hence, my problem should not be related to the master or slave index.

Using the Debug Bar I dumped the query args and the query passed to ES and I noticed that in the query passed to ES the post name is not available:

```
array(66) {
  ["page"]=>
  int(0)
  ["product"]=>
  string(12) "this-is-test"
  ["post_type"]=>
  string(7) "product"
  ["name"]=>
  string(12) "this-is-test"
  ["error"]=>
  string(0) ""
  ["m"]=>
  string(0) ""
  ["p"]=>
  int(0)
  ["post_parent"]=>
  string(0) ""
  ["subpost"]=>
  string(0) ""
  ["subpost_id"]=>
  string(0) ""
  ["attachment"]=>
  string(0) ""
  ["attachment_id"]=>
  int(0)
  ["static"]=>
  string(0) ""
  ["pagename"]=>
  string(0) ""
  ["page_id"]=>
  int(0)
  ["second"]=>
  string(0) ""
  ["minute"]=>
  string(0) ""
  ["hour"]=>
  string(0) ""
  ["day"]=>
  int(0)
  ["monthnum"]=>
  int(0)
  ["year"]=>
  int(0)
  ["w"]=>
  int(0)
  ["category_name"]=>
  string(0) ""
  ["tag"]=>
  string(0) ""
  ["cat"]=>
  string(0) ""
  ["tag_id"]=>
  string(0) ""
  ["author"]=>
  string(0) ""
  ["author_name"]=>
  string(0) ""
  ["feed"]=>
  string(0) ""
  ["tb"]=>
  string(0) ""
  ["paged"]=>
  int(0)
  ["meta_key"]=>
  string(0) ""
  ["meta_value"]=>
  string(0) ""
  ["preview"]=>
  string(0) ""
  ["s"]=>
  string(0) ""
  ["sentence"]=>
  string(0) ""
  ["title"]=>
  string(0) ""
  ["fields"]=>
  string(0) ""
  ["menu_order"]=>
  string(0) ""
  ["embed"]=>
  string(0) ""
  ["category__in"]=>
  array(0) {
  }
  ["category__not_in"]=>
  array(0) {
  }
  ["category__and"]=>
  array(0) {
  }
  ["post__in"]=>
  array(0) {
  }
  ["post__not_in"]=>
  array(0) {
  }
  ["post_name__in"]=>
  array(0) {
  }
  ["tag__in"]=>
  array(0) {
  }
  ["tag__not_in"]=>
  array(0) {
  }
  ["tag__and"]=>
  array(0) {
  }
  ["tag_slug__in"]=>
  array(0) {
  }
  ["tag_slug__and"]=>
  array(0) {
  }
  ["post_parent__in"]=>
  array(0) {
  }
  ["post_parent__not_in"]=>
  array(0) {
  }
  ["author__in"]=>
  array(0) {
  }
  ["author__not_in"]=>
  array(0) {
  }
  ["ep_integrate"]=>
  bool(true)
  ["cache_results"]=>
  bool(false)
  ["ignore_sticky_posts"]=>
  bool(false)
  ["suppress_filters"]=>
  bool(false)
  ["update_post_term_cache"]=>
  bool(true)
  ["update_post_meta_cache"]=>
  bool(true)
  ["posts_per_page"]=>
  int(10)
  ["nopaging"]=>
  bool(false)
  ["comments_per_page"]=>
  string(2) "50"
  ["no_found_rows"]=>
  bool(false)
  ["order"]=>
  string(4) "DESC"
}
```

and this is what gets passed to ES:

```
{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": []
    },
    "filter": {
        "and": [
            {
                "term": {
                    "post_type.raw": "product"
                }
            },
            {
                "term": {
                    "post_status": "publish"
                }
            }
        ]
    }
}
```

so it is simply returning 10 posts ordered by post date.

I tried to manipulate the query a little bit passing the 's' parameter with post_name as value and post_name, guid, permalink as post_fields. All the changes are visible in the WP_Query object but nothing shows in the query passed to ES.

Any help is appreciated. Thanks in advance!

Ciao,
Roberto

**Comment by rcespa** [comment]
After digging a little bit in the source code, I noticed that post_name as a filter is not available.
I modified the code for the author filter a little bit (class-ep-api.php):

```
                /**
                 * post_name query support by Roberto Cespa
                 *
                 * @since 2.1
                 */
                if ( ! empty( $args['name'] ) ) {
                       	$filter['and'][] = array(
                                'term' => array(
                                        'post_name.raw' => $args['name'],
                                ),
                        );
                        $use_filters = true;
                }
```
and now it is working as expected.

I consider this a quick and dirt workaround and I really do not know if it is the right way to solve this problem and I wonder if you can consider this request as a feature request.

Ciao,
Roberto

**Comment by tlovett1** [comment]
EP wasn't intended to pull single posts as MySQL will be faster. Why not just `switch_to_blog`?

**Comment by rcespa** [comment]
Hi @tlovett1 !
Sorry for the delay.
Yes, you're right: EP was not intended to replace MySQL but in my case switch_to_blog is a real pain.
Basically I need to run the same query on two different WP Sites in the same network, merge the results and proceed with the loop.
Unfortunately it is difficult with WooCommerce, probably because there are several loops or queries involved.

EP, on the other side, can return queries perfectly merged.
The real problem for me is the time needed to import 30K products and variations in WP+WC.
I was using a famous plugin but it needed more than 6 hours per site and often the import failed with no clear error.

I ended up writing my very specific import routine and now I can get the same result in about 1 hour per site.

So I removed my code but, please, consider this as a feature request for the future!

Ciao,
Roberto
