### ISSUE TITLE
Instance of wpdb passed to ep_wc_blacklist_coupons instead of WP_Query

### ISSUE THREAD

**Issue by nathanielks** [10up/ElasticPress#548]
Happy Monday, all!

I've got a curious bug occurring, but I'm not entirely sure it's EP's fault. I've got the following backtrace:

```
2016/08/08 19:09:52 [error] 465#465: *5921 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method wpdb::get() in /www/examplecom_761/bedrock/releases/20160808172629/web/app/plugins/elasticpress/modules/woocommerce/woocommerce.php:571
Stack trace:
#0 /www/examplecom_761/bedrock/releases/20160808172629/web/wp/wp-includes/plugin.php(235): ep_wc_blacklist_coupons(false, Object(wpdb))
#1 /www/examplecom_761/bedrock/releases/20160808172629/web/app/plugins/elasticpress/classes/class-ep-api.php(1571): apply_filters('ep_elasticpress...', false, Object(wpdb))
#2 /www/examplecom_761/bedrock/releases/20160808172629/web/app/plugins/elasticpress/classes/class-ep-api.php(2089): EP_API->elasticpress_enabled(Object(wpdb))
#3 /www/examplecom_761/bedrock/releases/20160808172629/web/app/plugins/elasticpress/classes/class-ep-wp-query-integration.php(184): ep_elasticpress_enabled(Object(wpdb))
#4 /www/examplecom_761/bedrock/releases/20160808172629/web/wp/wp-includes/plugin.php(291): EP_WP_Query_Integration->filter_found_posts_qu" while reading response header from upstream, client: 208.53.75.208, server: staging-examplecom.kinsta.com, request: "GET /?s=essentials HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7-fpm-examplecom.sock:", host: "staging-examplecom.kinsta.com"
```

I'm not getting this locally in production, so I'm aware it may be a hosting issue. Diving deeper, the two relevant portions of code are `elasticpress/classes/class-ep-wp-query-integration.php:183` which is called from `wp-includes/query.php:3817` because it's a filter.

Here's what's curious: the error says that an instance of `$wpdb` is being passed into the `filter_found_posts_query` function, but what _should_ be happening is that should be an instance of `WP_Query`, not `wpdb`. Looking at the WordPress core code, it should be `WP_Query` as well because it's passing an instance of itself by reference.

I'm wondering if you've encountered this before? I'm working with the host to get a more detailed backtrace so I can dive deeper. I'm also wondering if this is perhaps a language bug, that the `apply_filters_ref_array` function is picking up the `$wpdb` variable for whatever reason...

**Comment by tlovett1** [comment]
Haven't seen that one. Looks like something else is filtering in and returning $wpdb instead of WP_Query somewhere. Wish I could be of more help :(

**Comment by nathanielks** [comment]
Aha! I hadn't thought of that! Thanks, @tlovett1!

**Comment by nathanielks** [comment]
Ah! Figured it out! I forgot to deactivate SearchWP and it's related plugins... that's what was causing it. Thanks for the push in the right direction!
