### ISSUE TITLE
ElasticPress Integration works only when admin is logged in

### ISSUE THREAD

**Issue by silsha** [10up/ElasticPress#549]
I noticed an issue with ElasticPress on one of my websites: The wordpress integrated frontend search is only using elasticsearch while an admin is logged in.

As far as I was able to debug this, I noticed:
* About 10 minutes after the last admin was logged in, the search page stops using elasticsearch
* There are no new requests to the elasticsearch server
* The elasticsearch server is online and sends the expected result when querying manually
* As soon as an admin opens /wp-admin, everything works fine again for every user

**Comment by tlovett1** [comment]
Can you try to trace the problem? That makes no sense.

**Comment by silsha** [comment]
Absolutely. Do you have an idea how to trace this better?

**Comment by tlovett1** [comment]
Look in the query integration class and find where it "escapes"
