### ISSUE TITLE
PHP Fatal error:  Class 'WP_Metadata_Lazyloader' not found in Wordpress 4.5.3

### ISSUE THREAD

**Issue by paulhuisman** [10up/ElasticPress#550]
When running `wp elasticpress index --setup` i'm getting the following error:

`PHP Fatal error:  Class 'WP_Metadata_Lazyloader' not found`

This seems to be caused by a new version of Wordpress. I'm using 4.5.3.

Using elasticpress 1.6.2

**Comment by tlovett1** [comment]
Can you make sure WP CLI is up-to-date?
