### ISSUE TITLE
ElasticPress returning massively incorrect search results when endpoint times out.

### ISSUE THREAD

**Issue by richardmax** [10up/ElasticPress#551]
Hi

Great plugin btw... we are a massive global publishing firm with millions of users daily... thank you!

One big bug though! :)

If we index the site - all works fine. (200,000 WP articles indexed)

If we turn off ElasticPress - all works fine - it falls back to vanilla (urrgggh) WP search.

If however we don't change anything in ElasticPress (and all working fine) and the endpoint times out (as seems to happen every morning with our EC2 Cluster) then all hell breaks lose:

1) ElasticPress doesn't fall back to standand WP search.
2) We get 800,000 results showing on any search (when only 200,000 posts are indexed - this technically is impossible). Even 'fdsfsgtwrewe' returns 800,000 + results.

It appears that ElasticPress has checked that the endpoint worked when it was installed and indexed but then doesn't check or gracefully fail once all is setup. It basically assumes that the endpoint is available for eternity. If for any reason it isn't then it gets stuck.

Has anyone else experienced this?

More importantly we'd like to fix it or work with you to fix it - what is best?

Can we look to the elegant failure route so these 800,000 results are 0 for instance?

Happy to chat anytime directly....

KR

R

**Comment by tlovett1** [comment]
Hey Richard, definitely want to work together on this. What version are you running?

**Comment by richardmax** [comment]
Thanks for the swift reply, appreciated.

We are running two stacks...  Dev / Systest. Both are running Elastic Press 2.0.1 

Dev has Elastic Search 1.5, Systest has ES 2.0. Amazon based.

Last night FYI the endpoint didn't crash / vanish / go to sleep - first time ever. (FYI - we removed extra indices, and changed the loadbalancer listeners from TCP to HTTP yesterday)

Just seems like ElasticPress needs to trigger a fallback to standard WP vanilla search if the previously ok ES endpoint fails for any reason (on a per request basis). Maybe it should be a setting? The 800,000 results is a mystery but 100% connected to the latter.

Happy to assist and again thank-you for single-handily fixing WordPress Search (and opening up some v exciting opportunities re using ES to power apps from WP)

R

**Comment by tlovett1** [comment]
First, you should upgrade to 2.1 (in develop right now).

**Comment by tlovett1** [comment]
Ok so EP should be falling back to default search if the request to ES fails. You can filter the timeout using this filter: https://github.com/10up/ElasticPress/blob/8b158171cd423f1750f87eac6e52d95e11d70181/classes/class-ep-api.php#L276

**Comment by richardmax** [comment]
Hi. I am mid a major release so will look at this after. I had a peek at your code / suggestion re filtering the timeout but it didnt appear to be the right function. Put simply EP needs to either use Elastic Search or if fails for any reason it should fall back ideally or inform the user of an error. Currently its possible to be stuck in limbo where you get an invalid elastic search query and no fall back search being triggered. i have many ideas re solutions but keen to see what your clever minds come up with! :) thnks too

**Comment by tlovett1** [comment]
Fall back should always be WordPress search. The only issue I see is a very slow timeout while pinging ES. Can you reproduce in 2.1?
