### ISSUE TITLE
EP used even with ep_skip_query_integration

### ISSUE THREAD

**Issue by rcespa** [10up/ElasticPress#552]
Hi, I have a problem with a couple of plugins (FacetWP and Excel-Like Product Manager for WooCommerce).
Both the plugins stop working with EP activated.
The problem is that they run a standard query with the argument
`'field' => 'id'`

EP does its magic but always returns an array of WP_Post objects instead the expected array of post ids.

I tried with 

`add_filter('ep_skip_query_integration', '__return_true');`

but it still does not work.

Any suggestion?

Thanks in advance,
Roberto

**Comment by tlovett1** [comment]
What version are you using?

**Comment by rcespa** [comment]
EP: 2.1
WP: 4.5.3
WC: 2.6.4

**Comment by tlovett1** [comment]
Can you try to trace the issue? `ep_skip_query_integration` should work

**Comment by mdorchain** [comment]
I was testing EP with the same configuration (EP, Facetwp, woocommerce) and observed the same 2 issues about the array of posts returned when a an array of int is expected, but also the ep_skip_query_integration filter having no effect with the woocommerce module.

**Comment by tlovett1** [comment]
`'field' => 'id'` won't work in EP due to `WP_Query` limitations.

**Comment by jdmadison** [comment]
Sample filter implementation for the WooCommerce / StoreFront 404/featured products issue (Requires patch noted in Pull Request #705):

```php
function my_filter_ep_skip_query_integration( $skip, $query ) {

    $product = ( $query->get( 'post_type' ) === array( 'product', 'product_variation' ) );
    $featured = in_array( '_featured', array_column( $query->meta_query->queries, 'key' ) );

    return ( $skip || ( $product && $featured ) );

}

add_filter( 'ep_skip_query_integration', 'my_filter_ep_skip_query_integration', 10, 2 );
```
