### ISSUE TITLE
Fatal error: Call to a member function is_visible() on boolean in ...

### ISSUE THREAD

**Issue by khaclub** [10up/ElasticPress#554]
Hello,
I got an issue during indexing the site. 

```
Processed 20300/21314 entries. . .
Processed 20650/21314 entries. . .
Processed 21000/21314 entries. . .
Fatal error: Call to a member function is_visible() on boolean in /home/testtest/public_html/wp-content/themes/royal/framework/theme-functions.php on line 2714
Adding mapping...
Deleting index...
<div class="carousel-area  slider-1496"><h2 class="title"><span>Latest Products</span></h2><div class="owl-carousel productCarousel">
```

Do you know what type of error is and how to fix that? I thought i was gonna get the point but that happened at the end :(
I really appreciate your help.

**Comment by khaclub** [comment]
All right guys. The permalink url of the search has been changed too. In my case, it was changed from 
"?s=(KEYWORDS)&post_type=product" to "?submit=Search&s=(KEYWORDS)". So try to change your search result link in your theme to fix that

**Comment by tlovett1** [comment]
This is an error in your theme.
