### ISSUE TITLE
Missing Orders in Admin and Order Search

### ISSUE THREAD

**Issue by scoopdev** [10up/ElasticPress#555]
Hey Guys, 

First of all I absolutely love the plugin, it has made my life a lot easier. I have an issue which has meant I have had to disable it for now though if you can help please. Basically it has been missing the occasional orders; the customer has completed successfully but the order has not shown in the admin and could not be found in the search. Then today we had 100 pending orders but only around 40 actually showed in admin until the plugin was disabled. 

The plugins I have installed are below and I can provide a full status report if required. I appreciate your help with this. 

Gravity Forms 	  	by rocketgenius – 2.0.3
Reviews.co.uk for WooCommerce 	  	by Reviews.co.uk – 0.4
Advanced Custom Fields PRO 	  	by Elliot Condon – 5.3.10
Akismet 	  	by Automattic – 3.1.11
Custom Post Type UI 	  	by WebDevStudios – 1.3.5
Custom Sidebars 	  	by WPMU DEV – 2.1.0.8
Developer's Custom Fields 	  	by Steve Taylor – 1.3.1
Disqus Comment System 	  	by Disqus – 2.85
Easy Bootstrap Shortcode 	  	by oscitas – 4.5.4
ElasticPress WooCommerce 	  	by Taylor Lovett, 10up – 1.2.1
Gravity Forms + Custom Post Types 	  	by spivurno – 3.1.4
HTML Page Sitemap 	  	by – 1.3
Imagify 	  	by WP Media – 1.5.6
Mailgun 	  	by Mailgun – 1.4
Maintenance Page 	  	by ThemeGrill – 1.0.8
Options Framework 	  	by Devin Price – 1.8.5
PayPal for WooCommerce 	  	by Angell EYE – 1.2.3
Recover Abandoned Cart 	  	by Fantastic Plugins – 13.0
Show Current Template 	  	by JOTAKI Taisuke – 0.2.2
Simple 301 Redirects 	  	by Scott Nellé – 1.07
Sucuri Security - Auditing, Malware Scanner and Hardening 	  	by Sucuri, INC – 1.8.1
Tawk.to Live Chat 	  	by Tawkto – 0.2.0
WooCommerce - Social Login 	  	by WPWeb – 1.4.3
WooCommerce Address Validation 	  	by WooThemes / SkyVerge – 1.9.2
WooCommerce Extended Coupon Features 	  	by Jos Koenis – 2.3.4
WooCommerce Cart Notices 	  	by WooThemes / SkyVerge – 1.6.0
WooCommerce Checkout Add-Ons 	  	by WooThemes / SkyVerge – 1.8.0 – 1.8.2 is available
WooCommerce Google Analytics Integration 	  	by WooThemes – 1.4.0
WooCommerce Mix and Match 	  	by WooThemes – 1.1.5 – 1.1.6 is available
WooCommerce Print Invoices/Packing Lists 	  	by WooThemes / SkyVerge – 3.1.4
WooCommerce Table Rate Shipping 	  	by WooThemes – 3.0.1
WooCommerce 	  	by WooThemes – 2.6.4
WooCommerce Helper 	  	by WooCommerce – 1.7.0
Yoast SEO 	  	by Team Yoast – 3.4.2
WP Customer Reviews 	  	by Go Web Solutions – 3.1.2
WP Bullet Varnish Cache 	  	by Mike – 1.0

**Comment by tlovett1** [comment]
Well first of all, you can always resolve missing posts by re-indexing. First I would try upgrading to 2.1 (in develop branch).

**Comment by blindpet** [comment]
@tlovett1 it is a WooCommerce site, is it possible the bug is in ElasticPress WooCommerce?

**Comment by tlovett1** [comment]
in 2.1 the EP WooCommerce plugin is merged into the core plugin. Deactivate EP WooCommerce and upgrade to 2.1 for testing.

**Comment by lvickers** [comment]
I am experiencing this same issue. The order count will rise, but the order does not appear until I reindex. It doesn't happen every time though. Is there a way I could tell ElasticPress to just reindex the "shop_order" post type after each order? Would that be the correct way to fix this?

**Comment by blindpet** [comment]
@lvickers have you tested the dev branch of EP? I believe @tlovett1 is suggesting that will fix it.
