### ISSUE TITLE
How to enable modules

### ISSUE THREAD

**Issue by lmartins** [10up/ElasticPress#556]
Sorry, this is most likely something I am missing but could you explain how to enable the additional modules such as admin, related posts or WooCommerce?

Thank you.

**Comment by tlovett1** [comment]
Navigate to the admin and click "Activate" for the modules you want.

**Comment by lmartins** [comment]
Thanks Taylor, I feel im missing something though. This is what I have on ElasticPress settings page:
https://cl.ly/2z3i2o3p3U2K

**Comment by tlovett1** [comment]
You need to use the develop branch in Github. 2.1 is still in beta.

**Comment by lmartins** [comment]
oohh, this looks sweet. Thanks Taylor.
