### ISSUE TITLE
'date_query' and 'meta_query' don't work together. 

### ISSUE THREAD

**Issue by sgogov** [10up/ElasticPress#557]
Hi there.

Is it possible to use  'date_query' and 'meta_query' in the same query.
This is my query:
$args = array(
	'ep_integrate' => true,
	'sites' => array(1,2),
	'post_type' => 'post',
	'posts_per_page' => 1,
	'post_status' => 'publish',

        'date_query' => array(
           array(
               'column' => 'post_date',
               'before' => $current_date_braking_news,
           ),
           array(
               'column' => 'post_date',
               'after'  => $expire_date_string,
           ),
        ),
        'meta_query' => array(
            array(
                'key'   => 'breaking_news',
                'value' => '1',
                'compare' => '=',
            ),    
        ),
        
        'orderby' => 'date',
        'order' => 'DESC',
);

The relation between date_query and meta_query i need to be 'AND'. 
Thank you for your work.

**Comment by Ritesh-patel** [comment]
Hi @sgogov 

I checked Elasticsearch query for above WP_Query args and relation between date_query and meta_query is "AND" only.

Can you give us some more details? You can debug Elasticsearch query with [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugin.

- Ritesh
