### ISSUE TITLE
wp_get_sites() has been deprecated in 4.6

### ISSUE THREAD

**Issue by schrapel** [10up/ElasticPress#559]
https://developer.wordpress.org/reference/functions/wp_get_sites/
https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1615

If I have time I'll make the change myself but right now I'm doing a audit to upgrade our sites

**Comment by tlovett1** [comment]
Fixed

**Comment by schrapel** [comment]
Thanks so much. Are we able to do a minor tag so we can update our composer?
