### ISSUE TITLE
QA GUI sync (single site and multisite)

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#560]
The following scenarios should be tested:
- Multisite
  - Some sites with posts
  - Some sites with no posts
- Single site
   - With posts
   - With no posts
- Syncing with custom post types and taxonomies
- Pause sync
- Resume sync

**Comment by Ritesh-patel** [comment]
All the above test cases are working fine except one. If by any reason Elasticsearch index is deleted, the ElasticPress Query doesn't fallback to WP Query though the request response is 404. Need to add extra check of request status using `wp_remote_retrieve_response_code` function.

**Comment by tlovett1** [comment]
Can you write a PR and a unit test?

**Comment by Ritesh-patel** [comment]
Added PR https://github.com/10up/ElasticPress/pull/565
