### ISSUE TITLE
wp-cli send_bulk_errors Array to string conversion

### ISSUE THREAD

**Issue by wkw** [10up/ElasticPress#561]
EP **v2.0.1**
ES: **v2.3.4**

First time use of EP and working out the filters I need to put in place to control post_meta. While running some wp-cli indexing, I had a half dozen posts fail to index. Started sleuthing @ [wp-cli.php](https://github.com/10up/ElasticPress/blob/c41d8968dbcdb915be03bafe2b989ac8b12371d4/bin/wp-cli.php#L556).

for this command: `wp elasticpress index --show-bulk-errors`

I'm getting these PHP warnings:
```
PHP Notice:  Array to string conversion in 
.../web/app/plugins/elasticpress/bin/wp-cli.php on line 557
```

Dumping `$this->failed_posts_message` shows it to have this structure:

```
[2167] => Array
(
    [type] => illegal_argument_exception
    [reason] => Document contains ...<snip>...
    [caused_by] => Array
        (
            [type] => max_bytes_length_exceeded_exception
            [reason] => bytes can be at most 32766 in length; got 35237
        )
)
```

Which makes this code not work and I don't get useful diagnostics:
`$error_text .= "\t" . $this->failed_posts_message[ $failed ] . PHP_EOL;`

Is that error response somehow unique to my setup? I presume it's elasticsearch's response?

If I knew errors would always look like that, I could work up a PR.

**Comment by tlovett1** [comment]
Can you try on EP 2.1?
