### ISSUE TITLE
wp-cli index operation always re-activates EP.

### ISSUE THREAD

**Issue by wkw** [10up/ElasticPress#562]
EP v2.0.1

When EP plugin is enabled, but not "active", running cli index always makes it "active" after indexing. While I don't have a strong case to argue against this behavior, it nonetheless seems wrong. I'd like to think I can index or perform other operations, but do so while not having the integration active. I'm probably the odd dude out on this issue, but for the moment in our dev cycle I kind of need it turned off (multiple parties interacting with the various dev/staging databases and saw some weird results from the Admin integration module).

The output I get, as confirmed by reloading Settings -> EP page after indexing:

> Warning: ElasticPress is already **deactivated**.
> Indexing posts...
> ElasticPress is currently deactivated, **activating**...
> Success: **ElasticPress was activated**!

The plugin should respect the current active setting after indexing.

PR: #563 

Postscript:  we use Composer in our deploys so forking composer-managed modules for tiny changes ends up being a maintenance headache down the line since we do primarily client work, and often hand these projects off at some point. I'd much rather get PRs accepted and stick to the canonical repo. Doesn't matter for this issue, but more so for the previous one I posted re: indexing and the bulk error reporting (type of things...).

PPS: **Thanks** to the 10up team for this work (and the other great open source!). I used Fantastic ElasticSearch on several projects, but it went dormant, started to have problems, and a colleague brought EP in for one or two projects and made me check it out. I appreciate how slim your plugin is; in less than a day I've been through most of the code and know where I'm at with it. FES had the Elastica baggage in it which was more than I wanted to take on. No dis to ParisHolley, his shit rocked too!

**Comment by tlovett1** [comment]
@wkw thanks for using the plugin! No doubt this is an issue in 2.0.1. However, we've done a bit of a refactor in 2.1 (hopefully releasing in the next month). I'd recommend trying the new version (develop branch) before going doing the road of fixing 2.0.1

**Comment by wkw** [comment]
Will do. thanks.
