### ISSUE TITLE
Better meta_query support

### ISSUE THREAD

**Issue by solepixel** [10up/ElasticPress#567]
Has anyone implemented better support for `meta_query` more compatible with the WP_Query standard? I'm curious if there's a module that may already be written to support this or plans to implement broader arrays. I'm starting to dig into it a bit now, but wondering if this may already exist. Specifically looking for nested array support. Thanks!

**Comment by tlovett1** [comment]
Wondering what you think is important but missing?

**Comment by solepixel** [comment]
Here is a gist that shows both WP_Query args and ElasticPress formatted args:
https://gist.github.com/solepixel/8acf278ed60105a0e846f17a932276d4

As you can see I have many meta_query args but they don't make it over to the ElasticPress args. The documentation says:

> `meta_query` accepts an array of arrays where each inner array _only_ supports `key` (string), `type` (string), `value` (string|array|int), and `compare` (string) parameters.

The example is just a sample, but the query can get more complicated than just the example. My standard queries are taking 20-30 seconds, which is why I'm implementing ElasticSearch.

**Comment by tlovett1** [comment]
Most of that should be supported. Can you find what exactly isn't?

**Comment by solepixel** [comment]
Well, from what I can tell, I feel I'm writing my WP_Query args correctly. If it's supported, then what am I doing wrong that would cause those meta queries to not work. The args for ElasticSearch seem to only be honoring the post type. I pretty much get ALL results (very quickly, mind you), but it's not filtering them based on the `meta_query`. Do I need to format them a different way?

**Comment by solepixel** [comment]
Still digging (slowly), but nested multiple conditions is where I'm finding an issue. Here's a dump of my query args vs the formatted args for ElasticSearch:

https://gist.github.com/solepixel/6c3b5b4ce55bfb25c4ef2c0734ce88bc

**Comment by solepixel** [comment]
Should I be using aggregations instead of the meta_query args?

https://qbox.io/blog/elasticsearch-aggregations

I'm not sure I fully understand them well enough to know how to format them correctly.

**Comment by solepixel** [comment]
Here's another dump of vars when wp_formatted_args actually has some criteria from the meta_query:

https://gist.github.com/solepixel/244ef9b493c00bc492f8434970532d27

Sorry if I'm just posting a lot while I'm digging around, but struggling to get this to work right and hope maybe something I post makes sense to someone that knows how I can fix it.

**Comment by tlovett1** [comment]
@solepixel closing this. Feel free to reopen with a specific missing feature or submit a PR.

**Comment by pySilver** [comment]
well looks like nested meta/tax queries are not supported https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1079

I guess this is what @solepixel meant. I also face the same issue.

**Comment by ivankristianto** [comment]
@pySilver Yes, nested tax_query is not supported yet.
