### ISSUE TITLE
post_parent = 0 evaluates as false

### ISSUE THREAD

**Issue by leeroyrose** [10up/ElasticPress#571]
When trying to hide group products from woocommerce sites, setting post_parent to 0 has no effect. It evaluates as false in the format_args function: ! empty( $args['post_parent'] ). As this parameter does not accept an array, it's more accurate to use isset( $args['post_parent'] ).

**Comment by tlovett1** [comment]
@Ritesh-patel can you test this one out?

**Comment by tuanmh** [comment]
I can confirm this @tlovett1, fixed by this PR https://github.com/10up/ElasticPress/pull/564 a week ago.
