### ISSUE TITLE
Exclude Post Type from “Related Posts”

### ISSUE THREAD

**Issue by FlorianBrinkmann** [10up/ElasticPress#575]
Hi!

At first: Thanks for the nice plugin :)
Would it be possible to add a filter or something like that so one or more post types could be excluded from the “Related Posts” module? I only display the module for normal posts and doesn’t want it to display pages and a CPT…

**Comment by tlovett1** [comment]
@Ritesh-patel can you take care of this one? Should be an easy patch.

**Comment by Ritesh-patel** [comment]
Introduced `ep_find_related_args` filter for related posts query args in https://github.com/10up/ElasticPress/pull/576

**Comment by FlorianBrinkmann** [comment]
Great, thank you!
