### ISSUE TITLE
Elasticsearch indexing widget area

### ISSUE THREAD

**Issue by aakal** [10up/ElasticPress#578]
Hello everyone,

I have setup Elasticpress with our own Elasticsearch server, on a development environment. So far, the results are pretty good but I have noticed a weird problem (maybe it's default plugin behavior I don't know at this point), that Elasticsearch also indexes the widget area.

This brings up the following problem: If a post, woocommerce item, etc. has your search terms on the widget area, then it will be included on the search results too. Let me illustrate this:

Suppose you search for "running shoes", and a "soccer ball" has a top sellers widget, which includes "nike running shoe" as a top seller at the time of indexing. 

This leads to the inclusion of "soccer ball" (which is irrelevant to your search terms) due to Elasticsearch indexing the text on the widget area.

Now I don't know if this is the normal behavior, or there is a problem in our configuration as this is the first time we're using Elasticsearch. If there's a way of excluding widget areas and indexing titles and post contents, that would be great. Any help would be much appreciated, thanks!

**Comment by tlovett1** [comment]
This is definitely a bug. Version 2.1?

**Comment by aakal** [comment]
Hi,

Thanks for getting in touch. 

That's correct, just checked it now from elasticpress.php. 

By the way, let me say this is one of the most helpful plugins that I have come across. We are currently remaking a student community website with Wordpress, using around 40 heavy plugins; Elasticpress coupled with Redis, make the admin area faster than stock WP out of the box :)

The same goes for the frontend too. Just wanted to congratulate you for the great work. Please let me know if I could be of any help. Thanks.

**Comment by AaronHolbrook** [comment]
Very cool to hear, thanks for the kind words @aakal !

**Comment by Ritesh-patel** [comment]
Hi @aakal 

I am not sure if I understand the issue here correctly. Can you give us more details how to reproduce this one?

And thanks for your kind words :)

Regards,
Ritesh

**Comment by aakal** [comment]
Hi Ritesh,

Well, in my opinion you guys definitely deserve some kudos :)

Onto the bug; the problem I was describing was, when Elasticpress indexes a page, it indexes both the #primary (content) and the #secondary (widget) areas. This causes inclusion of irrelevant items (especially for woocommerce) when returning search results. 

If you want to reproduce this issue, please enter a woocommerce product called "nike running shoe". Adjust this item from the database so that it becomes a top selling product. Then, setup a woocommerce top sellers sidebar widget. After that, create a product called "adidas soccer ball".

Now, when you navigate the to "adidas soccer ball", you should see "nike running shoe" in the woocommerce top sellers widget. 

If you index results exactly at this point, and make a search with the search term "nike running shoe", you will see "adidas soccer ball" coming up in the search results. This is probably due to Elasticpress indexing the whole page, so that "nike running shoe" keywords gets indexed for "adidas soccer ball", therefore including that item in the search results, albeit it's irrelevant.

I hope I could clearly illustrated the issue here. I did want to include pictures, but we have pushed our dev server to production yesterday, and we have shutdown woocommerce temporarily in our production environment in order to make some cosmetic changes. Once I setup our staging environment I can send you some pics if you like. Thanks,

**Comment by Ritesh-patel** [comment]
Hi @aakal 

Thanks for the detailed explanation. I can't find WooCommerce top sellers widget in WooCommerce plugin. Can you point out the exact widget you are using?

Regards,
Ritesh

**Comment by aakal** [comment]
Hi @Ritesh-patel 
Sorry about that. I looked it up now, it was "Top Rated Products" widget, we then replaced it with an external best sellers widget, that's why I mixed them up. 

However, please bear in mind that this bug is not dependent of what widget is in the sidebar. The problem here is **indexing** of the sidebar area. That means, if your search term appears in the sidebar when that singular page is being archived, then that singular page will be included in the search results even though it's irrelevant to the search term you are looking for. I hope I could explain what the problem is here, it's kind of a weird and difficult to describe problem. 

Let me illustrate it a bit more for you. For example, you can easily reproduce this problem by simply outputting a text "Ritesh Patel" in a widget that appears on both archive and single pages. Then, if you index the pages, and run a search query with the term "Ritesh Patel", you'll see all those pages come up.

Please let me know if you need more details.

**Comment by Ritesh-patel** [comment]
Hi @aakal 

I tried but still can't reproduce it. What I understand is, while doing indexing, it also indexes widget area for that page? That seems unexpected behaviour as ElasticPress only indexes page/post content and related meta details.

I suggest you to check it once with WordPress' default theme, all plugins disabled (except which are needed to reproduce this) and perform re-index.

**Comment by tlovett1** [comment]
@aakal see this?

**Comment by aakal** [comment]
@tlovett1 ugh sorry about that forgot to post answer.
@Ritesh-patel Yes that's correct. It also indexes the widget area. I was completely busy for the past 2 weeks but I was able to setup the testing environment. I'll test with default settings and no other plugins as you said on next week, and let you know as soon as possible. Thanks!

**Comment by aakal** [comment]
@Ritesh-patel Ritesh, the "re-indexing" part may be the culprit here. While having that problem, I was not re-indexing the posts. I'll check that also and let you know.

**Comment by Ritesh-patel** [comment]
Hey @aakal 

We are still not able to reproduce this one. Any more detail you can provide?

**Comment by Ritesh-patel** [comment]
Hi @aakal 

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
