### ISSUE TITLE
Support for orderby rand

### ISSUE THREAD

**Issue by jonathan-dejong** [10up/ElasticPress#580]
Hi!

Just wondering wether it's even possible to support orderby rand? 
I've got a query where I set orderby to `meta_value rand`. While meta_value works rand does not and I notices it's not supported. 

This is not a pretentious request. I'm wondering wether there is a way to support rand at all? I have no insight in how the querying towards elasticsearch works :)

**Comment by tlovett1** [comment]
Definitely possible. Not something we've added yet.

**Comment by jonathan-dejong** [comment]
Cool! Great to hear.. I spent about 30min trying to figure out the code of the plugin but I could not find the relevant locations to tinker with :)

**Comment by Ritesh-patel** [comment]
@tlovett1 @jonathan-dejong this has been added in #584 however, orderby rand will work standalone, `orderby => meta_value rand` won't give expected results.

**Comment by jonathan-dejong** [comment]
Hi @Ritesh-patel 

Thanks! Is it due to a technical incompatibility? Or just not "fixed" yet? 
I very much appreciate you working on this but for it to be useful in my particular situation I'd need the ability to filter by `meta_value rand` :)

**Comment by Ritesh-patel** [comment]
Hi @jonathan-dejong 

I think it's technical incompatibility. In Elasticsearch I can't find any way to sort on random order along with other fields.

**Comment by jonathan-dejong** [comment]
Damn that's not good news.. :/
