### ISSUE TITLE
action_queue_meta_sync function attempts to index even when EP is not alive

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#582]
Noticed this during a migration that does one-off importing, the function `action_queue_meta_sync` attempts to process even if the Elasticsearch host application is unreachable.

This causes increased processing time on each item as the remote request must timeout before proceeding.

**Comment by tlovett1** [comment]
Ritesh, can you test this one?

**Comment by Ritesh-patel** [comment]
@tlovett1 @AaronHolbrook this is not limited to `action_queue_meta_sync` function only, it does try to sync post on post update if Elasticsearch host is not reachable. So I think none of the module should be active in such case.
