### ISSUE TITLE
HTTP Request 404 to .../post/_search

### ISSUE THREAD

**Issue by isuke01** [10up/ElasticPress#590]
Hello,
Just installed ElasticPress (2.1.1)
Wordpress (4.6.1)
Elasticsearch Host to : http://192.168.10.10 and test to domain (http://starter.dev)
I turned on module, and tried to test plugin using custom function:

`function test_query( $type = false ){
    $before = microtime(true);
    if( !$type ){
        $querry = new WP_Query( array(
                //'ep_integrate'   => false,
                'post_type'      => 'post',
                'posts_per_page' => 50,
            ) );
    }else{
        $querry = new WP_Query( array(
                'ep_integrate'   => true,
                'post_type'      => 'post',
                'posts_per_page' => 50,
            ) );
    }
    $after = microtime(true);
    return ($after-$before) . "  script\n";
}`

And in debug (Query monitor)
**404 Not Found**
POST
http://192.168.10.10/starterdev-1/post/_search

> WP_Http->request()
 wp-includes/class-http.php:227
wp_remote_request()
 wp-includes/http.php:153
EP_API->remote_request()
 wp-content/plugins/elasticpress/classes/class-ep-api.php:1879
ep_remote_request()
 wp-content/plugins/elasticpress/classes/class-ep-api.php:2264
EP_API->query()
 wp-content/plugins/elasticpress/classes/class-ep-api.php:167
ep_query()
 wp-content/plugins/elasticpress/classes/class-ep-api.php:2200
EP_WP_Query_Integration->filter_posts_request()
 wp-content/plugins/elasticpress/classes/class-ep-wp-query-integration.php:239
apply_filters_ref_array('posts_request')
 wp-includes/plugin.php:291
WP_Query->get_posts()
 wp-includes/query.php:3561
WP_Query->query()
 wp-includes/query.php:4050
WP_Query->__construct()
 wp-includes/query.php:4161
test_query()
 wp-content/themes/tankenbak/home.php:30

And also i found 1 more bug.
Woocommerce plugin on, go to Elastic Press setting, turn on WOO module, Turn off Woocommerce, now we cant disable module for woocommerce.
But in few places we will see :
`Fatal error: Uncaught Error: Call to undefined function WC() in /home/vagrant/projects/starter.dev/wp-content/plugins/elasticpress/modules/woocommerce/woocommerce.php:309 `
In backend (when click on posts) , on frontend, in place where we have custom query, where are post types "product".

**Comment by Ritesh-patel** [comment]
Hi @isuke01 

Looking at the error, it seems ElasticPress is not able to connect to Elasticsearch instance. Can you please make sure that Elasticsearch is running on `192.168.10.10 ` ? You can check ElasticPress in admin dashboard for that.

Thanks for pointing out to WooCommerce module bug, we will look into it.
