### ISSUE TITLE
Why is the ElasticPress Main Menu so high in the order?

### ISSUE THREAD

**Issue by jakejackson1** [10up/ElasticPress#592]
I just updated to 2.1 and noticed the ElasticPress settings have been moved to a top level menu. While I have no issue with this (the new settings page looks great), I'm not sure why it was decided to position it above Posts in the menu and not below Settings.

**Comment by tlovett1** [comment]
We felt that a plugin that literally transforms the way you receive/store your data merited that high of a position. Of course, happy to change that if people disagree.

**Comment by jakejackson1** [comment]
I've been using it for 6 months now and found once it's been configured there's no reason to continue visiting the settings page (I've been using the CLI to manage indexing ect).

**Comment by mustafauysal** [comment]
I agree with @jakejackson1 , at least a filter would be nice to determine menu position.

**Comment by ekandreas** [comment]
Please don't overestimate the plugins importance. Sorry, but the wp cli interface is much better for this kind of plugin.

**Comment by AaronHolbrook** [comment]
I agree - especially considering there isn't much currently offered at the plugin's page.

What happened to the server status information? I really liked knowing whether or not it was working or not.

**Comment by ekandreas** [comment]
There are also a lot of trouble using the plugin with the cli and then switch to wp ui.

**Comment by hberberoglu** [comment]
I agree - the position should be below Settings.

**Comment by tlovett1** [comment]
We will move the position back to where it was in 2.2. Thanks for the feedback!
