### ISSUE TITLE
Taxonomy query with oddly indexed array will return in invalid query

### ISSUE THREAD

**Issue by jeichorn** [10up/ElasticPress#595]
So I don't have reduced test case for this.  But a query being pushed though the integration created a taxonomy section like:

```
 "filter": {
        "and": [
            {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "terms.product_cat.slug": {
                                    "1": "swedish"
                                }
                            }
                        }
                    ]
                }
            },
```

Patching line 979 to use an array_values will fix this.

```
'terms.' . $single_tax_query['taxonomy'] . '.' . $field => array_values($terms),
```

Likely any case you are passing an array directly through using array_values is a good idea

**Comment by Ritesh-patel** [comment]
Hey @jeichorn 

I am not seeing taxonomy section like you mentioned in my local setup. Which version of EP you are checking with? I tried using `array_values` function but it's not making any difference. 

For me it's as following:
```
"bool": {
    "must": [
        {
            "terms": {
                "terms.category.slug": [
                    "solli"
                ]
            }
        }
    ]
}
```

Can you give the WP query you are using which generated this EP query? Any other relevant information will be great help here.

Regards,
Ritesh

**Comment by Ritesh-patel** [comment]
Hi @jeichorn 

Did you see this?

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
