### ISSUE TITLE
How do I know if EP is over-riding WP Search on the frontend?

### ISSUE THREAD

**Issue by enriqueguardia** [10up/ElasticPress#597]
Rookie question here. I've installed EP and indexed/activated the Search, WooCommerce and Admin sections successfully but how can I make sure ES is over-riding the default wordpress search on my theme?

(BTW: I tried installing WP CLI to no luck so I was wondering if there was a way to check this without CLI)

**Comment by fabioneves** [comment]
There's a way, if you didn't run the index/sync process, you should have 0 results on search. This way you'll know it's running.

**Comment by tlovett1** [comment]
Install the ElasticPress Debug Bar plugin.
