### ISSUE TITLE
Partial matching not quite working. Any ideas on how to improve it?

### ISSUE THREAD

**Issue by fabioneves** [10up/ElasticPress#598]
The partial matching don't entirely work, I'll demonstrate my issue with an example, it's easier:

I have two posts, with the following titles:
- California
- Til Indiana – og California!

If I search for: californ
Results: 0

If I search for: californi
Results: 2

Shouldn't it get a partial on "californ" too? Any way to improve this through filters? I don't know much about Elasticsearch, just started using it now.

Thanks!

**Comment by foadyousefi** [comment]
For partial matching, you can use 'edgeNGram' with 'min_gram' and 'max_gram' configurations:

'min_gram': Minimum number of letters so partial matching starts.
Example: We want to search for my company name "Frontkom", with min_gram of 3, partial match can  match followings:
Fro
Fron
Front
Frontk
Frontko
Then you know max_gran.

```
 $mapping['settings']['analysis']['filter']['edge_ngram'] = [
 	'type'     => 'edgeNGram',
 	'min_gram' => 3,
 	'max_gram' => 12
 ];
	// And here add 'edge_ngram' filter to be able to partial match
 $mapping['settings']['analysis']['analyzer']['default']['filter'][] = 'edge_ngram';
```

Note: By the way, this solution found by Fabio himself. I just added it for others to use.

**Comment by fabioneves** [comment]
That's it! We can also use the 'NGram' filter, which will tokenize the string from any part of it.
