### ISSUE TITLE
Search Fields removed by "Improved Search"

### ISSUE THREAD

**Issue by ekandreas** [10up/ElasticPress#599]
In the file modules/search/search.php at line 68 it reads:
```
add_action( 'pre_get_posts', 'ep_improve_default_search', 10, 1 );
```
That is a filter that "destroys" the search fields parameters in ElasticPress.
Please modify it so it's possible to make advanced search with meta fields, thanks!

The workaround to get ElasticPress to work normal again is to make the following action removal:
```
add_action( 'pre_get_posts', function(){
	remove_action( 'pre_get_posts', 'ep_improve_default_search' );
});
```

**Comment by Ritesh-patel** [comment]
Hi @ekandreas 

Does it happen on standard WordPress' search page or custom WP_Query? If WP_Query, can you give us parameters you are using with WP_Query to get posts?

**Comment by ekandreas** [comment]
It's a custom WP_Query. Just try a query with a search_field set to something and you will notice the issue.
```
$args=[
    's' => 'test',
    'search_fields' => [
        'my_custom_test_field1',
        'my_custom-test_field2',
        'my_custom-test_field3',
    ],
    'post_type' => 'post',
    'paged' => 1,
    'posts_per_page' => 20,
];

$query = new WP_Query($args);
```
