### ISSUE TITLE
If indexing via WPCLI fails the admin gui is locked with the WPCLI in syncing message

### ISSUE THREAD

**Issue by ivanlopez** [10up/ElasticPress#602]
Today while indexing a large site I had WPCLI time out. When I went to the GUI to try and index from there the GUI was disabled with the WPCLI is syncing message. I was able to get around it by opening up the chrome inspector. I'm thinking we need to implement a try catch so that if anything goes wrong while indexing via WPCLI the admin GUI does not get locked down.

**Comment by tlovett1** [comment]
Hmmm, maybe we need a manual override button for that dashboard warning.

**Comment by Ritesh-patel** [comment]
We can add that button in CLI sync message.
**_"WP CLI sync is occuring. Refresh the page to see if it's finished. Click here to proceed anyway."_**

**Comment by tlovett1** [comment]
Is there anyway to detect a WP-CLI error or timeout?

**Comment by Ritesh-patel** [comment]
As @brandwaffle  suggested, we can use transient to fix this.
So, we will set transient for 15 mins of lifetime while wp-cli is indexing. If there is any error or time out it will automatically invalid after 15 mins and we can use Dashboard. Only thing we need to take care of is to keep transient active while indexing is in progress.

**Comment by Ritesh-patel** [comment]
@tlovett1 #611 fixes this using transient.
