### ISSUE TITLE
Admin integration doesn't actually work when searching

### ISSUE THREAD

**Issue by cmmarslender** [10up/ElasticPress#606]
When integrating with the admin, if the search box is used, results that are returned don't take the search query into consideration.

The admin module integrates the admin by setting `ep_integrate` to true. If you look here, we never pay any attention to the `s` param of the query if `ep_integrate` is not empty https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1496

I think ideally, the logic in the `class-ep-api.php` file should be fixed, but I was able to make admin search results work by doing the following in the admin module:
Previously, we would just do this: `$query->set( 'ep_integrate', true );`

I was able to make search work by changing both instances of that to this:

```
if ( $query->is_search() ) {
    add_filter( 'ep_admin_wp_query_integration', '__return_true' );
} else {
    $query->set( 'ep_integrate', true );
}
```

In `class-ep-api.php` - do we really want to _not_ filter the query based on the value of `s` if both `ep_integrate` and `s` have values? I can't think of a scenario when `ep_integrate` is set that we would want to ignore the `s` parameter.

**Comment by nicoladj77** [comment]
This is true also for any front end search. This breaks any compatibility with older versions of the plugin, where activating EP required to set `ep_integrate` to true. Discussed this with @dkotter

**Comment by Ritesh-patel** [comment]
@tlovett1 as @cmmarslender suggested, I don't see any harm by replacing `if ( ! empty( $args['s'] ) && empty( $args['ep_match_all'] ) && empty( $args['ep_integrate'] ) )` with `if ( ! empty( $args['s'] ) )` at https://github.com/10up/ElasticPress/blob/2.1.1/classes/class-ep-api.php#L1474. I think if search term is set than it shouldn't matter if `ep_integrate` is set or not.

**Comment by tlovett1** [comment]
I'm fine with using `s` if `s` AND `ep_integrate` are set. This is definitely a backwards compat break that we'd have to note. Does that solve the problem @cmmarslender?

**Comment by tlovett1** [comment]
@cmmarslender ^

**Comment by cmmarslender** [comment]
@tlovett1 I'm confused by what you are suggesting :)

Can someone make up a PR so I can see the suggested changes, and I'll test based on that?

**Comment by Ritesh-patel** [comment]
@cmmarslender see #622

**Comment by cmmarslender** [comment]
Looks good to me.
