### ISSUE TITLE
Related Posts module's queries not integrated with EP

### ISSUE THREAD

**Issue by charlesLF** [10up/ElasticPress#607]
Hello,

I am currently using the master branch, so my apologies if this was fixed in a different branch or if it is a known issue.

In `related-posts.php`, in function `ep_find_related`, the `$args` array does not contain `ep_integrate`, and includes an empty query in the `s` field.

When the `ep_elasticpress_enabled` filter is applied and the `ep_integrate_search_queries` function is called, `$enabled` will evaluate to false.
That is because on line 230, `! empty( $query->query_vars['s'] )` is false.
(https://github.com/10up/ElasticPress/blob/develop/modules/search/search.php#L230)

I have got it working locally by hooking into the `ep_find_related_args` filter and setting `ep_integrate` to true, but I believe this ought to be patched in the plugin too?

Thanks!

**Comment by Ritesh-patel** [comment]
Hi @charlesLF 

I am not sure what exactly issue here because I can see related posts is working fine with master branch that related posts are loading from Elasticsearch.

**Comment by charlesLF** [comment]
Hello @Ritesh-patel,

If you enable the module, you will see "related posts" at the bottom of the post content, but these are not fetched from Elasticsearch at all.
You can monitor the api calls being made to ES and you'll see that nothing is being sent for the "more_like" ES query.

The reason behind this is what I have outlined above, and it boils down to how `ep_elasticpress_enabled` is set to true or false in `class-ep-api.php`:  https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1701

```
	public function elasticpress_enabled( $query ) {
		$enabled = false;
		if ( ! empty( $query->query_vars['ep_match_all'] ) ) { // ep_match_all is supported for legacy reasons
			$enabled = true;
		} elseif ( ! empty( $query->query_vars['ep_integrate'] ) ) {
			$enabled = true;
		}
		return apply_filters( 'ep_elasticpress_enabled', $enabled, $query );
	}
```

So by default, elasticpress is not enabled unless the query_var `ep_integrate` is set to true.

Now we go to `search.php`, and look at the filter applied to `ep_elasticpress_enabled`: https://github.com/10up/ElasticPress/blob/develop/modules/search/search.php#L227

```
function ep_integrate_search_queries( $enabled, $query ) {
	if ( isset( $query->query_vars['ep_integrate'] ) && false === $query->query_vars['ep_integrate'] ) {
		$enabled = false;
	} else if ( method_exists( $query, 'is_search' ) && $query->is_search() && ! empty( $query->query_vars['s'] ) ) {
		$enabled = true;
	}
	return $enabled;
}
```

So this filter adds a new rule, and that's if the query is a search and `query_var['s']` is not empty, then elasticpress is enabled for that query.


For the "related posts" query, here's what's being set: 

```
function ep_find_related( $post_id, $return = 4 ) {
	$args = array(
		'more_like'		 => $post_id,
		'posts_per_page' => $return,
		's'				 => ''
	);
	$query = new WP_Query( apply_filters( 'ep_find_related_args', $args ) );
	if ( ! $query->have_posts() ) {
		return false;
	}
	return $query->posts;
}
```

As you can see:

1. ep_integrate is not set, so by default this means it's "false"
2. the query arg `s` is empty, so the `ep_integrate_search_queries` will evaluate to false
3. The end result is that `elasticpress_enabled` is false, and this query gets sent directly to the normal WP_Query without ElasticPress integration.

Am I missing something in here?

**Comment by Ritesh-patel** [comment]
Hi @charlesLF 

Thanks for the detailed explanation, I manage to reproduce the issue (I had search module enable previously) and you are right, just by adding `'ep_integrate' => true` in the `$args` can fix the issue.
