### ISSUE TITLE
WP CLI WooCommerce product creation bug

### ISSUE THREAD

**Issue by dsgnr** [10up/ElasticPress#608]
Just started using this plugin with a local development VM for a large Woocommerce site I am developing. 

I am importing around 2000 products using a small script to import products using WP CLI. When the Elasticpress plugin is activated, I am getting this response for each product.

`PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 466
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 466
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 484
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 484
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 485
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 485
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 486
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 486
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 487
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 487
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 488
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 488
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 489
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 489
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 490
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 490
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 491
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 491
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 518
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 518
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 519
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 519
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 520
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 520
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 521
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 521
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 524
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 524
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 525
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 525
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 526
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 526
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 586
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 586
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 606
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 606
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 606
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 606
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 664
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 664
    PHP Notice:  Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 535
    Notice: Trying to get property of non-object in /var/www/domain.local/lib/plugins/elasticpress/classes/class-ep-api.php on line 535`

This doesn't occur when the plugin is deactivated. I can confirm that no products are added either.

**Comment by Ritesh-patel** [comment]
Hi @dsgnr 

I suspect this is because no products are getting added in importing process and looking at the code at given lines from error log, it is expecting a post object which is empty or null I guess. Can you get us debug backtrace info using `debug_backtrace` function so that we can fix this in EP if there is any?

**Comment by Ritesh-patel** [comment]
Hi @dsgnr 

Have you checked this?

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
