### ISSUE TITLE
WooCommerce Module in admin

### ISSUE THREAD

**Issue by danielhuesken** [10up/ElasticPress#609]
Why is the WooCommerce module active in Admin when the Admin module is not active.

Also i think it is better to have a WooCommerce Module that handle only products and variation in frontend. And not indexing the complete order data.

**Comment by dnaber-de** [comment]
From the filter names, one could easily deactivate query integration in admin:

```
apply_filters( 'ep_admin_wp_query_integration', '_return_false' );
```

This would prevent the _search_ module from being active in the admin interface. The _WooCommerce_ module, however, undermine this by hooking into `pre_get_posts` and set the query variable `ep_integrate` to true on admin main queries. That leads `EP_WP_Query_Integration` to act on admin queries as `ep_elasticpress_enabled() (which is actually a wrapper for `EP_API::elasticpress_enabled()`) returns `true` for any query even in admin. 

This could either be prevented with by filtering `ep_elasticpress_enabled` or `ep_skip_query_integration`. I would prefer the second option as it's not clear what the first one disables beside the query integration:

```php
if ( is_admin() ) {
    apply_filters( 'ep_admin_wp_query_integration', '_return_false' );
    apply_filters( 'ep_skip_query_integration', '_return_true' );
}
```

**Comment by Ritesh-patel** [comment]
Hi @danielhuesken @dnaber-de 

Which version of EP you are using? If you are not using latest, can you check with the current develop branch?

**Comment by dnaber-de** [comment]
We're using EP 2.1.1. The current state of the develop branch don't change anything of the described behavior. https://github.com/10up/ElasticPress/compare/2.1.1...develop

**Comment by tlovett1** [comment]
Hey guys, so the WooCommerce module is independent from the admin module. I realize this is unexpected. I'm open to suggestions here. Perhaps, it makes sense to rename the admin module.

**Comment by dnaber-de** [comment]
I think, «admin» is not a real module domain. There's «search» as well as «woocommerce». Both are domains that acts independent of the «interface» to WP you're working with (REST, theme, wp-admin, AJAX). So I think the best way should be to resolve the «admin» module and keep the filter `ep_admin_wp_query_integration` as a public API to adapt the behavior of the complete plugin (including each module). It could be implemented in the module loading process, maybe with an additional parameter that passes the current module to the callback so a user could either deactivate all modules in wp-admin or just some specific ones.

**Comment by tlovett1** [comment]
Appreciate the discussion. One thign to remember is the `admin` feature actually contains functionality that stands apart from other features - integrating EP into posts tables. This is why I'm saying it might just make sense to rename admin to `Posts Table`. Then admin search would be bundled into search, admin WC into WC, etc.

**Comment by dnaber-de** [comment]
Yes, «Post Table» seems to be a legit name for that module.
