### ISSUE TITLE
Undefined variable ep_query when using the 'ep_wp_query_search_cached_posts' filter

### ISSUE THREAD

**Issue by jvolfson** [10up/ElasticPress#616]
When using the 'ep_wp_query_search_cached_posts' filter, if it returns a non empty response, $ep_query is never set and as a result line 303 generates a PHP warning indicating so. 

Notice:  Undefined variable: ep_query in ....../plugins/elasticpress/classes/class-ep-wp-query-integration.php on line 303

**Comment by jvolfson** [comment]
https://github.com/10up/ElasticPress/pull/617

**Comment by Ritesh-patel** [comment]
@jvolfson you can also set default value of `$ep_query` to empty array before `if( count( $new_posts ) < 1 )` statement at line 220. This way any future reference to $ep_query will have a default value.

**Comment by Ritesh-patel** [comment]
@tlovett1 this issue can be closed as the PR has been merged.
