### ISSUE TITLE
Respect actuall indexed post types in Woocommerce module (ep_wc_translate_args)

### ISSUE THREAD

**Issue by dnaber-de** [10up/ElasticPress#621]
The function `ep_wc_translate_args()` [assumes](https://github.com/10up/ElasticPress/blob/d1f8ffcbb2bb95f78ffaad2a208ac798ab3b63f9/modules/woocommerce/woocommerce.php#L291) that the post types `shop_order`, `shop_order_refund`, `product` and `product_variations` are always be indexed. It would be nice to apply the `ep_indexable_post_types` filter here in order to be compatible to possible changes from third-party code.

**Update** A even better solution would be to ask for `ep_get_indexable_post_types()`.

**Comment by allan23** [comment]
Hi @dnaber-de,

Thank you for reporting this issue and submitting a PR for it.

**Comment by dnaber-de** [comment]
You're welcome.
