### ISSUE TITLE
How to index if a plugin has its own tables?

### ISSUE THREAD

**Issue by aakal** [10up/ElasticPress#624]
Hi,

In one of the projects I have been building, I have a Q&A plugin called "sabai" which uses its own tables to store questions and answers; it doesn't use custom post types. 

Now, currently Elasticpress cannot index the questions and answers but is there a way to make it index even if the data is stored on the plugin's own tables? If so, could you show me an example, I'll appreciate it! Thanks!

**Comment by tlovett1** [comment]
Hey, this is possible but require extensive usage of the EP developer API. I don't have any examples. Sorry!

**Comment by mattonomics** [comment]
The best example, IMO, is in the plugin itself. You can take a look at the mapping here: `https://github.com/10up/ElasticPress/blob/develop/includes/mappings/5-0.php` That will show how db fields were mapped to ES and should get you on your way to creating a fully custom mapping. Hope that helps a little!

**Comment by Ritesh-patel** [comment]
Hi @aakal 

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
