### ISSUE TITLE
2.1.2 Hotfix Testing

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#627]
Can everyone please test the hotfix-es-50 branch?

**Comment by Ritesh-patel** [comment]
Working fine with Elasticsearch 2.3.5

**Comment by tlovett1** [comment]
Looking for feedback on @alijmlzd on 5.0+

**Comment by Ritesh-patel** [comment]
@tlovett1 I found following issues while testing with Elasticsearch 5.0

This error is while WooCommerce module is active and tried indexing:
```
java.lang.IllegalArgumentException: mapper [meta._wc_average_rating.double] cannot be changed from type [float] to [long]
```

This error is while testing default search:
```
{
    "type": "parsing_exception",
    "reason": "field [post_date_gmt] is of type [indexed,tokenized], but only numeric types are supported.",
    "line": 1,
    "col": 1
}
```

**Comment by tlovett1** [comment]
@Ritesh-patel can you trace it down?

**Comment by tlovett1** [comment]
Actually, please test my latest change. I might have figured it out.

**Comment by Ritesh-patel** [comment]
@tlovett1 yes, with latest change it's working fine now.
