### ISSUE TITLE
Wrong page number in search result

### ISSUE THREAD

**Issue by resimovic** [10up/ElasticPress#628]
Hi, 
I have about 60000 posts in db, I have noticed some problems with plugin:
When returning results in pager on search page results, shown number (1 of 2356) real number is much much smaller - 1 or maybe two pages not so many, and take long time to switch to another page (like start search from begin).

**Comment by kersten** [comment]
Hi,

i think my problem is nearly the same, but without search.

My problem is, if I display a category or subcategory page the product list shows the e.g. correct products, but the paginator and result set displays many more, how can I fix that?

For better explanation, I've attached a screenshot.

Thanks for help

![image](https://cloud.githubusercontent.com/assets/487289/20227019/cb70d11c-a84a-11e6-96fc-d216a63ef2f2.png)

**Comment by allan23** [comment]
Hi @resimovic,

Can you let us know what theme or pagination code is used to display page numbers?

**Comment by Ritesh-patel** [comment]
Hi @resimovic and @kersten  

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
