### ISSUE TITLE
Indexed posts contain HTML tags

### ISSUE THREAD

**Issue by resimovic** [10up/ElasticPress#629]
Hi,
Indexed posts contain HTML tags which is not striped so if I search word "class" I will get all posts in search result.

**Comment by wkw** [comment]
I discovered that too while implementing match highlights. Spent a little time trying to adjust the mapping to strip html but didn't get it working yet. Bailed on it for the now since client isn't demanding it yet. I suppose an alternative would be to use php to strip the html through a post indexing filter. possibly here `ep_post_sync_args_post_prepare_meta`.

**Comment by allan23** [comment]
Hi @resimovic and @wkw,
Thank you for bringing this to our attention.

Can you provide us an example of content you are indexing that contains the HTML tags?

**Comment by Ritesh-patel** [comment]
Hi @resimovic and @wkw  

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh

**Comment by madrid1979** [comment]
This is still an issue.

**Comment by tlovett1** [comment]
Not sure how this would be happening: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L564

**Comment by madrid1979** [comment]
I'm curious if that commit (@tlovett1) addresses custom content type queries, or only posts.

**Comment by tlovett1** [comment]
Just posts.

**Comment by madrid1979** [comment]
How would you recommend preparing other custom content types?

**Comment by madrid1979** [comment]
Any update on this?

**Comment by wkw** [comment]
@madrid1979 you could do something like this:

```
function prepare_text_content( $content ) {
  $content = strip_tags( $content );
  $content = preg_replace( '#[\n\r]+#s', ' ', $content );

  return $content;
}
function ep_post_sync_args_filter($post_args, $post_id) {
  if ($post_args['post_type'] == 'YOUR_TYPE') {
    $post_args['post_content'] = prepare_text_content($post_args['post_content']);
  }

  return $post_args;
}

add_filter( 'ep_post_sync_args', 'ep_post_sync_args_filter', 10, 2);
```
You can replace `YOUR_TYPE` with your CPT name, or just run every type through this (remove the conditional).

**Comment by madrid1979** [comment]
That did the trick, thank you @wkw
