### ISSUE TITLE
 Posts are not sorted by relevance

### ISSUE THREAD

**Issue by resimovic** [10up/ElasticPress#630]
Hi,
Post in search result not ordered by relevance, Post title is not included in relevance calculation, For example I have post vith title "div" in search result is on 10th place, first in is "Plovdiv"

**Comment by allan23** [comment]
Hi @resimovic,
Are you specifying an order_by in your query?

**Comment by Ritesh-patel** [comment]
Hi @resimovic  

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
