### ISSUE TITLE
Problem with aggregations

### ISSUE THREAD

**Issue by charlesLF** [10up/ElasticPress#634]
I believe there's a bug in the aggregation implementation.
https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1682

I wonder if the above line should be changed to:
```
$formatted_args['aggs'][ $agg_name ] = $agg_obj['aggs'];
```

You will need to have `use-filter` set to `false` and have a custom aggregation name in order to replicate this bug.

Also, is the information in the wiki (in terms of the aggs parameters) outdated: https://github.com/10up/ElasticPress/wiki/Working-with-Aggregations ?

**Comment by Ritesh-patel** [comment]
Thanks @charlesLF for reporting it and thanks @lukaspawlik for the PR. 
@tlovett1 #635 can be merged.
