### ISSUE TITLE
Call to undefined method EP_Feature::dependencies_met()

### ISSUE THREAD

**Issue by lukaspawlik** [10up/ElasticPress#644]
When I tried to execute

```
wp elasticpress activate-feature search
```

I got error as follows:

> Fatal error: Uncaught Error: Call to undefined method EP_Feature::dependencies_met() in wp-content/plugins/elasticpress/bin/wp-cli.php:59

**Comment by Ritesh-patel** [comment]
Thanks Lukas for bringing this to our notice and for PR.
