### ISSUE TITLE
Search in multiple indices

### ISSUE THREAD

**Issue by bjorngustafsson** [10up/ElasticPress#646]
Is it possible to search multiple indices in the same search ? I know i can hook into ep_index_name filter and change index, but only to one index. The reason is that im searching from a singlesite but searching on a multisite on another site, but on same server. 

Im thinking im using wp-rest-api to serve the list of all blogs to the single site.

**Comment by Ritesh-patel** [comment]
Hi @bjorngustafsson 

I think you can use `ep_search_request_path` filter and change the path to match multiple index as described in https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-index-multi-type.html

**Comment by bjorngustafsson** [comment]
Oh thanx, great ! i will check up that, i discovered you also could use wildcards (such as * ) in the ep_index_name hook, since all blogs' index start with same url in my case. For example if blogs url are:
blogg.example.com/blog1
blogg.example.com/blog2
etc.
Use:
add_filter( 'ep_index_name', 'custom_index_blog_name', 20, 2 );
function custom_index_blog_name() {
    if( is_search() ) {
        return 'bloggexample*';
    }
}

**Comment by bjorngustafsson** [comment]
Hi, thanx for the response. How does this work in an ajax call? I want my ajax call also to use multiple indices. I have tried to add the code above to my ajax file, but it only returns results from the default index. I have tried adding the hook with different priorities and run apply_filters but with no success.

**Comment by Ritesh-patel** [comment]
I think issue is you are checking with `is_search()`. In ajax request, I don't think is_search will return true. You shouldn't put this code in more than place. Put it in MU plugin or custom plugin or in theme.

**Comment by tlovett1** [comment]
You could create custom aliases. Check out how we search across multiple blogs.

**Comment by marcinkrzeminski** [comment]
Hi,

I'd like to search in multiple indices (posts, terms) within the same query. However, when I use a wildcard in the `ep_index_name` and try to reindex using `wp-cli` I'm getting this error. Any suggestions? 

```php
add_filter( 'ep_index_prefix', function ( $prefix ) {
	return 'prefix';
}, 10, 1 );

add_filter( 'ep_index_name', function ( $name ) {
	return 'prefix*';
}, 10, 1 );
```

```bash
➜ wp elasticpress index --setup
Indexing with setup option needs to delete Elasticsearch index first, are you sure you want to delete your Elasticsearch index? [y/n] y
Adding post mapping...
Error: Mapping failed
```
