### ISSUE TITLE
Related Posts for Woocommerce sites

### ISSUE THREAD

**Issue by consciousimages** [10up/ElasticPress#647]
In 2.1.2, activating 'related posts' for a Woocommerce site (at least the one I'm administering) not only adds related posts to the 'post' post type but also 'products' and even the homepage... 

Also, when there are less than 3 related posts (say there are only 4 blog posts), it pulls up the 'contact us' page, which isn't a post, but a page.

My preference would be either the plugin is only restricted to the 'post' post type out of the box (and only pulls from that post type), or there is a filter or an admin setting to restrict the post types it is activated for.

**Comment by Ritesh-patel** [comment]
Hi @consciousimages 

You can use `ep_find_related_args` filter to pass post_type. Let us know if that helps or not.

Regards,
Ritesh

**Comment by tlovett1** [comment]
Also, this will be a widget only in 2.2.
