### ISSUE TITLE
Number of total results ignoring post_type?

### ISSUE THREAD

**Issue by yannp** [10up/ElasticPress#649]
Hi,

I'm encountering an issue when trying to get the number of total results.
I'm querying like this:
```
$args = array(
  'ep_integrate'   => true,
  'post_type' => 'recipe',
  'posts_per_page' => 8,
  's' => "chocolate",
);
get_posts($args);
```
This works fine, I get the first 8 recipes matching "chocolate", the most relevant ones. But now I would like to know how many total results there are. I've seen the `ep_search_results_array` and setup the callback like this:
```
public function my_ep_search_results_array( $results, $response, $args, $scope ) {
      $this->last_query_count = $results['found_posts'];
      return $results;
    }
```
I store the number of `found_posts` in `last_query_count` for further use.
Now, what's happening is that this `found_posts` seems to contain the number of posts matching the query but ignoring the `post_type` filter I setup in my query. Let's say there are 100 posts containing the word "chocolate" but only 20 post_type "recipe" containing the word "chocolate", currently `$results['found_posts']` returns 100 instead of 20.

Thanks for your help

**Comment by Ritesh-patel** [comment]
Hi @yannp 

Thanks for the detailed report. Which version of ElasticPress and Elasticsearch you are using? I am not able to reproduce this.

Regards,
Ritesh

**Comment by yannp** [comment]
I have ElasticPress 2.1 and Elasticsearch 1.7.

**Comment by Ritesh-patel** [comment]
Can you check it with latest version of ElasticPress and Elasticsearch in your dev environment?

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
