### ISSUE TITLE
Cant sync new or edit existing posts

### ISSUE THREAD

**Issue by bjorngustafsson** [10up/ElasticPress#650]
Hi! 

Im having problems with syncing new posts or edit old posts. When i save my new post or edit the title of an old one and then click the sync button it looks like like it syncs all my posts fine. But if i search or check the index in the terminal, the post title for example is not updated. I have also tried using the ep_post_sync_args hook but without success with for example:

```
add_filter( 'ep_post_sync_args', 'sync_search_fields', 10, 2 );
function sync_search_fields( $post_args, $post_id ) {
    ...
    $post_args['post_title'] = get_the_title($post_id);
    return $post_args;
}  
```
If i click the sync button, it says syncing 2900 posts. I then add another post, click sync again, and it says syncing 2901 posts. Im running in terminal
curl 'localhost:9200/*myblog*/_search?q=mynewposttitle&pretty'
gets zero results, but 
curl 'localhost:9200/*myblog*/_search?q=myexistingposttitle&pretty'
gets one result so posts that existed when i installed elasticsearch is working fine.

I have other sites that can successfully update index, but not this one.

**Comment by Ritesh-patel** [comment]
Hi @bjorngustafsson 

If issue is for one particular site only than I suggest to check it with WordPress default theme and with other plugins disabled except ElasticPress. I think this might be a theme or plugin conflict.

Regards,
Ritesh

**Comment by bjorngustafsson** [comment]
I think this is what caused it :

add_filter( 'ep_index_name', 'custom_index_blog_name', 20);
function custom_index_blog_name() {
    if( is_search() ) {
        return '*partofmanyindexiwanttosearchin*';
    }
}

Thanks !
