### ISSUE TITLE
Plugin ignores search parameters and doesn't behave as advertised

### ISSUE THREAD

**Issue by aoodham** [10up/ElasticPress#653]
We have an elastic search server hosted on AWS, which I am using as the backend for this plugin. However, my experiments have shown that at present it is not behaving:

1) Unless the 'ep_integrate' = true parameter is specifically set for the WP_Query then elastic search will not integrate with the query (contrary to the advertised behaviour in the docs)
2) Unfortunately, when elastic search does integrate with the query it ignores search terms passed to it. 

I can confirm both of these by running a packet capture whilst trying to use the plugin. When I observe the correct behaviour (with ep_integrate not set) no packets are sent to the remote elastic search server => just using the local MySQL search, when I set ep_integrate I can see the packets going to the remote server, but I can also see the search query has no mention of my search term (see extract below)

`{"from":0,"size":10,"sort":[{"_score":{"order":"desc"}}],"query":{"match_all":{"boost":1}},"post_filter":{"bool":{"must":[{"term":{"post_type.raw":"page"}},{"term":{"post_status":"publish"}}]}}}`

It has correctly picked up that I wish to search post_type = page, but my search query of s = "price" is not included.

**Comment by Ritesh-patel** [comment]
Hi @aoodham 

So you are using admin module only. Can you please debug it once with [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/l) plugin? Can you tell me for which admin pages you are facing this issue?

Regards,
Ritesh

**Comment by aoodham** [comment]
Hi Ritesh,

Yes, it seems the search is failing when I use an ajax request targeting the admin-ajax.php (which I thought was the "correct" way to trigger ajax requests in wordpress?). I've switched to using a REST-API plugin to provide a search endpoint and then the elasticpress plugin functions as expected. 

Under both conditions (ep_integrate set and not set) when using the admin-ajax method for running the search I see the behaviour as above, the elasticpress debug bar offers no insight, claiming no searches have happened in either case.

Alex

**Comment by tlovett1** [comment]
Which features do you have active? Without the "admin" feature active, no integration will happen on admin-ajax.php since that is within the admin.

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
