### ISSUE TITLE
Stop_the_insanity method is not compatible with WP 4.7.

### ISSUE THREAD

**Issue by nicholasio** [10up/ElasticPress#654]
Part of the code inside the stop_the_insanity method (https://github.com/10up/ElasticPress/blob/develop/bin/wp-cli.php#L806) will throw an error on WordPress 4.7 due to changes in the hook system. See more details here: https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/

**Comment by tlovett1** [comment]
Mind creating a quick PR?

**Comment by nicholasio** [comment]
@tlovett1 Sure. I'm wrapping up a PR for MU-Migration to solve the same issue and I'll submit PR here.

**Comment by tlovett1** [comment]
@nicholasio any update?
