### ISSUE TITLE
Visiting post edit page inits "_edit_lock", which then causes syncing of post

### ISSUE THREAD

**Issue by aschmoe** [10up/ElasticPress#655]
Entire meta_update hook process fires after setting the lock value, which ultimately causes the entire post to be built and synced.

Seems like unnecessary overhead for this particular meta change.  Think some action or filter could be introduced (or does one exist I'm missing) to cancel sync? 

Thanks!

**Comment by Ritesh-patel** [comment]
Hi @aschmoe 

I am not able to reproduce it with current develop branch. Which version of EP you are using?

Regards,
Ritesh

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
