### ISSUE TITLE
No Pages Found on WP Pages section?

### ISSUE THREAD

**Issue by Lovecannon** [10up/ElasticPress#657]
Hello, I have had an issue with ElasticPress on two different multi-site installs. ElasticPress seems to work well in every regard but when it is enabled the Pages section of Wordpress will not show any pages. Any idea what could be causing this? I really like how much faster searching is with ElasticPress and I'd like to be able to use it.

Here is a screenshot of what I am talking about:

![pages nidy sports wordpress](https://cloud.githubusercontent.com/assets/13548078/21144141/8f601062-c117-11e6-8fbe-27a8c41c381c.png)

**Comment by Ritesh-patel** [comment]
Hello,

Can you check with https://wordpress.org/plugins/debug-bar-elasticpress/ plugin and see request/response from Elastcisearch. Also, can you perform reindex?

Regards,
Ritesh

**Comment by tlovett1** [comment]
I'm not able to reproduce.

**Comment by Ritesh-patel** [comment]
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh

**Comment by marcocanestrari** [comment]
Hi,
I've the same issue, with pages and attachments when performing a search.
All items are indexed and:
- for pages, the response seen with the debug bar has actually the pages list
- for attachment, no results, even if the index is fine

Thanks!
