### ISSUE TITLE
WP_Terms_Query Support

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#658]
Feature request to integrate `WP_Terms_Query` with ElasticPress.

**Comment by tlovett1** [comment]
@ivankristianto working on this

**Comment by kallehauge** [comment]
Just out of curiosity. How far is this @ivankruchkoff ?

**Comment by lougreenwood** [comment]
I suppose this duplicates #257 ?

**Comment by tlovett1** [comment]
See https://github.com/10up/ElasticPress/pull/1443
