### ISSUE TITLE
Intelligent POST size / Elasticsearch Memory limit detection

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#66]
Originally reported in #62:

> we'll need to be aware of the max post size on the server and the max amount of data elasticsearch/java can receive.

This isn't a critical priority - but it would be a really nice thing to have. Ideally our plugin would intelligently detect (and cache it's findings) how large of a POST request it can get through. Additionally, if possible, detect from Elasticsearch how much memory/size of bulk index would be allowable. Using those values we can set a larger than default bulk index set size to minimize the number of requests it has to perform.

This would be an enhancement not just for minimizing HTTP requests, but would also help prevent issues where WordPress posts have a large amount of data per post (i.e. large meta data fields) that could end up causing the small default value of posts in a bulk index to cause failure.

**Comment by felipeelia** [comment]
Closing this in favor of #2519.
