### ISSUE TITLE
Number of results displayed is wildly inaccurate

### ISSUE THREAD

**Issue by mugwumpr** [10up/ElasticPress#665]
Hello,

On my website, https://edmontonbookstore.com there are 32,194 products, however, with ElasticPress activated it says there are 181,604. Deactivate EP and it goes back to the proper number.

With EP activated:
![image](https://cloud.githubusercontent.com/assets/23413873/21536900/1bee31be-cd46-11e6-82c7-a02b24d38297.png)

Without EP activated:
![image](https://cloud.githubusercontent.com/assets/23413873/21536908/3504a9da-cd46-11e6-9a18-c6b0749ee823.png)

I'm loving how EP has made my site faster, but not so much loving the skewed product count.

Thanks!

Linda

**Comment by Ritesh-patel** [comment]
@mugwumpr 

How many published products you can see in admin dashboard with both ElasticPress disabled and enabled?

**Comment by mugwumpr** [comment]
There are 167,714. I have no idea where the other imaginary products are coming from.

![image](https://cloud.githubusercontent.com/assets/23413873/21625833/e7e111dc-d1ca-11e6-9833-dc69d63403f6.png)

**Comment by tlovett1** [comment]
@mugwumpr feel free to email me (see my profile email). I'd like to help you debug.
