### ISSUE TITLE
Show score on each searchresult

### ISSUE THREAD

**Issue by bjorngustafsson** [10up/ElasticPress#666]
Hi !

Is it possible to show the elasticsearch score on each post in the searchresults page ? I know i can hook in on the `ep_retrieve_raw_response` hook too see the raw response, but i would like to have it in the post objects or if it possible on some other way.

**Comment by Ritesh-patel** [comment]
@bjorngustafsson 

I think you can use `ep_retrieve_the_post` filter using which you can filter out each post. The callback function will have single post and raw data of that single post.

Let us know if that helps.

Regards,
Ritesh

**Comment by bjorngustafsson** [comment]
Thanks! Yes i got the score as you described. I used

add_filter( 'ep_retrieve_the_post', 'ep_retrieve_the_postep_retrieve_the_post', 10, 2 );
function ep_retrieve_the_postep_retrieve_the_post($var1, $var2) {
    var_dump($var2);
    die;
};

Thanks again for a great plugin !
