### ISSUE TITLE
woocommerce short-code not working

### ISSUE THREAD

**Issue by diditho** [10up/ElasticPress#673]
After indexing the commerce section, this woocommerce short-code is not working

[recent_products per_page="4" columns="4"]
[featured_products per_page="4" columns="4"]

but, this short-code is working

[product_categories number="12" parent="0" columns="3"]

Thankyou

**Comment by allan23** [comment]
Hi @diditho,

Thank you for reporting this issue. In order to troubleshoot, can you please let us know what versions of ElasticPress and WooCommerce you are running?

**Comment by diditho** [comment]
Hi @allan23 

I'm using

WooCommerce 2.6.11
ElasticPress 2.1.2

**Comment by allan23** [comment]
Thanks for the information @diditho. We are currently reviewing.

**Comment by ivankristianto** [comment]
Seems like this issue is fixed in ElasticPress 2.2

**Comment by ivankristianto** [comment]
@diditho just want checking in if the 2.2 works for you?

**Comment by diditho** [comment]
just testing 2.2 and it's working fine. Thank You @ivankristianto @allan23
