### ISSUE TITLE
Enabling Admin feature does not enable the ES search on the media library

### ISSUE THREAD

**Issue by j3j5** [10up/ElasticPress#674]
I've been testing with the latest version of  the `develop` branch, and, with the admin feature enabled,  the search for the media library doesn't use ElasticSearch, even though WP internally is using WP_Query. 

After debugging a bit I've found what I think it was wrong. 

There is a check, on the [setup of the search feature](https://github.com/10up/ElasticPress/blob/develop/features/search/search.php#L47) that ensures ElasticPress isn't used when using AJAX requests to the admin. The filter `ep_admin_wp_query_integration` is set [on the admin feature](https://github.com/10up/ElasticPress/blob/develop/features/admin/admin.php#L18) but, on the [plugin class](https://github.com/10up/ElasticPress/blob/develop/elasticpress.php#L59) the search is loaded before the admin, so when the setup is done, the filter from the admin isn't yet set.

Afterwards, there is another check, from the filter `ep_ajax_wp_query_integration` but looking on the plugin's source code, that filter isn't set anywhere. As I understand it, it should be set within the admin's feature setup, [right after the previously mentioned filter](https://github.com/10up/ElasticPress/blob/develop/features/admin/admin.php#L18).

Am I understanding this wrong? If not and this is a bug I can create a PR with these simple fixes. I've been testing for a while and nothing seems to break after applying them.

Thanks for the good work on this plugin!

**Comment by tlovett1** [comment]
Hey @j3j5, hold tight on this one. Internally we are deciding on the scope of this feature and whether it should affect the media library. More info soon!

**Comment by marcocanestrari** [comment]
Yes please!

**Comment by shpetimshala** [comment]
@tlovett1 any news regarding this feature ?

**Comment by tlovett1** [comment]
The Media feature is slated for 2.3.  However, I don't think that will touch media library search. Unfortunately the state of this particular feature is unknown. Happy to consider PRs.

**Comment by svandragt** [comment]
Any update on this? We have a media library with 50k+ images that would really benefit from this.
