### ISSUE TITLE
Querying with ElasticPress for default categories

### ISSUE THREAD

**Issue by aakal** [10up/ElasticPress#675]
Hi guys,

I was wondering if I could use ElasticPress for querying the posts shown on the front end. I'm playing around with the idea of using something like:

`function elasticpress_frontend( $query ) {
    if ( $query->is_category() && $query->is_main_query() ) {
        $query->set( 'ep_integrate', true );
    }
}
add_action( 'pre_get_posts', 'elasticpress_frontend' );`

So that, I can use ElasticPress for much faster rendering of posts on front-end. I'd appreciate some feedback on this. Thanks!

**Comment by tlovett1** [comment]
You could definitely do that. Code looks fine. We do something similar in the WooCommerce feature.

**Comment by aakal** [comment]
@tlovett1 thanks a lot. I'll keep you posted if I come up with something interesting. It seems I'll be using Elasticpress a lot, and I want to help out, so that I can somehow "give back" on such a useful tool.

I read on an issue below that you guys are working on documentation. I can help out with that since I'll be going over the files on the following weeks. You can just tell me if you need any help on that.

I also want to explore the ability to index posts that use their own custom tables. I'll let you know if I come up with something on that. Cheers,
