### ISSUE TITLE
Querying with $wpdb or EP

### ISSUE THREAD

**Issue by aakal** [10up/ElasticPress#676]
Hi
@tlovett1 and everyone else I have a question. Our recent project involves collecting basic user behavior data such as login time and duration, the post cats / subcats which the users have visited, etc. and then taking basic actions such as sending mails, or customizing user feeds based on that collected data.

To accomplish this, I was obviously thinking about a custom table. However, I have used ElasticPress before and I know that it is such a powerful query tool. For our expected user base, I think ElasticPress would produce much more performance than SQL queries. 

So, my question is; for this type of data, should I use a custom table, or create a custom post type such as "user stats", associate that post type with users based on their user id. I'd collect the meta data over this said post type (I don't know if EP can integrate with wp_user_query), and then query using ElasticPress. @tlovett1 I would really appreciate if I can hear your thoughts on this. Thanks!

**Comment by tlovett1** [comment]
@aakal have you used Stream by XWP?

**Comment by aakal** [comment]
Just checked it out very quickly, really cool stuff, and it seems they have done it all with custom posts. Both alerts and logs are kept as custom posts from what I've seen.

The question I have for you is (and I know you're the right person to answer this, you are a Wordpress core contributor :) ), does this not add an immense weight and bog down the posts / postmet tables? 

Because if you think that by querying with EP it won't be a problem, it's much much easier to use custom posts.

I am really looking forward for your feedback on this one.

**Comment by tlovett1** [comment]
Querying with EP will not be a problem.
