### ISSUE TITLE
Page admin shows no pages when admin module activated.

### ISSUE THREAD

**Issue by teddarling** [10up/ElasticPress#677]
I'm reporting this on a fresh install with 2017 theme and only ElasticPress installed.

When the admin module is deactivated, I see the list of pages on the site (See first image)

<img width="849" alt="screen shot 2017-01-15 at 3 17 39 pm" src="https://cloud.githubusercontent.com/assets/3044359/21966252/d2aa66dc-db35-11e6-8629-83fe68c9e75d.png">

Upon activating the admin module, I see that it reports 2 pages "All (2)" and "Published (2)" but "no pages found" listed as in the next screen shot:

<img width="840" alt="screen shot 2017-01-15 at 3 19 27 pm" src="https://cloud.githubusercontent.com/assets/3044359/21966268/2c8f3614-db36-11e6-8d5b-ea28bc1ab43a.png">

Expected behavior is to see the list of available pages for editing, viewing, etc... as in the first screenshot. I setup on a fresh install as I was noticing this on other sites that I was trying to install the plugin on.

If it helps, tested on Cloudways hosting with Varnish on and off, re-sync and still the same issue. PHP memory limit 256MB (tested originally at 32MB).

**Comment by tlovett1** [comment]
What version of EP?

**Comment by ekandreas** [comment]
Workaround is making a index command `wp elasticpress index`and pages are back. This has bothering me for some month now and occurs after a whole indexing with the setup flag sometimes.

**Comment by teddarling** [comment]
@tlovett1 

plugin version: 2.1.2
WP: 4.7.1

@ekandreas 
I did do a run of `wp elasticpress index` with no change as well as deleting the index and trying again.

Host is Cloudways if that makes any difference (I've had other plugins break due to NGINX to Varnish to Apache). But again, I have tried with Varnish enabled and disabled.

Also if it helps, I've installed the EP Debug Bar which provides the following output (some data replaced for security reasons with xxxxx):


TOTAL ELASTICPRESS QUERIES:
1
TOTAL BLOCKING ELASTICPRESS QUERY TIME:
9 ms
Host: http://xxxxx:9200
Time Taken: 9 ms
URL: http://xxxxx:9200/wordpress2540054247195413cloudwaysappscom-1/post/_search
Method: POST
Query Args: 
array(67) {
  ["order"]=>
  string(3) "ASC"
  ["orderby"]=>
  string(16) "menu_order title"
  ["posts_per_page"]=>
  int(-1)
  ["posts_per_archive_page"]=>
  int(-1)
  ["post_type"]=>
  string(4) "page"
  ["fields"]=>
  string(10) "id=>parent"
  ["error"]=>
  string(0) ""
  ["m"]=>
  string(0) ""
  ["p"]=>
  int(0)
  ["post_parent"]=>
  string(0) ""
  ["subpost"]=>
  string(0) ""
  ["subpost_id"]=>
  string(0) ""
  ["attachment"]=>
  string(0) ""
  ["attachment_id"]=>
  int(0)
  ["name"]=>
  string(0) ""
  ["static"]=>
  string(0) ""
  ["pagename"]=>
  string(0) ""
  ["page_id"]=>
  int(0)
  ["second"]=>
  string(0) ""
  ["minute"]=>
  string(0) ""
  ["hour"]=>
  string(0) ""
  ["day"]=>
  int(0)
  ["monthnum"]=>
  int(0)
  ["year"]=>
  int(0)
  ["w"]=>
  int(0)
  ["category_name"]=>
  string(0) ""
  ["tag"]=>
  string(0) ""
  ["cat"]=>
  string(0) ""
  ["tag_id"]=>
  string(0) ""
  ["author"]=>
  string(0) ""
  ["author_name"]=>
  string(0) ""
  ["feed"]=>
  string(0) ""
  ["tb"]=>
  string(0) ""
  ["paged"]=>
  int(0)
  ["meta_key"]=>
  string(0) ""
  ["meta_value"]=>
  string(0) ""
  ["preview"]=>
  string(0) ""
  ["s"]=>
  string(0) ""
  ["sentence"]=>
  string(0) ""
  ["title"]=>
  string(0) ""
  ["menu_order"]=>
  string(0) ""
  ["embed"]=>
  string(0) ""
  ["category__in"]=>
  array(0) {
  }
  ["category__not_in"]=>
  array(0) {
  }
  ["category__and"]=>
  array(0) {
  }
  ["post__in"]=>
  array(0) {
  }
  ["post__not_in"]=>
  array(0) {
  }
  ["post_name__in"]=>
  array(0) {
  }
  ["tag__in"]=>
  array(0) {
  }
  ["tag__not_in"]=>
  array(0) {
  }
  ["tag__and"]=>
  array(0) {
  }
  ["tag_slug__in"]=>
  array(0) {
  }
  ["tag_slug__and"]=>
  array(0) {
  }
  ["post_parent__in"]=>
  array(0) {
  }
  ["post_parent__not_in"]=>
  array(0) {
  }
  ["author__in"]=>
  array(0) {
  }
  ["author__not_in"]=>
  array(0) {
  }
  ["ep_integrate"]=>
  bool(true)
  ["ignore_sticky_posts"]=>
  bool(false)
  ["suppress_filters"]=>
  bool(false)
  ["cache_results"]=>
  bool(true)
  ["update_post_term_cache"]=>
  bool(true)
  ["lazy_load_term_meta"]=>
  bool(true)
  ["update_post_meta_cache"]=>
  bool(true)
  ["nopaging"]=>
  bool(true)
  ["comments_per_page"]=>
  string(2) "50"
  ["no_found_rows"]=>
  bool(false)
}
Query Body: 
{
    "from": 0,
    "size": 10000,
    "sort": [
        {
            "menu_order": {
                "order": "asc"
            }
        },
        {
            "post_title.sortable": {
                "order": "asc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "term": {
                        "post_type.raw": "page"
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    }
}
Query Response Code: HTTP 200
Query Result: 
{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 2,
        "max_score": null,
        "hits": [
            {
                "_index": "wordpress2540054247195413cloudwaysappscom-1",
                "_type": "post",
                "_id": "92",
                "_score": null,
                "_source": {
                    "post_id": 92,
                    "ID": 92,
                    "post_author": {
                        "raw": "xxxxx",
                        "login": "xxxxx",
                        "display_name": "Ted",
                        "id": 1
                    },
                    "post_date": "2017-01-15 11:30:53",
                    "post_date_gmt": "2017-01-15 19:30:53",
                    "post_title": "Test",
                    "post_excerpt": "",
                    "post_content": "<p>Testing</p>n",
                    "post_status": "publish",
                    "post_name": "test",
                    "post_modified": "2017-01-15 11:31:03",
                    "post_modified_gmt": "2017-01-15 19:31:03",
                    "post_parent": 0,
                    "post_type": "page",
                    "post_mime_type": "",
                    "permalink": "http://wordpress-25400-54247-195413.cloudwaysapps.com/test/",
                    "terms": [],
                    "post_meta": [],
                    "date_terms": {
                        "year": 2017,
                        "month": 1,
                        "week": 2,
                        "dayofyear": 14,
                        "day": 15,
                        "dayofweek": 0,
                        "dayofweek_iso": 7,
                        "hour": 11,
                        "minute": 30,
                        "second": 53,
                        "m": 201701
                    },
                    "comment_count": 0,
                    "comment_status": 0,
                    "ping_status": 0,
                    "menu_order": 0,
                    "guid": "http://wordpress-25400-54247-195413.cloudwaysapps.com/?page_id=92",
                    "meta": []
                },
                "sort": [
                    0,
                    "test"
                ]
            },
            {
                "_index": "wordpress2540054247195413cloudwaysappscom-1",
                "_type": "post",
                "_id": "95",
                "_score": null,
                "_source": {
                    "post_id": 95,
                    "ID": 95,
                    "post_author": {
                        "raw": "xxxxx",
                        "login": "xxxxx",
                        "display_name": "Ted",
                        "id": 1
                    },
                    "post_date": "2017-01-15 13:55:44",
                    "post_date_gmt": "2017-01-15 19:55:44",
                    "post_title": "Test 2",
                    "post_excerpt": "",
                    "post_content": "<p>Testing again</p>n",
                    "post_status": "publish",
                    "post_name": "test-2",
                    "post_modified": "2017-01-15 13:55:44",
                    "post_modified_gmt": "2017-01-15 19:55:44",
                    "post_parent": 0,
                    "post_type": "page",
                    "post_mime_type": "",
                    "permalink": "http://wordpress-25400-54247-195413.cloudwaysapps.com/test-2/",
                    "terms": [],
                    "post_meta": [],
                    "date_terms": {
                        "year": 2017,
                        "month": 1,
                        "week": 2,
                        "dayofyear": 14,
                        "day": 15,
                        "dayofweek": 0,
                        "dayofweek_iso": 7,
                        "hour": 13,
                        "minute": 55,
                        "second": 44,
                        "m": 201701
                    },
                    "comment_count": 0,
                    "comment_status": 0,
                    "ping_status": 0,
                    "menu_order": 0,
                    "guid": "http://wordpress-25400-54247-195413.cloudwaysapps.com/?page_id=95",
                    "meta": []
                },
                "sort": [
                    0,
                    "test 2"
                ]
            }
        ]
    }
}

**Comment by tlovett1** [comment]
Please try 2.2 (in develop branch)

**Comment by teddarling** [comment]
2.2 installed, deleted index, setup index, ran again `wp elasticpress index` as suggested by @ekandreas and the result is the same.

**Comment by tlovett1** [comment]
@allan23 mind debugging this one?

**Comment by pbogdan** [comment]
Hi,

so I was able to reproduce this locally on:

- WP 4.7.1
- ES 2.4.4
- EP 2.1.2

I'm not very familiar with EP, my current understanding of how queries are
intercepted is as follows:

1. `posts_requests` filter is used to hook into query execution process and send
  the query to ES
2. if the query succeeds the filter returns a new request (SQL query) that
  returns empty results
3. and finally `the_posts` filter is used to swap the results if ES query
  returned any results

In my environment the issue came down to the fact that WordPress may attempt to use the new request / SQL query returned from step 2. and return the results before execution ever reaches point 3. And if 1. succeeded the query WordPress will be running is `SELECT * FROM $wpdb->posts WHERE 1=0` and hence the empty results page.

Relevant lines from core:

- [L2752](https://github.com/WordPress/WordPress/blob/4.7.1/wp-includes/class-wp-query.php#L2752) - at this point Wordpress may have been given the "empty" query
- [L2773](https://github.com/WordPress/WordPress/blob/4.7.1/wp-includes/class-wp-query.php#L2773) & [L2785](https://github.com/WordPress/WordPress/blob/4.7.1/wp-includes/class-wp-query.php#L2785) - this is where WordPress may return from early using results obtained by the "empty" query before we would reach the step below
- [L2785](https://github.com/WordPress/WordPress/blob/4.7.1/wp-includes/class-wp-query.php#L2785) - results are substituted with their ES result

I believe the reason this may not occur in each environment is due to ES version. When tested against ES 5.1.2 the query ES issues to EP fails with [an error related to fielddata](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/fielddata.html#_fielddata_is_disabled_on_literal_text_literal_fields_by_default) and so EP will not try to override the request / SQL query. In contrast 2.4 [would build the fielddata on demand](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/fielddata.html#fielddata) so no errors would be produced. At least that's my understanding of ES docs and is probably a separate issue.

Not quite sure what a proper solution would be but one option would be to move the result substitution to earlier on in the process, for example using `posts_pre_query` filter that fires right before WordPress may try querying the database, though I don't know if there was a specific reason to defer substitution until later on.

Otherwise it seems that inspecting the requested fields in the query may be required which would also mean bypassing ES for situations where WordPress may return early.

Not sure about trade-offs between the two approaches but FWIW I implemented both as an mu-plugin which cleared the issue for me:

```php
<?php

add_action(
    "plugins_loaded",
    function () {
        if (!class_exists("EP_WP_Query_Integration")) {
            return;
        }

        remove_filter(
            'the_posts',
            array(
                EP_WP_Query_Integration::factory(),
                'filter_the_posts' ),
            10,
            2
        );

        add_filter(
            'posts_pre_query',
            array(
                EP_WP_Query_Integration::factory(),
                'filter_the_posts'
            ),
            10,
            2
        );
    }
);
```

and

```php
<?php

add_filter(
    "ep_skip_query_integration",
    function ($skip, $query) {
        $es_version = get_transient("es_version");

        if (!$es_version) {
            $es_version = EP_API::factory()->get_elasticsearch_version();
            set_transient("es_version", $es_version, 600);
        }

        if (version_compare($es_version, "5.0.0", ">=")) {
            return $skip;
        }

        $fields = $query->query_vars['fields'];
        switch ($fields) {
        case "ids":
        case "id=>parent":
            return true;
        default:
            return false;
        }
    },
    10,
    2
);
```

Thanks,
Piotr

**Comment by consciousimages** [comment]
I've just noticed this as well.  For me, it's not only preventing pages from appearing in the admin, but this is a Woocommerce site syncing to Square (via Woocommerce Square plugin) and it's preventing product updates in Square (syncing) - this is how I originally started troubleshooting this.  The plugin logs aren't particularly helpful, but before they basically said 'getting all inventory' and then nothing, for inventory, products, etc.  After deactivating EP, I get  'getting all inventory' then 'updating inventory', etc.  Posts are not affected.

ES 1.7.3 (!)
EP 2.1.2
WP 4.7.1

I'll get my host (Pagely) to upgrade my ES version, it's ancient.  Hadn't realized that previously.

My guess is this is related to a change WP 4.7 - not Elasticpress.  I know for a fact in early/mid December (prior to the 17th) everything was working fine -- both pages and the Square syncing. On Dec. 17th syncing stopped working.  Pagely updated us to WP 4.7 late, and without contacting their support I would bet that happened on Dec. 16.

**Comment by teddarling** [comment]
@pbogdan Thanks for that. I will try that out this evening when not working on client stuff and report how it works out for me. If not, if the wife doesn't keep me busy this weekend, I may try some debugging myself.

Also, for what it's worth: ES 1.7.6 (not previously mentioned)

**Comment by ivankristianto** [comment]
I tried this PR #697, it fixed the issue.

**Comment by tlovett1** [comment]
We are pulling page table query integration for now. Should work fine now with 2.2.
