### ISSUE TITLE
When a fields argument is passed to get_posts the returned object should be respected

### ISSUE THREAD

**Issue by rsouthgate** [10up/ElasticPress#678]
The EP modules hook into the get_post posts_request filter and returns a request query that guarantees zero results... it then goes away and handles the query from ElasticSearch. The trouble is it always then returns arrays of WP_Post objects. But if the original get_posts call passed in a fields argument of, say, ID the original get_posts call would have returned an array of just the post IDs.

Should the EP plugin handle fields generically and not construct post objects if not needed?

**Comment by tlovett1** [comment]
`WP_Query` makes this impossible for us to do. A core patch would be needed.

**Comment by rsouthgate** [comment]
I think I see where in WP_Query it returns early without calling the_posts filter but prior to that there is a posts_pre_query filter. Couldn't the integration class filter_the_posts method be hooked to that? Since the result is cached it could be hooked to both I guess.

I've hacked around with it and added the conditional logic to handle the field filters in the filter_posts_request method like in this gist and the early hook to the posts_pre_query filter: https://gist.github.com/rsouthgate/a0ac3ecca09987fa2d05ee3506b68bab
