### ISSUE TITLE
Warning on fresh Wordpress 4.7.1 install (PHP 7.1)

### ISSUE THREAD

**Issue by francesconero** [10up/ElasticPress#682]
Every page (admin and site) presents this warning after activating the plugin:

> Warning: Parameter 2 to EP_WP_Query_Integration::filter_the_posts() expected to be a reference, value given in /wp-includes/class-wp-hook.php on line 298

Digging through the code it seems that changing the `$query` parameter to be value and not reference (removing the `&`) in `classes/class-ep-wp-query-integration.php`:

```php
	/**
	 * Filter the posts array to contain ES query results in EP_Post form. Pull previously queried posts.
	 *
	 * @param array $posts
	 * @param object &$query
	 * @return array
	 */
	public function filter_the_posts( $posts, &$query ) {
		if ( ! ep_elasticpress_enabled( $query ) || apply_filters( 'ep_skip_query_integration', false, $query ) || ! isset( $this->posts_by_query[spl_object_hash( $query )] ) ) {
			return $posts;
		}

		$new_posts = $this->posts_by_query[spl_object_hash( $query )];

		return $new_posts;
	}
```
fixes the issue. I'm not a PHP developer so this might be completely the wrong way of fixing it, but looking at the function reference [here](https://developer.wordpress.org/reference/functions/apply_filters_ref_array/) there seem to be comments saying that the function doesn't pass by reference anymore since php 5.4. Could that be it?

**Comment by tlovett1** [comment]
Thanks! This will be fixed in 2.2 or you can use the develop branch.

**Comment by manishverma025** [comment]
Where is classes folder in wordpress-4.9.5

**Comment by agafforov** [comment]
I don't now is it the correct resolve, but it works... Thanks!
