### ISSUE TITLE
Duplicate meta values in synced items?

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#683]
Maybe I'm crazy, but I'm seeing all meta items indexed for each post twice.

Once in `post_meta` and once in `meta`.

![](http://d.pr/i/nOtP/1GZsYmr5+)

![](http://d.pr/i/1i4zC/1nCqDC12+)

This seems like a huge waste of processing and overall storage; can anyone verify that I'm not misunderstanding this? 

cc @tlovett1

**Comment by tlovett1** [comment]
Hey @AaronHolbrook, you're correct. Remember we did this way back to avoid backwards compat issues? Originally we only had post_meta. We could certainly remove this; it's been a long time. In fact, the WC feature removes it since the documents are already huge.

**Comment by AaronHolbrook** [comment]
I don't recall the addition of `meta`, but that could've happened while I was busy with other things.

Why did it get renamed to `meta`?

**Comment by tlovett1** [comment]
I think we totally restructured the field and didn't want to break backwards compat.

**Comment by AaronHolbrook** [comment]
Ahh, well I'd be all for removing it, maybe we can do it in a point release and make it clear in the changelog that it'd be removed, possibly causing breakage?

**Comment by sushicodeur** [comment]
Which one may be removed ? meta ? post_meta ?

I came here searching for information why these two properties were present and see if I can safely  hook ep_post_sync_args_post_prepare_meta to remove the meta entry (or post_meta depending on which one may be removed lately).

**Comment by tlovett1** [comment]
`post_meta` is slated to be removed in 2.4. #865
