### ISSUE TITLE
How to know which part matched ?

### ISSUE THREAD

**Issue by bactisme** [10up/ElasticPress#684]
That would be very perfect if we had functions that allow us to show which field matched. 

Would it be possible with elasticsearch or would it be only php functions?

**Comment by allan23** [comment]
HI @bactisme, can you provide an example of what you mean?

**Comment by dnaber-de** [comment]
@bactisme You can use the [explain API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-explain.html) of Elasticsearch. Here's an example how you can adapt EP:

```php
<?php 

namespace Your\Project;

class EsAnalyzer {

	/**
	 * @wp-hook ep_search_request_path
	 */
	public function analyze_query_arg( $path, $args, $scope, $query_args ) {

		return add_query_arg( 'explain', '', $path );
	}

	/**
	 * @wp-hook ep_retrieve_the_post
	 *
	 * @param array $post
	 * @param array $hit
	 *
	 * @return array
	 */
	public function map_document_hit( array $post, array $hit = [] ) {

		isset( $hit[ '_explanation' ] ) and $post[ '_explanation' ] = $hit[ '_explanation' ];

		return $post;
	}

	/**
	 * @wp-hook ep_search_post_return_args
	 */
	public function whitelist_post_field( array $fields ) {

		$fields[] = '_explanation';

		return $fields;
	}

	/**
	 * @return EsAnalyzer
	 */
	public static function create_and_register() {

		$analyzer = new self;

		add_filter( 'ep_search_request_path', [ $analyzer, 'analyze_query_arg' ], 10, 4 );
		add_filter( 'ep_retrieve_the_post', [ $analyzer, 'map_document_hit' ], 10, 2 );
		add_filter( 'ep_search_post_return_args', [ $analyzer, 'whitelist_post_field' ] );

		return $analyzer;
	}
}
```
And call it like this:

```php
Your\Project\EsAnalyzer::create_and_register();
```
You'll then find a property `_explanation` on each post that shows you how the relevance score was calculated.

**Comment by bactisme** [comment]
Great !! 

Why not include this class in the project?
I was also about plugin option that could allow, on the search page, to underline keyword in the post title in the research page or extract interesting parts in the excerpt.

**Comment by dnaber-de** [comment]
The class is just a quick'n'dirty solution for development and debugging. You should not use that in production as the explanation API is rather expensive.

About highlighting: This is also [possible](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html) with a listener on `ep_formatted_args`.
For example (not tested):

```php
<?php
add_filter( 'ep_formatted_args', function( array $es_query, array $wp_query_args ) {

    ! isset( $es_query[ 'highlight' ] ) and $es_query[ 'highlight' ] = [
        'fields' => [
            '_all' => []
        ]
    ];

    return $es_query;
}, 10, 2 );
```
