### ISSUE TITLE
Search by post_title and post_content with different search phrase in the same query

### ISSUE THREAD

**Issue by psgdev** [10up/ElasticPress#687]
I didn't find how to set query when the search form has two text fields, one for title and one for content search.  Am I missing something or this functionality is not supported?

**Comment by allan23** [comment]
Hi @psgdev, how are you performing a query with ElasticPress? 

From what it sounds like is that you have a custom search form, in which you will probably need to either consolidate the fields or alter the WP_Query that form uses.

**Comment by psgdev** [comment]
Form has two text fields to differentiate search on post_title and post_content, and few dropdowns to search relation set with taxonomies. If I turn off one text field and set only one to default "s" parameter, everything is good using "pre_get_posts" action altering with "set" method the arguments. But when using two custom search fields, e.g. title_field and content_field text form elements in the same search form, it's impossible or I missed the write procedure in the documentation here on git. How to alter or write a new wp_query?

**Comment by ivankristianto** [comment]
@psgdev currently how your WP_Query looks like? And with that WP_Query all you need is just add the `'ep_integrate'   => true`

**Comment by psgdev** [comment]
@ivankristianto I'm sorry, but it seems that you have not understood my question. Everything is good when the form has only one, default text search input field ("s"). But if I want to have two text fields in the form with names "x_title" and "x_content" (and few select elements too), I didn't find the way to say to EP how to search data. I want to search post_title field by x_title value and post_content field by x_content value. My question was: Am I missing something or it is not possible. I understand usage of ep_integrate, but something else have to be set and i don't see in the documentation. After few days of playing with WP_Query, my conclusion was that it is not possible.

**Comment by ivankristianto** [comment]
@psgdev I got what You mean. 
This plugin is not support that feature.
