### ISSUE TITLE
How would I go about removing the related posts from certain pages/posts/custom content, etc?

### ISSUE THREAD

**Issue by madrid1979** [10up/ElasticPress#689]
We have a few places in our content where it doesn't make sense to have any other related content. Is there a method to (for now) programmatically omitting this feature?

**Comment by madrid1979** [comment]
Also, thank you for the work on this. We're using it on https://thenevadaindependent.com/ which was just covered on Meet The Press Daily with Chuck Todd.

**Comment by tlovett1** [comment]
Hey @madrid1979, which version are you running. Version 2.2 actually moves related posts to a widget. You could still easily append it to post_content if you wanted to though.

**Comment by madrid1979** [comment]
@tlovett1 Looks like we're on 2.1.2. I'll update and try appending as appropriate. Thank you!
