### ISSUE TITLE
Missing posts after successful syncing

### ISSUE THREAD

**Issue by colis** [10up/ElasticPress#692]
I'm trying to index hundreds of custom post types, using both GUI and wp-cli, but only a few posts are being actually indexex, as you can see in the pictures below

![total-indexed](https://cloud.githubusercontent.com/assets/9059716/22408812/ee94efd4-e67f-11e6-9539-927cbd3bf746.png)

![real-indexed](https://cloud.githubusercontent.com/assets/9059716/22408815/f390f53c-e67f-11e6-9a5f-3e00c3e9e70a.png)

**Comment by pereirinha** [comment]
Hi @colis:

You might have some errors while trying to index those posts. Can you try indexing using the CLI interface and using the `--show-bulk-errors` argument?

**Comment by colis** [comment]
Hi @pereirinha 

Unfortunately I already tried that, but I don't see errors during/after indexing with CLI interface

**Comment by dnaber-de** [comment]
Are your custom post types `public`? Is there maybe a filter on `ep_indexable_post_types`?

**Comment by colis** [comment]
Hi @dnaber-de 

yes, post types are registered as `public`
![public-cpt](https://cloud.githubusercontent.com/assets/9059716/22419195/a91d6d20-e6dc-11e6-9356-93581607f2aa.png)

and there's no filter on `ep_indexable_post_types`

**Comment by colis** [comment]
ok, I couldn't see errors using `--show-bulk-errors` argument because I have tons of PHP warnings

![bulk-errors](https://cloud.githubusercontent.com/assets/9059716/22420860/a71b660a-e6e4-11e6-8ee5-30910a45220d.png)

**Comment by tlovett1** [comment]
Bulk errors should be showing properly now.

**Comment by colis** [comment]
thanks @tlovett1 

Anyway I think I solved the problem: the structure of my custom post types was triggering `Limit of total fields [1000] in index [xxxxx] has been exceeded`, so I had to raise `index.mapping.total_fields.limit` , same issue as #632

**Comment by tlovett1** [comment]
Awesome. Yep, figured it would be something like that.
