### ISSUE TITLE
Indexing stops if module "woocommerce" is enabled

### ISSUE THREAD

**Issue by futurmat** [10up/ElasticPress#694]
I have a woocommerce website with about 14000 products hosted on cloudways.com. I enabled elasticsearch on the host and installed and configured elasticpress. Indexing works fine if I enable the module "search". However, as soon as I enable "woocommerce" and start the indexing process it fails:
```
Adding mapping...
Deleting index...
Success: Index deleted
Success: Mapping sent
Indexing posts...
Processed 350/117097 entries. . .
[xxxxxxxxx]:public_html$ 
```
Right after "Indexing posts" the command returns. Looking at the stats it says Documents: 350. There is no error message whatsoever. Is there any possibility to find out, why the indexing process stops?

**Comment by allan23** [comment]
Hi @futurmat, thanks for the report. Can you let us know which version of ElasticPress, Elasticsearch, WordPress, and WooCommerce you are running?

**Comment by tlovett1** [comment]
This should be fixed. Please reopen if it's not.
