### ISSUE TITLE
Read only option

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#698]
Feature request.

When developing locally, it would be nice to be able to use EP to query an ES server, but not write.

**Comment by tlovett1** [comment]
Definitely a cool idea.

**Comment by rveitch** [comment]
I have had this thought myself. It would definitely be useful from a development standpoint to have indexing disabled/deactivated/decoupled separately from search/query integration.

**Comment by psorensen** [comment]
This might be a good start. #301

**Comment by psorensen** [comment]
PR #782

**Comment by lukaspawlik** [comment]
@psorensen I am closing this due to the fact that corresponding #782 was also closed. I'd like to clean up issues list a bit.
