### ISSUE TITLE
Disable dashboard sync with constant

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#701]
This would be helpful for sites we manage where clicking the dashboard sync problem would cause major problems (deleting the index).

**Comment by rveitch** [comment]
I'd be happy to help with this and submit a PR, this is something I need to address for our integration anyways.

**Comment by tlovett1** [comment]
Go for it!

**Comment by rveitch** [comment]
Hey @tlovett1 sorry for the delay, I had to catch up on some ES5 migration projects before I could swing back to this.  I almost have the PR ready, but I was curious how much of the dashboard sync functionality, related notices and options we want to disable with the constant? Aside from the actual sync button there are three dashboard notifications (`no-sync`, `upgrade-sync`, `auto-activate-sync`) that can display with links to trigger a dashboard sync, as well as directly triggering it via the query parameter (eg. `?page=elasticpress&do_sync`).

So my question is, do we want to cover the other possible notifications and methods that could potentially trigger a sync from the dashboard to more fully lock it down from front-end intervention, or simply just the button itself?  I have branches covering both scenarios, but I imagine the use case for this being managed hosting where indexing should be managed only from WP-CLI without interaction on the part of the user to better ensure data integrity and service up-time.

The potential gotcha for this is `auto-activate-sync` when features are activated that require reindexing to take effect. While I imagine that users on managed situations that would use this constant would be made aware of this, I want to be careful not to make too many assumptions. 

Here's a few possible approaches I have considered, let me know what you think and I'll get a PR submitted once we've decided on an approach.

#### Choose Your Weapon:
1. Display slightly different conditional (dismissible) notifications when dashboard sync is disabled informing the user that a sync is required, but must be done via WP-CLI (or that Dashboard Sync is disabled)
2. Prevent features that require indexing from being enabled/disabled/changed via the dashboard (WP-CLI only)
3. Disable all dashboard sync EXCEPT `auto-activate-sync`, and include a second constant to optionally disable this as well
4. Allow dashboard sync when triggered by notifications and only disable the main sync button

**Comment by tlovett1** [comment]
@rveitch this is really well thought out. Nice work! I'm leaning towards 2. What are your thoughts?

**Comment by rveitch** [comment]
@tlovett1 Thanks! I agree, option 2 should provide the most coverage and control, and it should be fairly simple to work into the EP_Feature requirement_status() function. I'll dig into that and get a PR submitted as soon as possible.

**Comment by rveitch** [comment]
@tlovett1 PR #780 submitted.  If you notice anything you'd like changed or adjusted just let me know. :)
