### ISSUE TITLE
Notice message is not correct when first install

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#702]
Steps to reproduce:
1. Do fresh install
2. In plugin page it shows correct notice
3. In settings page it says "Your Elasticsearch version is below the minimum required Elasticsearch version 1.3. ElasticPress may or may not work properly."

I haven't set any host yet.

Trace down code:
class-ep-dashboard.php in function maybe_notice()

```
$es_version = ep_get_elasticsearch_version();

/**
 * Check Elasticsearch version compat
 */

if ( false !== $es_version ) {
	// First reduce version to major version i.e. 5.1 not 5.1.1
	$major_es_version = preg_replace( '#^([0-9]+\.[0-9]+).*#', '$1', $es_version );

	if ( -1 === version_compare( EP_ES_VERSION_MAX, $major_es_version ) ) {
		$notice = 'above-es-compat';
	} elseif ( 1 === version_compare( EP_ES_VERSION_MIN, $major_es_version ) ) {
		$notice = 'below-es-compat';
	}
}
```

$es_version will return null, thus $notice will set into 'below-es-compat'

**Comment by tlovett1** [comment]
Which version of ES are you running?

**Comment by ivankristianto** [comment]
ES 5.0.0
