### ISSUE TITLE
Install and configure Elasticsearch URL showing 404

### ISSUE THREAD

**Issue by musamamasood** [10up/ElasticPress#721]
Hello, 

URL placed at [installation page](https://wordpress.org/plugins/elasticpress/installation/) linked to [404](https://www.elastic.co/guide/en/elasticsearch/guide/current/_installing_elasticsearch.html). 

But it linked correctly on github, so please update on [WordPress](https://wordpress.org/plugins/elasticpress/installation/) as well.

**Comment by tlovett1** [comment]
This will be fixed in 2.2
