### ISSUE TITLE
wp elasticpress index, gives notice errors

### ISSUE THREAD

**Issue by ekandreas** [10up/ElasticPress#722]
EP: 2.1.2
WP: 4.7.2
OS: Ubuntu 16

When running command for index with debug the elasticpress index routine gives notice warning, like:
```
PHP Notice:  Indirect modification of overloaded element of WP_Hook has no effect in ...plugins/elasticpress/bin/wp-cli.php on line 787

**Comment by tlovett1** [comment]
Mind giving a little more information?

- What version of ES
- What CLI command are your running specifically
- What EP modules do you have active

I just tested with EP 2.1.2, ES 5.2, WP 4.7.2, and search/admin activated. I didn't get any errors.

**Comment by ekandreas** [comment]
EP: 2.1.2

`wp elasticpress index`

No modules...

**Comment by tlovett1** [comment]
Ah I see. This is a problem with our stop the insanity function. We could push a hotfix but I'm not sure it's necessary since this is just a notice. This shouldn't be causing any problems.

**Comment by ekandreas** [comment]
No, just clean it up for future releases. Ok?

**Comment by yannux** [comment]
Hi, 
I had those Notice during test of the v3. 
I find cleaner solution ( I think/hope ) than one in Command.php stop_the_insanity();

Hooked in `ep_wp_cli_pre_index` with : 
```
add_action('ep_wp_cli_pre_index', function($args, $assoc_args){
    wp_suspend_cache_addition(true);
    wp_suspend_cache_invalidation(true);
    // @see https://wordpress.stackexchange.com/questions/102349/faster-way-to-wp-insert-post-add-post-meta-in-bulk
    wp_defer_term_counting(true);
    wp_defer_comment_counting(true);
}, 100, 2);
```

Then no need to check for : 
```
if ( preg_match( '#^[0-9a-f]{32}lazyload_term_meta$#', $hook ) ) {
    unset( $filter_callbacks[10][ $hook ] );
}
```

If that can help clean unwanted Notice :)

Sorry if it's bad too comment this closed issue
