### ISSUE TITLE
After activating and indexing WooCommerce orders, most of the orders are not listed

### ISSUE THREAD

**Issue by Holyto** [10up/ElasticPress#726]
Hi,

I installed the plugin and indexed my orders via ElasticPress Dashboard and also WP-CLI.

The result is that most of my orders are not visible on the Dashboard, instead of 11 647 orders, only 621 are listed.

Did anyone have had the same issue?

I'm using:
ES: 5.2.0
WP: 4.7.2
WC: 2.6.13
EP: 2.1.2

Thank you in advance.

**Comment by ivankristianto** [comment]
Probably related to #714

**Comment by tlovett1** [comment]
Please give 2.2 a shot

**Comment by Holyto** [comment]
Thanks for the leads.
I have switched to EP 2.2 and the behaviour is much different now.
The EP 2.2 indexed only 248/248 entries.

I'm using custom wp-content directory.
Maybe this might be the issue?

p.s.
Also tried the fix #725

**Comment by ivankristianto** [comment]
Just wondering if you turn on the feature Woocommerce and Protected Content ?

**Comment by Holyto** [comment]
Oh right I didn't enable Protected Content after update, but it seems that the issue is still there.

Here's the dashboard screen:
[http://ratomski.pl/wp-content/uploads/2017/02/dashboard.png](url)

Not all orders are listed and I also noticed that my attribute filtering does not work on the shop.

**Comment by tlovett1** [comment]
You'll need to trace through the index and find out where the error (if any) is occurring.

**Comment by ivankristianto** [comment]
@Holyto Is the issue still persist?

**Comment by tlovett1** [comment]
@Holyto can you email me? (My email is in my profile)

**Comment by Holyto** [comment]
@ivankristianto I downloaded the newest build and the attributes are now working and the shop performance is faster, however I still have problems with the protected content. Not all of my orders are listed and the admin search does not work at all.

**Comment by ivankristianto** [comment]
@Holyto You might have an issue in during the indexing.
Can you please install the EP Troubleshooting plugin on your staging site and send us the JSON file?

https://github.com/allan23/ep-troubleshoot/archive/master.zip

Instructions for this plugin can be found here: https://github.com/allan23/ep-troubleshoot/blob/master/README.md

Thanks.
