### ISSUE TITLE
Index file contents, use Ingest attachment or pre-parse binary files before hands?

### ISSUE THREAD

**Issue by foadyousefi** [10up/ElasticPress#727]
Hi there!
I have a website using ElasticPress and need to index pdf file contents. I'm having hard time figuring out how to read file content and did lots of researches. Also read [this topic](https://discuss.elastic.co/t/mapper-attachment-plugin-vs-pre-parsing-and-extracting-content-from-binary-files/73764) of Taylor on discuss.elastic.co

There was some projects of EP to add capability of indexing attachment contents before. What happened to them?

Now the question is: Do I really need to use Ingest Attachment or just as Taylor said, pre-parse pdf files? and also please how to do?

With my experiences with ElasticSearch and ElasticPress, I think easiest way is to pre-parse, thats way I just need to add some extra fields to index and don't need to specify pipeline, mappings and indexing.

**Comment by tlovett1** [comment]
We are working internally on an ElasticPress feature that uses the Ingest Attachment plugin. Just FYI.

**Comment by foadyousefi** [comment]
For now I solved the problem by pre-parsing the attachments using "Tika" and some php classes and then indexing attachments contents. 

Looking forward for future releases.
