### ISSUE TITLE
--network-wide in wpcli elasticpress blindly run through all sites

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#734]
If i use --network-wide in wpcli it will run the elasticpress command (index, delete-index, put-mapping, etc) to all sites without checking if that site activate the plugin elasticpress or not.

My setup is 
WP 4.2.2
EP 2.2
ES 5.2.0
Multisite Enabled

Site A: EP activated
Site B: EP not activated
Site C: EP activated

Delete index command:
```
vagrant@vvv:/srv/www/10up/htdocs/wp-content/plugins/ElasticPress$ wp elasticpress delete-index --network-wide
Deleting index for site 1...
Success: Index deleted
Deleting index for site 2...
Error: Delete index failed
```

The script will stop in site 2 and will never run in site 3.

**Comment by tlovett1** [comment]
This is only intended to be run in the plugin is network activated. We should probably just output an error and exit if the plugin isn't network activated.

**Comment by ivankristianto** [comment]
I got what you mean. 
Close this ticket now
