### ISSUE TITLE
Replace Woocommerce related products using ElasticPress

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#740]
Currently Woocommerce related products handled by woocommerce and use a specific query args:
```
'post__in' => 
    array (size=4)
      0 => string '3206' (length=4)
      1 => string '3186' (length=4)
      2 => string '3264' (length=4)
      3 => string '3216' (length=4)
  'post__not_in' => 
    array (size=1)
      0 => int 3226
```

This will return result only from the same category or tags.
It would be great if we can accommodate this feature using elasticpress.

**Comment by ivankristianto** [comment]
PR #756

**Comment by tlovett1** [comment]
@ivankristianto should we close this?

**Comment by ivankristianto** [comment]
yes we can close this
