### ISSUE TITLE
What WP Filter to use to change the default query and use 'search_fields' ?

### ISSUE THREAD

**Issue by benners00** [10up/ElasticPress#753]
I'm sure I'm missing something obvious but just can't see how to use 'search_fields' and just change the default text search. The Elastic press debug bar shows I am now running two elastic queries and not one which clearly isn't right, but the Query Results and Query Args all seem fine and return the results I expect but I get 'no results found' on my search page.

`function elastic_query( $query ) 
{

    if ( $query->query['s'] && $query->is_main_query() ) 
    {

        $query = new WP_Query(
            array(
	            's' => $query->query['s'],
	            'search_fields' => array(
	                    'post_title',
	                    'post_content',
	                    'post_excerpt',
	                    'meta' => array( 'intro', 'sub_heading' ),
	                ),
	            'post_type' => array('post','page'),
	            'posts_per_page' => 20,
	            'paged' => $paged
            )
        );

        return $query;
	
    }

}
add_action( 'pre_get_posts', 'elastic_query' );`

**Comment by benners00** [comment]
I seem to have found the issue. I was confused about the none WP standard 'search_fields' and using it with `$query->set`. Might be worth add this filter example to the README.md

`function elastic_query( $query ) 
{
    if ( $query->query['s'] && $query->is_main_query() ) {

		$query->set( 'search_fields', array(
			'post_title',
			'post_content',
			'post_excerpt',
			'meta' => array(  'intro', 'sub_heading'  ),
			'taxonomies' => array(
				'post_tag',
				'category',
			),
		) );
        
    }
}
add_action( 'pre_get_posts', 'elastic_query' );`

**Comment by ivankristianto** [comment]
@benners00, thank you and we will update the README.md
