### ISSUE TITLE
Error While Indexing when using Woocommerce Product with Custom Taxonomy

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#754]
```
- 4780: The Manhattan Transcripts Project, New York, New York, Episode 1: The Park
type: illegal_argument_exception
reason: Limit of total fields [1000] in index [10updev-1] has been exceeded
```

How to replicate:
1. Create a custom taxonomy for woocommerce product
2. Add a tax for a product
3. Reindex.

Env:
WP: 4.7.2
EP: 2.2
ES: 5.2
WC: 2.6.14

**Comment by tlovett1** [comment]
This is an Elasticsearch setting. We could certainly cut down extra fields though.

**Comment by ivankristianto** [comment]
Should we cut down of increase it to have more limit? 
i see the PR that allow that: #757

**Comment by ivankristianto** [comment]
This issue only for Elasticsearch version 5.1 and 5.2
For elasticsearch 2.4, it is working fine

**Comment by ivankristianto** [comment]
related to #722

**Comment by thomascharbit** [comment]
I had the same issue today, without WooCommerce. I had to raise the limit.
