### ISSUE TITLE
Official Elasticsearch PHP Clients

### ISSUE THREAD

**Issue by kallehauge** [10up/ElasticPress#759]
_I'm still getting a hang of the plugin, so please close this "issue" if it is without interest._ 🙉 

Would it make sense to extend the `EP_API` class based upon the official ES PHP Clients?

- https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_quickstart.html
- https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_quickstart.html

The general idea is that we might be able to move a lot of responsibility and be able to focus even more on the integration part instead of also creating the bridge to ES itself?

/ Kallehauge :heart:

**Comment by tlovett1** [comment]
I don't think this would make sense. 99% of that class revolves around WordPress integration and translation of arguments.
