### ISSUE TITLE
Dashboard sync is successful when it really is not

### ISSUE THREAD

**Issue by allan23** [10up/ElasticPress#762]
When performing a sync from the dashboard, regardless of the status code returned it will say "Sync complete". This does not happen when using WP_CLI.

How I can reproduce:
1. Restrict the index name on the ES host (e.g. mysite-1).
2. Attempt a sync from a site that does not have a valid index name (e.g. notmysite-1).
3. The ES server will return a 403 Forbidden response due to the restriction.
4. "Sync complete" message appears despite error.

Another way:
1. Set a valid ES host in EP.
2. Once the sync icon is available, turn off ES.
3. Attempt a sync.
4. "Sync complete" message appears despite error connecting to ES server.

**Comment by ivankristianto** [comment]
Yes I can reproduce this and confirm it.
No matter what result is when indexing, the dashboard always return "Sync complete".
It need better error handling
