### ISSUE TITLE
No WooCommerce Products Showing in Search Results

### ISSUE THREAD

**Issue by brunocrosier** [10up/ElasticPress#767]
when i search for any product, no results are found. any idea why this could be? take a look: staging[dot]vincentius[dot]com

**Comment by ivankristianto** [comment]
Hey @brunocrosier i tried to search it and it return results.
keyword: Orlando
do you still having this problem?
Did you do reindexing after activate the woocommerce module?

**Comment by brunocrosier** [comment]
hmm how can i test whether it's getting the results from elasticpress or normall from wordpress?

**Comment by kallehauge** [comment]
Hi @brunocrosier !

If you enable `Debug bar` and `Debug Bar ElasticPress` then you'll be able to see which queries were done with ElasticPress, what they sent to Elasticsearch and the Elasticsearch response.
So if your queries doesn't show up under the "ElasticPress" tab, then it executed as a "normal" WP search :relaxed:

https://srd.wordpress.org/plugins/debug-bar/
https://da.wordpress.org/plugins/debug-bar-elasticpress/
