### ISSUE TITLE
There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work.

### ISSUE THREAD

**Issue by samuelstubbs** [10up/ElasticPress#768]
I'm having an issue debugging the plugin when connecting to ES on my staging environment. Tested and working on my local environment both environments are running on the same instance. Error and server logs are returning nothing. It would be nice if instead of just saying "There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work."  actually outputting the error / response from ES so the developer can easily and quickly fix it. Also when you click on "fix it" it just takes you back to the setting page, why?

**Comment by tlovett1** [comment]
Hey @samuelstubbs, do you have the ElasticPress Debug plugin installed? That will tell you the error. Where are you hosting your ES cluster?

**Comment by samuelstubbs** [comment]
@tlovett1 yes I have it installed this is the response:

Time Taken: 4708 ms
Method: GET
Query Response Code: HTTP 0

Which doesn't tell me much, the cluster is being hosted on elastic.co Cloud platform.

**Comment by ivankristianto** [comment]
Is your host can connect to the ES server? any firewall rule that might block it?

**Comment by tlovett1** [comment]
@samuelstubbs we are pushing an update to the Debug Bar plugin today to show you more details. The request is failing before it reaches Elasticsearch. This is usually a cURL error.
