### ISSUE TITLE
[Idea] Disable write actions

### ISSUE THREAD

**Issue by kallehauge** [10up/ElasticPress#771]
The WP Redis plugin have a constant named `WP_REDIS_DISABLED` that basically disables actions to the Redis cache.

My thought is that it can be a "cumbersome" task to reindex a large DB when working on a new production database, locally, to debug issues. So would it make sense make an option to block all request TO Elasticsearch and allow pure "read" access by a constant? 

PR: https://github.com/tillkruss/redis-cache/pull/47
Explanation: https://github.com/tillkruss/redis-cache/pull/47#issuecomment-251865212

**Comment by ivankristianto** [comment]
@kallehauge yes this definitely a good idea. And there is an issue for that #698 
So we can merge this issue, and close this one
