### ISSUE TITLE
Site goes down when enabling woocommerce 

### ISSUE THREAD

**Issue by nastyraj7** [10up/ElasticPress#774]
When I enable the woocommerce feature of this plugin the front end stops working. 
My site configuration 👍 
httsp://www.nepalikart.com
->Running latest woocommerce and wordpress
-> Nginx installed by easyengine
-> WP Rocket plugin with rocket-nginx.conf
->Nitro theme latest.

Any help i can get this working. I am not sure what is the cause of the issue.

**Comment by ivankristianto** [comment]
Hi @nastyraj7 can you tell me what is your environment version:

WordPress:
Woocoomerce:
ElasticPress:
Elasticsearch:

What ElasticPress modules do you activated?

Did you run full reindexing?
