### ISSUE TITLE
No results in WooCommerce admin order search

### ISSUE THREAD

**Issue by chercka** [10up/ElasticPress#775]
With ElasticPress enabled, the order search in WooCommerce admin returns nothing for name, email, possibly other fields. Order number is found correctly. Disabling ElasticPress returns the correct/expected order search results.

I noticed in the 2.2 changelog it mentions 'WooCommerce order search broken' - can you elaborate. I assume it means you had issues, that were resolved in 2.2!

**Comment by allan23** [comment]
Hi @chercka,
Did you run a sync after activating?

Which version of Elasticsearch, WooCommerce, and WordPress are you running?

**Comment by chercka** [comment]
Hi @allan23,
Yes we've synced several times since activation.
We are running latest versions of everything.

WooCommerce 2.6.14
ElasticPress 2.2
WordPress 4.7.3

**Comment by tlovett1** [comment]
@chercka please email me at taylor.lovett@10up.com

**Comment by ivankristianto** [comment]
@chercka there is a possibility that the indexing has failed to index all the orders. maybe be related to #722 
if you can get me the debug.log / error_log file that would be good to start with.

**Comment by chercka** [comment]
Hi @ivankristianto attached is the error log - thanks!

[error_log.zip](https://github.com/10up/ElasticPress/files/861645/error_log.zip)

**Comment by tlovett1** [comment]
@chercka we need to figure out two things:
1) Was there an error in putting the mapping? You'll need to manually do a put mapping and debug output to check this. CLI let's you easily do a put mapping.
2) You will need to install the ElasticPress Debug Bar and send us the formatted request/response for order search

**Comment by ivankristianto** [comment]
@chercka I cannot replicate the issue you are having.
But for the information, in Admin Order search elasticpress will search into these fields:
```
"fields": [
                                    "post_title",
                                    "post_content",
                                    "post_excerpt",
                                    "meta._order_key.value",
                                    "meta._billing_company.value",
                                    "meta._billing_address_1.value",
                                    "meta._billing_address_2.value",
                                    "meta._billing_city.value",
                                    "meta._billing_postcode.value",
                                    "meta._billing_country.value",
                                    "meta._billing_state.value",
                                    "meta._billing_email.value",
                                    "meta._billing_phone.value",
                                    "meta._shipping_address_1.value",
                                    "meta._shipping_address_2.value",
                                    "meta._shipping_city.value",
                                    "meta._shipping_postcode.value",
                                    "meta._shipping_country.value",
                                    "meta._shipping_state.value",
                                    "meta._billing_last_name.value",
                                    "meta._billing_first_name.value",
                                    "meta._shipping_first_name.value",
                                    "meta._shipping_last_name.value"
                                ]
```

I tried to search using order id, customer name, customer email, and shipping name, it is working as expected.

Can you try to sync using wp-cli?

**Comment by chercka** [comment]
Hey guys,

I'm working on the cli commands you've suggested. (I'm only able to debug on our staging server, so I don't have total freedom).

Attached is the debug bar output when I perform a search for an order in woocommerce admin by email (which I know exists).
[debug-bar-output.txt](https://github.com/10up/ElasticPress/files/876094/debug-bar-output.txt)

@ivankristianto the versions are listed above in the thread. Everything is up to date.

**Comment by chercka** [comment]
@tlovett1, going to pursue that manual put-mapping next. How do we debug the output from it?

**Comment by chercka** [comment]
Manual sync did not resolve the issue. Waiting on feedback for how to do the put-mapping and debug the output.

**Comment by ivankristianto** [comment]
@chercka how is your setup? 
are you using WP multisite? And do you have multiple webserver setup?

**Comment by chercka** [comment]
@ivankristianto we are not running multisite. The site has a dedicated elasticpress.
Can you please provide steps on performing the action @tlovett1 suggested: "You'll need to manually do a put mapping and debug output to check this."

**Comment by ivankristianto** [comment]
@chercka 
what is your ElasticSearch version?

to do manually put mapping you can run this command:
`wp elasticpress put-mapping`

But to do full re-index ( it will destroy old index, rebuild mapping, and reindex all content ), you can run this command:
`wp elasticpress index --setup`

**Comment by chercka** [comment]
We are running ElasticPress 2.2.1. Is there a separate ElasticSearch version number you are looking for?

We will try the full re-index.

**Comment by chercka** [comment]
Here are the results of the full re-index. Something going on during index, but it returns that all 149 posts have been indexed? How else to troubleshoot this?

**wp elasticpress index --setup**
Adding mapping...
Deleting index...
Success: Index deleted
Success: Mapping sent
Indexing posts...

Oops! It looks like you&#8217;re not logged in to your account.

Processed 149/149 entries. . .
Number of posts indexed on site 1: 149
Total time elapsed: 9.600
Success: Done!

**Comment by allan23** [comment]
Hi @chercka,

What other plugins do you have installed?

**Comment by chercka** [comment]
@allan23 it's a massive site with over 150.000 registered users, there are all manner of plugins running, a lot of them 100% custom.

More than a solution, I'm looking for strategies on how to troubleshoot this. For example, since the search is returning no results, does that mean indexing has failed? Or does the manual put-mapping confirm that indexing is succesful, and we are looking at an issue further down the line? How do I troubleshoot this?

**Comment by allan23** [comment]
@chercka, without knowing all the plugins, it may be difficult to troubleshoot. I would recommend deactivating plugins one by one and performing an index operation to determine if there is an issue with one of them. 

You mentioned previously that only 149 posts were indexed. Of these 149 that were indexed, what post type were they? Are there missing post types that should have been indexed?

**Comment by chercka** [comment]
@allan23 
1. I can run through the plugins and test indexing - how do I know if the indexing is succesful? Is there a way to do this through the admin interface? I don't personally have WP-CLI access and have to go through someone else for this.

2. 149 posts were indexed on the staging server, correct. How can I see which posts they are?

**Comment by chercka** [comment]
Any input on how to troubleshoot in response to my 2 questions above?

**Comment by allan23** [comment]
Hi @chercka,
I have been thinking about ways to help you with your issue, so I have developed a plugin that will generate some debugging information that you can share with us. Can you please install the EP Troubleshooting plugin on your staging site and send us the JSON file?

https://github.com/allan23/ep-troubleshoot/archive/master.zip

Instructions for this plugin can be found here: https://github.com/allan23/ep-troubleshoot/blob/master/README.md

Thanks.

**Comment by chercka** [comment]
That's a fantastic idea, thanks @allan23 . Attached is the json result.


[ep-troubleshoot.json.zip](https://github.com/10up/ElasticPress/files/917382/ep-troubleshoot.json.zip)

**Comment by allan23** [comment]
Thanks for the quick response @chercka. At a glance, it appears that the `shop_order` post type is not being indexed. This is likely due to the Protected Content feature not being enabled and the order search being conducted through WordPress and not ElasticPress. 

On my local setup, I have a few test orders from a customer from Testerville. With Protected Content turned off and performing a search for "Testerville", I get no results. However, when I activate Protected Content, I get results from the search.

We recommend only turning on the Protected Content feature if your Elasticsearch instance is secured. If it is not, we highly recommend checking out https://elasticpress.io/ as a secured Elasticsearch offering with our support team to help you out if anything should happen.

I hope this helps.

**Comment by tlovett1** [comment]
Yep, that's definitely the problem.

**Comment by chercka** [comment]
That's awesome guys, thanks. I'm currently unable to re-index via the WP interface so I'm getting our WP-CLI access guy to do it and will report back. Thanks!

**Comment by fraunholz** [comment]
I am having the same issue with the current version of Elasticpress. When going back to version 2.1.1 then also the orders are indexed. But one can not search for order number, customer number and from the email addresses we have to remove the dots (.) before searching, otherwise all orders are returned.

**Comment by tlovett1** [comment]
@fraunholz so you are saying this is working now? Search and Protected Content are required for searching WC orders.

**Comment by tlovett1** [comment]
@chercka we'll need to see the error message/stack tract in the logs.

**Comment by chercka** [comment]
@tlovett1 since it's run through WP-CLI it is not getting logged in the server log. Is there an elasticpress log watching somewhere? 

Segmentation Fault is what is output in WP-CLI.

**Comment by tlovett1** [comment]
Nope, there is not. You'll need to trace down where that error is coming from. Perhaps, you are running out of memory.

**Comment by fraunholz** [comment]
adding post_id to $search_fields allows to search for the order number but breaks for some reasons the search for other name and email. So for searching the order number elasticsearch was skipped, the performance is acceptable since it's using an index for post_id.
Still there are issues when searching with special characters, e.g. '-' or '@' in emails:
max.mustermann@gmail.com returns all clients with gmail.com addresses.

**Comment by ivankristianto** [comment]
@fraunholz I made a PR for this #803 
can you please check?

**Comment by fraunholz** [comment]
I integrated this commit.
Searching for order number works, but it is doing an elasticsearch AND a (slow) standard search.
The search by email finds wrong orders (see screenshot).
![bildschirmfoto 2017-04-18 um 12 00 23](https://cloud.githubusercontent.com/assets/19900773/25125309/af6f58ac-242e-11e7-9f03-c0aeabb32f36.png)

**Comment by ivankristianto** [comment]
@fraunholz let's continue this in issue #802 to keep this thread relevant.

**Comment by chercka** [comment]
Server error log when attempting to index 984 items on staging, including protected content:
```
[Tue Apr 18 11:44:07.191987 2017] [access_compat:error] [pid 47837:tid 140310080325376] [client 173.252.98.86:43055] AH01797: client denied by server configuration: /var/www/vhosts/sitename.com/httpdocs/current/category

[Tue Apr 18 11:44:07.192307 2017] [access_compat:error] [pid 47837:tid 140310080325376] [client 173.252.98.86:43055] AH01797: client denied by server configuration: /var/www/vhosts/sitename.com/httpdocs/current/index.php

[Tue Apr 18 11:44:59.558334 2017] [proxy_fcgi:error] [pid 47837:tid 140310122288896] (70007)The timeout specified has expired: [client 216.27.93.193:42900] AH01075: Error dispatching request to :, referer: http://stage.sitename.com/wp-admin/admin.php?page=elasticpress
```
The Elasticsearch host is set to http://127.0.0.1:9200. Does this need to configured for https??

As a sidenote perhaps, Disabling protected content and hitting sync seems to run ok for 158 items on staging. Produces this error in the server log though. Maybe nothing.
`
[Tue Apr 18 11:43:21.048336 2017] [proxy_fcgi:error] [pid 47731:tid 140310105503488] [client 216.27.93.193:42319] AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/vhosts/sitename.com/httpdocs/releases/20170418145306/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 2222\n', referer: http://stage.sitename.com/wp-admin/admin.php?page=elasticpress`

**Comment by chercka** [comment]
We got admin search to return results once again by removing the filter 'op_wc_shop_order_search_fields' on init:

`add_action( 'init', 'remove_ep_wc_shop_order_search_fields_filter' );
function remove_ep_wc_shop_order_search_fields_filter() {
    remove_filter( 'woocommerce_shop_order_search_fields', 'ep_wc_shop_order_search_fields', 9999 );
}`

What is the reason for this being in EP? If it is only for frontend, then it should be in an is_admin() conditional?

**Comment by tlovett1** [comment]
Hmmm, I'm testing EP with Protected Content and WooCommerce enabled. I am getting orders in search when I search by orderer name.

The reason for that being in EP is to prevent an unnecessary meta query from firing.

**Comment by fraunholz** [comment]
how to disable the fuzziness? I tried several ways but it keeps showing zero or similar results.
That's ok for names but for customer numbers and order numbers we want only direct hits.
