### ISSUE TITLE
WooCommerce Product Filter Plugin Issue

### ISSUE THREAD

**Issue by PrintableCuttableCreatables** [10up/ElasticPress#776]
Having issues using ElasticPress with WOOF WooCommerce Products Filter plugin that I have been using successfully for a year before installing ElasticPress.

With ElasticPress enabled, the filter results show ALL products, unfiltered.
Disabling ElasticPress returns the correct/expected filter results.
I have tested other WooCommerce filter plugins to replace this one, however none of theme seem to work with ElasticPress enabled. Any suggestions to fix this compatibility issue, or recommendations for filter plugins that are compatible with Elastic Press are greatly appreciated!

You can see example "Filter by Theme" menu in Sidebar here: https://stagingcw[dot]printablecuttablecreatables[dot]com

Thank you!

**Comment by allan23** [comment]
Hi @PrintableCuttableCreatables,

Can you let us know what version of ElasticPress, WordPress, Elasticsearch, and WooCommerce you are running on your site?

**Comment by PrintableCuttableCreatables** [comment]
Hi Allan,
Thanks for your reply. I am running the following versions:
ElasticPress: v2.2
WordPress: v4.7.3
WooCommerce: v2.6.14

**Comment by allan23** [comment]
Thanks for the info @PrintableCuttableCreatables.
It appears that WOOF WooCommerce Products Filter is a commercial plugin. While we do strive to make ElasticPress as compatible as possible with third-party plugins, we cannot accommodate all of them. 
This may be something that the plugin author will need to fix on their end in order to be compatible with ElasticPress. I would encourage you to reach out to the author.

**Comment by PrintableCuttableCreatables** [comment]
Hi @allan23 

WOOF also offers a free version of this plugin, which is what I have been using. I have contacted the author, who suggested adding either of the following snippets to the top of the ElasticPress main file before all other functions. Do you think either of these may work?

if(class_exists('WOOF')){
    global $WOOF;
    $serch_arg = $WOOF->get_request_data();
   if(!empty($serch_arg)){
       return;
    }
}

OR this snippet:

 if (isset($_REQUEST['woof_wp_query_args']))
        {
            return;
        }

**Comment by allan23** [comment]
@PrintableCuttableCreatables I am sorry, but this is not a suitable solution. I am afraid that the plugin author will need to do some work to make their plugin compatible.

**Comment by PrintableCuttableCreatables** [comment]
I see- that was my concern. Thank you!

**Comment by PrintableCuttableCreatables** [comment]
@allan23 By any chance do you know of any other Filter plugins that are already compatible with Elastic Press? Thank you!

**Comment by tlovett1** [comment]
@PrintableCuttableCreatables can you email me? taylor.lovett@10up.com

**Comment by kordicpetar** [comment]
The same is with this filtering plugin WooCommerce Product Filter by dzeriho. Also you have problem with official woocommerce brands plugin. Maybe you should consider this as problem from your side also cause Elasticpress is not working well with main brands plugins.

**Comment by kordicpetar** [comment]
Hi there,

Here is official woocommerce brands plugin. It would be great if you can
make ElasticPress compatible with it. Also I am sending you link to product
filter plugin.
https://wetransfer.com/downloads/040e0e11b097a4ab9a646d24d60ac56720190125094101/306e0f743ca0514a619b8b3aad39f3bf20190125094101/0f3f88

Both of it have same problem, when Elasticpress is on, Brands have bug.
Also if Elasticpress is on, in Filter plugin adoptive filter is not working.



Petar Kordić
Agencija za digitalni marketing <petar.kordic@likesandcookies.rs>

 +381 69 18 43 285
 petar.kordic@likesandcookies.rs
[image: LikesAndCookies] LikesAndCookies
<https://www.facebook.com/LikesAndCookies/>
 likesandcookies <https://www.instagram.com/likesandcookies/>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
