### ISSUE TITLE
[Question?] Duplicate posts after 10.000 results in batches.

### ISSUE THREAD

**Issue by kallehauge** [10up/ElasticPress#779]
When running "WP_Query" in some sort of batches, then the results start to be duplicated after `10.000` combined results. It might be something I'm missing but it's pretty normal to run through large data-sets in batches to make sure you do not memory exhaust the server etc.
So when I limit the query to 1.000 results per iteration and it reaches batch-iteration 10+ then the results will just be duplicated from iteration 10.

_The number matches max window size so I'm thinking there is a connection? What I find curious, if this should be the case, is that the results are fetched in batches of `1.000` and should therefor not hit the max window size._

Some example code to illustrate what I'm trying to explain:
```
/**
 * Batch example.
 */
function run_batch_stuff() {
	$batch_stop = FALSE;
	$batch_iteration = 0;
	while( $batch_stop !== TRUE ) {

		$batch_iteration++;
		$the_query = new WP_Query( [
			'post_type'              => [ 'product', 'product_variation' ],
			'post_status'            => 'publish',
			'posts_per_page'         => 1000,
			'paged'                  => $batch_iteration,
			'tax_query'              => $tax_query,
			...
		] );

		// Go through results and do something magical.
		if ( $the_query->have_posts() ) {
			foreach ( $the_query->get_posts() as $post ) {
				// Do something with the post.
			}
		}
		// Stop the while loop if there is no more results.
		else {
			$batch_stop = TRUE;
		}
	}
}
```

**Comment by tlovett1** [comment]
Pushed a fix for this. However, using extremely large result windows might result in some performance issues. We'll address that if it comes up.

**Comment by kallehauge** [comment]
Thank you for the quick reaction @tlovett1 :+1: - Although I'm still wondering if the connection is actually due to the `max window size` since it's 10+ different `WP_Query`s that are all below the previous `10.000` and not 1 large request?

**Comment by tlovett1** [comment]
Let us know if this is still an issue.
