### ISSUE TITLE
Why I can't use elasticpress more effectively 

### ISSUE THREAD

**Issue by ahmed32ali** [10up/ElasticPress#783]
Why can't elastic press provide api to connect to elastic search and get posts with different criteria now  for ex. I can not search for meta, and provide a way to search for users with different roles also searching .

**Comment by ivankristianto** [comment]
Hey @ahmed32ali can you tell me your environment?
WordPress version?
ElasticPress version?
Elasticsearch version?

For searching in post meta, i believe it can be done using EP. But if you need to search with your custom query, all you need is add `ep_integrate` to your WP_Query, see more here: https://github.com/10up/ElasticPress#supported-wp_query-parameters

And for user query, it is not available yet in EP.
