### ISSUE TITLE
Two questions about adding meta data and setting default queries

### ISSUE THREAD

**Issue by sermersooq-webmaster** [10up/ElasticPress#784]
Hi 10up

I want to write a connector to [Polylang](https://wordpress.org/plugins/polylang/) so ElasticPress can be used in a multilingual site. Here comes the two questions:

How do I add additional meta data to ElasticPress? The meta data is not present as a meta data field in WordPress.

How do I add a filter query to every search/query made that searches on previously mentioned meta data?

Thanks in advance!

**Comment by ivankristianto** [comment]
@sermersooq-webmaster 
The additional meta data will automatically added when doing sync.  see this line: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L607

And to hook that as default search, you can change in filter `ep_formatted_args`: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1525

**Comment by sermersooq-webmaster** [comment]
Thanks, was what I was looking for!
