### ISSUE TITLE
Unable to connect to ElasticSearch

### ISSUE THREAD

**Issue by lswale** [10up/ElasticPress#785]
Dear ElasticPress team,

Really looking forward to testing this plugin but I'm struggling to connect to my ElasticSearch instance.

I'm currently using AWS for both my website and my Elasticsearch instance (these are not running on the same server). FW rules are set to allow ALL traffic in and out.

From my web server I can access (using CURL) the ES instance from the command line (with any user) and I can see the access attempts in the ES logs.

Unfortunately, when I enter the host in the ElasticPress plugin I get the following error:

"There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work."

I've tried setting the host to include the port and without:

Without (Debug bar) >>
"cURL error 7: Failed connect to 54.229.60.130:80; Connection refused"

With ":9200" port added >>
"cURL error 7: Failed to connect to 54.229.60.130: Permission denied"

Both the above attempts do not register on the ElasticSearch access logs whereas the command line attempts show.

My ES server: http://54.229.60.130:9200 

Any assistance here would be appreciated. Thanks...

Lee

**Comment by lswale** [comment]
Additional info:

Wordpress: 4.7.3
ElasticPress: 2.2
ElasticSearch: 5.0.1

**Comment by lswale** [comment]
Additional info:

I ran a trace on the Wordpress server whilst updating the ElasticPress host parameter. Without the port specified I noted traffic to the ES server whereas when adding the ":9200" port to the host I see zero packets transmitted to the host. Possibly a bug not picking up the port? Thank you.

**Comment by lswale** [comment]
FYI - I started another Elasticsearch server (AWS) which runs on port 80 and I was able to connect without issues.

**Comment by ivankristianto** [comment]
@lswale it might be issue in firewall. 
But great to hear it work with port 80?
So is your issue solved?
