### ISSUE TITLE
Error connecting to ElasticSearch cloud endpoint

### ISSUE THREAD

**Issue by sjferwerda** [10up/ElasticPress#786]
Thanks for the great plugin. Unfortunately, I've tried connecting to different cloud hosts (Qbox and elastic.co) and I'm getting the "There is a problem with connecting to your Elasticsearch host." error. Looking at the http requests in query monitor I'm seeing:

Qbox
```
cURL error 7: Failed to connect to 34.197.23.4: Permission denied for "GET
https://{xxxxx}@c55eaa9a.qb0x.com:32542/_nodes/plugins"
```

cloud.elastic.co
```
cURL error 7: Failed to connect to 23.23.163.81: Permission denied for "GET
https://{xxxxx}.us-east-1.aws.found.io:9243/_nodes/plugins"
```

and:

Qbox
```
cURL error 7: Failed to connect to 34.197.23.4: Permission denied for "GET
https://{xxxxx}@c55eaa9a.qb0x.com:32542/"
```

cloud.elastic.com
```
cURL error 7: Failed to connect to 50.19.86.80: Permission denied for "	GET
https://{xxxxx}.us-east-1.aws.found.io:9243/"
```

Any suggestions? I assumed that perhaps I had to whitelist my server IP or something like that in the  cloud host (Qbox or elastic.co) config panel, but I don't see any settings like that. I've tried adding the define('ES_SHIELD',{password}) constant to wp-config but that doesn't seem to do anything. I'm using the very latest github ElasticPress plugin version.

Any bit of help would be much appreciated!

Update: I can access my cloud.elastic.co endpoint directly through the browser or using curl at the command line. Just doesn't seem to work through the ElasticPress plugin.

**Comment by sjferwerda** [comment]
I'm starting to think that it's a selinux/firewall issue on my local server. Will update this ticket if that's the case or if I rule that out.

**Comment by sjferwerda** [comment]
Problem solved. The permission denied error was due to my server firewall settings. But I also had to add define( 'ES_SHIELD', '{username}:{password}' ); to wp-config.

**Comment by tw2113** [comment]
Not an issue re-open, I just wanted to say thanks to @sjferwerda quick for the ES_SHIELD tip, as it's what I needed for a project I'm helping out with.
