### ISSUE TITLE
Understanding ElasticPress

### ISSUE THREAD

**Issue by lswale** [10up/ElasticPress#787]
I am new to both ElasticSearch and ElasticPress. I would like to use both in conjunction with Wordpress and AWS S3 (using WP plugin "WP Offload S3") to move any dynamic content away from the local server allowing for auto-scaling using AWS images that contain only the core WP files.

My theory was to create a base image which could be used to spawn new instances using auto-scaling but any changes would be reflected in the new instances as WP is now using S3 and ElasticSearch. I have tested this by creating 2 servers both running the same configuration (ElasticPress and S3) and then making a small modification on one of the severs. I was hoping, as the changes are not made locally (or so I thought) that the 2nd server would reflect the changes. Is my theory incorrect? Your input welcome here. Thanks.

**Comment by lswale** [comment]
Some additional info:

I thought I'd found the issue > I was using 2 different domains to access the two Wordpress servers and therefore changes applied on server #2 are saved on the elastic search server under a new index based on the domain. Hopefully in a LIVE environment where servers share the same domain this would not be an issue, however, I wanted to test updating a record directly on the ElasticSearch stored data to see if that was reflected on the website. Unfortunately it doesn't. Is this because Wordpress is still taking the data from the Database (I noticed you still need to maintain a local DB and records are stored there also even with ElasicPress running) -OR- is this a caching issue?

**Comment by ivankristianto** [comment]
@lswale I'm not getting how is your server configured.
I suggest you configured your server this way:
2 webservers (load balanced)
2 database server ( master-slave replication )
1 cluster of elasticsearch
1 Amazon S3 Bucket

With that setup you can setup better autoscaling.

**Comment by lswale** [comment]
@ivankristianto 
I think my question is: can ElaseticSearch be used as a primary data store i.e. eliminating the requirement for a conventional SQL database? From other forums it appears ES may be more of an analytics tools as opposed to primary storage>? May be this is developing as we speak... >?

**Comment by ivankristianto** [comment]
@lswale 
I believe WordPress still and will use MySQL as the primary database, and as I know there is no discussion about changing it in the near future.
What is ElasticPress  do is seamlessly integrate the WordPress query function to ElasticSearch, but will not eliminate MySQL database.
