### ISSUE TITLE
ElasticPress Indexing Issue (Pages)

### ISSUE THREAD

**Issue by stevensjn** [10up/ElasticPress#788]
Hi there,

I've been working with ElasticPress for a couple months on and off, and have been running into difficulties with finding indexed pages on our site. 

When indexing via the web admin GUI, of the 224 pages we have, only 60 are indexed. When indexing via WP CLI if I specify multiple post_types I get the same experience - 60 pages are indexed. If I use WP CLI to index only the pages post_type, I get then get all 224 pages indexed. I can then add the other post_types and seemingly create a proper full index of the content I would like to be queried.

How can I best help to identify the cause of this index issue? I would be glad to provide any details that could help.

Regards,

Jacob Stevens

**Comment by ivankristianto** [comment]
Hey @stevensjn,
first you can check how many documents are indexed in elasticpress.
Run this command in WP-CLI:
`wp elasticpress stats`

I think you might have error while indexing, can you turn on WP_DEBUG & WP_DEBUG_LOG to see if there is an error in debug.log?

**Comment by stevensjn** [comment]
====== Stats for: huroncountyca-1 ======
Documents:  933
Index Size: 4.22 MB
====== End Stats ======

The debug.log does not show any errors. There are a few notices about deprecated contact form 7 calls.

Here are my 'public' and 'searchable' post_types:

Array
(
    [0] => post
    [1] => page
    [2] => attachment
    [3] => news
    [4] => tender
    [5] => job
    [6] => facebook_events
    [7] => tribe_venue
    [8] => tribe_events
    [9] => tribe-ea-record
)

**Comment by ivankristianto** [comment]
@stevensjn from the stats it seems normal.
Did you enable feature "protected content" and try reindexing? And see if you can search your posts/pages.

**Comment by stevensjn** [comment]
I'll provide a report on my indexing results using "wp elasticpress" from the command line and the sync process in ElasticPress separately. Perhaps this will help narrow the scope of my problem.

Of the post_types listed above are there some that ElasticPress will ignore by default, or does it index all public searchable post_types by default? The documentation on this is not clear (copied below).

"Filter posts by post type. any will search all public post types. WP_Query defaults to either post or any if no post_type is provided depending on the context of the query. This is confusing. ElasticPress will ALWAYS default to any if no post_type is provided. If you want to search for post posts, you MUST specify post as the post_type."

- js

**Comment by mikekosulin** [comment]
Try to refresh page and unpause scanner.

**Comment by ivankristianto** [comment]
From what I see, there is an issue while doing an indexing that make it stop on 60 posts.
I like to troubleshoot this issue more deeper.
Can you please install the EP Troubleshooting plugin on your staging site and send us the JSON file?
https://github.com/allan23/ep-troubleshoot/archive/master.zip

Instructions for this plugin can be found here: https://github.com/allan23/ep-troubleshoot/blob/master/README.md

**Comment by stevensjn** [comment]
Here is the requested document:

[ep-troubleshoot.zip](https://github.com/10up/ElasticPress/files/945345/ep-troubleshoot.zip)

**Comment by stevensjn** [comment]
By syncing via plugin I get 956 records.  We have a page titled "Huron County Cycling Strategy" which is not returned at all. I have double checked in Kibana and the page is not in the index. Kibana shows 50 records of post_type "page" after this sync.

Syncing via "wp elasticpress" at the command line (one post type at a time) I get the 837 records if I sync all the post_types listed in the EP-TroubleShoot plugin's report. ([results shared in the attached file.](https://github.com/10up/ElasticPress/files/945384/ElasticPressIndexingResults.txt))

The page "Huron County Cycling Strategy" immediately shows up as the top result of a search on the website or in Kibana afterindexing at the command line.

I'll continue to do whatever I can to help.

**Comment by ivankristianto** [comment]
@stevensjn I saw your index log file.
You have an error in your shortcode: `subpages_unqprfx_shortcode`
can you fix the shortcode and try to reindex?

**Comment by ivankristianto** [comment]
I'm closing this issue. Feel free to re-open if you have any questions.

**Comment by irakligeek** [comment]
I'm having the same issue, none of my pages are being indexed, any solutions ?

**Comment by ivankristianto** [comment]
@irakligeek please open a new issue and describe your setup there, so we can help you analyze it better. thanks.
