### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by RichElse** [10up/ElasticPress#789]
Hi

Does anyone know if there is a way to index featured images, or if there is a maintained plug-in?

I've found the below but it doesn't seem to be actively maintained:

[Elastic Press Featured Image](https://github.com/rveitch/elasticpress-featured-image-url)

Thanks!

Rich

**Comment by ivankristianto** [comment]
Hey @RichElse 
We may add this in the future release. 
But for now you can add filter to make it indexable by elasticpress.

You might want to look into:
ep_config_mapping,  ep_prepare_post, and ep_search_fields

**Comment by Jaygangkun** [comment]
I am going to get feature image url of product.
The elastic search returns feature image id instead of image url.

How can I do it?

**Comment by ikappas** [comment]
For anyone interested, I am sharing the following snippet that works around the issue of indexing thumbnail urls (but can be adjusted to inject anything into the meta fields for that matter):
```php
/**
 * Inject metadata during elastic search indexing.
 *
 * @param null|array|string $value     The value get_metadata() should return - a single metadata value,
 *                                     or an array of values.
 * @param int               $object_id Object ID.
 * @param string            $meta_key  Meta key.
 * @param bool              $single    Whether to return only the first value of the specified $meta_key.
 *
 * @return null|array|string
 */
function dw_indexing_metadata_injector( $value, $post_id, $meta_key, $single ) {

	// Determine whether we are currently indexing.
	if ( function_exists( '\ElasticPress\Utils\is_indexing' ) && \ElasticPress\Utils\is_indexing() ) {

		if ( '' === $meta_key || 'thumbnail_url' === $meta_key ) {

			// Fetch the thumbnail url.
			$thumbnail_url = get_the_post_thumbnail_url( $post_id, 'post-thumbnail' );

			if ( '' === $meta_key ) {

				// Get the current meta cache.
				$meta_cache = wp_cache_get( $post_id, 'post_meta' );

				// Now inject our value in the cache.
				$meta_cache['thumbnail_url'] = array( $thumbnail_url );

				// Assign back modified cache.
				wp_cache_set( $post_id, $meta_cache, 'post_meta' );

			} else {

				// Directly assign our value.
				$value = $thumbnail_url;

			}
		}
	}

	return $value;
}

add_filter( 'get_post_metadata', 'dw_indexing_metadata_injector', PHP_INT_MAX, 4 );
```

**Comment by shmaltz** [comment]
@ikappas Thanks for the snippet! Does it still work with the latest version of EP?

And is there a way to display the image in the autosuggest results?
