### ISSUE TITLE
ElasticPress and AWS connection issues

### ISSUE THREAD

**Issue by glagonikas** [10up/ElasticPress#790]
Hello,

I've been trying to integrate your plugin with Amazon ElasticSearch, however i keep getting 403 errors.

I've tried the following
1. Enable "Allow open access to the domain"
This gives me an error "User: anonymous is not authorized to perform: es:ESHttpGet on resource:"
2. Enable "Allow access to the domain from specific IP(s)"
This gives me an error "User: anonymous is not authorized to perform: es:ESHttpGet on resource:"
3. Enable "Allow or deny access to one or more AWS accounts or IAM users"
I did this in conjunction to define( 'ES_SHIELD', 'username:password' ); I created an IAM user and granted access but i got "Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic "

I'm a bit lost here, am i missing any configuration options?

Thanks in advance

**Comment by ivankristianto** [comment]
@glagonikas 
I can use Elasticsearch on Amazon AWS just fine.
I'm using the settings "Allow access to the domain from specific IP(s)"
and to find out my outgoing ip from my server, i use this command:
`dig +short myip.opendns.com @resolver1.opendns.com`
and whitelist that ip.

**Comment by glagonikas** [comment]
Hi @ivankristianto ,

I've tried this as explained above (point 2), but i get this error from AWS. I have installed the debug plugin, then white-listed my ip and run the same request you make, but i get the same error.

I'm using version 5.1, can i confirm that's the one you use also?

**Comment by ivankristianto** [comment]
Yes i'm using version 5.1 as well.
where do you hosted your WordPress? amazon aws?

**Comment by glagonikas** [comment]
I'm hosting this outside of AWS and i can't limit to specific IP as we have horizontal scaling without fixed IP addresses. I therefore need to use ES_SHIELD.

Tried the following:

1. Created a new IAM user
2. Added the following policy
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::XXXXXXXXXXX:user/ElasticPress",
          "arn:aws:iam::XXXXXXXXXXX:root"
        ]
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:eu-west-2:XXXXXXXXXXX:domain/*"
    }
  ]
}`
3. Set define( 'ES_SHIELD', 'ElasticPress:Password' ); - Didn't work
4. Set define( 'ES_SHIELD', 'AccessKeyID:AccessKeySecret' ); - Didn't work

Any ideas?

**Comment by glagonikas** [comment]
By the way, i'm using the PaaS service from AWS, not sure if that was obvious from my previous messages

**Comment by glagonikas** [comment]
I think the issue is to do with the Shield plugin (X-Pack). According to https://forums.aws.amazon.com/thread.jspa?threadID=248200 it's not supported on the AWS PaaS which explains why the plugin works when the policy is allowed to all.

I will test by installing ES on a stand-alone instance.

I don't think that's a bug with your plugin, but it'd be good to update https://github.com/10up/ElasticPress#security as the "shield" has now been renamed and the URL is updated. Also it would be good to mention that X-Pack is currently not supported by AWS Elastic Search service.

**Comment by tlovett1** [comment]
If there is an issue with ElasticPress, we are happy to provide support. However, we don't currently provide support for setting up Elasticsearch. We recommend looking at the installation documentation. We also provide ElasticPress.io as a managed Elasticsearch instance that "just works".

**Comment by joehoyle** [comment]
FYI I did get a fix for this, and though it's somewhat up to the ES service, I thought I'd share how to make ElasticPress work with the AWS Elasticsearch Service, as it's not uncommon. 

I should also say that IP based access that AWS Elasticsearch _does_ support is really no good for decent infrastructure design, instead the IAM / role based approach is far superior.

To do authentication with Elasticsearch using IAM roles, you have to add AWS v4 signature headers to the requests being sent to Elasticsearch. As ElasticPress uses the inbuilt `wp_remote_*` WordPress API, you can't use the standard SignatureV4 signing available to you in the AWS SDK, instead you have to proxy the header across. 

As there's also no catch-all ElasticPress specific filter, you need to filter _all_ remote requests, filtering out the ones you don't want. All in all, the below should generate valid signatures and provide authentication for IAM / Role based ES auth:

```php
namespace ElasticPress_Integration;

use GuzzleHttp\Psr7\Request;
use Aws\Signature\SignatureV4;
use Aws\Credentials;

add_filter( 'http_request_args', __NAMESPACE__ . '\\on_http_request_args', 10, 2 );

function sign_wp_request( array $args, string $url ) : array {
	$host = parse_url( $url, PHP_URL_HOST );

	if ( EP_HOST !== $host ) {
		return $args;
	}
	$request = new Request( $args['method'], $url, $args['headers'], $args['body'] );
	$signer = new SignatureV4( 'es', HM_ENV_REGION );
	if ( defined( 'ELASTICSEARCH_AWS_KEY' ) ) {
		$credentials = new Credentials\Credentials( ELASTICSEARCH_AWS_KEY, ELASTICSEARCH_AWS_SECRET );
	} else {
		$credentials = new Credentials\InstanceProfileProvider();
	}

	$signed_request = $signer->signRequest( $request, $credentials );
	$args['headers']['Authorization'] = $signed_request->getHeader( 'Authorization' )[0];
	$args['headers']['X-Amz-Date'] = $signed_request->getHeader( 'X-Amz-Date' )[0];
	return $args;
}
```

**Comment by ivankristianto** [comment]
Thanks @joehoyle,
I create a wiki for this: https://github.com/10up/ElasticPress/wiki/Connect-from-Amazon-Web-Service

**Comment by jayhill90** [comment]
Hi @joehoyle was wondering if you had any suggestions in getting the above code snippet to work properly. I had attempted to drop that filter and function into my theme's functions.php file. The IAM user access/secret key that I had setup had full AWS access but I was unable to connect to my AWS ElasticSearch cluster. Was wondering if you had any suggestions for helping get it to work. Thanks in advance.

**Comment by JJPragmatic** [comment]
I dont think this authrisation works with version 3.6 of the plugin, would it be possible to get the wiki updated with a current solution?

**Comment by KalmanG** [comment]
@ivankristianto The wiki link is broken. We are working on connecting to AWS. Is there a replacement or any other docs?

**Comment by joehoyle** [comment]
@roborourke I think you recently discovered there might be an EP header getting in the way of Authorization/AWS signed params?

**Comment by roborourke** [comment]
Correct, EP adds an “EP-Search-Term” header containing the raw search term value for search queries. The value isn’t escaped though - headers have to be ASCII so must be mime encoded. This is why request signing fails at any rate.

In Altis we just removed the header for now as I think it’s specific to elasticpress.io

**Comment by sovabarmak** [comment]
@roborourke  can you tell what need to do, to allow plugin to work with amazon aws?
