### ISSUE TITLE
WP can't find ES server but curl  -XGET 'localhost:9200/?pretty' works...

### ISSUE THREAD

**Issue by sergionader** [10up/ElasticPress#791]
Hello, 

I have a ubuntu server 16.04 on AWS -- this is not an ES instance, but a common one. 
$wp_version = '4.6.4';
Elastic Search 5.3.0
Elastic Press 2.2

The EP admin page says "There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work." no matter what I place in the wp-config.php file: localhost, 127.0.0.1, the internal IP or the public IP -- all of the with http:// and the port number :9200

The command `wp elasticpress index` returns: 
`Error: Unable to reach Elasticsearch Server! Check that service is running.`

So we may think that ES server is not running. However, 
`curl  -XGET 'localhost:9200/?pretty'`
returns:
```
{
  "name" : "JBhJAZ7",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "6tPYCmYOSg-m9vdT7i9fRg",
  "version" : {
    "number" : "5.3.0",
    "build_hash" : "3adb13b",
    "build_date" : "2017-03-23T03:31:50.652Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}

```
More than that: if I edit a post, it will show edited on the search result. 

In other works, it works, but WP does not recognize it. 

I read all the posts about this issue, tried all of them and no one has worked. 

Thanks!!!!!!

Sergio

**Comment by ivankristianto** [comment]
Hey @sergionader 
Can you try with Elasticsearch version 5.2.0 ?
Because ElasticPress is not compatible with version 5.3.0

**Comment by sergionader** [comment]
Thanks for the reply, Ivan!

I deleted version 530 and then
```
 **wget** 'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.0.zip'
**cd** /elasticsearch-5.2.
**./bin/elasticsearch -d -p pid**
ps aux | grep elasticsearch
  0:08 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/home/ubuntu/es/elasticsearch-5.2.0 -cp /home/ubuntu/es/elasticsearch-5.2.0/lib/elasticsearch-5.2.0.jar:/home/ubuntu/es/elasticsearch-5.2.0/lib/* org.elasticsearch.bootstrap.Elasticsearch -d -p pid
**curl  -XGET 'localhost:9200/?pretty'**
{
  "name" : "DKoc15x",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "2v8ZXiMLRpC8LRpZHhSJjw",
  "version" : {
    **"number" : "5.2.0",**
    "build_hash" : "24e05b9",
    "build_date" : "2017-01-24T19:52:35.800Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.0"
  },
  "tagline" : "You Know, for Search"
}
```

My wp-config.php shows:
`define( 'EP_HOST', 'http://localhost:9200' );`

However, I still see "There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work."

Any ideas? 

Thanks

**Comment by ivankristianto** [comment]
@sergionader 
can you check with `http://127.0.0.1:9200` ?
And is the elastisearch and your webserver in the same EC2 instance?

**Comment by sergionader** [comment]
Thanks for the reply. 
I changed it to http://127.0.0.1:9200, but the error is still there. 
Yes, the web server, WordPress and ES are in the same ec2 instance. 
Thanks

**Comment by tlovett1** [comment]
Hey @sergionader if there is an issue with ElasticPress, we are happy to provide support. However, we don't currently provide support for setting up Elasticsearch. We recommend looking at the [installation documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html). We also provide [ElasticPress.io](https://elasticpress.io) as a managed Elasticsearch instance that "just works".
