### ISSUE TITLE
Queries not running when upgrading Elastic from 2.3.1 to 5.2.2

### ISSUE THREAD

**Issue by leeroyrose** [10up/ElasticPress#793]
Upgrading elastic from 2.3.1 and queries won't run. 

Error message is:
`
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "field [post_date_gmt] is of type [indexed,tokenized], but only numeric types are supported.",
                "line": 1,
                "col": 1
            }
        ],
`

Query is:

[query.txt](https://github.com/10up/ElasticPress/files/889579/query.txt)

WordPress version: 4.7.3
Elasticpress version: 2.2.1
Elastic version: 5.2.2

Elastic is hosted on cloud.elastic.co.

**Comment by ivankristianto** [comment]
@leeroyrose did you run reindex after upgrading elastisearch?

**Comment by leeroyrose** [comment]
Yes, I switched server when doing the change, so I had to re-index anyway

**Comment by ivankristianto** [comment]
Might be related to: https://github.com/10up/ElasticPress/issues/625
let me know if you can try with wp-cli reindexing:
`wp elasticpress index --setup`
and see if the issue has been fixed

**Comment by leeroyrose** [comment]
I managed to solve this by deleting and reinstalling the plugin. I have to upgrade a few production sites with the new setup, so i'll be sure to try the wp-cli approach on those.

**Comment by tlovett1** [comment]
Somehow the index failed. Not sure exactly what happens. EP asks ES for the version and sends the mapping accordingly. If it sent the 5.0+ mapping to a 2.x instance, the mapping would fail.
