### ISSUE TITLE
Seeking advice on theme unit testing/mocking EP

### ISSUE THREAD

**Issue by crazyjaco** [10up/ElasticPress#796]
Hi!

I work on a very high traffic site with a great deal of content that requires ElasticPress to prevent the database from crashing.

In adding unit tests (default WordPress) we have discovered that we get several errors whenever we created a test post in a unit test for our theme. I believe this is from ElasticPress trying to index the new post, but we don't have an elasticsearch instance setup for our local dev environments. Is there some currently established way to mock EP? Or is there a better strategy that is commonly used in this instance?

Any feedback is very much appreciated.

Thank you!

**Comment by tlovett1** [comment]
I would just filter to prevent that post type from being indexed: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-config.php#L144

Out of curiosity, what website is this for?

**Comment by crazyjaco** [comment]
Ah, thanks. I'll give that a shot.
