### ISSUE TITLE
npm package for reactjs in the future ?

### ISSUE THREAD

**Issue by adalidda** [10up/ElasticPress#797]
Hi,

We love ElasticPress plugin for Wordpress. It's fast and very efficient for the search on our wordpress website. 

We would like to do the same search from our Reactjs website. Any development of elasticpress npm package in the future ?

Elasticpress is used on http://media.adalidda.net

We would like to use it on http://adalidda.net  too.

Thank You
Adalidda

**Comment by ivankristianto** [comment]
Hey @adalidda thank you for your feedback.
ElasticPress has dependency to WordPress and won't be a npm package.
