### ISSUE TITLE
sort the search results by date desc

### ISSUE THREAD

**Issue by dogumobile** [10up/ElasticPress#799]
hello, I am trying out the plugin and it works wonderfully, however the results are not sorted according to date. I suppose I have to use some kind of a filter to sort the results by date. but I am not sure where and how to use a filter that would sort the search results.. any advices?

**Comment by ivankristianto** [comment]
Hey @dogumobile can you give a little bit more details?
Where do you try to do the search? is it in front or admin area?
And can you tell us your WP Version and Elasticsearch version?

**Comment by dogumobile** [comment]
hello ivan, thanks for fast reply!

the search is in the front, the search that a visitor does when he/she is trying to find the blog post needed. I have a huge database of posts. my wordpress version is the latest version. the elasticsearch version I dont know because my server master installed it for me but I think it is also the latest version. the plugin works, the search uses the elastic index but the results are not sorted by date. the date is very important for the relevancy of my posts. so I need to display the results in post date DESC. any directions would be great!

**Comment by ivankristianto** [comment]
By default the search results will be ordered by relevance (by keyword) and then sort by date.
can you give me the link to your search result?

**Comment by allan23** [comment]
@dogumobile, for orderby filters, please see my reply here: https://github.com/10up/ElasticPress/issues/795#issuecomment-293667229

**Comment by dogumobile** [comment]
thanks @allan23 
thanks @ivankristianto 

allan23's solution works
