### ISSUE TITLE
VIP Go?

### ISSUE THREAD

**Issue by keg** [10up/ElasticPress#800]
Hi, this is a general question and not an issue, I'm curious if anyone is running this on VIP GO?

Thanks!

**Comment by tlovett1** [comment]
No one is yet. If you are going to attempt to get the plugin on VIP, 10up would be happy to provide any assistance we can.

**Comment by keg** [comment]
Thanks, Taylor, [we've](https://github.com/dfmedia/) got plans to submit it for a formal review soon.

**Comment by tlovett1** [comment]
@keg mind shooting me an email? taylor.lovett [at] 10up.com

**Comment by jasonbahl** [comment]
@tlovett1 hey, we submitted to VIP and got a list of "blockers" back. Emailing you to discuss. 

Thanks!
