### ISSUE TITLE
starting the indexing process from crontab

### ISSUE THREAD

**Issue by dogumobile** [10up/ElasticPress#804]
hello, is there a way so that we can start the indexing process from crontab?
so that the index will refresh itself in defined intervals without our manual intervention?

**Comment by ivankristianto** [comment]
What would you want to re-indexing it with cron?
EP designed to incrementally update as you create/update your posts.

**Comment by dogumobile** [comment]
my posts enter into the database directly. not from within the admin area of wordpress. so it would be good to be able to run the indexing process to index the new posts from time to time automatically..

**Comment by ivankristianto** [comment]
In that case you can setup cron and run it with wp-cli, here is the command: `wp elasticpress index`

**Comment by dogumobile** [comment]
will this command delete the old index and build a new index or will it continue to add on the previous index?

**Comment by ivankristianto** [comment]
No it doesn't delete the old index. But it does re-indexing whole content.

**Comment by dogumobile** [comment]
is there separate commands to 
1) delete the whole index and re-index everything
2) add only the non-indexed post on top of the index

**Comment by ivankristianto** [comment]
To delete and reindexing you can run this command: `wp elasticpress index --setup`
But there us no command to add only the non-indexed post

**Comment by dogumobile** [comment]
thanks for the fast assistance @ivankristianto
