### ISSUE TITLE
different weights for title and contents

### ISSUE THREAD

**Issue by dogumobile** [10up/ElasticPress#805]
i did a search but couldnt find a solution. how can we set different weights for title and post contents?

**Comment by ivankristianto** [comment]
Hey @dogumobile currently it's not possible to have different weight for specific fields. interest in PR?

**Comment by dogumobile** [comment]
what is PR?

**Comment by ivankristianto** [comment]
PR = Pull Request.
If you can work on a solution for this issue and submit it as Pull Request.

**Comment by dogumobile** [comment]
ok. i will

**Comment by tlovett1** [comment]
Something like this:

```php
add_filter( 'ep_search_fields', function( $args ) {
	unset( $args[ array_search( 'post_title', $args ) ] );
	$args[] = 'post_title^5';

	return array_values( $args );
} );
```
