### ISSUE TITLE
post_content does not contain post HTML content

### ISSUE THREAD

**Issue by bliles** [10up/ElasticPress#806]
Is it possible for $post->post_content to contain the HTML content of the post? I can understand why you might not want to return the HTML content since you want to index the visible text.

**Comment by myworkpool** [comment]
The workaround way for me is after you have searched you will get the Post ID.

Then, use that in normal WordPress loop   get_posts( $ID )

**Comment by ivankristianto** [comment]
@bliles i don't think that would be good to include the html in the index. it will confuse the index for your keyword with html class/tag.

**Comment by bliles** [comment]
I thought that might be the case, just wanted to confirm the best approach, get_post is what I used and that worked great. Thank you.
