### ISSUE TITLE
Build the elasticsearch url in Rest  from WP_Query

### ISSUE THREAD

**Issue by myworkpool** [10up/ElasticPress#807]
Is there a way to build the url in REST API form that we can use it in other app Rest calling.

e.g.  sending a WP_Query   of something and it return as'

http:/localhost:9200/__indice__/post/34223?pretty

**Comment by ivankristianto** [comment]
You could definitely create a plugin to extend the wp-api, then do the wp_query and return it in json format.
But this is not something EP would do.

**Comment by myworkpool** [comment]
May be we understand in a wrong small way.

Is there a way to catch the data post into the elasticsearch server?

**Comment by myworkpool** [comment]
Answer to myself: 

Use this snippet code in your <theme>/functions.php  or create a new plugin

http://www.hinnerk-altenburg.de/weblog/wordpress-filter-hook-logging-debugging-wp_http-requests/#.WPd6glOGPdQ

p.s. to create a new plugin,  go to wp-content/plugins   folder and create a new folder. Then create a new file with the code snippet from above.   Then tell WP this is my plugin by insert the text in the top of the file (after <?php ):  

//Plugin Name:  YOUR NAME

use double //  for comment in php zone

**Comment by tlovett1** [comment]
ElasticPress integrates with WP_Query. All you need to do is hook in to ensure ElasticPress integrates with REST queries (`ep_integrate => true`).
