### ISSUE TITLE
[Network] Syncing from dashboard: 'the_content' filters may not be run appropriately for subsites

### ISSUE THREAD

**Issue by brocheafoin** [10up/ElasticPress#810]
Hi!

We have a multisite network. In such a case, ElasticPress's settings are added to the Network Settings area, which is fine. What is less fine is what happens when performing a batch sync from there, which looks like this:

1. Find the first unfinished subsite in the queue
2. switch_to_blog()
3. Get posts
4. For each post:
    1. ep_prepare_post()
    2. Add to EP index queue
5. ep_bulk_index_posts()
6. Repeat until queue empty

The problem is at step 4.1. Here:

```php
$post_args = array(
	'post_id'           => $post_id,
	// [...]
	'post_content'      => $this->prepare_text_content( apply_filters( 'the_content', $post->post_content ) ),
	// [...]
);
```

Since this is run in the main site, the active plugins and theme may differ from those in the subsite, some of which may hook into 'the_content' to modify or add to it. End result: what's sent to the index is not what's visible to the readers of the subsite. Our specific case: a page builder that hooks in 'the_content' to add its output. The page builder is not active in the main site, so the page builder contents of all subsites is not indexed.

I'm not sure there's an easy way to fix this (I'll think about it) but I wanted to bring this to your attention. Thanks!

**Comment by tlovett1** [comment]
Yep, this is a problem. I'm fine with a filter in `prepare_text_content` that let's you disable applying the content filter. Want to submit a PR?

**Comment by brocheafoin** [comment]
Thanks for the answer! Disabling `the_content` filter only solves half the problem, though. There's no way to add the hooks from a subsite's active plugin or theme if this plugin or theme is not active in the main site.

**Comment by tlovett1** [comment]
Unfortunately, the only way to accomplish this is using WP CLI to loop through sites and run a sync individually.

**Comment by brocheafoin** [comment]
My situation is peculiar in that we're running a network, but the sysadmin won't give us shell access, so WP CLI is not an option. As I said, I'm not sure there's an easy way to fix this, but I had a few shower thoughts about it. Since the syncing process is controlled by polling admin-ajax.php, would it be possible, when a subsite is done indexing, to send the "start_batch" action to its subsite's admin_ajax.php and therefore inherit its context (theme, plugins)? I may take a crack at it in the coming weeks.

**Comment by ivankristianto** [comment]
@brocheafoin that would be a hardway to do it. I suggest you let the web admin run it for you.

**Comment by brocheafoin** [comment]
@ivankristianto yeah you're right. I'm probably alone in my situation. Let's not write too much single-use code. Thanks!
