### ISSUE TITLE
Using this pluggins don't recocer any from the Database

### ISSUE THREAD

**Issue by mingotaku** [10up/ElasticPress#814]
Hello.
Using this pluggin made me some missfortuned. 
Firstly, this pluggin required Elastic Search 5.2.0, when the 5.3.1 version is already released.

Moreover, the pluggin doesn't work correctly. All the data from my WP are correctly indexed, but when I make some search, all the results crome from the MySQL DDBB from Wordpress, instead of the Elastic Search.

I am using elastic Search and WP on localhost.

Why colud it be?
Thanks you so much!

**Comment by ivankristianto** [comment]
You need to downgrade your Elasticsearch to version 5.2.x as we are not support version 5.3.x yet.
