### ISSUE TITLE
Multiple orderby not working

### ISSUE THREAD

**Issue by colis** [10up/ElasticPress#815]
I'm using this orderby clause

`'orderby'        => array(`
`'meta.accommodation_type.raw' => 'DESC',`
`'title' => 'ASC',`
`'relevance' => 'DESC'`
`)`

but basically only the first orderby property affects the results. Any thoughts?

**Comment by ivankristianto** [comment]
Hey @colis 
i tried it with woocommerce, sort by multiple orderby and it's working.
here is my WP_Query:

```
$query = new WP_Query(
		array(
			'ep_integrate'   => true,
			'post_type'      => 'product',
			'post_status'	=> 'publish',
			'order'	=> 'DESC',
			'orderby' => array( 'meta._regular_price.double' => 'desc', 'title' => 'desc' )
		)
	);
```

Result:
Test A Product 10000
Loving By Henry Green 122.5
**Mushrooms 120
A Milk ‐ 1 Pint 120**

AND
```
$query = new WP_Query(
		array(
			'ep_integrate'   => true,
			'post_type'      => 'product',
			'post_status'	=> 'publish',
			'order'	=> 'DESC',
			'orderby' => array( 'meta._regular_price.double' => 'desc', 'title' => 'asc' )
		)
	);
```
Result:
Test A Product 10000
Loving By Henry Green 122.5
**A Milk ‐ 1 Pint 120
Mushrooms 120**
