### ISSUE TITLE
Wordpress MU Domain Mapping + Multisite + WP_Query with sites array fails to return all results when used on a network site

### ISSUE THREAD

**Issue by catsr** [10up/ElasticPress#817]
I have a multisite set up with two network sites:

- ID 1 = the main site with which the multisite install was spun up
- ID 4 = a second network site in the network

Without the _MU Domain Mapping_ plug-in enabled, cross-site queries work as expected.

However, when enabling the MU Domain Mapping plug-in, and configuring a different TLD to point at network site with ID=4, the following query - run from within network site 4 - fails to return results from network site 1:

```
$q = new WP_Query( array(
    'ep_integrate' => true,
    'sites' => array( 1, 4 )
) );

```

A few additional observations:

- The same exact query, when run from within network site 1, runs correctly
- If `'all'` is used instead of `array(1, 4)`, the query runs correctly from within network site 4 as well
- If `array(1)` or `array(4)` is used, when run from within network site 4, the query also correctly returns results from site 1 or 4, respectively

Is this a bug, or is this a specific limitation in the context of a multisite domain mapping scenario?

**Comment by ivankristianto** [comment]
Can you send us the elasticsearch query post?
you can get using https://github.com/10up/debug-bar-elasticpress
it's in top right corner. See my screenshot.
And please paste here the query args, query bodu and query result.
![screen shot 2017-04-28 at 21 48 54](https://cloud.githubusercontent.com/assets/656006/25533960/8aeebda2-2c5c-11e7-944b-257495a923cf.png)

**Comment by catsr** [comment]
Thanks for the quick response!

Checking the ElasticPress debug log, I was able to find what was going on. Posting the results (and a solution) here for posterity (or in case there is anything that the ElasticPress plug-in could do in the future to automate this).

> **TL/DR:** The problem is that a domain-re-mapped network site names its own ElasticSearch index differently than other sites in the network. One solution is to create an ElasticSearch index alias.

It looks like this is caused specifically by the way **Site 4** (which has a re-mapped TLD) references its own index by name.

Domain names below were modified for purposes of this post, but reflect the context correctly:

- **Site 1** still serves at its original domain, `example.com`
- **Site 4** would normally serve at `site4.example.com` based on multisite sub-domain settings, but was mapped, via WPMU Domain Mapping plug-in, to serve at `site4.com`

The logs reveal the following:

**Site 1** runs the query as follows, i.e. it references the index of Site 4 by its original name `site4examplecom-4`. This reflects the original location of Site 4 at `site4.example.com`, and works fine:

`https://[ELASTIC_SEARCH_SERVER_URL]/examplecom-1,site4examplecom-4/post/_search
`
```
Query Response: 200
"hits": {
        "total": 2,
        ...
}

```
However, **Site 4** runs the query as follows, i.e. it references its own index by the name it believes it should have based on its own re-mapped domain, i.e. `site4com-4`. This reflects the re-mapped location of Site 4 at `site4.com`, and does not work, because the index does not exist under that name:

`URL: https://[ELASTIC_SEARCH_SERVER_URL]/examplecom-1,site4com-4/post/_search`

```
Query Response: 400
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index",
                "resource.type": "index_or_alias",
                "resource.id": "site4com-4",
                "index_uuid": "_na_",
                "index": "site4com-4"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "site4com-4",
        "index_uuid": "_na_",
        "index": "site4com-4"
    },
    "status": 404
}
```

One solution is to add a respective alias to the ElasticSearch index, e.g. via
```
POST /_aliases
{
    "actions" : [
        { "add" : { "index" : "site4examplecom-4", "alias" : "site4com-4" } }
    ]
}
```

After this, both Site 1 and Site 4 correctly return the same 2 ElasticSearch hits with a 200 response code.
