### ISSUE TITLE
Hook into a taxonomy term update and post meta update

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#82]
Currently if a taxonomy term is updated, ElasticPress does not know to re-index all posts that have that taxonomy term associated with it - this could be a major problem.

**Comment by tlovett1** [comment]
Same thing with post meta.

**Comment by ChrisWiegman** [comment]
@dkotter After reviewing the two attached issues and their related PRs I'm going ahead and closing this issue as it appears to be fixed. Some testing seems as if it is working as well.
