### ISSUE TITLE
Custom WP_Query force ep_integrate to true for WooCommerce product query

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#820]
This is my WP_Query:
```
$query = new WP_Query(
		array(
			'ep_integrate'   => false,
			'post_type'      => 'product',
			'post_status'	=> 'publish',
			'order'	=> 'DESC',
			'orderby' => array( 'meta._regular_price.double' => 'desc', 'title' => 'asc' )
		)
	);
```

Event though I specifically put `'ep_integrate'   => false`, it will be forced to true.
Here is the code that cause it: https://github.com/10up/ElasticPress/blob/develop/features/woocommerce/woocommerce.php#L362

**Comment by pcfreak30** [comment]
I had to add a pre post hook to override this and set ep_integrate to false after this code.
