### ISSUE TITLE
Not getting thumbnail_image

### ISSUE THREAD

**Issue by javierZippia** [10up/ElasticPress#828]
Since the last update seems its not adding post meta thumbnail_image to ES  with the CLI tool. Always seting post_meta empty

**Comment by ivankristianto** [comment]
I don't experience your issue on my default local installation.
Can you post one of post index from elasticsearch?
You can do it by:
1. Install Sense for Chrome: https://chrome.google.com/webstore/detail/sense-beta/lhjgkmllcaadmopgmanpapmpjgmfcfig?hl=en
2. run this in body post:
```
POST /**{your-index-name}**/post/_search
{
    "query" : {
        "term" : { "ID" : **PostID** }
    }
}
```

**Comment by javierZippia** [comment]
i debug and seems in:
prepare_meta never $allowed_protected_keys didnt work for '_thumbnail_id'.

Apart from that if i force to add '_thumbnail_id', its not adding to ES the link of the image, so i calculate it manually:

`class-ep-api.php	2017-05-09 12:22:21.626271566 +0200
@@ -792,6 +792,9 @@
 			if ( true === $allow_index || apply_filters( 'ep_prepare_meta_whitelist_key', false, $key, $post ) ) {
 				$prepared_meta[ $key ] = maybe_unserialize( $value );
 			}
+			if($key=='_thumbnail_id'){
+				$prepared_meta[ $key ] = get_the_post_thumbnail_url( $post->ID );
+			}
 		}
 
 		return $prepared_meta;`
