### ISSUE TITLE
Hanging on indexing posts

### ISSUE THREAD

**Issue by vichang** [10up/ElasticPress#831]
Wordpress 4.7.4
Elasticsearch 5.2

Running setup through wp-cli, it seems to hang on Indexing posts...

Enabled logging in elasticsearch but don't see any significant errors.

**Comment by ivankristianto** [comment]
What is your ElasticPress version?

**Comment by vichang** [comment]
Elasticpress 2.2.1

**Comment by ivankristianto** [comment]
can you try with the version from this develop branch?

**Comment by vichang** [comment]
This version managed to setup the index.
