### ISSUE TITLE
Multiple modifiers in search term

### ISSUE THREAD

**Issue by renanno** [10up/ElasticPress#836]
Hi

I don't know if this is an issue or a pull request, so correct  if I'm wrong posting this as an issue.

I have a subscription website. Users sign in and subscribe to get restrict content about law. So, my "product" is content. Some with more than 3k words.

We have some complex terms, with more than one word, and other terms with one word only.

So we need to find this kind of terms in the same document, and they are all relevant:
- This is a phrase
- WordA
- WordB

So I would try to find something like this: **"This is a phrase" and WordA and WordB**

Elasticpress currently try to find the phrase "_This is a phrase WordA WordB_". For us this doesn't make much sense, so probably won't find anything and then will try with "AND" modifier: _This AND is AND a AND phrase AND WordA AND WordB_.

Right? This will return some results, but not so relevant.

Then ElasticPress will use fuzzy search and will look for any of the words in search term.

My question is: is there a way the user can type a phrase between quotes and the rest using AND modifier? Like this:

> "This is a phrase" WordA WordB

Where would return only documents containing the exact term "This is a phrase" and, in other parts of the text, also WordA **AND** WordB, like this:

> Lorem ipsum dolor sit amet, **THIS IS A PHRASE** consectetur adipiscing elit. Sed tellus erat, iaculis non facilisis at, facilisis in tellus. **WORDA** Duis ut posuere massa. Ut sapien leo, **WORDB** porttitor nec felis nec, faucibus feugiat est.

It won't get documents like this one for example:

> Lorem ipsum dolor sit amet, **THIS IS** consectetur adipiscing **A PHRASE** elit. Sed tellus erat, iaculis non facilisis at, facilisis in tellus. **WORDA** Duis ut posuere massa. Ut sapien leo, **WORDB** porttitor nec felis nec, faucibus feugiat est.

Because it can't find "This is a phrase" exact term. 

Nor this kind

> Lorem ipsum dolor sit amet, **THIS IS A PHRASE** consectetur adipiscing elit. Sed tellus erat, iaculis non facilisis at, facilisis in tellus. Duis ut posuere massa. Ut sapien leo, **WORDB** porttitor nec felis nec, faucibus feugiat est.

Because it can't find WordA in the document.

Thanks

**Comment by ivankristianto** [comment]
@renanno ElasticPress not support your requirement by default.
But I believe you can filter it to match your case.
Filter you need to use is `ep_formatted_args`,
where you can see in this line:
```
$query = array(
			'bool' => array(
				'should' => array(
					array(
						'multi_match' => array(
							'query' => '',
							'type' => 'phrase',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_phrase_boost', 4, $search_fields, $args ),
						)
					),
					array(
						'multi_match' => array(
							'query' => '',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_boost', 2, $search_fields, $args ),
							'fuzziness' => 0,
							'operator' => 'and',
						)
					),
					array(
						'multi_match' => array(
							'fields' => $search_fields,
							'query' => '',
							'fuzziness' => apply_filters( 'ep_fuzziness_arg', 1, $search_fields, $args ),
						),
					)
				),
			),
		);
```

you need to remove the second and third array. and it should return the exact match.
this documentation would also help: https://www.elastic.co/guide/en/elasticsearch/guide/current/phrase-matching.html

**Comment by renanno** [comment]
I don't know if I didn't get it, but I don't think this would solve this question.

I mean, following my example above, the $query would need to be this way, right?

```
$query = array(
			'bool' => array(
				'should' => array(
					array(
						'multi_match' => array(
							'query' => 'THIS IS A PHRASE',
							'type' => 'phrase',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_phrase_boost', 4, $search_fields, $args ),
						)
					),
					array(
						'multi_match' => array(
							'query' => 'WordA WordB',
							'fields' => $search_fields,
							'boost' => apply_filters( 'ep_match_boost', 2, $search_fields, $args ),
							'fuzziness' => 0,
							'operator' => 'and',
						)
					)
				),
			),
		);
```

That way would return results with 'THIS IS A PHRASE' exact term and WordA and WordB, all in its content. Right?

So, possibly using regex I would have to look for terms inside quotes ("") to put in phrase type array and all the rest (unquoted) in the second array, which uses 'and' operator.

**Comment by ivankristianto** [comment]
I close this issue as we consider this as won't fix. But feel free to re-open if you have any question.
