### ISSUE TITLE
Sync Problems

### ISSUE THREAD

**Issue by fraunholz** [10up/ElasticPress#837]
We are having problems with the Elasticsearch synchronization.
Sometimes when changing the order status from e.g. pending to processing the order still shows in the list for pending orders. After deactivating elasticsearch or reindexing the status is correct.
By debugging in class-ep-sync-manager.php function sync_post we saw the following behaviour:
during the post status change the new and correct status is synced multiple times to elasticsearch.
Then a last sync happens a second later with the old post status.

**Comment by ivankristianto** [comment]
@fraunholz I did try it and it working well.

![test-wc-order-update](https://cloud.githubusercontent.com/assets/656006/26245248/674dd16e-3cbd-11e7-9991-2fdbce5c6aab.gif)

Can you check if you have any hook to run update_post_meta while change status?

**Comment by fraunholz** [comment]
first of all: which tool are you using to create the video? :-)
Yes, sometimes and especially when done manually there is no problem.
It is difficult to debug. 
For the meta hook I added logging now also to action_sync_on_update and I will check as soon the problem occurs again.

**Comment by fraunholz** [comment]
flushing the Wordpress cache for this post before sync seems to be the solution
