### ISSUE TITLE
fullname

### ISSUE THREAD

**Issue by fraunholz** [10up/ElasticPress#842]
Hi,

when searching by name for orders in woocommerce with elasticsearch the orders are not returned in the correct way, e.g. a search for "John Smith" is finding many "John"s and many "Smith"s, but should show the "John Smith"s first.
How can we set the search to take firstname and lastname as one?

Kind Regards
Christian Fraunholz

**Comment by ivankristianto** [comment]
@fraunholz you can increase the score weight for some fields.
Here is the snippet code to do that:
```
add_filter( 'ep_search_fields', function( $search_fields, $args ){
	$key = array_search('meta._billing_first_name.value', $search_fields);
	if( $key ){
		$search_fields[$key] = 'meta._billing_first_name.value^3';
	}

	$key = array_search('meta._shipping_first_name.value', $search_fields);
	if( $key ){
		$search_fields[$key] = 'meta._shipping_first_name.value^3';
	}

	return $search_fields;
}, 10, 2 );
```

**Comment by hrose1** [comment]
that does not have any effect

**Comment by hrose1** [comment]
One way of dealing with these types of queries is simply to index the first_name and last_name fields into a single full_name field. Of course, this can only be done at index time.

The cross_field type tries to solve these problems at query time by taking a term-centric approach. It first analyzes the query string into individual terms, then looks for each term in any of the fields, as though they were one big field.
