### ISSUE TITLE
sort orders by date

### ISSUE THREAD

**Issue by hrose1** [10up/ElasticPress#843]
we added sort=date to the url and it is used by elasticsearch, but the orders are not returned in the correct historical order.
Example: searching for "amazon" to retrieve all orders coming from Amazon.

**Comment by ivankristianto** [comment]
@fraunholz I tried to search the wc order with name and sort by date. it's working well. can you elaborate?

**Comment by hrose1** [comment]
![sort](https://user-images.githubusercontent.com/19900773/27856833-aa89a85a-616f-11e7-8cbd-07e1e6605f8b.png)
The screenshot shows a search by email, but as you can see the orders are not in the correct order (by date)

**Comment by ivankristianto** [comment]
@hrose1 you need to click the date column head
