### ISSUE TITLE
Nag removal

### ISSUE THREAD

**Issue by ekandreas** [10up/ElasticPress#844]
How to remove these annoying nags to check ES compability?
```
Your Elasticsearch version 5.3.0 is above the maximum required Elasticsearch version 5.2. ElasticPress may or may not work properly.
```

**Comment by ivankristianto** [comment]
@ekandreas we haven't fully tested it on ES 5.3.0
so it will stay there for now. So you either downgrade your ES to 5.2.0 or disable it by css

**Comment by ekandreas** [comment]
Ok, I see your point but we love to live in danger.
Why not add a filter to the nag functions?

**Comment by ivankristianto** [comment]
That could be a good idea. Mind to create a PR and so the other team could consider it?

**Comment by ekandreas** [comment]
Can't just remove a nag via CSS. There's no specific class or id to your nag in wp-admin.
Your warning doesn't concern the general users of WordPress.
