### ISSUE TITLE
General: ElasticSearch on AWS

### ISSUE THREAD

**Issue by devenh** [10up/ElasticPress#845]
I currently have my wordpress site hosted on AWS, but I'm new to ElasticSearch. AWS has two options when using ES. I can either setup my own EC2 machine and install ES or use [Amazon's hosted ES service](https://aws.amazon.com/elasticsearch-service/faqs/). 

If I'm planning on using ElasticPress, is there a particular ES option that you recommend over another? 

I think using the AWS hosted ES service will be easier for a beginner like me, but I'm curious if the WP-CLI commands for ElasticPress will properly create indexes for my data if I'm using the hosted AWS ES service.

**Comment by ivankristianto** [comment]
@devenh from what I experienced, AWS ES is good. You can use that one. 
And for WP-CLI command it has nothing to do where you hosted it. So yes it will works well.
