### ISSUE TITLE
How to use GNU licenses for your own software

### ISSUE THREAD

**Issue by jhabdas** [10up/ElasticPress#847]
https://www.gnu.org/licenses/gpl-howto.html

> Whichever license you plan to use, the process involves adding two elements to each source file of your program: a copyright notice (such as “Copyright 1999 Terry Jones”), and a statement of copying permission, saying that the program is distributed under the terms of the GNU General Public License (or the Lesser GPL).

> If you are releasing your program under the GNU AGPL, you only need to include the text version of the GNU AGPL.

**Comment by jhabdas** [comment]
https://github.com/xwp/wp-dev-lib/issues/240

**Comment by ntwb** [comment]
The repo has a license, @jhabdas please cease harassing the WordPress community on GitHub with your licensing issues, the issues are yours, not the projects you are opening these issues on.

**Comment by jhabdas** [comment]
Though not relevant unless switching to AGPLv3, a stronger copyleft license with the [same GNU license compatibility](https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility) as the GPLv3, I've [opened a question](https://opensource.stackexchange.com/q/5524/8188) to help clarify the meaning of the second block quote in my post above as could potentially have some bearing on the outcomes of a decision to apply the current license in order to meet GNU license compatibility guidelines.

**Comment by jhabdas** [comment]
Closing this given it's not clear to me if this is an actual issue. It was opened because I saw MIT licensed projects coping individual files without Licensing headers from GPL projects built in GitHub and there seemed to be a lack of guidance on the WordPress Forums. Please feel free to reopen if it makes sense. Sorry if I caused any ill will with this issue. My only intention was to help this project.

**Comment by tlovett1** [comment]
No worries!
