### ISSUE TITLE
2.3 Upgrade removes EP Dashboard/Settings page

### ISSUE THREAD

**Issue by sjferwerda** [10up/ElasticPress#848]
Just upgraded to EP 2.3 and now the ElasticPress menu link is gone and when I go to:

/wp-admin/admin.php?page=elasticpress

It's telling me: Sorry, you are not allowed to access this page.

I'm logged in as an Administrator.

Any ideas what's going on? Could it be related to the EP_DASHBOARD_SYNC enhancement.

**Comment by ivankristianto** [comment]
@sjferwerda no it doesn't related to `EP_DASHBOARD_SYNC`, I'm wondering if the plugin is activated?

**Comment by sjferwerda** [comment]
Well that's really odd. I swear that the plugin was activated when I looked before filing this issue request... but just went back and checked and it wasn't showing as activated now. Thanks! :-)
