### ISSUE TITLE
Disable on specific pages

### ISSUE THREAD

**Issue by misulicus** [10up/ElasticPress#855]
hey guys.
had some issues with FacetWP and Es but thanks to a PR mentioned here https://github.com/10up/ElasticPress/issues/839 it partially worked.
We did noticed now that the query results is not following the orderby menu_order title from the query.

I tested with ES disabled and then it works so my question is, is it possible to disable ES on a specific page ?
That page in question has its own page template so i could drop a line or whatever needs done at the top of the file before the FacetWP template runs

**Comment by misulicus** [comment]
Bump on this if anyone has any ideas

**Comment by tlovett1** [comment]
Definitely possible. Hook here: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1912

If current page = ...., then return false.
