### ISSUE TITLE
There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work.

### ISSUE THREAD

**Issue by PrintableCuttableCreatables** [10up/ElasticPress#856]
Hello
I have been using ElasticPress and Elastic Search for several months now without issue, however I logged into WPAdmin this morning and saw this message: 

"There is a problem with connecting to your Elasticsearch host. You will need to fix it for ElasticPress to work."

My server (Clludways) shows that Elastic Search is running and I have not changed any settings with the Elastic Press connection. 

I see that there is an update for the EP plugin but when i try to update I get the error: "Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions."

Do you have any insight as to what may have caused this to happen, and how to fix it?

**Comment by wenotice** [comment]
I'm having this same issue. I rolled the update back to the previous version, but still need a fix. Also, getting this kind of error in command line sync.

**Comment by ivankristianto** [comment]
@PrintableCuttableCreatables & @wenotice where you host your Elasticsearch server?

**Comment by ivankristianto** [comment]
@PrintableCuttableCreatables & @wenotice  
I cannot replicate your issue.
Can you install debug bar plugin + debug-bar-elasticpress plugin, and then send the result to my email: ivan.kristianto[at]10up.com?
I provide the screenshot of which data i would like to see.
![elasticpress 10up wordpress](https://user-images.githubusercontent.com/656006/27011402-3c05f600-4ee5-11e7-9308-5fca2b3aad0c.jpg)
