### ISSUE TITLE
bbpress support

### ISSUE THREAD

**Issue by sourfe** [10up/ElasticPress#857]
How can I make bbpress work with ElasticPress?

**Comment by ivankristianto** [comment]
@sourfe 
bbpress use post types which is by default supported by ElasticPress.
Can you elaborate which part you need that doesn't work?

**Comment by sourfe** [comment]
The bbpress posts are indexed but no bbpress posts show up when I search.
Is there something else I need to do?

**Comment by ivankristianto** [comment]
I looked into old issue here: https://github.com/10up/ElasticPress/issues/4
It's not available yet for bbpress search function.
But there is a way to integrate a search for that.
Interested in opening a PR?

**Comment by sourfe** [comment]
What is a "PR" Personal Request, custom work?

bbPress would really benefit from ElasticSearch due to very slow queries on
larger databases.

/S

2017-06-12 11:41 GMT+02:00 Ivan Kristianto <notifications@github.com>:

**Comment by ivankristianto** [comment]
Sorry I mean PR = Pull Request :)
here is all the PRs: https://github.com/10up/ElasticPress/pulls

**Comment by ivankristianto** [comment]
@sourfe I did try bbpress on my local and the search function just working fine. 
I wonder you did full sync before try to search your forum?
Can you give me your test site where it gone wrong?

**Comment by sourfe** [comment]
That is good news.
I did a full sync and I that was ok.

What version of bbpress did you try? I'am using 2.6RC3. I know it's not
official but 2.6 is so much better and and must for me to import from
Vbulletin.

Let me see if I can give you access.

/S

2017-06-19 13:27 GMT+02:00 Ivan Kristianto <notifications@github.com>:

**Comment by ivankristianto** [comment]
I'm using version 2.5.12.
I take a quick look at the code of bbpress 2.5, and i found nothing out of ordinary for the search function. And feel like it should be work with EP out of the box.
Just make sure you do full sync

**Comment by ivankristianto** [comment]
@sourfe i'm closing this issue as I feel there is nothing to do. Feel free to reopen it in the future.

**Comment by sourfe** [comment]
I will try on a clean bbpress 2.6 and see if it works.

Thanks!

/S

2017-06-19 13:43 GMT+02:00 Ivan Kristianto <notifications@github.com>:
