### ISSUE TITLE
Excluding post_author from index on certain post types

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#862]
New to elasticpress and trying to tune what is and what is not indexed. Apologies that this is more of a question than an issue, but may be helpful to document something like this for others looking to achieve the same result.

We run a news site and have 10 post types in our WP install. On regular posts and a couple other post types, it is critical to be able to search and aggregate by the author's name.

On other post types, like pages, calendar events, etc, the post author is completely irrelevant. It just happens to be the person who first entered it in WordPress.

By default, it looks like Elasticpress indexes `post_author` on all indexable post types, which we want in some cases, but not others. Is the following application of the `ep_post_sync_args` the correct way to address this?
```
function elasticpress_exclude_author( $post_args, $post_id ) {
	$allow_author_index = ['post', 'cpt1', 'cpt2'];
	if ( ! in_array( $post_args['post_type'], $allow_author_index ) ) {
		unset( $post_args['post_author'] );
	}
	return $post_args;
}
add_filter('ep_post_sync_args', 'elasticpress_exclude_author', 10, 2);
```
Any other consequences to this? We do have the protected content admin functionality enabled as well.

**Comment by ivankristianto** [comment]
@kevinlisota removing the post_author from index would cause an issue, and more often on admin post list. When protected content feature activated, wp will get post lists from elasticsearch, especially during the search. So if you output the post_author in list table, it will show empty post_author.
By default wordpress will store post_author for all the post types. So better to keep it same way.

**Comment by kevinlisota** [comment]
OK. Then is there a way for to make a scenario like this work? Here is s simple example.

- Posts are news articles, published daily
- Calendar is a custom post type to host event listings for community events
- Pages are used for things like a Contact Us or About page

All three post types should be available in search results to end user.

Todd is a WordPress author. He writes daily news articles. It is important to be able to search for his name or aggregate articles on his name as he is the reporter for these news articles.

Todd also creates the Contact US page and enters community events in the Calendar custom post type. He is the "post author" for these as well. However, when an end user searches on his name, these should not appear. The fact that he is the post author is unrelated to the content of these post types, unlike posts.

This is a very common scenario for us, and I'm guessing it is fairly common on other sites.

**Comment by ivankristianto** [comment]
Yes of course you can limit the search only to certain post type.
So here is the example of the wp_query
```
new WP_Query( array(
    's'             => 'username',
    'search_fields' => array(
        'author_name',
    ),
   'post_type'      => array( 'post', 'page', 'calendar' ),
) );
```

Hope that helps.

**Comment by kevinlisota** [comment]
But that isn't what we want in the end user search box. We want all 3 post types to appear in search results to end users.

By default, it looks like your search.php integration sets the search fields to the following:
```
		$query->set( 'search_fields', array(
			'post_title',
			'post_content',
			'post_excerpt',
			'author_name',
			'taxonomies' => array(
				'post_tag',
				'category',
			),
		) );
```
The WordPress search box is only going to issue a single query to ES. If the author_name is indexed on all post types, it is going to return the results for other posts created by that author. In our case, only 'post' is relevant to search by author name. The other posts technically shouldn't have an "author," as it doesn't make sense to have an author for a Contact Us page, for example. I get that WordPress needs and author on all CPT, given how it is structured.

**Comment by ivankristianto** [comment]
Looking by your case. It need to have different search_fields for different
post types. Even WP_Query cannot do that in single query.
But if you do have lists of post ids you don't want to be exist in search
results, you could add arguments with post__not_in.

**Comment by ivankristianto** [comment]
I'm closing this issue. Feel free to re-open if you have any questions.
