### ISSUE TITLE
ElasticPress queries /_nodes/plugins on every pageload

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#863]
Using Query Monitor to watch HTTP requests made by ElasticPress.

I'm seeing an HTTP request to our ES instance on every pageload, regardless of whether that page is using ES functionality or not in both front-end and admin pages. The HTTP request goes to /_nodes/plugins on the ES remote instance.

Seems like a lot of unneeded HTTP requests. Shouldn't this fire only when ES capabilities are actually needed?

**Comment by ivankristianto** [comment]
Yeah I think you are right. Will put this on the list of enhancement.

**Comment by tlovett1** [comment]
Here's why we do that:

On every page load, we auto-activate/deactivate features. Each feature has a list of criteria that needs to be met for it do be auto-activated. For WooCommerce, the plugin must be active. The theory is we need to check those conditions on every page load to handle that. The plugins endpoint provides info critical to certain features e.g. documents.

I'm open to hearing work arounds.

Thanks!

**Comment by kevinlisota** [comment]
Could the result be cached in a transient? I think the response rarely changes, and on our site, that request may be made a 100k times a day, and while not slow, there is some built-in latency having to traverse the net to an ES endpoint.

**Comment by kevinlisota** [comment]
What data centers do you host your Elasticsearch clusters in on elasticpress.io? 

Our site is in an Azure datacenter, and I've been testing with an Elasticsearch cluster hosted by Elastic.co cloud, which is on AWS in a nearby region.

The plugins query to ES adds 120-125ms to each and every pageload on our site. Given that our typical pageload time is 400-500ms, this is adding a blocking function that increases latency by 25%-30%, which will ultimately be a showstopper for us.

I'm going to have to try this with an ES cluster in the same datacenter as our site to see if I can overcome the latency issue.

**Comment by tlovett1** [comment]
We will be releasing a bug fix for this soon.
