### ISSUE TITLE
[ES 2.3.1] Stopwords are not changed when analyzer `language` key is set

### ISSUE THREAD

**Issue by fabianmarz** [10up/ElasticPress#864]
It seems like the `language` key from the analyzer does not set the correct stopwords for the specified language. If I create an index via `$ wp elasticpress put-mapping` with `"language": "german"`, the analysis returns the following:

```
$ curl -XGET 'localhost:9200/<indexname>/_analyze?pretty' -d 'as eupen'
{
  "tokens" : [ {
    "token" : "eupen",
    "start_offset" : 3,
    "end_offset" : 8,
    "type" : "<ALPHANUM>",
    "position" : 1
  } ]
}
```

While setting the index analyzer setting as follows:
```
{
  "analysis" : {
    "analyzer":{
      "default":{
        "type":"german"
      }
    }
  }
}
```
will result in this:
```
"default": {
    "filter": [
        "standard",
        "ewp_word_delimiter",
        "lowercase",
        "stop",
        "ewp_snowball"
    ],
    "language": "english",
    "type": "german",
    "tokenizer": "standard"
}
```
The analysis seems to be correct:
```
$ curl -XGET 'localhost:9200/<indexname>/_analyze?pretty' -d 'as eupen'
{
  "tokens" : [ {
    "token" : "as",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "<ALPHANUM>",
    "position" : 0
  }, {
    "token" : "eup",
    "start_offset" : 3,
    "end_offset" : 8,
    "type" : "<ALPHANUM>",
    "position" : 1
  } ]
}
```

Has any of you encountered the same issue? Would it make sense, to drop the `language` key but setting it via the `type` key? Also it looks like the default filter list is overridden with the language specific one if `type` is set to a language.

**Comment by tlovett1** [comment]
You might want to ask this on the Elasticsearch forums.

**Comment by fabianmarz** [comment]
Yes, you're right! Will post this in the Forums.

**Comment by ivankristianto** [comment]
i'm closing this issue. But feel free to re-open if you have more question.
