### ISSUE TITLE
Document feature check elasticsearch version too early

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#866]
As reported in this issue #854 
document feature check the elasticsearch version in this line https://github.com/10up/ElasticPress/blob/develop/elasticpress.php#L61
earlier than other plugin or themes to filter the `http_request_args`.
the case is to add the self-signed certificate, which is caused the connection notice always show up.

**Comment by tlovett1** [comment]
@ivankristianto closing this one since this isn't just an issue with the document feature but how features are setup.
