### ISSUE TITLE
Indexing stops with admin button but works in command line 

### ISSUE THREAD

**Issue by foadyousefi** [10up/ElasticPress#867]
Hi there!
We have a website running Wordpress + woocommerce + ElasticPress and about 5 thousands products + posts. When we re-index from admin setting page by clicking on index button, it stops  after 4,550 and after some minutes, we must refresh the page and click on resume indexing and after some attempts, it finishes the indexing. 

If we run "wp elasticpress index --setup" from command line, it does the job. 

After some more checking and researches, found out when EP tries to index the posts (with post_type of post) gets so slow, indexing products (post_type of product) is normal and fast. 

The reason might be post_metas, products has lots of meta fields, EP puts mapping according to all meta fields, but posts don't have those fields, so I think while trying to send posts to index, struggling with finding appropriate meta value for the meta field exists in the mapping. 

Please consider this problem. 
I hope I was clear explaining the issue.

**Comment by tlovett1** [comment]
You will have to debug why the dashboard index is failing.

**Comment by ivankristianto** [comment]
i'm closing this issue. But feel free to re-open if you have more question.
