### ISSUE TITLE
German translation finished

### ISSUE THREAD

**Issue by ahoerl** [10up/ElasticPress#869]
Hi, just finished the German Plugin translation over here:
https://translate.wordpress.org/projects/wp-plugins/elasticpress/dev/de/default 

Cheers - tomorrow I will try the Plugin ;)

**Comment by tott** [comment]
@ahoerl, this is great, thanks for working on this. I did a quick sweep and there are still a few alterations we will need to do on the translations before merging them in, but this is a great base to start from. @tlovett1 I will make sure to review these translations next week so we can get them added if you agree

**Comment by ahoerl** [comment]
Of course you can use it, merge it, change it – whatever ☺

Mit freundlichen Grüßen / Best Regards
Andreas Hoerl
Rendering

[Prolicht GmbH]
T +43 5234 33499 95
andreas.hoerl@prolicht.at <mailto:andreas.hoerl@prolicht.at>

PROLICHT GmbH
Gewerbepark 9
A-6091 Götzens
F +43 5234 33499 22
www.prolicht.at<http://www.prolicht.at>

VISIT US AT:      [cid:image002.jpg@01D2EC22.BA303390] <https://vimeo.com/prolicht>  [cid:image003.jpg@01D2EC22.BA303390] <https://twitter.com/prolicht>  <https://www.facebook.com/prolicht>  [cid:image005.jpg@01D2EC22.BA303390] <https://issuu.com/prolicht>  [cid:image006.jpg@01D2EC22.BA303390] <https://www.youtube.com/channel/UC2pUOpq6LdAyBbZUN1sfeBA/videos>  [cid:image007.jpg@01D2EC22.BA303390] <https://www.pinterest.com/prolicht/>

[cid:image008.png@01D2EC22.BA303390]<http://www.prolicht.at/>




Gerichtsstand Innsbruck | UID ATU30905802 | FN 41416G
ARA-Lizenz Nr. 11951 | Handelsgericht Innsbruck
Von: Thorsten Ott [mailto:notifications@github.com]
Gesendet: Freitag, 23. Juni 2017 13:14
An: 10up/ElasticPress
Cc: ahoerl; Mention
Betreff: Re: [10up/ElasticPress] German translation finished (#869)


@ahoerl<https://github.com/ahoerl>, this is great, thanks for working on this. I did a quick sweep and there are still a few alterations we will need to do on the translations before merging them in, but this is a great base to start from. @tlovett1<https://github.com/tlovett1> I will make sure to review these translations next week so we can get them added if you agree
