### ISSUE TITLE
Wrong product on single product url when WooCommerce == enabled

### ISSUE THREAD

**Issue by isvaljek** [10up/ElasticPress#870]
My single single product template displays only the latest product in the db when WooCommerce integration is enabled (even with Twenty Seventeen theme).
![image](https://user-images.githubusercontent.com/2500267/27486102-b4bc9a2e-582f-11e7-939d-75e19cd6060f.png)

**Comment by tlovett1** [comment]
@ivankristianto can you take a look at this one?

**Comment by isvaljek** [comment]
I've created a pull request that fixes it for me, but fails in travis ci: https://github.com/10up/ElasticPress/pull/871#partial-pull-merging

**Comment by ivankristianto** [comment]
Sure i'll take a look

**Comment by ivankristianto** [comment]
@isvaljek i'm not sure how you get the issue.
my single product show just fine.
I cannot replicate your issue.
Can you tell me your environment settings? (WP, EP, ES version)?
And do you have any other plugin installed?

**Comment by isvaljek** [comment]
![image](https://user-images.githubusercontent.com/2500267/27517580-406b7d60-59cf-11e7-9fc9-8208d310f1ee.png)
Have you tried toggling this one? When I enable wocommerce then it happens. Look at my pull request above, it's a single line change. And to me it seems a more of a wp way.
I'm using ES 5.4.1 and I do get the superversion notice, but this code happens before any call to my ES server is made, just single post template load. Last EP plugin 2.3. Last WP 4.8.

**Comment by ivankristianto** [comment]
@isvaljek 
Yes I do activate that.
ElasticPress doesn't do any query when in single product. 
So most probably there is another plugin crash that cause query `product` is returning empty. Thus it will activate the elasitcpress and get only the latest product.

**Comment by isvaljek** [comment]
You're right, it's something related to WPML plugin. But only when both EP and WPML are active. Not sure whose authority it is yet.

**Comment by lukaspawlik** [comment]
@isvaljek ,

Did you try checking this on WooCommerce 3.x? I believe this may be happening on 2.x only.

**Comment by lukaspawlik** [comment]
Extra note @isvaljek,

This issue should be fixed in https://github.com/10up/ElasticPress/pull/947 (if you have a chance to test it).
