### ISSUE TITLE
Search should default to user display_name

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#872]
Looks like the default WordPress search functionality sends a query that includes an author login name and author nicename (which is the slug)

I realize there is a filter to alter the way this behaves, but this seems like the wrong choice of fields for out-of-the-box author searching.

Shouldn't it be the user display_name instead? That seems the most readable and user/search-friendly version of the author name. It is typically what would appear in a byline, since the slug or login name may exclude the first or last name or possibly jam those two together into one string.

For example, a typical install might have the following

user_login: john
user_nicename: john
display_name: John Smith

or something like this

user_login: tjones
user_nicename: tjones
display_name: Tom Jones

**Comment by tlovett1** [comment]
Sorry, not understanding.

**Comment by kevinlisota** [comment]
By default, the plugin doesn't use the user display_name in the search query, rather it is using login and author_name.

In the examples above, which are likely fairly common, you may be searching on truncated or concatenated strings that do not contain the full author name which you might see in a byline.

On a multi-author site, I think the most common search for author would be on their full name like "Tom Jones". Without altering the search fields via a filter, the search results may get limited or no hits because you are actually querying on a login name or nicename which could very well be "tjones".

I'm suggesting that display_name may be the most appropriate field to search against here when the intention is to return results for author names.

**Comment by lukaspawlik** [comment]
Hi @kevinlisota,

Can we start from scratch? Can you please mentioned WordPress query? I'd like to understand how to reproduce your issue. Where do you observe this behaviour?

**Comment by lukaspawlik** [comment]
Closing.
