### ISSUE TITLE
author_name not an indexed field

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#873]
I'm using the debug bar to view queries sent and results received in the wordpress search page. It is requesting the following fields:
```
                                "fields": [
                                    "post_title",
                                    "post_content",
                                    "post_excerpt",
                                    "author_name",
                                    "terms.post_tag.name",
                                    "terms.category.name",
                                    "post_author.login",
                                ],
```
Looking at my index in Kibana, I show the following available fields

```
post_author.display_name
post_author.id
post_author.login
post_author.raw
```
I know that author_name is a valid WP_Query parameter, corresponding to user_nicename. However, it appears that this is not an indexed field? Maybe some incorrect field mapping/indexing here?

**Comment by tlovett1** [comment]
`author_name` should work. If it doesn't, that's a bug.

**Comment by ivankristianto** [comment]
@kevinlisota 
`author_name` is added in search feature as the `search_fields` and later will be translated to `post_author.login`.
But there is a bug that should unset `author_name` from the `search_fields`
I have opened a PR to fix this.

But if you are trying to add `author_name` in your wp_query then it will be translated to `post_filters`
