### ISSUE TITLE
Indexing is incomplete when protected content is enabled

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#875]
I am getting incomplete indexing results when I enable protected content.

Our site has 30k published posts of type 'post'. When I index the site with protected content feature turned off, the sync seems to capture all of the content and search results look correct. Running a query in Kibana of `post_type:post` gives 30,249 hits.

I then enable protected content feature, which causes a reindex of the site and adds another 20k documents to the index. However, at the completion of the indexing, the search results are incomplete and a `post_type:post` query in Kibana only shows 8,738 hits. There are now 21,000 posts missing from the index compared to what is in WordPress.

The admin console shows no errors during the indexing process, and the debug log is also not showing any errors related to the plugin.

Any pointers on how to debug this?

**Comment by allan23** [comment]
@kevinlisota This is interesting. Can you install the EP Troubleshooter plugin and send us the troubleshooting data?

(https://github.com/allan23/ep-troubleshoot)

**Comment by kevinlisota** [comment]
@allan23 Is there an email alias that I can send that data to?

**Comment by allan23** [comment]
@kevinlisota allan.collins[at]10up.com

**Comment by allan23** [comment]
No response. Closing this unless additional details are provided.
