### ISSUE TITLE
How to disable an unwanted search field with ep_search_fields

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPress#876]
I am attempting to disable a search field via the `ep_search_fields` filter. My function unsets that search field like so:
```
	function change_search( $search_fields, $args ) {
		$post_tag_index = array_search( 'terms.post_tag.name', $search_fields );
		unset( $search_fields[ $post_tag_index ] );
		return $search_fields;
	}
add_filter('ep_search_fields', 'change_search');
```
This results in a 400 Bad Request error to the EP endpoint, and it looks like it is is somehow related to adding the array index numbers into the ES query. This is what the debug bar shows for search fields. Notice the array index numbers, which aren't there prior to application of the above filter.
```
                                "fields": {
                                    "0": "post_title",
                                    "1": "post_content",
                                    "2": "post_excerpt",
                                    "4": "terms.category.name",
                                    "5": "post_author.login"
                                },
```
I have successfully added a search field with this method, but subtracting a search field doesn't seem to work as expected. Is there a different filter for this?

**Comment by allan23** [comment]
Hi @kevinlisota,
This appears to be an issue with the array keys. If you return `array_values( $search_fields );` instead of just `$search_fields` in your filter it should resolve your issue.

**Comment by kevinlisota** [comment]
That seems to work. Not sure why it choked on the array keys.
