### ISSUE TITLE
Unable to sync — »An error occured while syncing«.

### ISSUE THREAD

**Issue by FlorianBrinkmann** [10up/ElasticPress#880]
Current WordPress version: 4.8

Current ElasticPress version: 2.3.2

Current Elasticsearch version: 2.3.3 

Where do you host your Elasticsearch server: searchly.com

I don’t know since when this issue occurs exactly, but I cannot sync with the Elasticsearch host… It works on a local dev instance with the same Elasticsearch server URL, but not on the live site. The connection to the host seems to work — I see a matching index in the searchly dashboard, but it is unable to sync the content. I always get the message »An error occured while syncing«.

**Comment by AntBentinck** [comment]
@FlorianBrinkmann Agreed I am also seeing this:

Current WordPress version: 4.8
Current ElasticPress version: 2.3.2
Current Elasticsearch version: Provider: 5.3.2

HTTPS / QBOX / AWS Environment:

What is also annoying is WooCommerce products do not show on our admin dashboard. Have burst all caches and disabled plugins. Sync gets to 5600 of 17000 then dies on website 1. sync fails completely on Website2 2074 records.

Also seeeing the following admin-ajax.php 500 or 524 error when the sync fails in console.

**Comment by AntBentinck** [comment]
Not sure if this is any help but on a sync when it got to 5600 records out of 17000 we got a 524 error on the console dashboard.min.js:formatted:116 POST https://www.(REMOVED)/wp-admin/admin-ajax.php 524 ()

**Comment by AntBentinck** [comment]
We have run a lot of new scenarios here now and the the only thing which seems to be causing this issue for us is the Protected Content setting. When this is turned off we get completed syncs without any issue.

**Comment by FlorianBrinkmann** [comment]
I have the issue without having the Protected Content setting enabled…

**Comment by tlovett1** [comment]
@ivankristianto can you take a look?

**Comment by ivankristianto** [comment]
@FlorianBrinkmann / @AntBentinck 
Is the issue also occurred when doing sync via wp-cli?

**Comment by FlorianBrinkmann** [comment]
I am currently running the `wp elasticpress index` since a few minutes, but it only shows _Indexing posts..._. How can I exit this indexing, without getting the message _WP CLI sync is occuring. Refresh the page to see if it's finished_ in the backend? :D

Something interesting: It is a multisite, and it works fine on a sub site `/en/` (the issue occurs on the main page of the multisite).

**Comment by ivankristianto** [comment]
@FlorianBrinkmann to remove that message you can remove transient data `ep_wpcli_sync`
I wonder if you are using network flag when doing indexing:
`wp elasticpress index --network-wide`
and if you have any issue while indexing, can you let me know the error message?

**Comment by FlorianBrinkmann** [comment]
No, I’m not using the network flag, because I have various sites in the network which I don’t want to be indexed. I tried it now, but get the message `Indexing posts network-wide...` since a few minutes, and nothing else.

The working sync on the `/en/` site was made via the dashboard.

**Comment by ivankristianto** [comment]
Seems like a plugin crash to me.
Can you email me your error log to ivan.kristianto[at]10up.com?

**Comment by FlorianBrinkmann** [comment]
Oh man, you are right, it was a plugin crash — I should have taken a look at the error log… 🙈 It was a conflict with the Gutenberg editor, here the relating line from the logs:

```
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /path/to/html/wp-content/plugins/gutenberg/lib/parser.php on line 1221, referer: https://florianbrinkmann.com/wp-admin/admin.php?page=elasticpress
```

Deactivating the Gutenberg plugin resolves the issue.

**Comment by ivankristianto** [comment]
@AntBentinck are you still having the sync issue?

**Comment by ivankristianto** [comment]
@FlorianBrinkmann after i investigate more on this issue.
with Gutenberg activated and doing sync via cli, the syncing actually running but very slow because of Gutenberg parser.
and when doing dashboard sync, it will cause max execution timeout, if your gutenberg content is quite long ( the gutenberg demo content is long enough to cause this ).
So yeah, deactivate gutenberg for now is the only way.

**Comment by FlorianBrinkmann** [comment]
@ivankristianto good to know, thanks for taking a deeper look!

**Comment by ivankristianto** [comment]
I close this issue for now, and will open a ticket to gutenberg instead.
If you have any issue, feel free to open
