### ISSUE TITLE
Question on sorting on multiple fields

### ISSUE THREAD

**Issue by DavidWFresh** [10up/ElasticPress#885]
I have a question regarding the functionality of this plugin.

Does it use the built in WP_Query functionality for searching, or are there other methods as well?

What I'm currently trying to do is to order the results based on 3 different meta keys, basically the reviews and ratings.  Is there any advanced sorting available from this plugin through to elastic press?

Below is an example of what I was trying to do, but I haven't had much progress on getting good results.  Thank you for any information you can provide on this question.

```
$s = get_search_query();
$args = array(
	's' => $s,
	'paged' => get_query_var( 'paged' ),
	'posts_per_page' => 12,
	'post_type' => array(
		'product',
		'post',
		'faq',
	),
	'orderby' => array(
		'post_type' => 'ASC',
		'meta_value_num' => 'DESC',
		),
	'meta_query' => array(
		'relation' => 'And',
		array(
			'key' => 'user-reviews-count',
		),
		array(
			'key' => 'user-rating',
		),
	),
);

global $the_query;
$the_query = new WP_Query( $args );
```

**Comment by ivankristianto** [comment]
@DavidWFresh Yes you can sort it by multilple value.
This is from the doc:
```
orderby (string)

Order results by field name instead of relevance. Supports: title, modified, meta_value, meta_value_num, type, name, date, and relevance; anything else will be interpretted as a document path i.e. meta.my_key.long or meta.my_key.raw. You can sort by multiple fields as well i.e. title meta.my_key.raw
```

so in your case you can do as:
```
'orderby' => array(
		'post_type' => 'ASC',
		'meta.user-reviews-count.raw' => 'DESC',
                'meta.user-rating.raw' => 'ASC',
		),
```

**Comment by DavidWFresh** [comment]
Ah, sorry I hadn't seen that one.  I was able to get it working, with the above with "post_type.raw" included.

Is there any included functionality for '_script' within the 'orderby' as well, or just the parameters listed?

For example.  
	'orderby' => array(
		'post_type.raw' => 'ASC',
		'_script' => array( 
			'script' => "if(doc['meta.image-medium.raw'].value != 0) 1",
			'type' => 'string',
			'order' => 'DESC',
			),
		'_script' => array(
			'script' => "script": "doc['meta.user-reviews-count.long'].value * doc['meta.user-rating.long'].value",
			'type' => 'number',
			'order' => 'DESC',
		),
		'meta.user-rating.raw' => 'DESC',
		'meta.user-reviews-count.long' => 'DESC',

**Comment by ivankristianto** [comment]
@DavidWFresh you can filter it with `ep_formatted_args`, and change the arguments to anything you like.
