### ISSUE TITLE
Index single/some posts only in EP CLI

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#886]
Currently we can only re-indexing whole content or based on post type.
So i'm proposing to have indexing based on:
1. Post Id(s): `wp elasticpress index --post-ids=1,2,3,4,5`
2. Taxonomy: `wp elasticpress index --taxonomy=category --tax-slug=art,poetry`
3. URL: `wp elasticpress index --url=http://domain.dev/post-slug/`

@tlovett1 what do you think?

**Comment by tlovett1** [comment]
3 already exists (core WP-CLI functionality). Do you have a use case for 1 and 2?

**Comment by ivankristianto** [comment]
For #1 & #2 
Sometimes I just want to re-index only for certain posts or from some categories only.
This is not a typical daily case, but it would be nice if we can have that options.

This is happen when I debug EP + Gutenberg, where save_post failed to sync post to ES due to timeout. And I want to just sync for that post only rather than reindex the whole posts.

**Comment by dotancohen** [comment]
Regarding idea number 1, I've implemented it here:
https://github.com/10up/ElasticPress/pull/1044
