### ISSUE TITLE
'publicly_queryable' Doesn't Make Taxonomies Queryable

### ISSUE THREAD

**Issue by kesed** [10up/ElasticPress#890]
Have you searched for similar issues before submitting this one?
Yes. Only found one other issue mentioning 'publicly_queryable' and this case seems different.

Is this a bug, question or feature request?
It appears to be a bug.

Describe the issue you encountered:
`'publicly_queryable' => true` does not seem to have the intended affect on taxonomies – this alone does not make the taxonomies queryable. They are only queryable when `'public' => true`. While this did throw us off, once we realized what was going on it's not a major issue. It's just nice to be able to set the public argument to false so that it's inherited by other arguments like show_ui and show_in_nav_menus. We've worked around this issue by just setting the public arg to true and explicitly listing out the other arguments we want to be false.

Current WordPress version:
4.8

Current ElasticPress version:
2.3.2

Where do you host your Elasticsearch server:
ElasticPress.io

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Advanced Custom Fields PRO, Custom Upload Dir, Debug Bar, Debug Bar ElasticPress, Formidable Forms, Query Monitor, Restrict Content Pro, WP All Import Pro, WP Redis, WP-CFM

**Comment by allan23** [comment]
Hi @kesed, I have submitted PR #891 which should resolve this issue. Can you please test and verify?
