### ISSUE TITLE
Add support for Sticky posts

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/ElasticPress#898]
**Have you searched for similar issues before submitting this one?**
Yes

**Is this a bug, question or feature request?**
Feature request

**Describe the issue you encountered:**
When using WP_Query calls with ignore_sticky_posts as true/false, EP does nothing with Elasticsearch arguments sent in the request to float sticky posts up to the top when ignore_sticky_posts=false, so all ES queries are treated ultimately as ignore_sticky_posts=true which may be opposite of the intended WP_Query call.

**Current WordPress version:**
4.7

**Current ElasticPress version:**
2.3.2

**Current Elasticsearch version:**
5.3

**Where do you host your Elasticsearch server:**
Local server

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):**
Not related

**Steps to reproduce:**

1. Do a WP_Query call for `'post_type' => 'post'` and `'ignore_sticky_posts' => false` (explicitly setting to false to avoid any suspicion of any defaults).
2. Get back posts, sticky posts are not listed first

**Screenshots, if needed:**
N/A

**Comment by tlovett1** [comment]
Definitely not supporting this right now. We'll try to add to 2.4. Thanks!
