### ISSUE TITLE
the_post_thumbnail doesn't load if ElasticPress is activated and sync hasn't been done

### ISSUE THREAD

**Issue by Pezzab** [10up/ElasticPress#900]
This probably isn't any big deal but it caused me some consternation until I worked it out.

If ElasticPress is active but a sync hasn't been done search works in WordPress but post thumbnails aren't displayed.

I guess this isn't a big deal as you would want to sync the database any way but in my case it sent me on a bit of a wild goose chase thinking there was a bug in EP as thumbnails appeared when it was deactivated until it dawned on me that I hadn't done a sync.

I couldn't figure out why the same template with thumbnails worked fine in a taxonomy archive but not with search.

Perhaps more a heads up than a bug per se.

**Comment by ivankristianto** [comment]
@Pezzab Thank you for reporting this issue.
I'll take a look on this.

**Comment by lukaspawlik** [comment]
Hi @Pezzab,

Could you share some more details about your issue? I tried to replicate this on my local test environment and I couldn't reproduce this issue.

I tried following scenario: 

- create an article without thumbnail
- index articles in Elasticsearch
- turn off ElasticPress
- add thumbnail to created article
- enable ElasticPress
- visit search page and search for a created article; returned results were displaying post thumbnail correctly (even if it wasn't pulled from Elasticsearch as it wasn't there); I am using current _develop_ branch of ElasticPress + _Twentyfifteen_ theme.

Could you share details like ElasticPress version and Theme and it's version (if it's publicly available) ?

I am quite sure this is not a bug as if Elasticsearch isn't in sync with database then results pulled from Elasticsearch will differ from results in database. I'd like to add that taxonomy archive by default doesn't use Elasticsearch integration (and it pulls data from database) while search page by default does. This can explain discrepancy you saw however this is how it should work in my opinion (unless I am missing something in your report).

**Comment by lukaspawlik** [comment]
Closing due to lack of response.
