### ISSUE TITLE
wp_cli --show-bulk-errors timed out

### ISSUE THREAD

**Issue by DavidWFresh** [10up/ElasticPress#901]
Hello,

When I try running: wp elasticpress index --setup --show-bulk-errors --url=site.com/subsite/ 

It is just showing an error that it timed out instead of showing what the error was.

![image](https://user-images.githubusercontent.com/29987149/28530601-40caf8ea-7049-11e7-8e0c-e122df7caf90.png)

Do you know what might be causing this issue to happen?

Thank you

**Comment by tlovett1** [comment]
Can you debug the request? The payload being sent to ES is 37.19 MB. That is massive. There must be a post that is absolutely huge.

**Comment by DavidWFresh** [comment]
Hello, I am using WPEngine to run the commands, so I am not directly running them.  What would be the correct process to debug it?

Thank you.

**Comment by tlovett1** [comment]
In that case you'll have to debug it locally.
