### ISSUE TITLE
Trouble weighting search results and searching by custom fields

### ISSUE THREAD

**Issue by dbourdin** [10up/ElasticPress#902]
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?
Question
Describe the issue you encountered:
I'm having trouble while defining custom search fields and adding weight to the query search results.
I'm using Listify and facetwp to make faceted searchs among my listings. I want to use elasticsearch as searchengine for my keyword searchs in facetwp.
Current WordPress version:
4.7.3
Current ElasticPress version:
2.3.2
Current Elasticsearch version:
5.4.0
Where do you host your Elasticsearch server:
Google compute engine VM
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
FacetWP, Valu FacetWP ElasticPress Integration (https://github.com/MikkoVirenius/vafael), woocommerce, wp job manager, wp job manager paid listings (and many more, but I think there is no need to mention them)
Steps to reproduce:
First of all, I want to search in more fields than just post title, post content and post excerpt. In order to do this, I found a little way through, by registering a new "search engine" with Valu FacetWP ElasticPress Integration. By defining a new search engine I can pick which fields I want the search to use. (I couldn't find a way to do this without using this plugin, if there's a way I'd like to know). For example, I want the keyword search to include job_listing_category taxonomy.
To be able to use this Valu FacetWP ElasticPress Integration plugin I had to "modify" a line in its code to fix integration with elasticpress (It said is_plugin_active( 'ElasticPress/elasticpress.php' ) wile it should be elasticpress/elasticpress.php).
Then I could register a new search engine like this in my functions.php:

```
add_action('init', function(){
	$engine = array(
		'post_type'     => 'job_listing',
		'post_status' => 'publish',
		'search_fields' => array(
			'post_title',
			'post_content',
			'post_excerpt',
			'taxonomies' => array( 'job_listing_category' ),
			'meta' => array(
				'_ciudad',
				'_barrio',
				'_vehiculo_modelo',
				'_vehiculo_anio',
				'_vehiculo_version',
				'_vehiculo_estado',
				'_subcategoria_inmuebles'
	) ) );
	VAFAEL()->register_engine( 'ElasticPress Listing search', $engine );
});
```

After making this I can tell FacetWP to use this custom engine to make keyword searchs, and include those fields in the search. So far so good, it's working fine.
But now I need to make a weighted search in order to prioritize fields. I tried following this "guide"
https://github.com/10up/ElasticPress/wiki/Weighting-Search-Results
I'm definitely not being able to add weight to the taxonomy, or any of the metas. I wish to see a more concrete example on how to do it, because I'm not understanding quite well how to do it. 
Also I wish to know if there's a way of defining the search among these custom fields without using this plugin to create a new search engine.

**Comment by rickertl** [comment]
@dbourdin Did you ever find a solution for weighting these custom fields AND/OR did you find a way to include custom fields without the Valu FacetWP plugin? Thanks.

**Comment by dwlorimer** [comment]
I am also trying to do this in elasticpress.  Did you ever find a solution?

**Comment by dbourdin** [comment]
@dwlorimer No, i'm really sorry. I couldn't find a workaround for this.
