### ISSUE TITLE
Random ordering bug in Woocommerce feature

### ISSUE THREAD

**Issue by pySilver** [10up/ElasticPress#906]
We should remove this lines: https://github.com/10up/ElasticPress/blob/develop/features/woocommerce/woocommerce.php#L365 

```php
if ( ! empty( $orderby ) && 'rand' === $orderby ) {
			$query->set( 'orderby', false ); // Just order by relevance.
		}
```

since *random* ordering is supported here:
https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1403

**Comment by ivankristianto** [comment]
Good catch @pySilver, mind to create a PR for this?
