### ISSUE TITLE
Improved WP-CLI Error Messaging

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#907]
Right now when mapping fails, you see a "Mapping Failed" message with no context. It would be nice to see the Elasticsearch reason for why it failed. Perhaps there is a `--debug` parameter that provides more information.

**Comment by lukaspawlik** [comment]
@tlovett1 If we could treat this issue as a hub issue for all wp-cli error messaging related issues then it would be great as in other ticket (https://github.com/10up/ElasticPress/issues/953) I saw that exposing any information that indexing of some documents failed would be very welcome.

**Comment by lukaspawlik** [comment]
@tlovett1 Additional info about #953 - https://github.com/10up/ElasticPress/issues/953#issuecomment-338657803
