### ISSUE TITLE
Trying to get property of non-object in /elasticpress/features/woocommerce/woocommerce.php on line 274

### ISSUE THREAD

**Issue by BurlesonBrad** [10up/ElasticPress#908]
_Have you searched for similar issues before submitting this one?_
**As best as possible**
_Is this a bug, question or feature request?_
**Bug**
_Describe the issue you encountered:_
[https://youtu.be/UGIF0T_uD70](https://youtu.be/UGIF0T_uD70) **In <---that video that the girls sent me, the girls in the corporate office are attempting to search for WooCommerce orders using a customer's email and then various other parameters.  Finally she was able to pull up the info, but not without a bit of issues which I was able to replicate as I created my own video cast that I made here:** [https://youtu.be/I3nMaBfK1TI](https://youtu.be/I3nMaBfK1TI) 
_Current WordPress version:_
**4.7.5**
_Current ElasticPress version:_
**2.3.2**
_Current Elasticsearch version:_
**Still wondering & looking.....**
_Where do you host your Elasticsearch server:_
**Pagely**
_Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):_
[https://gist.github.com/BurlesonBrad/eee52e295b840dab912647c2dff8bd59](https://gist.github.com/BurlesonBrad/eee52e295b840dab912647c2dff8bd59)
_Steps to reproduce:_

1. (reference video linked above) Put customer's email into `.post-search-input` field
2. whack enter or gracefully hover over the word `Search` and delicately depress the mouse button
3. And / or place customer's email in the `.select2-_customer_user-z7-container` area
4. hover over the word `Filter` and delicately apply thy finger to the mouse button
5. I replicated the behavior in my own video cast : [https://youtu.be/I3nMaBfK1TI](https://youtu.be/I3nMaBfK1TI)

_Screenshots, if needed:_
**Hopefully the video(s) are better than a screenshot**
_Can you paste anything in your error logs related to ElasticSearch?_
**Sure.**
```[03-Aug-2017 03:55:17 UTC] PHP Notice: Trying to get property of non-object in /wp-content/plugins/elasticpress/features/woocommerce/woocommerce.php on line 274```

https://github.com/10up/ElasticPress/blob/develop/features/woocommerce/woocommerce.php#L274

Indexing orders + being able to quickly pull them up when a customer is on the phone is one of the main reasons that we went through the process of installing, configuring, and setting up ElasticPress.

So, @tlovett1 ,  is ElasticPress having a difficult time retrieving the child terms in the order taxonomy? If so, how can we fix this?

**Comment by ivankristianto** [comment]
@BurlesonBrad can you get me the query body and query args when you try to search it with email address via the search text field?
TO get the query args and query body, please follow this post: https://www.elasticpress.io/blog/2017/05/debugging/

**Comment by ivankristianto** [comment]
This issue related to incomplete indexed as reported in this issue #909.
I'm closing this issue. Feel free to reopen it if your issue still persist.
