### ISSUE TITLE
Null pointer exception while using outer document field in the script written in nested term aggregation

### ISSUE THREAD

**Issue by akashmpatel91** [10up/ElasticPress#910]
We have a use case where we are doing term aggregation and returning first 10 results in descending order of sum and SKU (SKU is text). We have SKU present in the document as well as all all nested document of the outer document Please find sample document structure below.

We want to filter buckets with bucket_selector where we will have 2 conditions, totalUnitSold < X and sku > Y (X would be number and Y would be the String). We are unable to use document SKU in the script. Please find data below. (We have SKU present in outer document as well as all nested document of the outer document, we need to find a way to get that sku in the script)
```
POST test1/_mapping/testIndex
{
  "properties": {
    "userName": {
      "type": "long"
    },
    "sku": {
      "type": "string",
      "fielddata": true
    },
    "ad": {
      "type": "nested", 
      "properties": {
        "sku": {
          "type": "string"
        },
        "unitSold":{
          "type" : "long"
        }
      }
    }
  }
}
```
Below query is returning throwing an exception

```
GET /test2/_search
{
  "_source": "{}",
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "seller": 1
          }
        }
      ]
    }
  },
  "aggs": {
    "reverse_nested": {
      "nested": {
        "path": "ad"
      },
      "aggs": {
        "group_by_sku": {
          "terms": {
            "field": "ad.sku",
            "size": 4,
            "order": {
              "totalUnitSold": "desc",
              "_term": "desc"
            }
          },
          "aggs": {
            "totalUnitSold": {
              "sum": {
                "field": "ad.unitSold"
              }
            },
            "bucket_filter": {
              "bucket_selector": {
                "buckets_path": {
                  "totalUnitSold": "totalUnitSold", 
                   "sku" : "ad.sku"
                },
                "script": "params.totalUnitSold>= 75 && params.sku == 'abc'  "
              }
            }
          }
        }
      }
    }
  }
}
```

We have tried this too "script": "params.totalUnitSold>= 75 && doc['sku'] == 'abc'  but no luck so far and getting  null_pointer_exception

Current Elasticsearch version: 5.x

**Comment by ivankristianto** [comment]
@akashmpatel91 I believe you should ask this issue in Elasticsearch forum. As it more related there.

**Comment by lukaspawlik** [comment]
Closing.
