### ISSUE TITLE
WooCommerce: update whitelisted data for 3.x

### ISSUE THREAD

**Issue by kallehauge** [10up/ElasticPress#914]
I'm currently debugging a WooCommerce shop and realised that product variation prices are no longer saved on the parent (after WooCommerce 3.x) so we do not have to store this data anymore:

```
[
	'_min_variation_price',
	'_max_variation_price',
	'_min_price_variation_id',
	'_max_price_variation_id',
	'_min_variation_regular_price',
	'_max_variation_regular_price',
	'_min_regular_price_variation_id',
	'_max_regular_price_variation_id',
	'_min_variation_sale_price',
	'_max_variation_sale_price',
	'_min_sale_price_variation_id',
	'_max_sale_price_variation_id',
]
```

A simple test to prove this would be to create a variable product in a shop without pre Woo 3.x data and see that they are no longer set.

A more "in depth" way would be to look at the Variable Product Data Store: `WC_Product_Variable_Data_Store_CPT::read_price_data`.
Here we see that a Variable Product will iterate through all their Product Variations and get `_price`, `_regular_price` and `_sale_price`.

_This could also be a start ticket to look into the rest of the whitelisted metadata._

**Comment by tlovett1** [comment]
@kallehauge do you want to create a PR for updating that whitelist?

**Comment by kallehauge** [comment]
@tlovett1 based on #946 then it looks like EP should still support Woo 2.x? If that is the case, then there is nothing to update and this issue can be closed :)
