### ISSUE TITLE
Does this plugin support Arabic language?

### ISSUE THREAD

**Issue by Mello21century** [10up/ElasticPress#915]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I tried to install it and connected it with elastic.co and fully index the website but search result appear to be totally different than keyword

Current WordPress version:
4.8.1

Current ElasticPress version:
2.3.2

Current Elasticsearch version:
5.2.2

Where do you host your Elasticsearch server:
No

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce but no data on it

Steps to reproduce:

1. N/A
2. 
3. 

Screenshots, if needed:
N/A

**Comment by ivankristianto** [comment]
Have you set the language analyzer to Arabic?
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html
