### ISSUE TITLE
Any issue if we add post using $wpdb->query("Insert into table....")

### ISSUE THREAD

**Issue by ChaitanyaSyne** [10up/ElasticPress#920]
Any issue if we add post using $wpdb->query("Insert into table....")

Have you searched for similar issues before submitting this one?
Didn't get any good result.

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I am using $wpdb->query("Insert into table....") to create a post directly into WordPress. Is there any problem in using it? I am also updating post meta for that posts.  How that post will sync with elastic search automatically? Please suggest.

Current WordPress version:
4.8.1

Current ElasticPress version:
Version 2.3.2

Current Elasticsearch version:
Version 5.5

Where do you host your Elasticsearch server: On my local machine (http://localhost:9200/)

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
No

Steps to reproduce:

1. Insert a post manually by using $wpdb->query(Insert into table ...) 
2. Not getting that post in ES results
3. 

Screenshots, if needed:

**Comment by tlovett1** [comment]
Unfortunately, this won't work as changes won't make it into Elasticsearch. Sorry!

**Comment by ChaitanyaSyne** [comment]
@tlovett1 
Thank you for your reply. We have changed our logic from insert into with WP_INSERT(). Will it work now?
