### ISSUE TITLE
Unable to sync an error occured while syncing

### ISSUE THREAD

**Issue by yshanthipriya** [10up/ElasticPress#924]
Hi 

I can not sync the data with elasticsearch where as in dev environment it works, with production database we always gets an error occured while syncing message and we can also see admin-ajax.php 500 error when the sync fails in console.  I have tried increasing the timeout value in elasticpress plugin did not help.

**Comment by andrewblossom** [comment]
Perhaps it's a php memory limit error? I've been battling the same issue when I try to sync Documents.

**Comment by yshanthipriya** [comment]
thanks @andrewblossom this worked

**Comment by chillpilllike** [comment]
Thanks andrewblossom, the second point worked

**Comment by scooterlord** [comment]
Hello, this is an old topic but I am having problems with server 500 errors. I have increased memory size to 1gb and reduced to 100 item per cycle, but I am still getting errors. Is there any way to investigate further?

**Comment by felipeelia** [comment]
@scooterlord , the best way to debug this type of error is running an index via WP-CLI with the --show-errors flag. Did you already try that? If you did and it didn't give you any hint about what is going on, I'd recommend opening a new issue :) Thanks!

**Comment by scooterlord** [comment]
@felipeelia Thanks for the swift reply! Have no idea how to do this! Any pointers?

**Comment by felipeelia** [comment]
@scooterlord sure! :) this would be the command you'd have to run in the terminal

wp elasticpress index --setup --show-errors

**Comment by scooterlord** [comment]
Felipeelia, actually it was easier than I thought to install wp-cli. Run the command, currently syncing.. will respond when it's done (shortly). Thank you so far!

**Comment by scooterlord** [comment]
I got a `Warning: Too many requests` several times, but the process continues... is this normal? Could this be the reason that the front-end hangs? The process finished successfully after all though. I don't mind doing this through CLI if it fixes my problem.

Also, I wonder why the same behaviour doesn't occur on the frontend as well?

Can I somehow increase this limit, or is it a host thing?

**Comment by scooterlord** [comment]
@felipeelia Host confirmed that there is no limit on incoming requests. What else could it be? From what I am seeing, I am well above the limits people in this thread are talking about. What other limit can I increase?

**Comment by felipeelia** [comment]
Hi @scooterlord ,

Yeah, that would require some further investigation. Do you mind opening a new issue here at GitHub? Thanks!
