### ISSUE TITLE
pipeline with id does not exist

### ISSUE THREAD

**Issue by hjanuschka** [10up/ElasticPress#927]
>Have you searched for similar issues before submitting this one?

✅
>Is this a bug, question or feature request?

question/bug
> Describe the issue you encountered:

running bulk import results in:

```
type: illegal_argument_exception
reason: pipeline with id [indexname-1] does not exist
```

>Current WordPress version:

`4.8.1`

>Current ElasticPress version:

`develop`

>Current Elasticsearch version:

`5.3.0`

> Where do you host your Elasticsearch server:

`inhouse`

> Steps to reproduce:

run `wp elasticpress index --show-bulk-errors -posts-per-page=300`

**Comment by tlovett1** [comment]
This usually happens when you don't have permission to create pipelines on your ES cluster. You'll need to contact your ES provider.
