### ISSUE TITLE
How do I enable Protected content ?

### ISSUE THREAD

**Issue by Wp1stop** [10up/ElasticPress#928]
Looking for the way to enable protected content. And when I run wp elasticpress index --setup nothing happens -   I need to allow order search on Woocommerce admin - I went over a post but I do not know how to enable Protected content

Current WordPress version:WordPress 4.8.1 r

Current ElasticPress version: . 2.3.2

Current Elasticsearch version: 2.4

Where do you host your Elasticsearch server: Cloudways

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Woocommerce - 

Steps to reproduce:

1.  Need to know how to enable protected content.  Thanks so much

**Comment by ivankristianto** [comment]
@Wp1stop 
to enable it, you can go to ElasticPress dashboard.
![screen shot 2017-09-11 at 17 15 12](https://user-images.githubusercontent.com/656006/30269902-d72d1f06-9714-11e7-806c-debeaa41dcc4.png)

**Comment by lukaspawlik** [comment]
Hi @Wp1stop ,

Does @ivankristianto suggestion solve your issue?
