### ISSUE TITLE
post_type.raw reference in query to ES cluster causes no results

### ISSUE THREAD

**Issue by maartenbusstra** [10up/ElasticPress#934]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
question/bug

Describe the issue you encountered:
Search yields no results

Current WordPress version:
4.8

Current ElasticPress version:
2.3.2

Current Elasticsearch version:
5.1

Where do you host your Elasticsearch server:
Amazon Elasticsearch Service

---

I'm getting no results because of the query being used states `post_type.raw: [...]` instead of `post_type: [...]`. How would I go about changing that?

**Comment by lukaspawlik** [comment]
Hi @maartenbusstra,

Could you please attach your full `ElasticSearch` query and `WP_Query` query arguments here? Using `post_type.raw` in ES query doesn't seem to be a problem (at least for regular use - I tested this on one of my sites). Maybe there is something wrong with your query?

**Comment by lukaspawlik** [comment]
Closing due to lack of response.

**Comment by teplyiswiter** [comment]
Hi
I faced with same behavior.
ElasticPress query contains post_type.raw 
`{"from":0,"size":10000,"sort":[{"_score":{"order":"desc"}}],"query":{"bool":{"should":[{"multi_match":{"query":"Harmonize","type":"phrase","fields":["meta.filemeta.value","attachments.attachment.content"],"boost":4}},{"multi_match":{"query":"Harmonize","fields":["meta.filemeta.value","attachments.attachment.content"],"boost":2,"fuzziness":0,"operator":"and"}},{"multi_match":{"fields":["meta.filemeta.value","attachments.attachment.content"],"query":"Harmonize","fuzziness":1}}]}},"post_filter":{"bool":{"must":[{"bool":{"must":[{"exists":{"field":"meta.filemeta"}}]}},{"term":{"post_type.raw":"attachment"}},{"term":{"post_status":"inherit"}}]}}}` 
but ElasticSearch documents contains field 
`"post_type" : "attachment"`
So no results in response. But If I manually do curl post request with mentioned query but with "post_type" filter - lot of responses receive. Please help
