### ISSUE TITLE
Multiple WP sites on single Elastic install

### ISSUE THREAD

**Issue by hotnuts21** [10up/ElasticPress#936]
Just a quick question.

Is there any issue/problem with using a single Elastic install to manage the search for multiple sites (not multisite, but individual sites and their own domains). 

thnks for an awesome plugin
Paul

**Comment by lukaspawlik** [comment]
Hi @hotnuts21,

No there is no problem at all. Each site uses its own index name (based on site domain) so all data will be logically separated. 

Please let me know if you have any questions.
