### ISSUE TITLE
Bucket Aggregation by Post Type

### ISSUE THREAD

**Issue by omar-otieku** [10up/ElasticPress#937]
I am a bit new to Elasticsearch and Elasticpress. I am trying to do a custom query with an aggregation to bucket results by post_type but I am getting an invalid response from Ep and I may be way off.

My Query:

```
$query = new \WP_Query( [
            's'     => $term,
            'aggs'  => [
                'name' => 'autosuggest',
                'use-filter'    => true,
                'aggs'          => [
                    'terms' => [
                        'field' => 'post_type.raw'
                    ]
                ]
            ]
        ] );
```

WP 4.8.2
Elasticpress 2.3.2
Elasticsearch 5.5.2

Any guidance would be appreciated.

**Comment by lukaspawlik** [comment]
Hi @omar-otieku,

Can you try removing `use-filter` parameter from your query arguments? Does it help?

**Comment by omar-otieku** [comment]
Yes, that did the trick. Thank you.
