### ISSUE TITLE
Yoast SEO conflict when activated no WooCommerce order results shown.

### ISSUE THREAD

**Issue by RonalddeRooij** [10up/ElasticPress#938]
Have you searched for similar issues before submitting this one?
Yes without finding a similar issue.

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
If plug-in Yoast SEO is active, WooCommerce Order search doesn't show any results. Turning the plug-in off, it works perfectly fine. Installed Debug with Debug ElasticPress:

If Yoast SEO is not active:
Total ElasticPress Queries: 1 

If Yoast SEO is active:
Total ElasticPress Queries: 2

First Query Args has the search keyword however the second query is missing the search keyword. 

Current WordPress version: 4.8.2
Current ElasticPress version: 2.3.2
Current Elasticsearch version: 5.6.1
Current Yoast SEO: 5.5

Where do you host your Elasticsearch server:
Sohosted

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Many plug-ins installed turned them all off and activated them one by one the issue appears if Yoast SEO is active.

Steps to reproduce:

1. Yoast SEO plug-in active
2. Search WooCommerce orders (shows result number, without the results itself)
3. Turn of Yoast SEO plug-in, everything works fine

Screenshots, if needed:
![extra-information](https://user-images.githubusercontent.com/16287765/30910261-467c711a-a384-11e7-8da5-b3c0fa21abf6.jpg)

**Comment by lukaspawlik** [comment]
Thanks @RonalddeRooij for reporting this. I'll check it and I'll get back to you as soon as possible.

**Comment by RonalddeRooij** [comment]
Hi, thanks for picking this up. Do you have any update on this issue?

**Comment by lukaspawlik** [comment]
Hello,

I don't have any update on this ticket yet. I should have something near the end of the week.

**Comment by lukaspawlik** [comment]
Hello @RonalddeRooij,

I was able to inspect this and identify issue. I've prepared fix for this in pull request https://github.com/10up/ElasticPress/pull/947.

Basically this issue occurs only on WooCommerce 2.x. Version 3.x is not affected. I suggest updating WooCommerce to version 3.x or waiting until #947 is merged and new ElasticPress version released.

**Comment by RonalddeRooij** [comment]
@lukaspawlik Thank you very much for investigating the issue. I will update WooCommerce from 2.x to version 3.x to fix my issue.
