### ISSUE TITLE
Are facets supported?

### ISSUE THREAD

**Issue by paulgibbs** [10up/ElasticPress#942]
I've searched the issues and wiki, but I want to check if there's any special support for Elasticsearch facets in ElasticPress? I have had a quick search of the code but I am unfamiliar with what I should be looking for, so figured I'd ask. :)

**Comment by ivankristianto** [comment]
@paulgibbs facetwp use return fields id, which is not supported in current version.
But there is a fixed and will release in next 2.4. 
PR: https://github.com/10up/ElasticPress/pull/760

**Comment by lukaspawlik** [comment]
@paulgibbs Maybe this [article](https://www.elasticpress.io/blog/2017/09/aggregations-api-for-grouping-data/) will be helpful in case you have an option to modify _WP_Query_ programmatically.

**Comment by lukaspawlik** [comment]
Closing due to no response.
