### ISSUE TITLE
PHP Notice:  Trying to get property of non-object in /var/www/mysite.com/wp-content/plugins/elasticpress/features/woocommerce/woocommerce.php on line 274

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#943]
Have you searched for similar issues before submitting this one?

Yes, but the issue was closed without resolution.

Is this a bug, question or feature request?

Bug.

Describe the issue you encountered:

Debug log shows the following errors pretty frequently:

`PHP Notice:  Trying to get property of non-object in /var/www/mysite.com/wp-content/plugins/elasticpress/features/woocommerce/woocommerce.php on line 274`

As far as I can tell, WordPress, WooCommerce, and ElasticPress work properly, i.e., searches return the expected results.

Current WordPress version:

4.8.2

Current ElasticPress version:

2.3.2

Current Elasticsearch version:

5.6.2

Where do you host your Elasticsearch server:

Self-hosted.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce, Yoast.

Steps to reproduce:

1. Install WordPress, WooCommerce, and ElasticPress
2. Enable and index WooCommerce products
3. Check debug.log

**Comment by lukaspawlik** [comment]
Hi @ahmed-sigmalux,

Thanks for reporting this. I'll check this and create PR if needed.

**Comment by lukaspawlik** [comment]
@ahmed-sigmalux,

PR created and waiting for review.

**Comment by ahmed-sigmalux** [comment]
Thanks for the prompt reply and fix!

**Comment by lukaspawlik** [comment]
This has been merged to develop branch and will be released in 2.4

Closing.
