### ISSUE TITLE
How to get post meta from id?

### ISSUE THREAD

**Issue by JACK-ARRAY** [10up/ElasticPress#944]
I want to know how how i can get post meta value from id with Elasticpress. Here is wordpress solution

`$thumburl = get_post_meta($id, 'thumb', true);`

Getting post 'thumb' meta from 'id'.

Pulling post meta from wordpress is causing high mysql load. So please share a solution.
Thanks

**Comment by kallehauge** [comment]
Just to provide a quick answer for you @JACK-ARRAY _(I'm not a maintainer)_: This is currently not possible.

But if you feel like there is a gain from this, then you could rephrase the issue as a feature-request/enhancement with arguments of why and how this can be a performance-enhancement.

**Comment by JACK-ARRAY** [comment]
I got the solution thanks.

**Comment by tlovett1** [comment]
Sorry not possible. MySQL should be faster for this anyway.
