### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by JukeBoxDeveloper** [10up/ElasticPress#950]
Have you searched for similar issues before submitting this one?
Yes
Is this a bug, question or feature request?
Bug 
Describe the issue you encountered:
while indexing is running I get an error, the log show error 500 but there's no further description other than : {success: false} success:false, it usually get's through the first 5000 documents before this happens.

edit:

To add more information, console error is saying Syntax error, unrecognized expression: {success: false}

Current WordPress version:
4.8.2
Current ElasticPress version:
2.3.2
Current Elasticsearch version:
5.1.1
Where do you host your Elasticsearch server:
Qbox
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
None
Steps to reproduce:

1. Delete elastic search index
2. Re index documents from wp
3. 

Screenshots, if needed:

**Comment by JACK-ARRAY** [comment]
I think its your QBOX problem. Please contact them.

**Comment by lukaspawlik** [comment]
Hi @JukeBoxDeveloper,

I am unable to inspect this as your report doesn't contain anything that could help us. Error 500 may be returned for many reasons and for example your object may have too many meta fields to index and Elasticsearch may be rejecting this request. If you could provide us any Elasticsearch error logs that would tell us if it's plugin bug or not.

I am going to close this issue unless you can provide us error log.
