### ISSUE TITLE
Indexing leaves out about 33% of the posts

### ISSUE THREAD

**Issue by javorszky** [10up/ElasticPress#953]
## Have you searched for similar issues before submitting this one?

yes

## Is this a bug, question or feature request?

not sure. I don't know where to start finding out why this had happened. I suspect it's a bug / misconfiguration issues

## Describe the issue you encountered:

* I have a local site.
* ElasticSearch installed (version 5.6).
* I filter the index name so I remember what it is. Using `ep_index_name`
* I am using wpcli
* I drop the index with `wp elasticpress delete-index` for good measure, even though it shouldn't exist
* I recreate the index with `wp elasticpress index --posts-per-page=1000` (1500 would timeout)
* it finishes, and tells me it indexed 129k posts in 3300 seconds
* I then look at the indices by visiting http://localhost:9200/_cat/indices?v
* I see that the index only has 86.5k posts
* there's a difference of about 42k posts... where did they go?
* wp cli indexing did not time out

## Current WordPress version:

4.8.2

## Current ElasticPress version:

2.4

## Current Elasticsearch version:

5.6.3

## Where do you host your Elasticsearch server:

localhost, via `brew install elasticsearch`

## Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

```
$ wp plugin list --status=active
+--------------------------------------------+--------+-----------+-----------+
| name                                       | status | update    | version   |
+--------------------------------------------+--------+-----------+-----------+
| bj-lazy-load                               | active | available | 1.0.8     |
| <client>-conditional-quantity-field-master | active | none      | 1.0.0     |
| sizeguide                                  | active | available | 2.1       |
| custom-menu-wizard                         | active | none      | 3.3.0     |
| debug-bar                                  | active | none      | 0.9       |
| debug-bar-elasticpress                     | active | none      | 1.2       |
| <client>-defaulttax-master                 | active | none      | 1.0.1     |
| disable-comments                           | active | none      | 1.7       |
| disable-emails                             | active | none      | 1.3.0     |
| disable-google-fonts                       | active | none      | 1.3       |
| elasticpress                               | active | none      | 2.4       |
| <client>-ep-extended-master                | active | none      | 1.2       |
| enhanced-text-widget                       | active | available | 1.4.5     |
| envato-market                              | active | none      | 1.0.0-RC2 |
| font-awesome                               | active | none      | 3.2.1     |
| formidable                                 | active | available | 2.02.12   |
| a                                          | active | none      | 1.0.0     |
| mailchimp-for-wp                           | active | available | 4.1.5     |
| oomph-clone-widgets                        | active | none      | 2.0.0     |
| <client>-recount-product-visibility        | active | none      | 1.0.0     |
| redirection                                | active | available | 2.6.4     |
| scripts-n-styles                           | active | available | 3.4.0     |
| shiftnav-pro                               | active | none      | 1.6.1.2   |
| simple-custom-css                          | active | none      | 3.3       |
| storefront-designer                        | active | none      | 1.8.3     |
| storefront-top-bar                         | active | none      | 1.1.1     |
| storefront-woocommerce-customiser          | active | none      | 1.9.0     |
| toggle-wpautop                             | active | none      | 1.2.5     |
| ubermenu                                   | active | none      | 3.2.7     |
| woocommerce                                | active | available | 3.1.1     |
| woocommerce-hide-weight-dimensions-master  | active | none      | 0.2       |
| woocommerce-advanced-bulk-edit             | active | available | 4.2.2     |
| woocommerce-attribute-descriptions-master  | active | none      | 1.0.0     |
| woocommerce-currency-converter-widget      | active | none      | 1.6.5     |
| woocommerce-customer-order-csv-export      | active | none      | 4.3.5     |
| woocommerce-direct-variation-link          | active | none      | 1.0.3     |
| woocommerce-shipping-fedex                 | active | none      | 3.4.9     |
| woocommerce-gateway-paypal-pro             | active | none      | 4.4.7     |
| woocommerce-pretty-emails                  | active | none      | 1.8.2     |
| woocommerce-product-image-flipper          | active | available | 0.3.0     |
| jck-woo-quickview                          | active | available | 3.4.4     |
| woocommerce-smart-coupons                  | active | none      | 3.3.5     |
| woocommerce-social-login                   | active | none      | 2.3.1     |
| woocommerce-store-credit                   | active | none      | 2.1.8     |
| woocommerce-table-rate-shipping            | active | none      | 3.0.4     |
| woocommerce-tab-manager                    | active | none      | 1.8.2     |
| woosidebars                                | active | none      | 1.4.3     |
| wp-all-export-pro                          | active | none      | 1.4.7     |
| wpmandrill                                 | active | none      | 1.33      |
+--------------------------------------------+--------+-----------+-----------+
```

## Steps to reproduce:

1. I'm not sure
2. posts missing are mostly products
3. some products are present in the index though

**Comment by javorszky** [comment]
Looking at the logs, I have a feeling it's https://github.com/10up/ElasticPress/issues/861

**Comment by javorszky** [comment]
According to the log, the limit is 1000. The mapping files do specify a value to be 5000 by default, so I guess that never gets pulled through due to a mismatch between elasticsearch versions?

Is there a mappings file for 5.6?

**Comment by javorszky** [comment]
I've followed things:

* the mappings file isn't automatically sent down to the server when doing indexing
* I called `wp elasticpress put-mapping`, which did send the 5.2 mapping file to my 5.6.3 server, which seemed okay, and deleted the index as well
* importing everything again resulted in the index and the CLI being in agreement about how  many posts there are. The meta key that I was missing is also in the keys list according to kibana

So questions:

* when will ES 5.6 be supported officially?
* is the mapping not sent to the ES server on purpose? Is it an activate / deactivate thing?
* can the CLI command fail with `WP_CLI::error` as soon as the ES server returns an error about max fields?

**Comment by lukaspawlik** [comment]
Hey @javorszky ,

Just a question: Current official ElasticPress release is 2.3.2 (https://wordpress.org/plugins/elasticpress/). Do you use our current develop branch instead of plugin from official WordPress repositiory?

**Comment by javorszky** [comment]
I don't actually know. It's a client's site's archive. I can try with a release version, or with latest develop branch.

**Comment by lukaspawlik** [comment]
@javorszky I don't suggest using develop branch as it doesn't have to be stable. Could you please use 2.3.2 from WordPress repository?

**Comment by javorszky** [comment]
Sure, let me try that.

**Comment by javorszky** [comment]
So not sure what would have changed when I downgraded from 2.4 to 2.3.2, but using the current release version:

* I still need to manually put the mapping onto the ES server with `wp elasticpress put-mapping`
* there is no 5-2.php mapping file
* indexing still errors out with the index.mappings.maxfield thing

**Comment by lukaspawlik** [comment]
Hi,

Please let me clarify the issue with putting mapping. When you use `wp-cli` to index site mapping is being sent only when you add `--setup` switch to `index` command:

`wp elasticpress index --setup` will drop your index, recreate it, send mapping and index data. If you omit `--setup` in `wp-cli` then mapping is not sent. It's intentional behaviour.

As you mentioned on `2.3.2` there is no `5.2` mapping file and it's introduced in current develop branch that is intended to be `2.4`.

Current develop branch is compatible with `ES 5.6` however it doesn't contain any specific mapping for this version and we use mapping file used for `ES 5.2`.

I can investigate your issue with `index.mappings.maxfield` but I need your database dump to give you any reliable answer/solution.

**Comment by javorszky** [comment]
The db dump is 2 Gb and it's client data, so I'll have to say no to that.

The info on setup is helpful.

The issue with the `index.mappings.maxfield` goes away as soon as I either push the mapping up manually, or use the `--setup` switch.

**Comment by javorszky** [comment]
If you want to reproduce the issue, just have an example site, and set the maxfield low enough so that the log files will start generating errors about it. WPCLI just carries on

**Comment by lukaspawlik** [comment]
Thank you. I am marking this as `enhancement` as it's mostly about better messaging in `wp-cli` when posts are not indexed correctly (for any reason).

Thank you for reporting this!

**Comment by lukaspawlik** [comment]
I've mentioned about need for more verbose messaging in https://github.com/10up/ElasticPress/issues/907 so I am closing this one to keep issue list quite clean. Thanks for reporting this @javorszky

**Comment by javorszky** [comment]
That's a different issue.

More verbose messaging means that there IS a failure message, but it's not good enough.

The issue I'm talking about, and have provided steps on how to reproduce, is that syncing data fails, ElasticSearch returns an error, logs it in its error log, yet WP-CLI (and I suspect the GUI version too) carries on like nothing had happened instead of telling me that *something's* gone wrong.

This silently fails.

The solution isn't more verbose messaging. The solution is throwing an error when ElasticSearch couldn't deal with something we've given it.

**Comment by javorszky** [comment]
Please reopen the issue.

**Comment by lukaspawlik** [comment]
I'll also add your note about throwing an error instead of verbose messaging in wp-cli.

Re-opening this.

**Comment by javorszky** [comment]
#907 is a different issue from what I can tell. They might be connected, but at least 907 GETS some error message. This one doesn't.

**Comment by lukaspawlik** [comment]
@javorszky purpose of #907 is to improve `wp-cli` messaging and hopefully also throwing errors/warnings depending on indexing problems. I am trying to solve general issue with lack of `wp-cli` verbosity (even if it means throwing errors) when something doesn't go smooth and your issue is a part of this problem (lack of any information about unsuccessful plugin operations when using `wp-cli`). 

@tlovett1 I am assigning this issue to you to decide if we can handle overall `wp-cli` issues with messaging indexing issues as a part of #907 improvement or this one will be kept as a separate problem.

**Comment by oscarssanchez** [comment]
We had a similar issue reccently that was related with mappings and excessive fields generated in elasticsearch while indexing. 

We were able to partially solve this by setting the total_field_max to 10,000 for which ElasticPress already does provide a filter to modify. 

We ended up solving this and tracing the error down to a lot of similar meta keys, causing the mappings of elasticsearch to be absurdly big.

Due to the huge amount of plugins and / or previously installed ones, I'm almost sure there's a lot of meta that's likely to be similar in your wp_postmeta table, due to poorly written plugins. 

If you are still having this issue @javorszky , please check out for similar meta_key values. You can do this already by pinging your mappings in es by doing : `your-esserver-adress/your-es-index-name/_mappings` 

Look out for similar meta values, delete them from the wp_postmeta table and you'll be good to go :)
