### ISSUE TITLE
Securing ElasticSearch running on dedicated server

### ISSUE THREAD

**Issue by renanno** [10up/ElasticPress#956]
Hi

This is more like a question than an issue. I hope there is no problem posting it here.

I can see ElasticPress recommend it's own service to index protected content.

I have a dedicated server running ElasticSearch exclusively. And I have another dedicated server running my Wordpress website. The second server connects to the first using port 9200, which returns elasticsearch's results.

I could install Shield on the second server. But, since I'm running a dedicated server with no public access, without any website running on it and running only Elasticsearch service, wouldn't be easier for me to block access to port 9200 for everyone, except the second server IPs?

That way, could I start indexing protected content securely using ElasticPress?

**Comment by lukaspawlik** [comment]
Hi @renanno,

You're correct. As long as there is no way to connect directly/indirectly to your Elasticsearch server outside your infrastructure then you're good to enable _Protected Content_ feature.

Thanks
