### ISSUE TITLE
Why does Elasticsearch slow down this basic query?

### ISSUE THREAD

**Issue by edwardr** [10up/ElasticPress#964]
I'm working with Elasticsearch (EP plugin) for the first time to see if it can help us with some of our larger queries. I set up a test environment and ran tests using WP_Query with the ep_integrate parameter as true and false, and have the following results (avg. of three tests each):

With ep_integrate = true:
5.50 second average

With ep_integrate = false:
2.85 second average.

The sample query is rather basic and returns approximately 10k results:

```
$args = array(
    'ep_integrate' => true,
    'post_type' => 'member',
    'posts_per_page' => 10000,
);

$members = new WP_Query($args);
```

Is something like this to be expected without a search parameter? I was under the impression that Elasticsearch could possibly improve the performance of queries overall, regardless of whether or not they are search queries.

**Comment by tott** [comment]
Hi Edward,

with this amount of results returned the networking overhead might play in here. How quick is the connection between your web server and your ElasticSearch instance? How are the results when setting posts per page to 100, 500, 1000?

Looking forward to hearing from you

Thorsten

**Comment by JACK-ARRAY** [comment]
Elasticpress returned only ID of posts and rest of post contents returned by MYSQL server. So it may a bit slower while loading content from MYSQL server.

**Comment by edwardr** [comment]
I'm getting similar results with smaller fetches -- 500, 1000 items, etc.

I'll try some more complex queries with inner joins and see if there's any performance difference.

**Comment by edwardr** [comment]
I ran these same tests on a different build and found dramatic performance improvements using ep_integrate, so I suspect this may be related to my testing ES instance. I'll update when I get to the bottom of it.

**Comment by tlovett1** [comment]
Definitely sounds like Elasticsearch latency issues.

**Comment by AustinTBiggs** [comment]
> I was under the impression that Elasticsearch could possibly improve the performance of queries overall, regardless of whether or not they are search queries.

Is this correct? If so wonderful news!

**Comment by edwardr** [comment]
`Is this correct? If so wonderful news!`

Absolutely. The performance difference was pretty remarkable -- roughly an 80% reduction in my particular test case.
