### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by eugene-manuilov** [10up/ElasticPress#965]
Hi @tlovett1,

I have decided to open this ticket to start a discussion about an implementation of faceted search support in this plugin. I have seen a few tickets (#282, #942) where people ask about it, so it may be a good candidate to include into the next version.

For the beginning, we can "override" **Filter Products by Attribute** widget by WooCommerce and implement facets there. By doing it, we will make sure that it can be integrated seamlessly into any theme which already supports WooCommerce.

Later on, we can create a new widget which will work with regular posts and custom post types, and inherit markup and styles of standard **Categories** widget.

Let me know what do you think about it?

cc @brandwaffle

**Comment by ryansmiller** [comment]
Hi guys,

Is this feature being added to 2.5? I'm about to start a new project where Faceted search is required and I'd like to also use ElasticPress. I've noticed that there is a plugin floating around connecting FacetWP with ElasticPress (https://github.com/MikkoVirenius/vafael), but curious if this type of integration is coming in the next release or if it's still being figured out.

Thanks!

**Comment by elvismdev** [comment]
@ryansmiller As far as now I could say using the latest versions of ElasticPress and FacetWP works together. Just make sure to use the filter I mention below to disable the "ordeby = post__in" argument that get's added by FacetWP, this one is not supported by Elasticsearch. You would have a problem similar to issue #1081 

```php
add_filter( 'facetwp_use_search_relevancy', '__return_false' );
```
