### ISSUE TITLE
Notice: Array to string conversion in elasticpress-stream/includes/functions/core.php on line 165

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#966]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Bug.

Describe the issue you encountered:

`Notice: Array to string conversion in /var/www/wordpress/wp-content/plugins/elasticpress-stream/includes/functions/core.php on line 165`

Current WordPress version:

4.8.3

Current ElasticPress version:

2.4

Current Elasticsearch version:

5.6.3

Where do you host your Elasticsearch server:

Self-hosted.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce and Yoast.

Steps to reproduce:

1. Start with a fresh Elasticsearch installation
2. Run "wp elasticpress index"
3. Read the console ouput

Screenshots, if needed:

**Comment by eugene-manuilov** [comment]
Hi @ahmed-sigmalux,

this bug is relevant to **elasticpress-stream** plugin, which is stored in another repository. I have created a pull request to fix this issue. Once it gets approved, you will be able to grab it.

https://github.com/10up/elasticpress-stream/pull/2

**Comment by ahmed-sigmalux** [comment]
Thank you for the prompt fix. Also, my apologies for posting in the wrong repository.
