### ISSUE TITLE
Warning: First parameter must either be an object or the name of an existing class in elasticpress/classes/class-ep-api.php on line 696

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#967]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Bug.

Describe the issue you encountered:

`Warning: First parameter must either be an object or the name of an existing class in /var/www/wordpress/wp-content/plugins/elasticpress/classes/class-ep-api.php on line 696`

Current WordPress version:

4.8.3

Current ElasticPress version:

2.4

Current Elasticsearch version:

5.6.3

Where do you host your Elasticsearch server:

Self-hosted.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

WooCommerce and Yoast.

Steps to reproduce:

1. Start with a fresh Elasticsearch installation
2. Run "wp elasticpress index"
3. Read the console output

Screenshots, if needed:

**Comment by eugene-manuilov** [comment]
Thanks @ahmed-sigmalux!

I have submitted a pull request to fix this issue.

**Comment by eugene-manuilov** [comment]
Re-created pull request against develop branch. #1009
