### ISSUE TITLE
Elasticpress fails indexing posts to elasticsearch server

### ISSUE THREAD

**Issue by yshanthipriya** [10up/ElasticPress#969]
Hi,

we are currently running following configuration in our site.
Current WordPress version:4.8.1
Current ElasticPress version:2.4
Current Elasticsearch version:v2.0.1
 
We recently switched our windows server to linux after the change elasticpress(v2.0.1) stopped indexing the posts to elasticsearch server if we see the connections in backend throughing the error set proper host where as the configurations are correct. We updated the elasticpress plugin from v2.0.1 to v2.4 but did not help still the posts are not getting indexed in elasticsearch. 

Please find the attachments we found so far with elasticpress
![elasticpress-host-fail](https://user-images.githubusercontent.com/28725767/32484042-8290acc4-c3c4-11e7-8ffc-4432d9292e58.jpg)
![elasticpress-debugger-log](https://user-images.githubusercontent.com/28725767/32484051-8ae085c0-c3c4-11e7-8ad4-991e56bd0d97.jpg)
![elasticpress-sync-fail](https://user-images.githubusercontent.com/28725767/32484058-8f273cfa-c3c4-11e7-9897-a3dcfcaa0d06.jpg)

Is there any solutions for this issue?

**Comment by eugene-manuilov** [comment]
Hi @yshanthipriya!

Is your elasticsearch server reachable? Looks like ElasticPress can't connect to it.

**Comment by yshanthipriya** [comment]
we are able to connect to elasticsearch server with curl in our site. Is there any other way to check the connection?

**Comment by eugene-manuilov** [comment]
@yshanthipriya, it's hard to say why without seeing what you are doing. The fact that it stopped working after you switched server, makes me think that it is something related to your server configuration. Unfortunately, your situation is out-of-scope for this plugin and we can't help with that.

Am going to close this thread for now. But if you find an issue relevant to the plugin, feel free to reopen it.
