### ISSUE TITLE
Support for 'relation' in tax_query inner arrays

### ISSUE THREAD

**Issue by tirriainen** [10up/ElasticPress#971]
Have you searched for similar issues before submitting this one?
Yes
Is this a bug, question or feature request?
Feature request

Is there a way to use 'relation' in tax_query (and meta_query) inner arrays? What I'm trying to achieve is something like this:

```
$args['tax_query'] => [
	'relation' => 'and'
	[
		'taxonomy' => TAX1_TAX_NAME,
		'terms'    => 1,					
	],
	[
		'relation' => 'or',
		[
			'taxonomy' => TAX2_TAX_NAME,
			'terms'    => 2,							
		],
		[
			'taxonomy' => TAX3_TAX_NAME,
			'terms'    => 3,							
		]				
	]
];
```

**Comment by eugene-manuilov** [comment]
Hi @tirriainen! Thanks for submitting this. We will work on it.
