### ISSUE TITLE
a way to exclude posts from indexing to ES.

### ISSUE THREAD

**Issue by ChangbaeSong** [10up/ElasticPress#972]
Have you searched for similar issues before submitting this one?
yes
Is this a bug, question or feature request?
question
Describe the issue you encountered:
what is the best way to exclude posts by a custom field, boolean when indexing(initial, created, updated) to ES?
Current WordPress version:
Version 4.8.3
Current ElasticPress version:
Version 2.1.1

**Comment by eugene-manuilov** [comment]
Hi @ChangbaeSong,

please, see #253 thread for more insights.
