### ISSUE TITLE
Can Elasticpress be used for $wpdb queries?

### ISSUE THREAD

**Issue by andrewbanchich** [10up/ElasticPress#973]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Question

Describe the issue you encountered:

I would like to be able to use Elasticpress with $wpdb SQL queries instead of just WP_Query, but I'm not sure if there is a way to do that already. I can't find much in depth documentation.

Current WordPress version:

4.8

Current ElasticPress version:

2.4

Current Elasticsearch version:

5.6

**Comment by eugene-manuilov** [comment]
Hi @andrewbanchich,

there is no way to use it with $wpdb. Why do you need it?

**Comment by andrewbanchich** [comment]
@eugene-manuilov There are some core WordPress functions which take a very long time to load from MySQL which I would like to reroute to Elasticsearch. Looking at their code, I see they use a normal SQL query using $wpdb.

**Comment by eugene-manuilov** [comment]
Can you cache results for those functions?

**Comment by andrewbanchich** [comment]
@eugene-manuilov I'm not sure, but even if we can, I would ideally like to use Elasticsearch instead of querying MySQL so that the data is always up to date and to make use of other Elasticsearch stuff.

**Comment by andrewbanchich** [comment]
I'm thinking if there is no way to hook into and override core WordPress functions that it might be useful to have an ElasticPress library of functions we can use that duplicate the core WordPress functions but use Elasticsearch instead. For example, instead of get_posts() we could call ep_get_posts().

@tlovett1 Any thoughts on this?

**Comment by eugene-manuilov** [comment]
get_posts() function uses WP_Query internally, so it can integrate with ES, just add `"ep_integrate" => 1` to the arguments list and EP will redirect a request to the ES.

**Comment by andrewbanchich** [comment]
Yep, I just reference that as an example. I mean for other functions which use $wpdb.

**Comment by eugene-manuilov** [comment]
I don't believe we will have time for it. If you want, submit a pull request and we can check that. For now, I am going to close this ticket because there is nothing else what we can do here.
