### ISSUE TITLE
Upgrading Elasticsearch to 6.0 causes "Not acceptable" error in WP-CLI

### ISSUE THREAD

**Issue by andrewbanchich** [10up/ElasticPress#974]
Have you searched for similar issues before submitting this one?

Yes.

Is this a bug, question or feature request?

Bug

Describe the issue you encountered:

I upgraded Elastisearch from 5.6 to 6.0 and ElasticPress via WP-CLI throws a "Not acceptable" error when I try to index.

Current WordPress version:

4.9

Current ElasticPress version:

2.4

Current Elasticsearch version:

6.0

**Comment by mustafauysal** [comment]
Hi @andrewbanchich,

Because ElasticPress supports max 5.6 right now. See: https://github.com/10up/ElasticPress/blob/2.4/elasticpress.php#L36

**Comment by andrewbanchich** [comment]
Do you know how long it usually takes to support an upgrade like this?

**Comment by andrewbanchich** [comment]
@mustafauysal Just letting anyone else experiencing this know: Elasticsearch 6.0 works fine for me with ElasticPress except for this issue, which was caused by Elasticsearch 6.0 doing strict type checking using the headers of the http requests. You have to explicitly set the Content-Type as JSON or else Elasticsearch will throw this error.

I confirmed this by installing Nginx as configuring it to set that header on all requests.
