### ISSUE TITLE
broken connections during indexing

### ISSUE THREAD

**Issue by andrewbanchich** [10up/ElasticPress#975]
Have you searched for similar issues before submitting this one?

Yes

Is this a bug, question or feature request?

Feature request / question / bug

Describe the issue you encountered:

I'm not sure if there is some config issue causing this, but I've found using ElasticPress via WP-CLI that when indexing a relatively large database it will often randomly stop, and I'll have to restart using the `--offset` option, and look at Elasticsearch to find the number of documents it stopped at. It happens quite a lot, and it would be much nicer if it handled this in a different way. Sometimes Elasticpress has no error message at all when it does this, but other times I do get a CURL error of a timeout of 30 seconds, having received 0 bytes.

Ideally, it just wouldn't drop the connection or would automatically resume where it left off. If that isn't possible, it would be nice to have a `--resume` option that would check where it left off since last time and offset the indexing by that amount.

Current WordPress version:

4.9

Current ElasticPress version:

Latest

Current Elasticsearch version:

6.0

Where do you host your Elasticsearch server:

AWS

**Comment by eugene-manuilov** [comment]
Hi @andrewbanchich,

seems like your Elasticsearch server works too slowly... Also, as of now Elasticsearch 6.0 is not supported officially. Can you downgrade it to 5.6 and check it?

**Comment by andrewbanchich** [comment]
@eugene-manuilov Yep, I did that and it had the same issue. I did finally realize, though, that if I lower the number of posts per page while indexing that it works fine. By default it loses the connection very often, but if I set it to 75 posts per page it will have no problem.

**Comment by andrewbanchich** [comment]
@eugene-manuilov I actually just checked it again after letting it run for a while at 75 posts per page, and tried removing the `posts-per-page` option altogether and it is working just fine now at 350 per page. I assume that the issue was some kind of very large sized posts near the beginning of indexing or something?

**Comment by eugene-manuilov** [comment]
It is hard to say why it happens on your end... I tend to consider it as your Elasticsearch latency issue and close this issue for now. If you find something else, feel free to reopen it.
