### ISSUE TITLE
post type check for ep_sync_post

### ISSUE THREAD

**Issue by mustafauysal** [10up/ElasticPress#976]
Have you searched for similar issues before submitting this one?
Yes.
Is this a bug, question or feature request?
Question.
Describe the issue you encountered:

Currently, ElasticPress allows to index non-indexable post_types through `ep_sync_post`. Internally, It respects the post types but, it might be safer to check inside `ep_sync_post`. What do you think about this?

```
Current WordPress version:
4.8.3
Current ElasticPress version:
1.7.5
Current Elasticsearch version:
2.4
```

**Comment by eugene-manuilov** [comment]
Hi @mustafauysal,

yes, it sounds useful, but by not having it, we have an ability to index "edge case" posts. Plus, if we add it there we might get compatibility issues if somebody already uses it. So, we can't simply add it there...

**Comment by mustafauysal** [comment]
Hi @eugene-manuilov,

Thanks for the explanation, you might be right for the "edge case" situations. It seems changing EP core for this purpose can cause more problem than it solves.

I think we can handle this case with using `ep_post_sync_kill` without changing current behaviour. Something like;

```

add_filter( 'ep_post_sync_kill', function ( $status, $post_args, $post_id ) {
	if ( ! in_array( $post_args['post_type'], ep_get_indexable_post_types() ) ) {
		return true;
	}

	return $status;
}, 10, 3 );
```

**Comment by eugene-manuilov** [comment]
I would escape overcomplicating that logic. It is just a matter of synchronization configuration setup, there is no need to go deeply into checking everything. I am going to close this issue for now, but if you have more to say, feel free to reopen it.
