### ISSUE TITLE
Ordering by title when titles have special characters

### ISSUE THREAD

**Issue by tirriainen** [10up/ElasticPress#977]
Have you searched for similar issues before submitting this one?
Yes
Is this a bug, question or feature request?
Question

Is there a way to make post titles with scandinavian characters to be sorted correctly in the queries? At the moment Ä is mixed with A in post archive when orderby is set to 'title'.

The problem is mentioned here, but at the moment there isn't a filter to affect the mappings https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-folding.html

**Comment by mustafauysal** [comment]
Hi @tirriainen,

You can use `ep_config_mapping` for the custom mapping. Also `ep_analyzer_language` available for the changing analyzer language.
