### ISSUE TITLE
enabling autosuggest via wp-cli

### ISSUE THREAD

**Issue by andrewbanchich** [10up/ElasticPress#978]
Have you searched for similar issues before submitting this one?

yes

Is this a bug, question or feature request?

question/bug

Describe the issue you encountered:

ElasticPress finished indexing, but I saw autosuggest was not activated, so I ran `wp elasticpress activate-feature autosuggest` and it said it activated the feature. I then ran `wp elasticpress list-features` and it simply shows `Active features:` without anything listed. If I try running `wp elasticpress activate-feature autosuggest` again, and it outputs `Error: This feature is already active` even though it doesn't list it when I run `list-features`. I'm not sure if this would have anything to do with it, but I wanted to mention I also disabled reindexing from the dashboard with `define( 'EP_DASHBOARD_SYNC', false );`.

This happens to me currently when I run it with Elasticsearch 6.0, but the same issue happened before I upgraded from Elasticsearch 5.6, so I don't think it has to do with it being 6.0.

I would love to be able to start using autosuggest, but I'm not sure if this is a bug or I'm misunderstanding something.

Also, I was wondering: when it says it requires reindexing, that means it has to upload the entire database to Elasticsearch again? Is there not any way to enable autosuggest without doing that?

Thank you!

Current WordPress version: 4.9

Current ElasticPress version: 2.4

Current Elasticsearch version: 6.0

Where do you host your Elasticsearch server: AWS

**Comment by eugene-manuilov** [comment]
Hi @andrewbanchich,

unfortunately, i can't replicate this issue on my end... Do you see anything suspicious in your `debug.log` file? 

> Also, I was wondering: when it says it requires reindexing, that means it has to upload the entire database to Elasticsearch again? 

It has to re-index all posts which previously have been already indexed. What usually not the entire database.

> Is there not any way to enable autosuggest without doing that?

Autosuggest requires additional changes in mapping configuration to work properly. That leads to the need to re-index posts. So, unfortunately, reindexing is required.

**Comment by andrewbanchich** [comment]
@eugene-manuilov where do I find the `debug.log` file?

**Comment by andrewbanchich** [comment]
here is what i get with the `--debug` flag for wp-cli
```
/Applications/MAMP/htdocs/domain.com (elasticsearch *) λ ~/wp-cli.phar elasticpress list-features --debug
Debug (bootstrap): No readable global config found (0.054s)
Debug (bootstrap): No project config found (0.054s)
Debug (bootstrap): argv: /Users/abanchich/wp-cli.phar elasticpress list-features --debug (0.054s)
Debug (bootstrap): ABSPATH defined: /Applications/MAMP/htdocs/domain.com/ (0.055s)
Debug (bootstrap): Begin WordPress load (0.055s)
Debug (bootstrap): wp-config.php path: /Applications/MAMP/htdocs/domain.com/wp-config.php (0.055s)
Debug (bootstrap): Set URL: domain.com/ (0.056s)
Debug (bootstrap): Loaded WordPress (0.349s)
Debug (bootstrap): Running command: elasticpress list-features (0.349s)
Active features:
/Applications/MAMP/htdocs/domain.com (elasticsearch *) λ ~/wp-cli.phar elasticpress activate-feature autosuggest --debug 
Debug (bootstrap): No readable global config found (0.051s)
Debug (bootstrap): No project config found (0.052s)
Debug (bootstrap): argv: /Users/abanchich/wp-cli.phar elasticpress activate-feature autosuggest --debug (0.052s)
Debug (bootstrap): ABSPATH defined: /Applications/MAMP/htdocs/domain.com/ (0.052s)
Debug (bootstrap): Begin WordPress load (0.053s)
Debug (bootstrap): wp-config.php path: /Applications/MAMP/htdocs/domain.com/wp-config.php (0.053s)
Debug (bootstrap): Set URL: domain.com/ (0.053s)
Debug (bootstrap): Loaded WordPress (0.343s)
Debug (bootstrap): Running command: elasticpress activate-feature (0.343s)
Error: This feature is already active
/Applications/MAMP/htdocs/domain.com (elasticsearch *) λ ~/wp-cli.phar elasticpress deactivate-feature autosuggest --debug
Debug (bootstrap): No readable global config found (0.049s)
Debug (bootstrap): No project config found (0.05s)
Debug (bootstrap): argv: /Users/abanchich/wp-cli.phar elasticpress deactivate-feature autosuggest --debug (0.05s)
Debug (bootstrap): ABSPATH defined: /Applications/MAMP/htdocs/domain.com/ (0.051s)
Debug (bootstrap): Begin WordPress load (0.051s)
Debug (bootstrap): wp-config.php path: /Applications/MAMP/htdocs/domain.com/wp-config.php (0.051s)
Debug (bootstrap): Set URL: domain.com/ (0.051s)
Debug (bootstrap): Loaded WordPress (0.333s)
Debug (bootstrap): Running command: elasticpress deactivate-feature (0.334s)
Error: Feature is not active
```

**Comment by eugene-manuilov** [comment]
@andrewbanchich, you need to enable debugging in your WordPress. See [this article](https://codex.wordpress.org/Debugging_in_WordPress) for more information. You need to make sure you have following in your `wp-config.php`:

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

After enabling debugging, WordPress will log all errors in `wp-content/debug.log` file. So you will need to run that cli commands and see what errors you have in the debug.log file.

**Comment by andrewbanchich** [comment]
Okay, I enabled debugging and tailed the logs as I tried running wp-cli commands to enable autosuggest. there was one error that showed up, so I fixed that and tried again and it still doesn't work even though I am not seeing any new errors in the `debug.log` file. Out of curiosity, I tried using wp-cli to activate and deactivate the search feature and I'm getting the same results. I also tried enabling the dashboard sync again and it has no effect.

**Comment by eugene-manuilov** [comment]
What plugins do you use? I can't replicate it on my setup... Can you try to do the same on a new setup without other plugins?

**Comment by andrewbanchich** [comment]
Looks like I'm getting the same issue after disabling all other plugins, except it is outputting a lot of errors now due to theme integrations we had with some of the plugins. I don't see any errors related to ElasticPress though, other than the usual `Error: Feature is not active` and `Error: This feature is already active`.

Is there an ETA on when you'll support Elastisearch 6.0 so I can confirm that it isn't a conflict with that? Would this kind of issue have to do with the Elasticsearch version? I would think that something like enabling / disabling the search feature wouldn't even need to look at Elasticsearch at all since it doesn't require reindexing, would it?

**Comment by andrewbanchich** [comment]
Interesting note: I updated our database which caused ElasticPress to be deactivated, so I activated it and tried `wp elasticpress activate-feature autosuggest` and it output:

```
Warning: Feature is usable but there are warnings: This feature modifies the site’s default user experience by presenting a list of suggestions below detected search fields as text is entered into the field.

You aren't using <a href='https://elasticpress.io'>ElasticPress.io</a> so we can't be sure your host is properly secured. Autosuggest requires a publicly accessible endpoint, which can expose private content and allow data modification if improperly configured.
Warning: This feature requires a re-index. You may want to run the index command next.
Success: Feature activated
```

But then if I run the following immediately after it I get:

```/Applications/MAMP/htdocs/buffalonews.com (elasticsearch *) λ ~/wp-cli.phar elasticpress list-features
Active features:
/Applications/MAMP/htdocs/buffalonews.com (elasticsearch *) λ ~/wp-cli.phar elasticpress deactivate-feature autosuggest
Error: Feature is not active
```

and it goes back to the previous issue. Does it maybe have this issue until I run `wp elasticpress index`, and then it will say it is activated?

**Comment by eugene-manuilov** [comment]
Hi @andrewbanchich,

hm... something weird happens on your end. It's hard to say what exactly... Can you try to create a new site in your environment and activate only ElasticPress to check if it works properly?

**Comment by andrewbanchich** [comment]
Okay, I'll try that out and reopen this if it still doesn't work. Thanks
