### ISSUE TITLE
System requirements should include php-curl

### ISSUE THREAD

**Issue by dustinrue** [10up/ElasticPress#980]
Recently I determined that php-curl should be installed on any system running ElasticPress to avoid an issue with the Requests library that wp-cli uses. You can read the details here - https://github.com/rmccue/Requests/issues/301.

In summary, Ubuntu 16.04 doesn't include php-curl unless you explicitly install it. Without the curl library installed the Requests library used by wp-cli falls back to fsockopen leading to false reports that the Elasticsearch server is down or not available.

**Comment by tlovett1** [comment]
Aren't these the system requirements for WP CLI? If so, I think it would make more sense for WP CLI be the one to dictate that requirement. Thoughts?

**Comment by soulseekah** [comment]
That issue boils down to Requests not supporting the "deflate" encoding algorithm. cURL supports it out of the box, which is contacting an Elasticsearch server works. Doing the same using fsockopen yields LZ77-encoded content which Requests does not know how to handle, as it only knows how to work with the "gzip" encoding.
