### ISSUE TITLE
SQL_CALC_FOUND_ROWS in query returns 0 results

### ISSUE THREAD

**Issue by scs-ben** [10up/ElasticPress#981]
I did some indepth looking at a filter plugin and found that the issue is that this query is returning 0 results:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id) 
LEFT JOIN wp_term_relationships AS tt1
ON (wp_posts.ID = tt1.object_id) 
LEFT JOIN wp_term_relationships AS tt2
ON (wp_posts.ID = tt2.object_id)
WHERE 1=1 
AND ( wp_term_relationships.term_taxonomy_id IN (8930) 
AND wp_posts.ID NOT IN ( 
SELECT object_id 
FROM wp_term_relationships 
WHERE term_taxonomy_id IN (1286) ) 
AND tt1.term_taxonomy_id IN (8930) 
AND tt2.term_taxonomy_id IN (8930) )
AND wp_posts.post_type = 'product'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'wc-gplsquote-req'
OR wp_posts.post_status = 'acf-disabled'
OR wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
ORDER BY wp_posts.menu_order ASC, wp_posts.post_title ASC 
LIMIT 0,999
```

If I turned off Elasticsearch, the filter worked great. I went in to the `class-ep-wp-query-integration.php` file and modified the `filter_posts_requests` to send the request through MySQL and the plugin also works.

```
if (strpos($query->request, 'SQL_CALC_FOUND_ROWS') !== false) {
                return $query->request;
        } else {
                do_action( 'ep_wp_query_search', $new_posts, $ep_query, $query );

                return "SELECT * FROM $wpdb->posts WHERE 1=0";
        }
```

Is there a better way than manually modifying this file?

**Comment by eugene-manuilov** [comment]
Hey @scs-ben,

where did you get that query? ElasticPress uses results returned from Elasticsearch to override WP_Query params related to found posts and total pages.

**Comment by tlovett1** [comment]
Any issue with a MySQL query shouldn't be related to ElasticPress. If I'm mistaken, please reopen.

**Comment by scs-ben** [comment]
The issue is that when it goes into ElasticPress, it returns 0 results but when I override ElasticPress and have it go through MySQL, it returns the correct # of results.
Also, I don't know how to re-open issues

**Comment by nprasath002** [comment]
Hi @scs-ben ,

> I did some indepth looking at a filter plugin 
Can you provide more details on the filter plugin/code used that constructs the query so that we can troubleshoot more?

Thanks

**Comment by nprasath002** [comment]
Closing this out. Feel free to reopen if you still have any issues

**Comment by scs-ben** [comment]
Sorry for missing your request for more information. This is the filter we are using: https://codecanyon.net/item/woocommerce-product-filter/8514038?s_rank=1

**Comment by scs-ben** [comment]
I guess to also clarify based on tlovett1's comment: the issue isn't with MySQL doing the wrong thing (it works when it goes to MySQL), the problem is that when that specific query comes to your plugin, it isn't handled properly.
