### ISSUE TITLE
Limited Host Memory

### ISSUE THREAD

**Issue by penguinpower80** [10up/ElasticPress#983]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question, but also maybe a feature request?

Describe the issue you encountered:
We have about 13,000 posts to sync, of which most (~10,000) are PDF files.  I can get the sync to work fine if I limit the mime types, but once I try a full, the host keeps running out of memory.   I also tried to set ep_index_posts_per_page to only be 1 (tried 25, 50, 100).

**The question, really, is there any way to mark a post as "synced" so it won't try to do it again if the sync fails?**  For now, I'd be willing to just write a log file to check against to at least slowly make progress.  This is a shared hosting (WP-Engine) so I don't get much wiggle room on upping the resources.

Current WordPress version: 4.9.1
Current ElasticPress version:  2.4
Current Elasticsearch version: 5.6.1

Where do you host your Elasticsearch server: Linode, 4gb ram

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):  A variety, but I'm not sure that matters here - not WooCommerce, and this is on a staging system with most turned off.

Steps to reproduce:

1.  Remove the ep_allowed_documents_ingest_mime_types filter
2. Turn on documents
3.  Push Sync
4. Wait

Error Message:

[Thu Dec 14 22:31:05.005821 2017] [:error] [pid 31840] [client 164.119.78.227:19584] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 74609904 bytes) in /nas/content/staging/educationne/wp-content/mu-plugins/wpengine-common/plugin.php on line 2385, referer: https://educationne.staging.wpengine.com/wp-admin/admin.php?page=elasticpress

**Comment by eugene-manuilov** [comment]
Hi @penguinpower80,

> The question, really, is there any way to mark a post as "synced" so it won't try to do it again if the sync fails?

You can make it on your own by using something like this:

```
function check_if_post_is_synced( $kill, $args, $post_id ) {
    $synced = get_post_meta( $post_id, 'synced', true );
    if ( ! empty( $synced ) ) {
        return true;
    }

    return $kill;
}
add_filter( 'ep_post_sync_kill', 'check_if_post_is_synced', 10, 3 );

function add_sync_meta( $args ) {
    if ( ! empty( $args['post_id'] ) ) {
        update_post_meta( $args['post_id'], 'synced', 1 );
    }
}
add_action( 'ep_after_index_post', 'add_sync_meta' );
```

Let me know if it helps.

**Comment by penguinpower80** [comment]
Thanks!  That's the path I started down through digging into the elasticpress code, but was wondering if it would work since ep_after_index__post doesn't (??) appear to be triggered during a bulk sync?

**Comment by penguinpower80** [comment]
So this is what I'm using for now - a bit of a mix, and a total hack I'm sure (be kind with your comments) but this is one of those "I need to get this done NOW" things, and bear in mind this is in a class :

    add_action('ep_add_query_log', array($this, 'track_ep_good_sync'));
    add_filter('ep_post_sync_kill', array($this,'check_ep_need_sync'), 10, 3);

    public function track_ep_good_sync($query) {
            $rawinfo = explode("\n", $query['args']['body']);            
            foreach ($rawinfo as $r) {
                $info = json_decode($r);                
                if ($info && !empty($info->post_id)) {
                    update_post_meta( $info->post_id, 'eplastsync', time() );                    
                }
            }                        
    }
    
    public function check_ep_need_sync($kill, $args, $post_id) {
        $synced = get_post_meta( $post_id, 'eplastsync', true );
        if ( ! empty( $synced ) ) :
            return true; //comment this line to base re-sync on sync age            
            $age = time() - $synced;
            //is it less than 5 minutes old.
            if ( $age < 300 ) return true;
            endif;
        return $kill;
    }

I'm also working on other stuff, so I ran Chrome console and set this to run every 10 seconds so I don't have to watch it and re-click the sync button:

    setInterval(function() {if (jQuery('.start-sync').is(':visible')) {jQuery('.start-sync').trigger('click'); console.log('Visible')} else console.log('Not Visible') }, 10000);

so if it ever stops, it will pick back up again...

**Comment by penguinpower80** [comment]
I'm still trying to work something out to get this to work.  The strategy above started to work until I needed to filter out ~5,000 post id's and then I started running out of memory.  I started to create a manual sync process that loads only a few posts at a time per page load - I don't care if it takes a long time, but just need it to work. 

I've got it adding posts to elasticsearch by this doe (again, this is to get it done rapidly - I'll clean it up later).  It puts things into elasticsearch, but isn't using my custom index name (which the global sync *does* use fine), set via:

        add_filter('ep_index_name', function(){ return 'myindex'; });

The part added via the actual wp sync manager goes into an index "myindex", the posts I add with the code below goes into an index that looks to be from the site url(?) which is the same as if I didn't have the above filter added.  Really I'm just looking to be able to programatically send a post to the index (properly).
         
        if ( class_exists('EP_Sync_Manager')) :
        $e =new EP_Sync_Manager();
        global $wpdb;
        $qry_for_count = "SELECT count(*) as COUNT FROM " . $wpdb->postmeta . " WHERE meta_key = 'eplastsync'";
        $c = $wpdb->get_var($qry_for_count);
        echo $c . " items indexed\n";   
        $q = "SELECT ID, post_title, post_status,post_type,post_mime_type FROM " . $wpdb->posts . " WHERE post_status IN ('publish','inherit') AND post_type IN ('post','page','attachment') AND post_mime_type NOT LIKE \"image/%\" AND ID NOT IN (SELECT post_id FROM " . $wpdb->postmeta . " WHERE meta_key = 'eplastsync')";
        $posts = $wpdb->get_results($q);
        echo "POSSIBLY NEEDING SYNCING " . count($posts)."<br />";                
        $loop = 0;
        foreach ($posts as $post) {
            if ($loop > 0) break;
            echo "Syncing ". $post->post_title . '(' . $post->ID.") - a ". $post->post_type;
            if ($post->post_type == 'attachment' ) echo "and a mime type of " . $post->post_mime_type;
            echo "<br />\n";            
            $e->sync_post($post->ID);
            update_post_meta( $post->ID, 'eplastsync', time() );
            $loop++;
        }
        
        if ( count($posts) > 0 ) :
        ?>
        <script>location.reload();</script>
        <?php
        endif;
        
        endif;
        die('FINISHED');

**Comment by penguinpower80** [comment]
Ok - chalk one thing up to me being an idiot and trying to shortcut the system - I was running things outside of the normal WP structure - I realized it meant that it was running before the filters were registered which changed the index name.

**Comment by eugene-manuilov** [comment]
Hey @penguinpower80,

do you still need a help or you have managed it on your end?

**Comment by penguinpower80** [comment]
Thanks for checking up - no - I don't think the problem is *really* solved, but I was able to work around it by the solution above and also an array of excluded posts that (I think) were just too large to  be indexed (~300-400mb PDF, all text based).  Once it was synced, then things worked ok.
