### ISSUE TITLE
Related widget doesn't show

### ISSUE THREAD

**Issue by pierrebuet** [10up/ElasticPress#985]
After different commits on the setup function of the class EP_Features, the setup is now on the init hook (instead of plugins_loaded before). Since widgets_init is triggered on the init hook with a priority of 1, the widget doesn't show.

**Comment by eugene-manuilov** [comment]
Hey @pierrebuet!

Thanks for submitting it! We have created a pull request for it and will deploy it in the next release.

**Comment by eugene-manuilov** [comment]
Re-created pull request against develop branch (#1004).
