### ISSUE TITLE
Clicking autosuggest list items does not redirect to the matching page on Firefox 57 

### ISSUE THREAD

**Issue by myselfhimself** [10up/ElasticPress#989]
Have you searched for similar issues before submitting this one?
: )

Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
On Firefox 57, after enabling and plugging the 

Current WordPress version:
4.9

Current ElasticPress version:
2.3.2

Current Elasticsearch version:
5.2

Where do you host your Elasticsearch server:
Docker image

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Easy Digital Downloads + Olam theme

Steps to reproduce:

1. Enable the autosuggest feature, giving it a nice elasticsearch endpoint (eg. http://localhost:9200/myIndex/post/_search)
2. Add a search widget onto the front, having an input field having the [right markup](https://www.elasticpress.io/blog/2017/11/elasticpress-2-4-autosuggest/) such as like:
```
<form role="search" method="get" id="searchform2" class="searchform" action="http://nrt.eglises.xyz/">
				<div>
					<label class="screen-reader-text" for="s">Rechercher&nbsp;:</label>
					<input value="" name="se" id="se" type="search">
					<input id="searchsubmit2" value="Rechercher" type="submit">
				</div>
			</form>
```
3. Visit with Firefox 57, possibly with CORS disabled (or not.. depends on your ES's host and CORS settings).
4. Type in at least two characters that would return a non-empty suggestion list (see browser's develop tool's XHR network requests)
5. click on one of the suggestion items showing up, nothing happens when you should have been redirected to the right page. You should see be able to see an error in the console, telling that some element has not 'dataset' property or null or undefined (I do not remember sorry).  This is due to the fact that event.srcElement evaluates to nothing on Firefox 57, from autosuggest.min.js

**Comment by myselfhimself** [comment]
Here is a matching build pull request fixing this: https://github.com/10up/ElasticPress/pull/988

**Comment by eugene-manuilov** [comment]
Thanks, @myselfhimself! I have created another pull request for it that contains the fix in the minified file as well. Going to cancel your Pull Request, but thanks anyway!

**Comment by eugene-manuilov** [comment]
Re-created pull request against develop branch. #1006
