### ISSUE TITLE
Items are indexed, but widget only searches on current site not across the multisite network.

### ISSUE THREAD

**Issue by joecue** [10up/ElasticPress#990]
Have you searched for similar issues before submitting this one? **Yes**

Is this a bug, question or feature request? **bug**

Describe the issue you encountered:  **I have a 68 site multisite network and I was able to get all of the sites indexed in our AWS Elasticsearch Service.  When I try to search I'm getting no results.  Even though I should be finding something.  The Elasticpress debug bar extension shows a 200 http result, and shows the query where it's only looking at the current site the widget is on.**

Current WordPress version: **4.7.7**

Current ElasticPress version: **2.4**

Current Elasticsearch version: **5.3**

Where do you host your Elasticsearch server:  AWS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
**Accordions
Activity Log
Aksimet
amr shortcode any widget
AngularJS for WordPress
Better Rest API Featured Images
Clink WordPress Link Manager
Debug Bar
Debug Bar Elasticpress
Email Subscribers and Newsletters
Enhanced Media Library
Gravity Forms
Gravity Forms - Upload as Attachments
Gravity Forms - Logging Add-on
Gravity Forms - PayPal Standard Add-on
Jetpack
Latest Tweets
A few custom written plugins (mostly CPTs, Taxonomies, Rest API calls)
WP Rest API
WP SVG Icons
Yoast Seo
Zendy Speed: Query Strings**

Steps to reproduce:

1.  Add VPC Endpoint to ElasticPress Settings Screen
2.  Index site
3.  Search for term that should return results.

Screenshots, if needed:

**Comment by tlovett1** [comment]
Can you post your WP_Query arguments?

**Comment by joecue** [comment]
Taylor-

Here is the WP Query arguments from the elasticpress debug bar extension.  Please let me know if you need something else.

array(68) {
  ["s"]=>
  string(4) "test"
  ["error"]=>
  string(0) ""
  ["m"]=>
  string(0) ""
  ["p"]=>
  int(0)
  ["post_parent"]=>
  string(0) ""
  ["subpost"]=>
  string(0) ""
  ["subpost_id"]=>
  string(0) ""
  ["attachment"]=>
  string(0) ""
  ["attachment_id"]=>
  int(0)
  ["name"]=>
  string(0) ""
  ["static"]=>
  string(0) ""
  ["pagename"]=>
  string(0) ""
  ["page_id"]=>
  int(0)
  ["second"]=>
  string(0) ""
  ["minute"]=>
  string(0) ""
  ["hour"]=>
  string(0) ""
  ["day"]=>
  int(0)
  ["monthnum"]=>
  int(0)
  ["year"]=>
  int(0)
  ["w"]=>
  int(0)
  ["category_name"]=>
  string(0) ""
  ["tag"]=>
  string(0) ""
  ["cat"]=>
  string(0) ""
  ["tag_id"]=>
  string(0) ""
  ["author"]=>
  string(0) ""
  ["author_name"]=>
  string(0) ""
  ["feed"]=>
  string(0) ""
  ["tb"]=>
  string(0) ""
  ["paged"]=>
  int(0)
  ["meta_key"]=>
  string(0) ""
  ["meta_value"]=>
  string(0) ""
  ["preview"]=>
  string(0) ""
  ["sentence"]=>
  string(0) ""
  ["title"]=>
  string(0) ""
  ["fields"]=>
  string(0) ""
  ["menu_order"]=>
  string(0) ""
  ["embed"]=>
  string(0) ""
  ["category__in"]=>
  array(0) {
  }
  ["category__not_in"]=>
  array(0) {
  }
  ["category__and"]=>
  array(0) {
  }
  ["post__in"]=>
  array(0) {
  }
  ["post__not_in"]=>
  array(0) {
  }
  ["post_name__in"]=>
  array(0) {
  }
  ["tag__in"]=>
  array(0) {
  }
  ["tag__not_in"]=>
  array(0) {
  }
  ["tag__and"]=>
  array(0) {
  }
  ["tag_slug__in"]=>
  array(0) {
  }
  ["tag_slug__and"]=>
  array(0) {
  }
  ["post_parent__in"]=>
  array(0) {
  }
  ["post_parent__not_in"]=>
  array(0) {
  }
  ["author__in"]=>
  array(0) {
  }
  ["author__not_in"]=>
  array(0) {
  }
  ["cache_results"]=>
  bool(false)
  ["search_fields"]=>
  array(5) {
    [0]=>
    string(10) "post_title"
    [1]=>
    string(12) "post_content"
    [2]=>
    string(12) "post_excerpt"
    [3]=>
    string(11) "author_name"
    ["taxonomies"]=>
    array(2) {
      [0]=>
      string(8) "post_tag"
      [1]=>
      string(8) "category"
    }
  }
  ["ignore_sticky_posts"]=>
  bool(false)
  ["suppress_filters"]=>
  bool(false)
  ["update_post_term_cache"]=>
  bool(true)
  ["lazy_load_term_meta"]=>
  bool(true)
  ["update_post_meta_cache"]=>
  bool(true)
  ["post_type"]=>
  string(3) "any"
  ["posts_per_page"]=>
  int(10)
  ["nopaging"]=>
  bool(false)
  ["comments_per_page"]=>
  string(2) "50"
  ["no_found_rows"]=>
  bool(false)
  ["search_terms_count"]=>
  int(1)
  ["search_terms"]=>
  array(1) {
    [0]=>
    string(4) "test"
  }
  ["search_orderby_title"]=>
  array(1) {
    [0]=>
    string(170) "lc1159_71_posts.post_title LIKE '{cf8cc2de6bb11c53b8ed8430b179a86c397bf8c0d26e834d4656fd440b93197f}test{cf8cc2de6bb11c53b8ed8430b179a86c397bf8c0d26e834d4656fd440b93197f}'"
  }
  ["order"]=>
  string(4) "DESC"
}

Somone else suggested I use a filter to rename the index and keep it the same name for the whole network?

// For standard installation option
add_filter( 'option_ep_index_meta', 'your_function_to_return_index_name', 10, 2 ); 

// For multisite installtion option
add_filter( 'site_option_ep_index_meta', 'your_function_to_return_index_name', 10, 3 ); 

I was going to give the a try this morning.

I also saw on the github page for the plugin something about modifying the query argument to include 'sites' => 'all'; but I'm not sure how to modify the search page to do this.

Thanks for your help!

**Comment by eugene-manuilov** [comment]
Looks like it happens because post_type is "any". We discuss it in the #986 ticket.

**Comment by joecue** [comment]
So do I need to modify plugin code or do I need to add a query to my search.php page in my theme?  I guess I'm confused as to how to resolve this so I can use this with Elastic Search for my WordPress site. 

Do I need to be using the Open Source version running on a server vs the AWS Search Service?

**Comment by eugene-manuilov** [comment]
@joecue, can you try to pass all available post types instead of `any`? Try something like this:

```
$query = new \WP_Query( array(
    ...
    'post_type' => ep_get_indexable_post_types(),
    ...
) );
```

Please, let me know if it helps to resolve your issue.

**Comment by joecue** [comment]
That would go in the search.php page?

**Comment by eugene-manuilov** [comment]
Actually, can you download [this version](https://github.com/10up/ElasticPress/archive/fix/any-post-type.zip) of the plugin and try it on your end? That version includes that fix and probably should help you. Let me know.

**Comment by joecue** [comment]
I tried the version you linked to above and it did not change.  It still seems like it's searching only the index of the site the search is started on.

I deleted the index and ran the WP CLI call to rebuild the index network-wide.  Should I try adding the post type parameter to the call?

Here are the query arguments from this latest test.

array(68) {
  ["s"]=>
  string(7) "classes"
  ["error"]=>
  string(0) ""
  ["m"]=>
  string(0) ""
  ["p"]=>
  int(0)
  ["post_parent"]=>
  string(0) ""
  ["subpost"]=>
  string(0) ""
  ["subpost_id"]=>
  string(0) ""
  ["attachment"]=>
  string(0) ""
  ["attachment_id"]=>
  int(0)
  ["name"]=>
  string(0) ""
  ["static"]=>
  string(0) ""
  ["pagename"]=>
  string(0) ""
  ["page_id"]=>
  int(0)
  ["second"]=>
  string(0) ""
  ["minute"]=>
  string(0) ""
  ["hour"]=>
  string(0) ""
  ["day"]=>
  int(0)
  ["monthnum"]=>
  int(0)
  ["year"]=>
  int(0)
  ["w"]=>
  int(0)
  ["category_name"]=>
  string(0) ""
  ["tag"]=>
  string(0) ""
  ["cat"]=>
  string(0) ""
  ["tag_id"]=>
  string(0) ""
  ["author"]=>
  string(0) ""
  ["author_name"]=>
  string(0) ""
  ["feed"]=>
  string(0) ""
  ["tb"]=>
  string(0) ""
  ["paged"]=>
  int(0)
  ["meta_key"]=>
  string(0) ""
  ["meta_value"]=>
  string(0) ""
  ["preview"]=>
  string(0) ""
  ["sentence"]=>
  string(0) ""
  ["title"]=>
  string(0) ""
  ["fields"]=>
  string(0) ""
  ["menu_order"]=>
  string(0) ""
  ["embed"]=>
  string(0) ""
  ["category__in"]=>
  array(0) {
  }
  ["category__not_in"]=>
  array(0) {
  }
  ["category__and"]=>
  array(0) {
  }
  ["post__in"]=>
  array(0) {
  }
  ["post__not_in"]=>
  array(0) {
  }
  ["post_name__in"]=>
  array(0) {
  }
  ["tag__in"]=>
  array(0) {
  }
  ["tag__not_in"]=>
  array(0) {
  }
  ["tag__and"]=>
  array(0) {
  }
  ["tag_slug__in"]=>
  array(0) {
  }
  ["tag_slug__and"]=>
  array(0) {
  }
  ["post_parent__in"]=>
  array(0) {
  }
  ["post_parent__not_in"]=>
  array(0) {
  }
  ["author__in"]=>
  array(0) {
  }
  ["author__not_in"]=>
  array(0) {
  }
  ["cache_results"]=>
  bool(false)
  ["search_fields"]=>
  array(5) {
    [0]=>
    string(10) "post_title"
    [1]=>
    string(12) "post_content"
    [2]=>
    string(12) "post_excerpt"
    [3]=>
    string(11) "author_name"
    ["taxonomies"]=>
    array(2) {
      [0]=>
      string(8) "post_tag"
      [1]=>
      string(8) "category"
    }
  }
  ["ignore_sticky_posts"]=>
  bool(false)
  ["suppress_filters"]=>
  bool(false)
  ["update_post_term_cache"]=>
  bool(true)
  ["lazy_load_term_meta"]=>
  bool(true)
  ["update_post_meta_cache"]=>
  bool(true)
  ["post_type"]=>
  string(3) "any"
  ["posts_per_page"]=>
  int(10)
  ["nopaging"]=>
  bool(false)
  ["comments_per_page"]=>
  string(2) "50"
  ["no_found_rows"]=>
  bool(false)
  ["search_terms_count"]=>
  int(1)
  ["search_terms"]=>
  array(1) {
    [0]=>
    string(7) "classes"
  }
  ["search_orderby_title"]=>
  array(1) {
    [0]=>
    string(170) "lc1323_posts.post_title LIKE '{b008ff4738f63c91681ef87d48e9d6b97c6b4d17111619cb567d3adc3798f0d8}classes{b008ff4738f63c91681ef87d48e9d6b97c6b4d17111619cb567d3adc3798f0d8}'"
  }
  ["order"]=>
  string(4) "DESC"
}

**Comment by joecue** [comment]
I just attempted a reindex using the WP CLI command adding two post types to the post-type parameter and I'm still not seeing results.  When I run WP CLI with the stats parameter I'm seeing individual indexes for each subsite from the multisite.

**Comment by eugene-manuilov** [comment]
@joecue, there was another bug in that branch related to `any` post type. I have updated my pull request. Could you please re-download plugin from my branch (link is posted above) and try again on your end?

**Comment by joecue** [comment]
@eugene-manuilov,
I deleted the old plugin, uploaded the new download from the link above.  Added my elasticsearch service endpoint, deleted the index, re-indexed using WP CLI, and no change to my search results.

**Comment by lcccweb** [comment]
@eugene-manuilov Piotr Kierzniewski from the Advanced WordPress Group on Facebook suggested adding this gist to my functions.php, https://gist.github.com/kierzniak/23f9c66060cae7f6f3887e62a8d14fb0, and it seems to be working.  I may need to tweak the index slightly, but I can at least get search results across my network now.

**Comment by joecue** [comment]
@eugene-manuilov Piotr Kierzniewski on the Advanced WordPress Facebook group suggested adding this gist, https://gist.github.com/kierzniak/23f9c66060cae7f6f3887e62a8d14fb0, to my functions.php file.  I am now able to get results back from across the network using Elasticpress.  I may need to tweak my index slightly to improve the results, but it's working.

**Comment by tlovett1** [comment]
By default, ElasticPress only searches the current site/blog. You need to use `sites => all` in your `WP_Query`.

**Comment by madrid1979** [comment]
This is maddening. Where do i add `sites => all` in my `WP_Query`? Sorry, I've been looking everywhere for this, and I'm coming up with nothing. Would be ideal if you just added a checkbox or something that enabled this.
