### ISSUE TITLE
Elasticsearch 6.1 - "Content-Type header [application/x-www-form-urlencoded] is not supported"

### ISSUE THREAD

**Issue by azcoppen** [10up/ElasticPress#995]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Feature request

Describe the issue you encountered:
Elasticsearch 6.1 requires application/json as the content type in requests: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

Type: put_mapping
Host: http://elastic.domain.com
Time Taken: 15 ms
URL: http://elastic.domain.com/indexname-1
Method: PUT
Query Body: 
Query Response Code: HTTP 406
Query Result: 
{
    "error": "Content-Type header [application/x-www-form-urlencoded] is not supported",
    "status": 406
}

Current WordPress version:
4.5

Current ElasticPress version:
2.4 

Current Elasticsearch version:
6.1

Where do you host your Elasticsearch server:
Custom Linux box on Azure

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. Install ES 6.1 + plugins
2. Attempt sync
3. Look at debug.

Screenshots, if needed:

**Comment by eugene-manuilov** [comment]
Hey @azcoppen,

thanks for posting it! I have created a pull request to update content type.

**Comment by eugene-manuilov** [comment]
Re-created pull request against develop branch. #1005

**Comment by archon810** [comment]
Is there a roadmap for the next release that will incorporate this @eugene-manuilov?

**Comment by eugene-manuilov** [comment]
@archon810, we are planning to release a new version in the first half of 2018, but there is no specific date yet.

**Comment by azcoppen** [comment]
Seconding request by @archon810 . Would love to use this across our multi-site networks for Wordpress installs but it's currently breaking them.
